import type { ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Written-test formats for planet Sharpholm (C#): trace tables (dry-run the code, fill the values)
// and debugging tasks (tap the buggy line, then fix it). The validator runs every `verify` and proves
// each fix passes the tests while the buggy code and the near misses fail (.NET 10 on Compiler
// Explorer). Debug files are `using` lines then types: the engine puts the tests before the types.

const code = (...lines: string[]) => lines.join("\n");

const after = (n: number) => L(`after line ${n}`, `tras la línea ${n}`, `${n}行目の後`);

// ─── Junior ─────────────────────────────────────────────────────────────────

/** Junior trace: + is evaluated left to right, so a string on the left turns ints into text. */
export const concatTrace: ExamQuestion = {
  kind: "trace",
  topic: "types-strings",
  difficulty: 1,
  prompt: L("Trace table: numbers and strings", "Tabla de traza: números y strings", "トレース：数値と文字列"),
  brief: L(
    "Each row is the end of one pass of the for loop.",
    "Cada fila es el final de una vuelta del bucle for.",
    "各行は for ループ1周の終わり。",
  ),
  code: code(
    'string s = "";',
    "int sum = 0;",
    "for (int i = 1; i <= 3; i++)",
    "{",
    "    sum += i * 2;",
    "    s = s + i + 1;",
    "}",
  ),
  columns: ["i", "sum", "s"],
  rows: [
    { label: "i = 1", cells: ["1", "2", "11"], given: [0] },
    { label: "i = 2", cells: ["2", "6", "1121"], given: [0] },
    { label: "i = 3", cells: ["3", "12", "112131"], given: [0] },
  ],
  verify: code(
    'string s = "";',
    "int sum = 0;",
    "for (int i = 1; i <= 3; i++)",
    "{",
    "    sum += i * 2;",
    "    s = s + i + 1;",
    '    Console.WriteLine($"{i} | {sum} | {s}");',
    "}",
  ),
  explain: L(
    "s + i is a string, so + 1 appends \"1\" instead of adding: s gets i then 1 each pass. sum adds 2, 4, 6 as ints.",
    "s + i es un string, así que + 1 añade \"1\" en vez de sumar: s recibe i y luego 1 en cada vuelta. sum suma 2, 4, 6 como int.",
    "s + i は文字列なので + 1 は加算でなく \"1\" の連結。毎周 i と 1 が付く。sum は int で 2, 4, 6 を足す。",
  ),
};

/** Junior trace: assigning a struct copies it, assigning a class shares the object. */
export const structClassTrace: ExamQuestion = {
  kind: "trace",
  topic: "value-reference",
  difficulty: 1,
  prompt: L("Trace table: struct vs class", "Tabla de traza: struct vs class", "トレース：struct と class"),
  code: code(
    "var p = new Point { X = 1 };",
    "var box = new Box { X = 1 };",
    "var p2 = p;",
    "var box2 = box;",
    "p2.X = 7;",
    "box2.X = 9;",
    "",
    "struct Point { public int X; }",
    "class Box { public int X; }",
  ),
  columns: ["p.X", "p2.X", "box.X", "box2.X"],
  rows: [
    { label: after(4), cells: ["1", "1", "1", "1"], given: [0, 1] },
    { label: after(5), cells: ["1", "7", "1", "1"] },
    { label: after(6), cells: ["1", "7", "9", "9"] },
  ],
  verify: code(
    "var p = new Point { X = 1 };",
    "var box = new Box { X = 1 };",
    "var p2 = p;",
    "var box2 = box;",
    'Console.WriteLine($"{p.X} | {p2.X} | {box.X} | {box2.X}");',
    "p2.X = 7;",
    'Console.WriteLine($"{p.X} | {p2.X} | {box.X} | {box2.X}");',
    "box2.X = 9;",
    'Console.WriteLine($"{p.X} | {p2.X} | {box.X} | {box2.X}");',
    "",
    "struct Point { public int X; }",
    "class Box { public int X; }",
  ),
  explain: L(
    "p2 = p copies the struct, so p stays 1. box2 = box copies only the reference: both names point to one Box, so both read 9.",
    "p2 = p copia el struct, así que p sigue en 1. box2 = box copia solo la referencia: ambos nombres apuntan a un Box y leen 9.",
    "p2 = p は struct のコピーなので p は 1 のまま。box2 = box は参照のコピーで同じ Box を指し、両方 9。",
  ),
};

// ─── Mid ────────────────────────────────────────────────────────────────────

/** Mid trace: a LINQ query is re-run against the live list each time it is enumerated. */
export const deferredTrace: ExamQuestion = {
  kind: "trace",
  topic: "linq",
  difficulty: 2,
  prompt: L("Trace table: a deferred query", "Tabla de traza: una consulta diferida", "トレース：遅延クエリ"),
  code: code(
    "var nums = new List<int> { 1, 2, 3 };",
    "var big = nums.Where(n => n > 1);",
    "nums.Add(5);",
    "nums[0] = 7;",
  ),
  columns: ["nums.Count", "big.Count()", "big.Sum()"],
  rows: [
    { label: after(2), cells: ["3", "2", "5"], given: [0] },
    { label: after(3), cells: ["4", "3", "10"] },
    { label: after(4), cells: ["4", "4", "17"] },
  ],
  verify: code(
    "var nums = new List<int> { 1, 2, 3 };",
    "var big = nums.Where(n => n > 1);",
    'Console.WriteLine($"{nums.Count} | {big.Count()} | {big.Sum()}");',
    "nums.Add(5);",
    'Console.WriteLine($"{nums.Count} | {big.Count()} | {big.Sum()}");',
    "nums[0] = 7;",
    'Console.WriteLine($"{nums.Count} | {big.Count()} | {big.Sum()}");',
  ),
  explain: L(
    "Where stores the recipe, not the results: each Count() or Sum() filters the list as it is now, so 5 and the new 7 show up.",
    "Where guarda la receta, no el resultado: cada Count() o Sum() filtra la lista tal como está, así que aparecen el 5 y el nuevo 7.",
    "Where は結果でなく手順を保持する。Count() や Sum() のたびに今のリストを絞り込むので、5 と新しい 7 も入る。",
  ),
};

/** Mid trace: a for loop shares one variable across closures; foreach gets a fresh one per pass. */
export const loopClosureTrace: ExamQuestion = {
  kind: "trace",
  topic: "delegates-closures",
  difficulty: 2,
  prompt: L("Trace table: closures in loops", "Tabla de traza: closures en bucles", "トレース：ループ内のクロージャ"),
  brief: L(
    "Each row is what fs[k]() and gs[k]() return after both loops have finished.",
    "Cada fila es lo que devuelven fs[k]() y gs[k]() cuando ya terminaron ambos bucles.",
    "各行は、両方のループが終わった後に fs[k]() と gs[k]() が返す値。",
  ),
  code: code(
    "var fs = new List<Func<int>>();",
    "for (int i = 0; i < 3; i++) fs.Add(() => i * 10);",
    "var gs = new List<Func<int>>();",
    "foreach (var j in new[] { 0, 1, 2 }) gs.Add(() => j * 10);",
  ),
  columns: ["k", "fs[k]()", "gs[k]()"],
  rows: [
    { label: "k = 0", cells: ["0", "30", "0"], given: [0] },
    { label: "k = 1", cells: ["1", "30", "10"], given: [0] },
    { label: "k = 2", cells: ["2", "30", "20"], given: [0] },
  ],
  verify: code(
    "var fs = new List<Func<int>>();",
    "for (int i = 0; i < 3; i++) fs.Add(() => i * 10);",
    "var gs = new List<Func<int>>();",
    "foreach (var j in new[] { 0, 1, 2 }) gs.Add(() => j * 10);",
    'for (int k = 0; k < 3; k++) Console.WriteLine($"{k} | {fs[k]()} | {gs[k]()}");',
  ),
  explain: L(
    "All three for lambdas capture the same i, which ends at 3, so each returns 30. foreach declares a new j per pass: 0, 10, 20.",
    "Las tres lambdas del for capturan el mismo i, que termina en 3: todas devuelven 30. foreach declara un j nuevo por vuelta: 0, 10, 20.",
    "for の3つのラムダは同じ i を捕まえ、i は最後 3 なので全部 30。foreach は毎周新しい j：0、10、20。",
  ),
};

/** Mid debug: strings are immutable, so a call whose result is ignored changes nothing. */
export const slugDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "types-strings",
  difficulty: 2,
  prompt: L("Debug: make a slug", "Depura: crear un slug", "デバッグ：スラッグを作る"),
  brief: L(
    "Slugger.Slug(title) should trim the title, lowercase it and replace spaces with '-'. But Slug(\"  Hello World \") returns \"Hello-World\" instead of \"hello-world\".",
    "Slugger.Slug(title) debería recortar el título, pasarlo a minúsculas y cambiar los espacios por '-'. Pero Slug(\"  Hello World \") devuelve \"Hello-World\" en vez de \"hello-world\".",
    "Slugger.Slug(title) はタイトルの前後空白を除き、小文字にして空白を '-' にするはず。でも Slug(\"  Hello World \") が \"hello-world\" でなく \"Hello-World\" になる。",
  ),
  code: code(
    "using System;",
    "",
    "public static class Slugger",
    "{",
    '    // "  Hello World " -> "hello-world"',
    "    public static string Slug(string title)",
    "    {",
    "        string t = title.Trim();",
    "        t.ToLowerInvariant();",
    "        return t.Replace(' ', '-');",
    "    }",
    "}",
  ),
  bugLine: 9,
  solution: code(
    "using System;",
    "",
    "public static class Slugger",
    "{",
    '    // "  Hello World " -> "hello-world"',
    "    public static string Slug(string title)",
    "    {",
    "        string t = title.Trim();",
    "        t = t.ToLowerInvariant();",
    "        return t.Replace(' ', '-');",
    "    }",
    "}",
  ),
  nearMiss: [
    // Another call whose result is thrown away.
    code(
      "using System;",
      "",
      "public static class Slugger",
      "{",
      "    public static string Slug(string title)",
      "    {",
      "        string t = title.Trim();",
      "        t.ToLower();",
      "        return t.Replace(' ', '-');",
      "    }",
      "}",
    ),
    // Lowercases the untrimmed title, losing the Trim.
    code(
      "using System;",
      "",
      "public static class Slugger",
      "{",
      "    public static string Slug(string title)",
      "    {",
      "        string t = title.Trim();",
      "        t = title.ToLowerInvariant();",
      "        return t.Replace(' ', '-');",
      "    }",
      "}",
    ),
  ],
  tests: [
    { run: 'Console.WriteLine("[" + Slugger.Slug("  Hello World ") + "]");', expect: "[hello-world]" },
    { run: 'Console.WriteLine("[" + Slugger.Slug("Big Cat") + "]");', expect: "[big-cat]" },
    { run: 'Console.WriteLine("[" + Slugger.Slug("abc") + "]");', expect: "[abc]", hidden: true },
    { run: 'Console.WriteLine("[" + Slugger.Slug("  A  B ") + "]");', expect: "[a--b]", hidden: true },
    { run: 'Console.WriteLine("[" + Slugger.Slug("NEW") + "]");', expect: "[new]", hidden: true },
  ],
  explain: L(
    "Strings are immutable: ToLowerInvariant returns a new string and t was left as it was. Assigning the result back keeps it.",
    "Los strings son inmutables: ToLowerInvariant devuelve un string nuevo y t quedaba igual. Asignar el resultado lo conserva.",
    "string は不変。ToLowerInvariant は新しい文字列を返すだけで t は元のまま。結果を代入し直せば反映される。",
  ),
};

/** Mid debug: a deferred query is enumerated after the data it filters has changed. */
export const shipPendingDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "linq",
  difficulty: 2,
  prompt: L("Debug: ship the pending orders", "Depura: enviar pedidos pendientes", "デバッグ：未発送の注文を発送"),
  brief: L(
    "Shop.ShipPending(orders) should return the ids of the orders not shipped yet, then mark every order as shipped. But with orders a (pending), b (shipped), c (pending) it returns nothing instead of a,c.",
    "Shop.ShipPending(orders) debería devolver los ids de los pedidos aún no enviados y luego marcar todos como enviados. Pero con a (pendiente), b (enviado), c (pendiente) no devuelve nada en vez de a,c.",
    "Shop.ShipPending(orders) は未発送の注文の id を返し、その後全注文を発送済みにするはず。でも a（未）、b（済）、c（未）で a,c でなく何も返らない。",
  ),
  code: code(
    "using System;",
    "using System.Collections.Generic;",
    "using System.Linq;",
    "",
    "public class Order",
    "{",
    "    public Order(string id, bool shipped) { Id = id; Shipped = shipped; }",
    "    public string Id { get; }",
    "    public bool Shipped { get; set; }",
    "}",
    "",
    "public static class Shop",
    "{",
    "    // Ids of the orders not shipped yet; then every order is marked as shipped.",
    "    public static IEnumerable<string> ShipPending(List<Order> orders)",
    "    {",
    "        var pending = orders.Where(o => !o.Shipped).Select(o => o.Id);",
    "        foreach (var o in orders) o.Shipped = true;",
    "        return pending;",
    "    }",
    "}",
  ),
  bugLine: 17,
  solution: code(
    "using System;",
    "using System.Collections.Generic;",
    "using System.Linq;",
    "",
    "public class Order",
    "{",
    "    public Order(string id, bool shipped) { Id = id; Shipped = shipped; }",
    "    public string Id { get; }",
    "    public bool Shipped { get; set; }",
    "}",
    "",
    "public static class Shop",
    "{",
    "    // Ids of the orders not shipped yet; then every order is marked as shipped.",
    "    public static IEnumerable<string> ShipPending(List<Order> orders)",
    "    {",
    "        var pending = orders.Where(o => !o.Shipped).Select(o => o.Id).ToList();",
    "        foreach (var o in orders) o.Shipped = true;",
    "        return pending;",
    "    }",
    "}",
  ),
  nearMiss: [
    // AsEnumerable is still deferred.
    code(
      "using System;",
      "using System.Collections.Generic;",
      "using System.Linq;",
      "",
      "public class Order",
      "{",
      "    public Order(string id, bool shipped) { Id = id; Shipped = shipped; }",
      "    public string Id { get; }",
      "    public bool Shipped { get; set; }",
      "}",
      "",
      "public static class Shop",
      "{",
      "    public static IEnumerable<string> ShipPending(List<Order> orders)",
      "    {",
      "        var pending = orders.Where(o => !o.Shipped).Select(o => o.Id).AsEnumerable();",
      "        foreach (var o in orders) o.Shipped = true;",
      "        return pending;",
      "    }",
      "}",
    ),
    // Materializes the ids but forgets to ship.
    code(
      "using System;",
      "using System.Collections.Generic;",
      "using System.Linq;",
      "",
      "public class Order",
      "{",
      "    public Order(string id, bool shipped) { Id = id; Shipped = shipped; }",
      "    public string Id { get; }",
      "    public bool Shipped { get; set; }",
      "}",
      "",
      "public static class Shop",
      "{",
      "    public static IEnumerable<string> ShipPending(List<Order> orders)",
      "    {",
      "        return orders.Where(o => !o.Shipped).Select(o => o.Id).ToList();",
      "    }",
      "}",
    ),
  ],
  tests: [
    { run: '{ var os = new List<Order> { new("a", false), new("b", true), new("c", false) }; Console.WriteLine("[" + string.Join(",", Shop.ShipPending(os)) + "]"); }', expect: "[a,c]" },
    { run: '{ var os = new List<Order> { new("x", false) }; Shop.ShipPending(os); Console.WriteLine(os[0].Shipped); }', expect: "True" },
    { run: '{ var os = new List<Order> { new("p", false), new("q", false) }; Console.WriteLine("[" + string.Join(",", Shop.ShipPending(os)) + "]"); }', expect: "[p,q]", hidden: true },
    { run: '{ var os = new List<Order> { new("d", true) }; Console.WriteLine("[" + string.Join(",", Shop.ShipPending(os)) + "]"); }', expect: "[]", hidden: true },
    { run: '{ var os = new List<Order> { new("e", false), new("f", true) }; Shop.ShipPending(os); Console.WriteLine(os.All(o => o.Shipped)); }', expect: "True", hidden: true },
  ],
  explain: L(
    "The query ran only when the caller enumerated it, after the loop had shipped everything. ToList() runs it before the loop.",
    "La consulta se ejecutaba al recorrerla quien llama, cuando el bucle ya había enviado todo. ToList() la ejecuta antes del bucle.",
    "クエリは呼び出し側が列挙した時、つまり全件発送後に実行されていた。ToList() でループ前に実行する。",
  ),
};

// ─── Senior ─────────────────────────────────────────────────────────────────

/** Senior trace: assigning a struct to an interface boxes a copy; copying the interface shares the box. */
export const boxingTrace: ExamQuestion = {
  kind: "trace",
  topic: "value-reference",
  difficulty: 3,
  prompt: L("Trace table: boxing a struct", "Tabla de traza: boxing de un struct", "トレース：struct のボックス化"),
  code: code(
    "var c = new Counter();",
    "IBump boxed = c;",
    "boxed.Bump();",
    "c.Bump();",
    "c.Bump();",
    "IBump alias = boxed;",
    "alias.Bump();",
    "",
    "interface IBump { int N { get; } void Bump(); }",
    "struct Counter : IBump",
    "{",
    "    public int N { get; private set; }",
    "    public void Bump() => N++;",
    "}",
  ),
  columns: ["c.N", "boxed.N"],
  rows: [
    { label: after(3), cells: ["0", "1"], given: [0] },
    { label: after(5), cells: ["2", "1"] },
    { label: after(7), cells: ["2", "2"] },
  ],
  verify: code(
    "var c = new Counter();",
    "IBump boxed = c;",
    "boxed.Bump();",
    'Console.WriteLine($"{c.N} | {boxed.N}");',
    "c.Bump();",
    "c.Bump();",
    'Console.WriteLine($"{c.N} | {boxed.N}");',
    "IBump alias = boxed;",
    "alias.Bump();",
    'Console.WriteLine($"{c.N} | {boxed.N}");',
    "",
    "interface IBump { int N { get; } void Bump(); }",
    "struct Counter : IBump",
    "{",
    "    public int N { get; private set; }",
    "    public void Bump() => N++;",
    "}",
  ),
  explain: L(
    "IBump boxed = c boxes a copy of c, so the two count apart. alias = boxed copies the reference to that box: alias bumps boxed.",
    "IBump boxed = c mete en una caja una copia de c, así que cuentan por separado. alias = boxed copia la referencia a esa caja.",
    "IBump boxed = c は c のコピーをボックス化するので別々に数える。alias = boxed は同じ箱への参照のコピー。",
  ),
};

/** Senior debug: a lambda is a new delegate, so `-=` with a fresh lambda removes nothing. */
export const detachDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "delegates-closures",
  difficulty: 3,
  prompt: L("Debug: stop logging the alarm", "Depura: dejar de registrar la alarma", "デバッグ：アラームの記録を止める"),
  brief: L(
    "Logger.Attach(alarm) should log each ring as \"tag: msg\" and Detach(alarm) should stop it. But after Attach, Ring(\"one\"), Detach, Ring(\"two\"), the log holds \"L: one,L: two\" instead of \"L: one\".",
    "Logger.Attach(alarm) debería registrar cada timbre como \"tag: msg\" y Detach(alarm) dejar de hacerlo. Pero tras Attach, Ring(\"one\"), Detach, Ring(\"two\"), el log tiene \"L: one,L: two\" en vez de \"L: one\".",
    "Logger.Attach(alarm) は鳴るたびに \"tag: msg\" を記録し、Detach(alarm) で止めるはず。でも Attach、Ring(\"one\")、Detach、Ring(\"two\") の後、記録が \"L: one\" でなく \"L: one,L: two\"。",
  ),
  code: code(
    "using System;",
    "using System.Collections.Generic;",
    "",
    "public class Alarm",
    "{",
    "    public event Action<string>? Rang;",
    "    public void Ring(string msg) => Rang?.Invoke(msg);",
    "}",
    "",
    "public class Logger",
    "{",
    "    private readonly List<string> lines = new();",
    "    private readonly string tag;",
    "    public Logger(string tag) => this.tag = tag;",
    "    public IReadOnlyList<string> Lines => lines;",
    "",
    "    // Each ring is logged as \"tag: msg\".",
    "    public void Attach(Alarm alarm) => alarm.Rang += msg => lines.Add($\"{tag}: {msg}\");",
    "",
    "    // Rings after this are not logged any more.",
    "    public void Detach(Alarm alarm) => alarm.Rang -= msg => lines.Add($\"{tag}: {msg}\");",
    "}",
  ),
  bugLine: 21,
  solution: code(
    "using System;",
    "using System.Collections.Generic;",
    "",
    "public class Alarm",
    "{",
    "    public event Action<string>? Rang;",
    "    public void Ring(string msg) => Rang?.Invoke(msg);",
    "}",
    "",
    "public class Logger",
    "{",
    "    private readonly List<string> lines = new();",
    "    private readonly string tag;",
    "    public Logger(string tag) => this.tag = tag;",
    "    public IReadOnlyList<string> Lines => lines;",
    "    private void OnRang(string msg) => lines.Add($\"{tag}: {msg}\");",
    "",
    "    // Each ring is logged as \"tag: msg\".",
    "    public void Attach(Alarm alarm) => alarm.Rang += OnRang;",
    "",
    "    // Rings after this are not logged any more.",
    "    public void Detach(Alarm alarm) => alarm.Rang -= OnRang;",
    "}",
  ),
  nearMiss: [
    // Clears the log instead of unsubscribing: later rings still arrive.
    code(
      "using System;",
      "using System.Collections.Generic;",
      "",
      "public class Alarm",
      "{",
      "    public event Action<string>? Rang;",
      "    public void Ring(string msg) => Rang?.Invoke(msg);",
      "}",
      "",
      "public class Logger",
      "{",
      "    private readonly List<string> lines = new();",
      "    private readonly string tag;",
      "    public Logger(string tag) => this.tag = tag;",
      "    public IReadOnlyList<string> Lines => lines;",
      "",
      "    public void Attach(Alarm alarm) => alarm.Rang += msg => lines.Add($\"{tag}: {msg}\");",
      "",
      "    public void Detach(Alarm alarm) { alarm.Rang -= msg => lines.Add($\"{tag}: {msg}\"); lines.Clear(); }",
      "}",
    ),
  ],
  tests: [
    { run: '{ var a = new Alarm(); var log = new Logger("L"); log.Attach(a); a.Ring("one"); log.Detach(a); a.Ring("two"); Console.WriteLine(string.Join(",", log.Lines)); }', expect: "L: one" },
    { run: '{ var a = new Alarm(); var log = new Logger("L"); log.Attach(a); a.Ring("x"); a.Ring("y"); Console.WriteLine(string.Join(",", log.Lines)); }', expect: "L: x,L: y" },
    { run: '{ var a = new Alarm(); var log = new Logger("Q"); log.Attach(a); log.Detach(a); a.Ring("z"); Console.WriteLine(log.Lines.Count); }', expect: "0", hidden: true },
    { run: '{ var a = new Alarm(); var p = new Logger("P"); var q = new Logger("Q"); p.Attach(a); q.Attach(a); p.Detach(a); a.Ring("m"); Console.WriteLine(p.Lines.Count + " " + string.Join(",", q.Lines)); }', expect: "0 Q: m", hidden: true },
    { run: '{ var a = new Alarm(); var log = new Logger("R"); log.Attach(a); log.Detach(a); log.Attach(a); a.Ring("k"); Console.WriteLine(string.Join(",", log.Lines)); }', expect: "R: k", hidden: true },
  ],
  explain: L(
    "Each lambda is a new delegate to a different method, so -= found no match. A named method gives += and -= equal delegates.",
    "Cada lambda es un delegado nuevo a otro método, así que -= no hallaba coincidencia. Un método con nombre da delegados iguales.",
    "ラムダは毎回別メソッドの新しいデリゲートなので -= が一致しない。名前付きメソッドなら += と -= が等しくなる。",
  ),
};

/** Senior paper debug: calling a mutating method on a readonly struct field works on a copy. */
export const readonlyStructDebug: ExamQuestion = {
  kind: "debug",
  mode: "paper",
  topic: "value-reference",
  difficulty: 3,
  prompt: L("Debug: the scoreboard", "Depura: el marcador", "デバッグ：スコアボード"),
  brief: L(
    "Scoreboard.Hit(pts) should add a hit worth pts and remember the best hit. But after Hit(3) and Hit(5), Summary() returns \"0 hits, 0 pts, best 5\" instead of \"2 hits, 8 pts, best 5\".",
    "Scoreboard.Hit(pts) debería sumar un golpe de pts puntos y recordar el mejor. Pero tras Hit(3) y Hit(5), Summary() devuelve \"0 hits, 0 pts, best 5\" en vez de \"2 hits, 8 pts, best 5\".",
    "Scoreboard.Hit(pts) は pts 点の命中を加え、最高点を覚えるはず。でも Hit(3) と Hit(5) の後、Summary() が \"2 hits, 8 pts, best 5\" でなく \"0 hits, 0 pts, best 5\" になる。",
  ),
  code: code(
    "using System;",
    "",
    "public struct Tally",
    "{",
    "    public int Points;",
    "    public int Hits;",
    "    public void Add(int pts) { Points += pts; Hits++; }",
    "}",
    "",
    "public class Scoreboard",
    "{",
    "    private readonly Tally tally;",
    "    private int best;",
    "",
    "    // Records one hit worth pts points and remembers the best single hit.",
    "    public void Hit(int pts)",
    "    {",
    "        tally.Add(pts);",
    "        best = Math.Max(best, pts);",
    "    }",
    "",
    "    public string Summary() => $\"{tally.Hits} hits, {tally.Points} pts, best {best}\";",
    "}",
  ),
  bugLine: 12,
  solution: code(
    "using System;",
    "",
    "public struct Tally",
    "{",
    "    public int Points;",
    "    public int Hits;",
    "    public void Add(int pts) { Points += pts; Hits++; }",
    "}",
    "",
    "public class Scoreboard",
    "{",
    "    private Tally tally;",
    "    private int best;",
    "",
    "    // Records one hit worth pts points and remembers the best single hit.",
    "    public void Hit(int pts)",
    "    {",
    "        tally.Add(pts);",
    "        best = Math.Max(best, pts);",
    "    }",
    "",
    "    public string Summary() => $\"{tally.Hits} hits, {tally.Points} pts, best {best}\";",
    "}",
  ),
  nearMiss: [
    // Drops readonly but mutates a local copy.
    code(
      "using System;",
      "",
      "public struct Tally",
      "{",
      "    public int Points;",
      "    public int Hits;",
      "    public void Add(int pts) { Points += pts; Hits++; }",
      "}",
      "",
      "public class Scoreboard",
      "{",
      "    private Tally tally;",
      "    private int best;",
      "",
      "    public void Hit(int pts)",
      "    {",
      "        var t = tally;",
      "        t.Add(pts);",
      "        best = Math.Max(best, pts);",
      "    }",
      "",
      "    public string Summary() => $\"{tally.Hits} hits, {tally.Points} pts, best {best}\";",
      "}",
    ),
    // Initializing the readonly field does not make it writable.
    code(
      "using System;",
      "",
      "public struct Tally",
      "{",
      "    public int Points;",
      "    public int Hits;",
      "    public void Add(int pts) { Points += pts; Hits++; }",
      "}",
      "",
      "public class Scoreboard",
      "{",
      "    private readonly Tally tally = new Tally();",
      "    private int best;",
      "",
      "    public void Hit(int pts)",
      "    {",
      "        tally.Add(pts);",
      "        best = Math.Max(best, pts);",
      "    }",
      "",
      "    public string Summary() => $\"{tally.Hits} hits, {tally.Points} pts, best {best}\";",
      "}",
    ),
  ],
  tests: [
    { run: "{ var s = new Scoreboard(); s.Hit(3); s.Hit(5); Console.WriteLine(s.Summary()); }", expect: "2 hits, 8 pts, best 5" },
    { run: "{ var s = new Scoreboard(); s.Hit(4); Console.WriteLine(s.Summary()); }", expect: "1 hits, 4 pts, best 4" },
    { run: "{ var s = new Scoreboard(); Console.WriteLine(s.Summary()); }", expect: "0 hits, 0 pts, best 0", hidden: true },
    { run: "{ var s = new Scoreboard(); s.Hit(2); s.Hit(9); s.Hit(1); Console.WriteLine(s.Summary()); }", expect: "3 hits, 12 pts, best 9", hidden: true },
    { run: "{ var s = new Scoreboard(); s.Hit(0); s.Hit(0); Console.WriteLine(s.Summary()); }", expect: "2 hits, 0 pts, best 0", hidden: true },
  ],
  explain: L(
    "A method call on a readonly struct field runs on a defensive copy, so Add never touched tally. Without readonly it edits the field.",
    "Llamar un método sobre un campo struct readonly actúa sobre una copia defensiva: Add nunca tocaba tally. Sin readonly edita el campo.",
    "readonly な struct フィールドへのメソッド呼び出しは防御的コピーに対して行われ、tally は不変。readonly を外せば直接変わる。",
  ),
};

/** Senior paper debug: int * int overflows before it is widened to long. */
export const quotaDebug: ExamQuestion = {
  kind: "debug",
  mode: "paper",
  topic: "types-strings",
  difficulty: 3,
  prompt: L("Debug: the storage quota", "Depura: la cuota de almacenamiento", "デバッグ：ストレージ容量"),
  brief: L(
    "Quota.TotalBytes(sizesMb) should add up file sizes given in MiB and return bytes; Fits checks the 10 GiB limit. But TotalBytes(new[] { 4096 }) returns 0 instead of 4294967296, and Fits(new[] { 20000 }) says True.",
    "Quota.TotalBytes(sizesMb) debería sumar tamaños en MiB y devolver bytes; Fits comprueba el límite de 10 GiB. Pero TotalBytes(new[] { 4096 }) devuelve 0 en vez de 4294967296, y Fits(new[] { 20000 }) dice True.",
    "Quota.TotalBytes(sizesMb) は MiB 単位のサイズを合計しバイトで返し、Fits は 10 GiB 制限を判定するはず。でも TotalBytes(new[] { 4096 }) が 4294967296 でなく 0、Fits(new[] { 20000 }) が True。",
  ),
  code: code(
    "using System;",
    "",
    "public static class Quota",
    "{",
    "    public const long LimitBytes = 10L * 1024 * 1024 * 1024; // 10 GiB",
    "",
    "    // Total size in bytes of files given in whole MiB.",
    "    public static long TotalBytes(int[] sizesMb)",
    "    {",
    "        long total = 0;",
    "        foreach (int mb in sizesMb)",
    "        {",
    "            total += mb * 1024 * 1024;",
    "        }",
    "        return total;",
    "    }",
    "",
    "    public static bool Fits(int[] sizesMb) => TotalBytes(sizesMb) <= LimitBytes;",
    "}",
  ),
  bugLine: 13,
  solution: code(
    "using System;",
    "",
    "public static class Quota",
    "{",
    "    public const long LimitBytes = 10L * 1024 * 1024 * 1024; // 10 GiB",
    "",
    "    // Total size in bytes of files given in whole MiB.",
    "    public static long TotalBytes(int[] sizesMb)",
    "    {",
    "        long total = 0;",
    "        foreach (int mb in sizesMb)",
    "        {",
    "            total += mb * 1024L * 1024;",
    "        }",
    "        return total;",
    "    }",
    "",
    "    public static bool Fits(int[] sizesMb) => TotalBytes(sizesMb) <= LimitBytes;",
    "}",
  ),
  nearMiss: [
    // The cast comes after the int multiplication already overflowed.
    code(
      "using System;",
      "",
      "public static class Quota",
      "{",
      "    public const long LimitBytes = 10L * 1024 * 1024 * 1024;",
      "",
      "    public static long TotalBytes(int[] sizesMb)",
      "    {",
      "        long total = 0;",
      "        foreach (int mb in sizesMb)",
      "        {",
      "            total += (long)(mb * 1024 * 1024);",
      "        }",
      "        return total;",
      "    }",
      "",
      "    public static bool Fits(int[] sizesMb) => TotalBytes(sizesMb) <= LimitBytes;",
      "}",
    ),
    // checked turns the silent wrap into an OverflowException.
    code(
      "using System;",
      "",
      "public static class Quota",
      "{",
      "    public const long LimitBytes = 10L * 1024 * 1024 * 1024;",
      "",
      "    public static long TotalBytes(int[] sizesMb)",
      "    {",
      "        long total = 0;",
      "        foreach (int mb in sizesMb)",
      "        {",
      "            total += checked(mb * 1024 * 1024);",
      "        }",
      "        return total;",
      "    }",
      "",
      "    public static bool Fits(int[] sizesMb) => TotalBytes(sizesMb) <= LimitBytes;",
      "}",
    ),
  ],
  tests: [
    { run: "Console.WriteLine(Quota.TotalBytes(new[] { 4096 }));", expect: "4294967296" },
    { run: "Console.WriteLine(Quota.TotalBytes(new[] { 1, 2 }));", expect: "3145728" },
    { run: "Console.WriteLine(Quota.Fits(new[] { 20000 }));", expect: "False", hidden: true },
    { run: "Console.WriteLine(Quota.TotalBytes(new[] { 3000, 2048 }));", expect: "5293211648", hidden: true },
    { run: "Console.WriteLine(Quota.Fits(new[] { 5000, 5000 }));", expect: "True", hidden: true },
    { run: "Console.WriteLine(Quota.TotalBytes(new int[0]));", expect: "0", hidden: true },
  ],
  explain: L(
    "mb * 1024 * 1024 is int math and silently wraps past 2^31 before += widens it. 1024L makes the multiplication long.",
    "mb * 1024 * 1024 es aritmética int y da la vuelta al pasar 2^31 antes de que += la amplíe. 1024L hace la multiplicación long.",
    "mb * 1024 * 1024 は int 演算で、+= が long にする前に 2^31 を超えて黙って桁あふれする。1024L で long の乗算になる。",
  ),
};

export const juniorTraceDebug: ExamQuestion[] = [concatTrace, structClassTrace];
export const midTraceDebug: ExamQuestion[] = [deferredTrace, loopClosureTrace, slugDebug, shipPendingDebug];
export const seniorTraceDebug: ExamQuestion[] = [boxingTrace, detachDebug, readonlyStructDebug, quotaDebug];
