import type { ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Written-test formats for moon Reactia (React): trace tables (dry-run the code, fill the values)
// and debugging tasks (tap the buggy line, then fix it). Code is TSX; state logic (update queues,
// reducers, memo comparisons) is traced as plain functions, and components are judged with a static
// render (renderToStaticMarkup), like the coding tasks. The validator type-checks and runs every
// `verify`, and proves each fix passes the tests while the buggy code and the near misses fail.

const code = (...lines: string[]) => lines.join("\n");

/** Debug files begin with these imports, like the coding tasks, so the tests can render JSX. */
const IMPORTS = 'import React from "react";\nimport { renderToStaticMarkup } from "react-dom/server";\n';
/** Debug file: the imports, a blank line, then the code (line numbers count the imports). */
const file = (...lines: string[]) => [IMPORTS, ...lines].join("\n");

// ─── JUNIOR ───────────────────────────────────────────────────────────────

/** Junior trace: the setter calls of one click, replayed in order. */
export const updateQueueTrace: ExamQuestion = {
  slug: "update-queue",
  kind: "trace",
  topic: "state",
  difficulty: 1,
  prompt: L("Trace table: one click, four setter calls", "Tabla de traza: un clic, cuatro setters", "トレース：1回のクリックと4回の set"),
  brief: L(
    "React queues the four calls, then applies them in order. Each row is state after that update.",
    "React encola las cuatro llamadas y luego las aplica en orden. Cada fila es state tras ese cambio.",
    "React は4回の呼び出しを溜めて順に適用する。各行はその更新後の state。",
  ),
  code: code(
    "let state = 0;",
    "const queue: Array<number | ((n: number) => number)> = [];",
    "const setCount = (u: number | ((n: number) => number)) => queue.push(u);",
    "const count = state; // the value this render saw",
    "setCount(count + 1);",
    "setCount((c) => c + 1);",
    "setCount(count + 5);",
    "setCount((c) => c * 2);",
    "for (const u of queue) state = typeof u === \"function\" ? u(state) : u;",
  ),
  columns: ["state"],
  rows: [
    { label: L("after update 1", "tras el cambio 1", "更新1の後"), cells: ["1"] },
    { label: L("after update 2", "tras el cambio 2", "更新2の後"), cells: ["2"] },
    { label: L("after update 3", "tras el cambio 3", "更新3の後"), cells: ["5"] },
    { label: L("after update 4", "tras el cambio 4", "更新4の後"), cells: ["10"] },
  ],
  verify: code(
    "let state = 0;",
    "const queue: Array<number | ((n: number) => number)> = [];",
    "const setCount = (u: number | ((n: number) => number)) => queue.push(u);",
    "const count = state;",
    "setCount(count + 1);",
    "setCount((c) => c + 1);",
    "setCount(count + 5);",
    "setCount((c) => c * 2);",
    "for (const u of queue) {",
    "  state = typeof u === \"function\" ? u(state) : u;",
    "  console.log(state);",
    "}",
  ),
  explain: L(
    "count stays 0 for the whole click. A value replaces the state (0+1, then 0+5); an updater gets the latest one (1+1, then 5*2).",
    "count sigue en 0 todo el clic. Un valor reemplaza el estado (0+1, luego 0+5); un updater recibe el último (1+1, luego 5*2).",
    "count はクリック中ずっと 0。値は state を置きかえ（0+1、0+5）、関数は最新値を受け取る（1+1、5*2）。",
  ),
};

/** Junior trace: && renders a 0, || falls back on an empty string. */
export const badgeMarkupTrace: ExamQuestion = {
  slug: "badge-markup",
  kind: "trace",
  topic: "jsx",
  difficulty: 1,
  prompt: L("Trace table: what Badge renders", "Tabla de traza: qué renderiza Badge", "トレース：Badge の描画結果"),
  brief: L(
    "Each row renders <Badge> with those props; write the HTML of renderToStaticMarkup.",
    "Cada fila renderiza <Badge> con esas props; escribe el HTML de renderToStaticMarkup.",
    "各行はその props で <Badge> を描画。renderToStaticMarkup の HTML を書く。",
  ),
  code: code(
    "function Badge({ count, name }: { count: number; name: string }) {",
    "  return <p title={name || \"anon\"}>{count && <b>{count}</b>}</p>;",
    "}",
  ),
  columns: ["HTML"],
  rows: [
    { label: "count=3 name=\"Ada\"", cells: ["<p title=\"Ada\"><b>3</b></p>"], given: [0] },
    { label: "count=0 name=\"Bo\"", cells: ["<p title=\"Bo\">0</p>"] },
    { label: "count=5 name=\"\"", cells: ["<p title=\"anon\"><b>5</b></p>"] },
    { label: "count=0 name=\"\"", cells: ["<p title=\"anon\">0</p>"] },
  ],
  verify: code(
    "import React from \"react\";",
    "import { renderToStaticMarkup } from \"react-dom/server\";",
    "function Badge({ count, name }: { count: number; name: string }) {",
    "  return <p title={name || \"anon\"}>{count && <b>{count}</b>}</p>;",
    "}",
    "console.log(renderToStaticMarkup(<Badge count={3} name=\"Ada\" />));",
    "console.log(renderToStaticMarkup(<Badge count={0} name=\"Bo\" />));",
    "console.log(renderToStaticMarkup(<Badge count={5} name=\"\" />));",
    "console.log(renderToStaticMarkup(<Badge count={0} name=\"\" />));",
  ),
  explain: L(
    "count && ... gives 0 when count is 0, and React renders the number 0. name || \"anon\" replaces the empty string.",
    "count && ... da 0 cuando count es 0, y React renderiza el número 0. name || \"anon\" reemplaza el string vacío.",
    "count が 0 だと count && ... は 0 になり、React は数値 0 を描く。name || \"anon\" は空文字を置きかえる。",
  ),
};

// ─── MID ──────────────────────────────────────────────────────────────────

/** Mid trace: a reducer run over a list of actions. */
export const reducerTrace: ExamQuestion = {
  slug: "reducer",
  kind: "trace",
  topic: "context_reducer",
  difficulty: 2,
  prompt: L("Trace table: dispatching actions", "Tabla de traza: despachar acciones", "トレース：アクションの dispatch"),
  brief: L(
    "Each row is the state after dispatching that action.",
    "Cada fila es el estado tras despachar esa acción.",
    "各行はそのアクションを dispatch した後の state。",
  ),
  code: code(
    "type S = { n: number; log: string };",
    "function reducer(s: S, a: \"inc\" | \"double\" | \"reset\"): S {",
    "  if (a === \"inc\") return { ...s, n: s.n + 1 };",
    "  if (a === \"double\") return { n: s.n * 2, log: s.log + \"d\" };",
    "  return { ...s, n: 0, log: s.log + \"r\" };",
    "}",
    "let s: S = { n: 1, log: \"s\" };",
    "for (const a of [\"inc\", \"double\", \"inc\", \"reset\", \"double\"] as const) s = reducer(s, a);",
  ),
  columns: ["a", "s.n", "s.log"],
  rows: [
    { label: L("dispatch 1", "acción 1", "1回目"), cells: ["inc", "2", "s"], given: [0] },
    { label: L("dispatch 2", "acción 2", "2回目"), cells: ["double", "4", "sd"], given: [0] },
    { label: L("dispatch 3", "acción 3", "3回目"), cells: ["inc", "5", "sd"], given: [0] },
    { label: L("dispatch 4", "acción 4", "4回目"), cells: ["reset", "0", "sdr"], given: [0] },
    { label: L("dispatch 5", "acción 5", "5回目"), cells: ["double", "0", "sdrd"], given: [0] },
  ],
  verify: code(
    "type S = { n: number; log: string };",
    "function reducer(s: S, a: \"inc\" | \"double\" | \"reset\"): S {",
    "  if (a === \"inc\") return { ...s, n: s.n + 1 };",
    "  if (a === \"double\") return { n: s.n * 2, log: s.log + \"d\" };",
    "  return { ...s, n: 0, log: s.log + \"r\" };",
    "}",
    "let s: S = { n: 1, log: \"s\" };",
    "for (const a of [\"inc\", \"double\", \"inc\", \"reset\", \"double\"] as const) {",
    "  s = reducer(s, a);",
    "  console.log(`${a} | ${s.n} | ${s.log}`);",
    "}",
  ),
  explain: L(
    "Each action gets the state the previous one returned. ...s keeps log on inc; double and reset append a letter.",
    "Cada acción recibe el estado que devolvió la anterior. ...s conserva log en inc; double y reset añaden una letra.",
    "各アクションは前の戻り値を受け取る。inc は ...s で log を保ち、double と reset は1文字足す。",
  ),
};

/** Mid trace: state follows the key, not the item. */
export const keyStateTrace: ExamQuestion = {
  slug: "key-state",
  kind: "trace",
  topic: "lists_keys",
  difficulty: 2,
  prompt: L("Trace table: state kept by key", "Tabla de traza: estado guardado por key", "トレース：key ごとに残る state"),
  brief: L(
    "A list keeps each row's state by key, like React. Each row renders that list with both versions; write the letters returned.",
    "Una lista guarda el estado de cada fila por key, como React. Cada fila renderiza esa lista con las dos versiones; escribe las letras devueltas.",
    "リストは React と同じく key ごとに state を持つ。各行でそのリストを両方で描画し、返る文字を書く。",
  ),
  code: code(
    "function makeList(keyOf: (name: string, i: number) => string) {",
    "  const state = new Map<string, string>(); // what React keeps per key",
    "  return (items: string[]) => items.map((name, i) => {",
    "    const key = keyOf(name, i);",
    "    if (!state.has(key)) state.set(key, name[0]); // first render",
    "    return state.get(key);",
    "  }).join(\"\");",
    "}",
    "const byIndex = makeList((_, i) => String(i));",
    "const byName = makeList((name) => name);",
  ),
  columns: ["byIndex", "byName"],
  rows: [
    { label: "[\"ant\", \"bee\", \"cat\"]", cells: ["abc", "abc"], given: [0, 1] },
    { label: "[\"bee\", \"cat\"]", cells: ["ab", "bc"] },
    { label: "[\"dog\", \"bee\", \"cat\"]", cells: ["abc", "dbc"] },
  ],
  verify: code(
    "function makeList(keyOf: (name: string, i: number) => string) {",
    "  const state = new Map<string, string>();",
    "  return (items: string[]) => items.map((name, i) => {",
    "    const key = keyOf(name, i);",
    "    if (!state.has(key)) state.set(key, name[0]);",
    "    return state.get(key);",
    "  }).join(\"\");",
    "}",
    "const byIndex = makeList((_, i) => String(i));",
    "const byName = makeList((name) => name);",
    "for (const list of [[\"ant\", \"bee\", \"cat\"], [\"bee\", \"cat\"], [\"dog\", \"bee\", \"cat\"]]) {",
    "  console.log(`${byIndex(list)} | ${byName(list)}`);",
    "}",
  ),
  explain: L(
    "With index keys, bee lands on key 0 and inherits ant's state. Name keys keep each item's own state when the order changes.",
    "Con keys de índice, bee cae en la key 0 y hereda el estado de ant. Las keys por nombre conservan el estado de cada item.",
    "添字 key だと bee は key 0 に入り ant の state を受け継ぐ。名前の key なら並びが変わっても各自の state を保つ。",
  ),
};

/** Mid debug (ide): sort() mutates the props array. */
export const leaderboardSortDebug: ExamQuestion = {
  slug: "leaderboard-sort",
  kind: "debug",
  mode: "ide",
  topic: "immutability",
  difficulty: 2,
  prompt: L("Debug: a leaderboard that reorders its props", "Depura: un ranking que reordena sus props", "デバッグ：props を並べ替えるランキング"),
  brief: L(
    "Leaderboard shows the 3 best players, highest score first, and must never change the players array it receives. But after rendering it with [Ada 3, Bo 9], the parent's array reads Bo, Ada.",
    "Leaderboard muestra los 3 mejores jugadores, de mayor a menor puntuación, y nunca debe cambiar el array players que recibe. Pero tras renderizarlo con [Ada 3, Bo 9], el array del padre queda Bo, Ada.",
    "Leaderboard は上位3人を高得点順に表示し、受け取った players 配列は変えてはいけない。でも [Ada 3, Bo 9] で描画すると、親の配列が Bo, Ada の順になる。",
  ),
  code: file(
    "type Player = { name: string; score: number };",
    "",
    "function Leaderboard({ players }: { players: Player[] }) {",
    "  const top = players.sort((a, b) => b.score - a.score).slice(0, 3);",
    "  return <ol>{top.map((p) => <li key={p.name}>{p.name}</li>)}</ol>;",
    "}",
  ),
  bugLine: 7,
  solution: file(
    "type Player = { name: string; score: number };",
    "",
    "function Leaderboard({ players }: { players: Player[] }) {",
    "  const top = [...players].sort((a, b) => b.score - a.score).slice(0, 3);",
    "  return <ol>{top.map((p) => <li key={p.name}>{p.name}</li>)}</ol>;",
    "}",
  ),
  nearMiss: [
    // Cuts before sorting: the best player may be past the first three.
    file(
      "type Player = { name: string; score: number };",
      "",
      "function Leaderboard({ players }: { players: Player[] }) {",
      "  const top = players.slice(0, 3).sort((a, b) => b.score - a.score);",
      "  return <ol>{top.map((p) => <li key={p.name}>{p.name}</li>)}</ol>;",
      "}",
    ),
    // Still sorts the props array in place.
    file(
      "type Player = { name: string; score: number };",
      "",
      "function Leaderboard({ players }: { players: Player[] }) {",
      "  const top = players.sort((a, b) => a.score - b.score).slice(-3).reverse();",
      "  return <ol>{top.map((p) => <li key={p.name}>{p.name}</li>)}</ol>;",
      "}",
    ),
  ],
  tests: [
    {
      run: "{\n  const ps = [{ name: \"Ada\", score: 3 }, { name: \"Bo\", score: 9 }];\n  renderToStaticMarkup(<Leaderboard players={ps} />);\n  console.log(ps.map((p) => p.name).join(\",\"));\n}",
      expect: "Ada,Bo",
    },
    {
      run: "console.log(renderToStaticMarkup(<Leaderboard players={[{ name: \"Ada\", score: 3 }, { name: \"Bo\", score: 9 }, { name: \"Cy\", score: 5 }, { name: \"Di\", score: 1 }]} />));",
      expect: "<ol><li>Bo</li><li>Cy</li><li>Ada</li></ol>",
    },
    {
      run: "console.log(renderToStaticMarkup(<Leaderboard players={[{ name: \"Ed\", score: 1 }, { name: \"Fa\", score: 2 }, { name: \"Gu\", score: 3 }, { name: \"Hu\", score: 99 }]} />));",
      expect: "<ol><li>Hu</li><li>Gu</li><li>Fa</li></ol>",
      hidden: true,
    },
    {
      run: "{\n  const ps = [{ name: \"Ed\", score: 1 }, { name: \"Fa\", score: 7 }, { name: \"Gu\", score: 4 }];\n  renderToStaticMarkup(<Leaderboard players={ps} />);\n  console.log(ps.map((p) => p.name).join(\",\"));\n}",
      expect: "Ed,Fa,Gu",
      hidden: true,
    },
    { run: "console.log(renderToStaticMarkup(<Leaderboard players={[]} />));", expect: "<ol></ol>", hidden: true },
  ],
  explain: L(
    "sort() reorders the array in place, and that array is the parent's props. Sort a copy ([...players]) and props stay untouched.",
    "sort() reordena el array en su sitio, y ese array son las props del padre. Ordena una copia ([...players]) y las props no cambian.",
    "sort() は配列そのものを並べ替え、それは親の props。コピー（[...players]）を並べれば props は変わらない。",
  ),
};

/** Mid debug (ide): setter calls built from the render's value instead of the pending one. */
export const addPointsQueueDebug: ExamQuestion = {
  slug: "add-points-queue",
  kind: "debug",
  mode: "ide",
  topic: "state",
  difficulty: 2,
  prompt: L("Debug: points lost in one click", "Depura: puntos perdidos en un clic", "デバッグ：1回のクリックで消える点"),
  brief: L(
    "addPoints adds every hit to the score during one click, building on any update already queued in that click. replay runs a click like React and returns the final state. But replay(10, (set) => addPoints(10, set, [1, 2])) gives 12 instead of 13.",
    "addPoints suma cada golpe a la puntuación durante un clic, partiendo de cualquier cambio ya encolado en ese clic. replay ejecuta un clic como React y devuelve el estado final. Pero replay(10, (set) => addPoints(10, set, [1, 2])) da 12 en vez de 13.",
    "addPoints は1回のクリック中に各 hit を score に足す。同じクリックで先に溜まった更新も土台にする。replay は React のようにクリックを処理し最終 state を返す。でも replay(10, (set) => addPoints(10, set, [1, 2])) が 13 ではなく 12。",
  ),
  code: file(
    "type Update = number | ((n: number) => number);",
    "type Setter = (u: Update) => void;",
    "",
    "// React's queue: run a click handler, then apply its updates in order.",
    "function replay(start: number, handler: (set: Setter) => void): number {",
    "  const queue: Update[] = [];",
    "  handler((u) => queue.push(u));",
    "  return queue.reduce<number>((s, u) => (typeof u === \"function\" ? u(s) : u), start);",
    "}",
    "",
    "// score is the value this render saw.",
    "function addPoints(score: number, setScore: Setter, hits: number[]) {",
    "  for (const h of hits) {",
    "    setScore(score + h);",
    "  }",
    "}",
  ),
  bugLine: 17,
  solution: file(
    "type Update = number | ((n: number) => number);",
    "type Setter = (u: Update) => void;",
    "",
    "// React's queue: run a click handler, then apply its updates in order.",
    "function replay(start: number, handler: (set: Setter) => void): number {",
    "  const queue: Update[] = [];",
    "  handler((u) => queue.push(u));",
    "  return queue.reduce<number>((s, u) => (typeof u === \"function\" ? u(s) : u), start);",
    "}",
    "",
    "// score is the value this render saw.",
    "function addPoints(score: number, setScore: Setter, hits: number[]) {",
    "  for (const h of hits) {",
    "    setScore((s) => s + h);",
    "  }",
    "}",
  ),
  nearMiss: [
    // Right total from the render's value, but it overwrites earlier queued updates.
    file(
      "type Update = number | ((n: number) => number);",
      "type Setter = (u: Update) => void;",
      "",
      "// React's queue: run a click handler, then apply its updates in order.",
      "function replay(start: number, handler: (set: Setter) => void): number {",
      "  const queue: Update[] = [];",
      "  handler((u) => queue.push(u));",
      "  return queue.reduce<number>((s, u) => (typeof u === \"function\" ? u(s) : u), start);",
      "}",
      "",
      "// score is the value this render saw.",
      "function addPoints(score: number, setScore: Setter, hits: number[]) {",
      "  for (const h of hits) {",
      "    score += h;",
      "    setScore(score);",
      "  }",
      "}",
    ),
    // An updater that ignores its argument.
    file(
      "type Update = number | ((n: number) => number);",
      "type Setter = (u: Update) => void;",
      "",
      "// React's queue: run a click handler, then apply its updates in order.",
      "function replay(start: number, handler: (set: Setter) => void): number {",
      "  const queue: Update[] = [];",
      "  handler((u) => queue.push(u));",
      "  return queue.reduce<number>((s, u) => (typeof u === \"function\" ? u(s) : u), start);",
      "}",
      "",
      "// score is the value this render saw.",
      "function addPoints(score: number, setScore: Setter, hits: number[]) {",
      "  for (const h of hits) {",
      "    setScore(() => score + h);",
      "  }",
      "}",
    ),
  ],
  tests: [
    { run: "console.log(replay(10, (set) => addPoints(10, set, [1, 2])));", expect: "13" },
    { run: "console.log(replay(0, (set) => addPoints(0, set, [5])));", expect: "5" },
    { run: "console.log(replay(4, (set) => addPoints(4, set, [])));", expect: "4", hidden: true },
    { run: "console.log(replay(10, (set) => { set((n) => n * 2); addPoints(10, set, [1]); }));", expect: "21", hidden: true },
    { run: "console.log(replay(1, (set) => { set(100); addPoints(1, set, [1, 1, 1]); }));", expect: "103", hidden: true },
  ],
  explain: L(
    "score is the render's snapshot, so each call set 10 + h and the last one won. (s) => s + h builds on the pending value.",
    "score es la foto del render: cada llamada ponía 10 + h y ganaba la última. (s) => s + h parte del valor pendiente.",
    "score は描画時のスナップショットで、毎回 10 + h を設定し最後が勝つ。(s) => s + h なら保留中の値に足す。",
  ),
};

// ─── SENIOR ───────────────────────────────────────────────────────────────

/** Senior trace: a useMemo-style cache compared with Object.is. */
export const memoDepsTrace: ExamQuestion = {
  slug: "memo-deps",
  kind: "trace",
  topic: "memoization",
  difficulty: 3,
  prompt: L("Trace table: when does the memo recompute?", "Tabla de traza: ¿cuándo recalcula el memo?", "トレース：memo が再計算するのはいつ？"),
  brief: L(
    "memo works like useMemo: it compares each dependency with Object.is. Each row is one render of the loop.",
    "memo funciona como useMemo: compara cada dependencia con Object.is. Cada fila es un render del bucle.",
    "memo は useMemo と同じく各依存を Object.is で比べる。各行はループ1回分の描画。",
  ),
  code: code(
    "let deps: unknown[] = [];",
    "let cached = 0;",
    "let computes = 0;",
    "function memo(fn: () => number, next: unknown[]): number {",
    "  const same = deps.length === next.length && next.every((d, i) => Object.is(d, deps[i]));",
    "  if (!same) { cached = fn(); computes++; deps = next; }",
    "  return cached;",
    "}",
    "const cfg = { mult: 2 };",
    "for (const [n, c] of [[3, cfg], [3, cfg], [3, { mult: 2 }], [NaN, cfg], [NaN, cfg]] as const)",
    "  memo(() => n * c.mult, [n, c]);",
  ),
  columns: ["returns", "computes"],
  rows: [
    { label: L("render 1", "render 1", "描画1"), cells: ["6", "1"], given: [0, 1] },
    { label: L("render 2", "render 2", "描画2"), cells: ["6", "1"] },
    { label: L("render 3", "render 3", "描画3"), cells: ["6", "2"] },
    { label: L("render 4", "render 4", "描画4"), cells: ["NaN", "3"] },
    { label: L("render 5", "render 5", "描画5"), cells: ["NaN", "3"] },
  ],
  verify: code(
    "let deps: unknown[] = [];",
    "let cached = 0;",
    "let computes = 0;",
    "function memo(fn: () => number, next: unknown[]): number {",
    "  const same = deps.length === next.length && next.every((d, i) => Object.is(d, deps[i]));",
    "  if (!same) { cached = fn(); computes++; deps = next; }",
    "  return cached;",
    "}",
    "const cfg = { mult: 2 };",
    "for (const [n, c] of [[3, cfg], [3, cfg], [3, { mult: 2 }], [NaN, cfg], [NaN, cfg]] as const) {",
    "  const r = memo(() => n * c.mult, [n, c]);",
    "  console.log(`${r} | ${computes}`);",
    "}",
  ),
  explain: L(
    "Render 3 passes a new object, equal in shape but not the same reference: recompute. Object.is(NaN, NaN) is true, so render 5 reuses.",
    "El render 3 pasa un objeto nuevo, igual en forma pero otra referencia: recalcula. Object.is(NaN, NaN) es true, así que el 5 reutiliza.",
    "描画3は形が同じでも別参照の新オブジェクトなので再計算。Object.is(NaN, NaN) は true なので描画5は再利用。",
  ),
};

/** Senior debug (ide): pages counted with floor, so the last partial page is unreachable. */
export const pagerDebug: ExamQuestion = {
  slug: "pager",
  kind: "debug",
  mode: "ide",
  topic: "rendering",
  difficulty: 3,
  prompt: L("Debug: the missing last page", "Depura: la última página que falta", "デバッグ：消えた最後のページ"),
  brief: L(
    "Pager shows perPage items of page page (0-based, clamped to the pages that exist; at least 1 page). But with 5 items, perPage 2 and page 2 it shows items 3-4 and \"Page 2 of 2\" instead of item 5 and \"Page 3 of 3\".",
    "Pager muestra perPage items de la página page (desde 0, limitada a las páginas que existen; al menos 1). Pero con 5 items, perPage 2 y page 2 muestra los items 3-4 y \"Page 2 of 2\" en vez del item 5 y \"Page 3 of 3\".",
    "Pager は page ページ目（0始まり、存在する範囲に制限、最低1ページ）の perPage 件を表示。でも5件・perPage 2・page 2 で、5件目と \"Page 3 of 3\" ではなく3〜4件目と \"Page 2 of 2\" になる。",
  ),
  code: file(
    "type PagerProps = { items: string[]; page: number; perPage: number };",
    "",
    "function Pager({ items, page, perPage }: PagerProps) {",
    "  const pages = Math.max(1, Math.floor(items.length / perPage));",
    "  const current = Math.min(Math.max(page, 0), pages - 1);",
    "  const start = current * perPage;",
    "  const visible = items.slice(start, start + perPage);",
    "  return (",
    "    <section>",
    "      <ul>",
    "        {visible.map((item) => (",
    "          <li key={item}>{item}</li>",
    "        ))}",
    "      </ul>",
    "      <p>{`Page ${current + 1} of ${pages}`}</p>",
    "    </section>",
    "  );",
    "}",
  ),
  bugLine: 7,
  solution: file(
    "type PagerProps = { items: string[]; page: number; perPage: number };",
    "",
    "function Pager({ items, page, perPage }: PagerProps) {",
    "  const pages = Math.max(1, Math.ceil(items.length / perPage));",
    "  const current = Math.min(Math.max(page, 0), pages - 1);",
    "  const start = current * perPage;",
    "  const visible = items.slice(start, start + perPage);",
    "  return (",
    "    <section>",
    "      <ul>",
    "        {visible.map((item) => (",
    "          <li key={item}>{item}</li>",
    "        ))}",
    "      </ul>",
    "      <p>{`Page ${current + 1} of ${pages}`}</p>",
    "    </section>",
    "  );",
    "}",
  ),
  nearMiss: [
    // One page too many when the items divide evenly.
    file(
      "type PagerProps = { items: string[]; page: number; perPage: number };",
      "",
      "function Pager({ items, page, perPage }: PagerProps) {",
      "  const pages = Math.max(1, Math.floor(items.length / perPage) + 1);",
      "  const current = Math.min(Math.max(page, 0), pages - 1);",
      "  const start = current * perPage;",
      "  const visible = items.slice(start, start + perPage);",
      "  return (",
      "    <section>",
      "      <ul>",
      "        {visible.map((item) => (",
      "          <li key={item}>{item}</li>",
      "        ))}",
      "      </ul>",
      "      <p>{`Page ${current + 1} of ${pages}`}</p>",
      "    </section>",
      "  );",
      "}",
    ),
    // round only works when the remainder is at least half a page.
    file(
      "type PagerProps = { items: string[]; page: number; perPage: number };",
      "",
      "function Pager({ items, page, perPage }: PagerProps) {",
      "  const pages = Math.max(1, Math.round(items.length / perPage));",
      "  const current = Math.min(Math.max(page, 0), pages - 1);",
      "  const start = current * perPage;",
      "  const visible = items.slice(start, start + perPage);",
      "  return (",
      "    <section>",
      "      <ul>",
      "        {visible.map((item) => (",
      "          <li key={item}>{item}</li>",
      "        ))}",
      "      </ul>",
      "      <p>{`Page ${current + 1} of ${pages}`}</p>",
      "    </section>",
      "  );",
      "}",
    ),
  ],
  tests: [
    {
      run: "console.log(renderToStaticMarkup(<Pager items={[\"a\", \"b\", \"c\", \"d\", \"e\"]} page={2} perPage={2} />));",
      expect: "<section><ul><li>e</li></ul><p>Page 3 of 3</p></section>",
    },
    {
      run: "console.log(renderToStaticMarkup(<Pager items={[\"a\", \"b\", \"c\", \"d\", \"e\"]} page={0} perPage={2} />));",
      expect: "<section><ul><li>a</li><li>b</li></ul><p>Page 1 of 3</p></section>",
    },
    {
      run: "console.log(renderToStaticMarkup(<Pager items={[\"a\", \"b\", \"c\", \"d\"]} page={9} perPage={2} />));",
      expect: "<section><ul><li>c</li><li>d</li></ul><p>Page 2 of 2</p></section>",
      hidden: true,
    },
    {
      run: "console.log(renderToStaticMarkup(<Pager items={[\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\"]} page={2} perPage={3} />));",
      expect: "<section><ul><li>g</li></ul><p>Page 3 of 3</p></section>",
      hidden: true,
    },
    {
      run: "console.log(renderToStaticMarkup(<Pager items={[]} page={0} perPage={5} />));",
      expect: "<section><ul></ul><p>Page 1 of 1</p></section>",
      hidden: true,
    },
  ],
  explain: L(
    "floor drops the last partial page (5/2 → 2), so page 2 was clamped to 1. ceil counts it (5/2 → 3) and the clamp lets it through.",
    "floor descarta la última página parcial (5/2 → 2), así que page 2 se limitaba a 1. ceil la cuenta (5/2 → 3) y el límite la deja pasar.",
    "floor は最後の端数ページを捨てる（5/2→2）ので page 2 が 1 に丸められた。ceil なら数える（5/2→3）。",
  ),
};

/** Senior debug (paper): undo history keeps a stale redo stack after a new edit. */
export const undoRedoDebug: ExamQuestion = {
  slug: "undo-redo",
  kind: "debug",
  mode: "paper",
  topic: "context_reducer",
  difficulty: 3,
  prompt: L("Debug: redo brings back the wrong text", "Depura: redo devuelve el texto equivocado", "デバッグ：redo で違う文字が戻る"),
  brief: L(
    "historyReducer powers undo/redo for a text field: type records a new present, undo and redo move through the history (doing nothing at the end), and typing after an undo starts a new branch, so there is nothing to redo. But type a, type ab, undo, type ax, redo shows ab instead of ax.",
    "historyReducer da undo/redo a un campo de texto: type guarda un nuevo present, undo y redo recorren el historial (sin hacer nada en los extremos), y escribir tras un undo abre una rama nueva, sin nada que rehacer. Pero type a, type ab, undo, type ax, redo muestra ab en vez de ax.",
    "historyReducer は入力欄の undo/redo。type は新しい present を記録し、undo/redo は履歴を移動（端では何もしない）。undo の後に入力すると新しい枝になり redo はない。でも type a, type ab, undo, type ax, redo で ax ではなく ab になる。",
  ),
  code: file(
    "type State = { past: string[]; present: string; future: string[] };",
    "type Action = { type: \"type\"; text: string } | { type: \"undo\" } | { type: \"redo\" };",
    "",
    "function historyReducer(s: State, a: Action): State {",
    "  switch (a.type) {",
    "    case \"type\":",
    "      return { past: [...s.past, s.present], present: a.text, future: s.future };",
    "    case \"undo\": {",
    "      if (s.past.length === 0) return s;",
    "      const prev = s.past[s.past.length - 1];",
    "      return { past: s.past.slice(0, -1), present: prev, future: [s.present, ...s.future] };",
    "    }",
    "    case \"redo\": {",
    "      if (s.future.length === 0) return s;",
    "      const [next, ...rest] = s.future;",
    "      return { past: [...s.past, s.present], present: next, future: rest };",
    "    }",
    "  }",
    "}",
  ),
  bugLine: 10,
  solution: file(
    "type State = { past: string[]; present: string; future: string[] };",
    "type Action = { type: \"type\"; text: string } | { type: \"undo\" } | { type: \"redo\" };",
    "",
    "function historyReducer(s: State, a: Action): State {",
    "  switch (a.type) {",
    "    case \"type\":",
    "      return { past: [...s.past, s.present], present: a.text, future: [] };",
    "    case \"undo\": {",
    "      if (s.past.length === 0) return s;",
    "      const prev = s.past[s.past.length - 1];",
    "      return { past: s.past.slice(0, -1), present: prev, future: [s.present, ...s.future] };",
    "    }",
    "    case \"redo\": {",
    "      if (s.future.length === 0) return s;",
    "      const [next, ...rest] = s.future;",
    "      return { past: [...s.past, s.present], present: next, future: rest };",
    "    }",
    "  }",
    "}",
  ),
  nearMiss: [
    // Drops only one entry of the stale redo stack.
    file(
      "type State = { past: string[]; present: string; future: string[] };",
      "type Action = { type: \"type\"; text: string } | { type: \"undo\" } | { type: \"redo\" };",
      "",
      "function historyReducer(s: State, a: Action): State {",
      "  switch (a.type) {",
      "    case \"type\":",
      "      return { past: [...s.past, s.present], present: a.text, future: s.future.slice(1) };",
      "    case \"undo\": {",
      "      if (s.past.length === 0) return s;",
      "      const prev = s.past[s.past.length - 1];",
      "      return { past: s.past.slice(0, -1), present: prev, future: [s.present, ...s.future] };",
      "    }",
      "    case \"redo\": {",
      "      if (s.future.length === 0) return s;",
      "      const [next, ...rest] = s.future;",
      "      return { past: [...s.past, s.present], present: next, future: rest };",
      "    }",
      "  }",
      "}",
    ),
    // Clears the redo stack but also the undo history.
    file(
      "type State = { past: string[]; present: string; future: string[] };",
      "type Action = { type: \"type\"; text: string } | { type: \"undo\" } | { type: \"redo\" };",
      "",
      "function historyReducer(s: State, a: Action): State {",
      "  switch (a.type) {",
      "    case \"type\":",
      "      return { past: [], present: a.text, future: [] };",
      "    case \"undo\": {",
      "      if (s.past.length === 0) return s;",
      "      const prev = s.past[s.past.length - 1];",
      "      return { past: s.past.slice(0, -1), present: prev, future: [s.present, ...s.future] };",
      "    }",
      "    case \"redo\": {",
      "      if (s.future.length === 0) return s;",
      "      const [next, ...rest] = s.future;",
      "      return { past: [...s.past, s.present], present: next, future: rest };",
      "    }",
      "  }",
      "}",
    ),
  ],
  tests: [
    {
      run: "{\n  const acts: Action[] = [{ type: \"type\", text: \"a\" }, { type: \"type\", text: \"ab\" }, { type: \"undo\" }, { type: \"type\", text: \"ax\" }, { type: \"redo\" }];\n  console.log(acts.reduce(historyReducer, { past: [], present: \"\", future: [] }).present);\n}",
      expect: "ax",
    },
    {
      run: "{\n  const acts: Action[] = [{ type: \"type\", text: \"a\" }, { type: \"type\", text: \"b\" }, { type: \"undo\" }, { type: \"undo\" }];\n  console.log(JSON.stringify(acts.reduce(historyReducer, { past: [], present: \"\", future: [] })));\n}",
      expect: "{\"past\":[],\"present\":\"\",\"future\":[\"a\",\"b\"]}",
    },
    {
      run: "{\n  const acts: Action[] = [{ type: \"type\", text: \"a\" }, { type: \"type\", text: \"b\" }, { type: \"type\", text: \"c\" }, { type: \"undo\" }, { type: \"undo\" }, { type: \"type\", text: \"z\" }];\n  console.log(JSON.stringify(acts.reduce(historyReducer, { past: [], present: \"\", future: [] })));\n}",
      expect: "{\"past\":[\"\",\"a\"],\"present\":\"z\",\"future\":[]}",
      hidden: true,
    },
    {
      run: "{\n  const acts: Action[] = [{ type: \"type\", text: \"a\" }, { type: \"undo\" }, { type: \"redo\" }, { type: \"redo\" }];\n  console.log(JSON.stringify(acts.reduce(historyReducer, { past: [], present: \"\", future: [] })));\n}",
      expect: "{\"past\":[\"\"],\"present\":\"a\",\"future\":[]}",
      hidden: true,
    },
    {
      run: "{\n  const s0 = { past: [], present: \"x\", future: [] };\n  console.log(historyReducer(s0, { type: \"undo\" }) === s0);\n}",
      expect: "true",
      hidden: true,
    },
  ],
  explain: L(
    "A new edit starts a new branch, but type kept s.future, so redo replayed the abandoned edit. future: [] drops the old branch.",
    "Una edición nueva abre otra rama, pero type conservaba s.future y redo repetía la edición abandonada. future: [] borra la rama vieja.",
    "新しい入力は新しい枝なのに type が s.future を残し、redo が捨てた編集を戻した。future: [] で古い枝を消す。",
  ),
};

/** Senior debug (paper): a memo comparator that never looks at the last tag. */
export const rowPropsEqualDebug: ExamQuestion = {
  slug: "row-props-equal",
  kind: "debug",
  mode: "paper",
  topic: "performance",
  difficulty: 3,
  prompt: L("Debug: a memo row that never updates", "Depura: una fila memo que no se actualiza", "デバッグ：更新されない memo の行"),
  brief: L(
    "rowPropsEqual is the comparator of React.memo(Row, ...): true skips the re-render. It must return true only when id, label and every tag (in order) are equal; onPick is ignored on purpose. But renaming the last tag, [\"new\", \"hot\"] to [\"new\", \"sale\"], returns true, so the row keeps showing hot.",
    "rowPropsEqual es el comparador de React.memo(Row, ...): true se salta el re-render. Debe devolver true solo si id, label y cada tag (en orden) son iguales; onPick se ignora a propósito. Pero cambiar el último tag, [\"new\", \"hot\"] a [\"new\", \"sale\"], devuelve true y la fila sigue mostrando hot.",
    "rowPropsEqual は React.memo(Row, ...) の比較関数で true なら再描画しない。id・label・全 tag（順番も）が等しい時だけ true。onPick はわざと無視。でも最後の tag を [\"new\", \"hot\"] から [\"new\", \"sale\"] に変えても true で、行は hot のまま。",
  ),
  code: file(
    "type RowProps = { id: number; label: string; tags: string[]; onPick: (id: number) => void };",
    "",
    "function Row({ id, label, tags, onPick }: RowProps) {",
    "  return <li onClick={() => onPick(id)}>{`${label} [${tags.join(\", \")}]`}</li>;",
    "}",
    "",
    "// true = props are equal, so React can skip the re-render.",
    "function rowPropsEqual(prev: RowProps, next: RowProps): boolean {",
    "  if (prev.id !== next.id || prev.label !== next.label) return false;",
    "  if (prev.tags.length !== next.tags.length) return false;",
    "  for (let i = 0; i < prev.tags.length - 1; i++) {",
    "    if (prev.tags[i] !== next.tags[i]) return false;",
    "  }",
    "  return true;",
    "}",
    "",
    "const MemoRow = React.memo(Row, rowPropsEqual);",
  ),
  bugLine: 14,
  solution: file(
    "type RowProps = { id: number; label: string; tags: string[]; onPick: (id: number) => void };",
    "",
    "function Row({ id, label, tags, onPick }: RowProps) {",
    "  return <li onClick={() => onPick(id)}>{`${label} [${tags.join(\", \")}]`}</li>;",
    "}",
    "",
    "// true = props are equal, so React can skip the re-render.",
    "function rowPropsEqual(prev: RowProps, next: RowProps): boolean {",
    "  if (prev.id !== next.id || prev.label !== next.label) return false;",
    "  if (prev.tags.length !== next.tags.length) return false;",
    "  for (let i = 0; i < prev.tags.length; i++) {",
    "    if (prev.tags[i] !== next.tags[i]) return false;",
    "  }",
    "  return true;",
    "}",
    "",
    "const MemoRow = React.memo(Row, rowPropsEqual);",
  ),
  nearMiss: [
    // Compares the arrays by reference: a new array with the same tags re-renders.
    file(
      "type RowProps = { id: number; label: string; tags: string[]; onPick: (id: number) => void };",
      "",
      "function Row({ id, label, tags, onPick }: RowProps) {",
      "  return <li onClick={() => onPick(id)}>{`${label} [${tags.join(\", \")}]`}</li>;",
      "}",
      "",
      "// true = props are equal, so React can skip the re-render.",
      "function rowPropsEqual(prev: RowProps, next: RowProps): boolean {",
      "  if (prev.id !== next.id || prev.label !== next.label) return false;",
      "  if (prev.tags.length !== next.tags.length) return false;",
      "  return prev.tags === next.tags;",
      "}",
      "",
      "const MemoRow = React.memo(Row, rowPropsEqual);",
    ),
    // Ignores the order of the tags.
    file(
      "type RowProps = { id: number; label: string; tags: string[]; onPick: (id: number) => void };",
      "",
      "function Row({ id, label, tags, onPick }: RowProps) {",
      "  return <li onClick={() => onPick(id)}>{`${label} [${tags.join(\", \")}]`}</li>;",
      "}",
      "",
      "// true = props are equal, so React can skip the re-render.",
      "function rowPropsEqual(prev: RowProps, next: RowProps): boolean {",
      "  if (prev.id !== next.id || prev.label !== next.label) return false;",
      "  if (prev.tags.length !== next.tags.length) return false;",
      "  return prev.tags.every((t) => next.tags.includes(t));",
      "}",
      "",
      "const MemoRow = React.memo(Row, rowPropsEqual);",
    ),
  ],
  tests: [
    {
      run: "{\n  const base = { id: 1, label: \"Tea\", onPick: () => {} };\n  console.log(rowPropsEqual({ ...base, tags: [\"new\", \"hot\"] }, { ...base, tags: [\"new\", \"sale\"] }));\n}",
      expect: "false",
    },
    {
      run: "{\n  const base = { id: 1, label: \"Tea\" };\n  console.log(rowPropsEqual({ ...base, tags: [\"new\"], onPick: () => {} }, { ...base, tags: [\"new\"], onPick: () => {} }));\n}",
      expect: "true",
    },
    {
      run: "{\n  const base = { id: 2, label: \"Jam\", onPick: () => {} };\n  console.log(rowPropsEqual({ ...base, tags: [\"a\", \"b\"] }, { ...base, tags: [\"b\", \"a\"] }), rowPropsEqual({ ...base, tags: [\"x\"] }, { ...base, tags: [\"y\"] }));\n}",
      expect: "false false",
      hidden: true,
    },
    {
      run: "{\n  const base = { id: 3, onPick: () => {} };\n  console.log(rowPropsEqual({ ...base, label: \"A\", tags: [] }, { ...base, label: \"A\", tags: [] }), rowPropsEqual({ ...base, label: \"A\", tags: [] }, { ...base, label: \"B\", tags: [] }));\n}",
      expect: "true false",
      hidden: true,
    },
    {
      run: "console.log(renderToStaticMarkup(<ul><MemoRow id={1} label=\"Tea\" tags={[\"new\", \"hot\"]} onPick={() => {}} /></ul>));",
      expect: "<ul><li>Tea [new, hot]</li></ul>",
      hidden: true,
    },
  ],
  explain: L(
    "The loop stopped at length - 1, so the last tag was never compared. i < prev.tags.length checks every tag.",
    "El bucle paraba en length - 1, así que el último tag nunca se comparaba. i < prev.tags.length revisa todos.",
    "ループが length - 1 で止まり最後の tag を比べていなかった。i < prev.tags.length で全部比べる。",
  ),
};

export const juniorTraceDebug: ExamQuestion[] = [updateQueueTrace, badgeMarkupTrace];
export const midTraceDebug: ExamQuestion[] = [reducerTrace, keyStateTrace, leaderboardSortDebug, addPointsQueueDebug];
export const seniorTraceDebug: ExamQuestion[] = [memoDepsTrace, pagerDebug, undoRedoDebug, rowPropsEqualDebug];
