import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";
import { say, enemySays } from "../../rust/helpers.ts";

// REGION 3 · STRUCT MOUNTAIN  (structs and methods, enums and tagged unions, pointers, slices and sentinels)
// Snippets without `pub fn main(` are wrapped in `pub fn main() !void { ... }` (scripts/snippet-wrap.ts).
// A struct declared inside main cannot name itself, so snippets with methods or free functions are full
// files built with `zmain` (the validator only adds `const std = @import("std");`).
// Prints use std.debug.print and end with \n; never print @typeName of our own types or undefined bytes.

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const YES = L("Yes", "Sí", "はい");
const NO_CE = L("No: compile error", "No: error de compilación", "いいえ：コンパイルエラー");
const PANICS = L("It panics", "Hace panic", "panic する");

/** A full file: top-level declarations, then `pub fn main` with the body indented. */
const zmain = (top: string, body: string) =>
  `${top}\n\npub fn main() ${/\btry\b/.test(body) ? "!void" : "void"} {\n${body.split("\n").map((l) => "    " + l).join("\n")}\n}`;

const POINT = "const Point = struct {\n    x: i32,\n    y: i32 = 0,\n\n    fn sum(self: Point) i32 {\n        return self.x + self.y;\n    }\n\n    fn moveRight(self: *Point, d: i32) void {\n        self.x += d;\n    }\n};";

// ─── 3.1 Structs and methods ───────────────────────────────────────────────
const structs: LessonDef = {
  slug: "structs-and-methods",
  title: L("Blueprints", "Planos", "設計図"),
  concept: "structs",
  mode: "lesson",
  xp: 70,
  enemy: "zig/undefined-imp",
  enemyName: L("BLUEPRINT IMP", "DIABLILLO PLANO", "設計図の小鬼"),
  beats: [
    say(L(
      "Welcome to Struct Mountain! A STRUCT is a blueprint: named fields with types. Point{ .x = 1, .y = 2 } builds one.",
      "¡Bienvenido a Struct Mountain! Un STRUCT es un plano: campos con nombre y tipo. Point{ .x = 1, .y = 2 } crea uno.",
      "ストラクト山へようこそ！struct は設計図。名前と型をもつフィールドの集まり。Point{ .x = 1, .y = 2 } で作れる。",
    )),
    {
      kind: "act",
      prompt: L("Draw the blueprint, build one and copy it", "Dibuja el plano, construye uno y cópialo", "設計図をかき、作ってコピーしよう"),
      steps: [
        { label: L("BLUEPRINT", "PLANO", "設計図"), line: "const Point = struct { x: i32, y: i32 = 0 };", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "say", actor: "hero", text: L("x and y!", "¡x e y!", "x と y！") }] },
        { label: L("BUILD p", "CREAR p", "p を作る"), line: "const p = Point{ .x = 1 };", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "p", value: "1, 0" }] },
        { label: L("COPY q", "COPIAR q", "q にコピー"), line: "var q = p;", effects: [{ t: "clone", to: "hero" }, { t: "tag", actor: "hero", text: "q", value: "1, 0" }] },
        { label: L("CHANGE q.x", "CAMBIAR q.x", "q.x を変える"), line: "q.x = 9;", effects: [{ t: "value", actor: "hero", text: "9, 0" }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: 'std.debug.print("{d} {d}\\n", .{ p.x, q.x });', effects: [{ t: "print", text: "1 9" }, { t: "say", actor: "ally", text: L("Mine is safe!", "¡El mío está intacto!", "ぼくのは無事！") }], output: "1 9" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Point = struct { x: i32, y: i32 = 0 };\nconst o = Point{ .x = 4 };\nstd.debug.print("{d} {d}\\n", .{ o.x, o.y });',
      options: ["4 0", "4 4", NO_CE],
      answer: 0,
      output: "4 0",
      check: { compiles: true, stdout: "4 0" },
      explain: L("y has a default (= 0), so you may leave it out. x has none.", "y tiene un valor por defecto (= 0), así que puedes omitirlo. x no.", "y にはデフォルト値（= 0）があるので省略できる。x にはない。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "o" }],
      win: [{ t: "value", actor: "ally", text: "4, 0" }, { t: "print", text: "4 0" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "const Point = struct { x: i32, y: i32 = 0 };\nconst p = Point{ .y = 2 };\n_ = p;",
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("x has no default, so it must be given: missing struct field: x.", "x no tiene valor por defecto, hay que darlo: missing struct field: x.", "x にはデフォルトがないので必須。missing struct field: x になる。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Point = struct { x: i32, y: i32 = 0 };\nconst p = Point{ .x = 1, .y = 2 };\nvar q = p;\nq.x = 100;\nstd.debug.print("{d} {d}\\n", .{ p.x, q.x });',
      options: ["1 100", "100 100", "1 1"],
      answer: 0,
      output: "1 100",
      check: { compiles: true, stdout: "1 100" },
      explain: L("Assignment COPIES a struct. q is its own Point; changing it leaves p alone.", "Asignar COPIA el struct. q es su propio Point; cambiarlo no toca p.", "代入すると struct はコピーされる。q は別の Point なので p は変わらない。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "p", value: "1" }],
      win: [{ t: "clone", to: "hero" }, { t: "tag", actor: "hero", text: "q", value: "100" }, { t: "print", text: "1 100" }],
    },
    say(L(
      "METHODS are functions inside the struct, called with a dot. self: Point gets a COPY; self: *Point can change the original.",
      "Los MÉTODOS son funciones dentro del struct, con punto. self: Point recibe una COPIA; self: *Point cambia el original.",
      "メソッドは struct の中の関数で、ドットで呼ぶ。self: Point はコピー、self: *Point は本物を変えられる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain(POINT, 'const p = Point{ .x = 1, .y = 2 };\nstd.debug.print("{d}\\n", .{p.sum()});'),
      options: ["3", "1", "12"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("p.sum() passes p as self, so it returns 1 + 2.", "p.sum() pasa p como self, así que devuelve 1 + 2.", "p.sum() は p を self としてわたすので 1 + 2 を返す。"),
      win: [{ t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain(POINT, 'var p = Point{ .x = 1, .y = 2 };\np.moveRight(5);\nstd.debug.print("{d} {d}\\n", .{ p.x, Point.sum(p) });'),
      options: ["6 8", "1 3", "6 3"],
      answer: 0,
      output: "6 8",
      check: { compiles: true, stdout: "6 8" },
      explain: L("moveRight takes *Point, so it changes p itself. Point.sum(p) is the same as p.sum().", "moveRight recibe *Point, así que cambia p mismo. Point.sum(p) es igual que p.sum().", "moveRight は *Point を受けとるので p 自体が変わる。Point.sum(p) は p.sum() と同じ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "p", value: "x=1" }],
      win: [{ t: "lend", to: "hero", mut: true }, { t: "value", actor: "ally", text: "x=6" }, { t: "print", text: "6 8" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: zmain(POINT, "const p = Point{ .x = 1 };\np.moveRight(1);"),
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("p is const, so &p is *const Point. moveRight wants *Point: cast discards const qualifier.", "p es const, así que &p es *const Point. moveRight pide *Point: cast discards const qualifier.", "p は const なので &p は *const Point。moveRight は *Point がほしい。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "const p" }],
      win: [{ t: "shake" }, { t: "say", actor: "ally", text: L("Carved in stone!", "¡Tallado en piedra!", "石に刻まれてる！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Point = struct { x: i32, y: i32 = 0 };\nconst p = Point{ .x = 6, .y = 2 };\nstd.debug.print("{any}\\n", .{p});',
      options: [".{ .x = 6, .y = 2 }", "6 2", "Point"],
      answer: 0,
      output: ".{ .x = 6, .y = 2 }",
      check: { compiles: true, stdout: ".{ .x = 6, .y = 2 }" },
      explain: L("{any} prints a struct field by field, in the same shape as a literal.", "{any} imprime un struct campo por campo, con la misma forma de un literal.", "{any} は struct をフィールドごとに、リテラルと同じ形で表示する。"),
    },
    say(L(
      "Inside a struct, @This() means 'this very type'. Handy when the struct has no name yet, or a long one.",
      "Dentro de un struct, @This() significa 'este mismo tipo'. Útil si aún no tiene nombre o es largo.",
      "struct の中の @This() は「この型自身」。名前がまだない時や長い時に便利。",
    )),
    {
      kind: "pick",
      prompt: L("Let inc change the counter", "Haz que inc cambie el contador", "inc でカウンターを変えよう"),
      code: 'const Counter = struct {\n    n: u32 = 0,\n    fn inc(self: ___) void {\n        self.n += 1;\n    }\n};\nvar c = Counter{};\nc.inc();\nc.inc();\nstd.debug.print("{d}\\n", .{c.n});',
      options: ["*@This()", "@This()"],
      answer: 0,
      check: { compiles: true, stdout: "2", wrongFail: true },
      explain: L("A plain @This() self is a read-only copy: self.n += 1 would not compile. *@This() points at c.", "Un self @This() simple es una copia de solo lectura: self.n += 1 no compila. *@This() apunta a c.", "ただの @This() は読むだけのコピーで self.n += 1 はエラー。*@This() は c を指す。"),
      win: [{ t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Point = struct { x: i32, y: i32 = 0 };\nvar pts = [_]Point{ .{ .x = 1 }, .{ .x = 2 } };\nfor (&pts) |*pt| pt.x *= 10;\nstd.debug.print("{d} {d}\\n", .{ pts[0].x, pts[1].x });',
      options: ["10 20", "1 2", "10 2"],
      answer: 0,
      output: "10 20",
      check: { compiles: true, stdout: "10 20" },
      explain: L("for (&pts) |*pt| gives a pointer to each element, so the writes land in the array.", "for (&pts) |*pt| da un puntero a cada elemento, así que se escribe en el array.", "for (&pts) |*pt| は各要素へのポインタ。だから配列そのものに書きこまれる。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const tup = .{ 1, "two", true };\nstd.debug.print("{d} {s} {}\\n", .{ tup[0], tup[1], tup.len });',
      options: ["1 two 3", "1 two true", NO_CE],
      answer: 0,
      output: "1 two 3",
      check: { compiles: true, stdout: "1 two 3" },
      explain: L(".{ ... } without names is a tuple: fields by index, and .len counts them.", ".{ ... } sin nombres es una tupla: campos por índice, y .len los cuenta.", "名前のない .{ ... } はタプル。番号でアクセスし、.len で数がわかる。"),
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print hp: 15 25", "Arréglalo: debe imprimir hp: 15 25", "直そう：hp: 15 25 と表示させて"),
      starter: 'const std = @import("std");\n\nconst Hero = struct {\n    hp: u32,\n    fn heal(self: *Hero, n: u32) void {\n        self.hp += n;\n    }\n};\n\npub fn main() void {\n    var party = [_]Hero{ .{ .hp = 10 }, .{ .hp = 20 } };\n    for (&party) |h| {\n        var hero = h;\n        hero.heal(5);\n    }\n    std.debug.print("hp: {d} {d}\\n", .{ party[0].hp, party[1].hp });\n}\n',
      solution: 'const std = @import("std");\n\nconst Hero = struct {\n    hp: u32,\n    fn heal(self: *Hero, n: u32) void {\n        self.hp += n;\n    }\n};\n\npub fn main() void {\n    var party = [_]Hero{ .{ .hp = 10 }, .{ .hp = 20 } };\n    for (&party) |*h| {\n        h.heal(5);\n    }\n    std.debug.print("hp: {d} {d}\\n", .{ party[0].hp, party[1].hp });\n}\n',
      expect: "hp: 15 25",
      fallback: [String.raw`for\s*\(\s*&party\s*\)\s*\|\s*\*h\s*\|[\s\S]*h\.heal\(\s*5\s*\)`, String.raw`party\[0\]\.heal\(\s*5\s*\)[\s\S]*party\[1\]\.heal\(\s*5\s*\)`],
      explain: L("var hero = h; heals a COPY. Capture |*h| to get a pointer and heal the real hero.", "var hero = h; cura una COPIA. Captura |*h| para tener un puntero y curar al héroe real.", "var hero = h; はコピーを回復している。|*h| でポインタを受けとり本物を回復しよう。"),
    },
  ],
};

// ─── 3.2 Enums and tagged unions ───────────────────────────────────────────
const SHAPE = "const Shape = union(enum) {\n    circle: f32,\n    rect: struct { w: f32, h: f32 },\n};\n\nfn area(s: Shape) f32 {\n    return switch (s) {\n        .circle => |r| 3 * r * r,\n        .rect => |r| r.w * r.h,\n    };\n}";

const enums: LessonDef = {
  slug: "enums-and-unions",
  title: L("Banners and shifters", "Estandartes y cambiaformas", "旗と変身者"),
  concept: "unions",
  mode: "lesson",
  xp: 70,
  enemy: "zig/undefined-imp",
  enemyName: L("SHIFTER IMP", "DIABLILLO MUTANTE", "変身の小鬼"),
  beats: [
    say(L(
      "An ENUM is a banner with a fixed set of symbols: enum { north, east, south, west }. When the type is known, write just .west.",
      "Un ENUM es un estandarte con símbolos fijos: enum { north, east, south, west }. Si el tipo se conoce, basta .west.",
      "enum は決まった記号だけの旗：enum { north, east, south, west }。型がわかれば .west だけでOK。",
    )),
    {
      kind: "act",
      prompt: L("Raise the banner and read it", "Alza el estandarte y léelo", "旗をかかげて読んでみよう"),
      steps: [
        { label: L("ENUM", "ENUM", "enum"), line: "const Dir = enum { north, east, south, west };", effects: [{ t: "item", kind: "shield", holder: "hero" }] },
        { label: L("PICK .west", "ELEGIR .west", ".west を選ぶ"), line: "const d: Dir = .west;", effects: [{ t: "tag", actor: "hero", text: "d", value: ".west" }] },
        { label: L("NAME", "NOMBRE", "名前"), line: 'std.debug.print("{s}\\n", .{@tagName(d)});', effects: [{ t: "print", text: "west" }], output: "west" },
        { label: L("NUMBER", "NÚMERO", "番号"), line: 'std.debug.print("{d}\\n", .{@intFromEnum(d)});', effects: [{ t: "print", text: "3" }, { t: "say", actor: "hero", text: L("Counted from 0!", "¡Desde 0!", "0 から数える！") }], output: "3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain("const Dir = enum {\n    north,\n    east,\n    south,\n    west,\n\n    fn turn(self: Dir) Dir {\n        return switch (self) {\n            .north => .east,\n            .east => .south,\n            .south => .west,\n            .west => .north,\n        };\n    }\n};", 'const d: Dir = .west;\nstd.debug.print("{s} {s}\\n", .{ @tagName(d), @tagName(d.turn()) });'),
      options: ["west north", "west east", "west south"],
      answer: 0,
      output: "west north",
      check: { compiles: true, stdout: "west north" },
      explain: L("Enums can have methods too. turn maps .west to .north.", "Los enums también tienen métodos. turn convierte .west en .north.", "enum にもメソッドが書ける。turn は .west を .north にする。"),
      win: [{ t: "print", text: "west north" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const E = enum(u8) { a = 1, b = 5, c };\nstd.debug.print("{d}\\n", .{@intFromEnum(E.c)});',
      options: ["6", "2", "3"],
      answer: 0,
      output: "6",
      check: { compiles: true, stdout: "6" },
      explain: L("enum(u8) lets you pick values. A tag without one takes the previous value + 1: 5 + 1.", "enum(u8) permite elegir valores. Un tag sin valor toma el anterior + 1: 5 + 1.", "enum(u8) なら値を選べる。値なしのタグは前の値 + 1：5 + 1。"),
    },
    say(L(
      "A switch on an enum must cover EVERY tag, or end with else. Forget one and the compiler stops you.",
      "Un switch sobre un enum debe cubrir CADA tag, o terminar con else. Si olvidas uno, el compilador te frena.",
      "enum の switch はすべてのタグを書くか、else で終える。ひとつ忘れるとコンパイラが止める。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "const Dir = enum { north, east, south, west };\nconst d: Dir = .east;\nswitch (d) {\n    .north => {},\n    .east => {},\n}",
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("south and west are missing: switch must handle all possibilities.", "Faltan south y west: switch must handle all possibilities.", "south と west がない。switch must handle all possibilities になる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Dir = enum { north, east, south, west };\nconst d: Dir = .south;\nconst msg = switch (d) {\n    .north, .south => "vertical",\n    else => "horizontal",\n};\nstd.debug.print("{s}\\n", .{msg});',
      options: ["vertical", "horizontal", NO_CE],
      answer: 0,
      output: "vertical",
      check: { compiles: true, stdout: "vertical" },
      explain: L("One prong can list several tags with commas; else catches the rest.", "Una rama puede listar varios tags con comas; else atrapa el resto.", "ひとつの分岐にカンマで複数のタグを書ける。残りは else。"),
    },
    say(L(
      "A TAGGED UNION, union(enum), is a shape-shifter: ONE field at a time. switch tells you which, and |r| captures its value.",
      "Una UNIÓN ETIQUETADA, union(enum), es un cambiaformas: UN campo a la vez. switch dice cuál y |r| captura su valor.",
      "タグ付き共用体 union(enum) は変身者。一度にひとつのフィールドだけ。switch で判定し |r| で値をとる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain(SHAPE, 'std.debug.print("{d} {d}\\n", .{ area(.{ .circle = 2 }), area(.{ .rect = .{ .w = 2, .h = 3 } }) });'),
      options: ["12 6", "6 12", "12 5"],
      answer: 0,
      output: "12 6",
      check: { compiles: true, stdout: "12 6" },
      explain: L("The circle prong gives 3 * 2 * 2 = 12; the rect prong gives 2 * 3 = 6.", "La rama circle da 3 * 2 * 2 = 12; la rama rect da 2 * 3 = 6.", "circle の分岐は 3 * 2 * 2 = 12、rect の分岐は 2 * 3 = 6。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: ".circle" }],
      win: [{ t: "tag", actor: "ally", text: ".rect" }, { t: "print", text: "12 6" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Shape = union(enum) { circle: f32, rect: struct { w: f32, h: f32 } };\nconst sh: Shape = .{ .rect = .{ .w = 2, .h = 5 } };\nswitch (sh) {\n    .circle => std.debug.print("round\\n", .{}),\n    .rect => |r| std.debug.print("{d}x{d}\\n", .{ r.w, r.h }),\n}',
      options: ["2x5", "round", "10"],
      answer: 0,
      output: "2x5",
      check: { compiles: true, stdout: "2x5" },
      explain: L("sh is a rect right now, so the .rect prong runs and r holds its w and h.", "sh es un rect ahora, así que corre la rama .rect y r tiene su w y h.", "sh は今 rect なので .rect の分岐が動き、r に w と h が入る。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Shape = union(enum) { circle: f32, rect: struct { w: f32, h: f32 } };\nconst sh: Shape = .{ .circle = 1 };\nstd.debug.print("{s} {}\\n", .{ @tagName(sh), sh == .circle });',
      options: ["circle true", "circle false", NO_CE],
      answer: 0,
      output: "circle true",
      check: { compiles: true, stdout: "circle true" },
      explain: L("A tagged union knows its active tag: @tagName reads it and == .circle compares it.", "Una unión etiquetada conoce su tag activo: @tagName lo lee y == .circle lo compara.", "タグ付き共用体は今のタグを知っている。@tagName で読み、== .circle で比べる。"),
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'const Shape = union(enum) { circle: f32, rect: struct { w: f32, h: f32 } };\nvar s: Shape = .{ .circle = 1.5 };\n_ = &s;\nstd.debug.print("{d}\\n", .{s.rect.w});',
      options: [PANICS, "1.5", NO_CE],
      answer: 0,
      check: { compiles: true, throws: "access of union field 'rect' while field 'circle' is active" },
      explain: L("s is a circle. Reading .rect is caught at run time: access of union field 'rect' while 'circle' is active.", "s es un circle. Leer .rect se detecta al ejecutar: access of union field 'rect' while 'circle' is active.", "s は circle。.rect を読むと実行時に検出される。switch で調べよう。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "shake" }, { t: "banner", text: L("WRONG FORM!", "¡FORMA ERRÓNEA!", "ちがう姿！") }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'const Color = enum(u8) { red, green };\nvar n: u8 = 5;\n_ = &n;\nconst c: Color = @enumFromInt(n);\nstd.debug.print("{s}\\n", .{@tagName(c)});',
      options: [PANICS, "red", "green"],
      answer: 0,
      check: { compiles: true, throws: "invalid enum value" },
      explain: L("Color only has 0 and 1. Turning 5 into a Color panics: invalid enum value.", "Color solo tiene 0 y 1. Convertir 5 en Color hace panic: invalid enum value.", "Color は 0 と 1 だけ。5 を Color にすると panic：invalid enum value。"),
    },
    {
      kind: "type",
      prompt: L("Make it a tagged union", "Hazla una unión etiquetada", "タグ付き共用体にしよう"),
      code: 'const Shape = union(___) {\n    circle: f32,\n    square: f32,\n};\nconst sh: Shape = .{ .square = 3 };\nstd.debug.print("{s}\\n", .{@tagName(sh)});',
      answer: "enum",
      check: { compiles: true, stdout: "square" },
      explain: L("union(enum) adds a hidden tag that remembers the active field, so switch and @tagName work.", "union(enum) agrega un tag oculto que recuerda el campo activo; así funcionan switch y @tagName.", "union(enum) は今のフィールドを覚えるタグを足す。だから switch や @tagName が使える。"),
      win: [{ t: "print", text: "square" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print value: 50 (a potion is worth 10)", "Arréglalo: debe imprimir value: 50 (poción = 10)", "直そう：value: 50（ポーション1つ10）"),
      starter: 'const std = @import("std");\n\nconst Item = union(enum) {\n    coins: u32,\n    potion: u8,\n};\n\nfn value(it: Item) u32 {\n    return it.coins;\n}\n\npub fn main() void {\n    const bag = [_]Item{ .{ .coins = 30 }, .{ .potion = 2 } };\n    var total: u32 = 0;\n    for (bag) |it| total += value(it);\n    std.debug.print("value: {d}\\n", .{total});\n}\n',
      solution: 'const std = @import("std");\n\nconst Item = union(enum) {\n    coins: u32,\n    potion: u8,\n};\n\nfn value(it: Item) u32 {\n    return switch (it) {\n        .coins => |c| c,\n        .potion => |p| @as(u32, p) * 10,\n    };\n}\n\npub fn main() void {\n    const bag = [_]Item{ .{ .coins = 30 }, .{ .potion = 2 } };\n    var total: u32 = 0;\n    for (bag) |it| total += value(it);\n    std.debug.print("value: {d}\\n", .{total});\n}\n',
      expect: "value: 50",
      fallback: [String.raw`switch\s*\(\s*it\s*\)[\s\S]*\.potion\s*=>\s*\|\s*\w+\s*\|[\s\S]*10`],
      explain: L("value read .coins from every item, even potions. switch on the tag and capture each payload.", "value leía .coins de todo, incluso pociones. Haz switch sobre el tag y captura cada valor.", "value はポーションからも .coins を読んでいた。タグで switch して値をとり出そう。"),
    },
  ],
};

// ─── 3.3 Pointers ──────────────────────────────────────────────────────────
const pointers: LessonDef = {
  slug: "pointers",
  title: L("Lending without giving", "Prestar sin regalar", "あげずに貸す"),
  concept: "slices",
  mode: "lesson",
  xp: 75,
  enemy: "zig/undefined-imp",
  enemyName: L("POINTER IMP", "DIABLILLO PUNTERO", "ポインタの小鬼"),
  beats: [
    say(L(
      "&x gives a POINTER to x: a *T that says where x lives. p.* reads or writes x through it, without copying.",
      "&x da un PUNTERO a x: un *T que dice dónde vive x. p.* lee o escribe x a través de él, sin copiar.",
      "&x は x へのポインタ（*T）。x の住所を指す。p.* でコピーせずに x を読み書きできる。",
    )),
    {
      kind: "act",
      prompt: L("Lend the chest and write through the pointer", "Presta el cofre y escribe por el puntero", "宝箱を貸して、ポインタ経由で書こう"),
      steps: [
        { label: L("VAR hp", "VAR hp", "var hp"), line: "var hp: i32 = 1;", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "potion", holder: "ally" }, { t: "tag", actor: "ally", text: "hp", value: "1" }] },
        { label: L("POINT &hp", "APUNTAR &hp", "&hp を指す"), line: "const p = &hp;", effects: [{ t: "lend", to: "hero", mut: true }, { t: "tag", actor: "hero", text: "p" }] },
        { label: L("WRITE p.*", "ESCRIBIR p.*", "p.* に書く"), line: "p.* = 7;", effects: [{ t: "value", actor: "ally", text: "7" }, { t: "say", actor: "ally", text: L("Changed!", "¡Cambió!", "変わった！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: 'std.debug.print("{d}\\n", .{hp});', effects: [{ t: "print", text: "7" }], output: "7" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain("fn addOne(p: *i32) void {\n    p.* += 1;\n}", 'var n: i32 = 41;\naddOne(&n);\nstd.debug.print("{d}\\n", .{n});'),
      options: ["42", "41", NO_CE],
      answer: 0,
      output: "42",
      check: { compiles: true, stdout: "42" },
      explain: L("addOne gets the address of n, so p.* += 1 changes n itself.", "addOne recibe la dirección de n, así que p.* += 1 cambia a n mismo.", "addOne は n の住所を受けとるので、p.* += 1 で n 自体が変わる。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "n", value: "41" }],
      win: [{ t: "lend", to: "hero", mut: true }, { t: "value", actor: "ally", text: "42" }, { t: "print", text: "42" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var n: i32 = 1;\nconst ptr = &n;\nptr.* = 7;\nstd.debug.print("{d} {}\\n", .{ n, @TypeOf(ptr) });',
      options: ["7 *i32", "1 *i32", "7 i32"],
      answer: 0,
      output: "7 *i32",
      check: { compiles: true, stdout: "7 *i32" },
      explain: L("&n on a var gives *i32, a writable pointer. Writing ptr.* changes n.", "&n sobre un var da *i32, un puntero escribible. Escribir ptr.* cambia n.", "var の &n は書きこめる *i32。ptr.* に書くと n が変わる。"),
    },
    say(L(
      "&x on a CONST gives *const T: look, don't touch. You can't turn it into a writable *T.",
      "&x sobre un CONST da *const T: mira, no toques. No puedes volverlo un *T escribible.",
      "const の &x は *const T。見るだけで、さわれない。書きこめる *T にはできない。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "const x: u8 = 1;\nconst p: *u8 = &x;\n_ = p;",
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("x is const, so &x is *const u8: expected type '*u8', found '*const u8'.", "x es const, así que &x es *const u8: expected type '*u8', found '*const u8'.", "x は const なので &x は *const u8。*u8 には入らない。"),
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Look, don't touch!", "¡Mira, no toques!", "見るだけ！") }],
    },
    say(L(
      "A SLICE []T is a pointer plus a length: a window onto an array. Writes through the window change the array.",
      "Un SLICE []T es un puntero más un largo: una ventana a un array. Escribir por la ventana cambia el array.",
      "スライス []T はポインタ＋長さ。配列をのぞく窓で、窓から書くと配列が変わる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var arr = [_]i32{ 1, 2, 3, 4, 5 };\nconst s = arr[1..4];\ns[0] = 99;\nstd.debug.print("{d} {d}\\n", .{ arr[1], s.len });',
      options: ["99 3", "2 3", "99 4"],
      answer: 0,
      output: "99 3",
      check: { compiles: true, stdout: "99 3" },
      explain: L("s looks at arr[1], arr[2], arr[3]. s[0] IS arr[1], and the window is 3 long.", "s mira arr[1], arr[2], arr[3]. s[0] ES arr[1], y la ventana mide 3.", "s は arr[1]〜arr[3] をのぞく。s[0] は arr[1] そのもので、長さは 3。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "item", kind: "gem", holder: "ally" }, { t: "tag", actor: "ally", text: "arr" }],
      win: [{ t: "lend", to: "hero", mut: true }, { t: "value", actor: "ally", text: "1 99 3 4 5" }, { t: "print", text: "99 3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var arr = [_]i32{ 1, 2, 3, 4, 5 };\nvar lo: usize = 1;\n_ = &lo;\nconst a = arr[1..4];\nconst b = arr[lo..4];\nstd.debug.print("{} {}\\n", .{ @TypeOf(a), @TypeOf(b) });',
      options: ["*[3]i32 []i32", "[]i32 []i32", "*[3]i32 *[3]i32"],
      answer: 0,
      output: "*[3]i32 []i32",
      check: { compiles: true, stdout: "*[3]i32 []i32" },
      explain: L("Bounds known at compile time give a pointer to an array (*[3]i32); runtime bounds give a slice.", "Límites conocidos al compilar dan un puntero a array (*[3]i32); límites en ejecución dan un slice.", "範囲がコンパイル時にわかれば配列へのポインタ *[3]i32、実行時ならスライス。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std.debug.print("{d} {d} {d}\\n", .{ @sizeOf([]const u8), @sizeOf([3]u8), @sizeOf(*u8) });',
      options: ["16 3 8", "8 3 8", "16 24 8"],
      answer: 0,
      output: "16 3 8",
      check: { compiles: true, stdout: "16 3 8" },
      explain: L("On 64-bit, a pointer is 8 bytes and a slice is pointer + length: 16. [3]u8 is just 3 bytes.", "En 64 bits, un puntero ocupa 8 bytes y un slice es puntero + largo: 16. [3]u8 son 3 bytes.", "64ビットではポインタは8バイト、スライスはポインタ＋長さで16。[3]u8 は3バイト。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: zmain("fn sumSlice(xs: []const i32) i32 {\n    var t: i32 = 0;\n    for (xs) |x| t += x;\n    return t;\n}", 'const xs = [_]i32{ 1, 2, 3 };\nstd.debug.print("{d}\\n", .{sumSlice(&xs)});'),
      options: ["6", "3", NO_CE],
      answer: 0,
      output: "6",
      check: { compiles: true, stdout: "6" },
      explain: L("&xs is *const [3]i32, which coerces to a []const i32 slice. Functions take slices of any length.", "&xs es *const [3]i32, que se convierte en slice []const i32. Las funciones aceptan slices de cualquier largo.", "&xs は *const [3]i32 で、[]const i32 に変換される。どんな長さでも渡せる。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var arr = [_]u8{ 1, 2, 3 };\nfor (&arr) |*x| x.* += 1;\nstd.debug.print("{any}\\n", .{arr});',
      options: ["{ 2, 3, 4 }", "{ 1, 2, 3 }", NO_CE],
      answer: 0,
      output: "{ 2, 3, 4 }",
      check: { compiles: true, stdout: "{ 2, 3, 4 }" },
      explain: L("|*x| captures a pointer to each element; x.* += 1 writes into arr.", "|*x| captura un puntero a cada elemento; x.* += 1 escribe en arr.", "|*x| は各要素へのポインタ。x.* += 1 で arr に書きこむ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "var arr = [_]u8{ 1, 2 };\nfor (arr) |x| {\n    x += 1;\n}\n_ = &arr;",
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("A plain |x| capture is a constant copy: cannot assign to constant. Use &arr and |*x|.", "Una captura |x| simple es una copia constante: cannot assign to constant. Usa &arr y |*x|.", "ただの |x| は定数のコピー。cannot assign to constant。&arr と |*x| を使おう。"),
    },
    {
      kind: "pick",
      prompt: L("Double every element", "Duplica cada elemento", "全要素を2倍にしよう"),
      code: 'var arr = [_]u8{ 1, 2, 3 };\nfor (&arr) |___| x.* *= 2;\nstd.debug.print("{any}\\n", .{arr});',
      options: ["*x", "x"],
      answer: 0,
      check: { compiles: true, stdout: "{ 2, 4, 6 }", wrongFail: true },
      explain: L("Only |*x| gives a pointer, and only a pointer has x.* to write through.", "Solo |*x| da un puntero, y solo un puntero tiene x.* para escribir.", "|*x| だけがポインタをくれる。x.* で書けるのはポインタだけ。"),
      win: [{ t: "print", text: "{ 2, 4, 6 }" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print xp: 50", "Arréglalo: debe imprimir xp: 50", "直そう：xp: 50 と表示させて"),
      starter: 'const std = @import("std");\n\nfn addXp(xp: *u32, n: u32) void {\n    var local = xp.*;\n    local += n;\n}\n\npub fn main() void {\n    var xp: u32 = 0;\n    addXp(&xp, 50);\n    std.debug.print("xp: {d}\\n", .{xp});\n}\n',
      solution: 'const std = @import("std");\n\nfn addXp(xp: *u32, n: u32) void {\n    xp.* += n;\n}\n\npub fn main() void {\n    var xp: u32 = 0;\n    addXp(&xp, 50);\n    std.debug.print("xp: {d}\\n", .{xp});\n}\n',
      expect: "xp: 50",
      fallback: [String.raw`xp\.\*\s*\+=\s*n`, String.raw`xp\.\*\s*=\s*xp\.\*\s*\+\s*n`, String.raw`xp\.\*\s*=\s*local`],
      explain: L("var local = xp.* copies the value; changing local is lost. Write through the pointer: xp.* += n.", "var local = xp.* copia el valor; cambiar local se pierde. Escribe por el puntero: xp.* += n.", "var local = xp.* は値のコピー。ポインタ経由で書こう：xp.* += n。"),
    },
  ],
};

// ─── 3.4 Slices and sentinels ──────────────────────────────────────────────
const sentinels: LessonDef = {
  slug: "slices-and-sentinels",
  title: L("Windows onto chests", "Ventanas a cofres", "宝箱の窓"),
  concept: "slices",
  mode: "lesson",
  xp: 75,
  enemy: "zig/overflow-spark",
  enemyName: L("WINDOW SPARK", "CHISPA VENTANA", "窓のスパーク"),
  beats: [
    say(L(
      "s[a..b] opens a window from a up to, but NOT including, b. s[a..] runs to the end. Windows are bounds-checked.",
      "s[a..b] abre una ventana desde a hasta b, SIN incluir b. s[a..] llega al final. Las ventanas se revisan.",
      "s[a..b] は a から b の手前までの窓。s[a..] は最後まで。範囲は実行時にチェックされる。",
    )),
    {
      kind: "act",
      prompt: L("Open windows on the word, then one too wide", "Abre ventanas en la palabra, luego una muy ancha", "単語に窓を開け、最後は広すぎる窓を"),
      steps: [
        { label: L("WORD", "PALABRA", "単語"), line: 'const s: []const u8 = "forge";', effects: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "s", value: "forge" }] },
        { label: L("s[0..2]", "s[0..2]", "s[0..2]"), line: 'std.debug.print("{s}\\n", .{s[0..2]});', effects: [{ t: "lend", to: "hero" }, { t: "print", text: "fo" }], output: "fo" },
        { label: L("s[2..]", "s[2..]", "s[2..]"), line: 'std.debug.print("{s}\\n", .{s[2..]});', effects: [{ t: "lend", to: "hero" }, { t: "print", text: "rge" }], output: "rge" },
        {
          label: L("TOO WIDE", "MUY ANCHA", "広すぎ"),
          line: 'std.debug.print("{s}\\n", .{s[0..end]}); // end = 9',
          effects: [{ t: "enter", actor: "enemy" }, { t: "shake" }, { t: "banner", text: L("PANIC!", "¡PANIC!", "パニック！") }],
          error: {
            compiler: "panic: index out of bounds: index 9, len 5",
            plain: L("The window ran past the end of the word. Zig rings the bell instead of reading junk.", "La ventana se pasó del final de la palabra. Zig da la alarma en vez de leer basura.", "窓が単語の終わりをこえた。Zig はゴミを読まずにベルを鳴らす。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const s: []const u8 = "forge";\nstd.debug.print("{s} {s} {s}\\n", .{ s[0..2], s[2..], s[1..4] });',
      options: ["fo rge org", "for rge orge", "fo orge org"],
      answer: 0,
      output: "fo rge org",
      check: { compiles: true, stdout: "fo rge org" },
      explain: L("The end index is excluded: [0..2] is f,o; [1..4] is o,r,g.", "El índice final se excluye: [0..2] es f,o; [1..4] es o,r,g.", "終わりの番号はふくまない。[0..2] は f,o、[1..4] は o,r,g。"),
      win: [{ t: "print", text: "fo rge org" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'const s: []const u8 = "abc";\nvar end: usize = 5;\n_ = &end;\nstd.debug.print("{s}\\n", .{s[0..end]});',
      options: [PANICS, "abc", NO_CE],
      answer: 0,
      check: { compiles: true, throws: "out of bounds" },
      explain: L("end is only known at run time, so the check happens then: 5 is past len 3, so it panics.", "end solo se conoce al ejecutar, así que se revisa entonces: 5 pasa de len 3 y hace panic.", "end は実行時にしかわからないのでその時チェック。5 は len 3 をこえて panic。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Some slices end in a SENTINEL: [:0]const u8 has a 0 byte after the last item, like C strings. String literals have one.",
      "Algunos slices terminan en un CENTINELA: [:0]const u8 tiene un byte 0 tras el último, como en C. Los literales lo tienen.",
      "番兵つきスライスもある。[:0]const u8 は最後のあとに 0 がある（C の文字列と同じ）。文字列リテラルにもある。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const z: [:0]const u8 = "hey";\nstd.debug.print("{d} {d}\\n", .{ z.len, z[3] });',
      options: ["3 0", "4 0", PANICS],
      answer: 0,
      output: "3 0",
      check: { compiles: true, stdout: "3 0" },
      explain: L("len counts 3 letters. The sentinel sits at index len and is readable: it is 0.", "len cuenta 3 letras. El centinela está en el índice len y se puede leer: es 0.", "len は3文字。番兵は len 番にあって読める。値は 0。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const lit = "abc";\nvar i: usize = 3;\n_ = &i;\nstd.debug.print("{d}\\n", .{lit[i]});',
      options: ["0", PANICS, "99"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("A literal is *const [3:0]u8, so index 3 is the sentinel 0, not out of bounds.", "Un literal es *const [3:0]u8, así que el índice 3 es el centinela 0, no está fuera de rango.", "リテラルは *const [3:0]u8。3番は番兵の 0 で、範囲外ではない。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'const s: []u8 = "hi";\n_ = s;',
      options: [YES, NO_CE],
      answer: 1,
      check: { compiles: false },
      explain: L("Literals are read-only. []u8 would allow writes, so it must be []const u8.", "Los literales son de solo lectura. []u8 permitiría escribir; debe ser []const u8.", "リテラルは読みとり専用。[]u8 だと書けてしまうので []const u8 にする。"),
    },
    say(L(
      "std.mem is the toolbox for slices: eql compares, indexOf finds, trim cuts, count counts, sort sorts.",
      "std.mem es la caja de herramientas de slices: eql compara, indexOf busca, trim recorta, count cuenta, sort ordena.",
      "std.mem はスライスの道具箱。eql で比較、indexOf で検索、trim で切りとり、count で数え、sort で並べる。",
    )),
    {
      kind: "pick",
      prompt: L("Compare the two words", "Compara las dos palabras", "2つの単語を比べよう"),
      code: 'const a: []const u8 = "ice";\nconst b: []const u8 = "ice";\nstd.debug.print("{}\\n", .{std.mem.___(u8, a, b)});',
      options: ["eql", "equal", "same"],
      answer: 0,
      check: { compiles: true, stdout: "true", wrongFail: true },
      explain: L("std.mem.eql(u8, a, b) compares the bytes. == on slices is not allowed.", "std.mem.eql(u8, a, b) compara los bytes. == no se permite con slices.", "std.mem.eql(u8, a, b) でバイトを比べる。スライスに == は使えない。"),
      win: [{ t: "print", text: "true" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std.debug.print("{any} {any}\\n", .{ std.mem.indexOf(u8, "forge", "rg"), std.mem.indexOfScalar(u8, "forge", \'z\') });',
      options: ["2 null", "2 -1", "3 null"],
      answer: 0,
      output: "2 null",
      check: { compiles: true, stdout: "2 null" },
      explain: L("indexOf returns ?usize: the position, or null when nothing is found.", "indexOf devuelve ?usize: la posición, o null si no encuentra nada.", "indexOf は ?usize を返す。位置か、見つからなければ null。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std.debug.print("[{s}]\\n", .{std.mem.trim(u8, "  hi  ", " ")});',
      options: ["[hi]", "[  hi  ]", "[hi  ]"],
      answer: 0,
      output: "[hi]",
      check: { compiles: true, stdout: "[hi]" },
      explain: L("trim cuts the listed bytes from both ends. It returns a smaller window, no copy.", "trim recorta los bytes indicados en ambos extremos. Devuelve una ventana menor, sin copiar.", "trim は両はしから指定のバイトを切る。コピーせず小さな窓を返す。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var xs = [_]i32{ 5, 2, 9, 1 };\nstd.mem.sort(i32, &xs, {}, std.sort.asc(i32));\nstd.debug.print("{any}\\n", .{xs});',
      options: ["{ 1, 2, 5, 9 }", "{ 9, 5, 2, 1 }", "{ 5, 2, 9, 1 }"],
      answer: 0,
      output: "{ 1, 2, 5, 9 }",
      check: { compiles: true, stdout: "{ 1, 2, 5, 9 }" },
      explain: L("std.mem.sort sorts the array in place through the slice &xs; asc means smallest first.", "std.mem.sort ordena el array en su lugar mediante el slice &xs; asc es de menor a mayor.", "std.mem.sort は &xs を通して配列をその場で並べる。asc は小さい順。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var buf: [32]u8 = undefined;\nconst msg = try std.fmt.bufPrint(&buf, "hp={d}", .{42});\nstd.debug.print("{s} {d}\\n", .{ msg, msg.len });',
      options: ["hp=42 5", "hp=42 32", NO_CE],
      answer: 0,
      output: "hp=42 5",
      check: { compiles: true, stdout: "hp=42 5" },
      explain: L("bufPrint writes into your stack buffer and returns the slice it filled: 5 bytes.", "bufPrint escribe en tu buffer de pila y devuelve el slice que llenó: 5 bytes.", "bufPrint はスタックのバッファに書き、うめた部分のスライス（5バイト）を返す。"),
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print first: [iggi]", "Arréglalo: debe imprimir first: [iggi]", "直そう：first: [iggi] と表示させて"),
      starter: 'const std = @import("std");\n\npub fn main() void {\n    const line = "iggi forge";\n    const space = std.mem.indexOfScalar(u8, line, \' \') orelse line.len;\n    const first = line[0 .. space - 1];\n    std.debug.print("first: [{s}]\\n", .{first});\n}\n',
      solution: 'const std = @import("std");\n\npub fn main() void {\n    const line = "iggi forge";\n    const space = std.mem.indexOfScalar(u8, line, \' \') orelse line.len;\n    const first = line[0..space];\n    std.debug.print("first: [{s}]\\n", .{first});\n}\n',
      expect: "first: [iggi]",
      fallback: [String.raw`line\[\s*0\s*\.\.\s*space\s*\]`, String.raw`line\[\s*0\s*\.\.\s*4\s*\]`],
      explain: L("The end index is already excluded, so space - 1 cut one letter too many. Use line[0..space].", "El índice final ya se excluye, así que space - 1 cortaba una letra de más. Usa line[0..space].", "終わりの番号はもともとふくまない。space - 1 だと1文字多く切れる。line[0..space] に。"),
    },
  ],
};

// ─── Boss ──────────────────────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "mountain-boss",
  title: L("The Imp in the Mountain", "El diablillo de la montaña", "山の小鬼"),
  concept: "structs",
  mode: "boss",
  xp: 180,
  enemy: "zig/undefined-imp",
  enemyName: L("MOUNTAIN IMP", "DIABLILLO MONTÉS", "山の小鬼"),
  beats: [
    enemySays(L(
      "Hee hee! I hide in copies, wrong forms and windows too wide. Can you see where memory really lives?",
      "¡Ji ji! Me escondo en copias, formas erróneas y ventanas muy anchas. ¿Ves dónde vive de verdad la memoria?",
      "ヒヒッ！コピーや、ちがう姿や、広すぎる窓にかくれるぞ。メモリが本当にどこにあるか見えるか？",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: 'const Point = struct { x: i32, y: i32 = 0 };\nconst p = Point{ .x = 1, .y = 2 };\nvar q = p;\nq.y = 50;\nstd.debug.print("{d} {d}\\n", .{ p.y, q.y });', options: ["2 50", "50 50", "2 2"], answer: 0, output: "2 50", check: { compiles: true, stdout: "2 50" }, explain: L("var q = p copies the whole struct. p keeps y = 2.", "var q = p copia el struct entero. p conserva y = 2.", "var q = p は struct 全体のコピー。p の y は 2 のまま。") },
    { kind: "predict", time: 15, prompt: COMPILES, code: zmain(POINT, "const p = Point{ .x = 1 };\np.moveRight(1);"), options: [YES, NO_CE], answer: 1, check: { compiles: false }, explain: L("A *Point method needs a var: &p of a const is *const Point.", "Un método *Point necesita un var: &p de un const es *const Point.", "*Point のメソッドには var が必要。const の &p は *const Point。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "const Dir = enum { north, east, south, west };\nconst d: Dir = .east;\nswitch (d) {\n    .north => {},\n    .east => {},\n}", options: [YES, NO_CE], answer: 1, check: { compiles: false }, explain: L("Every tag must be handled, or add else.", "Hay que manejar cada tag, o agregar else.", "すべてのタグを書くか else を足す。") },
    { kind: "predict", time: 15, prompt: HAPPENS, code: 'const Shape = union(enum) { circle: f32, rect: struct { w: f32, h: f32 } };\nvar s: Shape = .{ .circle = 1.5 };\n_ = &s;\nstd.debug.print("{d}\\n", .{s.rect.w});', options: [PANICS, "1.5", NO_CE], answer: 0, check: { compiles: true, throws: "access of union field 'rect' while field 'circle' is active" }, explain: L("Only the active field may be read. switch on the union instead.", "Solo se puede leer el campo activo. Mejor haz switch sobre la unión.", "読めるのは今のフィールドだけ。switch を使おう。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'var arr = [_]i32{ 1, 2, 3, 4, 5 };\nvar lo: usize = 1;\n_ = &lo;\nconst a = arr[1..4];\nconst b = arr[lo..4];\nstd.debug.print("{} {}\\n", .{ @TypeOf(a), @TypeOf(b) });', options: ["*[3]i32 []i32", "[]i32 []i32", "*[3]i32 *[3]i32"], answer: 0, output: "*[3]i32 []i32", check: { compiles: true, stdout: "*[3]i32 []i32" }, explain: L("Comptime bounds: pointer to array. Runtime bounds: slice.", "Límites al compilar: puntero a array. En ejecución: slice.", "コンパイル時の範囲は配列ポインタ、実行時はスライス。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "var arr = [_]u8{ 1, 2 };\nfor (arr) |x| {\n    x += 1;\n}\n_ = &arr;", options: [YES, NO_CE], answer: 1, check: { compiles: false }, explain: L("Loop captures are constants. Use &arr and |*x| to write.", "Las capturas del loop son constantes. Usa &arr y |*x| para escribir.", "ループのキャプチャは定数。&arr と |*x| で書こう。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'const lit = "abc";\nvar i: usize = 3;\n_ = &i;\nstd.debug.print("{d}\\n", .{lit[i]});', options: ["0", PANICS, "99"], answer: 0, output: "0", check: { compiles: true, stdout: "0" }, explain: L("Literals end in a 0 sentinel at index len.", "Los literales terminan en un centinela 0 en el índice len.", "リテラルは len 番に番兵 0 がある。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: 'const s: []u8 = "hi";\n_ = s;', options: [YES, NO_CE], answer: 1, check: { compiles: false }, explain: L("Literals are constant: use []const u8.", "Los literales son constantes: usa []const u8.", "リテラルは定数。[]const u8 を使う。") },
    { kind: "predict", time: 18, prompt: PRINT, code: zmain("fn bump(xs: []i32) void {\n    for (xs) |*x| x.* += 1;\n}", 'var arr = [_]i32{ 1, 2, 3, 4 };\nbump(arr[1..3]);\nstd.debug.print("{any}\\n", .{arr});'), options: ["{ 1, 3, 4, 4 }", "{ 2, 3, 4, 5 }", "{ 1, 2, 3, 4 }"], answer: 0, output: "{ 1, 3, 4, 4 }", check: { compiles: true, stdout: "{ 1, 3, 4, 4 }" }, explain: L("The window [1..3] covers only arr[1] and arr[2]; those two get bumped.", "La ventana [1..3] cubre solo arr[1] y arr[2]; esos dos suben.", "窓 [1..3] は arr[1] と arr[2] だけ。その2つが増える。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'const Item = union(enum) { coins: u32, key };\nconst items = [_]Item{ .{ .coins = 5 }, .key, .{ .coins = 7 } };\nvar total: u32 = 0;\nfor (items) |it| switch (it) {\n    .coins => |c| total += c,\n    .key => total += 100,\n};\nstd.debug.print("{d}\\n", .{total});', options: ["112", "12", "107"], answer: 0, output: "112", check: { compiles: true, stdout: "112" }, explain: L("A field with no type (key) carries no payload. 5 + 100 + 7 = 112.", "Un campo sin tipo (key) no lleva valor. 5 + 100 + 7 = 112.", "型のないフィールド key は値をもたない。5 + 100 + 7 = 112。") },
    { kind: "type", time: 15, prompt: L("Count the a's", "Cuenta las a", "a の数を数えよう"), code: 'std.debug.print("{d}\\n", .{std.mem.___(u8, "banana", "a")});', answer: "count", check: { compiles: true, stdout: "3" }, explain: L("std.mem.count counts how many times the needle appears.", "std.mem.count cuenta cuántas veces aparece la aguja.", "std.mem.count は探す文字列が何回出るか数える。") },
    enemySays(L(
      "Eek! You saw through every copy and window. Up in Comptime Tower, the Leak Jelly drips from the pipes...",
      "¡Iiih! Viste a través de cada copia y ventana. Arriba en Comptime Tower, la Leak Jelly gotea de las tuberías...",
      "ひぇっ！コピーも窓も見ぬかれた。コンプタイムの塔では、リークゼリーがパイプからしたたっているぞ…",
    )),
  ],
};

export const structMountain: RegionDef = {
  slug: "struct-mountain",
  name: L("Struct Mountain", "Monte Struct", "ストラクト山"),
  subtitle: L("structs · unions · pointers · slices", "structs · uniones · punteros · slices", "構造体・共用体・ポインタ・スライス"),
  theme: "mountain",
  lessons: [structs, enums, pointers, sentinels, boss],
};
