import type { ExamDef } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";
import { juniorTasks, midTasks, seniorTasks } from "./tasks.ts";
import { juniorTraceDebug, midTraceDebug, seniorTraceDebug } from "./trace-debug.ts";

// Entry exams that simulate company screenings for three.js roles.
// Topics, levels and bank sizes follow docs/research/webgl-threejs-curriculum.md ("Entry exams" → three.js moon)
// and docs/research/webgl-threejs-hiring-assessments.md. Snippets run three r186 without a GPU: WebGLRenderer,
// loaders and addons appear only in type-check-only claims (`declare const renderer: THREE.WebGLRenderer`).
// Verify with `npm run content:verify -- --lang=threejs --only=exam:`.

const code = (...lines: string[]) => ["import * as THREE from \"three\";", ...lines].join("\n");

const YES = L("Yes", "Sí", "はい");
const PRINTS = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile (tsc --strict)?", "¿Compila (tsc --strict)?", "コンパイルは通る？(strict)");
const BOX = "new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial())";
const RAY = "new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, 10), new THREE.Vector3(0, 0, -1))";

export const exams: ExamDef[] = [
  // ─── JUNIOR ───────────────────────────────────────────────────────────────
  {
    slug: "junior",
    level: "junior",
    title: L("Junior three.js Developer", "three.js Developer Junior", "ジュニア three.js 開発者"),
    description: L(
      "Skills test for a junior web 3D role: scene, camera, materials, transforms, scene graph, vectors, loop, shadows.",
      "Test para un puesto junior de 3D web: escena, cámara, materiales, transformaciones, grafo, vectores, bucle, sombras.",
      "ジュニア Web 3D 職の試験：シーン、カメラ、マテリアル、変換、シーングラフ、ベクトル、ループ、影。",
    ),
    count: 12,
    passPct: 70,
    secondsPerQuestion: 30,
    codeCount: 1,
    questions: [
      ...juniorTraceDebug,
      ...juniorTasks,
      // scene_basics ×3
      {
        topic: "scene_basics", difficulty: 1,
        kind: "pick",
        prompt: L("Which line draws the scene?", "¿Qué línea dibuja la escena?", "シーンを描く行は？"),
        code: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene, camera: THREE.PerspectiveCamera;", "___;"),
        options: ["renderer.render(scene, camera)", "scene.render(camera)", "camera.render(scene)"],
        answer: 0,
        check: { compiles: true, wrongFail: true },
        explain: L("The renderer paints a scene as seen from a camera. Scenes and cameras have no render method.", "El renderer pinta una escena vista desde una cámara. Escenas y cámaras no tienen método render.", "レンダラーがカメラから見たシーンを描く。シーンやカメラに render はないよ。"),
      },
      {
        topic: "scene_basics", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("const scene = new THREE.Scene();", "const mesh = new THREE.Mesh();", "scene.add(mesh);", "console.log(scene.children.length, mesh.parent === scene);"),
        options: ["1 true", "0 false", "1 false"],
        answer: 0,
        check: { compiles: true, stdout: "1 true" },
        explain: L("add puts the mesh in scene.children and sets its parent to the scene.", "add mete la malla en scene.children y pone a la escena como su parent.", "add でメッシュが scene.children に入り、parent がシーンになる。"),
      },
      {
        topic: "scene_basics", difficulty: 2,
        kind: "order",
        prompt: L("Order the steps to show a cube", "Ordena los pasos para mostrar un cubo", "立方体を表示する順に並べよう"),
        lines: ["const geometry = new THREE.BoxGeometry();", "const cube = new THREE.Mesh(geometry, material);", "scene.add(cube);", "renderer.render(scene, camera);"],
        check: {
          compiles: true,
          program: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene, camera: THREE.Camera, material: THREE.Material;", "const geometry = new THREE.BoxGeometry();", "const cube = new THREE.Mesh(geometry, material);", "scene.add(cube);", "renderer.render(scene, camera);"),
        },
        explain: L("Shape first, then the mesh, add it to the scene, and only then render what's on stage.", "Primero la forma, luego la malla, agrégala a la escena y solo entonces renderiza.", "形→メッシュ→シーンに追加→最後に描画。舞台にある物だけが描かれる。"),
      },
      // cameras ×3
      {
        topic: "cameras", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("const cam = new THREE.PerspectiveCamera();", "console.log(cam.fov, cam.aspect, cam.near, cam.far);"),
        options: ["50 1 0.1 2000", "75 1 0.1 1000", "45 1 1 100"],
        answer: 0,
        check: { compiles: true, stdout: "50 1 0.1 2000" },
        explain: L("Defaults: 50° vertical fov, aspect 1, near 0.1, far 2000. Real apps set aspect to width / height.", "Por defecto: fov vertical 50°, aspect 1, near 0.1, far 2000. En apps reales aspect = ancho / alto.", "初期値は fov 50°、aspect 1、near 0.1、far 2000。実際は aspect を幅 / 高さにする。"),
      },
      {
        topic: "cameras", difficulty: 1,
        kind: "pick",
        prompt: L("PerspectiveCamera's fov is…", "El fov de PerspectiveCamera es…", "PerspectiveCamera の fov は？"),
        code: "new THREE.PerspectiveCamera(fov, aspect, near, far);\n// fov is ___",
        options: [L("vertical, in degrees", "vertical, en grados", "縦方向、度"), L("horizontal, in radians", "horizontal, en radianes", "横方向、ラジアン")],
        answer: 0,
        explain: L("fov is the vertical field of view in degrees. Object rotations, by contrast, use radians.", "fov es el campo de visión vertical en grados. Las rotaciones de objetos, en cambio, usan radianes.", "fov は縦の視野角で単位は度。物体の回転はラジアンなので注意。"),
      },
      {
        topic: "cameras", difficulty: 2,
        kind: "type",
        prompt: L("Apply the new aspect", "Aplica el nuevo aspect", "新しい aspect を反映しよう"),
        code: code("const camera = new THREE.PerspectiveCamera(75, 1, 0.1, 1000);", "camera.aspect = 2;", "camera.___();", "console.log(camera.projectionMatrix.elements[0].toFixed(3));"),
        answer: "updateProjectionMatrix",
        check: { compiles: true, stdout: "0.652" },
        explain: L("Changing aspect, fov, near or far does nothing until updateProjectionMatrix() rebuilds the matrix.", "Cambiar aspect, fov, near o far no hace nada hasta que updateProjectionMatrix() rehace la matriz.", "aspect・fov・near・far を変えても、updateProjectionMatrix() まで行列は変わらない。"),
      },
      // materials ×3
      {
        topic: "materials", difficulty: 1,
        kind: "pick",
        prompt: L("No lights: which one still shows colour?", "Sin luces: ¿cuál muestra su color?", "ライトなしで色が見えるのは？"),
        code: code("const mat = new THREE.___({ color: 0xff0000 });"),
        options: ["MeshBasicMaterial", "MeshStandardMaterial", "MeshPhongMaterial"],
        answer: 0,
        check: { compiles: true },
        explain: L("MeshBasicMaterial ignores lighting. Standard and Phong react to lights and render black without them.", "MeshBasicMaterial ignora la luz. Standard y Phong reaccionan a la luz y sin ella se ven negros.", "MeshBasicMaterial は光を無視する。Standard と Phong は光が必要で、ないと真っ黒。"),
      },
      {
        topic: "materials", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const g = new THREE.BoxGeometry(1, 1, 1);", "console.log(g.attributes.position.count, g.index?.count);"),
        options: ["24 36", "8 12", "8 36"],
        answer: 0,
        check: { compiles: true, stdout: "24 36" },
        explain: L("Each face needs its own normals, so corners are repeated: 6 faces × 4 = 24 vertices, 12 triangles × 3 = 36 indices.", "Cada cara necesita sus normales, así que las esquinas se repiten: 6 × 4 = 24 vértices, 12 triángulos × 3 = 36 índices.", "面ごとに法線が要るので角が重複する。6面 × 4 = 24 頂点、12 三角形 × 3 = 36。"),
      },
      {
        topic: "materials", difficulty: 2,
        kind: "predict",
        prompt: COMPILES,
        code: code("const mat = new THREE.MeshBasicMaterial();", "mat.roughness = 0.5;"),
        options: [YES, L("No: Basic has no roughness", "No: Basic no tiene roughness", "いいえ：Basic に roughness はない")],
        answer: 1,
        check: { compiles: false },
        explain: L("TS2339: roughness belongs to MeshStandardMaterial (PBR). Basic is unlit and has no such property.", "TS2339: roughness es de MeshStandardMaterial (PBR). Basic no usa luz y no tiene esa propiedad.", "TS2339：roughness は MeshStandardMaterial（PBR）のもの。Basic にはない。"),
      },
      // transforms ×3
      {
        topic: "transforms", difficulty: 1,
        kind: "predict",
        prompt: COMPILES,
        code: code("const mesh = new THREE.Mesh();", "mesh.position = new THREE.Vector3(1, 2, 3);"),
        options: [YES, L("No: position is read-only", "No: position es de solo lectura", "いいえ：position は読み取り専用")],
        answer: 1,
        check: { compiles: false },
        explain: L("TS2540: position can't be replaced. Change it in place: mesh.position.set(1, 2, 3).", "TS2540: position no se puede reemplazar. Cámbiala en su lugar: mesh.position.set(1, 2, 3).", "TS2540：position は置きかえられない。mesh.position.set(1, 2, 3) で変えよう。"),
      },
      {
        topic: "transforms", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("console.log(THREE.MathUtils.radToDeg(Math.PI));"),
        options: ["180", "3.14", "90"],
        answer: 0,
        check: { compiles: true, stdout: "180" },
        explain: L("π radians is half a turn: 180°. Rotations in three.js are in radians.", "π radianes es media vuelta: 180°. Las rotaciones en three.js van en radianes.", "π ラジアンは半回転で 180°。three.js の回転はラジアンだよ。"),
      },
      {
        topic: "transforms", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code(`const a = ${BOX};`, "const b = a.clone();", "console.log(b.geometry === a.geometry, b.material === a.material, b.position === a.position);"),
        options: ["true true false", "false false false", "true true true"],
        answer: 0,
        check: { compiles: true, stdout: "true true false" },
        explain: L("clone() copies the transform but SHARES geometry and material. Changing the material changes both.", "clone() copia la transformación pero COMPARTE geometría y material. Cambiar el material cambia ambos.", "clone() は変換をコピーし、形とマテリアルは共有する。マテリアルを変えると両方変わる。"),
      },
      // scene_graph ×3
      {
        topic: "scene_graph", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("const parent = new THREE.Group();", "parent.position.x = 10;", "const kid = new THREE.Object3D();", "kid.position.x = 1;", "parent.add(kid);", "console.log(kid.getWorldPosition(new THREE.Vector3()).x, kid.position.x);"),
        options: ["11 1", "1 1", "11 11"],
        answer: 0,
        check: { compiles: true, stdout: "11 1" },
        explain: L("position is local to the parent; the world position adds the parent's 10.", "position es local al padre; la posición en el mundo suma el 10 del padre.", "position は親から見たローカル座標。ワールド座標は親の 10 が足される。"),
      },
      {
        topic: "scene_graph", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const p1 = new THREE.Group(), p2 = new THREE.Group();", "const c = new THREE.Object3D();", "p1.add(c);", "p2.add(c);", "console.log(p1.children.length, p2.children.length);"),
        options: ["0 1", "1 1", "1 0"],
        answer: 0,
        check: { compiles: true, stdout: "0 1" },
        explain: L("An object has ONE parent. add() removes it from its old parent first.", "Un objeto tiene UN solo padre. add() primero lo saca de su padre anterior.", "物体の親はひとつだけ。add() は先に元の親から外す。"),
      },
      {
        topic: "scene_graph", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const node = (name: string) => Object.assign(new THREE.Object3D(), { name });", "const root = node(\"root\"), a = node(\"a\"), b = node(\"b\"), c = node(\"c\");", "root.add(a, b);", "a.add(c);", "const names: string[] = [];", "root.traverse((o) => names.push(o.name));", "console.log(names.join(\",\"));"),
        options: ["root,a,c,b", "root,a,b,c", "c,a,b,root"],
        answer: 0,
        check: { compiles: true, stdout: "root,a,c,b" },
        explain: L("traverse is depth-first: a node, then all of its children, before moving to the next sibling.", "traverse es en profundidad: un nodo y todos sus hijos antes de pasar al siguiente hermano.", "traverse は深さ優先。ノードとその子を全部見てから次の兄弟へ進む。"),
      },
      // vectors ×3
      {
        topic: "vectors", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("console.log(new THREE.Vector3(3, 4, 0).length());"),
        options: ["5", "7", "25"],
        answer: 0,
        check: { compiles: true, stdout: "5" },
        explain: L("length is √(3² + 4² + 0²) = √25 = 5.", "length es √(3² + 4² + 0²) = √25 = 5.", "length は √(3² + 4² + 0²) = √25 = 5。"),
      },
      {
        topic: "vectors", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const a = new THREE.Vector3(1, 2, 3);", "const b = a;", "b.x = 9;", "console.log(a.x);"),
        options: ["9", "1", "undefined"],
        answer: 0,
        check: { compiles: true, stdout: "9" },
        explain: L("b = a copies the reference: one vector, two names. Use a.clone() for an independent copy.", "b = a copia la referencia: un vector, dos nombres. Usa a.clone() para una copia independiente.", "b = a は参照のコピー。ベクトルは1つで名前が2つ。別物にするなら a.clone()。"),
      },
      {
        topic: "vectors", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("const a = new THREE.Vector3(1, 1, 1);", "const b = new THREE.Vector3(1, 1, 1);", "console.log(a === b, a.equals(b));"),
        options: ["false true", "true true", "false false"],
        answer: 0,
        check: { compiles: true, stdout: "false true" },
        explain: L("=== compares identity: two different objects. equals() compares the x, y, z values.", "=== compara identidad: son dos objetos distintos. equals() compara los valores x, y, z.", "=== は同じ物かを比べる（別物）。equals() は x, y, z の値を比べる。"),
      },
      // render_loop ×2
      {
        topic: "render_loop", difficulty: 1,
        kind: "pick",
        prompt: L("Frame-rate independent movement", "Movimiento independiente de los fps", "fps に左右されない動き"),
        code: "declare const dt: number; // seconds since last frame\nconst speed = 3;\nlet x = 0;\nx += ___;",
        options: ["speed * dt", "speed"],
        answer: 0,
        check: { compiles: true },
        explain: L("x += speed moves more per second on faster screens. speed × dt is the same on all of them.", "x += speed avanza más por segundo en pantallas rápidas. speed × dt es igual en todas.", "x += speed は速い画面ほど進む。speed × dt ならどの画面でも同じ。"),
      },
      {
        topic: "render_loop", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const timer = new THREE.Timer();", "timer.update(2000);", "timer.update(2040);", "console.log(timer.getDelta());"),
        options: ["0.04", "40", "2.04"],
        answer: 0,
        check: { compiles: true, stdout: "0.04" },
        explain: L("update() takes timestamps in ms; getDelta() returns the seconds between the last two: 40 ms = 0.04 s.", "update() recibe marcas en ms; getDelta() da los segundos entre las dos últimas: 40 ms = 0.04 s.", "update() はミリ秒の時刻を受け取り、getDelta() は直近2回の差を秒で返す：40ms = 0.04秒。"),
      },
      // lights_shadows ×2
      {
        topic: "lights_shadows", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("const mesh = new THREE.Mesh();", "console.log(mesh.castShadow, mesh.receiveShadow);"),
        options: ["false false", "true true", "true false"],
        answer: 0,
        check: { compiles: true, stdout: "false false" },
        explain: L("Shadow flags start off. Turn on castShadow and receiveShadow only where needed.", "Las banderas de sombra empiezan apagadas. Enciende castShadow y receiveShadow solo donde haga falta.", "影のフラグは最初オフ。必要な所だけ castShadow と receiveShadow をオンに。"),
      },
      {
        topic: "lights_shadows", difficulty: 2,
        kind: "pick",
        prompt: L("Which light can't cast shadows?", "¿Qué luz no proyecta sombras?", "影を落とせないライトは？"),
        code: code("console.log(\"shadow\" in new THREE.___());"),
        options: ["AmbientLight", "DirectionalLight", "SpotLight"],
        answer: 0,
        check: { compiles: true, stdout: "false" },
        explain: L("AmbientLight lights everything evenly from nowhere, so it has no shadow. Directional and Spot do.", "AmbientLight ilumina todo parejo y sin origen, así que no tiene shadow. Directional y Spot sí.", "AmbientLight は全体を均一に照らし向きがないので shadow を持たない。"),
      },
    ],
  },

  // ─── MID ──────────────────────────────────────────────────────────────────
  {
    slug: "mid",
    level: "mid",
    title: L("Mid-level three.js Developer", "three.js Developer Semi-senior", "中級 three.js 開発者"),
    description: L(
      "Technical screen for a mid-level 3D role: transforms, rotations, loop, raycasting, assets, shadows, disposal, ecosystem.",
      "Entrevista técnica para un puesto 3D semi-senior: transformaciones, rotaciones, bucle, raycasting, recursos, sombras.",
      "中級 3D 職の技術面接：変換、回転、ループ、レイキャスト、アセット、影、解放、周辺ツール。",
    ),
    count: 14,
    passPct: 70,
    secondsPerQuestion: 40,
    codeCount: 2,
    questions: [
      ...midTraceDebug,
      ...midTasks,
      // cameras ×2
      {
        topic: "cameras", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const cam = new THREE.PerspectiveCamera(75, 16 / 9, 0.1, 1000);", "cam.aspect = 2;", "const before = cam.projectionMatrix.elements[0].toFixed(3);", "cam.updateProjectionMatrix();", "console.log(before, cam.projectionMatrix.elements[0].toFixed(3));"),
        options: ["0.733 0.652", "0.652 0.652", "0.733 0.733"],
        answer: 0,
        check: { compiles: true, stdout: "0.733 0.652" },
        explain: L("The matrix keeps the old 16/9 values until updateProjectionMatrix(): the stretched-resize bug.", "La matriz guarda los valores de 16/9 hasta updateProjectionMatrix(): el bug del resize estirado.", "updateProjectionMatrix() まで行列は 16/9 のまま。リサイズで画面が伸びるバグの原因。"),
      },
      {
        topic: "cameras", difficulty: 2,
        kind: "pick",
        prompt: L("Why cap the pixel ratio at 2?", "¿Por qué limitar el pixel ratio a 2?", "pixel ratio を2までにする理由は？"),
        code: "renderer.setPixelRatio(Math.min(devicePixelRatio, 2));\n// why? ___",
        options: [L("Pixels grow with the square", "Los píxeles crecen al cuadrado", "画素数が2乗で増える"), L("Textures break above 2", "Las texturas fallan sobre 2", "2超でテクスチャが壊れる")],
        answer: 0,
        explain: L("Ratio 3 draws 9× the pixels of ratio 1. Fragment cost explodes on phones for little visible gain.", "Un ratio 3 dibuja 9× los píxeles del ratio 1. El costo por fragmento explota en móviles sin mejora visible.", "比率3は比率1の9倍の画素を描く。スマホでは負荷が激増するのに見た目はほぼ同じ。"),
      },
      // scene_graph ×3
      {
        topic: "scene_graph", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const g = new THREE.Group();", "g.position.set(10, 0, 0);", "g.updateMatrixWorld();", "const c = new THREE.Object3D();", "c.position.set(5, 0, 0);", "g.attach(c);", "console.log(c.position.x);"),
        options: ["-5", "5", "15"],
        answer: 0,
        check: { compiles: true, stdout: "-5" },
        explain: L("attach keeps the world position (5), so the local position becomes 5 - 10 = -5.", "attach conserva la posición en el mundo (5), así que la local pasa a 5 - 10 = -5.", "attach はワールド座標 5 を保つ。だからローカルは 5 - 10 = -5。"),
      },
      {
        topic: "scene_graph", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const p = new THREE.Group();", "p.position.x = 10;", "p.scale.set(2, 2, 2);", "const kid = new THREE.Object3D();", "kid.position.x = 1;", "p.add(kid);", "console.log(kid.getWorldPosition(new THREE.Vector3()).x);"),
        options: ["12", "11", "22"],
        answer: 0,
        check: { compiles: true, stdout: "12" },
        explain: L("The parent scales the child's local offset first (1 × 2), then moves it: 10 + 2 = 12.", "El padre escala el desplazamiento local del hijo (1 × 2) y luego lo mueve: 10 + 2 = 12.", "親はまず子のローカル位置を拡大（1 × 2）、それから移動：10 + 2 = 12。"),
      },
      {
        topic: "scene_graph", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code("const hero = new THREE.Group();", "hero.position.x = 10;", "hero.updateMatrixWorld();", "const a = new THREE.Object3D(), b = new THREE.Object3D();", "a.position.x = 12; b.position.x = 12;", "hero.add(a);", "hero.attach(b);", "const wx = (o: THREE.Object3D) => o.getWorldPosition(new THREE.Vector3()).x;", "console.log(wx(a), wx(b));"),
        options: ["22 12", "12 12", "22 22"],
        answer: 0,
        check: { compiles: true, stdout: "22 12" },
        explain: L("add keeps the LOCAL x = 12, so it lands at 22. attach keeps the WORLD x = 12.", "add conserva la x LOCAL = 12, así que queda en 22. attach conserva la x del MUNDO = 12.", "add はローカル x = 12 を保つので 22 に。attach はワールド x = 12 を保つ。"),
      },
      // vectors ×2
      {
        topic: "vectors", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const v = new THREE.Vector3(1, 1, 1);", "const r = v.add(new THREE.Vector3(1, 0, 0));", "console.log(v.x, r === v);"),
        options: ["2 true", "1 false", "2 false"],
        answer: 0,
        check: { compiles: true, stdout: "2 true" },
        explain: L("Vector3 methods mutate this and return it for chaining. Clone first to keep the original.", "Los métodos de Vector3 mutan this y lo devuelven para encadenar. Clona antes para conservar el original.", "Vector3 のメソッドは自分を変えて自分を返す。元を残すなら先に clone()。"),
      },
      {
        topic: "vectors", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const x = new THREE.Vector3(1, 0, 0);", "const y = new THREE.Vector3(0, 1, 0);", "const c = x.clone().cross(y);", "console.log(x.dot(y), c.x, c.y, c.z);"),
        options: ["0 0 0 1", "1 0 0 1", "0 0 0 -1"],
        answer: 0,
        check: { compiles: true, stdout: "0 0 0 1" },
        explain: L("Perpendicular vectors have dot 0. X × Y = Z in a right-handed system; Y × X would give -Z.", "Vectores perpendiculares tienen dot 0. X × Y = Z en un sistema diestro; Y × X daría -Z.", "直交するベクトルの内積は 0。右手系では X × Y = Z、Y × X なら -Z。"),
      },
      // rotations ×3
      {
        topic: "rotations", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const o = new THREE.Object3D();", "o.rotation.y = Math.PI / 2;", "console.log(o.quaternion.y.toFixed(3), o.quaternion.w.toFixed(3));"),
        options: ["0.707 0.707", "1.571 0.000", "0.000 1.000"],
        answer: 0,
        check: { compiles: true, stdout: "0.707 0.707" },
        explain: L("rotation and quaternion stay in sync. 90° about Y is (0, sin 45°, 0, cos 45°).", "rotation y quaternion se mantienen sincronizados. 90° sobre Y es (0, sin 45°, 0, cos 45°).", "rotation と quaternion は連動する。Y軸90°は (0, sin45°, 0, cos45°)。"),
      },
      {
        topic: "rotations", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code("const T = new THREE.Matrix4().makeTranslation(10, 0, 0);", "const S = new THREE.Matrix4().makeScale(2, 2, 2);", "const px = (m: THREE.Matrix4) => new THREE.Vector3(1, 0, 0).applyMatrix4(m).x;", "console.log(px(T.clone().multiply(S)), px(T.clone().premultiply(S)));"),
        options: ["12 22", "22 12", "12 12"],
        answer: 0,
        check: { compiles: true, stdout: "12 22" },
        explain: L("T × S scales first, then moves: 1 × 2 + 10 = 12. premultiply gives S × T: (1 + 10) × 2 = 22.", "T × S escala primero y luego mueve: 1 × 2 + 10 = 12. premultiply da S × T: (1 + 10) × 2 = 22.", "T × S は拡大してから移動：1 × 2 + 10 = 12。premultiply は S × T：(1 + 10) × 2 = 22。"),
      },
      {
        topic: "rotations", difficulty: 2,
        kind: "pick",
        prompt: L("Gimbal lock is…", "El gimbal lock es…", "ジンバルロックとは？"),
        code: "// Euler angles, two axes line up: ___",
        options: [L("a lost rotation axis", "un eje de rotación perdido", "回転軸がひとつ失われる"), L("a WebGL error", "un error de WebGL", "WebGL のエラー")],
        answer: 0,
        explain: L("When two Euler axes align, one degree of freedom is lost. Quaternions don't suffer from it.", "Cuando dos ejes de Euler se alinean, se pierde un grado de libertad. Los cuaterniones no lo sufren.", "オイラー角の2軸が重なると自由度が1つ消える。クォータニオンなら起きない。"),
      },
      // render_loop ×2
      {
        topic: "render_loop", difficulty: 2,
        kind: "predict",
        prompt: L("Fixed 1/60 s physics steps run:", "Pasos de física de 1/60 s que corren:", "1/60秒の物理ステップは何回？"),
        code: "let acc = 0.06, steps = 0;\nconst STEP = 1 / 60;\nwhile (acc >= STEP) { acc -= STEP; steps++; }\nconsole.log(steps);",
        options: ["3", "4", "1"],
        answer: 0,
        check: { compiles: true, stdout: "3" },
        explain: L("An accumulator runs physics in fixed steps: 0.06 s holds three 1/60 s steps and keeps the rest.", "Un acumulador corre la física en pasos fijos: 0.06 s contiene tres pasos de 1/60 s y guarda el resto.", "蓄積方式で物理を固定刻みに。0.06秒に1/60秒が3回入り、残りは持ちこす。"),
      },
      {
        topic: "render_loop", difficulty: 2,
        kind: "order",
        prompt: L("Order one frame", "Ordena un frame", "1フレームを並べよう"),
        lines: ["timer.update(time);", "const dt = timer.getDelta();", "mesh.rotation.y += dt;", "renderer.render(scene, camera);"],
        check: {
          compiles: true,
          program: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene, camera: THREE.Camera, mesh: THREE.Mesh;", "const timer = new THREE.Timer();", "renderer.setAnimationLoop((time) => {", "  timer.update(time);", "  const dt = timer.getDelta();", "  mesh.rotation.y += dt;", "  renderer.render(scene, camera);", "});"),
        },
        explain: L("Tick the timer once, read dt, update the world, then render it.", "Avanza el timer una vez, lee dt, actualiza el mundo y luego renderiza.", "タイマーを1回進め、dt を読み、世界を更新してから描く。"),
      },
      // raycasting ×3
      {
        topic: "raycasting", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: "const ndcY = (py: number, h: number) => -(py / h) * 2 + 1;\nconsole.log(ndcY(0, 600), ndcY(600, 600));",
        options: ["1 -1", "-1 1", "0 1"],
        answer: 0,
        check: { compiles: true, stdout: "1 -1" },
        explain: L("Screen y grows down, NDC y grows up: the top pixel row is +1, the bottom is -1.", "La y de pantalla crece hacia abajo y la de NDC hacia arriba: la fila superior es +1, la inferior -1.", "画面の y は下向き、NDC の y は上向き。上端は +1、下端は -1。"),
      },
      {
        topic: "raycasting", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const group = new THREE.Group();", `group.add(${BOX});`, "const scene = new THREE.Scene();", "scene.add(group);", "scene.updateMatrixWorld();", `const rc = ${RAY};`, "console.log(rc.intersectObjects(scene.children).length, rc.intersectObjects(scene.children, false).length);"),
        options: ["1 0", "1 1", "0 0"],
        answer: 0,
        check: { compiles: true, stdout: "1 0" },
        explain: L("recursive defaults to true, so meshes inside groups (like a loaded model) are found. false checks the top level only.", "recursive es true por defecto, así encuentra mallas dentro de grupos (como un modelo cargado). false revisa solo el nivel superior.", "recursive の初期値は true。グループ内のメッシュも見つかる。false だと最上位だけ。"),
      },
      {
        topic: "raycasting", difficulty: 3,
        kind: "predict",
        prompt: L("Hits before and after the update?", "¿Impactos antes y después de actualizar?", "更新の前と後の当たり数は？"),
        code: code(`const box = ${BOX};`, "box.position.x = 3;", `const rc = ${RAY};`, "const before = rc.intersectObject(box).length;", "box.updateMatrixWorld();", "console.log(before, rc.intersectObject(box).length);"),
        options: ["1 0", "0 0", "1 1"],
        answer: 0,
        check: { compiles: true, stdout: "1 0" },
        explain: L("Raycasting reads matrixWorld, not position. Until it's updated, the box is still hit at x = 0.", "El raycasting lee matrixWorld, no position. Hasta actualizarla, la caja se sigue tocando en x = 0.", "レイキャストは position ではなく matrixWorld を読む。更新前は x = 0 で当たる。"),
      },
      // assets_color ×3
      {
        topic: "assets_color", difficulty: 1,
        kind: "predict",
        prompt: PRINTS,
        code: code("console.log(new THREE.Texture().colorSpace === THREE.NoColorSpace);"),
        options: ["true", "false"],
        answer: 0,
        check: { compiles: true, stdout: "true" },
        explain: L("Textures start with no colour space. Tag colour maps as sRGB yourself; glTF does it for you.", "Las texturas empiezan sin espacio de color. Marca tú los mapas de color como sRGB; glTF lo hace solo.", "テクスチャは色空間なしで始まる。色テクスチャは自分で sRGB に。glTF は自動。"),
      },
      {
        topic: "assets_color", difficulty: 2,
        kind: "pick",
        prompt: L("A loaded photo looks washed out. Fix:", "Una foto cargada se ve deslavada. Arreglo:", "写真が白っぽい。直し方は？"),
        code: code("const photo = new THREE.TextureLoader().load(\"/photo.jpg\");", "photo.colorSpace = ___;"),
        options: ["THREE.SRGBColorSpace", "THREE.NoColorSpace"],
        answer: 0,
        check: { compiles: true },
        explain: L("The image is sRGB-encoded. Without the tag three.js treats it as linear and it looks pale.", "La imagen está codificada en sRGB. Sin la marca, three.js la trata como lineal y se ve pálida.", "画像は sRGB で保存されている。指定しないと linear 扱いになり色が薄くなる。"),
      },
      {
        topic: "assets_color", difficulty: 2,
        kind: "pick",
        prompt: L("What do you add to the scene?", "¿Qué agregas a la escena?", "シーンに追加するのは？"),
        code: code("import { GLTFLoader } from \"three/addons/loaders/GLTFLoader.js\";", "const scene = new THREE.Scene();", "const gltf = await new GLTFLoader().loadAsync(\"/robot.glb\");", "scene.add(___);"),
        options: ["gltf.scene", "gltf", "gltf.meshes"],
        answer: 0,
        check: { compiles: true, wrongFail: true },
        explain: L("loadAsync resolves to a gltf object (scene, animations, cameras…). gltf.scene is the Group to add.", "loadAsync da un objeto gltf (scene, animations, cameras…). gltf.scene es el Group a agregar.", "loadAsync は gltf（scene・animations など）を返す。追加するのは gltf.scene。"),
      },
      // lights_shadows ×2
      {
        topic: "lights_shadows", difficulty: 2,
        kind: "pick",
        prompt: L("Which light has a shadow to tune?", "¿Qué luz tiene sombra que ajustar?", "影を調整できるライトは？"),
        code: code("const light = new THREE.___();", "light.shadow.mapSize.set(1024, 1024);"),
        options: ["SpotLight", "HemisphereLight"],
        answer: 0,
        check: { compiles: true, wrongFail: true },
        explain: L("HemisphereLight has no direction and no shadow (TS2339). Spot, Point and Directional lights do.", "HemisphereLight no tiene dirección ni shadow (TS2339). Spot, Point y Directional sí.", "HemisphereLight は向きも shadow もない（TS2339）。Spot・Point・Directional にはある。"),
      },
      {
        topic: "lights_shadows", difficulty: 2,
        kind: "pick",
        prompt: L("Everything a shadow needs", "Todo lo que necesita una sombra", "影に必要なものは？"),
        code: "// light.castShadow = true; and also ___",
        options: [L("shadowMap.enabled, mesh cast, floor receive", "shadowMap.enabled, malla cast, piso receive", "shadowMap・メッシュ cast・床 receive"), L("nothing else", "nada más", "ほかは不要")],
        answer: 0,
        explain: L("renderer.shadowMap.enabled, light.castShadow, mesh.castShadow and floor.receiveShadow: all four, all false by default.", "renderer.shadowMap.enabled, light.castShadow, mesh.castShadow y floor.receiveShadow: los cuatro, todos en false por defecto.", "shadowMap.enabled、ライトとメッシュの castShadow、床の receiveShadow。4つとも初期値は false。"),
      },
      // disposal ×2
      {
        topic: "disposal", difficulty: 1,
        kind: "pick",
        prompt: L("Does scene.remove(mesh) free GPU memory?", "¿scene.remove(mesh) libera la GPU?", "scene.remove で GPU メモリは空く？"),
        code: "scene.remove(mesh);\n// GPU memory freed? ___",
        options: [L("No", "No", "いいえ"), YES],
        answer: 0,
        explain: L("remove only detaches the object. Call dispose() on its geometry, material and textures.", "remove solo desconecta el objeto. Llama a dispose() en su geometría, material y texturas.", "remove は外すだけ。形・マテリアル・テクスチャの dispose() を呼ぼう。"),
      },
      {
        topic: "disposal", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("let n = 0;", "const geo = new THREE.BoxGeometry(), mat = new THREE.MeshBasicMaterial();", "geo.addEventListener(\"dispose\", () => n++);", "mat.addEventListener(\"dispose\", () => n++);", "const scene = new THREE.Scene(), mesh = new THREE.Mesh(geo, mat);", "scene.add(mesh); scene.remove(mesh);", "const afterRemove = n;", "geo.dispose(); mat.dispose();", "console.log(afterRemove, n);"),
        options: ["0 2", "2 2", "0 0"],
        answer: 0,
        check: { compiles: true, stdout: "0 2" },
        explain: L("Removing fires no dispose event. Only dispose() tells the renderer to free the GPU buffers.", "Quitar no lanza ningún evento dispose. Solo dispose() le avisa al renderer que libere los buffers.", "remove では dispose イベントは出ない。dispose() だけがレンダラーに解放を伝える。"),
      },
      // ecosystem ×2
      {
        topic: "ecosystem", difficulty: 1,
        kind: "pick",
        prompt: L("three.js as React components", "three.js como componentes React", "three.js を React 部品として使うのは？"),
        code: "// <Canvas><mesh /></Canvas> comes from ___",
        options: ["react-three-fiber", "react-dom", "three/addons"],
        answer: 0,
        explain: L("react-three-fiber (@react-three/fiber) renders three.js objects declaratively from JSX.", "react-three-fiber (@react-three/fiber) renderiza objetos three.js de forma declarativa con JSX.", "react-three-fiber（@react-three/fiber）は JSX で three.js を宣言的に描く。"),
      },
      {
        topic: "ecosystem", difficulty: 2,
        kind: "type",
        prompt: L("Damping needs this call every frame", "El damping necesita esta llamada por frame", "減衰には毎フレームこれを呼ぶ"),
        code: code("import { OrbitControls } from \"three/addons/controls/OrbitControls.js\";", "declare const camera: THREE.PerspectiveCamera, canvas: HTMLCanvasElement;", "const controls = new OrbitControls(camera, canvas);", "controls.enableDamping = true;", "function onFrame() {", "  controls.___();", "}"),
        answer: "update",
        check: { compiles: true },
        explain: L("With enableDamping (or autoRotate) OrbitControls must be updated in the loop, or the camera stops easing.", "Con enableDamping (o autoRotate), OrbitControls debe actualizarse en el bucle o la cámara deja de suavizar.", "enableDamping（や autoRotate）では、ループで update() を呼ばないとなめらかに動かない。"),
      },
    ],
  },

  // ─── SENIOR ───────────────────────────────────────────────────────────────
  {
    slug: "senior",
    level: "senior",
    title: L("Senior three.js / Creative Dev", "three.js / Creative Dev Senior", "シニア three.js 開発者"),
    description: L(
      "Senior web 3D interview: rotations, colour pipeline, leaks, draw calls, shaders and what the renderer does in WebGL.",
      "Entrevista senior de 3D web: rotaciones, color, fugas, draw calls, shaders y lo que hace el renderer en WebGL.",
      "シニア Web 3D 面接：回転、色の流れ、リーク、ドローコール、シェーダー、レンダラーの中身。",
    ),
    count: 15,
    passPct: 75,
    secondsPerQuestion: 50,
    codeCount: 2,
    questions: [
      ...seniorTraceDebug,
      ...seniorTasks,
      // rotations ×3
      {
        topic: "rotations", difficulty: 2,
        kind: "predict",
        prompt: L("Half-way slerp: angle in degrees?", "Slerp a la mitad: ¿ángulo en grados?", "半分の slerp：角度は何度？"),
        code: code("const a = new THREE.Quaternion();", "const b = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 0, 1), Math.PI / 2);", "const h = a.clone().slerp(b, 0.5);", "console.log((2 * Math.acos(h.w) * 180 / Math.PI).toFixed(1));"),
        options: ["45.0", "90.0", "22.5"],
        answer: 0,
        check: { compiles: true, stdout: "45.0" },
        explain: L("slerp interpolates along the shortest arc at constant speed: half of 90° is 45°.", "slerp interpola por el arco más corto a velocidad constante: la mitad de 90° es 45°.", "slerp は最短の弧を一定速度で補間する。90° の半分で 45°。"),
      },
      {
        topic: "rotations", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code("const m = new THREE.Matrix4().compose(new THREE.Vector3(1, 2, 3), new THREE.Quaternion(), new THREE.Vector3(2, 2, 2));", "const p = new THREE.Vector3(), q = new THREE.Quaternion(), s = new THREE.Vector3();", "m.decompose(p, q, s);", "console.log(p.toArray().join(\",\"), s.toArray().join(\",\"));"),
        options: ["1,2,3 2,2,2", "2,4,6 2,2,2", "1,2,3 1,1,1"],
        answer: 0,
        check: { compiles: true, stdout: "1,2,3 2,2,2" },
        explain: L("compose builds T × R × S; decompose splits it back. Translation isn't scaled by its own scale.", "compose arma T × R × S; decompose lo separa otra vez. La traslación no se escala con su propia escala.", "compose は T × R × S を作り、decompose で元に戻す。平行移動は自分のスケールで伸びない。"),
      },
      {
        topic: "rotations", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const m = new THREE.Matrix4().set(", "  1, 2, 3, 4,", "  5, 6, 7, 8,", "  9, 10, 11, 12,", "  13, 14, 15, 16);", "console.log(m.elements.slice(0, 4).join(\",\"));"),
        options: ["1,5,9,13", "1,2,3,4", "13,14,15,16"],
        answer: 0,
        check: { compiles: true, stdout: "1,5,9,13" },
        explain: L("set() reads row by row, but elements is stored column-major: the first column comes first.", "set() se lee fila por fila, pero elements se guarda por columnas: primero va la primera columna.", "set() は行ごとに書くが、elements は列優先で保存。最初の列が先に来る。"),
      },
      // raycasting ×2
      {
        topic: "raycasting", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const scene = new THREE.Scene();", "for (const [name, z] of [[\"far\", -5], [\"near\", 0]] as const) {", `  const box = ${BOX};`, "  box.name = name; box.position.z = z; scene.add(box);", "}", "scene.updateMatrixWorld();", `const rc = ${RAY};`, "console.log(rc.intersectObjects(scene.children).map((h) => `${h.object.name}:${h.distance.toFixed(1)}`).join(\",\"));"),
        options: ["near:9.5,far:14.5", "far:14.5,near:9.5", "near:10.0,far:15.0"],
        answer: 0,
        check: { compiles: true, stdout: "near:9.5,far:14.5" },
        explain: L("Hits are sorted nearest first. Distances go to each box's front face at z = 0.5 and z = -4.5.", "Los impactos se ordenan del más cercano. Las distancias llegan a la cara frontal de cada caja, en z = 0.5 y z = -4.5.", "当たりは近い順。距離は各箱の前面 z = 0.5 と z = -4.5 まで。"),
      },
      {
        topic: "raycasting", difficulty: 3,
        kind: "pick",
        prompt: L("Picking a 2M-triangle mesh is slow. Fix:", "Elegir en una malla de 2M triángulos es lento:", "200万三角形の選択が遅い。対策は？"),
        code: "// raycaster.intersectObject(city) takes 40 ms: ___",
        options: [L("a BVH (three-mesh-bvh)", "un BVH (three-mesh-bvh)", "BVH（three-mesh-bvh）"), L("a bigger far value", "un far más grande", "far を大きくする")],
        answer: 0,
        explain: L("The default raycast tests every triangle. A bounding volume hierarchy skips most of them; GPU picking is another option.", "El raycast por defecto prueba cada triángulo. Una jerarquía de volúmenes salta la mayoría; el picking por GPU es otra opción.", "標準のレイキャストは全三角形を調べる。BVH ならほとんど飛ばせる。GPU ピッキングも手。"),
      },
      // assets_color ×3
      {
        topic: "assets_color", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("console.log(new THREE.Color(0.5, 0.5, 0.5).getHexString());"),
        options: ["bcbcbc", "808080", "7f7f7f"],
        answer: 0,
        check: { compiles: true, stdout: "bcbcbc" },
        explain: L("Color components are linear; getHexString converts to sRGB. Linear 0.5 is brighter in sRGB: bc.", "Los componentes de Color son lineales; getHexString convierte a sRGB. El 0.5 lineal es más claro en sRGB: bc.", "Color の成分は linear。getHexString は sRGB に変換するので 0.5 は bc になる。"),
      },
      {
        topic: "assets_color", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("console.log(THREE.ColorManagement.enabled, THREE.ColorManagement.workingColorSpace);"),
        options: ["true srgb-linear", "false srgb", "true srgb"],
        answer: 0,
        check: { compiles: true, stdout: "true srgb-linear" },
        explain: L("Colour management is on: lighting math happens in linear sRGB and the output is converted to sRGB.", "La gestión de color está activa: la iluminación se calcula en sRGB lineal y la salida se convierte a sRGB.", "カラーマネジメントは有効。光の計算は linear で行い、出力を sRGB に変換する。"),
      },
      {
        topic: "assets_color", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code("const c = new THREE.Color(\"#808080\");", "console.log(c.r.toFixed(4), c.getHexString());"),
        options: ["0.2159 808080", "0.5020 808080", "0.2159 373737"],
        answer: 0,
        check: { compiles: true, stdout: "0.2159 808080" },
        explain: L("CSS hex is sRGB: it's stored converted to linear (0.2159) and read back as sRGB (808080).", "El hex CSS es sRGB: se guarda convertido a lineal (0.2159) y se lee de vuelta como sRGB (808080).", "CSS の16進は sRGB。linear（0.2159）で保存され、sRGB（808080）で読み戻される。"),
      },
      // disposal ×3
      {
        topic: "disposal", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const target = new THREE.WebGLRenderTarget(256, 256);", "let freed = 0;", "target.addEventListener(\"dispose\", () => freed++);", "target.dispose();", "console.log(freed, target.width);"),
        options: ["1 256", "0 256", "1 0"],
        answer: 0,
        check: { compiles: true, stdout: "1 256" },
        explain: L("Render targets hold GPU textures and framebuffers too; dispose() fires the event the renderer frees them on.", "Los render targets también tienen texturas y framebuffers en GPU; dispose() lanza el evento con que el renderer los libera.", "レンダーターゲットも GPU のテクスチャとフレームバッファを持つ。dispose() で解放される。"),
      },
      {
        topic: "disposal", difficulty: 3,
        kind: "pick",
        prompt: L("Does material.dispose() free its map?", "¿material.dispose() libera su map?", "material.dispose() で map も消える？"),
        code: "material.dispose();\n// material.map texture freed too? ___",
        options: [L("No: call map.dispose() too", "No: llama también a map.dispose()", "いいえ：map.dispose() も呼ぶ"), L("Yes, automatically", "Sí, automáticamente", "はい、自動で")],
        answer: 0,
        explain: L("Textures can be shared, so disposing a material leaves them alone. Dispose each texture yourself.", "Las texturas pueden compartirse, así que liberar un material no las toca. Libera cada textura tú.", "テクスチャは共有されうるので、マテリアルを消しても残る。テクスチャは自分で dispose しよう。"),
      },
      {
        topic: "disposal", difficulty: 2,
        kind: "pick",
        prompt: L("Where do you watch for a leak?", "¿Dónde vigilas una fuga?", "リークを監視する場所は？"),
        code: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene;", "console.log(___);"),
        options: ["renderer.info.memory.geometries", "scene.children.length"],
        answer: 0,
        check: { compiles: true },
        explain: L("renderer.info.memory counts GPU geometries and textures. Removed but undisposed meshes still count there.", "renderer.info.memory cuenta geometrías y texturas en GPU. Las mallas quitadas sin dispose siguen contando ahí.", "renderer.info.memory は GPU 上の形とテクスチャの数。外しただけのメッシュも数えられる。"),
      },
      // performance ×4
      {
        topic: "performance", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const im = new THREE.InstancedMesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial(), 100);", "console.log(im.instanceMatrix.array.length);"),
        options: ["1600", "100", "400"],
        answer: 0,
        check: { compiles: true, stdout: "1600" },
        explain: L("One draw call, 100 instances, one 4×4 matrix (16 floats) each in a single buffer.", "Un draw call, 100 instancias, una matriz 4×4 (16 floats) cada una en un solo buffer.", "ドローコール1回、インスタンス100個、それぞれ4×4行列（16個）を1つのバッファに。"),
      },
      {
        topic: "performance", difficulty: 2,
        kind: "pick",
        prompt: L("10 000 static rocks, 5 shapes", "10 000 rocas estáticas, 5 formas", "動かない岩1万個、形は5種類"),
        code: "// fastest way to draw them: ___",
        options: [L("5 InstancedMesh", "5 InstancedMesh", "InstancedMesh を5つ"), L("10 000 meshes", "10 000 mallas", "メッシュ1万個"), L("one shader per rock", "un shader por roca", "岩ごとにシェーダー")],
        answer: 0,
        explain: L("One InstancedMesh per shape: 5 draw calls instead of 10 000. Merging static geometry per material also works.", "Un InstancedMesh por forma: 5 draw calls en vez de 10 000. Fusionar geometría estática por material también sirve.", "形ごとに InstancedMesh：1万回が5回に。素材ごとに静的な形を結合する手もある。"),
      },
      {
        topic: "performance", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code("const lod = new THREE.LOD();", "const hi = Object.assign(new THREE.Object3D(), { name: \"hi\" });", "const lo = Object.assign(new THREE.Object3D(), { name: \"lo\" });", "lod.addLevel(hi, 0);", "lod.addLevel(lo, 50);", "console.log(lod.getObjectForDistance(10)?.name, lod.getObjectForDistance(80)?.name);"),
        options: ["hi lo", "lo hi", "hi hi"],
        answer: 0,
        check: { compiles: true, stdout: "hi lo" },
        explain: L("LOD swaps in the cheaper level once the camera is farther than its distance (50 here).", "LOD cambia al nivel más barato cuando la cámara está más lejos que su distancia (aquí 50).", "LOD はカメラが距離（ここでは 50）より遠いと軽いモデルに切りかえる。"),
      },
      {
        topic: "performance", difficulty: 3,
        kind: "predict",
        prompt: PRINTS,
        code: code(`const rock = ${BOX};`, "rock.matrixAutoUpdate = false;", "rock.position.x = 5;", "rock.updateMatrixWorld();", "const a = rock.matrixWorld.elements[12];", "rock.updateMatrix();", "rock.updateMatrixWorld();", "console.log(a, rock.matrixWorld.elements[12]);"),
        options: ["0 5", "5 5", "0 0"],
        answer: 0,
        check: { compiles: true, stdout: "0 5" },
        explain: L("With matrixAutoUpdate = false the local matrix isn't rebuilt each frame: cheap for static objects, but call updateMatrix() after moving.", "Con matrixAutoUpdate = false la matriz local no se rehace cada frame: barato para estáticos, pero llama a updateMatrix() tras mover.", "matrixAutoUpdate = false だと行列は毎フレーム作り直されない。静的な物に有効。動かしたら updateMatrix()。"),
      },
      // lights_shadows ×2
      {
        topic: "lights_shadows", difficulty: 2,
        kind: "type",
        prompt: L("Fix shadow acne", "Arregla el shadow acne", "シャドウアクネを直そう"),
        code: code("const sun = new THREE.DirectionalLight();", "sun.castShadow = true;", "sun.shadow.___ = -0.0005;", "console.log(sun.shadow.bias);"),
        answer: "bias",
        check: { compiles: true, stdout: "-0.0005" },
        explain: L("Acne is a surface shadowing itself from depth precision. A small bias (or normalBias) pushes the test off it.", "El acne es una superficie que se sombrea a sí misma por precisión de profundidad. Un bias pequeño (o normalBias) lo evita.", "アクネは深度精度のせいで面が自分に影を落とす現象。小さな bias（や normalBias）で防ぐ。"),
      },
      {
        topic: "lights_shadows", difficulty: 2,
        kind: "predict",
        prompt: L("Default shadow map size?", "¿Tamaño por defecto del shadow map?", "影マップの初期サイズは？"),
        code: code("const sun = new THREE.DirectionalLight();", "console.log(sun.shadow.mapSize.x, sun.shadow.mapSize.y);"),
        options: ["512 512", "1024 1024", "2048 2048"],
        answer: 0,
        check: { compiles: true, stdout: "512 512" },
        explain: L("512² by default. Doubling each side to 1024 costs 4× the memory and fill; tighten the shadow camera first.", "512² por defecto. Duplicar cada lado a 1024 cuesta 4× memoria; primero ajusta la cámara de sombra.", "初期値は 512²。1024 にすると4倍のメモリ。まず影カメラの範囲をしぼろう。"),
      },
      // shaders ×3
      {
        topic: "shaders", difficulty: 1,
        kind: "pick",
        prompt: L("Animate a ShaderMaterial each frame", "Anima un ShaderMaterial en cada frame", "ShaderMaterial を毎フレーム動かす"),
        code: code("const material = new THREE.ShaderMaterial({ uniforms: { uTime: { value: 0 } } });", "declare const elapsed: number;", "material.___ = elapsed;"),
        options: ["uniforms.uTime.value", "uTime"],
        answer: 0,
        check: { compiles: true, wrongFail: true },
        explain: L("Update the uniform's value; three.js uploads it on the next draw. Never rebuild the material per frame.", "Actualiza el value del uniform; three.js lo sube en el próximo dibujo. Nunca rehagas el material por frame.", "uniform の value を書きかえれば次の描画で送られる。毎フレーム作り直さないこと。"),
      },
      {
        topic: "shaders", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const m = new THREE.ShaderMaterial({ uniforms: { uTime: { value: 0 } } });", "const v0 = m.version;", "m.uniforms.uTime.value = 1.5;", "const v1 = m.version;", "m.needsUpdate = true;", "console.log(v0, v1, m.version);"),
        options: ["0 0 1", "0 1 2", "0 1 1"],
        answer: 0,
        check: { compiles: true, stdout: "0 0 1" },
        explain: L("Changing a uniform is cheap and bumps nothing. needsUpdate bumps the version: the program is rebuilt.", "Cambiar un uniform es barato y no sube nada. needsUpdate sube la versión: el programa se recompila.", "uniform の変更は軽く、version は変わらない。needsUpdate は version を上げ、プログラムを作り直す。"),
      },
      {
        topic: "shaders", difficulty: 3,
        kind: "pick",
        prompt: L("RawShaderMaterial vs ShaderMaterial", "RawShaderMaterial vs ShaderMaterial", "RawShaderMaterial の違いは？"),
        code: "// RawShaderMaterial: ___",
        options: [L("no built-in uniforms or prefix", "sin uniforms ni prefijo incluidos", "組みこみ uniform も前置きもない"), L("faster textures", "texturas más rápidas", "テクスチャが速い")],
        answer: 0,
        explain: L("ShaderMaterial prepends projectionMatrix, modelViewMatrix, position… Raw gives you none: declare everything yourself.", "ShaderMaterial antepone projectionMatrix, modelViewMatrix, position… Raw no da nada: declaras todo tú.", "ShaderMaterial は projectionMatrix などを先頭に足す。Raw は何もないので全部自分で宣言する。"),
      },
      // webgl_under_hood ×3
      {
        topic: "webgl_under_hood", difficulty: 1,
        kind: "pick",
        prompt: L("Each visible mesh roughly costs…", "Cada malla visible cuesta más o menos…", "見えるメッシュ1つのコストは？"),
        code: "// per frame, one Mesh with its own material: ___",
        options: [L("one draw call", "un draw call", "ドローコール1回"), L("one shader compile", "una compilación de shader", "シェーダーのコンパイル1回")],
        answer: 0,
        explain: L("The renderer binds the program and buffers and issues one draw per mesh. Shaders compile once and are cached.", "El renderer enlaza programa y buffers y emite un draw por malla. Los shaders se compilan una vez y se cachean.", "レンダラーはメッシュごとに1回描画命令を出す。シェーダーは1回コンパイルして使い回す。"),
      },
      {
        topic: "webgl_under_hood", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const pos = new THREE.BoxGeometry().attributes.position;", "console.log(pos.itemSize, pos.array.constructor.name);"),
        options: ["3 Float32Array", "1 Array", "4 Float64Array"],
        answer: 0,
        check: { compiles: true, stdout: "3 Float32Array" },
        explain: L("Attributes are typed arrays uploaded as GL buffers: vertexAttribPointer(size 3, gl.FLOAT) under the hood.", "Los atributos son typed arrays subidos como buffers GL: por debajo, vertexAttribPointer(tamaño 3, gl.FLOAT).", "属性は型付き配列で GL バッファとして送られる。内部では vertexAttribPointer(3, gl.FLOAT)。"),
      },
      {
        topic: "webgl_under_hood", difficulty: 3,
        kind: "predict",
        prompt: L("Box with an array of materials: groups?", "Caja con un array de materiales: ¿grupos?", "マテリアル配列の箱：グループ数は？"),
        code: code("console.log(new THREE.BoxGeometry().groups.length);"),
        options: ["6", "1", "12"],
        answer: 0,
        check: { compiles: true, stdout: "6" },
        explain: L("One group per face. With 6 materials the renderer issues one draw call per group: 6 draws for one box.", "Un grupo por cara. Con 6 materiales el renderer emite un draw call por grupo: 6 para una caja.", "面ごとに1グループ。マテリアル6つなら、グループごとに描画して箱1つで6回。"),
      },
      // scene_graph ×1
      {
        topic: "scene_graph", difficulty: 2,
        kind: "predict",
        prompt: PRINTS,
        code: code("const scene = new THREE.Scene(), group = new THREE.Group(), child = new THREE.Object3D();", "group.position.y = 2;", "group.scale.setScalar(3);", "child.position.set(1, 1, 0);", "scene.add(group); group.add(child);", "scene.updateMatrixWorld();", "console.log(new THREE.Vector3().setFromMatrixPosition(child.matrixWorld).toArray().join(\",\"));"),
        options: ["3,5,0", "1,3,0", "3,3,0"],
        answer: 0,
        check: { compiles: true, stdout: "3,5,0" },
        explain: L("world = parent × local: (1, 1, 0) scaled by 3 is (3, 3, 0), then lifted by 2 to (3, 5, 0).", "mundo = padre × local: (1, 1, 0) escalado por 3 es (3, 3, 0) y luego subido 2: (3, 5, 0).", "ワールド = 親 × ローカル。(1, 1, 0) を3倍で (3, 3, 0)、2上げて (3, 5, 0)。"),
      },
      // render_loop ×2
      {
        topic: "render_loop", difficulty: 3,
        kind: "pick",
        prompt: L("Why Timer over the old Clock?", "¿Por qué Timer y no el viejo Clock?", "古い Clock より Timer を使う理由は？"),
        code: "// THREE.Timer instead of THREE.Clock: ___",
        options: [L("stable delta per frame", "delta estable por frame", "フレーム内で delta が安定"), L("Clock is slower", "Clock es más lento", "Clock は遅い")],
        answer: 0,
        explain: L("Timer updates once per frame, so every getDelta() in it agrees; it can also handle hidden tabs. Clock is deprecated.", "Timer se actualiza una vez por frame, así cada getDelta() coincide; también maneja pestañas ocultas. Clock está obsoleto.", "Timer はフレームに1回更新するので getDelta() がそろう。隠れたタブにも対応。Clock は非推奨。"),
      },
      {
        topic: "render_loop", difficulty: 2,
        kind: "predict",
        prompt: L("update() called twice in one frame", "update() llamado dos veces en un frame", "1フレームで update() を2回"),
        code: code("const timer = new THREE.Timer();", "timer.update(0);", "timer.update(100);", "timer.update(100); // a second system ticks it again", "console.log(timer.getDelta());"),
        options: ["0", "0.1", "0.2"],
        answer: 0,
        check: { compiles: true, stdout: "0" },
        explain: L("The delta is the time between the last two updates. Tick the timer once per frame in one place.", "El delta es el tiempo entre los dos últimos updates. Avanza el timer una vez por frame en un solo lugar.", "delta は直近2回の update の差。タイマーは1か所でフレームに1回だけ進めよう。"),
      },
    ],
  },
];
