import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 2 · BUFFER FOREST  (typed arrays and buffers, attributes, stride and offset, indexed drawing, textures)
// The runner has no GPU: runnable claims are pure logic; WebGL API claims are type-checked only.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");

// ─── 2.1 Packing the cart ──────────────────────────────────────────────────
const typedArrays: LessonDef = {
  slug: "buffers-and-typed-arrays",
  title: L("Packing the cart", "Llenando el carro", "荷車につめこもう"),
  concept: "buffers",
  mode: "lesson",
  xp: 65,
  enemy: "webgl/shader-goblin",
  enemyName: L("BYTE GOBLIN", "GOBLIN DE BYTES", "バイトゴブリン"),
  beats: [
    say(L(
      "Welcome to Buffer Forest! The GPU can't read JS arrays. It reads raw bytes, so we pack numbers into TYPED ARRAYS.",
      "¡Bienvenido al Bosque de Buffers! La GPU no lee arrays de JS. Lee bytes crudos, así que empacamos números en TYPED ARRAYS.",
      "バッファの森へようこそ！GPU は JS の配列を読めない。生のバイトを読むから、数を型付き配列につめるんだ。",
    )),
    {
      kind: "act",
      prompt: L("Pack a triangle and weigh it", "Empaca un triángulo y pésalo", "三角形をつめて重さをはかろう"),
      steps: [
        { label: L("PACK", "EMPACAR", "つめる"), line: "const tri = new Float32Array([0, 0, 1, 0, 0, 1]);", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "tri" }] },
        { label: L("COUNT", "CONTAR", "数える"), line: "console.log(tri.length);", effects: [{ t: "value", actor: "hero", text: "6" }, { t: "print", text: "6" }], output: "6" },
        { label: L("BYTES", "BYTES", "バイト数"), line: "console.log(tri.byteLength);", effects: [{ t: "print", text: "24" }, { t: "say", actor: "hero", text: L("4 bytes each!", "¡4 bytes cada uno!", "1 つ 4 バイト！") }], output: "24" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(\n  Float32Array.BYTES_PER_ELEMENT,\n  Uint16Array.BYTES_PER_ELEMENT,\n  Uint8Array.BYTES_PER_ELEMENT,\n);",
      options: ["4 2 1", "32 16 8", "1 1 1"],
      answer: 0,
      output: "4 2 1",
      check: { compiles: true, stdout: "4 2 1" },
      explain: L("BYTES_PER_ELEMENT is the slot size in bytes: 32 bits = 4 bytes, 16 bits = 2, 8 bits = 1.", "BYTES_PER_ELEMENT es el tamaño de cada casilla en bytes: 32 bits = 4, 16 bits = 2, 8 bits = 1.", "BYTES_PER_ELEMENT は 1 マスのバイト数。32 ビット = 4、16 ビット = 2、8 ビット = 1。"),
      win: [{ t: "print", text: "4 2 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const quad = new Float32Array([0, 0, 0, 1, 1, 1, 1, 0, 0]);\nconsole.log(quad.length, quad.byteLength);",
      options: ["9 36", "9 9", "36 9"],
      answer: 0,
      output: "9 36",
      check: { compiles: true, stdout: "9 36" },
      explain: L("length counts numbers (9); byteLength counts bytes (9 × 4 = 36).", "length cuenta números (9); byteLength cuenta bytes (9 × 4 = 36).", "length は数の個数（9）、byteLength はバイト数（9 × 4 = 36）。"),
      win: [{ t: "print", text: "9 36" }],
    },
    say(L(
      "Each slot has a fixed size. Float32 rounds decimals, Uint16 wraps past 65535, Uint8Clamped clamps to 0..255.",
      "Cada casilla tiene tamaño fijo. Float32 redondea decimales, Uint16 da la vuelta tras 65535, Uint8Clamped se limita a 0..255.",
      "マスの大きさは決まっている。Float32 は小数を丸め、Uint16 は 65535 をこえると一周、Uint8Clamped は 0..255 におさめる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(new Float32Array([0.1])[0]);",
      options: ["0.10000000149011612", "0.1", "0"],
      answer: 0,
      output: "0.10000000149011612",
      check: { compiles: true, stdout: "0.10000000149011612" },
      explain: L("32-bit floats are less precise than JS numbers, so 0.1 is stored as the closest float32.", "Los floats de 32 bits son menos precisos que los números de JS, así que 0.1 se guarda como el float32 más cercano.", "32 ビット float は JS の数より精度が低い。0.1 は一番近い float32 で保存される。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'console.log(new Uint16Array([65535, 65536]).join(","));',
      options: ["65535,0", "65535,65536", "65535,65535"],
      answer: 0,
      output: "65535,0",
      check: { compiles: true, stdout: "65535,0" },
      explain: L("16 bits hold 0..65535. 65536 wraps around to 0, silently.", "16 bits guardan 0..65535. 65536 da la vuelta a 0, sin avisar.", "16 ビットは 0..65535。65536 はだまって 0 に戻る。"),
      win: [{ t: "shake" }, { t: "print", text: "65535,0" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(\n  new Uint8Array([300]).join(),\n  new Uint8ClampedArray([300]).join(),\n);",
      options: ["44 255", "255 255", "44 44"],
      answer: 0,
      output: "44 255",
      check: { compiles: true, stdout: "44 255" },
      explain: L("Uint8 wraps: 300 - 256 = 44. Uint8Clamped stops at the top: 255.", "Uint8 da la vuelta: 300 - 256 = 44. Uint8Clamped se frena arriba: 255.", "Uint8 は一周：300 - 256 = 44。Uint8Clamped は上限の 255 で止まる。"),
    },
    say(L(
      "Upload: createBuffer, bindBuffer, then bufferData with a typed array. ARRAY_BUFFER holds vertices, ELEMENT_ARRAY_BUFFER indices.",
      "Para subir: createBuffer, bindBuffer y bufferData con un typed array. ARRAY_BUFFER guarda vértices; ELEMENT_ARRAY_BUFFER, índices.",
      "送り方：createBuffer、bindBuffer、型付き配列で bufferData。頂点は ARRAY_BUFFER、番号は ELEMENT_ARRAY_BUFFER。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "declare const gl: WebGL2RenderingContext;\ngl.bufferData(gl.ARRAY_BUFFER, [0, 1, 2], gl.STATIC_DRAW);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2769: No overload matches this call. Wrap it: new Float32Array([0, 1, 2]).", "Error TS2769: ninguna sobrecarga coincide. Envuélvelo: new Float32Array([0, 1, 2]).", "エラー TS2769：合うオーバーロードがない。new Float32Array([0, 1, 2]) で包もう。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "pick",
      prompt: L("Bind point for indices", "Ranura para índices", "インデックス用の席"),
      code: "declare const gl: WebGL2RenderingContext;\ndeclare const indexBuf: WebGLBuffer;\ngl.bindBuffer(gl.___, indexBuf);",
      options: ["ELEMENT_ARRAY_BUFFER", "ARRAY_BUFFER", "INDEX_BUFFER"],
      answer: 0,
      check: { compiles: true },
      explain: L("Indices live in ELEMENT_ARRAY_BUFFER. ARRAY_BUFFER is for vertex data; INDEX_BUFFER doesn't exist.", "Los índices van en ELEMENT_ARRAY_BUFFER. ARRAY_BUFFER es para vértices; INDEX_BUFFER no existe.", "インデックスは ELEMENT_ARRAY_BUFFER。ARRAY_BUFFER は頂点用、INDEX_BUFFER はない。"),
    },
    say(L(
      "The last argument is a usage hint: STATIC_DRAW for data set once, DYNAMIC_DRAW for data you rewrite often.",
      "El último argumento es una pista de uso: STATIC_DRAW para datos fijos, DYNAMIC_DRAW para datos que reescribes seguido.",
      "最後の引数は使い方のヒント。一度だけなら STATIC_DRAW、よく書きかえるなら DYNAMIC_DRAW。",
    )),
    {
      kind: "pick",
      prompt: L("Rewritten every frame: hint?", "Se reescribe cada frame: ¿pista?", "毎フレーム書きかえ：ヒントは？"),
      code: "declare const gl: WebGL2RenderingContext;\ndeclare const particles: Float32Array;\n// rewritten every frame\ngl.bufferData(gl.ARRAY_BUFFER, particles, gl.___);",
      options: ["DYNAMIC_DRAW", "STATIC_DRAW"],
      answer: 0,
      check: { compiles: true },
      explain: L("Both compile, but DYNAMIC_DRAW tells the driver the data changes often, so it can place it well.", "Ambos compilan, pero DYNAMIC_DRAW avisa al driver que los datos cambian seguido para ubicarlos bien.", "どちらもコンパイルできるけど、DYNAMIC_DRAW はよく変わると伝えるので、ドライバーがうまく置ける。"),
    },
    {
      kind: "run",
      prompt: L("Count the cube's bytes, not its floats", "Cuenta los bytes del cubo, no floats", "float の数でなくバイト数を"),
      starter: 'const cube = new Float32Array(8 * 3);\nconst bytes = cube.length;\nconsole.log("bytes: " + bytes);\n',
      solution: 'const cube = new Float32Array(8 * 3);\nconst bytes = cube.length * Float32Array.BYTES_PER_ELEMENT;\nconsole.log("bytes: " + bytes);\n',
      expect: "bytes: 96",
      fallback: [String.raw`BYTES_PER_ELEMENT`, String.raw`byteLength`, String.raw`cube\.length\s*\*\s*4`],
      explain: L("24 floats × 4 bytes = 96. Use cube.byteLength or multiply by BYTES_PER_ELEMENT.", "24 floats × 4 bytes = 96. Usa cube.byteLength o multiplica por BYTES_PER_ELEMENT.", "24 個 × 4 バイト = 96。cube.byteLength か BYTES_PER_ELEMENT をかけよう。"),
    },
  ],
};

// ─── 2.2 The interleaved caravan ───────────────────────────────────────────
const attributes: LessonDef = {
  slug: "attributes-stride-offset",
  title: L("The interleaved caravan", "La caravana intercalada", "まぜこみキャラバン"),
  concept: "attributes",
  mode: "lesson",
  xp: 70,
  enemy: "webgl/z-fighting",
  enemyName: L("STRIDE TWINS", "GEMELOS STRIDE", "ストライドふたご"),
  beats: [
    say(L(
      "An ATTRIBUTE is per-vertex data the shader reads with in. Many attributes can share one INTERLEAVED buffer: x y z u v, x y z u v...",
      "Un ATTRIBUTE es dato por vértice que el shader lee con in. Varios pueden compartir un buffer INTERCALADO: x y z u v, x y z u v...",
      "アトリビュートは頂点ごとのデータで、シェーダーが in で読む。1 つのバッファにまぜて並べられる：x y z u v、x y z u v…",
    )),
    {
      kind: "act",
      prompt: L("Measure one wagon of the caravan", "Mide un vagón de la caravana", "キャラバンの 1 両をはかろう"),
      steps: [
        { label: L("LAYOUT", "DISEÑO", "並び"), line: "const F = 5; // x y z u v", effects: [{ t: "tag", actor: "hero", text: "F", value: "5" }] },
        { label: L("STRIDE", "STRIDE", "ストライド"), line: "const stride = F * 4;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "stride", value: "20" }, { t: "say", actor: "ally", text: L("20 bytes a wagon", "20 bytes x vagón", "1 両 20 バイト") }] },
        { label: L("UV OFFSET", "OFFSET UV", "UV の位置"), line: "const uvOffset = 3 * 4;", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "value", actor: "hero", text: "12" }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "console.log(stride, uvOffset);", effects: [{ t: "print", text: "20 12" }], output: "20 12" },
      ],
    },
    say(L(
      "STRIDE is the jump from one vertex to the next. OFFSET is where an attribute starts inside a vertex. Both are in BYTES.",
      "STRIDE es el salto de un vértice al siguiente. OFFSET es dónde empieza un attribute dentro del vértice. Ambos van en BYTES.",
      "ストライドは次の頂点までの距離。オフセットは頂点の中でアトリビュートが始まる位置。どちらもバイト単位。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "// x y z r g b (all floats)\nconst stride = (3 + 3) * 4;\nconst colorOffset = 3 * 4;\nconsole.log(stride, colorOffset);",
      options: ["24 12", "6 3", "24 3"],
      answer: 0,
      output: "24 12",
      check: { compiles: true, stdout: "24 12" },
      explain: L("6 floats × 4 bytes = 24 per vertex. Color starts after 3 floats: 12 bytes in.", "6 floats × 4 bytes = 24 por vértice. El color empieza tras 3 floats: en el byte 12.", "1 頂点 6 個 × 4 バイト = 24。色は float 3 個の後、12 バイト目から。"),
      win: [{ t: "print", text: "24 12" }],
    },
    {
      kind: "predict",
      prompt: L("3 floats + 4 bytes: stride?", "3 floats + 4 bytes: ¿stride?", "float 3 個 + 1 バイト 4 個の幅は？"),
      code: "// position: 3 FLOATs, color: 4 UNSIGNED_BYTEs\nconsole.log(3 * 4 + 4 * 1);",
      options: ["16", "7", "28"],
      answer: 0,
      output: "16",
      check: { compiles: true, stdout: "16" },
      explain: L("Add each attribute's bytes: 3 × 4 for floats plus 4 × 1 for bytes = 16.", "Suma los bytes de cada attribute: 3 × 4 de floats más 4 × 1 de bytes = 16.", "アトリビュートごとのバイトを足す：float 3 × 4 + バイト 4 × 1 = 16。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const data = new Float32Array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0]);\nconst F = 5; // x y z u v\nconst i = 1; // second vertex\nconsole.log(data[i * F + 3], data[i * F + 4]);",
      options: ["1 0", "0 1", "0 0"],
      answer: 0,
      output: "1 0",
      check: { compiles: true, stdout: "1 0" },
      explain: L("Vertex 1 starts at slot 5. Its u is slot 8 and its v is slot 9: 1 and 0.", "El vértice 1 empieza en la casilla 5. Su u es la casilla 8 y su v la 9: 1 y 0.", "頂点 1 はマス 5 から。u はマス 8、v はマス 9 で、1 と 0。"),
    },
    say(L(
      "vertexAttribPointer(loc, size, type, normalize, stride, offset) reads from the buffer bound to ARRAY_BUFFER at call time.",
      "vertexAttribPointer(loc, size, type, normalize, stride, offset) lee del buffer enlazado a ARRAY_BUFFER en ese momento.",
      "vertexAttribPointer(loc, size, type, normalize, stride, offset) は呼んだ時の ARRAY_BUFFER から読む。",
    )),
    {
      kind: "order",
      prompt: L("Feed one attribute, then draw", "Alimenta un attribute y dibuja", "アトリビュートを渡して描こう"),
      lines: [
        "const buf = gl.createBuffer();",
        "gl.bindBuffer(gl.ARRAY_BUFFER, buf);",
        "gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);",
        "gl.vertexAttribPointer(loc, 3, gl.FLOAT, false, 0, 0);",
        "gl.drawArrays(gl.TRIANGLES, 0, 3);",
      ],
      check: {
        compiles: true,
        program: "declare const gl: WebGL2RenderingContext;\ndeclare const data: Float32Array;\ndeclare const loc: number;\nconst buf = gl.createBuffer();\ngl.bindBuffer(gl.ARRAY_BUFFER, buf);\ngl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);\ngl.vertexAttribPointer(loc, 3, gl.FLOAT, false, 0, 0);\ngl.drawArrays(gl.TRIANGLES, 0, 3);",
      },
      explain: L("Create, bind, fill, describe the layout of the bound buffer, and only then draw.", "Crear, enlazar, llenar, describir el formato del buffer enlazado y recién entonces dibujar.", "作る、バインド、データを入れる、バインド中のバッファの並びを伝える、そして描く。"),
    },
    say(L(
      "Stride 0 is shorthand for tightly packed. And normalize: true turns UNSIGNED_BYTE 0..255 into 0..1 in the shader.",
      "Stride 0 significa datos bien juntos. Y normalize: true convierte UNSIGNED_BYTE 0..255 en 0..1 dentro del shader.",
      "ストライド 0 は「すき間なし」の省略。normalize: true なら UNSIGNED_BYTE の 0..255 がシェーダーで 0..1 になる。",
    )),
    {
      kind: "predict",
      prompt: L("Stride 0 here means…", "Aquí stride 0 significa…", "ここのストライド 0 の意味は？"),
      code: "gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);",
      options: [L("Packed: 2 × 4 bytes apart", "Juntos: cada 2 × 4 bytes", "すき間なし：2 × 4 バイトごと"), L("No data at all", "Ningún dato", "データなし"), L("Only one vertex", "Un solo vértice", "頂点 1 つだけ")],
      answer: 0,
      explain: L("With stride 0, WebGL computes it from size and type: 2 floats = 8 bytes per vertex.", "Con stride 0, WebGL lo calcula de size y type: 2 floats = 8 bytes por vértice.", "ストライド 0 なら size と type から計算：float 2 個 = 1 頂点 8 バイト。"),
    },
    {
      kind: "predict",
      prompt: L("Normalized byte 128 becomes…", "El byte normalizado 128 es…", "正規化した 128 は？"),
      code: "// normalize: true, type UNSIGNED_BYTE\nconsole.log((128 / 255).toFixed(3));",
      options: ["0.502", "0.500", "128.000"],
      answer: 0,
      output: "0.502",
      check: { compiles: true, stdout: "0.502" },
      explain: L("The value is divided by 255, not 256, so 128 lands just above half.", "Se divide entre 255, no 256, así que 128 queda apenas sobre la mitad.", "256 ではなく 255 で割るので、128 は半分より少し上になる。"),
      win: [{ t: "print", text: "0.502" }],
    },
    say(L(
      "Find an attribute with getAttribLocation(prog, name). It returns a number, or -1 if the shader doesn't use that name.",
      "Encuentra un attribute con getAttribLocation(prog, name). Devuelve un número, o -1 si el shader no usa ese nombre.",
      "アトリビュートは getAttribLocation(prog, name) で探す。数値が返り、シェーダーが使っていなければ -1。",
    )),
    {
      kind: "type",
      prompt: L("What type is the location?", "¿Qué tipo es la ubicación?", "位置の型は？"),
      code: 'declare const gl: WebGL2RenderingContext;\ndeclare const prog: WebGLProgram;\nconst loc: ___ = gl.getAttribLocation(prog, "a_uv");',
      answer: "number",
      check: { compiles: true },
      explain: L("Attribute locations are plain numbers (GLint). Uniform locations are objects instead.", "Las ubicaciones de attributes son números (GLint). Las de uniforms, en cambio, son objetos.", "アトリビュートの位置はただの数値（GLint）。uniform の位置はオブジェクトだよ。"),
    },
    {
      kind: "predict",
      prompt: L("Why did it return -1?", "¿Por qué devolvió -1?", "なぜ -1 が返った？"),
      code: 'const loc = gl.getAttribLocation(prog, "a_normal");\nconsole.log(loc); // -1',
      options: [L("The shader doesn't use a_normal", "El shader no usa a_normal", "シェーダーが a_normal を使っていない"), L("The buffer is empty", "El buffer está vacío", "バッファが空")],
      answer: 0,
      explain: L("-1 means missing or unused: compilers remove attributes that don't affect the output.", "-1 significa ausente o sin usar: el compilador quita attributes que no afectan el resultado.", "-1 はないか未使用。結果に効かないアトリビュートはコンパイラが消すんだ。"),
    },
    say(L(
      "In WebGL2 a VAO (vertex array object) records this whole attribute setup. Later, one bindVertexArray restores it.",
      "En WebGL2 un VAO (vertex array object) graba toda esta configuración. Después, un bindVertexArray la restaura.",
      "WebGL2 の VAO（頂点配列オブジェクト）はこの設定をまるごと記録。あとで bindVertexArray 1 回で戻せる。",
    )),
    {
      kind: "predict",
      prompt: L("What does a VAO store?", "¿Qué guarda un VAO?", "VAO が覚えるのは？"),
      code: "const vao = gl.createVertexArray();\ngl.bindVertexArray(vao);\n// ...attribute setup...",
      options: [L("Attribute pointers and buffers", "Punteros de attributes y buffers", "アトリビュートの設定とバッファ"), L("The program and its uniforms", "El programa y sus uniforms", "プログラムと uniform")],
      answer: 0,
      explain: L("A VAO keeps enables, pointers, their buffers and the ELEMENT_ARRAY_BUFFER binding, not the program.", "Un VAO guarda enables, punteros, sus buffers y el ELEMENT_ARRAY_BUFFER enlazado, no el programa.", "VAO は有効化、ポインター、そのバッファ、ELEMENT_ARRAY_BUFFER を覚える。プログラムは別。"),
    },
    {
      kind: "run",
      prompt: L("Stride and offset are bytes: fix them", "Stride y offset van en bytes: arréglalos", "ストライドとオフセットはバイトで"),
      starter: "const FLOATS_PER_VERTEX = 5; // x y z u v\nconst stride = FLOATS_PER_VERTEX;\nconst uvOffset = 3;\nconsole.log(`stride=${stride} uvOffset=${uvOffset}`);\n",
      solution: "const FLOATS_PER_VERTEX = 5; // x y z u v\nconst stride = FLOATS_PER_VERTEX * Float32Array.BYTES_PER_ELEMENT;\nconst uvOffset = 3 * Float32Array.BYTES_PER_ELEMENT;\nconsole.log(`stride=${stride} uvOffset=${uvOffset}`);\n",
      expect: "stride=20 uvOffset=12",
      fallback: [String.raw`stride\s*=\s*(FLOATS_PER_VERTEX|5)\s*\*\s*(4|Float32Array\.BYTES_PER_ELEMENT)[\s\S]*uvOffset\s*=\s*3\s*\*\s*(4|Float32Array\.BYTES_PER_ELEMENT)`, String.raw`stride\s*=\s*20[\s\S]*uvOffset\s*=\s*12`],
      explain: L("Multiply by Float32Array.BYTES_PER_ELEMENT (4): 5 floats = 20 bytes, uv starts at byte 12.", "Multiplica por Float32Array.BYTES_PER_ELEMENT (4): 5 floats = 20 bytes y uv empieza en el byte 12.", "Float32Array.BYTES_PER_ELEMENT（4）をかける：5 個 = 20 バイト、uv は 12 バイト目から。"),
    },
  ],
};

// ─── 2.3 Reusing corners ───────────────────────────────────────────────────
const indexed: LessonDef = {
  slug: "indexed-drawing",
  title: L("Reusing corners", "Reusando esquinas", "角を使いまわそう"),
  concept: "indexed_drawing",
  mode: "lesson",
  xp: 70,
  enemy: "slime",
  enemyName: L("INDEX SLIME", "SLIME ÍNDICE", "インデックスライム"),
  beats: [
    say(L(
      "A square is 2 triangles = 6 corners, but only 4 are unique. An INDEX buffer lists corner numbers, so each is stored once.",
      "Un cuadrado son 2 triángulos = 6 esquinas, pero solo 4 son únicas. Un buffer de ÍNDICES lista sus números: cada una se guarda una vez.",
      "四角形は三角形 2 つで角が 6 つ。でも本当は 4 つだけ。インデックスバッファは角の番号を並べ、各角を 1 回だけ保存する。",
    )),
    {
      kind: "act",
      prompt: L("Build a quad from 4 corners", "Arma un quad con 4 esquinas", "4 つの角で四角形を作ろう"),
      steps: [
        { label: L("4 CORNERS", "4 ESQUINAS", "角 4 つ"), line: "const verts = new Float32Array([0, 0, 1, 0, 1, 1, 0, 1]);", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "verts" }] },
        { label: L("6 INDICES", "6 ÍNDICES", "番号 6 つ"), line: "const idx = new Uint16Array([0, 1, 2, 2, 3, 0]);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "idx" }, { t: "lend", to: "ally" }] },
        { label: L("TRIANGLES", "TRIÁNGULOS", "三角形の数"), line: "console.log(idx.length / 3);", effects: [{ t: "print", text: "2" }, { t: "banner", text: L("2 TRIANGLES", "2 TRIÁNGULOS", "三角形 2 つ") }], output: "2" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const idx = [0, 1, 2, 2, 3, 0, 4, 5, 6, 6, 7, 4];\nconsole.log(idx.length / 3);",
      options: ["4", "12", "8"],
      answer: 0,
      output: "4",
      check: { compiles: true, stdout: "4" },
      explain: L("With TRIANGLES, every 3 indices make one triangle: 12 / 3 = 4.", "Con TRIANGLES, cada 3 índices forman un triángulo: 12 / 3 = 4.", "TRIANGLES では 3 つで三角形 1 つ。12 / 3 = 4。"),
      win: [{ t: "print", text: "4" }],
    },
    {
      kind: "predict",
      prompt: L("Quad bytes: indexed vs not?", "Bytes del quad: ¿con índices o sin?", "四角形のバイト数：あり／なし"),
      code: "// 12-byte vertices, 2-byte indices\nconst indexed = 4 * 12 + 6 * 2;\nconst plain = 6 * 12;\nconsole.log(indexed, plain);",
      options: ["60 72", "72 60", "48 72"],
      answer: 0,
      output: "60 72",
      check: { compiles: true, stdout: "60 72" },
      explain: L("4 vertices + 6 small indices beat 6 full vertices, and the gap grows with mesh size.", "4 vértices + 6 índices pequeños ganan a 6 vértices completos, y la diferencia crece con la malla.", "頂点 4 つ + 小さな番号 6 つは、頂点 6 つより軽い。メッシュが大きいほど差が広がる。"),
    },
    say(L(
      "drawElements(mode, count, type, offset): count is the number of INDICES; type matches the array, UNSIGNED_SHORT for Uint16Array.",
      "drawElements(mode, count, type, offset): count es el número de ÍNDICES; type coincide con el array, UNSIGNED_SHORT para Uint16Array.",
      "drawElements(mode, count, type, offset)：count は番号の数。Uint16Array なら type は UNSIGNED_SHORT。",
    )),
    {
      kind: "predict",
      prompt: L("Here, the 6 is the number of…", "Aquí, el 6 es la cantidad de…", "この 6 は何の数？"),
      code: "gl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT, 0);",
      options: [L("Indices", "Índices", "インデックス"), L("Triangles", "Triángulos", "三角形"), L("Vertices", "Vértices", "頂点")],
      answer: 0,
      explain: L("count is how many indices to read. 6 indices = 2 triangles over 4 vertices.", "count es cuántos índices leer. 6 índices = 2 triángulos sobre 4 vértices.", "count は読むインデックスの数。6 個 = 頂点 4 つで三角形 2 つ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "declare const gl: WebGL2RenderingContext;\ngl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2554: Expected 4 arguments, but got 3. The byte offset is required: use 0.", "Error TS2554: se esperaban 4 argumentos y llegaron 3. El offset en bytes es obligatorio: usa 0.", "エラー TS2554：引数は 4 つ必要なのに 3 つ。バイトオフセットは必須、0 を渡そう。"),
    },
    {
      kind: "predict",
      prompt: L("Does drawArrays need indices?", "¿drawArrays necesita índices?", "drawArrays にインデックスは？"),
      code: "gl.drawArrays(gl.TRIANGLES, 0, 6);",
      options: [L("No: reads vertices in order", "No: lee vértices en orden", "いらない：頂点を順に読む"), L("Yes: an index buffer", "Sí: un buffer de índices", "いる：インデックスバッファ")],
      answer: 0,
      explain: L("drawArrays walks the vertices from first to first + count. Only drawElements reads indices.", "drawArrays recorre los vértices de first a first + count. Solo drawElements lee índices.", "drawArrays は first から count 個の頂点を順に読む。インデックスを読むのは drawElements だけ。"),
    },
    {
      kind: "predict",
      prompt: L("Grid of 2×2 cells: verts, indices", "Grilla de 2×2: vértices, índices", "2×2 マスの格子：頂点と番号"),
      code: "const verts = (c: number, r: number) => (c + 1) * (r + 1);\nconst inds = (c: number, r: number) => c * r * 6;\nconsole.log(verts(2, 2), inds(2, 2));",
      options: ["9 24", "16 24", "9 12"],
      answer: 0,
      output: "9 24",
      check: { compiles: true, stdout: "9 24" },
      explain: L("A 2×2 grid has 3×3 shared corners, and each of its 4 cells needs 6 indices.", "Una grilla de 2×2 tiene 3×3 esquinas compartidas, y cada una de sus 4 celdas usa 6 índices.", "2×2 の格子は共有の角が 3×3。4 マスそれぞれに番号 6 つ。"),
    },
    say(L(
      "Uint16 indices stop at 65535. Bigger meshes need Uint32Array with gl.UNSIGNED_INT (core in WebGL2).",
      "Los índices Uint16 llegan hasta 65535. Mallas más grandes necesitan Uint32Array con gl.UNSIGNED_INT (nativo en WebGL2).",
      "Uint16 のインデックスは 65535 まで。もっと大きなメッシュは Uint32Array と gl.UNSIGNED_INT（WebGL2 は標準）。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(new Uint16Array([69999])[0]);",
      options: ["4463", "69999", "65535"],
      answer: 0,
      output: "4463",
      check: { compiles: true, stdout: "4463" },
      explain: L("69999 - 65536 = 4463: the index wraps silently and points at the wrong vertex.", "69999 - 65536 = 4463: el índice da la vuelta sin avisar y apunta al vértice equivocado.", "69999 - 65536 = 4463。番号がだまって一周し、ちがう頂点をさしてしまう。"),
      win: [{ t: "shake" }, { t: "print", text: "4463" }],
    },
    say(L(
      "Corner order matters: counter-clockwise is the FRONT by default. gl.enable(gl.CULL_FACE) skips back faces.",
      "El orden de las esquinas importa: antihorario es el FRENTE por defecto. gl.enable(gl.CULL_FACE) omite las caras traseras.",
      "角の順番は大事。既定では反時計回りが表。gl.enable(gl.CULL_FACE) で裏面を描かずにすむ。",
    )),
    {
      kind: "pick",
      prompt: L("The default front face", "La cara frontal por defecto", "既定の表面"),
      code: "declare const gl: WebGL2RenderingContext;\ngl.frontFace(gl.___); // the default",
      options: ["CCW", "CW"],
      answer: 0,
      check: { compiles: true },
      explain: L("CCW (counter-clockwise) is the default front. Both compile; only the winding changes.", "CCW (antihorario) es el frente por defecto. Ambos compilan; solo cambia el sentido.", "既定の表は CCW（反時計回り）。どちらもコンパイルでき、回る向きが変わるだけ。"),
    },
    {
      kind: "run",
      prompt: L("Each quad adds 4 vertices: fix the base", "Cada quad suma 4 vértices: arregla la base", "四角形 1 つで頂点 4 つ：基準を直そう"),
      starter: 'function quadIndices(quads: number): Uint16Array {\n  const out: number[] = [];\n  for (let q = 0; q < quads; q++) {\n    const b = q * 6;\n    out.push(b, b + 1, b + 2, b + 2, b + 3, b);\n  }\n  return new Uint16Array(out);\n}\nconsole.log("indices: " + quadIndices(2).join(","));\n',
      solution: 'function quadIndices(quads: number): Uint16Array {\n  const out: number[] = [];\n  for (let q = 0; q < quads; q++) {\n    const b = q * 4;\n    out.push(b, b + 1, b + 2, b + 2, b + 3, b);\n  }\n  return new Uint16Array(out);\n}\nconsole.log("indices: " + quadIndices(2).join(","));\n',
      expect: "indices: 0,1,2,2,3,0,4,5,6,6,7,4",
      fallback: String.raw`b\s*=\s*q\s*\*\s*4`,
      explain: L("Indices point at vertices, and each quad owns 4 of them. So quad q starts at vertex q * 4.", "Los índices apuntan a vértices, y cada quad tiene 4. Así, el quad q empieza en el vértice q * 4.", "番号は頂点をさす。四角形は頂点 4 つなので、q 番目は頂点 q * 4 から。"),
    },
  ],
};

// ─── 2.4 Painting by numbers ───────────────────────────────────────────────
const textures: LessonDef = {
  slug: "textures-and-uvs",
  title: L("Painting by numbers", "Pintar con números", "数字でぬり絵"),
  concept: "textures",
  mode: "lesson",
  xp: 75,
  enemy: "webgl/black-screen",
  enemyName: L("BLACK TEXTURE", "TEXTURA NEGRA", "まっくろテクスチャ"),
  beats: [
    say(L(
      "A TEXTURE is an image the GPU samples. UV coords pick a point in it: (0, 0) is one corner, (1, 1) the opposite one.",
      "Una TEXTURA es una imagen que la GPU muestrea. Las coordenadas UV eligen un punto: (0, 0) es una esquina y (1, 1) la opuesta.",
      "テクスチャは GPU が読みとる画像。UV 座標でその中の点を選ぶ：(0, 0) が角、(1, 1) が反対の角。",
    )),
    {
      kind: "act",
      prompt: L("Find the texel under a UV", "Halla el texel bajo un UV", "UV の下のテクセルを探そう"),
      steps: [
        { label: L("SIZE 4", "TAMAÑO 4", "サイズ 4"), line: "const size = 4;", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "size", value: "4" }] },
        { label: L("LOOKUP", "BUSCAR", "さがす"), line: "const texel = (u: number) => Math.min(Math.floor(u * size), size - 1);" },
        { label: L("MIDDLE", "MEDIO", "まんなか"), line: "console.log(texel(0.5));", effects: [{ t: "print", text: "2" }], output: "2" },
        { label: L("EDGE", "BORDE", "はし"), line: "console.log(texel(1));", effects: [{ t: "print", text: "3" }, { t: "say", actor: "hero", text: L("Clamped to 3!", "¡Limitado a 3!", "3 でストップ！") }], output: "3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const texel = (u: number, size: number) =>\n  Math.min(Math.floor(u * size), size - 1);\nconsole.log(texel(0.25, 8), texel(1, 8));",
      options: ["2 7", "2 8", "0.25 1"],
      answer: 0,
      output: "2 7",
      check: { compiles: true, stdout: "2 7" },
      explain: L("0.25 × 8 = 2. u = 1 would be texel 8, which doesn't exist, so it clamps to 7.", "0.25 × 8 = 2. u = 1 sería el texel 8, que no existe, así que se limita a 7.", "0.25 × 8 = 2。u = 1 だとテクセル 8 だけど存在しないので 7 におさめる。"),
      win: [{ t: "print", text: "2 7" }],
    },
    say(L(
      "Setup: createTexture, bindTexture(gl.TEXTURE_2D, tex), then texImage2D uploads the pixels. Same bind-then-act idea!",
      "Preparación: createTexture, bindTexture(gl.TEXTURE_2D, tex) y texImage2D sube los píxeles. ¡La misma idea de enlazar y actuar!",
      "準備：createTexture、bindTexture(gl.TEXTURE_2D, tex)、そして texImage2D でピクセルを送る。バインドしてから操作、同じだね！",
    )),
    {
      kind: "pick",
      prompt: L("Filter for crisp pixel art", "Filtro para pixel art nítido", "くっきりドット絵のフィルター"),
      code: "declare const gl: WebGL2RenderingContext;\n// crisp pixel art when zoomed in\ngl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.___);",
      options: ["NEAREST", "LINEAR"],
      answer: 0,
      check: { compiles: true },
      explain: L("NEAREST takes the closest texel, keeping hard pixel edges. LINEAR blends neighbors, which blurs.", "NEAREST toma el texel más cercano y mantiene bordes duros. LINEAR mezcla vecinos y desenfoca.", "NEAREST は一番近いテクセルでドットがくっきり。LINEAR はとなりとまぜるのでぼやける。"),
    },
    say(L(
      "MIPMAPS are smaller copies, each half the size, down to 1×1. A 256 texture has floor(log2(256)) + 1 levels.",
      "Los MIPMAPS son copias más chicas, cada una de la mitad, hasta 1×1. Una textura de 256 tiene floor(log2(256)) + 1 niveles.",
      "ミップマップは半分ずつ小さくしたコピーで、1×1 まで続く。256 のテクスチャは floor(log2(256)) + 1 段。",
    )),
    {
      kind: "predict",
      prompt: L("Mip levels of a 64×64 texture?", "¿Niveles mip de una textura 64×64?", "64×64 のミップは何段？"),
      code: "console.log(Math.floor(Math.log2(64)) + 1);",
      options: ["7", "6", "64"],
      answer: 0,
      output: "7",
      check: { compiles: true, stdout: "7" },
      explain: L("64, 32, 16, 8, 4, 2, 1: seven levels. log2(64) = 6, plus the 1×1 level.", "64, 32, 16, 8, 4, 2, 1: siete niveles. log2(64) = 6, más el nivel 1×1.", "64、32、16、8、4、2、1 の 7 段。log2(64) = 6 に 1×1 の段を足す。"),
      win: [{ t: "print", text: "7" }],
    },
    say(L(
      "WebGL1 can only mipmap power-of-two sizes, like 256 or 512. Test it with a bit trick: (n & (n - 1)) === 0.",
      "WebGL1 solo hace mipmaps con tamaños potencia de dos, como 256 o 512. Pruébalo con un truco de bits: (n & (n - 1)) === 0.",
      "WebGL1 のミップマップは 256 や 512 のような 2 のべき乗だけ。ビット技で判定：(n & (n - 1)) === 0。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const isPow2 = (n: number) => (n & (n - 1)) === 0;\nconsole.log([256, 300, 1].map(isPow2).join(","));',
      options: ["true,false,true", "true,false,false", "true,true,true"],
      answer: 0,
      output: "true,false,true",
      check: { compiles: true, stdout: "true,false,true" },
      explain: L("A power of two has a single 1 bit, and n - 1 flips every bit below it. 1 is 2⁰, so it counts.", "Una potencia de dos tiene un solo bit en 1, y n - 1 invierte los de abajo. 1 es 2⁰, así que cuenta.", "2 のべき乗は 1 のビットが 1 つだけ。n - 1 でその下が反転する。1 は 2⁰ なので true。"),
    },
    say(L(
      "Trap! The default MIN filter needs mipmaps. No mipmaps? The texture is incomplete and samples BLACK.",
      "¡Trampa! El filtro MIN por defecto necesita mipmaps. ¿Sin mipmaps? La textura queda incompleta y se ve NEGRA.",
      "ワナ！既定の MIN フィルターはミップマップが必要。なければテクスチャは不完全で、まっくろになる。",
    )),
    {
      kind: "predict",
      prompt: L("WebGL1, 300×200 image: why black?", "WebGL1, imagen 300×200: ¿por qué negro?", "WebGL1、300×200：なぜ黒い？"),
      code: "gl.bindTexture(gl.TEXTURE_2D, tex);\ngl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, img);\n// no texParameteri calls",
      options: [L("Default MIN filter needs mipmaps", "El filtro MIN pide mipmaps", "既定の MIN がミップ必須"), L("The image is too big", "La imagen es muy grande", "画像が大きすぎる")],
      answer: 0,
      explain: L("The default is NEAREST_MIPMAP_LINEAR. Set MIN_FILTER to LINEAR and wrap to CLAMP_TO_EDGE for NPOT.", "El valor por defecto es NEAREST_MIPMAP_LINEAR. Pon MIN_FILTER en LINEAR y wrap en CLAMP_TO_EDGE para NPOT.", "既定は NEAREST_MIPMAP_LINEAR。2 のべき乗でない画像は MIN_FILTER を LINEAR、wrap を CLAMP_TO_EDGE に。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "type",
      prompt: L("Trilinear: blend between mips", "Trilineal: mezcla entre mips", "トライリニア：段の間もまぜる"),
      code: "declare const gl: WebGL2RenderingContext;\ngl.generateMipmap(gl.TEXTURE_2D);\ngl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.___);",
      answer: "LINEAR_MIPMAP_LINEAR",
      check: { compiles: true },
      hint: L("LINEAR inside a level, LINEAR between levels.", "LINEAR dentro del nivel, LINEAR entre niveles.", "段の中も段の間も LINEAR。"),
      explain: L("The first word filters inside a mip level, the last one blends between two levels.", "La primera palabra filtra dentro de un nivel mip; la última mezcla entre dos niveles.", "前の語はミップの段の中、後ろの語は 2 つの段の間のまぜ方。"),
    },
    say(L(
      "Shaders read textures through UNITS: activeTexture(gl.TEXTURE0 + n), then uniform1i(samplerLoc, n).",
      "Los shaders leen texturas por UNIDADES: activeTexture(gl.TEXTURE0 + n) y luego uniform1i(samplerLoc, n).",
      "シェーダーはユニット経由でテクスチャを読む：activeTexture(gl.TEXTURE0 + n)、それから uniform1i(samplerLoc, n)。",
    )),
    {
      kind: "predict",
      prompt: L("What does the 2 mean here?", "¿Qué significa el 2 aquí?", "この 2 の意味は？"),
      code: "gl.activeTexture(gl.TEXTURE2);\ngl.bindTexture(gl.TEXTURE_2D, rockTex);\ngl.uniform1i(samplerLoc, 2);",
      options: [L("The sampler reads unit 2", "El sampler lee la unidad 2", "サンプラーがユニット 2 を読む"), L("The texture is 2 px wide", "La textura mide 2 px", "テクスチャの幅が 2px")],
      answer: 0,
      explain: L("A sampler uniform holds a unit number. rockTex sits in unit 2, so the sampler reads it.", "Un uniform sampler guarda un número de unidad. rockTex está en la unidad 2, así que el sampler la lee.", "サンプラーの uniform はユニット番号。rockTex はユニット 2 にあるので、それを読む。"),
    },
    {
      kind: "pick",
      prompt: L("The image shows upside down", "La imagen sale al revés", "画像が上下さかさま"),
      code: "declare const gl: WebGL2RenderingContext;\n// before texImage2D\ngl.pixelStorei(gl.___, true);",
      options: ["UNPACK_FLIP_Y_WEBGL", "UNPACK_ALIGNMENT"],
      answer: 0,
      check: { compiles: true },
      explain: L("Images store row 0 at the top, textures at v = 0. UNPACK_FLIP_Y_WEBGL flips rows on upload.", "Las imágenes guardan la fila 0 arriba y las texturas en v = 0. UNPACK_FLIP_Y_WEBGL invierte las filas al subir.", "画像は 0 行目が上、テクスチャは v = 0。UNPACK_FLIP_Y_WEBGL で送るときに行を反転する。"),
    },
    {
      kind: "run",
      prompt: L("Count the 1×1 level too", "Cuenta también el nivel 1×1", "1×1 の段も数えよう"),
      starter: 'function mipLevels(width: number, height: number): number {\n  return Math.floor(Math.log2(Math.max(width, height)));\n}\nconsole.log("levels: " + mipLevels(1024, 512));\n',
      solution: 'function mipLevels(width: number, height: number): number {\n  return Math.floor(Math.log2(Math.max(width, height))) + 1;\n}\nconsole.log("levels: " + mipLevels(1024, 512));\n',
      expect: "levels: 11",
      fallback: [String.raw`\)\s*\+\s*1\s*;`, String.raw`1\s*\+\s*Math\.floor`],
      explain: L("1024 halves 10 times to reach 1, so there are 10 + 1 = 11 levels counting the original.", "1024 se divide a la mitad 10 veces hasta llegar a 1: con el original son 10 + 1 = 11 niveles.", "1024 は 10 回半分にして 1 になる。元の段を入れて 10 + 1 = 11 段。"),
    },
  ],
};

// ─── 2.5 Boss: Buffer Hydra ────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "buffer-hydra",
  title: L("Boss: Buffer Hydra", "Jefe: Hidra Buffer", "ボス：バッファヒドラ"),
  concept: "buffers",
  mode: "boss",
  xp: 170,
  enemy: "dragon",
  enemyName: L("BUFFER HYDRA", "HIDRA BUFFER", "バッファヒドラ"),
  beats: [
    enemySays(L(
      "I AM THE BUFFER HYDRA. Miss one byte and I grow another head. Wrap one index and your mesh is mine!",
      "SOY LA HIDRA BUFFER. Fallas un byte y me crece otra cabeza. ¡Si un índice da la vuelta, tu malla es mía!",
      "我はバッファヒドラ。1 バイトまちがえれば首が増える。番号が一周すれば、メッシュは我のもの！",
    )),
    { kind: "predict", time: 15, prompt: L("Position, normal, uv: stride?", "Posición, normal, uv: ¿stride?", "位置・法線・UV のストライドは？"), code: "// x y z, nx ny nz, u v (floats)\nconsole.log((3 + 3 + 2) * 4);", options: ["32", "8", "24"], answer: 0, output: "32", check: { compiles: true, stdout: "32" }, explain: L("8 floats × 4 bytes = 32.", "8 floats × 4 bytes = 32.", "float 8 個 × 4 バイト = 32。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "console.log(new Uint16Array([65536])[0]);", options: ["0", "65536", "65535"], answer: 0, output: "0", check: { compiles: true, stdout: "0" }, explain: L("16 bits wrap: 65536 becomes 0.", "16 bits dan la vuelta: 65536 es 0.", "16 ビットは一周：65536 は 0。") },
    { kind: "predict", time: 15, prompt: L("Where does it read from?", "¿De dónde lee?", "どこから読む？"), code: "gl.bindBuffer(gl.ARRAY_BUFFER, posBuf);\ngl.vertexAttribPointer(loc, 3, gl.FLOAT, false, 0, 0);", options: [L("The buffer bound now: posBuf", "El enlazado ahora: posBuf", "今バインド中の posBuf"), L("The last created buffer", "El último buffer creado", "最後に作ったバッファ")], answer: 0, explain: L("It captures ARRAY_BUFFER at call time.", "Captura ARRAY_BUFFER en ese momento.", "呼んだ時の ARRAY_BUFFER をつかむ。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "declare const gl: WebGL2RenderingContext;\ngl.bufferData(gl.ARRAY_BUFFER, [1, 2], gl.STATIC_DRAW);", options: [YES, NO_TSC], answer: 1, check: { compiles: false }, explain: L("TS2769: pass a typed array, not a JS array.", "TS2769: pasa un typed array, no un array de JS.", "TS2769：JS 配列でなく型付き配列を。") },
    { kind: "predict", time: 12, prompt: L("Mip levels of a 512 texture?", "¿Niveles mip de una de 512?", "512 のミップは何段？"), code: "console.log(Math.floor(Math.log2(512)) + 1);", options: ["10", "9", "512"], answer: 0, output: "10", check: { compiles: true, stdout: "10" }, explain: L("log2(512) = 9, plus the 1×1 level.", "log2(512) = 9, más el nivel 1×1.", "log2(512) = 9 に 1×1 を足す。") },
    { kind: "pick", time: 15, prompt: L("Indices for 100 000 vertices", "Índices para 100 000 vértices", "頂点 10 万個の番号"), code: "declare const count: number;\nconst indices = new ___(count);", options: ["Uint32Array", "Uint16Array"], answer: 0, check: { compiles: true }, explain: L("Uint16 stops at 65535; use Uint32Array with UNSIGNED_INT.", "Uint16 llega a 65535; usa Uint32Array con UNSIGNED_INT.", "Uint16 は 65535 まで。Uint32Array と UNSIGNED_INT を。") },
    { kind: "type", time: 15, prompt: L("Uint16Array indices: type?", "Índices Uint16Array: ¿type?", "Uint16Array の type は？"), code: "declare const gl: WebGL2RenderingContext;\ndeclare const count: number;\n// the index buffer is a Uint16Array\ngl.drawElements(gl.TRIANGLES, count, gl.___, 0);", answer: "UNSIGNED_SHORT", check: { compiles: true }, explain: L("16-bit indices are UNSIGNED_SHORT.", "Los índices de 16 bits son UNSIGNED_SHORT.", "16 ビットの番号は UNSIGNED_SHORT。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "const texel = (u: number, size: number) =>\n  Math.min(Math.floor(u * size), size - 1);\nconsole.log(texel(0.75, 4));", options: ["3", "4", "2"], answer: 0, output: "3", check: { compiles: true, stdout: "3" }, explain: L("0.75 × 4 = 3, inside 0..3.", "0.75 × 4 = 3, dentro de 0..3.", "0.75 × 4 = 3、0..3 の中。") },
    { kind: "predict", time: 15, prompt: L("Normalized byte 51 becomes…", "El byte normalizado 51 es…", "正規化した 51 は？"), code: "console.log((51 / 255).toFixed(1));", options: ["0.2", "0.5", "51.0"], answer: 0, output: "0.2", check: { compiles: true, stdout: "0.2" }, explain: L("51 / 255 = 0.2 exactly.", "51 / 255 = 0.2 exacto.", "51 / 255 = ちょうど 0.2。") },
    { kind: "predict", time: 15, prompt: L("Two quads: which indices?", "Dos quads: ¿qué índices?", "四角形 2 つの番号は？"), code: 'const quads = 2;\nconst out: number[] = [];\nfor (let q = 0; q < quads; q++) out.push(q * 4, q * 4 + 1, q * 4 + 2);\nconsole.log(out.join(","));', options: ["0,1,2,4,5,6", "0,1,2,6,7,8", "0,1,2,3,4,5"], answer: 0, output: "0,1,2,4,5,6", check: { compiles: true, stdout: "0,1,2,4,5,6" }, explain: L("Each quad starts 4 vertices later.", "Cada quad empieza 4 vértices después.", "四角形ごとに頂点 4 つずつ進む。") },
    enemySays(L(
      "All my heads... packed, strided and indexed. Take the bytes, then. Matrix Mountain looms ahead.",
      "Todas mis cabezas... empacadas, con stride e indexadas. Llévate los bytes. Más allá se alza la Montaña Matriz.",
      "わが首がすべて…つめられ、並べられ、番号をふられた。バイトは持っていけ。その先にマトリックス山がそびえる。",
    )),
  ],
};

export const bufferForest: RegionDef = {
  slug: "buffer-forest",
  name: L("Buffer Forest", "Bosque de Buffers", "バッファの森"),
  subtitle: L("Buffers · attributes · indices · UVs", "Buffers · attributes · índices · UV", "バッファ・属性・インデックス・テクスチャ"),
  theme: "forest",
  lessons: [typedArrays, attributes, indexed, textures, boss],
};
