import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 3 · MATRIX MOUNTAIN  (matrices and transforms, projection and depth, normals and lighting,
// framebuffers, performance and context loss). The runner has no GPU: runnable claims are pure math,
// WebGL API usage is proven by type-checking against `declare const gl: WebGL2RenderingContext`.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");
const GL = "declare const gl: WebGL2RenderingContext;\n";

// ─── 3.1 The order of spells: matrices and transforms ──────────────────────
const matrices: LessonDef = {
  slug: "matrices-and-transforms",
  title: L("The order of spells", "El orden de los hechizos", "呪文の順番"),
  concept: "matrices",
  mode: "lesson",
  xp: 75,
  enemy: "webgl/shader-goblin",
  enemyName: L("ORDER GOBLIN", "DUENDE DEL ORDEN", "ジュンバンゴブリン"),
  beats: [
    say(L(
      "Welcome to Matrix Mountain! A 4×4 MATRIX is a magic key: 16 numbers that move, turn and scale a point in one go.",
      "¡Bienvenido a Matrix Mountain! Una MATRIZ 4×4 es una llave mágica: 16 números que mueven, giran y escalan un punto.",
      "マトリクス山へようこそ！4×4 の行列は魔法のカギ。16 個の数で点を動かし、回し、拡大できるよ。",
    )),
    {
      kind: "act",
      prompt: L("Forge the keys, then move the point", "Forja las llaves y mueve el punto", "カギを作って、点を動かそう"),
      steps: [
        { label: L("IDENTITY", "IDENTIDAD", "単位行列"), line: "const I = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "I" }, { t: "say", actor: "hero", text: L("Changes nothing", "No cambia nada", "何も変えない") }] },
        { label: L("TRANSLATE", "TRASLADAR", "平行移動"), line: "const T = [1,0,0,0, 0,1,0,0, 0,0,1,0, 5,0,0,1];", effects: [{ t: "tag", actor: "hero", text: "T" }, { t: "say", actor: "hero", text: L("tx is at index 12!", "¡tx en el índice 12!", "tx は 12 番！") }] },
        { label: L("MOVE POINT", "MOVER PUNTO", "点を動かす"), line: "console.log(apply(T, [1, 2, 3]).join(\",\"));", effects: [{ t: "enter", actor: "ally" }, { t: "value", actor: "ally", text: "6,2,3" }, { t: "print", text: "6,2,3" }], output: "6,2,3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const I = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];\nconsole.log(I[0] + I[5] + I[10] + I[15]);",
      options: ["4", "1", "16"],
      answer: 0,
      output: "4",
      check: { compiles: true, stdout: "4" },
      explain: L("The identity has 1 on the diagonal (indices 0, 5, 10, 15) and 0 elsewhere: 1+1+1+1.", "La identidad tiene 1 en la diagonal (índices 0, 5, 10, 15) y 0 en el resto: 1+1+1+1.", "単位行列は対角（0, 5, 10, 15 番）が 1、ほかは 0。1+1+1+1 だよ。"),
      win: [{ t: "print", text: "4" }],
    },
    say(L(
      "WebGL reads matrices COLUMN by COLUMN (column-major). The last column, tx ty tz 1, sits at indices 12 to 15.",
      "WebGL lee las matrices COLUMNA por COLUMNA (column-major). La última columna, tx ty tz 1, va en los índices 12 a 15.",
      "WebGL は行列を「列ごと」に読む（列優先）。最後の列 tx ty tz 1 は 12〜15 番だよ。",
    )),
    {
      kind: "pick",
      prompt: L("Read tx from the translation", "Lee tx de la traslación", "平行移動から tx を読もう"),
      code: "const tx = 5;\nconst T = [1,0,0,0, 0,1,0,0, 0,0,1,0, tx,0,0,1];\nconsole.log(T[___]);",
      options: ["12", "3", "15"],
      answer: 0,
      check: { compiles: true, stdout: "5" },
      explain: L("Column-major: column 4 starts at index 12, so tx is T[12]. Index 3 is where a row-major layout would put it.", "Column-major: la columna 4 empieza en el índice 12, así que tx es T[12]. El 3 sería en row-major.", "列優先では 4 列目が 12 番から始まるので tx は T[12]。3 番は行優先の場合だよ。"),
      win: [{ t: "print", text: "5" }],
    },
    say(L(
      "ORDER matters! In P * V * M * pos the key nearest the point acts first: model, then view, then projection.",
      "¡El ORDEN importa! En P * V * M * pos actúa primero la llave más cercana al punto: model, luego view, luego projection.",
      "順番が大事！P * V * M * pos では点に近いカギが先に効く。model、view、projection の順だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const T = (p: number) => p + 10;\nconst S = (p: number) => p * 2;\nconsole.log(T(S(1)), S(T(1)));",
      options: ["12 22", "22 12", "12 12"],
      answer: 0,
      output: "12 22",
      check: { compiles: true, stdout: "12 22" },
      explain: L("T(S(1)) scales first: 1*2+10 = 12. S(T(1)) moves first: (1+10)*2 = 22. Swapping keys changes the result.", "T(S(1)) escala primero: 1*2+10 = 12. S(T(1)) mueve primero: (1+10)*2 = 22. Cambiar el orden cambia el resultado.", "T(S(1)) は先に拡大：1*2+10 = 12。S(T(1)) は先に移動：(1+10)*2 = 22。順番で結果が変わる。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }],
      win: [{ t: "print", text: "12 22" }, { t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const log: string[] = [];\nconst M = (p: number) => { log.push("model"); return p; };\nconst V = (p: number) => { log.push("view"); return p; };\nconst P = (p: number) => { log.push("projection"); return p; };\nP(V(M(0)));\nconsole.log(log.join(" > "));',
      options: ["model > view > projection", "projection > view > model", "view > model > projection"],
      answer: 0,
      output: "model > view > projection",
      check: { compiles: true, stdout: "model > view > projection" },
      explain: L("Like P * V * M * pos, the innermost call runs first: the model places the object, view moves it in front of the camera.", "Como P * V * M * pos, la llamada más interna corre primero: model coloca el objeto, view lo pone ante la cámara.", "P * V * M * pos と同じく内側が先。model で物を置き、view でカメラの前へ運ぶよ。"),
      win: [{ t: "print", text: "model > view > projection" }],
    },
    say(L(
      "The 4th number is w. Points use w = 1, so translation moves them. Directions use w = 0: they turn, but never move.",
      "El 4.º número es w. Los puntos usan w = 1 y la traslación los mueve. Las direcciones usan w = 0: giran pero no se mueven.",
      "4 つ目の数は w。点は w = 1 なので平行移動で動く。方向は w = 0 で、回転はしても移動しないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const tx = 5;\nconst apply = (x: number, w: number) => x + tx * w;\nconsole.log(apply(1, 1), apply(1, 0));",
      options: ["6 1", "6 6", "1 1"],
      answer: 0,
      output: "6 1",
      check: { compiles: true, stdout: "6 1" },
      explain: L("Translation is multiplied by w. A point (w = 1) moves to 6; a direction (w = 0) stays 1, as a normal or arrow should.", "La traslación se multiplica por w. Un punto (w = 1) va a 6; una dirección (w = 0) queda en 1, como debe una normal.", "平行移動は w 倍される。点（w = 1）は 6 へ、方向（w = 0）は 1 のまま。法線などはこれでいい。"),
      win: [{ t: "print", text: "6 1" }],
    },
    {
      kind: "predict",
      prompt: L("Rotate (1, 0) by 90°", "Gira (1, 0) 90°", "(1, 0) を 90° 回すと？"),
      code: "const rot = (x: number, y: number, a: number) =>\n  [x * Math.cos(a) - y * Math.sin(a), x * Math.sin(a) + y * Math.cos(a)];\nconsole.log(rot(1, 0, Math.PI / 2).map((n) => n.toFixed(2)).join(\",\"));",
      options: ["0.00,1.00", "1.00,0.00", "0.00,-1.00"],
      answer: 0,
      output: "0.00,1.00",
      check: { compiles: true, stdout: "0.00,1.00" },
      explain: L("A quarter turn counter-clockwise sends +x to +y. toFixed hides the tiny float error in cos(90°).", "Un cuarto de vuelta antihorario lleva +x a +y. toFixed oculta el pequeño error de cos(90°).", "反時計回りに 90° 回すと +x は +y へ。cos(90°) の小さな誤差は toFixed で隠すよ。"),
      win: [{ t: "print", text: "0.00,1.00" }],
    },
    say(L(
      "Send a matrix to the shader with uniformMatrix4fv. The array is already column-major, so transpose must be false.",
      "Envía una matriz al shader con uniformMatrix4fv. El array ya es column-major, así que transpose debe ser false.",
      "行列は uniformMatrix4fv でシェーダーへ送る。配列はもう列優先なので transpose は false だよ。",
    )),
    {
      kind: "type",
      prompt: L("No transpose needed", "Sin transponer", "転置はいらない"),
      code: GL + "declare const loc: WebGLUniformLocation | null;\nconst model = new Float32Array(16);\ngl.uniformMatrix4fv(loc, ___, model);",
      answer: "false",
      check: { compiles: true },
      explain: L("WebGL1 requires false here (true is an error). Build your arrays column-major and always pass false.", "WebGL1 exige false aquí (true da error). Arma tus arrays en column-major y pasa siempre false.", "WebGL1 ではここは false 必須（true はエラー）。配列を列優先で作り、いつも false を渡そう。"),
    },
    {
      kind: "run",
      prompt: L("Fix the translation: it must print (6, 2, 3)", "Arregla la traslación: debe imprimir (6, 2, 3)", "平行移動を直して (6, 2, 3) と表示させよう"),
      starter: "function translation(tx: number, ty: number, tz: number): number[] {\n  return [1, 0, 0, tx, 0, 1, 0, ty, 0, 0, 1, tz, 0, 0, 0, 1];\n}\nfunction transformPoint(m: number[], [x, y, z]: number[]): number[] {\n  return [\n    m[0] * x + m[4] * y + m[8] * z + m[12],\n    m[1] * x + m[5] * y + m[9] * z + m[13],\n    m[2] * x + m[6] * y + m[10] * z + m[14],\n  ];\n}\nconsole.log(\"(\" + transformPoint(translation(5, 0, 0), [1, 2, 3]).join(\", \") + \")\");\n",
      solution: "function translation(tx: number, ty: number, tz: number): number[] {\n  return [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, tx, ty, tz, 1];\n}\nfunction transformPoint(m: number[], [x, y, z]: number[]): number[] {\n  return [\n    m[0] * x + m[4] * y + m[8] * z + m[12],\n    m[1] * x + m[5] * y + m[9] * z + m[13],\n    m[2] * x + m[6] * y + m[10] * z + m[14],\n  ];\n}\nconsole.log(\"(\" + transformPoint(translation(5, 0, 0), [1, 2, 3]).join(\", \") + \")\");\n",
      expect: "(6, 2, 3)",
      fallback: String.raw`0\s*,\s*0\s*,\s*1\s*,\s*0\s*,\s*tx\s*,\s*ty\s*,\s*tz\s*,\s*1`,
      explain: L("The starter wrote tx ty tz row-major. In column-major they go at indices 12, 13, 14: [..., tx, ty, tz, 1].", "El starter puso tx ty tz en row-major. En column-major van en los índices 12, 13, 14: [..., tx, ty, tz, 1].", "最初のコードは tx ty tz を行優先で置いていた。列優先では 12, 13, 14 番：[..., tx, ty, tz, 1]。"),
    },
  ],
};

// ─── 3.2 Near and far: projection, depth and blending ──────────────────────
const projection: LessonDef = {
  slug: "projection-and-depth",
  title: L("Near and far", "Cerca y lejos", "近くと遠く"),
  concept: "depth_blending",
  mode: "lesson",
  xp: 75,
  enemy: "webgl/z-fighting",
  enemyName: L("Z-FIGHTER", "Z-FIGHTER", "Zファイター"),
  beats: [
    say(L(
      "A PERSPECTIVE matrix stores distance in w. Then the GPU divides x, y and z by w: far things shrink toward the center.",
      "Una matriz de PERSPECTIVA guarda la distancia en w. Luego la GPU divide x, y, z entre w: lo lejano se encoge al centro.",
      "透視投影の行列は距離を w に入れる。GPU が x, y, z を w で割るので、遠い物ほど中心へ縮むよ。",
    )),
    {
      kind: "act",
      prompt: L("Divide by w and watch the far actor shrink", "Divide entre w y mira encogerse al lejano", "w で割って、遠い仲間が縮むのを見よう"),
      steps: [
        { label: L("NEAR POINT", "PUNTO CERCA", "近い点"), line: "const near = [2, 0, 0, 2];", effects: [{ t: "tag", actor: "hero", text: "w=2" }] },
        { label: L("FAR POINT", "PUNTO LEJOS", "遠い点"), line: "const far = [2, 0, 0, 4];", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "w=4" }] },
        { label: L("DIVIDE", "DIVIDIR", "w で割る"), line: "console.log(near[0] / near[3], far[0] / far[3]);", effects: [{ t: "value", actor: "hero", text: "1" }, { t: "value", actor: "ally", text: "0.5" }, { t: "say", actor: "ally", text: L("I look smaller!", "¡Me veo más chico!", "小さく見える！") }, { t: "print", text: "1 0.5" }], output: "1 0.5" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const clip = [2, 4, 6, 2];\nconsole.log(clip.slice(0, 3).map((c) => c / clip[3]).join(\",\"));",
      options: ["1,2,3", "2,4,6", "4,8,12"],
      answer: 0,
      output: "1,2,3",
      check: { compiles: true, stdout: "1,2,3" },
      explain: L("The perspective divide: x, y and z are each divided by w = 2, giving normalized device coordinates.", "La división de perspectiva: x, y, z se dividen entre w = 2 y dan coordenadas normalizadas (NDC).", "透視除算で x, y, z をそれぞれ w = 2 で割り、正規化デバイス座標（NDC）になるよ。"),
      win: [{ t: "print", text: "1,2,3" }],
    },
    {
      kind: "predict",
      prompt: L("Projection [0], fov 90°, aspect 1 and 2", "Projection [0], fov 90°, aspect 1 y 2", "fov 90°、aspect 1 と 2 の [0]"),
      code: "const f = 1 / Math.tan((90 * Math.PI) / 180 / 2);\nconsole.log(f.toFixed(3), (f / 2).toFixed(3));",
      options: ["1.000 0.500", "0.500 1.000", "2.000 1.000"],
      answer: 0,
      output: "1.000 0.500",
      check: { compiles: true, stdout: "1.000 0.500" },
      explain: L("Element 0 is f / aspect, with f = 1 / tan(fov / 2). A wider canvas (aspect 2) squeezes x so circles stay round.", "El elemento 0 es f / aspect, con f = 1 / tan(fov / 2). Un canvas más ancho (aspect 2) comprime x.", "0 番は f / aspect（f = 1 / tan(fov / 2)）。横長（aspect 2）なら x を縮めて円を丸く保つ。"),
    },
    say(L(
      "Without the DEPTH TEST, whatever you draw last covers the rest. With it on, each pixel keeps the closest depth.",
      "Sin el DEPTH TEST, lo último que dibujas tapa lo demás. Activado, cada píxel guarda la profundidad más cercana.",
      "深度テストがないと、最後に描いた物が全部を隠す。オンなら各ピクセルは一番近い深度を残すよ。",
    )),
    {
      kind: "pick",
      prompt: L("Turn the depth test on", "Activa el depth test", "深度テストをオンにしよう"),
      code: GL + "gl.enable(gl.___);",
      options: ["DEPTH_TEST", "Z_BUFFER", "DEPTH_CHECK"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: L("gl.enable(gl.DEPTH_TEST) turns it on. gl.Z_BUFFER and gl.DEPTH_CHECK don't exist: TS2339.", "gl.enable(gl.DEPTH_TEST) lo activa. gl.Z_BUFFER y gl.DEPTH_CHECK no existen: TS2339.", "gl.enable(gl.DEPTH_TEST) でオン。gl.Z_BUFFER や gl.DEPTH_CHECK は存在しない（TS2339）。"),
    },
    {
      kind: "predict",
      prompt: L("depthFunc LESS: which color wins?", "depthFunc LESS: ¿qué color gana?", "depthFunc LESS：残る色は？"),
      code: 'let depth = 1;\nlet color = "sky";\nconst draw = (name: string, z: number) => {\n  if (z < depth) { depth = z; color = name; }\n};\ndraw("rock", 0.3);\ndraw("tree", 0.7);\nconsole.log(color);',
      options: ["rock", "tree", "sky"],
      answer: 0,
      output: "rock",
      check: { compiles: true, stdout: "rock" },
      explain: L("The tree is drawn later but is farther (0.7 > 0.3), so the LESS test rejects it. Closer wins, not later.", "El árbol se dibuja después pero está más lejos (0.7 > 0.3): el test LESS lo rechaza. Gana el más cercano.", "木は後に描いたけど遠い（0.7 > 0.3）ので LESS テストで捨てられる。勝つのは近い方だよ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "hero", text: "rock 0.3" }, { t: "tag", actor: "ally", text: "tree 0.7" }],
      win: [{ t: "dead", actor: "ally" }, { t: "print", text: "rock" }],
    },
    {
      kind: "type",
      prompt: L("Clear depth every frame too", "Limpia también la profundidad", "毎フレーム深度も消そう"),
      code: GL + "gl.clear(gl.COLOR_BUFFER_BIT | gl.___);",
      answer: "DEPTH_BUFFER_BIT",
      check: { compiles: true },
      explain: L("Old depths from the last frame would hide new pixels. Clear both bits each frame.", "Las profundidades del cuadro anterior ocultarían píxeles nuevos. Limpia ambos bits en cada cuadro.", "前のフレームの深度が残ると新しいピクセルが隠れる。毎フレーム両方のビットを消そう。"),
    },
    say(L(
      "Z-FIGHTING: two surfaces get the same depth value and flicker. A tiny near plane wastes precision. Push near out!",
      "Z-FIGHTING: dos superficies reciben la misma profundidad y parpadean. Un near diminuto gasta precisión. ¡Aléjalo!",
      "Zファイティング：2つの面が同じ深度になりチラつく。near が小さすぎると精度のムダ。near を遠ざけよう！",
    )),
    {
      kind: "predict",
      prompt: L("16-bit depth: same bucket?", "Profundidad 16 bits: ¿mismo valor?", "16bit 深度：同じ値になる？"),
      code: "const depth = (z: number, n: number, f: number) => (1 / n - 1 / z) / (1 / n - 1 / f);\nconst bucket = (z: number, n: number) => Math.round(depth(z, n, 1000) * 65535);\nconst same = (n: number) => bucket(100, n) === bucket(100.5, n);\nconsole.log(same(0.01), same(1));",
      options: ["true false", "false true", "true true"],
      answer: 0,
      output: "true false",
      check: { compiles: true, stdout: "true false" },
      explain: L("With near 0.01 the walls at 100 and 100.5 get the same depth: z-fighting. With near 1 they separate.", "Con near 0.01 los muros a 100 y 100.5 reciben la misma profundidad: z-fighting. Con near 1 se separan.", "near 0.01 だと 100 と 100.5 の壁が同じ深度になりZファイティング。near 1 なら分かれる。"),
      win: [{ t: "shake" }, { t: "print", text: "true false" }],
    },
    say(L(
      "BLENDING mixes colors: src × a + dst × (1 − a). Draw opaque things first, then transparent ones from back to front.",
      "El BLENDING mezcla colores: src × a + dst × (1 − a). Dibuja primero lo opaco y luego lo transparente de atrás hacia adelante.",
      "ブレンドは色を混ぜる：src × a + dst × (1 − a)。不透明な物を先に、透明な物は奥から手前へ描こう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const blend = (s: number, d: number, a: number) => Math.round(s * a + d * (1 - a));\nconsole.log(blend(255, 0, 0.5));",
      options: ["128", "255", "0"],
      answer: 0,
      output: "128",
      check: { compiles: true, stdout: "128" },
      explain: L("Half of 255 plus half of 0 is 127.5, rounded to 128: a half-transparent layer.", "La mitad de 255 más la mitad de 0 es 127.5, redondeado a 128: una capa semitransparente.", "255 の半分と 0 の半分で 127.5、丸めて 128。半透明の重なりだよ。"),
    },
    {
      kind: "type",
      prompt: L("Classic alpha blending", "Blending alfa clásico", "定番のアルファブレンド"),
      code: GL + "gl.enable(gl.BLEND);\ngl.blendFunc(gl.SRC_ALPHA, gl.___);",
      answer: "ONE_MINUS_SRC_ALPHA",
      check: { compiles: true },
      explain: L("SRC_ALPHA weighs the new color by a; ONE_MINUS_SRC_ALPHA weighs what's behind by 1 − a.", "SRC_ALPHA pondera el color nuevo por a; ONE_MINUS_SRC_ALPHA pondera lo de atrás por 1 − a.", "SRC_ALPHA は新しい色に a を、ONE_MINUS_SRC_ALPHA は奥の色に 1 − a をかけるよ。"),
    },
    {
      kind: "predict",
      prompt: L("In what order are they drawn?", "¿En qué orden se dibujan?", "描く順番は？"),
      code: 'const objs = [\n  { n: "glass", z: 2, alpha: true },\n  { n: "wall", z: 9, alpha: false },\n  { n: "mist", z: 5, alpha: true },\n];\nconst opaque = objs.filter((o) => !o.alpha);\nconst clear = objs.filter((o) => o.alpha).sort((a, b) => b.z - a.z);\nconsole.log([...opaque, ...clear].map((o) => o.n).join(" > "));',
      options: ["wall > mist > glass", "glass > mist > wall", "wall > glass > mist"],
      answer: 0,
      output: "wall > mist > glass",
      check: { compiles: true, stdout: "wall > mist > glass" },
      explain: L("Opaque first, then transparent sorted far to near (bigger z first), so each layer blends over what's behind it.", "Primero lo opaco, luego lo transparente de lejos a cerca (z mayor primero): cada capa se mezcla con lo de atrás.", "不透明が先、透明は遠い順（z が大きい順）。それぞれが奥の色と正しく混ざるよ。"),
    },
    {
      kind: "run",
      prompt: L("Fix the blend: it must print blend: 191,0,64", "Arregla la mezcla: debe imprimir blend: 191,0,64", "ブレンドを直して blend: 191,0,64 と表示させよう"),
      starter: "type RGB = [number, number, number];\nfunction blend(src: RGB, dst: RGB, a: number): RGB {\n  return src.map((s, i) => Math.round(s * (1 - a) + dst[i] * a)) as RGB;\n}\nconsole.log(\"blend: \" + blend([255, 0, 0], [0, 0, 255], 0.75).join(\",\"));\n",
      solution: "type RGB = [number, number, number];\nfunction blend(src: RGB, dst: RGB, a: number): RGB {\n  return src.map((s, i) => Math.round(s * a + dst[i] * (1 - a))) as RGB;\n}\nconsole.log(\"blend: \" + blend([255, 0, 0], [0, 0, 255], 0.75).join(\",\"));\n",
      expect: "blend: 191,0,64",
      fallback: [String.raw`s\s*\*\s*a\s*\+\s*dst\[i\]\s*\*\s*\(\s*1\s*-\s*a\s*\)`, String.raw`dst\[i\]\s*\*\s*\(\s*1\s*-\s*a\s*\)\s*\+\s*s\s*\*\s*a`],
      explain: L("The weights were swapped. SRC_ALPHA, ONE_MINUS_SRC_ALPHA means s × a + dst × (1 − a): 75% red on top.", "Los pesos estaban invertidos. SRC_ALPHA, ONE_MINUS_SRC_ALPHA es s × a + dst × (1 − a): 75% de rojo encima.", "重みが逆だった。SRC_ALPHA, ONE_MINUS_SRC_ALPHA は s × a + dst × (1 − a)。赤が 75% 上にのる。"),
    },
  ],
};

// ─── 3.3 Facing the sun: normals and lighting ──────────────────────────────
const lighting: LessonDef = {
  slug: "normals-and-lighting",
  title: L("Facing the sun", "De cara al sol", "太陽に向かって"),
  concept: "lighting",
  mode: "lesson",
  xp: 80,
  enemy: "webgl/black-screen",
  enemyName: L("SHADOW VOID", "VACÍO SOMBRÍO", "カゲノヤミ"),
  beats: [
    say(L(
      "A NORMAL is an arrow of length 1 that sticks straight out of a surface. It tells the light which way the face looks.",
      "Una NORMAL es una flecha de largo 1 que sale recta de una superficie. Le dice a la luz hacia dónde mira la cara.",
      "法線は面からまっすぐ出る長さ 1 の矢印。面がどっちを向いているかを光に教えるよ。",
    )),
    {
      kind: "act",
      prompt: L("Turn the face to the sun, then away", "Gira la cara al sol y luego dale la espalda", "面を太陽に向けて、次に背を向けよう"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "sun" }],
      steps: [
        { label: L("NORMAL UP", "NORMAL ARRIBA", "法線は上"), line: "const N = [0, 1, 0];", effects: [{ t: "tag", actor: "hero", text: "N" }] },
        { label: L("FACE SUN", "MIRAR AL SOL", "太陽を向く"), line: "console.log(dot(N, [0, 1, 0]));", effects: [{ t: "hp", actor: "hero", value: 100 }, { t: "say", actor: "hero", text: L("So bright!", "¡Qué brillo!", "まぶしい！") }, { t: "print", text: "1" }], output: "1" },
        { label: L("TURN AWAY", "DAR LA ESPALDA", "背を向ける"), line: "console.log(dot(N, [0, -1, 0]));", effects: [{ t: "hp", actor: "hero", value: 0 }, { t: "shake" }, { t: "print", text: "-1" }], output: "-1" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const dot = (a: number[], b: number[]) => a.reduce((s, v, i) => s + v * b[i], 0);\nconsole.log(dot([0, 1, 0], [0, 1, 0]), dot([0, 1, 0], [1, 0, 0]), dot([0, 1, 0], [0, -1, 0]));",
      options: ["1 0 -1", "1 1 1", "0 1 0"],
      answer: 0,
      output: "1 0 -1",
      check: { compiles: true, stdout: "1 0 -1" },
      explain: L("For unit vectors, dot = cos of the angle: same way 1, sideways 0, opposite -1.", "Con vectores unitarios, dot = coseno del ángulo: mismo sentido 1, de lado 0, opuesto -1.", "単位ベクトルなら dot は角度の cos。同じ向き 1、真横 0、逆向き -1。"),
      win: [{ t: "print", text: "1 0 -1" }],
    },
    say(L(
      "LAMBERT lighting: brightness = max(dot(N, L), 0). A face turned away gets 0, never a negative light.",
      "Luz LAMBERT: brillo = max(dot(N, L), 0). Una cara de espaldas recibe 0, nunca luz negativa.",
      "ランバート照明：明るさ = max(dot(N, L), 0)。背を向けた面は 0、マイナスにはならないよ。",
    )),
    {
      kind: "predict",
      prompt: L("Light behind the face: brightness?", "Luz detrás de la cara: ¿brillo?", "光が面の裏側：明るさは？"),
      code: "console.log(Math.max(-0.5, 0));",
      options: ["0", "-0.5", "0.5"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("max(…, 0) clamps the negative dot. Without it, faces in shadow would subtract light.", "max(…, 0) recorta el dot negativo. Sin él, las caras en sombra restarían luz.", "max(…, 0) でマイナスの dot を 0 に切る。ないと影の面が光を引いてしまう。"),
    },
    {
      kind: "predict",
      prompt: L("Brightness at 60° from the light", "Brillo a 60° de la luz", "光から 60° の明るさ"),
      code: "console.log(Math.cos(Math.PI / 3).toFixed(2));",
      options: ["0.50", "0.87", "1.00"],
      answer: 0,
      output: "0.50",
      check: { compiles: true, stdout: "0.50" },
      explain: L("dot of unit vectors is cos(angle), and cos 60° = 0.5: the face gets half the light.", "El dot de unitarios es cos(ángulo), y cos 60° = 0.5: la cara recibe la mitad de la luz.", "単位ベクトルの dot は cos(角度)。cos 60° = 0.5 なので光は半分だよ。"),
    },
    say(L(
      "A face normal comes from the CROSS product of two edges. Swap the edges and the normal flips to the other side!",
      "La normal de una cara sale del producto CRUZ de dos aristas. ¡Si cambias el orden, la normal apunta al otro lado!",
      "面の法線は2つの辺の外積で求める。辺の順番を入れかえると法線は反対を向くよ！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const cross = (a: number[], b: number[]) =>\n  [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];\nconsole.log(cross([1, 0, 0], [0, 1, 0]).join(\",\"), cross([0, 1, 0], [1, 0, 0]).join(\",\"));",
      options: ["0,0,1 0,0,-1", "0,0,1 0,0,1", "1,1,0 1,1,0"],
      answer: 0,
      output: "0,0,1 0,0,-1",
      check: { compiles: true, stdout: "0,0,1 0,0,-1" },
      explain: L("x × y = +z, but y × x = -z. The order of the edges (the winding) decides which way the face points.", "x × y = +z, pero y × x = -z. El orden de las aristas (el winding) decide hacia dónde mira la cara.", "x × y = +z、y × x = -z。辺の順番（巻き方向）で面の向きが決まるよ。"),
      win: [{ t: "print", text: "0,0,1 0,0,-1" }],
    },
    say(L(
      "Lambert needs BOTH vectors of length 1. Normalize: divide each part by the length, Math.hypot(x, y, z).",
      "Lambert necesita AMBOS vectores de largo 1. Normaliza: divide cada parte por el largo, Math.hypot(x, y, z).",
      "ランバートは両方のベクトルが長さ 1 であることが必要。各成分を長さ Math.hypot(x, y, z) で割って正規化しよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const v = [3, 4, 0];\nconst len = Math.hypot(...v);\nconsole.log(len, v.map((n) => (n / len).toFixed(2)).join(\",\"));",
      options: ["5 0.60,0.80,0.00", "7 0.43,0.57,0.00", "5 3,4,0"],
      answer: 0,
      output: "5 0.60,0.80,0.00",
      check: { compiles: true, stdout: "5 0.60,0.80,0.00" },
      explain: L("hypot(3, 4, 0) = 5 (3-4-5 triangle). Dividing by 5 keeps the direction with length 1.", "hypot(3, 4, 0) = 5 (triángulo 3-4-5). Dividir entre 5 mantiene la dirección con largo 1.", "hypot(3, 4, 0) = 5（3-4-5 の三角形）。5 で割ると向きはそのまま長さ 1 になる。"),
    },
    {
      kind: "predict",
      prompt: L("Halfway between two unit normals: length?", "A mitad de dos normales: ¿largo?", "2つの法線の中間：長さは？"),
      code: "const a = [1, 0, 0];\nconst b = [0, 1, 0];\nconst mid = a.map((v, i) => (v + b[i]) / 2);\nconsole.log(Math.hypot(...mid).toFixed(3));",
      options: ["0.707", "1.000", "0.500"],
      answer: 0,
      output: "0.707",
      check: { compiles: true, stdout: "0.707" },
      explain: L("Interpolated normals get SHORTER than 1. That's why the fragment shader normalizes them again.", "Las normales interpoladas quedan más CORTAS que 1. Por eso el fragment shader las normaliza otra vez.", "補間された法線は 1 より短くなる。だからフラグメントシェーダーで正規化し直すんだ。"),
    },
    {
      kind: "predict",
      prompt: L("Ambient 0.2: what does a dark face get?", "Ambiente 0.2: ¿qué recibe la cara oscura?", "環境光 0.2：裏の面の明るさは？"),
      code: "const light = (d: number) => 0.2 + 0.8 * Math.max(d, 0);\nconsole.log(light(-1), light(1));",
      options: ["0.2 1", "0 1", "-0.6 1"],
      answer: 0,
      output: "0.2 1",
      check: { compiles: true, stdout: "0.2 1" },
      explain: L("The AMBIENT term keeps faces turned away from going pure black; the rest of the light comes from Lambert.", "El término AMBIENTE evita que las caras de espaldas queden negras; el resto de la luz viene de Lambert.", "環境光の項で、背を向けた面も真っ黒にならない。残りの光はランバートから来るよ。"),
    },
    {
      kind: "run",
      prompt: L("Normalize the light: it must print light 1.00", "Normaliza la luz: debe imprimir light 1.00", "光を正規化して light 1.00 と表示させよう"),
      starter: "type V3 = [number, number, number];\nconst dot = (a: V3, b: V3) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];\nfunction lambert(normal: V3, toLight: V3): number {\n  return Math.max(dot(normal, toLight), 0);\n}\nconsole.log(\"light \" + lambert([0, 1, 0], [0, 2, 0]).toFixed(2));\n",
      solution: "type V3 = [number, number, number];\nconst dot = (a: V3, b: V3) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];\nconst normalize = (v: V3): V3 => {\n  const l = Math.hypot(...v);\n  return [v[0] / l, v[1] / l, v[2] / l];\n};\nfunction lambert(normal: V3, toLight: V3): number {\n  return Math.max(dot(normalize(normal), normalize(toLight)), 0);\n}\nconsole.log(\"light \" + lambert([0, 1, 0], [0, 2, 0]).toFixed(2));\n",
      expect: "light 1.00",
      fallback: [String.raw`normalize\s*\(\s*toLight\s*\)`, String.raw`Math\.hypot\s*\(\s*\.\.\.\s*toLight\s*\)`, String.raw`Math\.hypot\s*\(\s*toLight\[0\]`],
      explain: L("The light vector had length 2, so the face looked twice as bright. Normalize it before the dot.", "El vector de luz medía 2, así que la cara brillaba el doble. Normalízalo antes del dot.", "光のベクトルの長さが 2 で、明るさが2倍になっていた。dot の前に正規化しよう。"),
    },
  ],
};

// ─── 3.4 The forge and the courier: framebuffers, performance, context loss
const performance: LessonDef = {
  slug: "framebuffers-and-performance",
  title: L("The forge and the courier", "La forja y el mensajero", "工房と配達人"),
  concept: "performance",
  mode: "lesson",
  xp: 85,
  enemy: "webgl/black-screen",
  enemyName: L("LOST CONTEXT", "CONTEXTO PERDIDO", "ロストコンテキスト"),
  beats: [
    say(L(
      "A FRAMEBUFFER lets you paint into a texture instead of the screen: blur, glow, shadow maps and mouse picking.",
      "Un FRAMEBUFFER te deja pintar en una textura en vez de la pantalla: blur, brillo, mapas de sombra y selección con el mouse.",
      "フレームバッファを使うと画面ではなくテクスチャに描ける。ぼかし、光、影、マウス選択に使うよ。",
    )),
    {
      kind: "act",
      prompt: L("Paint into the texture, then back to the screen", "Pinta en la textura y vuelve a la pantalla", "テクスチャに描いて、画面にもどろう"),
      steps: [
        { label: L("CREATE FB", "CREAR FB", "FB を作る"), line: "const fb = gl.createFramebuffer();", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "fb" }] },
        { label: L("BIND FB", "ENLAZAR FB", "FB をバインド"), line: "gl.bindFramebuffer(gl.FRAMEBUFFER, fb);", effects: [{ t: "enter", actor: "ally" }, { t: "give", to: "ally" }] },
        { label: L("ATTACH TEX", "UNIR TEXTURA", "テクスチャ接続"), line: "gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0);", effects: [{ t: "say", actor: "ally", text: L("Paint goes here!", "¡Pinto aquí!", "ここに描く！") }] },
        { label: L("BACK TO SCREEN", "A LA PANTALLA", "画面にもどる"), line: "gl.bindFramebuffer(gl.FRAMEBUFFER, null);", effects: [{ t: "give", to: "hero" }, { t: "banner", text: L("SCREEN AGAIN", "PANTALLA OTRA VEZ", "画面にもどった") }] },
      ],
    },
    {
      kind: "pick",
      prompt: L("Draw to the canvas again", "Vuelve a dibujar en el canvas", "キャンバスに描きもどそう"),
      code: GL + "gl.bindFramebuffer(gl.FRAMEBUFFER, ___);",
      options: ["null", "undefined"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: L("Binding null returns to the default framebuffer, the canvas. undefined is not allowed (TS2345).", "Enlazar null vuelve al framebuffer por defecto, el canvas. undefined no se permite (TS2345).", "null をバインドすると標準のフレームバッファ（キャンバス）にもどる。undefined は型エラー（TS2345）。"),
    },
    {
      kind: "type",
      prompt: L("Is the framebuffer ready?", "¿Está listo el framebuffer?", "フレームバッファは準備OK？"),
      code: GL + 'if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.___) {\n  console.log("framebuffer incomplete");\n}',
      answer: "FRAMEBUFFER_COMPLETE",
      check: { compiles: true },
      explain: L("checkFramebufferStatus returns FRAMEBUFFER_COMPLETE when the attachments are valid. Check once after setup.", "checkFramebufferStatus devuelve FRAMEBUFFER_COMPLETE si los adjuntos son válidos. Revísalo una vez al configurar.", "接続が正しければ checkFramebufferStatus は FRAMEBUFFER_COMPLETE を返す。準備のあと一度だけ確認しよう。"),
    },
    say(L(
      "Every DRAW CALL is a trip from the CPU to the GPU. 1000 rocks in 1000 calls is slow. INSTANCING draws them all in one.",
      "Cada DRAW CALL es un viaje de la CPU a la GPU. 1000 rocas en 1000 llamadas es lento. El INSTANCING las dibuja en una.",
      "ドローコールは CPU から GPU への往復。岩 1000 個に 1000 回は遅い。インスタンシングなら 1 回で全部描けるよ。",
    )),
    {
      kind: "predict",
      prompt: L("Draw calls with one instanced call per mesh type", "Draw calls con una instanciada por tipo", "メッシュの種類ごとに1回なら何回？"),
      code: 'const objs = ["tree", "tree", "rock", "tree", "rock"];\nconsole.log(new Set(objs).size);',
      options: ["2", "5", "3"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("A Set keeps unique values: tree and rock. One instanced draw per type gives 2 calls instead of 5.", "Un Set guarda valores únicos: tree y rock. Una llamada instanciada por tipo da 2 en vez de 5.", "Set は重複を消して tree と rock だけ残す。種類ごとに1回なら 5 回ではなく 2 回だよ。"),
      win: [{ t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: L("Divisor 1: which offset does vertex 1 of instance 2 read?", "Divisor 1: ¿qué offset lee el vértice 1 de la instancia 2?", "divisor 1：インスタンス2の頂点1は？"),
      code: "const offsets = [10, 20, 30];\nconst read = (vertex: number, instance: number, divisor: number) =>\n  divisor === 0 ? offsets[vertex] : offsets[Math.floor(instance / divisor)];\nconsole.log(read(1, 2, 1), read(1, 2, 0));",
      options: ["30 20", "20 30", "20 20"],
      answer: 0,
      output: "30 20",
      check: { compiles: true, stdout: "30 20" },
      explain: L("vertexAttribDivisor(loc, 1) advances the attribute once per INSTANCE; divisor 0 (default) advances per vertex.", "vertexAttribDivisor(loc, 1) avanza el atributo una vez por INSTANCIA; divisor 0 (por defecto) avanza por vértice.", "vertexAttribDivisor(loc, 1) は属性をインスタンスごとに進める。divisor 0（標準）は頂点ごと。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "declare const gl1: WebGLRenderingContext;\ngl1.drawArraysInstanced(gl1.TRIANGLES, 0, 3, 100);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2339: WebGL1 has no drawArraysInstanced. It's core in WebGL2; WebGL1 needs the ANGLE_instanced_arrays extension.", "TS2339: WebGL1 no tiene drawArraysInstanced. Es parte de WebGL2; WebGL1 necesita la extensión ANGLE_instanced_arrays.", "TS2339：WebGL1 に drawArraysInstanced はない。WebGL2 では標準、WebGL1 は ANGLE_instanced_arrays 拡張が必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: L("Bytes of one mat4 per instance, 1000 instances", "Bytes de un mat4 por instancia, 1000 instancias", "1000 個ぶんの mat4 のバイト数"),
      code: "const floatsPerMat4 = 16;\nconsole.log(1000 * floatsPerMat4 * Float32Array.BYTES_PER_ELEMENT);",
      options: ["64000", "16000", "4000"],
      answer: 0,
      output: "64000",
      check: { compiles: true, stdout: "64000" },
      explain: L("A mat4 is 16 floats of 4 bytes = 64 bytes. 1000 instances need 64000 bytes: tiny compared to 1000 draw calls.", "Un mat4 son 16 floats de 4 bytes = 64 bytes. 1000 instancias ocupan 64000 bytes: poco frente a 1000 draw calls.", "mat4 は 4 バイトの float が 16 個で 64 バイト。1000 個で 64000 バイト。1000 回の描画より安い。"),
    },
    {
      kind: "pick",
      prompt: L("Which call should NOT run every frame?", "¿Qué llamada NO debe correr cada cuadro?", "毎フレーム呼ぶべきでないのは？"),
      code: GL + "declare const prog: WebGLProgram;\nfunction frame() {\n  gl.useProgram(prog);\n  gl.drawArrays(gl.TRIANGLES, 0, 3);\n  console.log(gl.___());\n}",
      options: ["getError", "flush", "isContextLost"],
      answer: 0,
      check: { compiles: true },
      explain: L("getError forces the CPU to wait for the GPU. Use it while debugging, not in the production loop.", "getError obliga a la CPU a esperar a la GPU. Úsalo al depurar, no en el bucle de producción.", "getError は CPU に GPU を待たせる。デバッグ中だけ使い、本番のループでは呼ばないで。"),
    },
    say(L(
      "The browser may take the GPU away: CONTEXT LOST! Every buffer, texture and program is gone. You must rebuild them.",
      "El navegador puede quitarte la GPU: ¡CONTEXT LOST! Cada buffer, textura y programa desaparece. Debes reconstruirlos.",
      "ブラウザが GPU を取り上げることがある。コンテキストロスト！バッファもテクスチャも消えるので作り直そう。",
    )),
    {
      kind: "act",
      prompt: L("Lose the context, then bring it back", "Pierde el contexto y recupéralo", "コンテキストを失って、取りもどそう"),
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "buffers" }],
      steps: [
        { label: L("LISTEN LOST", "OÍR LOST", "lost を待つ"), line: 'canvas.addEventListener("webglcontextlost", (e) => {', effects: [{ t: "dead", actor: "hero" }, { t: "shake" }, { t: "banner", text: L("CONTEXT LOST", "CONTEXT LOST", "コンテキスト消失") }] },
        { label: L("ALLOW RESTORE", "PERMITIR", "復元を許可"), line: "  e.preventDefault();\n});", effects: [{ t: "say", actor: "hero", text: L("Please come back!", "¡Vuelve, por favor!", "もどってきて！") }] },
        { label: L("ON RESTORED", "AL VOLVER", "復元されたら"), line: 'canvas.addEventListener("webglcontextrestored", () => {', effects: [{ t: "untag", actor: "hero" }] },
        { label: L("REBUILD ALL", "RECONSTRUIR", "全部作り直す"), line: "  initBuffersTexturesPrograms();\n});", effects: [{ t: "tag", actor: "hero", text: "buffers" }, { t: "banner", text: L("REBUILT!", "¡RECONSTRUIDO!", "復活！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'declare const canvas: HTMLCanvasElement;\ncanvas.addEventListener("webglcontextlost", (e) => {\n  console.log(e.statusMessage);\n});',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2339: on a canvas this listener gets a plain Event. Cast it, e as WebGLContextEvent, to read statusMessage.", "TS2339: en un canvas este listener recibe un Event común. Conviértelo, e as WebGLContextEvent, para leer statusMessage.", "TS2339：キャンバスのこのリスナーはただの Event を受け取る。e as WebGLContextEvent にして statusMessage を読もう。"),
    },
    {
      kind: "pick",
      prompt: L("Read the reason the context was lost", "Lee por qué se perdió el contexto", "ロストの理由を読もう"),
      code: 'declare const canvas: HTMLCanvasElement;\ncanvas.addEventListener("webglcontextlost", (e) => {\n  e.preventDefault();\n  console.log((e as ___).statusMessage);\n});',
      options: ["WebGLContextEvent", "Event", "MouseEvent"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: L("WebGLContextEvent has statusMessage; Event and MouseEvent don't (TS2339). preventDefault() lets the context come back.", "WebGLContextEvent tiene statusMessage; Event y MouseEvent no (TS2339). preventDefault() deja que el contexto vuelva.", "statusMessage を持つのは WebGLContextEvent だけ（ほかは TS2339）。preventDefault() で復元できるようになる。"),
    },
    {
      kind: "run",
      prompt: L("Count instanced draws: it must print draw calls: 2", "Cuenta draws instanciados: debe imprimir draw calls: 2", "インスタンス描画を数えて draw calls: 2 と表示させよう"),
      starter: 'type Obj = { geometry: string; material: string };\nconst objs: Obj[] = [\n  { geometry: "tree", material: "bark" },\n  { geometry: "tree", material: "bark" },\n  { geometry: "tree", material: "bark" },\n  { geometry: "rock", material: "stone" },\n  { geometry: "rock", material: "stone" },\n];\nfunction drawCalls(list: Obj[]): number {\n  return list.length;\n}\nconsole.log("draw calls: " + drawCalls(objs));\n',
      solution: 'type Obj = { geometry: string; material: string };\nconst objs: Obj[] = [\n  { geometry: "tree", material: "bark" },\n  { geometry: "tree", material: "bark" },\n  { geometry: "tree", material: "bark" },\n  { geometry: "rock", material: "stone" },\n  { geometry: "rock", material: "stone" },\n];\nfunction drawCalls(list: Obj[]): number {\n  return new Set(list.map((o) => o.geometry + "|" + o.material)).size;\n}\nconsole.log("draw calls: " + drawCalls(objs));\n',
      expect: "draw calls: 2",
      fallback: [String.raw`new\s+Set\s*\(`, String.raw`\.filter\s*\(`],
      explain: L("Objects sharing geometry AND material can be one instanced draw. Count the unique pairs with a Set.", "Los objetos que comparten geometría Y material pueden ser un solo draw instanciado. Cuenta los pares únicos con un Set.", "ジオメトリとマテリアルが同じ物は1回のインスタンス描画にできる。Set でユニークな組を数えよう。"),
    },
  ],
};

// ─── 3.5 Boss: Matrix Titan ────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "matrix-titan",
  title: L("Boss: Matrix Titan", "Jefe: Titán Matriz", "ボス：マトリクスタイタン"),
  concept: "matrices",
  mode: "boss",
  xp: 190,
  enemy: "golem",
  enemyName: L("MATRIX TITAN", "TITÁN MATRIZ", "マトリクスタイタン"),
  beats: [
    enemySays(L(
      "I AM THE MATRIX TITAN. I swap your keys, steal your depth and blow out your lights. Can you keep the scene alive?",
      "SOY EL TITÁN MATRIZ. Cambio tus llaves, robo tu profundidad y apago tus luces. ¿Podrás mantener viva la escena?",
      "我はマトリクスタイタン。カギを入れかえ、深度を奪い、光を消す。シーンを守りきれるか？",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "const T = (p: number) => p + 3;\nconst S = (p: number) => p * 4;\nconsole.log(T(S(1)), S(T(1)));", options: ["7 16", "16 7", "7 7"], answer: 0, output: "7 16", check: { compiles: true, stdout: "7 16" }, explain: L("Inner first: 1*4+3 = 7, then (1+3)*4 = 16.", "Primero lo interno: 1*4+3 = 7 y (1+3)*4 = 16.", "内側が先：1*4+3 = 7、(1+3)*4 = 16。") },
    { kind: "pick", time: 12, prompt: L("Where is ty?", "¿Dónde está ty?", "ty はどこ？"), code: "const ty = 7;\nconst T = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,ty,0,1];\nconsole.log(T[___]);", options: ["13", "7", "4"], answer: 0, check: { compiles: true, stdout: "7" }, explain: L("Column-major: tx ty tz are at 12, 13, 14.", "Column-major: tx ty tz van en 12, 13, 14.", "列優先：tx ty tz は 12, 13, 14 番。") },
    { kind: "predict", time: 12, prompt: L("Direction (w = 0) after tx = 5", "Dirección (w = 0) tras tx = 5", "方向（w = 0）に tx = 5"), code: "const tx = 5;\nconst apply = (x: number, w: number) => x + tx * w;\nconsole.log(apply(2, 0));", options: ["2", "7", "10"], answer: 0, output: "2", check: { compiles: true, stdout: "2" }, explain: L("w = 0 cancels translation: directions never move.", "w = 0 anula la traslación: las direcciones no se mueven.", "w = 0 で平行移動は消える。方向は動かない。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "const clip = [3, -3, 0, 3];\nconsole.log(clip.slice(0, 2).map((c) => c / clip[3]).join(\",\"));", options: ["1,-1", "3,-3", "9,-9"], answer: 0, output: "1,-1", check: { compiles: true, stdout: "1,-1" }, explain: L("Divide by w = 3: the point lands on a corner of NDC.", "Divide entre w = 3: el punto cae en una esquina de NDC.", "w = 3 で割ると NDC の角に来る。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "const blend = (s: number, d: number, a: number) => Math.round(s * a + d * (1 - a));\nconsole.log(blend(200, 100, 0.25));", options: ["125", "175", "150"], answer: 0, output: "125", check: { compiles: true, stdout: "125" }, explain: L("200 × 0.25 + 100 × 0.75 = 50 + 75 = 125.", "200 × 0.25 + 100 × 0.75 = 50 + 75 = 125.", "200 × 0.25 + 100 × 0.75 = 50 + 75 = 125。") },
    { kind: "type", time: 12, prompt: L("Closer pixels must win", "Deben ganar los más cercanos", "近いピクセルを勝たせよう"), code: GL + "gl.___(gl.DEPTH_TEST);", answer: "enable", check: { compiles: true }, explain: L("gl.enable turns on the depth test.", "gl.enable activa el depth test.", "gl.enable で深度テストをオン。") },
    { kind: "predict", time: 15, prompt: L("Lambert, light from below", "Lambert, luz desde abajo", "ランバート、光が下から"), code: "const dot = (a: number[], b: number[]) => a.reduce((s, v, i) => s + v * b[i], 0);\nconsole.log(Math.max(dot([0, 1, 0], [0, -1, 0]), 0));", options: ["0", "-1", "1"], answer: 0, output: "0", check: { compiles: true, stdout: "0" }, explain: L("dot is -1, clamped to 0: no negative light.", "dot es -1, recortado a 0: sin luz negativa.", "dot は -1、0 に切られる。") },
    { kind: "predict", time: 12, prompt: L("Draw calls for 1000 identical rocks, instanced", "Draw calls de 1000 rocas iguales, instanciadas", "同じ岩 1000 個、インスタンスなら？"), code: 'const rocks = new Array<string>(1000).fill("rock");\nconsole.log(new Set(rocks).size);', options: ["1", "1000", "0"], answer: 0, output: "1", check: { compiles: true, stdout: "1" }, explain: L("One mesh type, one instanced draw call.", "Un tipo de malla, un draw call instanciado.", "1 種類なら 1 回のインスタンス描画。") },
    { kind: "predict", time: 15, prompt: COMPILES, code: 'declare const canvas: HTMLCanvasElement;\ncanvas.addEventListener("webglcontextlost", (e) => {\n  e.preventDefault();\n});', options: [YES, NO_TSC], answer: 0, check: { compiles: true }, explain: L("Every Event has preventDefault: this allows a restore.", "Todo Event tiene preventDefault: así se permite restaurar.", "どの Event にも preventDefault がある。これで復元できる。") },
    { kind: "order", time: 20, prompt: L("Model, then view, then projection", "Model, luego view, luego projection", "model → view → projection の順に"), lines: ["let p = 1;", "p = p * 2; // model", "p = p - 5; // view", "p = p * 10; // projection", "console.log(p);"], check: { compiles: true, stdout: "-30" }, explain: L("The point meets model first and projection last: ((1×2)−5)×10 = −30.", "El punto pasa primero por model y al final por projection: ((1×2)−5)×10 = −30.", "点は model が最初、projection が最後：((1×2)−5)×10 = −30。") },
    enemySays(L(
      "Impossible... my keys in order, my depths sorted, my lights clamped. The GPU is yours, painter of Shadera.",
      "Imposible... mis llaves en orden, mis profundidades ordenadas, mis luces recortadas. La GPU es tuya, pintor de Shadera.",
      "ばかな…カギは順番通り、深度は整い、光は切りそろえられた。GPU はおまえのものだ、シェイデラの絵師よ。",
    )),
  ],
};

export const matrixMountain: RegionDef = {
  slug: "matrix-mountain",
  name: L("Matrix Mountain", "Montaña Matriz", "マトリクス山"),
  subtitle: L("Matrices · depth · light · speed", "Matrices · profundidad · luz · velocidad", "行列・深度・光・速度"),
  theme: "mountain",
  lessons: [matrices, projection, lighting, performance, boss],
};
