import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 1 · PIPELINE VILLAGE  (clip space, the GPU state machine, shaders and GLSL)
// The runner has no GPU: runnable claims are pure logic; WebGL API claims are type-checked only.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");
const GLSL_OK = L("Valid GLSL?", "¿GLSL válido?", "正しい GLSL？");

// ─── 1.1 The -1 to +1 world ────────────────────────────────────────────────
const clipSpace: LessonDef = {
  slug: "clip-space",
  title: L("The -1 to +1 world", "El mundo de -1 a +1", "-1 から +1 の世界"),
  concept: "clip_space",
  mode: "lesson",
  xp: 60,
  enemy: "webgl/black-screen",
  enemyName: L("BLACK VOID", "VACÍO NEGRO", "まっくろボイド"),
  beats: [
    say(L(
      "Welcome to Shadera! I'm Trix. WebGL draws in CLIP SPACE: x and y go from -1 to +1, whatever the canvas size.",
      "¡Bienvenido a Shadera! Soy Trix. WebGL dibuja en CLIP SPACE: x e y van de -1 a +1, sin importar el tamaño del canvas.",
      "シェイデラへようこそ！トリックスだよ。WebGL はクリップ空間で描く。x も y も -1 から +1。キャンバスの大きさは関係ない。",
    )),
    {
      kind: "act",
      prompt: L("Turn pixels into clip space", "Convierte píxeles a clip space", "ピクセルをクリップ空間に変えよう"),
      steps: [
        { label: L("WIDTH 800", "ANCHO 800", "幅 800"), line: "const w = 800;", effects: [{ t: "tag", actor: "hero", text: "w", value: "800" }] },
        { label: L("CONVERT", "CONVERTIR", "変換する"), line: "const toClipX = (px: number) => (px / w) * 2 - 1;", effects: [{ t: "item", kind: "scroll", holder: "hero" }] },
        { label: L("CENTER", "CENTRO", "まんなか"), line: "console.log(toClipX(400));", effects: [{ t: "say", actor: "hero", text: L("Center is 0!", "¡El centro es 0!", "中心は 0！") }, { t: "print", text: "0" }], output: "0" },
        { label: L("RIGHT EDGE", "BORDE DER.", "右のはし"), line: "console.log(toClipX(800));", effects: [{ t: "print", text: "1" }, { t: "attack", from: "hero", to: "enemy" }], output: "1" },
      ],
    },
    {
      kind: "pick",
      prompt: L("Clip-space x starts at…", "Clip space x empieza en…", "クリップ空間の x の最小は？"),
      code: "// visible clip-space x range\nconst minX = ___;\nconst maxX = 1;",
      options: ["-1", "0", "0.5"],
      answer: 0,
      explain: L("Clip space runs from -1 to +1 on x and y, no matter how many pixels the canvas has.", "Clip space va de -1 a +1 en x e y, sin importar cuántos píxeles tenga el canvas.", "クリップ空間は x も y も -1 から +1。キャンバスのピクセル数は関係ないよ。"),
      win: [{ t: "tag", actor: "hero", text: "-1..+1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const toClipX = (px: number, w: number) => (px / w) * 2 - 1;\nconsole.log(toClipX(400, 800), toClipX(800, 800));",
      options: ["0 1", "400 800", "0.5 1"],
      answer: 0,
      output: "0 1",
      check: { compiles: true, stdout: "0 1" },
      explain: L("400/800 is 0.5, times 2 minus 1 is 0. The right edge (800) lands on +1.", "400/800 es 0.5; por 2 menos 1 da 0. El borde derecho (800) cae en +1.", "400/800 は 0.5。2 倍して 1 引くと 0。右のはし 800 は +1 になる。"),
      win: [{ t: "print", text: "0 1" }],
    },
    say(L(
      "Careful: pixel y grows DOWN, but clip y points UP. So flip it: 1 - (py / h) * 2.",
      "Cuidado: la y de los píxeles crece hacia ABAJO, pero la y de clip apunta ARRIBA. Inviértela: 1 - (py / h) * 2.",
      "注意！ピクセルの y は下へ増えるけど、クリップの y は上向き。だから反転：1 - (py / h) * 2。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const toClipY = (py: number, h: number) => 1 - (py / h) * 2;\nconsole.log(toClipY(0, 600), toClipY(600, 600));",
      options: ["1 -1", "-1 1", "0 600"],
      answer: 0,
      output: "1 -1",
      check: { compiles: true, stdout: "1 -1" },
      explain: L("Pixel row 0 is the top, which is clip +1. The bottom row (600) is clip -1.", "La fila 0 es arriba, que en clip es +1. La fila de abajo (600) es -1.", "ピクセルの 0 行目は一番上でクリップ +1。一番下 600 は -1 だよ。"),
      win: [{ t: "print", text: "1 -1" }],
    },
    {
      kind: "pick",
      prompt: L("Where is clip y = +1?", "¿Dónde está clip y = +1?", "クリップ y = +1 はどこ？"),
      code: "// clip space: y = +1 is the ___ edge",
      options: [L("top", "superior", "上"), L("bottom", "inferior", "下")],
      answer: 0,
      explain: L("Clip +y points up, like math graphs. Screen pixels count downward, hence the flip.", "En clip, +y apunta arriba, como en un gráfico. Los píxeles cuentan hacia abajo: por eso se invierte.", "クリップの +y は数学のグラフと同じ上向き。画面のピクセルは下へ数えるから反転するんだ。"),
    },
    say(L(
      "Outside -1..+1 nothing is drawn: it gets CLIPPED. gl.viewport maps -1..+1 onto the canvas pixels.",
      "Fuera de -1..+1 no se dibuja nada: se RECORTA (clipping). gl.viewport mapea -1..+1 a los píxeles del canvas.",
      "-1..+1 の外は描かれない。クリップ（切り取り）される。gl.viewport が -1..+1 をキャンバスのピクセルに対応させるよ。",
    )),
    {
      kind: "predict",
      prompt: L("Where does this vertex go?", "¿Adónde va este vértice?", "この頂点はどうなる？"),
      code: "// vertex shader output (GLSL)\n// gl_Position = vec4(1.5, 0.0, 0.0, 1.0);",
      options: [L("Clipped: off screen", "Recortado: fuera", "クリップされて消える"), L("Drawn at the right edge", "En el borde derecho", "右のはしに描かれる"), L("Wraps to -0.5", "Vuelve a -0.5", "-0.5 に回りこむ")],
      answer: 0,
      explain: L("x = 1.5 is past +1, so it's outside clip space. Geometry out there is cut away.", "x = 1.5 pasa de +1, así que queda fuera del clip space. Lo que está ahí se recorta.", "x = 1.5 は +1 をこえているのでクリップ空間の外。そこは切り取られるよ。"),
      win: [{ t: "dead", actor: "enemy" }, { t: "say", actor: "hero", text: L("Clipped!", "¡Recortado!", "クリップ！") }],
    },
    {
      kind: "type",
      prompt: L("Map clip space to the canvas", "Mapea el clip space al canvas", "クリップ空間をキャンバスへ"),
      code: "declare const gl: WebGL2RenderingContext;\ngl.___(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);",
      answer: "viewport",
      check: { compiles: true },
      explain: L("gl.viewport(x, y, width, height) sets which pixels -1..+1 covers. Use the drawing buffer size.", "gl.viewport(x, y, ancho, alto) define qué píxeles cubre -1..+1. Usa el tamaño del drawing buffer.", "gl.viewport(x, y, 幅, 高さ) で -1..+1 がどのピクセルにあたるか決める。描画バッファのサイズを使おう。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const ndcToPx = (x: number, w: number) => ((x + 1) / 2) * w;\nconsole.log(ndcToPx(0, 800), ndcToPx(-1, 800), ndcToPx(1, 800));",
      options: ["400 0 800", "0 -800 800", "400 800 0"],
      answer: 0,
      output: "400 0 800",
      check: { compiles: true, stdout: "400 0 800" },
      explain: L("This is what the viewport does: shift -1..+1 to 0..2, halve it, scale by the width.", "Es lo que hace el viewport: pasa -1..+1 a 0..2, lo divide entre 2 y escala por el ancho.", "viewport がやるのはこれ。-1..+1 を 0..2 にずらし、半分にして幅をかける。"),
      win: [{ t: "print", text: "400 0 800" }],
    },
    say(L(
      "The full trip: vertex shader, primitive assembly, rasterization, fragment shader, then depth and blend tests.",
      "El viaje completo: vertex shader, ensamblado de primitivas, rasterización, fragment shader y pruebas de profundidad y mezcla.",
      "全体の流れ：頂点シェーダー、プリミティブ組み立て、ラスタライズ、フラグメントシェーダー、深度とブレンドのテスト。",
    )),
    {
      kind: "order",
      prompt: L("Order the pipeline", "Ordena el pipeline", "パイプラインを並べよう"),
      lines: ["vertexShader();", "assemblePrimitives();", "rasterize();", "fragmentShader();", "depthAndBlendTests();"],
      explain: L("Vertices are placed, joined into triangles, turned into fragments, colored, then tested.", "Se ubican los vértices, se unen en triángulos, se vuelven fragmentos, se colorean y se prueban.", "頂点を置き、三角形につなぎ、フラグメントにして色をぬり、最後にテストする。"),
    },
    {
      kind: "run",
      prompt: L("Fix the Y flip: top-left must be -1,1", "Arregla la y: arriba a la izq. debe ser -1,1", "y を反転しよう：左上は -1,1"),
      starter: 'function pixelToClip(x: number, y: number, w: number, h: number): [number, number] {\n  return [(x / w) * 2 - 1, (y / h) * 2 - 1];\n}\nconsole.log("clip " + pixelToClip(0, 0, 400, 300).join(","));\n',
      solution: 'function pixelToClip(x: number, y: number, w: number, h: number): [number, number] {\n  return [(x / w) * 2 - 1, 1 - (y / h) * 2];\n}\nconsole.log("clip " + pixelToClip(0, 0, 400, 300).join(","));\n',
      expect: "clip -1,1",
      fallback: [String.raw`1\s*-\s*\(?\s*y\s*\/\s*h\s*\)?\s*\*\s*2`, String.raw`-\s*\(\s*\(?\s*y\s*\/\s*h\s*\)?\s*\*\s*2\s*-\s*1\s*\)`],
      explain: L("Pixel y grows down, clip y grows up: use 1 - (y / h) * 2 so row 0 becomes +1.", "La y de píxel crece hacia abajo y la de clip hacia arriba: usa 1 - (y / h) * 2 para que la fila 0 sea +1.", "ピクセルの y は下へ、クリップの y は上へ。1 - (y / h) * 2 で 0 行目が +1 になる。"),
    },
  ],
};

// ─── 1.2 The bound slot ────────────────────────────────────────────────────
const stateMachine: LessonDef = {
  slug: "gpu-state-machine",
  title: L("The bound slot", "La ranura enlazada", "バインドされた席"),
  concept: "gpu_state",
  mode: "lesson",
  xp: 65,
  enemy: "webgl/z-fighting",
  enemyName: L("BIND TWINS", "GEMELOS BIND", "バインドふたご"),
  beats: [
    say(L(
      "To draw, ask the canvas for a context: canvas.getContext(\"webgl2\"). No WebGL2 support? You get null.",
      "Para dibujar, pide un contexto al canvas: canvas.getContext(\"webgl2\"). ¿Sin soporte de WebGL2? Recibes null.",
      "描くにはキャンバスにコンテキストをもらう：canvas.getContext(\"webgl2\")。WebGL2 がなければ null が返るよ。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'declare const canvas: HTMLCanvasElement;\nconst gl = canvas.getContext("webgl2");\ngl.clearColor(0, 0, 0, 1);',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS18047: 'gl' is possibly 'null'. getContext returns null when WebGL2 is missing.", "Error TS18047: 'gl' is possibly 'null'. getContext devuelve null si no hay WebGL2.", "エラー TS18047：gl は null かもしれない。WebGL2 がないと getContext は null を返す。"),
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Null guard!", "¡Cuida el null!", "null に注意！") }],
    },
    {
      kind: "pick",
      prompt: L("Guard against null", "Protégete del null", "null をガードしよう"),
      code: 'declare const canvas: HTMLCanvasElement;\nconst gl = canvas.getContext("webgl2");\nif (___) throw new Error("no WebGL2");\ngl.clearColor(0, 0, 0, 1);',
      options: ["!gl", "gl", "gl === undefined"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: L("After if (!gl) throw, TypeScript knows gl is a WebGL2RenderingContext. The others leave null possible.", "Tras if (!gl) throw, TypeScript sabe que gl es un WebGL2RenderingContext. Las otras dejan posible el null.", "if (!gl) throw のあと、gl は WebGL2RenderingContext だと TS がわかる。ほかは null が残るよ。"),
      win: [{ t: "item", kind: "shield", holder: "hero" }],
    },
    say(L(
      "The context is a STATE MACHINE. You BIND an object to a slot like ARRAY_BUFFER, and later calls act on whatever is bound.",
      "El contexto es una MÁQUINA DE ESTADOS. ENLAZAS (bind) un objeto a una ranura como ARRAY_BUFFER y las llamadas siguientes usan lo enlazado.",
      "コンテキストは「状態機械」。ARRAY_BUFFER のような席にオブジェクトをバインドすると、後の命令はそこに座るものに効く。",
    )),
    {
      kind: "act",
      prompt: L("Bind, rebind, then upload", "Enlaza, vuelve a enlazar y sube", "バインド、つけかえ、アップロード"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "ARRAY_BUFFER" }],
      steps: [
        { label: L("BIND a", "ENLAZAR a", "a をバインド"), line: "gl.bindBuffer(gl.ARRAY_BUFFER, a);", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "give", to: "ally" }, { t: "value", actor: "ally", text: "a" }] },
        { label: L("BIND b", "ENLAZAR b", "b をバインド"), line: "gl.bindBuffer(gl.ARRAY_BUFFER, b);", effects: [{ t: "value", actor: "ally", text: "b" }, { t: "say", actor: "ally", text: L("Now I hold b!", "¡Ahora tengo b!", "いまは b！") }] },
        { label: L("UPLOAD", "SUBIR", "アップロード"), line: "gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);", effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("It went to b!", "¡Fue a b!", "b に入った！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: L("Which buffer gets the data?", "¿Qué buffer recibe los datos?", "データが入るバッファは？"),
      code: "gl.bindBuffer(gl.ARRAY_BUFFER, a);\ngl.bindBuffer(gl.ARRAY_BUFFER, b);\ngl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);",
      options: ["a", "b", L("Both", "Ambos", "両方")],
      answer: 1,
      explain: L("bufferData targets whatever sits in ARRAY_BUFFER right now: b replaced a.", "bufferData usa lo que esté en ARRAY_BUFFER en ese momento: b reemplazó a a.", "bufferData は今 ARRAY_BUFFER にあるものに効く。b が a と入れかわった。"),
      win: [{ t: "value", actor: "ally", text: "b" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const state = { program: "none" };\nconst use = (p: string) => { state.program = p; };\nuse("sky");\nuse("hero");\nconsole.log("drawing with " + state.program);',
      options: ["drawing with hero", "drawing with sky", "drawing with none"],
      answer: 0,
      output: "drawing with hero",
      check: { compiles: true, stdout: "drawing with hero" },
      explain: L("Like gl.useProgram: state stays until you change it, so the last call wins.", "Como gl.useProgram: el estado queda hasta que lo cambias, así que gana la última llamada.", "gl.useProgram と同じ。状態は変えるまで残るから、最後の呼び出しが勝つ。"),
      win: [{ t: "print", text: "drawing with hero" }],
    },
    say(L(
      "WebGL enums are plain numbers on the context: gl.TRIANGLES, gl.COLOR_BUFFER_BIT. Strings won't work.",
      "Los enums de WebGL son números del contexto: gl.TRIANGLES, gl.COLOR_BUFFER_BIT. Los strings no sirven.",
      "WebGL の列挙値はコンテキストにある数値：gl.TRIANGLES、gl.COLOR_BUFFER_BIT。文字列はダメ。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'declare const gl: WebGL2RenderingContext;\ngl.drawArrays("TRIANGLES", 0, 3);',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2345: a string is not a number. Write gl.TRIANGLES.", "Error TS2345: un string no es un number. Escribe gl.TRIANGLES.", "エラー TS2345：文字列は number じゃない。gl.TRIANGLES と書こう。"),
    },
    {
      kind: "type",
      prompt: L("Clear color AND depth", "Borra color Y profundidad", "色と深度を両方クリア"),
      code: "declare const gl: WebGL2RenderingContext;\ngl.clear(gl.COLOR_BUFFER_BIT ___ gl.DEPTH_BUFFER_BIT);",
      answer: "|",
      check: { compiles: true },
      explain: L("The bits are flags: | (bitwise OR) combines them into one number.", "Los bits son flags: | (OR bit a bit) los combina en un solo número.", "ビットはフラグ。| （ビット OR）で 1 つの数にまとめるよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const COLOR_BUFFER_BIT = 0x4000;\nconst DEPTH_BUFFER_BIT = 0x100;\nconsole.log(COLOR_BUFFER_BIT | DEPTH_BUFFER_BIT);",
      options: ["16640", "16384", "0"],
      answer: 0,
      output: "16640",
      check: { compiles: true, stdout: "16640" },
      explain: L("These are the real values: 16384 | 256 sets both bits, giving 16640.", "Son los valores reales: 16384 | 256 activa ambos bits y da 16640.", "これは本物の値。16384 | 256 で両方のビットが立ち 16640 になる。"),
      win: [{ t: "print", text: "16640" }],
    },
    {
      kind: "predict",
      prompt: L("What does this line do?", "¿Qué hace esta línea?", "この行は何をする？"),
      code: "gl.clearColor(1, 0, 0, 1);",
      options: [L("Sets the color for the next clear", "Fija el color del próximo clear", "次の clear の色を決める"), L("Paints the canvas red now", "Pinta el canvas de rojo ya", "今すぐ赤くぬる")],
      answer: 0,
      explain: L("clearColor only stores state. Nothing changes until gl.clear(gl.COLOR_BUFFER_BIT).", "clearColor solo guarda estado. Nada cambia hasta gl.clear(gl.COLOR_BUFFER_BIT).", "clearColor は状態を覚えるだけ。gl.clear(gl.COLOR_BUFFER_BIT) まで何も変わらない。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "declare const gl1: WebGLRenderingContext;\ngl1.createVertexArray();",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2339: WebGL1 has no createVertexArray. VAOs are core only in WebGL2.", "Error TS2339: WebGL1 no tiene createVertexArray. Los VAO son nativos solo en WebGL2.", "エラー TS2339：WebGL1 に createVertexArray はない。VAO が標準なのは WebGL2 だけ。"),
    },
    {
      kind: "run",
      prompt: L("Upload to A before binding B", "Sube a A antes de enlazar B", "B をバインドする前に A へ"),
      starter: 'class FakeGL {\n  bound = "";\n  sizes: Record<string, number> = { A: 0, B: 0 };\n  bindBuffer(name: string) { this.bound = name; }\n  bufferData(data: number[]) { this.sizes[this.bound] = data.length; }\n}\nconst gl = new FakeGL();\ngl.bindBuffer("A");\ngl.bindBuffer("B");\ngl.bufferData([1, 2, 3]); // meant for A\nconsole.log(`A=${gl.sizes.A} B=${gl.sizes.B}`);\n',
      solution: 'class FakeGL {\n  bound = "";\n  sizes: Record<string, number> = { A: 0, B: 0 };\n  bindBuffer(name: string) { this.bound = name; }\n  bufferData(data: number[]) { this.sizes[this.bound] = data.length; }\n}\nconst gl = new FakeGL();\ngl.bindBuffer("A");\ngl.bufferData([1, 2, 3]); // meant for A\ngl.bindBuffer("B");\nconsole.log(`A=${gl.sizes.A} B=${gl.sizes.B}`);\n',
      expect: "A=3 B=0",
      fallback: String.raw`bindBuffer\(\s*["']A["']\s*\)\s*;?\s*(\/\/[^\n]*\n\s*)?gl\.bufferData`,
      explain: L("bufferData hits whatever is bound. Upload right after binding A, then bind B.", "bufferData afecta a lo enlazado. Sube justo después de enlazar A y luego enlaza B.", "bufferData はバインド中のものに効く。A をバインドした直後にアップロードし、それから B。"),
    },
  ],
};

// ─── 1.3 Two spellbooks ────────────────────────────────────────────────────
const shaders: LessonDef = {
  slug: "shaders-and-glsl",
  title: L("Two spellbooks", "Dos libros de hechizos", "2 冊の呪文書"),
  concept: "shaders",
  mode: "lesson",
  xp: 70,
  enemy: "webgl/shader-goblin",
  enemyName: L("SHADER GOBLIN", "GOBLIN SHADER", "シェーダーゴブリン"),
  beats: [
    say(L(
      "SHADERS are tiny GPU programs written in GLSL. The VERTEX shader runs once per vertex and must set gl_Position.",
      "Los SHADERS son programitas para la GPU escritos en GLSL. El VERTEX shader corre una vez por vértice y debe fijar gl_Position.",
      "シェーダーは GLSL で書く GPU 用の小さなプログラム。頂点シェーダーは頂点ごとに 1 回動き、gl_Position を必ず決める。",
    )),
    {
      kind: "act",
      prompt: L("Write a vertex shader as a string", "Escribe un vertex shader como string", "頂点シェーダーを文字列で書こう"),
      steps: [
        { label: L("VERSION", "VERSIÓN", "バージョン"), line: "const vs = `#version 300 es", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "vs" }] },
        { label: L("INPUT", "ENTRADA", "入力"), line: "in vec4 a_position;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "a_position" }] },
        { label: L("MAIN", "MAIN", "main"), line: "void main() { gl_Position = a_position; }`;", effects: [{ t: "give", to: "ally" }, { t: "banner", text: L("COMPILED", "COMPILADO", "コンパイル成功") }] },
      ],
    },
    {
      kind: "pick",
      prompt: L("Which shader runs per vertex?", "¿Qué shader corre por vértice?", "頂点ごとに動くのは？"),
      code: "// runs once per vertex:\n// the ___ shader",
      options: ["vertex", "fragment"],
      answer: 0,
      explain: L("The vertex shader places each vertex in clip space. The fragment shader colors pixels.", "El vertex shader ubica cada vértice en clip space. El fragment shader colorea píxeles.", "頂点シェーダーは各頂点をクリップ空間に置く。フラグメントシェーダーはピクセルに色をぬる。"),
    },
    {
      kind: "type",
      prompt: L("What must the vertex shader set?", "¿Qué debe fijar el vertex shader?", "頂点シェーダーが決めるのは？"),
      code: "const vs = `#version 300 es\nin vec4 a_position;\nvoid main() { ___ = a_position; }`;",
      answer: "gl_Position",
      explain: L("gl_Position is the vertex's clip-space position. Without it, nothing appears.", "gl_Position es la posición del vértice en clip space. Sin ella, no aparece nada.", "gl_Position は頂点のクリップ空間の位置。書かないと何も出ないよ。"),
    },
    say(L(
      "The FRAGMENT shader runs once per fragment (a pixel to paint) and writes a color: out vec4 outColor.",
      "El FRAGMENT shader corre una vez por fragmento (un píxel a pintar) y escribe un color: out vec4 outColor.",
      "フラグメントシェーダーはフラグメント（ぬるピクセル）ごとに動き、色を書く：out vec4 outColor。",
    )),
    say(L(
      "A vec4 holds 4 floats. SWIZZLING picks parts by letter: v.zyx, c.rgb. Never mix the xyzw and rgba sets.",
      "Un vec4 tiene 4 floats. El SWIZZLING toma partes por letra: v.zyx, c.rgb. Nunca mezcles los grupos xyzw y rgba.",
      "vec4 は float 4 つ。スウィズルは文字で成分を選ぶ：v.zyx、c.rgb。xyzw と rgba の組は混ぜちゃダメ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const v = { x: 1, y: 2, z: 3, w: 4 };\n// like GLSL v.zyx\nconsole.log([..."zyx"].map((c) => v[c as keyof typeof v]).join(","));',
      options: ["3,2,1", "1,2,3", "4,3,2"],
      answer: 0,
      output: "3,2,1",
      check: { compiles: true, stdout: "3,2,1" },
      explain: L("Each letter picks one component, in order: z, y, x. In GLSL v.zyx is vec3(3.0, 2.0, 1.0).", "Cada letra toma un componente, en orden: z, y, x. En GLSL v.zyx es vec3(3.0, 2.0, 1.0).", "文字ごとに成分を順に選ぶ：z、y、x。GLSL なら v.zyx は vec3(3.0, 2.0, 1.0)。"),
      win: [{ t: "print", text: "3,2,1" }],
    },
    {
      kind: "predict",
      prompt: GLSL_OK,
      code: "// GLSL\nvec4 v = vec4(1.0, 2.0, 3.0, 4.0);\nvec2 a = v.xg;",
      options: [L("No: mixes xyzw and rgba", "No: mezcla xyzw y rgba", "いいえ：xyzw と rgba が混在"), L("Yes: gives vec2(1.0, 2.0)", "Sí: da vec2(1.0, 2.0)", "はい：vec2(1.0, 2.0)")],
      answer: 0,
      explain: L("x is from xyzw and g is from rgba. One swizzle must use a single set: v.xy or v.rg.", "x es de xyzw y g es de rgba. Un swizzle debe usar un solo grupo: v.xy o v.rg.", "x は xyzw、g は rgba の組。1 つのスウィズルは同じ組だけ：v.xy か v.rg。"),
    },
    say(L(
      "GLSL is strict: no int-to-float magic, so write 1.0, not 1. Fragment shaders also need: precision highp float;",
      "GLSL es estricto: no convierte int a float, así que escribe 1.0, no 1. El fragment shader además necesita: precision highp float;",
      "GLSL はきびしい。int は float に変わらないから 1 じゃなく 1.0。フラグメントには precision highp float; も必要。",
    )),
    {
      kind: "predict",
      prompt: GLSL_OK,
      code: "// GLSL ES 3.00\nfloat x = 1;",
      options: [L("No: 1 is an int", "No: 1 es un int", "いいえ：1 は int"), L("Yes: x is 1.0", "Sí: x vale 1.0", "はい：x は 1.0")],
      answer: 0,
      explain: L("GLSL ES has no implicit int-to-float conversion. Write float x = 1.0;", "GLSL ES no convierte int a float solo. Escribe float x = 1.0;", "GLSL ES は int を float に自動で変えない。float x = 1.0; と書こう。"),
    },
    {
      kind: "predict",
      prompt: GLSL_OK,
      code: "#version 300 es\n// no precision line\nout vec4 outColor;\nvoid main() { outColor = vec4(1.0); }",
      options: [L("No: no float precision", "No: falta la precisión", "いいえ：精度の指定がない"), L("Yes: it's a white fragment", "Sí: un fragmento blanco", "はい：白いフラグメント")],
      answer: 0,
      explain: L("Fragment shaders have no default float precision: add precision highp float; or it fails to build.", "El fragment shader no tiene precisión de float por defecto: agrega precision highp float; o falla.", "フラグメントシェーダーに float の既定精度はない。precision highp float; がないと失敗する。"),
    },
    say(L(
      "Data flows in three ways: in (per vertex), out to in (vertex to fragment) and uniform (one value for the whole draw).",
      "Los datos entran de tres formas: in (por vértice), out a in (de vértice a fragmento) y uniform (un valor para todo el dibujo).",
      "データの流れは 3 つ。in（頂点ごと）、out から in（頂点→フラグメント）、uniform（描画全体で 1 つの値）。",
    )),
    {
      kind: "pick",
      prompt: L("WebGL2 word for varying (vertex)", "Palabra WebGL2 para varying (vértice)", "WebGL2 で varying の代わり"),
      code: "// WebGL1: varying vec2 v_uv;\n// WebGL2 vertex shader:\n___ vec2 v_uv;",
      options: ["out", "in", "uniform"],
      answer: 0,
      explain: L("In WebGL2 the vertex shader writes out and the fragment shader reads the same name with in.", "En WebGL2 el vertex shader escribe out y el fragment shader lee el mismo nombre con in.", "WebGL2 では頂点シェーダーが out で書き、フラグメントが同じ名前を in で読む。"),
    },
    {
      kind: "predict",
      prompt: L("What is a uniform?", "¿Qué es un uniform?", "uniform とは？"),
      code: "// GLSL\nuniform vec4 u_color;",
      options: [L("Same value for the whole draw", "El mismo valor en todo el dibujo", "描画全体で同じ値"), L("A different value per vertex", "Un valor distinto por vértice", "頂点ごとにちがう値")],
      answer: 0,
      explain: L("A uniform is shared by every vertex and fragment in one draw call. Per-vertex data comes in with in.", "Un uniform es compartido por todo vértice y fragmento de un draw call. Lo de cada vértice entra con in.", "uniform は 1 回の描画ですべての頂点とフラグメントが共有。頂点ごとのデータは in で入る。"),
    },
    say(L(
      "Build it: create, source and compile each shader, then attach both, link and use. Check COMPILE_STATUS and LINK_STATUS.",
      "Constrúyelo: crea, carga y compila cada shader; luego adjunta ambos, enlaza y usa. Revisa COMPILE_STATUS y LINK_STATUS.",
      "組み立て：各シェーダーを作って入れてコンパイル、2 つをつけてリンクして使う。COMPILE_STATUS と LINK_STATUS を確認。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "declare const gl: WebGL2RenderingContext;\ndeclare const src: string;\nconst vs = gl.createShader(gl.VERTEX_SHADER);\ngl.shaderSource(vs, src);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2345: createShader returns WebGLShader | null. Check for null (or use !) first.", "Error TS2345: createShader devuelve WebGLShader | null. Primero verifica el null (o usa !).", "エラー TS2345：createShader は WebGLShader | null を返す。先に null を確認（か ! を使う）。"),
    },
    {
      kind: "order",
      prompt: L("Build and use a program", "Arma y usa un programa", "プログラムを作って使おう"),
      lines: [
        "const sh = gl.createShader(gl.VERTEX_SHADER)!;",
        "gl.shaderSource(sh, src);",
        "gl.compileShader(sh);",
        "const prog = gl.createProgram()!;",
        "gl.attachShader(prog, sh);",
        "gl.linkProgram(prog);",
        "gl.useProgram(prog);",
      ],
      check: {
        compiles: true,
        program: "declare const gl: WebGL2RenderingContext;\ndeclare const src: string;\nconst sh = gl.createShader(gl.VERTEX_SHADER)!;\ngl.shaderSource(sh, src);\ngl.compileShader(sh);\nconst prog = gl.createProgram()!;\ngl.attachShader(prog, sh);\ngl.linkProgram(prog);\ngl.useProgram(prog);",
      },
      explain: L("A shader needs its source before compiling; a program needs its shaders before linking.", "Un shader necesita su código antes de compilar; un programa, sus shaders antes de enlazar.", "シェーダーはコンパイル前にソース、プログラムはリンク前にシェーダーが必要。"),
    },
    {
      kind: "type",
      prompt: L("Did it compile?", "¿Se compiló?", "コンパイルできた？"),
      code: "declare const gl: WebGL2RenderingContext;\ndeclare const sh: WebGLShader;\nif (!gl.getShaderParameter(sh, gl.___)) {\n  console.log(gl.getShaderInfoLog(sh));\n}",
      answer: "COMPILE_STATUS",
      check: { compiles: true },
      explain: L("COMPILE_STATUS is false on a GLSL error; getShaderInfoLog tells you why.", "COMPILE_STATUS es false si hay un error de GLSL; getShaderInfoLog te dice por qué.", "GLSL エラーなら COMPILE_STATUS は false。理由は getShaderInfoLog で見られる。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "run",
      prompt: L("Make #version the very first line", "Haz que #version sea la primera línea", "#version を 1 行目にしよう"),
      starter: 'const vs = `\n#version 300 es\nin vec4 a_position;\nvoid main() { gl_Position = a_position; }`;\nfunction firstLineOk(src: string): boolean {\n  return src.split("\\n")[0] === "#version 300 es";\n}\nconsole.log("valid: " + firstLineOk(vs));\n',
      solution: 'const vs = `#version 300 es\nin vec4 a_position;\nvoid main() { gl_Position = a_position; }`;\nfunction firstLineOk(src: string): boolean {\n  return src.split("\\n")[0] === "#version 300 es";\n}\nconsole.log("valid: " + firstLineOk(vs));\n',
      expect: "valid: true",
      fallback: ["`#version 300 es", String.raw`\.trim(Start)?\(\)`],
      explain: L("The backtick is followed by a newline, so line 1 is empty. Start the text right after the backtick.", "Tras el backtick hay un salto de línea, así que la línea 1 está vacía. Empieza el texto justo tras el backtick.", "バッククォートの後に改行があるので 1 行目が空。バッククォートの直後から書こう。"),
    },
  ],
};

// ─── 1.4 Boss: Pipeline Golem ──────────────────────────────────────────────
const boss: LessonDef = {
  slug: "pipeline-golem",
  title: L("Boss: Pipeline Golem", "Jefe: Gólem Pipeline", "ボス：パイプラインゴーレム"),
  concept: "pipeline",
  mode: "boss",
  xp: 160,
  enemy: "golem",
  enemyName: L("PIPELINE GOLEM", "GÓLEM PIPELINE", "パイプゴーレム"),
  beats: [
    enemySays(L(
      "I AM THE PIPELINE GOLEM. Lose one sign, skip one check, and your screen stays BLACK forever!",
      "SOY EL GÓLEM PIPELINE. Pierde un signo, sáltate un chequeo, ¡y tu pantalla quedará NEGRA para siempre!",
      "我はパイプラインゴーレム。符号ひとつ、確認ひとつ忘れれば、画面は永遠にまっくろだ！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "const toClipY = (py: number, h: number) => 1 - (py / h) * 2;\nconsole.log(toClipY(300, 600));", options: ["0", "0.5", "-1"], answer: 0, output: "0", check: { compiles: true, stdout: "0" }, explain: L("The middle row is clip y = 0.", "La fila del medio es clip y = 0.", "まんなかの行はクリップ y = 0。") },
    { kind: "predict", time: 15, prompt: COMPILES, code: 'declare const canvas: HTMLCanvasElement;\nconst gl = canvas.getContext("webgl2");\ngl.clearColor(0, 0, 0, 1);', options: [YES, NO_TSC], answer: 1, check: { compiles: false }, explain: L("TS18047: gl may be null. Guard it first.", "TS18047: gl puede ser null. Protégelo antes.", "TS18047：gl は null かも。先にガード。") },
    { kind: "pick", time: 12, prompt: L("Who paints each pixel?", "¿Quién pinta cada píxel?", "ピクセルに色をぬるのは？"), code: "// decides each pixel's color:\n// the ___ shader", options: ["fragment", "vertex"], answer: 0, explain: L("The fragment shader outputs the color.", "El fragment shader da el color.", "色を出すのはフラグメントシェーダー。") },
    { kind: "predict", time: 12, prompt: L("What is a uniform?", "¿Qué es un uniform?", "uniform とは？"), code: "// GLSL\nuniform float u_time;", options: [L("Same value for the whole draw", "El mismo valor en todo el dibujo", "描画全体で同じ値"), L("A different value per vertex", "Un valor distinto por vértice", "頂点ごとにちがう値")], answer: 0, explain: L("Per-vertex data uses in, not uniform.", "Lo de cada vértice usa in, no uniform.", "頂点ごとのデータは in を使う。") },
    { kind: "type", time: 15, prompt: L("Did it link?", "¿Se enlazó?", "リンクできた？"), code: 'declare const gl: WebGL2RenderingContext;\ndeclare const prog: WebGLProgram;\nif (!gl.getProgramParameter(prog, gl.___)) {\n  throw new Error(gl.getProgramInfoLog(prog) ?? "");\n}', answer: "LINK_STATUS", check: { compiles: true }, explain: L("Programs report LINK_STATUS after linkProgram.", "Los programas informan LINK_STATUS tras linkProgram.", "linkProgram の後は LINK_STATUS を見る。") },
    { kind: "pick", time: 12, prompt: L("First line of a WebGL2 shader", "Primera línea de un shader WebGL2", "WebGL2 シェーダーの 1 行目"), code: "const fs = `___\nprecision highp float;\nout vec4 outColor;\nvoid main() { outColor = vec4(1.0); }`;", options: ["#version 300 es", "// my shader", "uniform float u_time;"], answer: 0, explain: L("#version 300 es must come before anything else.", "#version 300 es debe ir antes que todo.", "#version 300 es は何よりも先。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "const ndcToPx = (x: number, w: number) => ((x + 1) / 2) * w;\nconsole.log(ndcToPx(0.5, 800));", options: ["600", "400", "200"], answer: 0, output: "600", check: { compiles: true, stdout: "600" }, explain: L("(0.5 + 1) / 2 = 0.75, times 800 is 600.", "(0.5 + 1) / 2 = 0.75; por 800 da 600.", "(0.5 + 1) / 2 = 0.75、800 倍で 600。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "declare const gl: WebGL2RenderingContext;\ngl.drawArrays(gl.TRIANGLES, 0, 3);", options: [YES, NO_TSC], answer: 0, check: { compiles: true }, explain: L("gl.TRIANGLES is a number enum: correct.", "gl.TRIANGLES es un enum numérico: correcto.", "gl.TRIANGLES は数値の列挙値。正しい。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'let bound = "none";\nconst bind = (b: string) => { bound = b; };\nbind("grass");\nbind("sky");\nconsole.log("upload to " + bound);', options: ["upload to sky", "upload to grass", "upload to none"], answer: 0, output: "upload to sky", check: { compiles: true, stdout: "upload to sky" }, explain: L("The last bind wins, like ARRAY_BUFFER.", "Gana el último bind, como ARRAY_BUFFER.", "最後のバインドが勝つ。ARRAY_BUFFER と同じ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'const c = { r: 1, g: 0.5, b: 0, a: 1 };\n// like GLSL c.bgr\nconsole.log([..."bgr"].map((k) => c[k as keyof typeof c]).join(","));', options: ["0,0.5,1", "1,0.5,0", "0,1,0.5"], answer: 0, output: "0,0.5,1", check: { compiles: true, stdout: "0,0.5,1" }, explain: L("Swizzle order is letter order: b, g, r.", "El orden del swizzle es el de las letras: b, g, r.", "スウィズルは文字の順：b、g、r。") },
    enemySays(L(
      "My stones... clipped, bound and linked. The pipeline flows. The Buffer Forest awaits you.",
      "Mis piedras... recortadas, enlazadas y compiladas. El pipeline fluye. Te espera el Bosque de Buffers.",
      "わが石が…クリップされ、バインドされ、リンクされた。パイプラインは流れる。バッファの森が待つぞ。",
    )),
  ],
};

export const pipelineVillage: RegionDef = {
  slug: "pipeline-village",
  name: L("Pipeline Village", "Aldea del Pipeline", "パイプライン村"),
  subtitle: L("Clip space · GPU state · shaders", "Clip space · estado GPU · shaders", "クリップ空間・GPU 状態・シェーダー"),
  theme: "village",
  lessons: [clipSpace, stateMachine, shaders, boss],
};
