import type { ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Written-test formats for planet Velocis (C++): trace tables (dry-run the code, fill the values) and
// debugging tasks (tap the buggy line, then fix it). The validator runs every `verify` (a full
// program) and proves each fix passes the tests while the buggy code and the near misses fail
// (g++ 14, -std=c++20 on Compiler Explorer). Every bug yields a defined wrong result, never UB.

const code = (...lines: string[]) => lines.join("\n");

const after = (n: number) => L(`after line ${n}`, `tras la línea ${n}`, `${n}行目の後`);
const pass = (n: number) => L(`pass ${n}`, `vuelta ${n}`, `${n}周目`);

// ─── Junior ─────────────────────────────────────────────────────────────────

/** Junior trace: integer division and modulo peel digits off. */
export const reverseDigitsTrace: ExamQuestion = {
  slug: "reverse-digits",
  kind: "trace",
  topic: "basics",
  difficulty: 1,
  prompt: L("Trace table: reversing digits", "Tabla de traza: invertir dígitos", "トレース：桁の反転"),
  brief: L(
    "Each row is the end of one pass of the while loop.",
    "Cada fila es el final de una vuelta del bucle while.",
    "各行は while ループ1周の終わり。",
  ),
  code: code(
    "int n = 472;",
    "int rev = 0;",
    "while (n > 0) {",
    "    rev = rev * 10 + n % 10;",
    "    n /= 10;",
    "}",
  ),
  columns: ["n", "rev"],
  rows: [
    { label: pass(1), cells: ["47", "2"], given: [0] },
    { label: pass(2), cells: ["4", "27"] },
    { label: pass(3), cells: ["0", "274"] },
  ],
  verify: code(
    "#include <iostream>",
    "int main() {",
    "    int n = 472;",
    "    int rev = 0;",
    "    while (n > 0) {",
    "        rev = rev * 10 + n % 10;",
    "        n /= 10;",
    '        std::cout << n << " | " << rev << std::endl;',
    "    }",
    "}",
  ),
  explain: L(
    "n % 10 is the last digit and n /= 10 drops it (int division truncates): rev grows 2, 27, 274 while n shrinks 47, 4, 0.",
    "n % 10 es el último dígito y n /= 10 lo quita (la división entera trunca): rev crece 2, 27, 274 y n baja 47, 4, 0.",
    "n % 10 は末尾の桁、n /= 10 で切り捨てて除く。rev は 2, 27, 274、n は 47, 4, 0。",
  ),
};

/** Junior trace: a reference is another name for the same int; a copy is not. */
export const referenceAliasTrace: ExamQuestion = {
  slug: "reference-alias",
  kind: "trace",
  topic: "references",
  difficulty: 1,
  prompt: L("Trace table: copy vs reference", "Tabla de traza: copia vs referencia", "トレース：コピーと参照"),
  code: code(
    "int a = 5;",
    "int b = a;",
    "int& r = a;",
    "r += 3;",
    "b *= 2;",
    "r = b;",
  ),
  columns: ["a", "b", "r"],
  rows: [
    { label: after(4), cells: ["8", "5", "8"], given: [1] },
    { label: after(5), cells: ["8", "10", "8"] },
    { label: after(6), cells: ["10", "10", "10"] },
  ],
  verify: code(
    "#include <iostream>",
    "int main() {",
    "    int a = 5;",
    "    int b = a;",
    "    int& r = a;",
    "    r += 3;",
    '    std::cout << a << " | " << b << " | " << r << std::endl;',
    "    b *= 2;",
    '    std::cout << a << " | " << b << " | " << r << std::endl;',
    "    r = b;",
    '    std::cout << a << " | " << b << " | " << r << std::endl;',
    "}",
  ),
  explain: L(
    "b is a copy, so it keeps 5 until b *= 2. r IS a: r += 3 makes a 8, and r = b assigns 10 to a (it does not rebind r).",
    "b es una copia y sigue en 5 hasta b *= 2. r ES a: r += 3 deja a en 8, y r = b asigna 10 a a (no reenlaza r).",
    "b はコピーなので b *= 2 まで 5。r は a そのもの：r += 3 で a は 8、r = b は a に 10 を代入（r の付け替えではない）。",
  ),
};

// ─── Mid ────────────────────────────────────────────────────────────────────

/** Mid trace: vector copies are deep; range-for by value changes nothing. */
export const vectorCopyTrace: ExamQuestion = {
  slug: "vector-copy",
  kind: "trace",
  topic: "containers",
  difficulty: 2,
  prompt: L("Trace table: vectors and range-for", "Tabla de traza: vectores y range-for", "トレース：vector と範囲 for"),
  code: code(
    "std::vector<int> v{1, 2, 3};",
    "std::vector<int> w = v;",
    "for (int x : v) x *= 10;",
    "for (int& x : w) x += 1;",
    "v[0] = w[2];",
  ),
  columns: ["v[0]", "w[0]", "w[2]"],
  rows: [
    { label: after(3), cells: ["1", "1", "3"], given: [0] },
    { label: after(4), cells: ["1", "2", "4"] },
    { label: after(5), cells: ["4", "2", "4"] },
  ],
  verify: code(
    "#include <iostream>",
    "#include <vector>",
    "int main() {",
    "    std::vector<int> v{1, 2, 3};",
    "    std::vector<int> w = v;",
    "    for (int x : v) x *= 10;",
    '    std::cout << v[0] << " | " << w[0] << " | " << w[2] << std::endl;',
    "    for (int& x : w) x += 1;",
    '    std::cout << v[0] << " | " << w[0] << " | " << w[2] << std::endl;',
    "    v[0] = w[2];",
    '    std::cout << v[0] << " | " << w[0] << " | " << w[2] << std::endl;',
    "}",
  ),
  explain: L(
    "w = v copies every element. int x is a copy, so line 3 changes nothing; int& x edits w in place. v and w never share.",
    "w = v copia cada elemento. int x es una copia, así que la línea 3 no cambia nada; int& x edita w. v y w no comparten nada.",
    "w = v は全要素をコピー。int x はコピーなので3行目は無効、int& x は w を直接変える。v と w は共有しない。",
  ),
};

/** Mid trace: lambda capture by value is a snapshot, by reference follows the variable. */
export const lambdaCaptureTrace: ExamQuestion = {
  slug: "lambda-capture",
  kind: "trace",
  topic: "lambdas_stl",
  difficulty: 2,
  prompt: L("Trace table: lambda captures", "Tabla de traza: capturas de lambdas", "トレース：ラムダのキャプチャ"),
  brief: L(
    "The last two columns are what each call would return at that moment.",
    "Las dos últimas columnas son lo que devolvería cada llamada en ese momento.",
    "右の2列は、その時点で呼んだら返る値。",
  ),
  code: code(
    "int n = 1;",
    "auto byVal = [n] { return n * 10; };",
    "auto byRef = [&n] { return n * 10; };",
    "n = 2;",
    "n += byVal();",
  ),
  columns: ["n", "byVal()", "byRef()"],
  rows: [
    { label: after(3), cells: ["1", "10", "10"], given: [0] },
    { label: after(4), cells: ["2", "10", "20"] },
    { label: after(5), cells: ["12", "10", "120"] },
  ],
  verify: code(
    "#include <iostream>",
    "int main() {",
    "    int n = 1;",
    "    auto byVal = [n] { return n * 10; };",
    "    auto byRef = [&n] { return n * 10; };",
    '    std::cout << n << " | " << byVal() << " | " << byRef() << std::endl;',
    "    n = 2;",
    '    std::cout << n << " | " << byVal() << " | " << byRef() << std::endl;',
    "    n += byVal();",
    '    std::cout << n << " | " << byVal() << " | " << byRef() << std::endl;',
    "}",
  ),
  explain: L(
    "[n] copied n when the lambda was made, so byVal() is always 10. [&n] reads the live n: 10, 20, then 120 once n is 12.",
    "[n] copió n al crear la lambda, así que byVal() siempre es 10. [&n] lee el n actual: 10, 20 y 120 cuando n vale 12.",
    "[n] は作成時に n をコピーするので byVal() は常に 10。[&n] は今の n を読む：10、20、n が 12 なら 120。",
  ),
};

/** Mid debug: integer division hidden inside a function that returns double. */
export const averageDebug: ExamQuestion = {
  slug: "average",
  kind: "debug",
  mode: "ide",
  topic: "basics",
  difficulty: 2,
  prompt: L("Debug: the average", "Depura: el promedio", "デバッグ：平均値"),
  brief: L(
    "average(v) should return the mean of the values as a double, or 0 for an empty vector. But average({1, 2}) returns 1 instead of 1.5, and negative values give a huge number.",
    "average(v) debería devolver la media de los valores como double, o 0 si el vector está vacío. Pero average({1, 2}) devuelve 1 en vez de 1.5, y con negativos sale un número enorme.",
    "average(v) は値の平均を double で返し、空なら 0 を返すはず。でも average({1, 2}) が 1.5 でなく 1 になり、負の値では巨大な数になる。",
  ),
  code: code(
    "#include <vector>",
    "",
    "// Mean of the values, or 0 for an empty vector.",
    "double average(const std::vector<int>& v) {",
    "    if (v.empty()) return 0.0;",
    "    int sum = 0;",
    "    for (int x : v) sum += x;",
    "    return sum / v.size();",
    "}",
  ),
  bugLine: 8,
  solution: code(
    "#include <vector>",
    "",
    "// Mean of the values, or 0 for an empty vector.",
    "double average(const std::vector<int>& v) {",
    "    if (v.empty()) return 0.0;",
    "    int sum = 0;",
    "    for (int x : v) sum += x;",
    "    return static_cast<double>(sum) / v.size();",
    "}",
  ),
  nearMiss: [
    // Converts after the integer division already truncated.
    code(
      "#include <vector>",
      "",
      "double average(const std::vector<int>& v) {",
      "    if (v.empty()) return 0.0;",
      "    int sum = 0;",
      "    for (int x : v) sum += x;",
      "    return static_cast<double>(sum / v.size());",
      "}",
    ),
    // Fixes the sign but still divides integers.
    code(
      "#include <vector>",
      "",
      "double average(const std::vector<int>& v) {",
      "    if (v.empty()) return 0.0;",
      "    int sum = 0;",
      "    for (int x : v) sum += x;",
      "    return sum / static_cast<int>(v.size());",
      "}",
    ),
  ],
  tests: [
    { run: "std::cout << average({1, 2}) << std::endl;", expect: "1.5" },
    { run: "std::cout << average({2, 4, 9}) << std::endl;", expect: "5" },
    { run: "std::cout << average({}) << std::endl;", expect: "0", hidden: true },
    { run: "std::cout << average({1, 2, 2}) << std::endl;", expect: "1.66667", hidden: true },
    { run: "std::cout << average({-3, -4}) << std::endl;", expect: "-3.5", hidden: true },
  ],
  explain: L(
    "int / size_t is integer division, and sum turns unsigned (a negative wraps). Casting sum to double first divides in floating point.",
    "int / size_t es división entera y sum pasa a unsigned (un negativo da la vuelta). Convertir sum a double primero divide en coma flotante.",
    "int / size_t は整数除算で、sum は符号なしに変換される（負は巨大値に）。先に sum を double にすれば浮動小数点で割る。",
  ),
};

/** Mid debug: the vector is taken by value, so the caller never sees the change. */
export const addPrefixDebug: ExamQuestion = {
  slug: "add-prefix",
  kind: "debug",
  mode: "ide",
  topic: "references",
  difficulty: 2,
  prompt: L("Debug: prefix every name", "Depura: prefijo para cada nombre", "デバッグ：名前に接頭辞"),
  brief: L(
    "addPrefix(names, prefix) should put prefix in front of every name, changing the caller's vector. But after addPrefix(v, \"Dr. \") with v = {\"Ada\", \"Bo\"}, v is still {\"Ada\", \"Bo\"}.",
    "addPrefix(names, prefix) debería poner prefix delante de cada nombre, cambiando el vector de quien llama. Pero tras addPrefix(v, \"Dr. \") con v = {\"Ada\", \"Bo\"}, v sigue igual.",
    "addPrefix(names, prefix) は各名前の前に prefix を付け、呼び出し側の vector を変えるはず。でも v = {\"Ada\", \"Bo\"} で addPrefix(v, \"Dr. \") の後も v は変わらない。",
  ),
  code: code(
    "#include <string>",
    "#include <vector>",
    "",
    "// Puts prefix in front of every name, in place.",
    "void addPrefix(std::vector<std::string> names, const std::string& prefix) {",
    "    for (auto& n : names) n = prefix + n;",
    "}",
  ),
  bugLine: 5,
  solution: code(
    "#include <string>",
    "#include <vector>",
    "",
    "// Puts prefix in front of every name, in place.",
    "void addPrefix(std::vector<std::string>& names, const std::string& prefix) {",
    "    for (auto& n : names) n = prefix + n;",
    "}",
  ),
  nearMiss: [
    // The reference is right, but the loop edits copies.
    code(
      "#include <string>",
      "#include <vector>",
      "",
      "void addPrefix(std::vector<std::string>& names, const std::string& prefix) {",
      "    for (auto n : names) n = prefix + n;",
      "}",
    ),
    // Appends instead of prepending.
    code(
      "#include <string>",
      "#include <vector>",
      "",
      "void addPrefix(std::vector<std::string>& names, const std::string& prefix) {",
      "    for (auto& n : names) n += prefix;",
      "}",
    ),
  ],
  tests: [
    { run: '{ std::vector<std::string> v{"Ada", "Bo"}; addPrefix(v, "Dr. "); for (const auto& s : v) std::cout << "[" << s << "]"; std::cout << std::endl; }', expect: "[Dr. Ada][Dr. Bo]" },
    { run: '{ std::vector<std::string> v{"y"}; addPrefix(v, "x"); std::cout << v[0] << std::endl; }', expect: "xy" },
    { run: '{ std::vector<std::string> v; addPrefix(v, "z"); std::cout << v.size() << std::endl; }', expect: "0", hidden: true },
    { run: '{ std::vector<std::string> v{"a", "b", "c"}; addPrefix(v, "-"); for (const auto& s : v) std::cout << s; std::cout << std::endl; }', expect: "-a-b-c", hidden: true },
    { run: '{ std::vector<std::string> v{"ok"}; addPrefix(v, ""); std::cout << v[0] << std::endl; }', expect: "ok", hidden: true },
  ],
  explain: L(
    "names was a by-value copy: the loop edited the copy, which died at return. Taking std::vector<std::string>& edits the caller's vector.",
    "names era una copia por valor: el bucle editaba la copia, que moría al volver. Con std::vector<std::string>& se edita el del llamador.",
    "names は値渡しのコピーで、ループはコピーを変えて捨てていた。std::vector<std::string>& にすれば呼び出し側を変える。",
  ),
};

// ─── Senior ─────────────────────────────────────────────────────────────────

/** Senior trace: unsigned char wraps modulo 256 and is promoted to int in comparisons. */
export const unsignedWrapTrace: ExamQuestion = {
  slug: "unsigned-wrap",
  kind: "trace",
  topic: "basics",
  difficulty: 3,
  prompt: L("Trace table: an unsigned char counter", "Tabla de traza: contador unsigned char", "トレース：unsigned char のカウンタ"),
  brief: L(
    "Each row is the end of one pass. int(c) is the number stored in c.",
    "Cada fila es el final de una vuelta. int(c) es el número guardado en c.",
    "各行は1周の終わり。int(c) は c に入っている数値。",
  ),
  code: code(
    "unsigned char c = 240;",
    "int laps = 0;",
    "for (int k = 0; k < 4; ++k) {",
    "    c += 10;",
    "    if (c < 20) ++laps;",
    "}",
  ),
  columns: ["k", "int(c)", "laps"],
  rows: [
    { label: "k = 0", cells: ["0", "250", "0"], given: [0] },
    { label: "k = 1", cells: ["1", "4", "1"], given: [0] },
    { label: "k = 2", cells: ["2", "14", "2"], given: [0] },
    { label: "k = 3", cells: ["3", "24", "2"], given: [0] },
  ],
  verify: code(
    "#include <iostream>",
    "int main() {",
    "    unsigned char c = 240;",
    "    int laps = 0;",
    "    for (int k = 0; k < 4; ++k) {",
    "        c += 10;",
    "        if (c < 20) ++laps;",
    '        std::cout << k << " | " << int(c) << " | " << laps << std::endl;',
    "    }",
    "}",
  ),
  explain: L(
    "c += 10 computes in int, then stores modulo 256 (defined for unsigned): 250, 260→4, 14, 24. Only 4 and 14 are below 20.",
    "c += 10 calcula en int y guarda módulo 256 (definido en unsigned): 250, 260→4, 14, 24. Solo 4 y 14 son menores que 20.",
    "c += 10 は int で計算し 256 で割った余りを格納（符号なしは定義済み）：250、260→4、14、24。20 未満は 4 と 14 だけ。",
  ),
};

/** Senior debug: std::accumulate takes its type from the initial value. */
export const cartTotalDebug: ExamQuestion = {
  slug: "cart-total",
  kind: "debug",
  mode: "ide",
  topic: "lambdas_stl",
  difficulty: 3,
  prompt: L("Debug: the cart total", "Depura: el total del carrito", "デバッグ：カートの合計"),
  brief: L(
    "cartTotal(items, discountPct) should sum price * qty, apply the discount and round to cents. But cartTotal({{\"pen\", 1.25, 2}, {\"cap\", 2.5, 1}}, 0) returns 4 instead of 5.",
    "cartTotal(items, discountPct) debería sumar price * qty, aplicar el descuento y redondear a céntimos. Pero cartTotal({{\"pen\", 1.25, 2}, {\"cap\", 2.5, 1}}, 0) devuelve 4 en vez de 5.",
    "cartTotal(items, discountPct) は price * qty を合計し、割引して1セント単位に丸めるはず。でも cartTotal({{\"pen\", 1.25, 2}, {\"cap\", 2.5, 1}}, 0) が 5 でなく 4 になる。",
  ),
  code: code(
    "#include <numeric>",
    "#include <string>",
    "#include <vector>",
    "",
    "struct Item {",
    "    std::string name;",
    "    double price;",
    "    int qty;",
    "};",
    "",
    "// Sum of price * qty, minus discountPct percent, rounded to cents.",
    "double cartTotal(const std::vector<Item>& items, double discountPct) {",
    "    double subtotal = std::accumulate(items.begin(), items.end(), 0,",
    "        [](double acc, const Item& it) { return acc + it.price * it.qty; });",
    "    double total = subtotal * (100.0 - discountPct) / 100.0;",
    "    return static_cast<long long>(total * 100 + 0.5) / 100.0;",
    "}",
  ),
  bugLine: 13,
  solution: code(
    "#include <numeric>",
    "#include <string>",
    "#include <vector>",
    "",
    "struct Item {",
    "    std::string name;",
    "    double price;",
    "    int qty;",
    "};",
    "",
    "// Sum of price * qty, minus discountPct percent, rounded to cents.",
    "double cartTotal(const std::vector<Item>& items, double discountPct) {",
    "    double subtotal = std::accumulate(items.begin(), items.end(), 0.0,",
    "        [](double acc, const Item& it) { return acc + it.price * it.qty; });",
    "    double total = subtotal * (100.0 - discountPct) / 100.0;",
    "    return static_cast<long long>(total * 100 + 0.5) / 100.0;",
    "}",
  ),
  nearMiss: [
    // A wider integer is still an integer accumulator.
    code(
      "#include <numeric>",
      "#include <string>",
      "#include <vector>",
      "",
      "struct Item {",
      "    std::string name;",
      "    double price;",
      "    int qty;",
      "};",
      "",
      "double cartTotal(const std::vector<Item>& items, double discountPct) {",
      "    double subtotal = std::accumulate(items.begin(), items.end(), 0L,",
      "        [](double acc, const Item& it) { return acc + it.price * it.qty; });",
      "    double total = subtotal * (100.0 - discountPct) / 100.0;",
      "    return static_cast<long long>(total * 100 + 0.5) / 100.0;",
      "}",
    ),
    // A double accumulator, but the lambda truncates it on every call.
    code(
      "#include <numeric>",
      "#include <string>",
      "#include <vector>",
      "",
      "struct Item {",
      "    std::string name;",
      "    double price;",
      "    int qty;",
      "};",
      "",
      "double cartTotal(const std::vector<Item>& items, double discountPct) {",
      "    double subtotal = std::accumulate(items.begin(), items.end(), 0.0,",
      "        [](int acc, const Item& it) { return acc + it.price * it.qty; });",
      "    double total = subtotal * (100.0 - discountPct) / 100.0;",
      "    return static_cast<long long>(total * 100 + 0.5) / 100.0;",
      "}",
    ),
  ],
  tests: [
    { run: 'std::cout << cartTotal({{"pen", 1.25, 2}, {"cap", 2.5, 1}}, 0) << std::endl;', expect: "5" },
    { run: 'std::cout << cartTotal({{"tea", 3.2, 3}}, 10) << std::endl;', expect: "8.64" },
    { run: "std::cout << cartTotal({}, 20) << std::endl;", expect: "0", hidden: true },
    { run: 'std::cout << cartTotal({{"a", 0.99, 1}, {"b", 0.99, 1}, {"c", 0.99, 1}}, 0) << std::endl;', expect: "2.97", hidden: true },
    { run: 'std::cout << cartTotal({{"x", 10, 1}}, 50) << std::endl;', expect: "5", hidden: true },
  ],
  explain: L(
    "accumulate's sum has the type of its initial value: 0 is int, so each step was cut to an int. 0.0 keeps a double.",
    "La suma de accumulate tiene el tipo del valor inicial: 0 es int, así que cada paso se truncaba. 0.0 la mantiene double.",
    "accumulate の和は初期値の型になる。0 は int なので毎回切り捨てられていた。0.0 なら double のまま。",
  ),
};

/** Senior paper debug: an unsigned difference is never negative. */
export const overflowReportDebug: ExamQuestion = {
  slug: "overflow-report",
  kind: "debug",
  mode: "paper",
  topic: "basics",
  difficulty: 3,
  prompt: L("Debug: words that overflow", "Depura: palabras que desbordan", "デバッグ：はみ出す単語"),
  brief: L(
    "overflowReport(words, width) should list each word longer than width as \"word+extra\", separated by spaces. But overflowReport({\"cat\", \"giraffe\"}, 5) returns \"cat+18446744073709551614 giraffe+2\" instead of \"giraffe+2\".",
    "overflowReport(words, width) debería listar cada palabra más larga que width como \"word+extra\", separadas por espacios. Pero overflowReport({\"cat\", \"giraffe\"}, 5) devuelve \"cat+18446744073709551614 giraffe+2\" en vez de \"giraffe+2\".",
    "overflowReport(words, width) は width より長い単語を \"word+extra\" の形で空白区切りに並べるはず。でも overflowReport({\"cat\", \"giraffe\"}, 5) が \"giraffe+2\" でなく \"cat+18446744073709551614 giraffe+2\" になる。",
  ),
  code: code(
    "#include <string>",
    "#include <vector>",
    "",
    "// Lists the words wider than `width` columns as \"word+extra\",",
    "// separated by spaces, e.g. width 5: \"giraffe\" -> \"giraffe+2\".",
    "std::string overflowReport(const std::vector<std::string>& words, std::size_t width) {",
    "    std::string out;",
    "    for (const auto& w : words) {",
    "        std::size_t extra = w.size() - width;",
    "        if (extra > 0) {",
    "            if (!out.empty()) out += ' ';",
    "            out += w + \"+\" + std::to_string(extra);",
    "        }",
    "    }",
    "    return out;",
    "}",
  ),
  bugLine: 10,
  solution: code(
    "#include <string>",
    "#include <vector>",
    "",
    "// Lists the words wider than `width` columns as \"word+extra\",",
    "// separated by spaces, e.g. width 5: \"giraffe\" -> \"giraffe+2\".",
    "std::string overflowReport(const std::vector<std::string>& words, std::size_t width) {",
    "    std::string out;",
    "    for (const auto& w : words) {",
    "        std::size_t extra = w.size() - width;",
    "        if (w.size() > width) {",
    "            if (!out.empty()) out += ' ';",
    "            out += w + \"+\" + std::to_string(extra);",
    "        }",
    "    }",
    "    return out;",
    "}",
  ),
  nearMiss: [
    // Same unsigned comparison, written differently.
    code(
      "#include <string>",
      "#include <vector>",
      "",
      "std::string overflowReport(const std::vector<std::string>& words, std::size_t width) {",
      "    std::string out;",
      "    for (const auto& w : words) {",
      "        std::size_t extra = w.size() - width;",
      "        if (extra >= 1) {",
      "            if (!out.empty()) out += ' ';",
      "            out += w + \"+\" + std::to_string(extra);",
      "        }",
      "    }",
      "    return out;",
      "}",
    ),
    // Also reports words that fit exactly (+0).
    code(
      "#include <string>",
      "#include <vector>",
      "",
      "std::string overflowReport(const std::vector<std::string>& words, std::size_t width) {",
      "    std::string out;",
      "    for (const auto& w : words) {",
      "        std::size_t extra = w.size() - width;",
      "        if (w.size() >= width) {",
      "            if (!out.empty()) out += ' ';",
      "            out += w + \"+\" + std::to_string(extra);",
      "        }",
      "    }",
      "    return out;",
      "}",
    ),
  ],
  tests: [
    { run: 'std::cout << "[" << overflowReport({"cat", "giraffe"}, 5) << "]" << std::endl;', expect: "[giraffe+2]" },
    { run: 'std::cout << "[" << overflowReport({"tree", "elephant", "ox"}, 4) << "]" << std::endl;', expect: "[elephant+4]" },
    { run: 'std::cout << "[" << overflowReport({}, 3) << "]" << std::endl;', expect: "[]", hidden: true },
    { run: 'std::cout << "[" << overflowReport({"hello"}, 5) << "]" << std::endl;', expect: "[]", hidden: true },
    { run: 'std::cout << "[" << overflowReport({"hi", "rocket", "moon"}, 3) << "]" << std::endl;', expect: "[rocket+3 moon+1]", hidden: true },
  ],
  explain: L(
    "size_t is unsigned: a shorter word wraps to a huge extra, so extra > 0 is true for all but exact fits. Compare the sizes first.",
    "size_t es unsigned: una palabra más corta da un extra enorme, así que extra > 0 casi siempre es cierto. Compara los tamaños antes.",
    "size_t は符号なし。短い単語では extra が巨大値になり、extra > 0 はほぼ常に真。先にサイズ同士を比べる。",
  ),
};

/** Senior paper debug: passing a polymorphic object by value slices it. */
export const shippingSliceDebug: ExamQuestion = {
  slug: "shipping-slice",
  kind: "debug",
  mode: "paper",
  topic: "polymorphism",
  difficulty: 3,
  prompt: L("Debug: the shipping quote", "Depura: la cotización de envío", "デバッグ：送料の見積もり"),
  brief: L(
    "quote(method, kg) should return \"name:cost\" for the given shipping method. But for an Express e, quote(e, 2) returns \"standard:9\" instead of \"express:18\": every method is quoted as standard.",
    "quote(method, kg) debería devolver \"name:cost\" para el método de envío dado. Pero con un Express e, quote(e, 2) devuelve \"standard:9\" en vez de \"express:18\": todo se cotiza como standard.",
    "quote(method, kg) は配送方法の \"name:cost\" を返すはず。でも Express e で quote(e, 2) が \"express:18\" でなく \"standard:9\" になる。どの方法も standard 扱い。",
  ),
  code: code(
    "#include <string>",
    "",
    "struct Shipping {",
    "    virtual ~Shipping() = default;",
    "    virtual std::string name() const { return \"standard\"; }",
    "    virtual int cost(int kg) const { return 5 + 2 * kg; }",
    "};",
    "",
    "struct Express : Shipping {",
    "    std::string name() const override { return \"express\"; }",
    "    int cost(int kg) const override { return 12 + 3 * kg; }",
    "};",
    "",
    "struct Pickup : Shipping {",
    "    std::string name() const override { return \"pickup\"; }",
    "    int cost(int) const override { return 0; }",
    "};",
    "",
    "// \"name:cost\" for a parcel of kg kilos sent with the given method.",
    "std::string quote(Shipping method, int kg) {",
    "    return method.name() + \":\" + std::to_string(method.cost(kg));",
    "}",
  ),
  bugLine: 20,
  solution: code(
    "#include <string>",
    "",
    "struct Shipping {",
    "    virtual ~Shipping() = default;",
    "    virtual std::string name() const { return \"standard\"; }",
    "    virtual int cost(int kg) const { return 5 + 2 * kg; }",
    "};",
    "",
    "struct Express : Shipping {",
    "    std::string name() const override { return \"express\"; }",
    "    int cost(int kg) const override { return 12 + 3 * kg; }",
    "};",
    "",
    "struct Pickup : Shipping {",
    "    std::string name() const override { return \"pickup\"; }",
    "    int cost(int) const override { return 0; }",
    "};",
    "",
    "// \"name:cost\" for a parcel of kg kilos sent with the given method.",
    "std::string quote(const Shipping& method, int kg) {",
    "    return method.name() + \":\" + std::to_string(method.cost(kg));",
    "}",
  ),
  nearMiss: [
    // const does not stop the copy: still sliced to a Shipping.
    code(
      "#include <string>",
      "",
      "struct Shipping {",
      "    virtual ~Shipping() = default;",
      "    virtual std::string name() const { return \"standard\"; }",
      "    virtual int cost(int kg) const { return 5 + 2 * kg; }",
      "};",
      "",
      "struct Express : Shipping {",
      "    std::string name() const override { return \"express\"; }",
      "    int cost(int kg) const override { return 12 + 3 * kg; }",
      "};",
      "",
      "struct Pickup : Shipping {",
      "    std::string name() const override { return \"pickup\"; }",
      "    int cost(int) const override { return 0; }",
      "};",
      "",
      "std::string quote(const Shipping method, int kg) {",
      "    return method.name() + \":\" + std::to_string(method.cost(kg));",
      "}",
    ),
  ],
  tests: [
    { run: "{ Express e; std::cout << quote(e, 2) << std::endl; }", expect: "express:18" },
    { run: "{ Shipping s; std::cout << quote(s, 3) << std::endl; }", expect: "standard:11" },
    { run: "{ Pickup p; std::cout << quote(p, 10) << std::endl; }", expect: "pickup:0", hidden: true },
    { run: "{ Express e; std::cout << quote(e, 0) << std::endl; }", expect: "express:12", hidden: true },
    { run: "{ Shipping s; std::cout << quote(s, 0) << std::endl; }", expect: "standard:5", hidden: true },
  ],
  explain: L(
    "Taking Shipping by value copies only the base part (slicing), so virtual calls hit Shipping. A const reference keeps the real type.",
    "Recibir Shipping por valor copia solo la parte base (slicing) y las llamadas virtuales van a Shipping. Una referencia const conserva el tipo real.",
    "Shipping の値渡しは基底部分だけをコピー（スライシング）し、仮想呼び出しが Shipping に行く。const 参照なら実際の型のまま。",
  ),
};

export const juniorTraceDebug: ExamQuestion[] = [reverseDigitsTrace, referenceAliasTrace];
export const midTraceDebug: ExamQuestion[] = [vectorCopyTrace, lambdaCaptureTrace, averageDebug, addPrefixDebug];
export const seniorTraceDebug: ExamQuestion[] = [unsignedWrapTrace, cartTotalDebug, overflowReportDebug, shippingSliceDebug];
