import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { L, say, enemySays } from "../../rust/helpers.ts";

// REGION 3 · LINQ PEAKS  (collections and generics, delegates and closures, LINQ basics, deferred execution)
// Snippets are completed by the validator with `using System; System.Collections.Generic; System.Linq;
// System.Text; System.Threading.Tasks;`. Run beats are sent as written and carry their own usings.
// Never claim Dictionary/HashSet enumeration order or hash codes.

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO = L("No: compile error", "No: error de compilación", "いいえ：コンパイルエラー");

// ─── 3.1 The adventurer's packs: collections and generics ──────────────────
const collections: LessonDef = {
  slug: "collections-and-generics",
  title: L("The adventurer's packs", "Las mochilas del aventurero", "冒険者のバッグ"),
  concept: "collections-generics",
  mode: "lesson",
  xp: 70,
  enemy: "csharp/boxing-mimic",
  enemyName: L("PACK MIMIC", "MÍMICO MOCHILA", "バッグミミック"),
  beats: [
    say(L(
      "Welcome to Linq Peaks! Climbers need packs. An ARRAY is a fixed row of slots: new int[3] makes three slots, all 0.",
      "¡Bienvenido a Linq Peaks! Los escaladores necesitan mochilas. Un ARRAY es una fila fija: new int[3] crea tres casillas, todas en 0.",
      "リンクピークへようこそ！登山にはバッグが必要。配列は固定の列。new int[3] で 0 が3つできるよ。",
    )),
    {
      kind: "act",
      prompt: L("Fill the slots, then reach past the end", "Llena las casillas y luego pasa del final", "スロットを埋めて、端の先に手をのばそう"),
      steps: [
        { label: L("MAKE 3 SLOTS", "CREAR 3", "3つ作る"), line: "int[] slots = new int[3];", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "int[] slots" }, { t: "value", actor: "hero", text: "[0,0,0]" }] },
        { label: L("SET slots[0]", "PONER slots[0]", "0番に入れる"), line: "slots[0] = 7;", effects: [{ t: "value", actor: "hero", text: "[7,0,0]" }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: 'Console.WriteLine(slots[0] + " " + slots[1]);', effects: [{ t: "print", text: "7 0" }], output: "7 0" },
        {
          label: L("SLOT 3?", "¿CASILLA 3?", "スロット3？"),
          line: "slots[3] = 1;",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("No slot there!", "¡No hay casilla!", "そこは無い！") }],
          error: {
            compiler: "System.IndexOutOfRangeException: Index was outside the bounds of the array.",
            plain: L("Indexes start at 0, so 3 slots are 0, 1 and 2. Index 3 crashes at runtime.", "Los índices empiezan en 0: 3 casillas son 0, 1 y 2. El índice 3 falla al ejecutar.", "番号は 0 から。3つなら 0, 1, 2。3 は実行時にクラッシュ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'int[] a = new int[3];\nConsole.WriteLine(a[1] + " " + a.Length);',
      options: ["0 3", "null 3", "0 2"],
      answer: 0,
      output: "0 3",
      check: { compiles: true, stdout: "0 3" },
      explain: L("New int slots start at 0 (the default for int). Length counts slots: 3.", "Las casillas int nuevas valen 0 (el default de int). Length cuenta casillas: 3.", "新しい int のスロットは 0（int の既定値）。Length は数で 3。"),
      win: [{ t: "print", text: "0 3" }],
    },
    say(L(
      "A List<string> is a pack that GROWS. The <string> says what it holds: that makes List a GENERIC type. string.Join glues items.",
      "Un List<string> es una mochila que CRECE. El <string> dice qué guarda: eso hace de List un tipo GENÉRICO. string.Join une los items.",
      "List<string> は伸びるバッグ。<string> で中身の型を決める。これがジェネリック型。string.Join で連結できるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var l = new List<string> { "sword" };\nl.Add("shield");\nl.Insert(0, "gem");\nConsole.WriteLine(string.Join(",", l) + " " + l.Count);',
      options: ["gem,sword,shield 3", "sword,shield,gem 3", "gem,sword,shield 2"],
      answer: 0,
      output: "gem,sword,shield 3",
      check: { compiles: true, stdout: "gem,sword,shield 3" },
      explain: L("Add puts at the end, Insert(0, ...) at the front. Count is how many items: 3.", "Add agrega al final, Insert(0, ...) al inicio. Count es cuántos items hay: 3.", "Add は末尾、Insert(0, ...) は先頭に入れる。Count は個数で 3。"),
      setup: [{ t: "item", kind: "sword", holder: "hero" }],
      win: [{ t: "item", kind: "gem", holder: "hero" }, { t: "item", kind: "shield", holder: "hero" }, { t: "print", text: "gem,sword,shield 3" }],
    },
    {
      kind: "pick",
      prompt: L("Put the potion in the pack", "Mete la poción en la mochila", "ポーションをバッグに入れよう"),
      code: 'var bag = new List<string>();\nbag.___("potion");\nConsole.WriteLine(bag.Count);',
      options: ["Add", "Push", "Insert"],
      answer: 0,
      check: { compiles: true, stdout: "1", wrongFail: true },
      explain: L("List uses Add. Push belongs to Stack, and Insert also needs a position.", "List usa Add. Push es de Stack, e Insert también necesita una posición.", "List は Add を使う。Push は Stack 用、Insert は位置も必要。"),
      win: [{ t: "item", kind: "potion", holder: "hero" }, { t: "print", text: "1" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "var l = new List<int> { 1, 2 };\nConsole.WriteLine(l[2]);",
      options: ["ArgumentOutOfRangeException", "0", L("It prints nothing", "No imprime nada", "何も表示しない")],
      answer: 0,
      check: { compiles: true, throws: "ArgumentOutOfRangeException" },
      explain: L("Two items live at 0 and 1. A List throws ArgumentOutOfRangeException; an array would throw IndexOutOfRangeException.", "Dos items viven en 0 y 1. Un List lanza ArgumentOutOfRangeException; un array lanzaría IndexOutOfRangeException.", "要素は 0 と 1。List は ArgumentOutOfRangeException、配列なら IndexOutOfRangeException。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "A Dictionary is a wall of labelled chests: key → value. d[key] = v sets or overwrites. Reading a missing key crashes!",
      "Un Dictionary es un muro de cofres con etiqueta: clave → valor. d[clave] = v asigna o reemplaza. ¡Leer una clave que falta revienta!",
      "Dictionary はラベル付きの宝箱の壁。キー → 値。d[key] = v で設定か上書き。無いキーを読むとクラッシュ！",
    )),
    {
      kind: "act",
      prompt: L("Fill a chest, top it up, open an empty one", "Llena un cofre, súmale y abre uno vacío", "宝箱に入れて、足して、空の箱を開けよう"),
      steps: [
        { label: L("NEW WALL", "MURO NUEVO", "壁を作る"), line: "var gold = new Dictionary<string, int>();", effects: [{ t: "tag", actor: "hero", text: "gold" }] },
        { label: L("SET ana", "PONER ana", "ana に入れる"), line: 'gold["ana"] = 5;', effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "value", actor: "hero", text: "ana=5" }] },
        { label: L("ADD 10", "SUMAR 10", "10 足す"), line: 'gold["ana"] += 10;', effects: [{ t: "value", actor: "hero", text: "ana=15" }] },
        { label: L("READ ana", "LEER ana", "ana を読む"), line: 'Console.WriteLine(gold["ana"]);', effects: [{ t: "print", text: "15" }], output: "15" },
        {
          label: L("READ bob", "LEER bob", "bob を読む"),
          line: 'Console.WriteLine(gold["bob"]);',
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("No such chest!", "¡No hay cofre!", "その箱は無い！") }],
          error: {
            compiler: "System.Collections.Generic.KeyNotFoundException: The given key 'bob' was not present in the dictionary.",
            plain: L("Setting a missing key creates it, but READING a missing key throws.", "Asignar una clave nueva la crea, pero LEER una que falta lanza una excepción.", "無いキーへの代入は作成になるけど、読むと例外になる。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var d = new Dictionary<string, int> { ["gold"] = 5 };\nd["gold"] += 10;\nd["gems"] = 1;\nConsole.WriteLine(d["gold"] + " " + d.Count);',
      options: ["15 2", "15 1", "5 2"],
      answer: 0,
      output: "15 2",
      check: { compiles: true, stdout: "15 2" },
      explain: L("+= updates the gold chest to 15; setting \"gems\" adds a second key.", "+= sube el cofre gold a 15; asignar \"gems\" agrega una segunda clave.", "+= で gold は 15。\"gems\" への代入で2つ目のキーが増える。"),
      win: [{ t: "print", text: "15 2" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'var d = new Dictionary<string, int>();\nd.Add("a", 1);\nd.Add("a", 2);\nConsole.WriteLine(d["a"]);',
      options: ["ArgumentException", "2", "1"],
      answer: 0,
      check: { compiles: true, throws: "An item with the same key has already been added" },
      explain: L("Add refuses a key that already exists and throws ArgumentException. d[\"a\"] = 2 would overwrite instead.", "Add rechaza una clave que ya existe y lanza ArgumentException. d[\"a\"] = 2 la reemplazaría.", "Add は既存のキーを拒んで ArgumentException。d[\"a\"] = 2 なら上書き。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Safe reads: TryGetValue(key, out var v) returns true or false, and GetValueOrDefault(key) gives 0 when the chest is missing.",
      "Lecturas seguras: TryGetValue(clave, out var v) devuelve true o false, y GetValueOrDefault(clave) da 0 si el cofre no existe.",
      "安全に読むには：TryGetValue(key, out var v) は true か false。GetValueOrDefault(key) は無ければ 0。",
    )),
    {
      kind: "pick",
      prompt: L("Peek without crashing", "Mira sin reventar", "クラッシュせずにのぞこう"),
      code: 'var stock = new Dictionary<string, int> { ["potion"] = 3 };\nif (stock.___("potion", out int n))\n    Console.WriteLine("have " + n);\nelse\n    Console.WriteLine("none");',
      options: ["TryGetValue", "ContainsKey", "GetValueOrDefault"],
      answer: 0,
      check: { compiles: true, stdout: "have 3", wrongFail: true },
      explain: L("Only TryGetValue has an out parameter: it returns true and fills n with 3.", "Solo TryGetValue tiene un parámetro out: devuelve true y llena n con 3.", "out 引数を持つのは TryGetValue だけ。true を返し n に 3 を入れる。"),
      win: [{ t: "print", text: "have 3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var s = new HashSet<string> { "a", "b" };\nConsole.WriteLine(s.Add("a") + " " + s.Add("c") + " " + s.Count);',
      options: ["False True 3", "True True 4", "False True 2"],
      answer: 0,
      output: "False True 3",
      check: { compiles: true, stdout: "False True 3" },
      explain: L("A HashSet keeps each item once. Add returns false for the duplicate \"a\" and true for the new \"c\".", "Un HashSet guarda cada item una vez. Add devuelve false con el \"a\" repetido y true con el nuevo \"c\".", "HashSet は同じ物を1つだけ持つ。重複の \"a\" は false、新しい \"c\" は true。"),
      win: [{ t: "say", actor: "hero", text: L("Already have it!", "¡Ya lo tengo!", "もう持ってる！") }, { t: "print", text: "False True 3" }],
    },
    say(L(
      "You can write GENERIC methods too: T is a type to fill in later. where T : IComparable<T> promises T can CompareTo.",
      "También puedes escribir métodos GENÉRICOS: T es un tipo que se elige después. where T : IComparable<T> promete que T sabe CompareTo.",
      "ジェネリックなメソッドも書ける。T は後で決まる型。where T : IComparable<T> で CompareTo を約束する。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Console.WriteLine(Max(3, 9) + " " + Max("pear", "apple"));\n\nstatic T Max<T>(T a, T b) where T : IComparable<T>\n    => a.CompareTo(b) >= 0 ? a : b;',
      options: ["9 pear", "9 apple", "3 pear"],
      answer: 0,
      output: "9 pear",
      check: { compiles: true, stdout: "9 pear" },
      explain: L("One method, two types: T becomes int, then string. Strings compare alphabetically, so pear wins.", "Un método, dos tipos: T es int y luego string. Los strings se comparan por orden alfabético: gana pear.", "1つのメソッドで2つの型。T は int、次に string。文字列は辞書順なので pear。"),
      win: [{ t: "print", text: "9 pear" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "Console.WriteLine(Add(1, 2));\n\nstatic T Add<T>(T a, T b) => a + b;",
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L("Error CS0019: T could be any type, and not every type has +. A constraint must promise what you use.", "Error CS0019: T puede ser cualquier tipo, y no todos tienen +. Una restricción debe prometer lo que usas.", "エラー CS0019：T は何の型でもよく、+ が無い型もある。使う機能は制約で約束しよう。"),
      win: [{ t: "shake" }, { t: "banner", text: L("CS0019", "CS0019", "CS0019") }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "var l = new List<int> { 1, 2, 3 };\nforeach (var x in l)\n    if (x == 2) l.Remove(x);\nConsole.WriteLine(l.Count);",
      options: ["InvalidOperationException", "2", "3"],
      answer: 0,
      check: { compiles: true, throws: "Collection was modified" },
      explain: L("Never change a list while foreach walks it: the next step throws \"Collection was modified\".", "Nunca cambies una lista mientras foreach la recorre: el siguiente paso lanza \"Collection was modified\".", "foreach の途中でリストを変えないで。次の一歩で \"Collection was modified\" になる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "run",
      prompt: L("Make it print ether: 0 instead of crashing", "Haz que imprima ether: 0 en vez de reventar", "クラッシュせず ether: 0 と表示させよう"),
      starter: 'using System;\nusing System.Collections.Generic;\n\nvar stock = new Dictionary<string, int> { ["potion"] = 3 };\nConsole.WriteLine($"potion: {stock["potion"]}");\nConsole.WriteLine($"ether: {stock["ether"]}");\n',
      solution: 'using System;\nusing System.Collections.Generic;\n\nvar stock = new Dictionary<string, int> { ["potion"] = 3 };\nConsole.WriteLine($"potion: {stock["potion"]}");\nConsole.WriteLine($"ether: {stock.GetValueOrDefault("ether")}");\n',
      expect: "ether: 0",
      fallback: [String.raw`GetValueOrDefault\(\s*"ether"`, String.raw`TryGetValue\(\s*"ether"`],
      explain: L("stock[\"ether\"] throws KeyNotFoundException. GetValueOrDefault(\"ether\") returns 0 instead.", "stock[\"ether\"] lanza KeyNotFoundException. GetValueOrDefault(\"ether\") devuelve 0.", "stock[\"ether\"] は KeyNotFoundException。GetValueOrDefault(\"ether\") なら 0。"),
    },
  ],
};

// ─── 3.2 Spells in a bottle: delegates and closures ────────────────────────
const delegates: LessonDef = {
  slug: "delegates-and-closures",
  title: L("Spells in a bottle", "Hechizos en una botella", "ビンづめの呪文"),
  concept: "delegates-closures",
  mode: "lesson",
  xp: 75,
  enemy: "csharp/nullref-ghost",
  enemyName: L("BOTTLE GHOST", "FANTASMA BOTELLA", "ビンのゴースト"),
  beats: [
    say(L(
      "A LAMBDA is a spell in a bottle: x => x * 2. A Func<int, int> holds it. The LAST type is what the spell returns.",
      "Una LAMBDA es un hechizo en una botella: x => x * 2. Un Func<int, int> la guarda. El ÚLTIMO tipo es lo que devuelve.",
      "ラムダはビンづめの呪文：x => x * 2。Func<int, int> にしまえる。最後の型が戻り値だよ。",
    )),
    {
      kind: "act",
      prompt: L("Bottle the spell, then cast it twice", "Embotella el hechizo y lánzalo dos veces", "呪文をビンにつめて、2回唱えよう"),
      steps: [
        { label: L("BOTTLE IT", "EMBOTELLAR", "ビンにつめる"), line: "Func<int, int> dbl = x => x * 2;", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "dbl" }] },
        { label: L("CAST ON 3", "LANZAR CON 3", "3 に唱える"), line: "Console.WriteLine(dbl(3));", effects: [{ t: "attack", from: "hero", to: "enemy" }, { t: "print", text: "6" }], output: "6" },
        { label: L("CAST TWICE", "DOS VECES", "2回唱える"), line: "Console.WriteLine(dbl(dbl(3)));", effects: [{ t: "attack", from: "hero", to: "enemy", dmg: 2 }, { t: "print", text: "12" }], output: "12" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "Func<int, int, int> add = (a, b) => a + b;\nConsole.WriteLine(add(2, 3) * 2);",
      options: ["10", "7", "8"],
      answer: 0,
      output: "10",
      check: { compiles: true, stdout: "10" },
      explain: L("Func<int, int, int> takes two ints and returns an int. add(2, 3) is 5, times 2 is 10.", "Func<int, int, int> recibe dos int y devuelve un int. add(2, 3) es 5, por 2 da 10.", "Func<int, int, int> は int 2つを受け int を返す。add(2, 3) は 5、×2 で 10。"),
      win: [{ t: "print", text: "10" }],
    },
    say(L(
      "Func returns a value. Action returns nothing (void). A Func<T, bool> asks a yes/no question about a T.",
      "Func devuelve un valor. Action no devuelve nada (void). Un Func<T, bool> hace una pregunta de sí/no sobre un T.",
      "Func は値を返す。Action は何も返さない（void）。Func<T, bool> は T について はい/いいえ を答える。",
    )),
    {
      kind: "type",
      prompt: L("Type the delegate that returns bool", "Escribe el delegado que devuelve bool", "bool を返すデリゲートを書こう"),
      code: "___<int, bool> isEven = n => n % 2 == 0;\nConsole.WriteLine(isEven(4));",
      answer: "Func",
      check: { compiles: true, stdout: "True" },
      explain: L("Func<int, bool>: takes an int, returns a bool. bool prints as True or False.", "Func<int, bool>: recibe un int y devuelve un bool. Un bool se imprime como True o False.", "Func<int, bool> は int を受けて bool を返す。bool は True / False と表示。"),
      win: [{ t: "print", text: "True" }],
    },
    {
      kind: "pick",
      prompt: L("This spell returns nothing", "Este hechizo no devuelve nada", "この呪文は何も返さない"),
      code: '___<string> shout = s => Console.WriteLine(s + "!");\nshout("hi");',
      options: ["Action", "Func", "Predicate"],
      answer: 0,
      check: { compiles: true, stdout: "hi!", wrongFail: true },
      explain: L("Console.WriteLine returns void, so the bottle is an Action<string>. Func<string> would take no input at all.", "Console.WriteLine devuelve void, así que la botella es Action<string>. Func<string> no recibiría ninguna entrada.", "Console.WriteLine は void なので Action<string>。Func<string> は引数を受け取らない。"),
      win: [{ t: "print", text: "hi!" }],
    },
    say(L(
      "+= adds another spell to the same bottle: a MULTICAST delegate. An Action runs them all; a Func returns only the LAST result.",
      "+= agrega otro hechizo a la misma botella: un delegado MULTICAST. Un Action los corre todos; un Func devuelve solo el ÚLTIMO resultado.",
      "+= で同じビンに呪文を足せる（マルチキャスト）。Action は全部実行、Func は最後の結果だけ返す。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Action<string> cry = s => Console.Write(s);\ncry += s => Console.Write(s.ToUpper());\ncry("hi");',
      options: ["hiHI", "HI", "hi"],
      answer: 0,
      output: "hiHI",
      check: { compiles: true, stdout: "hiHI" },
      explain: L("Both spells are in the bottle, and they run in the order they were added.", "Los dos hechizos están en la botella y corren en el orden en que se agregaron.", "ビンには呪文が2つ。足した順に実行されるよ。"),
      win: [{ t: "print", text: "hiHI" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "Func<int> f = () => 1;\nf += () => 2;\nConsole.WriteLine(f());",
      options: ["2", "1", "3"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("Both run, but a multicast Func hands back only the last result: 2.", "Corren los dos, pero un Func multicast devuelve solo el último resultado: 2.", "両方動くけど、マルチキャストの Func は最後の結果 2 だけを返す。"),
    },
    say(L(
      "A lambda can use variables around it: a CLOSURE. It captures the VARIABLE itself, not a copy of its value.",
      "Una lambda puede usar variables de su alrededor: un CLOSURE. Captura la VARIABLE misma, no una copia de su valor.",
      "ラムダは周りの変数を使える。これがクロージャ。値のコピーではなく、変数そのものをつかむ。",
    )),
    {
      kind: "act",
      prompt: L("Give the spell a backpack, then cast it", "Dale una mochila al hechizo y lánzalo", "呪文にリュックを持たせて唱えよう"),
      steps: [
        { label: L("COUNTER", "CONTADOR", "カウンター"), line: "int count = 0;", effects: [{ t: "tag", actor: "hero", text: "count", value: "0" }] },
        { label: L("CAPTURE IT", "CAPTURARLO", "つかむ"), line: "Action inc = () => count++;", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "key", holder: "ally" }, { t: "tag", actor: "ally", text: "inc" }] },
        { label: L("CAST TWICE", "DOS VECES", "2回唱える"), line: "inc(); inc();", effects: [{ t: "attack", from: "ally", to: "enemy" }, { t: "value", actor: "hero", text: "2" }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "Console.WriteLine(count);", effects: [{ t: "print", text: "2" }], output: "2" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int hp = 10;\nFunc<int> read = () => hp;\nhp = 99;\nConsole.WriteLine(read());",
      options: ["99", "10", "0"],
      answer: 0,
      output: "99",
      check: { compiles: true, stdout: "99" },
      explain: L("read captured the variable hp, not the value 10. When cast, it reads hp as it is now: 99.", "read capturó la variable hp, no el valor 10. Al lanzarse, lee hp como está ahora: 99.", "read がつかんだのは変数 hp で、10 という値ではない。唱えた時の hp は 99。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "10" }],
      win: [{ t: "value", actor: "hero", text: "99" }, { t: "print", text: "99" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "var add10 = MakeAdder(10);\nConsole.WriteLine(add10(5));\n\nstatic Func<int, int> MakeAdder(int k) => x => x + k;",
      options: ["15", "10", "5"],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("MakeAdder returns a lambda that remembers k = 10, even after MakeAdder has finished.", "MakeAdder devuelve una lambda que recuerda k = 10, aunque MakeAdder ya terminó.", "MakeAdder は k = 10 をおぼえたラムダを返す。MakeAdder が終わった後もね。"),
      win: [{ t: "print", text: "15" }],
    },
    say(L(
      "The classic trap: a for loop has ONE i shared by every lambda. A foreach makes a fresh variable on each lap.",
      "La trampa clásica: un for tiene UN solo i compartido por todas las lambdas. Un foreach crea una variable nueva en cada vuelta.",
      "有名なワナ：for の i は全ラムダで共有の1つだけ。foreach は1周ごとに新しい変数を作る。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "var acts = new List<Action>();\nfor (int i = 0; i < 3; i++)\n    acts.Add(() => Console.Write(i));\nforeach (var a in acts) a();",
      options: ["333", "012", "222"],
      answer: 0,
      output: "333",
      check: { compiles: true, stdout: "333" },
      explain: L("All three lambdas share the same i. The loop ends with i == 3, and only then do they run.", "Las tres lambdas comparten el mismo i. El for termina con i == 3, y recién ahí corren.", "3つのラムダは同じ i を共有。ループ終了時 i は 3、その後に実行される。"),
      win: [{ t: "shake" }, { t: "print", text: "333" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "var acts = new List<Action>();\nforeach (var i in new[] { 0, 1, 2 })\n    acts.Add(() => Console.Write(i));\nforeach (var a in acts) a();",
      options: ["012", "222", "333"],
      answer: 0,
      output: "012",
      check: { compiles: true, stdout: "012" },
      explain: L("foreach gives each lap its own i, so each lambda keeps its own value.", "foreach le da a cada vuelta su propio i, así que cada lambda guarda su valor.", "foreach は1周ごとに別の i。だから各ラムダが自分の値を持つ。"),
      win: [{ t: "print", text: "012" }],
    },
    say(L(
      "An EVENT is a public bottle others can only += into. Its owner raises it with ?.Invoke, which skips it if nobody listens.",
      "Un EVENT es una botella pública donde otros solo pueden hacer +=. Su dueño lo dispara con ?.Invoke, que lo salta si nadie escucha.",
      "イベントは外から += しかできない公開のビン。持ち主が ?.Invoke で発火。聞き手がいなければ何もしない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var door = new Door();\ndoor.Opened += n => Console.Write("A" + n + " ");\ndoor.Opened += n => Console.Write("B" + n);\ndoor.Open();\n\nclass Door\n{\n    public event Action<int>? Opened;\n    public void Open() => Opened?.Invoke(7);\n}',
      options: ["A7 B7", "B7", "A7"],
      answer: 0,
      output: "A7 B7",
      check: { compiles: true, stdout: "A7 B7" },
      explain: L("An event is a multicast delegate: both listeners run, in order, with 7.", "Un event es un delegado multicast: corren los dos oyentes, en orden, con 7.", "イベントはマルチキャストのデリゲート。2つの聞き手が順に 7 を受け取る。"),
      win: [{ t: "print", text: "A7 B7" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "var door = new Door();\ndoor.Opened?.Invoke(1);\n\nclass Door\n{\n    public event Action<int>? Opened;\n}",
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L("Error CS0070: outside Door, an event can only appear with += or -=. Only its owner may raise it.", "Error CS0070: fuera de Door, un event solo admite += o -=. Solo su dueño puede dispararlo.", "エラー CS0070：Door の外では += か -= しかできない。発火できるのは持ち主だけ。"),
      win: [{ t: "shake" }, { t: "banner", text: L("CS0070", "CS0070", "CS0070") }],
    },
    {
      kind: "run",
      prompt: L("Fix the loop trap: it must print 012", "Arregla la trampa del for: debe imprimir 012", "ループのワナを直そう：012 と表示させて"),
      starter: "using System;\nusing System.Collections.Generic;\n\nvar acts = new List<Action>();\nfor (int i = 0; i < 3; i++)\n{\n    acts.Add(() => Console.Write(i));\n}\nforeach (var a in acts) a();\nConsole.WriteLine();\n",
      solution: "using System;\nusing System.Collections.Generic;\n\nvar acts = new List<Action>();\nfor (int i = 0; i < 3; i++)\n{\n    int copy = i;\n    acts.Add(() => Console.Write(copy));\n}\nforeach (var a in acts) a();\nConsole.WriteLine();\n",
      expect: "012",
      fallback: [String.raw`(int|var)\s+(\w+)\s*=\s*i\s*;[\s\S]*Write\(\s*\2\s*\)`, String.raw`foreach\s*\(\s*(var|int)\s+i\s+in`],
      explain: L("Copy i into a new local inside the loop body: each lap gets its own copy, so each lambda remembers 0, 1, 2.", "Copia i en una variable local dentro del for: cada vuelta tiene su copia y cada lambda recuerda 0, 1, 2.", "ループの中で i を新しい変数にコピー。1周ごとに別の変数なので 0, 1, 2 をおぼえる。"),
    },
  ],
};

// ─── 3.3 The caravan of helpers: LINQ basics ───────────────────────────────
const linq: LessonDef = {
  slug: "linq-basics",
  title: L("The caravan of helpers", "La caravana de ayudantes", "お手伝いキャラバン"),
  concept: "linq",
  mode: "lesson",
  xp: 75,
  enemy: "golem",
  enemyName: L("CARAVAN GOLEM", "GÓLEM CARAVANA", "キャラバンゴーレム"),
  beats: [
    say(L(
      "LINQ is a caravan of helpers. using System.Linq gives every collection Where (keep some) and Select (change each). They take lambdas!",
      "LINQ es una caravana de ayudantes. using System.Linq da a toda colección Where (filtrar) y Select (transformar). ¡Reciben lambdas!",
      "LINQ はお手伝いのキャラバン。using System.Linq で Where（選ぶ）と Select（変える）が使える。ラムダを渡すよ！",
    )),
    {
      kind: "act",
      prompt: L("Send the numbers down the caravan", "Manda los números por la caravana", "数字をキャラバンに流そう"),
      steps: [
        { label: L("THE PILE", "LA PILA", "山を用意"), line: "var nums = new List<int> { 5, 3, 8, 1, 8 };", effects: [{ t: "tag", actor: "hero", text: "nums" }, { t: "value", actor: "hero", text: "5 3 8 1 8" }] },
        { label: L("WHERE > 3", "WHERE > 3", "WHERE > 3"), line: "var big = nums.Where(n => n > 3);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Where" }, { t: "value", actor: "ally", text: "5 8 8" }] },
        { label: L("SELECT x10", "SELECT x10", "SELECT x10"), line: "var tens = big.Select(n => n * 10);", effects: [{ t: "say", actor: "ally", text: L("Times ten!", "¡Por diez!", "10倍！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: 'Console.WriteLine(string.Join(",", tens));', effects: [{ t: "print", text: "50,80,80" }], output: "50,80,80" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nvar q = nums.Where(n => n % 2 == 1).Select(n => n + 1);\nConsole.WriteLine(string.Join(",", q));',
      options: ["6,4,2", "5,3,1", "9,9"],
      answer: 0,
      output: "6,4,2",
      check: { compiles: true, stdout: "6,4,2" },
      explain: L("Where keeps the odd ones (5, 3, 1), then Select adds 1 to each. Order is kept.", "Where deja los impares (5, 3, 1) y luego Select le suma 1 a cada uno. El orden se mantiene.", "Where で奇数（5, 3, 1）を残し、Select で 1 足す。順番はそのまま。"),
      win: [{ t: "print", text: "6,4,2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nConsole.WriteLine(string.Join(",", nums.OrderBy(n => n)));',
      options: ["1,3,5,8,8", "8,8,5,3,1", "1,3,5,8"],
      answer: 0,
      output: "1,3,5,8,8",
      check: { compiles: true, stdout: "1,3,5,8,8" },
      explain: L("OrderBy sorts from small to big by the key you give (here, the number itself). Duplicates stay.", "OrderBy ordena de menor a mayor según la clave que das (aquí, el número). Los repetidos se quedan.", "OrderBy は渡したキー（ここでは数）で小さい順に並べる。重複も残る。"),
    },
    {
      kind: "pick",
      prompt: L("Biggest first, please", "Primero el mayor, por favor", "大きい順にしてね"),
      code: 'var nums = new List<int> { 5, 3, 8 };\nConsole.WriteLine(string.Join(",", nums.___(n => n)));',
      options: ["OrderByDescending", "OrderBy", "Where"],
      answer: 0,
      check: { compiles: true, stdout: "8,5,3" },
      explain: L("OrderByDescending sorts big to small: 8,5,3. OrderBy would give 3,5,8.", "OrderByDescending ordena de mayor a menor: 8,5,3. OrderBy daría 3,5,8.", "OrderByDescending は大きい順で 8,5,3。OrderBy なら 3,5,8。"),
      win: [{ t: "print", text: "8,5,3" }],
    },
    say(L(
      "Helpers that sum up: Count, Sum, Max, Distinct (drop repeats). Any asks \"at least one?\", All asks \"every one?\"",
      "Ayudantes que resumen: Count, Sum, Max, Distinct (quita repetidos). Any pregunta \"¿al menos uno?\" y All \"¿todos?\"",
      "まとめ役：Count、Sum、Max、Distinct（重複を消す）。Any は「1つでも？」、All は「全部？」と聞く。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nConsole.WriteLine(nums.Count(n => n == 8) + " " + nums.Sum() + " " + nums.Max() + " " + nums.Distinct().Count());',
      options: ["2 25 8 4", "1 25 8 5", "2 17 8 4"],
      answer: 0,
      output: "2 25 8 4",
      check: { compiles: true, stdout: "2 25 8 4" },
      explain: L("Two 8s; 5+3+8+1+8 = 25; the max is 8; without repeats there are 4 numbers.", "Dos 8; 5+3+8+1+8 = 25; el máximo es 8; sin repetidos quedan 4 números.", "8 は2つ。合計 25。最大 8。重複なしで4つ。"),
      win: [{ t: "print", text: "2 25 8 4" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nConsole.WriteLine(nums.Any(n => n > 7) + " " + nums.All(n => n > 1));',
      options: ["True False", "True True", "False False"],
      answer: 0,
      output: "True False",
      check: { compiles: true, stdout: "True False" },
      explain: L("Any: an 8 is over 7, so True. All: 1 is not over 1, so False.", "Any: un 8 es mayor que 7, así que True. All: 1 no es mayor que 1, así que False.", "Any：8 は 7 より大きいので True。All：1 は 1 より大きくないので False。"),
    },
    say(L(
      "First takes the first item and crashes if there is none. FirstOrDefault gives the default (0 for int). Single demands EXACTLY one.",
      "First toma el primer item y revienta si no hay. FirstOrDefault da el default (0 para int). Single exige EXACTAMENTE uno.",
      "First は最初の1つ。無いとクラッシュ。FirstOrDefault は既定値（int なら 0）。Single はちょうど1つを要求。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nConsole.WriteLine(nums.First() + " " + nums.First(n => n > 5) + " " + nums.Last());',
      options: ["5 8 8", "5 5 8", "1 8 8"],
      answer: 0,
      output: "5 8 8",
      check: { compiles: true, stdout: "5 8 8" },
      explain: L("First() is 5, the first item over 5 is 8, and Last() is the final 8.", "First() es 5, el primero mayor que 5 es 8 y Last() es el 8 final.", "First() は 5、5 より大きい最初は 8、Last() は最後の 8。"),
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "var nums = new List<int> { 5, 3, 8 };\nConsole.WriteLine(nums.First(n => n > 100));",
      options: ["InvalidOperationException", "0", L("It prints nothing", "No imprime nada", "何も表示しない")],
      answer: 0,
      check: { compiles: true, throws: "Sequence contains no matching element" },
      explain: L("No item is over 100, so First throws \"Sequence contains no matching element\".", "Ningún item es mayor que 100, así que First lanza \"Sequence contains no matching element\".", "100 より大きい物が無いので First は例外 \"Sequence contains no matching element\"。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "var nums = new List<int> { 5, 3, 8 };\nConsole.WriteLine(nums.FirstOrDefault(n => n > 100));",
      options: ["0", "null", "8"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("Nothing matches, so FirstOrDefault returns default(int), which is 0. No crash.", "Nada coincide, así que FirstOrDefault devuelve default(int), que es 0. Sin reventar.", "一致しないので default(int) の 0 を返す。クラッシュしない。"),
      win: [{ t: "value", actor: "hero", text: "0" }, { t: "print", text: "0" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "var nums = new List<int> { 5, 3, 8, 1, 8 };\nConsole.WriteLine(nums.Single(n => n == 8));",
      options: ["InvalidOperationException", "8", L("It prints 8 8", "Imprime 8 8", "8 8 と表示")],
      answer: 0,
      check: { compiles: true, throws: "Sequence contains more than one matching element" },
      explain: L("Single wants exactly one match. There are two 8s, so it throws.", "Single quiere exactamente una coincidencia. Hay dos 8, así que lanza una excepción.", "Single はちょうど1つを要求。8 が2つあるので例外。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "GroupBy sorts items into piles by a key. Query syntax reads like a sentence: from n in nums where ... select ...",
      "GroupBy reparte items en pilas según una clave. La sintaxis de consulta se lee como frase: from n in nums where ... select ...",
      "GroupBy はキーごとに山分けする。クエリ構文は文のように読める：from n in nums where ... select ...",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var words = new[] { "apple", "avocado", "banana" };\nforeach (var g in words.GroupBy(w => w[0]))\n    Console.Write($"{g.Key}:{string.Join("+", g)} ");',
      options: ["a:apple+avocado b:banana", "a:apple a:avocado b:banana", "apple+avocado banana"],
      answer: 0,
      output: "a:apple+avocado b:banana",
      check: { compiles: true, stdout: "a:apple+avocado b:banana" },
      explain: L("Each group has a Key (the first letter) and holds its items. Groups come in first-seen order.", "Cada grupo tiene una Key (la primera letra) y guarda sus items. Los grupos salen en el orden en que aparecen.", "各グループは Key（頭文字）と中身を持つ。グループは最初に出た順。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var nums = new List<int> { 5, 3, 8, 1, 8 };\nvar q = from n in nums\n        where n % 2 == 0\n        select n / 2;\nConsole.WriteLine(string.Join(",", q));',
      options: ["4,4", "8,8", "2,1"],
      answer: 0,
      output: "4,4",
      check: { compiles: true, stdout: "4,4" },
      explain: L("Same as nums.Where(n => n % 2 == 0).Select(n => n / 2): the evens 8 and 8, halved.", "Igual que nums.Where(n => n % 2 == 0).Select(n => n / 2): los pares 8 y 8, a la mitad.", "nums.Where(...).Select(n => n / 2) と同じ。偶数の 8 と 8 を半分に。"),
    },
    say(L(
      "How does a List get Where? EXTENSION methods: a static method in a static class whose first parameter has this.",
      "¿Cómo obtiene un List el Where? Métodos de EXTENSIÓN: un método static en una clase static cuyo primer parámetro lleva this.",
      "List に Where があるのはなぜ？拡張メソッド。static クラスの static メソッドで、最初の引数に this をつける。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Console.WriteLine("hello".Shout());\n\nstatic class Ext\n{\n    public static string Shout(this string s) => s.ToUpper() + "!";\n}',
      options: ["HELLO!", "hello!", "HELLO"],
      answer: 0,
      output: "HELLO!",
      check: { compiles: true, stdout: "HELLO!" },
      explain: L("this string s lets you call Shout as if it were a method of string. LINQ is built the same way.", "this string s permite llamar a Shout como si fuera un método de string. LINQ está hecho igual.", "this string s で string のメソッドのように呼べる。LINQ も同じ仕組み。"),
      win: [{ t: "print", text: "HELLO!" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "using System;\n\nint[] a = { 1, 2, 3 };\nConsole.WriteLine(a.Sum());",
      options: [YES, NO],
      answer: 1,
      check: { compiles: false, program: "using System;\n\nint[] a = { 1, 2, 3 };\nConsole.WriteLine(a.Sum());\n" },
      explain: L("Error CS1061: without using System.Linq, the Sum extension method isn't visible on int[].", "Error CS1061: sin using System.Linq, el método de extensión Sum no se ve en int[].", "エラー CS1061：using System.Linq が無いと拡張メソッド Sum は見えない。"),
      win: [{ t: "shake" }, { t: "banner", text: L("CS1061", "CS1061", "CS1061") }],
    },
    {
      kind: "run",
      prompt: L("The top score should be 90", "El mejor puntaje debería ser 90", "トップスコアは 90 のはず"),
      starter: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nvar scores = new List<int> { 40, 90, 70 };\nvar top = scores.OrderBy(s => s).First();\nConsole.WriteLine($"top: {top}");\n',
      solution: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nvar scores = new List<int> { 40, 90, 70 };\nvar top = scores.OrderByDescending(s => s).First();\nConsole.WriteLine($"top: {top}");\n',
      expect: "top: 90",
      fallback: [String.raw`OrderByDescending\(`, String.raw`scores\.Max\(\)`, String.raw`OrderBy\([^)]*\)\s*\.\s*Last\(\)`],
      explain: L("OrderBy puts the smallest first. Use OrderByDescending, or simply scores.Max().", "OrderBy pone primero al menor. Usa OrderByDescending, o simplemente scores.Max().", "OrderBy は小さい順。OrderByDescending か、scores.Max() を使おう。"),
    },
  ],
};

// ─── 3.4 Nothing moves until you pull: deferred execution ──────────────────
const deferred: LessonDef = {
  slug: "deferred-execution",
  title: L("Nothing moves until pulled", "Nada se mueve sin tirar", "引くまで動かない"),
  concept: "linq",
  mode: "lesson",
  xp: 80,
  enemy: "csharp/deadlock-hourglass",
  enemyName: L("IDLE HOURGLASS", "RELOJ OCIOSO", "ナマケ砂時計"),
  beats: [
    say(L(
      "A LINQ query is a RECIPE, not a result. Nothing runs until someone pulls: foreach, ToList, Count, First...",
      "Una consulta LINQ es una RECETA, no un resultado. Nada corre hasta que alguien tira: foreach, ToList, Count, First...",
      "LINQ のクエリは結果ではなくレシピ。だれかが引く（foreach、ToList、Count、First…）まで何も動かない。",
    )),
    {
      kind: "act",
      prompt: L("Write the recipe, change the pile, then pull", "Escribe la receta, cambia la pila y tira", "レシピを書き、山を変えてから引こう"),
      steps: [
        { label: L("THE PILE", "LA PILA", "山を用意"), line: "var src = new List<int> { 1, 2, 3 };", effects: [{ t: "tag", actor: "hero", text: "src" }, { t: "value", actor: "hero", text: "1 2 3" }] },
        { label: L("RECIPE", "RECETA", "レシピ"), line: "var q = src.Where(n => n > 1);", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "scroll", holder: "ally" }, { t: "tag", actor: "ally", text: "q" }, { t: "say", actor: "ally", text: L("Just a recipe...", "Solo una receta...", "ただのレシピ…") }] },
        { label: L("ADD 4", "AGREGAR 4", "4 を足す"), line: "src.Add(4);", effects: [{ t: "value", actor: "hero", text: "1 2 3 4" }] },
        { label: L("PULL", "TIRAR", "引く"), line: "Console.WriteLine(q.Count());", effects: [{ t: "say", actor: "ally", text: L("Running now!", "¡Ahora corro!", "いま実行！") }, { t: "print", text: "3" }], output: "3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "var src = new List<int> { 1, 2, 3 };\nvar q = src.Where(n => n > 1);\nsrc.Add(4);\nConsole.WriteLine(q.Count());",
      options: ["3", "2", "4"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("The Where runs at Count(), after 4 was added: 2, 3 and 4 pass.", "El Where corre en Count(), después de agregar el 4: pasan 2, 3 y 4.", "Where が動くのは Count() の時。4 を足した後なので 2, 3, 4 が通る。"),
      win: [{ t: "print", text: "3" }],
    },
    say(L(
      "ToList() pulls RIGHT NOW and keeps a snapshot in a new list. Later changes to the source don't touch it.",
      "ToList() tira AHORA MISMO y guarda una foto en una lista nueva. Los cambios posteriores a la fuente no la tocan.",
      "ToList() はその場で引いて、新しいリストにスナップショットを残す。後で元を変えても影響しない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "var src = new List<int> { 1, 2, 3 };\nvar q = src.Where(n => n > 1).ToList();\nsrc.Add(4);\nConsole.WriteLine(q.Count);",
      options: ["2", "3", "4"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("ToList ran the Where before 4 existed: the snapshot holds 2 and 3.", "ToList corrió el Where antes de que existiera el 4: la foto tiene 2 y 3.", "ToList は 4 を足す前に Where を実行。中身は 2 と 3。"),
      setup: [{ t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "clone", to: "ally" }, { t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var q = new[] { 1, 2, 3 }.Select(n => { Console.Write("s" + n + " "); return n; });\nConsole.Write("before ");\nforeach (var x in q) { }',
      options: ["before s1 s2 s3", "s1 s2 s3 before", "before"],
      answer: 0,
      output: "before s1 s2 s3",
      check: { compiles: true, stdout: "before s1 s2 s3" },
      explain: L("Building the Select prints nothing. The lambda only runs when foreach pulls each item.", "Armar el Select no imprime nada. La lambda solo corre cuando foreach tira de cada item.", "Select を作っただけでは何も出ない。foreach が引く時にラムダが動く。"),
    },
    say(L(
      "When pulled, ONE item walks the whole caravan before the next one starts. Watch Where (w) and Select (s) take turns.",
      "Al tirar, UN item recorre toda la caravana antes de que salga el siguiente. Mira cómo Where (w) y Select (s) se turnan.",
      "引かれると、1つの要素がキャラバン全体を通ってから次が出発。Where（w）と Select（s）が交互に動くよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'new[] { 1, 2, 3, 4 }\n    .Where(n => { Console.Write("w" + n + " "); return n % 2 == 0; })\n    .Select(n => { Console.Write("s" + n + " "); return n; })\n    .ToList();',
      options: ["w1 w2 s2 w3 w4 s4", "w1 w2 w3 w4 s2 s4", "s2 s4 w1 w2 w3 w4"],
      answer: 0,
      output: "w1 w2 s2 w3 w4 s4",
      check: { compiles: true, stdout: "w1 w2 s2 w3 w4 s4" },
      explain: L("Item by item: 1 fails Where; 2 passes Where and goes straight into Select; then 3, then 4.", "Item por item: 1 no pasa el Where; 2 pasa el Where y va directo al Select; luego 3, luego 4.", "1つずつ：1 は Where で落ち、2 は Where を通ってすぐ Select へ。次に 3、4。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var first = new[] { 1, 2, 3 }\n    .Select(n => { Console.Write("s" + n + " "); return n; })\n    .First();\nConsole.WriteLine(first);',
      options: ["s1 1", "s1 s2 s3 1", "1"],
      answer: 0,
      output: "s1 1",
      check: { compiles: true, stdout: "s1 1" },
      explain: L("First pulls just one item and stops. Only the work that is needed runs.", "First tira de un solo item y se detiene. Solo corre el trabajo necesario.", "First は1つだけ引いて止まる。必要な分しか動かない。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int limit = 2;\nvar q = new[] { 1, 2, 3 }.Where(n => n > limit);\nlimit = 0;\nConsole.WriteLine(q.Count());",
      options: ["3", "1", "0"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("The lambda captured the variable limit (a closure). At Count() it is 0, so all three pass.", "La lambda capturó la variable limit (un closure). En Count() vale 0, así que pasan los tres.", "ラムダは変数 limit をつかんでいる。Count() の時は 0 なので3つとも通る。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int calls = 0;\nvar q = new[] { 1, 2, 3 }.Select(n => { calls++; return n; });\nforeach (var x in q) { }\nforeach (var x in q) { }\nConsole.WriteLine(calls);",
      options: ["6", "3", "0"],
      answer: 0,
      output: "6",
      check: { compiles: true, stdout: "6" },
      explain: L("Each foreach runs the recipe again from scratch: 3 + 3 calls. Use ToList() to run it once.", "Cada foreach corre la receta de nuevo desde cero: 3 + 3 llamadas. Usa ToList() para correrla una vez.", "foreach のたびにレシピを最初から実行：3 + 3 回。1回にしたいなら ToList()。"),
    },
    say(L(
      "Write your own lazy sequence with yield return: the method pauses at each yield until the next item is pulled.",
      "Escribe tu propia secuencia perezosa con yield return: el método se pausa en cada yield hasta que se pida el siguiente item.",
      "yield return で自分の遅延シーケンスが書ける。次が引かれるまで yield ごとに一時停止するよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'var g = Gen();\nConsole.Write("made ");\nConsole.WriteLine(g.First());\n\nstatic IEnumerable<int> Gen()\n{\n    Console.Write("g1 ");\n    yield return 1;\n    Console.Write("g2 ");\n    yield return 2;\n}',
      options: ["made g1 1", "g1 g2 made 1", "g1 made 1"],
      answer: 0,
      output: "made g1 1",
      check: { compiles: true, stdout: "made g1 1" },
      explain: L("Calling Gen() runs none of its body. First() pulls one item: g1 prints, then it pauses forever.", "Llamar a Gen() no corre nada de su cuerpo. First() tira de un item: imprime g1 y se pausa para siempre.", "Gen() を呼んでも中身は動かない。First() が1つ引いて g1 が出て、そこで止まる。"),
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'var q = new[] { 1, 0, 2 }.Select(n => 10 / n);\nConsole.Write("ok ");\nConsole.WriteLine(q.Sum());',
      options: [
        L("Prints ok, then DivideByZeroException", "Imprime ok, luego DivideByZeroException", "ok の後に DivideByZeroException"),
        L("DivideByZeroException before ok", "DivideByZeroException antes de ok", "ok の前に DivideByZeroException"),
        "ok 15",
      ],
      answer: 0,
      check: { compiles: true, throws: "DivideByZeroException" },
      explain: L("The crash waits inside the recipe. It only explodes when Sum() pulls the 0, after ok.", "El error espera dentro de la receta. Solo explota cuando Sum() tira del 0, después de ok.", "エラーはレシピの中で待っている。Sum() が 0 を引いた時、ok の後に爆発。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "order",
      prompt: L("Order it so it prints 2", "Ordénalo para que imprima 2", "2 と表示される順に並べよう"),
      lines: [
        "var src = new List<int> { 1, 2, 3 };",
        "var snap = src.Where(n => n > 1).ToList();",
        "src.Add(4);",
        "Console.WriteLine(snap.Count);",
      ],
      check: { compiles: true, stdout: "2" },
      explain: L("Take the ToList snapshot BEFORE adding 4, so it only holds 2 and 3.", "Toma la foto con ToList ANTES de agregar el 4, así solo tiene 2 y 3.", "4 を足す前に ToList でスナップショットを取れば、中身は 2 と 3 だけ。"),
      win: [{ t: "print", text: "2" }],
    },
    {
      kind: "run",
      prompt: L("Keep the live count after Clear: alive: 2", "Conserva la cuenta tras Clear: alive: 2", "Clear の後も数を残そう：alive: 2"),
      starter: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nvar hp = new List<int> { 5, 0, 3 };\nvar alive = hp.Where(h => h > 0);\nhp.Clear();\nConsole.WriteLine($"alive: {alive.Count()}");\n',
      solution: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nvar hp = new List<int> { 5, 0, 3 };\nvar alive = hp.Where(h => h > 0).ToList();\nhp.Clear();\nConsole.WriteLine($"alive: {alive.Count()}");\n',
      expect: "alive: 2",
      fallback: [String.raw`Where\([^;]*\)\s*\.\s*(ToList|ToArray)\(\)`, String.raw`hp\.Count\(\s*h\s*=>\s*h\s*>\s*0\s*\)\s*;[\s\S]*Clear`],
      explain: L("The Where runs at Count(), after Clear() emptied hp. Add .ToList() to snapshot the living before clearing.", "El Where corre en Count(), después de que Clear() vació hp. Agrega .ToList() para guardar a los vivos antes.", "Where は Clear() の後の Count() で動く。.ToList() で消す前に保存しよう。"),
    },
  ],
};

// ─── 3.5 Boss: the LINQ Hydra ──────────────────────────────────────────────
const boss: LessonDef = {
  slug: "linq-hydra",
  title: L("The LINQ Hydra", "La Hidra LINQ", "LINQ ヒドラ"),
  concept: "linq",
  mode: "boss",
  xp: 180,
  enemy: "dragon",
  enemyName: L("LINQ HYDRA", "HIDRA LINQ", "LINQ ヒドラ"),
  beats: [
    enemySays(L(
      "I AM THE LINQ HYDRA. Cut one query and two more grow, lazy and waiting. Do you know WHEN your code runs?",
      "SOY LA HIDRA LINQ. Corta una consulta y crecen dos más, perezosas y al acecho. ¿Sabes CUÁNDO corre tu código?",
      "我は LINQ ヒドラ。クエリを1つ切れば、怠惰な2つが生える。コードがいつ動くか分かるか？",
    )),
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: 'var bag = new Dictionary<string, int> { ["gem"] = 2 };\nConsole.WriteLine(bag["key"]);',
      options: ["KeyNotFoundException", "0", "null"],
      answer: 0,
      check: { compiles: true, throws: "KeyNotFoundException" },
      explain: L("Reading a missing key with [ ] throws. Use TryGetValue or GetValueOrDefault.", "Leer una clave que falta con [ ] lanza. Usa TryGetValue o GetValueOrDefault.", "[ ] で無いキーを読むと例外。TryGetValue か GetValueOrDefault を。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: 'var s = new HashSet<int> { 1, 2 };\nConsole.WriteLine(s.Add(2) + " " + s.Add(3) + " " + s.Count);',
      options: ["False True 3", "True True 4", "False False 2"],
      answer: 0,
      output: "False True 3",
      check: { compiles: true, stdout: "False True 3" },
      explain: L("2 is already in the set (false); 3 is new (true). Three items.", "El 2 ya está (false); el 3 es nuevo (true). Tres items.", "2 はもうある（false）、3 は新しい（true）。全部で3つ。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "Func<int, int> f = x => x + 1;\nf += x => x * 10;\nConsole.WriteLine(f(4));",
      options: ["40", "5", "50"],
      answer: 0,
      output: "40",
      check: { compiles: true, stdout: "40" },
      explain: L("Both lambdas run on 4, but a multicast Func returns only the last result: 4 * 10.", "Las dos lambdas corren con 4, pero un Func multicast devuelve solo el último resultado: 4 * 10.", "両方 4 で動くが、返るのは最後の結果 4 * 10 だけ。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 18, prompt: PRINT,
      code: "var fs = new List<Func<int>>();\nfor (int i = 1; i <= 2; i++)\n    fs.Add(() => i * 10);\nConsole.WriteLine(fs[0]() + fs[1]());",
      options: ["60", "30", "40"],
      answer: 0,
      output: "60",
      check: { compiles: true, stdout: "60" },
      explain: L("One shared i, which is 3 when the loop ends: 30 + 30 = 60.", "Un solo i compartido, que vale 3 al terminar el for: 30 + 30 = 60.", "共有の i はループ後 3。30 + 30 = 60。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "pick", time: 15,
      prompt: L("No crash when nothing matches", "Sin reventar si nada coincide", "一致が無くてもクラッシュしない"),
      code: "var hp = new List<int> { 4, 7 };\nConsole.WriteLine(hp.___(h => h > 50));",
      options: ["FirstOrDefault", "First", "Single"],
      answer: 0,
      check: { compiles: true, stdout: "0" },
      explain: L("First and Single throw on no match; FirstOrDefault returns 0.", "First y Single lanzan si no hay coincidencia; FirstOrDefault devuelve 0.", "First と Single は一致なしで例外。FirstOrDefault は 0。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 18, prompt: PRINT,
      code: 'var ws = new[] { "cat", "cow", "dog", "cub" };\nforeach (var g in ws.GroupBy(w => w[0]))\n    Console.Write(g.Key + "" + g.Count() + " ");',
      options: ["c3 d1", "c2 d1 c1", "d1 c3"],
      answer: 0,
      output: "c3 d1",
      check: { compiles: true, stdout: "c3 d1" },
      explain: L("GroupBy gathers every c-word into one group, even cub after dog. First-seen key comes first.", "GroupBy junta toda palabra con c en un grupo, incluso cub después de dog. La primera clave vista va primero.", "GroupBy は c の単語を1つにまとめる（dog の後の cub も）。先に出たキーが先。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "var src = new List<int> { 5, 6 };\nvar q = src.Select(n => n * 2);\nsrc[0] = 1;\nConsole.WriteLine(q.First());",
      options: ["2", "10", "12"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("Deferred: Select runs at First(), after src[0] became 1.", "Diferido: el Select corre en First(), después de que src[0] pasó a 1.", "遅延実行：Select は First() の時に動く。src[0] はもう 1。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict", time: 20, prompt: PRINT,
      code: 'var r = new[] { 3, 4, 5 }\n    .Where(n => { Console.Write("w" + n + " "); return n > 3; })\n    .Select(n => { Console.Write("s" + n + " "); return n; })\n    .First();',
      options: ["w3 w4 s4", "w3 w4 w5 s4", "w3 s4"],
      answer: 0,
      output: "w3 w4 s4",
      check: { compiles: true, stdout: "w3 w4 s4" },
      explain: L("Items flow one at a time, and First stops at the first survivor: 4. The 5 is never touched.", "Los items fluyen de a uno, y First se detiene en el primer sobreviviente: 4. El 5 nunca se toca.", "1つずつ流れ、First は最初に残った 4 で止まる。5 には触れない。"),
      win: [{ t: "attack", from: "hero", to: "enemy", dmg: 2 }],
    },
    {
      kind: "predict", time: 15, prompt: COMPILES,
      code: "List<object> l = new List<string>();",
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L("Error CS0029: a List<string> is not a List<object>, or you could Add an int to a string list.", "Error CS0029: un List<string> no es un List<object>; si no, podrías meter un int en una lista de strings.", "エラー CS0029：List<string> は List<object> ではない。でないと int を入れられてしまう。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "run",
      prompt: L("Slay the even heads: print left: 1,3", "Corta las cabezas pares: imprime left: 1,3", "偶数の首を倒そう：left: 1,3 と表示"),
      starter: 'using System;\nusing System.Collections.Generic;\n\nvar mobs = new List<int> { 1, 2, 3, 4 };\nforeach (var m in mobs)\n    if (m % 2 == 0) mobs.Remove(m);\nConsole.WriteLine($"left: {string.Join(",", mobs)}");\n',
      solution: 'using System;\nusing System.Collections.Generic;\n\nvar mobs = new List<int> { 1, 2, 3, 4 };\nmobs.RemoveAll(m => m % 2 == 0);\nConsole.WriteLine($"left: {string.Join(",", mobs)}");\n',
      expect: "left: 1,3",
      fallback: [String.raw`RemoveAll\(`, String.raw`Where\([^;]*\)\s*\.\s*(ToList|ToArray)\(\)`, String.raw`foreach\s*\(\s*var\s+\w+\s+in\s+mobs\s*\.\s*(ToList|ToArray)\(\)`],
      explain: L("Removing inside foreach throws. RemoveAll(m => m % 2 == 0) removes every match in one safe step.", "Quitar dentro de un foreach lanza. RemoveAll(m => m % 2 == 0) quita todas las coincidencias en un paso seguro.", "foreach の中で消すと例外。RemoveAll(m => m % 2 == 0) なら一度に安全に消せる。"),
    },
  ],
};

export const linqPeaks: RegionDef = {
  slug: "linq-peaks",
  name: L("Linq Peaks", "Picos Linq", "リンクピーク"),
  subtitle: L("Collections, lambdas and LINQ", "Colecciones, lambdas y LINQ", "コレクション・ラムダ・LINQ"),
  theme: "mountain",
  lessons: [collections, delegates, linq, deferred, boss],
};
