import type { ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Written-test formats for moon Shadera (WebGL): trace tables (dry-run the code, fill the values) and
// debugging tasks (tap the buggy line, then fix it). There is no GPU in the runner, so every item is the
// pure math the pipeline does: clip space, strides and offsets, typed arrays, index buffers, column-major
// matrices, depth. The validator runs every `verify` and proves each fix passes the tests while the
// buggy code and the near misses fail.

const code = (...lines: string[]) => lines.join("\n");

// ─── Junior: trace tables ─────────────────────────────────────────────────────

/** Junior trace: canvas pixels to clip space, with the y flip. */
export const pixelToClipTrace: ExamQuestion = {
  kind: "trace",
  topic: "clip_space",
  difficulty: 1,
  prompt: L("Trace table: pixels to clip space", "Tabla de traza: de píxeles a clip space", "トレース：ピクセル→クリップ空間"),
  brief: L(
    "One row per point. Write x and y with 2 decimals, as toFixed(2) prints them.",
    "Una fila por punto. Escribe x e y con 2 decimales, como los imprime toFixed(2).",
    "1行が1点。x と y は toFixed(2) と同じく小数2桁で書く。",
  ),
  code: code(
    "const width = 800;",
    "const height = 600;",
    "for (const [px, py] of [[0, 0], [400, 150], [800, 600]]) {",
    "  const x = (px / width) * 2 - 1;",
    "  const y = 1 - (py / height) * 2;",
    "}",
  ),
  columns: ["px", "x", "y"],
  rows: [
    { label: "(0, 0)", cells: ["0", "-1.00", "1.00"], given: [0] },
    { label: "(400, 150)", cells: ["400", "0.00", "0.50"], given: [0] },
    { label: "(800, 600)", cells: ["800", "1.00", "-1.00"], given: [0] },
  ],
  verify: code(
    "const width = 800;",
    "const height = 600;",
    "for (const [px, py] of [[0, 0], [400, 150], [800, 600]]) {",
    "  const x = (px / width) * 2 - 1;",
    "  const y = 1 - (py / height) * 2;",
    "  console.log(`${px} | ${x.toFixed(2)} | ${y.toFixed(2)}`);",
    "}",
  ),
  explain: L(
    "x maps 0..800 to -1..1. Canvas y grows down but clip y grows up, so y = 150 of 600 is 0.50, above the center.",
    "x lleva 0..800 a -1..1. La y del canvas crece hacia abajo y la de clip hacia arriba: y = 150 de 600 es 0.50, sobre el centro.",
    "x は 0..800 を -1..1 へ。canvas の y は下向き、クリップは上向きなので 600 中 150 は 0.50（中央より上）。",
  ),
};

/** Junior trace: byte offsets in an interleaved x y z u v buffer. */
export const strideOffsetTrace: ExamQuestion = {
  kind: "trace",
  topic: "attributes",
  difficulty: 1,
  prompt: L("Trace table: byte offsets in a vertex buffer", "Tabla de traza: offsets en un vertex buffer", "トレース：頂点バッファのバイト位置"),
  brief: L(
    "Each vertex is x y z u v (5 floats). One row per pass: the byte where its position and its UV start.",
    "Cada vértice es x y z u v (5 floats). Una fila por vuelta: el byte donde empiezan su posición y su UV.",
    "各頂点は x y z u v（float 5個）。1行が1周：位置と UV の開始バイト。",
  ),
  code: code(
    "const FLOAT = 4;",
    "const stride = 5 * FLOAT;",
    "const uvOffset = 3 * FLOAT;",
    "for (let i = 0; i < 3; i++) {",
    "  const posByte = i * stride;",
    "  const uvByte = posByte + uvOffset;",
    "}",
  ),
  columns: ["i", "posByte", "uvByte"],
  rows: [
    { label: L("pass 1", "vuelta 1", "1周目"), cells: ["0", "0", "12"], given: [0] },
    { label: L("pass 2", "vuelta 2", "2周目"), cells: ["1", "20", "32"], given: [0] },
    { label: L("pass 3", "vuelta 3", "3周目"), cells: ["2", "40", "52"], given: [0] },
  ],
  verify: code(
    "const FLOAT = 4;",
    "const stride = 5 * FLOAT;",
    "const uvOffset = 3 * FLOAT;",
    "for (let i = 0; i < 3; i++) {",
    "  const posByte = i * stride;",
    "  const uvByte = posByte + uvOffset;",
    "  console.log(`${i} | ${posByte} | ${uvByte}`);",
    "}",
  ),
  explain: L(
    "The stride is 5 floats × 4 bytes = 20, and the UV skips the 3 position floats: 12 bytes. Vertex i starts at i × 20.",
    "El stride es 5 floats × 4 bytes = 20, y la UV salta los 3 floats de posición: 12 bytes. El vértice i empieza en i × 20.",
    "ストライドは 5 float × 4 バイト = 20。UV は位置の 3 float を飛ばして 12 バイト。頂点 i は i × 20 から。",
  ),
};

// ─── Mid: trace tables ────────────────────────────────────────────────────────

/** Mid trace: an index buffer for a row of quads. */
export const quadIndexTrace: ExamQuestion = {
  kind: "trace",
  topic: "drawing",
  difficulty: 2,
  prompt: L("Trace table: an index buffer for quads", "Tabla de traza: un index buffer de quads", "トレース：四角形のインデックス"),
  brief: L(
    "Each quad has 4 vertices and becomes 2 triangles. One row per pass, after the push.",
    "Cada quad tiene 4 vértices y se vuelve 2 triángulos. Una fila por vuelta, después del push.",
    "四角形は頂点4個で三角形2つ。1行が1周（push の後）。",
  ),
  code: code(
    "const indices: number[] = [];",
    "for (let q = 0; q < 3; q++) {",
    "  const b = q * 4;",
    "  indices.push(b, b + 1, b + 2, b, b + 2, b + 3);",
    "}",
  ),
  columns: ["q", "b", "indices.length", "indices.at(-1)"],
  rows: [
    { label: L("pass 1", "vuelta 1", "1周目"), cells: ["0", "0", "6", "3"], given: [0] },
    { label: L("pass 2", "vuelta 2", "2周目"), cells: ["1", "4", "12", "7"], given: [0] },
    { label: L("pass 3", "vuelta 3", "3周目"), cells: ["2", "8", "18", "11"], given: [0] },
  ],
  verify: code(
    "const indices: number[] = [];",
    "for (let q = 0; q < 3; q++) {",
    "  const b = q * 4;",
    "  indices.push(b, b + 1, b + 2, b, b + 2, b + 3);",
    "  console.log(`${q} | ${b} | ${indices.length} | ${indices.at(-1)}`);",
    "}",
  ),
  explain: L(
    "Vertices advance 4 per quad but indices 6 per quad: two triangles share the corners b and b + 2.",
    "Los vértices avanzan 4 por quad pero los índices 6: los dos triángulos comparten las esquinas b y b + 2.",
    "頂点は1枚ごとに4、インデックスは6進む。2つの三角形が角 b と b + 2 を共有する。",
  ),
};

/** Mid trace: what typed arrays do with out-of-range values. */
export const typedArrayTrace: ExamQuestion = {
  kind: "trace",
  topic: "buffers",
  difficulty: 2,
  prompt: L("Trace table: storing values in typed arrays", "Tabla de traza: valores en typed arrays", "トレース：型付き配列への格納"),
  brief: L(
    "One row per value v: what each array holds after the store.",
    "Una fila por valor v: lo que guarda cada array después de asignar.",
    "1行が1つの値 v：代入後に各配列が持つ値。",
  ),
  code: code(
    "const u8 = new Uint8Array(1);",
    "const c8 = new Uint8ClampedArray(1);",
    "const u16 = new Uint16Array(1);",
    "for (const v of [300, -5, 1.6, 70000]) {",
    "  u8[0] = v;",
    "  c8[0] = v;",
    "  u16[0] = v;",
    "}",
  ),
  columns: ["v", "u8[0]", "c8[0]", "u16[0]"],
  rows: [
    { label: "v = 300", cells: ["300", "44", "255", "300"], given: [0] },
    { label: "v = -5", cells: ["-5", "251", "0", "65531"], given: [0] },
    { label: "v = 1.6", cells: ["1.6", "1", "2", "1"], given: [0] },
    { label: "v = 70000", cells: ["70000", "112", "255", "4464"], given: [0] },
  ],
  verify: code(
    "const u8 = new Uint8Array(1);",
    "const c8 = new Uint8ClampedArray(1);",
    "const u16 = new Uint16Array(1);",
    "for (const v of [300, -5, 1.6, 70000]) {",
    "  u8[0] = v;",
    "  c8[0] = v;",
    "  u16[0] = v;",
    "  console.log(`${v} | ${u8[0]} | ${c8[0]} | ${u16[0]}`);",
    "}",
  ),
  explain: L(
    "Uint arrays drop the fraction and wrap modulo 2^n (300 → 44, 70000 → 4464). Clamped arrays round and clamp to 0..255.",
    "Los Uint descartan la fracción y dan la vuelta módulo 2^n (300 → 44, 70000 → 4464). Los Clamped redondean y limitan a 0..255.",
    "Uint 配列は小数を捨て 2^n で折り返す（300→44、70000→4464）。Clamped は丸めて 0..255 に収める。",
  ),
};

// ─── Mid: debugging tasks ─────────────────────────────────────────────────────

/** Mid debug: byte offsets used as float indexes. */
export const readAttributeDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "attributes",
  difficulty: 2,
  prompt: L("Debug: read one attribute from a buffer", "Depura: leer un atributo de un buffer", "デバッグ：バッファから属性を読む"),
  brief: L(
    "readAttribute(data, vertex, strideBytes, offsetBytes, size) should return the size floats of one attribute, given the same stride and offset in bytes that vertexAttribPointer takes. With x y z u v vertices, readAttribute(data, 1, 20, 12, 2) should be the UV of vertex 1, but it returns undefined values.",
    "readAttribute(data, vertex, strideBytes, offsetBytes, size) debería devolver los size floats de un atributo, con el mismo stride y offset en bytes que recibe vertexAttribPointer. Con vértices x y z u v, readAttribute(data, 1, 20, 12, 2) debería ser la UV del vértice 1, pero devuelve valores undefined.",
    "readAttribute(data, vertex, strideBytes, offsetBytes, size) は vertexAttribPointer と同じバイト単位の stride と offset で、属性の float を size 個返すはず。x y z u v の頂点で readAttribute(data, 1, 20, 12, 2) は頂点1の UV のはずが undefined になる。",
  ),
  code: code(
    "function readAttribute(data: Float32Array, vertex: number, strideBytes: number, offsetBytes: number, size: number): number[] {",
    "  const start = vertex * strideBytes + offsetBytes;",
    "  const out: number[] = [];",
    "  for (let k = 0; k < size; k++) {",
    "    out.push(data[start + k]);",
    "  }",
    "  return out;",
    "}",
  ),
  bugLine: 2,
  solution: code(
    "function readAttribute(data: Float32Array, vertex: number, strideBytes: number, offsetBytes: number, size: number): number[] {",
    "  const start = (vertex * strideBytes + offsetBytes) / Float32Array.BYTES_PER_ELEMENT;",
    "  const out: number[] = [];",
    "  for (let k = 0; k < size; k++) {",
    "    out.push(data[start + k]);",
    "  }",
    "  return out;",
    "}",
  ),
  nearMiss: [
    // Converts the stride to floats but leaves the offset in bytes.
    code(
      "function readAttribute(data: Float32Array, vertex: number, strideBytes: number, offsetBytes: number, size: number): number[] {",
      "  const start = vertex * (strideBytes / 4) + offsetBytes;",
      "  const out: number[] = [];",
      "  for (let k = 0; k < size; k++) {",
      "    out.push(data[start + k]);",
      "  }",
      "  return out;",
      "}",
    ),
    // Converts the offset but leaves the stride in bytes.
    code(
      "function readAttribute(data: Float32Array, vertex: number, strideBytes: number, offsetBytes: number, size: number): number[] {",
      "  const start = vertex * strideBytes + offsetBytes / 4;",
      "  const out: number[] = [];",
      "  for (let k = 0; k < size; k++) {",
      "    out.push(data[start + k]);",
      "  }",
      "  return out;",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(readAttribute(new Float32Array([0, 1, 2, 10, 11, 5, 6, 7, 20, 21]), 1, 20, 12, 2).join(","));', expect: "20,21" },
    { run: 'console.log(readAttribute(new Float32Array([0, 1, 2, 10, 11, 5, 6, 7, 20, 21]), 0, 20, 0, 3).join(","));', expect: "0,1,2" },
    { run: 'console.log(readAttribute(new Float32Array([0, 1, 2, 10, 11, 5, 6, 7, 20, 21]), 1, 20, 0, 3).join(","));', expect: "5,6,7", hidden: true },
    { run: 'console.log(readAttribute(new Float32Array([0, 1, 2, 10, 11, 5, 6, 7, 20, 21]), 0, 20, 12, 2).join(","));', expect: "10,11", hidden: true },
    { run: 'console.log(readAttribute(new Float32Array([1, 2, 3, 4, 5, 6]), 1, 12, 0, 3).join(","));', expect: "4,5,6", hidden: true },
  ],
  explain: L(
    "Stride and offset are bytes, but a Float32Array is indexed in floats. Dividing the byte position by 4 gives the index.",
    "Stride y offset están en bytes, pero un Float32Array se indexa en floats. Dividir la posición en bytes entre 4 da el índice.",
    "stride と offset はバイト単位だが Float32Array は float 単位で添字を取る。バイト位置を 4 で割れば添字になる。",
  ),
};

/** Mid debug: REPEAT wrapping done with %, which keeps the sign. */
export const wrapUvDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "textures",
  difficulty: 2,
  prompt: L("Debug: texture wrap modes", "Depura: modos de wrap de textura", "デバッグ：テクスチャのラップモード"),
  brief: L(
    "wrapUv(u, mode) should map a texture coordinate into 0..1 like the GPU: \"clamp\" (CLAMP_TO_EDGE), \"repeat\" (REPEAT) and \"mirror\" (MIRRORED_REPEAT). Positive coordinates work, but wrapUv(-0.25, \"repeat\") returns -0.25 instead of 0.75.",
    "wrapUv(u, mode) debería llevar una coordenada de textura a 0..1 como la GPU: \"clamp\" (CLAMP_TO_EDGE), \"repeat\" (REPEAT) y \"mirror\" (MIRRORED_REPEAT). Las coordenadas positivas funcionan, pero wrapUv(-0.25, \"repeat\") devuelve -0.25 en vez de 0.75.",
    "wrapUv(u, mode) は GPU と同じくテクスチャ座標を 0..1 に収めるはず：\"clamp\"、\"repeat\"、\"mirror\"。正の座標は動くが wrapUv(-0.25, \"repeat\") が 0.75 でなく -0.25 になる。",
  ),
  code: code(
    'function wrapUv(u: number, mode: "clamp" | "repeat" | "mirror"): number {',
    '  if (mode === "clamp") return Math.min(Math.max(u, 0), 1);',
    '  if (mode === "repeat") return u % 1;',
    "  const t = u - 2 * Math.floor(u / 2);",
    "  return t > 1 ? 2 - t : t;",
    "}",
  ),
  bugLine: 3,
  solution: code(
    'function wrapUv(u: number, mode: "clamp" | "repeat" | "mirror"): number {',
    '  if (mode === "clamp") return Math.min(Math.max(u, 0), 1);',
    '  if (mode === "repeat") return u - Math.floor(u);',
    "  const t = u - 2 * Math.floor(u / 2);",
    "  return t > 1 ? 2 - t : t;",
    "}",
  ),
  nearMiss: [
    // Drops the sign instead of wrapping: -0.25 becomes 0.25.
    code(
      'function wrapUv(u: number, mode: "clamp" | "repeat" | "mirror"): number {',
      '  if (mode === "clamp") return Math.min(Math.max(u, 0), 1);',
      '  if (mode === "repeat") return Math.abs(u % 1);',
      "  const t = u - 2 * Math.floor(u / 2);",
      "  return t > 1 ? 2 - t : t;",
      "}",
    ),
    // Always adds 1, which breaks positive coordinates.
    code(
      'function wrapUv(u: number, mode: "clamp" | "repeat" | "mirror"): number {',
      '  if (mode === "clamp") return Math.min(Math.max(u, 0), 1);',
      '  if (mode === "repeat") return (u % 1) + 1;',
      "  const t = u - 2 * Math.floor(u / 2);",
      "  return t > 1 ? 2 - t : t;",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(wrapUv(-0.25, "repeat").toFixed(2));', expect: "0.75" },
    { run: 'console.log(wrapUv(1.25, "repeat").toFixed(2));', expect: "0.25" },
    { run: 'console.log(wrapUv(1.5, "clamp").toFixed(2));', expect: "1.00", hidden: true },
    { run: 'console.log(wrapUv(1.25, "mirror").toFixed(2));', expect: "0.75", hidden: true },
    { run: 'console.log(wrapUv(-1.5, "repeat").toFixed(2));', expect: "0.50", hidden: true },
    { run: 'console.log(wrapUv(2, "repeat").toFixed(2));', expect: "0.00", hidden: true },
  ],
  explain: L(
    "In JS, % keeps the sign of the dividend, so -0.25 % 1 is -0.25. u - floor(u) is always in 0..1, which is what REPEAT does.",
    "En JS, % conserva el signo del dividendo: -0.25 % 1 es -0.25. u - floor(u) siempre cae en 0..1, que es lo que hace REPEAT.",
    "JS の % は被除数の符号を残すので -0.25 % 1 は -0.25。u - floor(u) は常に 0..1 で、REPEAT と同じ。",
  ),
};

// ─── Senior: trace table ──────────────────────────────────────────────────────

/** Senior trace: perspective depth is not linear. */
export const perspectiveDepthTrace: ExamQuestion = {
  kind: "trace",
  topic: "depth_blending",
  difficulty: 3,
  prompt: L("Trace table: perspective depth", "Tabla de traza: profundidad en perspectiva", "トレース：透視投影の深度"),
  brief: L(
    "near = 1, far = 100. One row per distance d in front of the camera; write 2 decimals, as toFixed(2).",
    "near = 1, far = 100. Una fila por distancia d delante de la cámara; escribe 2 decimales, como toFixed(2).",
    "near = 1、far = 100。1行がカメラ前方の距離 d。toFixed(2) と同じく小数2桁。",
  ),
  code: code(
    "const near = 1;",
    "const far = 100;",
    "for (const d of [2, 4, 10, 100]) {",
    "  const ndcZ = (far + near) / (far - near) - (2 * far * near) / ((far - near) * d);",
    "  const depth = ndcZ * 0.5 + 0.5;",
    "}",
  ),
  columns: ["d", "ndcZ", "depth"],
  rows: [
    { label: "d = 2", cells: ["2", "0.01", "0.51"], given: [0] },
    { label: "d = 4", cells: ["4", "0.52", "0.76"], given: [0] },
    { label: "d = 10", cells: ["10", "0.82", "0.91"], given: [0] },
    { label: "d = 100", cells: ["100", "1.00", "1.00"], given: [0] },
  ],
  verify: code(
    "const near = 1;",
    "const far = 100;",
    "for (const d of [2, 4, 10, 100]) {",
    "  const ndcZ = (far + near) / (far - near) - (2 * far * near) / ((far - near) * d);",
    "  const depth = ndcZ * 0.5 + 0.5;",
    "  console.log(`${d} | ${ndcZ.toFixed(2)} | ${depth.toFixed(2)}`);",
    "}",
  ),
  explain: L(
    "Depth goes as 1/d: one unit past the near plane already uses half the depth range, and 10..100 shares the last tenth.",
    "La profundidad va como 1/d: una unidad tras el plano near ya usa la mitad del rango, y 10..100 comparte el último décimo.",
    "深度は 1/d に比例。near から1単位で範囲の半分を使い、10..100 は最後の1割を分け合う。",
  ),
};

// ─── Senior: debugging tasks ──────────────────────────────────────────────────

/** Senior debug (ide): a texture-binding cache that forgets the wrong key on delete. */
export const textureCacheDebug: ExamQuestion = {
  kind: "debug",
  mode: "ide",
  topic: "state_machine",
  difficulty: 3,
  prompt: L("Debug: a texture binding cache", "Depura: una caché de texturas enlazadas", "デバッグ：テクスチャのバインドキャッシュ"),
  brief: L(
    "TextureBinder skips redundant GL calls and counts the real ones in calls. bound maps unit → texture. Handles are recycled ids, and deleting a texture unbinds it from every unit. After bind 7, delete 7, bind 7 (a new texture with the recycled id), calls should be 3, but it is 2: the last bind was skipped.",
    "TextureBinder evita llamadas GL redundantes y cuenta las reales en calls. bound mapea unidad → textura. Los handles son ids reciclados y borrar una textura la desenlaza de todas las unidades. Tras bind 7, delete 7, bind 7 (una textura nueva con el id reciclado), calls debería ser 3, pero es 2: se saltó el último bind.",
    "TextureBinder は冗長な GL 呼び出しを省き、実際の回数を calls に数える。bound はユニット→テクスチャ。ハンドルは再利用 id で、削除すると全ユニットから外れる。bind 7、delete 7、bind 7（同じ id の新テクスチャ）の後 calls は 3 のはずが 2：最後の bind が省かれた。",
  ),
  code: code(
    "class TextureBinder {",
    "  calls = 0;",
    "  private unit = 0;",
    "  private bound = new Map<number, number>();",
    "",
    "  activeTexture(unit: number): void {",
    "    if (unit === this.unit) return;",
    "    this.unit = unit;",
    "    this.calls++;",
    "  }",
    "",
    "  bindTexture(texture: number): void {",
    "    if (this.bound.get(this.unit) === texture) return;",
    "    this.bound.set(this.unit, texture);",
    "    this.calls++;",
    "  }",
    "",
    "  deleteTexture(texture: number): void {",
    "    for (const [unit, t] of this.bound) {",
    "      if (t === texture) this.bound.delete(texture);",
    "    }",
    "    this.calls++;",
    "  }",
    "}",
  ),
  bugLine: 20,
  solution: code(
    "class TextureBinder {",
    "  calls = 0;",
    "  private unit = 0;",
    "  private bound = new Map<number, number>();",
    "",
    "  activeTexture(unit: number): void {",
    "    if (unit === this.unit) return;",
    "    this.unit = unit;",
    "    this.calls++;",
    "  }",
    "",
    "  bindTexture(texture: number): void {",
    "    if (this.bound.get(this.unit) === texture) return;",
    "    this.bound.set(this.unit, texture);",
    "    this.calls++;",
    "  }",
    "",
    "  deleteTexture(texture: number): void {",
    "    for (const [unit, t] of this.bound) {",
    "      if (t === texture) this.bound.delete(unit);",
    "    }",
    "    this.calls++;",
    "  }",
    "}",
  ),
  nearMiss: [
    // Forgets only the active unit: a copy bound on another unit stays stale.
    code(
      "class TextureBinder {",
      "  calls = 0;",
      "  private unit = 0;",
      "  private bound = new Map<number, number>();",
      "",
      "  activeTexture(unit: number): void {",
      "    if (unit === this.unit) return;",
      "    this.unit = unit;",
      "    this.calls++;",
      "  }",
      "",
      "  bindTexture(texture: number): void {",
      "    if (this.bound.get(this.unit) === texture) return;",
      "    this.bound.set(this.unit, texture);",
      "    this.calls++;",
      "  }",
      "",
      "  deleteTexture(texture: number): void {",
      "    if (this.bound.get(this.unit) === texture) this.bound.delete(this.unit);",
      "    this.calls++;",
      "  }",
      "}",
    ),
    // Clears every unit, so later binds of other textures are not skipped any more.
    code(
      "class TextureBinder {",
      "  calls = 0;",
      "  private unit = 0;",
      "  private bound = new Map<number, number>();",
      "",
      "  activeTexture(unit: number): void {",
      "    if (unit === this.unit) return;",
      "    this.unit = unit;",
      "    this.calls++;",
      "  }",
      "",
      "  bindTexture(texture: number): void {",
      "    if (this.bound.get(this.unit) === texture) return;",
      "    this.bound.set(this.unit, texture);",
      "    this.calls++;",
      "  }",
      "",
      "  deleteTexture(texture: number): void {",
      "    this.bound.clear();",
      "    this.calls++;",
      "  }",
      "}",
    ),
  ],
  tests: [
    { run: "{\n  const gl = new TextureBinder();\n  gl.bindTexture(7);\n  gl.deleteTexture(7);\n  gl.bindTexture(7);\n  console.log(gl.calls);\n}", expect: "3" },
    { run: "{\n  const gl = new TextureBinder();\n  gl.bindTexture(1);\n  gl.bindTexture(1);\n  gl.activeTexture(0);\n  console.log(gl.calls);\n}", expect: "1" },
    { run: "{\n  const gl = new TextureBinder();\n  gl.activeTexture(1);\n  gl.bindTexture(4);\n  gl.activeTexture(0);\n  gl.bindTexture(4);\n  gl.deleteTexture(4);\n  gl.bindTexture(4);\n  gl.activeTexture(1);\n  gl.bindTexture(4);\n  console.log(gl.calls);\n}", expect: "8", hidden: true },
    { run: "{\n  const gl = new TextureBinder();\n  gl.bindTexture(2);\n  gl.activeTexture(1);\n  gl.bindTexture(3);\n  gl.deleteTexture(3);\n  gl.activeTexture(0);\n  gl.bindTexture(2);\n  console.log(gl.calls);\n}", expect: "5", hidden: true },
    { run: "{\n  const gl = new TextureBinder();\n  gl.bindTexture(5);\n  gl.deleteTexture(9);\n  gl.bindTexture(5);\n  console.log(gl.calls);\n}", expect: "2", hidden: true },
  ],
  explain: L(
    "bound is keyed by unit, but delete removed key texture, so the stale entry stayed and the next bind looked redundant. Delete the unit key.",
    "bound usa la unidad como clave, pero delete borraba la clave texture: la entrada vieja quedaba y el siguiente bind parecía redundante.",
    "bound のキーはユニットなのに texture をキーに削除していた。古い記録が残り次の bind が冗長に見えた。unit を削除する。",
  ),
};

/** Senior debug (paper): translation stored row-major in a column-major matrix. */
export const columnMajorDebug: ExamQuestion = {
  kind: "debug",
  mode: "paper",
  topic: "matrices",
  difficulty: 3,
  prompt: L("Debug: a column-major transform", "Depura: una transformación column-major", "デバッグ：列優先の変換行列"),
  brief: L(
    "These helpers build 4×4 matrices in the column-major layout uniformMatrix4fv expects (m[col * 4 + row]) and apply them to points. Scaling works, but transformPoint(translation(1, 2, 3), [0, 0, 0]) returns 0,0,0 instead of 1,2,3.",
    "Estas funciones construyen matrices 4×4 en el formato column-major que espera uniformMatrix4fv (m[col * 4 + row]) y las aplican a puntos. Escalar funciona, pero transformPoint(translation(1, 2, 3), [0, 0, 0]) devuelve 0,0,0 en vez de 1,2,3.",
    "uniformMatrix4fv が期待する列優先（m[col * 4 + row]）で 4×4 行列を作り点に適用する。拡大は動くが transformPoint(translation(1, 2, 3), [0, 0, 0]) が 1,2,3 でなく 0,0,0 になる。",
  ),
  code: code(
    "function identity(): Float32Array {",
    "  const m = new Float32Array(16);",
    "  m[0] = m[5] = m[10] = m[15] = 1;",
    "  return m;",
    "}",
    "function translation(tx: number, ty: number, tz: number): Float32Array {",
    "  const m = identity();",
    "  m[3] = tx; m[7] = ty; m[11] = tz;",
    "  return m;",
    "}",
    "function scaling(s: number): Float32Array {",
    "  const m = identity();",
    "  m[0] = m[5] = m[10] = s;",
    "  return m;",
    "}",
    "function multiply(a: Float32Array, b: Float32Array): Float32Array {",
    "  const out = new Float32Array(16);",
    "  for (let c = 0; c < 4; c++)",
    "    for (let r = 0; r < 4; r++)",
    "      for (let k = 0; k < 4; k++) out[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k];",
    "  return out;",
    "}",
    "function transformPoint(m: Float32Array, p: number[]): string {",
    "  const out = [0, 0, 0, 0];",
    "  for (let r = 0; r < 4; r++) out[r] = m[r] * p[0] + m[4 + r] * p[1] + m[8 + r] * p[2] + m[12 + r];",
    '  return out.slice(0, 3).map((v) => (v / out[3]).toFixed(1)).join(",");',
    "}",
  ),
  bugLine: 8,
  solution: code(
    "function identity(): Float32Array {",
    "  const m = new Float32Array(16);",
    "  m[0] = m[5] = m[10] = m[15] = 1;",
    "  return m;",
    "}",
    "function translation(tx: number, ty: number, tz: number): Float32Array {",
    "  const m = identity();",
    "  m[12] = tx; m[13] = ty; m[14] = tz;",
    "  return m;",
    "}",
    "function scaling(s: number): Float32Array {",
    "  const m = identity();",
    "  m[0] = m[5] = m[10] = s;",
    "  return m;",
    "}",
    "function multiply(a: Float32Array, b: Float32Array): Float32Array {",
    "  const out = new Float32Array(16);",
    "  for (let c = 0; c < 4; c++)",
    "    for (let r = 0; r < 4; r++)",
    "      for (let k = 0; k < 4; k++) out[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k];",
    "  return out;",
    "}",
    "function transformPoint(m: Float32Array, p: number[]): string {",
    "  const out = [0, 0, 0, 0];",
    "  for (let r = 0; r < 4; r++) out[r] = m[r] * p[0] + m[4 + r] * p[1] + m[8 + r] * p[2] + m[12 + r];",
    '  return out.slice(0, 3).map((v) => (v / out[3]).toFixed(1)).join(",");',
    "}",
  ),
  nearMiss: [
    // Reads the matrix row-major in transformPoint instead: single matrices work, products don't.
    code(
      "function identity(): Float32Array {",
      "  const m = new Float32Array(16);",
      "  m[0] = m[5] = m[10] = m[15] = 1;",
      "  return m;",
      "}",
      "function translation(tx: number, ty: number, tz: number): Float32Array {",
      "  const m = identity();",
      "  m[3] = tx; m[7] = ty; m[11] = tz;",
      "  return m;",
      "}",
      "function scaling(s: number): Float32Array {",
      "  const m = identity();",
      "  m[0] = m[5] = m[10] = s;",
      "  return m;",
      "}",
      "function multiply(a: Float32Array, b: Float32Array): Float32Array {",
      "  const out = new Float32Array(16);",
      "  for (let c = 0; c < 4; c++)",
      "    for (let r = 0; r < 4; r++)",
      "      for (let k = 0; k < 4; k++) out[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k];",
      "  return out;",
      "}",
      "function transformPoint(m: Float32Array, p: number[]): string {",
      "  const out = [0, 0, 0, 0];",
      "  for (let r = 0; r < 4; r++) out[r] = m[r * 4] * p[0] + m[r * 4 + 1] * p[1] + m[r * 4 + 2] * p[2] + m[r * 4 + 3];",
      '  return out.slice(0, 3).map((v) => (v / out[3]).toFixed(1)).join(",");',
      "}",
    ),
    // Moves the translation to the last column but writes w instead of z.
    code(
      "function identity(): Float32Array {",
      "  const m = new Float32Array(16);",
      "  m[0] = m[5] = m[10] = m[15] = 1;",
      "  return m;",
      "}",
      "function translation(tx: number, ty: number, tz: number): Float32Array {",
      "  const m = identity();",
      "  m[13] = tx; m[14] = ty; m[15] = tz;",
      "  return m;",
      "}",
      "function scaling(s: number): Float32Array {",
      "  const m = identity();",
      "  m[0] = m[5] = m[10] = s;",
      "  return m;",
      "}",
      "function multiply(a: Float32Array, b: Float32Array): Float32Array {",
      "  const out = new Float32Array(16);",
      "  for (let c = 0; c < 4; c++)",
      "    for (let r = 0; r < 4; r++)",
      "      for (let k = 0; k < 4; k++) out[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k];",
      "  return out;",
      "}",
      "function transformPoint(m: Float32Array, p: number[]): string {",
      "  const out = [0, 0, 0, 0];",
      "  for (let r = 0; r < 4; r++) out[r] = m[r] * p[0] + m[4 + r] * p[1] + m[8 + r] * p[2] + m[12 + r];",
      '  return out.slice(0, 3).map((v) => (v / out[3]).toFixed(1)).join(",");',
      "}",
    ),
  ],
  tests: [
    { run: "console.log(transformPoint(translation(1, 2, 3), [0, 0, 0]));", expect: "1.0,2.0,3.0" },
    { run: "console.log(transformPoint(scaling(2), [1, 2, 3]));", expect: "2.0,4.0,6.0" },
    { run: "console.log(transformPoint(multiply(translation(10, 0, 0), scaling(2)), [1, 1, 1]));", expect: "12.0,2.0,2.0", hidden: true },
    { run: "console.log(transformPoint(multiply(scaling(2), translation(10, 0, 0)), [1, 1, 1]));", expect: "22.0,2.0,2.0", hidden: true },
    { run: "console.log(transformPoint(translation(-1, 0, 5), [2, 2, 2]));", expect: "1.0,2.0,7.0", hidden: true },
  ],
  explain: L(
    "In column-major order the translation is column 3: m[12], m[13], m[14]. m[3], m[7], m[11] is the bottom row, which feeds w.",
    "En column-major la traslación es la columna 3: m[12], m[13], m[14]. m[3], m[7], m[11] es la fila de abajo, que alimenta w.",
    "列優先では平行移動は第3列 m[12]、m[13]、m[14]。m[3]、m[7]、m[11] は最下行で w に効いてしまう。",
  ),
};

/** Senior debug (paper): a software depth test with the wrong comparison. */
export const depthTestDebug: ExamQuestion = {
  kind: "debug",
  mode: "paper",
  topic: "depth_blending",
  difficulty: 3,
  prompt: L("Debug: a software depth test", "Depura: un depth test por software", "デバッグ：ソフトウェア深度テスト"),
  brief: L(
    "resolve(frags, size) replays fragments in draw order like gl.depthFunc(gl.LESS) with the depth cleared to 1.0: a fragment wins only if it is strictly nearer than what the pixel holds. It returns each pixel's color (\".\" if empty). Two fragments at the same depth on pixel 0, A then B, should leave A, but B wins.",
    "resolve(frags, size) reproduce fragmentos en orden de dibujo como gl.depthFunc(gl.LESS) con la profundidad limpia en 1.0: un fragmento gana solo si está estrictamente más cerca. Devuelve el color de cada píxel (\".\" si está vacío). Dos fragmentos a la misma profundidad en el píxel 0, A y luego B, deberían dejar A, pero gana B.",
    "resolve(frags, size) は深度 1.0 でクリアし gl.depthFunc(gl.LESS) と同じく描画順に処理する：厳密に手前のときだけ勝つ。各ピクセルの色（空なら \".\"）を返す。ピクセル0に同じ深度の A、B の順なら A が残るはずが B が勝つ。",
  ),
  code: code(
    "type Fragment = { pixel: number; depth: number; color: string };",
    "",
    "function resolve(frags: Fragment[], size: number, depthWrite = true): string {",
    "  const depth = new Array<number>(size).fill(1);",
    '  const color = new Array<string>(size).fill(".");',
    "  for (const f of frags) {",
    "    if (f.depth < 0 || f.depth > 1) continue;",
    "    if (f.depth > depth[f.pixel]) continue;",
    "    color[f.pixel] = f.color;",
    "    if (depthWrite) depth[f.pixel] = f.depth;",
    "  }",
    '  return color.join("");',
    "}",
  ),
  bugLine: 8,
  solution: code(
    "type Fragment = { pixel: number; depth: number; color: string };",
    "",
    "function resolve(frags: Fragment[], size: number, depthWrite = true): string {",
    "  const depth = new Array<number>(size).fill(1);",
    '  const color = new Array<string>(size).fill(".");',
    "  for (const f of frags) {",
    "    if (f.depth < 0 || f.depth > 1) continue;",
    "    if (f.depth >= depth[f.pixel]) continue;",
    "    color[f.pixel] = f.color;",
    "    if (depthWrite) depth[f.pixel] = f.depth;",
    "  }",
    '  return color.join("");',
    "}",
  ),
  nearMiss: [
    // Flips the test: now the farthest fragment wins (GREATER).
    code(
      "type Fragment = { pixel: number; depth: number; color: string };",
      "",
      "function resolve(frags: Fragment[], size: number, depthWrite = true): string {",
      "  const depth = new Array<number>(size).fill(1);",
      '  const color = new Array<string>(size).fill(".");',
      "  for (const f of frags) {",
      "    if (f.depth < 0 || f.depth > 1) continue;",
      "    if (f.depth < depth[f.pixel]) continue;",
      "    color[f.pixel] = f.color;",
      "    if (depthWrite) depth[f.pixel] = f.depth;",
      "  }",
      '  return color.join("");',
      "}",
    ),
    // Keeps the first fragment per pixel, whatever its depth.
    code(
      "type Fragment = { pixel: number; depth: number; color: string };",
      "",
      "function resolve(frags: Fragment[], size: number, depthWrite = true): string {",
      "  const depth = new Array<number>(size).fill(1);",
      '  const color = new Array<string>(size).fill(".");',
      "  for (const f of frags) {",
      "    if (f.depth < 0 || f.depth > 1) continue;",
      '    if (color[f.pixel] !== ".") continue;',
      "    color[f.pixel] = f.color;",
      "    if (depthWrite) depth[f.pixel] = f.depth;",
      "  }",
      '  return color.join("");',
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(resolve([{ pixel: 0, depth: 0.5, color: "A" }, { pixel: 0, depth: 0.5, color: "B" }], 1));', expect: "A" },
    { run: 'console.log(resolve([{ pixel: 0, depth: 0.8, color: "A" }, { pixel: 0, depth: 0.3, color: "B" }, { pixel: 1, depth: 0.2, color: "C" }], 3));', expect: "BC." },
    { run: 'console.log(resolve([{ pixel: 0, depth: 1, color: "A" }, { pixel: 1, depth: 0.9, color: "B" }], 2));', expect: ".B", hidden: true },
    { run: 'console.log(resolve([{ pixel: 0, depth: 0.2, color: "A" }, { pixel: 0, depth: 0.6, color: "B" }], 1));', expect: "A", hidden: true },
    { run: 'console.log(resolve([{ pixel: 0, depth: 0.4, color: "A" }, { pixel: 0, depth: 0.6, color: "B" }], 1, false));', expect: "B", hidden: true },
  ],
  explain: L(
    "> lets an equal depth pass, which is LEQUAL. LESS must reject equal depths too, so skip when f.depth >= the stored depth.",
    "> deja pasar una profundidad igual, que es LEQUAL. LESS también rechaza las iguales: salta cuando f.depth >= la guardada.",
    "> だと同じ深度が通り LEQUAL になる。LESS は等しい深度も弾くので f.depth >= 保存値なら飛ばす。",
  ),
};

export const juniorTraceDebug: ExamQuestion[] = [pixelToClipTrace, strideOffsetTrace];
export const midTraceDebug: ExamQuestion[] = [quadIndexTrace, typedArrayTrace, readAttributeDebug, wrapUvDebug];
export const seniorTraceDebug: ExamQuestion[] = [perspectiveDepthTrace, textureCacheDebug, columnMajorDebug, depthTestDebug];
