import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 3 · MODULE CASTLE  (classes and objects, mixins and lookup, class-level state, equality and copies)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
const C = (...lines: string[]) => lines.join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const VALID = L("Is this valid Ruby?", "¿Es Ruby válido?", "正しい Ruby？");

// ─── 3.1 Blueprints of the castle: classes and objects ─────────────────────
const classes: LessonDef = {
  slug: "classes-and-objects",
  title: L("Blueprints of the castle", "Planos del castillo", "城の設計図"),
  concept: "classes",
  mode: "lesson",
  xp: 75,
  enemy: "ruby/nil-ghost",
  enemyName: L("NIL GHOST", "FANTASMA NIL", "nil ゴースト"),
  beats: [
    say(L(
      "Welcome to Module Castle! A CLASS is a blueprint. Hero.new builds an object from it, and initialize sets it up.",
      "¡Bienvenido al Castillo de Módulos! Una CLASE es un plano. Hero.new construye un objeto y initialize lo prepara.",
      "モジュール城へようこそ！クラスは設計図。Hero.new でオブジェクトを作り、initialize で準備するよ。",
    )),
    {
      kind: "act",
      prompt: L("Draw the blueprint, then build a hero", "Dibuja el plano y construye un héroe", "設計図を書いて、ヒーローを作ろう"),
      steps: [
        { label: L("BLUEPRINT", "PLANO", "設計図"), line: C("class Hero", "  attr_reader :name"), effects: [{ t: "banner", text: L("class Hero", "class Hero", "class Hero") }] },
        { label: L("INITIALIZE", "INITIALIZE", "initialize"), line: C("  def initialize(name)", "    @name = name", "  end", "end"), effects: [{ t: "item", kind: "scroll", holder: "hero" }] },
        { label: L("NEW", "NEW", "new する"), line: 'rubi = Hero.new("Rubi")', effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "rubi", value: "@name" }, { t: "say", actor: "ally", text: L("I'm Rubi!", "¡Soy Rubi!", "ルビだよ！") }] },
        { label: L("ASK NAME", "PEDIR NOMBRE", "名前を聞く"), line: "puts rubi.name", effects: [{ t: "print", text: "Rubi" }], output: "Rubi" },
        {
          label: L("ASK HP", "PEDIR HP", "HP を聞く"),
          line: "puts rubi.hp",
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: L("No hp door!", "¡No hay puerta hp!", "hp の扉はない！") }],
          error: {
            compiler: "main.rb:7:in '<main>': undefined method 'hp' for an instance of Hero (NoMethodError)",
            plain: L("@vars are private. attr_reader opened a door only for name.", "Las @variables son privadas. attr_reader abrió una puerta solo para name.", "@変数は外から見えない。attr_reader は name の扉だけ開けた。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Hero", "  attr_reader :name", "  def initialize(name)", "    @name = name", "  end", "  def to_s", '    "Hero #{@name}"', "  end", "end", 'h = Hero.new("Rubi")', "puts h.name", 'puts "Hi, #{h}"'),
      options: ["Rubi\nHi, Hero Rubi", "Rubi\nHi, h", "name\nHi, Hero Rubi"],
      answer: 0,
      output: "Rubi\nHi, Hero Rubi",
      check: { compiles: true, stdout: "Rubi\nHi, Hero Rubi" },
      explain: L("puts and \"#{}\" call to_s. Define to_s and your object prints itself nicely.", "puts y \"#{}\" llaman a to_s. Defínelo y tu objeto se imprime bonito.", "puts と \"#{}\" は to_s を呼ぶ。to_s を定義すればきれいに表示される。"),
      win: [{ t: "print", text: "Rubi" }, { t: "print", text: "Hi, Hero Rubi" }],
    },
    say(L(
      "attr_reader opens a read door, attr_writer a write door, attr_accessor both. Without one, @vars stay inside.",
      "attr_reader abre una puerta de lectura, attr_writer una de escritura, attr_accessor ambas. Sin ellas, las @variables quedan adentro.",
      "attr_reader は読む扉、attr_writer は書く扉、attr_accessor は両方。なければ @変数は中に閉じたまま。",
    )),
    {
      kind: "pick",
      prompt: L("Read AND write hp", "Leer Y escribir hp", "hp を読み書きしたい"),
      code: C("class Hero", "  ___ :hp", "  def initialize", "    @hp = 10", "  end", "end", "h = Hero.new", "h.hp = 4", "puts h.hp"),
      options: ["attr_accessor", "attr_reader", "attr_writer"],
      answer: 0,
      check: { compiles: true, stdout: "4" },
      explain: L("h.hp = 4 needs a writer and h.hp needs a reader. attr_accessor gives both.", "h.hp = 4 necesita escritor y h.hp lector. attr_accessor da ambos.", "h.hp = 4 には書く扉、h.hp には読む扉が必要。attr_accessor なら両方。"),
      win: [{ t: "print", text: "4" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class Hero", "  attr_reader :name", "  def initialize(name)", "    @name = name", "  end", "end", 'Hero.new("Rubi").name = "X"'),
      options: [L("NoMethodError: no name= method", "NoMethodError: no hay método name=", "NoMethodError：name= がない"), L("name becomes X", "name pasa a ser X", "name が X になる"), "SyntaxError"],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("attr_reader makes only name. Writing needs name=, which attr_writer or attr_accessor would create.", "attr_reader solo crea name. Escribir necesita name=, que crearía attr_writer o attr_accessor.", "attr_reader が作るのは name だけ。書くには attr_writer か attr_accessor の name= が必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Hero", "  def mana", "    @mana", "  end", "end", "p Hero.new.mana"),
      options: ["nil", "0", "NameError"],
      answer: 0,
      output: "nil",
      check: { compiles: true, stdout: "nil" },
      explain: L("An instance variable that was never set is simply nil. No error.", "Una variable de instancia que nunca se asignó es simplemente nil. Sin error.", "一度も代入していないインスタンス変数は nil。エラーにはならない。"),
      win: [{ t: "print", text: "nil" }],
    },
    say(L(
      "Trap! Inside a method, hp = ... creates a NEW local variable. To call the writer, say self.hp = ...",
      "¡Trampa! Dentro de un método, hp = ... crea una variable local NUEVA. Para usar el escritor, di self.hp = ...",
      "ワナ！メソッドの中の hp = ... は新しいローカル変数を作る。書く扉を呼ぶなら self.hp = ... と書こう。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class Hero", "  attr_accessor :hp", "  def initialize", "    @hp = 10", "  end", "  def heal", "    hp = hp + 5", "  end", "end", "Hero.new.heal"),
      options: [L("NoMethodError: + for nil", "NoMethodError: + para nil", "NoMethodError：nil に +"), L("hp becomes 15", "hp pasa a 15", "hp が 15 になる"), L("Runs, nothing changes", "Corre, nada cambia", "動くが何も変わらない")],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("hp = makes a local hp, so the hp on the right is that new local: still nil. nil + 5 fails.", "hp = crea un hp local, así que el hp de la derecha es ese local nuevo: aún nil. nil + 5 falla.", "hp = でローカルの hp ができ、右の hp もそれ。まだ nil なので nil + 5 で失敗。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Boo! I'm nil!", "¡Bu! ¡Soy nil!", "ばあ！nil だよ！") }],
    },
    say(L(
      "Return self at the end of a method and calls can chain: h.hit(2).hit(3).",
      "Devuelve self al final de un método y las llamadas se encadenan: h.hit(2).hit(3).",
      "メソッドの最後で self を返すと、h.hit(2).hit(3) のようにつなげられる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Hero", "  attr_accessor :hp", "  def initialize", "    @hp = 10", "  end", "  def hit(n)", "    self.hp -= n", "    self", "  end", "end", "h = Hero.new", "h.hit(2).hit(3)", "puts h.hp"),
      options: ["5", "8", "10"],
      answer: 0,
      output: "5",
      check: { compiles: true, stdout: "5" },
      explain: L("self.hp -= n calls the writer, and returning self lets the second hit act on the same hero.", "self.hp -= n usa el escritor, y devolver self deja que el segundo hit actúe sobre el mismo héroe.", "self.hp -= n は書く扉を呼ぶ。self を返すので2回目の hit も同じヒーローに効く。"),
      win: [{ t: "attack", from: "enemy", to: "hero", dmg: 2 }, { t: "attack", from: "enemy", to: "hero", dmg: 3 }, { t: "print", text: "5" }],
    },
    say(L(
      "Methods after private are inner secrets: the class can call them, but outsiders can't.",
      "Los métodos después de private son secretos internos: la clase puede llamarlos, los de afuera no.",
      "private の後のメソッドは内緒。クラスの中からは呼べるけど、外からは呼べない。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class Vault", "  def open", '    "opened #{secret}"', "  end", "  private", "  def secret", '    "gold"', "  end", "end", "puts Vault.new.open", "Vault.new.secret"),
      options: [L("opened gold, then NoMethodError", "opened gold, luego NoMethodError", "opened gold の後 NoMethodError"), L("opened gold, then gold", "opened gold, luego gold", "opened gold と gold"), L("NoMethodError, nothing printed", "NoMethodError, nada impreso", "何も出ずに NoMethodError")],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("open calls secret from inside: fine. Vault.new.secret calls it from outside: private method error.", "open llama a secret desde adentro: bien. Vault.new.secret lo llama desde afuera: error de método privado.", "open は中から secret を呼ぶので OK。外から Vault.new.secret を呼ぶと private エラー。"),
      win: [{ t: "item", kind: "key", holder: "hero" }, { t: "print", text: "opened gold" }],
    },
    {
      kind: "predict",
      prompt: VALID,
      code: C("class hero", "end"),
      options: [L("Yes", "Sí", "はい"), L("No: class names are Constants", "No: los nombres de clase son Constantes", "いいえ：クラス名は定数")],
      answer: 1,
      check: { compiles: false },
      explain: L("A class name is a constant, so it must start with a capital letter: Hero. Ruby stops with a SyntaxError.", "El nombre de una clase es una constante: debe empezar con mayúscula, Hero. Ruby se detiene con SyntaxError.", "クラス名は定数なので大文字で始める：Hero。小文字だと SyntaxError。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Name the setup method", "Nombra el método que prepara", "準備メソッドの名前は？"),
      code: C("class Jewel", "  attr_reader :shine", "  def ___(shine)", "    @shine = shine", "  end", "end", "puts Jewel.new(7).shine"),
      answer: "initialize",
      check: { compiles: true, stdout: "7" },
      explain: L("new creates the object, then calls initialize with the same arguments.", "new crea el objeto y luego llama a initialize con los mismos argumentos.", "new がオブジェクトを作り、同じ引数で initialize を呼ぶ。"),
      win: [{ t: "item", kind: "gem", holder: "hero" }, { t: "print", text: "7" }],
    },
    {
      kind: "order",
      prompt: L("Build the class, then use it", "Arma la clase y luego úsala", "クラスを作ってから使おう"),
      lines: ["class Jewel", "  attr_reader :shine", "  def initialize(s); @shine = s; end", "end", "puts Jewel.new(9).shine"],
      check: { compiles: true, stdout: "9" },
      explain: L("class opens the blueprint, the body adds a reader and initialize, end closes it. Only then call new.", "class abre el plano, el cuerpo agrega lector e initialize, end lo cierra. Solo entonces llamas a new.", "class で開き、読む扉と initialize を書き、end で閉じる。それから new。"),
    },
    {
      kind: "run",
      prompt: L("Fix heal: it must print hp: 15", "Arregla heal: debe imprimir hp: 15", "heal を直して hp: 15 と表示させよう"),
      starter: C("class Hero", "  attr_accessor :hp", "  def initialize", "    @hp = 10", "  end", "  def heal", "    hp = hp + 5", "  end", "end", "rubi = Hero.new", "rubi.heal", 'puts "hp: #{rubi.hp}"', ""),
      solution: C("class Hero", "  attr_accessor :hp", "  def initialize", "    @hp = 10", "  end", "  def heal", "    self.hp += 5", "  end", "end", "rubi = Hero.new", "rubi.heal", 'puts "hp: #{rubi.hp}"', ""),
      expect: "hp: 15",
      fallback: [String.raw`self\.hp\s*\+=\s*5`, String.raw`@hp\s*\+=\s*5`, String.raw`self\.hp\s*=\s*(self\.|@)?hp\s*\+\s*5`, String.raw`@hp\s*=\s*@hp\s*\+\s*5`],
      explain: L("Write self.hp += 5 (calls the writer) or @hp += 5 (changes the variable directly).", "Escribe self.hp += 5 (usa el escritor) o @hp += 5 (cambia la variable directo).", "self.hp += 5（書く扉を呼ぶ）か @hp += 5（変数を直接変える）と書こう。"),
    },
  ],
};

// ─── 3.2 Shields and the line of answerers: mixins and lookup ──────────────
const mixins: LessonDef = {
  slug: "mixins-and-lookup",
  title: L("Shields and crests", "Escudos y blasones", "盾と紋章"),
  concept: "modules",
  mode: "lesson",
  xp: 80,
  enemy: "ruby/monkey-imp",
  enemyName: L("CREST IMP", "DIABLILLO BLASÓN", "紋章インプ"),
  beats: [
    say(L(
      "A class can inherit from ONE parent with <. The child gets every parent method and can override some.",
      "Una clase puede heredar de UN padre con <. El hijo recibe todos sus métodos y puede reemplazar algunos.",
      "クラスは < でひとつの親を継承できる。子は親のメソッドを全部もらい、一部を上書きできる。",
    )),
    {
      kind: "act",
      prompt: L("Build a family and follow the message", "Arma una familia y sigue el mensaje", "親子を作って、メッセージを追おう"),
      steps: [
        { label: L("PARENT", "PADRE", "親"), line: C("class Animal", "  def speak", '    "..."', "  end", "end"), effects: [{ t: "tag", actor: "hero", text: "Animal" }] },
        { label: L("CHILD", "HIJO", "子"), line: C("class Dog < Animal", "  def speak", '    super + " Woof"', "  end", "end"), effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Dog" }] },
        { label: L("SPEAK", "HABLAR", "話す"), line: "puts Dog.new.speak", effects: [{ t: "say", actor: "ally", text: L("... Woof", "... Woof", "... Woof") }, { t: "print", text: "... Woof" }], output: "... Woof" },
        { label: L("THE LINE", "LA FILA", "行列"), line: "p Dog.ancestors.take(3)", effects: [{ t: "banner", text: L("Dog > Animal > Object", "Dog > Animal > Object", "Dog→Animal") }, { t: "print", text: "[Dog, Animal, Object]" }], output: "[Dog, Animal, Object]" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Animal", "  def intro", '    "I say #{speak}"', "  end", "  def speak", '    "..."', "  end", "end", "class Dog < Animal", "  def speak", '    "Woof"', "  end", "end", "puts Dog.new.intro", "puts Animal.new.intro"),
      options: ["I say Woof\nI say ...", "I say ...\nI say ...", "I say Woof\nI say Woof"],
      answer: 0,
      output: "I say Woof\nI say ...",
      check: { compiles: true, stdout: "I say Woof\nI say ..." },
      explain: L("Lookup starts at the object's own class. intro lives in Animal, but speak is found in Dog first.", "La búsqueda empieza en la clase del objeto. intro vive en Animal, pero speak se encuentra antes en Dog.", "探索はオブジェクト自身のクラスから。intro は Animal にあるが、speak は先に Dog で見つかる。"),
      win: [{ t: "print", text: "I say Woof" }, { t: "print", text: "I say ..." }],
    },
    say(L(
      "super calls the parent's version. Bare super passes the SAME arguments; super() passes none.",
      "super llama a la versión del padre. super solo pasa los MISMOS argumentos; super() no pasa ninguno.",
      "super は親の版を呼ぶ。かっこなしの super は同じ引数を渡し、super() は何も渡さない。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class A", "  def hi(x)", '    "A #{x}"', "  end", "end", "class B < A", "  def hi(x)", "    super()", "  end", "end", "B.new.hi(1)"),
      options: [L("ArgumentError: 0 given, 1 expected", "ArgumentError: 0 dados, 1 esperado", "ArgumentError：0個渡し1個必要"), '"A 1"', '"A "'],
      answer: 0,
      check: { compiles: true, throws: "ArgumentError" },
      explain: L("super() sends zero arguments, but A#hi needs x. A bare super would forward 1.", "super() envía cero argumentos, pero A#hi necesita x. Un super solo reenviaría el 1.", "super() は引数ゼロだが A#hi は x が必要。かっこなし super なら 1 を渡す。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "A MODULE is a shield of skills. include it in a class and every object of that class can use them.",
      "Un MÓDULO es un escudo de habilidades. Inclúyelo en una clase y cada objeto de ella puede usarlas.",
      "モジュールはスキルの盾。クラスに include すると、そのクラスの全オブジェクトが使える。",
    )),
    {
      kind: "type",
      prompt: L("Mix the module into Bot", "Mezcla el módulo en Bot", "Bot にモジュールを混ぜよう"),
      code: C("module Greet", "  def hello", '    "hello from #{self.class}"', "  end", "end", "class Bot", "  ___ Greet", "end", "puts Bot.new.hello"),
      answer: "include",
      check: { compiles: true, stdout: "hello from Bot" },
      explain: L("include Greet adds the module's methods to every Bot. self.class is Bot.", "include Greet agrega los métodos del módulo a cada Bot. self.class es Bot.", "include Greet で全 Bot にメソッドが加わる。self.class は Bot。"),
      win: [{ t: "item", kind: "shield", holder: "hero" }, { t: "print", text: "hello from Bot" }],
    },
    say(L(
      "Lookup walks the ancestors line. include puts the module AFTER the class; prepend puts it BEFORE.",
      "La búsqueda recorre la fila de ancestors. include pone el módulo DESPUÉS de la clase; prepend, ANTES.",
      "探索は ancestors の行列をたどる。include はクラスの後ろ、prepend は前にモジュールを置く。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("module Loud", "  def hello", "    super.upcase", "  end", "end", "class Bot", "  prepend Loud", "  def hello", '    "beep"', "  end", "end", "puts Bot.new.hello", "p Bot.ancestors.take(2)"),
      options: ["BEEP\n[Loud, Bot]", "beep\n[Bot, Loud]", "BEEP\n[Bot, Loud]"],
      answer: 0,
      output: "BEEP\n[Loud, Bot]",
      check: { compiles: true, stdout: "BEEP\n[Loud, Bot]" },
      explain: L("prepend puts Loud first, so it answers and its super reaches Bot's \"beep\". A wrapper!", "prepend pone a Loud primero: responde y su super llega al \"beep\" de Bot. ¡Un envoltorio!", "prepend で Loud が先頭。先に答え、super で Bot の \"beep\" に届く。包みこみだね！"),
      win: [{ t: "print", text: "BEEP" }, { t: "print", text: "[Loud, Bot]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C('module M1; def who; "M1"; end; end', 'module M2; def who; "M2"; end; end', "class Multi", "  include M1", "  include M2", "end", "p Multi.new.who"),
      options: ['"M2"', '"M1"', "NameError"],
      answer: 0,
      output: '"M2"',
      check: { compiles: true, stdout: '"M2"' },
      explain: L("Each include lands right after the class, so the LAST included module is checked first.", "Cada include queda justo tras la clase, así que el ÚLTIMO módulo incluido se revisa primero.", "include はクラスのすぐ後ろに入る。だから最後に include したものが先に探される。"),
    },
    say(L(
      "Ruby's own mixins: define each and include Enumerable to get map, sort, max... Define <=> for Comparable.",
      "Mixins de Ruby: define each e incluye Enumerable para tener map, sort, max... Define <=> para Comparable.",
      "Ruby 標準の mixin：each を定義して Enumerable を include すると map や sort が使える。<=> なら Comparable。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Bag", "  include Enumerable", "  def initialize(*items)", "    @items = items", "  end", "  def each(&block)", "    @items.each(&block)", "  end", "end", "b = Bag.new(3, 1, 2)", "p b.sort, b.include?(2), b.max"),
      options: ["[1, 2, 3]\ntrue\n3", "[3, 1, 2]\ntrue\n3", "NoMethodError"],
      answer: 0,
      output: "[1, 2, 3]\ntrue\n3",
      check: { compiles: true, stdout: "[1, 2, 3]\ntrue\n3" },
      explain: L("Enumerable builds sort, include? and max on top of your each. One method, dozens of gifts.", "Enumerable construye sort, include? y max sobre tu each. Un método, decenas de regalos.", "Enumerable は each をもとに sort や include?、max を作る。1つ書けば何十個ももらえる。"),
      win: [{ t: "item", kind: "gem", holder: "hero" }, { t: "print", text: "[1, 2, 3]" }],
    },
    say(L(
      "extend gives a module's methods to ONE object, like the class itself, not to its instances.",
      "extend da los métodos de un módulo a UN solo objeto, como la clase misma, no a sus instancias.",
      "extend はモジュールのメソッドをひとつのオブジェクト（クラス自身など）にだけ渡す。インスタンスには渡らない。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("module Util", "  def helper", '    "h"', "  end", "end", "class Ext", "  extend Util", "end", "p Ext.helper", "Ext.new.helper"),
      options: [L('"h", then NoMethodError', '"h", luego NoMethodError', '"h" の後 NoMethodError'), L('"h" twice', '"h" dos veces', '"h" が2回'), L("NoMethodError right away", "NoMethodError de inmediato", "すぐに NoMethodError")],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("extend put helper on the Ext class object only. Instances made with Ext.new don't have it.", "extend puso helper solo en el objeto clase Ext. Las instancias de Ext.new no lo tienen.", "extend で helper を持つのはクラス Ext だけ。Ext.new のインスタンスは持たない。"),
      win: [{ t: "print", text: '"h"' }, { t: "shake" }],
    },
    say(L(
      "Duck typing: Ruby never checks an object's class, only whether it answers the message. respond_to? asks first.",
      "Duck typing: Ruby no revisa la clase, solo si el objeto responde el mensaje. respond_to? pregunta antes.",
      "ダックタイピング：Ruby はクラスを見ず、メッセージに答えるかだけを見る。respond_to? で先に聞ける。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Duck", '  def quack; "Quack"; end', "end", "class Robot", '  def quack; "beep"; end', "end", "[Duck.new, Robot.new].each { |d| puts d.quack }", "p 5.respond_to?(:quack)"),
      options: ["Quack\nbeep\nfalse", "Quack\nbeep\ntrue", "Quack\nNoMethodError"],
      answer: 0,
      output: "Quack\nbeep\nfalse",
      check: { compiles: true, stdout: "Quack\nbeep\nfalse" },
      explain: L("Both answer quack, so both work in the loop. The number 5 has no quack method.", "Ambos responden quack, así que los dos funcionan en el bucle. El número 5 no tiene quack.", "どちらも quack に答えるのでループで動く。数字の 5 には quack がない。"),
    },
    {
      kind: "run",
      prompt: L("Make versions comparable: newer: true", "Haz comparables las versiones: newer: true", "バージョンを比べられるように：newer: true"),
      starter: C("class Version", "  attr_reader :major, :minor", "  def initialize(major, minor)", "    @major, @minor = major, minor", "  end", "  def <=>(other)", "    [major, minor] <=> [other.major, other.minor]", "  end", "end", 'puts "newer: #{Version.new(1, 10) > Version.new(1, 9)}"', ""),
      solution: C("class Version", "  include Comparable", "  attr_reader :major, :minor", "  def initialize(major, minor)", "    @major, @minor = major, minor", "  end", "  def <=>(other)", "    [major, minor] <=> [other.major, other.minor]", "  end", "end", 'puts "newer: #{Version.new(1, 10) > Version.new(1, 9)}"', ""),
      expect: "newer: true",
      fallback: String.raw`include\s+Comparable`,
      explain: L("<=> alone gives no >. include Comparable builds <, >, ==, between? and clamp from it.", "<=> solo no da >. include Comparable construye <, >, ==, between? y clamp a partir de él.", "<=> だけでは > はない。include Comparable で <、>、==、between? などができる。"),
    },
  ],
};

// ─── 3.3 The castle's shared ledger: class-level state ─────────────────────
const classState: LessonDef = {
  slug: "class-level-state",
  title: L("The shared ledger", "El libro compartido", "共有の台帳"),
  concept: "classes",
  mode: "lesson",
  xp: 80,
  enemy: "ruby/hash-mimic",
  enemyName: L("LEDGER MIMIC", "MÍMICO LIBRO", "台帳ミミック"),
  beats: [
    say(L(
      "Methods can belong to the CLASS itself: def self.name. You call them on the blueprint, like Castle.guests.",
      "Los métodos pueden ser de la CLASE misma: def self.nombre. Se llaman sobre el plano, como Castle.guests.",
      "メソッドはクラス自身にも持たせられる：def self.名前。Castle.guests のように設計図に呼ぶ。",
    )),
    {
      kind: "act",
      prompt: L("Count every guest who enters the castle", "Cuenta cada invitado que entra", "城に入る客を数えよう"),
      steps: [
        { label: L("LEDGER", "LIBRO", "台帳"), line: C("class Castle", "  @@guests = 0"), effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "@@guests", value: "0" }] },
        { label: L("CLASS METHOD", "MÉTODO CLASE", "クラスメソッド"), line: C("  def self.guests", "    @@guests", "  end") },
        { label: L("COUNT", "CONTAR", "数える"), line: C("  def initialize", "    @@guests += 1", "  end", "end") },
        { label: L("TWO GUESTS", "DOS INVITADOS", "客が2人"), line: C("Castle.new", "Castle.new"), effects: [{ t: "enter", actor: "ally" }, { t: "value", actor: "hero", text: "2" }] },
        { label: L("ASK CLASS", "PREGUNTAR", "クラスに聞く"), line: "puts Castle.guests", effects: [{ t: "print", text: "2" }], output: "2" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Hero", "  attr_reader :name", "  def self.create(name)", "    new(name.upcase)", "  end", "  def initialize(name)", "    @name = name", "  end", "end", 'puts Hero.create("rubi").name'),
      options: ["RUBI", "rubi", "NoMethodError"],
      answer: 0,
      output: "RUBI",
      check: { compiles: true, stdout: "RUBI" },
      explain: L("Inside a class method, self is the class, so new means Hero.new. A tiny factory!", "Dentro de un método de clase, self es la clase, así que new es Hero.new. ¡Una pequeña fábrica!", "クラスメソッドの中の self はクラス。だから new は Hero.new。小さな工場だね！"),
      win: [{ t: "print", text: "RUBI" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class Hero", "  def self.create", '    "made"', "  end", "end", "p Hero.create", "Hero.new.create"),
      options: [L('"made", then NoMethodError', '"made", luego NoMethodError', '"made" の後 NoMethodError'), L('"made" twice', '"made" dos veces', '"made" が2回')],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("create belongs to the class object, not to the heroes it builds.", "create pertenece al objeto clase, no a los héroes que construye.", "create はクラスのもの。作られたヒーローは持っていない。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Danger! A @@var is ONE ledger shared by the class AND every subclass. A child writing it changes the parent's.",
      "¡Peligro! Una @@var es UN libro compartido por la clase Y cada subclase. Si un hijo escribe, cambia el del padre.",
      "危険！@@変数はクラスと全サブクラスで共有する1冊の台帳。子が書くと親のも変わる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Base", '  @@setting = "base"', "  def self.setting", "    @@setting", "  end", "end", "class Child < Base", '  @@setting = "child"', "end", "p Base.setting"),
      options: ['"child"', '"base"', "nil"],
      answer: 0,
      output: '"child"',
      check: { compiles: true, stdout: '"child"' },
      explain: L("Child didn't get its own @@setting: it overwrote the single shared one. That's why style guides avoid @@.", "Child no tuvo su propia @@setting: sobrescribió la única compartida. Por eso las guías evitan @@.", "Child は自分用を作らず、共有の1つを上書きした。だからスタイルガイドは @@ を避ける。"),
      win: [{ t: "shake" }, { t: "print", text: '"child"' }],
    },
    say(L(
      "Safer: a class instance variable, @x written in the class body. Each class keeps its own copy.",
      "Más seguro: una variable de instancia de clase, @x escrita en el cuerpo de la clase. Cada clase tiene la suya.",
      "安全なのはクラスインスタンス変数：クラス本体に書く @x。クラスごとに別々に持つ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Cfg", "  @level = 1", "  def self.level", "    @level", "  end", "  def level", "    @level", "  end", "end", "p Cfg.level, Cfg.new.level"),
      options: ["1\nnil", "1\n1", "nil\n1"],
      answer: 0,
      output: "1\nnil",
      check: { compiles: true, stdout: "1\nnil" },
      explain: L("The class body's @level belongs to the class object. An instance's @level is a different, unset variable.", "El @level del cuerpo pertenece al objeto clase. El @level de una instancia es otra variable, sin asignar.", "本体の @level はクラスのもの。インスタンスの @level は別の変数で、まだ nil。"),
    },
    say(L(
      "class << self opens the class's own space. attr_accessor there makes readers and writers on the class.",
      "class << self abre el espacio propio de la clase. attr_accessor ahí crea lector y escritor en la clase.",
      "class << self でクラス自身の場所を開く。そこで attr_accessor を書くとクラスに読み書きの扉ができる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Monster", "  class << self", "    attr_accessor :sound", "  end", '  self.sound = "..."', "end", "class Slime < Monster", '  self.sound = "blub"', "end", "p Monster.sound, Slime.sound"),
      options: ['"..."\n"blub"', '"blub"\n"blub"', '"..."\n"..."'],
      answer: 0,
      output: '"..."\n"blub"',
      check: { compiles: true, stdout: '"..."\n"blub"' },
      explain: L("Each class stores its own @sound, so Slime's value doesn't leak into Monster.", "Cada clase guarda su propio @sound, así que el de Slime no se filtra a Monster.", "クラスごとに自分の @sound を持つので、Slime の値は Monster にもれない。"),
      win: [{ t: "print", text: '"..."' }, { t: "print", text: '"blub"' }],
    },
    say(L(
      "CONSTANTS start with a capital: MAX = 100. Reach inside a class with Temp::MAX.",
      "Las CONSTANTES empiezan con mayúscula: MAX = 100. Entra a una clase con Temp::MAX.",
      "定数は大文字で始める：MAX = 100。クラスの中のものは Temp::MAX で取り出す。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("class Temp", "  MAX = 100", "end", "p Temp::MAX", "p Temp::MIN"),
      options: [L("100, then NameError", "100, luego NameError", "100 の後 NameError"), L("100, then nil", "100, luego nil", "100 の後 nil")],
      answer: 0,
      check: { compiles: true, throws: "NameError" },
      explain: L("Unlike @vars, a missing constant isn't nil: uninitialized constant Temp::MIN (NameError).", "A diferencia de las @vars, una constante que falta no es nil: uninitialized constant Temp::MIN (NameError).", "@変数と違い、ない定数は nil にならず NameError（uninitialized constant）。"),
      win: [{ t: "print", text: "100" }, { t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: C('NAME = "x"', 'NAME << "y"', "p NAME"),
      options: ['"xy"', '"x"', "FrozenError"],
      answer: 0,
      output: '"xy"',
      check: { compiles: true, stdout: '"xy"' },
      explain: L("A constant only promises the NAME won't be reassigned. The object itself can still change. Freeze it if needed.", "Una constante solo promete no reasignar el NOMBRE. El objeto aún puede cambiar. Congélalo si hace falta.", "定数が守るのは名前の再代入だけ。中身のオブジェクトは変えられる。必要なら freeze しよう。"),
    },
    say(L(
      "Struct.new builds a quick class with accessors. Data.define builds an immutable one: no writers at all.",
      "Struct.new arma una clase rápida con accesores. Data.define arma una inmutable: sin escritores.",
      "Struct.new はアクセサつきのクラスをすぐ作る。Data.define は変更できないクラスで、書く扉がない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("Point = Struct.new(:x, :y)", "pt = Point.new(3, 4)", "pt.x = 9", "p pt.x + pt.y, pt == Point.new(9, 4)"),
      options: ["13\ntrue", "7\ntrue", "13\nfalse"],
      answer: 0,
      output: "13\ntrue",
      check: { compiles: true, stdout: "13\ntrue" },
      explain: L("Struct gives readers and writers, and two structs with equal fields are ==.", "Struct da lectores y escritores, y dos structs con campos iguales son ==.", "Struct は読み書きの扉をくれる。フィールドが同じなら == は true。"),
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("Coord = Data.define(:lat, :lng)", "c = Coord.new(lat: 1, lng: 2)", "p c.with(lat: 5).lat", "c.lat = 3"),
      options: [L("5, then NoMethodError", "5, luego NoMethodError", "5 の後 NoMethodError"), L("5, then lat is 3", "5, luego lat es 3", "5 の後 lat が 3")],
      answer: 0,
      check: { compiles: true, throws: "NoMethodError" },
      explain: L("Data has no lat= writer. with builds a NEW copy with some fields changed.", "Data no tiene escritor lat=. with crea una copia NUEVA con algunos campos cambiados.", "Data には lat= がない。with は一部を変えた新しいコピーを作る。"),
      win: [{ t: "print", text: "5" }, { t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Make an immutable value class", "Crea una clase de valor inmutable", "変更できない値クラスを作ろう"),
      code: C("Coin = Data.___(:value)", "p Coin.new(value: 5).value"),
      answer: "define",
      check: { compiles: true, stdout: "5" },
      explain: L("Data.define(:value) builds a class with a reader for value and no writer.", "Data.define(:value) crea una clase con lector para value y sin escritor.", "Data.define(:value) で value の読む扉だけのクラスができる。"),
      win: [{ t: "item", kind: "gem", holder: "hero" }, { t: "print", text: "5" }],
    },
    {
      kind: "run",
      prompt: L("Give each monster its own sound: Slime: blub", "Dale a cada monstruo su sonido: Slime: blub", "モンスターごとに音を：Slime: blub"),
      starter: C("class Monster", '  @@sound = "..."', "  def self.sound", "    @@sound", "  end", "end", "class Slime < Monster", '  @@sound = "blub"', "end", "class Bat < Monster", '  @@sound = "screech"', "end", 'puts "Slime: #{Slime.sound}"', ""),
      solution: C("class Monster", '  @sound = "..."', "  def self.sound", "    @sound", "  end", "end", "class Slime < Monster", '  @sound = "blub"', "end", "class Bat < Monster", '  @sound = "screech"', "end", 'puts "Slime: #{Slime.sound}"', ""),
      expect: "Slime: blub",
      fallback: String.raw`[^@]@sound\s*=\s*"blub"`,
      explain: L("Bat overwrote the one shared @@sound. Use @sound (class instance variables): each class keeps its own.", "Bat sobrescribió la única @@sound compartida. Usa @sound (variables de instancia de clase): cada clase tiene la suya.", "Bat が共有の @@sound を上書きした。@sound（クラスインスタンス変数）ならクラスごとに別。"),
    },
  ],
};

// ─── 3.4 Twins, clones and ice: equality and copies ────────────────────────
const equality: LessonDef = {
  slug: "equality-and-copies",
  title: L("Twins, clones and ice", "Gemelos, clones y hielo", "双子とクローンと氷"),
  concept: "equality",
  mode: "lesson",
  xp: 80,
  enemy: "ruby/frozen-cube",
  enemyName: L("ICE CUBE", "CUBO DE HIELO", "アイスキューブ"),
  beats: [
    say(L(
      "Three kinds of equal: == same value, eql? same value AND type, equal? the very same object.",
      "Tres tipos de igual: == mismo valor, eql? mismo valor Y tipo, equal? exactamente el mismo objeto.",
      "等しさは3種類：== は同じ値、eql? は値も型も同じ、equal? はまったく同じオブジェクト。",
    )),
    {
      kind: "act",
      prompt: L("Make twin gems and test them", "Crea gemas gemelas y ponlas a prueba", "双子の宝石を作って比べよう"),
      steps: [
        { label: L("GEM a", "GEMA a", "宝石 a"), line: 'a = "gem"', effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }] },
        { label: L("GEM b", "GEMA b", "宝石 b"), line: 'b = "gem"', effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "gem", holder: "ally" }, { t: "tag", actor: "ally", text: "b" }] },
        { label: L("c = a", "c = a", "c = a"), line: "c = a", effects: [{ t: "say", actor: "hero", text: L("c is me too!", "¡c también soy yo!", "c もわたし！") }] },
        { label: L("SAME VALUE?", "¿MISMO VALOR?", "値は同じ？"), line: "p a == b", effects: [{ t: "print", text: "true" }], output: "true" },
        { label: L("SAME OBJECT?", "¿MISMO OBJETO?", "同じ物？"), line: "p a.equal?(b)", effects: [{ t: "print", text: "false" }], output: "false" },
        { label: L("a AND c?", "¿a Y c?", "a と c は？"), line: "p a.equal?(c)", effects: [{ t: "print", text: "true" }], output: "true" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "p 1 == 1.0, 1.eql?(1.0)",
      options: ["true\nfalse", "true\ntrue", "false\nfalse"],
      answer: 0,
      output: "true\nfalse",
      check: { compiles: true, stdout: "true\nfalse" },
      explain: L("1 and 1.0 have the same value, so ==. But Integer and Float differ, so eql? is false.", "1 y 1.0 valen lo mismo, así que ==. Pero Integer y Float difieren, así que eql? es false.", "1 と 1.0 は値が同じで ==。でも Integer と Float で型が違うので eql? は false。"),
    },
    say(L(
      "Your class can define == to compare values. But Hash keys and uniq use eql? and hash, not ==.",
      "Tu clase puede definir == para comparar valores. Pero las claves de Hash y uniq usan eql? y hash, no ==.",
      "自分のクラスで == を定義できる。でも Hash のキーや uniq が使うのは == ではなく eql? と hash。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("class Card", "  attr_reader :rank", "  def initialize(r); @rank = r; end", "  def ==(o)", "    o.is_a?(Card) && rank == o.rank", "  end", "end", "p Card.new(1) == Card.new(1)", "p [Card.new(1), Card.new(1)].uniq.size"),
      options: ["true\n2", "true\n1", "false\n2"],
      answer: 0,
      output: "true\n2",
      check: { compiles: true, stdout: "true\n2" },
      explain: L("== says they're equal, but uniq asks hash and eql?, still the default identity: two cards stay.", "== dice que son iguales, pero uniq pregunta a hash y eql?, que siguen por identidad: quedan dos cartas.", "== は等しいと言うが、uniq は hash と eql? を使い、それは元のまま。だから2枚残る。"),
      win: [{ t: "print", text: "true" }, { t: "print", text: "2" }],
    },
    {
      kind: "type",
      prompt: L("Teach uniq what equal means", "Enséñale a uniq qué es igual", "uniq に等しさを教えよう"),
      code: C("class Card", "  attr_reader :rank", "  def initialize(r); @rank = r; end", "  def ==(o)", "    o.is_a?(Card) && rank == o.rank", "  end", "  alias eql? ==", "  def ___", "    rank.hash", "  end", "end", "p [Card.new(1), Card.new(1)].uniq.size"),
      answer: "hash",
      check: { compiles: true, stdout: "1" },
      explain: L("Equal objects must give the same hash. With eql? and hash defined, uniq and Hash keys work.", "Objetos iguales deben dar el mismo hash. Con eql? y hash definidos, funcionan uniq y las claves de Hash.", "等しいなら同じ hash を返すこと。eql? と hash があれば uniq も Hash のキーも動く。"),
      win: [{ t: "print", text: "1" }],
    },
    say(L(
      "dup and clone copy an object. clone also keeps the ice (frozen state); dup gives a thawed copy.",
      "dup y clone copian un objeto. clone además conserva el hielo (congelado); dup da una copia descongelada.",
      "dup と clone はコピーを作る。clone は氷（freeze 状態）も写し、dup はとけたコピーを作る。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C('a = "x".freeze', "b = a.dup", "c = a.clone", "p b.frozen?, c.frozen?"),
      options: ["false\ntrue", "true\ntrue", "false\nfalse"],
      answer: 0,
      output: "false\ntrue",
      check: { compiles: true, stdout: "false\ntrue" },
      explain: L("dup copies the contents only. clone copies the frozen state too.", "dup copia solo el contenido. clone también copia el estado congelado.", "dup は中身だけ写す。clone は freeze 状態も写す。"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "clone", to: "ally" }, { t: "print", text: "false" }, { t: "print", text: "true" }],
    },
    say(L(
      "Both copies are SHALLOW: the outer satchel is new, but the pouches inside are shared.",
      "Ambas copias son SUPERFICIALES: la bolsa de afuera es nueva, pero las bolsitas de adentro se comparten.",
      "どちらのコピーも浅い。外のかばんは新しいけど、中の小袋は共有のまま。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C('inv = [["sword"], ["potion"]]', "copy = inv.dup", 'copy[0] << "!"', 'copy << ["gem"]', "p inv"),
      options: ['[["sword", "!"], ["potion"]]', '[["sword"], ["potion"]]', '[["sword", "!"], ["potion"], ["gem"]]'],
      answer: 0,
      output: '[["sword", "!"], ["potion"]]',
      check: { compiles: true, stdout: '[["sword", "!"], ["potion"]]' },
      explain: L("copy is a new outer array, so adding [\"gem\"] doesn't touch inv. But copy[0] is the same inner array.", "copy es un array externo nuevo: agregar [\"gem\"] no toca inv. Pero copy[0] es el mismo array interno.", "copy は新しい外側の配列なので [\"gem\"] は inv に入らない。でも copy[0] は同じ内側の配列。"),
      win: [{ t: "lend", to: "ally" }, { t: "print", text: '[["sword", "!"], ["potion"]]' }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: C("a = [1, [2]].freeze", "a[1] << 3", "p a", "a << 4"),
      options: [L("[1, [2, 3]], then FrozenError", "[1, [2, 3]], luego FrozenError", "[1, [2, 3]] の後 FrozenError"), L("FrozenError right away", "FrozenError de inmediato", "すぐに FrozenError"), "[1, [2, 3], 4]"],
      answer: 0,
      check: { compiles: true, throws: "FrozenError" },
      explain: L("freeze is shallow too: the inner [2] isn't frozen, so << 3 works. Pushing onto the frozen outer array fails.", "freeze también es superficial: el [2] de adentro no está congelado, << 3 funciona. Agregar al array congelado falla.", "freeze も浅い。中の [2] は凍っていないので << 3 は OK。凍った外側への追加は失敗。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "print", text: "[1, [2, 3]]" }, { t: "shake" }],
    },
    say(L(
      "A method receives the SAME object, not a copy. Mutating it shows outside; reassigning the parameter doesn't.",
      "Un método recibe el MISMO objeto, no una copia. Mutarlo se ve afuera; reasignar el parámetro no.",
      "メソッドが受け取るのはコピーではなく同じオブジェクト。変更は外にも見えるが、引数の再代入は見えない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: C("def change(s)", '  s << "b"', "end", "def rebind(s)", '  s = "zzz"', "end", 'x = "a"', "change(x)", "rebind(x)", "p x"),
      options: ['"ab"', '"zzz"', '"a"'],
      answer: 0,
      output: '"ab"',
      check: { compiles: true, stdout: '"ab"' },
      explain: L("change mutates the shared string. rebind only moves its own local label to a new string.", "change muta el string compartido. rebind solo mueve su etiqueta local a un string nuevo.", "change は共有の文字列を変える。rebind は自分のラベルを新しい文字列に貼りかえるだけ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'p :a.equal?(:a), "a".equal?("a")',
      options: ["true\nfalse", "true\ntrue", "false\nfalse"],
      answer: 0,
      output: "true\nfalse",
      check: { compiles: true, stdout: "true\nfalse" },
      explain: L("Every :a is the same symbol object. Each \"a\" literal builds a new string.", "Cada :a es el mismo objeto símbolo. Cada literal \"a\" crea un string nuevo.", ":a はいつも同じシンボル。\"a\" は書くたびに新しい文字列ができる。"),
    },
    {
      kind: "run",
      prompt: L("Make equal cards unique: unique: 1", "Haz únicas las cartas iguales: unique: 1", "同じカードを1枚に：unique: 1"),
      starter: C("class Card", "  attr_reader :rank", "  def initialize(rank)", "    @rank = rank", "  end", "  def ==(other)", "    other.is_a?(Card) && rank == other.rank", "  end", "end", 'cards = [Card.new("A"), Card.new("A")]', 'puts "unique: #{cards.uniq.size}"', ""),
      solution: C("class Card", "  attr_reader :rank", "  def initialize(rank)", "    @rank = rank", "  end", "  def ==(other)", "    other.is_a?(Card) && rank == other.rank", "  end", "  alias eql? ==", "  def hash", "    rank.hash", "  end", "end", 'cards = [Card.new("A"), Card.new("A")]', 'puts "unique: #{cards.uniq.size}"', ""),
      expect: "unique: 1",
      fallback: [String.raw`(alias\s+eql\?|alias_method\s+:eql\?|def\s+eql\?)[\s\S]*def\s+hash`, String.raw`def\s+hash[\s\S]*(alias\s+eql\?|alias_method\s+:eql\?|def\s+eql\?)`],
      explain: L("uniq groups by hash, then confirms with eql?. Add alias eql? == and def hash = rank.hash.", "uniq agrupa por hash y confirma con eql?. Agrega alias eql? == y def hash = rank.hash.", "uniq は hash で分け、eql? で確かめる。alias eql? == と hash を足そう。"),
    },
  ],
};

// ─── Boss: The Frozen Cube ─────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "castle-boss",
  title: L("The Frozen Cube", "El Cubo Congelado", "凍れるキューブ"),
  concept: "classes",
  mode: "boss",
  xp: 170,
  enemy: "ruby/frozen-cube",
  enemyName: L("FROZEN CUBE", "CUBO CONGELADO", "凍れるキューブ"),
  beats: [
    enemySays(L(
      "I AM THE FROZEN CUBE. I freeze your objects and twist your ancestors. Who answers, who is equal, who is ice?",
      "SOY EL CUBO CONGELADO. Congelo tus objetos y enredo tus ancestros. ¿Quién responde, quién es igual, quién es hielo?",
      "我は凍れるキューブ。オブジェクトを凍らせ、祖先をねじる。答えるのはだれ？等しいのは？氷は？",
    )),
    { kind: "predict", time: 18, prompt: PRINT, code: C("module Greet", '  def hello; "hi from #{self.class}"; end', "end", "module Loud", "  def hello; super.upcase; end", "end", "class Bot", "  include Greet", "  include Loud", "end", "puts Bot.new.hello"), options: ["HI FROM BOT", "hi from Bot", "NoMethodError"], answer: 0, output: "HI FROM BOT", check: { compiles: true, stdout: "HI FROM BOT" }, explain: L("Loud was included last, so it answers first; its super reaches Greet.", "Loud se incluyó al final: responde primero y su super llega a Greet.", "最後に include した Loud が先に答え、super で Greet へ。") },
    { kind: "predict", time: 15, prompt: HAPPENS, code: C("class Hero", "  attr_accessor :hp", "  def initialize; @hp = 3; end", "  def boost", "    hp = hp * 2", "  end", "end", "Hero.new.boost"), options: [L("NoMethodError on nil", "NoMethodError sobre nil", "nil に NoMethodError"), L("hp becomes 6", "hp pasa a 6", "hp が 6 になる")], answer: 0, check: { compiles: true, throws: "NoMethodError" }, explain: L("hp = makes a local; the hp on the right is that nil local. Use self.hp.", "hp = crea un local; el hp de la derecha es ese local nil. Usa self.hp.", "hp = でローカルができ、右の hp は nil。self.hp を使おう。") },
    { kind: "predict", time: 15, prompt: PRINT, code: C("class Tower", "  @@floors = 1", "  def self.floors; @@floors; end", "end", "class Spire < Tower", "  @@floors = 9", "end", "p Tower.floors"), options: ["9", "1", "nil"], answer: 0, output: "9", check: { compiles: true, stdout: "9" }, explain: L("One @@floors is shared with every subclass; Spire overwrote it.", "Una sola @@floors se comparte con cada subclase; Spire la sobrescribió.", "@@floors は全サブクラスで共有。Spire が上書きした。") },
    { kind: "predict", time: 15, prompt: PRINT, code: C("class Card", "  attr_reader :rank", "  def initialize(r); @rank = r; end", "  def ==(o); o.is_a?(Card) && rank == o.rank; end", "  alias eql? ==", "  def hash; rank.hash; end", "end", "h = { Card.new(1) => :ace }", "p h.key?(Card.new(1))"), options: ["true", "false"], answer: 0, output: "true", check: { compiles: true, stdout: "true" }, explain: L("With eql? and hash defined, a new equal Card finds the same Hash key.", "Con eql? y hash definidos, una Card igual nueva encuentra la misma clave.", "eql? と hash があるので、等しい新しい Card で同じキーが見つかる。") },
    { kind: "predict", time: 12, prompt: PRINT, code: C('s = "abc"', "f = s.freeze", "p f.equal?(s), s.frozen?"), options: ["true\ntrue", "false\ntrue", "false\nfalse"], answer: 0, output: "true\ntrue", check: { compiles: true, stdout: "true\ntrue" }, explain: L("freeze freezes the receiver itself and returns that same object.", "freeze congela al receptor mismo y devuelve ese mismo objeto.", "freeze は自分自身を凍らせ、その同じオブジェクトを返す。") },
    { kind: "predict", time: 15, prompt: HAPPENS, code: C('s = "abc".freeze', 't = s + "d"', "p t.frozen?", 's << "d"'), options: [L("false, then FrozenError", "false, luego FrozenError", "false の後 FrozenError"), L("true, then FrozenError", "true, luego FrozenError", "true の後 FrozenError"), L("false, then abcd", "false, luego abcd", "false の後 abcd")], answer: 0, check: { compiles: true, throws: "FrozenError" }, explain: L("+ builds a new, unfrozen string. << mutates s, which is ice.", "+ crea un string nuevo sin congelar. << muta s, que es hielo.", "+ は凍っていない新しい文字列を作る。<< は凍った s を変えようとする。") },
    { kind: "predict", time: 15, prompt: PRINT, code: C("Pos = Data.define(:x, :y)", "a = Pos.new(x: 1, y: 2)", "b = a.with(y: 5)", "p a.y, b.y, a == Pos.new(x: 1, y: 2)"), options: ["2\n5\ntrue", "5\n5\ntrue", "2\n5\nfalse"], answer: 0, output: "2\n5\ntrue", check: { compiles: true, stdout: "2\n5\ntrue" }, explain: L("with returns a new Data; a is untouched. Data objects with equal fields are ==.", "with devuelve un Data nuevo; a no cambia. Los Data con campos iguales son ==.", "with は新しい Data を返し a はそのまま。フィールドが同じ Data は ==。") },
    { kind: "predict", time: 15, prompt: PRINT, code: C('team = [["Rubi"], ["Kira"]]', "twin = team.clone", 'twin[1] << "!"', "p team[1]"), options: ['["Kira", "!"]', '["Kira"]'], answer: 0, output: '["Kira", "!"]', check: { compiles: true, stdout: '["Kira", "!"]' }, explain: L("clone is shallow like dup: the inner arrays are shared.", "clone es superficial como dup: los arrays internos se comparten.", "clone も dup と同じく浅い。中の配列は共有。") },
    { kind: "pick", time: 12, prompt: L("Wrap Shop's buy from the front", "Envuelve buy de Shop por delante", "Shop の buy を前から包もう"), code: C("module Log", '  def buy; "log+" + super; end', "end", "class Shop", '  def buy; "sold"; end', "end", "Shop.___ Log", "p Shop.new.buy"), options: ["prepend", "include", "extend"], answer: 0, check: { compiles: true, stdout: '"log+sold"' }, explain: L("prepend puts Log before Shop, so Log#buy runs first and super reaches Shop.", "prepend pone Log antes de Shop: Log#buy corre primero y super llega a Shop.", "prepend で Log が Shop の前に。Log#buy が先に動き super で Shop へ。") },
    {
      kind: "run",
      time: 90,
      prompt: L("Fix each so the party can map: [\"RUBI\", \"KIRA\"]", "Arregla each para que map funcione: [\"RUBI\", \"KIRA\"]", "each を直して map を動かそう"),
      starter: C("class Party", "  include Enumerable", "  def initialize(*names)", "    @names = names", "  end", "  def each(&block)", "    @names.each", "  end", "end", 'p Party.new("Rubi", "Kira").map(&:upcase)', ""),
      solution: C("class Party", "  include Enumerable", "  def initialize(*names)", "    @names = names", "  end", "  def each(&block)", "    @names.each(&block)", "  end", "end", 'p Party.new("Rubi", "Kira").map(&:upcase)', ""),
      expect: '["RUBI", "KIRA"]',
      fallback: [String.raw`@names\.each\s*\(\s*&block\s*\)`, String.raw`@names\.each\s*\{\s*\|(\w+)\|\s*(block\.call|yield)\s*\(?\s*\1`, String.raw`@names\.each\s+do\s*\|(\w+)\|\s*(block\.call|yield)\s*\(?\s*\1`],
      explain: L("Enumerable calls each with a block. Pass it on: @names.each(&block).", "Enumerable llama a each con un bloque. Pásalo: @names.each(&block).", "Enumerable は each にブロックを渡す。@names.each(&block) で受け渡そう。"),
    },
    enemySays(L(
      "Melting... You saw through every copy and every crest. Climb on: the Meta Tower awaits.",
      "Me derrito... Viste a través de cada copia y cada blasón. Sigue subiendo: te espera la Torre Meta.",
      "とける…すべてのコピーと紋章を見抜いたか。登るがいい、メタの塔が待っている。",
    )),
  ],
};

export const moduleCastle: RegionDef = {
  slug: "module-castle",
  name: L("Module Castle", "Castillo de Módulos", "モジュール城"),
  subtitle: L("Classes · mixins · identity", "Clases · mixins · identidad", "クラス・mixin・同一性"),
  theme: "castle",
  lessons: [classes, mixins, classState, equality, boss],
};
