import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 2 · COLLECTION FOREST  (list/tuple/dict/set, shared references and copies, comprehensions, sorting)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");

// ─── 2.1 The scroll and the stone tablet ───────────────────────────────────
const lists: LessonDef = {
  slug: "lists-and-tuples",
  title: L("Scrolls and tablets", "Pergaminos y tablillas", "巻物と石板"),
  concept: "collections",
  mode: "lesson",
  xp: 65,
  enemy: "slime",
  enemyName: L("SCROLL SLIME", "LIMO PERGAMINO", "巻物スライム"),
  beats: [
    say(L(
      "Welcome to Collection Forest! A LIST is a scroll of items in order: [\"sword\", \"potion\"]. You can add and remove lines.",
      "¡Bienvenido al Bosque de Colecciones! Una LISTA es un pergamino de cosas en orden: [\"sword\", \"potion\"]. Puedes agregar y quitar.",
      "コレクションの森へようこそ！リストは順番つきの巻物：[\"sword\", \"potion\"]。行の追加も削除もできるよ。",
    )),
    {
      kind: "act",
      prompt: L("Write on the scroll, then try the tablet", "Escribe en el pergamino y luego prueba la tablilla", "巻物に書いて、次は石板をためそう"),
      steps: [
        { label: L("SCROLL bag", "PERGAMINO bag", "巻物 bag"), line: 'bag = ["sword", "potion"]', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "bag", value: "2 items" }] },
        { label: L("APPEND gem", "AGREGAR gem", "gem を追加"), line: 'bag.append("gem")', effects: [{ t: "value", actor: "hero", text: "3 items" }, { t: "say", actor: "hero", text: L("One more line!", "¡Una línea más!", "1行ふえた！") }] },
        { label: L("LAST ITEM", "ÚLTIMO", "最後の品"), line: "print(bag[-1])", effects: [{ t: "print", text: "gem" }], output: "gem" },
        { label: L("TABLET t", "TABLILLA t", "石板 t"), line: "t = (1, 2, 3)", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "t", value: "(1, 2, 3)" }] },
        {
          label: L("CARVE t[0]", "TALLAR t[0]", "t[0] を彫る"),
          line: "t[0] = 9",
          effects: [{ t: "shake" }, { t: "banner", text: L("TypeError", "TypeError", "TypeError") }],
          error: {
            compiler: "TypeError: 'tuple' object does not support item assignment",
            plain: L("A tuple is a stone tablet: fixed once made. You can read it, never change it.", "Una tupla es una tablilla de piedra: fija una vez creada. Se lee, nunca se cambia.", "タプルは石板。一度作ったら固定で、読めるけど変えられないよ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'bag = ["sword", "potion"]\nbag.append("gem")\nprint(len(bag), bag[-1])',
      options: ["3 gem", "2 potion", "3 sword"],
      answer: 0,
      output: "3 gem",
      check: { compiles: true, stdout: "3 gem" },
      explain: L("append adds to the end, so there are 3 items and the last one, bag[-1], is gem.", "append agrega al final: hay 3 cosas y la última, bag[-1], es gem.", "append は末尾に追加。3個になり、最後の bag[-1] は gem だよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "bag", value: "2 items" }],
      win: [{ t: "value", actor: "hero", text: "3 items" }, { t: "print", text: "3 gem" }],
    },
    say(L(
      "Lists slice just like strings: nums[1:3], nums[:2], nums[::2]. A slice past the end never crashes.",
      "Las listas se cortan igual que los strings: nums[1:3], nums[:2], nums[::2]. Un corte fuera del final nunca falla.",
      "リストも文字列と同じく切り出せる：nums[1:3]、nums[:2]、nums[::2]。範囲外のスライスはエラーにならないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "nums = [10, 20, 30, 40, 50]\nprint(nums[1:3], nums[:2], nums[::2])",
      options: ["[20, 30] [10, 20] [10, 30, 50]", "[20, 30, 40] [10, 20] [20, 40]", "[10, 20, 30] [10, 20] [10, 30, 50]"],
      answer: 0,
      output: "[20, 30] [10, 20] [10, 30, 50]",
      check: { compiles: true, stdout: "[20, 30] [10, 20] [10, 30, 50]" },
      explain: L("[1:3] takes indexes 1 and 2. [:2] takes the first two. [::2] takes every second item.", "[1:3] toma los índices 1 y 2. [:2] toma los dos primeros. [::2] toma uno de cada dos.", "[1:3] はインデックス 1 と 2。[:2] は最初の2つ。[::2] は1つおきだよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "nums = [1, 2, 3]\nprint(nums.pop(), nums, nums[5:])",
      options: ["3 [1, 2] []", "1 [2, 3] []", "3 [1, 2] IndexError"],
      answer: 0,
      output: "3 [1, 2] []",
      check: { compiles: true, stdout: "3 [1, 2] []" },
      explain: L("pop() removes and returns the last item. nums[5:] is past the end: just an empty list.", "pop() quita y devuelve el último. nums[5:] está fuera del final: solo una lista vacía.", "pop() は最後の要素を取り出して返す。nums[5:] は範囲外なので空リストになるよ。"),
    },
    say(L(
      "for item in bag: runs the indented block once per item, in order. Lists and tuples both work.",
      "for item in bag: ejecuta el bloque indentado una vez por cosa, en orden. Sirve con listas y tuplas.",
      "for item in bag: は要素ごとに1回ずつ、字下げしたブロックを順に実行する。リストでもタプルでも OK。",
    )),
    {
      kind: "order",
      prompt: L("Print each item of the bag", "Imprime cada cosa de la bolsa", "bag の中身を1つずつ表示しよう"),
      lines: ['bag = ["sword", "gem"]', "for item in bag:", "    print(item)"],
      check: { compiles: true, stdout: "sword\ngem" },
      explain: L("Make the list first, then loop over it. The print is indented, so it runs for every item.", "Primero crea la lista y luego recórrela. El print está indentado, así que corre por cada cosa.", "先にリストを作ってからループ。print は字下げされているので要素ごとに動くよ。"),
      win: [{ t: "print", text: "sword" }, { t: "print", text: "gem" }],
    },
    say(L(
      "A TUPLE uses ( ) and can't change. Careful: the COMMA makes the tuple. (5) is just 5, (5,) is a tuple.",
      "Una TUPLA usa ( ) y no puede cambiar. Ojo: la COMA hace la tupla. (5) es solo 5, (5,) es una tupla.",
      "タプルは ( ) で作り、変更できない。注意：タプルを作るのはカンマ。(5) はただの 5、(5,) がタプル。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "t = (1, 2, 3)\nt[0] = 9\nprint(t)",
      options: ["TypeError", "(9, 2, 3)", "(1, 2, 3)"],
      answer: 0,
      check: { compiles: true, throws: "TypeError" },
      explain: L("Tuples are immutable: assigning to t[0] raises TypeError.", "Las tuplas son inmutables: asignar a t[0] lanza TypeError.", "タプルは変更不可。t[0] に代入すると TypeError になるよ。"),
      win: [{ t: "shake" }, { t: "banner", text: L("TypeError", "TypeError", "TypeError") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "t = (5)\nu = (5,)\nprint(type(t).__name__, type(u).__name__)",
      options: ["int tuple", "tuple tuple", "int int"],
      answer: 0,
      output: "int tuple",
      check: { compiles: true, stdout: "int tuple" },
      explain: L("Parentheses alone just group: (5) is 5. The trailing comma is what makes (5,) a tuple.", "Los paréntesis solos solo agrupan: (5) es 5. La coma final es lo que hace de (5,) una tupla.", "かっこだけではまとめるだけで (5) は 5。末尾のカンマで (5,) がタプルになるよ。"),
    },
    {
      kind: "type",
      prompt: L("Catch the rest in a list", "Atrapa el resto en una lista", "残りをリストで受けとろう"),
      code: "a, ___rest = [1, 2, 3, 4]\nprint(a, rest)",
      answer: "*",
      check: { compiles: true, stdout: "1 [2, 3, 4]" },
      explain: L("A star name collects every leftover item into a list: rest is [2, 3, 4].", "Un nombre con estrella junta todo lo que sobra en una lista: rest es [2, 3, 4].", "* をつけた名前は残りを全部リストで受けとる。rest は [2, 3, 4]。"),
      win: [{ t: "print", text: "1 [2, 3, 4]" }],
    },
    say(L(
      "x.sort() reorders the list itself and returns None. sorted(x) hands back a NEW sorted list.",
      "x.sort() reordena la lista misma y devuelve None. sorted(x) te da una lista NUEVA ordenada.",
      "x.sort() はリスト自体を並べかえて None を返す。sorted(x) は並べた「新しい」リストを返すよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "x = [3, 1, 2]\ny = x.sort()\nprint(y, x)",
      options: ["None [1, 2, 3]", "[1, 2, 3] [1, 2, 3]", "[1, 2, 3] [3, 1, 2]"],
      answer: 0,
      output: "None [1, 2, 3]",
      check: { compiles: true, stdout: "None [1, 2, 3]" },
      explain: L("sort() works in place: x changes, and the method itself returns None.", "sort() trabaja en el lugar: x cambia, y el método devuelve None.", "sort() はその場で並べかえる。x が変わり、メソッド自体は None を返すよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "x", value: "[3, 1, 2]" }],
      win: [{ t: "value", actor: "hero", text: "[1, 2, 3]" }, { t: "print", text: "None [1, 2, 3]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "x = [3, 1, 2]\nprint(sorted(x), x)",
      options: ["[1, 2, 3] [3, 1, 2]", "[1, 2, 3] [1, 2, 3]", "None [1, 2, 3]"],
      answer: 0,
      output: "[1, 2, 3] [3, 1, 2]",
      check: { compiles: true, stdout: "[1, 2, 3] [3, 1, 2]" },
      explain: L("sorted() makes a new list and leaves x untouched.", "sorted() crea una lista nueva y deja x intacta.", "sorted() は新しいリストを作り、x はそのまま。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "x", value: "[3, 1, 2]" }],
      win: [{ t: "clone", to: "ally" }, { t: "print", text: "[1, 2, 3] [3, 1, 2]" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print last: gem", "Arréglalo: debe imprimir last: gem", "直そう：last: gem と表示させて"),
      starter: 'bag = ["sword", "potion", "gem"]\nlast = bag[3]\nprint("last:", last)\n',
      solution: 'bag = ["sword", "potion", "gem"]\nlast = bag[-1]\nprint("last:", last)\n',
      expect: "last: gem",
      fallback: [String.raw`bag\[\s*-1\s*\]`, String.raw`bag\[\s*2\s*\]`, String.raw`bag\[\s*len\(\s*bag\s*\)\s*-\s*1\s*\]`],
      explain: L("3 items have indexes 0, 1, 2, so bag[3] is IndexError. bag[-1] always means the last.", "3 cosas tienen índices 0, 1 y 2, así que bag[3] da IndexError. bag[-1] siempre es el último.", "3個ならインデックスは 0, 1, 2。bag[3] は IndexError。bag[-1] はいつも最後だよ。"),
    },
  ],
};

// ─── 2.2 Gem pouches and shields ───────────────────────────────────────────
const dicts: LessonDef = {
  slug: "dicts-and-sets",
  title: L("Pouches and shields", "Bolsas y escudos", "ポーチと盾"),
  concept: "collections",
  mode: "lesson",
  xp: 70,
  enemy: "python/keyerror-key",
  enemyName: L("KEYERROR KEY", "LLAVE KEYERROR", "KeyError キー"),
  beats: [
    say(L(
      "A DICT maps keys to values, like a pouch with labeled pockets: {\"name\": \"Ada\", \"hp\": 10}.",
      "Un DICT asocia claves con valores, como una bolsa con bolsillos rotulados: {\"name\": \"Ada\", \"hp\": 10}.",
      "辞書（dict）はキーと値の組。名前つきポケットのあるポーチだよ：{\"name\": \"Ada\", \"hp\": 10}。",
    )),
    {
      kind: "act",
      prompt: L("Open the pockets of the pouch", "Abre los bolsillos de la bolsa", "ポーチのポケットを開けよう"),
      steps: [
        { label: L("POUCH hero", "BOLSA hero", "ポーチ hero"), line: 'hero = {"name": "Ada", "hp": 10}', effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "hero", value: "hp 10" }] },
        { label: L("HEAL hp", "CURAR hp", "hp 回復"), line: 'hero["hp"] += 5', effects: [{ t: "value", actor: "hero", text: "hp 15" }] },
        { label: L("READ hp", "LEER hp", "hp を読む"), line: 'print(hero["hp"])', effects: [{ t: "print", text: "15" }], output: "15" },
        {
          label: L("READ mp", "LEER mp", "mp を読む"),
          line: 'print(hero["mp"])',
          effects: [{ t: "shake" }, { t: "banner", text: L("KeyError", "KeyError", "KeyError") }],
          error: {
            compiler: "KeyError: 'mp'",
            plain: L("There is no pocket called mp. Square brackets on a missing key raise KeyError.", "No hay ningún bolsillo llamado mp. Los corchetes con una clave que falta lanzan KeyError.", "mp というポケットはない。ないキーを [ ] で読むと KeyError だよ。"),
          },
        },
        { label: L("GET mp", "GET mp", "get で mp"), line: 'print(hero.get("mp", 0))', effects: [{ t: "enter", actor: "ally" }, { t: "say", actor: "ally", text: L("Default: 0!", "¡Por defecto: 0!", "代わりに 0！") }, { t: "print", text: "0" }], output: "0" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'hero = {"name": "Ada", "hp": 10}\nhero["hp"] += 5\nprint(hero["hp"], len(hero))',
      options: ["15 2", "15 3", "10 2"],
      answer: 0,
      output: "15 2",
      check: { compiles: true, stdout: "15 2" },
      explain: L("hp becomes 15. len counts keys: name and hp, so 2.", "hp pasa a 15. len cuenta las claves: name y hp, así que 2.", "hp は 15 に。len はキーの数で、name と hp の 2 だよ。"),
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "hero", value: "hp 10" }],
      win: [{ t: "value", actor: "hero", text: "hp 15" }, { t: "print", text: "15 2" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'hero = {"name": "Ada"}\nprint(hero["mp"])',
      options: ["KeyError", "None", "0"],
      answer: 0,
      check: { compiles: true, throws: "KeyError" },
      explain: L("d[key] demands the key exists. mp is missing, so it raises KeyError: 'mp'.", "d[clave] exige que la clave exista. Falta mp, así que lanza KeyError: 'mp'.", "d[キー] はキーが必須。mp がないので KeyError: 'mp' になるよ。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("No such pocket!", "¡No hay bolsillo!", "そんなポケットない！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'hero = {"name": "Ada"}\nprint(hero.get("mp"), hero.get("mp", 0))',
      options: ["None 0", "KeyError", "0 0"],
      answer: 0,
      output: "None 0",
      check: { compiles: true, stdout: "None 0" },
      explain: L("get never raises: it returns None, or the default you pass, when the key is missing.", "get nunca lanza error: devuelve None, o el valor por defecto que pases, si falta la clave.", "get はエラーにならない。キーがなければ None か、渡したデフォルト値を返すよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'd = {"b": 1, "a": 2}\nd["c"] = 3\nprint(list(d))',
      options: ["['b', 'a', 'c']", "['a', 'b', 'c']", "[1, 2, 3]"],
      answer: 0,
      output: "['b', 'a', 'c']",
      check: { compiles: true, stdout: "['b', 'a', 'c']" },
      explain: L("Dicts remember insertion order. list(d) gives the keys in the order they were added.", "Los dicts recuerdan el orden de inserción. list(d) da las claves en el orden en que se agregaron.", "dict は追加した順番を覚えている。list(d) はキーを追加順に返すよ。"),
    },
    {
      kind: "order",
      prompt: L("Heal, then print every pocket", "Cura y luego imprime cada bolsillo", "回復してから全ポケットを表示"),
      lines: ['hero = {"hp": 10}', 'hero["hp"] += 5', "for k, v in hero.items():", "    print(k, v)"],
      check: { compiles: true, stdout: "hp 15" },
      explain: L(".items() gives (key, value) pairs, and for k, v unpacks each pair.", ".items() da pares (clave, valor), y for k, v desempaca cada par.", ".items() は (キー, 値) の組を返し、for k, v で1組ずつ分けて受けとるよ。"),
      win: [{ t: "print", text: "hp 15" }],
    },
    say(L(
      "A SET keeps each value once: duplicates bounce off. Its order is not guaranteed, so sort it before printing.",
      "Un SET guarda cada valor una sola vez: los repetidos rebotan. Su orden no está garantizado, ordénalo antes de imprimir.",
      "集合（set）は同じ値を1つだけ持つ。重複ははじかれる。順番は保証されないから、表示前に並べよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "s = {3, 1, 2, 3, 1}\nprint(len(s), sorted(s))",
      options: ["3 [1, 2, 3]", "5 [1, 1, 2, 3, 3]", "3 [3, 1, 2]"],
      answer: 0,
      output: "3 [1, 2, 3]",
      check: { compiles: true, stdout: "3 [1, 2, 3]" },
      explain: L("The set drops the repeated 3 and 1, leaving 3 values. sorted() gives a list in order.", "El set descarta el 3 y el 1 repetidos y quedan 3 valores. sorted() da una lista ordenada.", "set は重複した 3 と 1 を捨てて3個に。sorted() で順番どおりのリストにするよ。"),
      setup: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "s" }],
      win: [{ t: "drop" }, { t: "value", actor: "hero", text: "3 values" }, { t: "print", text: "3 [1, 2, 3]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(sorted(a & b), sorted(a | b), sorted(a - b))",
      options: ["[2, 3] [1, 2, 3, 4] [1]", "[1, 2, 3, 4] [2, 3] [4]", "[2, 3] [1, 2, 3, 2, 3, 4] [1]"],
      answer: 0,
      output: "[2, 3] [1, 2, 3, 4] [1]",
      check: { compiles: true, stdout: "[2, 3] [1, 2, 3, 4] [1]" },
      explain: L("& keeps what's in both, | joins everything once, - keeps what's in a but not in b.", "& deja lo que está en ambos, | une todo una vez, - deja lo que está en a pero no en b.", "& は両方にあるもの、| は全部を1つずつ、- は a にあって b にないものだよ。"),
    },
    {
      kind: "pick",
      prompt: L("Make an EMPTY set", "Crea un set VACÍO", "空の set を作ろう"),
      code: "e = ___\nprint(type(e).__name__)",
      options: ["set()", "{}"],
      answer: 0,
      check: { compiles: true, stdout: "set" },
      explain: L("{} is an empty dict, not a set. An empty set must be written set().", "{} es un dict vacío, no un set. Un set vacío se escribe set().", "{} は空の dict で set じゃない。空の set は set() と書くよ。"),
    },
    say(L(
      "Dict keys must be HASHABLE, meaning they can't change: numbers, strings and tuples work. Lists don't.",
      "Las claves de un dict deben ser HASHABLES, es decir, que no cambien: números, strings y tuplas sirven. Listas no.",
      "dict のキーは「ハッシュ可能」、つまり変わらないものだけ。数値、文字列、タプルは OK、リストはダメ。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'd = {[1, 2]: "x"}\nprint(d)',
      options: ["TypeError", "{[1, 2]: 'x'}", "KeyError"],
      answer: 0,
      check: { compiles: true, throws: "TypeError" },
      explain: L("A list can change, so it can't be a key: TypeError (unhashable type: 'list').", "Una lista puede cambiar, así que no puede ser clave: TypeError (unhashable type: 'list').", "リストは変わりうるのでキーにできない。TypeError（unhashable type: 'list'）だよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'd = {(1, 2): "x"}\nprint(d[(1, 2)])',
      options: ["x", "TypeError", "(1, 2)"],
      answer: 0,
      output: "x",
      check: { compiles: true, stdout: "x" },
      explain: L("A tuple of numbers can't change, so it's a fine key, like a grid position.", "Una tupla de números no puede cambiar, así que es una buena clave, como una posición en un mapa.", "数値のタプルは変わらないのでキーにできる。マスの座標みたいにね。"),
    },
    {
      kind: "run",
      prompt: L("Count the loot: it must print {'gem': 2, 'key': 1}", "Cuenta el botín: debe imprimir {'gem': 2, 'key': 1}", "戦利品を数えて：{'gem': 2, 'key': 1}"),
      starter: 'counts = {}\nfor w in ["gem", "key", "gem"]:\n    counts[w] += 1\nprint(counts)\n',
      solution: 'counts = {}\nfor w in ["gem", "key", "gem"]:\n    counts[w] = counts.get(w, 0) + 1\nprint(counts)\n',
      expect: "{'gem': 2, 'key': 1}",
      fallback: [String.raw`counts\[\s*w\s*\]\s*=\s*counts\.get\(\s*w\s*,\s*0\s*\)\s*\+\s*1`, String.raw`if\s+w\s+(?:not\s+)?in\s+counts`, String.raw`counts\.setdefault\(\s*w\s*,\s*0\s*\)`],
      explain: L("counts[w] += 1 reads a missing key first: KeyError. get(w, 0) starts each count at 0.", "counts[w] += 1 lee primero una clave que falta: KeyError. get(w, 0) empieza cada cuenta en 0.", "counts[w] += 1 はないキーを先に読むので KeyError。get(w, 0) なら 0 から数えられるよ。"),
    },
  ],
};

// ─── 2.3 Shared treasure ───────────────────────────────────────────────────
const shared: LessonDef = {
  slug: "shared-references",
  title: L("Shared treasure", "Tesoro compartido", "共有された宝"),
  concept: "references",
  mode: "lesson",
  xp: 75,
  enemy: "python/mutable-mimic",
  enemyName: L("MUTABLE MIMIC", "MÍMICO MUTABLE", "ミュータブルミミック"),
  beats: [
    say(L(
      "Big secret: assignment NEVER copies. b = a sticks a second label on the SAME list. Change it through b, a sees it too.",
      "Gran secreto: la asignación NUNCA copia. b = a pega otra etiqueta en la MISMA lista. Si la cambias por b, a también lo ve.",
      "大事な秘密：代入はコピーしない。b = a は「同じ」リストに2枚目のラベル。b から変えると a にも見えるよ。",
    )),
    {
      kind: "act",
      prompt: L("Share the scroll and watch both heroes", "Comparte el pergamino y mira a ambos", "巻物を共有して、2人を見てね"),
      steps: [
        { label: L("SCROLL a", "PERGAMINO a", "巻物 a"), line: "a = [1, 2]", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "[1, 2]" }] },
        { label: L("b = a", "b = a", "b = a"), line: "b = a", effects: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }, { t: "tag", actor: "ally", text: "b", value: "[1, 2]" }, { t: "say", actor: "ally", text: L("Same scroll!", "¡El mismo!", "同じ巻物！") }] },
        { label: L("b.append(3)", "b.append(3)", "b.append(3)"), line: "b.append(3)", effects: [{ t: "value", actor: "ally", text: "[1, 2, 3]" }, { t: "value", actor: "hero", text: "[1, 2, 3]" }, { t: "say", actor: "hero", text: L("Mine grew too?!", "¿¡El mío creció!?", "私のも増えた？！") }] },
        { label: L("PRINT a", "IMPRIMIR a", "a を表示"), line: "print(a)", effects: [{ t: "print", text: "[1, 2, 3]" }], output: "[1, 2, 3]" },
        { label: L("COPY a[:]", "COPIAR a[:]", "a[:] でコピー"), line: "c = a[:]", effects: [{ t: "clone", to: "ally" }, { t: "banner", text: L("SHALLOW COPY", "COPIA SUPERFICIAL", "浅いコピー") }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = [1, 2]\nb = a\nb.append(3)\nprint(a)",
      options: ["[1, 2, 3]", "[1, 2]", "[3]"],
      answer: 0,
      output: "[1, 2, 3]",
      check: { compiles: true, stdout: "[1, 2, 3]" },
      explain: L("a and b are two labels on one list. append through b changes the list a points to.", "a y b son dos etiquetas en una sola lista. append por b cambia la lista a la que apunta a.", "a と b は1つのリストに貼った2枚のラベル。b から append すると a のリストも変わるよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "[1, 2]" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }],
      win: [{ t: "lend", to: "ally" }, { t: "value", actor: "hero", text: "[1, 2, 3]" }, { t: "print", text: "[1, 2, 3]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = [1, 2]\nb = a[:]\nb.append(3)\nprint(a, b)",
      options: ["[1, 2] [1, 2, 3]", "[1, 2, 3] [1, 2, 3]", "[1, 2] [1, 2]"],
      answer: 0,
      output: "[1, 2] [1, 2, 3]",
      check: { compiles: true, stdout: "[1, 2] [1, 2, 3]" },
      explain: L("a[:] slices the whole list into a NEW one. b gets its own scroll, so a stays [1, 2].", "a[:] corta la lista entera en una NUEVA. b recibe su propio pergamino, así que a sigue en [1, 2].", "a[:] はリスト全体を切り出して「新しい」リストにする。b は別の巻物なので a は [1, 2] のまま。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "[1, 2]" }, { t: "enter", actor: "ally" }],
      win: [{ t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "b", value: "[1, 2, 3]" }, { t: "print", text: "[1, 2] [1, 2, 3]" }],
    },
    say(L(
      "def makes a function (more in the peaks!). It gets the SAME object you pass: changing it shows outside, re-labeling doesn't.",
      "def crea una función (¡más en las cumbres!). Recibe el MISMO objeto que pasas: cambiarlo se ve afuera, re-etiquetar no.",
      "def は関数を作る（くわしくは山で！）。渡したのと同じ物を受けとる。中身の変更は外に見え、貼りかえは見えないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'def add(item, bag):\n    bag.append(item)\n\ninv = []\nadd("gem", inv)\nprint(inv)',
      options: ["['gem']", "[]", "None"],
      answer: 0,
      output: "['gem']",
      check: { compiles: true, stdout: "['gem']" },
      explain: L("bag is a label on the caller's list, so append changes inv itself.", "bag es una etiqueta en la lista de quien llama, así que append cambia inv misma.", "bag は呼び出し側のリストに貼ったラベル。append で inv そのものが変わるよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'def reset(bag):\n    bag = []\n\ninv = ["gem"]\nreset(inv)\nprint(inv)',
      options: ["['gem']", "[]", "None"],
      answer: 0,
      output: "['gem']",
      check: { compiles: true, stdout: "['gem']" },
      explain: L("bag = [] only moves the local label bag to a new list. inv still points to the old one.", "bag = [] solo mueve la etiqueta local bag a una lista nueva. inv sigue apuntando a la anterior.", "bag = [] は関数内のラベル bag を新しいリストに貼りかえるだけ。inv は元のリストのまま。"),
    },
    say(L(
      "Immutable values (int, str, tuple) can't change, so += makes a NEW one. On a list, += changes it in place.",
      "Los valores inmutables (int, str, tuple) no cambian, así que += crea uno NUEVO. En una lista, += la cambia en su lugar.",
      "変更不可の値（int、str、tuple）では += は「新しい」値を作る。リストの += はその場で変更するよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 's = "hp"\nt = s\ns += "!"\nprint(s, t)',
      options: ["hp! hp", "hp! hp!", "hp hp"],
      answer: 0,
      output: "hp! hp",
      check: { compiles: true, stdout: "hp! hp" },
      explain: L("Strings can't change: s += \"!\" builds a new string and moves s. t keeps the old \"hp\".", "Los strings no cambian: s += \"!\" crea un string nuevo y mueve s. t conserva el viejo \"hp\".", "文字列は変えられない。s += \"!\" は新しい文字列を作って s を移す。t は元の \"hp\" のまま。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = [1, 2]\nb = a\na += [3]\nprint(b)",
      options: ["[1, 2, 3]", "[1, 2]", "[3]"],
      answer: 0,
      output: "[1, 2, 3]",
      check: { compiles: true, stdout: "[1, 2, 3]" },
      explain: L("On a list, += extends the same list in place, and b is a label on that list.", "En una lista, += extiende la misma lista en su lugar, y b es una etiqueta en esa lista.", "リストの += は同じリストをその場でのばす。b もそのリストのラベルだよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = [1, 2]\nb = a\na = a + [3]\nprint(b)",
      options: ["[1, 2]", "[1, 2, 3]", "[3]"],
      answer: 0,
      output: "[1, 2]",
      check: { compiles: true, stdout: "[1, 2]" },
      explain: L("a + [3] builds a NEW list and moves the label a onto it. b stays on the old list.", "a + [3] crea una lista NUEVA y mueve la etiqueta a hacia ella. b se queda en la vieja.", "a + [3] は新しいリストを作り、ラベル a をそちらへ移す。b は元のリストのまま。"),
    },
    say(L(
      "A shallow copy (a[:], copy.copy) copies only the outer list: inner lists are still shared. copy.deepcopy copies all.",
      "Una copia superficial (a[:], copy.copy) copia solo la lista de afuera: las internas siguen compartidas. copy.deepcopy copia todo.",
      "浅いコピー（a[:]、copy.copy）は外側だけ複製し、中のリストは共有のまま。copy.deepcopy は全部複製するよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "grid = [[0] * 2] * 2\ngrid[0][0] = 9\nprint(grid)",
      options: ["[[9, 0], [9, 0]]", "[[9, 0], [0, 0]]", "[[9, 9], [0, 0]]"],
      answer: 0,
      output: "[[9, 0], [9, 0]]",
      check: { compiles: true, stdout: "[[9, 0], [9, 0]]" },
      explain: L("* 2 on the outer list repeats the SAME inner list twice. Both rows are one object.", "* 2 en la lista de afuera repite la MISMA lista interna dos veces. Ambas filas son un solo objeto.", "外側の * 2 は「同じ」内側リストを2回並べる。2行とも同じ1つの物だよ。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Twin rows! Heh!", "¡Filas gemelas!", "双子の行！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "import copy\na = [[1], [2]]\ns = copy.copy(a)\nd = copy.deepcopy(a)\na[0].append(9)\nprint(s, d)",
      options: ["[[1, 9], [2]] [[1], [2]]", "[[1], [2]] [[1], [2]]", "[[1, 9], [2]] [[1, 9], [2]]"],
      answer: 0,
      output: "[[1, 9], [2]] [[1], [2]]",
      check: { compiles: true, stdout: "[[1, 9], [2]] [[1], [2]]" },
      explain: L("The shallow copy s shares the inner [1] with a, so it sees the 9. The deep copy d does not.", "La copia superficial s comparte el [1] interno con a, así que ve el 9. La copia profunda d no.", "浅いコピー s は中の [1] を a と共有しているので 9 が見える。深いコピー d には見えないよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }, { t: "enter", actor: "ally" }],
      win: [{ t: "clone", to: "ally" }, { t: "banner", text: L("DEEP COPY", "COPIA PROFUNDA", "深いコピー") }],
    },
    {
      kind: "predict",
      prompt: L("A tablet holding a scroll. What does it print?", "Una tablilla con un pergamino. ¿Qué imprime?", "巻物入りの石板。何が表示される？"),
      code: "t = ([1], 2)\nt[0].append(3)\nprint(t)",
      options: ["([1, 3], 2)", "TypeError", "([1], 2)"],
      answer: 0,
      output: "([1, 3], 2)",
      check: { compiles: true, stdout: "([1, 3], 2)" },
      explain: L("The tuple can't swap its items, but the list inside it is still mutable.", "La tupla no puede cambiar sus elementos, pero la lista que tiene dentro sigue siendo mutable.", "タプルは要素を入れかえられないけど、中のリスト自体は変更できるよ。"),
    },
    {
      kind: "run",
      prompt: L("Make a real backup: backup: [['sword'], ['bow']]", "Haz un respaldo real: backup: [['sword'], ['bow']]", "本物のバックアップを：backup: [['sword'], ['bow']]"),
      starter: 'import copy\nteam = [["sword"], ["bow"]]\nbackup = copy.copy(team)\nteam[0].append("shield")\nprint("backup:", backup)\n',
      solution: 'import copy\nteam = [["sword"], ["bow"]]\nbackup = copy.deepcopy(team)\nteam[0].append("shield")\nprint("backup:", backup)\n',
      expect: "backup: [['sword'], ['bow']]",
      fallback: [String.raw`copy\.deepcopy\(\s*team\s*\)`, String.raw`\[\s*(?:list\(\s*\w+\s*\)|\w+\[:\]|\w+\.copy\(\))\s+for\s+\w+\s+in\s+team\s*\]`],
      explain: L("copy.copy shares the inner lists, so the shield shows up in backup. deepcopy copies them too.", "copy.copy comparte las listas internas, así que el shield aparece en backup. deepcopy también las copia.", "copy.copy は中のリストを共有するので backup にも shield が入る。deepcopy なら中も複製するよ。"),
    },
  ],
};

// ─── 2.4 The sorting caravan ───────────────────────────────────────────────
const comprehensions: LessonDef = {
  slug: "comprehensions-and-sorting",
  title: L("The sorting caravan", "La caravana ordenada", "並べかえキャラバン"),
  concept: "comprehensions",
  mode: "lesson",
  xp: 80,
  enemy: "ghost",
  enemyName: L("CARAVAN GHOST", "FANTASMA CARAVANA", "キャラバンゴースト"),
  beats: [
    say(L(
      "range(5) counts 0, 1, 2, 3, 4. A COMPREHENSION builds a list in one line: [n * n for n in range(5)].",
      "range(5) cuenta 0, 1, 2, 3, 4. Una COMPRENSIÓN arma una lista en una línea: [n * n for n in range(5)].",
      "range(5) は 0, 1, 2, 3, 4 と数える。内包表記ならリストを1行で作れる：[n * n for n in range(5)]。",
    )),
    {
      kind: "act",
      prompt: L("Send the caravan through the gate", "Haz pasar la caravana por la puerta", "キャラバンを門に通そう"),
      steps: [
        { label: L("COUNT", "CONTAR", "数える"), line: "print(list(range(5)))", effects: [{ t: "print", text: "[0, 1, 2, 3, 4]" }], output: "[0, 1, 2, 3, 4]" },
        { label: L("SQUARE EACH", "AL CUADRADO", "それぞれ2乗"), line: "print([n * n for n in range(5)])", effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "print", text: "[0, 1, 4, 9, 16]" }], output: "[0, 1, 4, 9, 16]" },
        { label: L("FILTER", "FILTRAR", "ふるい分け"), line: "print([n for n in range(10) if n % 3 == 0])", effects: [{ t: "drop" }, { t: "say", actor: "ally", text: L("Only 3s pass!", "¡Solo pasan 3s!", "3の倍数だけ！") }, { t: "print", text: "[0, 3, 6, 9]" }], output: "[0, 3, 6, 9]" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print([n * n for n in range(5)])",
      options: ["[0, 1, 4, 9, 16]", "[1, 4, 9, 16, 25]", "[0, 2, 4, 6, 8]"],
      answer: 0,
      output: "[0, 1, 4, 9, 16]",
      check: { compiles: true, stdout: "[0, 1, 4, 9, 16]" },
      explain: L("range(5) gives 0 to 4, and each n becomes n * n.", "range(5) da de 0 a 4, y cada n se vuelve n * n.", "range(5) は 0 から 4。それぞれの n が n * n になるよ。"),
    },
    {
      kind: "type",
      prompt: L("Keep only multiples of 3", "Deja solo los múltiplos de 3", "3の倍数だけ残そう"),
      code: "print([n for n in range(10) ___ n % 3 == 0])",
      answer: "if",
      check: { compiles: true, stdout: "[0, 3, 6, 9]" },
      explain: L("An if at the end of a comprehension is a gate: only items that pass are kept.", "Un if al final de una comprensión es una puerta: solo se quedan las cosas que pasan.", "内包表記の最後の if は門。通ったものだけが残るよ。"),
      win: [{ t: "print", text: "[0, 3, 6, 9]" }],
    },
    {
      kind: "predict",
      prompt: L("Curly braces with key: value. What prints?", "Llaves con clave: valor. ¿Qué imprime?", "{ } に キー: 値。何が表示される？"),
      code: 'print({w: len(w) for w in ["gem", "sword"]})',
      options: ["{'gem': 3, 'sword': 5}", "[3, 5]", "{3, 5}"],
      answer: 0,
      output: "{'gem': 3, 'sword': 5}",
      check: { compiles: true, stdout: "{'gem': 3, 'sword': 5}" },
      explain: L("A dict comprehension: each word becomes a key, and its length the value.", "Una comprensión de dict: cada palabra es una clave y su largo el valor.", "辞書の内包表記。それぞれの単語がキー、その長さが値になるよ。"),
    },
    say(L(
      "With ( ) instead of [ ] you get a GENERATOR: it makes items one at a time, and only once. After that it's empty.",
      "Con ( ) en vez de [ ] obtienes un GENERADOR: produce las cosas de a una, y una sola vez. Después queda vacío.",
      "[ ] の代わりに ( ) だとジェネレータ。1個ずつ、1回だけ作る。使いきったら空っぽだよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "g = (n * 2 for n in range(3))\nprint(sum(g), sum(g))",
      options: ["6 0", "6 6", "0 0"],
      answer: 0,
      output: "6 0",
      check: { compiles: true, stdout: "6 0" },
      explain: L("The first sum uses up 0 + 2 + 4 = 6. The generator is then exhausted, so the second sum is 0.", "La primera suma consume 0 + 2 + 4 = 6. El generador queda agotado, así que la segunda suma es 0.", "1回目の sum で 0 + 2 + 4 = 6 を使いきる。もう空なので2回目は 0。"),
      win: [{ t: "say", actor: "enemy", text: L("Cart's empty!", "¡Carro vacío!", "荷車は空だ！") }],
    },
    say(L(
      "sorted() takes key= (what to sort by) and reverse=True. lambda h: h[1] is a tiny function: 'use item 1'.",
      "sorted() acepta key= (por qué ordenar) y reverse=True. lambda h: h[1] es una función mínima: 'usa el elemento 1'.",
      "sorted() には key=（何で並べるか）と reverse=True が使える。lambda h: h[1] は「要素1を使う」小さな関数。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'names = ["bob", "Cy", "al"]\nprint(sorted(names), sorted(names, key=str.lower))',
      options: ["['Cy', 'al', 'bob'] ['al', 'bob', 'Cy']", "['al', 'bob', 'Cy'] ['al', 'bob', 'Cy']", "['al', 'bob', 'Cy'] ['Cy', 'al', 'bob']"],
      answer: 0,
      output: "['Cy', 'al', 'bob'] ['al', 'bob', 'Cy']",
      check: { compiles: true, stdout: "['Cy', 'al', 'bob'] ['al', 'bob', 'Cy']" },
      explain: L("Uppercase letters sort before lowercase, so Cy is first. key=str.lower compares in lowercase.", "Las mayúsculas van antes que las minúsculas, así que Cy es primero. key=str.lower compara en minúsculas.", "大文字は小文字より前なので Cy が先頭。key=str.lower なら小文字にして比べるよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'heroes = [("ada", 3), ("bo", 5), ("cy", 3)]\nprint(sorted(heroes, key=lambda h: h[1], reverse=True))',
      options: ["[('bo', 5), ('ada', 3), ('cy', 3)]", "[('bo', 5), ('cy', 3), ('ada', 3)]", "[('ada', 3), ('cy', 3), ('bo', 5)]"],
      answer: 0,
      output: "[('bo', 5), ('ada', 3), ('cy', 3)]",
      check: { compiles: true, stdout: "[('bo', 5), ('ada', 3), ('cy', 3)]" },
      explain: L("Sorted by the number, highest first. Sorting is STABLE: ties keep their order, so ada stays before cy.", "Ordenado por el número, de mayor a menor. Ordenar es ESTABLE: los empates mantienen su orden, ada antes que cy.", "数値の大きい順。並べかえは「安定」で、同点は元の順を保つから ada が cy より前。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print(list(zip("ab", [1, 2, 3])), list(enumerate("xy", start=1)))',
      options: ["[('a', 1), ('b', 2)] [(1, 'x'), (2, 'y')]", "[('a', 1), ('b', 2), (None, 3)] [(0, 'x'), (1, 'y')]", "[('a', 1), ('b', 2)] [(0, 'x'), (1, 'y')]"],
      answer: 0,
      output: "[('a', 1), ('b', 2)] [(1, 'x'), (2, 'y')]",
      check: { compiles: true, stdout: "[('a', 1), ('b', 2)] [(1, 'x'), (2, 'y')]" },
      explain: L("zip pairs items and stops at the shortest. enumerate numbers each item, here from 1.", "zip empareja cosas y se detiene en la más corta. enumerate numera cada cosa, aquí desde 1.", "zip は組にして短い方で止まる。enumerate は番号をつける（ここでは 1 から）。"),
    },
    say(L(
      "The collections module has helpers: Counter counts things, defaultdict fills missing keys for you.",
      "El módulo collections tiene ayudantes: Counter cuenta cosas y defaultdict llena las claves que faltan.",
      "collections モジュールには便利な道具がある。Counter は数を数え、defaultdict はないキーを自動で作るよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'from collections import Counter\nc = Counter("banana")\nprint(c.most_common(2), c["z"])',
      options: ["[('a', 3), ('n', 2)] 0", "[('a', 3), ('n', 2)] KeyError", "[('b', 1), ('a', 3)] 0"],
      answer: 0,
      output: "[('a', 3), ('n', 2)] 0",
      check: { compiles: true, stdout: "[('a', 3), ('n', 2)] 0" },
      explain: L("banana has three a's and two n's. A Counter returns 0 for missing keys, no KeyError.", "banana tiene tres a y dos n. Un Counter devuelve 0 para claves que faltan, sin KeyError.", "banana は a が3つ、n が2つ。Counter はないキーに 0 を返し、KeyError にならないよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'from collections import defaultdict\nd = defaultdict(list)\nd["gems"].append(1)\nprint(dict(d), len(d))',
      options: ["{'gems': [1]} 1", "KeyError", "{} 0"],
      answer: 0,
      output: "{'gems': [1]} 1",
      check: { compiles: true, stdout: "{'gems': [1]} 1" },
      explain: L("A missing key gets a fresh list() automatically, so append just works.", "Una clave que falta recibe una list() nueva automáticamente, así que append funciona.", "ないキーには自動で新しい list() が入るから、そのまま append できるよ。"),
    },
    {
      kind: "run",
      prompt: L("Rank by score: ranking: ['bo', 'cy', 'ada']", "Ordena por puntaje: ranking: ['bo', 'cy', 'ada']", "点数順に：ranking: ['bo', 'cy', 'ada']"),
      starter: 'scores = {"ada": 3, "bo": 9, "cy": 5}\ntop = sorted(scores)\nprint("ranking:", top)\n',
      solution: 'scores = {"ada": 3, "bo": 9, "cy": 5}\ntop = sorted(scores, key=scores.get, reverse=True)\nprint("ranking:", top)\n',
      expect: "ranking: ['bo', 'cy', 'ada']",
      fallback: [String.raw`key\s*=\s*scores\.get`, String.raw`key\s*=\s*lambda\s+(\w+)\s*:\s*-?\s*scores\[\s*\1\s*\]`, String.raw`key\s*=\s*scores\.__getitem__`],
      explain: L("sorted(scores) sorts the names A to Z. key=scores.get sorts by each score, reverse=True puts the highest first.", "sorted(scores) ordena los nombres de la A a la Z. key=scores.get ordena por puntaje y reverse=True pone el mayor primero.", "sorted(scores) は名前のABC順。key=scores.get で点数順、reverse=True で高い順になるよ。"),
    },
  ],
};

// ─── 2.5 Boss: Alias Hydra ─────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "alias-hydra",
  title: L("Boss: Alias Hydra", "Jefe: Hidra de Alias", "ボス：エイリアスヒドラ"),
  concept: "references",
  mode: "boss",
  xp: 190,
  enemy: "dragon",
  enemyName: L("ALIAS HYDRA", "HIDRA DE ALIAS", "エイリアスヒドラ"),
  beats: [
    enemySays(L(
      "I AM THE ALIAS HYDRA. All my heads share ONE body. Cut one, and the others feel it!",
      "SOY LA HIDRA DE ALIAS. Todas mis cabezas comparten UN cuerpo. ¡Corta una y las demás lo sienten!",
      "我はエイリアスヒドラ。すべての首は「ひとつ」の体を共有する。1本切れば、ほかも感じるぞ！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "x = [1, 2, 3]\nfor n in x:\n    if n == 2:\n        x.remove(n)\nprint(x)", options: ["[1, 3]", "[1, 2, 3]", "RuntimeError"], answer: 0, output: "[1, 3]", check: { compiles: true, stdout: "[1, 3]" }, explain: L("remove deletes the first matching value. Here the 2 is gone.", "remove borra el primer valor que coincide. Aquí el 2 desaparece.", "remove は最初に一致した値を消す。ここでは 2 が消える。") },
    { kind: "predict", time: 18, prompt: PRINT, code: "x = [1, 2, 2, 3]\nfor n in x:\n    if n == 2:\n        x.remove(n)\nprint(x)", options: ["[1, 2, 3]", "[1, 3]", "[1, 2, 2, 3]"], answer: 0, output: "[1, 2, 3]", check: { compiles: true, stdout: "[1, 2, 3]" }, explain: L("Removing while looping shifts items left, so the loop skips the second 2. Loop over a copy.", "Quitar mientras recorres corre las cosas a la izquierda y el bucle salta el segundo 2. Recorre una copia.", "ループ中に消すと要素が左にずれ、2つ目の 2 を飛ばす。コピーをループしよう。") },
    { kind: "predict", time: 15, prompt: HAPPENS, code: 'd = {"a": 1}\nfor k in d:\n    d["b"] = 2', options: ["RuntimeError", "KeyError", L("Nothing, it runs", "Nada, funciona", "問題なく動く")], answer: 0, check: { compiles: true, throws: "RuntimeError" }, explain: L("A dict can't grow while you loop over it: RuntimeError: dictionary changed size during iteration.", "Un dict no puede crecer mientras lo recorres: RuntimeError: dictionary changed size during iteration.", "ループ中の dict は増やせない。RuntimeError: dictionary changed size during iteration。") },
    { kind: "pick", time: 15, prompt: L("Fix it so only one row changes", "Haz que cambie solo una fila", "1行だけ変わるように直そう"), code: "grid = [[0] * 2 ___]\ngrid[0][0] = 9\nprint(grid)", options: ["for _ in range(2)", "* 2"], answer: 0, check: { compiles: true, stdout: "[[9, 0], [0, 0]]" }, explain: L("The comprehension builds a NEW inner list on each pass, so the rows are separate.", "La comprensión crea una lista interna NUEVA en cada vuelta, así que las filas son independientes.", "内包表記は毎回「新しい」内側リストを作るので、行どうしは別物になる。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'd = dict.fromkeys(["a", "b"], [])\nd["a"].append(1)\nprint(d)', options: ["{'a': [1], 'b': [1]}", "{'a': [1], 'b': []}", "KeyError"], answer: 0, output: "{'a': [1], 'b': [1]}", check: { compiles: true, stdout: "{'a': [1], 'b': [1]}" }, explain: L("fromkeys puts the SAME list on every key. One list, two labels.", "fromkeys pone la MISMA lista en cada clave. Una lista, dos etiquetas.", "fromkeys は全キーに「同じ」リストを入れる。リスト1つにラベル2枚。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print([1, 2, 3][::-1], [1, 2, 3][-2:])", options: ["[3, 2, 1] [2, 3]", "[3, 2, 1] [1, 2]", "[1, 2, 3] [2, 3]"], answer: 0, output: "[3, 2, 1] [2, 3]", check: { compiles: true, stdout: "[3, 2, 1] [2, 3]" }, explain: L("[::-1] reverses. [-2:] takes the last two items.", "[::-1] invierte. [-2:] toma los dos últimos.", "[::-1] は逆順。[-2:] は最後の2つ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "x = [1, 2, 3]\nprint(x * 2, x[1:] + x[:1])", options: ["[1, 2, 3, 1, 2, 3] [2, 3, 1]", "[2, 4, 6] [2, 3, 1]", "[1, 2, 3, 1, 2, 3] [1, 2, 3]"], answer: 0, output: "[1, 2, 3, 1, 2, 3] [2, 3, 1]", check: { compiles: true, stdout: "[1, 2, 3, 1, 2, 3] [2, 3, 1]" }, explain: L("list * 2 repeats it. Gluing the tail to the head rotates it.", "list * 2 la repite. Pegar la cola a la cabeza la rota.", "list * 2 はくり返し。後ろと先頭をつなぐと回転する。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'print({"a": 1} | {"a": 2}, sorted({3, 1} | {2}))', options: ["{'a': 2} [1, 2, 3]", "{'a': 1} [1, 2, 3]", "TypeError"], answer: 0, output: "{'a': 2} [1, 2, 3]", check: { compiles: true, stdout: "{'a': 2} [1, 2, 3]" }, explain: L("| merges dicts too: on a shared key, the right side wins. On sets it's union.", "| también fusiona dicts: en una clave común gana el lado derecho. En sets es la unión.", "| は dict も合体できる。同じキーなら右側が勝つ。set では和集合。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "a = [[0], [0]]\nb = a[:]\nb[0].append(1)\nb[1] = [7]\nprint(a)", options: ["[[0, 1], [0]]", "[[0, 1], [7]]", "[[0], [0]]"], answer: 0, output: "[[0, 1], [0]]", check: { compiles: true, stdout: "[[0, 1], [0]]" }, explain: L("b is a shallow copy: the inner [0] lists are shared, but b[1] = [7] only re-labels b's slot.", "b es una copia superficial: las listas [0] internas se comparten, pero b[1] = [7] solo cambia el lugar de b.", "b は浅いコピー。中の [0] は共有だけど、b[1] = [7] は b の枠を貼りかえるだけ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'words = ["kiwi", "fig", "apple"]\nprint(max(words, key=len), sorted(words, key=len))', options: ["apple ['fig', 'kiwi', 'apple']", "kiwi ['apple', 'fig', 'kiwi']", "apple ['apple', 'kiwi', 'fig']"], answer: 0, output: "apple ['fig', 'kiwi', 'apple']", check: { compiles: true, stdout: "apple ['fig', 'kiwi', 'apple']" }, explain: L("key=len compares lengths: apple is longest, and sorting goes 3, 4, 5 letters.", "key=len compara largos: apple es el más largo y el orden va de 3, 4 a 5 letras.", "key=len は長さで比べる。最長は apple、並びは3文字・4文字・5文字。") },
    { kind: "type", time: 15, prompt: L("Count the loot in one line", "Cuenta el botín en una línea", "1行で戦利品を数えよう"), code: 'from collections import Counter\nprint(___("gemgem")["g"])', answer: "Counter", check: { compiles: true, stdout: "2" }, explain: L("Counter counts every letter. There are two g's.", "Counter cuenta cada letra. Hay dos g.", "Counter は文字ごとに数える。g は2つ。") },
    enemySays(L(
      "Ssss... you saw which heads shared a body. The Function Peaks await you, little traveler.",
      "Ssss... viste qué cabezas compartían cuerpo. Las Cumbres de Funciones te esperan, pequeño viajero.",
      "シャー…どの首が体を共有していたか見抜いたな。関数の山が待っているぞ、小さな旅人よ。",
    )),
  ],
};

export const collectionForest: RegionDef = {
  slug: "collection-forest",
  name: L("Collection Forest", "Bosque de Colecciones", "コレクションの森"),
  subtitle: L("list · dict · set · copies · sorting", "list · dict · set · copias · orden", "list・dict・set・コピー・整列"),
  theme: "forest",
  lessons: [lists, dicts, shared, comprehensions, boss],
};
