import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 3 · FUNCTION PEAKS (functions and arguments, scope and closures, decorators, exceptions).
// Stage mapping: a function is a key item; the hero gives it chips and a chip comes back.
// A closure is the key carrying a backpack scroll; a decorator is the ally wrapping the key.
// An exception is a shake plus a banner with its class; except is the ally's net.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
/** Code is written line by line for readability. */
const code = (...lines: string[]) => lines.join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");

// ─── 3.1 Spell keys: functions and arguments ────────────────────────────────
const functions: LessonDef = {
  slug: "functions-and-arguments",
  title: L("Spell keys", "Llaves de hechizo", "呪文のカギ"),
  concept: "functions",
  mode: "lesson",
  xp: 70,
  enemy: "python/mutable-mimic",
  enemyName: L("MIMIC BAG", "BOLSA MÍMICA", "ミミックぶくろ"),
  beats: [
    say(L(
      "Welcome to Function Peaks! def builds a FUNCTION: a spell key. Give it arguments, and return hands a value back.",
      "¡Bienvenido a los Picos de Funciones! def crea una FUNCIÓN: una llave de hechizo. Recibe argumentos y return devuelve un valor.",
      "関数の峰へようこそ！def で関数という呪文のカギを作る。引数をわたすと return で値が返ってくるよ。",
    )),
    {
      kind: "act",
      prompt: L("Forge the key, then turn it twice", "Forja la llave y gírala dos veces", "カギを作って、2回まわそう"),
      steps: [
        { label: L("DEF", "DEF", "def"), line: "def heal(hp, amount=5):", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "heal" }] },
        { label: L("RETURN", "RETURN", "return"), line: "    return hp + amount", effects: [{ t: "say", actor: "hero", text: L("Key ready!", "¡Llave lista!", "カギかんせい！") }] },
        { label: L("CALL", "LLAMAR", "呼ぶ"), line: "print(heal(10))", output: "15", effects: [{ t: "value", actor: "hero", text: "15" }, { t: "print", text: "15" }] },
        { label: L("CALL WITH 1", "LLAMAR CON 1", "1 で呼ぶ"), line: "print(heal(10, 1))", output: "11", effects: [{ t: "value", actor: "hero", text: "11" }, { t: "print", text: "11" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def heal(hp, amount=5):", "    return hp + amount", "print(heal(10), heal(10, 1), heal(amount=2, hp=1))"),
      options: ["15 11 3", "15 11 7", "15 6 3"],
      answer: 0,
      output: "15 11 3",
      check: { compiles: true, stdout: "15 11 3" },
      explain: L(
        "amount defaults to 5. Keyword arguments match by NAME, so their order does not matter: 1 + 2 = 3.",
        "amount vale 5 por defecto. Los argumentos con nombre se asignan por NOMBRE, el orden no importa: 1 + 2 = 3.",
        "amount の初期値は 5。キーワード引数は名前で決まるので順番は関係ない。1 + 2 = 3。",
      ),
      win: [{ t: "print", text: "15 11 3" }],
    },
    say(L(
      "No return? The function still runs, but hands back None, Python's 'nothing here'.",
      "¿Sin return? La función corre igual, pero devuelve None, el 'aquí no hay nada' de Python.",
      "return がない？関数は動くけど、返ってくるのは None。Python の「何もない」だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def shout():", '    print("hi")', "r = shout()", "print(r)"),
      options: ["hi None", "hi hi", "None"],
      answer: 0,
      output: "hi\nNone",
      check: { compiles: true, stdout: "hi\nNone" },
      explain: L(
        "Printing is not returning. shout prints hi, then gives back None, so r is None.",
        "Imprimir no es devolver. shout imprime hi y luego devuelve None, así que r es None.",
        "表示と返すことは別。shout は hi を表示して None を返すから、r は None。",
      ),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "shout" }],
      win: [{ t: "print", text: "hi" }, { t: "value", actor: "hero", text: "None" }, { t: "say", actor: "hero", text: L("Nothing came back!", "¡No volvió nada!", "何も返らない！") }],
    },
    say(L(
      "*args gathers extra positional arguments into a TUPLE. **kwargs gathers extra keyword ones into a DICT.",
      "*args junta los argumentos posicionales extra en una TUPLA. **kwargs junta los de nombre extra en un DICT.",
      "*args は余った位置引数をタプルに、**kwargs は余ったキーワード引数を辞書にまとめるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def total(*args, **kwargs):", "    return args, kwargs", "print(total(1, 2, x=3))"),
      options: ["((1, 2), {'x': 3})", "([1, 2], {'x': 3})", "((1, 2, 3), {})"],
      answer: 0,
      output: "((1, 2), {'x': 3})",
      check: { compiles: true, stdout: "((1, 2), {'x': 3})" },
      explain: L(
        "1 and 2 go to args as a tuple; x=3 goes to kwargs as a dict. Returning two values makes a tuple too.",
        "1 y 2 van a args como tupla; x=3 va a kwargs como dict. Devolver dos valores también arma una tupla.",
        "1 と 2 はタプルで args へ、x=3 は辞書で kwargs へ。2つ返すとそれもタプルになるよ。",
      ),
      win: [{ t: "print", text: "((1, 2), {'x': 3})" }],
    },
    {
      kind: "type",
      prompt: L("Gather every argument", "Junta todos los argumentos", "引数をぜんぶ集めよう"),
      code: code("def total(___args):", "    return sum(args)", "print(total(1, 2, 3))"),
      answer: "*",
      check: { compiles: true, stdout: "6" },
      explain: L("One star packs the positional arguments into the tuple args.", "Una estrella empaca los argumentos posicionales en la tupla args.", "星ひとつで位置引数がタプル args にまとまるよ。"),
      win: [{ t: "print", text: "6" }],
    },
    say(L(
      "TRAP! A default value is built ONCE, when def runs. A list default is the same list in every call.",
      "¡TRAMPA! Un valor por defecto se crea UNA vez, cuando corre def. Una lista por defecto es la misma en cada llamada.",
      "ワナ！デフォルト値は def の実行時に一度だけ作られる。リストなら毎回同じリストだよ。",
    )),
    {
      kind: "act",
      prompt: L("Call it twice and watch the bag", "Llámala dos veces y mira la bolsa", "2回呼んで、袋を見てごらん"),
      steps: [
        { label: L("DEF", "DEF", "def"), line: "def add_item(item, bag=[]):", effects: [{ t: "item", kind: "scroll", holder: "enemy" }, { t: "tag", actor: "enemy", text: "bag" }, { t: "say", actor: "enemy", text: L("One bag, forever", "Una bolsa, siempre", "袋はずっと1つ") }] },
        { label: L("APPEND", "APPEND", "append"), line: "    bag.append(item)" },
        { label: L("RETURN", "RETURN", "return"), line: "    return bag" },
        { label: L("ADD gem", "AGREGAR gem", "gem を追加"), line: 'print(add_item("gem"))', output: "['gem']", effects: [{ t: "value", actor: "enemy", text: "['gem']" }, { t: "print", text: "['gem']" }] },
        {
          label: L("ADD key", "AGREGAR key", "key を追加"),
          line: 'print(add_item("key"))',
          output: "['gem', 'key']",
          effects: [{ t: "value", actor: "enemy", text: "['gem', 'key']" }, { t: "shake" }, { t: "say", actor: "hero", text: L("Where's that gem from?", "¿Y esa gema?", "その gem はどこから？") }, { t: "print", text: "['gem', 'key']" }],
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def add_item(item, bag=[]):", "    bag.append(item)", "    return bag", 'add_item("gem")', 'print(add_item("key"))'),
      options: ["['gem', 'key']", "['key']", "['gem']"],
      answer: 0,
      output: "['gem', 'key']",
      check: { compiles: true, stdout: "['gem', 'key']" },
      explain: L(
        "The [] was made once, when def ran. Both calls append to that same list.",
        "La [] se creó una sola vez, al correr def. Ambas llamadas agregan a esa misma lista.",
        "[] は def のときに一度だけ作られた。2回とも同じリストに追加しているよ。",
      ),
      win: [{ t: "print", text: "['gem', 'key']" }, { t: "shake" }],
    },
    {
      kind: "pick",
      prompt: L("Pick the safe default", "Elige el valor seguro", "安全なデフォルトは？"),
      code: code("def add_item(item, bag=___):", "    if bag is None:", "        bag = []", "    bag.append(item)", "    return bag", 'add_item("gem")', 'print(add_item("key"))'),
      options: ["None", "[]"],
      answer: 0,
      check: { compiles: true, stdout: "['key']" },
      explain: L(
        "None is a safe marker. Each call that gets None builds a NEW empty list inside the function.",
        "None es una marca segura. Cada llamada que recibe None crea una lista vacía NUEVA dentro de la función.",
        "None は安全な目印。None を受けたら、関数の中で毎回新しい空リストを作るよ。",
      ),
      win: [{ t: "print", text: "['key']" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    say(L(
      "Parameters after a bare * are keyword-only: you MUST name them. Parameters before / are positional-only.",
      "Los parámetros después de un * solo son de nombre: DEBES nombrarlos. Los que van antes de / son solo posicionales.",
      "単独の * の後ろはキーワード専用で、名前が必須。/ の前は位置専用の引数だよ。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("def cast(a, /, b, *, c):", "    return a + b + c", "print(cast(1, 2, c=3))", "print(cast(1, 2, 3))"),
      options: [L("6, then TypeError", "6 y luego TypeError", "6 の後 TypeError"), "6 6", L("SyntaxError", "SyntaxError", "SyntaxError")],
      answer: 0,
      check: { compiles: true, throws: "TypeError" },
      explain: L(
        "The first call names c and prints 6. The second passes c by position, so Python raises TypeError.",
        "La primera llamada nombra c e imprime 6. La segunda pasa c por posición, y Python lanza TypeError.",
        "1回目は c を名前でわたして 6。2回目は位置でわたしたので TypeError になるよ。",
      ),
      win: [{ t: "print", text: "6" }, { t: "shake" }, { t: "banner", text: L("TypeError", "TypeError", "TypeError") }],
    },
    say(L(
      "return a, b sends back a TUPLE you can unpack. lambda makes a tiny one-line function with no name.",
      "return a, b devuelve una TUPLA que puedes desempacar. lambda crea una función mini de una línea, sin nombre.",
      "return a, b はタプルを返し、分けて受け取れる。lambda は名前のない1行の小さな関数だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def stats():", "    return 3, 5", "hp, mp = stats()", "print(hp, mp, type(stats()).__name__)"),
      options: ["3 5 tuple", "3 5 list", "(3, 5) None tuple"],
      answer: 0,
      output: "3 5 tuple",
      check: { compiles: true, stdout: "3 5 tuple" },
      explain: L("3, 5 is one tuple; hp, mp = ... unpacks it into two names.", "3, 5 es una sola tupla; hp, mp = ... la desempaca en dos nombres.", "3, 5 は1つのタプル。hp, mp = で2つの名前に分けるよ。"),
      win: [{ t: "print", text: "3 5 tuple" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("sq = lambda x: x * x", "print(sq(4), (lambda a, b=2: a * b)(3))"),
      options: ["16 6", "16 9", "8 6"],
      answer: 0,
      output: "16 6",
      check: { compiles: true, stdout: "16 6" },
      explain: L("A lambda returns its expression. The second one uses its default b=2: 3 * 2.", "Una lambda devuelve su expresión. La segunda usa su valor por defecto b=2: 3 * 2.", "lambda は式の値を返す。2つ目は b=2 のデフォルトで 3 * 2。"),
      win: [{ t: "print", text: "16 6" }],
    },
    {
      kind: "run",
      prompt: L("Give each hero their own bag", "Dale a cada héroe su propia bolsa", "それぞれに自分の袋を持たせよう"),
      starter: code("def add_loot(item, bag=[]):", "    bag.append(item)", "    return bag", "", 'print("ada:", add_loot("gem"))', 'print("bo:", add_loot("key"))', ""),
      solution: code("def add_loot(item, bag=None):", "    if bag is None:", "        bag = []", "    bag.append(item)", "    return bag", "", 'print("ada:", add_loot("gem"))', 'print("bo:", add_loot("key"))', ""),
      expect: "bo: ['key']",
      fallback: [String.raw`bag\s*=\s*None[\s\S]*if\s+(bag\s+is\s+None|not\s+bag)`, String.raw`bag\s*=\s*None[\s\S]*bag\s*=\s*bag\s+or\s+\[\]`],
      explain: L(
        "Use bag=None, then if bag is None: bag = []. Each call gets a fresh list.",
        "Usa bag=None y luego if bag is None: bag = []. Cada llamada recibe una lista nueva.",
        "bag=None にして、if bag is None: bag = [] と書こう。毎回新しいリストになるよ。",
      ),
    },
  ],
};

// ─── 3.2 The fog and the backpack: scope and closures ───────────────────────
const scope: LessonDef = {
  slug: "scope-and-closures",
  title: L("The fog and the backpack", "La niebla y la mochila", "霧とリュック"),
  concept: "scope_closures",
  mode: "lesson",
  xp: 75,
  enemy: "python/none-ghost",
  enemyName: L("FOG GHOST", "FANTASMA DE NIEBLA", "キリゴースト"),
  beats: [
    say(L(
      "Fog rings! Python looks a name up from the inside out: Local, Enclosing, Global, Built-in. LEGB.",
      "¡Anillos de niebla! Python busca un nombre de adentro hacia afuera: Local, Enclosing, Global, Built-in. LEGB.",
      "霧の輪！Python は名前を内側から外へ探す。ローカル、外側の関数、グローバル、組み込み。LEGB だよ。",
    )),
    {
      kind: "act",
      prompt: L("Make two x's: one outside, one inside", "Crea dos x: una afuera, otra adentro", "x を2つ作ろう：外と中"),
      steps: [
        { label: L("GLOBAL x", "x GLOBAL", "グローバル x"), line: 'x = "global"', effects: [{ t: "tag", actor: "hero", text: "x", value: '"global"' }] },
        { label: L("DEF f", "DEF f", "f を定義"), line: "def f():" },
        { label: L("LOCAL x", "x LOCAL", "ローカル x"), line: '    x = "local"', effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "x", value: '"local"' }, { t: "say", actor: "ally", text: L("My own x!", "¡Mi propia x!", "自分の x！") }] },
        { label: L("RETURN x", "RETURN x", "x を返す"), line: "    return x" },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "print(f(), x)", output: "local global", effects: [{ t: "print", text: "local global" }, { t: "exit", actor: "ally" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code('x = "global"', "def f():", '    x = "local"', "    return x", "print(f(), x)"),
      options: ["local global", "local local", "global global"],
      answer: 0,
      output: "local global",
      check: { compiles: true, stdout: "local global" },
      explain: L(
        "Assigning inside f makes a NEW local x. The global x is untouched.",
        "Asignar dentro de f crea una x local NUEVA. La x global no se toca.",
        "f の中で代入すると新しいローカル x ができる。グローバルの x はそのままだよ。",
      ),
      win: [{ t: "print", text: "local global" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("x = 10", "def f():", "    return x", "x = 20", "print(f())"),
      options: ["20", "10", "NameError"],
      answer: 0,
      output: "20",
      check: { compiles: true, stdout: "20" },
      explain: L(
        "f has no local x, so it reads the global one WHEN it runs. By then x is 20.",
        "f no tiene x local, así que lee la global CUANDO corre. Para entonces x vale 20.",
        "f にローカル x はないので、呼んだ「とき」のグローバル x を読む。もう 20 だよ。",
      ),
      win: [{ t: "print", text: "20" }],
    },
    say(L(
      "Careful: assigning a name ANYWHERE in a function makes it local for the WHOLE function, even lines above.",
      "Cuidado: asignar un nombre en CUALQUIER parte de una función lo vuelve local en TODA la función, incluso arriba.",
      "注意！関数のどこかで代入した名前は、上の行も含めて関数「全体」でローカルになるよ。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("count = 0", "def inc():", "    count += 1", "inc()"),
      options: ["UnboundLocalError", L("count becomes 1", "count pasa a 1", "count が 1 になる"), "NameError"],
      answer: 0,
      check: { compiles: true, throws: "UnboundLocalError" },
      explain: L(
        "count += 1 assigns, so count is local in inc. Reading it before it has a value fails.",
        "count += 1 asigna, así que count es local en inc. Leerla antes de que tenga valor falla.",
        "count += 1 は代入なので inc の中で count はローカル。値がないうちに読むと失敗するよ。",
      ),
      win: [{ t: "shake" }, { t: "banner", text: L("UnboundLocalError", "UnboundLocalError", "ローカル未定義！") }],
    },
    {
      kind: "type",
      prompt: L("Use the module's count", "Usa el count del módulo", "モジュールの count を使おう"),
      code: code("count = 0", "def inc():", "    ___ count", "    count += 1", "inc()", "inc()", "print(count)"),
      answer: "global",
      check: { compiles: true, stdout: "2" },
      explain: L("global count says: this name is the module-level one, not a new local.", "global count dice: este nombre es el del módulo, no uno local nuevo.", "global count は「新しいローカルじゃなく、モジュールの名前だよ」という宣言。"),
      win: [{ t: "print", text: "2" }],
    },
    say(L(
      "A function made inside another keeps the outer names alive in a backpack: a CLOSURE. nonlocal lets it change them.",
      "Una función creada dentro de otra guarda los nombres de afuera en una mochila: un CLOSURE. nonlocal le deja cambiarlos.",
      "関数の中で作った関数は、外の名前をリュックに入れて持ち歩く。これがクロージャ。nonlocal で書きかえられるよ。",
    )),
    {
      kind: "act",
      prompt: L("Pack the backpack, then step twice", "Llena la mochila y avanza dos veces", "リュックに入れて、2回進もう"),
      steps: [
        { label: L("FACTORY", "FÁBRICA", "工場"), line: "def make_counter():" },
        { label: L("count = 0", "count = 0", "count = 0"), line: "    count = 0", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "count", value: "0" }] },
        { label: L("INNER", "INTERNA", "内側"), line: "    def step():" },
        { label: L("NONLOCAL", "NONLOCAL", "nonlocal"), line: "        nonlocal count" },
        { label: L("ADD 1", "SUMAR 1", "1 足す"), line: "        count += 1" },
        { label: L("RETURN IT", "DEVOLVERLO", "返す"), line: "        return count" },
        { label: L("HAND OVER", "ENTREGAR", "わたす"), line: "    return step", effects: [{ t: "enter", actor: "ally" }, { t: "give", to: "ally" }, { t: "say", actor: "ally", text: L("Backpack on!", "¡Mochila puesta!", "リュック装備！") }] },
        { label: L("CALL TWICE", "LLAMAR 2 VECES", "2回呼ぶ"), line: "c = make_counter(); c(); print(c())", output: "2", effects: [{ t: "tag", actor: "ally", text: "count", value: "2" }, { t: "print", text: "2" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def make_counter():", "    count = 0", "    def step():", "        nonlocal count", "        count += 1", "        return count", "    return step", "c = make_counter()", "c()", "c()", "print(c())"),
      options: ["3", "1", "0"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L(
        "step keeps count in its backpack between calls, and nonlocal lets it update it: 1, 2, 3.",
        "step guarda count en su mochila entre llamadas, y nonlocal le deja actualizarla: 1, 2, 3.",
        "step は呼び出しの間も count をリュックに持ち、nonlocal で更新する。1、2、3。",
      ),
      win: [{ t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def mult(n):", "    return lambda x: x * n", "double = mult(2)", "print(double(5), mult(3)(5))"),
      options: ["10 15", "10 10", "15 15"],
      answer: 0,
      output: "10 15",
      check: { compiles: true, stdout: "10 15" },
      explain: L("Each call to mult makes a new closure with its own n: 2, then 3.", "Cada llamada a mult crea un closure nuevo con su propio n: 2 y luego 3.", "mult を呼ぶたびに、自分の n を持つ新しいクロージャができる。2 と 3。"),
      win: [{ t: "print", text: "10 15" }],
    },
    say(L(
      "Closures remember the VARIABLE, not its value at that moment. In a loop, every lambda shares one i.",
      "Los closures recuerdan la VARIABLE, no su valor en ese momento. En un bucle, todas las lambdas comparten una sola i.",
      "クロージャが覚えるのは「変数」で、その時の値じゃない。ループの lambda はみんな同じ i を見るよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("fns = [lambda: i for i in range(3)]", "print([f() for f in fns])"),
      options: ["[2, 2, 2]", "[0, 1, 2]", "[0, 0, 0]"],
      answer: 0,
      output: "[2, 2, 2]",
      check: { compiles: true, stdout: "[2, 2, 2]" },
      explain: L(
        "The lambdas run after the loop ends. They all read the same i, which is 2 by then.",
        "Las lambdas corren después del bucle. Todas leen la misma i, que para entonces vale 2.",
        "lambda が動くのはループの後。みんな同じ i を読み、その時 i は 2 だよ。",
      ),
      win: [{ t: "print", text: "[2, 2, 2]" }, { t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("fns = [lambda i=i: i for i in range(3)]", "print([f() for f in fns])"),
      options: ["[0, 1, 2]", "[2, 2, 2]", "TypeError"],
      answer: 0,
      output: "[0, 1, 2]",
      check: { compiles: true, stdout: "[0, 1, 2]" },
      explain: L(
        "A default is evaluated when the lambda is made, so i=i freezes each value: 0, 1, 2.",
        "Un valor por defecto se evalúa al crear la lambda, así que i=i congela cada valor: 0, 1, 2.",
        "デフォルト値は lambda を作るときに決まる。i=i でその時の値が固定される。0、1、2。",
      ),
      win: [{ t: "print", text: "[0, 1, 2]" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "run",
      prompt: L("Fix the counter: it must print count: 2", "Arregla el contador: debe imprimir count: 2", "カウンターを直して count: 2 と表示しよう"),
      starter: code("def make_counter():", "    count = 0", "    def step():", "        count += 1", "        return count", "    return step", "", "c = make_counter()", "c()", 'print("count:", c())', ""),
      solution: code("def make_counter():", "    count = 0", "    def step():", "        nonlocal count", "        count += 1", "        return count", "    return step", "", "c = make_counter()", "c()", 'print("count:", c())', ""),
      expect: "count: 2",
      fallback: String.raw`nonlocal\s+count`,
      explain: L(
        "count += 1 makes count local to step. Add nonlocal count so step updates the outer one.",
        "count += 1 vuelve local a count en step. Agrega nonlocal count para que step cambie la de afuera.",
        "count += 1 で count は step のローカルになる。nonlocal count を足して外側を更新しよう。",
      ),
    },
  ],
};

// ─── 3.3 Wrapping spells: decorators ────────────────────────────────────────
const decorators: LessonDef = {
  slug: "decorators",
  title: L("Wrapping spells", "Hechizos envueltos", "呪文をつつむ"),
  concept: "decorators",
  mode: "lesson",
  xp: 75,
  enemy: "python/indent-gremlin",
  enemyName: L("WRAPPER GREMLIN", "GREMLIN ENVOLTORIO", "ラッパーグレムリン"),
  beats: [
    say(L(
      "Functions are objects: you can pass them and return them. A DECORATOR takes a function and returns a wrapped one.",
      "Las funciones son objetos: puedes pasarlas y devolverlas. Un DECORADOR recibe una función y devuelve una envuelta.",
      "関数もオブジェクト。わたしたり返したりできる。デコレータは関数を受け取り、包んだ関数を返すよ。",
    )),
    {
      kind: "act",
      prompt: L("Wrap the key in a shield", "Envuelve la llave en un escudo", "カギを盾でつつもう"),
      steps: [
        { label: L("DECORATOR", "DECORADOR", "デコレータ"), line: "def shout(fn):", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "shield", holder: "ally" }] },
        { label: L("WRAPPER", "WRAPPER", "ラッパー"), line: "    def wrapper(*args, **kwargs):" },
        { label: L("CALL fn", "LLAMAR fn", "fn を呼ぶ"), line: "        return fn(*args, **kwargs).upper()" },
        { label: L("RETURN IT", "DEVOLVERLO", "返す"), line: "    return wrapper" },
        { label: L("@shout", "@shout", "@shout"), line: "@shout", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "give", to: "ally" }, { t: "say", actor: "ally", text: L("Calls go through me", "Pasan por mí", "呼び出しは私経由") }] },
        { label: L("DEF greet", "DEF greet", "greet を定義"), line: 'def greet(name): return f"hi {name}"' },
        { label: L("CALL", "LLAMAR", "呼ぶ"), line: 'print(greet("ada"))', output: "HI ADA", effects: [{ t: "print", text: "HI ADA" }, { t: "attack", from: "ally", to: "enemy" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def shout(fn):", "    def wrapper(*args, **kwargs):", "        return fn(*args, **kwargs).upper()", "    return wrapper", "@shout", "def greet(name):", '    return f"hi {name}"', 'print(greet("ada"))'),
      options: ["HI ADA", "hi ada", "None"],
      answer: 0,
      output: "HI ADA",
      check: { compiles: true, stdout: "HI ADA" },
      explain: L(
        "greet now IS the wrapper. It calls the original greet and uppercases the result.",
        "greet ahora ES el wrapper. Llama al greet original y pasa el resultado a mayúsculas.",
        "greet の正体はもう wrapper。元の greet を呼んで、結果を大文字にするよ。",
      ),
      win: [{ t: "print", text: "HI ADA" }],
    },
    say(L(
      "@shout above def greet is just shorthand for greet = shout(greet).",
      "@shout encima de def greet es solo un atajo de greet = shout(greet).",
      "def greet の上の @shout は、greet = shout(greet) の省略形だよ。",
    )),
    {
      kind: "pick",
      prompt: L("Decorate without the @", "Decora sin la @", "@ を使わずに飾ろう"),
      code: code("def shout(fn):", "    def wrapper(name):", "        return fn(name).upper()", "    return wrapper", "def greet(name):", '    return f"hi {name}"', "greet = ___(greet)", 'print(greet("ada"))'),
      options: ["shout", "wrapper", "greet"],
      answer: 0,
      check: { compiles: true, stdout: "HI ADA" },
      explain: L("shout(greet) returns the wrapper. wrapper only exists inside shout.", "shout(greet) devuelve el wrapper. wrapper solo existe dentro de shout.", "shout(greet) が wrapper を返す。wrapper は shout の中にしかないよ。"),
      win: [{ t: "print", text: "HI ADA" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def log(fn):", "    def wrapper(x):", '        print("before")', "        r = fn(x)", '        print("after")', "        return r", "    return wrapper", "@log", "def f(x):", '    print("in", x)', "    return x", "print(f(1))"),
      options: ["before in 1 after 1", "in 1 before after 1", "before after in 1 1"],
      answer: 0,
      output: "before\nin 1\nafter\n1",
      check: { compiles: true, stdout: "before\nin 1\nafter\n1" },
      explain: L(
        "The wrapper runs its own lines around the call: before, the original f, after, then returns r.",
        "El wrapper corre sus líneas alrededor de la llamada: before, la f original, after, y devuelve r.",
        "wrapper は呼び出しの前後に自分の行を実行する。before、元の f、after、そして r を返すよ。",
      ),
      win: [{ t: "say", actor: "ally", text: L("before", "before", "before") }, { t: "say", actor: "ally", text: L("after", "after", "after") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def register(fn):", '    print("registering", fn.__name__)', "    return fn", "@register", "def spell():", '    print("cast")', 'print("start")', "spell()"),
      options: ["registering spell start cast", "start registering spell cast", "start cast"],
      answer: 0,
      output: "registering spell\nstart\ncast",
      check: { compiles: true, stdout: "registering spell\nstart\ncast" },
      explain: L(
        "A decorator runs when def runs, before any call. That is how frameworks register routes.",
        "Un decorador corre cuando corre def, antes de cualquier llamada. Así registran rutas los frameworks.",
        "デコレータは def のときに動く。呼び出しより前だよ。フレームワークのルート登録はこの仕組み。",
      ),
      win: [{ t: "print", text: "registering spell" }],
    },
    say(L(
      "A wrapper hides the original's name. @functools.wraps(fn) on the wrapper copies the name back.",
      "Un wrapper esconde el nombre del original. @functools.wraps(fn) sobre el wrapper copia el nombre de vuelta.",
      "wrapper は元の名前を隠してしまう。wrapper に @functools.wraps(fn) をつけると名前が戻るよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def deco(fn):", "    def wrapper():", "        return fn()", "    return wrapper", "@deco", "def hello():", '    return "hi"', "print(hello.__name__)"),
      options: ["wrapper", "hello", "deco"],
      answer: 0,
      output: "wrapper",
      check: { compiles: true, stdout: "wrapper" },
      explain: L("hello now points to wrapper, so its __name__ is wrapper. That confuses logs and debuggers.", "hello ahora apunta a wrapper, así que su __name__ es wrapper. Eso confunde logs y depuradores.", "hello の中身は wrapper なので __name__ も wrapper。ログやデバッグが混乱するよ。"),
      win: [{ t: "print", text: "wrapper" }],
    },
    {
      kind: "type",
      prompt: L("Keep the name hello", "Conserva el nombre hello", "名前 hello を残そう"),
      code: code("import functools", "def deco(fn):", "    @functools.___(fn)", "    def wrapper():", "        return fn()", "    return wrapper", "@deco", "def hello():", '    return "hi"', "print(hello.__name__)"),
      answer: "wraps",
      check: { compiles: true, stdout: "hello" },
      explain: L("functools.wraps copies __name__ (and the docstring) from fn onto the wrapper.", "functools.wraps copia __name__ (y el docstring) de fn al wrapper.", "functools.wraps は fn の __name__ や docstring を wrapper にコピーするよ。"),
      win: [{ t: "print", text: "hello" }],
    },
    say(L(
      "Decorators can take arguments: @repeat(3) first CALLS repeat(3), which returns the real decorator. Three levels!",
      "Los decoradores aceptan argumentos: @repeat(3) primero LLAMA a repeat(3), que devuelve el decorador real. ¡Tres niveles!",
      "引数つきデコレータ：@repeat(3) はまず repeat(3) を呼び、本物のデコレータを受け取る。3段構えだよ！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def repeat(n):", "    def deco(fn):", "        def wrapper():", "            return [fn() for _ in range(n)]", "        return wrapper", "    return deco", "@repeat(3)", "def roll():", "    return 6", "print(roll())"),
      options: ["[6, 6, 6]", "6", "18"],
      answer: 0,
      output: "[6, 6, 6]",
      check: { compiles: true, stdout: "[6, 6, 6]" },
      explain: L("repeat(3) returns deco; deco wraps roll; the wrapper calls roll 3 times.", "repeat(3) devuelve deco; deco envuelve roll; el wrapper llama a roll 3 veces.", "repeat(3) が deco を返し、deco が roll を包み、wrapper が roll を3回呼ぶ。"),
      win: [{ t: "print", text: "[6, 6, 6]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def a(fn):", '    return lambda: "a(" + fn() + ")"', "def b(fn):", '    return lambda: "b(" + fn() + ")"', "@a", "@b", "def f():", '    return "f"', "print(f())"),
      options: ["a(b(f))", "b(a(f))", "a(f)"],
      answer: 0,
      output: "a(b(f))",
      check: { compiles: true, stdout: "a(b(f))" },
      explain: L("Stacked decorators apply bottom-up: f = a(b(f)). The top one is the outer shield.", "Los decoradores apilados se aplican de abajo hacia arriba: f = a(b(f)). El de arriba es el escudo externo.", "重ねたデコレータは下から順に適用：f = a(b(f))。一番上が外側の盾だよ。"),
      win: [{ t: "print", text: "a(b(f))" }],
    },
    say(L(
      "functools.lru_cache is a ready-made decorator: it remembers results, so repeated calls skip the work.",
      "functools.lru_cache es un decorador listo: recuerda resultados, así las llamadas repetidas se ahorran el trabajo.",
      "functools.lru_cache は既製のデコレータ。結果を覚えるので、同じ呼び出しは計算をスキップするよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("from functools import lru_cache", "calls = 0", "@lru_cache(maxsize=None)", "def fib(n):", "    global calls", "    calls += 1", "    return n if n < 2 else fib(n - 1) + fib(n - 2)", "print(fib(30), calls)"),
      options: ["832040 31", "832040 1664079", "832040 30"],
      answer: 0,
      output: "832040 31",
      check: { compiles: true, stdout: "832040 31" },
      explain: L(
        "Each n from 0 to 30 is computed once: 31 real calls. Without the cache it would be over a million.",
        "Cada n de 0 a 30 se calcula una vez: 31 llamadas reales. Sin la caché serían más de un millón.",
        "0 から 30 までの n を1回ずつ計算して31回。キャッシュなしなら100万回以上だよ。",
      ),
      win: [{ t: "print", text: "832040 31" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "run",
      prompt: L("Fix the wrapper: it must print power: 10", "Arregla el wrapper: debe imprimir power: 10", "wrapper を直して power: 10 と表示しよう"),
      starter: code("def double_result(fn):", "    def wrapper(*args):", "        fn(*args) * 2", "    return wrapper", "", "@double_result", "def power(x):", "    return x + 1", "", 'print("power:", power(4))', ""),
      solution: code("def double_result(fn):", "    def wrapper(*args):", "        return fn(*args) * 2", "    return wrapper", "", "@double_result", "def power(x):", "    return x + 1", "", 'print("power:", power(4))', ""),
      expect: "power: 10",
      fallback: [String.raw`return\s+fn\(\*args\)\s*\*\s*2`, String.raw`return\s+2\s*\*\s*fn\(\*args\)`],
      explain: L(
        "The wrapper computes the value but never returns it, so the call gives None. Add return.",
        "El wrapper calcula el valor pero nunca lo devuelve, así que la llamada da None. Agrega return.",
        "wrapper は計算するけど返していないので None になる。return を足そう。",
      ),
    },
  ],
};

// ─── 3.4 Traps and nets: exceptions ─────────────────────────────────────────
const exceptions: LessonDef = {
  slug: "exceptions",
  title: L("Traps and nets", "Trampas y redes", "ワナとネット"),
  concept: "exceptions",
  mode: "lesson",
  xp: 75,
  enemy: "python/keyerror-key",
  enemyName: L("TRAP KEY", "LLAVE TRAMPA", "ワナのカギ"),
  beats: [
    say(L(
      "When something goes wrong, Python RAISES an exception. Uncaught, it stops the program. try/except is a net.",
      "Cuando algo sale mal, Python LANZA una excepción. Si nadie la atrapa, detiene el programa. try/except es una red.",
      "何かがおかしいと Python は例外を「投げる」。捕まえないとプログラムが止まる。try/except はネットだよ。",
    )),
    {
      kind: "act",
      prompt: L("Spring the trap, then catch it", "Activa la trampa y luego atrápala", "ワナを作動させて、つかまえよう"),
      steps: [
        {
          label: L("DIVIDE", "DIVIDIR", "割る"),
          line: "print(10 / 0)",
          effects: [{ t: "shake" }, { t: "banner", text: L("ZeroDivisionError", "ZeroDivisionError", "0で割った！") }],
          error: {
            compiler: "ZeroDivisionError: division by zero",
            plain: L("Dividing by zero raised an exception, and nobody caught it: the program stopped.", "Dividir entre cero lanzó una excepción y nadie la atrapó: el programa se detuvo.", "0 で割って例外が発生。だれも捕まえないのでプログラムが止まった。"),
          },
        },
        { label: L("TRY", "TRY", "try"), line: "try:", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "shield", holder: "ally" }] },
        { label: L("DIVIDE AGAIN", "DIVIDIR OTRA VEZ", "もう一度割る"), line: "    print(10 / 0)", effects: [{ t: "shake" }] },
        { label: L("EXCEPT", "EXCEPT", "except"), line: "except ZeroDivisionError:", effects: [{ t: "say", actor: "ally", text: L("Got it!", "¡Atrapada!", "キャッチ！") }] },
        { label: L("HANDLE", "MANEJAR", "対処する"), line: '    print("caught")', output: "caught", effects: [{ t: "print", text: "caught" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("try:", "    print(1 / 0)", "except ZeroDivisionError:", '    print("caught")', 'print("still alive")'),
      options: ["caught still alive", "caught", "ZeroDivisionError"],
      answer: 0,
      output: "caught\nstill alive",
      check: { compiles: true, stdout: "caught\nstill alive" },
      explain: L("The net catches the exception, the handler runs, and the program carries on.", "La red atrapa la excepción, corre el manejador y el programa sigue.", "ネットが例外を捕まえ、対処のコードが動き、プログラムは続くよ。"),
      win: [{ t: "print", text: "caught" }, { t: "print", text: "still alive" }],
    },
    say(L(
      "else runs only if NO exception happened. finally ALWAYS runs at the end, error or not, even after return.",
      "else corre solo si NO hubo excepción. finally SIEMPRE corre al final, con error o sin él, incluso tras un return.",
      "else は例外が「なかった」ときだけ。finally はエラーがあってもなくても、return の後でも必ず動くよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("try:", '    x = int("7")', "except ValueError:", '    print("bad")', "else:", '    print("ok", x)', "finally:", '    print("done")'),
      options: ["ok 7 done", "bad done", "ok 7"],
      answer: 0,
      output: "ok 7\ndone",
      check: { compiles: true, stdout: "ok 7\ndone" },
      explain: L("int(\"7\") works, so except is skipped, else runs, and finally runs last.", "int(\"7\") funciona, así que se salta except, corre else y finally al final.", "int(\"7\") は成功。except は飛ばし、else が動き、最後に finally。"),
      win: [{ t: "print", text: "ok 7" }, { t: "print", text: "done" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def f():", "    try:", '        return "try"', "    finally:", '        print("finally")', "print(f())"),
      options: ["finally try", "try finally", "try"],
      answer: 0,
      output: "finally\ntry",
      check: { compiles: true, stdout: "finally\ntry" },
      explain: L(
        "return \"try\" is ready, but finally runs before the function leaves. Then print shows try.",
        "return \"try\" está listo, pero finally corre antes de salir de la función. Luego print muestra try.",
        "return \"try\" の準備ができても、関数を出る前に finally が動く。その後 try が表示されるよ。",
      ),
      win: [{ t: "print", text: "finally" }, { t: "print", text: "try" }],
    },
    {
      kind: "order",
      prompt: L("Build the full net", "Arma la red completa", "ネットを組み立てよう"),
      lines: ["try:", '    n = int("5")', "except ValueError:", '    print("bad")', "else:", '    print("ok", n)'],
      check: { compiles: true, stdout: "ok 5" },
      explain: L("try first, then except, then else. else must come after every except.", "Primero try, luego except, luego else. else va después de todos los except.", "try、except、else の順。else はすべての except の後に置くよ。"),
      win: [{ t: "print", text: "ok 5" }],
    },
    say(L(
      "Catch several kinds with a tuple, and name the exception with as e. KeyError and IndexError are both LookupError.",
      "Atrapa varios tipos con una tupla y nombra la excepción con as e. KeyError e IndexError son ambas LookupError.",
      "タプルで何種類も捕まえ、as e で名前をつけられる。KeyError も IndexError も LookupError の仲間だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("try:", "    [][0]", "except (KeyError, IndexError) as e:", "    print(type(e).__name__)"),
      options: ["IndexError", "KeyError", "LookupError"],
      answer: 0,
      output: "IndexError",
      check: { compiles: true, stdout: "IndexError" },
      explain: L("An empty list has no index 0: IndexError. The tuple net catches either kind.", "Una lista vacía no tiene índice 0: IndexError. La red con tupla atrapa cualquiera de los dos.", "空リストに 0 番はないので IndexError。タプルのネットはどちらも捕まえる。"),
      win: [{ t: "print", text: "IndexError" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("try:", '    {}["x"]', "except LookupError:", '    print("lookup")'),
      options: ["lookup", "KeyError", L("Nothing", "Nada", "何も出ない")],
      answer: 0,
      output: "lookup",
      check: { compiles: true, stdout: "lookup" },
      explain: L("A missing key raises KeyError, a child of LookupError, so the parent's net catches it.", "Una clave que falta lanza KeyError, hija de LookupError, así que la red del padre la atrapa.", "ないキーは KeyError。LookupError の子なので、親のネットで捕まるよ。"),
      win: [{ t: "print", text: "lookup" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    say(L(
      "raise throws your own. class OutOfMana(Exception): pass makes a new kind of exception with a clear name.",
      "raise lanza la tuya. class OutOfMana(Exception): pass crea un tipo nuevo de excepción con un nombre claro.",
      "raise で自分から投げられる。class OutOfMana(Exception): pass で分かりやすい名前の例外を作れるよ。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("def cast(mp):", "    if mp < 5:", '        raise ValueError("low mana")', '    return "boom"', "print(cast(1))"),
      options: ["ValueError", "None", "boom"],
      answer: 0,
      check: { compiles: true, throws: "ValueError" },
      explain: L("mp is 1, so raise fires. Nothing catches the ValueError, so the program stops.", "mp vale 1, así que raise se dispara. Nadie atrapa el ValueError y el programa se detiene.", "mp は 1 なので raise が発動。だれも ValueError を捕まえないので止まるよ。"),
      win: [{ t: "shake" }, { t: "banner", text: L("ValueError", "ValueError", "ValueError") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class OutOfMana(Exception):", "    pass", "try:", '    raise OutOfMana("need 5")', "except Exception as e:", "    print(type(e).__name__, e)"),
      options: ["OutOfMana need 5", "Exception need 5", "need 5"],
      answer: 0,
      output: "OutOfMana need 5",
      check: { compiles: true, stdout: "OutOfMana need 5" },
      explain: L("OutOfMana is a kind of Exception, so that net catches it. Printing e shows its message.", "OutOfMana es un tipo de Exception, así que esa red la atrapa. Imprimir e muestra su mensaje.", "OutOfMana は Exception の一種なので捕まる。e を表示するとメッセージが出るよ。"),
      win: [{ t: "print", text: "OutOfMana need 5" }],
    },
    {
      kind: "run",
      prompt: L("Skip bad text: it must print total: 7", "Salta el texto malo: debe imprimir total: 7", "変な文字は飛ばして total: 7 と表示しよう"),
      starter: code("def parse(text):", "    return int(text)", "", "total = 0", 'for t in ["3", "x", "4"]:', "    total += parse(t)", 'print("total:", total)', ""),
      solution: code("def parse(text):", "    try:", "        return int(text)", "    except ValueError:", "        return 0", "", "total = 0", 'for t in ["3", "x", "4"]:', "    total += parse(t)", 'print("total:", total)', ""),
      expect: "total: 7",
      fallback: [String.raw`try:[\s\S]*except\s*(\(?\s*ValueError|Exception|:)`, String.raw`isdigit\(\)`],
      explain: L(
        "int(\"x\") raises ValueError. Wrap it in try and return 0 in except ValueError.",
        "int(\"x\") lanza ValueError. Envuélvelo en try y devuelve 0 en except ValueError.",
        "int(\"x\") は ValueError を投げる。try で包んで、except ValueError で 0 を返そう。",
      ),
    },
  ],
};

// ─── 3.5 Boss: the closure wyvern ───────────────────────────────────────────
const boss: LessonDef = {
  slug: "closure-wyvern",
  title: L("The closure wyvern", "El guiverno closure", "クロージャの翼竜"),
  concept: "scope_closures",
  mode: "boss",
  xp: 180,
  enemy: "dragon",
  enemyName: L("CLOSURE WYVERN", "GUIVERNO CLOSURE", "クロージャ翼竜"),
  beats: [
    enemySays(L(
      "I AM THE CLOSURE WYVERN. I keep stale lists in my claws and old loop values in my backpack. Read carefully!",
      "SOY EL GUIVERNO CLOSURE. Guardo listas viejas en mis garras y valores de bucle en mi mochila. ¡Lee con cuidado!",
      "我はクロージャ翼竜。爪には古いリスト、リュックにはループの値。よく読むがいい！",
    )),
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("def f(x, items=[]):", "    items.append(x)", "    return len(items)", "print(f(1), f(2), f(3, []))"),
      options: ["1 2 1", "1 1 1", "1 2 3"], answer: 0, output: "1 2 1",
      check: { compiles: true, stdout: "1 2 1" },
      explain: L("The default list is shared: 1, then 2. f(3, []) gets its own new list: 1.", "La lista por defecto se comparte: 1 y luego 2. f(3, []) recibe su propia lista: 1.", "デフォルトのリストは共有で 1、2。f(3, []) は自分のリストなので 1。"),
    },
    {
      kind: "predict", time: 12, prompt: PRINT,
      code: code("def f(*args):", "    return type(args).__name__", "print(f(1, 2))"),
      options: ["tuple", "list", "int"], answer: 0, output: "tuple",
      check: { compiles: true, stdout: "tuple" },
      explain: L("*args always packs the extra positional arguments into a tuple.", "*args siempre empaca los argumentos posicionales extra en una tupla.", "*args は余った位置引数をいつもタプルにまとめる。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print((lambda *a, **k: (len(a), sorted(k)))(1, 2, b=1, a=2))",
      options: ["(2, ['a', 'b'])", "(4, ['a', 'b'])", "(2, ['b', 'a'])"], answer: 0, output: "(2, ['a', 'b'])",
      check: { compiles: true, stdout: "(2, ['a', 'b'])" },
      explain: L("Two positional arguments go to a. sorted(k) sorts the dict's keys: a, b.", "Dos argumentos posicionales van a a. sorted(k) ordena las claves del dict: a, b.", "位置引数2つが a へ。sorted(k) は辞書のキーを並べる：a、b。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("def outer():", "    n = 0", "    def inner():", "        nonlocal n", "        n += 1", "        return n", "    inner()", "    return inner()", "print(outer())"),
      options: ["2", "1", "0"], answer: 0, output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("Both calls update the same n through nonlocal: 1, then 2.", "Ambas llamadas actualizan la misma n con nonlocal: 1 y luego 2.", "2回とも nonlocal で同じ n を更新：1、2。"),
    },
    {
      kind: "pick", time: 15, prompt: L("Change the outer hp", "Cambia el hp de afuera", "外側の hp を変えよう"),
      code: code("def outer():", "    hp = 3", "    def hit():", "        ___ hp", "        hp -= 1", "    hit()", "    return hp", "print(outer())"),
      options: ["nonlocal", "global"], answer: 0,
      check: { compiles: true, stdout: "2" },
      explain: L("hp lives in the enclosing function, not the module: nonlocal. global would find no hp.", "hp vive en la función de afuera, no en el módulo: nonlocal. global no encontraría ningún hp.", "hp は外側の関数にある。モジュールではないので nonlocal。global だと hp がない。"),
    },
    {
      kind: "predict", time: 12, prompt: PRINT,
      code: code("fns = []", "for i in range(3):", "    fns.append(lambda: i * 10)", "print(fns[0]())"),
      options: ["20", "0", "30"], answer: 0, output: "20",
      check: { compiles: true, stdout: "20" },
      explain: L("Late binding: the lambda reads i when called, after the loop, when i is 2.", "Enlace tardío: la lambda lee i al llamarse, tras el bucle, cuando i vale 2.", "遅延束縛：lambda は呼ばれた時に i を読む。ループ後なので i は 2。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("from functools import lru_cache", "@lru_cache(maxsize=None)", "def sq(x):", '    print("calc", x)', "    return x * x", "sq(3)", "sq(3)", "print(sq(4))"),
      options: ["calc 3 calc 4 16", "calc 3 calc 3 calc 4 16", "16"], answer: 0, output: "calc 3\ncalc 4\n16",
      check: { compiles: true, stdout: "calc 3\ncalc 4\n16" },
      explain: L("The second sq(3) comes from the cache, so its body does not run again.", "El segundo sq(3) sale de la caché, así que su cuerpo no vuelve a correr.", "2回目の sq(3) はキャッシュから。本体はもう動かない。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("def f():", "    try:", '        return int("x")', "    except ValueError:", "        return -1", "    finally:", '        print("net")', "print(f())"),
      options: ["net -1", "-1 net", "ValueError"], answer: 0, output: "net\n-1",
      check: { compiles: true, stdout: "net\n-1" },
      explain: L("except catches the ValueError and returns -1, but finally prints first.", "except atrapa el ValueError y devuelve -1, pero finally imprime primero.", "except が捕まえて -1 を返すけど、先に finally が表示する。"),
    },
    {
      kind: "predict", time: 12, prompt: HAPPENS,
      code: code("try:", "    [1, 2][5]", "except KeyError:", '    print("caught")'),
      options: ["IndexError", "caught", "KeyError"], answer: 0,
      check: { compiles: true, throws: "IndexError" },
      explain: L("A bad list index is IndexError. A KeyError net does not catch it.", "Un índice de lista malo es IndexError. Una red de KeyError no lo atrapa.", "リストの番号ちがいは IndexError。KeyError のネットでは捕まらない。"),
    },
    {
      kind: "order", time: 20, prompt: L("Build a shouting decorator", "Arma un decorador que grita", "大声デコレータを作ろう"),
      lines: ["def shout(fn):", "    def wrapper(name):", "        return fn(name).upper()", "    return wrapper", "@shout", "def greet(name):", '    return "hi " + name', 'print(greet("bo"))'],
      check: { compiles: true, stdout: "HI BO" },
      explain: L("Define the decorator, return the wrapper, then put @shout right above def.", "Define el decorador, devuelve el wrapper y pon @shout justo encima de def.", "デコレータを書き、wrapper を返し、def の真上に @shout。"),
    },
    enemySays(L(
      "Grr... no stale list fooled you, no loop variable escaped you. The Object Tower awaits above the clouds.",
      "Grr... ninguna lista vieja te engañó, ninguna variable de bucle se te escapó. La Torre de Objetos te espera.",
      "ぐぬぬ…古いリストにもループ変数にもだまされぬか。雲の上でオブジェクトの塔が待っているぞ。",
    )),
  ],
};

export const functionPeaks: RegionDef = {
  slug: "function-peaks",
  name: L("Function Peaks", "Picos de Funciones", "関数の峰"),
  subtitle: L("Functions · scope · decorators · errors", "Funciones · scope · decoradores · fallos", "関数・スコープ・デコレータ・例外"),
  theme: "mountain",
  lessons: [functions, scope, decorators, exceptions, boss],
};
