import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 1 · NAME VILLAGE  (names and values, numbers, strings, truthiness, == vs is)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");

// ─── 1.1 Labels and chips ──────────────────────────────────────────────────
const names: LessonDef = {
  slug: "names-and-values",
  title: L("Labels and chips", "Etiquetas y fichas", "ラベルとチップ"),
  concept: "values",
  mode: "lesson",
  xp: 60,
  enemy: "python/indent-gremlin",
  enemyName: L("INDENT GREMLIN", "GREMLIN SANGRÍA", "インデントグレムリン"),
  beats: [
    say(L(
      "Welcome to Name Village! In Python, hp = 10 sticks a NAME, like a label, on the value 10.",
      "¡Bienvenido a la Aldea de los Nombres! En Python, hp = 10 pega un NOMBRE, como una etiqueta, en el valor 10.",
      "名前の村へようこそ！Python の hp = 10 は、値 10 に「名前」というラベルを貼ることだよ。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and watch the labels", "Pulsa en orden y mira las etiquetas", "順番に押して、ラベルを見てね"),
      steps: [
        { label: L("LABEL hp", "ETIQUETA hp", "hp を貼る"), line: "hp = 10", effects: [{ t: "tag", actor: "hero", text: "hp", value: "10" }] },
        { label: L("HEAL", "CURAR", "回復"), line: "hp = hp + 5", effects: [{ t: "value", actor: "hero", text: "15" }, { t: "say", actor: "hero", text: L("New chip: 15!", "¡Ficha nueva: 15!", "新チップ 15！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "print(hp)", effects: [{ t: "print", text: "15" }], output: "15" },
        { label: L("LABEL x", "ETIQUETA x", "x を貼る"), line: "x = 5", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "x", value: "5" }] },
        { label: L("NOW TEXT", "AHORA TEXTO", "文字列に"), line: 'x = "five"', effects: [{ t: "value", actor: "ally", text: "'five'" }, { t: "say", actor: "ally", text: L("Still x!", "¡Sigo siendo x!", "まだ x だよ！") }] },
        {
          label: L("PRINT potion", "IMPRIMIR potion", "potion 表示"),
          line: "print(potion)",
          effects: [{ t: "shake" }, { t: "banner", text: L("NameError", "NameError", "NameError") }],
          error: {
            compiler: "NameError: name 'potion' is not defined",
            plain: L("No label called potion exists yet, so Python can't find it.", "Todavía no existe ninguna etiqueta llamada potion, así que Python no la encuentra.", "potion というラベルはまだないから、Python は見つけられないよ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "hp = 10\nhp = hp + 5\nprint(hp)",
      options: ["15", "10", "105"],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("hp + 5 makes a new value 15, and the label hp moves onto it.", "hp + 5 crea un valor nuevo, 15, y la etiqueta hp pasa a él.", "hp + 5 で新しい値 15 ができて、ラベル hp がそちらに移るよ。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "10" }],
      win: [{ t: "value", actor: "hero", text: "15" }, { t: "print", text: "15" }],
    },
    say(L(
      "In Python the VALUE has a type, not the name. One label can sit on a number, then on text. type() tells you which.",
      "En Python el VALOR tiene tipo, no el nombre. Una etiqueta puede estar en un número y luego en texto. type() te lo dice.",
      "Python で型を持つのは名前じゃなく「値」。同じラベルを数値にも文字列にも貼れる。type() で調べよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'x = 5\nx = "five"\nprint(type(x).__name__)',
      options: ["str", "int", "five"],
      answer: 0,
      output: "str",
      check: { compiles: true, stdout: "str" },
      explain: L("The label x now sits on the text \"five\", a str. The old 5 doesn't matter anymore.", "La etiqueta x ahora está en el texto \"five\", un str. El 5 anterior ya no importa.", "x はいま文字列 \"five\"（str）に貼られている。前の 5 はもう関係ないよ。"),
      setup: [{ t: "tag", actor: "hero", text: "x", value: "5" }],
      win: [{ t: "value", actor: "hero", text: "'five'" }, { t: "print", text: "str" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print(type(3).__name__, type(3.0).__name__, type("3").__name__, type(True).__name__)',
      options: ["int float str bool", "int int str bool", "number number text bool"],
      answer: 0,
      output: "int float str bool",
      check: { compiles: true, stdout: "int float str bool" },
      explain: L("3 is an int (whole number), 3.0 a float (decimal), \"3\" a str (text), True a bool.", "3 es int (entero), 3.0 es float (decimal), \"3\" es str (texto) y True es bool.", "3 は int（整数）、3.0 は float（小数）、\"3\" は str（文字列）、True は bool だよ。"),
    },
    say(L(
      "b = a puts a second label on the same value. Moving a later doesn't drag b along.",
      "b = a pone una segunda etiqueta en el mismo valor. Mover a después no arrastra a b.",
      "b = a は同じ値に2枚目のラベルを貼る。あとで a を貼りかえても b はついてこないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = 1\nb = a\na = 2\nprint(a, b)",
      options: ["2 1", "2 2", "1 1"],
      answer: 0,
      output: "2 1",
      check: { compiles: true, stdout: "2 1" },
      explain: L("a = 2 only moves the label a. b still sits on 1. print separates values with a space.", "a = 2 solo mueve la etiqueta a. b sigue en 1. print separa los valores con un espacio.", "a = 2 で動くのはラベル a だけ。b は 1 のまま。print は値を空白で区切るよ。"),
      setup: [{ t: "tag", actor: "hero", text: "a", value: "1" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b", value: "1" }],
      win: [{ t: "value", actor: "hero", text: "2" }, { t: "print", text: "2 1" }],
    },
    {
      kind: "type",
      prompt: L("Swap the two labels in one line", "Intercambia las dos etiquetas en una línea", "1行で2つのラベルを入れかえよう"),
      code: "a, b = 1, 2\na, b = ___\nprint(a, b)",
      answer: "b, a",
      check: { compiles: true, stdout: "2 1" },
      explain: L("The right side is built first as (2, 1), then unpacked into a and b. No temp needed.", "Primero se arma el lado derecho como (2, 1) y luego se desempaca en a y b. Sin variable extra.", "右側が先に (2, 1) になり、a と b に分けて入る。一時変数はいらないよ。"),
      win: [{ t: "print", text: "2 1" }],
    },
    say(L(
      "Python never mixes text and numbers on its own. \"3\" + 3 crashes. Convert first with int() or str().",
      "Python nunca mezcla texto y números por su cuenta. \"3\" + 3 falla. Convierte antes con int() o str().",
      "Python は文字列と数値を勝手にまぜない。\"3\" + 3 はエラー。先に int() か str() で変換しよう。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'print("3" + 3)',
      options: ["TypeError", "6", "33"],
      answer: 0,
      check: { compiles: true, throws: "TypeError" },
      explain: L("str + int is not allowed: TypeError: can only concatenate str (not \"int\") to str.", "str + int no está permitido: TypeError: can only concatenate str (not \"int\") to str.", "str + int はできない。TypeError: can only concatenate str (not \"int\") to str だよ。"),
      win: [{ t: "shake" }, { t: "banner", text: L("TypeError", "TypeError", "TypeError") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print(int("3") + 3, "3" * 3)',
      options: ["6 333", "6 9", "33 333"],
      answer: 0,
      output: "6 333",
      check: { compiles: true, stdout: "6 333" },
      explain: L("int(\"3\") is the number 3, so 3 + 3 is 6. A str times an int repeats the text.", "int(\"3\") es el número 3, así que 3 + 3 es 6. Un str por un int repite el texto.", "int(\"3\") は数値 3 なので 3 + 3 は 6。str × int は文字列のくり返しだよ。"),
    },
    {
      kind: "predict",
      prompt: L("None means 'no value'. What does it print?", "None significa 'sin valor'. ¿Qué imprime?", "None は「値なし」。何が表示される？"),
      code: "x = None\nprint(x, type(x).__name__)",
      options: ["None NoneType", "None None", "0 int"],
      answer: 0,
      output: "None NoneType",
      check: { compiles: true, stdout: "None NoneType" },
      explain: L("None is Python's 'nothing here' value. It has its own type: NoneType.", "None es el valor 'aquí no hay nada' de Python. Tiene su propio tipo: NoneType.", "None は Python の「何もない」値。専用の型 NoneType を持っているよ。"),
      setup: [{ t: "tag", actor: "hero", text: "x" }],
      win: [{ t: "value", actor: "hero", text: "None" }, { t: "say", actor: "enemy", text: L("Nothing? Boo!", "¿Nada? ¡Bu!", "なにもない？") }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print total: 15", "Arréglalo: debe imprimir total: 15", "直そう：total: 15 と表示させて"),
      starter: 'gold = "10"\ntotal = gold + 5\nprint("total:", total)\n',
      solution: 'gold = "10"\ntotal = int(gold) + 5\nprint("total:", total)\n',
      expect: "total: 15",
      fallback: [String.raw`int\(\s*gold\s*\)\s*\+\s*5`, String.raw`gold\s*=\s*10\b`],
      explain: L("gold holds the text \"10\". int(gold) turns it into the number 10, then + 5 works.", "gold guarda el texto \"10\". int(gold) lo vuelve el número 10 y entonces + 5 funciona.", "gold は文字列 \"10\"。int(gold) で数値 10 にすれば + 5 ができるよ。"),
    },
  ],
};

// ─── 1.2 Coins and scrolls ─────────────────────────────────────────────────
const numbers: LessonDef = {
  slug: "numbers-and-strings",
  title: L("Coins and scrolls", "Monedas y pergaminos", "コインと巻物"),
  concept: "values",
  mode: "lesson",
  xp: 65,
  enemy: "slime",
  enemyName: L("COIN SLIME", "LIMO MONEDA", "コインスライム"),
  beats: [
    say(L(
      "Numbers come in two kinds: int for whole numbers and float for decimals. Let's split 7 coins between 2 heroes.",
      "Hay dos tipos de números: int para enteros y float para decimales. Repartamos 7 monedas entre 2 héroes.",
      "数値は2種類。整数の int と小数の float。7枚のコインを2人で分けてみよう。",
    )),
    {
      kind: "act",
      prompt: L("Split the coins and watch the chips", "Reparte las monedas y mira las fichas", "コインを分けて、チップを見てね"),
      steps: [
        { label: L("7 COINS", "7 MONEDAS", "コイン7枚"), line: "coins = 7", effects: [{ t: "tag", actor: "hero", text: "coins", value: "7" }, { t: "enter", actor: "ally" }] },
        { label: L("DIVIDE /", "DIVIDIR /", "/ で割る"), line: "print(coins / 2)", effects: [{ t: "print", text: "3.5" }, { t: "say", actor: "ally", text: L("Half a coin?!", "¿¡Media moneda!?", "半分のコイン？") }], output: "3.5" },
        { label: L("FLOOR //", "ENTERA //", "// で割る"), line: "print(coins // 2)", effects: [{ t: "print", text: "3" }, { t: "give", to: "ally" }], output: "3" },
        { label: L("LEFTOVER %", "SOBRA %", "% で余り"), line: "print(coins % 2)", effects: [{ t: "print", text: "1" }, { t: "drop" }], output: "1" },
        { label: L("SCROLL s", "PERGAMINO s", "巻物 s"), line: 's = "hero"', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "s", value: "'hero'" }] },
        {
          label: L("REWRITE s[0]", "REESCRIBIR s[0]", "s[0] を変更"),
          line: 's[0] = "H"',
          effects: [{ t: "shake" }, { t: "banner", text: L("TypeError", "TypeError", "TypeError") }],
          error: {
            compiler: "TypeError: 'str' object does not support item assignment",
            plain: L("Strings are immutable: you can read letters, never rewrite them in place.", "Los strings son inmutables: puedes leer letras, nunca reescribirlas en su lugar.", "文字列は変更不可。文字を読めても、その場で書きかえはできないよ。"),
          },
        },
      ],
    },
    say(L(
      "/ always gives a float. // divides and rounds DOWN. % is what's left over. ** is power.",
      "/ siempre da un float. // divide y redondea HACIA ABAJO. % es lo que sobra. ** es potencia.",
      "/ はいつも float。// は割って「切り捨て」。% は余り。** はべき乗だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(7 / 2, 7 // 2, 7 % 2)",
      options: ["3.5 3 1", "3 3 1", "3.5 3.5 1"],
      answer: 0,
      output: "3.5 3 1",
      check: { compiles: true, stdout: "3.5 3 1" },
      explain: L("7 / 2 is 3.5, 7 // 2 floors to 3, and 7 % 2 leaves 1.", "7 / 2 es 3.5, 7 // 2 redondea abajo a 3 y 7 % 2 deja 1.", "7 / 2 は 3.5、7 // 2 は切り捨てて 3、7 % 2 の余りは 1。"),
      win: [{ t: "print", text: "3.5 3 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(2 ** 10, 10 / 5)",
      options: ["1024 2.0", "20 2", "1024 2"],
      answer: 0,
      output: "1024 2.0",
      check: { compiles: true, stdout: "1024 2.0" },
      explain: L("2 ** 10 is 2 to the 10th power. / gives a float even when it divides evenly: 2.0.", "2 ** 10 es 2 a la décima potencia. / da float aunque la división sea exacta: 2.0.", "2 ** 10 は2の10乗。/ は割り切れても float で 2.0 になるよ。"),
    },
    {
      kind: "predict",
      prompt: L("Negative coins! What does it print?", "¡Monedas negativas! ¿Qué imprime?", "マイナスのコイン！何が表示される？"),
      code: "print(-7 // 2, -7 % 2)",
      options: ["-4 1", "-3 -1", "-3 1"],
      answer: 0,
      output: "-4 1",
      check: { compiles: true, stdout: "-4 1" },
      explain: L("// rounds toward minus infinity: -3.5 becomes -4. Then % is 1, since -4 * 2 + 1 is -7.", "// redondea hacia menos infinito: -3.5 pasa a -4. Luego % es 1, porque -4 * 2 + 1 es -7.", "// はマイナス無限大の方向に丸める。-3.5 は -4。-4 * 2 + 1 = -7 なので % は 1。"),
    },
    say(L(
      "Floats are stored in binary, so 0.1 + 0.2 is a hair off 0.3. Compare decimals with math.isclose().",
      "Los floats se guardan en binario, así que 0.1 + 0.2 queda a un pelo de 0.3. Compara decimales con math.isclose().",
      "float は二進数で保存されるから 0.1 + 0.2 は 0.3 から少しずれる。小数は math.isclose() で比べよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(0.1 + 0.2 == 0.3)",
      options: ["False", "True"],
      answer: 0,
      output: "False",
      check: { compiles: true, stdout: "False" },
      explain: L("0.1 + 0.2 is really 0.30000000000000004, so == says False.", "0.1 + 0.2 en realidad es 0.30000000000000004, así que == dice False.", "0.1 + 0.2 の実際の値は 0.30000000000000004。だから == は False。"),
    },
    {
      kind: "pick",
      prompt: L("Compare the decimals safely", "Compara los decimales con seguridad", "小数を安全に比べよう"),
      code: "import math\nprint(math.___(0.1 + 0.2, 0.3))",
      options: ["isclose", "isequal", "round"],
      answer: 0,
      check: { compiles: true, stdout: "True" },
      explain: L("math.isclose checks the numbers are almost equal. math has no isequal, and round needs one number.", "math.isclose verifica que los números sean casi iguales. math no tiene isequal, y round recibe un solo número.", "math.isclose は「ほぼ等しいか」を調べる。isequal は存在せず、round は数値1つ用だよ。"),
      win: [{ t: "print", text: "True" }],
    },
    say(L(
      "A string is a row of letters. s[0] is the first, s[-1] the last, and s[1:4] slices from 1 up to, not including, 4.",
      "Un string es una fila de letras. s[0] es la primera, s[-1] la última y s[1:4] corta desde 1 hasta 4, sin incluirlo.",
      "文字列は文字の並び。s[0] が最初、s[-1] が最後、s[1:4] は1から4の手前まで切り出すよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 's = "python"\nprint(s[0], s[-1], s[1:4], s[::-1])',
      options: ["p n yth nohtyp", "p n pyt nohtyp", "y n yth python"],
      answer: 0,
      output: "p n yth nohtyp",
      check: { compiles: true, stdout: "p n yth nohtyp" },
      explain: L("s[1:4] takes indexes 1, 2, 3: yth. A step of -1 in s[::-1] walks backward: reversed.", "s[1:4] toma los índices 1, 2 y 3: yth. Un paso de -1 en s[::-1] recorre al revés.", "s[1:4] はインデックス 1, 2, 3 で yth。s[::-1] は -1 ずつ進むので逆順になるよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "s", value: "'python'" }],
    },
    {
      kind: "type",
      prompt: L("Make it an f-string", "Conviértelo en f-string", "f文字列にしよう"),
      code: 'name = "Ada"\nlvl = 3\nprint(___"{name} is level {lvl + 1}")',
      answer: "f",
      check: { compiles: true, stdout: "Ada is level 4" },
      explain: L("An f before the quotes runs the code inside {} and puts the result in the text.", "Una f antes de las comillas ejecuta el código dentro de {} y pone el resultado en el texto.", "引用符の前に f をつけると {} の中が計算され、結果が文字列に入るよ。"),
      win: [{ t: "print", text: "Ada is level 4" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print("a,b,c".split(","), "-".join(["x", "y"]), " hi ".strip().upper())',
      options: ["['a', 'b', 'c'] x-y HI", "abc x-y HI", "['a', 'b', 'c'] -xy  HI "],
      answer: 0,
      output: "['a', 'b', 'c'] x-y HI",
      check: { compiles: true, stdout: "['a', 'b', 'c'] x-y HI" },
      explain: L("split cuts text into a list, join glues a list with the separator, strip trims spaces.", "split corta el texto en una lista, join une una lista con el separador y strip quita espacios.", "split は文字列をリストに分け、join は区切りでつなぎ、strip は空白をとるよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(round(2.5), round(3.5))",
      options: ["2 4", "3 4", "2 3"],
      answer: 0,
      output: "2 4",
      check: { compiles: true, stdout: "2 4" },
      explain: L("round() sends exact halves to the nearest EVEN number: 2.5 → 2, 3.5 → 4.", "round() lleva las mitades exactas al número PAR más cercano: 2.5 → 2, 3.5 → 4.", "round() はちょうど半分のとき、近い「偶数」にする。2.5 → 2、3.5 → 4。"),
    },
    {
      kind: "run",
      prompt: L("Whole coins only! It must print: each gets 3 coins", "¡Solo monedas enteras! Debe imprimir: each gets 3 coins", "コインは整数で！each gets 3 coins と表示させて"),
      starter: 'coins = 7\nper_hero = coins / 2\nprint(f"each gets {per_hero} coins")\n',
      solution: 'coins = 7\nper_hero = coins // 2\nprint(f"each gets {per_hero} coins")\n',
      expect: "gets 3 coins",
      fallback: [String.raw`coins\s*//\s*2`, String.raw`int\(\s*coins\s*/\s*2\s*\)`],
      explain: L("/ gives 3.5. // divides and drops the fraction, so each hero gets 3.", "/ da 3.5. // divide y descarta la fracción, así que cada héroe recibe 3.", "/ だと 3.5。// なら小数部分を切り捨てて、1人 3 枚になるよ。"),
    },
  ],
};

// ─── 1.3 Equal or the same? ────────────────────────────────────────────────
const truth: LessonDef = {
  slug: "truth-and-identity",
  title: L("Equal or the same?", "¿Igual o el mismo?", "等しい？同じもの？"),
  concept: "truthiness",
  mode: "lesson",
  xp: 70,
  enemy: "python/none-ghost",
  enemyName: L("NONE GHOST", "FANTASMA NONE", "None ゴースト"),
  beats: [
    say(L(
      "if runs its indented block only when the condition is true. else runs otherwise. Indentation IS the block!",
      "if ejecuta su bloque indentado solo si la condición es verdadera. Si no, else. ¡La indentación ES el bloque!",
      "if は条件が真のときだけ、字下げしたブロックを実行。ちがえば else。インデントがブロックそのものだよ！",
    )),
    say(L(
      "Any value can be a condition. Empty things, 0 and None are FALSY. Everything else is TRUTHY, even \"0\".",
      "Cualquier valor puede ser condición. Lo vacío, 0 y None son FALSY. Todo lo demás es TRUTHY, incluso \"0\".",
      "どんな値も条件になれる。空のもの、0、None は「偽」あつかい。それ以外は \"0\" でも「真」だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print(bool(0), bool(""), bool([]), bool("0"), bool([0]))',
      options: ["False False False True True", "False False False False False", "False True False True True"],
      answer: 0,
      output: "False False False True True",
      check: { compiles: true, stdout: "False False False True True" },
      explain: L("0, \"\" and [] are empty or zero: falsy. \"0\" is a non-empty text and [0] a non-empty list: truthy.", "0, \"\" y [] son vacíos o cero: falsy. \"0\" es texto no vacío y [0] una lista no vacía: truthy.", "0、\"\"、[] は空かゼロなので偽。\"0\" も [0] も中身があるので真だよ。"),
    },
    say(L(
      "and / or don't return True or False: they return one of their values. x or 3 gives x if truthy, else 3.",
      "and / or no devuelven True o False: devuelven uno de sus valores. x or 3 da x si es truthy, si no 3.",
      "and / or は True/False じゃなく、どちらかの値を返す。x or 3 は x が真なら x、偽なら 3。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print(repr(0 or "default"), repr("" and "x"), 5 and 7)',
      options: ["'default' '' 7", "True False True", "'default' 'x' 5"],
      answer: 0,
      output: "'default' '' 7",
      check: { compiles: true, stdout: "'default' '' 7" },
      explain: L("or returns the first truthy value. and stops at the first falsy one, or returns the last.", "or devuelve el primer valor truthy. and se detiene en el primer falsy, o devuelve el último.", "or は最初の真の値を返す。and は最初の偽の値で止まり、なければ最後の値を返すよ。"),
    },
    {
      kind: "predict",
      prompt: L("0 lives is real. What does it print?", "0 vidas es real. ¿Qué imprime?", "残機 0 は本物。何が表示される？"),
      code: "lives = 0\nprint(lives or 3)",
      options: ["3", "0", "True"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("0 is falsy, so or falls back to 3. A classic trap when 0 is a valid value.", "0 es falsy, así que or usa el respaldo 3. Una trampa clásica cuando 0 es un valor válido.", "0 は偽なので or は 3 を返す。0 が正しい値のときの定番のワナだよ。"),
      setup: [{ t: "tag", actor: "hero", text: "lives", value: "0" }],
      win: [{ t: "print", text: "3" }, { t: "say", actor: "enemy", text: L("Your 0 vanished!", "¡Tu 0 desapareció!", "0 が消えた！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(1 < 2 < 3, 3 > 2 > 1, 1 < 3 > 2)",
      options: ["True True True", "True True False", "False False False"],
      answer: 0,
      output: "True True True",
      check: { compiles: true, stdout: "True True True" },
      explain: L("Comparisons chain: 1 < 3 > 2 means 1 < 3 and 3 > 2. Both hold.", "Las comparaciones se encadenan: 1 < 3 > 2 significa 1 < 3 and 3 > 2. Ambas se cumplen.", "比較はつなげられる。1 < 3 > 2 は 1 < 3 and 3 > 2 のこと。どちらも真だよ。"),
    },
    {
      kind: "act",
      prompt: L("Two scrolls with the same text. Watch!", "Dos pergaminos con el mismo texto. ¡Mira!", "同じ中身の巻物が2本。見てね！"),
      steps: [
        { label: L("SCROLL a", "PERGAMINO a", "巻物 a"), line: "a = [1, 2]", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "[1, 2]" }] },
        { label: L("SCROLL b", "PERGAMINO b", "巻物 b"), line: "b = [1, 2]", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "scroll", holder: "ally" }, { t: "tag", actor: "ally", text: "b", value: "[1, 2]" }] },
        { label: L("SAME TEXT?", "¿MISMO TEXTO?", "中身は同じ？"), line: "print(a == b)", effects: [{ t: "print", text: "True" }, { t: "say", actor: "hero", text: L("Same text!", "¡Mismo texto!", "中身は同じ！") }], output: "True" },
        { label: L("SAME ITEM?", "¿MISMO OBJETO?", "同じもの？"), line: "print(a is b)", effects: [{ t: "print", text: "False" }, { t: "say", actor: "ally", text: L("Two scrolls!", "¡Dos pergaminos!", "巻物は2本！") }], output: "False" },
        { label: L("c = a", "c = a", "c = a"), line: "c = a", effects: [{ t: "say", actor: "hero", text: L("c is MY scroll", "c es MI pergamino", "c は私の巻物") }] },
        { label: L("a is c?", "¿a is c?", "a is c？"), line: "print(a is c)", effects: [{ t: "print", text: "True" }], output: "True" },
      ],
    },
    say(L(
      "== asks 'same value?'. is asks 'the very same object?'. Use is for None: if x is None.",
      "== pregunta '¿mismo valor?'. is pregunta '¿el mismísimo objeto?'. Usa is con None: if x is None.",
      "== は「値が同じ？」、is は「まったく同じもの？」。None には is を使おう：if x is None。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "a = [1, 2]\nb = [1, 2]\nc = a\nprint(a == b, a is b, a is c)",
      options: ["True False True", "True True True", "False False True"],
      answer: 0,
      output: "True False True",
      check: { compiles: true, stdout: "True False True" },
      explain: L("a and b hold equal lists, but two separate ones. c = a is a second label on a's list.", "a y b tienen listas iguales, pero son dos distintas. c = a es una segunda etiqueta en la lista de a.", "a と b は中身が同じ別々のリスト。c = a は a のリストに貼った2枚目のラベルだよ。"),
    },
    {
      kind: "pick",
      prompt: L("The PEP 8 way to test for None", "La forma PEP 8 de probar None", "PEP 8 流の None 判定"),
      code: 'x = None\nif x ___ None:\n    print("empty")',
      options: ["is", "=="],
      answer: 0,
      check: { compiles: true, stdout: "empty" },
      explain: L("Both run here, but there is only one None, so the style guide says: is None.", "Ambas funcionan aquí, pero solo existe un None, así que la guía de estilo dice: is None.", "ここではどちらも動くけど、None はひとつだけ。だからスタイルガイドは is None だよ。"),
      win: [{ t: "print", text: "empty" }, { t: "say", actor: "enemy", text: L("You found me!", "¡Me encontraste!", "見つかった！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print(True + True, True == 1, 1 == 1.0)",
      options: ["2 True True", "True True False", "2 False True"],
      answer: 0,
      output: "2 True True",
      check: { compiles: true, stdout: "2 True True" },
      explain: L("bool is a kind of int: True is 1, so True + True is 2. And 1 equals 1.0 in value.", "bool es un tipo de int: True es 1, así que True + True es 2. Y 1 vale lo mismo que 1.0.", "bool は int の一種で True は 1。だから True + True は 2。1 と 1.0 も値は等しいよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print("10" < "9", 10 < 9)',
      options: ["True False", "False False", "False True"],
      answer: 0,
      output: "True False",
      check: { compiles: true, stdout: "True False" },
      explain: L("Strings compare letter by letter: \"1\" comes before \"9\", so \"10\" < \"9\". Numbers compare by size.", "Los strings se comparan letra por letra: \"1\" va antes que \"9\", así que \"10\" < \"9\". Los números, por tamaño.", "文字列は1文字ずつ比べる。\"1\" は \"9\" より前なので \"10\" < \"9\"。数値は大きさで比べるよ。"),
    },
    {
      kind: "run",
      prompt: L("0 lives is a value! It must print lives set: 0", "¡0 vidas es un valor! Debe imprimir lives set: 0", "0 も値だよ！lives set: 0 と表示させて"),
      starter: 'lives = 0\nif lives is not None and lives:\n    print("lives set:", lives)\nelse:\n    print("no value")\n',
      solution: 'lives = 0\nif lives is not None:\n    print("lives set:", lives)\nelse:\n    print("no value")\n',
      expect: "lives set: 0",
      fallback: [String.raw`if\s+lives\s+is\s+not\s+None\s*:`, String.raw`if\s+not\s+lives\s+is\s+None\s*:`, String.raw`if\s+lives\s*!=\s*None\s*:`],
      explain: L("and lives fails because 0 is falsy. Only test is not None to accept 0.", "and lives falla porque 0 es falsy. Prueba solo is not None para aceptar el 0.", "0 は偽なので and lives で落ちる。is not None だけで判定すれば 0 も通るよ。"),
    },
  ],
};

// ─── 1.4 Boss: Type Golem ──────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "type-golem",
  title: L("Boss: Type Golem", "Jefe: Gólem de Tipos", "ボス：タイプゴーレム"),
  concept: "values",
  mode: "boss",
  xp: 180,
  enemy: "golem",
  enemyName: L("TYPE GOLEM", "GÓLEM DE TIPOS", "タイプゴーレム"),
  beats: [
    enemySays(L(
      "I AM THE TYPE GOLEM. Ints, floats, strings, None... my stones hide every type. Name them, if you can!",
      "SOY EL GÓLEM DE TIPOS. Ints, floats, strings, None... mis piedras esconden cada tipo. ¡Nómbralos si puedes!",
      "我はタイプゴーレム。int、float、str、None…この石にはあらゆる型がひそむ。見破れるか！",
    )),
    { kind: "predict", time: 12, prompt: PRINT, code: "print(type(10 / 2).__name__, 10 / 2)", options: ["float 5.0", "int 5", "float 5"], answer: 0, output: "float 5.0", check: { compiles: true, stdout: "float 5.0" }, explain: L("/ always returns a float, even for 10 / 2.", "/ siempre devuelve un float, incluso con 10 / 2.", "/ はいつも float。10 / 2 でもね。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: 'print("ab"[5])', options: ["IndexError", L("Prints nothing", "No imprime nada", "何も表示しない"), "None"], answer: 0, check: { compiles: true, throws: "IndexError" }, explain: L("\"ab\" has indexes 0 and 1 only. Index 5 is out of range: IndexError.", "\"ab\" solo tiene los índices 0 y 1. El 5 está fuera de rango: IndexError.", "\"ab\" のインデックスは 0 と 1 だけ。5 は範囲外で IndexError。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'print("ab"[1:5])', options: ["b", "IndexError", "ab"], answer: 0, output: "b", check: { compiles: true, stdout: "b" }, explain: L("Slices clamp to the string's end instead of crashing. Indexes don't.", "Los cortes se ajustan al final del string en vez de fallar. Los índices no.", "スライスは範囲外でも末尾で止まる。インデックスはエラーになる。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: 'print(int("3.5"))', options: ["ValueError", "3", "4"], answer: 0, check: { compiles: true, throws: "ValueError" }, explain: L("int() can't read \"3.5\" as a whole number: ValueError. Use float() first.", "int() no puede leer \"3.5\" como entero: ValueError. Usa float() primero.", "int() は \"3.5\" を整数として読めず ValueError。先に float() を使おう。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'print(int(3.9), int(-3.9), float("3.5"))', options: ["3 -3 3.5", "4 -4 3.5", "3 -4 3.5"], answer: 0, output: "3 -3 3.5", check: { compiles: true, stdout: "3 -3 3.5" }, explain: L("int() on a float chops the decimals toward zero: 3.9 → 3, -3.9 → -3.", "int() con un float corta los decimales hacia cero: 3.9 → 3, -3.9 → -3.", "float に int() を使うと0の方向に切る。3.9 → 3、-3.9 → -3。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'print([] or {} or 0 or "last")', options: ["last", "[]", "False"], answer: 0, output: "last", check: { compiles: true, stdout: "last" }, explain: L("[], {} and 0 are all falsy, so or keeps going until \"last\".", "[], {} y 0 son falsy, así que or sigue hasta \"last\".", "[]、{}、0 はすべて偽。or は \"last\" まで進むよ。") },
    { kind: "type", time: 15, prompt: L("Repeat the text 3 times", "Repite el texto 3 veces", "文字列を3回くり返そう"), code: 'print(3 ___ "ab" + "!")', answer: "*", check: { compiles: true, stdout: "ababab!" }, explain: L("int * str repeats the text: ababab, then + adds the !.", "int * str repite el texto: ababab, luego + agrega el !.", "int * str で文字列をくり返して ababab、+ で ! をつなぐ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "x = 5\nprint(1 < x < 10 == 10)", options: ["True", "False", "TypeError"], answer: 0, output: "True", check: { compiles: true, stdout: "True" }, explain: L("It chains: 1 < 5 and 5 < 10 and 10 == 10. All true.", "Se encadena: 1 < 5 and 5 < 10 and 10 == 10. Todo verdadero.", "つながって 1 < 5 and 5 < 10 and 10 == 10。すべて真。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "print(f\"{'hi':*^6}\")", options: ["**hi**", "hi****", "******"], answer: 0, output: "**hi**", check: { compiles: true, stdout: "**hi**" }, explain: L("After the colon: fill with *, ^ centers, width 6. So two stars on each side.", "Tras los dos puntos: relleno *, ^ centra, ancho 6. Dos estrellas a cada lado.", "コロンの後は「* で埋める・^ で中央・幅 6」。両側に * が2つずつ。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'print(bool(None), bool(" "))', options: ["False True", "False False", "True True"], answer: 0, output: "False True", check: { compiles: true, stdout: "False True" }, explain: L("None is falsy. \" \" holds a space, so it's not empty: truthy.", "None es falsy. \" \" contiene un espacio, no está vacío: truthy.", "None は偽。\" \" は空白が入っているので空じゃない：真。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'print(1 == "1", 1 == 1.0)', options: ["False True", "True True", "False False"], answer: 0, output: "False True", check: { compiles: true, stdout: "False True" }, explain: L("Python never converts text to numbers on its own. 1 and 1.0 are equal numbers.", "Python nunca convierte texto en número por su cuenta. 1 y 1.0 son números iguales.", "Python は文字列を勝手に数値にしない。1 と 1.0 は等しい数値。") },
    enemySays(L(
      "Crumble... you read every stone. The Collection Forest lies ahead, where lists share secrets.",
      "Me desmorono... leíste cada piedra. Adelante está el Bosque de Colecciones, donde las listas comparten secretos.",
      "くずれる…すべての石を読みとったな。この先はコレクションの森。リストが秘密を分けあう場所だ。",
    )),
  ],
};

export const nameVillage: RegionDef = {
  slug: "name-village",
  name: L("Name Village", "Aldea de Nombres", "名前の村"),
  subtitle: L("names · numbers · strings · truth", "nombres · números · strings · verdad", "名前・数値・文字列・真偽"),
  theme: "village",
  lessons: [names, numbers, truth, boss],
};
