import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 4 · OBJECT TOWER (classes and attributes, inheritance and dataclasses, generators and
// context managers, asyncio). Stage mapping: a class is a blueprint banner and each instance a
// potion; a generator is an enemy that hands one item per next(); a context manager is a door;
// in asyncio the hero is the event loop and each task an ally that waits while another acts.
// Threads cannot start in the browser runner, so the GIL and threads are concept-only questions.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
/** Code is written line by line for readability. */
const code = (...lines: string[]) => lines.join("\n");
/** Exception class names read the same in every locale. */
const exc = (name: string) => L(name, name, name);

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");

// ─── 4.1 Blueprints: classes and attributes ─────────────────────────────────
const classes: LessonDef = {
  slug: "classes-and-attributes",
  title: L("Blueprints", "Planos", "設計図"),
  concept: "classes",
  mode: "lesson",
  xp: 75,
  enemy: "golem",
  enemyName: L("BLUEPRINT GOLEM", "GÓLEM DE PLANOS", "設計図ゴーレム"),
  beats: [
    say(L(
      "Welcome to the Object Tower! A CLASS is a blueprint. Calling it builds an INSTANCE, and __init__ sets it up.",
      "¡Bienvenido a la Torre de Objetos! Una CLASE es un plano. Al llamarla construye una INSTANCIA, y __init__ la prepara.",
      "オブジェクトの塔へようこそ！クラスは設計図。呼ぶとインスタンスができ、__init__ が準備するよ。",
    )),
    {
      kind: "act",
      prompt: L("Draw the blueprint, then build a hero", "Dibuja el plano y construye un héroe", "設計図を描いて、ヒーローを作ろう"),
      steps: [
        { label: L("CLASS", "CLASS", "class"), line: "class Hero:", effects: [{ t: "banner", text: L("BLUEPRINT", "PLANO", "設計図") }] },
        { label: L("__init__", "__init__", "__init__"), line: "    def __init__(self, name):" },
        { label: L("SET name", "PONER name", "name を設定"), line: "        self.name = name" },
        { label: L("SET hp", "PONER hp", "hp を設定"), line: "        self.hp = 10" },
        { label: L("BUILD", "CONSTRUIR", "作る"), line: 'h = Hero("Ada")', effects: [{ t: "item", kind: "potion", holder: "hero" }, { t: "tag", actor: "hero", text: "h", value: "Ada 10" }, { t: "say", actor: "hero", text: L("self is me!", "¡self soy yo!", "self はわたし！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "print(h.name, h.hp)", output: "Ada 10", effects: [{ t: "print", text: "Ada 10" }] },
      ],
    },
    say(L(
      "self is the new object itself. self.name = name sticks a label on THAT instance, so each hero has its own.",
      "self es el objeto nuevo en sí. self.name = name pega una etiqueta en ESA instancia, así cada héroe tiene la suya.",
      "self は作られたオブジェクト自身。self.name = name で「その」インスタンスにラベルを貼るよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Hero:", "    def __init__(self, name):", "        self.name = name", "        self.hp = 10", 'h = Hero("Ada")', "h.hp -= 3", "print(h.name, h.hp)"),
      options: ["Ada 7", "Ada 10", "Hero 7"],
      answer: 0,
      output: "Ada 7",
      check: { compiles: true, stdout: "Ada 7" },
      explain: L("h.hp starts at 10 and h.hp -= 3 changes this instance's attribute to 7.", "h.hp empieza en 10 y h.hp -= 3 cambia el atributo de esta instancia a 7.", "h.hp は 10 から始まり、h.hp -= 3 でこのインスタンスの属性が 7 になる。"),
      setup: [{ t: "item", kind: "potion", holder: "hero" }, { t: "tag", actor: "hero", text: "h", value: "hp 10" }],
      win: [{ t: "value", actor: "hero", text: "hp 7" }, { t: "print", text: "Ada 7" }],
    },
    {
      kind: "type",
      prompt: L("Name the instance parameter", "Nombra el parámetro de la instancia", "インスタンスの引数名は？"),
      code: code("class Potion:", "    def __init__(___, power):", "        self.power = power", "print(Potion(5).power)"),
      answer: "self",
      check: { compiles: true, stdout: "5" },
      explain: L("Every method receives the instance first. By convention it is called self.", "Todo método recibe primero la instancia. Por convención se llama self.", "メソッドは最初にインスタンスを受け取る。名前は慣習で self だよ。"),
      win: [{ t: "print", text: "5" }],
    },
    say(L(
      "An attribute written in the class body belongs to the CLASS: every instance shares it. Assigning on one instance shadows it.",
      "Un atributo escrito en el cuerpo de la clase es de la CLASE: todas las instancias lo comparten. Asignarlo en una lo oculta.",
      "クラス本体に書いた属性はクラスのもの。全インスタンスで共有。インスタンスに代入すると上書きで隠れるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Hero:", "    level = 1", "a = Hero()", "b = Hero()", "a.level = 5", "print(a.level, b.level, Hero.level)"),
      options: ["5 1 1", "5 5 5", "5 5 1"],
      answer: 0,
      output: "5 1 1",
      check: { compiles: true, stdout: "5 1 1" },
      explain: L("a.level = 5 creates a's OWN attribute. b and Hero still read the class value 1.", "a.level = 5 crea un atributo PROPIO de a. b y Hero siguen leyendo el valor de la clase, 1.", "a.level = 5 は a だけの属性を作る。b と Hero はクラスの 1 を読むよ。"),
      win: [{ t: "print", text: "5 1 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Hero:", "    team = []", "    def __init__(self, name):", "        self.team.append(name)", 'a = Hero("Ada")', 'b = Hero("Bo")', "print(a.team, Hero.team is b.team)"),
      options: ["['Ada', 'Bo'] True", "['Ada'] False", "['Ada', 'Bo'] False"],
      answer: 0,
      output: "['Ada', 'Bo'] True",
      check: { compiles: true, stdout: "['Ada', 'Bo'] True" },
      explain: L(
        "append changes the ONE class list, it never assigns. Every hero shares the same team.",
        "append cambia la ÚNICA lista de la clase, nunca asigna. Todos los héroes comparten el mismo team.",
        "append はクラスの1つのリストを変えるだけで代入しない。全員が同じ team を共有するよ。",
      ),
      win: [{ t: "print", text: "['Ada', 'Bo'] True" }, { t: "shake" }],
    },
    say(L(
      "Dunder methods (__add__, __eq__, __repr__...) teach operators to your class. Without __eq__, == means 'same object'.",
      "Los métodos dunder (__add__, __eq__, __repr__...) enseñan operadores a tu clase. Sin __eq__, == significa 'mismo objeto'.",
      "ダンダーメソッド（__add__、__eq__、__repr__…）で演算子を教えられる。__eq__ がないと == は「同じ物か」。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class A:", "    def __init__(self, n):", "        self.n = n", "print(A(1) == A(1))"),
      options: ["False", "True", "TypeError"],
      answer: 0,
      output: "False",
      check: { compiles: true, stdout: "False" },
      explain: L("No __eq__, so == falls back to identity. Two separate objects are not equal.", "Sin __eq__, == usa la identidad. Dos objetos distintos no son iguales.", "__eq__ がないので == は同一性で比べる。別々の2つは等しくないよ。"),
      win: [{ t: "print", text: "False" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Vec:", "    def __init__(self, x, y):", "        self.x, self.y = x, y", "    def __add__(self, o):", "        return Vec(self.x + o.x, self.y + o.y)", "    def __eq__(self, o):", "        return (self.x, self.y) == (o.x, o.y)", "v = Vec(1, 2) + Vec(3, 4)", "print(v.x, v.y, Vec(1, 1) == Vec(1, 1), Vec(1, 1) is Vec(1, 1))"),
      options: ["4 6 True False", "4 6 True True", "4 6 False False"],
      answer: 0,
      output: "4 6 True False",
      check: { compiles: true, stdout: "4 6 True False" },
      explain: L("+ calls __add__ and == calls __eq__. is still asks 'same object?', and they are two.", "+ llama a __add__ y == a __eq__. is sigue preguntando '¿mismo objeto?', y son dos.", "+ は __add__、== は __eq__ を呼ぶ。is は「同じ物？」のままなので False。"),
      win: [{ t: "print", text: "4 6 True False" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Hero:", "    def __init__(self, name):", "        self.name = name", "    def __repr__(self):", '        return f"Hero({self.name!r})"', "    def __str__(self):", '        return f"the hero {self.name}"', 'h = Hero("Ada")', "print(h, [h])"),
      options: ["the hero Ada [Hero('Ada')]", "the hero Ada [the hero Ada]", "Hero('Ada') [Hero('Ada')]"],
      answer: 0,
      output: "the hero Ada [Hero('Ada')]",
      check: { compiles: true, stdout: "the hero Ada [Hero('Ada')]" },
      explain: L("print uses __str__, but a list shows its items with __repr__, the developer view.", "print usa __str__, pero una lista muestra sus elementos con __repr__, la vista para programadores.", "print は __str__ を使うけど、リストの中身は開発者向けの __repr__ で表示されるよ。"),
      win: [{ t: "print", text: "the hero Ada [Hero('Ada')]" }],
    },
    say(L(
      "@property makes a method read like an attribute. A setter can guard every write, like clamping hp at 0.",
      "@property hace que un método se lea como un atributo. Un setter puede vigilar cada escritura, como limitar hp a 0.",
      "@property でメソッドを属性のように読める。setter で書きこみを見張れる。hp を 0 未満にしない、とかね。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Hero:", "    def __init__(self, hp):", "        self._hp = hp", "    @property", "    def hp(self):", "        return self._hp", "    @hp.setter", "    def hp(self, value):", "        self._hp = max(0, value)", "h = Hero(5)", "h.hp = -3", "print(h.hp)"),
      options: ["0", "-3", "5"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("h.hp = -3 runs the setter, which stores max(0, -3), so 0.", "h.hp = -3 ejecuta el setter, que guarda max(0, -3), o sea 0.", "h.hp = -3 で setter が動き、max(0, -3) の 0 を保存するよ。"),
      win: [{ t: "print", text: "0" }, { t: "say", actor: "hero", text: L("Guarded!", "¡Protegido!", "ガード！") }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("class Hero:", "    @property", "    def hp(self):", "        return 10", "h = Hero()", "h.hp = 5"),
      options: ["AttributeError", L("hp becomes 5", "hp pasa a 5", "hp が 5 になる"), "TypeError"],
      answer: 0,
      check: { compiles: true, throws: "AttributeError" },
      explain: L("A property with no setter is read-only. Assigning to it raises AttributeError.", "Una property sin setter es de solo lectura. Asignarle lanza AttributeError.", "setter のない property は読み取り専用。代入すると AttributeError。"),
      win: [{ t: "shake" }, { t: "banner", text: exc("AttributeError") }],
    },
    {
      kind: "run",
      prompt: L("Fix the potion: it must print potion of 5", "Arregla la poción: debe imprimir potion of 5", "ポーションを直して potion of 5 と表示しよう"),
      starter: code("class Potion:", "    def __init__(self, power):", "        power = power", "", "    def describe(self):", '        return f"potion of {self.power}"', "", "print(Potion(5).describe())", ""),
      solution: code("class Potion:", "    def __init__(self, power):", "        self.power = power", "", "    def describe(self):", '        return f"potion of {self.power}"', "", "print(Potion(5).describe())", ""),
      expect: "potion of 5",
      fallback: String.raw`self\.power\s*=\s*power`,
      explain: L(
        "power = power only rebinds a local name. Store it on the instance: self.power = power.",
        "power = power solo reasigna un nombre local. Guárdalo en la instancia: self.power = power.",
        "power = power はローカル名を付け直すだけ。インスタンスに保存しよう：self.power = power。",
      ),
    },
  ],
};

// ─── 4.2 Bloodlines: inheritance and dataclasses ────────────────────────────
const inheritance: LessonDef = {
  slug: "inheritance-and-dataclasses",
  title: L("Bloodlines", "Linajes", "血すじ"),
  concept: "inheritance",
  mode: "lesson",
  xp: 80,
  enemy: "python/indent-gremlin",
  enemyName: L("HEIR GREMLIN", "GREMLIN HEREDERO", "あとつぎグレムリン"),
  beats: [
    say(L(
      "class Dog(Animal) INHERITS every method of Animal. Define a method with the same name to OVERRIDE it.",
      "class Dog(Animal) HEREDA todos los métodos de Animal. Define un método con el mismo nombre para SOBRESCRIBIRLO.",
      "class Dog(Animal) は Animal のメソッドをすべて受けつぐ。同じ名前で書けば上書き（オーバーライド）できるよ。",
    )),
    {
      kind: "act",
      prompt: L("Make a parent, then a child that barks", "Crea un padre y luego un hijo que ladra", "親を作って、ほえる子を作ろう"),
      steps: [
        { label: L("PARENT", "PADRE", "親"), line: "class Animal:", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "Animal" }] },
        { label: L("SPEAK", "HABLAR", "話す"), line: '    def speak(self): return "..."' },
        { label: L("CHILD", "HIJO", "子"), line: "class Dog(Animal):", effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "Dog" }] },
        { label: L("OVERRIDE", "SOBRESCRIBIR", "上書き"), line: '    def speak(self): return "woof"', effects: [{ t: "say", actor: "ally", text: L("woof!", "¡guau!", "ワン！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "print(Dog().speak(), Animal().speak())", output: "woof ...", effects: [{ t: "print", text: "woof ..." }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Animal:", "    def speak(self):", '        return "..."', "class Dog(Animal):", "    def speak(self):", '        return "woof"', "print(Dog().speak(), isinstance(Dog(), Animal), issubclass(Animal, Dog))"),
      options: ["woof True False", "woof True True", "... True False"],
      answer: 0,
      output: "woof True False",
      check: { compiles: true, stdout: "woof True False" },
      explain: L("Dog's speak wins. A Dog IS an Animal, but an Animal is not a Dog.", "Gana el speak de Dog. Un Dog ES un Animal, pero un Animal no es un Dog.", "Dog の speak が使われる。Dog は Animal だけど、Animal は Dog じゃない。"),
      win: [{ t: "print", text: "woof True False" }],
    },
    say(L(
      "A child's __init__ REPLACES the parent's. Call super().__init__(...) so the parent can set up its part too.",
      "El __init__ del hijo REEMPLAZA al del padre. Llama a super().__init__(...) para que el padre prepare su parte.",
      "子の __init__ は親のものを置きかえる。super().__init__(...) を呼んで、親の準備も走らせよう。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("class Base:", "    def __init__(self):", "        self.hp = 10", "class Kid(Base):", "    def __init__(self):", "        self.mp = 5", "print(Kid().hp)"),
      options: ["AttributeError", "10", "None"],
      answer: 0,
      check: { compiles: true, throws: "AttributeError" },
      explain: L("Kid's __init__ never calls Base's, so self.hp is never set.", "El __init__ de Kid nunca llama al de Base, así que self.hp nunca se crea.", "Kid の __init__ が Base のものを呼ばないので、self.hp が作られない。"),
      win: [{ t: "shake" }, { t: "banner", text: exc("AttributeError") }],
    },
    {
      kind: "pick",
      prompt: L("Run the parent's setup", "Ejecuta la preparación del padre", "親の準備を呼ぼう"),
      code: code("class Base:", "    def __init__(self, name):", "        self.name = name", "class Mage(Base):", "    def __init__(self, name, mp):", "        ___.__init__(name)", "        self.mp = mp", 'm = Mage("Ada", 9)', "print(m.name, m.mp)"),
      options: ["super()", "self", "Base"],
      answer: 0,
      check: { compiles: true, stdout: "Ada 9" },
      explain: L(
        "super() reaches the parent's method. self.__init__ would call Mage's own __init__ again.",
        "super() llega al método del padre. self.__init__ volvería a llamar al __init__ de Mage.",
        "super() で親のメソッドに届く。self.__init__ だと Mage 自身の __init__ をまた呼んでしまう。",
      ),
      win: [{ t: "print", text: "Ada 9" }],
    },
    say(L(
      "With two parents, Python lines classes up in one order, the MRO. super() follows that line, not just 'the parent'.",
      "Con dos padres, Python ordena las clases en una fila, el MRO. super() sigue esa fila, no solo 'al padre'.",
      "親が2つあると、Python はクラスを1列に並べる（MRO）。super() は「親」じゃなくその列をたどるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class A:", '    def who(self): return "A"', "class B(A):", '    def who(self): return "B" + super().who()', "class C(A):", '    def who(self): return "C" + super().who()', "class D(B, C):", '    def who(self): return "D" + super().who()', "print(D().who())"),
      options: ["DBCA", "DBA", "DBACA"],
      answer: 0,
      output: "DBCA",
      check: { compiles: true, stdout: "DBCA" },
      explain: L("D's MRO is D, B, C, A, object. B's super() goes to C, not to A, so A runs only once.", "El MRO de D es D, B, C, A, object. El super() de B va a C, no a A, así A corre una sola vez.", "D の MRO は D、B、C、A、object。B の super() は A ではなく C へ。A は1回だけ。"),
      win: [{ t: "banner", text: L("D → B → C → A", "D → B → C → A", "D → B → C → A") }, { t: "print", text: "DBCA" }],
    },
    say(L(
      "@dataclass reads the annotated fields and writes __init__, __repr__ and __eq__ for you.",
      "@dataclass lee los campos anotados y escribe __init__, __repr__ y __eq__ por ti.",
      "@dataclass は型注釈つきのフィールドを読んで、__init__、__repr__、__eq__ を書いてくれるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("from dataclasses import dataclass", "@dataclass", "class Item:", "    name: str", "    power: int = 1", 'a = Item("gem", 3)', 'print(a, a == Item("gem", 3))'),
      options: ["Item(name='gem', power=3) True", "Item(name='gem', power=3) False", "Item('gem', 3) True"],
      answer: 0,
      output: "Item(name='gem', power=3) True",
      check: { compiles: true, stdout: "Item(name='gem', power=3) True" },
      explain: L("The generated __repr__ shows each field by name, and __eq__ compares field values.", "El __repr__ generado muestra cada campo por nombre, y __eq__ compara los valores de los campos.", "生成された __repr__ はフィールド名つきで表示し、__eq__ は値を比べるよ。"),
      win: [{ t: "banner", text: L("auto __init__", "auto __init__", "自動 __init__") }, { t: "print", text: "Item(name='gem', power=3) True" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("from dataclasses import dataclass", "@dataclass", "class Bag:", "    items: list = []"),
      options: ["ValueError", L("Every Bag shares one list", "Todas las Bag comparten una lista", "全 Bag で1つのリストを共有"), L("It works fine", "Funciona bien", "問題なく動く")],
      answer: 0,
      check: { compiles: true, throws: "ValueError" },
      explain: L("dataclass refuses a mutable default like [] with ValueError, to save you from the shared-list trap.", "dataclass rechaza un valor mutable como [] con ValueError, para salvarte de la lista compartida.", "dataclass は [] のような変更可能なデフォルトを ValueError で拒否する。共有のワナ防止だよ。"),
      win: [{ t: "shake" }, { t: "banner", text: exc("ValueError") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("from dataclasses import dataclass, field", "@dataclass", "class Bag:", "    items: list = field(default_factory=list)", "a = Bag()", "b = Bag()", 'a.items.append("gem")', "print(b.items)"),
      options: ["[]", "['gem']", "None"],
      answer: 0,
      output: "[]",
      check: { compiles: true, stdout: "[]" },
      explain: L("default_factory calls list() for EACH new Bag, so every bag gets its own list.", "default_factory llama a list() para CADA Bag nueva, así cada bolsa tiene su propia lista.", "default_factory は Bag を作るたびに list() を呼ぶ。袋ごとに別のリストだよ。"),
      win: [{ t: "print", text: "[]" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("from dataclasses import dataclass", "@dataclass(frozen=True)", "class P:", "    x: int", "p = P(1)", "p.x = 2"),
      options: ["FrozenInstanceError", L("p.x becomes 2", "p.x pasa a 2", "p.x が 2 になる"), "TypeError"],
      answer: 0,
      check: { compiles: true, throws: "FrozenInstanceError" },
      explain: L("frozen=True makes instances read-only: assigning raises FrozenInstanceError.", "frozen=True vuelve las instancias de solo lectura: asignar lanza FrozenInstanceError.", "frozen=True でインスタンスは読み取り専用。代入すると FrozenInstanceError。"),
      win: [{ t: "shake" }, { t: "banner", text: L("FROZEN!", "¡CONGELADO!", "こおってる！") }],
    },
    say(L(
      "Type hints like x: int document intent for tools and readers. Python itself does NOT check them at runtime.",
      "Las anotaciones como x: int documentan la intención para herramientas y lectores. Python NO las revisa al ejecutar.",
      "x: int のような型ヒントはツールや読み手への説明。Python 自身は実行時にチェックしないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def heal(hp: int) -> int:", "    return hp * 2", 'print(heal("ab"))'),
      options: ["abab", "TypeError", "ab2"],
      answer: 0,
      output: "abab",
      check: { compiles: true, stdout: "abab" },
      explain: L("The hint says int, but nothing enforces it: \"ab\" * 2 is abab. A checker like mypy would warn.", "La anotación dice int, pero nada lo impone: \"ab\" * 2 es abab. Un verificador como mypy avisaría.", "ヒントは int でも強制はされない。\"ab\" * 2 は abab。mypy などなら警告するよ。"),
      win: [{ t: "print", text: "abab" }],
    },
    {
      kind: "run",
      prompt: L("Fix the knight: it must print Ada wears 3", "Arregla al caballero: debe imprimir Ada wears 3", "騎士を直して Ada wears 3 と表示しよう"),
      starter: code("class Base:", "    def __init__(self, name):", "        self.name = name", "", "class Knight(Base):", "    def __init__(self, name, armor):", "        self.armor = armor", "", 'k = Knight("Ada", 3)', 'print(f"{k.name} wears {k.armor}")', ""),
      solution: code("class Base:", "    def __init__(self, name):", "        self.name = name", "", "class Knight(Base):", "    def __init__(self, name, armor):", "        super().__init__(name)", "        self.armor = armor", "", 'k = Knight("Ada", 3)', 'print(f"{k.name} wears {k.armor}")', ""),
      expect: "Ada wears 3",
      fallback: [String.raw`super\(\)\.__init__\(\s*name\s*\)`, String.raw`Base\.__init__\(\s*self\s*,\s*name\s*\)`],
      explain: L(
        "Knight's __init__ skips the parent's. Add super().__init__(name) before setting armor.",
        "El __init__ de Knight se salta al del padre. Agrega super().__init__(name) antes de poner armor.",
        "Knight の __init__ が親を呼んでいない。armor の前に super().__init__(name) を足そう。",
      ),
    },
  ],
};

// ─── 4.3 Lazy enemies and magic doors: generators and context managers ──────
const generators: LessonDef = {
  slug: "generators-and-context-managers",
  title: L("Lazy enemies, magic doors", "Enemigos perezosos, puertas", "なまけ敵と魔法の扉"),
  concept: "generators",
  mode: "lesson",
  xp: 80,
  enemy: "python/none-ghost",
  enemyName: L("LAZY GHOST", "FANTASMA PEREZOSO", "なまけゴースト"),
  beats: [
    say(L(
      "iter() turns a list into an ITERATOR. next() takes one item; when none are left it raises StopIteration.",
      "iter() convierte una lista en un ITERADOR. next() toma un elemento; cuando no quedan, lanza StopIteration.",
      "iter() でリストをイテレータにする。next() で1つずつ取り出し、なくなると StopIteration だよ。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: code("it = iter([1, 2])", "print(next(it), next(it))", "next(it)"),
      options: [L("1 2, then StopIteration", "1 2 y luego StopIteration", "1 2 の後 StopIteration"), L("1 2, then None", "1 2 y luego None", "1 2 の後 None"), L("1 2, then 1", "1 2 y luego 1", "1 2 の後 1")],
      answer: 0,
      check: { compiles: true, throws: "StopIteration" },
      explain: L("The iterator hands out 1, then 2. The third next() finds it empty: StopIteration.", "El iterador entrega 1 y luego 2. El tercer next() lo encuentra vacío: StopIteration.", "1、2 と取り出し、3回目の next() は空なので StopIteration。"),
      win: [{ t: "print", text: "1 2" }, { t: "shake" }, { t: "banner", text: exc("StopIteration") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("it = iter([1, 2, 3])", "print(list(it), list(it))"),
      options: ["[1, 2, 3] []", "[1, 2, 3] [1, 2, 3]", "[] []"],
      answer: 0,
      output: "[1, 2, 3] []",
      check: { compiles: true, stdout: "[1, 2, 3] []" },
      explain: L("An iterator is used up once. The first list() drains it; the second finds nothing.", "Un iterador se gasta una sola vez. El primer list() lo vacía; el segundo no encuentra nada.", "イテレータは一度きり。1回目の list() で空になり、2回目は何もない。"),
      win: [{ t: "print", text: "[1, 2, 3] []" }],
    },
    say(L(
      "yield makes a GENERATOR: it pauses at each yield and resumes on the next next(). Nothing runs before the first one.",
      "yield crea un GENERADOR: se pausa en cada yield y sigue con el siguiente next(). Nada corre antes del primero.",
      "yield でジェネレータになる。yield ごとに止まり、次の next() で再開。最初の next() までは何も動かないよ。",
    )),
    {
      kind: "act",
      prompt: L("Pull items one at a time", "Saca elementos de uno en uno", "1つずつ取り出そう"),
      steps: [
        { label: L("MAKE g", "CREAR g", "g を作る"), line: "g = gen()", effects: [{ t: "tag", actor: "enemy", text: "g" }, { t: "say", actor: "enemy", text: L("Zzz...", "Zzz...", "ぐーぐー…") }] },
        { label: L("NEXT", "NEXT", "next"), line: "print(next(g))", output: "start\n1", effects: [{ t: "print", text: "start" }, { t: "item", kind: "gem", holder: "enemy" }, { t: "give", to: "hero" }, { t: "print", text: "1" }, { t: "wait", ms: 300 }] },
        { label: L("NEXT AGAIN", "OTRO NEXT", "もう一度 next"), line: "print(next(g))", output: "middle\n2", effects: [{ t: "print", text: "middle" }, { t: "item", kind: "gem", holder: "enemy" }, { t: "give", to: "hero" }, { t: "print", text: "2" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def gen():", '    print("start")', "    yield 1", '    print("middle")', "    yield 2", "g = gen()", 'print("made")', "print(next(g))", "print(next(g))"),
      options: ["made start 1 middle 2", "start middle made 1 2", "start made 1 middle 2"],
      answer: 0,
      output: "made\nstart\n1\nmiddle\n2",
      check: { compiles: true, stdout: "made\nstart\n1\nmiddle\n2" },
      explain: L("gen() only builds the generator. Its body starts on the first next() and pauses at each yield.", "gen() solo construye el generador. Su cuerpo empieza en el primer next() y se pausa en cada yield.", "gen() はジェネレータを作るだけ。本体は最初の next() で始まり、yield ごとに止まる。"),
      win: [{ t: "print", text: "made" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("def countdown(n):", "    while n > 0:", "        yield n", "        n -= 1", "print(list(countdown(3)), sum(countdown(4)))"),
      options: ["[3, 2, 1] 10", "[3, 2, 1, 0] 10", "[1, 2, 3] 6"],
      answer: 0,
      output: "[3, 2, 1] 10",
      check: { compiles: true, stdout: "[3, 2, 1] 10" },
      explain: L("list() and sum() keep calling next() until the generator ends: 3+2+1, and 4+3+2+1 = 10.", "list() y sum() llaman a next() hasta que el generador termina: 3+2+1, y 4+3+2+1 = 10.", "list() と sum() は終わるまで next() を呼ぶ。3,2,1 と 4+3+2+1 = 10。"),
      win: [{ t: "print", text: "[3, 2, 1] 10" }],
    },
    {
      kind: "type",
      prompt: L("Hand over a whole list", "Entrega una lista entera", "リストをまるごと渡そう"),
      code: code("def gen():", "    ___ from [1, 2]", "    yield 3", "print(list(gen()))"),
      answer: "yield",
      check: { compiles: true, stdout: "[1, 2, 3]" },
      explain: L("yield from hands out every item of another iterable, one by one.", "yield from entrega cada elemento de otro iterable, uno por uno.", "yield from は別のイテラブルの要素を1つずつ渡すよ。"),
      win: [{ t: "print", text: "[1, 2, 3]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("nums = [1, 2, 3]", "sq = (n * n for n in nums)", "nums.append(4)", "print(list(sq))"),
      options: ["[1, 4, 9, 16]", "[1, 4, 9]", "[]"],
      answer: 0,
      output: "[1, 4, 9, 16]",
      check: { compiles: true, stdout: "[1, 4, 9, 16]" },
      explain: L("A generator expression is lazy: it walks nums only when list() asks, after 4 was added.", "Una expresión generadora es perezosa: recorre nums solo cuando list() pide, después de agregar 4.", "ジェネレータ式は怠け者。list() が求めたときに nums を読むので、4 も入るよ。"),
      win: [{ t: "print", text: "[1, 4, 9, 16]" }],
    },
    say(L(
      "with is a magic door: __enter__ runs on the way in, and __exit__ ALWAYS runs on the way out, even after an error.",
      "with es una puerta mágica: __enter__ corre al entrar, y __exit__ SIEMPRE corre al salir, incluso tras un error.",
      "with は魔法の扉。入るとき __enter__、出るときは「必ず」__exit__。エラーが起きてもだよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Lamp:", "    def __enter__(self):", '        print("on")', '        return "light"', "    def __exit__(self, *exc):", '        print("off")', "with Lamp() as l:", "    print(l)"),
      options: ["on light off", "light on off", "on off light"],
      answer: 0,
      output: "on\nlight\noff",
      check: { compiles: true, stdout: "on\nlight\noff" },
      explain: L("__enter__ prints on and its return value goes to l. Leaving the block calls __exit__.", "__enter__ imprime on y lo que devuelve va a l. Al salir del bloque se llama a __exit__.", "__enter__ が on を表示し、戻り値が l に入る。ブロックを出ると __exit__。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Lamp" }],
      win: [{ t: "say", actor: "ally", text: L("on", "on", "on") }, { t: "print", text: "light" }, { t: "say", actor: "ally", text: L("off", "off", "off") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("class Lamp:", "    def __enter__(self):", "        return self", "    def __exit__(self, exc_type, exc, tb):", '        print("off", exc_type.__name__)', "        return True", "with Lamp():", "    1 / 0", 'print("after")'),
      options: ["off ZeroDivisionError after", "ZeroDivisionError", "after"],
      answer: 0,
      output: "off ZeroDivisionError\nafter",
      check: { compiles: true, stdout: "off ZeroDivisionError\nafter" },
      explain: L("__exit__ still runs and sees the error. Returning True swallows it, so the program goes on.", "__exit__ corre igual y ve el error. Devolver True se lo traga, así el programa sigue.", "__exit__ はちゃんと動いてエラーを受け取る。True を返すと例外を握りつぶし、先へ進む。"),
      win: [{ t: "shake" }, { t: "print", text: "off ZeroDivisionError" }, { t: "print", text: "after" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("from contextlib import contextmanager", "@contextmanager", "def tag(name):", '    print(f"<{name}>")', "    yield", '    print(f"</{name}>")', 'with tag("b"):', '    print("hi")'),
      options: ["<b> hi </b>", "<b> </b> hi", "hi <b> </b>"],
      answer: 0,
      output: "<b>\nhi\n</b>",
      check: { compiles: true, stdout: "<b>\nhi\n</b>" },
      explain: L("@contextmanager turns a generator into a door: code before yield is enter, after it is exit.", "@contextmanager convierte un generador en puerta: lo de antes de yield es la entrada, lo de después la salida.", "@contextmanager でジェネレータが扉になる。yield の前が入口、後が出口。"),
      win: [{ t: "print", text: "<b>" }, { t: "print", text: "hi" }, { t: "print", text: "</b>" }],
    },
    {
      kind: "run",
      prompt: L("Make evens a generator: evens: [0, 2, 4, 6]", "Haz de evens un generador: evens: [0, 2, 4, 6]", "evens をジェネレータにしよう"),
      starter: code("def evens(limit):", "    result = []", "    for n in range(limit):", "        if n % 2 == 0:", "            return n", "    return result", "", 'print("evens:", list(evens(7)))', ""),
      solution: code("def evens(limit):", "    for n in range(limit):", "        if n % 2 == 0:", "            yield n", "", 'print("evens:", list(evens(7)))', ""),
      expect: "evens: [0, 2, 4, 6]",
      fallback: [String.raw`yield\s+n`, String.raw`result\.append\(\s*n\s*\)[\s\S]*return\s+result`],
      explain: L(
        "return n stops at the first even and hands back an int. yield n hands each even out and keeps going.",
        "return n se detiene en el primer par y devuelve un int. yield n entrega cada par y sigue.",
        "return n は最初の偶数で終わって int を返す。yield n なら偶数を1つずつ渡して続くよ。",
      ),
    },
  ],
};

// ─── 4.4 The event loop tower: async and concurrency ────────────────────────
const asyncLesson: LessonDef = {
  slug: "async-and-concurrency",
  title: L("The event loop", "El event loop", "イベントループ"),
  concept: "async",
  mode: "lesson",
  xp: 85,
  enemy: "ghost",
  enemyName: L("AWAIT PHANTOM", "FANTASMA AWAIT", "await の幻"),
  beats: [
    say(L(
      "async def makes a COROUTINE function. Calling it runs nothing yet; await runs it. asyncio.run starts the loop.",
      "async def crea una función CORRUTINA. Llamarla aún no corre nada; await la ejecuta. asyncio.run arranca el loop.",
      "async def はコルーチン関数を作る。呼んだだけでは動かず、await で動く。asyncio.run がループを始めるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("import asyncio", "async def main():", '    print("hi")', "    return 7", "print(asyncio.run(main()))"),
      options: ["hi 7", "7", "hi"],
      answer: 0,
      output: "hi\n7",
      check: { compiles: true, stdout: "hi\n7" },
      explain: L("asyncio.run runs main to the end and gives back its return value, 7.", "asyncio.run corre main hasta el final y devuelve su valor de retorno, 7.", "asyncio.run は main を最後まで動かし、戻り値の 7 を返すよ。"),
      win: [{ t: "print", text: "hi" }, { t: "print", text: "7" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("async def greet():", '    print("hello")', '    return "hi"', "c = greet()", "print(type(c).__name__)", "c.close()"),
      options: ["coroutine", "hello coroutine", "str"],
      answer: 0,
      output: "coroutine",
      check: { compiles: true, stdout: "coroutine" },
      explain: L("Calling greet() only builds a coroutine object. Its body (and hello) never ran.", "Llamar a greet() solo construye un objeto corrutina. Su cuerpo (y hello) nunca corrió.", "greet() はコルーチンを作るだけ。本体（hello）は動いていないよ。"),
      win: [{ t: "print", text: "coroutine" }, { t: "say", actor: "hero", text: L("Not started!", "¡No arrancó!", "まだ動いてない！") }],
    },
    say(L(
      "await asyncio.sleep(...) pauses one task and hands the turn back to the loop, which lets another task run.",
      "await asyncio.sleep(...) pausa una tarea y devuelve el turno al loop, que deja correr a otra tarea.",
      "await asyncio.sleep(...) はタスクを止めて順番をループに返す。その間に別のタスクが動くよ。",
    )),
    {
      kind: "act",
      prompt: L("Two tasks take turns on one loop", "Dos tareas se turnan en un loop", "2つのタスクが交代で動く"),
      setup: [{ t: "tag", actor: "hero", text: "loop" }],
      steps: [
        { label: L("TASK a", "TAREA a", "タスク a"), line: 'print("a", 0)', output: "a 0", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "a" }, { t: "print", text: "a 0" }] },
        { label: L("a AWAITS", "a ESPERA", "a が待つ"), line: "await asyncio.sleep(0)", effects: [{ t: "say", actor: "ally", text: L("Your turn!", "¡Te toca!", "どうぞ！") }, { t: "wait", ms: 300 }] },
        { label: L("TASK b", "TAREA b", "タスク b"), line: 'print("b", 0)', output: "b 0", effects: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "b" }, { t: "print", text: "b 0" }] },
        { label: L("b AWAITS", "b ESPERA", "b が待つ"), line: "await asyncio.sleep(0)", effects: [{ t: "say", actor: "enemy", text: L("Back to a", "Vuelve a", "a に戻る") }] },
        { label: L("a AGAIN", "a OTRA VEZ", "また a"), line: 'print("a", 1)', output: "a 1", effects: [{ t: "print", text: "a 1" }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("import asyncio", "async def tick(name):", "    for i in range(2):", "        print(name, i)", "        await asyncio.sleep(0)", "async def main():", '    await asyncio.gather(tick("a"), tick("b"))', "asyncio.run(main())"),
      options: ["a 0, b 0, a 1, b 1", "a 0, a 1, b 0, b 1", "b 0, a 0, b 1, a 1"],
      answer: 0,
      output: "a 0\nb 0\na 1\nb 1",
      check: { compiles: true, stdout: "a 0\nb 0\na 1\nb 1" },
      explain: L("gather runs both. Each await sleep(0) hands the turn over, so the tasks interleave.", "gather corre ambas. Cada await sleep(0) cede el turno, así las tareas se intercalan.", "gather で両方動く。await sleep(0) のたびに順番をゆずるので交互になるよ。"),
      win: [{ t: "print", text: "a 0" }, { t: "print", text: "b 0" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("import asyncio", "async def job(name, delay):", "    await asyncio.sleep(delay)", "    return name", "async def main():", '    r = await asyncio.gather(job("slow", 0.05), job("fast", 0.01))', "    print(r)", "asyncio.run(main())"),
      options: ["['slow', 'fast']", "['fast', 'slow']", "slow"],
      answer: 0,
      output: "['slow', 'fast']",
      check: { compiles: true, stdout: "['slow', 'fast']" },
      explain: L("gather returns results in the order you LISTED them, even if fast finished first.", "gather devuelve los resultados en el orden en que los PASASTE, aunque fast termine primero.", "gather の結果は「渡した順」。fast が先に終わっても順番は変わらないよ。"),
      win: [{ t: "print", text: "['slow', 'fast']" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("import asyncio", "async def job(n):", "    await asyncio.sleep(0)", '    print("job", n)', "async def main():", "    t = asyncio.create_task(job(1))", '    print("main")', "    await t", "asyncio.run(main())"),
      options: ["main job 1", "job 1 main", "main"],
      answer: 0,
      output: "main\njob 1",
      check: { compiles: true, stdout: "main\njob 1" },
      explain: L("create_task schedules job, but it only runs when main pauses at await t.", "create_task agenda job, pero solo corre cuando main se pausa en await t.", "create_task で job は予約されるけど、動くのは main が await t で止まったとき。"),
      win: [{ t: "print", text: "main" }, { t: "print", text: "job 1" }],
    },
    {
      kind: "type",
      prompt: L("Wait for both results", "Espera ambos resultados", "両方の結果を待とう"),
      code: code("import asyncio", "async def double(n):", "    return n * 2", "async def main():", "    r = ___ asyncio.gather(double(1), double(2))", "    print(r)", "asyncio.run(main())"),
      answer: "await",
      check: { compiles: true, stdout: "[2, 4]" },
      explain: L("gather gives back an awaitable. await it to get the list of results.", "gather devuelve algo esperable. Usa await para obtener la lista de resultados.", "gather は待てるものを返す。await してはじめて結果のリストが手に入るよ。"),
      win: [{ t: "print", text: "[2, 4]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("import asyncio", "async def slow():", "    await asyncio.sleep(1)", "async def main():", "    try:", "        await asyncio.wait_for(slow(), timeout=0.01)", "    except TimeoutError:", '        print("timeout")', "asyncio.run(main())"),
      options: ["timeout", L("Nothing", "Nada", "何も出ない"), "TimeoutError"],
      answer: 0,
      output: "timeout",
      check: { compiles: true, stdout: "timeout" },
      explain: L("wait_for cancels slow after 0.01 s and raises TimeoutError, which except catches.", "wait_for cancela slow a los 0.01 s y lanza TimeoutError, que except atrapa.", "wait_for は 0.01 秒で slow を取り消して TimeoutError。except が捕まえる。"),
      win: [{ t: "print", text: "timeout" }],
    },
    say(L(
      "One loop, one thread: a blocking call like time.sleep freezes EVERY task. Only await lets others run.",
      "Un loop, un hilo: una llamada bloqueante como time.sleep congela TODAS las tareas. Solo await deja correr a otras.",
      "ループもスレッドも1つ。time.sleep のような止める呼び出しは全タスクを固める。他を動かすのは await だけ。",
    )),
    {
      kind: "pick",
      prompt: L("Let b start while a waits", "Que b empiece mientras a espera", "a が待つ間に b を始めよう"),
      code: code("import asyncio, time", "async def tick(name):", '    print(name, "start")', "    ___", '    print(name, "end")', "async def main():", '    await asyncio.gather(tick("a"), tick("b"))', "asyncio.run(main())"),
      options: ["await asyncio.sleep(0.01)", "time.sleep(0.01)"],
      answer: 0,
      check: { compiles: true, stdout: "a start\nb start\na end\nb end" },
      explain: L("await asyncio.sleep hands the turn to b. time.sleep blocks the loop: a would finish before b starts.", "await asyncio.sleep cede el turno a b. time.sleep bloquea el loop: a terminaría antes de que b empiece.", "await asyncio.sleep は b に順番をゆずる。time.sleep はループを止め、a が終わるまで b は始まらない。"),
      win: [{ t: "print", text: "a start" }, { t: "print", text: "b start" }],
    },
    say(L(
      "CPython's GIL lets one thread run Python code at a time. Threads help waiting (I/O); processes help heavy math.",
      "El GIL de CPython deja que un solo hilo corra código Python a la vez. Los hilos ayudan a esperar (I/O); los procesos, al cálculo pesado.",
      "CPython の GIL では、Python を実行できるスレッドは同時に1つ。待ち（I/O）はスレッド、重い計算はプロセス向き。",
    )),
    {
      kind: "predict",
      prompt: L("Best tool for this job?", "¿La mejor herramienta?", "この仕事に最適なのは？"),
      code: code("# Resize 1,000 images using all 8 CPU cores", "# Standard CPython, pure-Python math"),
      options: ["multiprocessing", "threading", "asyncio"],
      answer: 0,
      explain: L("CPU-heavy work is held back by the GIL in threads. Separate processes each get their own core.", "El trabajo pesado de CPU queda frenado por el GIL en hilos. Los procesos separados usan cada uno su núcleo.", "CPU を使う重い処理は GIL のせいでスレッドでは速くならない。プロセスなら各コアを使える。"),
      win: [{ t: "banner", text: L("8 CORES!", "¡8 NÚCLEOS!", "8コア！") }],
    },
    {
      kind: "run",
      prompt: L("Fix main: it must print got ADA", "Arregla main: debe imprimir got ADA", "main を直して got ADA と表示しよう"),
      starter: code("import asyncio", "", "async def fetch(name):", "    await asyncio.sleep(0)", "    return name.upper()", "", "async def main():", '    result = fetch("ada")', '    print("got", result)', "", "asyncio.run(main())", ""),
      solution: code("import asyncio", "", "async def fetch(name):", "    await asyncio.sleep(0)", "    return name.upper()", "", "async def main():", '    result = await fetch("ada")', '    print("got", result)', "", "asyncio.run(main())", ""),
      expect: "got ADA",
      fallback: String.raw`await\s+fetch\(`,
      explain: L(
        "Without await, result is a coroutine object, not its value. Write result = await fetch(\"ada\").",
        "Sin await, result es un objeto corrutina, no su valor. Escribe result = await fetch(\"ada\").",
        "await がないと result はコルーチンのまま。result = await fetch(\"ada\") と書こう。",
      ),
    },
  ],
};

// ─── 4.5 Boss: the event loop lich ──────────────────────────────────────────
const boss: LessonDef = {
  slug: "event-loop-lich",
  title: L("The event loop lich", "El liche del event loop", "イベントループのリッチ"),
  concept: "async",
  mode: "boss",
  xp: 200,
  enemy: "dragon",
  enemyName: L("EVENT LOOP LICH", "LICHE DEL LOOP", "ループのリッチ"),
  beats: [
    enemySays(L(
      "I AM THE EVENT LOOP LICH. Shared class lists, lazy generators, forgotten awaits: my tower is built of them. Climb!",
      "SOY EL LICHE DEL EVENT LOOP. Listas de clase compartidas, generadores perezosos, awaits olvidados: con eso hice mi torre. ¡Sube!",
      "我はループのリッチ。共有のクラスリスト、怠けるジェネレータ、忘れた await。それが我が塔だ。登ってみよ！",
    )),
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("class Guild:", "    members = []", "    def join(self, name):", "        self.members.append(name)", "a, b = Guild(), Guild()", 'a.join("Ada")', "print(b.members)"),
      options: ["['Ada']", "[]", "AttributeError"], answer: 0, output: "['Ada']",
      check: { compiles: true, stdout: "['Ada']" },
      explain: L("members is ONE class list shared by every guild, so b sees Ada too.", "members es UNA lista de clase compartida por todos los gremios, así b también ve a Ada.", "members はクラスの1つのリストで全員共有。b にも Ada が見える。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("from dataclasses import dataclass", "@dataclass", "class P:", "    x: int", "class Q:", "    def __init__(self, x):", "        self.x = x", "print(P(1) == P(1), Q(1) == Q(1))"),
      options: ["True False", "True True", "False False"], answer: 0, output: "True False",
      check: { compiles: true, stdout: "True False" },
      explain: L("The dataclass got an __eq__ that compares fields. Q has none, so == checks identity.", "La dataclass recibió un __eq__ que compara campos. Q no tiene, así que == revisa identidad.", "dataclass には値で比べる __eq__ がある。Q にはないので同一性で比べる。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("class A:", '    def hi(self): return "A"', "class B(A):", '    def hi(self): return "B" + super().hi()', "class C(B):", "    pass", "print(C().hi())"),
      options: ["BA", "A", "CBA"], answer: 0, output: "BA",
      check: { compiles: true, stdout: "BA" },
      explain: L("C inherits hi from B. B's super() then reaches A.", "C hereda hi de B. Luego el super() de B llega a A.", "C は B の hi を受けつぐ。B の super() が A に届く。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("def gen():", '    print("go")', "    yield 1", "g = gen()", "h = gen()", "print(next(g))"),
      options: ["go 1", "go go 1", "1"], answer: 0, output: "go\n1",
      check: { compiles: true, stdout: "go\n1" },
      explain: L("Only g was asked with next(). h was built but its body never started.", "Solo a g se le pidió next(). h se construyó, pero su cuerpo nunca empezó.", "next() したのは g だけ。h は作っただけで本体は動いていない。"),
    },
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: code("class Door:", "    def __enter__(self):", "        return self", "    def __exit__(self, *exc):", '        print("closed")', "with Door():", "    1 / 0"),
      options: [L("closed, then ZeroDivisionError", "closed y luego ZeroDivisionError", "closed の後 ZeroDivisionError"), L("Only closed", "Solo closed", "closed だけ"), L("Only ZeroDivisionError", "Solo ZeroDivisionError", "ZeroDivisionError だけ")], answer: 0,
      check: { compiles: true, throws: "ZeroDivisionError" },
      explain: L("__exit__ always runs, but it returns None (not True), so the error keeps flying.", "__exit__ siempre corre, pero devuelve None (no True), así el error sigue su camino.", "__exit__ は必ず動くけど None を返す（True じゃない）ので例外はそのまま飛ぶ。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("class Hero:", "    def __init__(self):", "        self._hp = 3", "    @property", "    def hp(self):", "        return self._hp * 10", "h = Hero()", "h._hp = 5", "print(h.hp)"),
      options: ["50", "30", "5"], answer: 0, output: "50",
      check: { compiles: true, stdout: "50" },
      explain: L("The property recomputes on every read: _hp is now 5, so 50.", "La property se recalcula en cada lectura: _hp ahora es 5, así que 50.", "property は読むたびに計算し直す。_hp は 5 なので 50。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("import asyncio", "async def main():", "    asyncio.sleep(0.01)", '    print("done")', "asyncio.run(main())"),
      options: ["done", L("Nothing", "Nada", "何も出ない"), "SyntaxError"], answer: 0, output: "done",
      check: { compiles: true, stdout: "done" },
      explain: L("No await: the sleep coroutine is created and dropped, never run. Python only warns.", "Sin await: la corrutina de sleep se crea y se descarta sin correr. Python solo avisa.", "await がないので sleep は作られて捨てられ、動かない。Python は警告だけ。"),
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: code("def heal(hp: int) -> int:", "    return hp + hp", "print(heal([1]))"),
      options: ["[1, 1]", "TypeError", "2"], answer: 0, output: "[1, 1]",
      check: { compiles: true, stdout: "[1, 1]" },
      explain: L("Hints are not enforced at runtime. A list plus itself is [1, 1].", "Las anotaciones no se imponen al ejecutar. Una lista más sí misma es [1, 1].", "型ヒントは実行時に強制されない。リスト + リストで [1, 1]。"),
    },
    {
      kind: "predict", time: 15, prompt: L("What does the GIL mean?", "¿Qué significa el GIL?", "GIL とは？"),
      code: code("# Standard CPython, one process", "# Two threads run pure-Python loops"),
      options: [L("One thread runs Python at a time", "Un hilo corre Python a la vez", "同時に動くのは1スレッド"), L("Python cannot make threads", "Python no puede crear hilos", "スレッドを作れない"), L("Both run on two cores", "Ambos usan dos núcleos", "2コアで同時に動く")], answer: 0,
      explain: L("The GIL lets only one thread execute Python bytecode at a time. Threads still help when waiting on I/O.", "El GIL deja que un solo hilo ejecute bytecode Python a la vez. Los hilos aún ayudan al esperar I/O.", "GIL では Python のバイトコードを実行できるのは同時に1スレッド。I/O 待ちにはスレッドが役立つ。"),
    },
    {
      kind: "order", time: 20, prompt: L("Build a counting generator", "Arma un generador que cuenta", "数えるジェネレータを組もう"),
      lines: ["def count_up(n):", "    i = 1", "    while i <= n:", "        yield i", "        i += 1", "print(list(count_up(3)))"],
      check: { compiles: true, stdout: "[1, 2, 3]" },
      explain: L("Start i at 1, loop while i <= n, yield i, then step i up.", "Empieza i en 1, repite mientras i <= n, haz yield i y luego súbelo.", "i を 1 から、i <= n の間ループ、yield i して i を増やす。"),
    },
    enemySays(L(
      "Impossible... every await remembered, every door closed. The tower is yours, keeper of the one obvious way.",
      "Imposible... recordaste cada await y cerraste cada puerta. La torre es tuya, guardián del camino obvio.",
      "ありえぬ…await を一つも忘れず、扉をすべて閉じたか。塔はおまえのものだ、明らかな道の守り手よ。",
    )),
  ],
};

export const objectTower: RegionDef = {
  slug: "object-tower",
  name: L("Object Tower", "Torre de Objetos", "オブジェクトの塔"),
  subtitle: L("Classes · generators · with · asyncio", "Clases · generadores · with · asyncio", "クラス・ジェネレータ・with・asyncio"),
  theme: "tower",
  lessons: [classes, inheritance, generators, asyncLesson, boss],
};
