import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 2 · LIFETIME FOREST  (classes and initialization, destructors and RAII, copy vs move and
// the rule of 3/5/0, smart pointers and cycles)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const SAFE = L("Is this code safe?", "¿Este código es seguro?", "このコードは安全？");
const YES = L("Yes", "Sí", "はい");
const NO_GCC = L("No: g++ stops it", "No: g++ lo detiene", "いいえ：g++ が止める");

// Helper types used by many questions. The player sees them in a dialog; checks prepend them.
const HEADERS = "#include <iostream>\n#include <string>\n#include <vector>\n#include <memory>\n#include <utility>\n";

const TORCH_SRC = `struct Torch {
  std::string n;
  Torch(std::string n) : n(n) { std::cout << "+" << n; }
  ~Torch() { std::cout << "-" << n; }
};`;

const ITEM_SRC = `struct Item {
  std::string n;
  Item(std::string n) : n(n) {}
  Item(const Item& o) : n(o.n) { std::cout << "copy "; }
  Item(Item&& o) noexcept : n(std::move(o.n)) { std::cout << "move "; }
};`;

/** Full program: headers + helper type + optional top-level code + main(body). */
const prog = (helper: string, body: string, top = "") => `${HEADERS}\n${helper}\n${top}\nint main() {\n${body}\n}\n`;
const torch = (body: string, top = "") => prog(TORCH_SRC, body, top);
const item = (body: string, top = "") => prog(ITEM_SRC, body, top);

const TORCH_SHORT = TORCH_SRC; // prints + on birth, - on death
const ITEM_SHORT = ITEM_SRC; // announces copies and moves

// ─── 2.1 Forging classes ───────────────────────────────────────────────────
const classes: LessonDef = {
  slug: "forging-classes",
  title: L("Forging classes", "Forjando clases", "クラスをきたえる"),
  concept: "classes",
  mode: "lesson",
  xp: 70,
  enemy: "cpp/ub-imp",
  enemyName: L("ORDER IMP", "DIABLILLO DEL ORDEN", "順番インプ"),
  beats: [
    say(L(
      "Welcome to the Lifetime Forest! A struct is a blueprint: it bundles boxes (members) into one new type.",
      "¡Bienvenido al Bosque de Vida! Un struct es un plano: junta cajas (miembros) en un tipo nuevo.",
      "ライフタイムの森へようこそ！struct は設計図。いくつもの箱（メンバ）を一つの新しい型にまとめる。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and forge a hero", "Pulsa en orden y forja un héroe", "順番に押して、ヒーローをきたえよう"),
      steps: [
        { label: L("BLUEPRINT", "PLANO", "設計図"), line: "struct Hero { std::string name; int hp = 100; };", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "say", actor: "hero", text: L("A plan!", "¡Un plano!", "設計図だ！") }] },
        { label: L("FORGE h", "FORJAR h", "h を作る"), line: 'Hero h{"Ada"};', effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "shield", holder: "ally" }, { t: "tag", actor: "ally", text: "h", value: "Ada 100" }] },
        { label: L("READ hp", "LEER hp", "hp を読む"), line: "std::cout << h.hp;", effects: [{ t: "print", text: "100" }], output: "100" },
        { label: L("SECRET CLASS", "CLASE SECRETA", "秘密のクラス"), line: "class Spy { int secret = 7; };", effects: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "Spy" }] },
        {
          label: L("PEEK", "ESPIAR", "のぞく"),
          line: "Spy s; std::cout << s.secret;",
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Private!", "¡Privado!", "非公開だ！") }],
          error: {
            compiler: "error: 'int Spy::secret' is private within this context",
            plain: L("struct members are public by default; class members are private.", "Los miembros de un struct son públicos por defecto; los de una class, privados.", "struct のメンバは標準で public、class のメンバは private。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Hero {\n  std::string name;\n  int hp = 100;\n};\nHero h{"Ada"};\nstd::cout << h.name << " " << h.hp;',
      options: ["Ada 100", "Ada 0", L("Error: hp missing", "Error: falta hp", "エラー：hp がない")],
      answer: 0,
      output: "Ada 100",
      check: { compiles: true, stdout: "Ada 100" },
      explain: L("{\"Ada\"} fills name; hp keeps its default value 100.", "{\"Ada\"} llena name; hp conserva su valor por defecto, 100.", "{\"Ada\"} で name が入り、hp は初期値の 100 のまま。"),
      win: [{ t: "enter", actor: "ally" }, { t: "item", kind: "shield", holder: "ally" }, { t: "print", text: "Ada 100" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "class Hero {\n  int hp = 100;\n};\nHero h;\nstd::cout << h.hp;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("In a class everything is private until you write public:. main can't read hp.", "En una class todo es privado hasta que escribes public:. main no puede leer hp.", "class は public: と書くまで全部 private。main から hp は読めない。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "struct Point { int x, y; };\nPoint p{1};\nstd::cout << p.x << p.y;",
      options: ["10", "11", L("Garbage for y", "Basura en y", "y はゴミ")],
      answer: 0,
      output: "10",
      check: { compiles: true, stdout: "10" },
      explain: L("Brace init fills members in order; the missing ones become zero.", "Las llaves llenan los miembros en orden; los que faltan quedan en cero.", "{} は順番にメンバを埋め、足りない分は 0 になる。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "struct Point { int x, y; };\nPoint p{1, 2, 3};",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("Point has only two members, so three values are 'too many initializers'.", "Point tiene solo dos miembros, así que tres valores son 'too many initializers'.", "Point のメンバは 2 つだけ。3 つの値は多すぎるエラー。"),
    },
    say(L(
      "A CONSTRUCTOR runs when an object is born. The list after : fills the members: Hero(int h) : hp(h) {}",
      "Un CONSTRUCTOR corre cuando nace un objeto. La lista tras : llena los miembros: Hero(int h) : hp(h) {}",
      "コンストラクタはオブジェクト誕生時に動く。: の後ろのリストでメンバを埋める：Hero(int h) : hp(h) {}",
    )),
    {
      kind: "type",
      prompt: L("Start the member initializer list", "Empieza la lista de inicialización", "初期化リストを始めよう"),
      code: "struct Hero {\n  int hp;\n  Hero(int h) ___ hp(h) {}\n};\nHero a(7);\nstd::cout << a.hp;",
      answer: ":",
      check: { compiles: true, stdout: "7" },
      explain: L("A colon after the parameters starts the list: hp(h) builds hp from h.", "Dos puntos tras los parámetros inician la lista: hp(h) construye hp con h.", "引数の後の : でリストが始まる。hp(h) で h から hp を作るよ。"),
      win: [{ t: "print", text: "7" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Hero {\n  int hp;\n  Hero() : hp(1) { std::cout << "default "; }\n  Hero(int h) : hp(h) { std::cout << "int "; }\n};\nHero a; Hero b(5); Hero c{7};',
      options: ["default int int", "default int default", "int int int"],
      answer: 0,
      output: "default int int",
      check: { compiles: true, stdout: "default int int" },
      explain: L("No arguments picks the default constructor. (5) and {7} both pick Hero(int).", "Sin argumentos se elige el constructor por defecto. (5) y {7} eligen Hero(int).", "引数なしはデフォルトコンストラクタ。(5) も {7} も Hero(int) を選ぶ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Hero {\n  Hero() { std::cout << "born "; }\n};\nHero h();\nstd::cout << "end";',
      options: ["end", "born end", L("Compile error", "Error de compilación", "コンパイルエラー")],
      answer: 0,
      output: "end",
      check: { compiles: true, stdout: "end" },
      explain: L("Hero h(); declares a FUNCTION named h, not an object! No hero is born. Write Hero h; or Hero h{};", "Hero h(); declara una FUNCIÓN llamada h, ¡no un objeto! No nace ningún héroe. Escribe Hero h; o Hero h{};", "Hero h(); は関数 h の宣言で、オブジェクトじゃない！Hero h; か Hero h{}; と書こう。"),
      win: [{ t: "banner", text: L("FUNCTION?!", "¿¡FUNCIÓN!?", "関数？！") }, { t: "print", text: "end" }],
    },
    say(L(
      "Trap! Members are built in the order they are DECLARED in the class, not in the order you list them after :.",
      "¡Trampa! Los miembros se construyen en el orden en que se DECLARAN en la clase, no en el de la lista tras :.",
      "ワナ！メンバが作られる順番は、: の後のリスト順じゃなく、クラスで宣言した順だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Log { Log(const char* s) { std::cout << s; } };\nstruct P {\n  Log b{"b"};\n  Log a{"a"};\n  P() : a("A"), b("B") {}\n};\nP p;',
      options: ["BA", "AB", "baAB"],
      answer: 0,
      output: "BA",
      check: { compiles: true, stdout: "BA" },
      explain: L("b is declared first, so it's built first (with \"B\"), then a. The list order is ignored.", "b se declara primero, así que se construye primero (con \"B\"), luego a. El orden de la lista se ignora.", "b が先に宣言されているので先に作られ（\"B\"）、次に a。リストの順番は無視される。"),
    },
    {
      kind: "predict",
      prompt: SAFE,
      code: "struct P {\n  int b;\n  int a;\n  P() : a(1), b(a + 1) {}\n};",
      options: [L("No: b reads a before a exists", "No: b lee a antes de que exista", "いいえ：b は作られる前の a を読む"), L("Yes: a is listed first", "Sí: a va primero en la lista", "はい：a がリストの先頭")],
      answer: 0,
      check: { compiles: true },
      explain: L("b is declared first, so b(a + 1) runs while a is still garbage: UB. Keep both orders the same.", "b se declara primero, así que b(a + 1) corre con a aún en basura: UB. Mantén ambos órdenes iguales.", "b が先なので、b(a + 1) の時点で a はまだゴミ：UB。順番はそろえよう。"),
      win: [{ t: "say", actor: "enemy", text: L("Foiled!", "¡Frustrado!", "見破られた！") }],
    },
    say(L(
      "explicit stops sneaky conversions. A const member function promises not to change the object, so const objects may call it.",
      "explicit frena conversiones a escondidas. Una función miembro const promete no cambiar el objeto, y los objetos const pueden llamarla.",
      "explicit はこっそり変換を防ぐ。const メンバ関数は変更しない約束で、const オブジェクトから呼べる。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "struct Meters {\n  explicit Meters(int v) : v(v) {}\n  int v;\n};\nvoid walk(Meters m) {}\n\nint main() { walk(5); }",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("explicit forbids turning 5 into Meters silently. You must write walk(Meters(5)).", "explicit prohíbe convertir 5 en Meters en silencio. Debes escribir walk(Meters(5)).", "explicit は 5 を Meters にこっそり変えるのを禁止。walk(Meters(5)) と書こう。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "struct Hero {\n  int hp = 1;\n  int get() { return hp; }\n};\nconst Hero h{};\nstd::cout << h.get();",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("h is const but get() isn't marked const, so it might change h. Write int get() const.", "h es const pero get() no está marcada const, así que podría cambiar h. Escribe int get() const.", "h は const なのに get() は const じゃない。int get() const と書こう。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "struct Counter {\n  inline static int count = 0;\n  Counter() { count++; }\n};\n\nint main() {\n  Counter a, b, c;\n  std::cout << Counter::count;\n}",
      options: ["3", "1", "0"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("A static member is shared by the whole class: one count for every Counter. Three births: 3.", "Un miembro static es compartido por toda la clase: un solo count para todos. Tres nacimientos: 3.", "static メンバはクラス全体で共有。count は一つだけで、3 回生まれたので 3。"),
    },
    say(L(
      "Inside a member function, hp means the member. But a local named hp HIDES it. this->hp always means the member.",
      "Dentro de una función miembro, hp es el miembro. Pero una local llamada hp lo OCULTA. this->hp siempre es el miembro.",
      "メンバ関数の中の hp はメンバ。でも同名のローカル hp があると隠れる。this->hp は常にメンバ。",
    )),
    {
      kind: "run",
      prompt: L("Fix heal: it must print hp: 120", "Arregla heal: debe imprimir hp: 120", "heal を直そう：hp: 120 と表示させて"),
      starter: '#include <iostream>\n\nstruct Hero {\n    int hp = 100;\n    void heal(int amount) {\n        int hp = this->hp;\n        hp += amount;\n    }\n};\n\nint main() {\n    Hero h;\n    h.heal(20);\n    std::cout << "hp: " << h.hp << "\\n";\n}\n',
      solution: '#include <iostream>\n\nstruct Hero {\n    int hp = 100;\n    void heal(int amount) {\n        hp += amount;\n    }\n};\n\nint main() {\n    Hero h;\n    h.heal(20);\n    std::cout << "hp: " << h.hp << "\\n";\n}\n',
      expect: "hp: 120",
      fallback: [String.raw`void\s+heal\s*\(\s*int\s+amount\s*\)\s*\{\s*hp\s*\+=\s*amount`, String.raw`this->hp\s*\+=\s*amount`, String.raw`this->hp\s*=\s*hp\s*;`, String.raw`int\s*&\s*hp\s*=\s*this->hp`],
      explain: L("The local hp was a copy that hid the member. Add to the member itself.", "La hp local era una copia que ocultaba al miembro. Suma al miembro mismo.", "ローカルの hp はメンバを隠すコピーだった。メンバ自体に足そう。"),
    },
  ],
};

// ─── 2.2 Drop the torch: destructors and RAII ──────────────────────────────
const raii: LessonDef = {
  slug: "drop-the-torch",
  title: L("Drop the torch", "Suelta la antorcha", "たいまつを置け"),
  concept: "raii",
  mode: "lesson",
  xp: 75,
  enemy: "cpp/leak-slime",
  enemyName: L("LEAK SLIME", "SLIME FUGA", "リークスライム"),
  beats: [
    say(L(
      "The DESTRUCTOR ~Name() runs when an object dies. Locals die at their closing }, in REVERSE order of birth.",
      "El DESTRUCTOR ~Name() corre cuando un objeto muere. Las locales mueren en su } final, en orden INVERSO al nacer.",
      "デストラクタ ~Name() はオブジェクトが死ぬときに動く。ローカルは } で、生まれた逆順に死ぬ。",
    )),
    say(L(
      "Meet Torch: it prints + and its name when lit, - and its name when dropped.",
      "Conoce a Torch: imprime + y su nombre al encenderse, - y su nombre al soltarse.",
      "Torch を紹介。点くと + と名前、消えると - と名前を表示するよ。",
    ), ),
    { kind: "dialog", speaker: "master", text: L("Here is its blueprint:", "Este es su plano:", "これが設計図："), code: TORCH_SHORT },
    {
      kind: "act",
      prompt: L("Light the torches, then reach the }", "Enciende las antorchas y llega a la }", "たいまつを点けて } まで進もう"),
      steps: [
        { label: L("LIGHT a", "ENCENDER a", "a を点ける"), line: 'Torch a("a");', effects: [{ t: "tag", actor: "hero", text: "a" }, { t: "item", kind: "sword", holder: "hero" }, { t: "print", text: "+a" }], output: "+a" },
        { label: L("LIGHT b", "ENCENDER b", "b を点ける"), line: 'Torch b("b");', effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "item", kind: "sword", holder: "ally" }, { t: "print", text: "+b" }], output: "+b" },
        { label: L("REACH }", "LLEGAR A }", "} に着く"), line: "}", effects: [{ t: "exit", actor: "ally" }, { t: "print", text: "-b" }, { t: "drop" }, { t: "print", text: "-a" }, { t: "banner", text: L("~Torch x2", "~Torch x2", "~Torch x2") }], output: "-b-a" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Torch a("a");\nTorch b("b");',
      options: ["+a+b-b-a", "+a+b-a-b", "+a-a+b-b"],
      answer: 0,
      output: "+a+b-b-a",
      check: { compiles: true, stdout: "+a+b-b-a", program: torch('Torch a("a");\nTorch b("b");') },
      explain: L("Last lit, first dropped: b dies before a, like a stack of plates.", "Último en encenderse, primero en soltarse: b muere antes que a, como una pila de platos.", "最後に点いたものが最初に消える。皿の山のように b が a より先。"),
      win: [{ t: "print", text: "+a+b-b-a" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: '{\n  Torch a("a");\n}\nTorch b("b");',
      options: ["+a-a+b-b", "+a+b-b-a", "+a+b-a-b"],
      answer: 0,
      output: "+a-a+b-b",
      check: { compiles: true, stdout: "+a-a+b-b", program: torch('{\n  Torch a("a");\n}\nTorch b("b");') },
      explain: L("Any { } block is a scope. a dies at its } before b is even born.", "Cualquier bloque { } es un ámbito. a muere en su } antes de que b nazca.", "{ } のブロックはスコープ。a は自分の } で消え、その後 b が生まれる。"),
    },
    {
      kind: "order",
      prompt: L('Output order of: Torch a("a"); { Torch b("b"); }', 'Orden de salida: Torch a("a"); { Torch b("b"); }', '出力順：Torch a("a"); { Torch b("b"); }'),
      lines: ["+a", "+b", "-b", "-a"],
      check: { compiles: true, stdout: "+a+b-b-a", program: torch('Torch a("a");\n{ Torch b("b"); }') },
      explain: L("a is born, b is born, b's block ends (-b), then main ends (-a).", "Nace a, nace b, termina el bloque de b (-b) y luego termina main (-a).", "a 誕生、b 誕生、b のブロック終了で -b、main 終了で -a。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'for (int i = 0; i < 2; ++i) {\n  Torch t(std::to_string(i));\n}',
      options: ["+0-0+1-1", "+0+1-1-0", "+0+1-0-1"],
      answer: 0,
      output: "+0-0+1-1",
      check: { compiles: true, stdout: "+0-0+1-1", program: torch('for (int i = 0; i < 2; ++i) {\n  Torch t(std::to_string(i));\n}') },
      explain: L("The loop body is a scope: each round's torch dies at the } before the next round.", "El cuerpo del bucle es un ámbito: la antorcha de cada vuelta muere en la } antes de la siguiente.", "ループ本体もスコープ。毎回のたいまつは次の回の前に } で消える。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Torch("tmp");\nstd::cout << "|";',
      options: ["+tmp-tmp|", "+tmp|-tmp", "|"],
      answer: 0,
      output: "+tmp-tmp|",
      check: { compiles: true, stdout: "+tmp-tmp|", program: torch('Torch("tmp");\nstd::cout << "|";') },
      explain: L("A nameless TEMPORARY dies at the end of its statement, the ;.", "Un TEMPORAL sin nombre muere al final de su sentencia, en el ;.", "名前のない一時オブジェクトは、その文の終わり（;）で消える。"),
    },
    say(L(
      "Members die too: in REVERSE order of declaration, right after the owner's destructor.",
      "Los miembros también mueren: en orden INVERSO a su declaración, justo tras el destructor del dueño.",
      "メンバも死ぬ。持ち主のデストラクタのすぐ後、宣言の逆順でね。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Pair {\n  Torch x{"x"};\n  Torch y{"y"};\n};\nPair p;',
      options: ["+x+y-y-x", "+x+y-x-y", "+y+x-x-y"],
      answer: 0,
      output: "+x+y-y-x",
      check: { compiles: true, stdout: "+x+y-y-x", program: torch("Pair p;", 'struct Pair {\n  Torch x{"x"};\n  Torch y{"y"};\n};') },
      explain: L("Members are built top to bottom (x, y) and destroyed bottom to top (y, x).", "Los miembros se construyen de arriba abajo (x, y) y se destruyen de abajo arriba (y, x).", "メンバは上から作られ（x, y）、下から壊される（y, x）。"),
    },
    say(L(
      "Heap objects only die on delete. Forget it and the torch burns forever: a LEAK.",
      "Los objetos del heap solo mueren con delete. Si lo olvidas, la antorcha arde para siempre: una FUGA.",
      "ヒープのオブジェクトは delete しないと死なない。忘れるとたいまつは燃え続ける：リーク。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Torch* p = new Torch("h");\nstd::cout << "|";',
      options: ["+h|", "+h|-h", "|"],
      answer: 0,
      output: "+h|",
      check: { compiles: true, stdout: "+h|", program: torch('Torch* p = new Torch("h");\nstd::cout << "|";') },
      explain: L("Nobody calls delete p, so ~Torch never runs: no -h. The memory leaks.", "Nadie llama a delete p, así que ~Torch nunca corre: no hay -h. La memoria se fuga.", "delete p を誰も呼ばないので ~Torch は動かず -h はない。メモリリーク。"),
      win: [{ t: "banner", text: L("LEAK", "FUGA", "リーク") }],
    },
    say(L(
      "RAII: acquire a resource in a constructor, release it in the destructor. std::make_unique gives a heap object an owner that deletes it.",
      "RAII: toma un recurso en el constructor y suéltalo en el destructor. std::make_unique da al objeto del heap un dueño que lo borra.",
      "RAII：コンストラクタで確保、デストラクタで解放。std::make_unique はヒープの物に delete する持ち主をつける。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'auto p = std::make_unique<Torch>("u");\nstd::cout << "|";',
      options: ["+u|-u", "+u|", "|-u"],
      answer: 0,
      output: "+u|-u",
      check: { compiles: true, stdout: "+u|-u", program: torch('auto p = std::make_unique<Torch>("u");\nstd::cout << "|";') },
      explain: L("p is a local owner. When p dies at the }, it deletes the torch: -u.", "p es un dueño local. Cuando p muere en la }, borra la antorcha: -u.", "p はローカルの持ち主。} で p が死ぬとき、たいまつを delete する：-u。"),
    },
    {
      kind: "pick",
      prompt: L("RAII means...", "RAII significa...", "RAII とは…"),
      code: "// RAII: ___",
      options: [
        L("the destructor frees what the constructor took", "el destructor libera lo que tomó el constructor", "コンストラクタで得た物をデストラクタで解放"),
        L("every object lives on the heap", "todo objeto vive en el heap", "すべてのオブジェクトをヒープに置く"),
        L("call delete at the end of each function", "llamar a delete al final de cada función", "関数の最後に毎回 delete を呼ぶ"),
      ],
      answer: 0,
      explain: L("Tie a resource to an object's lifetime and cleanup happens on EVERY exit path automatically.", "Ata un recurso a la vida de un objeto y la limpieza ocurre sola en TODAS las salidas.", "資源をオブジェクトの寿命に結びつければ、どの出口でも自動で後片付けされる。"),
    },
    say(L(
      "A throw is a gust of wind: it leaves the scope, and every local drops its torch on the way out. That's stack unwinding.",
      "Un throw es una ráfaga: sale del ámbito y cada local suelta su antorcha al salir. Eso es stack unwinding.",
      "throw は突風。スコープを飛び出し、途中のローカルは全部たいまつを置いていく。これがスタック巻き戻し。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'try {\n  Torch a("a");\n  throw 1;\n} catch (int) {\n  std::cout << "!";\n}',
      options: ["+a-a!", "+a!-a", "+a!"],
      answer: 0,
      output: "+a-a!",
      check: { compiles: true, stdout: "+a-a!", program: torch('try {\n  Torch a("a");\n  throw 1;\n} catch (int) {\n  std::cout << "!";\n}') },
      explain: L("Leaving the try block destroys a (-a) BEFORE the catch handler runs (!).", "Salir del bloque try destruye a (-a) ANTES de que corra el catch (!).", "try を出るときに a が壊れ（-a）、その後で catch が動く（!）。"),
      win: [{ t: "shake" }, { t: "print", text: "+a-a!" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Boom {\n  Torch t{"t"};\n  Boom() { throw 1; }\n  ~Boom() { std::cout << "~Boom"; }\n};\ntry { Boom b; } catch (int) { std::cout << "!"; }',
      options: ["+t-t!", "+t-t~Boom!", "+t!"],
      answer: 0,
      output: "+t-t!",
      check: { compiles: true, stdout: "+t-t!", program: torch('try { Boom b; } catch (int) { std::cout << "!"; }', 'struct Boom {\n  Torch t{"t"};\n  Boom() { throw 1; }\n  ~Boom() { std::cout << "~Boom"; }\n};') },
      explain: L("Boom was never fully born, so ~Boom never runs. Its finished member t is still destroyed.", "Boom nunca terminó de nacer, así que ~Boom no corre. Su miembro t, ya construido, sí se destruye.", "Boom は生まれきらなかったので ~Boom は動かない。でも完成済みのメンバ t は壊される。"),
    },
    {
      kind: "run",
      prompt: L("Fix work so the lock is always released", "Arregla work para soltar siempre el candado", "work を直して、ロックが必ず外れるように"),
      starter: '#include <iostream>\n\nstruct Lock {\n    Lock() { std::cout << "lock "; }\n    ~Lock() { std::cout << "unlock "; }\n};\n\nvoid work(bool fail) {\n    Lock* l = new Lock();\n    if (fail) return;\n    delete l;\n}\n\nint main() {\n    work(true);\n    std::cout << "done\\n";\n}\n',
      solution: '#include <iostream>\n\nstruct Lock {\n    Lock() { std::cout << "lock "; }\n    ~Lock() { std::cout << "unlock "; }\n};\n\nvoid work(bool fail) {\n    Lock l;\n    if (fail) return;\n}\n\nint main() {\n    work(true);\n    std::cout << "done\\n";\n}\n',
      expect: "unlock done",
      fallback: [String.raw`\bLock\s+\w+\s*;`, String.raw`\bLock\s+\w+\s*\{\s*\}`, String.raw`std::unique_ptr\s*<\s*Lock\s*>`, String.raw`make_unique\s*<\s*Lock\s*>`],
      explain: L("The early return skipped delete. A local Lock (RAII) unlocks at the } on every path.", "El return temprano se saltaba el delete. Un Lock local (RAII) se suelta en la } en todos los caminos.", "早めの return で delete が飛ばされた。ローカルの Lock（RAII）ならどの道でも } で外れる。"),
    },
  ],
};

// ─── 2.3 Give or clone: copy and move ──────────────────────────────────────
const moves: LessonDef = {
  slug: "give-or-clone",
  title: L("Give or clone", "Dar o copiar", "渡す？コピー？"),
  concept: "move",
  mode: "lesson",
  xp: 80,
  enemy: "cpp/dangling-wraith",
  enemyName: L("HOLLOW WRAITH", "ESPECTRO HUECO", "からっぽ亡霊"),
  beats: [
    say(L(
      "Copying a big object duplicates everything. MOVING steals its insides instead: fast, and the source is left empty.",
      "Copiar un objeto grande lo duplica todo. MOVERLO roba sus entrañas: rápido, y el origen queda vacío.",
      "大きなオブジェクトのコピーは全部を複製する。ムーブは中身を奪うだけ。速くて、元はからっぽになる。",
    )),
    { kind: "dialog", speaker: "master", text: L("Item announces which special member runs:", "Item anuncia qué miembro especial corre:", "Item はどの特殊メンバが動いたか教えてくれる："), code: ITEM_SHORT },
    {
      kind: "act",
      prompt: L("Press in order: clone, then give", "Pulsa en orden: copia y luego da", "順番に押そう：コピー、次に渡す"),
      steps: [
        { label: L("FORGE a", "FORJAR a", "a を作る"), line: 'Item a("gem");', effects: [{ t: "tag", actor: "hero", text: "a" }, { t: "item", kind: "gem", holder: "hero" }] },
        { label: L("COPY TO b", "COPIAR A b", "b にコピー"), line: "Item b = a;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "clone", to: "ally" }, { t: "banner", text: L("COPY", "COPIA", "コピー") }, { t: "print", text: "copy " }], output: "copy " },
        { label: L("MOVE TO c", "MOVER A c", "c にムーブ"), line: "Item c = std::move(a);", effects: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "c" }, { t: "give", to: "enemy" }, { t: "banner", text: L("MOVE", "MOVER", "ムーブ") }, { t: "print", text: "move " }], output: "move " },
        { label: L("LOOK AT a", "MIRAR a", "a を見る"), line: "// a: valid but unspecified", effects: [{ t: "say", actor: "hero", text: L("My hands are empty", "Mis manos están vacías", "手がからっぽ") }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Item a("gem");\nItem b = a;',
      options: ["copy", "move", L("Nothing", "Nada", "何も出ない")],
      answer: 0,
      output: "copy",
      check: { compiles: true, stdout: "copy", program: item('Item a("gem");\nItem b = a;') },
      explain: L("a is a named object still in use, so b is built by the copy constructor.", "a es un objeto con nombre aún en uso, así que b se construye con el constructor de copia.", "a は名前のある使用中のオブジェクト。だから b はコピーコンストラクタで作られる。"),
    },
    {
      kind: "type",
      prompt: L("Move a into b instead", "Mejor mueve a hacia b", "a を b にムーブしよう"),
      code: 'Item a("gem");\nItem b = std::___(a);',
      answer: "move",
      check: { compiles: true, stdout: "move", program: item('Item a("gem");\nItem b = std::move(a);') },
      explain: L("std::move(a) says 'you may steal from a', so the move constructor runs.", "std::move(a) dice 'puedes robar de a', así que corre el constructor de movimiento.", "std::move(a) は「a から奪っていいよ」の合図。ムーブコンストラクタが動く。"),
      win: [{ t: "give", to: "ally" }, { t: "print", text: "move " }],
    },
    say(L(
      "std::move moves NOTHING by itself: it only casts, marking the object as 'free to steal'. A constructor does the stealing.",
      "std::move no mueve NADA por sí solo: solo convierte, marcando el objeto como 'libre para robar'. Un constructor roba.",
      "std::move 自体は何もムーブしない。「奪ってOK」と印をつけるだけ。奪うのはコンストラクタ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Item a("gem");\nItem&& r = std::move(a);\nstd::cout << "none";',
      options: ["none", "move none", "copy none"],
      answer: 0,
      output: "none",
      check: { compiles: true, stdout: "none", program: item('Item a("gem");\nItem&& r = std::move(a);\nstd::cout << "none";') },
      explain: L("r is just a reference to a. No new Item is built, so no constructor runs.", "r es solo una referencia a a. No se construye ningún Item nuevo, así que no corre ningún constructor.", "r は a への参照にすぎない。新しい Item は作られないので何も動かない。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const Item a("gem");\nItem b = std::move(a);',
      options: ["copy", "move", L("Compile error", "Error de compilación", "コンパイルエラー")],
      answer: 0,
      output: "copy",
      check: { compiles: true, stdout: "copy", program: item('const Item a("gem");\nItem b = std::move(a);') },
      explain: L("You can't steal from a const object, so the move silently becomes a copy.", "No puedes robar de un objeto const, así que el move se vuelve una copia en silencio.", "const からは奪えない。だからムーブはこっそりコピーになる。"),
      win: [{ t: "banner", text: L("COPY", "COPIA", "コピー") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'void take(Item i) {}\n// in main:\nItem a("gem");\ntake(a);\ntake(std::move(a));',
      options: ["copy move", "copy copy", "move move"],
      answer: 0,
      output: "copy move",
      check: { compiles: true, stdout: "copy move", program: item('Item a("gem");\ntake(a);\ntake(std::move(a));', "void take(Item i) {}") },
      explain: L("A by-value parameter copies an lvalue (a) and moves an rvalue (std::move(a)).", "Un parámetro por valor copia un lvalue (a) y mueve un rvalue (std::move(a)).", "値渡しの引数は lvalue（a）ならコピー、rvalue（std::move(a)）ならムーブ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'Item make() { return Item("x"); }\n// in main:\nItem a = make();\nstd::cout << "done";',
      options: ["done", "move done", "copy done"],
      answer: 0,
      output: "done",
      check: { compiles: true, stdout: "done", program: item('Item a = make();\nstd::cout << "done";', 'Item make() { return Item("x"); }') },
      explain: L("Returning a fresh temporary is built straight into a (guaranteed copy elision): no copy, no move.", "Un temporal devuelto se construye directo en a (elisión de copia garantizada): ni copia ni move.", "新しく作った一時オブジェクトを返すと a に直接作られる（コピー省略の保証）。"),
    },
    {
      kind: "pick",
      prompt: L("After the move, what may you do with s?", "Tras el move, ¿qué puedes hacer con s?", "ムーブ後、s に何をしていい？"),
      code: 'std::string s = "gem";\nstd::string t = std::move(s);\n// s: ___',
      options: [
        L("assign it or let it die", "asignarle o dejarla morir", "代入するか、死なせる"),
        L("read it: still \"gem\"", "leerla: sigue siendo \"gem\"", "読む：まだ \"gem\""),
        L("nothing: it's destroyed", "nada: está destruida", "何も：もう壊れた"),
      ],
      answer: 0,
      check: { compiles: true },
      explain: L("A moved-from object is valid but UNSPECIFIED. Give it a new value or let it go out of scope.", "Un objeto movido es válido pero NO ESPECIFICADO. Dale un valor nuevo o deja que salga del ámbito.", "ムーブ後のオブジェクトは有効だが中身は不定。新しい値を入れるか、スコープ外へ。"),
    },
    say(L(
      "Rule of 3/5: write one of destructor, copy or move, and you likely need them all. Rule of 0: write none; let members manage it.",
      "Regla de 3/5: si escribes destructor, copia o move, quizá necesites todos. Regla de 0: no escribas ninguno.",
      "3/5 の法則：デストラクタ・コピー・ムーブのどれかを書くなら全部必要かも。0 の法則：何も書かない。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'Item a("a");\nItem b("b");\nb = a;',
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false, program: item('Item a("a");\nItem b("b");\nb = a;') },
      explain: L("Item declares a move constructor, so its implicit copy ASSIGNMENT is deleted.", "Item declara un constructor de movimiento, así que su ASIGNACIÓN de copia implícita se elimina.", "Item はムーブコンストラクタを宣言したので、暗黙のコピー代入は削除される。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "struct Bag { std::unique_ptr<int> p; };\nBag a;\nBag b = a;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("A unique_ptr can't be copied, so a class holding one is move-only: 'use of deleted function'.", "Un unique_ptr no se copia, así que una clase que lo tiene solo se mueve: 'use of deleted function'.", "unique_ptr はコピー不可。それを持つクラスもムーブ専用になる。"),
    },
    {
      kind: "pick",
      prompt: L("Only a destructor deletes a raw pointer...", "Solo un destructor borra un puntero crudo...", "生ポインタを消すデストラクタだけ書くと…"),
      code: "// copying it causes ___",
      options: [
        L("a double delete: follow rule 3/5 or 0", "un doble delete: aplica la regla 3/5 o 0", "二重 delete：3/5 か 0 の法則に従う"),
        L("nothing: the compiler fixes it", "nada: el compilador lo arregla", "何も：コンパイラが直す"),
      ],
      answer: 0,
      explain: L("The default copy copies the pointer, so both objects delete it. Use std::unique_ptr (rule of 0).", "La copia por defecto copia el puntero, y ambos objetos lo borran. Usa std::unique_ptr (regla de 0).", "デフォルトのコピーはポインタだけ複製し、両方が delete する。unique_ptr を使おう。"),
    },
    say(L(
      "noexcept promises 'no exceptions'. A vector moves old items when it grows only if their move is noexcept.",
      "noexcept promete 'sin excepciones'. Un vector mueve sus elementos al crecer solo si su move es noexcept.",
      "noexcept は「例外を投げない」約束。vector が伸びるとき、ムーブが noexcept なら要素をムーブする。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::vector<Item> v;\nv.reserve(1);\nv.emplace_back("a");\nv.emplace_back("b");',
      options: ["move", "copy", "move move"],
      answer: 0,
      output: "move",
      check: { compiles: true, stdout: "move", program: item('std::vector<Item> v;\nv.reserve(1);\nv.emplace_back("a");\nv.emplace_back("b");') },
      explain: L("The 2nd item doesn't fit, so the vector reallocates and MOVES \"a\" (noexcept). emplace_back builds in place.", "El 2.º no cabe: el vector se agranda y MUEVE \"a\" (noexcept). emplace_back construye en su lugar.", "2 個目が入らず再確保。noexcept なので \"a\" をムーブ。emplace_back はその場で作る。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "void a() noexcept {}\nvoid b() {}\n\nint main() {\n  std::cout << noexcept(a()) << noexcept(b());\n}",
      options: ["10", "11", "01"],
      answer: 0,
      output: "10",
      check: { compiles: true, stdout: "10" },
      explain: L("The noexcept(...) operator asks the compiler: only a() promised not to throw.", "El operador noexcept(...) le pregunta al compilador: solo a() prometió no lanzar.", "noexcept(...) 演算子はコンパイラに聞く。投げない約束をしたのは a() だけ。"),
    },
    {
      kind: "run",
      prompt: L("Move the items: it must print a has 0, b has 3", "Mueve los ítems: debe imprimir a has 0, b has 3", "ムーブしよう：a has 0, b has 3 と表示"),
      starter: '#include <iostream>\n#include <vector>\n\nstruct Bag {\n    std::vector<int> items;\n};\n\nint main() {\n    Bag a{{1, 2, 3}};\n    Bag b = a;\n    std::cout << "a has " << a.items.size() << ", b has " << b.items.size() << "\\n";\n}\n',
      solution: '#include <iostream>\n#include <utility>\n#include <vector>\n\nstruct Bag {\n    std::vector<int> items;\n};\n\nint main() {\n    Bag a{{1, 2, 3}};\n    Bag b = std::move(a);\n    std::cout << "a has " << a.items.size() << ", b has " << b.items.size() << "\\n";\n}\n',
      expect: "a has 0, b has 3",
      fallback: [String.raw`Bag\s+b\s*=\s*std::move\s*\(\s*a\s*\)`, String.raw`Bag\s+b\s*[({]\s*std::move\s*\(\s*a\s*\)`],
      explain: L("Bag follows the rule of 0: its implicit move moves the vector, which is left empty.", "Bag sigue la regla de 0: su move implícito mueve el vector, que queda vacío.", "Bag は 0 の法則。暗黙のムーブが vector をムーブし、元は空になる。"),
    },
  ],
};

// ─── 2.4 Smart relics: unique, shared, weak ────────────────────────────────
const smart: LessonDef = {
  slug: "smart-relics",
  title: L("Smart relics", "Reliquias inteligentes", "スマートな秘宝"),
  concept: "smart-pointers",
  mode: "lesson",
  xp: 80,
  enemy: "cpp/leak-slime",
  enemyName: L("CYCLE SLIME", "SLIME CÍCLICO", "循環スライム"),
  beats: [
    say(L(
      "Smart pointers own heap objects for you. unique_ptr: ONE owner, it can be moved but never copied.",
      "Los punteros inteligentes son dueños de objetos del heap. unique_ptr: UN dueño, se puede mover pero nunca copiar.",
      "スマートポインタがヒープの物を持ってくれる。unique_ptr は持ち主ひとり。ムーブはできてもコピー不可。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and pass the relic", "Pulsa en orden y pasa la reliquia", "順番に押して、秘宝を渡そう"),
      steps: [
        { label: L("MAKE p", "CREAR p", "p を作る"), line: "auto p = std::make_unique<int>(5);", effects: [{ t: "tag", actor: "hero", text: "p" }, { t: "item", kind: "gem", holder: "hero" }] },
        {
          label: L("COPY TO q", "COPIAR A q", "q にコピー"),
          line: "auto q = p;",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Only one owner!", "¡Un solo dueño!", "持ち主はひとり！") }],
          error: {
            compiler: "error: use of deleted function 'std::unique_ptr<int>::unique_ptr(const std::unique_ptr<int>&)'",
            plain: L("unique_ptr's copy constructor is deleted: two owners would delete twice.", "El constructor de copia de unique_ptr está eliminado: dos dueños borrarían dos veces.", "unique_ptr のコピーは削除ずみ。持ち主が 2 人だと 2 回 delete してしまう。"),
          },
        },
        { label: L("MOVE TO q", "MOVER A q", "q にムーブ"), line: "auto q = std::move(p);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "q" }, { t: "give", to: "ally" }, { t: "value", actor: "hero", text: "nullptr" }] },
        { label: L("READ *q", "LEER *q", "*q を読む"), line: "std::cout << *q;", effects: [{ t: "print", text: "5" }], output: "5" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "auto p = std::make_unique<int>(5);\nauto q = std::move(p);\nstd::cout << (p == nullptr) << *q;",
      options: ["15", "05", "55"],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("Moving a unique_ptr hands the object to q and leaves p as nullptr (true prints 1).", "Mover un unique_ptr entrega el objeto a q y deja p en nullptr (true se imprime 1).", "unique_ptr をムーブすると中身は q へ、p は nullptr（true は 1）。"),
      setup: [{ t: "tag", actor: "hero", text: "p" }, { t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "enter", actor: "ally" }, { t: "give", to: "ally" }, { t: "print", text: "15" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "auto p = std::make_unique<int>(1);\nstd::vector<std::unique_ptr<int>> v;\nv.push_back(p);",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("push_back(p) would copy p. Write v.push_back(std::move(p)) to hand it over.", "push_back(p) copiaría p. Escribe v.push_back(std::move(p)) para entregarlo.", "push_back(p) はコピーになる。v.push_back(std::move(p)) で渡そう。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'auto p = std::make_unique<Torch>("a");\np.reset();\nstd::cout << "|";',
      options: ["+a-a|", "+a|-a", "+a|"],
      answer: 0,
      output: "+a-a|",
      check: { compiles: true, stdout: "+a-a|", program: torch('auto p = std::make_unique<Torch>("a");\np.reset();\nstd::cout << "|";') },
      explain: L("reset() deletes the owned torch right away, before the |.", "reset() borra la antorcha de inmediato, antes del |.", "reset() は持っているたいまつをすぐ delete。| より先。"),
    },
    say(L(
      "shared_ptr: MANY owners with a counter. Each copy adds a rope; the object dies when the last rope is cut.",
      "shared_ptr: MUCHOS dueños con un contador. Cada copia agrega una cuerda; el objeto muere al cortar la última.",
      "shared_ptr は持ち主が何人もいてカウンタつき。コピーごとにロープが増え、最後のロープが切れると死ぬ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "auto a = std::make_shared<int>(1);\nauto b = a;\nstd::cout << a.use_count();",
      options: ["2", "1", "0"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("a and b share one int, so the count is 2.", "a y b comparten un int, así que la cuenta es 2.", "a と b が一つの int を共有。カウントは 2。"),
      setup: [{ t: "tag", actor: "hero", text: "a" }, { t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "lend", to: "ally" }, { t: "value", actor: "hero", text: "2" }, { t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "auto a = std::make_shared<int>(1);\n{\n  auto b = a;\n  std::cout << a.use_count();\n}\nstd::cout << a.use_count();",
      options: ["21", "22", "11"],
      answer: 0,
      output: "21",
      check: { compiles: true, stdout: "21" },
      explain: L("Inside the block b adds an owner (2). At the } b dies and the count drops to 1.", "Dentro del bloque b agrega un dueño (2). En la } b muere y la cuenta baja a 1.", "ブロック内で b が加わり 2。} で b が死んで 1 に戻る。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::shared_ptr<int> p;\nstd::cout << p.use_count() << (p ? "y" : "n");',
      options: ["0n", "1n", "0y"],
      answer: 0,
      output: "0n",
      check: { compiles: true, stdout: "0n" },
      explain: L("An empty shared_ptr owns nothing: count 0, and it tests as false.", "Un shared_ptr vacío no es dueño de nada: cuenta 0, y se evalúa como false.", "空の shared_ptr は何も持たない。カウント 0 で false あつかい。"),
    },
    say(L(
      "weak_ptr watches a shared object WITHOUT owning it. lock() gives a shared_ptr if it's still alive.",
      "weak_ptr observa un objeto compartido SIN ser dueño. lock() da un shared_ptr si sigue vivo.",
      "weak_ptr は共有オブジェクトを持たずに見守る。lock() はまだ生きていれば shared_ptr をくれる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "std::weak_ptr<int> w;\n{\n  auto s = std::make_shared<int>(7);\n  w = s;\n  std::cout << w.expired();\n}\nstd::cout << w.expired();",
      options: ["01", "00", "11"],
      answer: 0,
      output: "01",
      check: { compiles: true, stdout: "01" },
      explain: L("Inside the block s keeps it alive (0). w doesn't count, so at the } the int dies (1).", "Dentro del bloque s lo mantiene vivo (0). w no cuenta, así que en la } el int muere (1).", "ブロック内は s が生かす（0）。w は数に入らないので } で int は死ぬ（1）。"),
    },
    {
      kind: "type",
      prompt: L("Get a temporary owner from w", "Obtén un dueño temporal desde w", "w から一時的な持ち主を得よう"),
      code: 'auto s = std::make_shared<int>(7);\nstd::weak_ptr<int> w = s;\nif (auto p = w.___())\n  std::cout << *p << " " << s.use_count();',
      answer: "lock",
      check: { compiles: true, stdout: "7 2" },
      explain: L("lock() returns a shared_ptr: while p lives the count is 2 (s and p).", "lock() devuelve un shared_ptr: mientras p vive la cuenta es 2 (s y p).", "lock() は shared_ptr を返す。p がいる間カウントは 2（s と p）。"),
    },
    say(L(
      "Danger: two shared objects holding each other form a CYCLE. Neither count reaches 0, so they leak forever.",
      "Peligro: dos objetos compartidos que se sostienen entre sí forman un CICLO. Ninguna cuenta llega a 0: fuga eterna.",
      "危険：互いを shared_ptr で持ち合うと循環になる。カウントが 0 にならず永遠にリーク。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'struct Node {\n  std::shared_ptr<Node> next;\n  ~Node() { std::cout << "bye "; }\n};\n{\n  auto a = std::make_shared<Node>();\n  auto b = std::make_shared<Node>();\n  a->next = b; b->next = a;\n}\nstd::cout << "end";',
      options: ["end", "bye bye end", "bye end"],
      answer: 0,
      output: "end",
      check: { compiles: true, stdout: "end" },
      explain: L("Each node holds the other, so both counts stay at 1 after the }. No destructor runs: a leak.", "Cada nodo sostiene al otro, así que ambas cuentas quedan en 1 tras la }. Ningún destructor corre: fuga.", "互いに持ち合うので } の後もカウントは 1。デストラクタは動かずリーク。"),
      win: [{ t: "banner", text: L("LEAK", "FUGA", "リーク") }],
    },
    {
      kind: "pick",
      prompt: L("Default smart pointer, one owner", "Puntero inteligente por defecto, un dueño", "持ち主ひとりの基本スマートポインタ"),
      code: "std::___<Torch> t;",
      options: ["unique_ptr", "shared_ptr", "weak_ptr"],
      answer: 0,
      check: { compiles: true, program: torch("std::unique_ptr<Torch> t;") },
      explain: L("unique_ptr costs nothing extra over a raw pointer. Use shared_ptr only for real shared ownership.", "unique_ptr no cuesta nada extra frente a un puntero crudo. Usa shared_ptr solo si de verdad se comparte.", "unique_ptr は生ポインタと同じコスト。本当に共有するときだけ shared_ptr。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "auto arr = std::make_unique<int[]>(3);\nstd::cout << arr[2];",
      options: ["0", L("Garbage", "Basura", "ゴミ"), "3"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("make_unique<int[]>(3) builds three value-initialized ints: all zeros.", "make_unique<int[]>(3) crea tres int inicializados a valor: todos ceros.", "make_unique<int[]>(3) は値初期化された int を 3 個作る。全部 0。"),
    },
    {
      kind: "run",
      prompt: L("Break the cycle: Child only watches its parent", "Rompe el ciclo: Child solo observa a su padre", "循環を断て：Child は親を見守るだけ"),
      starter: '#include <iostream>\n#include <memory>\n\nstruct Child;\nstruct Parent {\n    std::shared_ptr<Child> child;\n    ~Parent() { std::cout << "parent "; }\n};\nstruct Child {\n    std::shared_ptr<Parent> parent;\n    ~Child() { std::cout << "child "; }\n};\n\nint main() {\n    {\n        auto p = std::make_shared<Parent>();\n        auto c = std::make_shared<Child>();\n        p->child = c;\n        c->parent = p;\n    }\n    std::cout << "end\\n";\n}\n',
      solution: '#include <iostream>\n#include <memory>\n\nstruct Child;\nstruct Parent {\n    std::shared_ptr<Child> child;\n    ~Parent() { std::cout << "parent "; }\n};\nstruct Child {\n    std::weak_ptr<Parent> parent;\n    ~Child() { std::cout << "child "; }\n};\n\nint main() {\n    {\n        auto p = std::make_shared<Parent>();\n        auto c = std::make_shared<Child>();\n        p->child = c;\n        c->parent = p;\n    }\n    std::cout << "end\\n";\n}\n',
      expect: "parent child",
      fallback: [String.raw`weak_ptr\s*<\s*Parent\s*>\s+parent`],
      explain: L("A weak_ptr doesn't own, so Parent's count hits 0 at the }. Parent dies, then releases Child.", "Un weak_ptr no es dueño: la cuenta de Parent llega a 0 en la }. Parent muere y luego suelta a Child.", "weak_ptr は持たないので } で Parent のカウントが 0 に。Parent が死に、次に Child が解放。"),
    },
  ],
};

// ─── 2.5 Boss: Lifetime Lich ───────────────────────────────────────────────
const boss: LessonDef = {
  slug: "lifetime-lich",
  title: L("Boss: Lifetime Lich", "Jefe: Liche del Tiempo", "ボス：寿命のリッチ"),
  concept: "lifetimes",
  mode: "boss",
  xp: 190,
  enemy: "ghost",
  enemyName: L("LIFETIME LICH", "LICHE DEL TIEMPO", "寿命のリッチ"),
  beats: [
    enemySays(L(
      "I AM THE LIFETIME LICH. I decide when objects are born and when they die. Can you read my rituals?",
      "SOY EL LICHE DEL TIEMPO. Yo decido cuándo nacen y mueren los objetos. ¿Sabes leer mis rituales?",
      "我は寿命のリッチ。オブジェクトの生と死を決める者。我が儀式を読み解けるか？",
    )),
    { kind: "predict", time: 12, prompt: PRINT, code: 'Item a("x");\nItem b(a);\nItem c(std::move(b));', options: ["copy move", "copy copy", "move move"], answer: 0, output: "copy move", check: { compiles: true, stdout: "copy move", program: item('Item a("x");\nItem b(a);\nItem c(std::move(b));') }, explain: L("b(a) copies a; c(std::move(b)) steals from b.", "b(a) copia a; c(std::move(b)) roba de b.", "b(a) は a のコピー、c(std::move(b)) は b から奪う。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'std::vector<Item> v;\nv.push_back(Item("t"));', options: ["move", "copy", "copy move"], answer: 0, output: "move", check: { compiles: true, stdout: "move", program: item('std::vector<Item> v;\nv.push_back(Item("t"));') }, explain: L("Item(\"t\") is a temporary, so push_back moves it into the vector.", "Item(\"t\") es un temporal, así que push_back lo mueve al vector.", "Item(\"t\") は一時オブジェクト。push_back はムーブで入れる。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "auto p = std::make_shared<int>(1);\nauto q = p;\np.reset();\nstd::cout << q.use_count() << *q;", options: ["11", "21", "01"], answer: 0, output: "11", check: { compiles: true, stdout: "11" }, explain: L("p lets go, so only q owns the int now: count 1, value still 1.", "p suelta, así que solo q es dueño del int: cuenta 1, valor aún 1.", "p が手放し、持ち主は q だけ。カウント 1、値は 1 のまま。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'Torch a("a");\n{\n  Torch b("b");\n  auto c = std::make_unique<Torch>("c");\n}\nTorch d("d");', options: ["+a+b+c-c-b+d-d-a", "+a+b+c-b-c+d-d-a", "+a+b+c+d-d-c-b-a"], answer: 0, output: "+a+b+c-c-b+d-d-a", check: { compiles: true, stdout: "+a+b+c-c-b+d-d-a", program: torch('Torch a("a");\n{\n  Torch b("b");\n  auto c = std::make_unique<Torch>("c");\n}\nTorch d("d");') }, explain: L("At the inner }, c's owner dies first (-c), then b. d is born after, and dies before a.", "En la } interna muere primero el dueño de c (-c), luego b. d nace después y muere antes que a.", "内側の } で c の持ち主が先に死に（-c）、次に b。d は後で生まれ a より先に死ぬ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'Torch make(std::string n) {\n  return Torch(n);\n}\n// in main:\nTorch t = make("m");\nstd::cout << "|";', options: ["+m|-m", "+m-m|-m", "+m|"], answer: 0, output: "+m|-m", check: { compiles: true, stdout: "+m|-m", program: torch('Torch t = make("m");\nstd::cout << "|";', "Torch make(std::string n) {\n  return Torch(n);\n}") }, explain: L("Guaranteed copy elision: the returned temporary IS t. One torch, one -m at the end.", "Elisión de copia garantizada: el temporal devuelto ES t. Una antorcha, un -m al final.", "コピー省略の保証で、返した一時オブジェクトが t そのもの。たいまつは 1 本。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'std::vector<Item> v;\nv.reserve(2);\nItem a("x");\nv.push_back(a);\nv.push_back(std::move(a));', options: ["copy move", "copy copy", "move move"], answer: 0, output: "copy move", check: { compiles: true, stdout: "copy move", program: item('std::vector<Item> v;\nv.reserve(2);\nItem a("x");\nv.push_back(a);\nv.push_back(std::move(a));') }, explain: L("Room for 2 means no reallocation: push_back(a) copies, push_back(std::move(a)) moves.", "Espacio para 2: no hay realocación. push_back(a) copia, push_back(std::move(a)) mueve.", "2 個分あるので再確保なし。push_back(a) はコピー、std::move(a) はムーブ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'struct Spy {\n  Spy() { std::cout << "D"; }\n  Spy(const Spy&) { std::cout << "C"; }\n  Spy& operator=(const Spy&) { std::cout << "A"; return *this; }\n};\nSpy a; Spy b = a; Spy c; c = a;', options: ["DCDA", "DADA", "DCDC"], answer: 0, output: "DCDA", check: { compiles: true, stdout: "DCDA" }, explain: L("Spy b = a builds a NEW object: copy constructor (C). c = a changes an existing one: assignment (A).", "Spy b = a crea un objeto NUEVO: constructor de copia (C). c = a cambia uno existente: asignación (A).", "Spy b = a は新しく作るのでコピーコンストラクタ（C）。c = a は既存への代入（A）。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "auto p = std::make_unique<int>(5);\nauto q = p;", options: [YES, NO_GCC], answer: 1, check: { compiles: false }, explain: L("unique_ptr has one owner only: its copy constructor is deleted. Use std::move(p).", "unique_ptr tiene un solo dueño: su constructor de copia está eliminado. Usa std::move(p).", "unique_ptr の持ち主はひとり。コピーは削除ずみ。std::move(p) を使おう。") },
    { kind: "predict", time: 12, prompt: SAFE, code: 'const std::string& f() {\n  return "hi";\n}\n\nint main() { f(); }', options: [L("No: the temporary dies at return", "No: el temporal muere en el return", "いいえ：一時オブジェクトは return で死ぬ"), L("Yes: literals live forever", "Sí: los literales viven siempre", "はい：リテラルは永遠")], answer: 0, check: { compiles: true }, explain: L("\"hi\" becomes a temporary std::string that dies at the return. The reference dangles; g++ warns.", "\"hi\" se vuelve un std::string temporal que muere en el return. La referencia queda colgando; g++ avisa.", "\"hi\" は一時的な std::string になり return で死ぬ。参照はダングリング。g++ も警告。") },
    {
      kind: "pick", time: 15,
      prompt: L("The rule of zero says...", "La regla de cero dice...", "0 の法則とは…"),
      code: "// rule of 0: ___",
      options: [
        L("let members like vector manage it", "deja que miembros como vector lo manejen", "vector などのメンバに任せる"),
        L("write all five special members", "escribe los cinco miembros especiales", "特殊メンバを 5 つ全部書く"),
        L("never use classes", "nunca uses clases", "クラスを使わない"),
      ],
      answer: 0,
      explain: L("Members like std::string, std::vector and std::unique_ptr already copy, move and clean up correctly.", "Miembros como std::string, std::vector y std::unique_ptr ya copian, mueven y limpian bien.", "std::string、vector、unique_ptr などは、コピーもムーブも後片付けも正しくこなす。"),
    },
    enemySays(L(
      "No... my rituals are broken. You know when every object lives and dies. The castle of shapes awaits!",
      "No... mis rituales se rompen. Sabes cuándo vive y muere cada objeto. ¡El castillo de las formas te espera!",
      "ばかな…儀式が破られた。お前はすべての生と死を知った。変身の城が待っているぞ！",
    )),
  ],
};

export const lifetimeForest: RegionDef = {
  slug: "lifetime-forest",
  name: L("Lifetime Forest", "Bosque de Vida", "ライフタイムの森"),
  subtitle: L("classes · RAII · move · smart pointers", "clases · RAII · move · punteros smart", "クラス・RAII・ムーブ・スマポ"),
  theme: "forest",
  lessons: [classes, raii, moves, smart, boss],
};
