import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 1 · VALUE VILLAGE  (types and const, references, pointers with stack vs heap, vector and string)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const SAFE = L("Is this code safe?", "¿Este código es seguro?", "このコードは安全？");
const YES = L("Yes", "Sí", "はい");
const NO_GCC = L("No: g++ stops it", "No: g++ lo detiene", "いいえ：g++ が止める");

// ─── 1.1 Boxes and types ──────────────────────────────────────────────────
const boxes: LessonDef = {
  slug: "boxes-and-types",
  title: L("Boxes and types", "Cajas y tipos", "箱と型"),
  concept: "types",
  mode: "lesson",
  xp: 60,
  enemy: "cpp/ub-imp",
  enemyName: L("UB IMP", "DIABLILLO UB", "UB インプ"),
  beats: [
    say(L(
      "Welcome to Velocis! In C++ a VARIABLE is a typed box: int holds whole numbers, double decimals, bool true or false.",
      "¡Bienvenido a Velocis! En C++ una VARIABLE es una caja con tipo: int guarda enteros, double decimales, bool true o false.",
      "ヴェロシスへようこそ！C++ の変数は「型つきの箱」。int は整数、double は小数、bool は true か false。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and watch the boxes", "Pulsa en orden y mira las cajas", "順番に押して、箱を見てね"),
      steps: [
        { label: L("BOX hp", "CAJA hp", "箱 hp"), line: "int hp = 10;", effects: [{ t: "tag", actor: "hero", text: "int hp", value: "10" }] },
        { label: L("HEAL", "CURAR", "回復"), line: "hp = hp + 5;", effects: [{ t: "value", actor: "hero", text: "15" }, { t: "say", actor: "hero", text: L("Feeling better!", "¡Mucho mejor!", "元気出た！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "std::cout << hp;", effects: [{ t: "print", text: "15" }], output: "15" },
        { label: L("SPLIT 7 / 2", "DIVIDIR 7 / 2", "7 / 2"), line: "std::cout << 7 / 2;", effects: [{ t: "print", text: "3" }, { t: "say", actor: "hero", text: L("Where's the .5?", "¿Y el .5?", ".5 はどこ？") }], output: "3" },
        { label: L("LOCK lives", "SELLAR lives", "lives を固定"), line: "const int lives = 3;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "const lives", value: "3" }] },
        {
          label: L("CHANGE lives", "CAMBIAR lives", "lives を変更"),
          line: "lives = 4;",
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: L("I'm sealed!", "¡Estoy sellada!", "封印ずみ！") }],
          error: {
            compiler: "error: assignment of read-only variable 'lives'",
            plain: L("const seals the box. g++ refuses to build the program.", "const sella la caja. g++ se niega a compilar el programa.", "const は箱を封印する。g++ がコンパイルを拒否するよ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int hp = 10;\nhp = hp + 5;\nstd::cout << hp;",
      options: ["15", "10", "105"],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("hp + 5 is 15, and = puts 15 back into the box hp.", "hp + 5 es 15, y = guarda 15 de vuelta en la caja hp.", "hp + 5 は 15。= で箱 hp に 15 を入れ直すよ。"),
      setup: [{ t: "tag", actor: "hero", text: "int hp", value: "10" }],
      win: [{ t: "value", actor: "hero", text: "15" }, { t: "print", text: "15" }],
    },
    say(L(
      "Dividing two ints gives an int: the fraction just falls off. Add a decimal point and you get a double.",
      "Dividir dos int da un int: la fracción simplemente se cae. Agrega un punto decimal y obtienes un double.",
      "int 同士の割り算は int。小数部分はこぼれ落ちる。小数点をつければ double になるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::cout << 7 / 2 << " " << 7.0 / 2;',
      options: ["3 3.5", "3.5 3.5", "4 3.5"],
      answer: 0,
      output: "3 3.5",
      check: { compiles: true, stdout: "3 3.5" },
      explain: L("7 / 2 is int division: 3. 7.0 is a double, so 7.0 / 2 is 3.5.", "7 / 2 es división entera: 3. 7.0 es un double, así que 7.0 / 2 es 3.5.", "7 / 2 は整数の割り算で 3。7.0 は double だから 7.0 / 2 は 3.5。"),
      win: [{ t: "print", text: "3 3.5" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::cout << 7 % 3 << " " << -7 / 2;',
      options: ["1 -3", "1 -4", "2 -3"],
      answer: 0,
      output: "1 -3",
      check: { compiles: true, stdout: "1 -3" },
      explain: L("% is the remainder: 7 = 2*3 + 1. Int division cuts toward zero, so -3.5 becomes -3.", "% es el resto: 7 = 2*3 + 1. La división entera corta hacia cero: -3.5 queda en -3.", "% は余り（7 = 2*3 + 1）。整数の割り算は 0 の方向に切るので -3.5 は -3。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "const int lives = 3;\nlives = 4;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("A const box can't change after it's filled: 'assignment of read-only variable'.", "Una caja const no cambia tras llenarse: 'assignment of read-only variable'.", "const の箱は一度入れたら変えられない。read-only のエラーだよ。"),
      setup: [{ t: "tag", actor: "hero", text: "const lives", value: "3" }],
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Sealed!", "¡Sellado!", "封印！") }],
    },
    say(L(
      "Braces {} are strict: they refuse to squeeze a double into an int. Plain = squeezes it and silently drops the decimals.",
      "Las llaves {} son estrictas: no meten un double en un int. El = simple lo mete y tira los decimales en silencio.",
      "波かっこ {} はきびしい。double を int に詰めこむのを拒否する。= だと小数をだまって捨てるよ。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "int x{3.7};",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("Brace init forbids narrowing: 'narrowing conversion from double to int'.", "La inicialización con llaves prohíbe el estrechamiento (narrowing) de double a int.", "{} の初期化は情報が欠ける変換（narrowing）を禁止するよ。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int y = 3.7;\nstd::cout << y;",
      options: ["3", "4", "3.7"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("With = the double is converted to int by cutting off the decimals. No rounding.", "Con = el double se convierte a int cortando los decimales. No redondea.", "= だと double は小数を切り捨てて int になる。四捨五入はしないよ。"),
      setup: [{ t: "tag", actor: "hero", text: "int y" }],
      win: [{ t: "value", actor: "hero", text: "3" }, { t: "print", text: "3" }],
    },
    say(L(
      "auto lets g++ pick the type from the value: auto a = 5 is an int, auto b = 2.5 is a double.",
      "auto deja que g++ elija el tipo según el valor: auto a = 5 es int, auto b = 2.5 es double.",
      "auto なら g++ が値から型を決める。auto a = 5 は int、auto b = 2.5 は double。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "auto a = 5;\nauto b = 2.5;\nstd::cout << a * b;",
      options: ["12.5", "12", "10"],
      answer: 0,
      output: "12.5",
      check: { compiles: true, stdout: "12.5" },
      explain: L("a is an int, b a double. int * double gives a double: 12.5.", "a es int y b double. int * double da un double: 12.5.", "a は int、b は double。int * double は double なので 12.5。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "char c = 'A';\nstd::cout << c + 1 << \" \" << char(c + 1);",
      options: ["66 B", "B B", "A1 B"],
      answer: 0,
      output: "66 B",
      check: { compiles: true, stdout: "66 B" },
      explain: L("A char is a small number ('A' is 65). char + int is an int: 66. char(66) is 'B' again.", "Un char es un número pequeño ('A' es 65). char + int es un int: 66. char(66) vuelve a ser 'B'.", "char は小さな数（'A' は 65）。char + int は int で 66。char(66) で 'B' に戻る。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'bool ok = true;\nstd::cout << ok << " " << std::boolalpha << ok;',
      options: ["1 true", "true true", "1 1"],
      answer: 0,
      output: "1 true",
      check: { compiles: true, stdout: "1 true" },
      explain: L("std::cout prints a bool as 1 or 0, until std::boolalpha switches it to words.", "std::cout imprime un bool como 1 o 0, hasta que std::boolalpha lo cambia a palabras.", "std::cout は bool を 1 か 0 で表示。std::boolalpha で文字表示に切りかわるよ。"),
    },
    say(L(
      "Names live in NAMESPACES. std::cout is cout from the std namespace; :: is the 'from' operator.",
      "Los nombres viven en NAMESPACES. std::cout es cout del namespace std; :: es el operador 'de'.",
      "名前は名前空間（namespace）に住んでいる。std::cout は std の中の cout。:: は「〜の」の意味だよ。",
    )),
    {
      kind: "type",
      prompt: L("Read level from the game namespace", "Lee level del namespace game", "名前空間 game の level を読もう"),
      code: "namespace game { int level = 7; }\n\nint main() {\n  std::cout << game___level;\n}",
      answer: "::",
      check: { compiles: true, stdout: "7" },
      explain: L("game::level means 'level inside game'. The same :: is in std::cout.", "game::level significa 'level dentro de game'. Es el mismo :: de std::cout.", "game::level は「game の中の level」。std::cout と同じ :: だよ。"),
      win: [{ t: "print", text: "7" }],
    },
    say(L(
      "Beware the UB imp! Some code compiles but is UNDEFINED BEHAVIOR: the program may do anything. Reading an empty box is one.",
      "¡Cuidado con el diablillo UB! Hay código que compila pero es COMPORTAMIENTO INDEFINIDO: puede pasar cualquier cosa.",
      "UB インプに注意！コンパイルできても「未定義動作」のコードがある。何が起きてもおかしくない。",
    )),
    {
      kind: "predict",
      prompt: L("Is this output defined?", "¿Esta salida está definida?", "この出力は決まっている？"),
      code: "int x;\nstd::cout << x;",
      options: [L("No: reading x is UB", "No: leer x es UB", "いいえ：x を読むのは UB"), L("Yes: it shows 0", "Sí: muestra 0", "はい：0 が出る")],
      answer: 0,
      check: { compiles: true },
      explain: L("A local int starts with garbage. Reading it before giving it a value is UB. Always initialize.", "Un int local empieza con basura. Leerlo antes de darle valor es UB. Inicializa siempre.", "ローカルの int の中身はゴミ。値を入れる前に読むと UB。必ず初期化しよう。"),
      win: [{ t: "say", actor: "enemy", text: L("Curses!", "¡Rayos!", "くそっ！") }],
    },
    {
      kind: "predict",
      prompt: L("The box is full. What happens?", "La caja está llena. ¿Qué pasa?", "箱が満杯。どうなる？"),
      code: "int big = 2147483647; // max int\nbig = big + 1;",
      options: [L("UB: signed overflow", "UB: desbordamiento con signo", "UB：符号つきオーバーフロー"), L("Always -2147483648", "Siempre -2147483648", "必ず -2147483648"), "0"],
      answer: 0,
      check: { compiles: true },
      explain: L("Overflowing a signed int is UB: the compiler assumes it never happens, so no result is promised.", "Desbordar un int con signo es UB: el compilador asume que nunca pasa, así que no hay resultado prometido.", "符号つき int のオーバーフローは UB。結果は何も保証されないよ。"),
    },
    say(L(
      "Need decimals from ints? Turn one side into a double: static_cast<double>(gold), or divide by 2.0.",
      "¿Necesitas decimales con int? Convierte un lado en double: static_cast<double>(gold), o divide entre 2.0.",
      "int から小数がほしい？片方を double に：static_cast<double>(gold) か 2.0 で割ろう。",
    )),
    {
      kind: "run",
      prompt: L("Fix it: it must print share: 3.5", "Arréglalo: debe imprimir share: 3.5", "直そう：share: 3.5 と表示させて"),
      starter: '#include <iostream>\n\nint main() {\n    int gold = 7;\n    int friends = 2;\n    double share = gold / friends;\n    std::cout << "share: " << share << "\\n";\n}\n',
      solution: '#include <iostream>\n\nint main() {\n    int gold = 7;\n    int friends = 2;\n    double share = static_cast<double>(gold) / friends;\n    std::cout << "share: " << share << "\\n";\n}\n',
      expect: "share: 3.5",
      fallback: [
        String.raw`static_cast<double>\s*\(\s*(gold|friends)\s*\)`,
        String.raw`\(\s*double\s*\)\s*(gold|friends)`,
        String.raw`double\s*\(\s*(gold|friends)\s*\)`,
        String.raw`gold\s*/\s*2\.0`,
        String.raw`double\s+(gold|friends)\s*=`,
      ],
      explain: L("gold / friends was int division (3) before landing in the double. Make one side a double first.", "gold / friends era división entera (3) antes de llegar al double. Convierte un lado a double primero.", "gold / friends は double に入る前に整数の割り算（3）になっていた。先に片方を double に。"),
    },
  ],
};

// ─── 1.2 Lend or clone? ────────────────────────────────────────────────────
const lend: LessonDef = {
  slug: "lend-or-clone",
  title: L("Lend or clone?", "¿Prestar o copiar?", "貸す？コピーする？"),
  concept: "references",
  mode: "lesson",
  xp: 65,
  enemy: "cpp/dangling-wraith",
  enemyName: L("ALIAS WRAITH", "ESPECTRO ALIAS", "エイリアス亡霊"),
  beats: [
    say(L(
      "Pass a box to a function and C++ COPIES it. The function edits its copy; your box never changes.",
      "Pasa una caja a una función y C++ la COPIA. La función edita su copia; tu caja no cambia.",
      "関数に箱を渡すと C++ はコピーする。関数がいじるのはコピーで、元の箱は変わらないよ。",
    )),
    {
      kind: "act",
      prompt: L("Press in order: copy first, then lend", "Pulsa en orden: primero copia, luego presta", "順番に押そう：まずコピー、次に貸す"),
      steps: [
        { label: L("BOX hp", "CAJA hp", "箱 hp"), line: "int hp = 5;", effects: [{ t: "tag", actor: "hero", text: "hp", value: "5" }, { t: "item", kind: "potion", holder: "hero" }] },
        {
          label: L("COPY IN", "COPIAR", "コピーで渡す"),
          line: "heal(hp);     // void heal(int h)",
          effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "h", value: "15" }, { t: "say", actor: "hero", text: L("Mine is still 5", "La mía sigue en 5", "ぼくのは 5 のまま") }],
        },
        {
          label: L("LEND IN", "PRESTAR", "参照で貸す"),
          line: "heal2(hp);    // void heal2(int& h)",
          effects: [{ t: "lend", to: "ally" }, { t: "value", actor: "hero", text: "15" }, { t: "say", actor: "ally", text: L("Edited the real one!", "¡Edité la de verdad!", "本物をいじった！") }],
        },
        { label: L("ALIAS r", "ALIAS r", "別名 r"), line: "int& r = hp;", effects: [{ t: "tag", actor: "hero", text: "hp / r", value: "15" }] },
        { label: L("r = 9", "r = 9", "r = 9"), line: "r = 9;", effects: [{ t: "value", actor: "hero", text: "9" }] },
        { label: L("PRINT hp", "IMPRIMIR hp", "hp を表示"), line: "std::cout << hp;", effects: [{ t: "print", text: "9" }], output: "9" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "void heal(int hp) { hp += 10; }\n\nint main() {\n  int hp = 5;\n  heal(hp);\n  std::cout << hp;\n}",
      options: ["5", "15", "10"],
      answer: 0,
      output: "5",
      check: { compiles: true, stdout: "5" },
      explain: L("heal got a COPY of hp. It added 10 to the copy, which vanished at its }.", "heal recibió una COPIA de hp. Sumó 10 a la copia, que desapareció en su }.", "heal が受け取ったのは hp のコピー。コピーに 10 足して、} で消えたよ。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "5" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "print", text: "5" }],
    },
    say(L(
      "Add & to the parameter and it becomes a REFERENCE: the function borrows your real box instead of a copy.",
      "Agrega & al parámetro y se vuelve una REFERENCIA: la función usa tu caja real en vez de una copia.",
      "引数に & をつけると「参照」になる。関数はコピーじゃなく本物の箱を借りるよ。",
    )),
    {
      kind: "type",
      prompt: L("Let heal change the real hp", "Haz que heal cambie el hp real", "heal が本物の hp を変えるように"),
      code: "void heal(int___ hp) { hp += 10; }\n\nint main() {\n  int hp = 5;\n  heal(hp);\n  std::cout << hp;\n}",
      answer: "&",
      check: { compiles: true, stdout: "15" },
      explain: L("int& hp is a reference: hp inside heal IS main's hp, so += 10 sticks.", "int& hp es una referencia: hp dentro de heal ES el hp de main, así que el += 10 se queda.", "int& hp は参照。heal の hp は main の hp そのものだから += 10 が残るよ。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "5" }],
      win: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }, { t: "value", actor: "hero", text: "15" }, { t: "print", text: "15" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int a = 1;\nint& r = a;\nr = 9;\nstd::cout << a;",
      options: ["9", "1", L("Error", "Error", "エラー")],
      answer: 0,
      output: "9",
      check: { compiles: true, stdout: "9" },
      explain: L("r is just another name for a. Writing to r writes to a.", "r es solo otro nombre para a. Escribir en r es escribir en a.", "r は a の別名にすぎない。r に書けば a に書いたことになるよ。"),
      setup: [{ t: "tag", actor: "hero", text: "a / r", value: "1" }],
      win: [{ t: "value", actor: "hero", text: "9" }, { t: "print", text: "9" }],
    },
    say(L(
      "A reference is glued to its box for life: it must be set when created, and it can never point to another box.",
      "Una referencia queda pegada a su caja de por vida: se fija al crearla y nunca apunta a otra caja.",
      "参照は一生その箱にくっつく。作るときに決める必要があり、別の箱に付けかえられない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "int a = 1, b = 2;\nint& r = a;\nr = b;\nb = 7;\nstd::cout << a << r;",
      options: ["22", "17", "77"],
      answer: 0,
      output: "22",
      check: { compiles: true, stdout: "22" },
      explain: L("r = b does not re-glue r. It copies b's value (2) into a. Later b = 7 doesn't touch a.", "r = b no vuelve a pegar r. Copia el valor de b (2) en a. Luego b = 7 no toca a.", "r = b は付けかえじゃない。b の値 2 を a にコピーするだけ。b = 7 は a に影響しない。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "int& r;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("A reference must be bound at birth: 'r declared as reference but not initialized'.", "Una referencia debe enlazarse al nacer: 'r declared as reference but not initialized'.", "参照は生まれたときに結びつける必要がある。初期化なしはエラー。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Big object, read only? Use const&: no copy, and the function promises not to touch it.",
      "¿Objeto grande y solo lectura? Usa const&: sin copia, y la función promete no tocarlo.",
      "大きなオブジェクトを読むだけなら const&。コピーなしで、変更しない約束になるよ。",
    )),
    {
      kind: "pick",
      prompt: L("Best way to read a long text", "Mejor forma de leer un texto largo", "長い文字列を読むだけの最善策"),
      code: "void show(___ s);",
      options: ["std::string", "const std::string&", "std::string&"],
      answer: 1,
      check: { compiles: true },
      explain: L("std::string copies the text; std::string& lets show change it. const& borrows read-only.", "std::string copia el texto; std::string& deja que show lo cambie. const& lo presta solo para leer.", "std::string はコピー、std::string& は変更できてしまう。const& は読むだけの借用。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'void show(const std::string& s) {\n  s += "!";\n}\n\nint main() {}',
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("s is a const reference: += would change it, so g++ refuses.", "s es una referencia const: += la cambiaría, así que g++ se niega.", "s は const 参照。+= は変更になるので g++ が拒否するよ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "void f(int& x) {}\n\nint main() {\n  f(5);\n}",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("5 is a temporary, not a box. A plain int& can't bind to it; a const int& could.", "5 es un temporal, no una caja. Un int& simple no puede enlazarse; un const int& sí.", "5 は一時的な値で箱じゃない。int& は結びつけないけど const int& ならOK。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::vector<int> v{1, 2, 3};\nauto w = v;\nw[0] = 99;\nstd::cout << v[0] << " " << w[0];',
      options: ["1 99", "99 99", "1 1"],
      answer: 0,
      output: "1 99",
      check: { compiles: true, stdout: "1 99" },
      explain: L("Containers are values: auto w = v copies the whole vector. Editing w leaves v alone.", "Los contenedores son valores: auto w = v copia todo el vector. Editar w no toca v.", "コンテナは値。auto w = v で vector 全体がコピーされ、w をいじっても v はそのまま。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "v" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "w" }, { t: "print", text: "1 99" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "void swap2(int& a, int& b) {\n  int t = a; a = b; b = t;\n}\n\nint main() {\n  int x = 1, y = 2;\n  swap2(x, y);\n  std::cout << x << y;\n}",
      options: ["21", "12", "22"],
      answer: 0,
      output: "21",
      check: { compiles: true, stdout: "21" },
      explain: L("a and b are references to x and y, so the swap happens in main's boxes.", "a y b son referencias a x e y, así que el intercambio ocurre en las cajas de main.", "a と b は x と y の参照。だから入れかえは main の箱で起きるよ。"),
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print level: 2", "Arréglalo: debe imprimir level: 2", "直そう：level: 2 と表示させて"),
      starter: '#include <iostream>\n\nvoid levelUp(int lvl) {\n    lvl++;\n}\n\nint main() {\n    int lvl = 1;\n    levelUp(lvl);\n    std::cout << "level: " << lvl << "\\n";\n}\n',
      solution: '#include <iostream>\n\nvoid levelUp(int& lvl) {\n    lvl++;\n}\n\nint main() {\n    int lvl = 1;\n    levelUp(lvl);\n    std::cout << "level: " << lvl << "\\n";\n}\n',
      expect: "level: 2",
      fallback: [String.raw`levelUp\s*\(\s*int\s*&`, String.raw`lvl\s*=\s*levelUp\s*\(`],
      explain: L("levelUp bumped a copy. Take the parameter by reference (int&) so it bumps main's lvl.", "levelUp subía una copia. Recibe el parámetro por referencia (int&) para subir el lvl de main.", "levelUp はコピーを増やしていた。int& で受け取れば main の lvl が増えるよ。"),
    },
  ],
};

// ─── 1.3 Keys and pointers ─────────────────────────────────────────────────
const pointers: LessonDef = {
  slug: "pointer-paths",
  title: L("Keys and pointers", "Llaves y punteros", "鍵とポインタ"),
  concept: "pointers",
  mode: "lesson",
  xp: 70,
  enemy: "cpp/segfault-skull",
  enemyName: L("SEGFAULT SKULL", "CALAVERA SEGFAULT", "セグフォスカル"),
  beats: [
    say(L(
      "A POINTER is a key that stores where a box lives. &hp gives the address; *p uses the key to open the box.",
      "Un PUNTERO es una llave que guarda dónde vive una caja. &hp da la dirección; *p usa la llave para abrirla.",
      "ポインタは箱の場所をしまう鍵。&hp で住所を取り、*p で鍵を使って箱を開けるよ。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and follow the key", "Pulsa en orden y sigue la llave", "順番に押して、鍵を追いかけよう"),
      steps: [
        { label: L("BOX hp", "CAJA hp", "箱 hp"), line: "int hp = 5;", effects: [{ t: "tag", actor: "hero", text: "hp", value: "5" }] },
        { label: L("MAKE KEY", "HACER LLAVE", "鍵を作る"), line: "int* p = &hp;", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "key", holder: "ally" }, { t: "tag", actor: "ally", text: "int* p", value: "&hp" }] },
        { label: L("USE KEY", "USAR LLAVE", "鍵を使う"), line: "*p = 8;", effects: [{ t: "lend", to: "hero" }, { t: "value", actor: "hero", text: "8" }, { t: "say", actor: "ally", text: L("Opened it!", "¡Abierta!", "開いた！") }] },
        { label: L("PRINT hp", "IMPRIMIR hp", "hp を表示"), line: "std::cout << hp;", effects: [{ t: "print", text: "8" }], output: "8" },
        { label: L("BLANK KEY", "LLAVE VACÍA", "空の鍵"), line: "p = nullptr;", effects: [{ t: "value", actor: "ally", text: "nullptr" }, { t: "say", actor: "ally", text: L("Opens nothing...", "No abre nada...", "何も開かない…") }] },
        {
          label: L("USE BLANK", "USAR VACÍA", "空の鍵を使う"),
          line: "std::cout << *p;",
          effects: [{ t: "shake" }, { t: "banner", text: L("UB!", "¡UB!", "UB！") }],
          error: {
            compiler: "Program terminated with signal: SIGSEGV",
            plain: L("p points nowhere. Following a null pointer is UB; here the program crashed.", "p no apunta a nada. Seguir un puntero nulo es UB; aquí el programa se cayó.", "p はどこも指していない。null をたどるのは UB。今回はクラッシュした。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int hp = 5;\nint* p = &hp;\n*p = 8;\nstd::cout << hp;",
      options: ["8", "5", L("An address", "Una dirección", "住所")],
      answer: 0,
      output: "8",
      check: { compiles: true, stdout: "8" },
      explain: L("p holds hp's address. *p = 8 opens that box and puts 8 inside: hp is 8.", "p guarda la dirección de hp. *p = 8 abre esa caja y mete 8: hp vale 8.", "p は hp の住所を持つ。*p = 8 はその箱に 8 を入れるので hp は 8。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "5" }, { t: "enter", actor: "ally" }, { t: "item", kind: "key", holder: "ally" }, { t: "tag", actor: "ally", text: "p" }],
      win: [{ t: "lend", to: "hero" }, { t: "value", actor: "hero", text: "8" }, { t: "print", text: "8" }],
    },
    {
      kind: "type",
      prompt: L("Make p point to hp", "Haz que p apunte a hp", "p が hp を指すように"),
      code: "int hp = 3;\nint* p = ___hp;\nstd::cout << *p;",
      answer: "&",
      check: { compiles: true, stdout: "3" },
      explain: L("&hp is 'the address of hp', exactly what an int* stores.", "&hp es 'la dirección de hp', justo lo que guarda un int*.", "&hp は「hp の住所」。int* がしまうのはまさにそれ。"),
      win: [{ t: "print", text: "3" }],
    },
    say(L(
      "Unlike a reference, a key can be handed to another box later, or be blank: nullptr.",
      "A diferencia de una referencia, una llave puede pasar a otra caja después, o estar vacía: nullptr.",
      "参照とちがって、鍵はあとで別の箱に付けかえられるし、空（nullptr）にもできる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "int a = 1, b = 2;\nint* p = &a;\np = &b;\n*p = 9;\nstd::cout << a << b;",
      options: ["19", "92", "99"],
      answer: 0,
      output: "19",
      check: { compiles: true, stdout: "19" },
      explain: L("p = &b re-aims the key at b. *p = 9 then changes b, and a stays 1.", "p = &b apunta la llave a b. Luego *p = 9 cambia b, y a sigue en 1.", "p = &b で鍵は b を指す。*p = 9 は b を変え、a は 1 のまま。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int* p = nullptr;\nstd::cout << (p == nullptr);",
      options: ["1", "0", L("Crash", "Se cae", "クラッシュ")],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("Comparing a pointer is safe; only using *p on nullptr is UB. true prints as 1.", "Comparar un puntero es seguro; solo usar *p con nullptr es UB. true se imprime como 1.", "ポインタの比較は安全。nullptr に *p するのが UB。true は 1 と表示。"),
    },
    {
      kind: "order",
      prompt: L("Order it so it prints 8", "Ordénalo para que imprima 8", "8 と表示されるように並べよう"),
      lines: ["int hp = 5;", "int* p = &hp;", "*p = 8;", "std::cout << hp;"],
      check: { compiles: true, stdout: "8" },
      explain: L("Make the box, make the key to it, use the key, then print.", "Crea la caja, crea su llave, usa la llave y luego imprime.", "箱を作り、その鍵を作り、鍵を使い、最後に表示。"),
    },
    say(L(
      "const can lock the box or the key: const int* p can't change the box; int* const p can't be re-aimed.",
      "const puede sellar la caja o la llave: const int* p no cambia la caja; int* const p no se reapunta.",
      "const は箱か鍵を封印する。const int* p は箱を変えられず、int* const p は付けかえ不可。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "int x = 1;\nconst int* p = &x;\n*p = 2;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("const int* is a read-only view of the box: writing through it is 'assignment of read-only location'.", "const int* es una vista de solo lectura: escribir a través de él da 'assignment of read-only location'.", "const int* は箱を読むだけの鍵。書きこむと read-only location のエラー。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "int x = 1, y = 2;\nint* const p = &x;\np = &y;",
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("int* const means the key itself is sealed: it can never be re-aimed at y.", "int* const significa que la llave misma está sellada: nunca puede apuntar a y.", "int* const は鍵そのものが封印。y に付けかえられない。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'int arr[3] = {10, 20, 30};\nint* p = arr;\nstd::cout << *(p + 2) << " " << p[1];',
      options: ["30 20", "12 20", "20 10"],
      answer: 0,
      output: "30 20",
      check: { compiles: true, stdout: "30 20" },
      explain: L("An array turns into a pointer to its first box. p + 2 walks two boxes ahead; p[1] is *(p + 1).", "Un array se vuelve un puntero a su primera caja. p + 2 avanza dos cajas; p[1] es *(p + 1).", "配列は先頭の箱へのポインタになる。p + 2 は 2 つ先、p[1] は *(p + 1)。"),
    },
    say(L(
      "Locals live on the STACK and die at their }. new puts a box on the HEAP: it stays until you delete it.",
      "Las locales viven en la PILA (stack) y mueren en su }. new pone una caja en el HEAP: se queda hasta que la borres con delete.",
      "ローカル変数はスタックに住み } で消える。new はヒープに箱を作り、delete するまで残るよ。",
    )),
    {
      kind: "predict",
      prompt: L("Where does x live?", "¿Dónde vive x?", "x はどこに住む？"),
      code: "void f() {\n  int x = 5;\n}",
      options: [L("On the stack", "En la pila (stack)", "スタック"), L("On the heap", "En el heap", "ヒープ")],
      answer: 0,
      explain: L("A plain local is on the stack and is gone at f's }. Only new int(5) would be on the heap.", "Una local simple está en la pila y desaparece en la } de f. Solo new int(5) estaría en el heap.", "ふつうのローカルはスタックで、f の } で消える。new int(5) ならヒープ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "int* p = new int(42);\nstd::cout << *p;\ndelete p;",
      options: ["42", L("An address", "Una dirección", "住所"), "0"],
      answer: 0,
      output: "42",
      check: { compiles: true, stdout: "42" },
      explain: L("new int(42) builds a heap box holding 42 and returns its address. delete frees it.", "new int(42) crea una caja en el heap con 42 y devuelve su dirección. delete la libera.", "new int(42) はヒープに 42 入りの箱を作り住所を返す。delete で解放。"),
      win: [{ t: "print", text: "42" }, { t: "drop" }],
    },
    {
      kind: "predict",
      prompt: L("No delete. What happens to the box?", "Sin delete. ¿Qué pasa con la caja?", "delete なし。箱はどうなる？"),
      code: "int* p = new int(42);\nstd::cout << *p;\n// no delete",
      options: [L("It leaks: never freed", "Se fuga: nunca se libera", "リーク：解放されない"), L("Compile error", "Error de compilación", "コンパイルエラー"), L("Freed at the }", "Se libera en la }", "} で解放される")],
      answer: 0,
      check: { compiles: true },
      explain: L("Heap boxes don't die at }. Without delete the memory is lost: a LEAK. Modern C++ avoids raw new.", "Las cajas del heap no mueren en la }. Sin delete esa memoria se pierde: una FUGA. El C++ moderno evita new.", "ヒープの箱は } で消えない。delete しないとリーク。現代の C++ は生の new を避けるよ。"),
      win: [{ t: "banner", text: L("LEAK", "FUGA", "リーク") }],
    },
    {
      kind: "predict",
      prompt: SAFE,
      code: "int* p = nullptr;\nstd::cout << *p;",
      options: [L("No: null dereference is UB", "No: desreferenciar null es UB", "いいえ：null の参照外しは UB"), L("Yes: it prints 0", "Sí: imprime 0", "はい：0 が出る")],
      answer: 0,
      // Compile-only proof: the UB line sits behind a branch that never runs, so nothing crashes.
      check: { compiles: true, program: "#include <iostream>\n\nint main(int argc, char**) {\n  int* p = nullptr;\n  if (argc > 99) std::cout << *p;\n}\n" },
      explain: L("It compiles, but *p on nullptr is UB: often a segfault, never a promise.", "Compila, pero *p con nullptr es UB: a menudo un segfault, nunca una promesa.", "コンパイルは通るけど nullptr への *p は UB。たいてい segfault。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Crack!", "¡Crac!", "バキッ！") }],
    },
    {
      kind: "predict",
      prompt: SAFE,
      code: "int* make() {\n  int x = 5;\n  return &x;\n}\n\nint main() { int* p = make(); }",
      options: [L("No: x died at the }", "No: x murió en la }", "いいえ：x は } で消えた"), L("Yes: p keeps x alive", "Sí: p mantiene viva a x", "はい：p が x を生かす")],
      answer: 0,
      check: { compiles: true },
      explain: L("x was a stack local. After return the key points to a dead box: a DANGLING pointer. g++ even warns.", "x era local en la pila. Tras el return la llave apunta a una caja muerta: puntero COLGANTE. g++ avisa.", "x はスタックのローカル。return 後の鍵は死んだ箱を指す（ダングリング）。g++ も警告するよ。"),
      win: [{ t: "say", actor: "enemy", text: L("Dangling!", "¡Colgando!", "ぶらーん！") }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print gold: 15", "Arréglalo: debe imprimir gold: 15", "直そう：gold: 15 と表示させて"),
      starter: '#include <iostream>\n\nvoid addGold(int* gold) {\n    gold += 10;\n}\n\nint main() {\n    int gold = 5;\n    addGold(&gold);\n    std::cout << "gold: " << gold << "\\n";\n}\n',
      solution: '#include <iostream>\n\nvoid addGold(int* gold) {\n    *gold += 10;\n}\n\nint main() {\n    int gold = 5;\n    addGold(&gold);\n    std::cout << "gold: " << gold << "\\n";\n}\n',
      expect: "gold: 15",
      fallback: [String.raw`\*\s*gold\s*\+=\s*10`, String.raw`\(\s*\*\s*gold\s*\)\s*\+=\s*10`, String.raw`\*\s*gold\s*=\s*\*\s*gold\s*\+\s*10`],
      explain: L("gold += 10 moved the KEY ten boxes away. *gold += 10 opens the box and adds to the value.", "gold += 10 movió la LLAVE diez cajas. *gold += 10 abre la caja y suma al valor.", "gold += 10 は鍵を 10 個先にずらしただけ。*gold += 10 で箱の中身に足そう。"),
    },
  ],
};

// ─── 1.4 Vectors and strings ───────────────────────────────────────────────
const bags: LessonDef = {
  slug: "bags-and-scrolls",
  title: L("Vectors and strings", "Vectores y strings", "vector と string"),
  concept: "containers",
  mode: "lesson",
  xp: 70,
  enemy: "cpp/leak-slime",
  enemyName: L("BOUNDS SLIME", "SLIME DE LÍMITES", "はみ出しスライム"),
  beats: [
    say(L(
      "std::vector is a scroll that grows: push_back adds a line, size counts them, front and back read the ends.",
      "std::vector es un pergamino que crece: push_back agrega una línea, size las cuenta, front y back leen los extremos.",
      "std::vector はのびる巻物。push_back で追加、size で数え、front と back で両端を読む。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and watch the scroll", "Pulsa en orden y mira el pergamino", "順番に押して、巻物を見てね"),
      steps: [
        { label: L("NEW bag", "NUEVO bag", "bag を作る"), line: "std::vector<int> bag{3, 1};", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "bag", value: "{3,1}" }] },
        { label: L("PUSH 4", "AGREGAR 4", "4 を追加"), line: "bag.push_back(4);", effects: [{ t: "value", actor: "hero", text: "{3,1,4}" }] },
        { label: L("COUNT", "CONTAR", "数える"), line: "std::cout << bag.size();", effects: [{ t: "print", text: "3" }], output: "3" },
        { label: L("READ [0]", "LEER [0]", "[0] を読む"), line: "std::cout << bag[0];", effects: [{ t: "print", text: "3" }], output: "3" },
        {
          label: L("READ at(5)", "LEER at(5)", "at(5) を読む"),
          line: "std::cout << bag.at(5);",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("No line 5!", "¡No hay línea 5!", "5 番はない！") }],
          error: {
            compiler: "terminate called after throwing an instance of 'std::out_of_range'",
            plain: L("at() checks the index and throws std::out_of_range. bag[5] would not check at all: UB.", "at() revisa el índice y lanza std::out_of_range. bag[5] no revisaría nada: UB.", "at() は範囲を調べて std::out_of_range を投げる。bag[5] は調べないので UB。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::vector<int> v{3, 1, 4};\nv.push_back(1);\nstd::cout << v.size() << " " << v.back();',
      options: ["4 1", "3 4", "4 3"],
      answer: 0,
      output: "4 1",
      check: { compiles: true, stdout: "4 1" },
      explain: L("push_back adds 1 at the end: 4 items, and back() is the last one, 1.", "push_back agrega 1 al final: 4 elementos, y back() es el último, 1.", "push_back で末尾に 1。要素は 4 個、back() は最後の 1。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "v", value: "{3,1,4}" }],
      win: [{ t: "value", actor: "hero", text: "{3,1,4,1}" }, { t: "print", text: "4 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "std::vector<int> v{5, 6, 7};\nstd::cout << v.front() + v.back();",
      options: ["12", "18", "57"],
      answer: 0,
      output: "12",
      check: { compiles: true, stdout: "12" },
      explain: L("front() is 5 and back() is 7: 5 + 7 = 12.", "front() es 5 y back() es 7: 5 + 7 = 12.", "front() は 5、back() は 7。5 + 7 = 12。"),
    },
    say(L(
      "Careful: (3) and {3} differ! vector<int>(3) is three zeros; vector<int>{3} is one item, the number 3.",
      "¡Ojo: (3) y {3} son distintos! vector<int>(3) son tres ceros; vector<int>{3} es un elemento, el número 3.",
      "注意：(3) と {3} はちがう！vector<int>(3) は 0 が 3 個、vector<int>{3} は 3 が 1 個。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "std::vector<int> a(3);\nstd::vector<int> b{3};\nstd::cout << a.size() << b.size();",
      options: ["31", "33", "13"],
      answer: 0,
      output: "31",
      check: { compiles: true, stdout: "31" },
      explain: L("a(3) means 'size 3' (three zeros). b{3} is a list with one item: 3.", "a(3) significa 'tamaño 3' (tres ceros). b{3} es una lista con un elemento: 3.", "a(3) は「サイズ 3」（0 が 3 個）。b{3} は要素 3 が 1 個のリスト。"),
    },
    say(L(
      "A range-for visits each item: for (int x : v). Without & each x is a COPY. With & you edit the real item.",
      "Un for de rango recorre cada elemento: for (int x : v). Sin & cada x es una COPIA. Con & editas el elemento real.",
      "範囲 for で各要素をめぐる：for (int x : v)。& なしなら x はコピー、& ありなら本物を編集。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "std::vector<int> v{1, 2, 3};\nfor (int x : v) x *= 2;\nstd::cout << v[0];",
      options: ["1", "2", "6"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("Each x was a copy, doubled and thrown away. The vector never changed.", "Cada x era una copia, duplicada y descartada. El vector nunca cambió.", "x は毎回コピー。2 倍にして捨てられただけで vector は変わらない。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "v", value: "{1,2,3}" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "print", text: "1" }],
    },
    {
      kind: "type",
      prompt: L("Make the loop edit the real items", "Haz que el bucle edite los reales", "ループで本物を書きかえよう"),
      code: "std::vector<int> v{1, 2, 3};\nfor (int___ x : v) x *= 2;\nstd::cout << v[0];",
      answer: "&",
      check: { compiles: true, stdout: "2" },
      explain: L("int& x is a reference to each item, so x *= 2 doubles the vector itself.", "int& x es una referencia a cada elemento, así que x *= 2 duplica el vector mismo.", "int& x は各要素への参照。x *= 2 で vector 自体が 2 倍になるよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "v", value: "{1,2,3}" }],
      win: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }, { t: "value", actor: "hero", text: "{2,4,6}" }, { t: "print", text: "2" }],
    },
    say(L(
      "Reading past the end: v[5] doesn't check (UB). v.at(5) checks and THROWS std::out_of_range, which try/catch can catch.",
      "Leer más allá del final: v[5] no revisa (UB). v.at(5) revisa y LANZA std::out_of_range, que try/catch puede atrapar.",
      "末尾の先を読むと：v[5] は確認しない（UB）。v.at(5) は std::out_of_range を投げ、try/catch で捕まえられる。",
    )),
    {
      kind: "predict",
      prompt: L("What happens?", "¿Qué pasa?", "どうなる？"),
      code: "std::vector<int> v{1, 2, 3};\nstd::cout << v.at(5);",
      options: [L("Throws std::out_of_range", "Lanza std::out_of_range", "std::out_of_range を投げる"), L("Shows 0", "Muestra 0", "0 が出る"), L("Compile error", "Error de compilación", "コンパイルエラー")],
      answer: 0,
      check: { compiles: true, throws: "std::out_of_range" },
      explain: L("at() finds that 5 is past the end and throws. Nobody catches it here, so the program stops.", "at() ve que 5 está fuera y lanza. Aquí nadie lo atrapa, así que el programa se detiene.", "at() は 5 が範囲外だと気づいて投げる。誰も捕まえないのでプログラムは止まる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::vector<int> v{1, 2, 3};\ntry {\n  v.at(5);\n} catch (const std::out_of_range&) {\n  std::cout << "caught";\n}',
      options: ["caught", L("Nothing", "Nada", "何も出ない"), "0"],
      answer: 0,
      output: "caught",
      check: { compiles: true, stdout: "caught" },
      explain: L("at(5) throws std::out_of_range and the catch block handles it: caught.", "at(5) lanza std::out_of_range y el bloque catch lo maneja: caught.", "at(5) が投げた std::out_of_range を catch が受け止めて caught。"),
      win: [{ t: "print", text: "caught" }],
    },
    {
      kind: "predict",
      prompt: SAFE,
      code: "std::vector<int> v{1, 2, 3};\nstd::cout << v[5];",
      options: [L("No: [] past the end is UB", "No: [] fuera del final es UB", "いいえ：範囲外の [] は UB"), L("Yes: it throws", "Sí: lanza una excepción", "はい：例外を投げる")],
      answer: 0,
      check: { compiles: true },
      explain: L("[] trusts you and checks nothing. Index 5 reads memory that isn't yours: UB.", "[] confía en ti y no revisa nada. El índice 5 lee memoria ajena: UB.", "[] は何も確認しない。5 番は自分のものじゃないメモリを読む：UB。"),
      win: [{ t: "banner", text: L("UB!", "¡UB!", "UB！") }],
    },
    say(L(
      "std::string is text that grows too: += glues more, size counts letters, s[0] reads the first one.",
      "std::string es texto que también crece: += pega más, size cuenta letras, s[0] lee la primera.",
      "std::string ものびる文字列。+= でつなぎ、size で文字数、s[0] で先頭を読む。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::string s = "hero";\ns += "!";\nstd::cout << s.size() << " " << s[0];',
      options: ["5 h", "4 h", "5 hero!"],
      answer: 0,
      output: "5 h",
      check: { compiles: true, stdout: "5 h" },
      explain: L("\"hero!\" has 5 letters, and s[0] is the first one: h.", "\"hero!\" tiene 5 letras, y s[0] es la primera: h.", "\"hero!\" は 5 文字。s[0] は先頭の h。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'std::string a = "10", b = "5";\nstd::cout << a + b << " " << std::stoi(a) + std::stoi(b);',
      options: ["105 15", "15 15", "105 105"],
      answer: 0,
      output: "105 15",
      check: { compiles: true, stdout: "105 15" },
      explain: L("+ on strings glues text: \"105\". std::stoi turns text into an int, so 10 + 5 = 15.", "+ con strings pega texto: \"105\". std::stoi convierte texto en int, así que 10 + 5 = 15.", "文字列の + は連結で \"105\"。std::stoi で int にすれば 10 + 5 = 15。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'std::string s = "a" + "b";',
      options: [YES, NO_GCC],
      answer: 1,
      check: { compiles: false },
      explain: L("\"a\" and \"b\" are plain char arrays, not std::string, and arrays can't be added.", "\"a\" y \"b\" son arrays de char, no std::string, y los arrays no se suman.", "\"a\" と \"b\" は std::string じゃなく char 配列。配列同士は足せない。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "std::vector<int> v;\nstd::cout << v.size() - 1;",
      options: ["18446744073709551615", "-1", "0"],
      answer: 0,
      output: "18446744073709551615",
      check: { compiles: true, stdout: "18446744073709551615" },
      explain: L("size() is unsigned (size_t). 0 - 1 can't go negative, so it wraps to the biggest value. That's defined.", "size() es sin signo (size_t). 0 - 1 no puede ser negativo: da la vuelta al valor máximo. Está definido.", "size() は符号なし（size_t）。0 - 1 は負になれず最大値に一周する。これは定義済み。"),
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print 10 20 30", "Arréglalo: debe imprimir 10 20 30", "直そう：10 20 30 と表示させて"),
      starter: '#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> v{1, 2, 3};\n    for (auto x : v) x *= 10;\n    for (auto x : v) std::cout << x << " ";\n    std::cout << "\\n";\n}\n',
      solution: '#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> v{1, 2, 3};\n    for (auto& x : v) x *= 10;\n    for (auto x : v) std::cout << x << " ";\n    std::cout << "\\n";\n}\n',
      expect: "10 20 30",
      fallback: [String.raw`for\s*\(\s*(auto|int)\s*&\s*\w+\s*:\s*v\s*\)`, String.raw`v\s*\[\s*\w+\s*\]\s*\*=\s*10`],
      explain: L("The first loop multiplied copies. auto& x edits each real item in the vector.", "El primer bucle multiplicaba copias. auto& x edita cada elemento real del vector.", "最初のループはコピーをかけていた。auto& x なら vector の本物を書きかえる。"),
    },
  ],
};

// ─── 1.5 Boss: Pointer Golem ───────────────────────────────────────────────
const boss: LessonDef = {
  slug: "pointer-golem",
  title: L("Boss: Pointer Golem", "Jefe: Gólem Puntero", "ボス：ポインタゴーレム"),
  concept: "pointers",
  mode: "boss",
  xp: 180,
  enemy: "golem",
  enemyName: L("POINTER GOLEM", "GÓLEM PUNTERO", "ポインタゴーレム"),
  beats: [
    enemySays(L(
      "I AM THE POINTER GOLEM. Copies, aliases, keys... follow every path through my stone, or be crushed!",
      "SOY EL GÓLEM PUNTERO. Copias, alias, llaves... ¡sigue cada camino por mi piedra o serás aplastado!",
      "我はポインタゴーレム。コピー、別名、鍵…この石の道をすべてたどれ。さもなくば砕く！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "int a = 5;\nint& r = a;\nint* p = &r;\n*p += 1;\nr *= 2;\nstd::cout << a;", options: ["12", "11", "6"], answer: 0, output: "12", check: { compiles: true, stdout: "12" }, explain: L("r and *p both reach a: 5 + 1 = 6, then 6 * 2 = 12.", "r y *p llegan ambos a a: 5 + 1 = 6, luego 6 * 2 = 12.", "r も *p も a のこと。5 + 1 = 6、6 * 2 = 12。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "std::cout << 10 / 4 * 4;", options: ["8", "10", "16"], answer: 0, output: "8", check: { compiles: true, stdout: "8" }, explain: L("Left to right: 10 / 4 is 2 (int division), then 2 * 4 = 8.", "De izquierda a derecha: 10 / 4 es 2 (división entera), luego 2 * 4 = 8.", "左から順に 10 / 4 = 2（整数の割り算）、2 * 4 = 8。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "unsigned int u = 0;\nu = u - 1;\nstd::cout << (u > 0);", options: ["1", "0", L("UB", "UB", "UB")], answer: 0, output: "1", check: { compiles: true, stdout: "1" }, explain: L("Unsigned numbers wrap around (defined!): 0 - 1 is the maximum, which is > 0.", "Los unsigned dan la vuelta (¡definido!): 0 - 1 es el máximo, que es > 0.", "unsigned は一周する（定義済み）。0 - 1 は最大値で > 0。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'std::vector<std::string> v{"a", "b"};\nstd::string s = v[0];\ns += "x";\nstd::cout << v[0] << s;', options: ["aax", "axax", "ax"], answer: 0, output: "aax", check: { compiles: true, stdout: "aax" }, explain: L("s is a copy of v[0]. Adding x to s leaves v[0] as \"a\".", "s es una copia de v[0]. Agregar x a s deja v[0] como \"a\".", "s は v[0] のコピー。s に x を足しても v[0] は \"a\" のまま。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "int x = 3;\nauto y = x;\nauto& z = x;\ny++;\nz += 10;\nstd::cout << x << y;", options: ["134", "44", "1314"], answer: 0, output: "134", check: { compiles: true, stdout: "134" }, explain: L("y is a copy (becomes 4); z is a reference to x (x becomes 13). Printed: 13 then 4.", "y es una copia (pasa a 4); z es referencia a x (x pasa a 13). Se imprime 13 y luego 4.", "y はコピー（4 に）、z は x の参照（x は 13 に）。表示は 13 と 4。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'std::cout << sizeof(char) << " " << 5 / 2.0;', options: ["1 2.5", "1 2", "8 2.5"], answer: 0, output: "1 2.5", check: { compiles: true, stdout: "1 2.5" }, explain: L("sizeof(char) is always 1. 2.0 is a double, so 5 / 2.0 is 2.5.", "sizeof(char) siempre es 1. 2.0 es double, así que 5 / 2.0 es 2.5.", "sizeof(char) はいつも 1。2.0 は double なので 5 / 2.0 は 2.5。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "void bump(int* p) { (*p)++; }\nvoid bumpRef(int& r) { r++; }\n\nint main() {\n  int hp = 1;\n  bump(&hp);\n  bumpRef(hp);\n  std::cout << hp;\n}", options: ["3", "2", "1"], answer: 0, output: "3", check: { compiles: true, stdout: "3" }, explain: L("Both reach the real hp: one through a key, one through a reference. 1 + 1 + 1 = 3.", "Ambos llegan al hp real: uno con una llave, otro con una referencia. 1 + 1 + 1 = 3.", "どちらも本物の hp に届く（鍵と参照）。1 + 1 + 1 = 3。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: "int* p = 5;", options: [YES, NO_GCC], answer: 1, check: { compiles: false }, explain: L("A pointer holds an address, not a number: 'invalid conversion from int to int*'.", "Un puntero guarda una dirección, no un número: 'invalid conversion from int to int*'.", "ポインタがしまうのは住所で、数じゃない。int から int* には変換できない。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "int x = 10;\nint* p = &x;\nint** pp = &p;\n**pp = 20;\nstd::cout << x;", options: ["20", "10", L("An address", "Una dirección", "住所")], answer: 0, output: "20", check: { compiles: true, stdout: "20" }, explain: L("pp is a key to the key p. **pp opens p, then opens x: x becomes 20.", "pp es una llave hacia la llave p. **pp abre p y luego abre x: x pasa a 20.", "pp は鍵 p への鍵。**pp で p を開け、さらに x を開けて 20 に。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'char s[] = "hi";\nstd::cout << sizeof(s);', options: ["3", "2", "8"], answer: 0, output: "3", check: { compiles: true, stdout: "3" }, explain: L("A text literal ends with a hidden '\\0' marker: h, i, '\\0' is 3 chars.", "Un texto literal termina con una marca oculta '\\0': h, i, '\\0' son 3 chars.", "文字列リテラルの最後には隠れた '\\0' がある。h, i, '\\0' で 3。") },
    { kind: "predict", time: 12, prompt: SAFE, code: "std::vector<int> v{1, 2, 3};\nint* p = &v[0];\nstd::cout << p[3];", options: [L("No: index 3 is past the end", "No: el índice 3 está fuera", "いいえ：3 番は範囲外"), L("Yes: it shows 0", "Sí: muestra 0", "はい：0 が出る")], answer: 0, check: { compiles: true }, explain: L("Valid indexes are 0, 1, 2. p[3] reads past the end: UB, just like v[3].", "Los índices válidos son 0, 1, 2. p[3] lee fuera del final: UB, igual que v[3].", "有効なのは 0, 1, 2。p[3] は範囲外を読むので v[3] と同じく UB。") },
    enemySays(L(
      "Crumble... you followed every key. But in the Lifetime Forest, objects are born and die. Beware!",
      "Me desmorono... seguiste cada llave. Pero en el Bosque de Vida los objetos nacen y mueren. ¡Cuidado!",
      "くずれる…すべての鍵をたどったか。だがライフタイムの森では、オブジェクトが生まれて死ぬ。気をつけろ！",
    )),
  ],
};

export const valueVillage: RegionDef = {
  slug: "value-village",
  name: L("Value Village", "Aldea de Valores", "バリュー村"),
  subtitle: L("types · references · pointers · vector", "tipos · referencias · punteros · vector", "型・参照・ポインタ・vector"),
  theme: "village",
  lessons: [boxes, lend, pointers, bags, boss],
};
