import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 2 · CLOSURE FOREST  (functions and arrows, scope and hoisting, closures, this)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");

// ─── 2.1 Spells: functions ─────────────────────────────────────────────────
const functions: LessonDef = {
  slug: "functions-and-arrows",
  title: L("Spells: functions", "Hechizos: funciones", "呪文：関数"),
  concept: "functions",
  mode: "lesson",
  xp: 65,
  enemy: "typescript/callback-spaghetti",
  enemyName: L("SPAGHETTI BUG", "BUG ESPAGUETI", "スパゲティバグ"),
  beats: [
    say(L(
      "Welcome to Closure Forest! A FUNCTION is a spell: write it once, cast it many times. Inputs go in, return sends a value out.",
      "¡Bienvenido al Bosque de Closures! Una FUNCIÓN es un hechizo: se escribe una vez y se lanza muchas. Entran datos y return saca un valor.",
      "クロージャの森へようこそ！関数は呪文。一度書けば何度でも唱えられる。入力を受けて return で値を返すよ。",
    )),
    {
      kind: "act",
      prompt: L("Write the spell, then cast it", "Escribe el hechizo y lánzalo", "呪文を書いて、唱えてみよう"),
      steps: [
        { label: L("NAME IT", "NOMBRARLO", "名前をつける"), line: "function add(a: number, b: number) {", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "add" }] },
        { label: L("RETURN", "RETURN", "return"), line: "  return a + b;" },
        { label: L("CLOSE", "CERRAR", "とじる"), line: "}", effects: [{ t: "say", actor: "hero", text: L("Spell ready!", "¡Hechizo listo!", "呪文かんせい！") }] },
        { label: L("CAST", "LANZAR", "唱える"), line: "console.log(add(2, 3));", effects: [{ t: "value", actor: "hero", text: "5" }, { t: "attack", from: "hero", to: "enemy" }, { t: "print", text: "5" }], output: "5" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "function add(a: number, b: number) {\n  return a + b;\n}\nconsole.log(add(4, 1), add(10, -3));",
      options: ["5 7", "41 10-3", "5 13"],
      answer: 0,
      output: "5 7",
      check: { compiles: true, stdout: "5 7" },
      explain: L("Each call fills a and b with new values: 4 + 1 and 10 + (-3).", "Cada llamada llena a y b con valores nuevos: 4 + 1 y 10 + (-3).", "呼ぶたびに a と b に新しい値が入る。4 + 1 と 10 + (-3) だよ。"),
      win: [{ t: "print", text: "5 7" }],
    },
    say(L(
      "No return? The spell still finishes, but hands back undefined.",
      "¿Sin return? El hechizo termina igual, pero devuelve undefined.",
      "return がない？呪文は終わるけど、返ってくるのは undefined だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "function heal(hp: number) {\n  hp + 5;\n}\nconsole.log(heal(10));",
      options: ["undefined", "15", "10"],
      answer: 0,
      output: "undefined",
      check: { compiles: true, stdout: "undefined" },
      explain: L("hp + 5 is computed and thrown away. Without return, a function gives undefined.", "hp + 5 se calcula y se tira. Sin return, una función devuelve undefined.", "hp + 5 は計算されて捨てられる。return がなければ undefined になるよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "heal" }],
      win: [{ t: "value", actor: "hero", text: "undefined" }, { t: "say", actor: "hero", text: L("Nothing came out!", "¡No salió nada!", "何も出ない！") }],
    },
    say(L(
      "ARROW functions are short spells: (n) => n * 2. With no braces, the value is returned automatically.",
      "Las funciones FLECHA son hechizos cortos: (n) => n * 2. Sin llaves, el valor se devuelve solo.",
      "アロー関数は短い呪文：(n) => n * 2。波かっこがなければ、値が自動で返るよ。",
    )),
    {
      kind: "type",
      prompt: L("Write the arrow", "Escribe la flecha", "矢印を書こう"),
      code: "const double = (n: number) ___ n * 2;\nconsole.log(double(4));",
      answer: "=>",
      check: { compiles: true, stdout: "8" },
      explain: L("=> separates the parameters from the result.", "=> separa los parámetros del resultado.", "=> は引数と結果を分ける記号だよ。"),
      win: [{ t: "print", text: "8" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "const sq = (n: number) => { n * n };\nconsole.log(sq(3));",
      options: ["undefined", "9", "NaN"],
      answer: 0,
      output: "undefined",
      check: { compiles: true, stdout: "undefined" },
      explain: L("The braces trap! With { } the arrow is a block and needs return. Without it: undefined.", "¡La trampa de las llaves! Con { } la flecha es un bloque y necesita return. Sin él: undefined.", "波かっこのワナ！{ } があるとブロックになり return が必要。ないと undefined。"),
      win: [{ t: "shake" }, { t: "print", text: "undefined" }],
    },
    say(L(
      "TypeScript types the inputs and the output: (s: string): number. Pass the wrong kind and it stops you.",
      "TypeScript tipa las entradas y la salida: (s: string): number. Si pasas otro tipo, te frena.",
      "TypeScript は入力と出力に型をつける：(s: string): number。違う型を渡すと止めてくれるよ。",
    )),
    {
      kind: "pick",
      prompt: L("What type does it return?", "¿Qué tipo devuelve?", "戻り値の型は？"),
      code: 'function len(s: string): ___ {\n  return s.length;\n}\nconsole.log(len("owl"));',
      options: ["number", "string", "void"],
      answer: 0,
      check: { compiles: true, stdout: "3", wrongFail: true },
      explain: L(".length is a number, so the return type is number. The others are error TS2322.", ".length es un number, así que el tipo de retorno es number. Los otros dan el error TS2322.", ".length は number だから戻り値も number。ほかはエラー TS2322 になるよ。"),
      win: [{ t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'function add(a: number, b: number): number {\n  return a + b;\n}\nadd(1, "2");',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2345: \"2\" is a string, but b must be a number. In plain JS it would print 12!", "Error TS2345: \"2\" es un string, pero b debe ser number. ¡En JS puro imprimiría 12!", "エラー TS2345：\"2\" は string、b は number が必要。素の JS なら 12 になっちゃう！"),
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Blocked!", "¡Bloqueado!", "ブロック！") }],
    },
    say(L(
      "Default parameters fill in missing arguments. ...rest gathers the extra ones into an array.",
      "Los parámetros por defecto rellenan argumentos que faltan. ...rest junta los sobrantes en un array.",
      "デフォルト引数は足りない引数をおぎなう。...rest は余った引数を配列にまとめるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'function greet(name = "hero") {\n  return "hi " + name;\n}\nconsole.log(greet(), greet("Ada"));',
      options: ["hi hero hi Ada", "hi undefined hi Ada", "hi hero hi hero"],
      answer: 0,
      output: "hi hero hi Ada",
      check: { compiles: true, stdout: "hi hero hi Ada" },
      explain: L("With no argument, name takes the default \"hero\". With one, the argument wins.", "Sin argumento, name toma el valor por defecto \"hero\". Con uno, gana el argumento.", "引数がなければ name はデフォルトの \"hero\"。渡せばその値が使われるよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "function sum(...nums: number[]) {\n  return nums.reduce((a, b) => a + b, 0);\n}\nconsole.log(sum(1, 2, 3));",
      options: ["6", "1", "123"],
      answer: 0,
      output: "6",
      check: { compiles: true, stdout: "6" },
      explain: L("...nums collects every argument into [1, 2, 3], and reduce adds them up.", "...nums junta todos los argumentos en [1, 2, 3], y reduce los suma.", "...nums が引数を [1, 2, 3] にまとめ、reduce で合計するよ。"),
    },
    {
      kind: "run",
      prompt: L("Fix the arrow: it must print 12", "Arregla la flecha: debe imprimir 12", "アロー関数を直そう：12 と表示させて"),
      starter: "const area = (w: number, h: number) => { w * h };\nconsole.log(area(3, 4));\n",
      solution: "const area = (w: number, h: number) => w * h;\nconsole.log(area(3, 4));\n",
      expect: "12",
      fallback: [String.raw`=>\s*\(?\s*w\s*\*\s*h`, String.raw`return\s+w\s*\*\s*h`, String.raw`=>\s*\(?\s*h\s*\*\s*w`, String.raw`return\s+h\s*\*\s*w`],
      explain: L("Drop the braces, or keep them and add return: { return w * h; }.", "Quita las llaves, o déjalas y agrega return: { return w * h; }.", "波かっこを消すか、残して return を書こう：{ return w * h; }。"),
    },
  ],
};

// ─── 2.2 The fog of scope ──────────────────────────────────────────────────
const scope: LessonDef = {
  slug: "scope-and-hoisting",
  title: L("The fog of scope", "La niebla del scope", "スコープの霧"),
  concept: "scope",
  mode: "lesson",
  xp: 70,
  enemy: "typescript/undefined-ghost",
  enemyName: L("FOG GHOST", "FANTASMA DE NIEBLA", "キリゴースト"),
  beats: [
    say(L(
      "SCOPE is where a name can be seen. let and const live only inside their { } block, like a clearing in the fog.",
      "El SCOPE es dónde se ve un nombre. let y const viven solo dentro de su bloque { }, como un claro en la niebla.",
      "スコープは名前が見える範囲。let と const は自分の { } ブロックの中だけ。霧の中の空き地みたいにね。",
    )),
    {
      kind: "act",
      prompt: L("Step into the clearing and back out", "Entra al claro y vuelve a salir", "空き地に入って、また出てみよう"),
      steps: [
        { label: L("OUTER n", "n DE AFUERA", "外の n"), line: "let n = 1;", effects: [{ t: "tag", actor: "hero", text: "n", value: "1" }] },
        { label: L("ENTER BLOCK", "ENTRAR", "ブロックへ"), line: "{" },
        { label: L("INNER n", "n DE ADENTRO", "中の n"), line: "  let n = 2;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "n", value: "2" }, { t: "say", actor: "ally", text: L("A NEW n!", "¡Un n NUEVO!", "新しい n！") }] },
        { label: L("LEAVE BLOCK", "SALIR", "ブロックを出る"), line: "}", effects: [{ t: "exit", actor: "ally" }] },
        { label: L("PRINT n", "IMPRIMIR n", "n を表示"), line: "console.log(n);", effects: [{ t: "print", text: "1" }], output: "1" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "let n = 1;\n{\n  let n = 2;\n}\nconsole.log(n);",
      options: ["1", "2", L("Error: n declared twice", "Error: n declarada dos veces", "エラー：n が2回宣言")],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("The inner let n is a NEW label that SHADOWS the outer one, and it vanishes with its block.", "El let n de adentro es una etiqueta NUEVA que OCULTA a la de afuera, y desaparece con su bloque.", "中の let n は外の n を隠す新しいラベル。ブロックを出ると消えるよ。"),
      win: [{ t: "print", text: "1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "let n = 1;\n{\n  n = 2;\n}\nconsole.log(n);",
      options: ["2", "1", "undefined"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("No let inside: the block reuses the outer n and changes it.", "Sin let adentro: el bloque usa el n de afuera y lo cambia.", "中に let がないから、外の n をそのまま書きかえるよ。"),
      setup: [{ t: "tag", actor: "hero", text: "n", value: "1" }],
      win: [{ t: "value", actor: "hero", text: "2" }, { t: "print", text: "2" }],
    },
    say(L(
      "var is the old way: it ignores { } blocks and belongs to the whole function. Prefer let and const.",
      "var es la forma antigua: ignora los bloques { } y pertenece a toda la función. Prefiere let y const.",
      "var は古い書き方。{ } ブロックを無視して関数全体のものになる。let と const を使おう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "function f() {\n  if (true) {\n    var a = 1;\n  }\n  return a;\n}\nconsole.log(f());",
      options: ["1", "undefined", "ReferenceError"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("var leaks out of the if block: a belongs to all of f.", "var se escapa del bloque if: a pertenece a toda f.", "var は if ブロックから漏れ出す。a は f 全体のものだよ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "{\n  let b = 2;\n}\nconsole.log(b);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2304: Cannot find name 'b'. Outside its block, b doesn't exist.", "Error TS2304: Cannot find name 'b'. Fuera de su bloque, b no existe.", "エラー TS2304：b が見つからない。ブロックの外に b はないんだ。"),
    },
    say(L(
      "HOISTING: before running, JS lifts declarations to the top of their scope. But let and const wait in the FOG.",
      "HOISTING: antes de ejecutar, JS sube las declaraciones al inicio de su scope. Pero let y const esperan en la NIEBLA.",
      "巻き上げ：実行前に JS は宣言をスコープの先頭へ持ち上げる。でも let と const は霧の中で待つんだ。",
    )),
    {
      kind: "act",
      prompt: L("Call show too early, then on time", "Llama a show muy pronto y luego a tiempo", "show を早すぎる時と、ちょうどの時に呼ぼう"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "y" }, { t: "dead", actor: "ally" }],
      steps: [
        { label: L("WRITE show", "ESCRIBIR show", "show を書く"), line: "const show = () => console.log(y);", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "show" }] },
        {
          label: L("CALL EARLY", "LLAMAR ANTES", "早く呼ぶ"),
          line: "show();",
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: L("Still in the fog!", "¡Sigo en la niebla!", "まだ霧の中！") }],
          error: {
            compiler: "ReferenceError: Cannot access 'y' before initialization",
            plain: L("y exists, but it's in the TDZ (the fog) until its let line runs.", "y existe, pero está en la TDZ (la niebla) hasta que corre su línea let.", "y はあるけど、let の行が動くまで TDZ（霧）の中なんだ。"),
          },
        },
        { label: L("DECLARE y", "DECLARAR y", "y を宣言"), line: "let y = 5;", effects: [{ t: "tag", actor: "ally", text: "y", value: "5" }, { t: "say", actor: "ally", text: L("I'm here!", "¡Llegué!", "来たよ！") }] },
        { label: L("CALL NOW", "LLAMAR AHORA", "いま呼ぶ"), line: "show();", effects: [{ t: "print", text: "5" }], output: "5" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'sayHi();\nfunction sayHi() {\n  console.log("hi");\n}',
      options: ["hi", "ReferenceError", "undefined"],
      answer: 0,
      output: "hi",
      check: { compiles: true, stdout: "hi" },
      explain: L("Function declarations are hoisted WHOLE, so you can call them before their line.", "Las declaraciones de función se elevan COMPLETAS, así que puedes llamarlas antes de su línea.", "関数宣言はまるごと巻き上げられる。だから書く前に呼べるんだ。"),
      win: [{ t: "print", text: "hi" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "function show() {\n  console.log(x);\n}\nshow();\nvar x = 5;",
      options: ["undefined", "5", "ReferenceError"],
      answer: 0,
      output: "undefined",
      check: { compiles: true, stdout: "undefined" },
      explain: L("var x is hoisted but starts as undefined. The = 5 only happens on its own line.", "var x se eleva pero empieza como undefined. El = 5 solo ocurre en su propia línea.", "var x は巻き上げられるけど最初は undefined。= 5 はその行で起きるよ。"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "x", value: "undefined" }],
      win: [{ t: "print", text: "undefined" }, { t: "say", actor: "enemy", text: L("Boo! Empty!", "¡Bu! ¡Vacío!", "ばあ！からっぽ！") }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "function show() {\n  console.log(y);\n}\nshow();\nlet y = 5;",
      options: ["ReferenceError", "undefined", "5"],
      answer: 0,
      check: { compiles: true, throws: "ReferenceError" },
      explain: L("let y is hoisted into the TDZ: touching it before its line throws ReferenceError.", "let y se eleva a la TDZ: tocarlo antes de su línea lanza ReferenceError.", "let y は TDZ に巻き上げられる。行より前にさわると ReferenceError だよ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "y" }, { t: "dead", actor: "ally" }],
      win: [{ t: "shake" }],
    },
    {
      kind: "order",
      prompt: L("Order it so it prints 10", "Ordénalo para que imprima 10", "10 と表示される順に並べよう"),
      lines: ["const base = 5;", "const total = base * 2;", "console.log(total);"],
      check: { compiles: true, stdout: "10" },
      explain: L("Declare before you use: base, then total, then print.", "Declara antes de usar: base, luego total, luego imprime.", "使う前に宣言しよう：base、total、そして表示。"),
    },
    {
      kind: "run",
      prompt: L("Clear the fog: it must print total: 10", "Despeja la niebla: debe imprimir total: 10", "霧をはらおう：total: 10 と表示させて"),
      starter: 'function report() {\n  console.log("total:", total);\n}\nreport();\nconst total = 5 * 2;\n',
      solution: 'function report() {\n  console.log("total:", total);\n}\nconst total = 5 * 2;\nreport();\n',
      expect: "total: 10",
      fallback: [String.raw`(?:const|let|var)\s+total\s*=[\s\S]*report\s*\(\s*\)\s*;`],
      explain: L("Call report() only after const total has run, so total is out of the TDZ.", "Llama a report() solo después de que corra const total, así total sale de la TDZ.", "const total の行のあとで report() を呼ぼう。そうすれば TDZ を抜けているよ。"),
    },
  ],
};

// ─── 2.3 The backpack spell (closures) ─────────────────────────────────────
const closures: LessonDef = {
  slug: "closures",
  title: L("The backpack spell", "El hechizo mochila", "リュックの呪文"),
  concept: "closures",
  mode: "lesson",
  xp: 75,
  enemy: "typescript/any-shifter",
  enemyName: L("BACKPACK THIEF", "LADRÓN DE MOCHILAS", "リュックどろぼう"),
  beats: [
    say(L(
      "A function REMEMBERS the variables around it, even after the outer function has ended. That memory is a CLOSURE.",
      "Una función RECUERDA las variables a su alrededor, incluso cuando la función de afuera ya terminó. Esa memoria es un CLOSURE.",
      "関数はまわりの変数をおぼえている。外の関数が終わったあともね。この記憶がクロージャだよ。",
    )),
    {
      kind: "act",
      prompt: L("Build a counter and press it", "Arma un contador y púlsalo", "カウンターを作って押してみよう"),
      steps: [
        { label: L("OUTER SPELL", "HECHIZO", "外の呪文"), line: "function makeCounter() {" },
        { label: L("PACK c", "GUARDAR c", "c を入れる"), line: "  let c = 0;", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "say", actor: "hero", text: L("c goes in the pack", "c va a la mochila", "c をリュックへ") }] },
        { label: L("RETURN KEY", "DAR LLAVE", "鍵を返す"), line: "  return () => ++c;\n}", effects: [{ t: "item", kind: "key", holder: "hero" }] },
        { label: L("MAKE ONE", "CREAR UNO", "ひとつ作る"), line: "const next = makeCounter();", effects: [{ t: "tag", actor: "hero", text: "next", value: "c=0" }] },
        { label: L("PRESS", "PULSAR", "押す"), line: "next();", effects: [{ t: "value", actor: "hero", text: "c=1" }] },
        { label: L("PRESS + PRINT", "PULSAR + VER", "押して表示"), line: "console.log(next());", effects: [{ t: "value", actor: "hero", text: "c=2" }, { t: "print", text: "2" }], output: "2" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "function makeCounter() {\n  let c = 0;\n  return () => ++c;\n}\nconst next = makeCounter();\nnext();\nnext();\nconsole.log(next());",
      options: ["3", "1", "0"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("makeCounter ended, but next still carries c in its backpack: 1, 2, 3.", "makeCounter terminó, pero next sigue llevando c en su mochila: 1, 2, 3.", "makeCounter は終わったけど、next はリュックに c を持ったまま：1、2、3。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "next", value: "c=0" }],
      win: [{ t: "value", actor: "hero", text: "c=3" }, { t: "print", text: "3" }],
    },
    say(L(
      "Each call to makeCounter packs a NEW backpack. Two counters never share their c.",
      "Cada llamada a makeCounter prepara una mochila NUEVA. Dos contadores nunca comparten su c.",
      "makeCounter を呼ぶたびに新しいリュックができる。2つのカウンターは c を共有しないよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "function makeCounter() {\n  let c = 0;\n  return () => ++c;\n}\nconst a = makeCounter();\nconst b = makeCounter();\na();\na();\nconsole.log(a(), b());",
      options: ["3 1", "3 4", "1 1"],
      answer: 0,
      output: "3 1",
      check: { compiles: true, stdout: "3 1" },
      explain: L("a and b each got their own c. a counted to 3; b only once, so 1.", "a y b recibieron cada uno su propio c. a contó hasta 3; b solo una vez, así que 1.", "a と b はそれぞれ自分の c を持つ。a は 3 まで、b は1回だけだから 1。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "c=0" }, { t: "enter", actor: "ally" }, { t: "item", kind: "key", holder: "ally" }, { t: "tag", actor: "ally", text: "b", value: "c=0" }],
      win: [{ t: "value", actor: "hero", text: "c=3" }, { t: "value", actor: "ally", text: "c=1" }, { t: "print", text: "3 1" }],
    },
    say(L(
      "A closure captures the VARIABLE itself, not a photo of its value. If the variable changes, the function sees it.",
      "Un closure captura la VARIABLE misma, no una foto de su valor. Si la variable cambia, la función lo ve.",
      "クロージャがつかむのは変数そのもの。値の写真じゃない。変数が変われば関数にも見えるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "let x = 1;\nconst show = () => console.log(x);\nx = 2;\nshow();",
      options: ["2", "1", "undefined"],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("show reads x when it runs, and by then x is 2.", "show lee x cuando se ejecuta, y para entonces x vale 2.", "show は実行したときに x を読む。そのとき x はもう 2 だよ。"),
    },
    say(L(
      "Loops! With let, each lap gets a FRESH i. With var, all laps share ONE i.",
      "¡Bucles! Con let, cada vuelta recibe un i NUEVO. Con var, todas las vueltas comparten UN solo i.",
      "ループでは、let なら1周ごとに新しい i。var だと全周でひとつの i を共有するよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
      options: ["3 3 3", "0 1 2", "2 2 2"],
      answer: 0,
      output: "3\n3\n3",
      check: { compiles: true, stdout: "3\n3\n3" },
      explain: L("The timers run after the loop. All three share one var i, which is 3 by then.", "Los timers corren después del bucle. Los tres comparten un solo var i, que ya vale 3.", "タイマーはループのあとで動く。3つとも同じ var i を見るから、もう 3 なんだ。"),
      win: [{ t: "print", text: "3" }, { t: "print", text: "3" }, { t: "print", text: "3" }],
    },
    {
      kind: "type",
      prompt: L("Give each lap its own i", "Dale a cada vuelta su propio i", "1周ごとに自分の i を"),
      code: "for (___ i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
      answer: "let",
      check: { compiles: true, stdout: "0\n1\n2" },
      explain: L("let creates a new i binding on every lap, so each timer remembers its own.", "let crea un nuevo i en cada vuelta, así cada timer recuerda el suyo.", "let は1周ごとに新しい i を作る。だからタイマーはそれぞれ自分の i をおぼえるよ。"),
      win: [{ t: "print", text: "0" }, { t: "print", text: "1" }, { t: "print", text: "2" }],
    },
    {
      kind: "pick",
      prompt: L("Make it work only once", "Que funcione solo una vez", "1回だけ動くようにしよう"),
      code: 'function once(fn: () => string) {\n  let done = false;\n  return () => {\n    if (done) return;\n    ___;\n    return fn();\n  };\n}\nconst init = once(() => "ran");\nconsole.log(init(), init());',
      options: ["done = true", "done = false", "fn()"],
      answer: 0,
      check: { compiles: true, stdout: "ran undefined" },
      explain: L("The backpack keeps done. Set it to true on the first call, and later calls stop early.", "La mochila guarda done. Ponlo en true en la primera llamada y las siguientes se detienen.", "リュックに done が残る。最初の呼び出しで true にすれば、次からはすぐ終わるよ。"),
      win: [{ t: "print", text: "ran undefined" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "const counter = (() => {\n  let n = 0;\n  return { inc: () => ++n, get: () => n };\n})();\nconsole.log(counter.n);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2339: n is not a property. It's hidden in the backpack: truly private state.", "Error TS2339: n no es una propiedad. Está escondido en la mochila: estado privado de verdad.", "エラー TS2339：n はプロパティじゃない。リュックに隠れた本当のプライベートな状態だよ。"),
      win: [{ t: "say", actor: "hero", text: L("Can't touch n!", "¡n es intocable!", "n にはさわれない！") }],
    },
    {
      kind: "run",
      prompt: L("Fix the loop: it must print 0,1,2", "Arregla el bucle: debe imprimir 0,1,2", "ループを直そう：0,1,2 と表示させて"),
      starter: 'const fns: (() => number)[] = [];\nfor (var i = 0; i < 3; i++) {\n  fns.push(() => i);\n}\nconsole.log(fns.map((f) => f()).join(","));\n',
      solution: 'const fns: (() => number)[] = [];\nfor (let i = 0; i < 3; i++) {\n  fns.push(() => i);\n}\nconsole.log(fns.map((f) => f()).join(","));\n',
      expect: "0,1,2",
      fallback: [String.raw`for\s*\(\s*let\s+i\b`, String.raw`const\s+\w+\s*=\s*i\s*;`],
      explain: L("With let i, each arrow captures its own lap's i: 0, 1 and 2.", "Con let i, cada flecha captura el i de su propia vuelta: 0, 1 y 2.", "let i なら、各アロー関数がその周の i をつかむ：0、1、2。"),
    },
  ],
};

// ─── 2.4 Who is this? ──────────────────────────────────────────────────────
const thisLesson: LessonDef = {
  slug: "this-and-binding",
  title: L("Who is this?", "¿Quién es this?", "this はだれ？"),
  concept: "this",
  mode: "lesson",
  xp: 80,
  enemy: "typescript/nan-gremlin",
  enemyName: L("KEY GREMLIN", "GREMLIN DE LLAVES", "カギグレムリン"),
  beats: [
    say(L(
      "In a method, this is whoever HOLDS the key when it turns. What matters is HOW the function is called, not where it was written.",
      "En un método, this es quien SOSTIENE la llave cuando gira. Importa CÓMO se llama la función, no dónde se escribió.",
      "メソッドの this は、鍵を回したときに持っている人。どこで書いたかより、どう呼んだかが大事だよ。",
    )),
    {
      kind: "act",
      prompt: L("Turn the key, then drop it", "Gira la llave y luego suéltala", "鍵を回して、それから手放そう"),
      steps: [
        { label: L("MAKE hero", "CREAR hero", "hero を作る"), line: 'const hero = {\n  name: "Ada",', effects: [{ t: "tag", actor: "hero", text: "hero" }, { t: "item", kind: "key", holder: "hero" }] },
        { label: L("ADD METHOD", "AÑADIR MÉTODO", "メソッド追加"), line: '  hi() { return "I am " + this.name; },\n};' },
        { label: L("TURN KEY", "GIRAR LLAVE", "鍵を回す"), line: "console.log(hero.hi());", effects: [{ t: "say", actor: "hero", text: L("this = me!", "¡this = yo!", "this はぼく！") }, { t: "print", text: "I am Ada" }], output: "I am Ada" },
        { label: L("DETACH", "SEPARAR", "取り外す"), line: "const hi = hero.hi;", effects: [{ t: "drop" }] },
        {
          label: L("CALL ALONE", "LLAMAR SOLA", "単独で呼ぶ"),
          line: "hi();",
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Nobody holds it!", "¡Nadie la tiene!", "だれも持ってない！") }],
          error: {
            compiler: "TypeError: Cannot read properties of undefined (reading 'name')",
            plain: L("Called alone, nobody holds the key: this is undefined.", "Llamada sola, nadie tiene la llave: this es undefined.", "単独で呼ぶと鍵の持ち主がいない。this は undefined だよ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const cat = {\n  name: "Tom",\n  meow() { return this.name + " says meow"; },\n};\nconsole.log(cat.meow());',
      options: ["Tom says meow", "undefined says meow", "TypeError"],
      answer: 0,
      output: "Tom says meow",
      check: { compiles: true, stdout: "Tom says meow" },
      explain: L("cat.meow(): cat holds the key, so this is cat.", "cat.meow(): cat tiene la llave, así que this es cat.", "cat.meow() は cat が鍵を持っているから、this は cat だよ。"),
      setup: [{ t: "tag", actor: "hero", text: "cat" }, { t: "item", kind: "key", holder: "hero" }],
      win: [{ t: "print", text: "Tom says meow" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'class Hero {\n  name = "Ada";\n  hi() { return this.name; }\n}\nconst h = new Hero();\nconst f = h.hi;\nconsole.log(f());',
      options: ["TypeError", "Ada", "undefined"],
      answer: 0,
      check: { compiles: true, throws: "TypeError" },
      explain: L("f() is a plain call: this is undefined, and reading undefined.name throws TypeError.", "f() es una llamada simple: this es undefined, y leer undefined.name lanza TypeError.", "f() はただの呼び出しで this は undefined。undefined.name を読むと TypeError。"),
      setup: [{ t: "tag", actor: "hero", text: "h" }, { t: "item", kind: "key", holder: "hero" }],
      win: [{ t: "drop" }, { t: "shake" }],
    },
    say(L(
      "Fix a lost this with bind: it makes a COPY of the function with this glued on for good.",
      "Arregla un this perdido con bind: crea una COPIA de la función con this pegado para siempre.",
      "迷子の this は bind で直せる。this を固定した関数のコピーを作るんだ。",
    )),
    {
      kind: "pick",
      prompt: L("Glue h as this", "Pega h como this", "h を this に固定しよう"),
      code: 'class Hero {\n  name = "Ada";\n  hi() { return this.name; }\n}\nconst h = new Hero();\nconst f = h.hi.___(h);\nconsole.log(f());',
      options: ["bind", "call", "apply"],
      answer: 0,
      check: { compiles: true, stdout: "Ada", wrongFail: true },
      explain: L("bind returns a new function. call and apply run it NOW and return a string, so f() fails.", "bind devuelve una función nueva. call y apply la ejecutan YA y devuelven un string, así que f() falla.", "bind は新しい関数を返す。call と apply はすぐ実行して文字列を返すから f() は失敗するよ。"),
      setup: [{ t: "tag", actor: "hero", text: "h" }, { t: "item", kind: "key", holder: "hero" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "f" }, { t: "lend", to: "ally" }, { t: "print", text: "Ada" }],
    },
    say(L(
      "call and apply run the function NOW with a chosen this. call takes arguments one by one; apply takes an array.",
      "call y apply ejecutan la función YA con el this que elijas. call recibe argumentos uno a uno; apply, un array.",
      "call と apply は this を指定してすぐ実行する。call は引数を1つずつ、apply は配列で渡すよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'function intro(this: { name: string }, greet: string) {\n  return greet + ", " + this.name;\n}\nconsole.log(intro.call({ name: "Bo" }, "Hey"), intro.apply({ name: "Cy" }, ["Yo"]));',
      options: ["Hey, Bo Yo, Cy", "Hey, Cy Yo, Bo", "Hey, undefined Yo, undefined"],
      answer: 0,
      output: "Hey, Bo Yo, Cy",
      check: { compiles: true, stdout: "Hey, Bo Yo, Cy" },
      explain: L("The first argument becomes this. call passes \"Hey\" directly; apply unpacks [\"Yo\"].", "El primer argumento pasa a ser this. call pasa \"Hey\" directo; apply desempaca [\"Yo\"].", "最初の引数が this になる。call は \"Hey\" をそのまま、apply は [\"Yo\"] を展開して渡すよ。"),
    },
    {
      kind: "type",
      prompt: L("Run f now with v = 7", "Ejecuta f ya con v = 7", "v = 7 で f をすぐ実行"),
      code: "function f(this: { v: number }) {\n  return this.v;\n}\nconsole.log(f.___({ v: 7 }));",
      answer: "call",
      check: { compiles: true, stdout: "7" },
      explain: L("f.call(obj) runs f right away with this = obj.", "f.call(obj) ejecuta f enseguida con this = obj.", "f.call(obj) は this = obj で f をすぐ実行するよ。"),
      win: [{ t: "print", text: "7" }],
    },
    {
      kind: "pick",
      prompt: L("Spread the array into max", "Pasa el array a max", "配列を max に渡そう"),
      code: "console.log(Math.max.___(null, [3, 9, 4]));",
      options: ["apply", "call", "bind"],
      answer: 0,
      check: { compiles: true, stdout: "9", wrongFail: true },
      explain: L("apply takes the arguments as an array. call and bind expect them one by one: TS2345.", "apply recibe los argumentos como array. call y bind los esperan uno a uno: TS2345.", "apply は引数を配列で受け取る。call と bind は1つずつ渡すからエラー TS2345。"),
      win: [{ t: "print", text: "9" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "function f(this: { v: number }) {\n  return this.v;\n}\nconst g = f.bind({ v: 1 });\nconsole.log(g.call({ v: 2 }));",
      options: ["1", "2", "undefined"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("Once bound, this is glued: a later call can't change it.", "Una vez con bind, this queda pegado: un call posterior no puede cambiarlo.", "bind したら this は固定。あとで call しても変わらないよ。"),
    },
    say(L(
      "ARROW functions have no this of their own: they borrow it from the code around them. Perfect for callbacks in methods.",
      "Las funciones FLECHA no tienen this propio: lo toman del código que las rodea. Perfectas para callbacks en métodos.",
      "アロー関数は自分の this を持たず、まわりのコードから借りる。メソッド内のコールバックにぴったり。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const team = {\n  name: "Ada",\n  later() { return [1].map(() => this.name)[0]; },\n};\nconsole.log(team.later());',
      options: ["Ada", "undefined", "TypeError"],
      answer: 0,
      output: "Ada",
      check: { compiles: true, stdout: "Ada" },
      explain: L("The arrow uses later's this, which is team.", "La flecha usa el this de later, que es team.", "アロー関数は later の this、つまり team を使うよ。"),
      win: [{ t: "print", text: "Ada" }],
    },
    {
      kind: "run",
      prompt: L("Fix the callback: it must print count: 6", "Arregla el callback: debe imprimir count: 6", "コールバックを直そう：count: 6 と表示させて"),
      starter: 'class Counter {\n  count = 0;\n  addAll(list: number[]) {\n    list.forEach(function (n) {\n      this.count += n;\n    });\n  }\n}\nconst c = new Counter();\nc.addAll([1, 2, 3]);\nconsole.log("count:", c.count);\n',
      solution: 'class Counter {\n  count = 0;\n  addAll(list: number[]) {\n    list.forEach((n) => {\n      this.count += n;\n    });\n  }\n}\nconst c = new Counter();\nc.addAll([1, 2, 3]);\nconsole.log("count:", c.count);\n',
      expect: "count: 6",
      fallback: [String.raw`forEach\s*\(\s*\(?\s*n\s*(?::\s*number\s*)?\)?\s*=>`, String.raw`\}\s*\.bind\s*\(\s*this\s*\)`, String.raw`for\s*\(\s*const\s+n\s+of\s+list\s*\)`],
      explain: L("A plain function callback loses this. An arrow borrows addAll's this, the counter.", "Un callback con function pierde this. Una flecha toma el this de addAll: el contador.", "function のコールバックは this を失う。アロー関数なら addAll の this を借りられるよ。"),
    },
  ],
};

// ─── 2.5 Boss: Closure Wraith ──────────────────────────────────────────────
const boss: LessonDef = {
  slug: "closure-wraith",
  title: L("Boss: Closure Wraith", "Jefe: Espectro Closure", "ボス：クロージャの亡霊"),
  concept: "closures",
  mode: "boss",
  xp: 180,
  enemy: "ghost",
  enemyName: L("CLOSURE WRAITH", "ESPECTRO CLOSURE", "クロージャの亡霊"),
  beats: [
    enemySays(L(
      "I AM THE CLOSURE WRAITH. I hide in old scopes and steal lost this. Who sees what, and when?",
      "SOY EL ESPECTRO CLOSURE. Me escondo en scopes viejos y robo los this perdidos. ¿Quién ve qué, y cuándo?",
      "我はクロージャの亡霊。古いスコープに潜み、迷子の this を奪う。だれが、いつ、何を見る？",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "function check() {\n  console.log(typeof hoisted, typeof notHoisted);\n}\ncheck();\nfunction hoisted() {}\nvar notHoisted = () => {};", options: ["function undefined", "function function", "undefined undefined"], answer: 0, output: "function undefined", check: { compiles: true, stdout: "function undefined" }, explain: L("Declarations hoist whole; a var hoists as undefined.", "Las declaraciones se elevan enteras; un var, como undefined.", "関数宣言はまるごと、var は undefined で巻き上げ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}", options: ["3 3 3", "0 1 2"], answer: 0, output: "3\n3\n3", check: { compiles: true, stdout: "3\n3\n3" }, explain: L("One shared var i, already 3 when timers run.", "Un solo var i compartido, ya en 3 al correr los timers.", "共有の var i はタイマー実行時もう 3。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "function makeAdder(x: number) {\n  return (y: number) => x + y;\n}\nconst add5 = makeAdder(5);\nconsole.log(add5(2), makeAdder(1)(1));", options: ["7 2", "7 7", "2 2"], answer: 0, output: "7 2", check: { compiles: true, stdout: "7 2" }, explain: L("Each adder remembers its own x.", "Cada sumador recuerda su propio x.", "それぞれが自分の x をおぼえている。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: "function f() {\n  const peek = () => x;\n  console.log(peek());\n  const x = 2;\n}\nf();", options: ["ReferenceError", "2", "undefined"], answer: 0, check: { compiles: true, throws: "ReferenceError" }, explain: L("x is still in the TDZ when peek reads it.", "x sigue en la TDZ cuando peek lo lee.", "peek が読むとき x はまだ TDZ の中。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "function f(this: { v: number }) {\n  return this.v;\n}\nconst g = f.bind({ v: 1 });\nconsole.log(g.call({ v: 2 }));", options: ["1", "2"], answer: 0, output: "1", check: { compiles: true, stdout: "1" }, explain: L("bind wins: call can't re-glue this.", "bind gana: call no puede volver a pegar this.", "bind が勝つ。call で this は変えられない。") },
    { kind: "pick", time: 15, prompt: L("Which keeps this?", "¿Cuál conserva this?", "this を保てるのは？"), code: 'class Owl {\n  name = "Tyto";\n  later() { return [1].map(___)[0]; }\n}\nconsole.log(new Owl().later());', options: ["() => this.name", "function () { return this.name; }"], answer: 0, check: { compiles: true, stdout: "Tyto", wrongFail: true }, explain: L("The arrow borrows later's this; function has its own.", "La flecha toma el this de later; function tiene el suyo.", "アローは later の this を借りる。function は別の this。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'function greet(name: string | null = "hero") {\n  return "hi " + name;\n}\nconsole.log(greet(undefined), greet(null));', options: ["hi hero hi null", "hi hero hi hero", "hi undefined hi null"], answer: 0, output: "hi hero hi null", check: { compiles: true, stdout: "hi hero hi null" }, explain: L("Defaults apply only to undefined, not null.", "El valor por defecto solo aplica a undefined, no a null.", "デフォルトは undefined のときだけ。null には効かない。") },
    { kind: "type", time: 12, prompt: L("Braces need it", "Las llaves lo necesitan", "波かっこには必要"), code: "const sq = (n: number) => { ___ n * n; };\nconsole.log(sq(3));", answer: "return", check: { compiles: true, stdout: "9" }, explain: L("A block body returns nothing without return.", "Un cuerpo con bloque no devuelve nada sin return.", "ブロックの本体は return がないと何も返さない。") },
    { kind: "order", time: 15, prompt: L("Build once", "Arma once", "once を組み立てよう"), lines: ["function once(fn: () => void) {", "let done = false;", "return () => {", "if (done) return;", "done = true;", "return fn();", "};", "}"], check: { compiles: true }, explain: L("The backpack holds done; flip it before calling fn.", "La mochila guarda done; cámbialo antes de llamar a fn.", "リュックに done。fn を呼ぶ前に true にする。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "function f(...nums: number[]) {\n  return nums.length;\n}\nconsole.log(f(), f(1, 2, 3));", options: ["0 3", "undefined 3", "1 3"], answer: 0, output: "0 3", check: { compiles: true, stdout: "0 3" }, explain: L("With no arguments, rest is an empty array.", "Sin argumentos, rest es un array vacío.", "引数なしなら rest は空の配列。") },
    enemySays(L(
      "No... every scope seen, every this found. Go on, then: the peaks of prototypes await.",
      "No... viste cada scope y hallaste cada this. Sigue, entonces: te esperan los picos de los prototipos.",
      "ばかな…すべてのスコープを見通し、this を見つけたか。行け、プロトタイプの峰が待っている。",
    )),
  ],
};

export const closureForest: RegionDef = {
  slug: "closure-forest",
  name: L("Closure Forest", "Bosque de Closures", "クロージャの森"),
  subtitle: L("Functions · scope · closures · this", "Funciones · scope · closures · this", "関数・スコープ・クロージャ・this"),
  theme: "forest",
  lessons: [functions, scope, closures, thisLesson, boss],
};
