import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 5 · EVENT LOOP TOWER (timers and the call stack, promises, async/await and errors,
// microtasks vs macrotasks). Stage mapping: hero = call stack, ally = microtask queue (VIP line),
// enemy = timer queue (macrotasks). Every ordering answer is what the game runner really prints.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
/** Code is written line by line for readability. */
const code = (...lines: string[]) => lines.join("\n");

// Shared labels and answers.
const WHAT_PRINTS = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const IN_ORDER = L("In what order does it print?", "¿En qué orden imprime?", "どの順番で表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルは通る？");
const YES = L("Yes", "Sí", "はい");
const LOG = L("LOG", "LOG", "ログ");
const LATER = L("Later!", "¡Luego!", "あとでね！");
const WAIT_ = L("WAIT", "ESPERAR", "待つ");
const WAIT_DEF = "const wait = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));";

// ─── 5.1 timers and the call stack ──────────────────────────────────────────
const timers: LessonDef = {
  slug: "callbacks-and-timers",
  title: L("Later, not now", "Luego, no ahora", "今じゃなく、あとで"),
  concept: "event_loop",
  mode: "lesson",
  xp: 60,
  enemy: "typescript/nan-gremlin",
  enemyName: L("IMPATIENT GREMLIN", "GREMLIN IMPACIENTE", "せっかちグレムリン"),
  beats: [
    say(L(
      "Welcome to the Event Loop Tower! JavaScript does ONE thing at a time. The line it is running sits on the call stack.",
      "¡Bienvenido a la Torre del Event Loop! JavaScript hace UNA cosa a la vez. La línea que corre está en la pila de llamadas.",
      "イベントループの塔へようこそ！JavaScript は一度に「ひとつ」しか実行しない。今のコードはコールスタックに乗っているよ。",
    )),
    {
      kind: "act",
      prompt: L("Press in order: who prints first?", "Pulsa en orden: ¿quién imprime primero?", "順番に押そう。先に表示されるのは？"),
      setup: [{ t: "tag", actor: "hero", text: "stack" }],
      steps: [
        { label: L("LOG A", "LOG A", "A を表示"), line: 'console.log("A");', output: "A", effects: [{ t: "say", actor: "hero", text: L("A, right now!", "¡A, ya mismo!", "A、今すぐ！") }] },
        {
          label: L("SCHEDULE B", "PROGRAMAR B", "B を予約"),
          line: 'setTimeout(() => console.log("B"), 0);',
          effects: [{ t: "item", kind: "scroll", holder: "enemy" }, { t: "tag", actor: "enemy", text: "timers" }, { t: "say", actor: "enemy", text: LATER }],
        },
        { label: L("LOG C", "LOG C", "C を表示"), line: 'console.log("C");', output: "C", effects: [{ t: "say", actor: "hero", text: L("C, right now!", "¡C, ya mismo!", "C、今すぐ！") }] },
        { label: L("STACK EMPTY", "PILA VACÍA", "スタック空"), output: "B", effects: [{ t: "give", to: "hero" }, { t: "banner", text: L("NOW THE TIMER", "AHORA EL TIMER", "タイマーの番") }] },
      ],
    },
    say(L(
      "setTimeout hands the callback to the timer queue. It runs only when the stack is EMPTY, even with 0 ms.",
      "setTimeout entrega el callback a la cola de timers. Corre solo cuando la pila está VACÍA, aunque sea con 0 ms.",
      "setTimeout はコールバックをタイマーの列に預ける。0 ms でも、スタックが空になってから動くよ。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code('console.log("A");', 'setTimeout(() => console.log("B"), 0);', 'console.log("C");'),
      options: ["A B C", "A C B", "B A C"],
      answer: 1,
      output: "A\nC\nB",
      explain: L(
        "A and C are synchronous and finish first. B waits in the timer queue until the stack is empty.",
        "A y C son síncronos y terminan primero. B espera en la cola de timers hasta que la pila quede vacía.",
        "A と C は同期処理なので先に終わる。B はスタックが空になるまでタイマーの列で待つよ。",
      ),
      check: { compiles: true, stdout: "A\nC\nB" },
      setup: [{ t: "tag", actor: "hero", text: "stack" }, { t: "item", kind: "scroll", holder: "enemy" }],
      win: [{ t: "print", text: "A" }, { t: "print", text: "C" }, { t: "give", to: "hero" }, { t: "print", text: "B" }],
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code('setTimeout(() => console.log("1"), 100);', 'setTimeout(() => console.log("2"), 0);'),
      options: ["1 2", "2 1"],
      answer: 1,
      output: "2\n1",
      explain: L(
        "Timers fire by delay, not by line order: the 0 ms timer is due long before the 100 ms one.",
        "Los timers saltan según su retraso, no según el orden de las líneas: el de 0 ms vence mucho antes que el de 100 ms.",
        "タイマーは書いた順ではなく待ち時間の順に動く。0 ms のほうが 100 ms よりずっと先だよ。",
      ),
      check: { compiles: true, stdout: "2\n1" },
      win: [{ t: "print", text: "2" }, { t: "print", text: "1" }],
    },
    say(L(
      "A slow loop keeps the stack busy. The timer is ready, but it must wait its turn. Nobody interrupts the stack.",
      "Un bucle lento mantiene ocupada la pila. El timer está listo, pero espera su turno. Nadie interrumpe la pila.",
      "重いループはスタックをふさぐ。タイマーは準備できても順番待ち。スタックは誰にも割り込まれないよ。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code('setTimeout(() => console.log("x"), 0);', "for (let i = 0; i < 1e7; i++) {}", 'console.log("y");'),
      options: ["x y", "y x"],
      answer: 1,
      output: "y\nx",
      explain: L(
        "The loop and y run on the stack first. The timer callback only gets a turn once all that synchronous work ends.",
        "El bucle y la y corren primero en la pila. El callback del timer solo tiene turno cuando termina todo lo síncrono.",
        "ループと y が先にスタックで動く。タイマーのコールバックは同期処理が全部終わってからだよ。",
      ),
      check: { compiles: true, stdout: "y\nx" },
      setup: [{ t: "item", kind: "scroll", holder: "enemy" }],
      win: [{ t: "print", text: "y" }, { t: "give", to: "hero" }, { t: "print", text: "x" }],
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(
        "function load(cb: (d: string) => void) {",
        '  setTimeout(() => cb("data"), 0);',
        "}",
        "load((d) => console.log(d));",
        'console.log("waiting");',
      ),
      options: ["data waiting", "waiting data"],
      answer: 1,
      output: "waiting\ndata",
      explain: L(
        "A callback is a function you hand over to be called later. load returns at once, so waiting prints first.",
        "Un callback es una función que entregas para que la llamen después. load vuelve enseguida, así que waiting sale primero.",
        "コールバックは「あとで呼んでね」と渡す関数。load はすぐ戻るので waiting が先だよ。",
      ),
      check: { compiles: true, stdout: "waiting\ndata" },
    },
    say(L(
      "Changed your mind? setTimeout returns an id. Pass it to clearTimeout and the callback never runs.",
      "¿Cambiaste de idea? setTimeout devuelve un id. Pásalo a clearTimeout y el callback nunca corre.",
      "気が変わった？ setTimeout は id を返す。clearTimeout に渡せばコールバックは動かないよ。",
    )),
    {
      kind: "pick",
      prompt: L("Cancel the timer before it fires", "Cancela el timer antes de que salte", "動く前にタイマーを取り消そう"),
      code: code('const t = setTimeout(() => console.log("boom"), 0);', "___(t);", 'console.log("safe");'),
      options: ["clearTimeout", "setTimeout", "stopTimeout"],
      answer: 0,
      explain: L(
        "clearTimeout(t) removes the scheduled callback, so only safe prints. stopTimeout doesn't exist.",
        "clearTimeout(t) quita el callback programado, así que solo se imprime safe. stopTimeout no existe.",
        "clearTimeout(t) で予約したコールバックを消す。だから safe だけ表示。stopTimeout は存在しないよ。",
      ),
      check: { compiles: true, stdout: "safe", wrongFail: true },
      setup: [{ t: "item", kind: "scroll", holder: "enemy" }],
      win: [{ t: "drop" }, { t: "print", text: "safe" }],
    },
    {
      kind: "type",
      prompt: L("Schedule the callback for later", "Programa el callback para después", "コールバックをあとで動かそう"),
      code: code('___(() => console.log("later"), 0);', 'console.log("now");'),
      answer: "setTimeout",
      explain: L(
        "setTimeout(callback, ms) queues the callback; now prints first because the stack finishes its work.",
        "setTimeout(callback, ms) encola el callback; now sale primero porque la pila termina su trabajo.",
        "setTimeout(callback, ms) でコールバックを列に入れる。スタックの処理が先なので now が先に出るよ。",
      ),
      check: { compiles: true, stdout: "now\nlater" },
      win: [{ t: "print", text: "now" }, { t: "print", text: "later" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print go", "Arréglalo: debe imprimir go", "直そう：go と表示させる"),
      starter: code("let ready = false;", "setTimeout(() => {", "  ready = true;", "}, 0);", 'console.log(ready ? "go" : "wait");', ""),
      solution: code("let ready = false;", "setTimeout(() => {", "  ready = true;", '  console.log(ready ? "go" : "wait");', "}, 0);", ""),
      expect: "go",
      fallback: [
        String.raw`ready\s*=\s*true;?\s*console\.log\(`,
        String.raw`setTimeout\(\s*\(\)\s*=>\s*console\.log\(\s*ready`,
      ],
      explain: L(
        "The log runs before the timer, so ready is still false. Log inside the callback, after ready = true.",
        "El log corre antes que el timer, así que ready sigue en false. Haz el log dentro del callback, tras ready = true.",
        "ログがタイマーより先に動くので ready はまだ false。ready = true の後、コールバックの中でログしよう。",
      ),
    },
  ],
};

// ─── 5.2 promises ───────────────────────────────────────────────────────────
const promises: LessonDef = {
  slug: "promise-chains",
  title: L("Sealed scrolls", "Pergaminos sellados", "封印された巻物"),
  concept: "async",
  mode: "lesson",
  xp: 65,
  enemy: "typescript/undefined-ghost",
  enemyName: L("UNDEFINED GHOST", "FANTASMA UNDEFINED", "undefined おばけ"),
  beats: [
    say(L(
      "A Promise is a sealed scroll: a value that arrives LATER. It is pending, then fulfilled or rejected, only once.",
      "Una Promise es un pergamino sellado: un valor que llega DESPUÉS. Está pendiente y luego se cumple o se rechaza, una sola vez.",
      "Promise は封印された巻物。値は「あとで」届く。保留中から、成功か失敗に一度だけ決まるよ。",
    )),
    {
      kind: "act",
      prompt: L("Seal a scroll and read it with then", "Sella un pergamino y léelo con then", "巻物を封印して then で読もう"),
      setup: [],
      steps: [
        {
          label: L("SEAL", "SELLAR", "封印"),
          line: "const p = new Promise<string>((resolve) => {",
          effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "p" }, { t: "say", actor: "hero", text: L("pending...", "pendiente...", "保留中…") }],
        },
        { label: L("RESOLVE", "RESOLVER", "解決"), line: '  resolve("gold");\n});', effects: [{ t: "value", actor: "hero", text: '"gold"' }, { t: "banner", text: L("FULFILLED", "CUMPLIDA", "成功") }] },
        { label: L("THEN", "THEN", "then"), line: "p.then((v) => console.log(v));", output: "gold", effects: [{ t: "enter", actor: "ally" }, { t: "give", to: "ally" }, { t: "say", actor: "ally", text: L("It says gold!", "¡Dice gold!", "gold だって！") }] },
        {
          label: L("REJECT", "RECHAZAR", "失敗"),
          line: 'Promise.reject(new Error("burnt"))\n  .catch((e) => console.log(e.message));',
          output: "burnt",
          effects: [{ t: "item", kind: "scroll", holder: "enemy" }, { t: "shake" }, { t: "say", actor: "enemy", text: L("It burns!", "¡Se quema!", "燃えてる！") }],
        },
      ],
    },
    say(L(
      "The function you pass to new Promise runs RIGHT AWAY. Only then and catch callbacks wait for later.",
      "La función que pasas a new Promise corre DE INMEDIATO. Solo los callbacks de then y catch esperan.",
      "new Promise に渡す関数は「すぐ」動く。あとで動くのは then と catch のコールバックだけだよ。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code("new Promise<void>((resolve) => {", '  console.log("A");', "  resolve();", "});", 'console.log("B");'),
      options: ["A B", "B A"],
      answer: 0,
      output: "A\nB",
      explain: L(
        "The executor runs synchronously, during new Promise. So A prints before B.",
        "El ejecutor corre de forma síncrona, durante new Promise. Por eso A sale antes que B.",
        "executor は new Promise の最中に同期的に動く。だから A が B より先だよ。",
      ),
      check: { compiles: true, stdout: "A\nB" },
      win: [{ t: "print", text: "A" }, { t: "print", text: "B" }],
    },
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code("Promise.resolve(1)", "  .then((x) => x + 1)", "  .then((x) => console.log(x));"),
      options: ["1", "2", "undefined"],
      answer: 1,
      output: "2",
      explain: L(
        "then returns a NEW promise holding what its callback returns. 1 becomes 2 for the next then.",
        "then devuelve una promesa NUEVA con lo que retorna su callback. 1 se vuelve 2 para el siguiente then.",
        "then はコールバックの戻り値を持つ「新しい」Promise を返す。1 が 2 になって次の then へ。",
      ),
      check: { compiles: true, stdout: "2" },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "value", actor: "hero", text: "1" }],
      win: [{ t: "value", actor: "hero", text: "2" }, { t: "print", text: "2" }],
    },
    say(L(
      "A throw inside then burns the scroll. Every then is skipped until a catch puts out the fire.",
      "Un throw dentro de then quema el pergamino. Se saltan todos los then hasta que un catch apaga el fuego.",
      "then の中で throw すると巻物が燃える。catch が火を消すまで、then は全部飛ばされるよ。",
    )),
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code(
        "Promise.resolve(1)",
        '  .then(() => { throw new Error("boom"); })',
        '  .then(() => console.log("skipped"))',
        "  .catch((e) => console.log(e.message));",
      ),
      options: ["skipped", "boom", L("skipped and boom", "skipped y boom", "skipped と boom")],
      answer: 1,
      output: "boom",
      explain: L(
        "The error rejects the chain: the second then is skipped and catch receives the Error.",
        "El error rechaza la cadena: el segundo then se salta y catch recibe el Error.",
        "エラーでチェーンが失敗になる。2つ目の then は飛ばされ、catch が Error を受け取るよ。",
      ),
      check: { compiles: true, stdout: "boom" },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }],
      win: [{ t: "shake" }, { t: "print", text: "boom" }],
    },
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code("Promise.resolve(5)", "  .then((x) => { x * 2; })", "  .then((v) => console.log(v));"),
      options: ["10", "5", "undefined"],
      answer: 2,
      output: "undefined",
      explain: L(
        "With braces, an arrow needs return. Nothing is returned, so the next then gets undefined.",
        "Con llaves, la flecha necesita return. No se devuelve nada, así que el siguiente then recibe undefined.",
        "波かっこ付きのアロー関数は return が必要。何も返さないので次の then は undefined を受け取るよ。",
      ),
      check: { compiles: true, stdout: "undefined" },
      win: [{ t: "enter", actor: "enemy" }, { t: "say", actor: "enemy", text: L("Boo! undefined!", "¡Bu! ¡undefined!", "ばあ！undefined！") }],
    },
    say(L(
      "Many scrolls at once? Promise.all waits for ALL and fails fast if one fails. Promise.any wants the first success.",
      "¿Muchos pergaminos a la vez? Promise.all espera a TODOS y falla en cuanto uno falla. Promise.any quiere el primer éxito.",
      "巻物がたくさん？ Promise.all は全部を待ち、一つでも失敗すれば即失敗。Promise.any は最初の成功を取るよ。",
    )),
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code(
        "Promise.all([",
        "  Promise.resolve(1),",
        '  Promise.reject(new Error("no")),',
        "])",
        '  .then(() => console.log("all ok"))',
        '  .catch((e) => console.log("fail:", e.message));',
      ),
      options: ["all ok", "fail: no", L("Nothing", "Nada", "何も出ない")],
      answer: 1,
      output: "fail: no",
      explain: L(
        "Promise.all rejects as soon as one promise rejects, with that error. Use allSettled to keep every result.",
        "Promise.all se rechaza en cuanto una promesa se rechaza, con ese error. Usa allSettled para conservar todos.",
        "Promise.all は一つが失敗した時点でその理由で失敗する。全部の結果が欲しいなら allSettled だよ。",
      ),
      check: { compiles: true, stdout: "fail: no" },
    },
    {
      kind: "pick",
      prompt: L("Take the first SUCCESS, ignore failures", "Toma el primer ÉXITO, ignora fallos", "最初の成功を取り、失敗は無視"),
      code: code('Promise.___([Promise.reject(new Error("a")), Promise.resolve(2)])', "  .then((v) => console.log(v));"),
      options: ["any", "all", "race"],
      answer: 0,
      explain: L(
        "Promise.any skips rejections and settles with the first fulfilled value: 2. all and race would reject here.",
        "Promise.any ignora los rechazos y se cumple con el primer valor exitoso: 2. all y race se rechazarían aquí.",
        "Promise.any は失敗を無視して最初の成功値 2 になる。ここで all や race を使うと失敗になるよ。",
      ),
      check: { compiles: true, stdout: "2" },
    },
    {
      kind: "type",
      prompt: L("Put out the fire", "Apaga el fuego", "火を消そう"),
      code: code('Promise.reject(new Error("x"))', '  .___((e) => console.log("caught", e.message));'),
      answer: "catch",
      explain: L(
        "catch handles a rejection, like then handles success. Without it the error is unhandled.",
        "catch maneja un rechazo, como then maneja el éxito. Sin él, el error queda sin manejar.",
        "catch は失敗を、then は成功を受け取る。catch がないとエラーは処理されないままだよ。",
      ),
      check: { compiles: true, stdout: "caught x" },
      setup: [{ t: "item", kind: "scroll", holder: "enemy" }, { t: "shake" }],
      win: [{ t: "drop" }, { t: "print", text: "caught x" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print xp: 30", "Arréglalo: debe imprimir xp: 30", "直そう：xp: 30 と表示させる"),
      starter: code(
        "function fetchLevel() {",
        "  return Promise.resolve(3);",
        "}",
        "fetchLevel()",
        "  .then((lv) => { lv * 10; })",
        '  .then((xp) => console.log("xp:", xp));',
        "",
      ),
      solution: code(
        "function fetchLevel() {",
        "  return Promise.resolve(3);",
        "}",
        "fetchLevel()",
        "  .then((lv) => lv * 10)",
        '  .then((xp) => console.log("xp:", xp));',
        "",
      ),
      expect: "xp: 30",
      fallback: [String.raw`\(?lv\)?\s*=>\s*lv\s*\*\s*10`, String.raw`return\s+lv\s*\*\s*10`],
      explain: L(
        "The braces swallow the value: return lv * 10, or drop the braces so the arrow returns it.",
        "Las llaves se tragan el valor: usa return lv * 10, o quita las llaves para que la flecha lo devuelva.",
        "波かっこが値を飲み込んでいる。return lv * 10 にするか、波かっこを外して値を返そう。",
      ),
    },
  ],
};

// ─── 5.3 async/await and errors ─────────────────────────────────────────────
const asyncAwait: LessonDef = {
  slug: "async-await-errors",
  title: L("Waiting spells", "Hechizos de espera", "待つ呪文"),
  concept: "async",
  mode: "lesson",
  xp: 70,
  enemy: "typescript/any-shifter",
  enemyName: L("FORGETFUL SHIFTER", "MUTANTE OLVIDADIZO", "わすれんぼシフター"),
  beats: [
    say(L(
      "then chains get long. async/await reads like normal code: await pauses the function until the promise settles.",
      "Las cadenas de then se alargan. async/await se lee como código normal: await pausa la función hasta que la promesa se resuelve.",
      "then の連鎖は長くなる。async/await なら普通のコードみたいに読める。await は Promise が決まるまで関数を止めるよ。",
    )),
    {
      kind: "act",
      prompt: L("Write an async spell and await it", "Escribe un hechizo async y espéralo", "async の呪文を書いて await しよう"),
      setup: [],
      steps: [
        { label: L("ASYNC", "ASYNC", "async"), line: "async function getHp() {", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "getHp" }] },
        { label: L("RETURN 7", "RETURN 7", "7 を返す"), line: "  return 7;\n}", effects: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "say", actor: "ally", text: L("A Promise!", "¡Una Promise!", "Promise だよ！") }] },
        { label: L("AWAIT", "AWAIT", "await"), line: "const hp = await getHp();", effects: [{ t: "give", to: "hero" }, { t: "tag", actor: "hero", text: "hp" }, { t: "value", actor: "hero", text: "7" }, { t: "banner", text: L("UNSEALED", "ABIERTO", "開封") }] },
        { label: LOG, line: "console.log(hp + 1);", output: "8" },
      ],
    },
    say(L(
      "An async function ALWAYS returns a Promise, even for return 7. await unwraps it into the plain value.",
      "Una función async SIEMPRE devuelve una Promise, incluso con return 7. await la abre y da el valor simple.",
      "async 関数は return 7 でも「必ず」Promise を返す。await でそれを開けて中の値を取り出すよ。",
    )),
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code("async function f() {", "  return 1;", "}", "console.log(f() instanceof Promise);", "f().then((v) => console.log(v));"),
      options: ["true 1", "false 1", "1 1"],
      answer: 0,
      output: "true\n1",
      explain: L(
        "f() is a Promise wrapping 1, so instanceof says true. then later receives the 1.",
        "f() es una Promise que envuelve 1, por eso instanceof da true. Luego then recibe el 1.",
        "f() は 1 を包んだ Promise なので instanceof は true。あとで then が 1 を受け取るよ。",
      ),
      check: { compiles: true, stdout: "true\n1" },
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(
        "async function f() {",
        '  console.log("2");',
        "  await null;",
        '  console.log("4");',
        "}",
        'console.log("1");',
        "f();",
        'console.log("3");',
      ),
      options: ["1 2 3 4", "1 2 4 3", "1 3 2 4"],
      answer: 0,
      output: "1\n2\n3\n4",
      explain: L(
        "f runs synchronously until its first await. Then it steps aside, 3 prints, and f resumes with 4.",
        "f corre de forma síncrona hasta su primer await. Ahí se aparta, se imprime 3 y f continúa con 4.",
        "f は最初の await までは同期で動く。そこで一歩引いて 3 が出て、そのあと f が 4 で再開するよ。",
      ),
      check: { compiles: true, stdout: "1\n2\n3\n4" },
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "f" }],
      win: [{ t: "exit", actor: "ally" }, { t: "print", text: "3" }, { t: "enter", actor: "ally" }, { t: "print", text: "4" }],
    },
    say(L(
      "Classic bug: forgetting await. You get a Promise, not the value. TypeScript catches it for you!",
      "Bug clásico: olvidar await. Obtienes una Promise, no el valor. ¡TypeScript lo detecta por ti!",
      "定番のバグは await の付け忘れ。値じゃなく Promise が来る。TypeScript が見つけてくれるよ！",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: code("async function getHp() {", "  return 7;", "}", "const hp = getHp();", "console.log(hp + 1);"),
      options: [YES, L("No: hp is a Promise", "No: hp es una Promise", "いいえ：hp は Promise")],
      answer: 1,
      explain: L(
        "hp is Promise<number>, and you can't add 1 to a promise. Plain JS would print [object Promise]1.",
        "hp es Promise<number> y no puedes sumarle 1 a una promesa. En JS puro imprimiría [object Promise]1.",
        "hp は Promise<number> なので 1 を足せない。素の JS だと [object Promise]1 と表示されるよ。",
      ),
      check: { compiles: false },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Caught me!", "¡Me atrapaste!", "ばれた！") }],
    },
    {
      kind: "pick",
      prompt: L("Get the number, not the Promise", "Obtén el número, no la Promise", "Promise でなく数を取り出そう"),
      code: code("async function getHp() {", "  return 7;", "}", "const hp = ___ getHp();", "console.log(hp + 1);"),
      options: ["await", "async", "then"],
      answer: 0,
      explain: L(
        "await unwraps the Promise<number> into a number, so hp + 1 is 8.",
        "await abre la Promise<number> y da un number, así que hp + 1 vale 8.",
        "await で Promise<number> を number に開ける。だから hp + 1 は 8 だよ。",
      ),
      check: { compiles: true, stdout: "8", wrongFail: true },
    },
    say(L(
      "A rejected promise makes await THROW. Catch it with try/catch, like any error. In TS, the caught e is unknown.",
      "Una promesa rechazada hace que await LANCE. Atrápalo con try/catch, como cualquier error. En TS, la e atrapada es unknown.",
      "失敗した Promise を await すると throw になる。try/catch で捕まえよう。TS では e は unknown だよ。",
    )),
    {
      kind: "predict",
      prompt: WHAT_PRINTS,
      code: code(
        "try {",
        '  await Promise.reject(new Error("bad"));',
        '  console.log("ok");',
        "} catch (e) {",
        '  if (e instanceof Error) console.log("caught", e.message);',
        "}",
      ),
      options: ["ok", "caught bad", L("ok and caught bad", "ok y caught bad", "ok と caught bad")],
      answer: 1,
      output: "caught bad",
      explain: L(
        "await throws the rejection, so ok is skipped. instanceof Error narrows the unknown e before reading message.",
        "await lanza el rechazo, así que ok se salta. instanceof Error estrecha la e unknown antes de leer message.",
        "await が失敗を throw するので ok は飛ばされる。instanceof Error で unknown の e を絞ってから message を読むよ。",
      ),
      check: { compiles: true, stdout: "caught bad" },
    },
    {
      kind: "order",
      prompt: L("Load the hp and survive a failure", "Carga el hp y sobrevive a un fallo", "hp を読み、失敗にも耐えよう"),
      lines: ["try {", "const hp = await loadHp();", "console.log(hp);", "} catch (e) {", 'console.log("failed");', "}"],
      explain: L(
        "The await goes inside try, so a rejection jumps straight to catch instead of crashing.",
        "El await va dentro del try, así un rechazo salta directo al catch en vez de romper todo.",
        "await は try の中に置く。失敗したらクラッシュせずに catch へ飛ぶよ。",
      ),
      check: {
        compiles: true,
        stdout: "5",
        program: code("const loadHp = async () => 5;", "try {", "  const hp = await loadHp();", "  console.log(hp);", "} catch (e) {", '  console.log("failed");', "}"),
      },
    },
    say(L(
      "Trap: forEach does NOT wait for async callbacks. Use for...of with await, or Promise.all with map.",
      "Trampa: forEach NO espera callbacks async. Usa for...of con await, o Promise.all con map.",
      "罠：forEach は async コールバックを待たない。for...of と await か、map と Promise.all を使おう。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(WAIT_DEF, "[1, 2].forEach(async (n) => {", "  await wait(10);", "  console.log(n);", "});", 'console.log("done");'),
      options: ["1 2 done", "done 1 2", "done"],
      answer: 1,
      output: "done\n1\n2",
      explain: L(
        "forEach fires both callbacks and returns at once, ignoring their promises. done prints before they finish.",
        "forEach dispara ambos callbacks y vuelve enseguida, ignorando sus promesas. done sale antes de que terminen.",
        "forEach は2つのコールバックを呼んですぐ戻り、Promise を無視する。だから終わる前に done が出るよ。",
      ),
      check: { compiles: true, stdout: "done\n1\n2" },
    },
    {
      kind: "type",
      prompt: L("Wait for both at the same time", "Espera a ambos a la vez", "両方を同時に待とう"),
      code: code("const [a, b] = await Promise.___([", "  Promise.resolve(1),", "  Promise.resolve(2),", "]);", "console.log(a + b);"),
      answer: "all",
      explain: L(
        "Promise.all runs the waits in parallel and gives back an array of results, in order.",
        "Promise.all hace las esperas en paralelo y devuelve un array de resultados, en orden.",
        "Promise.all は並行して待ち、結果を順番どおりの配列で返すよ。",
      ),
      check: { compiles: true, stdout: "3" },
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print [2,4,6]", "Arréglalo: debe imprimir [2,4,6]", "直そう：[2,4,6] と表示させる"),
      starter: code(
        WAIT_DEF,
        "async function loadAll() {",
        "  const results: number[] = [];",
        "  [1, 2, 3].forEach(async (n) => {",
        "    await wait(5);",
        "    results.push(n * 2);",
        "  });",
        "  return results;",
        "}",
        'loadAll().then((r) => console.log("[" + r.join(",") + "]"));',
        "",
      ),
      solution: code(
        WAIT_DEF,
        "async function loadAll() {",
        "  const results: number[] = [];",
        "  for (const n of [1, 2, 3]) {",
        "    await wait(5);",
        "    results.push(n * 2);",
        "  }",
        "  return results;",
        "}",
        'loadAll().then((r) => console.log("[" + r.join(",") + "]"));',
        "",
      ),
      expect: "[2,4,6]",
      fallback: [String.raw`for\s*\(\s*(const|let)\s+\w+\s+of\b`, String.raw`Promise\.all\(`],
      explain: L(
        "forEach returns before the waits end, so results is empty. A for...of loop awaits each step.",
        "forEach vuelve antes de que terminen las esperas, así que results está vacío. Un for...of espera cada paso.",
        "forEach は待ち終わる前に戻るので results は空。for...of なら一つずつ await できるよ。",
      ),
    },
  ],
};

// ─── 5.4 microtasks vs macrotasks ───────────────────────────────────────────
const queues: LessonDef = {
  slug: "microtasks-and-macrotasks",
  title: L("The three queues", "Las tres colas", "3つの列"),
  concept: "event_loop",
  mode: "lesson",
  xp: 80,
  enemy: "typescript/callback-spaghetti",
  enemyName: L("QUEUE JUMPER", "COLADO", "割り込みスパゲッティ"),
  beats: [
    say(L(
      "Time for the full loop! Promise callbacks go to the MICROTASK queue, a VIP line. Timers wait in the macrotask line.",
      "¡Hora del bucle completo! Los callbacks de promesas van a la cola de MICROTAREAS, una fila VIP. Los timers esperan en la de macrotareas.",
      "ループの全体像だ！Promise のコールバックは VIP 列のマイクロタスクへ。タイマーはマクロタスクの列で待つよ。",
    )),
    {
      kind: "act",
      prompt: L("Fill the queues and watch the order", "Llena las colas y mira el orden", "列を埋めて、順番を見よう"),
      setup: [{ t: "tag", actor: "hero", text: "stack" }],
      steps: [
        { label: L("LOG A", "LOG A", "A を表示"), line: 'console.log("A");', output: "A" },
        {
          label: L("TIMER B", "TIMER B", "タイマー B"),
          line: 'setTimeout(() => console.log("B"), 0);',
          effects: [{ t: "item", kind: "scroll", holder: "enemy" }, { t: "tag", actor: "enemy", text: "macro" }, { t: "say", actor: "enemy", text: LATER }],
        },
        {
          label: L("PROMISE C", "PROMESA C", "Promise C"),
          line: 'Promise.resolve().then(() => console.log("C"));',
          effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "micro" }, { t: "item", kind: "gem", holder: "ally" }, { t: "say", actor: "ally", text: L("VIP line!", "¡Fila VIP!", "VIP 列！") }],
        },
        { label: L("LOG D", "LOG D", "D を表示"), line: 'console.log("D");', output: "D" },
        { label: L("MICROTASKS", "MICROTAREAS", "マイクロ"), output: "C", effects: [{ t: "banner", text: L("VIP FIRST", "VIP PRIMERO", "VIP が先") }] },
        { label: L("ONE TIMER", "UN TIMER", "タイマー1つ"), output: "B", effects: [{ t: "give", to: "hero" }] },
      ],
    },
    say(L(
      "The loop: run the stack to empty, then drain ALL microtasks, then ONE macrotask, drain microtasks again, repeat.",
      "El bucle: vacía la pila, luego TODAS las microtareas, luego UNA macrotarea, otra vez las microtareas, y repite.",
      "ループの流れ：スタックを空に→マイクロタスクを全部→マクロタスクを1つ→またマイクロタスク、のくり返しだよ。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code('console.log("A");', 'setTimeout(() => console.log("B"), 0);', 'Promise.resolve().then(() => console.log("C"));', 'console.log("D");'),
      options: ["A B C D", "A D B C", "A D C B"],
      answer: 2,
      output: "A\nD\nC\nB",
      explain: L(
        "Sync first: A, D. Then the microtask C. The timer B is a macrotask, so it goes last.",
        "Primero lo síncrono: A, D. Luego la microtarea C. El timer B es una macrotarea, así que va al final.",
        "まず同期の A と D。次にマイクロタスクの C。タイマー B はマクロタスクなので最後だよ。",
      ),
      check: { compiles: true, stdout: "A\nD\nC\nB" },
      setup: [{ t: "enter", actor: "ally" }, { t: "item", kind: "gem", holder: "ally" }, { t: "item", kind: "scroll", holder: "enemy" }],
      win: [{ t: "print", text: "A" }, { t: "print", text: "D" }, { t: "print", text: "C" }, { t: "print", text: "B" }],
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code('setTimeout(() => console.log("T"), 0);', 'queueMicrotask(() => console.log("M"));', 'console.log("S");'),
      options: ["S M T", "S T M", "T M S"],
      answer: 0,
      output: "S\nM\nT",
      explain: L(
        "queueMicrotask puts a callback straight into the VIP line. Order: sync S, microtask M, timer T.",
        "queueMicrotask mete un callback directo en la fila VIP. Orden: síncrono S, microtarea M, timer T.",
        "queueMicrotask はコールバックを直接 VIP 列へ入れる。順番は同期 S、マイクロ M、タイマー T。",
      ),
      check: { compiles: true, stdout: "S\nM\nT" },
    },
    say(L(
      "After EACH timer, the loop drains the microtasks again. A promise made inside a timer jumps ahead of the next timer.",
      "Tras CADA timer, el bucle vacía otra vez las microtareas. Una promesa creada dentro de un timer se adelanta al siguiente timer.",
      "タイマーを1つ動かすたびに、マイクロタスクをまた全部片づける。タイマー内の Promise は次のタイマーより先だよ。",
    )),
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(
        "setTimeout(() => {",
        '  console.log("t1");',
        '  Promise.resolve().then(() => console.log("p1"));',
        "}, 0);",
        'setTimeout(() => console.log("t2"), 0);',
      ),
      options: ["t1 t2 p1", "t1 p1 t2", "p1 t1 t2"],
      answer: 1,
      output: "t1\np1\nt2",
      explain: L(
        "t1 runs and queues p1. Before t2, the loop drains microtasks, so p1 comes in between.",
        "t1 corre y encola p1. Antes de t2, el bucle vacía las microtareas, así que p1 se mete en medio.",
        "t1 が動いて p1 を予約。t2 の前にマイクロタスクを片づけるので、p1 が間に入るよ。",
      ),
      check: { compiles: true, stdout: "t1\np1\nt2" },
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(
        "Promise.resolve()",
        "  .then(() => console.log(1))",
        "  .then(() => console.log(2));",
        "Promise.resolve()",
        "  .then(() => console.log(3))",
        "  .then(() => console.log(4));",
      ),
      options: ["1 2 3 4", "1 3 2 4", "3 4 1 2"],
      answer: 1,
      output: "1\n3\n2\n4",
      explain: L(
        "Each then waits for the previous one, which queues it as a NEW microtask. The two chains take turns.",
        "Cada then espera al anterior, que lo encola como una microtarea NUEVA. Las dos cadenas se turnan.",
        "then は前の then が終わると新しいマイクロタスクとして並ぶ。だから2つのチェーンが交互に進むよ。",
      ),
      check: { compiles: true, stdout: "1\n3\n2\n4" },
    },
    {
      kind: "predict",
      prompt: IN_ORDER,
      code: code(
        'async function a() {',
        '  console.log("a1");',
        "  await b();",
        '  console.log("a2");',
        "}",
        'async function b() { console.log("b"); }',
        'console.log("s");',
        "a();",
        'Promise.resolve().then(() => console.log("p"));',
        'console.log("e");',
      ),
      options: ["s a1 b e a2 p", "s a1 b a2 e p", "s e a1 b p a2"],
      answer: 0,
      output: "s\na1\nb\ne\na2\np",
      explain: L(
        "a and b run synchronously up to the await. The rest of a is a microtask queued before p, so a2 comes first.",
        "a y b corren de forma síncrona hasta el await. El resto de a es una microtarea encolada antes que p: a2 va primero.",
        "a と b は await まで同期で動く。a の続きは p より先に並ぶマイクロタスクなので a2 が先だよ。",
      ),
      check: { compiles: true, stdout: "s\na1\nb\ne\na2\np" },
    },
    {
      kind: "predict",
      prompt: L("What happens?", "¿Qué pasa?", "どうなる？"),
      code: code("function loop() {", "  Promise.resolve().then(loop);", "}", "loop();", 'setTimeout(() => console.log("never"), 0);'),
      options: [
        L("never prints", "Se imprime never", "never が表示される"),
        L("The timer never runs", "El timer nunca corre", "タイマーは永遠に動かない"),
      ],
      answer: 1,
      explain: L(
        "Each microtask queues another one, so the VIP line never empties and the timer starves. Don't run this one!",
        "Cada microtarea encola otra, así que la fila VIP nunca se vacía y el timer se queda sin turno. ¡No lo ejecutes!",
        "マイクロタスクが次々に増えて VIP 列が空にならず、タイマーは永遠に待つ。これは実行しないでね！",
      ),
      check: { compiles: true },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Starving...", "Me muero de hambre", "腹ぺこ…") }],
    },
    {
      kind: "run",
      prompt: L("Make it print A, B, C without moving lines", "Haz que imprima A, B, C sin mover líneas", "行を動かさず A, B, C の順にしよう"),
      starter: code('setTimeout(() => console.log("B"), 0);', 'Promise.resolve().then(() => console.log("C"));', 'console.log("A");', ""),
      solution: code('setTimeout(() => console.log("C"), 0);', 'Promise.resolve().then(() => console.log("B"));', 'console.log("A");', ""),
      expect: "A\nB\nC",
      fallback: [
        String.raw`^(?=[\s\S]*setTimeout\(\s*\(\)\s*=>\s*console\.log\(\s*["']C["'])(?=[\s\S]*(then|queueMicrotask)\(\s*\(\)\s*=>\s*console\.log\(\s*["']B["'])`,
      ],
      explain: L(
        "The microtask beats the timer. Print B in the promise callback and C in the timer.",
        "La microtarea le gana al timer. Imprime B en el callback de la promesa y C en el timer.",
        "マイクロタスクはタイマーより先。Promise のコールバックで B、タイマーで C を出そう。",
      ),
    },
  ],
};

// ─── boss ───────────────────────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "event-loop-kraken",
  title: L("BOSS: Event Loop Kraken", "JEFE: Kraken del Bucle", "ボス：ループクラーケン"),
  concept: "event_loop",
  mode: "boss",
  xp: 180,
  enemy: "typescript/callback-spaghetti",
  enemyName: L("EVENT LOOP KRAKEN", "KRAKEN DEL BUCLE", "ループクラーケン"),
  beats: [
    enemySays(L(
      "I AM THE KRAKEN OF THE LOOP. My tentacles juggle stacks, microtasks and timers. Guess my order... if you can!",
      "SOY EL KRAKEN DEL BUCLE. Mis tentáculos manejan pilas, microtareas y timers. Adivina mi orden... ¡si puedes!",
      "我こそループのクラーケン。触手でスタック、マイクロタスク、タイマーを操る。順番を当ててみよ！",
    )),
    {
      kind: "predict", time: 12, prompt: IN_ORDER,
      code: code('setTimeout(() => console.log("T"), 0);', 'console.log("S");'),
      options: ["T S", "S T"], answer: 1,
      explain: L("Timers wait for the empty stack.", "Los timers esperan la pila vacía.", "タイマーはスタックが空になるまで待つ。"),
      check: { compiles: true, stdout: "S\nT" },
    },
    {
      kind: "predict", time: 12, prompt: IN_ORDER,
      code: code('new Promise<void>((r) => {', '  console.log("in");', "  r();", "});", 'console.log("out");'),
      options: ["in out", "out in"], answer: 0,
      explain: L("The executor runs synchronously.", "El ejecutor corre de forma síncrona.", "executor は同期で動く。"),
      check: { compiles: true, stdout: "in\nout" },
    },
    {
      kind: "predict", time: 12, prompt: WHAT_PRINTS,
      code: "Promise.resolve(2).then((x) => x * 3).then(console.log);",
      options: ["2", "6", "undefined"], answer: 1,
      explain: L("then passes its return value along: 2 * 3.", "then pasa su valor de retorno: 2 * 3.", "then は戻り値を次へ渡す：2 * 3。"),
      check: { compiles: true, stdout: "6" },
    },
    {
      kind: "type", time: 12, prompt: L("Handle the rejection", "Maneja el rechazo", "失敗を受け止めよう"),
      code: code('Promise.reject(new Error("x"))', '  .___(() => console.log("saved"));'),
      answer: "catch",
      explain: L("catch handles rejections.", "catch maneja los rechazos.", "catch が失敗を受け取る。"),
      check: { compiles: true, stdout: "saved" },
    },
    {
      kind: "pick", time: 12, prompt: L("Wait for every result", "Espera todos los resultados", "全部の結果を待とう"),
      code: code("Promise.___([Promise.resolve(1), Promise.resolve(2)])", '  .then((v) => console.log(v.join("+")));'),
      options: ["all", "race", "any"], answer: 0,
      explain: L("all gives an array; race and any give one value.", "all da un array; race y any dan un solo valor.", "all は配列、race と any は値1つ。"),
      check: { compiles: true, stdout: "1+2", wrongFail: true },
    },
    {
      kind: "predict", time: 12, prompt: COMPILES,
      code: code("async function f() {", "  return 1;", "}", "const n: number = f();"),
      options: [YES, L("No: it's a Promise", "No: es una Promise", "いいえ：Promise だ")], answer: 1,
      explain: L("f() returns Promise<number>: await it.", "f() devuelve Promise<number>: usa await.", "f() は Promise<number>。await しよう。"),
      check: { compiles: false },
    },
    {
      kind: "predict", time: 12, prompt: IN_ORDER,
      code: code("async function f() {", '  console.log("b");', "  await null;", '  console.log("d");', "}", 'console.log("a");', "f();", 'console.log("c");'),
      options: ["a b c d", "a b d c", "a c b d"], answer: 0,
      explain: L("await pauses only f, not the program.", "await pausa solo a f, no al programa.", "await が止めるのは f だけ。"),
      check: { compiles: true, stdout: "a\nb\nc\nd" },
    },
    {
      kind: "predict", time: 12, prompt: IN_ORDER,
      code: code("setTimeout(() => console.log(1), 0);", "Promise.resolve().then(() => console.log(2));", "console.log(3);"),
      options: ["1 2 3", "3 1 2", "3 2 1"], answer: 2,
      explain: L("Sync, then microtask, then timer.", "Síncrono, microtarea y luego timer.", "同期→マイクロ→タイマーの順。"),
      check: { compiles: true, stdout: "3\n2\n1" },
    },
    {
      kind: "predict", time: 15, prompt: IN_ORDER,
      code: code(
        'Promise.resolve().then(() => console.log("a"))',
        '  .then(() => console.log("b"));',
        'Promise.resolve().then(() => console.log("c"));',
      ),
      options: ["a b c", "a c b", "c a b"], answer: 1,
      explain: L("b is queued only after a runs.", "b se encola solo después de que corre a.", "b は a が終わってから並ぶ。"),
      check: { compiles: true, stdout: "a\nc\nb" },
    },
    {
      kind: "predict", time: 15, prompt: IN_ORDER,
      code: code(
        "console.log(1);",
        "setTimeout(() => console.log(2));",
        "Promise.resolve().then(() => console.log(3));",
        "(async () => {",
        "  console.log(4);",
        "  await null;",
        "  console.log(5);",
        "})();",
        "console.log(6);",
      ),
      options: ["1 4 6 3 5 2", "1 6 4 3 5 2", "1 4 6 5 3 2"], answer: 0,
      explain: L(
        "Sync 1 4 6, microtasks 3 then 5 in queue order, timer 2 last.",
        "Síncrono 1 4 6, microtareas 3 y 5 en orden de cola, el timer 2 al final.",
        "同期 1 4 6、マイクロは並んだ順に 3 と 5、最後にタイマー 2。",
      ),
      check: { compiles: true, stdout: "1\n4\n6\n3\n5\n2" },
    },
    enemySays(L(
      "Impossible... you read my queues like an open scroll. The tower is yours, master of the loop.",
      "Imposible... lees mis colas como un pergamino abierto. La torre es tuya, maestro del bucle.",
      "ばかな…我が列を開いた巻物のように読むとは。塔はお前のものだ、ループの達人よ。",
    )),
  ],
};

export const eventLoopTower: RegionDef = {
  slug: "event-loop-tower",
  name: L("Event Loop Tower", "Torre del Event Loop", "イベントループの塔"),
  subtitle: L("Timers, promises, async/await", "Timers, promesas y async/await", "タイマー・Promise・async/await"),
  theme: "tower",
  status: "active",
  lessons: [timers, promises, asyncAwait, queues, boss],
};
