import type { LessonDef, RegionDef, SnippetCheck } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";
import { enemySays, say } from "../../rust/helpers.ts";

// REGION 4 · TYPE CASTLE  (shapes and inference, unions and narrowing, generics, utility/mapped/conditional types)

const c = (...lines: string[]) => lines.join("\n");
const TC = L("Does it type-check?", "¿Pasa el chequeo de tipos?", "型チェックを通る？");
const OUT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const YES = L("Yes", "Sí", "はい");
const NO = L("No", "No", "いいえ");

// Proves a type claim with the real checker: the program only type-checks if A and B are the same type.
const EQUAL = "type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;";
const typeIs = (code: string, actual: string, expected: string): SnippetCheck => ({
  program: `${code}\n${EQUAL}\nconst proof: Equal<${actual}, ${expected}> = true;`,
  compiles: true,
});

const shapesLesson: LessonDef = {
  slug: "shapes-and-inference",
  title: L("The shape guard", "El guardián de formas", "かたちの門番"),
  concept: "ts_basics",
  mode: "lesson",
  xp: 70,
  enemy: "typescript/undefined-ghost",
  enemyName: L("LOOSE GHOST", "FANTASMA SUELTO", "ゆるゆるゴースト"),
  beats: [
    say(L(
      "Welcome to the Type Castle! TypeScript adds TYPES: labels that say what shape a value must have.",
      "¡Bienvenido al Castillo de Tipos! TypeScript agrega TIPOS: etiquetas que dicen qué forma debe tener un valor.",
      "型の城へようこそ！TypeScript は型を加える。値がどんな形であるべきかを示すラベルだよ。",
    )),
    say(L(
      "The checker reads your code BEFORE it runs. A value of the wrong shape? The gate closes with an error.",
      "El verificador lee tu código ANTES de ejecutarlo. ¿Un valor con la forma equivocada? La puerta se cierra con un error.",
      "型チェッカーは実行する前にコードを読む。形の違う値が来たら、門はエラーで閉じるよ。",
    )),
    {
      kind: "act",
      prompt: L("Label hp, then try to sneak in a string", "Etiqueta hp e intenta colar un string", "hp に型をつけて、文字列を入れてみよう"),
      steps: [
        { label: L("LABEL", "ETIQUETAR", "型をつける"), line: "let hp: number = 10;", effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "hp: number" }, { t: "value", actor: "hero", text: "10" }] },
        { label: L("SET 12", "PONER 12", "12 を入れる"), line: "hp = 12;", effects: [{ t: "value", actor: "hero", text: "12" }] },
        {
          label: L("SET \"ten\"", "PONER \"ten\"", "\"ten\" を入れる"),
          line: 'hp = "ten";',
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Blocked!", "¡Bloqueado!", "通さない！") }],
          error: {
            compiler: "error TS2322: Type 'string' is not assignable to type 'number'.",
            plain: L("hp only accepts numbers. The checker stops it before the code runs.", "hp solo acepta números. El verificador lo frena antes de ejecutar.", "hp は数値だけ。実行前にチェッカーが止めるよ。"),
          },
        },
        { label: L("INFER", "INFERIR", "推論"), line: "let mp = 5; // TS infers number", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "mp: number" }, { t: "banner", text: L("INFERRED!", "¡INFERIDO!", "型推論！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("let hp = 10;", 'hp = "ten";'),
      options: [YES, L("No: hp is a number", "No: hp es number", "いいえ：hp は number")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "No label written, but TS INFERRED number from 10. A string doesn't fit (TS2322).",
        "No hay etiqueta, pero TS INFIRIÓ number a partir de 10. Un string no cabe (TS2322).",
        "型を書かなくても、10 から number と推論される。文字列は入らない（TS2322）。",
      ),
      win: [{ t: "shake" }],
    },
    say(L(
      "interface describes an object's shape. ? marks a key as optional; readonly forbids changing it.",
      "interface describe la forma de un objeto. ? marca una clave como opcional; readonly prohíbe cambiarla.",
      "interface はオブジェクトの形を表す。? は省略可能、readonly は変更禁止の印だよ。",
    )),
    {
      kind: "type",
      prompt: L("Make title optional", "Haz title opcional", "title を省略可能にしよう"),
      code: c("interface Hero { name: string; title___: string }", 'const h: Hero = { name: "Ada" };', "console.log(h.title);"),
      answer: "?",
      check: { compiles: true, stdout: "undefined" },
      explain: L(
        "title?: string means the key may be missing; reading it then gives undefined.",
        "title?: string significa que la clave puede faltar; leerla da undefined.",
        "title?: string はキーがなくてもいいという意味。読むと undefined になるよ。",
      ),
      win: [{ t: "print", text: "undefined" }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("type User = { readonly id: number };", "const u: User = { id: 1 };", "u.id = 2;"),
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "id is readonly, so assigning it is error TS2540.",
        "id es readonly, así que asignarlo es el error TS2540.",
        "id は readonly なので代入はエラー TS2540 だよ。",
      ),
    },
    say(L(
      "Types are STRUCTURAL: a value fits if it has the needed keys. Extra keys are fine... unless you write a fresh literal.",
      "Los tipos son ESTRUCTURALES: un valor encaja si tiene las claves necesarias. Sobrar claves está bien... salvo en un literal nuevo.",
      "型は構造で判断される。必要なキーがあれば合格。余分なキーもOK…ただし直接書いたリテラルは別だよ。",
    )),
    {
      kind: "predict",
      prompt: TC,
      code: c(
        "interface Point { x: number; y: number }",
        "function len(p: Point) { return Math.hypot(p.x, p.y); }",
        "const v = { x: 3, y: 4, z: 9 };",
        "console.log(len(v));",
      ),
      options: [L("Yes: prints 5", "Sí: imprime 5", "はい：5 と表示"), L("No: z is extra", "No: sobra z", "いいえ：z が余分")],
      answer: 0,
      output: "5",
      check: { compiles: true, stdout: "5" },
      explain: L(
        "v has x and y, so it fits Point. An extra z in a variable is allowed.",
        "v tiene x e y, así que encaja en Point. Una z de más en una variable está permitida.",
        "v は x と y を持つので Point に合う。変数に入った余分な z は許されるよ。",
      ),
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "v" }],
      win: [{ t: "give", to: "ally" }, { t: "print", text: "5" }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c(
        "interface Point { x: number; y: number }",
        "function len(p: Point) { return Math.hypot(p.x, p.y); }",
        "console.log(len({ x: 3, y: 4, z: 9 }));",
      ),
      options: [YES, L("No: excess property z", "No: propiedad z de más", "いいえ：余分なプロパティ z")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "A FRESH literal gets an excess property check: z is probably a typo (TS2353).",
        "Un literal NUEVO pasa por el chequeo de propiedades de más: z probablemente es un error (TS2353).",
        "直接書いたリテラルは余分なプロパティをチェックされる。z はたぶん打ち間違い（TS2353）。",
      ),
      setup: [{ t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "shake" }, { t: "say", actor: "ally", text: L("What's z?", "¿Qué es z?", "z って何？") }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("let y = 5;", "const w: 5 = y;"),
      options: [YES, L("No: y is number", "No: y es number", "いいえ：y は number")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "let y can change, so TS widens it to number. Only const x = 5 keeps the literal type 5.",
        "let y puede cambiar, así que TS lo amplía a number. Solo const x = 5 conserva el tipo literal 5.",
        "let y は変わりうるので number に広がる。const x = 5 ならリテラル型 5 のままだよ。",
      ),
    },
    say(L(
      "satisfies checks a value against a type but KEEPS its precise inferred type. A : label would replace it.",
      "satisfies comprueba un valor contra un tipo pero CONSERVA su tipo inferido preciso. Una etiqueta : lo reemplazaría.",
      "satisfies は値を型と照合しつつ、推論された細かい型をそのまま残す。: で注釈すると置き換わるよ。",
    )),
    {
      kind: "pick",
      prompt: L("Check it but keep red a string", "Verifícalo pero que red siga siendo string", "チェックしつつ red は string のまま"),
      code: c(
        'const colors = { red: "#f00", blue: [0, 0, 255] } ___ Record<string, string | number[]>;',
        "console.log(colors.red.toUpperCase());",
      ),
      options: ["satisfies", "as", "extends"],
      answer: 0,
      check: { compiles: true, stdout: "#F00", wrongFail: true },
      explain: L(
        "With as, red becomes string | number[] and toUpperCase fails. satisfies keeps red: string.",
        "Con as, red pasa a string | number[] y toUpperCase falla. satisfies mantiene red: string.",
        "as だと red は string | number[] になり toUpperCase できない。satisfies なら red は string のまま。",
      ),
      win: [{ t: "print", text: "#F00" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: a missing qty counts as 1, print 13", "Arréglalo: sin qty cuenta 1, imprime 13", "直そう：qty なしは 1 として 13 を表示"),
      starter: c(
        "interface Item { name: string; price: number; qty?: number }",
        "function total(items: Item[]): number {",
        "  return items.reduce((sum, i) => sum + i.price * i.qty, 0);",
        "}",
        'console.log("total:", total([{ name: "gem", price: 5, qty: 2 }, { name: "key", price: 3 }]));',
        "",
      ),
      solution: c(
        "interface Item { name: string; price: number; qty?: number }",
        "function total(items: Item[]): number {",
        "  return items.reduce((sum, i) => sum + i.price * (i.qty ?? 1), 0);",
        "}",
        'console.log("total:", total([{ name: "gem", price: 5, qty: 2 }, { name: "key", price: 3 }]));',
        "",
      ),
      expect: "total: 13",
      fallback: [
        String.raw`i\s*\.\s*qty\s*\?\?\s*1`,
        String.raw`i\s*\.\s*qty\s*\|\|\s*1`,
        String.raw`i\s*\.\s*qty\s*[!=]==?\s*undefined`,
        String.raw`price\s*:\s*3\s*,\s*qty\s*:\s*1`,
      ],
      explain: L(
        "qty is optional, so it can be undefined and 3 * undefined is NaN. tsc warns too: TS18048. Use i.qty ?? 1.",
        "qty es opcional: puede ser undefined y 3 * undefined da NaN. tsc también avisa: TS18048. Usa i.qty ?? 1.",
        "qty は省略可能で undefined になりうる。3 * undefined は NaN。tsc も TS18048 で警告。i.qty ?? 1 を使おう。",
      ),
    },
  ],
};

const unionsLesson: LessonDef = {
  slug: "unions-and-narrowing",
  title: L("Two-faced values", "Valores de dos caras", "ふたつの顔を持つ値"),
  concept: "narrowing",
  mode: "lesson",
  xp: 75,
  enemy: "typescript/any-shifter",
  enemyName: L("MASK SHIFTER", "CAMBIAFORMAS", "仮面シフター"),
  beats: [
    say(L(
      "A union type string | number means one OR the other. Until you check which, you may only use what BOTH have.",
      "Un tipo unión string | number significa uno U otro. Hasta comprobar cuál, solo puedes usar lo que tienen AMBOS.",
      "ユニオン型 string | number は「どちらか」。どっちか確かめるまで、両方に共通するものしか使えないよ。",
    )),
    {
      kind: "act",
      prompt: L("Unmask the value with typeof", "Desenmascara el valor con typeof", "typeof で仮面をはがそう"),
      steps: [
        { label: L("MASKED", "CON MÁSCARA", "仮面つき"), line: "function show(x: string | number) {", effects: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "x: string | number" }] },
        { label: L("CHECK number", "¿ES number?", "number か確認"), line: '  if (typeof x === "number") return x.toFixed(1);', effects: [{ t: "value", actor: "enemy", text: "number" }, { t: "say", actor: "hero", text: L("A number!", "¡Un número!", "数値だ！") }] },
        { label: L("ELSE string", "SI NO, string", "残りは string"), line: "  return x.toUpperCase();", effects: [{ t: "value", actor: "enemy", text: "string" }] },
        { label: L("CLOSE", "CERRAR", "とじる"), line: "}" },
        { label: L("CALL", "LLAMAR", "呼ぶ"), line: 'console.log(show(2), show("a"));', output: "2.0 A", effects: [{ t: "print", text: "2.0 A" }, { t: "banner", text: L("NARROWED!", "¡ESTRECHADO!", "絞り込み！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: TC,
      code: "function len(x: string | number) { return x.length; }",
      options: [YES, L("No: number has no length", "No: number no tiene length", "いいえ：number に length はない")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "x might be a number, and numbers have no .length (TS2339). Narrow first.",
        "x podría ser un number, y los números no tienen .length (TS2339). Primero estrecha el tipo.",
        "x は number かもしれず、number に .length はない（TS2339）。先に型の絞り込みをしよう。",
      ),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "string | number" }],
      win: [{ t: "shake" }],
    },
    {
      kind: "pick",
      prompt: L("Narrow x to a string", "Estrecha x a string", "x を string に絞り込もう"),
      code: c(
        "function size(x: string | number) {",
        "  if (typeof x === ___) return x.length;",
        "  return x;",
        "}",
        'console.log(size("abc"), size(7));',
      ),
      options: ['"string"', '"number"', '"text"'],
      answer: 0,
      check: { compiles: true, stdout: "3 7", wrongFail: true },
      explain: L(
        "Inside if (typeof x === \"string\") TS knows x is a string, so .length is allowed.",
        "Dentro de if (typeof x === \"string\") TS sabe que x es string, así que .length está permitido.",
        "if (typeof x === \"string\") の中では x は string と分かるので .length が使えるよ。",
      ),
      win: [{ t: "print", text: "3 7" }],
    },
    say(L(
      "A union of literals like \"up\" | \"down\" works as a tiny menu: any other string is rejected.",
      "Una unión de literales como \"up\" | \"down\" funciona como un menú: cualquier otro string se rechaza.",
      "\"up\" | \"down\" のようなリテラルのユニオン型は小さなメニュー。ほかの文字列は通らないよ。",
    )),
    {
      kind: "predict",
      prompt: TC,
      code: c('type Dir = "up" | "down";', 'const d: Dir = "left";'),
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "\"left\" is not on the menu: only \"up\" or \"down\" fit Dir.",
        "\"left\" no está en el menú: solo \"up\" o \"down\" encajan en Dir.",
        "\"left\" はメニューにない。Dir に入るのは \"up\" か \"down\" だけだよ。",
      ),
    },
    {
      kind: "pick",
      prompt: L("Check if p can swim", "Comprueba si p puede nadar", "p が泳げるか確かめよう"),
      code: c(
        "type Fish = { swim: () => string };",
        "type Bird = { fly: () => string };",
        "function move(p: Fish | Bird) {",
        '  return "swim" ___ p ? p.swim() : p.fly();',
        "}",
        'console.log(move({ fly: () => "flap" }));',
      ),
      options: ["in", "of", "instanceof"],
      answer: 0,
      check: { compiles: true, stdout: "flap", wrongFail: true },
      explain: L(
        "\"swim\" in p checks for the key, and TS narrows p to Fish in that branch.",
        "\"swim\" in p comprueba si existe la clave, y TS estrecha p a Fish en esa rama.",
        "\"swim\" in p でキーの有無を調べると、その分岐で p は Fish に絞り込まれるよ。",
      ),
      win: [{ t: "print", text: "flap" }],
    },
    say(L(
      "Give each shape a kind tag and switch on it. Add `never` in default: a forgotten case becomes a type error.",
      "Dale a cada forma una etiqueta kind y usa switch. Pon `never` en default: un caso olvidado se vuelve error de tipos.",
      "各形に kind タグをつけて switch しよう。default に never を置けば、書き忘れた case が型エラーになる。",
    )),
    {
      kind: "predict",
      prompt: TC,
      code: c(
        'type Shape = { kind: "circle"; r: number }',
        '  | { kind: "square"; side: number }',
        '  | { kind: "tri"; base: number; h: number };',
        "function area(s: Shape): number {",
        "  switch (s.kind) {",
        '    case "circle": return 3 * s.r * s.r;',
        '    case "square": return s.side * s.side;',
        "    default: { const unreachable: never = s; return unreachable; }",
        "  }",
        "}",
      ),
      options: [YES, L("No: \"tri\" is not handled", "No: falta \"tri\"", "いいえ：\"tri\" が未処理")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "The tri shape reaches default, and it can't be assigned to never. The checker found the missing case.",
        "La forma tri llega a default y no se puede asignar a never. El verificador encontró el caso faltante.",
        "tri が default に届き、never には代入できない。チェッカーが書き忘れの case を見つけたんだ。",
      ),
      win: [{ t: "shake" }, { t: "banner", text: L("CASE MISSING!", "¡FALTA UN CASO!", "case 不足！") }],
    },
    say(L(
      "unknown means 'could be anything, check first'. any switches the checker OFF. Prefer unknown.",
      "unknown significa 'puede ser cualquier cosa, compruébalo'. any APAGA el verificador. Prefiere unknown.",
      "unknown は「何でもありうる、まず確かめて」。any はチェックを切ってしまう。unknown を使おう。",
    )),
    {
      kind: "predict",
      prompt: TC,
      code: "function f(x: unknown) { return x.length; }",
      options: [YES, L("No: narrow x first", "No: primero estrecha x", "いいえ：先に x を絞り込む")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "With unknown you must narrow before use (TS18046). With any it compiles, and bugs slip through.",
        "Con unknown debes estrechar antes de usar (TS18046). Con any compila, y los bugs se cuelan.",
        "unknown は使う前に絞り込みが必要（TS18046）。any だと通ってしまい、バグがすり抜ける。",
      ),
    },
    {
      kind: "type",
      prompt: L("Write a custom type guard", "Escribe un type guard propio", "自作の型ガードを書こう"),
      code: c(
        "function isString(x: unknown): x ___ string {",
        '  return typeof x === "string";',
        "}",
        'const v: unknown = "hi";',
        "if (isString(v)) console.log(v.toUpperCase());",
      ),
      answer: "is",
      check: { compiles: true, stdout: "HI" },
      explain: L(
        "x is string tells TS: when this returns true, treat x as a string.",
        "x is string le dice a TS: cuando esto devuelve true, trata x como string.",
        "x is string は「true を返したら x は string」と TS に伝えるよ。",
      ),
      win: [{ t: "print", text: "HI" }],
    },
    {
      kind: "run",
      prompt: L("Fix it: label(0) must print x0", "Arréglalo: label(0) debe dar x0", "直そう：label(0) は x0 にして"),
      starter: c(
        "function label(count?: number): string {",
        '  return count ? `x${count}` : "none";',
        "}",
        "console.log(label(3), label(0), label());",
        "",
      ),
      solution: c(
        "function label(count?: number): string {",
        '  return count !== undefined ? `x${count}` : "none";',
        "}",
        "console.log(label(3), label(0), label());",
        "",
      ),
      expect: "x3 x0 none",
      fallback: [
        String.raw`count\s*!==?\s*undefined`,
        String.raw`count\s*===?\s*undefined`,
        String.raw`count\s*!=\s*null`,
        String.raw`typeof\s+count\s*===?\s*["']number["']`,
      ],
      explain: L(
        "Truthiness narrowing drops 0 too, since 0 is falsy. Check count !== undefined instead.",
        "Estrechar por verdad también descarta 0, porque 0 es falsy. Comprueba count !== undefined.",
        "真偽値での絞り込みは 0 も落とす（0 は falsy）。count !== undefined で確かめよう。",
      ),
    },
  ],
};

const genericsLesson: LessonDef = {
  slug: "generic-chest",
  title: L("The shape-shifting chest", "El cofre cambiante", "形を変える宝箱"),
  concept: "generics",
  mode: "lesson",
  xp: 75,
  enemy: "slime",
  enemyName: L("SHAPE SLIME", "SLIME AMORFO", "かたちスライム"),
  beats: [
    say(L(
      "A generic <T> is a type PARAMETER: a blank the caller fills in. One chest that takes the shape of what goes in.",
      "Un genérico <T> es un PARÁMETRO de tipo: un hueco que llena quien llama. Un cofre que toma la forma de lo que entra.",
      "ジェネリクスの <T> は型のパラメータ。呼ぶ側が埋める空欄だよ。中身の形になる宝箱だね。",
    )),
    {
      kind: "act",
      prompt: L("Fill the chest with different shapes", "Llena el cofre con distintas formas", "いろんな形を宝箱に入れよう"),
      steps: [
        { label: L("CHEST <T>", "COFRE <T>", "宝箱 <T>"), line: "function first<T>(xs: T[]): T | undefined {", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "first<T>" }] },
        { label: L("BODY", "CUERPO", "中身"), line: "  return xs[0];" },
        { label: L("CLOSE", "CERRAR", "とじる"), line: "}" },
        { label: L("NUMBERS", "NÚMEROS", "数値"), line: "const n = first([1, 2]); // T = number", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "n" }, { t: "value", actor: "ally", text: "number | undefined" }] },
        { label: L("STRINGS", "STRINGS", "文字列"), line: 'const s = first(["gem"]); // T = string', effects: [{ t: "value", actor: "ally", text: "string | undefined" }, { t: "banner", text: L("T INFERRED!", "¡T INFERIDO!", "T を推論！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示する"), line: "console.log(n, s);", output: "1 gem", effects: [{ t: "print", text: "1 gem" }] },
      ],
    },
    {
      kind: "predict",
      prompt: L("What is the type of n?", "¿Cuál es el tipo de n?", "n の型は？"),
      code: c("function first<T>(xs: T[]): T | undefined {", "  return xs[0];", "}", "const n = first([1, 2]);"),
      options: ["number | undefined", "number", "T", "any"],
      answer: 0,
      check: typeIs(c("function first<T>(xs: T[]): T | undefined {", "  return xs[0];", "}", "const n = first([1, 2]);"), "typeof n", "number | undefined"),
      explain: L(
        "TS infers T = number from [1, 2], so the return type T | undefined becomes number | undefined.",
        "TS infiere T = number desde [1, 2], así que el retorno T | undefined queda number | undefined.",
        "[1, 2] から T = number と推論され、戻り値 T | undefined は number | undefined になるよ。",
      ),
    },
    {
      kind: "predict",
      prompt: TC,
      code: "function len<T>(x: T) { return x.length; }",
      options: [YES, L("No: T may have no length", "No: T puede no tener length", "いいえ：T に length がないかも")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "T could be anything, even a number. TS can't promise .length exists (TS2339).",
        "T podría ser cualquier cosa, hasta un número. TS no puede asegurar que exista .length (TS2339).",
        "T は数値かもしれない何でもあり。.length があるとは言えない（TS2339）。",
      ),
    },
    say(L(
      "A CONSTRAINT T extends ... puts a keyhole on the chest: only types with that shape fit.",
      "Una RESTRICCIÓN T extends ... pone una cerradura al cofre: solo entran tipos con esa forma.",
      "制約 T extends ... は宝箱の鍵穴。その形を持つ型だけが入れるよ。",
    )),
    {
      kind: "pick",
      prompt: L("Require a length", "Exige un length", "length を要求しよう"),
      code: c("function len<T extends ___>(x: T) { return x.length; }", 'console.log(len("abc"), len([1, 2]));'),
      options: ["{ length: number }", "number", "string[]"],
      answer: 0,
      check: { compiles: true, stdout: "3 2", wrongFail: true },
      explain: L(
        "{ length: number } accepts strings AND arrays. string[] would reject \"abc\"; number has no length.",
        "{ length: number } acepta strings Y arrays. string[] rechazaría \"abc\"; number no tiene length.",
        "{ length: number } なら文字列も配列もOK。string[] は \"abc\" を拒み、number に length はない。",
      ),
      win: [{ t: "print", text: "3 2" }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("function len<T extends { length: number }>(x: T) { return x.length; }", "len(5);"),
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "5 has no length, so it doesn't fit the keyhole (TS2345).",
        "5 no tiene length, así que no entra por la cerradura (TS2345).",
        "5 には length がないので鍵穴に合わない（TS2345）。",
      ),
      win: [{ t: "shake" }],
    },
    say(L(
      "keyof T is the union of T's keys. T[K] is the type stored under key K. Together they make safe getters.",
      "keyof T es la unión de las claves de T. T[K] es el tipo guardado en la clave K. Juntos hacen getters seguros.",
      "keyof T は T のキーのユニオン型。T[K] はキー K の値の型。組み合わせると安全なゲッターになるよ。",
    )),
    {
      kind: "pick",
      prompt: L("Only real keys allowed", "Solo claves reales", "本当にあるキーだけ"),
      code: c(
        "function getProp<T, K extends ___>(obj: T, key: K): T[K] {",
        "  return obj[key];",
        "}",
        'console.log(getProp({ hp: 7 }, "hp"));',
      ),
      options: ["keyof T", "string", "T"],
      answer: 0,
      check: { compiles: true, stdout: "7", wrongFail: true },
      explain: L(
        "K extends keyof T means key must be one of obj's keys, so obj[key] is safe and typed T[K].",
        "K extends keyof T obliga a que key sea una clave de obj: obj[key] es seguro y tiene tipo T[K].",
        "K extends keyof T なら key は obj のキーのどれか。obj[key] は安全で型は T[K] だよ。",
      ),
      win: [{ t: "print", text: "7" }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c(
        "function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {",
        "  return obj[key];",
        "}",
        'getProp({ hp: 1 }, "mp");',
      ),
      options: [YES, L("No: \"mp\" is not a key", "No: \"mp\" no es clave", "いいえ：\"mp\" はキーじゃない")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "keyof { hp: number } is just \"hp\". The typo \"mp\" is caught before running.",
        "keyof { hp: number } es solo \"hp\". El error \"mp\" se detecta antes de ejecutar.",
        "keyof { hp: number } は \"hp\" だけ。打ち間違いの \"mp\" は実行前に見つかるよ。",
      ),
    },
    {
      kind: "predict",
      prompt: L("What type is HP?", "¿Qué tipo es HP?", "HP の型は？"),
      code: c("type Hero = { name: string; hp: number };", 'type HP = Hero["hp"];'),
      options: ["number", '"hp"', "string"],
      answer: 0,
      check: typeIs(c("type Hero = { name: string; hp: number };", 'type HP = Hero["hp"];'), "HP", "number"),
      explain: L(
        "Indexed access Hero[\"hp\"] reads the type stored under the key hp: number.",
        "El acceso indexado Hero[\"hp\"] lee el tipo guardado en la clave hp: number.",
        "Hero[\"hp\"] はキー hp に入っている型を読む。つまり number だよ。",
      ),
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("type Res<T = string> = { data: T };", "const r: Res = { data: 1 };"),
      options: [YES, L("No: T defaults to string", "No: T por defecto es string", "いいえ：T の既定は string")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "Res without <...> uses the default T = string, and 1 is not a string.",
        "Res sin <...> usa el valor por defecto T = string, y 1 no es string.",
        "<...> なしの Res は既定の T = string を使う。1 は string じゃないよ。",
      ),
    },
    {
      kind: "run",
      prompt: L("Fix pluck: it must print Ada,Bo", "Arregla pluck: debe imprimir Ada,Bo", "pluck を直そう：Ada,Bo と表示"),
      starter: c(
        "function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {",
        "  return items.map(i => i.key);",
        "}",
        'console.log("names:", pluck([{ name: "Ada" }, { name: "Bo" }], "name").join(","));',
        "",
      ),
      solution: c(
        "function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {",
        "  return items.map(i => i[key]);",
        "}",
        'console.log("names:", pluck([{ name: "Ada" }, { name: "Bo" }], "name").join(","));',
        "",
      ),
      expect: "names: Ada,Bo",
      fallback: [String.raw`i\s*\[\s*key\s*\]`],
      explain: L(
        "i.key looks for a key literally named \"key\". i[key] uses the variable's value, \"name\".",
        "i.key busca una clave llamada literalmente \"key\". i[key] usa el valor de la variable, \"name\".",
        "i.key は \"key\" という名前のキーを探す。i[key] なら変数の値 \"name\" を使うよ。",
      ),
    },
  ],
};

const transformsLesson: LessonDef = {
  slug: "type-transformers",
  title: L("The type forge", "La forja de tipos", "型の鍛冶場"),
  concept: "type_transforms",
  mode: "lesson",
  xp: 80,
  enemy: "golem",
  enemyName: L("FORGE GOLEM", "GÓLEM FORJA", "鍛冶ゴーレム"),
  beats: [
    say(L(
      "Utility types are forges: put a type in, get a reshaped type out. Partial, Pick and Omit are built in.",
      "Los tipos utilitarios son forjas: entra un tipo y sale otro remodelado. Partial, Pick y Omit vienen incluidos.",
      "ユーティリティ型は鍛冶場。型を入れると形を変えた型が出てくる。Partial、Pick、Omit は標準装備だよ。",
    )),
    {
      kind: "act",
      prompt: L("Reforge the Hero type", "Reforja el tipo Hero", "Hero 型を鍛え直そう"),
      steps: [
        { label: L("ORE", "MINERAL", "原石"), line: "type Hero = { name: string; hp: number };", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "Hero" }, { t: "value", actor: "hero", text: "name, hp" }] },
        { label: L("Partial", "Partial", "Partial"), line: "type Patch = Partial<Hero>; // all optional", effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "Patch" }, { t: "value", actor: "ally", text: "name?, hp?" }] },
        { label: L("Pick", "Pick", "Pick"), line: 'type Tag = Pick<Hero, "name">; // only name', effects: [{ t: "tag", actor: "ally", text: "Tag" }, { t: "value", actor: "ally", text: "name" }] },
        { label: L("Omit", "Omit", "Omit"), line: 'type NoHp = Omit<Hero, "hp">; // drop hp', effects: [{ t: "tag", actor: "ally", text: "NoHp" }, { t: "value", actor: "ally", text: "name" }] },
        { label: L("USE", "USAR", "使う"), line: "const p: Patch = { hp: 5 };", effects: [{ t: "value", actor: "ally", text: "hp: 5" }] },
        { label: L("PRINT", "IMPRIMIR", "表示する"), line: "console.log(p);", output: "{ hp: 5 }", effects: [{ t: "print", text: "{ hp: 5 }" }, { t: "banner", text: L("FORGED!", "¡FORJADO!", "完成！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("type Hero = { name: string; hp: number };", "const patch: Partial<Hero> = { hp: 5 };"),
      options: [L("Yes", "Sí", "はい"), L("No: name is missing", "No: falta name", "いいえ：name がない")],
      answer: 0,
      check: { compiles: true },
      explain: L(
        "Partial makes every key optional, so { hp: 5 } alone is fine.",
        "Partial vuelve opcional cada clave, así que { hp: 5 } solo está bien.",
        "Partial は全キーを省略可能にする。{ hp: 5 } だけでOKだよ。",
      ),
    },
    {
      kind: "predict",
      prompt: TC,
      code: c("type Hero = { name: string; hp: number };", 'const h: Pick<Hero, "name"> = { name: "A", hp: 1 };'),
      options: [YES, L("No: hp was cut away", "No: hp fue recortado", "いいえ：hp は切り取られた")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "Pick<Hero, \"name\"> has only name. The extra hp in a fresh literal is TS2353.",
        "Pick<Hero, \"name\"> solo tiene name. El hp de más en un literal nuevo es TS2353.",
        "Pick<Hero, \"name\"> には name しかない。リテラルの余分な hp は TS2353。",
      ),
    },
    {
      kind: "pick",
      prompt: L("Grind away hp", "Elimina hp", "hp を削り取ろう"),
      code: c("type Hero = { name: string; hp: number };", 'type NoHp = ___<Hero, "hp">;', 'const n: NoHp = { name: "Ada" };', "console.log(n.name);"),
      options: ["Omit", "Pick", "Partial"],
      answer: 0,
      check: { compiles: true, stdout: "Ada", wrongFail: true },
      explain: L(
        "Omit<T, K> removes the keys K. Pick would KEEP only hp; Partial takes no key list.",
        "Omit<T, K> quita las claves K. Pick CONSERVARÍA solo hp; Partial no recibe lista de claves.",
        "Omit<T, K> はキー K を取り除く。Pick だと hp だけ残り、Partial はキーを受け取らない。",
      ),
      win: [{ t: "print", text: "Ada" }],
    },
    {
      kind: "predict",
      prompt: TC,
      code: c('type Inv = Record<"gem" | "key", number>;', "const i: Inv = { gem: 1 };"),
      options: [YES, L("No: key is missing", "No: falta key", "いいえ：key がない")],
      answer: 1,
      check: { compiles: false },
      explain: L(
        "Record<K, V> requires EVERY key in K. key is missing (TS2741).",
        "Record<K, V> exige TODAS las claves de K. Falta key (TS2741).",
        "Record<K, V> は K の全キーが必要。key がない（TS2741）。",
      ),
    },
    say(L(
      "ReturnType<F> reads a function's return type. But F must be a TYPE, so write ReturnType<typeof make>.",
      "ReturnType<F> lee el tipo de retorno de una función. Pero F debe ser un TIPO: escribe ReturnType<typeof make>.",
      "ReturnType<F> は関数の戻り値の型を読む。F は型なので ReturnType<typeof make> と書くよ。",
    )),
    {
      kind: "type",
      prompt: L("Turn the value into a type", "Convierte el valor en un tipo", "値を型に変えよう"),
      code: c("function make() { return { id: 1 }; }", "type M = ReturnType<___ make>;", "const m: M = { id: 7 };", "console.log(m.id);"),
      answer: "typeof",
      check: { compiles: true, stdout: "7" },
      explain: L(
        "make is a value. typeof make gives its type; without it TS says TS2749.",
        "make es un valor. typeof make da su tipo; sin él TS da el error TS2749.",
        "make は値。typeof make でその型が得られる。ないと TS2749 になるよ。",
      ),
      win: [{ t: "print", text: "7" }],
    },
    say(L(
      "You can build your own forges. A mapped type walks every key: { [K in keyof T]: boolean }.",
      "Puedes crear tus propias forjas. Un tipo mapeado recorre cada clave: { [K in keyof T]: boolean }.",
      "自分の鍛冶場も作れる。マップ型は全キーを回る：{ [K in keyof T]: boolean }。",
    )),
    {
      kind: "predict",
      prompt: L("What type is F?", "¿Qué tipo es F?", "F の型は？"),
      code: c("type Flags<T> = { [K in keyof T]: boolean };", "type F = Flags<{ a: string; b: number }>;"),
      options: ["{ a: boolean; b: boolean }", "{ a: string; b: number }", "boolean"],
      answer: 0,
      check: typeIs(c("type Flags<T> = { [K in keyof T]: boolean };", "type F = Flags<{ a: string; b: number }>;"), "F", "{ a: boolean; b: boolean }"),
      explain: L(
        "Same keys a and b, but every value type is replaced by boolean.",
        "Mismas claves a y b, pero cada tipo de valor se reemplaza por boolean.",
        "キー a と b はそのまま、値の型がすべて boolean に置き換わるよ。",
      ),
    },
    say(L(
      "A conditional type is an if for types: T extends string ? \"yes\" : \"no\". Given a union, it runs on EACH member.",
      "Un tipo condicional es un if para tipos: T extends string ? \"yes\" : \"no\". Con una unión, se aplica a CADA miembro.",
      "条件型は型の if 文：T extends string ? \"yes\" : \"no\"。ユニオン型なら各メンバーに分配されるよ。",
    )),
    {
      kind: "predict",
      prompt: L("What type is B?", "¿Qué tipo es B?", "B の型は？"),
      code: c('type IsStr<T> = T extends string ? "yes" : "no";', "type B = IsStr<string | number>;"),
      options: ['"yes" | "no"', '"no"', '"yes"'],
      answer: 0,
      check: typeIs(c('type IsStr<T> = T extends string ? "yes" : "no";', "type B = IsStr<string | number>;"), "B", '"yes" | "no"'),
      explain: L(
        "It distributes: IsStr<string> | IsStr<number> = \"yes\" | \"no\".",
        "Se distribuye: IsStr<string> | IsStr<number> = \"yes\" | \"no\".",
        "分配されて IsStr<string> | IsStr<number> = \"yes\" | \"no\" になるよ。",
      ),
    },
    {
      kind: "type",
      prompt: L("Capture the element type", "Captura el tipo del elemento", "要素の型を取り出そう"),
      code: c("type ElementOf<T> = T extends (___ U)[] ? U : never;", "const x: ElementOf<string[]> = \"gem\";", "console.log(x);"),
      answer: "infer",
      check: { compiles: true, stdout: "gem" },
      explain: L(
        "infer U names a type found inside the pattern, so ElementOf<string[]> is string.",
        "infer U nombra un tipo encontrado dentro del patrón: ElementOf<string[]> es string.",
        "infer U はパターンの中で見つけた型に名前をつける。ElementOf<string[]> は string だよ。",
      ),
      win: [{ t: "print", text: "gem" }],
    },
    {
      kind: "run",
      prompt: L("Fix pick: print name and hp", "Arregla pick: imprime name y hp", "pick を直そう：name と hp を表示"),
      starter: c(
        "function pick<T, K extends keyof T>(obj: T, keys: K[]): Pick<T, K> {",
        "  const out = {} as Pick<T, K>;",
        "  for (const k in keys) out[k] = obj[k];",
        "  return out;",
        "}",
        'console.log(JSON.stringify(pick({ name: "Ada", hp: 10, mp: 3 }, ["name", "hp"])));',
        "",
      ),
      solution: c(
        "function pick<T, K extends keyof T>(obj: T, keys: K[]): Pick<T, K> {",
        "  const out = {} as Pick<T, K>;",
        "  for (const k of keys) out[k] = obj[k];",
        "  return out;",
        "}",
        'console.log(JSON.stringify(pick({ name: "Ada", hp: 10, mp: 3 }, ["name", "hp"])));',
        "",
      ),
      expect: '{"name":"Ada","hp":10}',
      fallback: [
        String.raw`for\s*\(\s*(const|let)\s+k\s+of\s+keys\s*\)`,
        String.raw`keys\s*\.\s*forEach\s*\(`,
      ],
      explain: L(
        "for...in walks the array's INDEXES \"0\", \"1\". for...of walks the keys themselves. tsc flags it too: TS7053.",
        "for...in recorre los ÍNDICES \"0\", \"1\". for...of recorre las claves mismas. tsc también avisa: TS7053.",
        "for...in は配列の添字 \"0\"、\"1\" を回る。for...of ならキーそのもの。tsc も TS7053 で警告するよ。",
      ),
    },
  ],
};

const titan: LessonDef = {
  slug: "type-titan",
  title: L("BOSS: Type Titan", "JEFE: Titán de Tipos", "ボス：型の巨人"),
  concept: "type_transforms",
  mode: "boss",
  xp: 190,
  enemy: "dragon",
  enemyName: L("TYPE TITAN", "TITÁN DE TIPOS", "型の巨人"),
  beats: [
    enemySays(L(
      "I am the Type Titan. Every value that enters my castle is checked. Will YOUR code type-check?",
      "Soy el Titán de Tipos. Todo valor que entra a mi castillo se revisa. ¿TU código pasará el chequeo?",
      "我こそ型の巨人。この城に入る値はすべて検査する。お前のコードは型チェックを通るか？",
    )),
    {
      kind: "predict", time: 15, prompt: TC,
      code: c("type Brand<T, B> = T & { __brand: B };", 'type UserId = Brand<string, "UserId">;', "function load(id: UserId) {}", 'load("abc");'),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("A plain string lacks the brand, so it can't pass as a UserId.", "Un string simple no tiene la marca: no pasa como UserId.", "ただの string にはブランドがないので UserId にならない。"),
    },
    {
      kind: "predict", time: 12, prompt: TC,
      code: c('type Route = `/${"users" | "posts"}/${number}`;', 'const bad: Route = "/teams/1";'),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("Template literal types check the text: teams isn't allowed.", "Los tipos template literal revisan el texto: teams no está permitido.", "テンプレートリテラル型は文字列を検査する。teams は不可。"),
    },
    {
      kind: "predict", time: 12, prompt: L("What type is N?", "¿Qué tipo es N?", "N の型は？"),
      code: c("type MyAwaited<T> = T extends Promise<infer U> ? U : T;", "type N = MyAwaited<Promise<number>>;"),
      options: ["number", "Promise<number>", "unknown"], answer: 0,
      check: typeIs(c("type MyAwaited<T> = T extends Promise<infer U> ? U : T;", "type N = MyAwaited<Promise<number>>;"), "N", "number"),
      explain: L("infer U captures what the Promise holds: number.", "infer U captura lo que contiene la Promise: number.", "infer U が Promise の中身 number を取り出す。"),
    },
    {
      kind: "predict", time: 12, prompt: TC,
      code: 'let s = "a" as number;',
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("string and number don't overlap, so as refuses (TS2352).", "string y number no se solapan: as se niega (TS2352).", "string と number は重ならないので as は拒否（TS2352）。"),
    },
    {
      kind: "predict", time: 15, prompt: TC,
      code: c('const o = { kind: "circle" };', 'type S = { kind: "circle" | "square" };', "const s: S = o;"),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("o.kind was widened to string. Add as const to keep \"circle\".", "o.kind se amplió a string. Agrega as const para conservar \"circle\".", "o.kind は string に広がった。as const で \"circle\" を保とう。"),
    },
    {
      kind: "predict", time: 12, prompt: TC,
      code: "const p = { x: 1 } satisfies { x: number; y: number };",
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("y is missing, so it doesn't satisfy the type (TS1360).", "Falta y: no satisface el tipo (TS1360).", "y がないので型を満たさない（TS1360）。"),
    },
    {
      kind: "predict", time: 15, prompt: TC,
      code: c("const obj = { a: 1, b: 2 };", "for (const k in obj) {", "  console.log(obj[k]);", "}"),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("for...in gives k: string, and a plain string can't index obj (TS7053).", "for...in da k: string, y un string cualquiera no indexa obj (TS7053).", "for...in の k は string。普通の string では obj を引けない（TS7053）。"),
    },
    {
      kind: "predict", time: 15, prompt: TC,
      code: c("function parse(text: string) {", "  try { return JSON.parse(text); }", "  catch (err) { return err.message; }", "}"),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("Under strict, err is unknown: narrow it with instanceof Error first.", "En strict, err es unknown: estréchalo antes con instanceof Error.", "strict では err は unknown。先に instanceof Error で絞り込もう。"),
    },
    {
      kind: "predict", time: 15, prompt: L("What type is B?", "¿Qué tipo es B?", "B の型は？"),
      code: c('type IsStr<T> = [T] extends [string] ? "yes" : "no";', "type B = IsStr<string | number>;"),
      options: ['"no"', '"yes" | "no"', '"yes"'], answer: 0,
      check: typeIs(c('type IsStr<T> = [T] extends [string] ? "yes" : "no";', "type B = IsStr<string | number>;"), "B", '"no"'),
      explain: L("Wrapping T in [ ] stops distribution: the whole union isn't a string.", "Envolver T en [ ] detiene la distribución: la unión entera no es string.", "T を [ ] で包むと分配されない。ユニオン全体は string じゃない。"),
    },
    {
      kind: "predict", time: 15, prompt: TC,
      code: c(
        "type Animal = { name: string };",
        "type Dog = { name: string; bark: () => void };",
        "type Handler = { handle: (a: Animal) => void };",
        "const h: Handler = { handle: (d: Dog) => d.bark() };",
      ),
      options: [YES, NO], answer: 1,
      check: { compiles: false },
      explain: L("A Handler must accept ANY Animal; a Dog-only function can't (parameters are contravariant).", "Un Handler debe aceptar CUALQUIER Animal; una función solo para Dog no puede (parámetros contravariantes).", "Handler はどの Animal も受け取る必要がある。Dog 専用関数はダメ（引数は反変）。"),
    },
    enemySays(L(
      "Impossible... not one type slipped past you. The castle gates open. Beware the tower of the event loop!",
      "Imposible... ningún tipo se te escapó. Las puertas del castillo se abren. ¡Cuidado con la torre del event loop!",
      "ばかな…どの型も見逃さなかったとは。城の門は開いた。イベントループの塔に気をつけろ！",
    )),
  ],
};

export const typeCastle: RegionDef = {
  slug: "type-castle",
  name: L("Type Castle", "Castillo de Tipos", "型の城"),
  subtitle: L("Shapes · unions · generics", "Formas · uniones · genéricos", "型・ユニオン型・ジェネリクス"),
  theme: "castle",
  lessons: [shapesLesson, unionsLesson, genericsLesson, transformsLesson, titan],
};
