import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 1 · VALUE VILLAGE  (let/const, primitive types, numbers, strings, equality, truthiness)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");

// ─── 1.1 Labels and items ──────────────────────────────────────────────────
const labels: LessonDef = {
  slug: "labels-and-items",
  title: L("Labels and items", "Etiquetas y objetos", "ラベルとアイテム"),
  concept: "values",
  mode: "lesson",
  xp: 60,
  enemy: "typescript/undefined-ghost",
  enemyName: L("EMPTY GHOST", "FANTASMA VACÍO", "からっぽゴースト"),
  beats: [
    say(L(
      "Welcome to Value Village! A VARIABLE is a label you stick on a value, so you can find it again.",
      "¡Bienvenido a la Aldea de los Valores! Una VARIABLE es una etiqueta pegada a un valor para encontrarlo luego.",
      "バリュー村へようこそ！変数は値に貼る「ラベル」。あとで見つけられるようにね。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and watch the labels", "Pulsa en orden y mira las etiquetas", "順番に押して、ラベルを見てね"),
      steps: [
        { label: L("LABEL hp", "ETIQUETA hp", "hp を貼る"), line: "let hp = 10;", effects: [{ t: "tag", actor: "hero", text: "hp", value: "10" }] },
        { label: L("HEAL", "CURAR", "回復"), line: "hp = hp + 5;", effects: [{ t: "value", actor: "hero", text: "15" }, { t: "say", actor: "hero", text: L("Feeling better!", "¡Mucho mejor!", "元気出た！") }] },
        { label: L("PRINT", "IMPRIMIR", "表示"), line: "console.log(hp);", effects: [{ t: "print", text: "15" }], output: "15" },
        { label: L("GLUE gold", "PEGAR gold", "gold を固定"), line: "const gold = 5;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "gold", value: "5" }] },
        {
          label: L("MOVE gold", "MOVER gold", "gold を変える"),
          line: "gold = 6;",
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: L("I'm glued!", "¡Estoy pegada!", "動けない！") }],
          error: {
            compiler: "error TS2588: Cannot assign to 'gold' because it is a constant.",
            plain: L("const glues the label to its value. TypeScript stops it before it runs.", "const pega la etiqueta a su valor. TypeScript lo frena antes de ejecutar.", "const のラベルは貼りかえ不可。実行前に TypeScript が止めるよ。"),
          },
        },
      ],
    },
    say(L(
      "let: the label can move to a new value. const: the label is glued forever. Use const unless you need to change it.",
      "let: la etiqueta puede pasar a otro valor. const: queda pegada para siempre. Usa const salvo que necesites cambiarla.",
      "let は貼りかえOK、const は貼りっぱなし。変える必要がなければ const を使おう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "let hp = 10;\nhp = hp + 5;\nconsole.log(hp);",
      options: ["15", "10", "105"],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("hp + 5 is 15, and the label hp now points to 15.", "hp + 5 es 15, y la etiqueta hp ahora apunta a 15.", "hp + 5 は 15。ラベル hp はいま 15 を指しているよ。"),
      setup: [{ t: "tag", actor: "hero", text: "hp", value: "10" }],
      win: [{ t: "value", actor: "hero", text: "15" }, { t: "print", text: "15" }],
    },
    {
      kind: "pick",
      prompt: L("This label must change", "Esta etiqueta debe cambiar", "このラベルは変わるよ"),
      code: '___ name = "Ada";\nname = "Grace";\nconsole.log(name);',
      options: ["let", "const"],
      answer: 0,
      check: { compiles: true, stdout: "Grace", wrongFail: true },
      explain: L("The label is reassigned, so it must be let. const would be error TS2588.", "La etiqueta se reasigna, así que debe ser let. const daría el error TS2588.", "ラベルを貼りかえるから let。const だとエラー TS2588 になるよ。"),
      setup: [{ t: "tag", actor: "hero", text: "name", value: "Ada" }],
      win: [{ t: "value", actor: "hero", text: "Grace" }, { t: "print", text: "Grace" }],
    },
    say(L(
      "Careful: const glues the LABEL, not the item. A const array can still get new things inside.",
      "Ojo: const pega la ETIQUETA, no el objeto. Un array const todavía puede recibir cosas nuevas.",
      "注意：const が固定するのはラベルだけ。const の配列でも中身は増やせるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const bag = ["gem"];\nbag.push("key");\nconsole.log(bag.length);',
      options: ["2", "1", L("Error: bag is const", "Error: bag es const", "エラー：bag は const")],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("push changes the array itself. The label bag never moved, so const is happy.", "push cambia el array en sí. La etiqueta bag nunca se movió, así que const está feliz.", "push は配列の中身を変えるだけ。ラベル bag は動いていないから const でも OK。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "bag" }],
      win: [{ t: "value", actor: "hero", text: "2 items" }, { t: "print", text: "2" }],
    },
    say(L(
      "Every value has a type. typeof tells you which: number, string, boolean...",
      "Cada valor tiene un tipo. typeof te dice cuál: number, string, boolean...",
      "値にはそれぞれ型がある。typeof で調べられるよ：number、string、boolean…",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'console.log(typeof 42, typeof "hi", typeof true);',
      options: ["number string boolean", "42 hi true", "int text bool"],
      answer: 0,
      output: "number string boolean",
      check: { compiles: true, stdout: "number string boolean" },
      explain: L("typeof returns the type's name as a string. JS has one number type for all numbers.", "typeof devuelve el nombre del tipo como string. JS tiene un solo tipo number para todos los números.", "typeof は型の名前を文字列で返す。数値の型は number ひとつだけだよ。"),
    },
    {
      kind: "predict",
      prompt: L("An empty label. What does it print?", "Una etiqueta vacía. ¿Qué imprime?", "からっぽのラベル。何が表示される？"),
      code: "let x;\nconsole.log(x);",
      options: ["undefined", "null", "0"],
      answer: 0,
      output: "undefined",
      check: { compiles: true, stdout: "undefined" },
      explain: L("A label with no value yet holds undefined: 'nothing was put here'.", "Una etiqueta sin valor guarda undefined: 'aquí no se puso nada'.", "値を入れていないラベルは undefined。「まだ何も入っていない」って意味だよ。"),
      setup: [{ t: "tag", actor: "hero", text: "x" }],
      win: [{ t: "value", actor: "hero", text: "undefined" }, { t: "say", actor: "enemy", text: L("Boo! Empty!", "¡Bu! ¡Vacío!", "ばあ！からっぽ！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(typeof null);",
      options: ["object", "null", "undefined"],
      answer: 0,
      output: "object",
      check: { compiles: true, stdout: "object" },
      explain: L("A famous old bug: typeof null is 'object'. It was never fixed, to keep old sites working.", "Un bug antiguo y famoso: typeof null es 'object'. Nunca se arregló para no romper sitios viejos.", "有名な昔のバグで typeof null は 'object'。古いサイトを壊さないため直されていないんだ。"),
    },
    say(L(
      "TypeScript adds TYPE ANNOTATIONS: let level: number = 3. The checker then guards that label.",
      "TypeScript agrega ANOTACIONES DE TIPO: let level: number = 3. El verificador vigila esa etiqueta.",
      "TypeScript では型注釈を書ける：let level: number = 3。型チェッカーがラベルを見張るよ。",
    )),
    {
      kind: "type",
      prompt: L("Annotate the type of level", "Anota el tipo de level", "level の型を書こう"),
      code: "let level: ___ = 3;\nconsole.log(level + 1);",
      answer: "number",
      check: { compiles: true, stdout: "4" },
      explain: L("3 is a number, so the annotation is : number.", "3 es un number, así que la anotación es : number.", "3 は number だから、型注釈は : number だよ。"),
      win: [{ t: "tag", actor: "hero", text: "level: number", value: "3" }, { t: "print", text: "4" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'let level: number = 3;\nlevel = "three";',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("Error TS2322: a string can't go on a number label. The bug never reaches the player.", "Error TS2322: un string no cabe en una etiqueta number. El bug nunca llega al jugador.", "エラー TS2322：number のラベルに string は入れられない。バグは実行前に止まるよ。"),
      setup: [{ t: "tag", actor: "hero", text: "level: number", value: "3" }],
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Blocked!", "¡Bloqueado!", "ブロック！") }],
    },
    {
      kind: "run",
      prompt: L("Fix it: it must print score: 10", "Arréglalo: debe imprimir score: 10", "直そう：score: 10 と表示させて"),
      starter: 'const score = 0;\nscore = score + 10;\nconsole.log("score:", score);\n',
      solution: 'let score = 0;\nscore = score + 10;\nconsole.log("score:", score);\n',
      expect: "score: 10",
      fallback: [String.raw`let\s+score\s*=\s*0`, String.raw`var\s+score\s*=\s*0`, String.raw`let\s+score\s*:\s*number\s*=\s*0`],
      explain: L("score changes, so its label must be let, not const.", "score cambia, así que su etiqueta debe ser let, no const.", "score は変わるから、ラベルは const じゃなく let にしよう。"),
    },
  ],
};

// ─── 1.2 Numbers and strings ───────────────────────────────────────────────
const numbers: LessonDef = {
  slug: "numbers-and-strings",
  title: L("Numbers and strings", "Números y strings", "数値と文字列"),
  concept: "values",
  mode: "lesson",
  xp: 65,
  enemy: "typescript/nan-gremlin",
  enemyName: L("NAN GREMLIN", "GREMLIN NAN", "NaN グレムリン"),
  beats: [
    say(L(
      "JS has ONE number type for everything: 7, 3.5, -2. It's stored in binary, and that has quirks.",
      "JS tiene UN solo tipo de número para todo: 7, 3.5, -2. Se guarda en binario, y eso tiene rarezas.",
      "JS の数値型は number ひとつだけ。7 も 3.5 も -2 も同じ。二進数で保存されるからクセがあるよ。",
    )),
    {
      kind: "act",
      prompt: L("Weigh the coins and watch the scale", "Pesa las monedas y mira la balanza", "コインをはかって、目盛りを見てね"),
      steps: [
        { label: L("COIN a", "MONEDA a", "コイン a"), line: "const a = 0.1;", effects: [{ t: "tag", actor: "hero", text: "a", value: "0.1" }] },
        { label: L("COIN b", "MONEDA b", "コイン b"), line: "const b = 0.2;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b", value: "0.2" }] },
        { label: L("WEIGH", "PESAR", "はかる"), line: "console.log(a + b);", effects: [{ t: "print", text: "0.30000000000000004" }, { t: "shake" }, { t: "say", actor: "hero", text: L("Almost 0.3?!", "¿¡Casi 0.3!?", "ほぼ 0.3？！") }], output: "0.30000000000000004" },
        { label: L("DIVIDE 0/0", "DIVIDIR 0/0", "0/0 を計算"), line: "console.log(0 / 0);", effects: [{ t: "print", text: "NaN" }, { t: "say", actor: "enemy", text: L("I'm NaN! Hee!", "¡Soy NaN! ¡Ji!", "NaN だよ！ヒヒ！") }], output: "NaN" },
      ],
    },
    say(L(
      "0.1 + 0.2 is a hair off from 0.3. Never compare decimals with ===: check that the difference is tiny.",
      "0.1 + 0.2 queda a un pelo de 0.3. Nunca compares decimales con ===: verifica que la diferencia sea mínima.",
      "0.1 + 0.2 は 0.3 からほんの少しずれる。小数を === で比べず、差がとても小さいか確かめよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(0.1 + 0.2 === 0.3);",
      options: ["false", "true"],
      answer: 0,
      output: "false",
      check: { compiles: true, stdout: "false" },
      explain: L("0.1 + 0.2 is 0.30000000000000004, which is not exactly 0.3.", "0.1 + 0.2 es 0.30000000000000004, que no es exactamente 0.3.", "0.1 + 0.2 は 0.30000000000000004。ぴったり 0.3 じゃないんだ。"),
      win: [{ t: "print", text: "false" }, { t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(7 / 2, Math.floor(7 / 2));",
      options: ["3.5 3", "3 3", "3.5 4"],
      answer: 0,
      output: "3.5 3",
      check: { compiles: true, stdout: "3.5 3" },
      explain: L("/ never drops decimals. For whole-number division, round down with Math.floor.", "/ nunca descarta decimales. Para división entera, redondea hacia abajo con Math.floor.", "/ は小数を切り捨てない。整数の割り算は Math.floor で切り捨てよう。"),
    },
    say(L(
      "NaN means 'Not a Number', yet its type IS number. It's not even equal to itself: test it with Number.isNaN.",
      "NaN significa 'No es un Número', pero su tipo ES number. Ni siquiera es igual a sí mismo: pruébalo con Number.isNaN.",
      "NaN は「数ではない」なのに型は number。自分自身とも等しくないから Number.isNaN で調べよう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(typeof NaN, Number.isNaN(NaN));",
      options: ["number true", "NaN true", "number false"],
      answer: 0,
      output: "number true",
      check: { compiles: true, stdout: "number true" },
      explain: L("NaN is a special number value meaning 'failed math'. Number.isNaN is the safe test.", "NaN es un valor number especial que significa 'cálculo fallido'. Number.isNaN es la prueba segura.", "NaN は「計算失敗」を表す特別な number の値。Number.isNaN で確実に判定できるよ。"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "NaN" }],
      win: [{ t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(10 / 0, 0 / 0);",
      options: ["Infinity NaN", "0 0", L("Error: division by zero", "Error: división por cero", "エラー：ゼロ除算")],
      answer: 0,
      output: "Infinity NaN",
      check: { compiles: true, stdout: "Infinity NaN" },
      explain: L("JS never crashes on division by zero: 10 / 0 is Infinity and 0 / 0 is NaN.", "JS nunca falla al dividir por cero: 10 / 0 es Infinity y 0 / 0 es NaN.", "JS はゼロで割ってもエラーにならない。10 / 0 は Infinity、0 / 0 は NaN だよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'console.log(parseInt("42px"), Number("42px"));',
      options: ["42 NaN", "42 42", "NaN NaN"],
      answer: 0,
      output: "42 NaN",
      check: { compiles: true, stdout: "42 NaN" },
      explain: L("parseInt reads digits until it hits junk. Number needs the WHOLE string to be a number.", "parseInt lee dígitos hasta toparse con basura. Number necesita que TODO el string sea un número.", "parseInt は数字以外が出るまで読む。Number は文字列全体が数でないとダメなんだ。"),
    },
    say(L(
      "Strings use quotes. Backticks make TEMPLATE strings: put any value inside ${ } and it's plugged in.",
      "Los strings usan comillas. Las comillas invertidas crean TEMPLATES: pon cualquier valor dentro de ${ } y se inserta.",
      "文字列はクォートで囲む。バッククォートならテンプレート文字列。${ } の中の値が埋めこまれるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(`HP: ${3 + 4}`);",
      options: ["HP: 7", "HP: ${3 + 4}", "HP: 34"],
      answer: 0,
      output: "HP: 7",
      check: { compiles: true, stdout: "HP: 7" },
      explain: L("Inside ${ } the code runs first: 3 + 4 is 7, then it's placed in the string.", "Dentro de ${ } el código se ejecuta primero: 3 + 4 es 7 y luego se pone en el string.", "${ } の中が先に計算される。3 + 4 = 7 が文字列に入るよ。"),
    },
    {
      kind: "type",
      prompt: L("Shout the owl's name", "Grita el nombre del búho", "フクロウの名前を大文字に"),
      code: 'console.log("owl".___());',
      answer: "toUpperCase",
      check: { compiles: true, stdout: "OWL" },
      explain: L("toUpperCase returns a new string in capitals. Strings never change in place.", "toUpperCase devuelve un string nuevo en mayúsculas. Los strings nunca cambian en el sitio.", "toUpperCase は大文字の新しい文字列を返す。文字列そのものは変わらないよ。"),
      win: [{ t: "print", text: "OWL" }],
    },
    {
      kind: "pick",
      prompt: L("Replace EVERY l, not just the first", "Reemplaza CADA l, no solo la primera", "最初だけでなく全部の l を置換"),
      code: 'console.log("Hello".replace(/l/___, "L"));',
      options: ["g", "i", "m"],
      answer: 0,
      check: { compiles: true, stdout: "HeLLo" },
      explain: L("The g (global) flag replaces all matches. Without it, only the first l changes: HeLlo.", "La bandera g (global) reemplaza todas las coincidencias. Sin ella solo cambia la primera l: HeLlo.", "g（グローバル）フラグで全部を置換。ないと最初の l だけ変わって HeLlo になるよ。"),
    },
    {
      kind: "run",
      prompt: L("Fix the scale: it must print ok", "Arregla la balanza: debe imprimir ok", "はかりを直そう：ok と表示させて"),
      starter: 'const total = 0.1 + 0.2;\nconsole.log(total === 0.3 ? "ok" : "bad");\n',
      solution: 'const total = 0.1 + 0.2;\nconsole.log(Math.abs(total - 0.3) < Number.EPSILON ? "ok" : "bad");\n',
      expect: "ok",
      fallback: [
        String.raw`Math\.abs\s*\(\s*total\s*-\s*0\.3\s*\)\s*<`,
        String.raw`Math\.abs\s*\(\s*0\.3\s*-\s*total\s*\)\s*<`,
        String.raw`total\.toFixed\s*\(\s*\d\s*\)\s*===?\s*"0\.3`,
        String.raw`Math\.round\s*\(\s*total\s*\*\s*10+\s*\)`,
      ],
      explain: L("Compare the difference: Math.abs(total - 0.3) < Number.EPSILON means 'close enough'.", "Compara la diferencia: Math.abs(total - 0.3) < Number.EPSILON significa 'suficientemente cerca'.", "差で比べよう。Math.abs(total - 0.3) < Number.EPSILON は「十分近い」という意味だよ。"),
    },
  ],
};

// ─── 1.3 Equal or the same? ────────────────────────────────────────────────
const equality: LessonDef = {
  slug: "equality-and-truthiness",
  title: L("Equal or the same?", "¿Igual o idéntico?", "等しい？同じ？"),
  concept: "equality",
  mode: "lesson",
  xp: 70,
  enemy: "typescript/any-shifter",
  enemyName: L("ANY SHIFTER", "CAMBIAFORMAS ANY", "any バケ"),
  beats: [
    say(L(
      "=== compares value AND type, with no tricks. == converts types first, and that brings surprises.",
      "=== compara valor Y tipo, sin trucos. == convierte los tipos primero, y eso trae sorpresas.",
      "=== は値と型をそのまま比べる。== は先に型を変換するから、思わぬ結果になるよ。",
    )),
    {
      kind: "act",
      prompt: L("Compare the two chips", "Compara las dos fichas", "2つのチップを比べよう"),
      steps: [
        { label: L("NUMBER 1", "NÚMERO 1", "数値 1"), line: "const a: any = 1;", effects: [{ t: "tag", actor: "hero", text: "a", value: "1" }] },
        { label: L("STRING \"1\"", "STRING \"1\"", "文字列 \"1\""), line: 'const b: any = "1";', effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b", value: '"1"' }] },
        { label: L("LOOSE ==", "FLOJO ==", "ゆるい =="), line: "console.log(a == b);", effects: [{ t: "value", actor: "ally", text: "1" }, { t: "say", actor: "ally", text: L("I'll convert!", "¡Me convierto!", "変換しちゃえ！") }, { t: "print", text: "true" }], output: "true" },
        { label: L("STRICT ===", "ESTRICTO ===", "厳密 ==="), line: "console.log(a === b);", effects: [{ t: "value", actor: "ally", text: '"1"' }, { t: "shake" }, { t: "print", text: "false" }], output: "false" },
        {
          label: L("WITHOUT any", "SIN any", "any なし"),
          line: 'console.log(1 == "1");',
          effects: [{ t: "shake" }, { t: "banner", text: L("TSC SAYS NO", "TSC DICE NO", "tsc がダメ出し") }],
          error: {
            compiler: "error TS2367: This comparison appears to be unintentional because the types 'number' and 'string' have no overlap.",
            plain: L("TypeScript sees number vs string and stops you. With any, it can't help.", "TypeScript ve number contra string y te frena. Con any no puede ayudarte.", "number と string の比較は TypeScript が止める。any だと守れないんだ。"),
          },
        },
      ],
    },
    say(L(
      "Village rule: always use ===. And beware of any: it switches TypeScript's guard off.",
      "Regla de la aldea: usa siempre ===. Y cuidado con any: apaga la guardia de TypeScript.",
      "村のルール：いつも === を使おう。any には要注意。TypeScript の見張りが消えちゃうよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'const a: any = "5";\nconsole.log(a + 3, a - 3);',
      options: ["53 2", "8 2", "53 NaN"],
      answer: 0,
      output: "53 2",
      check: { compiles: true, stdout: "53 2" },
      explain: L("+ with a string glues text: \"53\". - only works on numbers, so \"5\" becomes 5: 2.", "+ con un string pega texto: \"53\". - solo trabaja con números, así que \"5\" pasa a 5: 2.", "+ に文字列があると連結して \"53\"。- は数値だけなので \"5\" は 5 になって 2。"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "a: any", value: '"5"' }],
      win: [{ t: "print", text: "53 2" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(null == undefined, null === undefined);",
      options: ["true false", "false false", "true true"],
      answer: 0,
      output: "true false",
      check: { compiles: true, stdout: "true false" },
      explain: L("== treats null and undefined as the same 'nothing'. === sees two different types.", "== trata null y undefined como la misma 'nada'. === ve dos tipos distintos.", "== は null と undefined を同じ「なし」とみなす。=== は別の型として扱うよ。"),
    },
    say(L(
      "In an if, values are TRUTHY or FALSY. Falsy: false, 0, \"\", null, undefined, NaN. Everything else is truthy.",
      "En un if, los valores son TRUTHY o FALSY. Falsy: false, 0, \"\", null, undefined, NaN. Todo lo demás es truthy.",
      "if では値は truthy か falsy。falsy は false、0、\"\"、null、undefined、NaN。ほかは全部 truthy。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'console.log(Boolean(""), Boolean("0"), Boolean([]));',
      options: ["false true true", "false false false", "false false true"],
      answer: 0,
      output: "false true true",
      check: { compiles: true, stdout: "false true true" },
      explain: L("Only the EMPTY string is falsy. \"0\" has a character, and any array, even empty, is truthy.", "Solo el string VACÍO es falsy. \"0\" tiene un carácter, y todo array, aunque esté vacío, es truthy.", "falsy なのは空文字だけ。\"0\" は1文字あるし、配列は空でも truthy だよ。"),
    },
    {
      kind: "pick",
      prompt: L("Which value is falsy?", "¿Qué valor es falsy?", "falsy な値はどれ？"),
      code: 'const v = ___;\nconsole.log(v ? "truthy" : "falsy");',
      options: ["0", '"false"', "[1]", "{}"],
      answer: 0,
      check: { compiles: true, stdout: "falsy" },
      explain: L("0 is falsy. \"false\" is a non-empty string, and arrays and objects are always truthy.", "0 es falsy. \"false\" es un string no vacío, y los arrays y objetos siempre son truthy.", "0 は falsy。\"false\" は空じゃない文字列、配列とオブジェクトはいつも truthy。"),
      win: [{ t: "print", text: "falsy" }],
    },
    say(L(
      "|| falls back on ANY falsy value. ?? falls back only on null or undefined. Huge difference when 0 is valid!",
      "|| usa el respaldo con CUALQUIER falsy. ?? solo con null o undefined. ¡Gran diferencia cuando 0 es válido!",
      "|| は falsy なら何でも代わりを使う。?? は null と undefined だけ。0 が正しい値のとき大違いだよ！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const n: number = 0;\nconsole.log(n || 10, n ?? 10);",
      options: ["10 0", "0 0", "10 10"],
      answer: 0,
      output: "10 0",
      check: { compiles: true, stdout: "10 0" },
      explain: L("0 is falsy, so || picks 10. But 0 is not null or undefined, so ?? keeps 0.", "0 es falsy, así que || elige 10. Pero 0 no es null ni undefined, así que ?? conserva 0.", "0 は falsy だから || は 10。でも null でも undefined でもないから ?? は 0 のまま。"),
      setup: [{ t: "tag", actor: "hero", text: "n", value: "0" }],
      win: [{ t: "print", text: "10 0" }],
    },
    {
      kind: "type",
      prompt: L("Fall back only when score is null", "Respaldo solo si score es null", "score が null のときだけ代わりを使う"),
      code: "const score: number | null = null;\nconsole.log(score ___ 0);",
      answer: "??",
      check: { compiles: true, stdout: "0" },
      explain: L("?? is the nullish fallback: it only replaces null and undefined.", "?? es el respaldo nullish: solo reemplaza null y undefined.", "?? は null と undefined だけを置きかえる演算子だよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "console.log(Object.is(NaN, NaN), Object.is(0, -0));",
      options: ["true false", "false true", "false false"],
      answer: 0,
      output: "true false",
      check: { compiles: true, stdout: "true false" },
      explain: L("Object.is means 'the very same value': NaN equals itself there, and 0 and -0 differ.", "Object.is significa 'el mismo valor exacto': ahí NaN es igual a sí mismo, y 0 y -0 son distintos.", "Object.is は「完全に同じ値か」。NaN は自分と等しく、0 と -0 は別あつかいだよ。"),
    },
    {
      kind: "run",
      prompt: L("0 lives is valid! It must print lives: 0", "¡0 vidas es válido! Debe imprimir lives: 0", "0 も正しい値！lives: 0 と表示させて"),
      starter: 'const input = 0;\nconst lives = input || 3;\nconsole.log("lives:", lives);\n',
      solution: 'const input = 0;\nconst lives = input ?? 3;\nconsole.log("lives:", lives);\n',
      expect: "lives: 0",
      fallback: [String.raw`input\s*\?\?\s*3`, String.raw`input\s*===?\s*(?:undefined|null)\s*\?\s*3\s*:\s*input`],
      explain: L("|| replaced the valid 0. ?? only replaces null or undefined, so 0 stays.", "|| reemplazó el 0 válido. ?? solo reemplaza null o undefined, así que el 0 se queda.", "|| は正しい 0 まで置きかえた。?? なら null と undefined だけだから 0 が残るよ。"),
    },
  ],
};

// ─── 1.4 Boss: Value Golem ─────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "value-golem",
  title: L("Boss: Value Golem", "Jefe: Gólem de Valores", "ボス：バリューゴーレム"),
  concept: "equality",
  mode: "boss",
  xp: 180,
  enemy: "golem",
  enemyName: L("VALUE GOLEM", "GÓLEM DE VALORES", "バリューゴーレム"),
  beats: [
    enemySays(L(
      "I AM THE VALUE GOLEM. My body is made of loose types. Can you tell what each value really is?",
      "SOY EL GÓLEM DE VALORES. Mi cuerpo está hecho de tipos sueltos. ¿Sabes qué es cada valor de verdad?",
      "我はバリューゴーレム。この体はゆるい型でできている。それぞれの値の正体がわかるか？",
    )),
    { kind: "predict", time: 12, prompt: PRINT, code: "console.log(typeof typeof 1);", options: ["string", "number", "typeof"], answer: 0, output: "string", check: { compiles: true, stdout: "string" }, explain: L("typeof 1 is the string \"number\", and typeof a string is \"string\".", "typeof 1 es el string \"number\", y typeof de un string es \"string\".", "typeof 1 は文字列 \"number\"。文字列の typeof は \"string\" だよ。") },
    { kind: "pick", time: 12, prompt: L("This label changes", "Esta etiqueta cambia", "このラベルは変わる"), code: "___ lives = 3;\nlives = lives - 1;\nconsole.log(lives);", options: ["let", "const"], answer: 0, check: { compiles: true, stdout: "2", wrongFail: true }, explain: L("Reassigned labels need let.", "Las etiquetas reasignadas necesitan let.", "貼りかえるラベルは let。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "console.log(0.1 + 0.2);", options: ["0.30000000000000004", "0.3", "0.30"], answer: 0, output: "0.30000000000000004", check: { compiles: true, stdout: "0.30000000000000004" }, explain: L("Binary floats can't store 0.1 exactly.", "Los floats binarios no guardan 0.1 exacto.", "二進数の小数は 0.1 を正確に保存できない。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'const a: any = null;\nconst b: any = undefined;\nconsole.log(a + 1, b + 1);', options: ["1 NaN", "NaN NaN", "1 1"], answer: 0, output: "1 NaN", check: { compiles: true, stdout: "1 NaN" }, explain: L("In math, null becomes 0 but undefined becomes NaN.", "En cálculos, null pasa a 0 pero undefined pasa a NaN.", "計算では null は 0、undefined は NaN になる。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'console.log("b" + "a" + +"a" + "a");', options: ["baNaNa", "baaa", "ba+aa"], answer: 0, output: "baNaNa", check: { compiles: true, stdout: "baNaNa" }, explain: L("+\"a\" tries to make a number from \"a\": NaN. Then it's glued as text.", "+\"a\" intenta hacer un número de \"a\": NaN. Luego se pega como texto.", "+\"a\" は \"a\" を数値にしようとして NaN。それが文字列に連結される。") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'const a: any = "3";\nconst b = a * 2;\nconsole.log(typeof b, b);', options: ["number 6", "string 33", "string 6"], answer: 0, output: "number 6", check: { compiles: true, stdout: "number 6" }, explain: L("* only works on numbers, so \"3\" is converted to 3.", "* solo trabaja con números, así que \"3\" se convierte en 3.", "* は数値専用だから \"3\" は 3 に変換される。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: 'const n: number = "3" * 2;', options: [YES, NO_TSC], answer: 1, check: { compiles: false }, explain: L("TS2362: TypeScript refuses math on a string.", "TS2362: TypeScript rechaza cálculos con un string.", "TS2362：文字列での計算は TypeScript が拒否する。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "const x: any = [];\nconsole.log(x == false);", options: ["true", "false"], answer: 0, output: "true", check: { compiles: true, stdout: "true" }, explain: L("== turns [] into \"\" and then 0, and false into 0. Use ===!", "== convierte [] en \"\" y luego 0, y false en 0. ¡Usa ===!", "== は [] を \"\" から 0 に、false を 0 に変換する。=== を使おう！") },
    { kind: "predict", time: 12, prompt: PRINT, code: 'const s: string = "false";\nconst n: number = 0;\nconsole.log(!!s, !!n);', options: ["true false", "false false", "true true"], answer: 0, output: "true false", check: { compiles: true, stdout: "true false" }, explain: L("A non-empty string is truthy; 0 is falsy.", "Un string no vacío es truthy; 0 es falsy.", "空でない文字列は truthy、0 は falsy。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'const s: string = "";\nconsole.log([s || "guest", s ?? "guest"]);', options: ["[ 'guest', '' ]", "[ 'guest', 'guest' ]", "[ '', '' ]"], answer: 0, output: "[ 'guest', '' ]", check: { compiles: true, stdout: "[ 'guest', '' ]" }, explain: L("\"\" is falsy, so || falls back. It's not null, so ?? keeps it.", "\"\" es falsy, así que || usa el respaldo. No es null, así que ?? lo conserva.", "\"\" は falsy なので || は代わりを使う。null じゃないので ?? はそのまま。") },
    { kind: "type", time: 15, prompt: L("The safe NaN test", "La prueba segura de NaN", "安全な NaN 判定"), code: "console.log(Number.___(NaN));", answer: "isNaN", check: { compiles: true, stdout: "true" }, explain: L("Number.isNaN(NaN) is true. NaN === NaN is always false.", "Number.isNaN(NaN) es true. NaN === NaN siempre es false.", "Number.isNaN(NaN) は true。NaN === NaN はいつも false。") },
    enemySays(L(
      "Crumble... you saw through every disguise. The forest of closures lies ahead, traveler.",
      "Me desmorono... viste a través de cada disfraz. El bosque de closures te espera, viajero.",
      "くずれる…すべての化けの皮を見破ったな。この先はクロージャの森だ、旅人よ。",
    )),
  ],
};

export const valueVillage: RegionDef = {
  slug: "value-village",
  name: L("Value Village", "Aldea de Valores", "バリュー村"),
  subtitle: L("let/const · types · equality", "let/const · tipos · igualdad", "let/const・型・等価"),
  theme: "village",
  lessons: [labels, numbers, equality, boss],
};
