import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { L, say, enemySays } from "../../rust/helpers.ts";

// REGION 2 · FOLD FOREST  (recursion, higher-order functions, currying and composition, folds)

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_GHC = L("No: GHC stops it", "No: GHC lo detiene", "いいえ：GHC が止める");
const NO_COMPILE = L("Compile error", "Error de compilación", "コンパイルエラー");

// ─── 2.1 The owl that asks itself ──────────────────────────────────────────
const recursion: LessonDef = {
  slug: "recursion",
  title: L("The owl that asks itself", "El búho que se pregunta", "自分に聞くフクロウ"),
  concept: "recursion",
  mode: "lesson",
  xp: 65,
  enemy: "ghost",
  enemyName: L("ECHO GHOST", "FANTASMA ECO", "こだまゴースト"),
  beats: [
    say(L(
      "Haskell has no loops. Instead, a function calls ITSELF on a smaller input, until a BASE CASE answers directly.",
      "Haskell no tiene bucles. En su lugar, una función se llama a SÍ MISMA con algo más pequeño, hasta que un CASO BASE responde.",
      "Haskell にループはない。関数が小さくした入力で自分を呼び、「基底ケース」が直接答えるまで続ける。",
    )),
    {
      kind: "act",
      prompt: L("Teach len to count, then ask it", "Enseña a len a contar y luego pregúntale", "len に数え方を教えて聞いてみよう"),
      steps: [
        { label: L("BASE CASE", "CASO BASE", "基底ケース"), line: "len [] = 0", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "len" }, { t: "say", actor: "ally", text: L("Empty? 0!", "¿Vacía? ¡0!", "空なら 0！") }] },
        { label: L("STEP", "PASO", "くり返し"), line: "len (_:xs) = 1 + len xs", effects: [{ t: "say", actor: "ally", text: L("1 + len of the rest", "1 + len del resto", "1 + 残りの len") }] },
        { label: L("ASK \"owl\"", "PREGUNTAR \"owl\"", "\"owl\" を聞く"), line: "main = print (len \"owl\")", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "give", to: "ally" }, { t: "clone", to: "ally" }, { t: "say", actor: "ally", text: L("1+1+1+0", "1+1+1+0", "1+1+1+0") }, { t: "print", text: "3" }], output: "3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "len :: [a] -> Int\nlen [] = 0\nlen (_:xs) = 1 + len xs\n\nmain = print (len \"owl\")",
      options: ["3", "0", "1"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("Each step adds 1 and asks about the rest: 1 + (1 + (1 + 0)) = 3.", "Cada paso suma 1 y pregunta por el resto: 1 + (1 + (1 + 0)) = 3.", "1 足して残りを聞く：1 + (1 + (1 + 0)) = 3。"),
      win: [{ t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "fact :: Integer -> Integer\nfact 0 = 1\nfact n = n * fact (n - 1)\n\nmain = print (fact 5)",
      options: ["120", "15", "24"],
      answer: 0,
      output: "120",
      check: { compiles: true, stdout: "120" },
      explain: L("5 * 4 * 3 * 2 * 1 * 1 = 120. fact 0 = 1 is the base case that stops it.", "5 * 4 * 3 * 2 * 1 * 1 = 120. fact 0 = 1 es el caso base que lo detiene.", "5 * 4 * 3 * 2 * 1 * 1 = 120。fact 0 = 1 が止める基底ケース。"),
      win: [{ t: "print", text: "120" }],
    },
    say(L(
      "Remember: Int wraps around silently when too big, Integer never does. Big recursive answers need Integer.",
      "Recuerda: Int da la vuelta en silencio si es muy grande; Integer nunca. Las respuestas recursivas grandes necesitan Integer.",
      "思い出して：Int は大きすぎると黙って一周、Integer はしない。大きな再帰の答えには Integer。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "factInt :: Int -> Int\nfactInt 0 = 1\nfactInt n = n * factInt (n - 1)\n\nmain = print (factInt 25)",
      options: ["7034535277573963776", "15511210043330985984000000", L("An overflow error", "Un error de desbordamiento", "オーバーフローのエラー")],
      answer: 0,
      output: "7034535277573963776",
      check: { compiles: true, stdout: "7034535277573963776" },
      explain: L("25! needs 84 bits. Int has 64, so it wraps and prints a wrong number with no warning.", "25! necesita 84 bits. Int tiene 64, así que da la vuelta e imprime un número erróneo sin aviso.", "25! は 84 ビット必要。Int は 64 ビットなので、黙って間違った数になる。"),
      win: [{ t: "shake" }, { t: "print", text: "7034535277573963776" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "countdown :: Int -> [Int]\ncountdown 0 = [0]\ncountdown n = n : countdown (n - 1)\n\nmain = print (countdown 3)",
      options: ["[3,2,1,0]", "[0,1,2,3]", "[3,2,1]"],
      answer: 0,
      output: "[3,2,1,0]",
      check: { compiles: true, stdout: "[3,2,1,0]" },
      explain: L("Each step puts n at the front of the rest. The base case adds the final [0].", "Cada paso pone n al frente del resto. El caso base agrega el [0] final.", "毎回 n を先頭に置く。基底ケースが最後の [0] を足す。"),
      win: [{ t: "print", text: "[3,2,1,0]" }],
    },
    say(L(
      "A helper named go can carry an ACCUMULATOR: a running total that is already the answer when the base case is reached.",
      "Un ayudante llamado go puede llevar un ACUMULADOR: un total parcial que ya es la respuesta al llegar al caso base.",
      "go という補助関数は「アキュムレータ」を運べる。基底ケースに着いたとき、それが答えになっている。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "sumTo :: Int -> Int\nsumTo n = go 0 n\n  where\n    go acc 0 = acc\n    go acc k = go (acc + k) (k - 1)\n\nmain = print (sumTo 100)",
      options: ["5050", "100", "0"],
      answer: 0,
      output: "5050",
      check: { compiles: true, stdout: "5050" },
      explain: L("go adds k to acc and counts down. At k = 0, acc holds 100 + 99 + ... + 1 = 5050.", "go suma k a acc y cuenta hacia abajo. En k = 0, acc tiene 100 + 99 + ... + 1 = 5050.", "go は k を acc に足して数を減らす。k = 0 で acc は 100 + 99 + … + 1 = 5050。"),
      win: [{ t: "tag", actor: "hero", text: "acc", value: "5050" }, { t: "print", text: "5050" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "myMax :: [Int] -> Int\nmyMax [x] = x\nmyMax (x:xs) = max x (myMax xs)\n\nmain = print (myMax [3,9,2])",
      options: ["9", "3", "2"],
      answer: 0,
      output: "9",
      check: { compiles: true, stdout: "9" },
      explain: L("A one-item list is the base case. Each step keeps the bigger of x and the best of the rest.", "Una lista de un objeto es el caso base. Cada paso se queda con el mayor entre x y lo mejor del resto.", "1個のリストが基底ケース。毎回 x と残りの最大のうち大きい方を残す。"),
      win: [{ t: "print", text: "9" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "fib :: Int -> Int\nfib 0 = 0\nfib 1 = 1\nfib n = fib (n - 1) + fib (n - 2)\n\nmain = print (fib 10)",
      options: ["55", "89", "10"],
      answer: 0,
      output: "55",
      check: { compiles: true, stdout: "55" },
      explain: L("Two base cases, and each number is the sum of the two before: 0 1 1 2 3 5 8 13 21 34 55.", "Dos casos base, y cada número es la suma de los dos anteriores: 0 1 1 2 3 5 8 13 21 34 55.", "基底ケースは2つ。前の2つの和：0 1 1 2 3 5 8 13 21 34 55。"),
      win: [{ t: "print", text: "55" }],
    },
    {
      kind: "pick",
      prompt: L("No base case. What happens on fact 3?", "Sin caso base. ¿Qué pasa con fact 3?", "基底ケースなし。fact 3 はどうなる？"),
      code: "fact :: Integer -> Integer\nfact n = n * fact (n - 1)\n-- fact 3 = 3 * fact 2 = ... ___",
      options: [
        L("never stops: runs out of time or memory", "nunca para: se queda sin tiempo o memoria", "止まらない：時間かメモリが尽きる"),
        L("stops at 0 and gives 0", "se detiene en 0 y da 0", "0 で止まって 0 を返す"),
        L("GHC refuses to compile it", "GHC se niega a compilarlo", "GHC がコンパイルを拒否"),
      ],
      answer: 0,
      explain: L("It compiles, but fact keeps calling fact -1, -2, ... forever. The sandbox kills it.", "Compila, pero fact sigue llamando a fact -1, -2, ... para siempre. El sandbox lo mata.", "コンパイルはできるが、-1, -2, … と永遠に呼び続け、サンドボックスに止められる。"),
      win: [{ t: "say", actor: "enemy", text: L("Forever... ever...", "Siempre... siempre...", "永遠に…") }],
    },
    {
      kind: "order",
      prompt: L("Put len in order", "Ordena len", "len を正しい順に"),
      lines: ["len :: [a] -> Int", "len [] = 0", "len (_:xs) = 1 + len xs"],
      check: { compiles: true, stdout: "4", program: "len :: [a] -> Int\nlen [] = 0\nlen (_:xs) = 1 + len xs\n\nmain = print (len \"owls\")\n" },
      explain: L("Signature, then the base case, then the step that recurses on the rest.", "La firma, luego el caso base y después el paso que se llama con el resto.", "シグネチャ、基底ケース、残りで自分を呼ぶ式の順。"),
    },
    {
      kind: "run",
      prompt: L("Fix the count: it must print length: 4", "Arregla la cuenta: debe imprimir length: 4", "数え方を直して length: 4 と表示"),
      starter: "myLength :: [a] -> Int\nmyLength [] = 0\nmyLength (_:xs) = myLength xs\n\nmain :: IO ()\nmain = putStrLn (\"length: \" ++ show (myLength \"owls\"))\n",
      solution: "myLength :: [a] -> Int\nmyLength [] = 0\nmyLength (_:xs) = 1 + myLength xs\n\nmain :: IO ()\nmain = putStrLn (\"length: \" ++ show (myLength \"owls\"))\n",
      expect: "length: 4",
      fallback: ["=\\s*1\\s*\\+\\s*myLength\\s+xs", "=\\s*myLength\\s+xs\\s*\\+\\s*1"],
      explain: L("The step forgot to count the item it removed. Add 1 + before myLength xs.", "El paso olvidó contar el objeto que quitó. Agrega 1 + antes de myLength xs.", "取り除いた1個を数え忘れている。myLength xs の前に 1 + を。"),
    },
  ],
};

// ─── 2.2 Allies on the conveyor ────────────────────────────────────────────
const higherOrder: LessonDef = {
  slug: "higher-order-functions",
  title: L("Allies on the conveyor", "Aliados en la cinta", "ベルトコンベアの仲間"),
  concept: "higher-order",
  mode: "lesson",
  xp: 65,
  enemy: "slime",
  enemyName: L("CONVEYOR SLIME", "SLIME DE CINTA", "コンベアスライム"),
  beats: [
    say(L(
      "Functions are values too: you can hand one to another function. map applies a function to EVERY item of a list.",
      "Las funciones también son valores: puedes pasarle una a otra función. map aplica una función a CADA objeto de una lista.",
      "関数も値。別の関数に渡せる。map はリストの全部の要素に関数を適用する。",
    )),
    {
      kind: "act",
      prompt: L("Run the gems down the conveyor", "Pasa las gemas por la cinta", "宝石をコンベアに流そう"),
      steps: [
        { label: L("LAMBDA", "LAMBDA", "ラムダ"), line: "let double = \\x -> x * 2", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "double", value: "\\x -> x * 2" }] },
        { label: L("MAP", "MAP", "map"), line: "print (map double [1,2,3])", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "print", text: "[2,4,6]" }], output: "[2,4,6]" },
        { label: L("FILTER", "FILTER", "filter"), line: "print (filter even [1..6])", effects: [{ t: "banner", text: L("odd ones drop", "caen los impares", "奇数は落ちる") }, { t: "print", text: "[2,4,6]" }], output: "[2,4,6]" },
        { label: L("ZIPWITH", "ZIPWITH", "zipWith"), line: "print (zipWith (+) [1,2] [10,20])", effects: [{ t: "print", text: "[11,22]" }], output: "[11,22]" },
      ],
    },
    say(L(
      "\\x -> x * 2 is a LAMBDA: a function with no name. The backslash stands for the Greek letter λ.",
      "\\x -> x * 2 es una LAMBDA: una función sin nombre. La barra invertida representa la letra griega λ.",
      "\\x -> x * 2 は「ラムダ」、名前のない関数。バックスラッシュはギリシャ文字 λ のかわり。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (map (\\x -> x * 2) [1,2,3])",
      options: ["[2,4,6]", "[1,2,3,1,2,3]", "12"],
      answer: 0,
      output: "[2,4,6]",
      check: { compiles: true, stdout: "[2,4,6]" },
      explain: L("map gives each item to the lambda and collects the results in a new list.", "map le da cada objeto a la lambda y junta los resultados en una lista nueva.", "map は各要素をラムダに渡し、結果を新しいリストに集める。"),
      win: [{ t: "print", text: "[2,4,6]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (filter even [1..10])",
      options: ["[2,4,6,8,10]", "[1,3,5,7,9]", "5"],
      answer: 0,
      output: "[2,4,6,8,10]",
      check: { compiles: true, stdout: "[2,4,6,8,10]" },
      explain: L("filter keeps only the items for which the test (even) says True.", "filter deja solo los objetos para los que la prueba (even) dice True.", "filter は判定（even）が True の要素だけ残す。"),
      win: [{ t: "print", text: "[2,4,6,8,10]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (zipWith (+) [1,2,3] [10,20,30])",
      options: ["[11,22,33]", "[1,2,3,10,20,30]", "66"],
      answer: 0,
      output: "[11,22,33]",
      check: { compiles: true, stdout: "[11,22,33]" },
      explain: L("zipWith walks both lists side by side and combines each pair with (+).", "zipWith recorre ambas listas a la par y combina cada pareja con (+).", "zipWith は2つのリストを並んで歩き、ペアを (+) でまとめる。"),
      win: [{ t: "print", text: "[11,22,33]" }],
    },
    say(L(
      "takeWhile keeps items while the test holds and stops at the FIRST failure. dropWhile skips those same items.",
      "takeWhile toma objetos mientras la prueba se cumple y para en el PRIMER fallo. dropWhile salta esos mismos objetos.",
      "takeWhile は条件が成り立つ間だけ取り、最初に外れたら止まる。dropWhile はその分を飛ばす。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (takeWhile (\\x -> x < 5) [1,3,5,2])\nprint (dropWhile (\\x -> x < 5) [1,3,5,2])",
      options: ["[1,3]\n[5,2]", "[1,3,2]\n[5]", "[1,3]\n[5]"],
      answer: 0,
      output: "[1,3]\n[5,2]",
      check: { compiles: true, stdout: "[1,3]\n[5,2]" },
      explain: L("It stops at 5, the first failure. The 2 after it is never tested.", "Se detiene en 5, el primer fallo. El 2 que sigue nunca se prueba.", "最初に外れる 5 で止まる。その後の 2 は調べない。"),
      win: [{ t: "print", text: "[1,3]" }, { t: "print", text: "[5,2]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (any even [1,3,5], all odd [1,3,5])",
      options: ["(False,True)", "(True,True)", "(False,False)"],
      answer: 0,
      output: "(False,True)",
      check: { compiles: true, stdout: "(False,True)" },
      explain: L("No item is even, so any gives False. Every item is odd, so all gives True.", "Ningún objeto es par, así que any da False. Todos son impares, así que all da True.", "偶数がないので any は False。全部奇数なので all は True。"),
      win: [{ t: "print", text: "(False,True)" }],
    },
    say(L(
      "You can write your own! In a signature, (a -> a) in parentheses means 'this argument is a function'.",
      "¡Puedes escribir las tuyas! En una firma, (a -> a) entre paréntesis significa 'este argumento es una función'.",
      "自分でも作れる！シグネチャのかっこ付き (a -> a) は「この引数は関数」という意味。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "applyTwice :: (a -> a) -> a -> a\napplyTwice f x = f (f x)\n\nmain = print (applyTwice (\\x -> x + 3) 10, applyTwice reverse \"abc\")",
      options: ["(16,\"abc\")", "(13,\"cba\")", "(16,\"cba\")"],
      answer: 0,
      output: "(16,\"abc\")",
      check: { compiles: true, stdout: "(16,\"abc\")" },
      explain: L("f runs twice: 10 + 3 + 3 = 16, and reversing twice gives back \"abc\".", "f corre dos veces: 10 + 3 + 3 = 16, e invertir dos veces devuelve \"abc\".", "f を2回：10 + 3 + 3 = 16。2回 reverse すると \"abc\" に戻る。"),
      win: [{ t: "print", text: "(16,\"abc\")" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (filter (\\(k, v) -> v > 1) [('a',1),('b',2)])",
      options: ["[('b',2)]", "[('a',1)]", "\"b\""],
      answer: 0,
      output: "[('b',2)]",
      check: { compiles: true, stdout: "[('b',2)]" },
      explain: L("A lambda can take a pair apart with a pattern. Only ('b',2) has v > 1.", "Una lambda puede separar un par con un patrón. Solo ('b',2) tiene v > 1.", "ラムダもパターンでペアを分けられる。v > 1 は ('b',2) だけ。"),
      win: [{ t: "print", text: "[('b',2)]" }],
    },
    {
      kind: "pick",
      prompt: L("Which type fits map?", "¿Qué tipo le va a map?", "map に合う型は？"),
      code: "myMap :: ___\nmyMap = map\n\nmain = print (myMap (+1) [1,2])",
      options: ["(a -> b) -> [a] -> [b]", "a -> b -> [a]", "[a] -> (a -> b) -> b"],
      answer: 0,
      check: { compiles: true, stdout: "[2,3]", wrongFail: true },
      explain: L("map takes a function from a to b, then a list of a, and gives a list of b.", "map recibe una función de a a b, luego una lista de a, y da una lista de b.", "map は a から b への関数と a のリストを受け取り、b のリストを返す。"),
      win: [{ t: "print", text: "[2,3]" }],
    },
    {
      kind: "type",
      prompt: L("Keep the odd ones: [1,3]", "Deja los impares: [1,3]", "奇数だけ残す：[1,3]"),
      code: "print (___ odd [1,2,3])",
      answer: "filter",
      check: { compiles: true, stdout: "[1,3]" },
      explain: L("filter odd keeps the items where odd says True.", "filter odd deja los objetos donde odd dice True.", "filter odd は odd が True の要素を残す。"),
      win: [{ t: "print", text: "[1,3]" }],
    },
    {
      kind: "run",
      prompt: L("Double every score: it must print [6,14,20]", "Duplica cada puntaje: debe imprimir [6,14,20]", "全部の点を2倍に：[6,14,20] と表示"),
      starter: "main :: IO ()\nmain = print (map (\\s -> s + 2) [3, 7, 10])\n",
      solution: "main :: IO ()\nmain = print (map (\\s -> s * 2) [3, 7, 10])\n",
      expect: "[6,14,20]",
      fallback: ["\\\\s\\s*->\\s*s\\s*\\*\\s*2", "\\\\s\\s*->\\s*2\\s*\\*\\s*s", "\\\\s\\s*->\\s*s\\s*\\+\\s*s", "map\\s*\\(\\*\\s*2\\)", "map\\s*\\(2\\s*\\*\\)"],
      explain: L("The lambda adds 2. Make it multiply: \\s -> s * 2.", "La lambda suma 2. Haz que multiplique: \\s -> s * 2.", "ラムダが 2 を足している。かけ算に：\\s -> s * 2。"),
    },
  ],
};

// ─── 2.3 Half-cast spells ───────────────────────────────────────────────────
const currying: LessonDef = {
  slug: "currying-and-composition",
  title: L("Half-cast spells", "Hechizos a medias", "半分だけの呪文"),
  concept: "currying",
  mode: "lesson",
  xp: 70,
  enemy: "golem",
  enemyName: L("GLUE GOLEM", "GÓLEM PEGAMENTO", "のりゴーレム"),
  beats: [
    say(L(
      "A secret: every Haskell function takes ONE argument. add 5 is a new function, waiting for the next number.",
      "Un secreto: toda función de Haskell recibe UN argumento. add 5 es una función nueva que espera el siguiente número.",
      "秘密：Haskell の関数は引数をひとつだけ取る。add 5 は次の数を待つ新しい関数なんだ。",
    )),
    {
      kind: "act",
      prompt: L("Cast the spell in two halves", "Lanza el hechizo en dos mitades", "呪文を半分ずつかけよう"),
      steps: [
        { label: L("ADD", "ADD", "add"), line: "add x y = x + y", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "add", value: "Int -> Int -> Int" }] },
        { label: L("HALF: add 5", "MITAD: add 5", "半分：add 5"), line: "let add5 = add 5", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "tag", actor: "ally", text: "add5", value: "Int -> Int" }, { t: "say", actor: "ally", text: L("Waiting for y...", "Espero a y...", "y を待ってる…") }] },
        { label: L("FINISH", "TERMINAR", "完成"), line: "print (add5 10)", effects: [{ t: "print", text: "15" }], output: "15" },
        {
          label: L("TOO MANY", "DEMASIADOS", "引数が多い"),
          line: "print length [1,2,3]",
          effects: [{ t: "shake" }],
          error: {
            compiler: "The function `print' is applied to two value arguments,\n    but its type `(t0 a0 -> Int) -> IO ()' has only one",
            plain: L("print gets length AND the list: two arguments. Group them: print (length [1,2,3]).", "print recibe length Y la lista: dos argumentos. Agrúpalos: print (length [1,2,3]).", "print に length とリストの2つが渡っている。print (length [1,2,3]) とまとめよう。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "add :: Int -> Int -> Int\nadd x y = x + y\n\nmain = do\n  let add5 = add 5\n  print (add5 10)",
      options: ["15", "5", NO_COMPILE],
      answer: 0,
      output: "15",
      check: { compiles: true, stdout: "15" },
      explain: L("add 5 is a function still waiting for y. Giving it 10 finishes the job: 15.", "add 5 es una función que aún espera a y. Darle 10 termina el trabajo: 15.", "add 5 は y を待つ関数。10 を渡すと完成して 15。"),
      win: [{ t: "print", text: "15" }],
    },
    say(L(
      "Operators can be half-cast too, with a SECTION: (2^) fills the LEFT side, (^2) fills the RIGHT side.",
      "Los operadores también se lanzan a medias con una SECCIÓN: (2^) llena el lado IZQUIERDO, (^2) el DERECHO.",
      "演算子も「セクション」で半分だけ使える。(2^) は左側、(^2) は右側を埋める。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (map (2^) [1,2,3])\nprint (map (^2) [1,2,3])",
      options: ["[2,4,8]\n[1,4,9]", "[1,4,9]\n[2,4,8]", "[2,4,8]\n[2,4,8]"],
      answer: 0,
      output: "[2,4,8]\n[1,4,9]",
      check: { compiles: true, stdout: "[2,4,8]\n[1,4,9]" },
      explain: L("(2^) x is 2 ^ x (powers of two). (^2) x is x ^ 2 (squares).", "(2^) x es 2 ^ x (potencias de dos). (^2) x es x ^ 2 (cuadrados).", "(2^) x は 2 ^ x（2のべき乗）、(^2) x は x ^ 2（2乗）。"),
      win: [{ t: "print", text: "[2,4,8]" }, { t: "print", text: "[1,4,9]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((/ 2) 10, (2 /) 10)",
      options: ["(5.0,0.2)", "(0.2,5.0)", "(5.0,5.0)"],
      answer: 0,
      output: "(5.0,0.2)",
      check: { compiles: true, stdout: "(5.0,0.2)" },
      explain: L("(/ 2) 10 is 10 / 2. (2 /) 10 is 2 / 10. The side you fill matters.", "(/ 2) 10 es 10 / 2. (2 /) 10 es 2 / 10. Importa qué lado llenas.", "(/ 2) 10 は 10 / 2、(2 /) 10 は 2 / 10。どちら側を埋めるかが大事。"),
      win: [{ t: "print", text: "(5.0,0.2)" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (map (-1) [1,2,3])",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("(-1) is just the number minus one, not a function. Write subtract 1 instead.", "(-1) es solo el número menos uno, no una función. Escribe subtract 1.", "(-1) はただの数 -1 で関数じゃない。subtract 1 と書こう。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "f . g glues two functions: g runs FIRST, then f. $ means 'everything on my right first' and saves parentheses.",
      "f . g pega dos funciones: g corre PRIMERO y luego f. $ significa 'primero todo lo de mi derecha' y ahorra paréntesis.",
      "f . g は2つの関数をつなぐ。g が先、次に f。$ は「右側を全部先に」の意味で、かっこを減らせる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((negate . abs) (-5), (show . (+1)) 41)",
      options: ["(-5,\"42\")", "(5,\"42\")", "(-5,42)"],
      answer: 0,
      output: "(-5,\"42\")",
      check: { compiles: true, stdout: "(-5,\"42\")" },
      explain: L("Right to left: abs gives 5, then negate gives -5. (+1) gives 42, then show makes it text.", "De derecha a izquierda: abs da 5 y negate da -5. (+1) da 42 y show lo vuelve texto.", "右から左：abs で 5、negate で -5。(+1) で 42、show で文字列に。"),
      win: [{ t: "print", text: "(-5,\"42\")" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print $ sum $ map (*2) [1,2,3]",
      options: ["12", "6", "[2,4,6]"],
      answer: 0,
      output: "12",
      check: { compiles: true, stdout: "12" },
      explain: L("Read from the right: map doubles to [2,4,6], sum gives 12, print shows it.", "Lee desde la derecha: map duplica a [2,4,6], sum da 12 y print lo muestra.", "右から読む：map で [2,4,6]、sum で 12、print で表示。"),
      win: [{ t: "print", text: "12" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "processBad = filter odd . map (*2)\nprocessGood = map (*2) . filter odd\n\nmain = print (processBad [1..5], processGood [1..5])",
      options: ["([],[2,6,10])", "([2,6,10],[2,6,10])", "([2,6,10],[])"],
      answer: 0,
      output: "([],[2,6,10])",
      check: { compiles: true, stdout: "([],[2,6,10])" },
      explain: L("processBad doubles first, so everything is even and filter odd removes it all.", "processBad duplica primero, así que todo es par y filter odd lo quita todo.", "processBad は先に2倍するので全部偶数。filter odd で全部消える。"),
      win: [{ t: "print", text: "([],[2,6,10])" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (length . filter even [1..10])",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("filter even [1..10] is already a list, not a function, so . can't glue it. Use $ before the list.", "filter even [1..10] ya es una lista, no una función, así que . no puede pegarla. Usa $ antes de la lista.", "filter even [1..10] はもうリストで関数じゃない。. ではつなげない。リストの前に $ を。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Save the parentheses: it prints 6", "Ahorra paréntesis: imprime 6", "かっこを省いて 6 と表示"),
      code: "print ___ sum [1,2,3]",
      answer: "$",
      check: { compiles: true, stdout: "6" },
      explain: L("$ makes sum [1,2,3] happen first, then print gets the result.", "$ hace que sum [1,2,3] ocurra primero, y luego print recibe el resultado.", "$ で sum [1,2,3] が先に計算され、print に結果が渡る。"),
      win: [{ t: "print", text: "6" }],
    },
    {
      kind: "run",
      prompt: L("Keep the odd ones, THEN double: [2,6,10]", "Deja los impares y LUEGO duplica: [2,6,10]", "奇数を残してから2倍：[2,6,10]"),
      starter: "process :: [Int] -> [Int]\nprocess = filter odd . map (*2)\n\nmain :: IO ()\nmain = print (process [1, 2, 3, 4, 5])\n",
      solution: "process :: [Int] -> [Int]\nprocess = map (*2) . filter odd\n\nmain :: IO ()\nmain = print (process [1, 2, 3, 4, 5])\n",
      expect: "[2,6,10]",
      fallback: ["map\\s*\\(\\*\\s*2\\)\\s*\\.\\s*filter\\s+odd", "map\\s*\\(2\\s*\\*\\)\\s*\\.\\s*filter\\s+odd"],
      explain: L("Composition runs right to left. Put filter odd on the right so it runs first.", "La composición corre de derecha a izquierda. Pon filter odd a la derecha para que corra primero.", "合成は右から左。filter odd を右に置いて先に動かそう。"),
    },
  ],
};

// ─── 2.4 Melting the row into one gem ──────────────────────────────────────
const folds: LessonDef = {
  slug: "folds",
  title: L("Melt the row into one gem", "Funde la fila en una gema", "列を溶かしてひとつに"),
  concept: "folds",
  mode: "lesson",
  xp: 75,
  enemy: "dragon",
  enemyName: L("FURNACE DRAGON", "DRAGÓN HORNO", "るつぼドラゴン"),
  beats: [
    say(L(
      "A FOLD melts a whole list into one value. foldr f z swaps each : for f and the empty end [] for z.",
      "Un FOLD funde una lista entera en un solo valor. foldr f z cambia cada : por f y el final vacío [] por z.",
      "畳み込み（fold）はリストをひとつの値に溶かす。foldr f z は各 : を f に、最後の [] を z に置きかえる。",
    )),
    {
      kind: "act",
      prompt: L("Melt the gems from both sides", "Funde las gemas desde ambos lados", "両側から宝石を溶かそう"),
      steps: [
        { label: L("ROW", "FILA", "列"), line: "let gems = [1,2,3]", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "gems", value: "[1,2,3]" }] },
        { label: L("FOLDR +", "FOLDR +", "foldr +"), line: "print (foldr (+) 0 gems)", effects: [{ t: "banner", text: L("1+(2+(3+0))", "1+(2+(3+0))", "1+(2+(3+0))") }, { t: "print", text: "6" }], output: "6" },
        { label: L("FOLDL -", "FOLDL -", "foldl -"), line: "print (foldl (-) 0 gems)", effects: [{ t: "banner", text: L("((0-1)-2)-3", "((0-1)-2)-3", "((0-1)-2)-3") }, { t: "print", text: "-6" }], output: "-6" },
        {
          label: L("FOLDL' ?", "FOLDL' ?", "foldl' ?"),
          line: "print (foldl' (+) 0 gems)",
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Who is foldl'?", "¿Quién es foldl'?", "foldl' って誰？") }],
          error: {
            compiler: "Variable not in scope:\n      foldl' :: (a0 -> a0 -> a0) -> t0 -> [a1] -> a2",
            plain: L("In GHC 9.8, foldl' lives in Data.List. Add: import Data.List (foldl').", "En GHC 9.8, foldl' vive en Data.List. Agrega: import Data.List (foldl').", "GHC 9.8 では foldl' は Data.List にある。import Data.List (foldl') を足そう。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (foldr (+) 0 [1,2,3])",
      options: ["6", "0", "123"],
      answer: 0,
      output: "6",
      check: { compiles: true, stdout: "6" },
      explain: L("foldr turns 1 : 2 : 3 : [] into 1 + (2 + (3 + 0)) = 6.", "foldr convierte 1 : 2 : 3 : [] en 1 + (2 + (3 + 0)) = 6.", "foldr は 1 : 2 : 3 : [] を 1 + (2 + (3 + 0)) = 6 に変える。"),
      win: [{ t: "print", text: "6" }],
    },
    say(L(
      "foldr groups from the right: 1-(2-(3-0)). foldl groups from the left: ((0-1)-2)-3. With - the answers differ!",
      "foldr agrupa desde la derecha: 1-(2-(3-0)). foldl desde la izquierda: ((0-1)-2)-3. ¡Con - las respuestas cambian!",
      "foldr は右からまとめる：1-(2-(3-0))。foldl は左から：((0-1)-2)-3。- だと答えが変わる！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (foldr (-) 0 [1,2,3], foldl (-) 0 [1,2,3])",
      options: ["(2,-6)", "(-6,2)", "(-6,-6)"],
      answer: 0,
      output: "(2,-6)",
      check: { compiles: true, stdout: "(2,-6)" },
      explain: L("1-(2-(3-0)) = 1-(2-3) = 2, while ((0-1)-2)-3 = -6.", "1-(2-(3-0)) = 1-(2-3) = 2, mientras que ((0-1)-2)-3 = -6.", "1-(2-(3-0)) = 1-(2-3) = 2、((0-1)-2)-3 = -6。"),
      win: [{ t: "print", text: "(2,-6)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (foldr (\\x acc -> \"(\" ++ show x ++ \"+\" ++ acc ++ \")\") \"0\" [1,2,3])",
      options: ["\"(1+(2+(3+0)))\"", "\"(((0+1)+2)+3)\"", "\"(3+(2+(1+0)))\""],
      answer: 0,
      output: "\"(1+(2+(3+0)))\"",
      check: { compiles: true, stdout: "\"(1+(2+(3+0)))\"" },
      explain: L("foldr's function gets the item x and the already-melted rest acc, so brackets nest to the right.", "La función de foldr recibe el objeto x y el resto ya fundido acc, así que los paréntesis se anidan a la derecha.", "foldr の関数は要素 x と、溶かし済みの残り acc を受け取る。かっこは右に入れ子になる。"),
      win: [{ t: "print", text: "\"(1+(2+(3+0)))\"" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (foldl (\\acc x -> x : acc) [] \"abc\")\nprint (foldr (\\x acc -> x : acc) [] \"abc\")",
      options: ["\"cba\"\n\"abc\"", "\"abc\"\n\"cba\"", "\"abc\"\n\"abc\""],
      answer: 0,
      output: "\"cba\"\n\"abc\"",
      check: { compiles: true, stdout: "\"cba\"\n\"abc\"" },
      explain: L("foldl meets 'a' first and pushes each letter to the front: reversed. foldr rebuilds the list as it was.", "foldl ve 'a' primero y empuja cada letra al frente: queda invertido. foldr reconstruye la lista igual.", "foldl は 'a' から順に先頭へ積むので逆順。foldr は元どおりに組み直す。"),
      win: [{ t: "print", text: "\"cba\"" }, { t: "print", text: "\"abc\"" }],
    },
    say(L(
      "Plain foldl delays every step as a sealed box, a THUNK. Huge lists pile them up. foldl' opens each box at once.",
      "foldl normal aplaza cada paso como una caja sellada, un THUNK. Las listas enormes las apilan. foldl' abre cada caja al instante.",
      "ふつうの foldl は各ステップを封をした箱「サンク」として後回しにする。巨大なリストだと山になる。foldl' はすぐ開ける。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (foldl' (+) 0 [1..10])",
      options: [YES, L("No: foldl' is not in scope", "No: foldl' no está en alcance", "いいえ：foldl' が見つからない")],
      answer: 1,
      check: { compiles: false },
      explain: L("GHC 9.8's Prelude has no foldl'. It needs import Data.List (foldl') at the top.", "El Prelude de GHC 9.8 no trae foldl'. Hace falta import Data.List (foldl') arriba.", "GHC 9.8 の Prelude に foldl' はない。先頭に import Data.List (foldl') が必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "import Data.List (foldl')\n\nmain = print (foldl' (+) 0 [1..1000000])",
      options: ["500000500000", "1000000", NO_COMPILE],
      answer: 0,
      output: "500000500000",
      check: { compiles: true, stdout: "500000500000" },
      explain: L("With the import, foldl' adds a million numbers, opening every box right away.", "Con el import, foldl' suma un millón de números abriendo cada caja enseguida.", "import すれば foldl' が箱をすぐ開けながら百万個を足す。"),
      win: [{ t: "print", text: "500000500000" }, { t: "say", actor: "enemy", text: L("No pile?!", "¿¡Sin pila!?", "山がない？！") }],
    },
    say(L(
      "scanl is a fold that shows every step it took. Folds of an empty list just give the starting value.",
      "scanl es un fold que muestra cada paso que dio. El fold de una lista vacía solo da el valor inicial.",
      "scanl は途中経過を全部見せる fold。空リストの fold は初期値だけを返す。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (scanl (+) 0 [1,2,3])",
      options: ["[0,1,3,6]", "[1,3,6]", "6"],
      answer: 0,
      output: "[0,1,3,6]",
      check: { compiles: true, stdout: "[0,1,3,6]" },
      explain: L("Start at 0, then 0+1, then 1+2, then 3+3: every running total is kept.", "Empieza en 0, luego 0+1, luego 1+2, luego 3+3: se guarda cada total parcial.", "0 から始めて 0+1、1+2、3+3。途中の合計を全部残す。"),
      win: [{ t: "print", text: "[0,1,3,6]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (sum [], product [], and [], or [])",
      options: ["(0,1,True,False)", "(0,0,False,False)", "(0,1,False,True)"],
      answer: 0,
      output: "(0,1,True,False)",
      check: { compiles: true, stdout: "(0,1,True,False)" },
      explain: L("Each is a fold that returns its start value on []: 0 for +, 1 for *, True for &&, False for ||.", "Cada uno es un fold que da su valor inicial con []: 0 para +, 1 para *, True para &&, False para ||.", "どれも [] では初期値を返す fold：+ は 0、* は 1、&& は True、|| は False。"),
      win: [{ t: "print", text: "(0,1,True,False)" }],
    },
    {
      kind: "pick",
      prompt: L("foldl (+) on 10 million numbers blows memory. Fix?", "foldl (+) con 10 millones agota la memoria. ¿Solución?", "1千万個の foldl (+) でメモリ不足。対策は？"),
      code: "import Data.List (foldl')\n\nmain = print (___ (+) 0 [1..10])",
      options: ["foldl'", "foldr1", "foldl"],
      answer: 0,
      check: { compiles: true, stdout: "55" },
      explain: L("foldl' forces the running total at every step, so no thunk pile ever forms.", "foldl' fuerza el total parcial en cada paso, así que nunca se forma una pila de thunks.", "foldl' は毎回途中の合計を計算するので、サンクの山ができない。"),
      win: [{ t: "print", text: "55" }],
    },
    {
      kind: "type",
      prompt: L("Import the strict fold", "Importa el fold estricto", "正格な fold を import"),
      code: "import Data.List (___)\n\nmain = print (foldl' (+) 0 [1,2,3])",
      answer: "foldl'",
      check: { compiles: true, stdout: "6" },
      explain: L("import Data.List (foldl') brings just foldl' into scope.", "import Data.List (foldl') trae solo foldl' al alcance.", "import Data.List (foldl') で foldl' だけを使えるようにする。"),
      win: [{ t: "print", text: "6" }],
    },
    {
      kind: "run",
      prompt: L("Build the number 427 from [4, 2, 7]", "Arma el número 427 a partir de [4, 2, 7]", "[4, 2, 7] から 427 を作ろう"),
      starter: "main :: IO ()\nmain = putStrLn (\"number: \" ++ show (foldr (\\d acc -> acc * 10 + d) 0 [4, 2, 7]))\n",
      solution: "main :: IO ()\nmain = putStrLn (\"number: \" ++ show (foldl (\\acc d -> acc * 10 + d) 0 [4, 2, 7]))\n",
      expect: "number: 427",
      fallback: ["foldl'?\\s*\\(\\\\acc\\s+d\\s*->\\s*acc\\s*\\*\\s*10\\s*\\+\\s*d\\)", "foldl'?\\s*\\(\\\\(\\w+)\\s+(\\w+)\\s*->\\s*\\1\\s*\\*\\s*10\\s*\\+\\s*\\2\\)"],
      explain: L("foldr starts melting from the right end, giving 724. foldl starts from the left: 427.", "foldr empieza a fundir desde la derecha y da 724. foldl empieza por la izquierda: 427.", "foldr は右端から溶かすので 724。foldl は左からで 427。"),
    },
  ],
};

// ─── BOSS · The Thunk Pile ──────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "forest-boss",
  title: L("The Thunk Pile", "La Pila de Thunks", "サンクの山"),
  concept: "folds",
  mode: "boss",
  xp: 180,
  enemy: "haskell/thunk-pile",
  enemyName: L("THUNK PILE", "PILA DE THUNKS", "サンクパイル"),
  beats: [
    enemySays(L(
      "Rumble... I am the THUNK PILE, every step you put off for later. Fold me wrong and I grow until the forest bursts!",
      "Retumbo... Soy la PILA DE THUNKS, cada paso que dejas para después. ¡Pliégame mal y creceré hasta reventar el bosque!",
      "ゴゴゴ…我はサンクパイル、後回しにされた計算の山。まちがった fold で森ごと膨れあがるぞ！",
    )),
    {
      kind: "predict", time: 20, prompt: PRINT,
      code: "print (foldr (\\x acc -> x + 10 * acc) 0 [1,2,3])\nprint (foldl (\\acc x -> acc * 10 + x) 0 [1,2,3])",
      options: ["321\n123", "123\n321", "123\n123"],
      answer: 0,
      output: "321\n123",
      check: { compiles: true, stdout: "321\n123" },
      explain: L("foldr: 1 + 10 * (2 + 10 * (3 + 0)) = 321. foldl: ((0*10+1)*10+2)*10+3 = 123.", "foldr: 1 + 10 * (2 + 10 * (3 + 0)) = 321. foldl: ((0*10+1)*10+2)*10+3 = 123.", "foldr：1 + 10 * (2 + 10 * (3 + 0)) = 321。foldl：((0*10+1)*10+2)*10+3 = 123。"),
      win: [{ t: "attack", from: "hero", to: "enemy" }, { t: "print", text: "321" }, { t: "print", text: "123" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print (foldl (-) 10 [1,2,3])",
      options: ["4", "-4", "2"],
      answer: 0,
      output: "4",
      check: { compiles: true, stdout: "4" },
      explain: L("foldl starts with 10 on the left: ((10-1)-2)-3 = 4.", "foldl empieza con 10 a la izquierda: ((10-1)-2)-3 = 4.", "foldl は左の 10 から：((10-1)-2)-3 = 4。"),
      win: [{ t: "print", text: "4" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print (scanl max 0 [3,1,4,1,5])",
      options: ["[0,3,3,4,4,5]", "[3,1,4,1,5]", "[0,3,1,4,1,5]"],
      answer: 0,
      output: "[0,3,3,4,4,5]",
      check: { compiles: true, stdout: "[0,3,3,4,4,5]" },
      explain: L("scanl keeps the running result: the biggest value seen so far at each step.", "scanl guarda el resultado parcial: el mayor valor visto hasta cada paso.", "scanl は途中結果を残す：その時点までの最大値。"),
      win: [{ t: "print", text: "[0,3,3,4,4,5]" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print (zipWith (*) [1,2,3] [4,5,6])",
      options: ["[4,10,18]", "32", "[5,7,9]"],
      answer: 0,
      output: "[4,10,18]",
      check: { compiles: true, stdout: "[4,10,18]" },
      explain: L("zipWith (*) multiplies the pairs: 1*4, 2*5, 3*6.", "zipWith (*) multiplica las parejas: 1*4, 2*5, 3*6.", "zipWith (*) はペアをかける：1*4、2*5、3*6。"),
      win: [{ t: "print", text: "[4,10,18]" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print ((+) 2 3, ((+1) . (*2)) 5)",
      options: ["(5,11)", "(5,12)", "(6,11)"],
      answer: 0,
      output: "(5,11)",
      check: { compiles: true, stdout: "(5,11)" },
      explain: L("(+) in parentheses is a normal function: 2 + 3. Then (*2) runs first: 10 + 1 = 11.", "(+) entre paréntesis es una función normal: 2 + 3. Luego (*2) corre primero: 10 + 1 = 11.", "かっこ付き (+) はふつうの関数：2 + 3。(*2) が先で 10 + 1 = 11。"),
      win: [{ t: "print", text: "(5,11)" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print ((map (+1) . filter even) [1..6])",
      options: ["[3,5,7]", "[2,4,6]", "[2,3,4,5,6,7]"],
      answer: 0,
      output: "[3,5,7]",
      check: { compiles: true, stdout: "[3,5,7]" },
      explain: L("Right to left: filter even keeps [2,4,6], then map (+1) gives [3,5,7].", "De derecha a izquierda: filter even deja [2,4,6] y map (+1) da [3,5,7].", "右から左：filter even で [2,4,6]、map (+1) で [3,5,7]。"),
      win: [{ t: "print", text: "[3,5,7]" }],
    },
    {
      kind: "predict", time: 15, prompt: COMPILES,
      code: "print (map (-2) [5,6])",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("(-2) is the number minus two, not a section. map needs a function: subtract 2.", "(-2) es el número menos dos, no una sección. map necesita una función: subtract 2.", "(-2) は数でセクションじゃない。map には関数が必要：subtract 2。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "print (length . filter even $ [1..10])",
      options: ["5", "10", NO_COMPILE],
      answer: 0,
      output: "5",
      check: { compiles: true, stdout: "5" },
      explain: L("$ hands the whole list to the glued function length . filter even: 5 even numbers.", "$ le pasa la lista entera a la función pegada length . filter even: 5 pares.", "$ がリストを合成関数 length . filter even に渡す。偶数は 5 個。"),
      win: [{ t: "print", text: "5" }],
    },
    {
      kind: "predict", time: 20, prompt: PRINT,
      code: "productOf :: [Integer] -> Integer\nproductOf xs = go 1 xs\n  where\n    go acc [] = acc\n    go acc (y:ys) = go (acc * y) ys\n\nmain = print (productOf [1..20])",
      options: ["2432902008176640000", "210", "20"],
      answer: 0,
      output: "2432902008176640000",
      check: { compiles: true, stdout: "2432902008176640000" },
      explain: L("go multiplies acc by each item; at [] acc holds 20! as an exact Integer.", "go multiplica acc por cada objeto; en [] acc tiene 20! como Integer exacto.", "go が acc に要素をかけていき、[] で acc は 20! の正確な Integer。"),
      win: [{ t: "tag", actor: "hero", text: "acc", value: "20!" }, { t: "print", text: "2432902008176640000" }],
    },
    {
      kind: "pick", time: 15,
      prompt: L("Bring foldl' in to crush the pile", "Trae foldl' para aplastar la pila", "foldl' を呼んで山をつぶせ"),
      code: "___ Data.List (foldl')\n\nmain = print (foldl' (+) 0 [1..100])",
      options: ["import", "include", "using"],
      answer: 0,
      check: { compiles: true, stdout: "5050", wrongFail: true },
      explain: L("Haskell brings modules in with import at the top of the file.", "Haskell trae módulos con import al inicio del archivo.", "Haskell ではファイルの先頭で import してモジュールを使う。"),
      win: [{ t: "print", text: "5050" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "type", time: 15,
      prompt: L("Take one from each: [4,5]", "Resta uno a cada uno: [4,5]", "ひとつずつ減らす：[4,5]"),
      code: "print (map (___ 1) [5,6])",
      answer: "subtract",
      check: { compiles: true, stdout: "[4,5]" },
      explain: L("subtract 1 is a function waiting for a number; (-1) would just be a number.", "subtract 1 es una función que espera un número; (-1) sería solo un número.", "subtract 1 は数を待つ関数。(-1) はただの数。"),
      win: [{ t: "print", text: "[4,5]" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    enemySays(L(
      "Crumble... every box opened at once. But on Lazy Mountain, boxes wait forever, and something hides inside them...",
      "Derrumbe... todas las cajas abiertas al instante. Pero en la Montaña Perezosa las cajas esperan para siempre, y algo se esconde dentro...",
      "ガラガラ…箱が全部すぐ開けられた。だが怠惰の山では箱は永遠に待ち、中に何かがひそんでいる…",
    )),
  ],
};

export const foldForest: RegionDef = {
  slug: "fold-forest",
  name: L("Fold Forest", "Bosque Fold", "フォールドの森"),
  subtitle: L("recursion · map · composition · folds", "recursión · map · composición · folds", "再帰・map・合成・fold"),
  theme: "forest",
  lessons: [recursion, higherOrder, currying, folds, boss],
};
