import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { L, say, enemySays } from "../../rust/helpers.ts";

// REGION 1 · LAMBDA VILLAGE  (expressions, immutability, types, lists and strings, patterns and guards)

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const YES = L("Yes", "Sí", "はい");
const NO_GHC = L("No: GHC stops it", "No: GHC lo detiene", "いいえ：GHC が止める");
const NO_COMPILE = L("Compile error", "Error de compilación", "コンパイルエラー");

// ─── 1.1 Everything is an expression ───────────────────────────────────────
const expressions: LessonDef = {
  slug: "pure-expressions",
  title: L("Everything is an expression", "Todo es una expresión", "すべては式"),
  concept: "expressions",
  mode: "lesson",
  xp: 60,
  enemy: "slime",
  enemyName: L("MUTANT SLIME", "SLIME MUTANTE", "へんしんスライム"),
  beats: [
    say(L(
      "Welcome to Lambda Village! A Haskell program is built from EXPRESSIONS: pieces of code that each produce a value.",
      "¡Bienvenido a la Aldea Lambda! Un programa en Haskell se arma con EXPRESIONES: trozos de código que producen un valor.",
      "ラムダ村へようこそ！Haskell のプログラムは「式」でできている。式はどれも値をひとつ生むよ。",
    )),
    {
      kind: "act",
      prompt: L("Press in order and watch the values", "Pulsa en orden y mira los valores", "順番に押して、値を見てね"),
      steps: [
        { label: L("PRINT 2+3*4", "IMPRIMIR 2+3*4", "2+3*4 を表示"), line: "print (2 + 3 * 4)", effects: [{ t: "banner", text: L("* goes first", "* va primero", "* が先") }, { t: "print", text: "14" }], output: "14" },
        { label: L("NAME x", "NOMBRAR x", "x と名づける"), line: "let x = 5", effects: [{ t: "tag", actor: "hero", text: "x", value: "5" }] },
        { label: L("NAME y", "NOMBRAR y", "y と名づける"), line: "let y = x * 2", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "y", value: "10" }] },
        { label: L("PRINT x + y", "IMPRIMIR x + y", "x + y を表示"), line: "print (x + y)", effects: [{ t: "print", text: "15" }], output: "15" },
        {
          label: L("CHANGE x", "CAMBIAR x", "x を変える"),
          line: "x = 6",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Values never change", "Nada cambia aquí", "値は変わらない") }],
          error: {
            compiler: "parse error on input `='\n    Perhaps you need a 'let' in a 'do' block?",
            plain: L("A name is bound once and never changes. In Haskell you make new values instead.", "Un nombre se une una vez y nunca cambia. En Haskell creas valores nuevos.", "名前は一度決めたら変わらない。Haskell では新しい値を作るんだ。"),
          },
        },
      ],
    },
    say(L(
      "print shows a value on the screen. In 2 + 3 * 4 the * goes first, just like in math class: 14.",
      "print muestra un valor en pantalla. En 2 + 3 * 4 el * va primero, como en la escuela: 14.",
      "print は値を画面に出す。2 + 3 * 4 は算数と同じで * が先。答えは 14。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (2 + 3 * 4)",
      options: ["14", "20", "9"],
      answer: 0,
      output: "14",
      check: { compiles: true, stdout: "14" },
      explain: L("* binds tighter than +, so it is 2 + 12 = 14.", "* se aplica antes que +, así que es 2 + 12 = 14.", "* は + より先に計算するから 2 + 12 = 14。"),
      win: [{ t: "print", text: "14" }],
    },
    say(L(
      "Two ways to divide: `div` keeps whole numbers and `mod` gives the remainder. / gives a fraction. Backticks turn a function into an operator.",
      "Dos formas de dividir: `div` da enteros y `mod` el resto. / da una fracción. Las comillas invertidas vuelven operador a una función.",
      "割り算は2種類。`div` は整数、`mod` は余り、/ は小数。バッククォートで関数を演算子にできる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (7 `div` 2, 7 `mod` 2, 7 / 2)",
      options: ["(3,1,3.5)", "(3.5,1,3.5)", "(3,1,3)"],
      answer: 0,
      output: "(3,1,3.5)",
      check: { compiles: true, stdout: "(3,1,3.5)" },
      explain: L("div drops the fraction (3), mod is what is left (1), and / keeps the fraction (3.5).", "div descarta la fracción (3), mod es lo que sobra (1) y / conserva la fracción (3.5).", "div は小数を捨てて 3、mod は余りの 1、/ は小数のまま 3.5。"),
      win: [{ t: "print", text: "(3,1,3.5)" }],
    },
    {
      kind: "pick",
      prompt: L("It must print 3", "Debe imprimir 3", "3 と表示させよう"),
      code: "print (7 ___ 2)",
      options: ["`div`", "/", "`mod`"],
      answer: 0,
      check: { compiles: true, stdout: "3" },
      explain: L("`div` gives the whole part: 3. / would print 3.5 and `mod` would print 1.", "`div` da la parte entera: 3. / imprimiría 3.5 y `mod` imprimiría 1.", "`div` は整数部分の 3。/ なら 3.5、`mod` なら 1 になる。"),
      win: [{ t: "print", text: "3" }],
    },
    say(L(
      "putStrLn prints text as it is. print shows ANY value, so text comes out with quotes. ++ joins strings; show turns a value into text.",
      "putStrLn imprime texto tal cual. print muestra CUALQUIER valor (el texto, con comillas). ++ une strings y show vuelve texto un valor.",
      "putStrLn は文字列をそのまま出す。print はどんな値も見せるので、文字列は引用符つき。++ で文字列をつなぎ、show で値を文字列にする。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "putStrLn (\"Hi, \" ++ \"Lambo\")\nprint (\"Hi, \" ++ \"Lambo\")",
      options: ["Hi, Lambo\n\"Hi, Lambo\"", "Hi, Lambo\nHi, Lambo", "\"Hi, Lambo\"\nHi, Lambo"],
      answer: 0,
      output: "Hi, Lambo\n\"Hi, Lambo\"",
      check: { compiles: true, stdout: "Hi, Lambo\n\"Hi, Lambo\"" },
      explain: L("putStrLn writes the letters. print shows the value as code, quotes included.", "putStrLn escribe las letras. print muestra el valor como código, con comillas.", "putStrLn は文字だけ。print は値をコードの形で見せるから引用符がつく。"),
      win: [{ t: "print", text: "Hi, Lambo" }, { t: "print", text: "\"Hi, Lambo\"" }],
    },
    {
      kind: "type",
      prompt: L("Join the text: it prints 42!", "Une el texto: imprime 42!", "つなげて 42! と表示"),
      code: "putStrLn (show 42 ___ \"!\")",
      answer: "++",
      check: { compiles: true, stdout: "42!" },
      explain: L("show turns 42 into the text \"42\", and ++ glues \"!\" after it.", "show convierte 42 en el texto \"42\" y ++ le pega \"!\" detrás.", "show で 42 を文字列 \"42\" にして、++ で \"!\" をつなげる。"),
      win: [{ t: "print", text: "42!" }],
    },
    say(L(
      "if is an expression too, so it must ALWAYS give a value: both then and else are required.",
      "if también es una expresión, así que SIEMPRE debe dar un valor: then y else son obligatorios.",
      "if も式だから、いつも値を返す必要がある。then と else の両方が必須だよ。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (if True then 1)",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("parse error: an if without else has no value when the test is False.", "parse error: un if sin else no tiene valor cuando la prueba es False.", "parse error：else がないと False のときの値がない。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (if 3 > 2 then \"yes\" else \"no\")",
      options: ["\"yes\"", "yes", "\"no\""],
      answer: 0,
      output: "\"yes\"",
      check: { compiles: true, stdout: "\"yes\"" },
      explain: L("3 > 2 is True, so the if gives \"yes\". print shows it with quotes.", "3 > 2 es True, así que el if da \"yes\". print lo muestra con comillas.", "3 > 2 は True なので \"yes\"。print だから引用符つき。"),
    },
    say(L(
      "A second let with the same name makes a NEW name that hides the old one. Nothing was changed: that is shadowing.",
      "Un segundo let con el mismo nombre crea un nombre NUEVO que tapa al viejo. Nada cambió: eso es sombreado.",
      "同じ名前でもう一度 let すると、古い名前を隠す新しい名前ができる。何も変わっていない。これがシャドーイング。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "let n = 1\nlet n = 2\nprint n",
      options: ["2", "1", NO_COMPILE],
      answer: 0,
      output: "2",
      check: { compiles: true, stdout: "2" },
      explain: L("The second let makes a new n that covers the first. The old 1 was never modified.", "El segundo let crea un n nuevo que tapa al primero. El 1 viejo nunca se modificó.", "2つ目の let が新しい n を作って前の n を隠す。1 は変わっていない。"),
      setup: [{ t: "tag", actor: "hero", text: "n", value: "1" }],
      win: [{ t: "dead", actor: "hero" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "n", value: "2" }, { t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (abs -3)",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("It reads as abs - 3: subtracting from a function! Negative numbers need parentheses: abs (-3).", "Se lee como abs - 3: ¡restarle a una función! Los negativos van entre paréntesis: abs (-3).", "abs - 3（関数から引き算）と読まれる。負の数はかっこで：abs (-3)。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "run",
      prompt: L("Count only FULL bags: it must print 3 full bags", "Cuenta solo bolsas LLENAS: debe imprimir 3 full bags", "満杯の袋だけ数えて 3 full bags と表示"),
      starter: "main :: IO ()\nmain = do\n  let coins = 17\n  let perBag = 5\n  putStrLn (show (coins / perBag) ++ \" full bags\")\n",
      solution: "main :: IO ()\nmain = do\n  let coins = 17\n  let perBag = 5\n  putStrLn (show (coins `div` perBag) ++ \" full bags\")\n",
      expect: "3 full bags",
      fallback: ["`div`", "\\bdiv\\s+coins", "`quot`", "\\bquot\\s+coins"],
      explain: L("/ gives 3.4 bags. `div` keeps only the whole part: 3 full bags.", "/ da 3.4 bolsas. `div` deja solo la parte entera: 3 bolsas llenas.", "/ だと 3.4 袋。`div` なら整数部分だけで 3 袋。"),
    },
  ],
};

// ─── 1.2 Every value wears a type ──────────────────────────────────────────
const types: LessonDef = {
  slug: "types-and-signatures",
  title: L("Every value wears a type", "Cada valor tiene un tipo", "値はみんな型を着ている"),
  concept: "types",
  mode: "lesson",
  xp: 65,
  enemy: "golem",
  enemyName: L("TYPE GOLEM", "GÓLEM DE TIPOS", "かたゴーレム"),
  beats: [
    say(L(
      "Every value wears a TYPE: Int, Double, Char, String, Bool. A SIGNATURE, name :: Type, says it out loud.",
      "Cada valor lleva un TIPO: Int, Double, Char, String, Bool. Una FIRMA, nombre :: Tipo, lo dice en voz alta.",
      "値はみんな「型」を着ている：Int、Double、Char、String、Bool。型シグネチャ 名前 :: 型 で宣言するよ。",
    )),
    {
      kind: "act",
      prompt: L("Give the function a chip and watch its type", "Dale una ficha a la función y mira su tipo", "関数にチップを渡して、型を見てね"),
      steps: [
        { label: L("SIGNATURE", "FIRMA", "シグネチャ"), line: "double :: Int -> Int", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "double", value: "Int -> Int" }] },
        { label: L("BODY", "CUERPO", "本体"), line: "double x = x * 2", effects: [{ t: "say", actor: "ally", text: L("x times 2!", "¡x por 2!", "x かける 2！") }] },
        { label: L("GIVE 21", "DAR 21", "21 を渡す"), line: "main = print (double 21)", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "print", text: "42" }], output: "42" },
        {
          label: L("GIVE 2.5", "DAR 2.5", "2.5 を渡す"),
          line: "main = print (double 2.5)",
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: L("Not an Int!", "¡No es un Int!", "Int じゃない！") }],
          error: {
            compiler: "No instance for `Fractional Int' arising from the literal `2.5'",
            plain: L("double only takes an Int. 2.5 is a fraction, so GHC refuses before running.", "double solo acepta Int. 2.5 es una fracción, así que GHC se niega antes de ejecutar.", "double は Int だけ。2.5 は小数だから、実行前に GHC が断る。"),
          },
        },
      ],
    },
    say(L(
      "Read -> as 'takes, then gives'. Int -> Int takes an Int and gives an Int. The LAST type is the result.",
      "Lee -> como 'recibe y luego da'. Int -> Int recibe un Int y da un Int. El ÚLTIMO tipo es el resultado.",
      "-> は「受け取って、返す」。Int -> Int は Int を受け取り Int を返す。最後の型が結果だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "double :: Int -> Int\ndouble x = x * 2\n\nmain = print (double 21)",
      options: ["42", "21", "2121"],
      answer: 0,
      output: "42",
      check: { compiles: true, stdout: "42" },
      explain: L("double takes 21 and gives 21 * 2 = 42.", "double recibe 21 y da 21 * 2 = 42.", "double は 21 を受け取って 21 * 2 = 42 を返す。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "double", value: "Int -> Int" }],
      win: [{ t: "print", text: "42" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "double :: Int -> Int\ndouble x = x * 2\n\nmain = print (double 2.5)",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("No instance for Fractional Int: 2.5 is not an Int, and Haskell never converts silently.", "No instance for Fractional Int: 2.5 no es Int y Haskell nunca convierte en silencio.", "No instance for Fractional Int：2.5 は Int じゃない。勝手に変換はしない。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "double", value: "Int -> Int" }],
      win: [{ t: "shake" }],
    },
    say(L(
      "More arguments, more arrows: Double -> Double -> Double takes two Doubles and gives one.",
      "Más argumentos, más flechas: Double -> Double -> Double recibe dos Double y da uno.",
      "引数が増えれば矢印も増える。Double -> Double -> Double は Double を2つ受け取り1つ返す。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "area :: Double -> Double -> Double\narea w h = w * h\n\nmain = print (area 2 3.5)",
      options: ["7.0", "7", "5.5"],
      answer: 0,
      output: "7.0",
      check: { compiles: true, stdout: "7.0" },
      explain: L("2 * 3.5 = 7, and a Double always prints with a decimal point: 7.0.", "2 * 3.5 = 7, y un Double siempre se imprime con punto decimal: 7.0.", "2 * 3.5 = 7。Double はいつも小数点つきで 7.0 と表示。"),
      win: [{ t: "print", text: "7.0" }],
    },
    say(L(
      "length gives an Int, and / only works on fractions. fromIntegral converts a whole number so / accepts it.",
      "length da un Int, y / solo funciona con fracciones. fromIntegral convierte un entero para que / lo acepte.",
      "length は Int を返す。/ は小数用。fromIntegral で整数を変換すれば / が使える。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (length [1,2,3] / 2)",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("No instance for Fractional Int: length is an Int, and / needs a fraction type.", "No instance for Fractional Int: length es Int, y / necesita un tipo fraccionario.", "No instance for Fractional Int：length は Int、/ は小数の型が必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (fromIntegral (length [1,2,3]) / 2)",
      options: ["1.5", "1", NO_COMPILE],
      answer: 0,
      output: "1.5",
      check: { compiles: true, stdout: "1.5" },
      explain: L("fromIntegral turns the Int 3 into a number / accepts, so 3 / 2 = 1.5.", "fromIntegral convierte el Int 3 en un número que / acepta: 3 / 2 = 1.5.", "fromIntegral で Int の 3 を / が使える数に。3 / 2 = 1.5。"),
      win: [{ t: "print", text: "1.5" }],
    },
    say(L(
      "Int has a fixed size and silently wraps around when too big. Integer grows as big as it needs.",
      "Int tiene un tamaño fijo y da la vuelta en silencio si es muy grande. Integer crece lo que haga falta.",
      "Int は大きさが決まっていて、大きすぎると黙って一周する。Integer は必要なだけ大きくなる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (2 ^ 64 :: Integer)\nprint (2 ^ 64 :: Int)",
      options: ["18446744073709551616\n0", "18446744073709551616\n18446744073709551616", "0\n0"],
      answer: 0,
      output: "18446744073709551616\n0",
      check: { compiles: true, stdout: "18446744073709551616\n0" },
      explain: L("Integer holds the exact value. Int has 64 bits, so 2 ^ 64 wraps to 0 with no warning.", "Integer guarda el valor exacto. Int tiene 64 bits, así que 2 ^ 64 da la vuelta a 0 sin aviso.", "Integer は正確な値。Int は 64 ビットなので 2 ^ 64 は黙って 0 になる。"),
      win: [{ t: "print", text: "18446744073709551616" }, { t: "print", text: "0" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "putStrLn (\"Score: \" ++ 10)",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("10 is a number, not text. Turn it into a String first: \"Score: \" ++ show 10.", "10 es un número, no texto. Conviértelo primero: \"Score: \" ++ show 10.", "10 は数で文字列じゃない。先に変換：\"Score: \" ++ show 10。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Complete the signature", "Completa la firma", "シグネチャを完成させよう"),
      code: "double :: Int ___ Int\ndouble x = x * 2\n\nmain = print (double 4)",
      answer: "->",
      check: { compiles: true, stdout: "8" },
      explain: L("Int -> Int: takes an Int, gives an Int.", "Int -> Int: recibe un Int y da un Int.", "Int -> Int：Int を受け取り Int を返す。"),
      win: [{ t: "print", text: "8" }],
    },
    {
      kind: "run",
      prompt: L("Keep the fraction: it must print half of 7 is 3.5", "Conserva la fracción: debe imprimir half of 7 is 3.5", "小数を残して half of 7 is 3.5 と表示"),
      starter: "half :: Int -> Int\nhalf x = x `div` 2\n\nmain :: IO ()\nmain = putStrLn (\"half of 7 is \" ++ show (half 7))\n",
      solution: "half :: Double -> Double\nhalf x = x / 2\n\nmain :: IO ()\nmain = putStrLn (\"half of 7 is \" ++ show (half 7))\n",
      expect: "half of 7 is 3.5",
      fallback: ["half\\s*::\\s*Double\\s*->\\s*Double[\\s\\S]*x\\s*/\\s*2", "half\\s*::\\s*Float\\s*->\\s*Float[\\s\\S]*x\\s*/\\s*2"],
      explain: L("An Int can't hold 3.5. Make half a Double -> Double and divide with /.", "Un Int no puede guardar 3.5. Haz half Double -> Double y divide con /.", "Int に 3.5 は入らない。half を Double -> Double にして / で割ろう。"),
    },
  ],
};

// ─── 1.3 Rows of items, scrolls of letters ─────────────────────────────────
const lists: LessonDef = {
  slug: "lists-and-strings",
  title: L("Rows and scrolls", "Filas y pergaminos", "リストと文字列"),
  concept: "lists",
  mode: "lesson",
  xp: 65,
  enemy: "ghost",
  enemyName: L("EMPTY GHOST", "FANTASMA VACÍO", "からっぽゴースト"),
  beats: [
    say(L(
      "A LIST is a row of values of ONE type: [1,2,3]. : puts one item at the front, ++ joins two rows.",
      "Una LISTA es una fila de valores de UN tipo: [1,2,3]. : pone un objeto al frente, ++ une dos filas.",
      "リストは同じ型の値の列：[1,2,3]。: は先頭にひとつ足し、++ は2つの列をつなぐ。",
    )),
    {
      kind: "act",
      prompt: L("Build a row of gems", "Arma una fila de gemas", "宝石の列を作ろう"),
      steps: [
        { label: L("ROW", "FILA", "列"), line: "let gems = [1,2,3]", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "gems", value: "[1,2,3]" }] },
        { label: L("FRONT 0", "FRENTE 0", "先頭に 0"), line: "print (0 : gems)", effects: [{ t: "print", text: "[0,1,2,3]" }], output: "[0,1,2,3]" },
        { label: L("JOIN", "UNIR", "つなぐ"), line: "print (gems ++ [4,5])", effects: [{ t: "banner", text: L("walks the 1st row", "recorre la 1.ª fila", "1つ目を歩く") }, { t: "print", text: "[1,2,3,4,5]" }], output: "[1,2,3,4,5]" },
        { label: L("HEAD", "HEAD", "head"), line: "print (head gems)", effects: [{ t: "print", text: "1" }], output: "1" },
        {
          label: L("HEAD OF []", "HEAD DE []", "[] の head"),
          line: "print (head ([] :: [Int]))",
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Nothing here!", "¡Aquí no hay nada!", "なにもないよ！") }],
          error: {
            compiler: "Prelude.head: empty list",
            plain: L("An empty row has no first item. head compiles fine but crashes when it runs.", "Una fila vacía no tiene primer objeto. head compila, pero se cae al ejecutarse.", "空の列に先頭はない。head はコンパイルできても、実行時に落ちる。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ([1,2,3] ++ [4,5])\nprint (0 : [1,2,3])",
      options: ["[1,2,3,4,5]\n[0,1,2,3]", "[1,2,3,[4,5]]\n[0,1,2,3]", "[1,2,3,4,5]\n[1,2,3,0]"],
      answer: 0,
      output: "[1,2,3,4,5]\n[0,1,2,3]",
      check: { compiles: true, stdout: "[1,2,3,4,5]\n[0,1,2,3]" },
      explain: L("++ joins two lists into one. : adds a single item at the FRONT.", "++ une dos listas en una. : agrega un solo objeto al FRENTE.", "++ は2つのリストを1つに。: は先頭にひとつ足す。"),
      win: [{ t: "print", text: "[1,2,3,4,5]" }, { t: "print", text: "[0,1,2,3]" }],
    },
    say(L(
      "A String is just a list of Char: \"abc\" is ['a','b','c']. So list tools like length and reverse work on text.",
      "Un String es solo una lista de Char: \"abc\" es ['a','b','c']. Así que length y reverse funcionan con texto.",
      "String は Char のリストにすぎない：\"abc\" は ['a','b','c']。だから length や reverse が文字列にも使える。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (\"abc\" == ['a','b','c'])",
      options: ["True", "False", NO_COMPILE],
      answer: 0,
      output: "True",
      check: { compiles: true, stdout: "True" },
      explain: L("A String IS a list of Char, so both sides are the same value.", "Un String ES una lista de Char, así que ambos lados son el mismo valor.", "String は Char のリストそのもの。両辺は同じ値だよ。"),
      win: [{ t: "print", text: "True" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (length \"abc\", reverse \"lambda\")",
      options: ["(3,\"adbmal\")", "(3,\"lambda\")", "(6,\"adbmal\")"],
      answer: 0,
      output: "(3,\"adbmal\")",
      check: { compiles: true, stdout: "(3,\"adbmal\")" },
      explain: L("\"abc\" has 3 letters, and reverse flips the row of letters.", "\"abc\" tiene 3 letras, y reverse da vuelta la fila de letras.", "\"abc\" は3文字。reverse は文字の列をひっくり返す。"),
      win: [{ t: "print", text: "(3,\"adbmal\")" }],
    },
    say(L(
      "!! picks by position, counting from 0. take n keeps the first n items, drop n skips them.",
      "!! elige por posición, contando desde 0. take n deja los primeros n, drop n los salta.",
      "!! は位置で取り出す（0 から数える）。take n は最初の n 個、drop n はそれを飛ばす。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ([1,2,3] !! 1, take 2 [5,6,7], drop 2 [5,6,7])",
      options: ["(2,[5,6],[7])", "(1,[5,6],[7])", "(2,[6,7],[5])"],
      answer: 0,
      output: "(2,[5,6],[7])",
      check: { compiles: true, stdout: "(2,[5,6],[7])" },
      explain: L("Position 1 is the second item (2). take 2 keeps [5,6]; drop 2 leaves [7].", "La posición 1 es el segundo objeto (2). take 2 deja [5,6]; drop 2 deja [7].", "位置 1 は2番目の 2。take 2 は [5,6]、drop 2 は残りの [7]。"),
      win: [{ t: "print", text: "(2,[5,6],[7])" }],
    },
    say(L(
      "[1..5] counts for you, [2,4..10] steps by 2. A COMPREHENSION builds a list from a rule: [x * x | x <- [1..5], odd x].",
      "[1..5] cuenta por ti, [2,4..10] avanza de 2 en 2. Una COMPRENSIÓN arma una lista con una regla: [x * x | x <- [1..5], odd x].",
      "[1..5] は自動で数え、[2,4..10] は2つ飛ばし。内包表記はルールでリストを作る：[x * x | x <- [1..5], odd x]。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print [2,4..10]\nprint ['a'..'e']",
      options: ["[2,4,6,8,10]\n\"abcde\"", "[2,4,6,8,10]\n['a','b','c','d','e']", "[2,4,10]\n\"ae\""],
      answer: 0,
      output: "[2,4,6,8,10]\n\"abcde\"",
      check: { compiles: true, stdout: "[2,4,6,8,10]\n\"abcde\"" },
      explain: L("Ranges fill the gaps. A list of Char is a String, so print shows \"abcde\".", "Los rangos rellenan los huecos. Una lista de Char es un String, así que print muestra \"abcde\".", "範囲はすき間を埋める。Char のリストは String だから \"abcde\" と表示。"),
      win: [{ t: "print", text: "[2,4,6,8,10]" }, { t: "print", text: "\"abcde\"" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print [x * x | x <- [1..5], odd x]",
      options: ["[1,9,25]", "[1,4,9,16,25]", "[4,16]"],
      answer: 0,
      output: "[1,9,25]",
      check: { compiles: true, stdout: "[1,9,25]" },
      explain: L("x walks 1..5, only odd x pass the gate (1, 3, 5), and each one is squared.", "x recorre 1..5, solo los impares pasan (1, 3, 5) y cada uno se eleva al cuadrado.", "x は 1..5 を歩き、奇数（1, 3, 5）だけ通って2乗される。"),
      win: [{ t: "print", text: "[1,9,25]" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print [1, 'a']",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("A list holds ONE type. A number and a Char can't share a row.", "Una lista guarda UN solo tipo. Un número y un Char no comparten fila.", "リストの型はひとつ。数と Char は同じ列に並べない。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (\"x\" : \"yz\")",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("\"x\" is a String, but : wants one Char at the front: 'x' : \"yz\" works.", "\"x\" es un String, pero : quiere un Char al frente: 'x' : \"yz\" sí funciona.", "\"x\" は String。: の左は Char ひとつ：'x' : \"yz\" ならOK。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "putStrLn \"before\"\nprint (head ([] :: [Int]))",
      options: [
        L("before, then crash: Prelude.head: empty list", "before y luego cae: Prelude.head: empty list", "before のあと落ちる：Prelude.head: empty list"),
        "before\n0",
        NO_COMPILE,
      ],
      answer: 0,
      check: { compiles: true, throws: "Prelude.head: empty list" },
      explain: L("It compiles. putStrLn runs, then head finds no first item and the program crashes.", "Compila. putStrLn se ejecuta, luego head no encuentra primer objeto y el programa cae.", "コンパイルはできる。putStrLn のあと、head が先頭を見つけられず落ちる。"),
      win: [{ t: "print", text: "before" }, { t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Flip the word: it prints \"lwo\"", "Invierte la palabra: imprime \"lwo\"", "単語を逆に：\"lwo\" と表示"),
      code: "print (___ \"owl\")",
      answer: "reverse",
      check: { compiles: true, stdout: "\"lwo\"" },
      explain: L("A String is a list, so reverse flips its letters.", "Un String es una lista, así que reverse invierte sus letras.", "String はリストだから reverse で文字が逆になる。"),
      win: [{ t: "print", text: "\"lwo\"" }],
    },
    {
      kind: "run",
      prompt: L("The sign must show the first six letters: Lambda", "El cartel debe mostrar las seis primeras letras: Lambda", "看板に最初の6文字 Lambda を表示"),
      starter: "main :: IO ()\nmain = putStrLn (drop 3 \"Lambdara\")\n",
      solution: "main :: IO ()\nmain = putStrLn (take 6 \"Lambdara\")\n",
      expect: "Lambda",
      fallback: ["take\\s+6\\s+\"Lambdara\"", "\"Lambda\""],
      explain: L("drop 3 skips letters. take 6 keeps the first six: Lambda.", "drop 3 salta letras. take 6 deja las seis primeras: Lambda.", "drop 3 は文字を飛ばす。take 6 で最初の6文字 Lambda。"),
    },
  ],
};

// ─── 1.4 Which shape is it? ─────────────────────────────────────────────────
const patterns: LessonDef = {
  slug: "patterns-and-guards",
  title: L("Which shape is it?", "¿Qué forma tiene?", "どんな形？"),
  concept: "patterns",
  mode: "lesson",
  xp: 70,
  enemy: "haskell/bottom-wraith",
  enemyName: L("GAP WRAITH", "ESPECTRO HUECO", "すきまレイス"),
  beats: [
    say(L(
      "A function can have several EQUATIONS. Haskell tries them top to bottom and runs the first one whose pattern fits.",
      "Una función puede tener varias ECUACIONES. Haskell las prueba de arriba abajo y usa la primera cuyo patrón encaja.",
      "関数は複数の「式（等式）」で書ける。上から順に試し、パターンが合った最初のものを使う。",
    )),
    {
      kind: "act",
      prompt: L("Build the sorting board and feed it", "Arma el tablero clasificador y aliméntalo", "仕分け板を作って値を入れよう"),
      steps: [
        { label: L("SLOT 0", "RANURA 0", "0 の穴"), line: "isZero 0 = \"zero\"", effects: [{ t: "enter", actor: "ally" }, { t: "say", actor: "ally", text: L("Slot: exactly 0", "Ranura: justo 0", "穴：ぴったり 0") }] },
        { label: L("SLOT _", "RANURA _", "_ の穴"), line: "isZero _ = \"other\"", effects: [{ t: "say", actor: "ally", text: L("Slot: anything", "Ranura: lo que sea", "穴：なんでも") }] },
        { label: L("TRY 0", "PROBAR 0", "0 を試す"), line: "print (isZero 0)", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "print", text: "\"zero\"" }], output: "\"zero\"" },
        { label: L("TRY 5", "PROBAR 5", "5 を試す"), line: "print (isZero 5)", effects: [{ t: "say", actor: "ally", text: L("Fell to _", "Cayó en _", "_ に落ちた") }, { t: "print", text: "\"other\"" }], output: "\"other\"" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "isZero :: Int -> String\nisZero 0 = \"zero\"\nisZero _ = \"other\"\n\nmain = print (isZero 0, isZero 5)",
      options: ["(\"zero\",\"other\")", "(\"zero\",\"zero\")", "(\"other\",\"other\")"],
      answer: 0,
      output: "(\"zero\",\"other\")",
      check: { compiles: true, stdout: "(\"zero\",\"other\")" },
      explain: L("0 fits the first equation. 5 doesn't, so it falls to _, which matches anything.", "0 encaja en la primera ecuación. 5 no, así que cae en _, que encaja con todo.", "0 は1つ目に合う。5 は合わず、なんでも合う _ に落ちる。"),
      win: [{ t: "print", text: "(\"zero\",\"other\")" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "anyF :: Int -> String\nanyF _ = \"any\"\nanyF 0 = \"zero\"\n\nmain = print (anyF 0)",
      options: ["\"any\"", "\"zero\"", NO_COMPILE],
      answer: 0,
      output: "\"any\"",
      check: { compiles: true, stdout: "\"any\"" },
      explain: L("The first equation that fits wins. _ fits 0, so \"zero\" is never reached.", "Gana la primera ecuación que encaja. _ encaja con 0, así que nunca se llega a \"zero\".", "最初に合った式が勝つ。_ が 0 に合うので \"zero\" には届かない。"),
    },
    say(L(
      "A list has two shapes: [] (empty) or (x:xs), a first item x stuck to the rest xs.",
      "Una lista tiene dos formas: [] (vacía) o (x:xs), un primer objeto x pegado al resto xs.",
      "リストの形は2つ：[]（空）か (x:xs)。先頭 x と残り xs だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "firstOr :: a -> [a] -> a\nfirstOr d [] = d\nfirstOr _ (x:_) = x\n\nmain = print (firstOr 0 [], firstOr 0 [4,5])",
      options: ["(0,4)", "(0,5)", "(4,4)"],
      answer: 0,
      output: "(0,4)",
      check: { compiles: true, stdout: "(0,4)" },
      explain: L("[] fits the first equation and gives the default 0. [4,5] fits (x:_) with x = 4.", "[] encaja en la primera y da el valor por defecto 0. [4,5] encaja en (x:_) con x = 4.", "[] は1つ目に合ってデフォルトの 0。[4,5] は (x:_) に合って x = 4。"),
      win: [{ t: "print", text: "(0,4)" }],
    },
    say(L(
      "GUARDS, | test = result, are signposts checked top to bottom. otherwise is the last sign: it always says yes.",
      "Las GUARDAS, | prueba = resultado, son carteles revisados de arriba abajo. otherwise es el último: siempre dice sí.",
      "ガード | 条件 = 結果 は上から順に見る道しるべ。otherwise は最後の札で、いつも「はい」。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "grade :: Int -> Char\ngrade n\n  | n >= 90 = 'A'\n  | n >= 70 = 'B'\n  | otherwise = 'C'\n\nmain = print (map grade [95, 70, 10])",
      options: ["\"ABC\"", "['A','B','C']", "\"AAC\""],
      answer: 0,
      output: "\"ABC\"",
      check: { compiles: true, stdout: "\"ABC\"" },
      explain: L("95 passes the first sign, 70 the second, 10 only otherwise. A list of Char prints as a String.", "95 pasa el primer cartel, 70 el segundo, 10 solo otherwise. Una lista de Char se imprime como String.", "95 は1つ目、70 は2つ目、10 は otherwise。Char のリストは文字列として表示。"),
      win: [{ t: "print", text: "\"ABC\"" }],
    },
    say(L(
      "where names a helper that every guard can share. case ... of matches patterns in the middle of an expression.",
      "where nombra un ayudante que todas las guardas comparten. case ... of compara patrones dentro de una expresión.",
      "where は全ガードで共有する名前を作る。case ... of は式の途中でパターンを照合する。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "bmi :: Double -> Double -> String\nbmi w h\n  | v < 18.5 = \"under\"\n  | v < 25 = \"normal\"\n  | otherwise = \"over\"\n  where v = w / h ^ 2\n\nmain = print (bmi 50 1.8, bmi 70 1.75)",
      options: ["(\"under\",\"normal\")", "(\"normal\",\"normal\")", "(\"under\",\"over\")"],
      answer: 0,
      output: "(\"under\",\"normal\")",
      check: { compiles: true, stdout: "(\"under\",\"normal\")" },
      explain: L("v is computed once in where: 50 / 3.24 is about 15.4 (under), 70 / 3.06 about 22.9 (normal).", "v se calcula una vez en where: 50 / 3.24 es unos 15.4 (under), 70 / 3.06 unos 22.9 (normal).", "v は where で計算：50 / 3.24 は約 15.4（under）、70 / 3.06 は約 22.9（normal）。"),
      win: [{ t: "print", text: "(\"under\",\"normal\")" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "sizeOf :: String -> String\nsizeOf xs = case xs of\n  [] -> \"empty\"\n  [_] -> \"one\"\n  _ -> \"many\"\n\nmain = print (sizeOf \"abc\", sizeOf \"\", sizeOf \"x\")",
      options: ["(\"many\",\"empty\",\"one\")", "(\"many\",\"one\",\"one\")", "(\"one\",\"empty\",\"one\")"],
      answer: 0,
      output: "(\"many\",\"empty\",\"one\")",
      check: { compiles: true, stdout: "(\"many\",\"empty\",\"one\")" },
      explain: L("[_] fits a list of exactly one item. \"\" is the empty list [], and \"abc\" falls to _.", "[_] encaja con una lista de exactamente un objeto. \"\" es la lista vacía [] y \"abc\" cae en _.", "[_] はちょうど1個のリスト。\"\" は空リスト []、\"abc\" は _ に落ちる。"),
      win: [{ t: "print", text: "(\"many\",\"empty\",\"one\")" }],
    },
    say(L(
      "If NO equation or guard fits, the program crashes while running. Always cover every shape!",
      "Si NINGUNA ecuación o guarda encaja, el programa cae al ejecutarse. ¡Cubre siempre todas las formas!",
      "どの式もガードも合わないと、実行中に落ちる。すべての形をカバーしよう！",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "describe :: Int -> String\ndescribe 1 = \"one\"\ndescribe 2 = \"two\"\n\nmain = putStrLn (describe 3)",
      options: [
        L("Crash: Non-exhaustive patterns", "Cae: Non-exhaustive patterns", "落ちる：Non-exhaustive patterns"),
        L("Prints nothing", "No imprime nada", "何も表示しない"),
        NO_COMPILE,
      ],
      answer: 0,
      check: { compiles: true, throws: "Non-exhaustive patterns in function describe" },
      explain: L("It compiles, but 3 fits no equation, so the program dies at run time.", "Compila, pero 3 no encaja en ninguna ecuación, así que el programa muere al ejecutarse.", "コンパイルはできるが、3 に合う式がないので実行時に落ちる。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("A gap! Mine!", "¡Un hueco! ¡Mío!", "すきまだ！") }],
    },
    {
      kind: "type",
      prompt: L("The last sign always says yes", "El último cartel siempre dice sí", "最後の札はいつも「はい」"),
      code: "sign :: Int -> String\nsign n\n  | n < 0 = \"negative\"\n  | n > 0 = \"positive\"\n  | ___ = \"zero\"\n\nmain = putStrLn (sign 0)",
      answer: "otherwise",
      check: { compiles: true, stdout: "zero" },
      explain: L("otherwise is just True: the catch-all sign at the bottom.", "otherwise es simplemente True: el cartel final que atrapa todo.", "otherwise はただの True。一番下の受け皿だよ。"),
      win: [{ t: "print", text: "zero" }],
    },
    {
      kind: "order",
      prompt: L("Put the function in order", "Ordena la función", "関数を正しい順に並べよう"),
      lines: ["grade :: Int -> Char", "grade n", "  | n >= 90 = 'A'", "  | otherwise = 'C'"],
      check: { compiles: true, stdout: "\"AC\"", program: "grade :: Int -> Char\ngrade n\n  | n >= 90 = 'A'\n  | otherwise = 'C'\n\nmain = print (map grade [95, 10])\n" },
      explain: L("Signature first, then the name and argument, then the guards, ending with otherwise.", "Primero la firma, luego el nombre y el argumento, después las guardas, terminando en otherwise.", "まずシグネチャ、次に名前と引数、そしてガード。最後は otherwise。"),
    },
    {
      kind: "run",
      prompt: L("Cover the missing shape: describe 0 must print zero", "Cubre la forma que falta: describe 0 debe imprimir zero", "足りない形を補って describe 0 で zero"),
      starter: "describe :: Int -> String\ndescribe n\n  | n < 0 = \"negative\"\n  | n > 0 = \"positive\"\n\nmain :: IO ()\nmain = do\n  putStrLn (describe 5)\n  putStrLn (describe 0)\n",
      solution: "describe :: Int -> String\ndescribe n\n  | n < 0 = \"negative\"\n  | n > 0 = \"positive\"\n  | otherwise = \"zero\"\n\nmain :: IO ()\nmain = do\n  putStrLn (describe 5)\n  putStrLn (describe 0)\n",
      expect: "zero",
      fallback: ["\\|\\s*otherwise\\s*=\\s*\"zero\"", "\\|\\s*n\\s*==\\s*0\\s*=\\s*\"zero\"", "describe\\s+0\\s*=\\s*\"zero\""],
      explain: L("0 is neither < 0 nor > 0, so no guard fits and it crashes. Add | otherwise = \"zero\".", "0 no es < 0 ni > 0, así que ninguna guarda encaja y cae. Agrega | otherwise = \"zero\".", "0 は < 0 でも > 0 でもないので落ちる。| otherwise = \"zero\" を足そう。"),
    },
  ],
};

// ─── BOSS · The Partial Moth ────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "village-boss",
  title: L("The Partial Moth", "La Polilla Parcial", "部分関数の蛾"),
  concept: "patterns",
  mode: "boss",
  xp: 160,
  enemy: "haskell/partial-moth",
  enemyName: L("PARTIAL MOTH", "POLILLA PARCIAL", "パーシャルモス"),
  beats: [
    enemySays(L(
      "Flutter... I am the PARTIAL MOTH. I nibble holes where your functions forget a shape. Let's see what you missed!",
      "Aleteo... Soy la POLILLA PARCIAL. Muerdo huecos donde tus funciones olvidan una forma. ¡Veamos qué olvidaste!",
      "パタパタ…我はパーシャルモス。関数が忘れた形に穴をあける。何を見落としたかな！",
    )),
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: "print (last ([] :: [Int]))",
      options: [L("Crash: Prelude.last: empty list", "Cae: Prelude.last: empty list", "落ちる：Prelude.last: empty list"), "0", NO_COMPILE],
      answer: 0,
      check: { compiles: true, throws: "Prelude.last: empty list" },
      explain: L("Like head, last has no answer for an empty list: it compiles, then crashes.", "Como head, last no tiene respuesta para una lista vacía: compila y luego cae.", "head と同じく、空リストの last は答えがない。コンパイル後に落ちる。"),
      win: [{ t: "attack", from: "enemy", to: "hero" }, { t: "shake" }],
    },
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: "print ([1,2,3] !! 5)",
      options: [L("Crash: index too large", "Cae: index too large", "落ちる：index too large"), "3", NO_COMPILE],
      answer: 0,
      check: { compiles: true, throws: "Prelude.!!: index too large" },
      explain: L("Positions go 0, 1, 2. There is no position 5, so !! crashes at run time.", "Las posiciones van 0, 1, 2. No hay posición 5, así que !! cae al ejecutarse.", "位置は 0, 1, 2 だけ。5 はないので !! は実行時に落ちる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: "print (maximum ([] :: [Int]))",
      options: [L("Crash: empty list", "Cae: empty list", "落ちる：empty list"), "0", NO_COMPILE],
      answer: 0,
      check: { compiles: true, throws: "Prelude.maximum: empty list" },
      explain: L("The biggest item of nothing doesn't exist. maximum is partial too.", "El mayor objeto de nada no existe. maximum también es parcial.", "何もない中の最大値は存在しない。maximum も部分関数。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict", time: 15, prompt: COMPILES,
      code: "print (sum [1,2,3] / length [1,2,3])",
      options: [YES, NO_GHC],
      answer: 1,
      check: { compiles: false },
      explain: L("length is an Int, and / needs a fraction type: No instance for Fractional Int. Use fromIntegral.", "length es Int y / necesita un tipo fraccionario: No instance for Fractional Int. Usa fromIntegral.", "length は Int、/ は小数の型が必要。fromIntegral を使おう。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict", time: 12, prompt: PRINT,
      code: "print [c | c <- \"banana\", c == 'a']",
      options: ["\"aaa\"", "3", "\"bnn\""],
      answer: 0,
      output: "\"aaa\"",
      check: { compiles: true, stdout: "\"aaa\"" },
      explain: L("Only the letters equal to 'a' pass the gate. A list of Char prints as a String.", "Solo las letras iguales a 'a' pasan. Una lista de Char se imprime como String.", "'a' と等しい文字だけ通る。Char のリストは文字列として表示。"),
      win: [{ t: "print", text: "\"aaa\"" }],
    },
    {
      kind: "predict", time: 12, prompt: PRINT,
      code: "print (take 3 (reverse [1..10]))",
      options: ["[10,9,8]", "[1,2,3]", "[3,2,1]"],
      answer: 0,
      output: "[10,9,8]",
      check: { compiles: true, stdout: "[10,9,8]" },
      explain: L("reverse runs first (inner parentheses), then take keeps the first three.", "reverse va primero (paréntesis interiores), luego take deja los tres primeros.", "内側の reverse が先、そのあと take で最初の3つ。"),
      win: [{ t: "print", text: "[10,9,8]" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "swap :: (a, b) -> (b, a)\nswap (x, y) = (y, x)\n\nmain = print (swap (1, \"one\"))",
      options: ["(\"one\",1)", "(1,\"one\")", NO_COMPILE],
      answer: 0,
      output: "(\"one\",1)",
      check: { compiles: true, stdout: "(\"one\",1)" },
      explain: L("The pattern (x, y) takes the pair apart, and the result builds it the other way round.", "El patrón (x, y) separa el par y el resultado lo arma al revés.", "パターン (x, y) でペアを分けて、逆向きに組み立てる。"),
      win: [{ t: "print", text: "(\"one\",1)" }],
    },
    {
      kind: "predict", time: 15, prompt: PRINT,
      code: "label :: Int -> String\nlabel n\n  | n > 100 = \"huge\"\n  | n > 10 = \"big\"\n  | otherwise = \"small\"\n\nmain = print (map label [5, 50, 500])",
      options: ["[\"small\",\"big\",\"huge\"]", "[\"small\",\"big\",\"big\"]", "[\"small\",\"huge\",\"huge\"]"],
      answer: 0,
      output: "[\"small\",\"big\",\"huge\"]",
      check: { compiles: true, stdout: "[\"small\",\"big\",\"huge\"]" },
      explain: L("Signs are checked top to bottom: 500 stops at > 100, 50 at > 10, 5 reaches otherwise.", "Los carteles se revisan de arriba abajo: 500 para en > 100, 50 en > 10, 5 llega a otherwise.", "上から順に見る：500 は > 100、50 は > 10、5 は otherwise。"),
      win: [{ t: "print", text: "[\"small\",\"big\",\"huge\"]" }],
    },
    {
      kind: "predict", time: 15, prompt: HAPPENS,
      code: "firstOne :: [Int] -> Int\nfirstOne xs = case xs of\n  (x:_) -> x\n\nmain = print (firstOne [])",
      options: [L("Crash: Non-exhaustive patterns", "Cae: Non-exhaustive patterns", "落ちる：Non-exhaustive patterns"), "0", NO_COMPILE],
      answer: 0,
      check: { compiles: true, throws: "Non-exhaustive patterns" },
      explain: L("The case only knows the (x:_) shape. [] fits nothing, so the moth eats a hole.", "El case solo conoce la forma (x:_). [] no encaja en nada, así que la polilla muerde un hueco.", "case は (x:_) の形しか知らない。[] は合わず、蛾が穴をあける。"),
      win: [{ t: "attack", from: "enemy", to: "hero" }, { t: "shake" }],
    },
    {
      kind: "pick", time: 15,
      prompt: L("Cover the empty list", "Cubre la lista vacía", "空リストをカバーしよう"),
      code: "firstOr :: Int -> [Int] -> Int\nfirstOr d ___ = d\nfirstOr _ (x:_) = x\n\nmain = print (firstOr 7 [], firstOr 7 [1])",
      options: ["[]", "(x:xs)", "[_]"],
      answer: 0,
      check: { compiles: true, stdout: "(7,1)" },
      explain: L("[] is the empty shape. With it, every list fits some equation: no holes left.", "[] es la forma vacía. Con ella, toda lista encaja en alguna ecuación: sin huecos.", "[] が空の形。これで全部のリストがどれかに合う。穴なし！"),
      win: [{ t: "print", text: "(7,1)" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "type", time: 15,
      prompt: L("The remainder: it prints 1", "El resto: imprime 1", "余りを出そう：1 と表示"),
      code: "print (7 `___` 2)",
      answer: "mod",
      check: { compiles: true, stdout: "1" },
      explain: L("7 `mod` 2 is what is left after dividing: 1.", "7 `mod` 2 es lo que sobra al dividir: 1.", "7 `mod` 2 は割った余りの 1。"),
      win: [{ t: "print", text: "1" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    enemySays(L(
      "No holes left to nibble... Fine. In the Fold Forest, functions travel as values. You won't cover THAT so easily!",
      "No quedan huecos que morder... Bien. En el Bosque Fold las funciones viajan como valores. ¡Eso no lo cubrirás tan fácil!",
      "かじる穴がない…いいだろう。フォールドの森では関数が値として旅をする。そう簡単にはいかないぞ！",
    )),
  ],
};

export const lambdaVillage: RegionDef = {
  slug: "lambda-village",
  name: L("Lambda Village", "Aldea Lambda", "ラムダ村"),
  subtitle: L("expressions · types · lists · patterns", "expresiones · tipos · listas · patrones", "式・型・リスト・パターン"),
  theme: "village",
  lessons: [expressions, types, lists, patterns, boss],
};
