import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 3 · LAZY MOUNTAIN  (infinite lists, thunks and bottom, algebraic data types, Maybe and Either)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
const code = (...lines: string[]) => lines.join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const FOREVER = L("It runs forever", "Corre para siempre", "永遠に終わらない");
const CRASH_UNDEF = L("Crash: Prelude.undefined", "Crash: Prelude.undefined", "クラッシュ：Prelude.undefined");

// ─── 3.1 The endless staircase ─────────────────────────────────────────────
const infiniteLists: LessonDef = {
  slug: "infinite-lists",
  title: L("The endless staircase", "La escalera sin fin", "終わらない階段"),
  concept: "laziness",
  mode: "lesson",
  xp: 75,
  enemy: "haskell/thunk-pile",
  enemyName: L("STAIR THUNK", "THUNK ESCALERA", "カイダンサンク"),
  beats: [
    say(L(
      "Welcome to Lazy Mountain! Haskell is LAZY: it computes a value only when someone needs it. So a list can go on forever.",
      "¡Bienvenido a la Montaña Perezosa! Haskell es PEREZOSO: calcula un valor solo cuando alguien lo necesita. Así, una lista puede ser infinita.",
      "なまけ山へようこそ！Haskell は怠惰（レイジー）。必要になるまで値を計算しない。だからリストは無限にできる。",
    )),
    {
      kind: "act",
      prompt: L("Build an endless staircase, then climb 3 steps", "Crea una escalera sin fin y sube 3 escalones", "無限の階段を作って、3段のぼろう"),
      steps: [
        { label: L("ENDLESS", "SIN FIN", "むげん"), line: "let steps = [1..]",
          effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "steps", value: "[1,2,3,...]" }, { t: "say", actor: "hero", text: L("Still sealed!", "¡Sigue sellada!", "まだ封印中！") }] },
        { label: L("TAKE 3", "TOMAR 3", "3つ取る"), line: "print (take 3 steps)",
          effects: [{ t: "value", actor: "hero", text: "[1,2,3]" }, { t: "print", text: "[1,2,3]" }, { t: "attack", from: "hero", to: "enemy" }], output: "[1,2,3]" },
        { label: L("THE REST?", "¿EL RESTO?", "残りは？"),
          effects: [{ t: "say", actor: "enemy", text: L("Never opened!", "¡Nunca abierto!", "開けられてない！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (take 5 [1..])",
      options: ["[1,2,3,4,5]", "[1,2,3,4]", FOREVER],
      answer: 0,
      output: "[1,2,3,4,5]",
      check: { compiles: true, stdout: "[1,2,3,4,5]" },
      explain: L("take 5 asks for only five items, so only five are ever computed.", "take 5 pide solo cinco elementos, así que solo se calculan cinco.", "take 5 は5個だけ欲しがるから、計算されるのも5個だけ。"),
      win: [{ t: "print", text: "[1,2,3,4,5]" }],
    },
    say(L(
      "cycle repeats a list forever, repeat repeats one item, and iterate f x gives x, f x, f (f x)...",
      "cycle repite una lista sin fin, repeat repite un elemento e iterate f x da x, f x, f (f x)...",
      "cycle はリストを、repeat は1つの値を永遠にくり返す。iterate f x は x, f x, f (f x)... だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (take 4 (cycle \"ab\"), take 3 (repeat 'x'))",
      options: ['("abab","xxx")', '("ab","x")', '("abab","x")'],
      answer: 0,
      output: '("abab","xxx")',
      check: { compiles: true, stdout: '("abab","xxx")' },
      explain: L("cycle \"ab\" is abababab..., repeat 'x' is xxxx... take cuts each one.", "cycle \"ab\" es abababab..., repeat 'x' es xxxx... take corta cada una.", "cycle \"ab\" は abab...、repeat 'x' は xxx...。take で切り取るよ。"),
      win: [{ t: "print", text: '("abab","xxx")' }],
    },
    {
      kind: "pick",
      prompt: L("Double again and again", "Duplica una y otra vez", "何度も2倍にしよう"),
      code: "print (take 5 (___ (*2) 1))",
      options: ["iterate", "repeat", "cycle"],
      answer: 0,
      check: { compiles: true, stdout: "[1,2,4,8,16]", wrongFail: true },
      explain: L("iterate (*2) 1 gives 1, 2, 4, 8, 16... repeat and cycle take no function.", "iterate (*2) 1 da 1, 2, 4, 8, 16... repeat y cycle no reciben una función.", "iterate (*2) 1 は 1, 2, 4, 8, 16...。repeat と cycle は関数を受け取らない。"),
      win: [{ t: "print", text: "[1,2,4,8,16]" }],
    },
    say(L(
      "takeWhile stops at the first item that fails the test. filter would keep searching an endless list forever.",
      "takeWhile se detiene en el primer elemento que no pasa la prueba. filter seguiría buscando para siempre.",
      "takeWhile は条件に合わない最初の値で止まる。filter だと無限リストを永遠に探し続けるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (takeWhile (< 20) (map (^2) [1..]))",
      options: ["[1,4,9,16]", "[1,4,9,16,25]", FOREVER],
      answer: 0,
      output: "[1,4,9,16]",
      check: { compiles: true, stdout: "[1,4,9,16]" },
      explain: L("Squares are 1, 4, 9, 16, 25... At 25 the test fails, so takeWhile stops.", "Los cuadrados son 1, 4, 9, 16, 25... En 25 la prueba falla y takeWhile se detiene.", "2乗は 1, 4, 9, 16, 25...。25 で条件が外れて takeWhile が止まる。"),
      win: [{ t: "print", text: "[1,4,9,16]" }],
    },
    {
      kind: "pick",
      prompt: L("Which one finishes?", "¿Cuál termina?", "終わるのはどっち？"),
      code: "print (___ (< 5) [1..])",
      options: ["takeWhile", "filter"],
      answer: 0,
      check: { compiles: true, stdout: "[1,2,3,4]" },
      explain: L("filter compiles too, but after 4 it keeps checking 5, 6, 7... forever and never closes the list.", "filter también compila, pero tras 4 sigue revisando 5, 6, 7... para siempre y nunca cierra la lista.", "filter もコンパイルできるけど、4 のあと 5, 6, 7... と永遠に調べ続けて終わらない。"),
      win: [{ t: "print", text: "[1,2,3,4]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (head (filter (> 100) [1..]))",
      options: ["101", "100", FOREVER],
      answer: 0,
      output: "101",
      check: { compiles: true, stdout: "101" },
      explain: L("head needs only the FIRST match. Once 101 is found, nobody asks for more.", "head solo necesita la PRIMERA coincidencia. Al hallar 101, nadie pide más.", "head は最初の1個だけ必要。101 が見つかれば、それ以上はだれも求めない。"),
      win: [{ t: "print", text: "101" }],
    },
    say(L(
      "A lazy list can even be built from itself! fibs adds itself to its own tail, one step behind.",
      "¡Una lista perezosa puede construirse a sí misma! fibs se suma a su propia cola, un paso atrás.",
      "レイジーなリストは自分自身からも作れる！fibs は自分と、自分のしっぽを足していくよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "fibs :: [Integer]",
        "fibs = 0 : 1 : zipWith (+) fibs (tail fibs)",
        "",
        "main :: IO ()",
        "main = print (take 8 fibs)",
      ),
      options: ["[0,1,1,2,3,5,8,13]", "[0,1,2,3,4,5,6,7]", FOREVER],
      answer: 0,
      output: "[0,1,1,2,3,5,8,13]",
      check: { compiles: true, stdout: "[0,1,1,2,3,5,8,13]" },
      explain: L("Each item is the sum of the two before it. Only the 8 we take are computed.", "Cada elemento es la suma de los dos anteriores. Solo se calculan los 8 que tomamos.", "各値は前の2つの和。計算されるのは取り出した8個だけ。"),
      win: [{ t: "print", text: "[0,1,1,2,3,5,8,13]" }],
    },
    {
      kind: "type",
      prompt: L("Grab the first 3 steps", "Toma los 3 primeros escalones", "最初の3段を取ろう"),
      code: "print (___ 3 [7..])",
      answer: "take",
      check: { compiles: true, stdout: "[7,8,9]" },
      explain: L("take n xs keeps the first n items, even from an endless list.", "take n xs conserva los primeros n elementos, incluso de una lista infinita.", "take n xs は最初の n 個を取る。無限リストでも大丈夫。"),
      win: [{ t: "print", text: "[7,8,9]" }],
    },
    {
      kind: "run",
      prompt: L("Print the first five powers of two: [1,2,4,8,16]", "Imprime las cinco primeras potencias de dos: [1,2,4,8,16]", "2のべき乗を5個表示しよう：[1,2,4,8,16]"),
      starter: code("main :: IO ()", "main = print (take 5 (iterate (+2) 1))", ""),
      solution: code("main :: IO ()", "main = print (take 5 (iterate (*2) 1))", ""),
      expect: "[1,2,4,8,16]",
      fallback: [String.raw`iterate\s*\(\s*\*\s*2\s*\)\s*1`, String.raw`iterate\s*\(\s*2\s*\*\s*\)\s*1`, String.raw`map\s*\(\s*2\s*\^\s*\)`],
      explain: L("(+2) adds two each step; (*2) doubles: 1, 2, 4, 8, 16.", "(+2) suma dos en cada paso; (*2) duplica: 1, 2, 4, 8, 16.", "(+2) は毎回2を足す。(*2) なら2倍：1, 2, 4, 8, 16。"),
    },
  ],
};

// ─── 3.2 Sealed boxes and the wraith inside ────────────────────────────────
const thunks: LessonDef = {
  slug: "thunks-and-bottom",
  title: L("Sealed boxes", "Cajas selladas", "封印された箱"),
  concept: "laziness",
  mode: "lesson",
  xp: 75,
  enemy: "haskell/bottom-wraith",
  enemyName: L("BOX WRAITH", "ESPECTRO CAJA", "ハコのレイス"),
  beats: [
    say(L(
      "A value not computed yet is a sealed box: a THUNK. Haskell opens a box only when its value is really needed.",
      "Un valor aún no calculado es una caja sellada: un THUNK. Haskell abre la caja solo cuando de verdad necesita su valor.",
      "まだ計算されていない値は封印された箱、サンク。Haskell は本当に必要なときだけ箱を開ける。",
    )),
    say(L(
      "undefined is a cursed box: opening it crashes the program. But a box nobody opens is harmless!",
      "undefined es una caja maldita: abrirla hace fallar el programa. ¡Pero una caja que nadie abre es inofensiva!",
      "undefined は呪われた箱。開けるとプログラムがクラッシュ。でも、だれも開けなければ無害！",
    )),
    {
      kind: "act",
      prompt: L("Count the boxes, then open them all", "Cuenta las cajas y luego ábrelas todas", "箱を数えて、そのあと全部開けよう"),
      steps: [
        { label: L("3 BOXES", "3 CAJAS", "箱3つ"), line: "let xs = [1, undefined, 3] :: [Int]",
          effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "xs", value: "[?,?,?]" }] },
        { label: L("COUNT", "CONTAR", "数える"), line: "print (length xs)",
          effects: [{ t: "print", text: "3" }, { t: "say", actor: "hero", text: L("Counted, not opened", "Contadas, no abiertas", "数えただけ") }], output: "3" },
        { label: L("SUM", "SUMAR", "合計"), line: "print (sum xs)",
          effects: [{ t: "attack", from: "enemy", to: "hero" }, { t: "shake" }, { t: "banner", text: L("CURSED BOX!", "¡CAJA MALDITA!", "呪いの箱！") }],
          error: {
            compiler: "prog: Prelude.undefined",
            plain: L("sum must open every box, and the second one holds the wraith.", "sum debe abrir cada caja, y la segunda guarda al espectro.", "sum は全部の箱を開ける。2つ目にレイスがいた。"),
          } },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "let xs = [1, undefined, 3] :: [Int]\nprint (length xs)",
      options: ["3", CRASH_UNDEF, "2"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("length counts the boxes without opening them, so undefined is never touched.", "length cuenta las cajas sin abrirlas, así que undefined nunca se toca.", "length は箱を開けずに数える。undefined には触れないよ。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (fst (1, undefined), snd (undefined, "safe"))',
      options: ['(1,"safe")', CRASH_UNDEF],
      answer: 0,
      output: '(1,"safe")',
      check: { compiles: true, stdout: '(1,"safe")' },
      explain: L("fst only needs the first part and snd the second. The cursed halves stay sealed.", "fst solo necesita la primera parte y snd la segunda. Las mitades malditas siguen selladas.", "fst は前だけ、snd は後ろだけ使う。呪われた半分は封印されたまま。"),
      win: [{ t: "print", text: '(1,"safe")' }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'putStrLn "start"\nprint (sum [1, undefined, 3 :: Int])',
      options: [L("Prints start, then crashes", "Imprime start y luego falla", "start を表示してクラッシュ"), L("Prints start and 4", "Imprime start y 4", "start と 4 を表示"), L("Crashes before start", "Falla antes de start", "start の前にクラッシュ")],
      answer: 0,
      check: { compiles: true, throws: "Prelude.undefined" },
      explain: L("Steps run in order. putStrLn speaks first; then sum opens the cursed box.", "Los pasos corren en orden. putStrLn habla primero; luego sum abre la caja maldita.", "順番に実行される。まず putStrLn、そのあと sum が呪われた箱を開ける。"),
      win: [{ t: "print", text: "start" }, { t: "shake" }],
    },
    say(L(
      "error \"msg\" is a cursed box with YOUR message. Like undefined, it only crashes if someone opens it.",
      "error \"msg\" es una caja maldita con TU mensaje. Como undefined, solo falla si alguien la abre.",
      "error \"msg\" は自分のメッセージ入りの呪いの箱。undefined と同じく、開けたときだけ落ちる。",
    )),
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'let hp = 0 :: Int\nif hp <= 0 then error "hero fainted" else print hp',
      options: [L("Crash: hero fainted", "Crash: hero fainted", "クラッシュ：hero fainted"), "0", L("Does not compile", "No compila", "コンパイルできない")],
      answer: 0,
      check: { compiles: true, throws: "hero fainted" },
      explain: L("hp <= 0 is True, so the error branch is chosen and opened: it crashes with its message.", "hp <= 0 es True, así que se elige y se abre la rama error: falla con su mensaje.", "hp <= 0 が True なので error の分岐が開かれ、そのメッセージで落ちる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (length (map (\\x -> x `div` 0) [1,2,3]))",
      options: ["3", L("Crash: divide by zero", "Crash: divide by zero", "クラッシュ：divide by zero"), "0"],
      answer: 0,
      output: "3",
      check: { compiles: true, stdout: "3" },
      explain: L("map builds three sealed divisions. length counts them; no division ever runs.", "map arma tres divisiones selladas. length las cuenta; ninguna división se ejecuta.", "map は封印された割り算を3つ作るだけ。length は数えるだけで割り算は起きない。"),
      win: [{ t: "print", text: "3" }],
    },
    say(L(
      "seq a b opens the OUTER lid of a (weak head normal form), then returns b. Only the outer lid!",
      "seq a b abre la tapa EXTERIOR de a (forma normal débil de cabeza) y luego devuelve b. ¡Solo la exterior!",
      "seq a b は a の外側のふただけ開けて（弱頭部正規形）、b を返す。外側だけだよ！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (Just undefined `seq` "ok")',
      options: ['"ok"', CRASH_UNDEF],
      answer: 0,
      output: '"ok"',
      check: { compiles: true, stdout: '"ok"' },
      explain: L("seq only checks that the box is a Just. The wraith deeper inside stays sealed.", "seq solo comprueba que la caja es un Just. El espectro de adentro sigue sellado.", "seq は Just かどうかだけ確かめる。中のレイスは封印されたまま。"),
      win: [{ t: "print", text: '"ok"' }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: 'print (undefined `seq` "ok")',
      options: [CRASH_UNDEF, '"ok"'],
      answer: 0,
      check: { compiles: true, throws: "Prelude.undefined" },
      explain: L("Here the outer lid IS undefined, so opening it releases the wraith.", "Aquí la tapa exterior ES undefined, así que abrirla libera al espectro.", "今度は外側のふた自体が undefined。開けた瞬間レイスが出る。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Open the outer lid first", "Abre primero la tapa exterior", "まず外側のふたを開けよう"),
      code: 'print (___ (Just undefined) "ok")',
      answer: "seq",
      check: { compiles: true, stdout: '"ok"' },
      explain: L("seq a b is the prefix form of a `seq` b.", "seq a b es la forma prefija de a `seq` b.", "seq a b は a `seq` b の前置きの書き方。"),
      win: [{ t: "print", text: '"ok"' }],
    },
    say(L(
      "A bang ! on an accumulator opens its box at every step, so unopened sums never pile up.",
      "Un ! en un acumulador abre su caja en cada paso, así las sumas sin abrir nunca se apilan.",
      "アキュムレータに ! をつけると毎回箱を開ける。未計算の足し算が積み上がらない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "sumStrict :: [Int] -> Int",
        "sumStrict = go 0",
        "  where",
        "    go !acc [] = acc",
        "    go !acc (x:xs) = go (acc + x) xs",
        "",
        "main :: IO ()",
        "main = print (sumStrict [1..100])",
      ),
      options: ["5050", L("Does not compile", "No compila", "コンパイルできない"), "100"],
      answer: 0,
      output: "5050",
      check: { compiles: true, stdout: "5050" },
      explain: L("Bang patterns work out of the box in GHC 2021. The result is 1 + 2 + ... + 100.", "Los bang patterns funcionan directo en GHC 2021. El resultado es 1 + 2 + ... + 100.", "GHC2021 では ! パターンがそのまま使える。結果は 1 + 2 + ... + 100。"),
      win: [{ t: "print", text: "5050" }, { t: "attack", from: "hero", to: "enemy" }],
    },
    {
      kind: "run",
      prompt: L("Add only the first two scores; leave the cursed box sealed", "Suma solo los dos primeros puntajes; no abras la caja maldita", "最初の2つだけ足そう。呪いの箱は開けない"),
      starter: code("main :: IO ()", "main = do", "  let scores = [10, 20, undefined, 40] :: [Int]", "  print (sum scores)", ""),
      solution: code("main :: IO ()", "main = do", "  let scores = [10, 20, undefined, 40] :: [Int]", "  print (sum (take 2 scores))", ""),
      expect: "30",
      fallback: [String.raw`sum\s*\(\s*take\s+2\s+scores\s*\)`, String.raw`sum\s*\$\s*take\s+2\s+scores`],
      explain: L("take 2 hands sum only the first two boxes, so undefined is never opened.", "take 2 le da a sum solo las dos primeras cajas, así undefined nunca se abre.", "take 2 で最初の2箱だけ sum に渡す。undefined は開かれない。"),
    },
  ],
};

// ─── 3.3 Crafting your own items ───────────────────────────────────────────
const SHAPE = code(
  "data Shape = Circle Double | Rect Double Double",
  "  deriving Show",
  "",
  "area :: Shape -> Double",
  "area (Circle r) = 3 * r * r",
  "area (Rect w h) = w * h",
);
const HERO = 'data Hero = Hero { name :: String, hp :: Int }\n  deriving Show';
const COLOR = "data Color = Red | Green | Blue\n  deriving (Show, Eq, Ord, Enum, Bounded)";

const adts: LessonDef = {
  slug: "algebraic-data-types",
  title: L("Crafting your own items", "Forja tus propios objetos", "自分のアイテムを作ろう"),
  concept: "adts",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/partial-moth",
  enemyName: L("MOULD MOTH", "POLILLA MOLDE", "イガタモス"),
  beats: [
    say(L(
      "Time to craft your own types! data declares a type and its CONSTRUCTORS: the moulds that make its values.",
      "¡Hora de forjar tus propios tipos! data declara un tipo y sus CONSTRUCTORES: los moldes que crean sus valores.",
      "自分の型を作ろう！data は型と、その値を作る型枠、コンストラクタを宣言するよ。",
    )),
    {
      kind: "act",
      prompt: L("Forge a Shape type, then measure one", "Forja un tipo Shape y mide uno", "Shape 型を作って、面積を測ろう"),
      steps: [
        { label: L("MOULDS", "MOLDES", "型枠"), line: "data Shape = Circle Double | Rect Double Double",
          effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "Shape" }] },
        { label: L("SHOW BADGE", "INSIGNIA SHOW", "Show バッジ"), line: "  deriving Show",
          effects: [{ t: "say", actor: "hero", text: L("Now it can print", "Ya se puede imprimir", "表示できる！") }] },
        { label: L("CIRCLE", "CÍRCULO", "円"), line: "area (Circle r) = 3 * r * r" },
        { label: L("RECT", "RECT", "長方形"), line: "area (Rect w h) = w * h" },
        { label: L("MEASURE", "MEDIR", "測る"), line: "main = print (area (Rect 2 3))",
          effects: [{ t: "value", actor: "hero", text: "6.0" }, { t: "print", text: "6.0" }, { t: "attack", from: "hero", to: "enemy" }], output: "6.0" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: SHAPE + "\n\nmain :: IO ()\nmain = print (map area [Circle 1, Rect 2 3])",
      options: ["[3.0,6.0]", "[3,6]", "[Circle,Rect]"],
      answer: 0,
      output: "[3.0,6.0]",
      check: { compiles: true, stdout: "[3.0,6.0]" },
      explain: L("Each equation matches one constructor. Doubles print with a decimal point.", "Cada ecuación coincide con un constructor. Los Double se imprimen con punto decimal.", "各式が1つのコンストラクタに対応。Double は小数点つきで表示される。"),
      win: [{ t: "print", text: "[3.0,6.0]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: SHAPE + "\n\nmain :: IO ()\nmain = print (Rect 2 3)",
      options: ["Rect 2.0 3.0", "Rect 2 3", "6.0"],
      answer: 0,
      output: "Rect 2.0 3.0",
      check: { compiles: true, stdout: "Rect 2.0 3.0" },
      explain: L("deriving Show prints the constructor and its fields; the fields are Doubles.", "deriving Show imprime el constructor y sus campos; los campos son Double.", "deriving Show はコンストラクタとフィールドを表示。フィールドは Double。"),
      win: [{ t: "print", text: "Rect 2.0 3.0" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "data Shape = Circle Double\n\nmain :: IO ()\nmain = print (Circle 1)",
      options: [YES, L("No: Shape has no Show", "No: Shape no tiene Show", "いいえ：Shape に Show がない")],
      answer: 1,
      check: { compiles: false },
      explain: L("Without deriving Show, GHC says: No instance for 'Show Shape'.", "Sin deriving Show, GHC dice: No instance for 'Show Shape'.", "deriving Show がないと No instance for 'Show Shape' と言われる。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Record syntax names the fields, and each name becomes a getter function: hp h reads the hero's hp.",
      "La sintaxis de registro nombra los campos y cada nombre es una función lectora: hp h lee el hp del héroe.",
      "レコード構文ではフィールドに名前をつける。名前は取り出し関数になる。hp h で hp を読むよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: HERO + '\n\nmain :: IO ()\nmain = print (Hero { name = "Ada", hp = 10 })',
      options: ['Hero {name = "Ada", hp = 10}', 'Hero "Ada" 10', "Ada 10"],
      answer: 0,
      output: 'Hero {name = "Ada", hp = 10}',
      check: { compiles: true, stdout: 'Hero {name = "Ada", hp = 10}' },
      explain: L("A derived Show for a record prints the field names too.", "Un Show derivado de un registro también imprime los nombres de los campos.", "レコードの deriving Show はフィールド名も表示する。"),
      win: [{ t: "print", text: 'Hero {name = "Ada", hp = 10}' }],
    },
    say(L(
      "h { hp = 7 } builds a NEW hero with one field changed. The old hero never changes.",
      "h { hp = 7 } crea un héroe NUEVO con un campo cambiado. El héroe viejo nunca cambia.",
      "h { hp = 7 } はフィールドを1つ変えた新しいヒーローを作る。元のヒーローは変わらない。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: HERO + '\n\nmain :: IO ()\nmain = do\n  let h = Hero { name = "Ada", hp = 10 }\n  let h2 = h { hp = 7 }\n  print (hp h, hp h2)',
      options: ["(10,7)", "(7,7)", "(10,10)"],
      answer: 0,
      output: "(10,7)",
      check: { compiles: true, stdout: "(10,7)" },
      explain: L("Values never change. h2 is a copy with hp = 7; h still has 10.", "Los valores nunca cambian. h2 es una copia con hp = 7; h sigue con 10.", "値は変わらない。h2 は hp = 7 のコピーで、h は 10 のまま。"),
      setup: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "h", value: "10" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "h2", value: "7" }, { t: "print", text: "(10,7)" }],
    },
    say(L(
      "deriving gives more badges: Eq, Ord (in declaration order), Enum to count, Bounded for the first and last.",
      "deriving da más insignias: Eq, Ord (en orden de declaración), Enum para contar y Bounded para el primero y el último.",
      "deriving でほかのバッジも：Eq、Ord（宣言順）、数えられる Enum、最初と最後の Bounded。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: COLOR + "\n\nmain :: IO ()\nmain = print [minBound .. maxBound :: Color]",
      options: ["[Red,Green,Blue]", "[Blue,Green,Red]", "[Red,Blue]"],
      answer: 0,
      output: "[Red,Green,Blue]",
      check: { compiles: true, stdout: "[Red,Green,Blue]" },
      explain: L("minBound is the first constructor, maxBound the last; Enum fills in between.", "minBound es el primer constructor y maxBound el último; Enum completa el medio.", "minBound は最初、maxBound は最後のコンストラクタ。間は Enum が埋める。"),
      win: [{ t: "print", text: "[Red,Green,Blue]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: COLOR + "\n\nmain :: IO ()\nmain = print (Red < Blue, succ Red, fromEnum Blue)",
      options: ["(True,Green,2)", "(False,Green,3)", "(True,Blue,2)"],
      answer: 0,
      output: "(True,Green,2)",
      check: { compiles: true, stdout: "(True,Green,2)" },
      explain: L("Ord follows declaration order. succ is the next one, and fromEnum counts from 0.", "Ord sigue el orden de declaración. succ es el siguiente y fromEnum cuenta desde 0.", "Ord は宣言順。succ は次、fromEnum は 0 から数える。"),
      win: [{ t: "print", text: "(True,Green,2)" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "data Shape = Circle { radius :: Double }\n           | Square { side :: Double }\n\nmain :: IO ()\nmain = print (radius (Square 2))",
      options: [L("Crash: no match in radius", "Crash: no match in radius", "クラッシュ：radius 不一致"), "2.0", L("Does not compile", "No compila", "コンパイルできない")],
      answer: 0,
      check: { compiles: true, throws: "No match in record selector radius" },
      explain: L("A Square has no radius. The getter compiles but crashes: No match in record selector radius.", "Un Square no tiene radius. El lector compila pero falla: No match in record selector radius.", "Square に radius はない。コンパイルは通るが実行時に No match in record selector radius。"),
      win: [{ t: "shake" }, { t: "attack", from: "enemy", to: "hero" }],
    },
    {
      kind: "type",
      prompt: L("Hand out the badges", "Reparte las insignias", "バッジを配ろう"),
      code: "data Color = Red | Green ___ (Show, Eq)\n\nmain :: IO ()\nmain = print [Red, Green]",
      answer: "deriving",
      check: { compiles: true, stdout: "[Red,Green]" },
      explain: L("deriving (Show, Eq) asks GHC to write those instances for you.", "deriving (Show, Eq) le pide a GHC que escriba esas instancias por ti.", "deriving (Show, Eq) で GHC がインスタンスを書いてくれる。"),
      win: [{ t: "print", text: "[Red,Green]" }],
    },
    {
      kind: "run",
      prompt: L("A potion heals 5: it must print hp: 15", "Una poción cura 5: debe imprimir hp: 15", "ポーションで5回復：hp: 15 と表示させて"),
      starter: code(
        "data Hero = Hero { name :: String, hp :: Int } deriving Show",
        "",
        "heal :: Hero -> Hero",
        "heal h = h { hp = hp h }",
        "",
        "main :: IO ()",
        "main = do",
        '  let h = Hero { name = "Ada", hp = 10 }',
        '  putStrLn ("hp: " ++ show (hp (heal h)))',
        "",
      ),
      solution: code(
        "data Hero = Hero { name :: String, hp :: Int } deriving Show",
        "",
        "heal :: Hero -> Hero",
        "heal h = h { hp = hp h + 5 }",
        "",
        "main :: IO ()",
        "main = do",
        '  let h = Hero { name = "Ada", hp = 10 }',
        '  putStrLn ("hp: " ++ show (hp (heal h)))',
        "",
      ),
      expect: "hp: 15",
      fallback: [String.raw`hp\s*=\s*hp\s+h\s*\+\s*5`, String.raw`hp\s*=\s*5\s*\+\s*hp\s+h`],
      explain: L("The record update builds a new hero whose hp is the old hp plus 5.", "La actualización del registro crea un héroe nuevo con el hp viejo más 5.", "レコード更新で、hp が元の値 + 5 の新しいヒーローを作る。"),
    },
  ],
};

// ─── 3.4 Chests that may be empty ──────────────────────────────────────────
const SAFE_HEAD = "safeHead :: [a] -> Maybe a\nsafeHead [] = Nothing\nsafeHead (x:_) = Just x";
const SAFE_DIV = "safeDiv :: Int -> Int -> Either String Int\nsafeDiv _ 0 = Left \"divide by zero\"\nsafeDiv a b = Right (a `div` b)";

const maybeEither: LessonDef = {
  slug: "maybe-and-either",
  title: L("Chests that may be empty", "Cofres quizá vacíos", "空かもしれない宝箱"),
  concept: "maybe",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/partial-moth",
  enemyName: L("EMPTY CHEST MOTH", "POLILLA DEL COFRE", "カラバコモス"),
  beats: [
    say(L(
      "Haskell has no null. A value that may be missing is a Maybe: Nothing, or Just x. A chest, empty or with one item.",
      "Haskell no tiene null. Un valor que puede faltar es un Maybe: Nothing, o Just x. Un cofre vacío o con un objeto.",
      "Haskell に null はない。ないかもしれない値は Maybe：Nothing か Just x。空か、1つ入った宝箱だよ。",
    )),
    {
      kind: "act",
      prompt: L("Write a safe head that never crashes", "Escribe un head seguro que nunca falla", "クラッシュしない head を書こう"),
      steps: [
        { label: L("SIGNATURE", "FIRMA", "型シグネチャ"), line: "safeHead :: [a] -> Maybe a" },
        { label: L("EMPTY ROW", "FILA VACÍA", "空の列"), line: "safeHead [] = Nothing",
          effects: [{ t: "say", actor: "hero", text: L("Nothing here", "Aquí no hay nada", "何もない") }] },
        { label: L("ONE ITEM", "UN OBJETO", "1つある"), line: "safeHead (x:_) = Just x",
          effects: [{ t: "item", kind: "gem", holder: "hero" }] },
        { label: L("OPEN [3,4]", "ABRIR [3,4]", "[3,4] を開く"), line: "main = print (safeHead [3,4])",
          effects: [{ t: "value", actor: "hero", text: "Just 3" }, { t: "print", text: "Just 3" }, { t: "attack", from: "hero", to: "enemy" }], output: "Just 3" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: SAFE_HEAD + "\n\nmain :: IO ()\nmain = print (safeHead [] :: Maybe Int, safeHead [3,4])",
      options: ["(Nothing,Just 3)", "(Nothing,3)", L("Crash: empty list", "Crash: lista vacía", "クラッシュ：空リスト")],
      answer: 0,
      output: "(Nothing,Just 3)",
      check: { compiles: true, stdout: "(Nothing,Just 3)" },
      explain: L("The empty row gives Nothing instead of crashing; [3,4] gives the chest Just 3.", "La fila vacía da Nothing en vez de fallar; [3,4] da el cofre Just 3.", "空の列はクラッシュせず Nothing、[3,4] は宝箱 Just 3。"),
      win: [{ t: "print", text: "(Nothing,Just 3)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (lookup "b" [("a",1),("b",2)], lookup "z" [("a",1)])',
      options: ["(Just 2,Nothing)", "(2,0)", "(Just 2,Just 0)"],
      answer: 0,
      output: "(Just 2,Nothing)",
      check: { compiles: true, stdout: "(Just 2,Nothing)" },
      explain: L("lookup searches a list of pairs and answers with a Maybe: the key may be missing.", "lookup busca en una lista de pares y responde con un Maybe: la clave puede faltar.", "lookup はペアのリストを探して Maybe で答える。キーがないかもしれないから。"),
      win: [{ t: "print", text: "(Just 2,Nothing)" }],
    },
    say(L(
      "To open a chest, use case, or maybe d f m, or fromMaybe d m. Each one says what to do when it is empty.",
      "Para abrir un cofre usa case, maybe d f m o fromMaybe d m. Cada uno dice qué hacer si está vacío.",
      "宝箱を開けるには case、maybe d f m、fromMaybe d m。どれも空のときの対応を決める。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (case lookup \'z\' [(\'a\', "owl")] of\n  Nothing -> "missing"\n  Just v -> v)',
      options: ['"missing"', '"owl"', L("Crash", "Crash", "クラッシュ")],
      answer: 0,
      output: '"missing"',
      check: { compiles: true, stdout: '"missing"' },
      explain: L("There is no 'z', so lookup gives Nothing and the first branch answers.", "No hay 'z', así que lookup da Nothing y responde la primera rama.", "'z' はないので lookup は Nothing、最初の分岐が答える。"),
      win: [{ t: "print", text: '"missing"' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "import Data.Maybe (fromMaybe)\n\nmain :: IO ()\nmain = print (maybe 0 (+1) (Just 5), maybe 0 (+1) Nothing, fromMaybe 0 Nothing)",
      options: ["(6,0,0)", "(5,0,0)", "(6,1,0)"],
      answer: 0,
      output: "(6,0,0)",
      check: { compiles: true, stdout: "(6,0,0)" },
      explain: L("maybe d f applies f to a Just and gives d for Nothing; fromMaybe d just unwraps or gives d.", "maybe d f aplica f a un Just y da d con Nothing; fromMaybe d desenvuelve o da d.", "maybe d f は Just なら f を適用、Nothing なら d。fromMaybe d は中身か d。"),
      win: [{ t: "print", text: "(6,0,0)" }],
    },
    say(L(
      "Either e a carries a REASON: Left err for failure, Right x for success. Right is right!",
      "Either e a lleva una RAZÓN: Left err para el fallo, Right x para el éxito. ¡Right es lo correcto!",
      "Either e a は理由を運ぶ。失敗は Left err、成功は Right x。Right は「正しい」！",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: SAFE_DIV + "\n\nmain :: IO ()\nmain = print (safeDiv 10 2, safeDiv 1 0)",
      options: ['(Right 5,Left "divide by zero")', "(5,0)", L("Crash: divide by zero", "Crash: divide by zero", "クラッシュ：divide by zero")],
      answer: 0,
      output: '(Right 5,Left "divide by zero")',
      check: { compiles: true, stdout: '(Right 5,Left "divide by zero")' },
      explain: L("Dividing by 0 never happens: the 0 case answers Left with the reason.", "Nunca se divide entre 0: el caso 0 responde Left con la razón.", "0 で割ることはない。0 の場合は理由つきの Left を返す。"),
      win: [{ t: "print", text: '(Right 5,Left "divide by zero")' }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: "print (Just (3 :: Int) + 1)",
      options: [L("Yes: Just 4", "Sí: Just 4", "はい：Just 4"), L("No: a Maybe Int is not an Int", "No: un Maybe Int no es un Int", "いいえ：Maybe Int は Int じゃない")],
      answer: 1,
      check: { compiles: false },
      explain: L("You must open the chest first. GHC: No instance for 'Num (Maybe Int)'.", "Primero hay que abrir el cofre. GHC: No instance for 'Num (Maybe Int)'.", "先に宝箱を開けないとダメ。GHC：No instance for 'Num (Maybe Int)'。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: "import Data.Maybe (fromJust)\n\nmain :: IO ()\nmain = print (fromJust (Nothing :: Maybe Int))",
      options: [L("Crash: fromJust Nothing", "Crash: fromJust Nothing", "クラッシュ：fromJust Nothing"), "0", "Nothing"],
      answer: 0,
      check: { compiles: true, throws: "fromJust" },
      explain: L("fromJust smashes the chest open. An empty one crashes: Maybe.fromJust: Nothing.", "fromJust rompe el cofre. Si está vacío, falla: Maybe.fromJust: Nothing.", "fromJust は宝箱を壊して開ける。空なら Maybe.fromJust: Nothing で落ちる。"),
      win: [{ t: "shake" }, { t: "attack", from: "enemy", to: "hero" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'import Text.Read (readMaybe)\n\nmain :: IO ()\nmain = print (readMaybe "42" :: Maybe Int, readMaybe "4x" :: Maybe Int)',
      options: ["(Just 42,Nothing)", "(42,0)", L("Crash: no parse", "Crash: no parse", "クラッシュ：no parse")],
      answer: 0,
      output: "(Just 42,Nothing)",
      check: { compiles: true, stdout: "(Just 42,Nothing)" },
      explain: L("readMaybe is the safe read: bad text gives Nothing instead of crashing.", "readMaybe es el read seguro: un texto malo da Nothing en vez de fallar.", "readMaybe は安全な read。読めない文字列はクラッシュせず Nothing。"),
      win: [{ t: "print", text: "(Just 42,Nothing)" }],
    },
    {
      kind: "type",
      prompt: L("An empty row has no head", "Una fila vacía no tiene cabeza", "空の列に先頭はない"),
      code: "safeHead :: [a] -> Maybe a\nsafeHead [] = ___\nsafeHead (x:_) = Just x\n\nmain :: IO ()\nmain = print (safeHead ([] :: [Int]))",
      answer: "Nothing",
      check: { compiles: true, stdout: "Nothing" },
      explain: L("Nothing is the empty chest: the honest answer for an empty list.", "Nothing es el cofre vacío: la respuesta honesta para una lista vacía.", "Nothing は空の宝箱。空リストへの正直な答え。"),
      win: [{ t: "print", text: "Nothing" }],
    },
    {
      kind: "run",
      prompt: L('Dividing by 0 must give Left "cannot divide by zero"', 'Dividir entre 0 debe dar Left "cannot divide by zero"', '0 で割ったら Left "cannot divide by zero" に'),
      starter: code(
        "safeDiv :: Int -> Int -> Either String Int",
        "safeDiv _ 0 = Right 0",
        "safeDiv a b = Right (a `div` b)",
        "",
        "main :: IO ()",
        "main = print (safeDiv 7 0)",
        "",
      ),
      solution: code(
        "safeDiv :: Int -> Int -> Either String Int",
        'safeDiv _ 0 = Left "cannot divide by zero"',
        "safeDiv a b = Right (a `div` b)",
        "",
        "main :: IO ()",
        "main = print (safeDiv 7 0)",
        "",
      ),
      expect: 'Left "cannot divide by zero"',
      fallback: [String.raw`safeDiv\s+_\s+0\s*=\s*Left\s+"cannot divide by zero"`],
      explain: L("Right 0 is a silent wrong answer. Left carries the reason the division failed.", "Right 0 es una respuesta incorrecta silenciosa. Left lleva la razón del fallo.", "Right 0 は静かな間違い。Left なら失敗の理由を運べる。"),
    },
  ],
};

// ─── Boss: The Bottom Wraith ───────────────────────────────────────────────
const boss: LessonDef = {
  slug: "mountain-boss",
  title: L("Boss: The Bottom Wraith", "Jefe: El Espectro Bottom", "ボス：ボトムのレイス"),
  concept: "laziness",
  mode: "boss",
  xp: 170,
  enemy: "haskell/bottom-wraith",
  enemyName: L("BOTTOM WRAITH", "ESPECTRO BOTTOM", "ボトムのレイス"),
  beats: [
    enemySays(L(
      "I AM THE BOTTOM WRAITH. I sleep in sealed boxes and empty chests. Open the wrong one and I am free!",
      "SOY EL ESPECTRO BOTTOM. Duermo en cajas selladas y cofres vacíos. ¡Abre la equivocada y seré libre!",
      "我はボトムのレイス。封印の箱と空の宝箱に眠る。まちがった箱を開ければ、我は自由だ！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "print (null [undefined], length [undefined, undefined], head [1, undefined])", options: ["(False,2,1)", CRASH_UNDEF, "(True,2,1)"], answer: 0, output: "(False,2,1)", check: { compiles: true, stdout: "(False,2,1)" }, explain: L("null, length and head never open the cursed boxes.", "null, length y head nunca abren las cajas malditas.", "null も length も head も呪いの箱は開けない。"), win: [{ t: "print", text: "(False,2,1)" }] },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (take 3 (map (*10) [1..]))", options: ["[10,20,30]", FOREVER, "[1,2,3]"], answer: 0, output: "[10,20,30]", check: { compiles: true, stdout: "[10,20,30]" }, explain: L("map is lazy too: only three items are ever multiplied.", "map también es perezoso: solo se multiplican tres.", "map もレイジー。かけ算されるのは3個だけ。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "fibs :: [Integer]\nfibs = 0 : 1 : zipWith (+) fibs (tail fibs)\n\nmain :: IO ()\nmain = print (fibs !! 50)", options: ["12586269025", FOREVER, "50"], answer: 0, output: "12586269025", check: { compiles: true, stdout: "12586269025" }, explain: L("!! walks to item 50; each one is computed once and shared.", "!! camina hasta el elemento 50; cada uno se calcula una vez.", "!! は50番目まで進む。各値は一度だけ計算される。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: 'let d = 0 :: Int\nprint (10 `div` d)', options: [L("Crash: divide by zero", "Crash: divide by zero", "クラッシュ：divide by zero"), "0", "Infinity"], answer: 0, check: { compiles: true, throws: "divide by zero" }, explain: L("print needs the value, so the division runs and crashes.", "print necesita el valor, así que la división corre y falla.", "print が値を必要とするので割り算が実行され落ちる。"), win: [{ t: "shake" }] },
    { kind: "predict", time: 15, prompt: PRINT, code: "data Point = Point Int Int deriving (Show, Eq)\n\nmain :: IO ()\nmain = print (Point 1 2 == Point 1 2, Point 1 2)", options: ["(True,Point 1 2)", "(False,Point 1 2)", L("Does not compile", "No compila", "コンパイルできない")], answer: 0, output: "(True,Point 1 2)", check: { compiles: true, stdout: "(True,Point 1 2)" }, explain: L("Derived Eq compares field by field; derived Show prints them.", "El Eq derivado compara campo por campo; Show los imprime.", "deriving Eq はフィールドごとに比べ、Show が表示する。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "data Tree = Leaf | Node Tree Int Tree\n\ntotal :: Tree -> Int\ntotal Leaf = 0\ntotal (Node l v r) = total l + v + total r\n\nmain :: IO ()\nmain = print (total (Node (Node Leaf 1 Leaf) 2 Leaf))", options: ["3", "2", "1"], answer: 0, output: "3", check: { compiles: true, stdout: "3" }, explain: L("A type can contain itself: a tree. total adds 1 + 2.", "Un tipo puede contenerse a sí mismo: un árbol. total suma 1 + 2.", "型は自分を含められる：木。total は 1 + 2。") },
    { kind: "predict", time: 15, prompt: PRINT, code: 'import Data.Maybe (mapMaybe)\nimport Text.Read (readMaybe)\n\nmain :: IO ()\nmain = print (mapMaybe (\\s -> readMaybe s :: Maybe Int) ["1","x","3"])', options: ["[1,3]", "[Just 1,Nothing,Just 3]", L("Crash: no parse", "Crash: no parse", "クラッシュ：no parse")], answer: 0, output: "[1,3]", check: { compiles: true, stdout: "[1,3]" }, explain: L("mapMaybe keeps the Just results and drops each Nothing.", "mapMaybe conserva los Just y descarta cada Nothing.", "mapMaybe は Just だけ残し Nothing を捨てる。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: 'print (read "abc" :: Int)', options: [L("Crash: no parse", "Crash: no parse", "クラッシュ：no parse"), "0", "Nothing"], answer: 0, check: { compiles: true, throws: "no parse" }, explain: L("read is partial: bad text crashes. readMaybe is the safe one.", "read es parcial: un texto malo falla. readMaybe es el seguro.", "read は部分関数。安全なのは readMaybe。"), win: [{ t: "shake" }] },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (either length negate (Left \"abc\" :: Either String Int))", options: ["3", "-3", '"abc"'], answer: 0, output: "3", check: { compiles: true, stdout: "3" }, explain: L("either f g uses f on a Left and g on a Right.", "either f g usa f con Left y g con Right.", "either f g は Left に f、Right に g。") },
    { kind: "type", time: 12, prompt: L("A failure with a reason", "Un fallo con razón", "理由つきの失敗"), code: 'check :: Int -> Either String Int\ncheck n = if n < 0 then ___ "negative" else Right n\n\nmain :: IO ()\nmain = print (check (-1))', answer: "Left", check: { compiles: true, stdout: 'Left "negative"' }, explain: L("Left holds the error scroll; Right the good item.", "Left guarda el pergamino de error; Right el objeto bueno.", "Left はエラーの巻物、Right はよいアイテム。") },
    enemySays(L(
      "No... you opened only what you needed, and every empty chest had a plan. The tower above awaits.",
      "No... abriste solo lo necesario y cada cofre vacío tenía un plan. La torre de arriba te espera.",
      "ばかな…必要な箱だけ開け、空の宝箱にも備えていたとは。上の塔が待っているぞ。",
    )),
  ],
};

export const lazyMountain: RegionDef = {
  slug: "lazy-mountain",
  name: L("Lazy Mountain", "Montaña Perezosa", "なまけ山"),
  subtitle: L("Laziness · thunks · data · Maybe", "Pereza · thunks · data · Maybe", "遅延評価・サンク・data・Maybe"),
  theme: "mountain",
  lessons: [infiniteLists, thunks, adts, maybeEither, boss],
};
