import type { Beat, LessonDef, NoteBlock, NoteDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 4 · MONAD TOWER  (type classes, Functor and Applicative, Monad and do, IO and Data.Map)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
const code = (...lines: string[]) => lines.join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO = L("No: GHC stops it", "No: GHC lo detiene", "いいえ：GHC が止める");
const NO_COMPILE = L("Does not compile", "No compila", "コンパイルできない");
const MAP = "import qualified Data.Map as M\n\nmain :: IO ()\nmain = do\n";

// Guidebook notes: long explanations players can reopen from any question (📖).
// Examples use names and values different from the questions so they never give an answer away.
const note = (id: string, title: Text, ...blocks: NoteBlock[]): NoteDef => ({ id, title, blocks });
const p = (en: string, es: string, ja: string): NoteBlock => ({ t: "p", text: L(en, es, ja) });
/** A runnable example; the validator checks `output` against the real compiler. */
const ex = (src: string, output: string, caption?: Text): NoteBlock => ({ t: "code", code: src, output, caption });
/** An example that must NOT compile (verified too). */
const bad = (src: string, caption: Text): NoteBlock => ({ t: "code", code: src, caption, check: { compiles: false } });
/** An example that compiles and then crashes with a message containing `msg` (verified too). */
const crash = (src: string, msg: string, caption: Text): NoteBlock => ({ t: "code", code: src, caption, check: { compiles: true, throws: msg } });

// ─── 4.1 Badges for types ──────────────────────────────────────────────────
const classNotes: NoteDef[] = [
  note("classes-instances", L("Type classes and instances", "Clases de tipos e instancias", "型クラスとインスタンス"),
    p(
      "A type class is a named list of operations, called methods, with their types: class Describable a where describe :: a -> String. It is a promise: every type that has an instance of the class supports those operations.",
      "Una clase de tipos es una lista con nombre de operaciones, llamadas métodos, con sus tipos: class Describable a where describe :: a -> String. Es una promesa: todo tipo que tenga una instancia de la clase soporta esas operaciones.",
      "型クラスは、メソッドと呼ばれる操作とその型に名前をつけた一覧：class Describable a where describe :: a -> String。これは約束で、そのクラスのインスタンスを持つ型はどれもその操作が使える。",
    ),
    p(
      "An instance supplies the code for one type: instance Describable Bool where ... When you call the method, GHC picks the instance from the type of the argument, at compile time.",
      "Una instancia aporta el código para un tipo: instance Describable Bool where ... Cuando llamas al método, GHC elige la instancia según el tipo del argumento, al compilar.",
      "インスタンスは1つの型のためのコードを書く：instance Describable Bool where ...。メソッドを呼ぶと、GHC は引数の型を見て、コンパイル時にインスタンスを選ぶ。",
    ),
    ex("class Loud a where\n  shout :: a -> String\ninstance Loud Int where\n  shout n = show n ++ \"!\"\ninstance Loud Char where\n  shout c = [c, c, c]\n\nmain :: IO ()\nmain = putStrLn (shout (5 :: Int) ++ \" \" ++ shout 'z')", "5! zzz",
      L("Each type gets its own code for the same method", "Cada tipo tiene su propio código para el mismo método", "同じメソッドでも型ごとに別のコード")),
    p(
      "Standard classes work the same way: Show provides show, Eq provides == and /=, Ord provides compare and <. You can derive them, or write the instance yourself to choose the behavior, such as a custom show.",
      "Las clases estándar funcionan igual: Show aporta show, Eq aporta == y /=, Ord aporta compare y <. Puedes derivarlas o escribir la instancia tú mismo para elegir el comportamiento, como un show propio.",
      "標準のクラスも同じ。Show は show、Eq は == と /=、Ord は compare や < を提供する。deriving でもらうか、インスタンスを自分で書いて、show などの動きを決められる。",
    ),
    ex('data Coin = Coin Int\n\ninstance Show Coin where\n  show (Coin n) = show n ++ " gold"\n\nmain :: IO ()\nmain = print [Coin 2, Coin 7]', "[2 gold,7 gold]",
      L("A hand-written Show decides the text", "Un Show escrito a mano decide el texto", "手書きの Show が表示を決める")),
    p(
      "Rule: a type can have only one instance of each class. Deriving Show AND writing instance Show is a Duplicate instance declarations error: pick one. Also, each method belongs to one class, so you write show inside a Show instance, not an Eq one.",
      "Regla: un tipo solo puede tener una instancia de cada clase. Derivar Show Y escribir instance Show da el error Duplicate instance declarations: elige uno. Además, cada método pertenece a una clase, así que show se escribe dentro de una instancia de Show, no de Eq.",
      "ルール：1つの型が持てるのは各クラスにつき1つのインスタンスだけ。deriving Show と instance Show を両方書くと Duplicate instance declarations。どちらか1つに。また、メソッドは1つのクラスに属する。show を書くのは Show のインスタンスで、Eq ではない。",
    ),
    bad("data Gem = Gem deriving Eq\ninstance Eq Gem where\n  _ == _ = True\n\nmain :: IO ()\nmain = print (Gem == Gem)",
      L("Does not compile: Gem would have two Eq instances", "No compila: Gem tendría dos instancias Eq", "コンパイル不可：Gem に Eq が2つ")),
  ),
  note("constraints-ord", L("Constraints and derived Ord", "Restricciones y Ord derivado", "制約と導出された Ord"),
    p(
      "A constraint in a signature asks for a class: bigger :: Ord a => a -> a -> a works for any type a that has an Ord instance. Before => come the requirements; after it, the normal type. Inside, you may use only what the class provides, like > and <.",
      "Una restricción en una firma pide una clase: bigger :: Ord a => a -> a -> a sirve para cualquier tipo a con instancia de Ord. Antes de => van los requisitos; después, el tipo normal. Adentro solo puedes usar lo que la clase aporta, como > y <.",
      "シグネチャの制約はクラスを求める。bigger :: Ord a => a -> a -> a は Ord のインスタンスを持つどの型 a にも使える。=> の前が条件、後ろがふつうの型。中ではクラスが提供する > や < だけが使える。",
    ),
    ex('bigger :: Ord a => a -> a -> a\nbigger x y = if x > y then x else y\n\nmain :: IO ()\nmain = print (bigger 3 8, bigger "cat" "car")', '(8,"cat")',
      L("One function, any type that has Ord", "Una función para cualquier tipo con Ord", "Ord を持つどの型にも使える関数")),
    p(
      "Derived Eq compares constructors and then fields; lists are equal only with the same items in the same order. Derived Ord orders constructors in declaration order, the first is smallest. compare a b answers LT, EQ or GT, and maximum and minimum rely on Ord.",
      "El Eq derivado compara constructores y luego campos; las listas son iguales solo con los mismos elementos en el mismo orden. El Ord derivado ordena los constructores en orden de declaración; el primero es el menor. compare a b responde LT, EQ o GT, y maximum y minimum usan Ord.",
      "導出された Eq はコンストラクタ、次にフィールドを比べる。リストは同じ要素が同じ順番のときだけ等しい。導出された Ord は宣言順で、最初が一番小さい。compare a b は LT、EQ、GT で答え、maximum や minimum も Ord を使う。",
    ),
    ex("data Rank = Bronze | Silver | Gold deriving (Eq, Ord, Show)\n\nmain :: IO ()\nmain = print (minimum [Gold, Bronze, Silver], compare Gold Silver)", "(Bronze,GT)"),
    p(
      "Constraints are checked at compile time: calling bigger on a type without Ord does not compile. Common mistake: reading compare backwards. compare a b describes a relative to b, so LT means a is the smaller one.",
      "Las restricciones se revisan al compilar: llamar a bigger con un tipo sin Ord no compila. Error común: leer compare al revés. compare a b describe a respecto de b, así que LT significa que a es el menor.",
      "制約はコンパイル時にチェックされる。Ord のない型で bigger を呼ぶとコンパイルできない。よくあるミス：compare を逆に読むこと。compare a b は b から見た a のことで、LT なら a のほうが小さい。",
    ),
  ),
  note("newtype", L("newtype: a new name, a new type", "newtype: nombre nuevo, tipo nuevo", "newtype：新しい名前の新しい型"),
    p(
      "newtype Meters = Meters Double creates a brand-new type with exactly one constructor and one field. At runtime it is just the Double, with no extra cost, but for the type checker Meters and Double, or Meters and another wrapper, are different types.",
      "newtype Meters = Meters Double crea un tipo totalmente nuevo con exactamente un constructor y un campo. En ejecución es solo el Double, sin costo extra, pero para el verificador de tipos Meters y Double, o Meters y otro envoltorio, son tipos distintos.",
      "newtype Meters = Meters Double は、コンストラクタ1つ・フィールド1つのまったく新しい型を作る。実行時はただの Double でコストはないが、型チェッカーにとって Meters と Double、Meters とほかの包みは別の型。",
    ),
    p(
      "That is the point: a function that takes one wrapper rejects another, even if both hold a Double. Mixing units becomes a compile error instead of a silent bug. To use the value inside, pattern match on the constructor.",
      "Esa es la idea: una función que recibe un envoltorio rechaza otro, aunque ambos guarden un Double. Mezclar unidades se vuelve un error de compilación en vez de un fallo silencioso. Para usar el valor de adentro, haz pattern matching con el constructor.",
      "それが狙い。ある包みを受け取る関数は、中身が同じ Double でも別の包みを拒否する。単位の取り違えが、静かなバグではなくコンパイルエラーになる。中の値を使うにはコンストラクタでパターンマッチする。",
    ),
    ex("newtype Seconds = Seconds Int\n\ndouble :: Seconds -> Seconds\ndouble (Seconds s) = Seconds (s * 2)\n\nmain :: IO ()\nmain = let Seconds t = double (Seconds 21) in print t", "42",
      L("Unwrap with a pattern, work, wrap again", "Desenvuelve con un patrón, calcula y vuelve a envolver", "パターンで取り出し、計算して、また包む")),
    bad("newtype Gold = Gold Int\nnewtype Silver = Silver Int\n\nspend :: Gold -> Int\nspend (Gold g) = g\n\nmain :: IO ()\nmain = print (spend (Silver 5))",
      L("Does not compile: Silver is not Gold", "No compila: Silver no es Gold", "コンパイル不可：Silver は Gold ではない")),
    p(
      "Common mistake: thinking the same thing inside means the same type. It does not. Also remember that newtype allows exactly one constructor with one field; for anything bigger, use data.",
      "Error común: pensar que lo mismo adentro significa el mismo tipo. No es así. Recuerda también que newtype permite exactamente un constructor con un campo; para algo más grande, usa data.",
      "よくある誤解：中身が同じなら同じ型だと思うこと。違う。また newtype はコンストラクタ1つ・フィールド1つだけ。それより大きいものには data を使おう。",
    ),
  ),
  note("semigroup-monoid", L("Semigroup and Monoid: joining values", "Semigroup y Monoid: unir valores", "Semigroup と Monoid：値をつなぐ"),
    p(
      "Semigroup is the class of types whose values can be joined with <>. For lists and strings, <> is the same as ++. Joining must be associative: (a <> b) <> c equals a <> (b <> c), so the grouping never changes the result.",
      "Semigroup es la clase de los tipos cuyos valores se pueden unir con <>. Para listas y strings, <> es lo mismo que ++. La unión debe ser asociativa: (a <> b) <> c es igual a a <> (b <> c), así que la agrupación nunca cambia el resultado.",
      "Semigroup は <> で値をつなげる型のクラス。リストと文字列では <> は ++ と同じ。つなぎ方は結合的でなければならない。(a <> b) <> c と a <> (b <> c) は等しく、まとめ方で結果は変わらない。",
    ),
    p(
      "Monoid adds mempty, the empty value that changes nothing when joined: [] for lists and \"\" for strings. mconcat joins a whole list of values, starting from mempty.",
      "Monoid agrega mempty, el valor vacío que no cambia nada al unirse: [] para listas y \"\" para strings. mconcat une toda una lista de valores, empezando desde mempty.",
      "Monoid は mempty を加える。つないでも何も変えない空の値で、リストなら []、文字列なら \"\"。mconcat は mempty から始めて、値のリスト全体をつなぐ。",
    ),
    ex('print ([4, 5] <> [6], "sun" <> "set", mconcat [[1], [2, 3], []])', '([4,5,6],"sunset",[1,2,3])',
      L("For lists and strings, joining means appending", "Para listas y strings, unir es concatenar", "リストと文字列では、つなぐ＝連結")),
    p(
      "Other types join in their own way: Maybe joins the insides of two Justs and skips a Nothing. So <> is not always addition; it depends on the type's instance. Common mistake: expecting <> on two lists of numbers to add the numbers.",
      "Otros tipos unen a su manera: Maybe une el interior de dos Just y salta un Nothing. Así que <> no siempre es suma; depende de la instancia del tipo. Error común: esperar que <> con dos listas de números sume los números.",
      "ほかの型は独自のつなぎ方をする。Maybe は2つの Just の中身をつなぎ、Nothing は飛ばす。<> はいつも足し算ではなく、型のインスタンス次第。よくあるミス：数のリスト同士の <> で数が足されると思うこと。",
    ),
    ex('print (Just "ab" <> Just "cd", Nothing <> Just [3])', '(Just "abcd",Just [3])',
      L("Maybe joins what is inside and skips Nothing", "Maybe une lo de adentro y salta Nothing", "Maybe は中身をつなぎ Nothing を飛ばす")),
  ),
  note("read-types", L("read needs a result type", "read necesita un tipo de resultado", "read には結果の型が必要"),
    p(
      "read turns text into a value: read \"42\" could become an Int, a Double, or any type with a Read instance. The text alone does not decide; the type does. So GHC must know which type you want before it can compile the call.",
      "read convierte texto en un valor: read \"42\" podría ser un Int, un Double o cualquier tipo con instancia de Read. El texto solo no decide; decide el tipo. Por eso GHC debe saber qué tipo quieres antes de poder compilar la llamada.",
      "read は文字列を値に変える。read \"42\" は Int にも Double にも、Read のインスタンスを持つどの型にもなれる。決めるのは文字列ではなく型。だから GHC はどの型が欲しいかわからないとコンパイルできない。",
    ),
    p(
      "If nothing fixes the type, for example when the result goes straight to show or print, which accept many types, GHC reports an ambiguous type and refuses to compile. Add an annotation like :: Int, or use the result somewhere only one type fits.",
      "Si nada fija el tipo, por ejemplo cuando el resultado va directo a show o print, que aceptan muchos tipos, GHC informa un tipo ambiguo y se niega a compilar. Agrega una anotación como :: Int, o usa el resultado donde solo encaje un tipo.",
      "型を決めるものがないと、たとえば多くの型を受け取る show や print に直接渡すと、GHC はあいまいな型だと言ってコンパイルを拒む。:: Int のような注釈をつけるか、型が1つに決まる場所で使おう。",
    ),
    bad('putStrLn (show (read "3"))',
      L("Does not compile: read what type?", "No compila: ¿read de qué tipo?", "コンパイル不可：何の型として read？")),
    ex('print (read "7" :: Double, read "[1,2]" :: [Int])', "(7.0,[1,2])",
      L("The annotation picks the type, and the type picks the parser", "La anotación elige el tipo y el tipo elige cómo leer", "注釈が型を決め、型が読み方を決める")),
    p(
      "Common mistake: forgetting that read is also partial. Text that does not fit the type crashes at runtime with no parse. readMaybe from Text.Read returns Nothing instead.",
      "Error común: olvidar que read también es parcial. Un texto que no encaja con el tipo falla al ejecutar con no parse. readMaybe de Text.Read devuelve Nothing en su lugar.",
      "よくあるミス：read が部分関数でもあることを忘れること。型に合わない文字列は実行時に no parse で落ちる。Text.Read の readMaybe なら Nothing を返す。",
    ),
  ),
];

const typeClasses: LessonDef = {
  slug: "type-classes",
  notes: classNotes,
  title: L("Badges for types", "Insignias para tipos", "型のためのバッジ"),
  concept: "typeclasses",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/thunk-pile",
  enemyName: L("BADGE THIEF", "LADRÓN DE INSIGNIAS", "バッジドロボウ"),
  beats: [
    say(L(
      "Welcome to Monad Tower! A TYPE CLASS is a badge: it lists operations, and any type wearing it supports them.",
      "¡Bienvenido a la Torre Mónada! Una CLASE DE TIPOS es una insignia: lista operaciones y todo tipo que la lleva las soporta.",
      "モナドの塔へようこそ！型クラスはバッジ。操作の一覧で、バッジをつけた型はそれが使える。",
    )),
    {
      kind: "act",
      prompt: L("Design a badge, then give it to Bool", "Diseña una insignia y dásela a Bool", "バッジを作って Bool に渡そう"),
      steps: [
        { label: L("THE BADGE", "LA INSIGNIA", "バッジ"), line: "class Describable a where",
          effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "Describable" }] },
        { label: L("ITS RULE", "SU REGLA", "ルール"), line: "  describe :: a -> String" },
        { label: L("FOR Bool", "PARA Bool", "Bool 用"), line: "instance Describable Bool where",
          effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Bool" }, { t: "give", to: "ally" }] },
        { label: L("True", "True", "True"), line: '  describe True = "yes"' },
        { label: L("False", "False", "False"), line: '  describe False = "no"' },
        { label: L("USE IT", "USARLA", "使う"), line: "main = putStrLn (describe True)",
          effects: [{ t: "say", actor: "ally", text: L("yes", "yes", "yes") }, { t: "print", text: "yes" }, { t: "attack", from: "ally", to: "enemy" }], output: "yes" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "class Describable a where",
        "  describe :: a -> String",
        "instance Describable Bool where",
        '  describe True = "yes"',
        '  describe False = "no"',
        "",
        "main :: IO ()",
        "main = putStrLn (describe (1 > 2))",
      ),
      options: ["no", "yes", NO_COMPILE],
      answer: 0,
      output: "no",
      check: { compiles: true, stdout: "no" },
      hint: L("What type is 1 > 2, and what value? That picks the instance, and then which equation matches.", "¿De qué tipo es 1 > 2 y qué valor tiene? Eso elige la instancia y luego la ecuación que coincide.", "1 > 2 の型と値は？それでインスタンスが決まり、合う式も決まる。"),
      note: "classes-instances",
      explain: L("1 > 2 is False, a Bool, so the Bool instance answers \"no\".", "1 > 2 es False, un Bool, así que responde la instancia de Bool: \"no\".", "1 > 2 は False（Bool）。Bool のインスタンスが \"no\" と答える。"),
      win: [{ t: "print", text: "no" }],
    },
    say(L(
      "You already met badges: Show, Eq, Ord. deriving hands them out for free, or you write the instance yourself.",
      "Ya conoces insignias: Show, Eq, Ord. deriving las reparte gratis, o puedes escribir la instancia tú mismo.",
      "Show、Eq、Ord もバッジ。deriving で自動でもらえるし、インスタンスを自分で書いてもいい。",
    )),
    {
      kind: "pick",
      prompt: L("Which badge lets it print?", "¿Qué insignia permite imprimir?", "表示できるバッジは？"),
      code: 'data Owl = Owl\ninstance ___ Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print [Owl, Owl]',
      options: ["Show", "Eq", "Print"],
      answer: 0,
      check: { compiles: true, stdout: "[hoot,hoot]", wrongFail: true },
      hint: L("The instance defines a method called show. Which class does that method belong to?", "La instancia define un método llamado show. ¿A qué clase pertenece ese método?", "インスタンスは show というメソッドを定義している。そのメソッドはどのクラスのもの？"),
      note: "classes-instances",
      explain: L("show belongs to the Show class. Eq has no show, and there is no Print class.", "show pertenece a la clase Show. Eq no tiene show, y no existe una clase Print.", "show は Show クラスのもの。Eq に show はないし、Print クラスもない。"),
      win: [{ t: "print", text: "[hoot,hoot]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "data Size = S | M | L deriving (Eq, Ord, Show)\n\nmain :: IO ()\nmain = print (maximum [M, S, L], compare S L, S < M)",
      options: ["(L,LT,True)", "(M,GT,False)", "(L,GT,True)"],
      answer: 0,
      output: "(L,LT,True)",
      check: { compiles: true, stdout: "(L,LT,True)" },
      hint: L("Derived Ord follows declaration order. compare a b tells how a relates to b.", "El Ord derivado sigue el orden de declaración. compare a b dice cómo se relaciona a con b.", "導出された Ord は宣言順。compare a b は b から見た a の関係を答える。"),
      note: "constraints-ord",
      explain: L("Derived Ord follows declaration order: S < M < L. compare answers LT, EQ or GT.", "El Ord derivado sigue el orden de declaración: S < M < L. compare responde LT, EQ o GT.", "deriving Ord は宣言順：S < M < L。compare は LT、EQ、GT で答える。"),
      win: [{ t: "print", text: "(L,LT,True)" }],
    },
    say(L(
      "A constraint asks for a badge: same :: Eq a => a -> a -> Bool works for ANY type that wears Eq.",
      "Una restricción pide una insignia: same :: Eq a => a -> a -> Bool sirve para CUALQUIER tipo con Eq.",
      "制約はバッジを求める。same :: Eq a => a -> a -> Bool は Eq を持つどの型にも使える。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "same :: Eq a => a -> a -> Bool\nsame x y = x == y\n\nmain :: IO ()\nmain = print (same 'a' 'a', same [1,2] [2,1])",
      options: ["(True,False)", "(True,True)", NO_COMPILE],
      answer: 0,
      output: "(True,False)",
      check: { compiles: true, stdout: "(True,False)" },
      hint: L("Both calls use ==. Are two lists with the same items in a different order equal?", "Ambas llamadas usan ==. ¿Dos listas con los mismos elementos en otro orden son iguales?", "どちらも == を使う。同じ要素で順番が違うリストは等しい？"),
      note: "constraints-ord",
      explain: L("Char and lists both wear Eq. Lists are equal only in the same order.", "Char y las listas llevan Eq. Las listas son iguales solo en el mismo orden.", "Char もリストも Eq を持つ。リストは順番まで同じときだけ等しい。"),
      win: [{ t: "print", text: "(True,False)" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'data Owl = Owl deriving Show\ninstance Show Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print Owl',
      options: [YES, L("No: two Show badges", "No: dos insignias Show", "いいえ：Show が2つ")],
      answer: 1,
      check: { compiles: false },
      hint: L("Count the ways Owl receives Show here. How many instances of one class may a type have?", "Cuenta de cuántas formas recibe Owl la clase Show aquí. ¿Cuántas instancias de una clase puede tener un tipo?", "Owl が Show をもらう方法をいくつ書いた？1つの型が持てる同じクラスのインスタンスは何個？"),
      note: "classes-instances",
      explain: L("A type gets each badge only once: Duplicate instance declarations.", "Un tipo recibe cada insignia una sola vez: Duplicate instance declarations.", "バッジは1つの型に1回だけ。Duplicate instance declarations になる。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "newtype wraps one value in a NEW type, at no runtime cost. Meters and Feet can't be mixed up.",
      "newtype envuelve un valor en un tipo NUEVO, sin costo en ejecución. Meters y Feet no se pueden mezclar.",
      "newtype は値1つを新しい型で包む。実行時コストはゼロ。Meters と Feet は混ざらない。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: code(
        "newtype Meters = Meters Double",
        "newtype Feet = Feet Double",
        "",
        "climb :: Meters -> Double",
        "climb (Meters m) = m",
        "",
        "main :: IO ()",
        "main = print (climb (Feet 3))",
      ),
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      hint: L("Both wrap a Double, but are the two newtypes the same type to GHC?", "Ambos envuelven un Double, pero ¿los dos newtype son el mismo tipo para GHC?", "どちらも Double を包んでいるが、GHC にとって2つの newtype は同じ型？"),
      note: "newtype",
      explain: L("Same Double inside, different types outside: Couldn't match 'Meters' with 'Feet'.", "Mismo Double adentro, tipos distintos afuera: Couldn't match 'Meters' with 'Feet'.", "中身は同じ Double でも型は別。Couldn't match 'Meters' with 'Feet'。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Semigroup gives <> to join two values. Monoid adds mempty, the empty one, and mconcat joins a whole list.",
      "Semigroup da <> para unir dos valores. Monoid agrega mempty, el vacío, y mconcat une toda una lista.",
      "Semigroup の <> は2つをつなぐ。Monoid には空の mempty と、リストをまとめる mconcat がある。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print ([1] <> [2], "ab" <> "cd", mconcat ["a","b","c"])',
      options: ['([1,2],"abcd","abc")', '([3],"abcd","abc")', NO_COMPILE],
      answer: 0,
      output: '([1,2],"abcd","abc")',
      check: { compiles: true, stdout: '([1,2],"abcd","abc")' },
      hint: L("For lists and strings, does <> add or join? mconcat applies that to a whole list.", "Para listas y strings, ¿<> suma o une? mconcat lo aplica a toda una lista.", "リストと文字列の <> は足す？つなぐ？mconcat はそれをリスト全体に使う。"),
      note: "semigroup-monoid",
      explain: L("For lists and strings, <> is ++ and mconcat joins them all.", "Para listas y strings, <> es ++ y mconcat las une todas.", "リストと文字列では <> は ++。mconcat は全部つなぐ。"),
      win: [{ t: "print", text: '([1,2],"abcd","abc")' }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'print (read "5")',
      options: [L("Yes: prints 5", "Sí: imprime 5", "はい：5 と表示"), L("No: read what type?", "No: ¿read de qué tipo?", "いいえ：何の型を read？")],
      answer: 1,
      check: { compiles: false },
      hint: L("read can produce many types. Does anything in this line tell GHC which one you want?", "read puede producir muchos tipos. ¿Algo en esta línea le dice a GHC cuál quieres?", "read はいろいろな型を作れる。この行に、どの型か GHC に伝えるものはある？"),
      note: "read-types",
      explain: L("read needs a known result type. Add one: read \"5\" :: Int.", "read necesita conocer el tipo del resultado. Agrégalo: read \"5\" :: Int.", "read は結果の型が必要。read \"5\" :: Int のように書こう。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "run",
      prompt: L("Shop labels must read: potion x3", "Las etiquetas deben decir: potion x3", "値札は potion x3 と表示させて"),
      starter: code("data Potion = Potion Int deriving Show", "", "main :: IO ()", "main = print (Potion 3)", ""),
      solution: code("data Potion = Potion Int", "", "instance Show Potion where", '  show (Potion n) = "potion x" ++ show n', "", "main :: IO ()", "main = print (Potion 3)", ""),
      expect: "potion x3",
      fallback: [String.raw`instance\s+Show\s+Potion\s+where`],
      hint: L("deriving Show prints the constructor. To choose the text yourself, what do you write instead of deriving?", "deriving Show imprime el constructor. Para elegir el texto tú mismo, ¿qué escribes en lugar de deriving?", "deriving Show はコンストラクタを表示する。表示を自分で決めるには、deriving の代わりに何を書く？"),
      note: "classes-instances",
      explain: L("Remove deriving Show and write the instance yourself: show (Potion n) = \"potion x\" ++ show n.", "Quita deriving Show y escribe la instancia: show (Potion n) = \"potion x\" ++ show n.", "deriving Show を消して自分で書こう：show (Potion n) = \"potion x\" ++ show n。"),
    },
  ],
};

// ─── 4.2 Reaching into chests ──────────────────────────────────────────────
const functorNotes: NoteDef[] = [
  note("functor", L("Functor and fmap", "Functor y fmap", "Functor と fmap"),
    p(
      "fmap f x applies f to the value or values inside a container x and keeps the container's shape. For a list, fmap is map. For Maybe, Just v becomes Just (f v), and Nothing stays Nothing because there is nothing to apply f to.",
      "fmap f x aplica f al valor o valores dentro de un contenedor x y conserva la forma del contenedor. Para una lista, fmap es map. Para Maybe, Just v se vuelve Just (f v), y Nothing sigue siendo Nothing porque no hay nada a qué aplicar f.",
      "fmap f x は入れ物 x の中の値に f を当て、入れ物の形はそのまま保つ。リストなら fmap は map と同じ。Maybe なら Just v は Just (f v) になり、Nothing は f を当てる中身がないので Nothing のまま。",
    ),
    ex("print (fmap (* 3) [1, 2], fmap (* 3) (Just 5), fmap (* 3) (Nothing :: Maybe Int))", "([3,6],Just 15,Nothing)",
      L("Same function, three containers, shapes kept", "La misma función en tres contenedores; formas intactas", "同じ関数、3つの入れ物、形はそのまま")),
    p(
      "<$> is fmap written as an operator: f <$> x means exactly fmap f x. You will see it everywhere, especially together with <*> from Applicative.",
      "<$> es fmap escrito como operador: f <$> x significa exactamente fmap f x. Lo verás en todas partes, sobre todo junto con <*> de Applicative.",
      "<$> は fmap の演算子版。f <$> x は fmap f x とまったく同じ意味。とくに Applicative の <*> と一緒によく見かける。",
    ),
    ex('print (length <$> Just "moon")', "Just 4"),
    p(
      "For Either e, fmap changes only a Right; a Left, the error, passes through untouched. For a pair (a, b), fmap changes only the second part: the first component counts as part of the shape, just like the Left of an Either.",
      "Para Either e, fmap cambia solo un Right; un Left, el error, pasa intacto. Para un par (a, b), fmap cambia solo la segunda parte: el primer componente cuenta como parte de la forma, igual que el Left de un Either.",
      "Either e の fmap が変えるのは Right だけ。エラーの Left はそのまま通る。ペア (a, b) では2つ目だけが変わる。1つ目は Either の Left と同じく、形の一部とみなされる。",
    ),
    ex('print (fmap show (Right 7 :: Either String Int), fmap negate ("tag", 5))', '(Right "7",("tag",-5))',
      L("Right and the second part of a pair are the items inside", "Right y la segunda parte del par son lo de adentro", "Right とペアの2つ目が中身")),
    p(
      "Common mistakes: expecting fmap on a pair to change both parts, or expecting fmap to fix a Nothing or a Left. fmap never changes the shape: same number of items, same constructor.",
      "Errores comunes: esperar que fmap en un par cambie ambas partes, o que fmap arregle un Nothing o un Left. fmap nunca cambia la forma: mismo número de elementos, mismo constructor.",
      "よくあるミス：ペアの fmap で両方が変わると思うこと、fmap が Nothing や Left を直すと思うこと。fmap は形を変えない。要素の数もコンストラクタも同じまま。",
    ),
  ),
  note("applicative", L("Applicative: combining containers", "Applicative: combinar contenedores", "Applicative：入れ物を組み合わせる"),
    p(
      "fmap works with one container. To combine several, use Applicative: f <$> a <*> b applies a two-argument function f to the values inside a and b. For Maybe, if both are Just you get Just (f x y); if any of them is Nothing, the result is Nothing.",
      "fmap trabaja con un contenedor. Para combinar varios, usa Applicative: f <$> a <*> b aplica una función de dos argumentos f a los valores dentro de a y b. Para Maybe, si ambos son Just obtienes Just (f x y); si alguno es Nothing, el resultado es Nothing.",
      "fmap は入れ物1つ用。複数を組み合わせるなら Applicative：f <$> a <*> b は2引数の関数 f を a と b の中身に当てる。Maybe なら両方 Just のとき Just (f x y)、どれかが Nothing なら結果も Nothing。",
    ),
    ex("print (max <$> Just 4 <*> Just 9, max <$> Nothing <*> Just (9 :: Int))", "(Just 9,Nothing)"),
    p(
      "For Either it is similar, but the first Left wins: once a Left appears, the rest is not examined and that Left becomes the result, message included.",
      "Con Either es parecido, pero gana el primer Left: en cuanto aparece un Left, el resto no se examina y ese Left se vuelve el resultado, mensaje incluido.",
      "Either も似ているが、最初の Left が勝つ。Left が出たら残りは調べられず、その Left がメッセージごと結果になる。",
    ),
    ex('print ((*) <$> Right 6 <*> (Right 7 :: Either String Int), (*) <$> Right 6 <*> (Left "oops" :: Either String Int))', '(Right 42,Left "oops")'),
    p(
      "For lists, <*> tries every combination: each item of the first list with each item of the second, in order. The first list is the outer loop and the second the inner loop.",
      "Para listas, <*> prueba cada combinación: cada elemento de la primera lista con cada elemento de la segunda, en orden. La primera lista es el bucle exterior y la segunda el interior.",
      "リストの <*> は全組み合わせを試す。1つ目のリストの各要素と、2つ目の各要素を順に組む。1つ目が外側のループ、2つ目が内側のループ。",
    ),
    ex("print ((-) <$> [10, 20] <*> [1, 2])", "[9,8,19,18]",
      L("10 with 1 and 2, then 20 with 1 and 2", "10 con 1 y 2, luego 20 con 1 y 2", "10 と 1, 2、次に 20 と 1, 2")),
    p(
      "The function decides what the result holds, and its types must fit the values: (+) needs two numbers of the same type, while a tuple constructor can pair values of different types. Common mistake: forgetting that a single empty container empties the whole result.",
      "La función decide qué contiene el resultado, y sus tipos deben encajar con los valores: (+) necesita dos números del mismo tipo, mientras que un constructor de tuplas puede emparejar valores de tipos distintos. Error común: olvidar que un solo contenedor vacío vacía todo el resultado.",
      "結果の中身は関数で決まり、その型は値に合わなければならない。(+) は同じ型の数2つが必要だが、タプルのコンストラクタなら違う型の値も組める。よくあるミス：空の入れ物が1つあれば結果全体が空になるのを忘れること。",
    ),
  ),
];

const functors: LessonDef = {
  slug: "functor-and-applicative",
  notes: functorNotes,
  title: L("Reaching into chests", "Metiendo la mano en cofres", "宝箱に手をのばす"),
  concept: "functor",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/partial-moth",
  enemyName: L("LID MOTH", "POLILLA TAPA", "フタモス"),
  beats: [
    say(L(
      "fmap reaches INTO a chest, changes the item, and closes the lid. The chest keeps its shape; an empty one stays empty.",
      "fmap mete la mano EN el cofre, cambia el objeto y cierra la tapa. El cofre conserva su forma; uno vacío sigue vacío.",
      "fmap は宝箱の中に手を入れて中身を変え、ふたを閉める。形はそのまま、空の箱は空のまま。",
    )),
    {
      kind: "act",
      prompt: L("Reach into chests with fmap", "Mete la mano en cofres con fmap", "fmap で宝箱に手を入れよう"),
      steps: [
        { label: L("JUST 2", "JUST 2", "Just 2"), line: "print (fmap (+1) (Just 2))",
          effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "Just", value: "3" }, { t: "print", text: "Just 3" }], output: "Just 3" },
        { label: L("NOTHING", "NOTHING", "Nothing"), line: "print (fmap (+1) Nothing)",
          effects: [{ t: "say", actor: "hero", text: L("Still empty", "Sigue vacío", "空のまま") }, { t: "print", text: "Nothing" }], output: "Nothing" },
        { label: L("A LIST", "UNA LISTA", "リスト"), line: "print ((+1) <$> [1,2,3])",
          effects: [{ t: "print", text: "[2,3,4]" }, { t: "attack", from: "hero", to: "enemy" }], output: "[2,3,4]" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (fmap (+1) (Just 2), fmap (+1) Nothing)",
      options: ["(Just 3,Nothing)", "(3,Nothing)", "(Just 3,Just 1)"],
      answer: 0,
      output: "(Just 3,Nothing)",
      check: { compiles: true, stdout: "(Just 3,Nothing)" },
      hint: L("fmap changes what is inside and keeps the chest's shape. What is inside Nothing?", "fmap cambia lo de adentro y conserva la forma del cofre. ¿Qué hay dentro de Nothing?", "fmap は中身を変え、箱の形は保つ。Nothing の中身は？"),
      note: "functor",
      explain: L("fmap changes what is inside. Nothing has nothing inside, so it stays Nothing.", "fmap cambia lo de adentro. Nothing no tiene nada adentro, así que sigue Nothing.", "fmap は中身を変える。Nothing は中身がないので Nothing のまま。"),
      win: [{ t: "print", text: "(Just 3,Nothing)" }],
    },
    {
      kind: "type",
      prompt: L("The operator form of fmap", "La forma operador de fmap", "fmap の演算子版"),
      code: "print ((+1) ___ Just 2)",
      answer: "<$>",
      check: { compiles: true, stdout: "Just 3" },
      hint: L("You need the operator version of fmap, the one often seen right before <*>.", "Necesitas la versión operador de fmap, la que suele verse justo antes de <*>.", "fmap の演算子版じゃ。<*> の前によく出てくるもの。"),
      note: "functor",
      explain: L("f <$> x is just fmap f x written as an operator.", "f <$> x es fmap f x escrito como operador.", "f <$> x は fmap f x の演算子版。"),
      win: [{ t: "print", text: "Just 3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (fmap length (Right "abc" :: Either String String))\nprint (fmap length (Left "e" :: Either String String))',
      options: [L("Right 3, then Left \"e\"", "Right 3, luego Left \"e\"", "Right 3、次に Left \"e\""), L("Right 3, then Left 1", "Right 3, luego Left 1", "Right 3、次に Left 1")],
      answer: 0,
      output: 'Right 3\nLeft "e"',
      check: { compiles: true, stdout: 'Right 3\nLeft "e"' },
      hint: L("For Either, which side does fmap change? The other side passes through exactly as it is.", "Para Either, ¿qué lado cambia fmap? El otro lado pasa exactamente como está.", "Either の fmap が変えるのはどっち側？もう片方はそのまま通る。"),
      note: "functor",
      explain: L("fmap only touches the Right side. A Left error passes through unchanged.", "fmap solo toca el lado Right. Un error Left pasa sin cambios.", "fmap が触るのは Right だけ。Left のエラーはそのまま通る。"),
      win: [{ t: "print", text: "Right 3" }, { t: "print", text: 'Left "e"' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (fmap (+1) (10, 20))",
      options: ["(10,21)", "(11,21)", "(11,20)"],
      answer: 0,
      output: "(10,21)",
      check: { compiles: true, stdout: "(10,21)" },
      hint: L("For a pair, only one part counts as the item inside the chest. Which one?", "En un par, solo una parte cuenta como el objeto dentro del cofre. ¿Cuál?", "ペアでは、箱の中身とみなされるのは片方だけ。どっち？"),
      note: "functor",
      explain: L("For a pair, the chest's item is the SECOND part. The first is part of the shape.", "En un par, el objeto del cofre es la SEGUNDA parte. La primera es parte de la forma.", "ペアでは中身は2つ目。1つ目は箱の形の一部だよ。"),
      win: [{ t: "print", text: "(10,21)" }],
    },
    say(L(
      "Applicative combines SEVERAL chests: f <$> a <*> b. If any chest is empty, the result is empty too.",
      "Applicative combina VARIOS cofres: f <$> a <*> b. Si alguno está vacío, el resultado también.",
      "Applicative は複数の宝箱を組み合わせる：f <$> a <*> b。どれか空なら結果も空。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((+) <$> Just 3 <*> Just 4, (+) <$> Just 3 <*> Nothing)",
      options: ["(Just 7,Nothing)", "(Just 7,Just 3)", "(7,Nothing)"],
      answer: 0,
      output: "(Just 7,Nothing)",
      check: { compiles: true, stdout: "(Just 7,Nothing)" },
      hint: L("The function runs only when every chest is full. What if one of them is empty?", "La función solo corre si todos los cofres están llenos. ¿Y si uno está vacío?", "関数が動くのは全部の箱に中身があるときだけ。1つが空なら？"),
      note: "applicative",
      explain: L("Both chests full: 3 + 4 inside a Just. One empty chest makes the whole result Nothing.", "Ambos llenos: 3 + 4 dentro de un Just. Un cofre vacío hace que todo sea Nothing.", "両方あれば Just の中で 3 + 4。1つでも空なら全体が Nothing。"),
      win: [{ t: "print", text: "(Just 7,Nothing)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((+) <$> [1,2] <*> [10,20])",
      options: ["[11,21,12,22]", "[11,22]", "[11,12,21,22]"],
      answer: 0,
      output: "[11,21,12,22]",
      check: { compiles: true, stdout: "[11,21,12,22]" },
      hint: L("Lists try every combination: the first item on the left with each item on the right, then the next.", "Las listas prueban cada combinación: el primer elemento de la izquierda con cada uno de la derecha, luego el siguiente.", "リストは全組み合わせ。左の最初の要素と右の各要素、そのあと左の次の要素。"),
      note: "applicative",
      explain: L("Lists try every combination: 1 with 10 and 20, then 2 with 10 and 20.", "Las listas prueban cada combinación: 1 con 10 y 20, luego 2 con 10 y 20.", "リストは全組み合わせ。1 と 10, 20、次に 2 と 10, 20。"),
      win: [{ t: "print", text: "[11,21,12,22]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print ((+) <$> Left "a" <*> (Left "b" :: Either String Int))',
      options: ['Left "a"', 'Left "b"', 'Left "ab"'],
      answer: 0,
      output: 'Left "a"',
      check: { compiles: true, stdout: 'Left "a"' },
      hint: L("With Either, when there are several Lefts, which one decides the result?", "Con Either, cuando hay varios Left, ¿cuál decide el resultado?", "Either で Left が複数あるとき、結果を決めるのはどれ？"),
      note: "applicative",
      explain: L("With Either, the FIRST Left wins and the rest is never looked at.", "Con Either gana el PRIMER Left y el resto ni se mira.", "Either では最初の Left が勝ち、残りは見られない。"),
      win: [{ t: "print", text: 'Left "a"' }],
    },
    {
      kind: "pick",
      prompt: L("Pair up two chests", "Empareja dos cofres", "2つの宝箱をペアに"),
      code: 'print (___ <$> Just 1 <*> Just "a")',
      options: ["(,)", "(+)"],
      answer: 0,
      check: { compiles: true, stdout: 'Just (1,"a")', wrongFail: true },
      hint: L("The result must hold a number and a String together. Which function can combine different types?", "El resultado debe guardar un número y un String juntos. ¿Qué función puede combinar tipos distintos?", "結果は数と String を一緒に持つ。違う型を組み合わせられる関数は？"),
      note: "applicative",
      explain: L("(,) builds a pair from two values. (+) can't add a number to a String.", "(,) arma un par con dos valores. (+) no puede sumar un número a un String.", "(,) は2つの値からペアを作る。(+) で数と String は足せない。"),
      win: [{ t: "print", text: 'Just (1,"a")' }],
    },
    {
      kind: "run",
      prompt: L("Add the apple and the pear: Just 7", "Suma la manzana y la pera: Just 7", "りんごとなしを足そう：Just 7"),
      starter: code(
        "main :: IO ()",
        "main = do",
        '  let prices = [("apple", 3), ("pear", 4)]',
        '  print ((+) <$> lookup "apple" prices <*> lookup "peach" prices)',
        "",
      ),
      solution: code(
        "main :: IO ()",
        "main = do",
        '  let prices = [("apple", 3), ("pear", 4)]',
        '  print ((+) <$> lookup "apple" prices <*> lookup "pear" prices)',
        "",
      ),
      expect: "Just 7",
      fallback: [String.raw`lookup\s+"pear"\s+prices`],
      hint: L("One lookup comes back empty. Check each key against the price list.", "Un lookup vuelve vacío. Revisa cada clave contra la lista de precios.", "lookup の1つが空で返ってくる。各キーを価格リストと見比べよう。"),
      note: "applicative",
      explain: L("There is no peach, so one chest was empty and the result was Nothing.", "No hay durazno, así que un cofre estaba vacío y el resultado fue Nothing.", "peach はないので宝箱が1つ空になり、結果が Nothing だった。"),
    },
  ],
};

// ─── 4.3 A chain of chests ─────────────────────────────────────────────────
const TABLE = 'table :: [(Int, String)]\ntable = [(1, "lam"), (2, "bda")]';

const monadNotes: NoteDef[] = [
  note("bind", L("Monads and >>= (bind)", "Mónadas y >>= (bind)", "モナドと >>=（バインド）"),
    p(
      "A monad lets you chain steps where each step returns a value in a context, like a Maybe chest. m >>= f opens m, passes its value to f, and f returns the next chest. The result is not wrapped twice: f already returns a chest, and that chest is the result.",
      "Una mónada permite encadenar pasos donde cada paso devuelve un valor en un contexto, como un cofre Maybe. m >>= f abre m, pasa su valor a f, y f devuelve el siguiente cofre. El resultado no se envuelve dos veces: f ya devuelve un cofre, y ese cofre es el resultado.",
      "モナドは、Maybe の宝箱のように文脈つきの値を返す処理をつなぐしくみ。m >>= f は m を開けて中身を f に渡し、f が次の箱を返す。二重には包まれない。f が返す箱がそのまま結果になる。",
    ),
    ex("print (Just 6 >>= \\k -> Just (k + 1))", "Just 7"),
    p(
      "If m is Nothing, there is no value to pass, so f never runs and the whole chain is Nothing. This is short-circuiting: the first failure stops every step after it. That makes >>= perfect for chaining functions that may fail.",
      "Si m es Nothing, no hay valor que pasar, así que f nunca corre y toda la cadena es Nothing. Esto es cortocircuito: el primer fallo detiene todos los pasos siguientes. Por eso >>= es perfecto para encadenar funciones que pueden fallar.",
      "m が Nothing なら渡す値がないので f は動かず、くさり全体が Nothing。これがショートで、最初の失敗がその後の全部を止める。だから >>= は失敗するかもしれない関数をつなぐのにぴったり。",
    ),
    ex("half :: Int -> Maybe Int\nhalf x = if even x then Just (x `div` 2) else Nothing\n\nmain :: IO ()\nmain = print (Just 12 >>= half >>= half, Just 12 >>= half >>= half >>= half)", "(Just 3,Nothing)",
      L("12, 6, 3, and then 3 is odd: the chain stops", "12, 6, 3, y luego 3 es impar: la cadena para", "12、6、3、そして3は奇数でくさりが止まる")),
    p(
      "Why not fmap? Using fmap with a function that returns a chest gives a chest inside a chest, like Just (Just 5). >>= is for functions that themselves return a chest. For lists, >>= applies the function to each item and joins the resulting lists.",
      "¿Por qué no fmap? Usar fmap con una función que devuelve un cofre da un cofre dentro de otro, como Just (Just 5). >>= es para funciones que ya devuelven un cofre. Para listas, >>= aplica la función a cada elemento y une las listas resultantes.",
      "なぜ fmap ではない？箱を返す関数に fmap を使うと、Just (Just 5) のように箱の中に箱ができる。>>= は自分で箱を返す関数のためのもの。リストの >>= は各要素に関数を当て、できたリストをつなぐ。",
    ),
    ex("print (\"ab\" >>= \\c -> [c, '-'])", "\"a-b-\"",
      L("List >>= turns each item into a list, then joins them", ">>= de listas vuelve cada elemento una lista y las une", "各要素をリストにしてつなぐ")),
  ),
  note("do-notation", L("do notation", "Notación do", "do 記法"),
    p(
      "do is a friendlier way to write >>= chains. Each line x <- m opens m and names its value x for the lines below. The last line gives the result of the whole block, and must itself be a chest, such as return v or Just v.",
      "do es una forma más amable de escribir cadenas de >>=. Cada línea x <- m abre m y llama x a su valor para las líneas de abajo. La última línea da el resultado de todo el bloque y debe ser un cofre, como return v o Just v.",
      "do は >>= のくさりを読みやすく書く方法。x <- m の行は m を開けて、中身に x という名前をつけ、下の行で使えるようにする。最後の行がブロック全体の結果で、return v や Just v のような箱でなければならない。",
    ),
    ex('ages :: [(String, Int)]\nages = [("ann", 30), ("bo", 12)]\n\nmain :: IO ()\nmain = print (do { a <- lookup "ann" ages; b <- lookup "bo" ages; return (a + b) })', "Just 42",
      L("Both lookups succeed, so return wraps the sum", "Ambos lookup funcionan y return envuelve la suma", "両方の lookup が成功し return が和を包む")),
    p(
      "In Maybe, if any line's chest is Nothing, the whole block is Nothing and the lines after it do not run. In Either, the first Left stops the block and becomes its result, keeping its message.",
      "En Maybe, si el cofre de cualquier línea es Nothing, todo el bloque es Nothing y las líneas siguientes no corren. En Either, el primer Left detiene el bloque y se vuelve su resultado, conservando su mensaje.",
      "Maybe では、どれかの行の箱が Nothing ならブロック全体が Nothing になり、その後の行は動かない。Either では最初の Left がブロックを止め、メッセージごと結果になる。",
    ),
    ex('pos :: Int -> Either String Int\npos n = if n > 0 then Right n else Left ("not positive: " ++ show n)\n\nmain :: IO ()\nmain = print (do { a <- pos 5; b <- pos (-2); c <- pos 0; return (a + b + c) })', 'Left "not positive: -2"',
      L("The first Left stops the block; pos 0 is never checked", "El primer Left detiene el bloque; pos 0 ni se revisa", "最初の Left で止まり pos 0 は調べられない")),
    p(
      "return is NOT like return in other languages: it does not exit. It only wraps a value in a chest, so return 5 is Just 5 in Maybe. A return in the middle of a block makes a chest that is thrown away; the block continues and the last line decides.",
      "return NO es como el return de otros lenguajes: no sale. Solo envuelve un valor en un cofre, así que return 5 es Just 5 en Maybe. Un return en medio de un bloque crea un cofre que se descarta; el bloque sigue y la última línea decide.",
      "return はほかの言語の return と違い、抜け出さない。値を箱に包むだけで、Maybe なら return 5 は Just 5。ブロックの途中の return は捨てられる箱を作るだけで、処理は続き、最後の行が結果を決める。",
    ),
    ex("print (do { k <- Just 'q'; return 'z'; Just [k, k] })", "Just \"qq\"",
      L("The middle return is ignored; the last line wins", "El return del medio se ignora; gana la última línea", "途中の return は無視され最後の行が勝つ")),
    p(
      "In the list monad, each x <- xs tries every item, so a do block over lists produces every combination, with the first line as the outer loop. Common mistake: mixing monads, since all the lines of one do block must use the same one.",
      "En la mónada lista, cada x <- xs prueba cada elemento, así que un bloque do sobre listas produce todas las combinaciones, con la primera línea como bucle exterior. Error común: mezclar mónadas, ya que todas las líneas de un bloque do deben usar la misma.",
      "リストのモナドでは x <- xs が全要素を試すので、do ブロックは全組み合わせを作る。最初の行が外側のループ。よくあるミス：モナドを混ぜること。1つの do ブロックの行はすべて同じモナドでなければならない。",
    ),
  ),
  note("sequence", L("sequence and traverse", "sequence y traverse", "sequence と traverse"),
    p(
      "sequence turns a list of chests into one chest holding a list. It works like a do block over every chest in the list, so the usual rule applies: one Nothing makes the whole result Nothing, and with Either the first Left wins.",
      "sequence convierte una lista de cofres en un cofre que contiene una lista. Funciona como un bloque do sobre cada cofre de la lista, así que aplica la regla de siempre: un Nothing hace que todo el resultado sea Nothing, y con Either gana el primer Left.",
      "sequence は箱のリストを、リスト入りの箱1つに変える。リストの全部の箱に do ブロックを使うのと同じなので、いつものルールどおり Nothing が1つあれば全体が Nothing、Either なら最初の Left が勝つ。",
    ),
    ex('print (sequence [Just \'a\', Just \'b\'], sequence [Right 1, Left "x", Left "y" :: Either String Int])', '(Just "ab",Left "x")'),
    p(
      "traverse f xs is fmap followed by sequence: apply a chest-returning function to every item, then collect the results. If every call succeeds you get a Just holding the whole list.",
      "traverse f xs es fmap seguido de sequence: aplica una función que devuelve un cofre a cada elemento y luego junta los resultados. Si todas las llamadas funcionan, obtienes un Just con toda la lista.",
      "traverse f xs は fmap のあとに sequence をしたもの。箱を返す関数を全要素に当て、結果を集める。全部成功すれば、リスト全体が入った Just になる。",
    ),
    ex("print (traverse (\\k -> if k < 10 then Just (k * 2) else Nothing) [1, 2, 3])", "Just [2,4,6]"),
    p(
      "Common mistake: expecting sequence to drop the empty chests and keep the rest. It does not. To keep only the successes, use catMaybes or mapMaybe from Data.Maybe.",
      "Error común: esperar que sequence descarte los cofres vacíos y conserve el resto. No lo hace. Para quedarte solo con los éxitos, usa catMaybes o mapMaybe de Data.Maybe.",
      "よくある誤解：sequence が空の箱を捨てて残りを残すと思うこと。そうはしない。成功だけ残したいなら Data.Maybe の catMaybes か mapMaybe を使おう。",
    ),
  ),
];

const monads: LessonDef = {
  slug: "monads-and-do",
  notes: monadNotes,
  title: L("A chain of chests", "Una cadena de cofres", "宝箱のくさり"),
  concept: "monads",
  mode: "lesson",
  xp: 85,
  enemy: "haskell/bottom-wraith",
  enemyName: L("CHAIN WRAITH", "ESPECTRO CADENA", "クサリのレイス"),
  beats: [
    say(L(
      "A MONAD chains steps that each return a chest. >>= opens the chest and feeds the item to the next step.",
      "Una MÓNADA encadena pasos que devuelven un cofre. >>= abre el cofre y pasa el objeto al siguiente paso.",
      "モナドは宝箱を返す処理をつなぐ。>>= は箱を開けて中身を次の処理に渡す。",
    )),
    {
      kind: "act",
      prompt: L("Feed chests down the chain", "Pasa cofres por la cadena", "宝箱をくさりに流そう"),
      steps: [
        { label: L("FULL CHEST", "COFRE LLENO", "中身あり"), line: "print (Just 5 >>= \\x -> Just (x * 2))",
          effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "print", text: "Just 10" }], output: "Just 10" },
        { label: L("EMPTY CHEST", "COFRE VACÍO", "空の箱"), line: "print (Nothing >>= \\x -> Just (x * 2))",
          effects: [{ t: "shake" }, { t: "banner", text: L("SHORT-CIRCUIT", "CORTOCIRCUITO", "ショートした！") }, { t: "print", text: "Nothing" }], output: "Nothing" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (Just 5 >>= \\x -> Just (x * 2))",
      options: ["Just 10", "10", "Just (Just 10)"],
      answer: 0,
      output: "Just 10",
      check: { compiles: true, stdout: "Just 10" },
      hint: L(">>= opens the chest and the lambda returns a new chest. Does that chest get wrapped again?", ">>= abre el cofre y la lambda devuelve un cofre nuevo. ¿Ese cofre se envuelve otra vez?", ">>= が箱を開け、ラムダが新しい箱を返す。その箱はさらに包まれる？"),
      note: "bind",
      explain: L(">>= opens Just 5, gives 5 to the lambda, and the lambda returns the new chest Just 10.", ">>= abre Just 5, pasa 5 a la lambda y la lambda devuelve el cofre nuevo Just 10.", ">>= が Just 5 を開けて 5 をラムダに渡し、ラムダが新しい箱 Just 10 を返す。"),
      win: [{ t: "print", text: "Just 10" }],
    },
    {
      kind: "type",
      prompt: L("Open and feed the next step", "Abre y alimenta el siguiente paso", "開けて次へ渡そう"),
      code: "print (Just 5 ___ \\x -> Just (x * 2))",
      answer: ">>=",
      check: { compiles: true, stdout: "Just 10" },
      hint: L("You need the operator called bind: it opens a monadic value and feeds it to the next function.", "Necesitas el operador llamado bind: abre un valor monádico y se lo pasa a la siguiente función.", "バインドと呼ばれる演算子じゃ。モナドの値を開けて次の関数に渡す。"),
      note: "bind",
      explain: L(">>= is called bind: it binds the item to x for the next step.", ">>= se llama bind: liga el objeto a x para el siguiente paso.", ">>= はバインド。中身を x に結びつけて次へ渡す。"),
      win: [{ t: "print", text: "Just 10" }],
    },
    say(L(
      "do notation is sugar for >>=. Each x <- chest opens one chest. One empty chest stops the whole block.",
      "La notación do es azúcar para >>=. Cada x <- cofre abre un cofre. Un cofre vacío detiene todo el bloque.",
      "do 記法は >>= の糖衣構文。x <- 箱 で1つ開ける。空の箱が1つでもあればブロック全体が止まる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: TABLE + "\n\nboth :: Maybe String\nboth = do\n  a <- lookup 1 table\n  b <- lookup 2 table\n  return (a ++ b)\n\nmain :: IO ()\nmain = print both",
      options: ['Just "lambda"', '"lambda"', "Nothing"],
      answer: 0,
      output: 'Just "lambda"',
      check: { compiles: true, stdout: 'Just "lambda"' },
      hint: L("Do both keys exist in the table? If every step succeeds, return wraps the final value.", "¿Existen ambas claves en la tabla? Si todos los pasos funcionan, return envuelve el valor final.", "両方のキーは表にある？全部成功すれば return が最後の値を包む。"),
      note: "do-notation",
      explain: L("Both lookups found a value, so return wraps \"lam\" ++ \"bda\" in a Just.", "Ambos lookup hallaron valor, así que return envuelve \"lam\" ++ \"bda\" en un Just.", "両方の lookup が成功。return が \"lam\" ++ \"bda\" を Just に包む。"),
      win: [{ t: "print", text: 'Just "lambda"' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: TABLE + "\n\nboth :: Maybe String\nboth = do\n  a <- lookup 1 table\n  b <- lookup 3 table\n  return (a ++ b)\n\nmain :: IO ()\nmain = print both",
      options: ["Nothing", 'Just "lam"', L("Crash", "Crash", "クラッシュ")],
      answer: 0,
      output: "Nothing",
      check: { compiles: true, stdout: "Nothing" },
      hint: L("Check each lookup. What does a single empty chest do to the whole do block?", "Revisa cada lookup. ¿Qué le hace un solo cofre vacío a todo el bloque do?", "lookup を1つずつ確かめよう。空の箱が1つあると do ブロック全体はどうなる？"),
      note: "do-notation",
      explain: L("There is no key 3. That empty chest short-circuits the block: the answer is Nothing.", "No hay clave 3. Ese cofre vacío corta el bloque: la respuesta es Nothing.", "キー 3 はない。空の箱でブロックがショートし、答えは Nothing。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "banner", text: L("SHORT-CIRCUIT", "CORTOCIRCUITO", "ショートした！") }, { t: "print", text: "Nothing" }],
    },
    say(L(
      "Either works the same way, but stops at the first Left and keeps its reason.",
      "Either funciona igual, pero se detiene en el primer Left y conserva su razón.",
      "Either も同じ。ただし最初の Left で止まり、その理由を残す。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "age :: String -> Either String Int",
        'age s | not (null s) && all (`elem` "0123456789") s = Right (read s)',
        '      | otherwise = Left ("bad age: " ++ s)',
        "",
        "main :: IO ()",
        'main = print (do { a <- age "30"; b <- age "x1"; c <- age "4"; return (a + b + c) })',
      ),
      options: ['Left "bad age: x1"', "Right 34", 'Left "bad age: 4"'],
      answer: 0,
      output: 'Left "bad age: x1"',
      check: { compiles: true, stdout: 'Left "bad age: x1"' },
      hint: L("Check each age in order. Where does the first Left appear, and does anything run after it?", "Revisa cada edad en orden. ¿Dónde aparece el primer Left y se ejecuta algo después?", "年齢を順に確かめよう。最初の Left はどこ？そのあと何か動く？"),
      note: "do-notation",
      explain: L("\"x1\" fails, so the chain stops there with that Left. \"4\" is never checked.", "\"x1\" falla, así que la cadena se detiene ahí con ese Left. \"4\" ni se revisa.", "\"x1\" で失敗し、その Left で止まる。\"4\" は調べられない。"),
      win: [{ t: "print", text: 'Left "bad age: x1"' }],
    },
    say(L(
      "Careful: return does NOT exit the block. It only wraps a value in a chest, and the block goes on.",
      "Cuidado: return NO sale del bloque. Solo envuelve un valor en un cofre, y el bloque sigue.",
      "注意：return はブロックを抜けない。値を箱に包むだけで、処理は続く。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (do { x <- Just 1; return 99; Just (x + 1) })",
      options: ["Just 2", "Just 99", "99"],
      answer: 0,
      output: "Just 2",
      check: { compiles: true, stdout: "Just 2" },
      hint: L("return does not leave the block. Which line gives the block its result?", "return no sale del bloque. ¿Qué línea le da su resultado al bloque?", "return はブロックを抜けない。ブロックの結果を決めるのはどの行？"),
      note: "do-notation",
      explain: L("return 99 makes Just 99, which is thrown away. The last line decides: Just 2.", "return 99 crea Just 99, que se descarta. La última línea decide: Just 2.", "return 99 は Just 99 を作って捨てられる。最後の行が答え：Just 2。"),
      win: [{ t: "print", text: "Just 2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (do { x <- [1,2]; y <- "ab"; return (x, y) })',
      options: ["[(1,'a'),(1,'b'),(2,'a'),(2,'b')]", "[(1,'a'),(2,'b')]", "(2,'b')"],
      answer: 0,
      output: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]",
      check: { compiles: true, stdout: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]" },
      hint: L("In the list monad each <- tries every item. Walk through all pairs, the first list as the outer loop.", "En la mónada lista cada <- prueba cada elemento. Recorre todos los pares, con la primera lista como bucle exterior.", "リストのモナドでは <- が全要素を試す。1つ目のリストを外側にして全ペアをたどろう。"),
      note: "do-notation",
      explain: L("In the list monad, each <- tries every item, so you get every combination.", "En la mónada lista, cada <- prueba cada elemento y obtienes todas las combinaciones.", "リストのモナドでは <- が全要素を試すので、全組み合わせになる。"),
      win: [{ t: "print", text: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (sequence [Just 1, Just 2], sequence [Just 1, Nothing])",
      options: ["(Just [1,2],Nothing)", "([Just 1,Just 2],[Just 1,Nothing])", "(Just [1,2],Just [1])"],
      answer: 0,
      output: "(Just [1,2],Nothing)",
      check: { compiles: true, stdout: "(Just [1,2],Nothing)" },
      hint: L("sequence builds one chest holding a list. What happens if one of the chests is empty?", "sequence crea un cofre que contiene una lista. ¿Qué pasa si uno de los cofres está vacío?", "sequence はリスト入りの箱を1つ作る。箱の1つが空だったら？"),
      note: "sequence",
      explain: L("sequence turns a list of chests into one chest with a list. One empty chest empties it all.", "sequence convierte una lista de cofres en un cofre con una lista. Uno vacío lo vacía todo.", "sequence は箱のリストを、リスト入りの箱1つに変える。空が1つあれば全部空。"),
      win: [{ t: "print", text: "(Just [1,2],Nothing)" }],
    },
    {
      kind: "run",
      prompt: L('Overdrawing must give Left "insufficient funds"', 'Sacar de más debe dar Left "insufficient funds"', '残高不足なら Left "insufficient funds" に'),
      starter: code(
        "withdraw :: Int -> Int -> Either String Int",
        "withdraw bal amt = if amt > bal then Right bal else Right (bal - amt)",
        "",
        "main :: IO ()",
        "main = print (do { b1 <- withdraw 100 30; withdraw b1 90 })",
        "",
      ),
      solution: code(
        "withdraw :: Int -> Int -> Either String Int",
        'withdraw bal amt = if amt > bal then Left "insufficient funds" else Right (bal - amt)',
        "",
        "main :: IO ()",
        "main = print (do { b1 <- withdraw 100 30; withdraw b1 90 })",
        "",
      ),
      expect: 'Left "insufficient funds"',
      fallback: [String.raw`then\s+Left\s+"insufficient funds"`],
      hint: L("The overdraft branch should fail with a reason. Which Either constructor carries an error?", "La rama de sobregiro debe fallar con una razón. ¿Qué constructor de Either lleva un error?", "残高不足の分岐は理由つきで失敗すべき。エラーを運ぶ Either のコンストラクタは？"),
      note: "do-notation",
      explain: L("Right bal hid the failure. A Left stops the chain and says why.", "Right bal escondía el fallo. Un Left detiene la cadena y dice por qué.", "Right bal は失敗を隠していた。Left ならくさりを止めて理由を伝える。"),
    },
  ],
};

// ─── 4.4 Speaking scrolls and the key ring ─────────────────────────────────
const ioNotes: NoteDef[] = [
  note("io-actions", L("IO actions: descriptions of effects", "Acciones IO: descripciones de efectos", "IO アクション：作用の説明書"),
    p(
      "An IO action, of type IO a, describes something to do, like printing, that will produce a value of type a. Creating it or giving it a name does nothing. The action runs only when it becomes a step of main, the action the program executes.",
      "Una acción IO, de tipo IO a, describe algo por hacer, como imprimir, que producirá un valor de tipo a. Crearla o darle un nombre no hace nada. La acción corre solo cuando se vuelve un paso de main, la acción que el programa ejecuta.",
      "IO アクション（型 IO a）は、表示など「やること」の説明書で、実行すると型 a の値を生む。作ったり名前をつけたりしても何も起きない。プログラムが実行する main の一歩になったときだけ動く。",
    ),
    p(
      "In a do block, each line that is an action runs, in order. Naming an action with let only gives it a name; every time that name appears as a line of the block, the action runs again.",
      "En un bloque do, cada línea que es una acción se ejecuta, en orden. Nombrar una acción con let solo le da un nombre; cada vez que ese nombre aparece como línea del bloque, la acción se ejecuta otra vez.",
      "do ブロックでは、アクションの行が順番に実行される。let でアクションに名前をつけても名前がつくだけ。その名前がブロックの行として出てくるたびに、アクションがもう一度動く。",
    ),
    ex('let beep = putStrLn "beep"\nputStrLn "start"\nbeep\nbeep\nbeep', "start\nbeep\nbeep\nbeep",
      L("let prints nothing; each line beep runs it once", "let no imprime; cada línea beep la ejecuta una vez", "let は何も表示せず beep の行ごとに1回")),
    p(
      "Pure functions cannot perform IO. putStrLn has type String -> IO (), so its result is an action, not a String. A function whose signature promises a String cannot return it. Keep the logic pure by building the String, and print it in main.",
      "Las funciones puras no pueden hacer IO. putStrLn tiene tipo String -> IO (), así que su resultado es una acción, no un String. Una función cuya firma promete un String no puede devolverla. Mantén la lógica pura construyendo el String e imprímelo en main.",
      "純粋関数は IO ができない。putStrLn の型は String -> IO () で、結果は String ではなくアクション。シグネチャで String を約束した関数はそれを返せない。処理は純粋に保って String を作り、表示は main で。",
    ),
    ex('label :: Int -> String\nlabel n = "level " ++ show n\n\nmain :: IO ()\nmain = putStrLn (label 4)', "level 4",
      L("Pure function builds the text; main prints it", "La función pura arma el texto; main lo imprime", "純粋関数が文字列を作り main が表示")),
    bad("label :: Int -> String\nlabel n = print n\n\nmain :: IO ()\nmain = putStrLn (label 4)",
      L("Does not compile: print gives an IO (), not a String", "No compila: print da un IO (), no un String", "コンパイル不可：print は String ではなく IO ()")),
  ),
  note("mapm-form", L("mapM_, forM_ and map", "mapM_, forM_ y map", "mapM_・forM_・map"),
    p(
      "map f xs builds a list. With an IO function like print, map print xs builds a list of actions, of type [IO ()], but does not run them. A list is not an action, so it cannot be a line of a do block, and GHC rejects it.",
      "map f xs construye una lista. Con una función IO como print, map print xs construye una lista de acciones, de tipo [IO ()], pero no las ejecuta. Una lista no es una acción, así que no puede ser una línea de un bloque do, y GHC la rechaza.",
      "map f xs はリストを作る。print のような IO 関数なら、map print xs は型 [IO ()] のアクションのリストを作るだけで、実行はしない。リストはアクションではないので do の行にはなれず、GHC が拒否する。",
    ),
    bad('map putStrLn ["x", "y"]\nreturn ()',
      L("Does not compile: a list of actions is not an action", "No compila: una lista de acciones no es una acción", "コンパイル不可：アクションのリストはアクションではない")),
    p(
      "mapM_ f xs runs f on each item, in order, and discards the results. forM_ is the same with the arguments swapped, list first, which reads nicely with a lambda; import it from Control.Monad. mapM, without the underscore, also collects the results in a list.",
      "mapM_ f xs ejecuta f con cada elemento, en orden, y descarta los resultados. forM_ es lo mismo con los argumentos al revés, la lista primero, cómodo con una lambda; se importa de Control.Monad. mapM, sin guion bajo, además junta los resultados en una lista.",
      "mapM_ f xs は各要素に順番に f を実行し、結果は捨てる。forM_ は引数が逆（リストが先）で、ラムダと相性がよい。Control.Monad から import する。下線のない mapM は結果もリストに集める。",
    ),
    ex('mapM_ putStrLn ["north", "south"]', "north\nsouth"),
    ex("import Control.Monad (forM_)\n\nmain :: IO ()\nmain = forM_ [3, 1] $ \\k -> print (k * 10)", "30\n10",
      L("forM_ takes the list first, then the action", "forM_ recibe primero la lista y luego la acción", "forM_ はリストが先、アクションが後")),
    p(
      "Rule: use map to transform data, and mapM_ or forM_ to perform an action for each item. Common mistake: forgetting the import of forM_; GHC then says the variable is not in scope.",
      "Regla: usa map para transformar datos, y mapM_ o forM_ para hacer una acción por cada elemento. Error común: olvidar importar forM_; entonces GHC dice que la variable no está en alcance.",
      "ルール：データを変換するなら map、要素ごとにアクションを実行するなら mapM_ か forM_。よくあるミス：forM_ の import を忘れること。GHC に not in scope と言われる。",
    ),
  ),
  note("data-map", L("Data.Map: a sorted key ring", "Data.Map: un llavero ordenado", "Data.Map：並んだカギの輪"),
    p(
      "Data.Map stores key-value pairs and finds values by key quickly. Import it qualified, import qualified Data.Map as M, because many of its names clash with the Prelude. M.fromList builds a map from a list of pairs. Keys are always kept sorted, whatever order you gave them in.",
      "Data.Map guarda pares clave-valor y encuentra valores por clave rápidamente. Impórtalo calificado, import qualified Data.Map as M, porque muchos de sus nombres chocan con el Prelude. M.fromList crea un mapa a partir de una lista de pares. Las claves siempre se mantienen ordenadas, sin importar el orden en que las diste.",
      "Data.Map はキーと値のペアを保存し、キーで値をすばやく見つける。名前が Prelude とぶつかるので import qualified Data.Map as M のように修飾つきで import する。M.fromList はペアのリストから Map を作る。キーは渡した順番に関係なく常に並べて保たれる。",
    ),
    ex('import qualified Data.Map as M\n\nmain :: IO ()\nmain = print (M.fromList [(3, "c"), (1, "a"), (2, "b")])', 'fromList [(1,"a"),(2,"b"),(3,"c")]',
      L("Printed in key order, not insertion order", "Se imprime en orden de clave, no de inserción", "入れた順ではなくキー順で表示")),
    p(
      "M.lookup k m returns a Maybe, because the key may be missing. M.findWithDefault d k m returns the value or the default d. m M.! k returns the value directly, but crashes if the key is missing, so prefer the first two.",
      "M.lookup k m devuelve un Maybe, porque la clave puede faltar. M.findWithDefault d k m devuelve el valor o el valor por defecto d. m M.! k devuelve el valor directamente, pero falla si la clave falta, así que prefiere los dos primeros.",
      "M.lookup k m はキーがないかもしれないので Maybe を返す。M.findWithDefault d k m は値か、デフォルト d。m M.! k は値を直接返すが、キーがないと落ちる。前の2つを使おう。",
    ),
    crash("import qualified Data.Map as M\n\nmain :: IO ()\nmain = print (M.fromList [('x', 1 :: Int)] M.! 'y')", "given key is not an element in the map",
      L("M.! has no plan for a missing key", "M.! no tiene plan para una clave ausente", "M.! はキーがないときの備えがない")),
    p(
      "Maps are immutable: M.insert k v m returns a NEW map, and m itself does not change. The same goes for M.delete and M.adjust. Keep the result under a new name and use that one.",
      "Los mapas son inmutables: M.insert k v m devuelve un mapa NUEVO, y m no cambia. Lo mismo pasa con M.delete y M.adjust. Guarda el resultado con un nombre nuevo y usa ese.",
      "Map は不変。M.insert k v m は新しい Map を返し、m 自体は変わらない。M.delete や M.adjust も同じ。結果に新しい名前をつけて、そちらを使おう。",
    ),
    ex('import qualified Data.Map as M\n\nmain :: IO ()\nmain = do\n  let m = M.fromList [(1, "a")]\n  let m2 = M.delete 1 (M.insert 2 "b" m)\n  print (M.toList m, M.toList m2)', '([(1,"a")],[(2,"b")])',
      L("m2 is a new map; m still has its one key", "m2 es un mapa nuevo; m conserva su única clave", "m2 は新しい Map、m はキー1つのまま")),
  ),
  note("map-combine", L("Duplicate keys: fromListWith", "Claves repetidas: fromListWith", "重複キー：fromListWith"),
    p(
      "A map holds each key only once. M.fromList with a repeated key keeps only the LAST value given for it. M.fromListWith f instead combines the values of a repeated key using f.",
      "Un mapa guarda cada clave una sola vez. M.fromList con una clave repetida conserva solo el ÚLTIMO valor dado para ella. M.fromListWith f, en cambio, combina los valores de una clave repetida usando f.",
      "Map は各キーを1回だけ持つ。M.fromList に重複キーがあると、最後の値だけが残る。M.fromListWith f は重複キーの値を f で組み合わせる。",
    ),
    ex('import qualified Data.Map as M\n\nmain :: IO ()\nmain = do\n  print (M.fromList [("k", 1), ("k", 5)])\n  print (M.fromListWith (+) [("k", 1), ("k", 5)])', 'fromList [("k",5)]\nfromList [("k",6)]',
      L("fromList keeps the last value; fromListWith combines them", "fromList guarda el último; fromListWith los combina", "fromList は最後だけ、fromListWith は組み合わせる")),
    p(
      "Pairing every item with 1 and combining with (+) counts how many times each item appears: a classic counter. M.toList then gives the counts as pairs sorted by key.",
      "Emparejar cada elemento con 1 y combinar con (+) cuenta cuántas veces aparece cada elemento: un contador clásico. Luego M.toList da los conteos como pares ordenados por clave.",
      "各要素を 1 と組にして (+) で組み合わせると、出てきた回数が数えられる。定番のカウンター。M.toList でキー順のペアとして取り出せる。",
    ),
    ex("import qualified Data.Map as M\n\nmain :: IO ()\nmain = print (M.toList (M.fromListWith (+) [(x, 1) | x <- [3, 1, 3, 3]]))", "[(1,1),(3,3)]"),
    p(
      "M.unionWith f joins two maps the same way: keys found in both get their values combined with f, and the other keys are copied. Common mistake: using M.fromList to count and getting 1 for every key.",
      "M.unionWith f une dos mapas de la misma forma: las claves presentes en ambos combinan sus valores con f, y las demás se copian. Error común: usar M.fromList para contar y obtener 1 en cada clave.",
      "M.unionWith f も同じように2つの Map をつなぐ。両方にあるキーは値を f で組み合わせ、ほかはそのまま写す。よくあるミス：M.fromList で数えて、どのキーも 1 になること。",
    ),
  ),
];

const ioMaps: LessonDef = {
  slug: "io-and-maps",
  notes: ioNotes,
  title: L("Scrolls and the key ring", "Pergaminos y el llavero", "巻物とカギの輪"),
  concept: "io",
  mode: "lesson",
  xp: 85,
  enemy: "haskell/partial-moth",
  enemyName: L("KEY MOTH", "POLILLA LLAVE", "カギモス"),
  beats: [
    say(L(
      "IO is a monad too! An IO action is a sealed scroll of instructions. Writing it does nothing; main reads it aloud.",
      "¡IO también es una mónada! Una acción IO es un pergamino sellado de instrucciones. Escribirla no hace nada; main la lee.",
      "IO もモナド！IO アクションは指示の巻物。書くだけでは何も起きず、main が読み上げる。",
    )),
    {
      kind: "act",
      prompt: L("Write a scroll, then read it twice", "Escribe un pergamino y léelo dos veces", "巻物を書いて、2回読もう"),
      steps: [
        { label: L("WRITE", "ESCRIBIR", "書く"), line: 'let act = putStrLn "hi"',
          effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "act" }, { t: "say", actor: "hero", text: L("Silence...", "Silencio...", "しーん…") }] },
        { label: L("READ", "LEER", "読む"), line: "act", effects: [{ t: "print", text: "hi" }], output: "hi" },
        { label: L("AGAIN", "OTRA VEZ", "もう一度"), line: "act", effects: [{ t: "print", text: "hi" }, { t: "attack", from: "hero", to: "enemy" }], output: "hi" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'let act = putStrLn "hi"\nact\nact',
      options: [L("hi, twice", "hi, dos veces", "hi を2回"), L("hi, three times", "hi, tres veces", "hi を3回"), L("hi, once", "hi, una vez", "hi を1回")],
      answer: 0,
      output: "hi\nhi",
      check: { compiles: true, stdout: "hi\nhi" },
      hint: L("let only names the action. Count how many times that name runs as a line of the block.", "let solo nombra la acción. Cuenta cuántas veces ese nombre se ejecuta como línea del bloque.", "let は名前をつけるだけ。その名前がブロックの行として何回動くか数えよう。"),
      note: "io-actions",
      explain: L("let only writes the scroll. Each line act runs it once: two runs, two hi.", "let solo escribe el pergamino. Cada línea act lo ejecuta una vez: dos veces, dos hi.", "let は巻物を書くだけ。act の行ごとに1回実行、だから hi が2回。"),
      win: [{ t: "print", text: "hi" }, { t: "print", text: "hi" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'greet :: String -> String\ngreet n = putStrLn ("hi " ++ n)\n\nmain :: IO ()\nmain = putStrLn (greet "Ada")',
      options: [YES, L("No: a pure function can't print", "No: una función pura no imprime", "いいえ：純粋関数は表示できない")],
      answer: 1,
      check: { compiles: false },
      hint: L("What type does putStrLn return? Compare it with the String that the signature promises.", "¿Qué tipo devuelve putStrLn? Compáralo con el String que promete la firma.", "putStrLn は何の型を返す？シグネチャが約束する String と比べよう。"),
      note: "io-actions",
      explain: L("putStrLn gives an IO (), not a String. Only IO actions can speak.", "putStrLn da un IO (), no un String. Solo las acciones IO pueden hablar.", "putStrLn は String ではなく IO () を返す。話せるのは IO だけ。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "To run an action for each item, use mapM_ or forM_. map print xs only BUILDS a list of scrolls.",
      "Para correr una acción por elemento, usa mapM_ o forM_. map print xs solo CONSTRUYE una lista de pergaminos.",
      "要素ごとにアクションを実行するなら mapM_ か forM_。map print xs は巻物のリストを作るだけ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "mapM_ print [1,2,3]",
      options: [L("1, 2, 3 on three lines", "1, 2, 3 en tres líneas", "1, 2, 3 を3行で"), "[1,2,3]", L("Nothing", "Nada", "何も出ない")],
      answer: 0,
      output: "1\n2\n3",
      check: { compiles: true, stdout: "1\n2\n3" },
      hint: L("mapM_ runs the action for each item, in order. What does print show for each one?", "mapM_ ejecuta la acción para cada elemento, en orden. ¿Qué muestra print para cada uno?", "mapM_ は各要素に順番にアクションを実行する。print はそれぞれ何を表示する？"),
      note: "mapm-form",
      explain: L("mapM_ runs print on each item, in order, and throws the results away.", "mapM_ ejecuta print en cada elemento, en orden, y descarta los resultados.", "mapM_ は各要素に順番に print を実行し、結果は捨てる。"),
      win: [{ t: "print", text: "1" }, { t: "print", text: "2" }, { t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'map print [1, 2, 3]\nputStrLn "done"',
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      hint: L("What does map print give: an action, or a list of actions? Can a do line be a list?", "¿Qué da map print: una acción o una lista de acciones? ¿Puede una línea de do ser una lista?", "map print が作るのはアクション？アクションのリスト？do の行はリストでもいい？"),
      note: "mapm-form",
      explain: L("map print gives a list of actions, not an action. A do line must be an IO action.", "map print da una lista de acciones, no una acción. Una línea de do debe ser una acción IO.", "map print はアクションのリストで、アクションではない。do の行は IO アクションが必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "import Control.Monad (forM_)\n\nmain :: IO ()\nmain = forM_ [1..3] $ \\i -> putStrLn (replicate i '*')",
      options: [L("*, **, *** on three lines", "*, **, *** en tres líneas", "*, **, *** を3行で"), "***", L("Does not compile", "No compila", "コンパイルできない")],
      answer: 0,
      output: "*\n**\n***",
      check: { compiles: true, stdout: "*\n**\n***" },
      hint: L("forM_ runs the lambda for each number, in order. What does replicate i '*' build?", "forM_ ejecuta la lambda para cada número, en orden. ¿Qué construye replicate i '*'?", "forM_ は各数に順番にラムダを実行する。replicate i '*' は何を作る？"),
      note: "mapm-form",
      explain: L("forM_ is mapM_ with the list first. Import it from Control.Monad.", "forM_ es mapM_ con la lista primero. Se importa de Control.Monad.", "forM_ はリストが先の mapM_。Control.Monad から import する。"),
      win: [{ t: "print", text: "*" }, { t: "print", text: "**" }, { t: "print", text: "***" }],
    },
    say(L(
      "Data.Map is a key ring: keys open values, kept sorted. M.lookup answers with a Maybe, since a key may be missing.",
      "Data.Map es un llavero: las claves abren valores, siempre ordenados. M.lookup responde con Maybe, la clave puede faltar.",
      "Data.Map はカギの輪。キーで値を開け、キー順に並ぶ。キーがないかもしれないので M.lookup は Maybe。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("b",2),("a",1)]\n  print m',
      options: ['fromList [("a",1),("b",2)]', 'fromList [("b",2),("a",1)]', '[("a",1),("b",2)]'],
      answer: 0,
      output: 'fromList [("a",1),("b",2)]',
      check: { compiles: true, stdout: 'fromList [("a",1),("b",2)]' },
      hint: L("Does a Map remember the order you inserted keys in, or keep them in some order of its own?", "¿Un Map recuerda el orden en que insertaste las claves o las mantiene en un orden propio?", "Map はキーを入れた順を覚える？それとも自分の順番で並べる？"),
      note: "data-map",
      explain: L("A Map keeps its keys sorted, whatever order you gave them in.", "Un Map mantiene sus claves ordenadas, sin importar el orden en que las diste.", "Map は渡した順番に関係なく、キーを並べて保つ。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "m" }],
      win: [{ t: "print", text: 'fromList [("a",1),("b",2)]' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("a",1),("b",2)]\n  print (M.lookup "a" m, M.lookup "z" m, M.findWithDefault 0 "z" m)',
      options: ["(Just 1,Nothing,0)", "(1,0,0)", "(Just 1,Nothing,Nothing)"],
      answer: 0,
      output: "(Just 1,Nothing,0)",
      check: { compiles: true, stdout: "(Just 1,Nothing,0)" },
      hint: L("lookup can't promise a key exists; findWithDefault has a fallback. Which keys are present?", "lookup no puede prometer que la clave exista; findWithDefault tiene un respaldo. ¿Qué claves hay?", "lookup はキーの存在を約束できず、findWithDefault には代わりの値がある。どのキーがある？"),
      note: "data-map",
      explain: L("lookup gives a Maybe; findWithDefault gives the default when the key is missing.", "lookup da un Maybe; findWithDefault da el valor por defecto si falta la clave.", "lookup は Maybe、findWithDefault はキーがなければデフォルト値。"),
      win: [{ t: "print", text: "(Just 1,Nothing,0)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("a",1),("b",2)]\n  let m2 = M.insert "c" 3 m\n  print (M.size m, M.size m2)',
      options: ["(2,3)", "(3,3)", "(2,2)"],
      answer: 0,
      output: "(2,3)",
      check: { compiles: true, stdout: "(2,3)" },
      hint: L("insert returns a new map. Is the original m changed?", "insert devuelve un mapa nuevo. ¿Cambia el m original?", "insert は新しい Map を返す。元の m は変わる？"),
      note: "data-map",
      explain: L("insert returns a NEW key ring. The old m still has two keys.", "insert devuelve un llavero NUEVO. El m viejo sigue con dos claves.", "insert は新しいカギの輪を返す。元の m はキー2つのまま。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "m", value: "2" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "m2", value: "3" }, { t: "print", text: "(2,3)" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: MAP + '  let m = M.fromList [("a", 1 :: Int)]\n  print (m M.! "a")\n  print (m M.! "b")',
      options: [L("Prints 1, then crashes", "Imprime 1 y luego falla", "1 を表示してクラッシュ"), L("Prints 1 and 0", "Imprime 1 y 0", "1 と 0 を表示"), L("Prints 1 and Nothing", "Imprime 1 y Nothing", "1 と Nothing を表示")],
      answer: 0,
      check: { compiles: true, throws: "given key is not an element in the map" },
      hint: L("The first key exists. What does M.! do when a key is missing?", "La primera clave existe. ¿Qué hace M.! cuando falta una clave?", "最初のキーはある。キーがないとき M.! はどうする？"),
      note: "data-map",
      explain: L("M.! is partial: a missing key crashes. Prefer M.lookup or findWithDefault.", "M.! es parcial: una clave que falta falla. Prefiere M.lookup o findWithDefault.", "M.! は部分関数。キーがないと落ちる。M.lookup か findWithDefault を使おう。"),
      win: [{ t: "print", text: "1" }, { t: "shake" }, { t: "attack", from: "enemy", to: "hero" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  print (M.toList (M.fromListWith (+) [(c, 1) | c <- "banana"]))',
      options: ["[('a',3),('b',1),('n',2)]", "[('b',1),('a',3),('n',2)]", "[('a',1),('b',1),('n',1)]"],
      answer: 0,
      output: "[('a',3),('b',1),('n',2)]",
      check: { compiles: true, stdout: "[('a',3),('b',1),('n',2)]" },
      hint: L("Repeated keys are combined with (+). Count each letter of the word, then sort by key.", "Las claves repetidas se combinan con (+). Cuenta cada letra de la palabra y ordena por clave.", "重複キーは (+) で組み合わされる。単語の各文字を数え、キー順に並べよう。"),
      note: "map-combine",
      explain: L("fromListWith (+) adds the values of repeated keys: a counter. toList comes out sorted.", "fromListWith (+) suma los valores de claves repetidas: un contador. toList sale ordenado.", "fromListWith (+) は重複キーの値を足す。カウンターになる。toList はキー順。"),
      win: [{ t: "print", text: "[('a',3),('b',1),('n',2)]" }],
    },
    {
      kind: "run",
      prompt: L("Count the words: owl must appear 2 times", "Cuenta las palabras: owl debe salir 2 veces", "単語を数えよう：owl は2回"),
      starter: code(
        "import qualified Data.Map as M",
        "",
        "main :: IO ()",
        "main = do",
        '  let counts = M.fromList [(w, 1) | w <- words "owl cat owl"]',
        '  print (M.lookup "owl" counts)',
        "",
      ),
      solution: code(
        "import qualified Data.Map as M",
        "",
        "main :: IO ()",
        "main = do",
        '  let counts = M.fromListWith (+) [(w, 1) | w <- words "owl cat owl"]',
        '  print (M.lookup "owl" counts)',
        "",
      ),
      expect: "Just 2",
      fallback: [String.raw`fromListWith\s*\(\s*\+\s*\)`],
      hint: L("fromList keeps only one value per repeated key. Which function combines duplicates instead?", "fromList conserva un solo valor por clave repetida. ¿Qué función combina los duplicados?", "fromList は重複キーの値を1つしか残さない。重複を組み合わせる関数は？"),
      note: "map-combine",
      explain: L("fromList keeps only the last duplicate. fromListWith (+) adds them up.", "fromList conserva solo el último duplicado. fromListWith (+) los suma.", "fromList は重複の最後だけ残す。fromListWith (+) なら足し合わせる。"),
    },
  ],
};

// ─── Boss: The Tower Guardian ──────────────────────────────────────────────
const bossNotes: NoteDef[] = [
  note("recap-classes", L("Recap: classes and instances", "Repaso: clases e instancias", "復習：クラスとインスタンス"),
    p(
      "A class lists methods; an instance provides them for one type, and each type gets at most one instance per class. Write the instance yourself when you want to choose the behavior, such as a custom show.",
      "Una clase lista métodos; una instancia los aporta para un tipo, y cada tipo tiene como mucho una instancia por clase. Escribe la instancia tú mismo cuando quieras elegir el comportamiento, como un show propio.",
      "クラスはメソッドの一覧、インスタンスはそれを1つの型に与えるもの。1つの型が持てるのは各クラス1つまで。show などの動きを自分で決めたいときは、インスタンスを自分で書く。",
    ),
    ex('data Bell = Bell\n\ninstance Show Bell where\n  show Bell = "ding"\n\nmain :: IO ()\nmain = print (Bell, [Bell])', "(ding,[ding])"),
    p(
      "read needs to know its result type, so add an annotation when nothing else fixes it. <> comes from Semigroup: lists join, and Maybe joins the insides of two Justs and skips a Nothing.",
      "read necesita saber su tipo de resultado, así que agrega una anotación cuando nada más lo fije. <> viene de Semigroup: las listas se unen, y Maybe une el interior de dos Just y salta un Nothing.",
      "read は結果の型を知る必要があるので、ほかに決めるものがなければ注釈をつける。<> は Semigroup のもの。リストはつながり、Maybe は2つの Just の中身をつなぎ Nothing は飛ばす。",
    ),
    ex('print (read "2.5" :: Double, Just "x" <> Nothing <> Just "y")', '(2.5,Just "xy")'),
    p(
      "Common mistake: writing deriving Show and a Show instance for the same type. GHC rejects the duplicate; keep only one of them.",
      "Error común: escribir deriving Show y una instancia de Show para el mismo tipo. GHC rechaza el duplicado; deja solo uno.",
      "よくあるミス：同じ型に deriving Show と Show のインスタンスを両方書くこと。GHC は重複を拒否する。どちらか1つだけに。",
    ),
  ),
  note("recap-chains", L("Recap: fmap, >>= and return", "Repaso: fmap, >>= y return", "復習：fmap・>>=・return"),
    p(
      "fmap keeps the shape and changes only the item inside; on a pair, that is the second part. >>= chains functions that return a chest; for lists it maps each item to a list and joins them. return wraps a value in a chest and never exits a do block, so the last line decides.",
      "fmap conserva la forma y cambia solo el objeto de adentro; en un par, es la segunda parte. >>= encadena funciones que devuelven un cofre; en listas, mapea cada elemento a una lista y las une. return envuelve un valor en un cofre y nunca sale de un bloque do, así que decide la última línea.",
      "fmap は形を保ち中身だけ変える。ペアなら2つ目。>>= は箱を返す関数をつなぎ、リストでは各要素をリストにしてつなぐ。return は値を箱に包むだけで do ブロックを抜けないので、最後の行が結果を決める。",
    ),
    ex("print (fmap (+ 1) ('k', 1), [5, 6] >>= \\k -> [k, -k])", "(('k',2),[5,-5,6,-6])"),
    p(
      "traverse f xs applies a chest-returning f to every item and collects the results into one chest. If any call fails, the whole result fails: one Nothing gives Nothing.",
      "traverse f xs aplica una f que devuelve un cofre a cada elemento y junta los resultados en un solo cofre. Si alguna llamada falla, todo el resultado falla: un Nothing da Nothing.",
      "traverse f xs は箱を返す f を全要素に当て、結果を1つの箱に集める。1回でも失敗すれば全体が失敗し、Nothing が1つなら Nothing。",
    ),
    ex("print (traverse (\\k -> if even k then Just k else Nothing) [2, 4], traverse (\\k -> if even k then Just k else Nothing) [2, 5])", "(Just [2,4],Nothing)",
      L("One odd number makes the whole traverse fail", "Un número impar hace fallar todo el traverse", "奇数が1つあれば traverse 全体が失敗")),
  ),
  note("recap-io-map", L("Recap: IO loops and maps", "Repaso: bucles IO y mapas", "復習：IO のループと Map"),
    p(
      "mapM_ runs an action for each item and discards the results; mapM runs them in order and also collects the results; map only builds a list of actions and runs nothing.",
      "mapM_ ejecuta una acción por elemento y descarta los resultados; mapM las ejecuta en orden y además junta los resultados; map solo construye una lista de acciones y no ejecuta nada.",
      "mapM_ は要素ごとにアクションを実行して結果を捨てる。mapM は順に実行して結果も集める。map はアクションのリストを作るだけで、何も実行しない。",
    ),
    ex('xs <- mapM (\\k -> do { putStrLn ("go " ++ show k); return (k + 1) }) [7, 8]\nprint xs', "go 7\ngo 8\n[8,9]",
      L("Effects happen in order, then the results are collected", "Los efectos ocurren en orden y luego se juntan los resultados", "作用は順番に起き、結果が集められる")),
    p(
      "A Data.Map keeps its keys sorted. M.lookup answers with a Maybe, while M.! crashes on a missing key. M.unionWith f merges two maps, combining the values of keys found in both with f.",
      "Un Data.Map mantiene sus claves ordenadas. M.lookup responde con un Maybe, mientras que M.! falla con una clave ausente. M.unionWith f une dos mapas, combinando con f los valores de las claves presentes en ambos.",
      "Data.Map はキーを並べて保つ。M.lookup は Maybe で答え、M.! はキーがないと落ちる。M.unionWith f は2つの Map をまとめ、両方にあるキーの値を f で組み合わせる。",
    ),
    ex("import qualified Data.Map as M\n\nmain :: IO ()\nmain = print (M.toList (M.unionWith max (M.fromList [(1, 5), (2, 1)]) (M.fromList [(2, 9), (3, 0)])))", "[(1,5),(2,9),(3,0)]",
      L("Key 2 is in both maps, so max picks its value", "La clave 2 está en ambos, así que max elige su valor", "キー2は両方にあるので max で選ぶ")),
  ),
];

const boss: LessonDef = {
  slug: "tower-boss",
  notes: bossNotes,
  title: L("Boss: The Tower Guardian", "Jefe: El Guardián", "ボス：塔の番人"),
  concept: "monads",
  mode: "boss",
  xp: 200,
  enemy: "haskell/partial-moth",
  enemyName: L("TOWER GUARDIAN", "GUARDIÁN", "塔の番人"),
  beats: [
    enemySays(L(
      "I AM THE TOWER GUARDIAN. Badges, chests, chains and scrolls: one wrong step and you fall to the mountain!",
      "SOY EL GUARDIÁN DE LA TORRE. Insignias, cofres, cadenas y pergaminos: ¡un paso en falso y caes a la montaña!",
      "我は塔の番人。バッジ、宝箱、くさり、巻物。一歩まちがえば山まで落ちるぞ！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "r <- mapM (\\x -> do { print x; return (x * 2) }) [1,2]\nprint r", options: [L("1, 2, then [2,4]", "1, 2 y luego [2,4]", "1, 2、そして [2,4]"), "[2,4]", L("1, 2 only", "Solo 1, 2", "1, 2 だけ")], answer: 0, output: "1\n2\n[2,4]", check: { compiles: true, stdout: "1\n2\n[2,4]" }, hint: L("mapM runs each action in order and collects what each one returns. What prints first?", "mapM ejecuta cada acción en orden y junta lo que devuelve cada una. ¿Qué se imprime primero?", "mapM は順に実行し、それぞれの戻り値を集める。最初に表示されるのは？"), note: "recap-io-map", explain: L("mapM runs each action in order AND collects the results.", "mapM ejecuta cada acción en orden Y junta los resultados.", "mapM は順に実行し、結果も集める。"), win: [{ t: "print", text: "[2,4]" }] },
    { kind: "predict", time: 12, prompt: COMPILES, code: 'print (read "5")', options: [L("Yes: prints 5", "Sí: imprime 5", "はい：5 と表示"), NO], answer: 1, check: { compiles: false }, hint: L("Can GHC tell which type read should produce in this line?", "¿Puede GHC saber qué tipo debe producir read en esta línea?", "この行で read が作る型を GHC は判断できる？"), note: "recap-classes", explain: L("read needs to know its result type: ambiguous.", "read necesita saber su tipo de resultado: ambiguo.", "read は結果の型が必要。あいまいでエラー。"), win: [{ t: "shake" }] },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (fmap (*2) (3, 4))", options: ["(3,8)", "(6,8)", "(6,4)"], answer: 0, output: "(3,8)", check: { compiles: true, stdout: "(3,8)" }, hint: L("For a pair, fmap touches only one of the two parts.", "En un par, fmap toca solo una de las dos partes.", "ペアの fmap が触るのは2つのうち片方だけ。"), note: "recap-chains", explain: L("fmap on a pair touches only the second part.", "fmap en un par toca solo la segunda parte.", "ペアの fmap は2つ目だけ変える。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (do { x <- Just 1; return 99; Just (x + 1) })", options: ["Just 2", "Just 99"], answer: 0, output: "Just 2", check: { compiles: true, stdout: "Just 2" }, hint: L("return wraps a value but does not exit. Which line decides the result?", "return envuelve un valor pero no sale. ¿Qué línea decide el resultado?", "return は包むだけで抜けない。結果を決めるのはどの行？"), note: "recap-chains", explain: L("return does not exit; the last line wins.", "return no sale; gana la última línea.", "return は抜けない。最後の行が答え。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print ([1,2,3] >>= \\x -> [x, x * 10])", options: ["[1,10,2,20,3,30]", "[10,20,30]", "[[1,10],[2,20],[3,30]]"], answer: 0, output: "[1,10,2,20,3,30]", check: { compiles: true, stdout: "[1,10,2,20,3,30]" }, hint: L("List >>= turns each item into a list, then joins those lists in order.", ">>= de listas vuelve cada elemento una lista y luego une esas listas en orden.", "リストの >>= は各要素をリストにして、順番につなぐ。"), note: "recap-chains", explain: L("List >>= maps each item to a list, then joins them.", ">>= de listas mapea cada elemento a una lista y las une.", "リストの >>= は各要素をリストにして連結。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "positive :: Int -> Maybe Int\npositive x = if x > 0 then Just x else Nothing\n\nmain :: IO ()\nmain = print (traverse positive [1,2,3], traverse positive [1,0,3])", options: ["(Just [1,2,3],Nothing)", "([Just 1,Just 2,Just 3],[Just 1,Nothing,Just 3])", "(Just [1,2,3],Just [1,3])"], answer: 0, output: "(Just [1,2,3],Nothing)", check: { compiles: true, stdout: "(Just [1,2,3],Nothing)" }, hint: L("traverse applies positive to each item and collects the results. What does one Nothing do?", "traverse aplica positive a cada elemento y junta los resultados. ¿Qué hace un solo Nothing?", "traverse は各要素に positive を当てて集める。Nothing が1つあると？"), note: "recap-chains", explain: L("traverse is map plus sequence: one Nothing fails it all.", "traverse es map más sequence: un Nothing lo hace fallar todo.", "traverse は map + sequence。Nothing 1つで全体失敗。") },
    { kind: "predict", time: 15, prompt: PRINT, code: MAP + '  let m = M.fromList [("b",2),("a",1)]\n  print (M.toList (M.unionWith (+) m (M.fromList [("a",5),("d",4)])))', options: ['[("a",6),("b",2),("d",4)]', '[("a",5),("b",2),("d",4)]', '[("b",2),("a",6),("d",4)]'], answer: 0, output: '[("a",6),("b",2),("d",4)]', check: { compiles: true, stdout: '[("a",6),("b",2),("d",4)]' }, hint: L("Keys found in both maps get their values combined with (+). The result is sorted by key.", "Las claves presentes en ambos mapas combinan sus valores con (+). El resultado sale ordenado por clave.", "両方の Map にあるキーは値を (+) で組み合わせる。結果はキー順。"), note: "recap-io-map", explain: L("unionWith (+) adds values of shared keys; the result is sorted.", "unionWith (+) suma valores de claves compartidas; sale ordenado.", "unionWith (+) は共通キーの値を足す。キー順。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (Just [1] <> Nothing, Just [1] <> Just [2])", options: ["(Just [1],Just [1,2])", "(Nothing,Just [1,2])", "(Just [1],Just [2])"], answer: 0, output: "(Just [1],Just [1,2])", check: { compiles: true, stdout: "(Just [1],Just [1,2])" }, hint: L("For Maybe, <> joins the insides of two Justs. What happens when one side is Nothing?", "Para Maybe, <> une el interior de dos Just. ¿Qué pasa cuando un lado es Nothing?", "Maybe の <> は2つの Just の中身をつなぐ。片方が Nothing なら？"), note: "recap-classes", explain: L("<> on Maybe skips a Nothing and joins the insides.", "<> en Maybe ignora Nothing y une lo de adentro.", "Maybe の <> は Nothing を飛ばし中身をつなぐ。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: MAP + '  let m = M.fromList [(1, "owl")]\n  putStrLn (m M.! 2)', options: [L("Crash: key not in map", "Crash: clave ausente", "クラッシュ：キーなし"), '""', "Nothing"], answer: 0, check: { compiles: true, throws: "given key is not an element in the map" }, hint: L("Is key 2 in the map? M.! has no plan for a missing key.", "¿Está la clave 2 en el mapa? M.! no tiene plan para una clave ausente.", "キー2は Map にある？M.! にはキーがないときの備えがない。"), note: "recap-io-map", explain: L("M.! crashes on a missing key.", "M.! falla con una clave ausente.", "M.! はキーがないと落ちる。"), win: [{ t: "shake" }] },
    { kind: "pick", time: 15, prompt: L("Run an action per item", "Una acción por elemento", "要素ごとに実行"), code: '___ putStrLn ["a", "b"]\nputStrLn "done"', options: ["mapM_", "map"], answer: 0, check: { compiles: true, stdout: "a\nb\ndone", wrongFail: true }, hint: L("One option only builds a list of actions; the other runs them. A do line must be an action.", "Una opción solo construye una lista de acciones; la otra las ejecuta. Una línea de do debe ser una acción.", "片方はアクションのリストを作るだけ、もう片方は実行する。do の行はアクションでなければならない。"), note: "recap-io-map", explain: L("map only builds a list of actions; mapM_ runs them.", "map solo arma una lista de acciones; mapM_ las ejecuta.", "map はリストを作るだけ。実行は mapM_。") },
    { kind: "type", time: 12, prompt: L("Give Owl the Show badge", "Dale a Owl la insignia Show", "Owl に Show を"), code: 'data Owl = Owl\n___ Show Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print Owl', answer: "instance", check: { compiles: true, stdout: "hoot" }, hint: L("Which keyword gives a class to a type, with your own code for its methods?", "¿Qué palabra clave le da una clase a un tipo, con tu propio código para sus métodos?", "自分のコードでメソッドを書いて、型にクラスを与えるキーワードは？"), note: "recap-classes", explain: L("instance gives a class to one type.", "instance da una clase a un tipo.", "instance で型にクラスを与える。") },
    enemySays(L(
      "No... every badge earned, every chest opened safely. Lambdara's sky is pure again. Well climbed, functional hero.",
      "No... cada insignia ganada, cada cofre abierto con cuidado. El cielo de Lambdara vuelve a ser puro. Bien subido, héroe funcional.",
      "ばかな…すべてのバッジを得て、宝箱を安全に開けたとは。ラムダラの空はまた純粋だ。見事だ、関数の勇者よ。",
    )),
  ],
};

export const monadTower: RegionDef = {
  slug: "monad-tower",
  name: L("Monad Tower", "Torre Mónada", "モナドの塔"),
  subtitle: L("Classes · Functor · Monad · IO", "Clases · Functor · Monad · IO", "型クラス・Functor・Monad・IO"),
  theme: "tower",
  lessons: [typeClasses, functors, monads, ioMaps, boss],
};
