import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 4 · MONAD TOWER  (type classes, Functor and Applicative, Monad and do, IO and Data.Map)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
const code = (...lines: string[]) => lines.join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const HAPPENS = L("What happens?", "¿Qué pasa?", "どうなる？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO = L("No: GHC stops it", "No: GHC lo detiene", "いいえ：GHC が止める");
const NO_COMPILE = L("Does not compile", "No compila", "コンパイルできない");
const MAP = "import qualified Data.Map as M\n\nmain :: IO ()\nmain = do\n";

// ─── 4.1 Badges for types ──────────────────────────────────────────────────
const typeClasses: LessonDef = {
  slug: "type-classes",
  title: L("Badges for types", "Insignias para tipos", "型のためのバッジ"),
  concept: "typeclasses",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/thunk-pile",
  enemyName: L("BADGE THIEF", "LADRÓN DE INSIGNIAS", "バッジドロボウ"),
  beats: [
    say(L(
      "Welcome to Monad Tower! A TYPE CLASS is a badge: it lists operations, and any type wearing it supports them.",
      "¡Bienvenido a la Torre Mónada! Una CLASE DE TIPOS es una insignia: lista operaciones y todo tipo que la lleva las soporta.",
      "モナドの塔へようこそ！型クラスはバッジ。操作の一覧で、バッジをつけた型はそれが使える。",
    )),
    {
      kind: "act",
      prompt: L("Design a badge, then give it to Bool", "Diseña una insignia y dásela a Bool", "バッジを作って Bool に渡そう"),
      steps: [
        { label: L("THE BADGE", "LA INSIGNIA", "バッジ"), line: "class Describable a where",
          effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "Describable" }] },
        { label: L("ITS RULE", "SU REGLA", "ルール"), line: "  describe :: a -> String" },
        { label: L("FOR Bool", "PARA Bool", "Bool 用"), line: "instance Describable Bool where",
          effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Bool" }, { t: "give", to: "ally" }] },
        { label: L("True", "True", "True"), line: '  describe True = "yes"' },
        { label: L("False", "False", "False"), line: '  describe False = "no"' },
        { label: L("USE IT", "USARLA", "使う"), line: "main = putStrLn (describe True)",
          effects: [{ t: "say", actor: "ally", text: L("yes", "yes", "yes") }, { t: "print", text: "yes" }, { t: "attack", from: "ally", to: "enemy" }], output: "yes" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "class Describable a where",
        "  describe :: a -> String",
        "instance Describable Bool where",
        '  describe True = "yes"',
        '  describe False = "no"',
        "",
        "main :: IO ()",
        "main = putStrLn (describe (1 > 2))",
      ),
      options: ["no", "yes", NO_COMPILE],
      answer: 0,
      output: "no",
      check: { compiles: true, stdout: "no" },
      explain: L("1 > 2 is False, a Bool, so the Bool instance answers \"no\".", "1 > 2 es False, un Bool, así que responde la instancia de Bool: \"no\".", "1 > 2 は False（Bool）。Bool のインスタンスが \"no\" と答える。"),
      win: [{ t: "print", text: "no" }],
    },
    say(L(
      "You already met badges: Show, Eq, Ord. deriving hands them out for free, or you write the instance yourself.",
      "Ya conoces insignias: Show, Eq, Ord. deriving las reparte gratis, o puedes escribir la instancia tú mismo.",
      "Show、Eq、Ord もバッジ。deriving で自動でもらえるし、インスタンスを自分で書いてもいい。",
    )),
    {
      kind: "pick",
      prompt: L("Which badge lets it print?", "¿Qué insignia permite imprimir?", "表示できるバッジは？"),
      code: 'data Owl = Owl\ninstance ___ Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print [Owl, Owl]',
      options: ["Show", "Eq", "Print"],
      answer: 0,
      check: { compiles: true, stdout: "[hoot,hoot]", wrongFail: true },
      explain: L("show belongs to the Show class. Eq has no show, and there is no Print class.", "show pertenece a la clase Show. Eq no tiene show, y no existe una clase Print.", "show は Show クラスのもの。Eq に show はないし、Print クラスもない。"),
      win: [{ t: "print", text: "[hoot,hoot]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "data Size = S | M | L deriving (Eq, Ord, Show)\n\nmain :: IO ()\nmain = print (maximum [M, S, L], compare S L, S < M)",
      options: ["(L,LT,True)", "(M,GT,False)", "(L,GT,True)"],
      answer: 0,
      output: "(L,LT,True)",
      check: { compiles: true, stdout: "(L,LT,True)" },
      explain: L("Derived Ord follows declaration order: S < M < L. compare answers LT, EQ or GT.", "El Ord derivado sigue el orden de declaración: S < M < L. compare responde LT, EQ o GT.", "deriving Ord は宣言順：S < M < L。compare は LT、EQ、GT で答える。"),
      win: [{ t: "print", text: "(L,LT,True)" }],
    },
    say(L(
      "A constraint asks for a badge: same :: Eq a => a -> a -> Bool works for ANY type that wears Eq.",
      "Una restricción pide una insignia: same :: Eq a => a -> a -> Bool sirve para CUALQUIER tipo con Eq.",
      "制約はバッジを求める。same :: Eq a => a -> a -> Bool は Eq を持つどの型にも使える。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "same :: Eq a => a -> a -> Bool\nsame x y = x == y\n\nmain :: IO ()\nmain = print (same 'a' 'a', same [1,2] [2,1])",
      options: ["(True,False)", "(True,True)", NO_COMPILE],
      answer: 0,
      output: "(True,False)",
      check: { compiles: true, stdout: "(True,False)" },
      explain: L("Char and lists both wear Eq. Lists are equal only in the same order.", "Char y las listas llevan Eq. Las listas son iguales solo en el mismo orden.", "Char もリストも Eq を持つ。リストは順番まで同じときだけ等しい。"),
      win: [{ t: "print", text: "(True,False)" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'data Owl = Owl deriving Show\ninstance Show Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print Owl',
      options: [YES, L("No: two Show badges", "No: dos insignias Show", "いいえ：Show が2つ")],
      answer: 1,
      check: { compiles: false },
      explain: L("A type gets each badge only once: Duplicate instance declarations.", "Un tipo recibe cada insignia una sola vez: Duplicate instance declarations.", "バッジは1つの型に1回だけ。Duplicate instance declarations になる。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "newtype wraps one value in a NEW type, at no runtime cost. Meters and Feet can't be mixed up.",
      "newtype envuelve un valor en un tipo NUEVO, sin costo en ejecución. Meters y Feet no se pueden mezclar.",
      "newtype は値1つを新しい型で包む。実行時コストはゼロ。Meters と Feet は混ざらない。",
    )),
    {
      kind: "predict",
      prompt: COMPILES,
      code: code(
        "newtype Meters = Meters Double",
        "newtype Feet = Feet Double",
        "",
        "climb :: Meters -> Double",
        "climb (Meters m) = m",
        "",
        "main :: IO ()",
        "main = print (climb (Feet 3))",
      ),
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L("Same Double inside, different types outside: Couldn't match 'Meters' with 'Feet'.", "Mismo Double adentro, tipos distintos afuera: Couldn't match 'Meters' with 'Feet'.", "中身は同じ Double でも型は別。Couldn't match 'Meters' with 'Feet'。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Semigroup gives <> to join two values. Monoid adds mempty, the empty one, and mconcat joins a whole list.",
      "Semigroup da <> para unir dos valores. Monoid agrega mempty, el vacío, y mconcat une toda una lista.",
      "Semigroup の <> は2つをつなぐ。Monoid には空の mempty と、リストをまとめる mconcat がある。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print ([1] <> [2], "ab" <> "cd", mconcat ["a","b","c"])',
      options: ['([1,2],"abcd","abc")', '([3],"abcd","abc")', NO_COMPILE],
      answer: 0,
      output: '([1,2],"abcd","abc")',
      check: { compiles: true, stdout: '([1,2],"abcd","abc")' },
      explain: L("For lists and strings, <> is ++ and mconcat joins them all.", "Para listas y strings, <> es ++ y mconcat las une todas.", "リストと文字列では <> は ++。mconcat は全部つなぐ。"),
      win: [{ t: "print", text: '([1,2],"abcd","abc")' }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'print (read "5")',
      options: [L("Yes: prints 5", "Sí: imprime 5", "はい：5 と表示"), L("No: read what type?", "No: ¿read de qué tipo?", "いいえ：何の型を read？")],
      answer: 1,
      check: { compiles: false },
      explain: L("read needs a known result type. Add one: read \"5\" :: Int.", "read necesita conocer el tipo del resultado. Agrégalo: read \"5\" :: Int.", "read は結果の型が必要。read \"5\" :: Int のように書こう。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "run",
      prompt: L("Shop labels must read: potion x3", "Las etiquetas deben decir: potion x3", "値札は potion x3 と表示させて"),
      starter: code("data Potion = Potion Int deriving Show", "", "main :: IO ()", "main = print (Potion 3)", ""),
      solution: code("data Potion = Potion Int", "", "instance Show Potion where", '  show (Potion n) = "potion x" ++ show n', "", "main :: IO ()", "main = print (Potion 3)", ""),
      expect: "potion x3",
      fallback: [String.raw`instance\s+Show\s+Potion\s+where`],
      explain: L("Remove deriving Show and write the instance yourself: show (Potion n) = \"potion x\" ++ show n.", "Quita deriving Show y escribe la instancia: show (Potion n) = \"potion x\" ++ show n.", "deriving Show を消して自分で書こう：show (Potion n) = \"potion x\" ++ show n。"),
    },
  ],
};

// ─── 4.2 Reaching into chests ──────────────────────────────────────────────
const functors: LessonDef = {
  slug: "functor-and-applicative",
  title: L("Reaching into chests", "Metiendo la mano en cofres", "宝箱に手をのばす"),
  concept: "functor",
  mode: "lesson",
  xp: 80,
  enemy: "haskell/partial-moth",
  enemyName: L("LID MOTH", "POLILLA TAPA", "フタモス"),
  beats: [
    say(L(
      "fmap reaches INTO a chest, changes the item, and closes the lid. The chest keeps its shape; an empty one stays empty.",
      "fmap mete la mano EN el cofre, cambia el objeto y cierra la tapa. El cofre conserva su forma; uno vacío sigue vacío.",
      "fmap は宝箱の中に手を入れて中身を変え、ふたを閉める。形はそのまま、空の箱は空のまま。",
    )),
    {
      kind: "act",
      prompt: L("Reach into chests with fmap", "Mete la mano en cofres con fmap", "fmap で宝箱に手を入れよう"),
      steps: [
        { label: L("JUST 2", "JUST 2", "Just 2"), line: "print (fmap (+1) (Just 2))",
          effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "Just", value: "3" }, { t: "print", text: "Just 3" }], output: "Just 3" },
        { label: L("NOTHING", "NOTHING", "Nothing"), line: "print (fmap (+1) Nothing)",
          effects: [{ t: "say", actor: "hero", text: L("Still empty", "Sigue vacío", "空のまま") }, { t: "print", text: "Nothing" }], output: "Nothing" },
        { label: L("A LIST", "UNA LISTA", "リスト"), line: "print ((+1) <$> [1,2,3])",
          effects: [{ t: "print", text: "[2,3,4]" }, { t: "attack", from: "hero", to: "enemy" }], output: "[2,3,4]" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (fmap (+1) (Just 2), fmap (+1) Nothing)",
      options: ["(Just 3,Nothing)", "(3,Nothing)", "(Just 3,Just 1)"],
      answer: 0,
      output: "(Just 3,Nothing)",
      check: { compiles: true, stdout: "(Just 3,Nothing)" },
      explain: L("fmap changes what is inside. Nothing has nothing inside, so it stays Nothing.", "fmap cambia lo de adentro. Nothing no tiene nada adentro, así que sigue Nothing.", "fmap は中身を変える。Nothing は中身がないので Nothing のまま。"),
      win: [{ t: "print", text: "(Just 3,Nothing)" }],
    },
    {
      kind: "type",
      prompt: L("The operator form of fmap", "La forma operador de fmap", "fmap の演算子版"),
      code: "print ((+1) ___ Just 2)",
      answer: "<$>",
      check: { compiles: true, stdout: "Just 3" },
      explain: L("f <$> x is just fmap f x written as an operator.", "f <$> x es fmap f x escrito como operador.", "f <$> x は fmap f x の演算子版。"),
      win: [{ t: "print", text: "Just 3" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (fmap length (Right "abc" :: Either String String))\nprint (fmap length (Left "e" :: Either String String))',
      options: [L("Right 3, then Left \"e\"", "Right 3, luego Left \"e\"", "Right 3、次に Left \"e\""), L("Right 3, then Left 1", "Right 3, luego Left 1", "Right 3、次に Left 1")],
      answer: 0,
      output: 'Right 3\nLeft "e"',
      check: { compiles: true, stdout: 'Right 3\nLeft "e"' },
      explain: L("fmap only touches the Right side. A Left error passes through unchanged.", "fmap solo toca el lado Right. Un error Left pasa sin cambios.", "fmap が触るのは Right だけ。Left のエラーはそのまま通る。"),
      win: [{ t: "print", text: "Right 3" }, { t: "print", text: 'Left "e"' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (fmap (+1) (10, 20))",
      options: ["(10,21)", "(11,21)", "(11,20)"],
      answer: 0,
      output: "(10,21)",
      check: { compiles: true, stdout: "(10,21)" },
      explain: L("For a pair, the chest's item is the SECOND part. The first is part of the shape.", "En un par, el objeto del cofre es la SEGUNDA parte. La primera es parte de la forma.", "ペアでは中身は2つ目。1つ目は箱の形の一部だよ。"),
      win: [{ t: "print", text: "(10,21)" }],
    },
    say(L(
      "Applicative combines SEVERAL chests: f <$> a <*> b. If any chest is empty, the result is empty too.",
      "Applicative combina VARIOS cofres: f <$> a <*> b. Si alguno está vacío, el resultado también.",
      "Applicative は複数の宝箱を組み合わせる：f <$> a <*> b。どれか空なら結果も空。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((+) <$> Just 3 <*> Just 4, (+) <$> Just 3 <*> Nothing)",
      options: ["(Just 7,Nothing)", "(Just 7,Just 3)", "(7,Nothing)"],
      answer: 0,
      output: "(Just 7,Nothing)",
      check: { compiles: true, stdout: "(Just 7,Nothing)" },
      explain: L("Both chests full: 3 + 4 inside a Just. One empty chest makes the whole result Nothing.", "Ambos llenos: 3 + 4 dentro de un Just. Un cofre vacío hace que todo sea Nothing.", "両方あれば Just の中で 3 + 4。1つでも空なら全体が Nothing。"),
      win: [{ t: "print", text: "(Just 7,Nothing)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print ((+) <$> [1,2] <*> [10,20])",
      options: ["[11,21,12,22]", "[11,22]", "[11,12,21,22]"],
      answer: 0,
      output: "[11,21,12,22]",
      check: { compiles: true, stdout: "[11,21,12,22]" },
      explain: L("Lists try every combination: 1 with 10 and 20, then 2 with 10 and 20.", "Las listas prueban cada combinación: 1 con 10 y 20, luego 2 con 10 y 20.", "リストは全組み合わせ。1 と 10, 20、次に 2 と 10, 20。"),
      win: [{ t: "print", text: "[11,21,12,22]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print ((+) <$> Left "a" <*> (Left "b" :: Either String Int))',
      options: ['Left "a"', 'Left "b"', 'Left "ab"'],
      answer: 0,
      output: 'Left "a"',
      check: { compiles: true, stdout: 'Left "a"' },
      explain: L("With Either, the FIRST Left wins and the rest is never looked at.", "Con Either gana el PRIMER Left y el resto ni se mira.", "Either では最初の Left が勝ち、残りは見られない。"),
      win: [{ t: "print", text: 'Left "a"' }],
    },
    {
      kind: "pick",
      prompt: L("Pair up two chests", "Empareja dos cofres", "2つの宝箱をペアに"),
      code: 'print (___ <$> Just 1 <*> Just "a")',
      options: ["(,)", "(+)"],
      answer: 0,
      check: { compiles: true, stdout: 'Just (1,"a")', wrongFail: true },
      explain: L("(,) builds a pair from two values. (+) can't add a number to a String.", "(,) arma un par con dos valores. (+) no puede sumar un número a un String.", "(,) は2つの値からペアを作る。(+) で数と String は足せない。"),
      win: [{ t: "print", text: 'Just (1,"a")' }],
    },
    {
      kind: "run",
      prompt: L("Add the apple and the pear: Just 7", "Suma la manzana y la pera: Just 7", "りんごとなしを足そう：Just 7"),
      starter: code(
        "main :: IO ()",
        "main = do",
        '  let prices = [("apple", 3), ("pear", 4)]',
        '  print ((+) <$> lookup "apple" prices <*> lookup "peach" prices)',
        "",
      ),
      solution: code(
        "main :: IO ()",
        "main = do",
        '  let prices = [("apple", 3), ("pear", 4)]',
        '  print ((+) <$> lookup "apple" prices <*> lookup "pear" prices)',
        "",
      ),
      expect: "Just 7",
      fallback: [String.raw`lookup\s+"pear"\s+prices`],
      explain: L("There is no peach, so one chest was empty and the result was Nothing.", "No hay durazno, así que un cofre estaba vacío y el resultado fue Nothing.", "peach はないので宝箱が1つ空になり、結果が Nothing だった。"),
    },
  ],
};

// ─── 4.3 A chain of chests ─────────────────────────────────────────────────
const TABLE = 'table :: [(Int, String)]\ntable = [(1, "lam"), (2, "bda")]';

const monads: LessonDef = {
  slug: "monads-and-do",
  title: L("A chain of chests", "Una cadena de cofres", "宝箱のくさり"),
  concept: "monads",
  mode: "lesson",
  xp: 85,
  enemy: "haskell/bottom-wraith",
  enemyName: L("CHAIN WRAITH", "ESPECTRO CADENA", "クサリのレイス"),
  beats: [
    say(L(
      "A MONAD chains steps that each return a chest. >>= opens the chest and feeds the item to the next step.",
      "Una MÓNADA encadena pasos que devuelven un cofre. >>= abre el cofre y pasa el objeto al siguiente paso.",
      "モナドは宝箱を返す処理をつなぐ。>>= は箱を開けて中身を次の処理に渡す。",
    )),
    {
      kind: "act",
      prompt: L("Feed chests down the chain", "Pasa cofres por la cadena", "宝箱をくさりに流そう"),
      steps: [
        { label: L("FULL CHEST", "COFRE LLENO", "中身あり"), line: "print (Just 5 >>= \\x -> Just (x * 2))",
          effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "give", to: "ally" }, { t: "print", text: "Just 10" }], output: "Just 10" },
        { label: L("EMPTY CHEST", "COFRE VACÍO", "空の箱"), line: "print (Nothing >>= \\x -> Just (x * 2))",
          effects: [{ t: "shake" }, { t: "banner", text: L("SHORT-CIRCUIT", "CORTOCIRCUITO", "ショートした！") }, { t: "print", text: "Nothing" }], output: "Nothing" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (Just 5 >>= \\x -> Just (x * 2))",
      options: ["Just 10", "10", "Just (Just 10)"],
      answer: 0,
      output: "Just 10",
      check: { compiles: true, stdout: "Just 10" },
      explain: L(">>= opens Just 5, gives 5 to the lambda, and the lambda returns the new chest Just 10.", ">>= abre Just 5, pasa 5 a la lambda y la lambda devuelve el cofre nuevo Just 10.", ">>= が Just 5 を開けて 5 をラムダに渡し、ラムダが新しい箱 Just 10 を返す。"),
      win: [{ t: "print", text: "Just 10" }],
    },
    {
      kind: "type",
      prompt: L("Open and feed the next step", "Abre y alimenta el siguiente paso", "開けて次へ渡そう"),
      code: "print (Just 5 ___ \\x -> Just (x * 2))",
      answer: ">>=",
      check: { compiles: true, stdout: "Just 10" },
      explain: L(">>= is called bind: it binds the item to x for the next step.", ">>= se llama bind: liga el objeto a x para el siguiente paso.", ">>= はバインド。中身を x に結びつけて次へ渡す。"),
      win: [{ t: "print", text: "Just 10" }],
    },
    say(L(
      "do notation is sugar for >>=. Each x <- chest opens one chest. One empty chest stops the whole block.",
      "La notación do es azúcar para >>=. Cada x <- cofre abre un cofre. Un cofre vacío detiene todo el bloque.",
      "do 記法は >>= の糖衣構文。x <- 箱 で1つ開ける。空の箱が1つでもあればブロック全体が止まる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: TABLE + "\n\nboth :: Maybe String\nboth = do\n  a <- lookup 1 table\n  b <- lookup 2 table\n  return (a ++ b)\n\nmain :: IO ()\nmain = print both",
      options: ['Just "lambda"', '"lambda"', "Nothing"],
      answer: 0,
      output: 'Just "lambda"',
      check: { compiles: true, stdout: 'Just "lambda"' },
      explain: L("Both lookups found a value, so return wraps \"lam\" ++ \"bda\" in a Just.", "Ambos lookup hallaron valor, así que return envuelve \"lam\" ++ \"bda\" en un Just.", "両方の lookup が成功。return が \"lam\" ++ \"bda\" を Just に包む。"),
      win: [{ t: "print", text: 'Just "lambda"' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: TABLE + "\n\nboth :: Maybe String\nboth = do\n  a <- lookup 1 table\n  b <- lookup 3 table\n  return (a ++ b)\n\nmain :: IO ()\nmain = print both",
      options: ["Nothing", 'Just "lam"', L("Crash", "Crash", "クラッシュ")],
      answer: 0,
      output: "Nothing",
      check: { compiles: true, stdout: "Nothing" },
      explain: L("There is no key 3. That empty chest short-circuits the block: the answer is Nothing.", "No hay clave 3. Ese cofre vacío corta el bloque: la respuesta es Nothing.", "キー 3 はない。空の箱でブロックがショートし、答えは Nothing。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "banner", text: L("SHORT-CIRCUIT", "CORTOCIRCUITO", "ショートした！") }, { t: "print", text: "Nothing" }],
    },
    say(L(
      "Either works the same way, but stops at the first Left and keeps its reason.",
      "Either funciona igual, pero se detiene en el primer Left y conserva su razón.",
      "Either も同じ。ただし最初の Left で止まり、その理由を残す。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "age :: String -> Either String Int",
        'age s | not (null s) && all (`elem` "0123456789") s = Right (read s)',
        '      | otherwise = Left ("bad age: " ++ s)',
        "",
        "main :: IO ()",
        'main = print (do { a <- age "30"; b <- age "x1"; c <- age "4"; return (a + b + c) })',
      ),
      options: ['Left "bad age: x1"', "Right 34", 'Left "bad age: 4"'],
      answer: 0,
      output: 'Left "bad age: x1"',
      check: { compiles: true, stdout: 'Left "bad age: x1"' },
      explain: L("\"x1\" fails, so the chain stops there with that Left. \"4\" is never checked.", "\"x1\" falla, así que la cadena se detiene ahí con ese Left. \"4\" ni se revisa.", "\"x1\" で失敗し、その Left で止まる。\"4\" は調べられない。"),
      win: [{ t: "print", text: 'Left "bad age: x1"' }],
    },
    say(L(
      "Careful: return does NOT exit the block. It only wraps a value in a chest, and the block goes on.",
      "Cuidado: return NO sale del bloque. Solo envuelve un valor en un cofre, y el bloque sigue.",
      "注意：return はブロックを抜けない。値を箱に包むだけで、処理は続く。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (do { x <- Just 1; return 99; Just (x + 1) })",
      options: ["Just 2", "Just 99", "99"],
      answer: 0,
      output: "Just 2",
      check: { compiles: true, stdout: "Just 2" },
      explain: L("return 99 makes Just 99, which is thrown away. The last line decides: Just 2.", "return 99 crea Just 99, que se descarta. La última línea decide: Just 2.", "return 99 は Just 99 を作って捨てられる。最後の行が答え：Just 2。"),
      win: [{ t: "print", text: "Just 2" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'print (do { x <- [1,2]; y <- "ab"; return (x, y) })',
      options: ["[(1,'a'),(1,'b'),(2,'a'),(2,'b')]", "[(1,'a'),(2,'b')]", "(2,'b')"],
      answer: 0,
      output: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]",
      check: { compiles: true, stdout: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]" },
      explain: L("In the list monad, each <- tries every item, so you get every combination.", "En la mónada lista, cada <- prueba cada elemento y obtienes todas las combinaciones.", "リストのモナドでは <- が全要素を試すので、全組み合わせになる。"),
      win: [{ t: "print", text: "[(1,'a'),(1,'b'),(2,'a'),(2,'b')]" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "print (sequence [Just 1, Just 2], sequence [Just 1, Nothing])",
      options: ["(Just [1,2],Nothing)", "([Just 1,Just 2],[Just 1,Nothing])", "(Just [1,2],Just [1])"],
      answer: 0,
      output: "(Just [1,2],Nothing)",
      check: { compiles: true, stdout: "(Just [1,2],Nothing)" },
      explain: L("sequence turns a list of chests into one chest with a list. One empty chest empties it all.", "sequence convierte una lista de cofres en un cofre con una lista. Uno vacío lo vacía todo.", "sequence は箱のリストを、リスト入りの箱1つに変える。空が1つあれば全部空。"),
      win: [{ t: "print", text: "(Just [1,2],Nothing)" }],
    },
    {
      kind: "run",
      prompt: L('Overdrawing must give Left "insufficient funds"', 'Sacar de más debe dar Left "insufficient funds"', '残高不足なら Left "insufficient funds" に'),
      starter: code(
        "withdraw :: Int -> Int -> Either String Int",
        "withdraw bal amt = if amt > bal then Right bal else Right (bal - amt)",
        "",
        "main :: IO ()",
        "main = print (do { b1 <- withdraw 100 30; withdraw b1 90 })",
        "",
      ),
      solution: code(
        "withdraw :: Int -> Int -> Either String Int",
        'withdraw bal amt = if amt > bal then Left "insufficient funds" else Right (bal - amt)',
        "",
        "main :: IO ()",
        "main = print (do { b1 <- withdraw 100 30; withdraw b1 90 })",
        "",
      ),
      expect: 'Left "insufficient funds"',
      fallback: [String.raw`then\s+Left\s+"insufficient funds"`],
      explain: L("Right bal hid the failure. A Left stops the chain and says why.", "Right bal escondía el fallo. Un Left detiene la cadena y dice por qué.", "Right bal は失敗を隠していた。Left ならくさりを止めて理由を伝える。"),
    },
  ],
};

// ─── 4.4 Speaking scrolls and the key ring ─────────────────────────────────
const ioMaps: LessonDef = {
  slug: "io-and-maps",
  title: L("Scrolls and the key ring", "Pergaminos y el llavero", "巻物とカギの輪"),
  concept: "io",
  mode: "lesson",
  xp: 85,
  enemy: "haskell/partial-moth",
  enemyName: L("KEY MOTH", "POLILLA LLAVE", "カギモス"),
  beats: [
    say(L(
      "IO is a monad too! An IO action is a sealed scroll of instructions. Writing it does nothing; main reads it aloud.",
      "¡IO también es una mónada! Una acción IO es un pergamino sellado de instrucciones. Escribirla no hace nada; main la lee.",
      "IO もモナド！IO アクションは指示の巻物。書くだけでは何も起きず、main が読み上げる。",
    )),
    {
      kind: "act",
      prompt: L("Write a scroll, then read it twice", "Escribe un pergamino y léelo dos veces", "巻物を書いて、2回読もう"),
      steps: [
        { label: L("WRITE", "ESCRIBIR", "書く"), line: 'let act = putStrLn "hi"',
          effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "act" }, { t: "say", actor: "hero", text: L("Silence...", "Silencio...", "しーん…") }] },
        { label: L("READ", "LEER", "読む"), line: "act", effects: [{ t: "print", text: "hi" }], output: "hi" },
        { label: L("AGAIN", "OTRA VEZ", "もう一度"), line: "act", effects: [{ t: "print", text: "hi" }, { t: "attack", from: "hero", to: "enemy" }], output: "hi" },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: 'let act = putStrLn "hi"\nact\nact',
      options: [L("hi, twice", "hi, dos veces", "hi を2回"), L("hi, three times", "hi, tres veces", "hi を3回"), L("hi, once", "hi, una vez", "hi を1回")],
      answer: 0,
      output: "hi\nhi",
      check: { compiles: true, stdout: "hi\nhi" },
      explain: L("let only writes the scroll. Each line act runs it once: two runs, two hi.", "let solo escribe el pergamino. Cada línea act lo ejecuta una vez: dos veces, dos hi.", "let は巻物を書くだけ。act の行ごとに1回実行、だから hi が2回。"),
      win: [{ t: "print", text: "hi" }, { t: "print", text: "hi" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'greet :: String -> String\ngreet n = putStrLn ("hi " ++ n)\n\nmain :: IO ()\nmain = putStrLn (greet "Ada")',
      options: [YES, L("No: a pure function can't print", "No: una función pura no imprime", "いいえ：純粋関数は表示できない")],
      answer: 1,
      check: { compiles: false },
      explain: L("putStrLn gives an IO (), not a String. Only IO actions can speak.", "putStrLn da un IO (), no un String. Solo las acciones IO pueden hablar.", "putStrLn は String ではなく IO () を返す。話せるのは IO だけ。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "To run an action for each item, use mapM_ or forM_. map print xs only BUILDS a list of scrolls.",
      "Para correr una acción por elemento, usa mapM_ o forM_. map print xs solo CONSTRUYE una lista de pergaminos.",
      "要素ごとにアクションを実行するなら mapM_ か forM_。map print xs は巻物のリストを作るだけ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "mapM_ print [1,2,3]",
      options: [L("1, 2, 3 on three lines", "1, 2, 3 en tres líneas", "1, 2, 3 を3行で"), "[1,2,3]", L("Nothing", "Nada", "何も出ない")],
      answer: 0,
      output: "1\n2\n3",
      check: { compiles: true, stdout: "1\n2\n3" },
      explain: L("mapM_ runs print on each item, in order, and throws the results away.", "mapM_ ejecuta print en cada elemento, en orden, y descarta los resultados.", "mapM_ は各要素に順番に print を実行し、結果は捨てる。"),
      win: [{ t: "print", text: "1" }, { t: "print", text: "2" }, { t: "print", text: "3" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: 'map print [1, 2, 3]\nputStrLn "done"',
      options: [YES, NO],
      answer: 1,
      check: { compiles: false },
      explain: L("map print gives a list of actions, not an action. A do line must be an IO action.", "map print da una lista de acciones, no una acción. Una línea de do debe ser una acción IO.", "map print はアクションのリストで、アクションではない。do の行は IO アクションが必要。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: "import Control.Monad (forM_)\n\nmain :: IO ()\nmain = forM_ [1..3] $ \\i -> putStrLn (replicate i '*')",
      options: [L("*, **, *** on three lines", "*, **, *** en tres líneas", "*, **, *** を3行で"), "***", L("Does not compile", "No compila", "コンパイルできない")],
      answer: 0,
      output: "*\n**\n***",
      check: { compiles: true, stdout: "*\n**\n***" },
      explain: L("forM_ is mapM_ with the list first. Import it from Control.Monad.", "forM_ es mapM_ con la lista primero. Se importa de Control.Monad.", "forM_ はリストが先の mapM_。Control.Monad から import する。"),
      win: [{ t: "print", text: "*" }, { t: "print", text: "**" }, { t: "print", text: "***" }],
    },
    say(L(
      "Data.Map is a key ring: keys open values, kept sorted. M.lookup answers with a Maybe, since a key may be missing.",
      "Data.Map es un llavero: las claves abren valores, siempre ordenados. M.lookup responde con Maybe, la clave puede faltar.",
      "Data.Map はカギの輪。キーで値を開け、キー順に並ぶ。キーがないかもしれないので M.lookup は Maybe。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("b",2),("a",1)]\n  print m',
      options: ['fromList [("a",1),("b",2)]', 'fromList [("b",2),("a",1)]', '[("a",1),("b",2)]'],
      answer: 0,
      output: 'fromList [("a",1),("b",2)]',
      check: { compiles: true, stdout: 'fromList [("a",1),("b",2)]' },
      explain: L("A Map keeps its keys sorted, whatever order you gave them in.", "Un Map mantiene sus claves ordenadas, sin importar el orden en que las diste.", "Map は渡した順番に関係なく、キーを並べて保つ。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "m" }],
      win: [{ t: "print", text: 'fromList [("a",1),("b",2)]' }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("a",1),("b",2)]\n  print (M.lookup "a" m, M.lookup "z" m, M.findWithDefault 0 "z" m)',
      options: ["(Just 1,Nothing,0)", "(1,0,0)", "(Just 1,Nothing,Nothing)"],
      answer: 0,
      output: "(Just 1,Nothing,0)",
      check: { compiles: true, stdout: "(Just 1,Nothing,0)" },
      explain: L("lookup gives a Maybe; findWithDefault gives the default when the key is missing.", "lookup da un Maybe; findWithDefault da el valor por defecto si falta la clave.", "lookup は Maybe、findWithDefault はキーがなければデフォルト値。"),
      win: [{ t: "print", text: "(Just 1,Nothing,0)" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  let m = M.fromList [("a",1),("b",2)]\n  let m2 = M.insert "c" 3 m\n  print (M.size m, M.size m2)',
      options: ["(2,3)", "(3,3)", "(2,2)"],
      answer: 0,
      output: "(2,3)",
      check: { compiles: true, stdout: "(2,3)" },
      explain: L("insert returns a NEW key ring. The old m still has two keys.", "insert devuelve un llavero NUEVO. El m viejo sigue con dos claves.", "insert は新しいカギの輪を返す。元の m はキー2つのまま。"),
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "m", value: "2" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "m2", value: "3" }, { t: "print", text: "(2,3)" }],
    },
    {
      kind: "predict",
      prompt: HAPPENS,
      code: MAP + '  let m = M.fromList [("a", 1 :: Int)]\n  print (m M.! "a")\n  print (m M.! "b")',
      options: [L("Prints 1, then crashes", "Imprime 1 y luego falla", "1 を表示してクラッシュ"), L("Prints 1 and 0", "Imprime 1 y 0", "1 と 0 を表示"), L("Prints 1 and Nothing", "Imprime 1 y Nothing", "1 と Nothing を表示")],
      answer: 0,
      check: { compiles: true, throws: "given key is not an element in the map" },
      explain: L("M.! is partial: a missing key crashes. Prefer M.lookup or findWithDefault.", "M.! es parcial: una clave que falta falla. Prefiere M.lookup o findWithDefault.", "M.! は部分関数。キーがないと落ちる。M.lookup か findWithDefault を使おう。"),
      win: [{ t: "print", text: "1" }, { t: "shake" }, { t: "attack", from: "enemy", to: "hero" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: MAP + '  print (M.toList (M.fromListWith (+) [(c, 1) | c <- "banana"]))',
      options: ["[('a',3),('b',1),('n',2)]", "[('b',1),('a',3),('n',2)]", "[('a',1),('b',1),('n',1)]"],
      answer: 0,
      output: "[('a',3),('b',1),('n',2)]",
      check: { compiles: true, stdout: "[('a',3),('b',1),('n',2)]" },
      explain: L("fromListWith (+) adds the values of repeated keys: a counter. toList comes out sorted.", "fromListWith (+) suma los valores de claves repetidas: un contador. toList sale ordenado.", "fromListWith (+) は重複キーの値を足す。カウンターになる。toList はキー順。"),
      win: [{ t: "print", text: "[('a',3),('b',1),('n',2)]" }],
    },
    {
      kind: "run",
      prompt: L("Count the words: owl must appear 2 times", "Cuenta las palabras: owl debe salir 2 veces", "単語を数えよう：owl は2回"),
      starter: code(
        "import qualified Data.Map as M",
        "",
        "main :: IO ()",
        "main = do",
        '  let counts = M.fromList [(w, 1) | w <- words "owl cat owl"]',
        '  print (M.lookup "owl" counts)',
        "",
      ),
      solution: code(
        "import qualified Data.Map as M",
        "",
        "main :: IO ()",
        "main = do",
        '  let counts = M.fromListWith (+) [(w, 1) | w <- words "owl cat owl"]',
        '  print (M.lookup "owl" counts)',
        "",
      ),
      expect: "Just 2",
      fallback: [String.raw`fromListWith\s*\(\s*\+\s*\)`],
      explain: L("fromList keeps only the last duplicate. fromListWith (+) adds them up.", "fromList conserva solo el último duplicado. fromListWith (+) los suma.", "fromList は重複の最後だけ残す。fromListWith (+) なら足し合わせる。"),
    },
  ],
};

// ─── Boss: The Tower Guardian ──────────────────────────────────────────────
const boss: LessonDef = {
  slug: "tower-boss",
  title: L("Boss: The Tower Guardian", "Jefe: El Guardián", "ボス：塔の番人"),
  concept: "monads",
  mode: "boss",
  xp: 200,
  enemy: "haskell/partial-moth",
  enemyName: L("TOWER GUARDIAN", "GUARDIÁN", "塔の番人"),
  beats: [
    enemySays(L(
      "I AM THE TOWER GUARDIAN. Badges, chests, chains and scrolls: one wrong step and you fall to the mountain!",
      "SOY EL GUARDIÁN DE LA TORRE. Insignias, cofres, cadenas y pergaminos: ¡un paso en falso y caes a la montaña!",
      "我は塔の番人。バッジ、宝箱、くさり、巻物。一歩まちがえば山まで落ちるぞ！",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: "r <- mapM (\\x -> do { print x; return (x * 2) }) [1,2]\nprint r", options: [L("1, 2, then [2,4]", "1, 2 y luego [2,4]", "1, 2、そして [2,4]"), "[2,4]", L("1, 2 only", "Solo 1, 2", "1, 2 だけ")], answer: 0, output: "1\n2\n[2,4]", check: { compiles: true, stdout: "1\n2\n[2,4]" }, explain: L("mapM runs each action in order AND collects the results.", "mapM ejecuta cada acción en orden Y junta los resultados.", "mapM は順に実行し、結果も集める。"), win: [{ t: "print", text: "[2,4]" }] },
    { kind: "predict", time: 12, prompt: COMPILES, code: 'print (read "5")', options: [L("Yes: prints 5", "Sí: imprime 5", "はい：5 と表示"), NO], answer: 1, check: { compiles: false }, explain: L("read needs to know its result type: ambiguous.", "read necesita saber su tipo de resultado: ambiguo.", "read は結果の型が必要。あいまいでエラー。"), win: [{ t: "shake" }] },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (fmap (*2) (3, 4))", options: ["(3,8)", "(6,8)", "(6,4)"], answer: 0, output: "(3,8)", check: { compiles: true, stdout: "(3,8)" }, explain: L("fmap on a pair touches only the second part.", "fmap en un par toca solo la segunda parte.", "ペアの fmap は2つ目だけ変える。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (do { x <- Just 1; return 99; Just (x + 1) })", options: ["Just 2", "Just 99"], answer: 0, output: "Just 2", check: { compiles: true, stdout: "Just 2" }, explain: L("return does not exit; the last line wins.", "return no sale; gana la última línea.", "return は抜けない。最後の行が答え。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print ([1,2,3] >>= \\x -> [x, x * 10])", options: ["[1,10,2,20,3,30]", "[10,20,30]", "[[1,10],[2,20],[3,30]]"], answer: 0, output: "[1,10,2,20,3,30]", check: { compiles: true, stdout: "[1,10,2,20,3,30]" }, explain: L("List >>= maps each item to a list, then joins them.", ">>= de listas mapea cada elemento a una lista y las une.", "リストの >>= は各要素をリストにして連結。") },
    { kind: "predict", time: 15, prompt: PRINT, code: "positive :: Int -> Maybe Int\npositive x = if x > 0 then Just x else Nothing\n\nmain :: IO ()\nmain = print (traverse positive [1,2,3], traverse positive [1,0,3])", options: ["(Just [1,2,3],Nothing)", "([Just 1,Just 2,Just 3],[Just 1,Nothing,Just 3])", "(Just [1,2,3],Just [1,3])"], answer: 0, output: "(Just [1,2,3],Nothing)", check: { compiles: true, stdout: "(Just [1,2,3],Nothing)" }, explain: L("traverse is map plus sequence: one Nothing fails it all.", "traverse es map más sequence: un Nothing lo hace fallar todo.", "traverse は map + sequence。Nothing 1つで全体失敗。") },
    { kind: "predict", time: 15, prompt: PRINT, code: MAP + '  let m = M.fromList [("b",2),("a",1)]\n  print (M.toList (M.unionWith (+) m (M.fromList [("a",5),("d",4)])))', options: ['[("a",6),("b",2),("d",4)]', '[("a",5),("b",2),("d",4)]', '[("b",2),("a",6),("d",4)]'], answer: 0, output: '[("a",6),("b",2),("d",4)]', check: { compiles: true, stdout: '[("a",6),("b",2),("d",4)]' }, explain: L("unionWith (+) adds values of shared keys; the result is sorted.", "unionWith (+) suma valores de claves compartidas; sale ordenado.", "unionWith (+) は共通キーの値を足す。キー順。") },
    { kind: "predict", time: 12, prompt: PRINT, code: "print (Just [1] <> Nothing, Just [1] <> Just [2])", options: ["(Just [1],Just [1,2])", "(Nothing,Just [1,2])", "(Just [1],Just [2])"], answer: 0, output: "(Just [1],Just [1,2])", check: { compiles: true, stdout: "(Just [1],Just [1,2])" }, explain: L("<> on Maybe skips a Nothing and joins the insides.", "<> en Maybe ignora Nothing y une lo de adentro.", "Maybe の <> は Nothing を飛ばし中身をつなぐ。") },
    { kind: "predict", time: 12, prompt: HAPPENS, code: MAP + '  let m = M.fromList [(1, "owl")]\n  putStrLn (m M.! 2)', options: [L("Crash: key not in map", "Crash: clave ausente", "クラッシュ：キーなし"), '""', "Nothing"], answer: 0, check: { compiles: true, throws: "given key is not an element in the map" }, explain: L("M.! crashes on a missing key.", "M.! falla con una clave ausente.", "M.! はキーがないと落ちる。"), win: [{ t: "shake" }] },
    { kind: "pick", time: 15, prompt: L("Run an action per item", "Una acción por elemento", "要素ごとに実行"), code: '___ putStrLn ["a", "b"]\nputStrLn "done"', options: ["mapM_", "map"], answer: 0, check: { compiles: true, stdout: "a\nb\ndone", wrongFail: true }, explain: L("map only builds a list of actions; mapM_ runs them.", "map solo arma una lista de acciones; mapM_ las ejecuta.", "map はリストを作るだけ。実行は mapM_。") },
    { kind: "type", time: 12, prompt: L("Give Owl the Show badge", "Dale a Owl la insignia Show", "Owl に Show を"), code: 'data Owl = Owl\n___ Show Owl where\n  show Owl = "hoot"\n\nmain :: IO ()\nmain = print Owl', answer: "instance", check: { compiles: true, stdout: "hoot" }, explain: L("instance gives a class to one type.", "instance da una clase a un tipo.", "instance で型にクラスを与える。") },
    enemySays(L(
      "No... every badge earned, every chest opened safely. Lambdara's sky is pure again. Well climbed, functional hero.",
      "No... cada insignia ganada, cada cofre abierto con cuidado. El cielo de Lambdara vuelve a ser puro. Bien subido, héroe funcional.",
      "ばかな…すべてのバッジを得て、宝箱を安全に開けたとは。ラムダラの空はまた純粋だ。見事だ、関数の勇者よ。",
    )),
  ],
};

export const monadTower: RegionDef = {
  slug: "monad-tower",
  name: L("Monad Tower", "Torre Mónada", "モナドの塔"),
  subtitle: L("Classes · Functor · Monad · IO", "Clases · Functor · Monad · IO", "型クラス・Functor・Monad・IO"),
  theme: "tower",
  lessons: [typeClasses, functors, monads, ioMaps, boss],
};
