import type { CodeTaskBeat, ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Coding tasks for planet Scriptara (TypeScript). The tests run in the player's browser (js-browser
// runner) after the player's code, as one module, so a test that declares names wraps itself in
// { ... }. Async tests use top-level await on resolved promises only. The validator proves the
// solution type-checks under tsc --strict and passes, the starter fails and each near miss fails.

const c = (...lines: string[]) => lines.join("\n") + "\n";

// ─── REGION BOSSES ────────────────────────────────────────────────────────────

/** Value Village boss: strings to numbers without the coercion traps. */
export const parseAmountTask: CodeTaskBeat = {
  slug: "parse-amount",
  kind: "code",
  mode: "ide",
  prompt: L("Mini project: read the golem's price tags", "Mini proyecto: lee las etiquetas del gólem", "ミニ課題：ゴーレムの値札を読む"),
  brief: L(
    "Write parseAmount(raw): raw is a price tag as text. Ignore spaces around it and return the number it holds, or null when it is not a number at all: empty or blank text, or text with junk like \"12abc\". Careful: \"0\" is a real price, and Number(\"\") is 0.",
    "Escribe parseAmount(raw): raw es una etiqueta de precio como texto. Ignora los espacios alrededor y devuelve el número que contiene, o null si no es un número: texto vacío o en blanco, o con basura como \"12abc\". Ojo: \"0\" es un precio real, y Number(\"\") da 0.",
    "parseAmount(raw) を書こう。raw は文字列の値札。前後の空白は無視して、その数値を返す。数値でなければ null：空や空白だけの文字列、\"12abc\" のようなゴミ入りも null。注意：\"0\" は本物の値段で、Number(\"\") は 0 になる。",
  ),
  starter: c(
    "function parseAmount(raw: string): number | null {",
    "  // your code here",
    "  return null;",
    "}",
  ),
  solution: c(
    "function parseAmount(raw: string): number | null {",
    "  const text = raw.trim();",
    '  if (text === "") return null;',
    "  const n = Number(text);",
    "  return Number.isNaN(n) ? null : n;",
    "}",
  ),
  nearMiss: [
    // parseFloat stops at the first bad character: "12abc" becomes 12.
    c(
      "function parseAmount(raw: string): number | null {",
      "  const n = parseFloat(raw);",
      "  return Number.isNaN(n) ? null : n;",
      "}",
    ),
    // || treats 0 as missing.
    c(
      "function parseAmount(raw: string): number | null {",
      "  return Number(raw.trim()) || null;",
      "}",
    ),
    // Blank text converts to 0.
    c(
      "function parseAmount(raw: string): number | null {",
      "  const n = Number(raw);",
      "  return Number.isNaN(n) ? null : n;",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(parseAmount("42"));', expect: "42" },
    { run: 'console.log(parseAmount("abc"));', expect: "null" },
    { run: 'console.log(parseAmount(" 2.5 "));', expect: "2.5", hidden: true },
    { run: 'console.log(parseAmount("12abc"));', expect: "null", hidden: true },
    { run: 'console.log(parseAmount("0"));', expect: "0", hidden: true },
    { run: 'console.log(parseAmount("   "));', expect: "null", hidden: true },
  ],
  hint: L(
    "Number() rejects junk but turns blank text into 0. Check for blank first, then test the result with Number.isNaN.",
    "Number() rechaza la basura pero da 0 con texto en blanco. Revisa el blanco primero y luego usa Number.isNaN.",
    "Number() はゴミは弾くが空白は 0 にする。先に空白を調べ、結果は Number.isNaN で確かめよう。",
  ),
  note: "coercion-recap",
  explain: L(
    "Trim, return null for empty text, then Number(): it rejects \"12abc\" with NaN. Test NaN with Number.isNaN, never || (0 is falsy).",
    "Recorta, devuelve null si queda vacío y luego Number(): rechaza \"12abc\" con NaN. Prueba NaN con Number.isNaN, nunca con || (0 es falsy).",
    "trim して空なら null、次に Number()。\"12abc\" は NaN になる。NaN は Number.isNaN で調べ、|| は使わない（0 は falsy）。",
  ),
};

/** Closure Forest boss: a counter whose state lives in a closure. */
export const makeCounterTask: CodeTaskBeat = {
  slug: "make-counter",
  kind: "code",
  mode: "ide",
  prompt: L("Mini project: the wraith's counting stones", "Mini proyecto: las piedras del espectro", "ミニ課題：亡霊の数え石"),
  brief: L(
    "Write makeCounter(start, step = 1). It returns an object with next(), which adds step and returns the new value, and reset(), which goes back to start. Every counter keeps its own value: two counters never share state.",
    "Escribe makeCounter(start, step = 1). Devuelve un objeto con next(), que suma step y devuelve el valor nuevo, y reset(), que vuelve a start. Cada contador guarda su propio valor: dos contadores nunca comparten estado.",
    "makeCounter(start, step = 1) を書こう。返すオブジェクトには next()（step を足して新しい値を返す）と reset()（start に戻す）がある。カウンターはそれぞれ自分の値を持ち、2つが状態を共有しないこと。",
  ),
  starter: c(
    "function makeCounter(start: number, step: number = 1): { next(): number; reset(): void } {",
    "  // your code here",
    "  return { next: () => 0, reset: () => {} };",
    "}",
  ),
  solution: c(
    "function makeCounter(start: number, step: number = 1): { next(): number; reset(): void } {",
    "  let value = start;",
    "  return {",
    "    next() {",
    "      value += step;",
    "      return value;",
    "    },",
    "    reset() {",
    "      value = start;",
    "    },",
    "  };",
    "}",
  ),
  nearMiss: [
    // One variable outside the function: every counter shares it.
    c(
      "let value = 0;",
      "function makeCounter(start: number, step: number = 1): { next(): number; reset(): void } {",
      "  value = start;",
      "  return {",
      "    next() { value += step; return value; },",
      "    reset() { value = start; },",
      "  };",
      "}",
    ),
    // reset goes to 0 instead of start.
    c(
      "function makeCounter(start: number, step: number = 1): { next(): number; reset(): void } {",
      "  let value = start;",
      "  return {",
      "    next() { value += step; return value; },",
      "    reset() { value = 0; },",
      "  };",
      "}",
    ),
  ],
  tests: [
    { run: "{ const c = makeCounter(10); console.log(c.next(), c.next()); }", expect: "11 12" },
    { run: "{ const c = makeCounter(0, 5); c.next(); c.next(); c.reset(); console.log(c.next()); }", expect: "5" },
    { run: "{ const a = makeCounter(0); const b = makeCounter(100); a.next(); a.next(); console.log(a.next(), b.next()); }", expect: "3 101", hidden: true },
    { run: "{ const c = makeCounter(7, 2); c.next(); c.reset(); console.log(c.next()); }", expect: "9", hidden: true },
    { run: "{ const c = makeCounter(3, -1); console.log(c.next(), c.next(), c.next()); }", expect: "2 1 0", hidden: true },
  ],
  hint: L(
    "Declare the value inside makeCounter, so each call packs a fresh backpack that next and reset share.",
    "Declara el valor dentro de makeCounter, así cada llamada arma una mochila nueva que next y reset comparten.",
    "値は makeCounter の中で宣言しよう。呼ぶたびに新しいリュックができ、next と reset が共有する。",
  ),
  note: "closure-recap",
  explain: L(
    "let value = start inside makeCounter: each call makes a new closure, so counters are independent, and reset can return to that start.",
    "let value = start dentro de makeCounter: cada llamada crea un closure nuevo, así los contadores son independientes y reset vuelve a ese start.",
    "makeCounter の中で let value = start。呼ぶたびに新しいクロージャができ、カウンターは独立し、reset はその start に戻れる。",
  ),
};

/** Prototype Peaks boss: copy, update and sort without touching the input. */
export const promoteTask: CodeTaskBeat = {
  slug: "promote",
  kind: "code",
  mode: "ide",
  prompt: L("Mini project: promote the party", "Mini proyecto: sube de nivel al grupo", "ミニ課題：パーティーを昇格"),
  brief: L(
    "Write promote(party): return a NEW array where every hero has level + 1, sorted by level from high to low; on a tie, by name A to Z. Don't change the party array or its hero objects: the Hydra keeps the old roster.",
    "Escribe promote(party): devuelve un array NUEVO donde cada héroe tiene level + 1, ordenado por nivel de mayor a menor; si empatan, por nombre de la A a la Z. No cambies el array party ni sus objetos héroe: la Hidra guarda la lista vieja.",
    "promote(party) を書こう。全員の level を +1 した「新しい」配列を返す。level の高い順、同じなら名前の A→Z 順。party 配列もヒーローのオブジェクトも変えないこと。ヒドラは古い名簿を持っている。",
  ),
  starter: c(
    "type Hero = { name: string; level: number };",
    "",
    "function promote(party: Hero[]): Hero[] {",
    "  // your code here",
    "  return party;",
    "}",
  ),
  solution: c(
    "type Hero = { name: string; level: number };",
    "",
    "function promote(party: Hero[]): Hero[] {",
    "  return party",
    "    .map((h) => ({ ...h, level: h.level + 1 }))",
    "    .sort((a, b) => b.level - a.level || (a.name < b.name ? -1 : 1));",
    "}",
  ),
  nearMiss: [
    // Bumps the level on the caller's objects.
    c(
      "type Hero = { name: string; level: number };",
      "",
      "function promote(party: Hero[]): Hero[] {",
      "  party.forEach((h) => h.level++);",
      "  return [...party].sort((a, b) => b.level - a.level || (a.name < b.name ? -1 : 1));",
      "}",
    ),
    // sort() reorders the caller's array in place.
    c(
      "type Hero = { name: string; level: number };",
      "",
      "function promote(party: Hero[]): Hero[] {",
      "  const sorted = party.sort((a, b) => b.level - a.level || (a.name < b.name ? -1 : 1));",
      "  return sorted.map((h) => ({ ...h, level: h.level + 1 }));",
      "}",
    ),
    // No tie-breaker: equal levels keep their old order.
    c(
      "type Hero = { name: string; level: number };",
      "",
      "function promote(party: Hero[]): Hero[] {",
      "  return party.map((h) => ({ ...h, level: h.level + 1 })).sort((a, b) => b.level - a.level);",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(promote([{ name: "Ana", level: 2 }, { name: "Bo", level: 5 }]).map((h) => `${h.name}:${h.level}`).join(" "));', expect: "Bo:6 Ana:3" },
    { run: "console.log(JSON.stringify(promote([])));", expect: "[]" },
    { run: 'console.log(promote([{ name: "Cy", level: 3 }, { name: "Al", level: 3 }, { name: "Bo", level: 1 }]).map((h) => `${h.name}:${h.level}`).join(" "));', expect: "Al:4 Cy:4 Bo:2", hidden: true },
    { run: '{ const party = [{ name: "Di", level: 1 }]; promote(party); console.log(party[0].level); }', expect: "1", hidden: true },
    { run: '{ const party = [{ name: "Ed", level: 1 }, { name: "Fy", level: 9 }]; promote(party); console.log(party.map((h) => h.name).join(" ")); }', expect: "Ed Fy", hidden: true },
  ],
  hint: L(
    "map with a spread makes new hero objects, and sorting that new array leaves party alone. Break level ties by name.",
    "map con spread crea héroes nuevos, y ordenar ese array nuevo deja party en paz. Desempata los niveles por nombre.",
    "map とスプレッドで新しいヒーローを作り、その新しい配列を並べれば party は無事。同じ level は名前で決める。",
  ),
  note: "recap-copies",
  explain: L(
    "map((h) => ({ ...h, level: h.level + 1 })) copies each hero, then sort the copy: by level descending, then by name.",
    "map((h) => ({ ...h, level: h.level + 1 })) copia cada héroe; luego ordena la copia: por nivel descendente y después por nombre.",
    "map((h) => ({ ...h, level: h.level + 1 })) で各ヒーローをコピーし、そのコピーを level の降順、次に名前で並べる。",
  ),
};

/** Type Castle boss: narrow unknown JSON into a typed value. */
export const parsePlayerTask: CodeTaskBeat = {
  slug: "parse-player",
  kind: "code",
  mode: "ide",
  prompt: L("Mini project: check the titan's scrolls", "Mini proyecto: revisa los pergaminos del titán", "ミニ課題：巨人の巻物を調べる"),
  brief: L(
    "Write parsePlayer(raw): raw is JSON text. Return a new Player { name, level } (only those two fields) when the JSON is an object whose name is a string and level is a number. Return null for invalid JSON, null, arrays, other values or wrong field types. Don't trust it with as: check every field.",
    "Escribe parsePlayer(raw): raw es texto JSON. Devuelve un Player { name, level } nuevo (solo esos dos campos) si el JSON es un objeto cuyo name es string y level es number. Devuelve null para JSON inválido, null, arrays, otros valores o campos de otro tipo. No confíes con as: revisa cada campo.",
    "parsePlayer(raw) を書こう。raw は JSON 文字列。オブジェクトで name が string、level が number なら、その2つだけを持つ新しい Player { name, level } を返す。不正な JSON・null・配列・その他の値・型ちがいは null。as で信じこまず、全部の項目を確かめること。",
  ),
  starter: c(
    "type Player = { name: string; level: number };",
    "",
    "function parsePlayer(raw: string): Player | null {",
    "  // your code here",
    "  return null;",
    "}",
  ),
  solution: c(
    "type Player = { name: string; level: number };",
    "",
    "function parsePlayer(raw: string): Player | null {",
    "  let data: unknown;",
    "  try {",
    "    data = JSON.parse(raw);",
    "  } catch {",
    "    return null;",
    "  }",
    '  if (typeof data !== "object" || data === null) return null;',
    "  const { name, level } = data as Record<string, unknown>;",
    '  if (typeof name !== "string" || typeof level !== "number") return null;',
    "  return { name, level };",
    "}",
  ),
  nearMiss: [
    // typeof null is "object": destructuring null throws.
    c(
      "type Player = { name: string; level: number };",
      "",
      "function parsePlayer(raw: string): Player | null {",
      "  let data: unknown;",
      "  try { data = JSON.parse(raw); } catch { return null; }",
      '  if (typeof data !== "object") return null;',
      "  const { name, level } = data as Record<string, unknown>;",
      '  if (typeof name !== "string" || typeof level !== "number") return null;',
      "  return { name, level };",
      "}",
    ),
    // as only silences the compiler: nothing is checked at runtime.
    c(
      "type Player = { name: string; level: number };",
      "",
      "function parsePlayer(raw: string): Player | null {",
      "  try { return JSON.parse(raw) as Player; } catch { return null; }",
      "}",
    ),
  ],
  tests: [
    { run: `console.log(JSON.stringify(parsePlayer('{"name":"Ada","level":3}')));`, expect: '{"name":"Ada","level":3}' },
    { run: 'console.log(parsePlayer("{oops"));', expect: "null" },
    { run: 'console.log(parsePlayer("null"));', expect: "null", hidden: true },
    { run: `console.log(parsePlayer('{"name":"Bo","level":"7"}'));`, expect: "null", hidden: true },
    { run: `console.log(JSON.stringify(parsePlayer('{"level":2,"name":"Cy","hp":9}')));`, expect: '{"name":"Cy","level":2}', hidden: true },
    { run: 'console.log(parsePlayer("[1,2]"));', expect: "null", hidden: true },
  ],
  hint: L(
    "Keep the parsed value unknown and narrow it step by step. Remember which value has typeof \"object\" but no fields.",
    "Deja el valor parseado como unknown y estréchalo paso a paso. ¿Qué valor tiene typeof \"object\" pero no tiene campos?",
    "パース結果は unknown のまま少しずつ絞ろう。typeof が \"object\" なのに項目がない値を思い出して。",
  ),
  note: "recap-strict-checks",
  explain: L(
    "JSON.parse in try/catch, then narrow: an object that is not null, a string name, a number level. Build a new object with just those two.",
    "JSON.parse dentro de try/catch y luego estrecha: objeto que no sea null, name string, level number. Arma un objeto nuevo solo con esos dos.",
    "JSON.parse は try/catch で。次に絞り込む：null でないオブジェクト、string の name、number の level。その2つだけで新しく作る。",
  ),
};

/** Event Loop Tower boss: run every load, keep the order, survive failures. */
export const loadAllTask: CodeTaskBeat = {
  slug: "load-all",
  kind: "code",
  mode: "ide",
  prompt: L("Mini project: load every map", "Mini proyecto: carga todos los mapas", "ミニ課題：全部のマップを読みこむ"),
  brief: L(
    "Write async loadAll(ids, load): load(id) returns a Promise<string> that may reject. Start every load and wait for all of them. Resolve to { ok, failed }: ok holds the loaded strings and failed the ids that rejected, both in the order of ids (not the order they finish). Never reject.",
    "Escribe async loadAll(ids, load): load(id) devuelve una Promise<string> que puede rechazar. Inicia todas las cargas y espéralas todas. Resuelve a { ok, failed }: ok tiene los strings cargados y failed los ids que rechazaron, ambos en el orden de ids (no en el que terminan). Nunca rechaces.",
    "async loadAll(ids, load) を書こう。load(id) は Promise<string> を返し、reject することもある。全部の読みこみを始めて、全部を待つ。{ ok, failed } で resolve：ok は読めた文字列、failed は reject した id。どちらも ids の順（終わった順ではない）。loadAll 自体は reject しない。",
  ),
  starter: c(
    "async function loadAll(",
    "  ids: number[],",
    "  load: (id: number) => Promise<string>,",
    "): Promise<{ ok: string[]; failed: number[] }> {",
    "  // your code here",
    "  return { ok: [], failed: [] };",
    "}",
  ),
  solution: c(
    "async function loadAll(",
    "  ids: number[],",
    "  load: (id: number) => Promise<string>,",
    "): Promise<{ ok: string[]; failed: number[] }> {",
    "  const results = await Promise.allSettled(ids.map((id) => load(id)));",
    "  const ok: string[] = [];",
    "  const failed: number[] = [];",
    "  results.forEach((r, i) => {",
    '    if (r.status === "fulfilled") ok.push(r.value);',
    "    else failed.push(ids[i]);",
    "  });",
    "  return { ok, failed };",
    "}",
  ),
  nearMiss: [
    // Promise.all rejects as soon as one load fails.
    c(
      "async function loadAll(",
      "  ids: number[],",
      "  load: (id: number) => Promise<string>,",
      "): Promise<{ ok: string[]; failed: number[] }> {",
      "  const ok = await Promise.all(ids.map((id) => load(id)));",
      "  return { ok, failed: [] };",
      "}",
    ),
    // forEach doesn't wait for async callbacks: returns before anything loads.
    c(
      "async function loadAll(",
      "  ids: number[],",
      "  load: (id: number) => Promise<string>,",
      "): Promise<{ ok: string[]; failed: number[] }> {",
      "  const ok: string[] = [];",
      "  const failed: number[] = [];",
      "  ids.forEach(async (id) => {",
      "    try { ok.push(await load(id)); } catch { failed.push(id); }",
      "  });",
      "  return { ok, failed };",
      "}",
    ),
    // Pushes in the order the loads finish.
    c(
      "async function loadAll(",
      "  ids: number[],",
      "  load: (id: number) => Promise<string>,",
      "): Promise<{ ok: string[]; failed: number[] }> {",
      "  const ok: string[] = [];",
      "  const failed: number[] = [];",
      "  await Promise.all(ids.map(async (id) => {",
      "    try { ok.push(await load(id)); } catch { failed.push(id); }",
      "  }));",
      "  return { ok, failed };",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(JSON.stringify(await loadAll([1, 2], async (id) => "map" + id)));', expect: '{"ok":["map1","map2"],"failed":[]}' },
    { run: 'console.log(JSON.stringify(await loadAll([1, 2, 3], async (id) => { if (id === 2) throw new Error("lost"); return "map" + id; })));', expect: '{"ok":["map1","map3"],"failed":[2]}' },
    { run: 'console.log(JSON.stringify(await loadAll([], async (id) => "map" + id)));', expect: '{"ok":[],"failed":[]}', hidden: true },
    { run: 'console.log(JSON.stringify(await loadAll([1, 2], async (id) => { if (id === 1) { await null; await null; await null; } return "map" + id; })));', expect: '{"ok":["map1","map2"],"failed":[]}', hidden: true },
    { run: 'console.log(JSON.stringify(await loadAll([4, 5], async (id) => { throw new Error("lost " + id); })));', expect: '{"ok":[],"failed":[4,5]}', hidden: true },
  ],
  hint: L(
    "One Promise combinator waits for every promise and never rejects. Its results come back in input order.",
    "Un combinador de Promise espera todas las promesas y nunca rechaza. Sus resultados vuelven en el orden de entrada.",
    "全部の Promise を待ち、決して reject しない組み合わせ関数がある。結果は入力の順で返る。",
  ),
  note: "recap-async",
  explain: L(
    "Promise.allSettled waits for all loads and gives results in input order; fulfilled ones go to ok, rejected ids to failed.",
    "Promise.allSettled espera todas las cargas y da los resultados en el orden de entrada: los cumplidos van a ok y los ids rechazados a failed.",
    "Promise.allSettled は全部を待ち、入力順で結果を返す。fulfilled は ok へ、rejected の id は failed へ。",
  ),
};

// ─── JUNIOR (ide) ─────────────────────────────────────────────────────────────

export const capitalizeWordsTask: ExamQuestion = {
  slug: "capitalize-words",
  kind: "code",
  mode: "ide",
  topic: "values",
  difficulty: 1,
  prompt: L("Coding: capitalize every word", "Código: mayúscula en cada palabra", "コーディング：単語の頭を大文字に"),
  brief: L(
    "Write capitalizeWords(text): upper-case the first letter of every word and lower-case the rest. Words are separated by single spaces. An empty string stays empty.",
    "Escribe capitalizeWords(text): pasa a mayúscula la primera letra de cada palabra y a minúscula el resto. Las palabras se separan con un espacio. Un string vacío queda vacío.",
    "capitalizeWords(text) を書こう。各単語の最初の文字を大文字、残りを小文字にする。単語は空白1つで区切られる。空文字列は空のまま。",
  ),
  starter: c(
    "function capitalizeWords(text: string): string {",
    "  // your code here",
    "  return text;",
    "}",
  ),
  solution: c(
    "function capitalizeWords(text: string): string {",
    "  return text",
    '    .split(" ")',
    "    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())",
    '    .join(" ");',
    "}",
  ),
  nearMiss: [
    // Leaves the rest of each word as it was.
    c(
      "function capitalizeWords(text: string): string {",
      '  return text.split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");',
      "}",
    ),
    // w[0] is undefined for an empty word: crashes on "".
    c(
      "function capitalizeWords(text: string): string {",
      '  return text.split(" ").map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join(" ");',
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(JSON.stringify(capitalizeWords("hello world")));', expect: '"Hello World"' },
    { run: 'console.log(JSON.stringify(capitalizeWords("bITWISE quest")));', expect: '"Bitwise Quest"' },
    { run: 'console.log(JSON.stringify(capitalizeWords("")));', expect: '""', hidden: true },
    { run: 'console.log(JSON.stringify(capitalizeWords("a")));', expect: '"A"', hidden: true },
    { run: 'console.log(JSON.stringify(capitalizeWords("TS IS FUN")));', expect: '"Ts Is Fun"', hidden: true },
  ],
  explain: L(
    "Split on spaces, then charAt(0).toUpperCase() plus slice(1).toLowerCase() for each word. charAt returns \"\" on an empty word instead of crashing.",
    "Divide por espacios y en cada palabra usa charAt(0).toUpperCase() más slice(1).toLowerCase(). charAt da \"\" en una palabra vacía en vez de fallar.",
    "空白で分け、各単語を charAt(0).toUpperCase() + slice(1).toLowerCase() に。charAt は空の単語でも落ちずに \"\" を返す。",
  ),
};

export const sumEvenTask: ExamQuestion = {
  slug: "sum-even",
  kind: "code",
  mode: "ide",
  topic: "arrays",
  difficulty: 1,
  prompt: L("Coding: add up the even numbers", "Código: suma los números pares", "コーディング：偶数を合計する"),
  brief: L(
    "Write sumEven(nums): return the sum of the even numbers in the array. Numbers can be negative. An empty array (or one with no even numbers) sums to 0.",
    "Escribe sumEven(nums): devuelve la suma de los números pares del array. Los números pueden ser negativos. Un array vacío (o sin pares) suma 0.",
    "sumEven(nums) を書こう。配列の偶数の合計を返す。負の数もある。空の配列（や偶数がない配列）の合計は 0。",
  ),
  starter: c(
    "function sumEven(nums: number[]): number {",
    "  // your code here",
    "  return -1;",
    "}",
  ),
  solution: c(
    "function sumEven(nums: number[]): number {",
    "  return nums.filter((n) => n % 2 === 0).reduce((sum, n) => sum + n, 0);",
    "}",
  ),
  nearMiss: [
    // reduce without a start value: crashes on [] and starts from an odd first item.
    c(
      "function sumEven(nums: number[]): number {",
      "  return nums.reduce((sum, n) => (n % 2 === 0 ? sum + n : sum));",
      "}",
    ),
    // -3 % 2 is -1, not 1: negative odd numbers slip through.
    c(
      "function sumEven(nums: number[]): number {",
      "  return nums.filter((n) => n % 2 !== 1).reduce((sum, n) => sum + n, 0);",
      "}",
    ),
  ],
  tests: [
    { run: "console.log(sumEven([1, 2, 3, 4]));", expect: "6" },
    { run: "console.log(sumEven([]));", expect: "0" },
    { run: "console.log(sumEven([-4, 3, -2]));", expect: "-6", hidden: true },
    { run: "console.log(sumEven([3, 4]));", expect: "4", hidden: true },
    { run: "console.log(sumEven([-3, 2]));", expect: "2", hidden: true },
  ],
  explain: L(
    "Keep n % 2 === 0 and reduce with a start value of 0. Without it, reduce crashes on [] and uses the first item even when it is odd.",
    "Quédate con n % 2 === 0 y reduce con valor inicial 0. Sin él, reduce falla con [] y usa el primer elemento aunque sea impar.",
    "n % 2 === 0 で絞り、初期値 0 で reduce。初期値なしだと [] で落ち、最初の要素が奇数でも足してしまう。",
  ),
};

export const makeTallyTask: ExamQuestion = {
  slug: "make-tally",
  kind: "code",
  mode: "ide",
  topic: "closures",
  difficulty: 1,
  prompt: L("Coding: a word tally", "Código: un contador de palabras", "コーディング：単語カウンター"),
  brief: L(
    "Write makeTally(): it returns a function tally(word) that returns how many times this tally has seen word, counting this call. Ignore case (\"Gem\" and \"gem\" are the same word). Each tally made by makeTally counts on its own.",
    "Escribe makeTally(): devuelve una función tally(word) que retorna cuántas veces este tally vio word, contando esta llamada. Ignora mayúsculas (\"Gem\" y \"gem\" son la misma palabra). Cada tally creado por makeTally cuenta por su cuenta.",
    "makeTally() を書こう。返す関数 tally(word) は、その tally が word を見た回数（今回を含む）を返す。大文字・小文字は区別しない（\"Gem\" と \"gem\" は同じ）。makeTally で作った tally はそれぞれ別に数える。",
  ),
  starter: c(
    "function makeTally(): (word: string) => number {",
    "  // your code here",
    "  return (word) => 0;",
    "}",
  ),
  solution: c(
    "function makeTally(): (word: string) => number {",
    "  const counts = new Map<string, number>();",
    "  return (word) => {",
    "    const key = word.toLowerCase();",
    "    const n = (counts.get(key) ?? 0) + 1;",
    "    counts.set(key, n);",
    "    return n;",
    "  };",
    "}",
  ),
  nearMiss: [
    // The map lives outside: every tally shares the same counts.
    c(
      "const counts = new Map<string, number>();",
      "function makeTally(): (word: string) => number {",
      "  return (word) => {",
      "    const key = word.toLowerCase();",
      "    const n = (counts.get(key) ?? 0) + 1;",
      "    counts.set(key, n);",
      "    return n;",
      "  };",
      "}",
    ),
    // Case-sensitive.
    c(
      "function makeTally(): (word: string) => number {",
      "  const counts = new Map<string, number>();",
      "  return (word) => {",
      "    const n = (counts.get(word) ?? 0) + 1;",
      "    counts.set(word, n);",
      "    return n;",
      "  };",
      "}",
    ),
  ],
  tests: [
    { run: '{ const t = makeTally(); console.log(t("gem"), t("gem"), t("key")); }', expect: "1 2 1" },
    { run: '{ const t = makeTally(); console.log(t("Gem"), t("gem")); }', expect: "1 2" },
    { run: '{ const a = makeTally(); const b = makeTally(); a("orb"); a("orb"); console.log(b("orb")); }', expect: "1", hidden: true },
    { run: '{ const t = makeTally(); t("a"); t("b"); console.log(t("A"), t("b")); }', expect: "2 2", hidden: true },
  ],
  explain: L(
    "Create the Map inside makeTally so each tally gets its own, and lower-case the word before counting.",
    "Crea el Map dentro de makeTally para que cada tally tenga el suyo, y pasa la palabra a minúsculas antes de contar.",
    "Map は makeTally の中で作れば tally ごとに別になる。数える前に単語を小文字にしよう。",
  ),
};

export const fizzBuzzTask: ExamQuestion = {
  slug: "fizz-buzz",
  kind: "code",
  mode: "ide",
  topic: "values",
  difficulty: 1,
  prompt: L("Coding: FizzBuzz", "Código: FizzBuzz", "コーディング：FizzBuzz"),
  brief: L(
    "Write fizzBuzz(n): return an array of strings for the numbers 1 to n. Multiples of both 3 and 5 become \"FizzBuzz\", multiples of 3 \"Fizz\", multiples of 5 \"Buzz\", and the rest the number as text (\"1\"). For n = 0, return [].",
    "Escribe fizzBuzz(n): devuelve un array de strings para los números del 1 al n. Los múltiplos de 3 y de 5 a la vez son \"FizzBuzz\", los de 3 \"Fizz\", los de 5 \"Buzz\" y el resto el número como texto (\"1\"). Para n = 0, devuelve [].",
    "fizzBuzz(n) を書こう。1 から n までの文字列の配列を返す。3 と 5 両方の倍数は \"FizzBuzz\"、3 の倍数は \"Fizz\"、5 の倍数は \"Buzz\"、それ以外は数字の文字列（\"1\"）。n = 0 なら []。",
  ),
  starter: c(
    "function fizzBuzz(n: number): string[] {",
    "  // your code here",
    "  return [];",
    "}",
  ),
  solution: c(
    "function fizzBuzz(n: number): string[] {",
    "  const out: string[] = [];",
    "  for (let i = 1; i <= n; i++) {",
    '    if (i % 15 === 0) out.push("FizzBuzz");',
    '    else if (i % 3 === 0) out.push("Fizz");',
    '    else if (i % 5 === 0) out.push("Buzz");',
    "    else out.push(String(i));",
    "  }",
    "  return out;",
    "}",
  ),
  nearMiss: [
    // Checks 3 first: 15 never reaches the FizzBuzz branch.
    c(
      "function fizzBuzz(n: number): string[] {",
      "  const out: string[] = [];",
      "  for (let i = 1; i <= n; i++) {",
      '    if (i % 3 === 0) out.push("Fizz");',
      '    else if (i % 5 === 0) out.push("Buzz");',
      '    else if (i % 15 === 0) out.push("FizzBuzz");',
      "    else out.push(String(i));",
      "  }",
      "  return out;",
      "}",
    ),
    // Off by one: stops before n.
    c(
      "function fizzBuzz(n: number): string[] {",
      "  const out: string[] = [];",
      "  for (let i = 1; i < n; i++) {",
      '    if (i % 15 === 0) out.push("FizzBuzz");',
      '    else if (i % 3 === 0) out.push("Fizz");',
      '    else if (i % 5 === 0) out.push("Buzz");',
      "    else out.push(String(i));",
      "  }",
      "  return out;",
      "}",
    ),
  ],
  tests: [
    { run: "console.log(JSON.stringify(fizzBuzz(5)));", expect: '["1","2","Fizz","4","Buzz"]' },
    { run: "console.log(JSON.stringify(fizzBuzz(0)));", expect: "[]" },
    { run: "console.log(JSON.stringify(fizzBuzz(15)[14]));", expect: '"FizzBuzz"', hidden: true },
    { run: "console.log(fizzBuzz(15).length);", expect: "15", hidden: true },
    { run: "console.log(JSON.stringify(fizzBuzz(10).slice(5)));", expect: '["Fizz","7","8","Fizz","Buzz"]', hidden: true },
  ],
  explain: L(
    "Loop from 1 to n inclusive and test 15 (both) before 3 and 5, or the FizzBuzz case is never reached.",
    "Recorre de 1 a n inclusive y prueba 15 (ambos) antes que 3 y 5; si no, nunca se llega al caso FizzBuzz.",
    "1 から n まで（n を含む）回し、3 や 5 より先に 15（両方）を調べる。でないと FizzBuzz に届かない。",
  ),
};

// ─── MID (2 ide + 2 paper) ────────────────────────────────────────────────────

export const groupByTask: ExamQuestion = {
  slug: "group-by",
  kind: "code",
  mode: "ide",
  topic: "generics",
  difficulty: 2,
  prompt: L("Coding: a generic groupBy", "Código: un groupBy genérico", "コーディング：ジェネリックな groupBy"),
  brief: L(
    "Write groupBy<T>(items, keyOf): keyOf(item) returns a string key. Return an object that maps each key to the array of items with that key, keeping the items' order. Keys appear in the order they are first seen. An empty array gives {}.",
    "Escribe groupBy<T>(items, keyOf): keyOf(item) devuelve una clave string. Devuelve un objeto que asocia cada clave al array de items con esa clave, en el orden de los items. Las claves aparecen en el orden en que se ven por primera vez. Un array vacío da {}.",
    "groupBy<T>(items, keyOf) を書こう。keyOf(item) は文字列のキーを返す。キーごとにその items の配列を持つオブジェクトを返す。items の順は保つ。キーは最初に出た順。空の配列なら {}。",
  ),
  starter: c(
    "function groupBy<T>(items: T[], keyOf: (item: T) => string): Record<string, T[]> {",
    "  // your code here",
    "  return {};",
    "}",
  ),
  solution: c(
    "function groupBy<T>(items: T[], keyOf: (item: T) => string): Record<string, T[]> {",
    "  const out: Record<string, T[]> = {};",
    "  for (const item of items) {",
    "    const key = keyOf(item);",
    "    (out[key] ??= []).push(item);",
    "  }",
    "  return out;",
    "}",
  ),
  nearMiss: [
    // Replaces the group instead of adding to it.
    c(
      "function groupBy<T>(items: T[], keyOf: (item: T) => string): Record<string, T[]> {",
      "  const out: Record<string, T[]> = {};",
      "  for (const item of items) out[keyOf(item)] = [item];",
      "  return out;",
      "}",
    ),
    // Sorts the keys: they no longer follow first appearance.
    c(
      "function groupBy<T>(items: T[], keyOf: (item: T) => string): Record<string, T[]> {",
      "  const keys = [...new Set(items.map(keyOf))].sort();",
      "  const out: Record<string, T[]> = {};",
      "  for (const k of keys) out[k] = items.filter((item) => keyOf(item) === k);",
      "  return out;",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(JSON.stringify(groupBy(["ant", "bee", "cat", "cow"], (w) => w[0])));', expect: '{"a":["ant"],"b":["bee"],"c":["cat","cow"]}' },
    { run: "console.log(JSON.stringify(groupBy([] as number[], (n) => String(n))));", expect: "{}" },
    { run: 'console.log(JSON.stringify(groupBy([1, 2, 3, 4, 5], (n) => (n % 2 ? "odd" : "even"))));', expect: '{"odd":[1,3,5],"even":[2,4]}', hidden: true },
    { run: 'console.log(JSON.stringify(groupBy([{ t: "x", v: 1 }, { t: "y", v: 2 }, { t: "x", v: 3 }], (o) => o.t)));', expect: '{"x":[{"t":"x","v":1},{"t":"x","v":3}],"y":[{"t":"y","v":2}]}', hidden: true },
  ],
  explain: L(
    "Create the group the first time a key appears (out[key] ??= []) and push every item into it. Object string keys keep insertion order.",
    "Crea el grupo la primera vez que aparece una clave (out[key] ??= []) y agrega cada item. Las claves string de un objeto conservan el orden de inserción.",
    "キーが初めて出たときに組を作り（out[key] ??= []）、各 item を push。文字列キーは挿入順を保つ。",
  ),
};

export const retryTask: ExamQuestion = {
  slug: "retry",
  kind: "code",
  mode: "ide",
  topic: "async",
  difficulty: 2,
  prompt: L("Coding: retry an async task", "Código: reintenta una tarea async", "コーディング：非同期タスクを再試行"),
  brief: L(
    "Write async retry(task, attempts): call task() (it returns a Promise) up to attempts times (attempts ≥ 1). Resolve with the first value that succeeds. If every attempt rejects, reject with the error of the LAST attempt. Don't call task again after a success.",
    "Escribe async retry(task, attempts): llama a task() (devuelve una Promise) hasta attempts veces (attempts ≥ 1). Resuelve con el primer valor exitoso. Si todos los intentos rechazan, rechaza con el error del ÚLTIMO intento. No vuelvas a llamar a task después de un éxito.",
    "async retry(task, attempts) を書こう。task()（Promise を返す）を最大 attempts 回呼ぶ（attempts ≥ 1）。最初に成功した値で resolve。全部 reject なら「最後」の試行のエラーで reject。成功したらもう呼ばないこと。",
  ),
  starter: c(
    "async function retry<T>(task: () => Promise<T>, attempts: number): Promise<T> {",
    "  // your code here",
    '  throw new Error("not implemented");',
    "}",
  ),
  solution: c(
    "async function retry<T>(task: () => Promise<T>, attempts: number): Promise<T> {",
    "  let lastError: unknown;",
    "  for (let i = 0; i < attempts; i++) {",
    "    try {",
    "      return await task();",
    "    } catch (e) {",
    "      lastError = e;",
    "    }",
    "  }",
    "  throw lastError;",
    "}",
  ),
  nearMiss: [
    // return without await: the rejection escapes the try, so nothing is retried.
    c(
      "async function retry<T>(task: () => Promise<T>, attempts: number): Promise<T> {",
      "  let lastError: unknown;",
      "  for (let i = 0; i < attempts; i++) {",
      "    try {",
      "      return task();",
      "    } catch (e) {",
      "      lastError = e;",
      "    }",
      "  }",
      "  throw lastError;",
      "}",
    ),
    // Off by one: one attempt too many.
    c(
      "async function retry<T>(task: () => Promise<T>, attempts: number): Promise<T> {",
      "  let lastError: unknown;",
      "  for (let i = 0; i <= attempts; i++) {",
      "    try {",
      "      return await task();",
      "    } catch (e) {",
      "      lastError = e;",
      "    }",
      "  }",
      "  throw lastError;",
      "}",
    ),
  ],
  tests: [
    { run: '{ let calls = 0; const r = await retry(async () => { calls++; if (calls < 3) throw new Error("fail " + calls); return "ok"; }, 3); console.log(r, calls); }', expect: "ok 3" },
    { run: '{ let calls = 0; try { await retry(async () => { calls++; throw new Error("boom " + calls); }, 2); } catch (e) { console.log((e as Error).message, calls); } }', expect: "boom 2 2" },
    { run: '{ let calls = 0; const r = await retry(async () => { calls++; return "ok"; }, 5); console.log(r, calls); }', expect: "ok 1", hidden: true },
    { run: '{ let calls = 0; try { await retry(async () => { calls++; throw new Error("boom " + calls); }, 1); } catch (e) { console.log((e as Error).message, calls); } }', expect: "boom 1 1", hidden: true },
    { run: '{ let calls = 0; const r = await retry(async () => { calls++; if (calls < 4) throw new Error("x"); return calls; }, 4); console.log(r); }', expect: "4", hidden: true },
  ],
  explain: L(
    "Loop attempts times with return await task() inside try: await makes a rejection land in catch. Keep the last error and throw it at the end.",
    "Repite attempts veces con return await task() dentro del try: await hace que el rechazo caiga en el catch. Guarda el último error y lánzalo al final.",
    "try の中で return await task() を attempts 回くり返す。await があるから reject が catch に入る。最後のエラーを覚えて最後に投げる。",
  ),
};

export const chunkTask: ExamQuestion = {
  slug: "chunk",
  kind: "code",
  mode: "paper",
  topic: "arrays",
  difficulty: 2,
  prompt: L("Written test: split an array into chunks", "Prueba escrita: divide un array en trozos", "筆記：配列を小分けにする"),
  brief: L(
    "Write chunk<T>(items, size): split items into arrays of length size, in order; the last chunk holds whatever is left and can be shorter. size is at least 1. An empty array gives []. Don't modify items.",
    "Escribe chunk<T>(items, size): divide items en arrays de largo size, en orden; el último trozo guarda lo que sobra y puede ser más corto. size es al menos 1. Un array vacío da []. No modifiques items.",
    "chunk<T>(items, size) を書こう。items を順に長さ size の配列に分ける。最後の組は残りで、短くてもよい。size は 1 以上。空の配列なら []。items は変えないこと。",
  ),
  starter: c(
    "function chunk<T>(items: T[], size: number): T[][] {",
    "  // your code here",
    "  return [items];",
    "}",
  ),
  solution: c(
    "function chunk<T>(items: T[], size: number): T[][] {",
    "  const out: T[][] = [];",
    "  for (let i = 0; i < items.length; i += size) {",
    "    out.push(items.slice(i, i + size));",
    "  }",
    "  return out;",
    "}",
  ),
  nearMiss: [
    // Integer count of full chunks: the short last chunk is lost.
    c(
      "function chunk<T>(items: T[], size: number): T[][] {",
      "  const out: T[][] = [];",
      "  for (let i = 0; i < Math.floor(items.length / size); i++) {",
      "    out.push(items.slice(i * size, (i + 1) * size));",
      "  }",
      "  return out;",
      "}",
    ),
    // splice empties the caller's array.
    c(
      "function chunk<T>(items: T[], size: number): T[][] {",
      "  const out: T[][] = [];",
      "  while (items.length > 0) out.push(items.splice(0, size));",
      "  return out;",
      "}",
    ),
  ],
  tests: [
    { run: "console.log(JSON.stringify(chunk([1, 2, 3, 4, 5], 2)));", expect: "[[1,2],[3,4],[5]]" },
    { run: "console.log(JSON.stringify(chunk([], 3)));", expect: "[]" },
    { run: 'console.log(JSON.stringify(chunk(["a", "b", "c"], 3)));', expect: '[["a","b","c"]]', hidden: true },
    { run: "console.log(JSON.stringify(chunk([1, 2, 3], 5)));", expect: "[[1,2,3]]", hidden: true },
    { run: "console.log(JSON.stringify(chunk([1, 2, 3, 4], 1)));", expect: "[[1],[2],[3],[4]]", hidden: true },
    { run: "{ const xs = [1, 2, 3]; chunk(xs, 2); console.log(JSON.stringify(xs)); }", expect: "[1,2,3]", hidden: true },
  ],
  explain: L(
    "Step i by size and push items.slice(i, i + size): slice copies, never mutates, and stops at the end, so the last chunk can be short.",
    "Avanza i de size en size y agrega items.slice(i, i + size): slice copia, nunca muta, y se detiene al final, así el último trozo puede ser corto.",
    "i を size ずつ進め items.slice(i, i + size) を push。slice はコピーで元を変えず、末尾で止まるので最後の組は短くてよい。",
  ),
};

export const bankAccountTask: ExamQuestion = {
  slug: "bank-account",
  kind: "code",
  mode: "paper",
  topic: "classes",
  difficulty: 2,
  prompt: L("Written test: a bank account class", "Prueba escrita: una clase de cuenta bancaria", "筆記：銀行口座クラス"),
  brief: L(
    "Write class BankAccount: constructor(initial = 0); deposit(amount) and withdraw(amount) return the new balance; getBalance() returns it. An amount ≤ 0 throws Error(\"invalid amount\"). Withdrawing more than the balance throws Error(\"insufficient funds\"). A failed call leaves the balance unchanged.",
    "Escribe class BankAccount: constructor(initial = 0); deposit(amount) y withdraw(amount) devuelven el saldo nuevo; getBalance() lo devuelve. Un monto ≤ 0 lanza Error(\"invalid amount\"). Retirar más que el saldo lanza Error(\"insufficient funds\"). Una llamada fallida deja el saldo igual.",
    "class BankAccount を書こう。constructor(initial = 0)。deposit(amount) と withdraw(amount) は新しい残高を返し、getBalance() は残高を返す。amount ≤ 0 は Error(\"invalid amount\")。残高より多い引き出しは Error(\"insufficient funds\")。失敗しても残高は変えない。",
  ),
  starter: c(
    "class BankAccount {",
    "  constructor(initial: number = 0) {",
    "    // your code here",
    "  }",
    "",
    "  deposit(amount: number): number {",
    "    return 0;",
    "  }",
    "",
    "  withdraw(amount: number): number {",
    "    return 0;",
    "  }",
    "",
    "  getBalance(): number {",
    "    return 0;",
    "  }",
    "}",
  ),
  solution: c(
    "class BankAccount {",
    "  private balance: number;",
    "",
    "  constructor(initial: number = 0) {",
    "    this.balance = initial;",
    "  }",
    "",
    "  deposit(amount: number): number {",
    '    if (amount <= 0) throw new Error("invalid amount");',
    "    this.balance += amount;",
    "    return this.balance;",
    "  }",
    "",
    "  withdraw(amount: number): number {",
    '    if (amount <= 0) throw new Error("invalid amount");',
    '    if (amount > this.balance) throw new Error("insufficient funds");',
    "    this.balance -= amount;",
    "    return this.balance;",
    "  }",
    "",
    "  getBalance(): number {",
    "    return this.balance;",
    "  }",
    "}",
  ),
  nearMiss: [
    // >= refuses to withdraw the exact balance.
    c(
      "class BankAccount {",
      "  private balance: number;",
      "  constructor(initial: number = 0) { this.balance = initial; }",
      "  deposit(amount: number): number {",
      '    if (amount <= 0) throw new Error("invalid amount");',
      "    this.balance += amount;",
      "    return this.balance;",
      "  }",
      "  withdraw(amount: number): number {",
      '    if (amount <= 0) throw new Error("invalid amount");',
      '    if (amount >= this.balance) throw new Error("insufficient funds");',
      "    this.balance -= amount;",
      "    return this.balance;",
      "  }",
      "  getBalance(): number { return this.balance; }",
      "}",
    ),
    // Subtracts first, then complains: the failed withdrawal already changed the balance.
    c(
      "class BankAccount {",
      "  private balance: number;",
      "  constructor(initial: number = 0) { this.balance = initial; }",
      "  deposit(amount: number): number {",
      '    if (amount <= 0) throw new Error("invalid amount");',
      "    this.balance += amount;",
      "    return this.balance;",
      "  }",
      "  withdraw(amount: number): number {",
      '    if (amount <= 0) throw new Error("invalid amount");',
      "    this.balance -= amount;",
      '    if (this.balance < 0) throw new Error("insufficient funds");',
      "    return this.balance;",
      "  }",
      "  getBalance(): number { return this.balance; }",
      "}",
    ),
  ],
  tests: [
    { run: "{ const a = new BankAccount(10); a.deposit(5); console.log(a.withdraw(3), a.getBalance()); }", expect: "12 12" },
    { run: "{ const a = new BankAccount(); try { a.withdraw(1); } catch (e) { console.log((e as Error).message); } }", expect: "insufficient funds" },
    { run: "{ const a = new BankAccount(5); console.log(a.withdraw(5)); }", expect: "0", hidden: true },
    { run: "{ const a = new BankAccount(4); try { a.withdraw(9); } catch { /* expected */ } console.log(a.getBalance()); }", expect: "4", hidden: true },
    { run: "{ const a = new BankAccount(1); try { a.deposit(-2); } catch (e) { console.log((e as Error).message, a.getBalance()); } }", expect: "invalid amount 1", hidden: true },
  ],
  explain: L(
    "Validate before changing state: amount ≤ 0 is invalid, and only amount > balance is insufficient, so withdrawing the exact balance is fine.",
    "Valida antes de cambiar el estado: monto ≤ 0 es inválido y solo monto > saldo es insuficiente, así que retirar el saldo exacto está bien.",
    "状態を変える前に確かめる。amount ≤ 0 は不正、残高不足は amount > balance のときだけ。ちょうど全額の引き出しは OK。",
  ),
};

// ─── SENIOR (1 ide + 3 paper) ─────────────────────────────────────────────────

export const rateLimiterTask: ExamQuestion = {
  slug: "rate-limiter",
  kind: "code",
  mode: "ide",
  topic: "performance",
  difficulty: 3,
  prompt: L("Coding: a sliding-window rate limiter", "Código: un limitador de ventana deslizante", "コーディング：スライド窓のレート制限"),
  brief: L(
    "Write makeRateLimiter(limit, windowMs): it returns allow(now), where now is a time in ms (never decreasing). allow returns true and records the call when fewer than limit ACCEPTED calls happened in the last windowMs (a call exactly windowMs ago no longer counts); otherwise it returns false. Rejected calls don't count. Each limiter is independent.",
    "Escribe makeRateLimiter(limit, windowMs): devuelve allow(now), donde now es un tiempo en ms (nunca decrece). allow devuelve true y registra la llamada si hubo menos de limit llamadas ACEPTADAS en los últimos windowMs (una de hace exactamente windowMs ya no cuenta); si no, devuelve false. Las rechazadas no cuentan. Cada limitador es independiente.",
    "makeRateLimiter(limit, windowMs) を書こう。返す allow(now) の now は ms の時刻（減らない）。直近 windowMs 内に「受け入れた」呼び出しが limit 未満なら記録して true、そうでなければ false。ちょうど windowMs 前の呼び出しは数えない。拒否は数えない。リミッターはそれぞれ独立。",
  ),
  starter: c(
    "function makeRateLimiter(limit: number, windowMs: number): (now: number) => boolean {",
    "  // your code here",
    "  return (now) => true;",
    "}",
  ),
  solution: c(
    "function makeRateLimiter(limit: number, windowMs: number): (now: number) => boolean {",
    "  const accepted: number[] = [];",
    "  return (now) => {",
    "    while (accepted.length > 0 && accepted[0] <= now - windowMs) accepted.shift();",
    "    if (accepted.length >= limit) return false;",
    "    accepted.push(now);",
    "    return true;",
    "  };",
    "}",
  ),
  nearMiss: [
    // Fixed windows (0-999, 1000-1999...) instead of a sliding one.
    c(
      "function makeRateLimiter(limit: number, windowMs: number): (now: number) => boolean {",
      "  let bucket = -1;",
      "  let count = 0;",
      "  return (now) => {",
      "    const b = Math.floor(now / windowMs);",
      "    if (b !== bucket) { bucket = b; count = 0; }",
      "    if (count >= limit) return false;",
      "    count++;",
      "    return true;",
      "  };",
      "}",
    ),
    // Records rejected calls too.
    c(
      "function makeRateLimiter(limit: number, windowMs: number): (now: number) => boolean {",
      "  const calls: number[] = [];",
      "  return (now) => {",
      "    while (calls.length > 0 && calls[0] <= now - windowMs) calls.shift();",
      "    const ok = calls.length < limit;",
      "    calls.push(now);",
      "    return ok;",
      "  };",
      "}",
    ),
    // Off by one at the edge: a call exactly windowMs ago still counts.
    c(
      "function makeRateLimiter(limit: number, windowMs: number): (now: number) => boolean {",
      "  const accepted: number[] = [];",
      "  return (now) => {",
      "    while (accepted.length > 0 && accepted[0] < now - windowMs) accepted.shift();",
      "    if (accepted.length >= limit) return false;",
      "    accepted.push(now);",
      "    return true;",
      "  };",
      "}",
    ),
  ],
  tests: [
    { run: '{ const allow = makeRateLimiter(2, 1000); console.log([0, 100, 200].map((t) => allow(t)).join(" ")); }', expect: "true true false" },
    { run: '{ const allow = makeRateLimiter(2, 1000); console.log([0, 100, 1000, 1050].map((t) => allow(t)).join(" ")); }', expect: "true true true false" },
    { run: '{ const allow = makeRateLimiter(1, 100); console.log([0, 50, 100, 150].map((t) => allow(t)).join(" ")); }', expect: "true false true false", hidden: true },
    { run: '{ const allow = makeRateLimiter(2, 1000); console.log([900, 950, 1000, 1899, 1900].map((t) => allow(t)).join(" ")); }', expect: "true true false false true", hidden: true },
    { run: "{ const a = makeRateLimiter(1, 10); const b = makeRateLimiter(1, 10); console.log(a(0), b(0), a(5)); }", expect: "true true false", hidden: true },
  ],
  explain: L(
    "Keep the times of accepted calls in the closure; drop those ≤ now - windowMs, then accept only if fewer than limit remain.",
    "Guarda en el closure los tiempos de las llamadas aceptadas; descarta las ≤ now - windowMs y acepta solo si quedan menos de limit.",
    "受け入れた時刻をクロージャに保存。now - windowMs 以下を捨て、残りが limit 未満のときだけ受け入れる。",
  ),
};

export const promiseAllTask: ExamQuestion = {
  slug: "promise-all",
  kind: "code",
  mode: "paper",
  topic: "async",
  difficulty: 3,
  prompt: L("Written test: implement Promise.all", "Prueba escrita: implementa Promise.all", "筆記：Promise.all を実装"),
  brief: L(
    "Write promiseAll<T>(promises) without using Promise.all. Resolve with the values in the same order as the input, whatever order they settle in. Reject with the first rejection's reason. An empty array resolves to [] right away.",
    "Escribe promiseAll<T>(promises) sin usar Promise.all. Resuelve con los valores en el mismo orden que la entrada, sin importar en qué orden se resuelvan. Rechaza con el motivo del primer rechazo. Un array vacío resuelve a [] de inmediato.",
    "Promise.all を使わずに promiseAll<T>(promises) を書こう。完了の順番にかかわらず、入力と同じ順で値を resolve する。最初の reject の理由で reject。空の配列はすぐ [] で resolve。",
  ),
  starter: c(
    "function promiseAll<T>(promises: Promise<T>[]): Promise<T[]> {",
    "  // your code here",
    "  return Promise.resolve([]);",
    "}",
  ),
  solution: c(
    "function promiseAll<T>(promises: Promise<T>[]): Promise<T[]> {",
    "  return new Promise((resolve, reject) => {",
    "    const results: T[] = new Array(promises.length);",
    "    let left = promises.length;",
    "    if (left === 0) return resolve([]);",
    "    promises.forEach((p, i) => {",
    "      p.then((value) => {",
    "        results[i] = value;",
    "        left--;",
    "        if (left === 0) resolve(results);",
    "      }, reject);",
    "    });",
    "  });",
    "}",
  ),
  nearMiss: [
    // results.length jumps when a later index is filled first: resolves too early.
    c(
      "function promiseAll<T>(promises: Promise<T>[]): Promise<T[]> {",
      "  return new Promise((resolve, reject) => {",
      "    const results: T[] = [];",
      "    if (promises.length === 0) return resolve([]);",
      "    promises.forEach((p, i) => {",
      "      p.then((value) => {",
      "        results[i] = value;",
      "        if (results.length === promises.length) resolve(results);",
      "      }, reject);",
      "    });",
      "  });",
      "}",
    ),
    // push keeps the settle order, not the input order.
    c(
      "function promiseAll<T>(promises: Promise<T>[]): Promise<T[]> {",
      "  return new Promise((resolve, reject) => {",
      "    const results: T[] = [];",
      "    if (promises.length === 0) return resolve([]);",
      "    promises.forEach((p) => {",
      "      p.then((value) => {",
      "        results.push(value);",
      "        if (results.length === promises.length) resolve(results);",
      "      }, reject);",
      "    });",
      "  });",
      "}",
    ),
  ],
  tests: [
    { run: "console.log(JSON.stringify(await promiseAll([Promise.resolve(1), Promise.resolve(2)])));", expect: "[1,2]" },
    { run: "console.log(JSON.stringify(await promiseAll([])));", expect: "[]" },
    { run: '{ const slow = Promise.resolve("a").then((v) => v).then((v) => v).then((v) => v); console.log(JSON.stringify(await promiseAll([slow, Promise.resolve("b")]))); }', expect: '["a","b"]', hidden: true },
    { run: '{ const bad = Promise.reject(new Error("nope")); bad.catch(() => {}); try { await promiseAll([Promise.resolve(1), bad]); } catch (e) { console.log((e as Error).message); } }', expect: "nope", hidden: true },
    { run: '{ const late = Promise.resolve(3).then((v) => v * 10); console.log(JSON.stringify(await promiseAll([late, Promise.resolve(1), Promise.resolve(2)]))); }', expect: "[30,1,2]", hidden: true },
  ],
  explain: L(
    "Store each value at its index and count how many are left; resolve when the count hits 0. results.length is wrong: filling index 2 makes it 3.",
    "Guarda cada valor en su índice y cuenta cuántos faltan; resuelve cuando la cuenta llega a 0. results.length falla: llenar el índice 2 lo vuelve 3.",
    "値は自分の添字に入れ、残り数を数えて 0 で resolve。results.length は不可：添字 2 を入れると長さは 3 になる。",
  ),
};

export const getPathTask: ExamQuestion = {
  slug: "get-path",
  kind: "code",
  mode: "paper",
  topic: "narrowing",
  difficulty: 3,
  prompt: L("Written test: read a nested path safely", "Prueba escrita: lee una ruta anidada sin romper", "筆記：入れ子のパスを安全に読む"),
  brief: L(
    "Write getPath(obj, path, fallback): path is keys joined by dots, like \"party.1.hp\" (array indexes are keys too). Walk obj step by step and return the value found. Return fallback when a step hits null, undefined or a non-object, or when the final value is undefined. Real values like 0, \"\" and false must come back as they are.",
    "Escribe getPath(obj, path, fallback): path son claves unidas por puntos, como \"party.1.hp\" (los índices de array también son claves). Recorre obj paso a paso y devuelve el valor hallado. Devuelve fallback si un paso cae en null, undefined o algo que no es objeto, o si el valor final es undefined. Valores reales como 0, \"\" y false vuelven tal cual.",
    "getPath(obj, path, fallback) を書こう。path は \"party.1.hp\" のようにキーをドットでつないだもの（配列の添字もキー）。obj を1段ずつたどり、見つけた値を返す。途中で null・undefined・オブジェクト以外に当たるか、最後が undefined なら fallback。0・\"\"・false はそのまま返すこと。",
  ),
  starter: c(
    "function getPath(obj: unknown, path: string, fallback?: unknown): unknown {",
    "  // your code here",
    "  return fallback;",
    "}",
  ),
  solution: c(
    "function getPath(obj: unknown, path: string, fallback?: unknown): unknown {",
    "  let current: unknown = obj;",
    '  for (const key of path.split(".")) {',
    '    if (current === null || typeof current !== "object") return fallback;',
    "    current = (current as Record<string, unknown>)[key];",
    "  }",
    "  return current === undefined ? fallback : current;",
    "}",
  ),
  nearMiss: [
    // Only guards undefined: reading a key of null throws.
    c(
      "function getPath(obj: unknown, path: string, fallback?: unknown): unknown {",
      "  let current: any = obj;",
      '  for (const key of path.split(".")) {',
      "    if (current === undefined) return fallback;",
      "    current = current[key];",
      "  }",
      "  return current === undefined ? fallback : current;",
      "}",
    ),
    // || replaces every falsy value, including 0 and false.
    c(
      "function getPath(obj: unknown, path: string, fallback?: unknown): unknown {",
      "  let current: unknown = obj;",
      '  for (const key of path.split(".")) {',
      '    if (current === null || typeof current !== "object") return fallback;',
      "    current = (current as Record<string, unknown>)[key];",
      "  }",
      "  return current || fallback;",
      "}",
    ),
  ],
  tests: [
    { run: 'console.log(JSON.stringify(getPath({ hero: { name: "Ada" } }, "hero.name")));', expect: '"Ada"' },
    { run: 'console.log(JSON.stringify(getPath({ hero: {} }, "hero.bag.gold", 0)));', expect: "0" },
    { run: 'console.log(JSON.stringify(getPath({ party: [{ hp: 3 }, { hp: 7 }] }, "party.1.hp")));', expect: "7", hidden: true },
    { run: 'console.log(JSON.stringify(getPath({ gold: 0 }, "gold", 99)));', expect: "0", hidden: true },
    { run: 'console.log(JSON.stringify(getPath({ boss: null }, "boss.hp", -1)));', expect: "-1", hidden: true },
    { run: 'console.log(JSON.stringify(getPath({ a: { b: false } }, "a.b", true)));', expect: "false", hidden: true },
  ],
  explain: L(
    "Before each step, narrow: typeof null is \"object\", so test null too. At the end, use fallback only for undefined, never ||.",
    "Antes de cada paso, estrecha: typeof null es \"object\", así que prueba null también. Al final usa fallback solo para undefined, nunca ||.",
    "各段の前に絞り込む。typeof null は \"object\" なので null も調べる。最後は undefined のときだけ fallback、|| は使わない。",
  ),
};

export const emitterTask: ExamQuestion = {
  slug: "emitter",
  kind: "code",
  mode: "paper",
  topic: "classes",
  difficulty: 3,
  prompt: L("Written test: an event emitter", "Prueba escrita: un emisor de eventos", "筆記：イベントエミッター"),
  brief: L(
    "Write class Emitter with on(event, fn), off(event, fn) and emit(event, ...args). emit calls the event's listeners in the order they were added, with args, and returns how many it called. off removes only that listener (unknown ones are ignored). A listener may call off during emit: every listener registered when emit started still runs.",
    "Escribe class Emitter con on(event, fn), off(event, fn) y emit(event, ...args). emit llama a los listeners del evento en el orden en que se agregaron, con args, y devuelve cuántos llamó. off quita solo ese listener (los desconocidos se ignoran). Un listener puede llamar a off durante emit: todos los registrados al empezar emit igual corren.",
    "class Emitter を書こう。on(event, fn)・off(event, fn)・emit(event, ...args)。emit はそのイベントのリスナーを追加順に args 付きで呼び、呼んだ数を返す。off はそのリスナーだけを外す（知らないものは無視）。emit 中にリスナーが off してもよい。emit 開始時に登録済みのリスナーは全部動くこと。",
  ),
  starter: c(
    "type Listener = (...args: unknown[]) => void;",
    "",
    "class Emitter {",
    "  on(event: string, fn: Listener): void {",
    "    // your code here",
    "  }",
    "",
    "  off(event: string, fn: Listener): void {",
    "    // your code here",
    "  }",
    "",
    "  emit(event: string, ...args: unknown[]): number {",
    "    return 0;",
    "  }",
    "}",
  ),
  solution: c(
    "type Listener = (...args: unknown[]) => void;",
    "",
    "class Emitter {",
    "  private listeners = new Map<string, Listener[]>();",
    "",
    "  on(event: string, fn: Listener): void {",
    "    const list = this.listeners.get(event) ?? [];",
    "    list.push(fn);",
    "    this.listeners.set(event, list);",
    "  }",
    "",
    "  off(event: string, fn: Listener): void {",
    "    const list = this.listeners.get(event);",
    "    const i = list ? list.indexOf(fn) : -1;",
    "    if (list && i !== -1) list.splice(i, 1);",
    "  }",
    "",
    "  emit(event: string, ...args: unknown[]): number {",
    "    const list = [...(this.listeners.get(event) ?? [])];",
    "    for (const fn of list) fn(...args);",
    "    return list.length;",
    "  }",
    "}",
  ),
  nearMiss: [
    // off drops every listener of the event.
    c(
      "type Listener = (...args: unknown[]) => void;",
      "",
      "class Emitter {",
      "  private listeners = new Map<string, Listener[]>();",
      "  on(event: string, fn: Listener): void {",
      "    const list = this.listeners.get(event) ?? [];",
      "    list.push(fn);",
      "    this.listeners.set(event, list);",
      "  }",
      "  off(event: string, fn: Listener): void {",
      "    this.listeners.delete(event);",
      "  }",
      "  emit(event: string, ...args: unknown[]): number {",
      "    const list = [...(this.listeners.get(event) ?? [])];",
      "    for (const fn of list) fn(...args);",
      "    return list.length;",
      "  }",
      "}",
    ),
    // Iterates the live array: a listener that removes itself makes the next one get skipped.
    c(
      "type Listener = (...args: unknown[]) => void;",
      "",
      "class Emitter {",
      "  private listeners = new Map<string, Listener[]>();",
      "  on(event: string, fn: Listener): void {",
      "    const list = this.listeners.get(event) ?? [];",
      "    list.push(fn);",
      "    this.listeners.set(event, list);",
      "  }",
      "  off(event: string, fn: Listener): void {",
      "    const list = this.listeners.get(event);",
      "    const i = list ? list.indexOf(fn) : -1;",
      "    if (list && i !== -1) list.splice(i, 1);",
      "  }",
      "  emit(event: string, ...args: unknown[]): number {",
      "    const list = this.listeners.get(event) ?? [];",
      "    let called = 0;",
      "    list.forEach((fn) => { fn(...args); called++; });",
      "    return called;",
      "  }",
      "}",
    ),
  ],
  tests: [
    { run: '{ const e = new Emitter(); const log: string[] = []; e.on("hit", (n) => { log.push("a" + String(n)); }); e.on("hit", (n) => { log.push("b" + String(n)); }); console.log(e.emit("hit", 3), log.join(" ")); }', expect: "2 a3 b3" },
    { run: '{ const e = new Emitter(); console.log(e.emit("nothing")); }', expect: "0" },
    { run: '{ const e = new Emitter(); const log: string[] = []; const a = () => { log.push("a"); }; e.on("x", a); e.on("x", () => { log.push("b"); }); e.off("x", a); console.log(e.emit("x"), log.join(" ")); }', expect: "1 b", hidden: true },
    { run: '{ const e = new Emitter(); let n = 0; e.on("a", () => { n++; }); e.emit("b"); console.log(n); }', expect: "0", hidden: true },
    { run: '{ const e = new Emitter(); const log: string[] = []; const first = () => { log.push("1"); e.off("x", first); }; e.on("x", first); e.on("x", () => { log.push("2"); }); e.emit("x"); e.emit("x"); console.log(log.join(" ")); }', expect: "1 2 2", hidden: true },
    { run: '{ const e = new Emitter(); e.off("none", () => {}); console.log("ok"); }', expect: "ok", hidden: true },
  ],
  explain: L(
    "Keep a Map of event → listener array. off splices out one function; emit loops over a COPY, so removals during emit don't skip anyone.",
    "Guarda un Map de evento → array de listeners. off quita una función con splice; emit recorre una COPIA, así quitar durante emit no salta a nadie.",
    "イベント → リスナー配列の Map を持つ。off は splice で1つ外す。emit は「コピー」を回すので、途中で外しても飛ばされない。",
  ),
};
