import type { ExamDef } from "../../lib/content/types.ts";

// Entry exams that simulate company technical screenings for Rust roles.
// Topic and format choices are grounded in docs/research/rust-hiring-assessments.md.
// Every answer that depends on the compiler or runtime carries a `check` verified on the
// Rust Playground (`npm run content:verify -- --lang=rust`).

const YN = ["Sí", "No"];

/** Drop-tracing struct reused by several senior snippets. */
const D = `struct D(&'static str);
impl Drop for D { fn drop(&mut self) { println!("{}", self.0); } }`;

export const exams: ExamDef[] = [
  // ─── JUNIOR ───────────────────────────────────────────────────────────────
  {
    slug: "junior",
    level: "junior",
    title: "Rust Developer Junior",
    description:
      "Simula la pantalla técnica inicial (test online de opción múltiple): sintaxis, mutabilidad, ownership, préstamos, match, Option/Result y colecciones básicas.",
    count: 12,
    passPct: 70,
    secondsPerQuestion: 30,
    questions: [
      // variables
      { topic: "variables", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: "let a = 1;\na = 2;", options: YN, answer: 1, explain: "Las variables son inmutables por defecto: para reasignar hay que declararla con `let mut`.", check: { compiles: false } },
      { topic: "variables", difficulty: 1, kind: "pick", prompt: "Haz que x pueda cambiar", code: 'let ___ x = 5;\nx += 1;\nprintln!("{}", x);', options: ["mut", "var", "&mut"], answer: 0, explain: "`let mut` declara un binding mutable. `var` no existe en Rust y `&mut` es un tipo de préstamo, no un modificador de variable.", check: { compiles: true, stdout: "6", wrongFail: true } },
      { topic: "variables", difficulty: 1, kind: "type", prompt: "Declara una constante", code: "___ MAX: u32 = 100;\nlet doble = MAX * 2;", answer: "const", explain: "`const` define un valor fijo en compilación; siempre lleva tipo explícito y se escribe en MAYÚSCULAS.", check: { compiles: true } },
      // types
      { topic: "types", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let x = 5;\nlet x = x + 1;\n{\n    let x = x * 2;\n    println!("{}", x);\n}\nprintln!("{}", x);', options: ["12 y 6", "12 y 12", "6 y 6", "No compila"], answer: 0, explain: "Shadowing: cada `let x` crea un binding nuevo. El del bloque interno (12) desaparece al cerrar la llave y vuelve a verse el 6.", check: { compiles: true, stdout: "12\n6" } },
      { topic: "types", difficulty: 1, kind: "pick", prompt: "Haz que imprima 3.5", code: 'let x = 7.0 / ___;\nprintln!("{}", x);', options: ["2.0", "2", "2i32"], answer: 0, explain: "Rust no convierte tipos solo: f64 / entero no compila. Y con dos enteros, `7 / 2` daría 3 (división entera).", check: { compiles: true, stdout: "3.5", wrongFail: true } },
      { topic: "types", difficulty: 1, kind: "pick", prompt: "Tipo de un literal de texto", code: 'let s: ___ = "hola";', options: ["&str", "String", "char"], answer: 0, explain: "Un literal de texto es `&'static str`, un préstamo a texto guardado en el binario. `String` es el texto con dueño en el heap.", check: { compiles: true, wrongFail: true } },
      { topic: "types", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: "let x: u8 = 255;\nlet y = x + 1;", options: YN, answer: 1, explain: "El compilador detecta el overflow constante (lint `arithmetic_overflow`). Con valores en runtime, en debug sería un panic y en release daría la vuelta a 0.", check: { compiles: false } },
      // ownership
      { topic: "ownership", difficulty: 1, kind: "type", prompt: "Que a siga siendo válida", code: 'let a = String::from("x");\nlet b = a.___();\nprintln!("{} {}", a, b);', answer: "clone", explain: "`let b = a` movería el String y `a` dejaría de ser válido. `a.clone()` duplica los datos del heap; otra opción es prestar con `&a`.", check: { compiles: true, stdout: "x x" } },
      { topic: "ownership", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: 'let a = 5;\nlet b = a;\nprintln!("{} {}", a, b);', options: YN, answer: 0, explain: "Los enteros implementan `Copy`: asignar copia el valor y `a` sigue siendo válido.", check: { compiles: true, stdout: "5 5" } },
      { topic: "ownership", difficulty: 2, kind: "order", prompt: "Ordena: usa s antes de moverla", lines: ['let s = String::from("hi");', 'println!("{}", s.len());', "tomar(s);"], explain: "Pasar un String por valor a `fn tomar(s: String)` lo mueve: después ya no se puede usar `s`. Si recibiera `&str`, no habría move.", check: { program: 'fn tomar(_s: String) {}\nfn main() {\n    let s = String::from("hi");\n    println!("{}", s.len());\n    tomar(s);\n}\n', compiles: true, stdout: "2" } },
      { topic: "ownership", difficulty: 2, kind: "pick", prompt: "Recibe el texto sin moverlo", code: 'fn largo(s: ___) -> usize { s.len() }\nlet s = String::from("hola");\nprintln!("{} {}", largo(&s), s);', options: ["&str", "String", "Box<str>"], answer: 0, explain: "`&str` presta sin tomar ownership y acepta tanto `&String` (por deref coercion) como literales. Es la firma idiomática.", check: { compiles: true, stdout: "4 hola", wrongFail: true } },
      // borrowing
      { topic: "borrowing", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: "let mut s = String::new();\nlet a = &mut s;\nlet b = &mut s;\na.push('x');", options: YN, answer: 1, explain: "Solo puede existir un `&mut` activo a la vez; `a` se usa después de crear `b`, así que chocan.", check: { compiles: false } },
      { topic: "borrowing", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: "let mut v = vec![1, 2];\nlet primero = &v[0];\nv.push(3);\nprintln!(\"{}\", primero);", options: YN, answer: 1, explain: "`push` puede realocar el Vec y dejar `primero` colgando. No se puede mutar mientras un préstamo compartido sigue vivo.", check: { compiles: false } },
      { topic: "borrowing", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: 'let mut v = vec![1];\nlet r = &v[0];\nprintln!("{}", r);\nv.push(2);\nprintln!("{}", v.len());', options: YN, answer: 0, explain: "Non-lexical lifetimes: el préstamo `r` termina en su último uso, así que el `push` posterior es válido.", check: { compiles: true, stdout: "1\n2" } },
      { topic: "borrowing", difficulty: 1, kind: "type", prompt: "Pide un préstamo mutable", code: "let mut s = String::new();\nlet r = &___ s;\nr.push('a');", answer: "mut", explain: "`&mut s` crea un préstamo exclusivo que permite modificar el valor sin tomar ownership.", check: { compiles: true } },
      // patterns
      { topic: "patterns", difficulty: 1, kind: "pick", prompt: "Cubre todos los casos", code: 'let n = 3;\nlet t = match n {\n    0 => "cero",\n    1..=9 => "dígito",\n    ___ => "otro",\n};\nprintln!("{}", t);', options: ["_", "else", "default"], answer: 0, explain: "`_` es el comodín de match. `else` no existe ahí y `default` compilaría, pero solo como variable que atrapa todo. Rust exige que match sea exhaustivo, y con enteros hace falta un caso por defecto.", check: { compiles: true, stdout: "dígito" } },
      { topic: "patterns", difficulty: 2, kind: "pick", prompt: "Completa el match exhaustivo", code: 'let o: Option<i32> = None;\nmatch o {\n    Some(x) => println!("{}", x),\n    ___ => println!("nada"),\n}', options: ["None", "Some()", "Option::Null"], answer: 0, explain: "match debe ser exhaustivo: hace falta el brazo `None`. Así Rust te obliga a manejar la ausencia de valor (no existe null).", check: { compiles: true, stdout: "nada", wrongFail: true } },
      { topic: "patterns", difficulty: 1, kind: "predict", prompt: "¿Qué imprime?", code: 'if let Some(x) = "41".parse::<i32>().ok() {\n    println!("{}", x + 1);\n} else {\n    println!("nada");\n}', options: ["42", "41", "nada", "No compila"], answer: 0, explain: "`parse` devuelve Ok(41), `.ok()` lo convierte en Some(41) e `if let` extrae el valor.", check: { compiles: true, stdout: "42" } },
      // errors
      { topic: "errors", difficulty: 1, kind: "pick", prompt: "Propaga el error al llamador", code: "fn doble(s: &str) -> Result<i32, std::num::ParseIntError> {\n    let n = s.parse::<i32>()___;\n    Ok(n * 2)\n}", options: ["?", "!", ".err()"], answer: 0, explain: "`?` devuelve el valor si es Ok y retorna el Err temprano desde la función. Es la forma idiomática de propagar errores.", check: { compiles: true, wrongFail: true } },
      { topic: "errors", difficulty: 1, kind: "predict", prompt: "¿Qué imprime?", code: 'let r: Result<i32, String> = Err("x".into());\nprintln!("{}", r.unwrap_or(0));', options: ["0", "x", "Panic"], answer: 0, explain: "`unwrap_or` da un valor por defecto en caso de Err, sin panic. Es preferible a `unwrap()` cuando hay un fallback razonable.", check: { compiles: true, stdout: "0" } },
      { topic: "errors", difficulty: 1, kind: "predict", prompt: "¿Qué pasa con None.unwrap()?", code: "let o: Option<i32> = None;\nlet v = o.unwrap();", options: ["Panic en runtime", "Error de compilación", "v vale 0"], answer: 0, explain: "Compila, pero `unwrap()` sobre None hace panic al ejecutar. Por eso en código de producción se prefiere match, `?` o `unwrap_or`.", check: { program: "fn main() {\n    let o: Option<i32> = None;\n    let r = std::panic::catch_unwind(|| o.unwrap());\n    println!(\"{}\", r.is_err());\n}", compiles: true, stdout: "true" } },
      { topic: "errors", difficulty: 2, kind: "order", prompt: "Ordena la función", lines: ["fn doble(s: &str) -> Result<i32, std::num::ParseIntError> {", "    let n: i32 = s.parse()?;", "    Ok(n * 2)", "}"], explain: "Primero se parsea (propagando el error con `?`) y al final se devuelve el éxito envuelto en `Ok`.", check: { compiles: true } },
      // collections
      { topic: "collections", difficulty: 1, kind: "predict", prompt: "¿Qué imprime?", code: 'let v = vec![1, 2, 3];\nprintln!("{:?}", v.get(10));', options: ["None", "Panic", "0"], answer: 0, explain: "`get` devuelve Option y no hace panic fuera de rango. En cambio `v[10]` sí haría panic.", check: { compiles: true, stdout: "None" } },
      { topic: "collections", difficulty: 2, kind: "pick", prompt: "Primer carácter de un String", code: 'let s = String::from("hola");\nlet c = s.___().next();\nprintln!("{:?}", c);', options: ["chars", "index", "get"], answer: 0, explain: "String es UTF-8 y no se indexa con `s[0]`. `chars()` recorre caracteres Unicode; `get` necesita un rango de bytes.", check: { compiles: true, stdout: "Some('h')", wrongFail: true } },
      { topic: "collections", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'use std::collections::HashMap;\nlet mut m = HashMap::new();\n*m.entry("a").or_insert(0) += 1;\n*m.entry("a").or_insert(0) += 1;\nprintln!("{}", m["a"]);', options: ["2", "1", "0"], answer: 0, explain: "`entry().or_insert(0)` inserta 0 solo la primera vez y devuelve `&mut` al valor; cada línea suma 1.", check: { compiles: true, stdout: "2" } },
    ],
  },

  // ─── MID / SEMI-SENIOR ────────────────────────────────────────────────────
  {
    slug: "mid",
    level: "mid",
    title: "Rust Developer Semi-Senior",
    description:
      "Simula la prueba técnica para backend o infraestructura: lifetimes en funciones y structs, traits y genéricos, errores con ?, iteradores, closures, smart pointers y threads.",
    count: 14,
    passPct: 70,
    secondsPerQuestion: 40,
    questions: [
      // lifetimes
      { topic: "lifetimes", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: "fn mayor(a: &str, b: &str) -> &str {\n    if a.len() > b.len() { a } else { b }\n}", options: YN, answer: 1, explain: "Con dos referencias de entrada, la elisión no sabe a cuál ligar la salida. Hace falta `<'a>` en las tres.", check: { compiles: false } },
      { topic: "lifetimes", difficulty: 1, kind: "pick", prompt: "Tipo de retorno correcto", code: "fn mayor<'a>(a: &'a str, b: &'a str) -> ___ {\n    if a.len() > b.len() { a } else { b }\n}", options: ["&'a str", "&str", "&'static str"], answer: 0, explain: "El resultado vive tanto como la más corta de las dos entradas: `&'a str`. `'static` exigiría datos que viven todo el programa.", check: { compiles: true, wrongFail: true } },
      { topic: "lifetimes", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: 'let r;\n{\n    let x = 5;\n    r = &x;\n}\nprintln!("{}", r);', options: YN, answer: 1, explain: "`x` muere al cerrar el bloque y `r` quedaría colgando. El borrow checker rechaza referencias que sobreviven a su dato.", check: { compiles: false } },
      { topic: "lifetimes", difficulty: 2, kind: "pick", prompt: "Struct que guarda un préstamo", code: "struct Parser<'a> {\n    entrada: ___,\n}", options: ["&'a str", "&str", "str"], answer: 0, explain: "Un campo referencia en un struct siempre necesita lifetime explícito; `str` sin & no tiene tamaño conocido.", check: { compiles: true, wrongFail: true } },
      { topic: "lifetimes", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: "struct S { nombre: String }\nimpl S {\n    fn get(&self, _otro: &str) -> &str {\n        &self.nombre\n    }\n}", options: YN, answer: 0, explain: "Tercera regla de elisión: si hay `&self`, la salida toma el lifetime de self. Aquí devolvemos un préstamo de self, así que encaja.", check: { compiles: true } },
      // traits
      { topic: "traits", difficulty: 1, kind: "pick", prompt: "Bound para poder comparar con >", code: "fn max<T: ___>(a: T, b: T) -> T {\n    if a > b { a } else { b }\n}", options: ["PartialOrd", "Eq", "Display"], answer: 0, explain: "Los operadores `<` y `>` vienen de `PartialOrd`. `Eq` solo da igualdad y `Display` es para formatear.", check: { compiles: true, wrongFail: true } },
      { topic: "traits", difficulty: 1, kind: "pick", prompt: "Acepta cualquier cosa imprimible con {}", code: 'fn mostrar(x: impl ___) {\n    println!("{}", x);\n}\nmostrar(5);', options: ["std::fmt::Display", "std::fmt::Debug", "Clone"], answer: 0, explain: "`{}` requiere `Display`; `{:?}` requiere `Debug`. `impl Trait` en argumento es azúcar para un genérico con bound.", check: { compiles: true, stdout: "5", wrongFail: true } },
      { topic: "traits", difficulty: 1, kind: "pick", prompt: "Haz que P se pueda clonar", code: '#[derive(Debug, ___)]\nstruct P { x: i32 }\nlet a = P { x: 1 };\nlet b = a.clone();\nprintln!("{:?}", b);', options: ["Clone", "Copy", "PartialEq"], answer: 0, explain: "`clone()` solo existe si el tipo implementa `Clone`. `Copy` sin `Clone` no compila y `PartialEq` solo da `==`.", check: { compiles: true, stdout: "P { x: 1 }", wrongFail: true } },
      { topic: "traits", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'trait Hola {\n    fn nombre(&self) -> String;\n    fn saludo(&self) -> String { format!("Hola, {}", self.nombre()) }\n}\nstruct Ana;\nimpl Hola for Ana { fn nombre(&self) -> String { "Ana".into() } }\nprintln!("{}", Ana.saludo());', options: ["Hola, Ana", "Hola, ", "No compila"], answer: 0, explain: "Los traits pueden tener métodos por defecto que usan los métodos requeridos. `Ana` solo implementa `nombre`.", check: { compiles: true, stdout: "Hola, Ana" } },
      { topic: "traits", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: 'fn crear(f: bool) -> impl std::fmt::Display {\n    if f { 1 } else { "uno" }\n}', options: YN, answer: 1, explain: "`impl Trait` en el retorno es UN tipo concreto oculto, no varios. Para devolver tipos distintos se usa `Box<dyn Display>`.", check: { compiles: false } },
      { topic: "traits", difficulty: 3, kind: "pick", prompt: "Devuelve tipos distintos", code: 'fn crear(f: bool) -> ___ {\n    if f { Box::new(1) } else { Box::new("uno") }\n}', options: ["Box<dyn std::fmt::Display>", "impl std::fmt::Display", "Box<impl std::fmt::Display>"], answer: 0, explain: "Un trait object `Box<dyn Trait>` permite elegir el tipo en runtime (dispatch dinámico vía vtable).", check: { compiles: true, wrongFail: true } },
      // errors
      { topic: "errors", difficulty: 2, kind: "type", prompt: "¿Qué trait usa ? para convertir?", code: "enum AppErr { Parse(std::num::ParseIntError) }\nimpl ___<std::num::ParseIntError> for AppErr {\n    fn from(e: std::num::ParseIntError) -> Self { AppErr::Parse(e) }\n}\nfn f(s: &str) -> Result<i32, AppErr> {\n    Ok(s.parse::<i32>()?)\n}", answer: "From", explain: "`?` llama a `From::from` sobre el error, así que implementar `From` permite convertir errores de librerías a tu tipo de error.", check: { compiles: true } },
      { topic: "errors", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'fn f() -> Option<i32> {\n    let v: Vec<i32> = vec![];\n    let x = v.first()?;\n    Some(x * 2)\n}\nprintln!("{:?}", f());', options: ["None", "Some(0)", "Panic"], answer: 0, explain: "`?` también funciona con Option: si es None, la función retorna None de inmediato.", check: { compiles: true, stdout: "None" } },
      { topic: "errors", difficulty: 1, kind: "type", prompt: "main que puede usar ?", code: 'fn main() -> Result<(), std::num::ParseIntError> {\n    let n: i32 = "5".parse()?;\n    println!("{}", n);\n    ___(())\n}', answer: "Ok", explain: "`?` solo se usa en funciones que devuelven Result u Option. Si `main` devuelve Result, termina con `Ok(())`.", check: { compiles: true, stdout: "5" } },
      // iterators
      { topic: "iterators", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let v = vec![1, 2, 3];\nv.iter().map(|x| println!("{}", x));\nprintln!("fin");', options: ["fin", "1 2 3 fin", "No compila"], answer: 0, explain: "Los iteradores son perezosos: `map` no hace nada hasta que algo lo consume (`for`, `collect`, `for_each`). Compila con un warning.", check: { compiles: true, stdout: "fin" } },
      { topic: "iterators", difficulty: 1, kind: "type", prompt: "Consume el iterador sumando (da 60)", code: 'let s: i32 = (1..=4)\n    .filter(|n| n % 2 == 0)\n    .map(|n| n * 10)\n    .___();\nprintln!("{}", s);', answer: "sum", explain: "Filtra 2 y 4, los multiplica (20, 40) y `sum()` consume el iterador: 60.", check: { compiles: true, stdout: "60" } },
      { topic: "iterators", difficulty: 1, kind: "pick", prompt: "Consume el iterador en un Vec", code: "let v = vec![1, 2, 3];\nlet d: Vec<i32> = v.iter().map(|x| x * 2).___;", options: ["collect()", "to_vec()", "into()"], answer: 0, explain: "`collect()` consume el iterador y construye la colección indicada por el tipo anotado.", check: { compiles: true, wrongFail: true } },
      { topic: "iterators", difficulty: 2, kind: "pick", prompt: "Itera sin mover el Vec", code: 'let v = vec![String::from("a")];\nfor s in ___ {\n    println!("{}", s);\n}\nprintln!("{}", v.len());', options: ["&v", "v", "*v"], answer: 0, explain: "`for s in v` llama a `into_iter()` y mueve el Vec. Con `&v` (o `v.iter()`) se itera por préstamo y `v` sigue disponible.", check: { compiles: true, stdout: "a\n1", wrongFail: true } },
      // closures
      { topic: "closures", difficulty: 1, kind: "predict", prompt: "¿Qué imprime?", code: 'let mut c = 0;\nlet mut inc = || c += 1;\ninc();\ninc();\nprintln!("{}", c);', options: ["2", "0", "No compila"], answer: 0, explain: "La closure captura `c` por préstamo mutable (es FnMut). Tras su último uso, `c` se puede leer.", check: { compiles: true, stdout: "2" } },
      { topic: "closures", difficulty: 2, kind: "order", prompt: "Ordena para que imprima 1", lines: ["let mut c = 0;", "let mut inc = || c += 1;", "inc();", 'println!("{}", c);'], explain: "La closure mantiene un `&mut c` hasta su último uso (`inc()`); leer `c` recién después evita chocar con ese préstamo.", check: { compiles: true, stdout: "1" } },
      // smart pointers
      { topic: "smart_pointers", difficulty: 2, kind: "pick", prompt: "Enum recursivo", code: "enum Lista {\n    Cons(i32, ___),\n    Nil,\n}", options: ["Box<Lista>", "Lista", "&Lista"], answer: 0, explain: "Un tipo recursivo tendría tamaño infinito; `Box` lo rompe con un puntero de tamaño fijo al heap.", check: { compiles: true, wrongFail: true } },
      { topic: "smart_pointers", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'use std::rc::Rc;\nlet a = Rc::new(5);\nlet b = Rc::clone(&a);\n{\n    let _c = Rc::clone(&a);\n    println!("{}", Rc::strong_count(&a));\n}\nprintln!("{}", Rc::strong_count(&b));', options: ["3 y 2", "3 y 3", "1 y 1", "2 y 1"], answer: 0, explain: "Cada `Rc::clone` suma una referencia (no copia el dato). Al salir del bloque `_c` se libera y el contador baja a 2.", check: { compiles: true, stdout: "3\n2" } },
      // concurrency
      { topic: "concurrency", difficulty: 1, kind: "pick", prompt: "El hilo necesita poseer name", code: 'let name = String::from("Ana");\nlet h = std::thread::spawn(___ || println!("{}", name));\nh.join().unwrap();', options: ["move", "ref", "&"], answer: 0, explain: "Un hilo puede vivir más que la función, así que la closure debe tomar ownership de lo que captura con `move`.", check: { compiles: true, stdout: "Ana", wrongFail: true } },
      { topic: "concurrency", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: "use std::sync::{Arc, Mutex};\nlet n = Arc::new(Mutex::new(0));\nlet hs: Vec<_> = (0..4).map(|_| {\n    let n = Arc::clone(&n);\n    std::thread::spawn(move || *n.lock().unwrap() += 1)\n}).collect();\nfor h in hs { h.join().unwrap(); }\nprintln!(\"{}\", n.lock().unwrap());", options: ["4", "Varía", "0", "No compila"], answer: 0, explain: "`Arc` comparte el dato entre hilos y `Mutex` serializa cada suma; tras `join` el resultado es siempre 4.", check: { compiles: true, stdout: "4" } },
      { topic: "concurrency", difficulty: 2, kind: "order", prompt: "Ordena: comparte y modifica en un hilo", lines: ["let data = Arc::new(Mutex::new(vec![]));", "let d = Arc::clone(&data);", "let h = thread::spawn(move || d.lock().unwrap().push(1));", "h.join().unwrap();", "println!(\"{:?}\", data.lock().unwrap());"], explain: "Se crea el dato compartido, se clona el Arc para el hilo, se lanza, se espera con `join` y recién entonces se lee el resultado.", check: { program: "use std::sync::{Arc, Mutex};\nuse std::thread;\nfn main() {\n    let data = Arc::new(Mutex::new(vec![]));\n    let d = Arc::clone(&data);\n    let h = thread::spawn(move || d.lock().unwrap().push(1));\n    h.join().unwrap();\n    println!(\"{:?}\", data.lock().unwrap());\n}\n", compiles: true, stdout: "[1]" } },
      // patterns
      { topic: "patterns", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let p = (3, -3);\nmatch p {\n    (x, y) if x == -y => println!("opuestos"),\n    (x, _) if x > 0 => println!("positivo"),\n    _ => println!("otro"),\n}', options: ["opuestos", "positivo", "otro"], answer: 0, explain: "match evalúa los brazos en orden y se queda con el primero cuyo patrón y guarda `if` se cumplen.", check: { compiles: true, stdout: "opuestos" } },
    ],
  },

  // ─── SENIOR ───────────────────────────────────────────────────────────────
  {
    slug: "senior",
    level: "senior",
    title: "Rust Developer Senior",
    description:
      "Simula la entrevista técnica senior (sistemas, infra, blockchain): Send/Sync, Rc vs Arc, interior mutability, trait objects, varianza y 'static, Drop, layout, async y reglas de unsafe.",
    count: 15,
    passPct: 75,
    secondsPerQuestion: 50,
    questions: [
      // concurrency: Send / Sync
      { topic: "concurrency", difficulty: 1, kind: "pick", prompt: "Comparte el valor con otro hilo", code: 'use std::{rc::Rc, sync::Arc};\nlet r = ___::new(5);\nstd::thread::spawn(move || println!("{}", r))\n    .join().unwrap();', options: ["Arc", "Rc"], answer: 0, explain: "`Rc` no es `Send`: su contador no es atómico. Entre hilos se usa `Arc`.", check: { compiles: true, stdout: "5", wrongFail: true } },
      { topic: "concurrency", difficulty: 2, kind: "pick", prompt: "Bound mínimo para mover a otro hilo", code: "fn lanzar<T: ___ + 'static>(v: T) {\n    std::thread::spawn(move || drop(v));\n}", options: ["Send", "Sync", "Copy", "Clone"], answer: 0, explain: "`thread::spawn` exige que lo capturado sea `Send + 'static`. `Sync` es para compartir `&T` entre hilos.", check: { compiles: true, wrongFail: true } },
      { topic: "concurrency", difficulty: 2, kind: "pick", prompt: "Préstamos en runtime que sí son Sync", code: "fn need_sync<T: Sync>() {}\nneed_sync::<___<i32>>();", options: ["std::sync::RwLock", "std::cell::RefCell", "std::cell::Cell"], answer: 0, explain: "`RefCell` y `Cell` son `Send` pero no `Sync`: su estado interno no soporta accesos concurrentes. La versión thread-safe es `RwLock`/`Mutex`.", check: { compiles: true, wrongFail: true } },
      { topic: "concurrency", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: "fn need_sync<T: Sync>() {}\nneed_sync::<std::sync::Mutex<std::cell::Cell<i32>>>();", options: YN, answer: 0, explain: "`Mutex<T>` es `Sync` siempre que `T: Send`; el lock garantiza acceso exclusivo, así que el `Cell` interno no necesita ser `Sync`.", check: { compiles: true } },
      { topic: "concurrency", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: 'let v = vec![1, 2, 3];\nstd::thread::scope(|s| {\n    s.spawn(|| println!("{}", v.len()));\n});\nprintln!("{:?}", v);', options: YN, answer: 0, explain: "`thread::scope` garantiza que los hilos terminan antes de salir del scope, así que pueden prestar datos locales sin `Arc` ni `move`.", check: { compiles: true, stdout: "3\n[1, 2, 3]" } },
      // smart pointers / interior mutability
      { topic: "smart_pointers", difficulty: 2, kind: "predict", prompt: "¿Qué pasa al ejecutar?", code: "use std::cell::RefCell;\nlet c = RefCell::new(1);\nlet _a = c.borrow_mut();\nlet _b = c.borrow_mut();", options: ["Panic en runtime", "No compila", "Funciona"], answer: 0, explain: "`RefCell` mueve las reglas de préstamo a runtime: compila, pero el segundo `borrow_mut` activo provoca panic (BorrowMutError).", check: { program: "use std::cell::RefCell;\nfn main() {\n    let c = RefCell::new(1);\n    let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {\n        let _a = c.borrow_mut();\n        let _b = c.borrow_mut();\n    }));\n    println!(\"{}\", r.is_err());\n}\n", compiles: true, stdout: "true" } },
      { topic: "smart_pointers", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let c = std::cell::RefCell::new(1);\nlet _a = c.borrow();\nprintln!("{}", c.try_borrow_mut().is_err());', options: ["true", "false", "Panic"], answer: 0, explain: "Hay un préstamo compartido vivo, así que el mutable falla. `try_borrow_mut` devuelve Err en lugar de hacer panic.", check: { compiles: true, stdout: "true" } },
      { topic: "smart_pointers", difficulty: 1, kind: "type", prompt: "Muta a través de & (tipo Copy)", code: 'let c = std::cell::___::new(5);\nlet r = &c;\nr.set(10);\nprintln!("{}", c.get());', answer: "Cell", explain: "`Cell` da interior mutability para tipos Copy: permite modificar a través de `&` copiando valores dentro y fuera, sin préstamos activos.", check: { compiles: true, stdout: "10" } },
      { topic: "smart_pointers", difficulty: 2, kind: "pick", prompt: "Evita el ciclo hijo → padre", code: "use std::{cell::RefCell, rc};\nstruct Nodo {\n    padre: rc::___<RefCell<Nodo>>,\n    hijos: Vec<rc::Rc<RefCell<Nodo>>>,\n}", options: ["Weak", "Rc", "Box"], answer: 0, explain: "Con `Rc` en ambos sentidos el contador nunca llega a 0 y hay fuga. `Weak` no cuenta como dueño y se promueve con `upgrade()`.", check: { compiles: true } },
      // traits: dyn vs generics
      { topic: "traits", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: "trait Clonar { fn clonar(&self) -> Self; }\nstruct A;\nimpl Clonar for A { fn clonar(&self) -> Self { A } }\nlet v: Vec<Box<dyn Clonar>> = vec![Box::new(A)];", options: YN, answer: 1, explain: "Un método que devuelve `Self` hace al trait no dyn-compatible: detrás de `dyn` el tamaño de Self es desconocido.", check: { compiles: false } },
      { topic: "traits", difficulty: 3, kind: "type", prompt: "Excluye el método del vtable", code: "trait Clonar {\n    fn clonar(&self) -> Self where Self: ___;\n}\nstruct A;\nimpl Clonar for A { fn clonar(&self) -> Self { A } }\nlet v: Vec<Box<dyn Clonar>> = vec![Box::new(A)];", answer: "Sized", explain: "`where Self: Sized` saca ese método del trait object; el resto del trait se puede seguir usando con `dyn`.", check: { compiles: true } },
      { topic: "traits", difficulty: 2, kind: "pick", prompt: "Display sin romper la orphan rule", code: 'use std::fmt;\nstruct MiVec(Vec<i32>);\nimpl fmt::Display for ___ {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "v")\n    }\n}\nprintln!("{}", MiVec(vec![]));', options: ["MiVec", "Vec<i32>"], answer: 0, explain: "Orphan rule: no puedes implementar un trait ajeno para un tipo ajeno. El newtype `MiVec` es local, así que sí se puede.", check: { compiles: true, stdout: "v", wrongFail: true } },
      { topic: "closures", difficulty: 2, kind: "pick", prompt: "Bound para llamarla dos veces mutando", code: 'fn dos_veces<F: ___>(mut f: F) { f(); f(); }\nlet mut n = 0;\ndos_veces(|| n += 1);\nprintln!("{}", n);', options: ["FnMut()", "Fn()", "FnOnce()"], answer: 0, explain: "La closure muta lo capturado, así que no es `Fn`; y se llama dos veces, así que `FnOnce` no alcanza. `FnMut` es el bound justo.", check: { compiles: true, stdout: "2", wrongFail: true } },
      // lifetimes
      { topic: "lifetimes", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: 'fn guardar<T: \'static>(t: T) -> T { t }\nlet s = String::from("hola");\nprintln!("{}", guardar(s));', options: YN, answer: 0, explain: "`T: 'static` no significa \"vive para siempre\" sino \"no contiene préstamos no-'static\". Un String con dueño lo cumple.", check: { compiles: true, stdout: "hola" } },
      { topic: "lifetimes", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: 'fn guardar<T: \'static>(t: T) -> T { t }\nlet s = String::from("hola");\nlet r = guardar(&s);', options: YN, answer: 1, explain: "`&s` es un préstamo de un local, no `'static`. Por eso `thread::spawn` rechaza capturar referencias a la pila.", check: { compiles: false } },
      { topic: "lifetimes", difficulty: 3, kind: "type", prompt: "Liga la salida a otro, no a self", code: "struct Ctx { s: String }\nimpl Ctx {\n    fn elegir<'a>(&self, otro: &'a str) -> ___ str {\n        otro\n    }\n}", answer: "&'a", explain: "Sin anotar, la elisión liga la salida a `&self`, no a `otro`, y no compila. Con `'a` en `otro` y en la salida, el contrato es correcto.", check: { compiles: true } },
      { topic: "lifetimes", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: "fn push<'a>(v: &mut Vec<&'a str>, s: &'a str) { v.push(s); }\nlet mut v: Vec<&'static str> = vec![\"hola\"];\nlet s = String::from(\"x\");\npush(&mut v, &s);", options: YN, answer: 1, explain: "`&mut T` es invariante en T: `'a` queda fijado a `'static` y `&s` no vive tanto. Con `&T` (covariante) sí se podría acortar.", check: { compiles: false } },
      // iterators
      { topic: "iterators", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let v: Vec<i32> = vec![1, 2]\n    .into_iter()\n    .map(|x| { print!("m{} ", x); x })\n    .filter(|x| { print!("f{} ", x); true })\n    .collect();', options: ["m1 f1 m2 f2", "m1 m2 f1 f2", "Nada"], answer: 0, explain: "Los adaptadores se encadenan por elemento: cada valor pasa por toda la cadena antes de pedir el siguiente.", check: { compiles: true, stdout: "m1 f1 m2 f2" } },
      { topic: "iterators", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let n = (1..).map(|x| x * x).find(|x| *x > 50);\nprintln!("{:?}", n);', options: ["Some(64)", "Se cuelga", "Some(49)"], answer: 0, explain: "El rango infinito es perezoso y `find` corta en el primer match, así que solo calcula hasta 8².", check: { compiles: true, stdout: "Some(64)" } },
      // memory
      { topic: "memory", difficulty: 2, kind: "order", prompt: "D imprime al destruirse. Ordena: a y luego b", lines: ['let _b = D("b");', 'let _a = D("a");'], explain: "Las variables locales se destruyen en orden inverso a su declaración (como una pila): la última en nacer es la primera en morir.", check: { program: `${D}\nfn main() {\n    let _b = D("b");\n    let _a = D("a");\n}\n`, compiles: true, stdout: "a\nb" } },
      { topic: "memory", difficulty: 3, kind: "predict", prompt: "¿Qué imprime?", code: `${D}\nlet _ = D("x");\nprintln!("y");`, options: ["x y y", "y y x", "solo y"], answer: 0, explain: "`let _` no crea binding: el valor se destruye en el acto. `let _x` sí lo mantiene vivo hasta el final del scope (útil con guards de Mutex).", check: { compiles: true, stdout: "x\ny" } },
      { topic: "memory", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'use std::mem::size_of;\nprintln!("{}", size_of::<Option<Box<i32>>>() == size_of::<Box<i32>>());', options: ["true", "false"], answer: 0, explain: "Niche optimization: Box nunca es nulo, así que None se representa con el puntero nulo y Option no ocupa más.", check: { compiles: true, stdout: "true" } },
      { topic: "memory", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'use std::mem::size_of;\nlet fat = size_of::<&dyn std::fmt::Debug>();\nprintln!("{}", fat == 2 * size_of::<usize>());', options: ["true", "false"], answer: 0, explain: "`&dyn Trait` es un fat pointer: puntero al dato más puntero a la vtable. Ese es el costo del dispatch dinámico frente a genéricos.", check: { compiles: true, stdout: "true" } },
      // async
      { topic: "async", difficulty: 2, kind: "predict", prompt: "¿Qué imprime?", code: 'let fut = async { println!("dentro"); };\nprintln!("fuera");\ndrop(fut);', options: ["fuera", "dentro y fuera", "fuera y dentro"], answer: 0, explain: "Los futures en Rust son perezosos: no se ejecutan hasta que un executor los hace `poll` (por ejemplo con `.await`).", check: { compiles: true, stdout: "fuera" } },
      { topic: "async", difficulty: 3, kind: "predict", prompt: "¿Compila?", code: 'use std::rc::Rc;\nfn assert_send<T: Send>(_: T) {}\nasync fn tarea() {\n    let r = Rc::new(1);\n    async {}.await;\n    println!("{}", r);\n}\nassert_send(tarea());', options: YN, answer: 1, explain: "`r` sigue vivo a través del `.await`, queda dentro del future y lo hace no-Send. Por eso `tokio::spawn` lo rechazaría.", check: { compiles: false } },
      { topic: "async", difficulty: 3, kind: "type", prompt: "Tipo de self en poll", code: "use std::{future::Future, pin::Pin, task::{Context, Poll}};\nstruct Listo;\nimpl Future for Listo {\n    type Output = u8;\n    fn poll(self: ___<&mut Self>, _cx: &mut Context<'_>) -> Poll<u8> {\n        Poll::Ready(1)\n    }\n}", answer: "Pin", explain: "`poll` recibe `Pin<&mut Self>`: garantiza que el future no se moverá en memoria, necesario para futures autorreferenciales.", check: { compiles: true } },
      // unsafe
      { topic: "unsafe_ffi", difficulty: 1, kind: "predict", prompt: "¿Compila?", code: 'let x = 5;\nlet p = &x as *const i32;\nprintln!("{}", *p);', options: YN, answer: 1, explain: "Crear un puntero crudo es seguro; desreferenciarlo requiere un bloque `unsafe`.", check: { compiles: false } },
      { topic: "unsafe_ffi", difficulty: 1, kind: "type", prompt: "Desreferencia el puntero crudo", code: 'let x = 5;\nlet p = &x as *const i32;\nlet y = ___ { *p };\nprintln!("{}", y);', answer: "unsafe", explain: "Dentro de `unsafe` tú garantizas que el puntero es válido y está alineado; el compilador ya no puede comprobarlo.", check: { compiles: true, stdout: "5" } },
      { topic: "unsafe_ffi", difficulty: 2, kind: "predict", prompt: "¿Compila?", code: "let mut s = String::new();\nunsafe {\n    let a = &mut s;\n    let b = &mut s;\n    a.push('x');\n}", options: YN, answer: 1, explain: "`unsafe` no apaga el borrow checker: solo habilita operaciones extra (punteros crudos, funciones unsafe, static mut, FFI).", check: { compiles: false } },
      // errors
      { topic: "errors", difficulty: 2, kind: "pick", prompt: "Error genérico para propagar con ?", code: 'fn run() -> Result<(), Box<dyn ___>> {\n    let n: i32 = "x".parse()?;\n    Ok(())\n}\nprintln!("{}", run().is_err());', options: ["std::error::Error", "std::fmt::Display", "std::fmt::Debug"], answer: 0, explain: "`?` convierte cualquier error en `Box<dyn Error>` vía `From`; a `Box<dyn Display>` o `Box<dyn Debug>` no. Cómodo en binarios; en librerías se prefiere un enum propio.", check: { compiles: true, stdout: "true", wrongFail: true } },
    ],
  },
];
