import type { ExamQuestion } from "../../lib/content/types.ts";
import { L } from "../../lib/i18n/text.ts";

// Written-test formats for planet Concurra (Go): trace tables (dry-run the code, fill the values)
// and debugging tasks (tap the buggy line, then fix it). The validator runs every `verify` on the Go
// Playground and proves each fix passes the tests while the buggy code and the near misses fail.
// Debug code is the player's file (package main, imports, functions, never main), as in tasks.ts.

const code = (...lines: string[]) => lines.join("\n");

// ─── JUNIOR ──────────────────────────────────────────────────────────────────

/** Junior trace: integer division truncates. */
export const intDivTrace: ExamQuestion = {
  slug: "int-div",
  kind: "trace",
  topic: "basics",
  difficulty: 1,
  prompt: L("Trace table: integer division", "Tabla de traza: división entera", "トレース：整数の割り算"),
  brief: L(
    "One row per pass of the loop, with the values at the end of the pass.",
    "Una fila por vuelta del bucle, con los valores al final de la vuelta.",
    "ループの1周ごとに1行、周の終わりの値を書く。",
  ),
  code: code(
    "n := 7",
    "sum := 0",
    "for i := 1; i <= 3; i++ {",
    "\tsum += n / i",
    "\tn -= 2",
    "}",
  ),
  columns: ["i", "n", "sum"],
  rows: [
    { label: L("pass 1", "vuelta 1", "1周目"), cells: ["1", "5", "7"], given: [0] },
    { label: L("pass 2", "vuelta 2", "2周目"), cells: ["2", "3", "9"], given: [0] },
    { label: L("pass 3", "vuelta 3", "3周目"), cells: ["3", "1", "10"], given: [0] },
  ],
  verify: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "func main() {",
    "\tn := 7",
    "\tsum := 0",
    "\tfor i := 1; i <= 3; i++ {",
    "\t\tsum += n / i",
    "\t\tn -= 2",
    '\t\tfmt.Println(i, "|", n, "|", sum)',
    "\t}",
    "}",
  ),
  explain: L(
    "Dividing two ints drops the fraction: 7/1 = 7, then 5/2 = 2, then 3/3 = 1, so sum ends at 10.",
    "Dividir dos int descarta la parte decimal: 7/1 = 7, luego 5/2 = 2 y 3/3 = 1, así sum termina en 10.",
    "int 同士の割り算は小数を切り捨てる：7/1=7、5/2=2、3/3=1 で sum は 10。",
  ),
};

/** Junior trace: range over a string walks runes at byte offsets. */
export const runeRangeTrace: ExamQuestion = {
  slug: "rune-range",
  kind: "trace",
  topic: "strings",
  difficulty: 1,
  prompt: L("Trace table: range over a string", "Tabla de traza: range sobre un string", "トレース：文字列の range"),
  brief: L(
    "One row per pass of the loop, at its end. Write string(r) without quotes.",
    "Una fila por vuelta del bucle, al final. Escribe string(r) sin comillas.",
    "ループの1周ごとに1行、周の終わりの値。string(r) は引用符なしで。",
  ),
  code: code(
    's := "héllo"',
    "count := 0",
    "for i, r := range s {",
    "\tif r == 'l' {",
    "\t\tcount++",
    "\t}",
    "}",
  ),
  columns: ["i", "string(r)", "count"],
  rows: [
    { label: L("pass 1", "vuelta 1", "1周目"), cells: ["0", "h", "0"], given: [0, 1] },
    { label: L("pass 2", "vuelta 2", "2周目"), cells: ["1", "é", "0"] },
    { label: L("pass 3", "vuelta 3", "3周目"), cells: ["3", "l", "1"] },
    { label: L("pass 4", "vuelta 4", "4周目"), cells: ["4", "l", "2"] },
    { label: L("pass 5", "vuelta 5", "5周目"), cells: ["5", "o", "2"] },
  ],
  verify: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "func main() {",
    '\ts := "héllo"',
    "\tcount := 0",
    "\tfor i, r := range s {",
    "\t\tif r == 'l' {",
    "\t\t\tcount++",
    "\t\t}",
    '\t\tfmt.Println(i, "|", string(r), "|", count)',
    "\t}",
    "}",
  ),
  explain: L(
    "range decodes runes and i is the byte offset: é takes 2 bytes in UTF-8, so i jumps from 1 to 3.",
    "range decodifica runas e i es el desplazamiento en bytes: é ocupa 2 bytes en UTF-8, así que i salta de 1 a 3.",
    "range はルーンを読み、i はバイト位置。é は UTF-8 で2バイトなので i は 1 から 3 へ飛ぶ。",
  ),
};

// ─── MID ─────────────────────────────────────────────────────────────────────

/** Mid trace: a subslice shares memory until append outgrows its capacity. */
export const sharedSliceTrace: ExamQuestion = {
  slug: "shared-slice",
  kind: "trace",
  topic: "slices",
  difficulty: 2,
  prompt: L("Trace table: a slice of a slice", "Tabla de traza: un slice de un slice", "トレース：スライスのスライス"),
  brief: L(
    "Write each slice as fmt.Println shows it, e.g. [1 2].",
    "Escribe cada slice como lo muestra fmt.Println, p. ej. [1 2].",
    "各スライスは fmt.Println の表示どおりに書く（例：[1 2]）。",
  ),
  code: code(
    "a := []int{1, 2, 3, 4}",
    "b := a[1:3]",
    "b[0] = 20",
    "b = append(b, 30)",
    "b = append(b, 40)",
    "b[0] = 50",
  ),
  columns: ["a", "b"],
  rows: [
    { label: L("after line 3", "tras la línea 3", "3行目の後"), cells: ["[1 20 3 4]", "[20 3]"] },
    { label: L("after line 4", "tras la línea 4", "4行目の後"), cells: ["[1 20 3 30]", "[20 3 30]"] },
    { label: L("after line 5", "tras la línea 5", "5行目の後"), cells: ["[1 20 3 30]", "[20 3 30 40]"] },
    { label: L("after line 6", "tras la línea 6", "6行目の後"), cells: ["[1 20 3 30]", "[50 3 30 40]"] },
  ],
  verify: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "func main() {",
    "\ta := []int{1, 2, 3, 4}",
    "\tb := a[1:3]",
    "\tb[0] = 20",
    '\tfmt.Println(a, "|", b)',
    "\tb = append(b, 30)",
    '\tfmt.Println(a, "|", b)',
    "\tb = append(b, 40)",
    '\tfmt.Println(a, "|", b)',
    "\tb[0] = 50",
    '\tfmt.Println(a, "|", b)',
    "}",
  ),
  explain: L(
    "b has cap 3 inside a, so b[0] and the first append write into a. The second append needs a new array: after it, b no longer touches a.",
    "b tiene cap 3 dentro de a, así que b[0] y el primer append escriben en a. El segundo append necesita un array nuevo: desde ahí b ya no toca a.",
    "b は a の中で cap 3。b[0] と1回目の append は a に書く。2回目は新しい配列が必要で、以後 b は a に触れない。",
  ),
};

/** Mid trace: deferred calls run last-in first-out and can change a named result. */
export const deferOrderTrace: ExamQuestion = {
  slug: "defer-order",
  kind: "trace",
  topic: "defer_panic",
  difficulty: 2,
  prompt: L("Trace table: defers and a named result", "Tabla de traza: defers y un resultado con nombre", "トレース：defer と名前付き戻り値"),
  brief: L(
    "return 5 sets n to 5, then the deferred calls run. One row per deferred call, in the order they run.",
    "return 5 pone n en 5 y luego corren las llamadas diferidas. Una fila por llamada diferida, en el orden en que corren.",
    "return 5 で n が 5 になり、その後 defer が実行される。実行順に defer 1回につき1行。",
  ),
  code: code(
    "func run() (n int) {",
    "\tfor i := 1; i <= 3; i++ {",
    "\t\tdefer func(k int) { n = n*10 + k }(i)",
    "\t}",
    "\treturn 5",
    "}",
  ),
  columns: ["k", "n"],
  rows: [
    { label: L("1st deferred call", "1.ª llamada diferida", "1回目の defer"), cells: ["3", "53"] },
    { label: L("2nd deferred call", "2.ª llamada diferida", "2回目の defer"), cells: ["2", "532"] },
    { label: L("3rd deferred call", "3.ª llamada diferida", "3回目の defer"), cells: ["1", "5321"] },
  ],
  verify: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "func run() (n int) {",
    "\tfor i := 1; i <= 3; i++ {",
    "\t\tdefer func(k int) {",
    "\t\t\tn = n*10 + k",
    '\t\t\tfmt.Println(k, "|", n)',
    "\t\t}(i)",
    "\t}",
    "\treturn 5",
    "}",
    "",
    "func main() {",
    "\trun()",
    "}",
  ),
  explain: L(
    "Defers run in reverse order (3, 2, 1), each with the k it got when deferred, and they edit the named n after return set it: run() gives 5321.",
    "Los defers corren al revés (3, 2, 1), cada uno con el k que recibió, y editan la n con nombre tras el return: run() da 5321.",
    "defer は逆順（3,2,1）で、登録時の k を使い、return 後の名前付き n を変える。run() は 5321。",
  ),
};

/** Mid debug: modifying a copy of a struct instead of the slice element. */
export const healCopyDebug: ExamQuestion = {
  slug: "heal-copy",
  kind: "debug",
  mode: "ide",
  topic: "structs",
  difficulty: 2,
  prompt: L("Debug: healing does nothing", "Depura: curar no hace nada", "デバッグ：回復が効かない"),
  brief: L(
    "HealAll(ps, amount) should add amount to every player's HP, never above Max. But after ps := []Player{{\"ana\", 5, 10}} and HealAll(ps, 3), ps is still [{ana 5 10}] instead of [{ana 8 10}].",
    "HealAll(ps, amount) debería sumar amount al HP de cada jugador, sin pasar de Max. Pero tras ps := []Player{{\"ana\", 5, 10}} y HealAll(ps, 3), ps sigue en [{ana 5 10}] en vez de [{ana 8 10}].",
    "HealAll(ps, amount) は各プレイヤーの HP に amount を足す（Max まで）。でも ps := []Player{{\"ana\", 5, 10}} で HealAll(ps, 3) の後も ps が [{ana 8 10}] でなく [{ana 5 10}] のまま。",
  ),
  code: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "type Player struct {",
    "\tName string",
    "\tHP   int",
    "\tMax  int",
    "}",
    "",
    "// HealAll adds amount to every player's HP, never above Max.",
    "func HealAll(ps []Player, amount int) {",
    "\tfor i := range ps {",
    "\t\tp := ps[i]",
    "\t\tp.HP += amount",
    "\t\tif p.HP > p.Max {",
    "\t\t\tp.HP = p.Max",
    "\t\t}",
    "\t}",
    "}",
  ),
  bugLine: 14,
  solution: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "type Player struct {",
    "\tName string",
    "\tHP   int",
    "\tMax  int",
    "}",
    "",
    "// HealAll adds amount to every player's HP, never above Max.",
    "func HealAll(ps []Player, amount int) {",
    "\tfor i := range ps {",
    "\t\tp := &ps[i]",
    "\t\tp.HP += amount",
    "\t\tif p.HP > p.Max {",
    "\t\t\tp.HP = p.Max",
    "\t\t}",
    "\t}",
    "}",
  ),
  nearMiss: [
    // A pointer to the range copy still edits the copy.
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "type Player struct {",
      "\tName string",
      "\tHP   int",
      "\tMax  int",
      "}",
      "",
      "func HealAll(ps []Player, amount int) {",
      "\tfor _, q := range ps {",
      "\t\tp := &q",
      "\t\tp.HP += amount",
      "\t\tif p.HP > p.Max {",
      "\t\t\tp.HP = p.Max",
      "\t\t}",
      "\t}",
      "}",
    ),
    // Writes the element back before the cap, so HP can pass Max.
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "type Player struct {",
      "\tName string",
      "\tHP   int",
      "\tMax  int",
      "}",
      "",
      "func HealAll(ps []Player, amount int) {",
      "\tfor i := range ps {",
      "\t\tp := ps[i]",
      "\t\tp.HP += amount",
      "\t\tps[i] = p",
      "\t\tif p.HP > p.Max {",
      "\t\t\tp.HP = p.Max",
      "\t\t}",
      "\t}",
      "}",
    ),
  ],
  tests: [
    { run: '{\n\tps := []Player{{"ana", 5, 10}}\n\tHealAll(ps, 3)\n\tfmt.Println(ps)\n}', expect: "[{ana 8 10}]" },
    { run: '{\n\tps := []Player{{"bo", 9, 10}, {"cy", 1, 4}}\n\tHealAll(ps, 5)\n\tfmt.Println(ps)\n}', expect: "[{bo 10 10} {cy 4 4}]" },
    { run: "{\n\tvar ps []Player\n\tHealAll(ps, 2)\n\tfmt.Println(len(ps))\n}", expect: "0", hidden: true },
    { run: '{\n\tps := []Player{{"di", 2, 9}, {"ed", 0, 3}}\n\tHealAll(ps, 1)\n\tfmt.Println(ps[0].HP, ps[1].HP)\n}', expect: "3 1", hidden: true },
    { run: '{\n\tps := []Player{{"fo", 6, 7}}\n\tHealAll(ps, 4)\n\tfmt.Println(ps)\n}', expect: "[{fo 7 7}]", hidden: true },
  ],
  explain: L(
    "p := ps[i] copies the struct, so the changes were lost. p := &ps[i] points at the element in the slice.",
    "p := ps[i] copia el struct, así que los cambios se perdían. p := &ps[i] apunta al elemento dentro del slice.",
    "p := ps[i] は構造体のコピーなので変更が消えていた。p := &ps[i] ならスライスの要素を指す。",
  ),
};

/** Mid debug: a loop condition that drops the last chunk. */
export const chunkDebug: ExamQuestion = {
  slug: "chunk",
  kind: "debug",
  mode: "ide",
  topic: "slices",
  difficulty: 2,
  prompt: L("Debug: the last chunk goes missing", "Depura: falta el último trozo", "デバッグ：最後のチャンクが消える"),
  brief: L(
    "Chunk(xs, size) should split xs into slices of size items, the last one possibly shorter. But Chunk([]int{1, 2, 3, 4, 5}, 2) returns [[1 2] [3 4]] instead of [[1 2] [3 4] [5]].",
    "Chunk(xs, size) debería partir xs en slices de size elementos; el último puede ser más corto. Pero Chunk([]int{1, 2, 3, 4, 5}, 2) devuelve [[1 2] [3 4]] en vez de [[1 2] [3 4] [5]].",
    "Chunk(xs, size) は xs を size 個ずつに分ける（最後は短くてよい）。でも Chunk([]int{1, 2, 3, 4, 5}, 2) が [[1 2] [3 4] [5]] でなく [[1 2] [3 4]] を返す。",
  ),
  code: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "// Chunk splits xs into slices of size items; the last one may be shorter.",
    "func Chunk(xs []int, size int) [][]int {",
    "\tvar out [][]int",
    "\tfor i := 0; i+size < len(xs); i += size {",
    "\t\tend := i + size",
    "\t\tif end > len(xs) {",
    "\t\t\tend = len(xs)",
    "\t\t}",
    "\t\tout = append(out, xs[i:end])",
    "\t}",
    "\treturn out",
    "}",
  ),
  bugLine: 8,
  solution: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "// Chunk splits xs into slices of size items; the last one may be shorter.",
    "func Chunk(xs []int, size int) [][]int {",
    "\tvar out [][]int",
    "\tfor i := 0; i < len(xs); i += size {",
    "\t\tend := i + size",
    "\t\tif end > len(xs) {",
    "\t\t\tend = len(xs)",
    "\t\t}",
    "\t\tout = append(out, xs[i:end])",
    "\t}",
    "\treturn out",
    "}",
  ),
  nearMiss: [
    // Keeps every full chunk but still drops a short last one.
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "func Chunk(xs []int, size int) [][]int {",
      "\tvar out [][]int",
      "\tfor i := 0; i+size <= len(xs); i += size {",
      "\t\tend := i + size",
      "\t\tif end > len(xs) {",
      "\t\t\tend = len(xs)",
      "\t\t}",
      "\t\tout = append(out, xs[i:end])",
      "\t}",
      "\treturn out",
      "}",
    ),
    // One pass too many: adds an empty chunk when size divides len(xs).
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "func Chunk(xs []int, size int) [][]int {",
      "\tvar out [][]int",
      "\tfor i := 0; i <= len(xs); i += size {",
      "\t\tend := i + size",
      "\t\tif end > len(xs) {",
      "\t\t\tend = len(xs)",
      "\t\t}",
      "\t\tout = append(out, xs[i:end])",
      "\t}",
      "\treturn out",
      "}",
    ),
  ],
  tests: [
    { run: "fmt.Println(Chunk([]int{1, 2, 3, 4, 5}, 2))", expect: "[[1 2] [3 4] [5]]" },
    { run: "fmt.Println(Chunk([]int{1, 2, 3}, 5))", expect: "[[1 2 3]]" },
    { run: "fmt.Println(Chunk([]int{1, 2, 3, 4}, 2))", expect: "[[1 2] [3 4]]", hidden: true },
    { run: "fmt.Println(Chunk([]int{}, 3))", expect: "[]", hidden: true },
    { run: "fmt.Println(Chunk([]int{7, 8, 9}, 1))", expect: "[[7] [8] [9]]", hidden: true },
  ],
  explain: L(
    "i+size < len(xs) stops before the last chunk starts. Loop while i < len(xs); the end check already shortens the last chunk.",
    "i+size < len(xs) se detiene antes de que empiece el último trozo. Itera mientras i < len(xs); el chequeo de end ya acorta el último.",
    "i+size < len(xs) では最後のチャンクの前で止まる。i < len(xs) の間回せばよい。末尾は end の確認で短くなる。",
  ),
};

// ─── SENIOR ──────────────────────────────────────────────────────────────────

/** Senior trace: append inside a function writes into the caller's spare capacity. */
export const appendAliasTrace: ExamQuestion = {
  slug: "append-alias",
  kind: "trace",
  topic: "slices",
  difficulty: 3,
  prompt: L("Trace table: append into shared capacity", "Tabla de traza: append en capacidad compartida", "トレース：共有容量への append"),
  brief: L(
    "Write each slice as fmt.Println shows it, e.g. [1 2]. Note the capacity on line 7.",
    "Escribe cada slice como lo muestra fmt.Println, p. ej. [1 2]. Fíjate en la capacidad de la línea 7.",
    "各スライスは fmt.Println の表示で（例：[1 2]）。7行目の容量に注意。",
  ),
  code: code(
    "func add(s []int, v int) []int {",
    "\ts = append(s, v)",
    "\ts[0] = v",
    "\treturn s",
    "}",
    "func main() {",
    "\ta := make([]int, 1, 2)",
    "\tb := add(a, 5)",
    "\tc := add(a, 7)",
    "\tc = add(c, 9)",
    "\tb = add(b[:1], 1)",
    "}",
  ),
  columns: ["a", "b", "c"],
  rows: [
    { label: L("after line 9", "tras la línea 9", "9行目の後"), cells: ["[7]", "[7 7]", "[7 7]"] },
    { label: L("after line 10", "tras la línea 10", "10行目の後"), cells: ["[7]", "[7 7]", "[9 7 9]"] },
    { label: L("after line 11", "tras la línea 11", "11行目の後"), cells: ["[1]", "[1 1]", "[9 7 9]"] },
  ],
  verify: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "func add(s []int, v int) []int {",
    "\ts = append(s, v)",
    "\ts[0] = v",
    "\treturn s",
    "}",
    "",
    "func main() {",
    "\ta := make([]int, 1, 2)",
    "\tb := add(a, 5)",
    "\tc := add(a, 7)",
    '\tfmt.Println(a, "|", b, "|", c)',
    "\tc = add(c, 9)",
    '\tfmt.Println(a, "|", b, "|", c)',
    "\tb = add(b[:1], 1)",
    '\tfmt.Println(a, "|", b, "|", c)',
    "}",
  ),
  explain: L(
    "a, b and c share one 2-slot array, so add(a, 7) rewrites b too. add(c, 9) outgrows it and copies; add(b[:1], 1) writes into the shared array again.",
    "a, b y c comparten un array de 2 lugares, así que add(a, 7) reescribe b. add(c, 9) lo desborda y copia; add(b[:1], 1) vuelve a escribir en el compartido.",
    "a,b,c は2要素の配列を共有し、add(a, 7) は b も書き換える。add(c, 9) は容量超過でコピー、add(b[:1], 1) は共有配列に書く。",
  ),
};

/** Senior debug (ide): waiting for the workers before anyone reads their results. */
export const parallelSumDebug: ExamQuestion = {
  slug: "parallel-sum",
  kind: "debug",
  mode: "ide",
  topic: "channels",
  difficulty: 3,
  prompt: L("Debug: the parallel sum deadlocks", "Depura: la suma paralela se bloquea", "デバッグ：並列合計がデッドロック"),
  brief: L(
    'ParallelSum(chunks) should sum each chunk in its own goroutine and return the grand total. But ParallelSum([][]int{{1, 2}, {3}}) never returns 6: the program dies with "fatal error: all goroutines are asleep - deadlock!".',
    'ParallelSum(chunks) debería sumar cada trozo en su propia goroutine y devolver el total. Pero ParallelSum([][]int{{1, 2}, {3}}) nunca devuelve 6: el programa muere con "fatal error: all goroutines are asleep - deadlock!".',
    'ParallelSum(chunks) は各チャンクを別の goroutine で合計し総計を返すはず。でも ParallelSum([][]int{{1, 2}, {3}}) は 6 を返さず "fatal error: all goroutines are asleep - deadlock!" で落ちる。',
  ),
  code: code(
    "package main",
    "",
    "import (",
    '\t"fmt"',
    '\t"sync"',
    ")",
    "",
    "// ParallelSum adds up every chunk in its own goroutine and returns the grand total.",
    "func ParallelSum(chunks [][]int) int {",
    "\tresults := make(chan int)",
    "\tvar wg sync.WaitGroup",
    "\tfor _, c := range chunks {",
    "\t\twg.Add(1)",
    "\t\tgo func(c []int) {",
    "\t\t\tdefer wg.Done()",
    "\t\t\ts := 0",
    "\t\t\tfor _, v := range c {",
    "\t\t\t\ts += v",
    "\t\t\t}",
    "\t\t\tresults <- s",
    "\t\t}(c)",
    "\t}",
    "\twg.Wait()",
    "\tclose(results)",
    "\ttotal := 0",
    "\tfor s := range results {",
    "\t\ttotal += s",
    "\t}",
    "\treturn total",
    "}",
  ),
  bugLine: 23,
  alsoLines: [10, 24],
  solution: code(
    "package main",
    "",
    "import (",
    '\t"fmt"',
    '\t"sync"',
    ")",
    "",
    "// ParallelSum adds up every chunk in its own goroutine and returns the grand total.",
    "func ParallelSum(chunks [][]int) int {",
    "\tresults := make(chan int)",
    "\tvar wg sync.WaitGroup",
    "\tfor _, c := range chunks {",
    "\t\twg.Add(1)",
    "\t\tgo func(c []int) {",
    "\t\t\tdefer wg.Done()",
    "\t\t\ts := 0",
    "\t\t\tfor _, v := range c {",
    "\t\t\t\ts += v",
    "\t\t\t}",
    "\t\t\tresults <- s",
    "\t\t}(c)",
    "\t}",
    "\tgo func() {",
    "\t\twg.Wait()",
    "\t\tclose(results)",
    "\t}()",
    "\ttotal := 0",
    "\tfor s := range results {",
    "\t\ttotal += s",
    "\t}",
    "\treturn total",
    "}",
  ),
  nearMiss: [
    // A buffer of 1 only lets one worker finish; the rest still block before Wait returns.
    code(
      "package main",
      "",
      "import (",
      '\t"fmt"',
      '\t"sync"',
      ")",
      "",
      "func ParallelSum(chunks [][]int) int {",
      "\tresults := make(chan int, 1)",
      "\tvar wg sync.WaitGroup",
      "\tfor _, c := range chunks {",
      "\t\twg.Add(1)",
      "\t\tgo func(c []int) {",
      "\t\t\tdefer wg.Done()",
      "\t\t\ts := 0",
      "\t\t\tfor _, v := range c {",
      "\t\t\t\ts += v",
      "\t\t\t}",
      "\t\t\tresults <- s",
      "\t\t}(c)",
      "\t}",
      "\twg.Wait()",
      "\tclose(results)",
      "\ttotal := 0",
      "\tfor s := range results {",
      "\t\ttotal += s",
      "\t}",
      "\treturn total",
      "}",
    ),
    // Waits in the background but never closes, so the range never ends.
    code(
      "package main",
      "",
      "import (",
      '\t"fmt"',
      '\t"sync"',
      ")",
      "",
      "func ParallelSum(chunks [][]int) int {",
      "\tresults := make(chan int)",
      "\tvar wg sync.WaitGroup",
      "\tfor _, c := range chunks {",
      "\t\twg.Add(1)",
      "\t\tgo func(c []int) {",
      "\t\t\tdefer wg.Done()",
      "\t\t\ts := 0",
      "\t\t\tfor _, v := range c {",
      "\t\t\t\ts += v",
      "\t\t\t}",
      "\t\t\tresults <- s",
      "\t\t}(c)",
      "\t}",
      "\tgo func() {",
      "\t\twg.Wait()",
      "\t}()",
      "\ttotal := 0",
      "\tfor s := range results {",
      "\t\ttotal += s",
      "\t}",
      "\treturn total",
      "}",
    ),
  ],
  tests: [
    { run: "fmt.Println(ParallelSum([][]int{{1, 2}, {3}}))", expect: "6" },
    { run: "fmt.Println(ParallelSum(nil))", expect: "0" },
    { run: "fmt.Println(ParallelSum([][]int{{5}}))", expect: "5", hidden: true },
    { run: "fmt.Println(ParallelSum([][]int{{1, 2, 3}, {4, 5}, {6}, {}}))", expect: "21", hidden: true },
    { run: "fmt.Println(ParallelSum([][]int{{-4, 4}, {10}}))", expect: "10", hidden: true },
  ],
  explain: L(
    "wg.Wait() blocked main while every worker blocked sending on the unbuffered channel. Wait and close in a goroutine so main can receive.",
    "wg.Wait() bloqueaba main mientras cada worker esperaba para enviar por el canal sin buffer. Espera y cierra en una goroutine para que main reciba.",
    "main が wg.Wait() で止まり、各 worker はバッファなしチャネルへの送信で止まっていた。Wait と close を goroutine で行えば main が受信できる。",
  ),
};

/** Senior debug (paper): `:=` inside the loop shadows the error that is returned. */
export const shadowedErrDebug: ExamQuestion = {
  slug: "shadowed-err",
  kind: "debug",
  mode: "paper",
  topic: "errors",
  difficulty: 3,
  prompt: L("Debug: a bad price returns no error", "Depura: un precio malo no da error", "デバッグ：不正な価格でエラーが出ない"),
  brief: L(
    'ParsePrices(pairs) reads "name=cents" pairs, stops at the first bad one and returns the prices so far plus an error naming it. But ParsePrices([]string{"tea=150", "cake=x"}) returns map[tea:150] and a nil error instead of the error bad price in "cake=x".',
    'ParsePrices(pairs) lee pares "nombre=centavos", se detiene en el primero malo y devuelve los precios hasta ahí y un error que lo nombra. Pero ParsePrices([]string{"tea=150", "cake=x"}) devuelve map[tea:150] y un error nil en vez del error bad price in "cake=x".',
    'ParsePrices(pairs) は "name=cents" を読み、最初の不正なペアで止まり、それまでの価格とそのペア名入りのエラーを返す。でも ParsePrices([]string{"tea=150", "cake=x"}) は bad price in "cake=x" でなく nil エラーを返す。',
  ),
  code: code(
    "package main",
    "",
    "import (",
    '\t"fmt"',
    '\t"strconv"',
    '\t"strings"',
    ")",
    "",
    '// ParsePrices reads "name=cents" pairs. It stops at the first bad pair and',
    "// returns the prices read so far and an error naming that pair.",
    "func ParsePrices(pairs []string) (map[string]int, error) {",
    "\tprices := map[string]int{}",
    "\tvar err error",
    "\tfor _, p := range pairs {",
    '\t\tname, raw, ok := strings.Cut(p, "=")',
    "\t\tif !ok {",
    '\t\t\terr = fmt.Errorf("bad pair %q", p)',
    "\t\t\tbreak",
    "\t\t}",
    "\t\tcents, err := strconv.Atoi(raw)",
    "\t\tif err != nil {",
    '\t\t\terr = fmt.Errorf("bad price in %q", p)',
    "\t\t\tbreak",
    "\t\t}",
    "\t\tprices[name] = cents",
    "\t}",
    "\treturn prices, err",
    "}",
  ),
  bugLine: 20,
  alsoLines: [22],
  solution: code(
    "package main",
    "",
    "import (",
    '\t"fmt"',
    '\t"strconv"',
    '\t"strings"',
    ")",
    "",
    '// ParsePrices reads "name=cents" pairs. It stops at the first bad pair and',
    "// returns the prices read so far and an error naming that pair.",
    "func ParsePrices(pairs []string) (map[string]int, error) {",
    "\tprices := map[string]int{}",
    "\tvar err error",
    "\tfor _, p := range pairs {",
    '\t\tname, raw, ok := strings.Cut(p, "=")',
    "\t\tif !ok {",
    '\t\t\terr = fmt.Errorf("bad pair %q", p)',
    "\t\t\tbreak",
    "\t\t}",
    "\t\tcents, convErr := strconv.Atoi(raw)",
    "\t\tif convErr != nil {",
    '\t\t\terr = fmt.Errorf("bad price in %q", p)',
    "\t\t\tbreak",
    "\t\t}",
    "\t\tprices[name] = cents",
    "\t}",
    "\treturn prices, err",
    "}",
  ),
  nearMiss: [
    // Fixes the shadowing but keeps going after the bad pair.
    code(
      "package main",
      "",
      "import (",
      '\t"fmt"',
      '\t"strconv"',
      '\t"strings"',
      ")",
      "",
      "func ParsePrices(pairs []string) (map[string]int, error) {",
      "\tprices := map[string]int{}",
      "\tvar err error",
      "\tfor _, p := range pairs {",
      '\t\tname, raw, ok := strings.Cut(p, "=")',
      "\t\tif !ok {",
      '\t\t\terr = fmt.Errorf("bad pair %q", p)',
      "\t\t\tbreak",
      "\t\t}",
      "\t\tcents, convErr := strconv.Atoi(raw)",
      "\t\tif convErr != nil {",
      '\t\t\terr = fmt.Errorf("bad price in %q", p)',
      "\t\t\tcontinue",
      "\t\t}",
      "\t\tprices[name] = cents",
      "\t}",
      "\treturn prices, err",
      "}",
    ),
    // Returns the raw strconv error, which doesn't name the pair.
    code(
      "package main",
      "",
      "import (",
      '\t"fmt"',
      '\t"strconv"',
      '\t"strings"',
      ")",
      "",
      "func ParsePrices(pairs []string) (map[string]int, error) {",
      "\tprices := map[string]int{}",
      "\tvar err error",
      "\tfor _, p := range pairs {",
      '\t\tname, raw, ok := strings.Cut(p, "=")',
      "\t\tif !ok {",
      '\t\t\terr = fmt.Errorf("bad pair %q", p)',
      "\t\t\tbreak",
      "\t\t}",
      "\t\tcents, convErr := strconv.Atoi(raw)",
      "\t\tif convErr != nil {",
      "\t\t\terr = convErr",
      "\t\t\tbreak",
      "\t\t}",
      "\t\tprices[name] = cents",
      "\t}",
      "\treturn prices, err",
      "}",
    ),
  ],
  tests: [
    { run: 'fmt.Println(ParsePrices([]string{"tea=150", "cake=x"}))', expect: 'map[tea:150] bad price in "cake=x"' },
    { run: 'fmt.Println(ParsePrices([]string{"tea=150", "pie=320"}))', expect: "map[pie:320 tea:150] <nil>" },
    { run: 'fmt.Println(ParsePrices([]string{"a=1", "b=x", "c=2"}))', expect: 'map[a:1] bad price in "b=x"', hidden: true },
    { run: 'fmt.Println(ParsePrices([]string{"nope"}))', expect: 'map[] bad pair "nope"', hidden: true },
    { run: '{\n\t_, err := ParsePrices([]string{"x=1.5"})\n\tfmt.Println(err != nil)\n}', expect: "true", hidden: true },
  ],
  explain: L(
    "cents, err := declared a new err inside the loop, so the outer err stayed nil. A different name keeps the error in the outer err.",
    "cents, err := declaraba una err nueva dentro del bucle, así que la err de afuera seguía en nil. Otro nombre deja el error en la err externa.",
    "cents, err := がループ内で新しい err を宣言し、外の err は nil のままだった。別名にすれば外の err にエラーが入る。",
  ),
};

/** Senior debug (paper): a nil pointer stored in an error interface is not a nil error. */
export const typedNilDebug: ExamQuestion = {
  slug: "typed-nil",
  kind: "debug",
  mode: "paper",
  topic: "interfaces",
  difficulty: 3,
  prompt: L("Debug: a valid user gets an error", "Depura: un usuario válido recibe un error", "デバッグ：正しいユーザーでもエラー"),
  brief: L(
    'Register(db, u) should store a valid user\'s age in db and return nil, or return the validation error. But for User{"ana", 30} it stores the age and still returns a non-nil error: Register(db, u) == nil is false.',
    'Register(db, u) debería guardar la edad de un usuario válido en db y devolver nil, o devolver el error de validación. Pero con User{"ana", 30} guarda la edad y aun así devuelve un error no nil: Register(db, u) == nil es false.',
    'Register(db, u) は正しいユーザーの年齢を db に保存して nil を返し、不正なら検証エラーを返すはず。でも User{"ana", 30} では保存した上で nil でないエラーを返し、Register(db, u) == nil が false。',
  ),
  code: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "type User struct {",
    "\tName string",
    "\tAge  int",
    "}",
    "",
    "type ValidationError struct{ Field string }",
    "",
    'func (e *ValidationError) Error() string { return "invalid " + e.Field }',
    "",
    "func validate(u User) *ValidationError {",
    '\tif u.Name == "" {',
    '\t\treturn &ValidationError{Field: "name"}',
    "\t}",
    "\tif u.Age < 0 || u.Age > 150 {",
    '\t\treturn &ValidationError{Field: "age"}',
    "\t}",
    "\treturn nil",
    "}",
    "",
    "// Register stores a valid user's age in db and returns nil, or the validation error.",
    "func Register(db map[string]int, u User) error {",
    "\terr := validate(u)",
    "\tif err == nil {",
    "\t\tdb[u.Name] = u.Age",
    "\t}",
    "\treturn err",
    "}",
  ),
  bugLine: 14,
  solution: code(
    "package main",
    "",
    'import "fmt"',
    "",
    "type User struct {",
    "\tName string",
    "\tAge  int",
    "}",
    "",
    "type ValidationError struct{ Field string }",
    "",
    'func (e *ValidationError) Error() string { return "invalid " + e.Field }',
    "",
    "func validate(u User) error {",
    '\tif u.Name == "" {',
    '\t\treturn &ValidationError{Field: "name"}',
    "\t}",
    "\tif u.Age < 0 || u.Age > 150 {",
    '\t\treturn &ValidationError{Field: "age"}',
    "\t}",
    "\treturn nil",
    "}",
    "",
    "// Register stores a valid user's age in db and returns nil, or the validation error.",
    "func Register(db map[string]int, u User) error {",
    "\terr := validate(u)",
    "\tif err == nil {",
    "\t\tdb[u.Name] = u.Age",
    "\t}",
    "\treturn err",
    "}",
  ),
  nearMiss: [
    // Declaring err as error still wraps the typed nil pointer.
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "type User struct {",
      "\tName string",
      "\tAge  int",
      "}",
      "",
      "type ValidationError struct{ Field string }",
      "",
      'func (e *ValidationError) Error() string { return "invalid " + e.Field }',
      "",
      "func validate(u User) *ValidationError {",
      '\tif u.Name == "" {',
      '\t\treturn &ValidationError{Field: "name"}',
      "\t}",
      "\tif u.Age < 0 || u.Age > 150 {",
      '\t\treturn &ValidationError{Field: "age"}',
      "\t}",
      "\treturn nil",
      "}",
      "",
      "func Register(db map[string]int, u User) error {",
      "\tvar err error = validate(u)",
      "\tif err == nil {",
      "\t\tdb[u.Name] = u.Age",
      "\t}",
      "\treturn err",
      "}",
    ),
    // A value receiver changes the method set, not the typed nil.
    code(
      "package main",
      "",
      'import "fmt"',
      "",
      "type User struct {",
      "\tName string",
      "\tAge  int",
      "}",
      "",
      "type ValidationError struct{ Field string }",
      "",
      'func (e ValidationError) Error() string { return "invalid " + e.Field }',
      "",
      "func validate(u User) *ValidationError {",
      '\tif u.Name == "" {',
      '\t\treturn &ValidationError{Field: "name"}',
      "\t}",
      "\tif u.Age < 0 || u.Age > 150 {",
      '\t\treturn &ValidationError{Field: "age"}',
      "\t}",
      "\treturn nil",
      "}",
      "",
      "func Register(db map[string]int, u User) error {",
      "\terr := validate(u)",
      "\tif err == nil {",
      "\t\tdb[u.Name] = u.Age",
      "\t}",
      "\treturn err",
      "}",
    ),
  ],
  tests: [
    { run: '{\n\tdb := map[string]int{}\n\tfmt.Println(Register(db, User{"ana", 30}) == nil, db)\n}', expect: "true map[ana:30]" },
    { run: '{\n\tdb := map[string]int{}\n\tfmt.Println(Register(db, User{"", 5}), db)\n}', expect: "invalid name map[]" },
    { run: '{\n\tdb := map[string]int{}\n\tfmt.Println(Register(db, User{"old", 200}), db)\n}', expect: "invalid age map[]", hidden: true },
    { run: '{\n\tdb := map[string]int{}\n\tRegister(db, User{"bo", 7})\n\tRegister(db, User{"cy", -1})\n\tfmt.Println(len(db), db)\n}', expect: "1 map[bo:7]", hidden: true },
    { run: '{\n\terr := Register(map[string]int{}, User{"ed", 40})\n\tfmt.Println(err == nil)\n}', expect: "true", hidden: true },
  ],
  explain: L(
    "A nil *ValidationError inside an error interface is not nil: the interface holds a type. Returning error makes `return nil` a real nil.",
    "Un *ValidationError nil dentro de una interfaz error no es nil: la interfaz guarda un tipo. Devolver error hace que `return nil` sea nil de verdad.",
    "error インターフェースに入った nil の *ValidationError は nil ではない（型を持つ）。戻り値を error にすれば return nil が本当の nil。",
  ),
};

export const juniorTraceDebug: ExamQuestion[] = [intDivTrace, runeRangeTrace];
export const midTraceDebug: ExamQuestion[] = [sharedSliceTrace, deferOrderTrace, healCopyDebug, chunkDebug];
export const seniorTraceDebug: ExamQuestion[] = [appendAliasTrace, parallelSumDebug, shadowedErrDebug, typedNilDebug];
