import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 2 · GRAPH FOREST  (scene graph and local vs world space, Vector3, Matrix4, Euler and Quaternion)

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const IMP = 'import * as THREE from "three";\n';
const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");

// ─── 2.1 The family tree ───────────────────────────────────────────────────
const sceneGraph: LessonDef = {
  slug: "scene-graph",
  title: L("The family tree", "El árbol familiar", "家族の木"),
  concept: "scene_graph",
  mode: "lesson",
  xp: 70,
  enemy: "threejs/lost-wanderer",
  enemyName: L("LOST WANDERER", "ERRANTE PERDIDO", "まいごの旅人"),
  beats: [
    say(L(
      "Welcome to Graph Forest! Objects form a family tree: parent.add(child). A child rides along wherever its parent goes.",
      "¡Bienvenido al Bosque del Grafo! Los objetos forman un árbol: parent.add(child). El hijo viaja con su padre a todas partes.",
      "グラフの森へようこそ！物体は家族の木を作る。parent.add(child) で、子は親にくっついて動くよ。",
    )),
    {
      kind: "act",
      prompt: L("Put the kid on the parent's shoulders", "Sube al hijo a los hombros del padre", "子を親の肩に乗せよう"),
      steps: [
        { label: L("PARENT", "PADRE", "親"), line: "const p = new THREE.Group();\np.position.x = 10;", effects: [{ t: "tag", actor: "hero", text: "p", value: "x 10" }] },
        { label: L("KID", "HIJO", "子"), line: "const kid = new THREE.Object3D();\nkid.position.x = 1;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "kid", value: "x 1" }] },
        { label: L("ADD", "AGREGAR", "追加"), line: "p.add(kid);", effects: [{ t: "give", to: "hero" }, { t: "say", actor: "ally", text: L("Up I go!", "¡Arriba!", "乗ったよ！") }] },
        { label: L("WHERE?", "¿DÓNDE?", "どこ？"), line: "console.log(kid.getWorldPosition(new THREE.Vector3()).x);", effects: [{ t: "print", text: "11" }, { t: "banner", text: L("LOCAL 1, WORLD 11", "LOCAL 1, MUNDO 11", "ローカル1 ワールド11") }], output: "11" },
      ],
    },
    say(L(
      "kid.position is LOCAL: relative to its parent. Its WORLD position is the parent's world transform applied to it.",
      "kid.position es LOCAL: relativa a su padre. Su posición en el MUNDO es la del padre aplicada encima.",
      "kid.position は親から見たローカル座標。ワールド座標は親の変形をかけた結果だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const p = new THREE.Group();\np.position.x = 10;\nconst kid = new THREE.Object3D();\nkid.position.x = 1;\np.add(kid);\nconsole.log(kid.getWorldPosition(new THREE.Vector3()).x, kid.position.x);",
      options: ["11 1", "1 1", "11 11"],
      answer: 0,
      output: "11 1",
      check: { compiles: true, stdout: "11 1" },
      explain: L("Local stays 1; the world adds the parent's 10. getWorldPosition updates the matrices for you.", "Lo local sigue en 1; el mundo suma el 10 del padre. getWorldPosition actualiza las matrices por ti.", "ローカルは1のまま、ワールドは親の10を足す。getWorldPosition は行列も更新してくれる。"),
      setup: [{ t: "tag", actor: "hero", text: "p", value: "x 10" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "kid", value: "x 1" }],
      win: [{ t: "print", text: "11 1" }],
    },
    {
      kind: "predict",
      prompt: L("Now the parent is 2x big. Print?", "Ahora el padre mide 2x. ¿Imprime?", "親が2倍に。何が表示される？"),
      code: IMP + "const p = new THREE.Group();\np.position.x = 10;\np.scale.set(2, 2, 2);\nconst kid = new THREE.Object3D();\nkid.position.x = 1;\np.add(kid);\nconsole.log(kid.getWorldPosition(new THREE.Vector3()).x);",
      options: ["12", "11", "22"],
      answer: 0,
      output: "12",
      check: { compiles: true, stdout: "12" },
      explain: L("The parent's scale stretches the kid's offset first: 1 × 2 = 2, then + 10 = 12.", "La escala del padre estira primero la distancia del hijo: 1 × 2 = 2, luego + 10 = 12.", "親の scale で子の距離がまず伸びる。1×2＝2、それに10を足して12。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const p1 = new THREE.Group();\nconst p2 = new THREE.Group();\nconst c = new THREE.Object3D();\np1.add(c);\np2.add(c);\nconsole.log(p1.children.length, p2.children.length);",
      options: ["0 1", "1 1", "1 0"],
      answer: 0,
      output: "0 1",
      check: { compiles: true, stdout: "0 1" },
      explain: L("An object has ONE parent. add() first removes it from its old parent.", "Un objeto tiene UN solo padre. add() primero lo quita de su padre anterior.", "親はひとりだけ。add() は先に前の親から外すよ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "enter", actor: "enemy" }],
      win: [{ t: "give", to: "ally" }, { t: "print", text: "0 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const p = new THREE.Group();\nconst c = new THREE.Object3D();\np.add(c);\np.add(c);\nconsole.log(p.children.length);",
      options: ["1", "2", "0"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("Adding the same child twice still leaves one entry: it just moves to its own parent again.", "Agregar el mismo hijo dos veces deja una sola entrada: solo vuelve a su mismo padre.", "同じ子を2回足しても1つだけ。同じ親に入り直すだけだよ。"),
    },
    say(L(
      "traverse(fn) visits a whole tree, depth first: each parent before its children.",
      "traverse(fn) recorre todo el árbol en profundidad: cada padre antes que sus hijos.",
      "traverse(fn) は木全体を深さ優先でたどる。親が先、子はその後だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const root = new THREE.Group(); root.name = "root";\nconst a = new THREE.Object3D(); a.name = "a";\nconst b = new THREE.Object3D(); b.name = "b";\nconst c = new THREE.Object3D(); c.name = "c";\nroot.add(a, b);\na.add(c);\nconst names: string[] = [];\nroot.traverse((o) => { names.push(o.name); });\nconsole.log(names.join(","));',
      options: ["root,a,c,b", "root,a,b,c", "c,a,b,root"],
      answer: 0,
      output: "root,a,c,b",
      check: { compiles: true, stdout: "root,a,c,b" },
      explain: L("Depth first: root, then a and a's whole family (c), then b.", "En profundidad: root, luego a y toda su familia (c), luego b.", "深さ優先：root→a→a の子 c→b の順。"),
      win: [{ t: "print", text: "root,a,c,b" }],
    },
    say(L(
      "To move a child to a new parent WITHOUT it jumping, use newParent.attach(child): it keeps its world position.",
      "Para pasar un hijo a otro padre SIN que salte, usa newParent.attach(child): conserva su posición en el mundo.",
      "子を別の親へ跳ばさずに移すなら newParent.attach(child)。ワールド位置を保つよ。",
    )),
    {
      kind: "pick",
      prompt: L("Pick up the sword where it lies", "Recoge la espada donde está", "剣をその場で拾おう"),
      code: IMP + "const hero = new THREE.Group();\nhero.position.x = 10;\nhero.updateMatrixWorld();\nconst sword = new THREE.Object3D();\nsword.position.x = 12;\nhero.___(sword);\nconsole.log(sword.getWorldPosition(new THREE.Vector3()).x);",
      options: ["attach", "add"],
      answer: 0,
      check: { compiles: true, stdout: "12" },
      explain: L("attach keeps the sword at world x 12 (local 2). add would keep local 12 and jump it to world 22.", "attach deja la espada en x 12 del mundo (local 2). add mantendría local 12 y la saltaría a 22.", "attach なら剣はワールド x 12（ローカル2）のまま。add だとローカル12でワールド22へ跳ぶ。"),
      setup: [{ t: "tag", actor: "hero", text: "hero", value: "x 10" }, { t: "enter", actor: "ally" }, { t: "item", kind: "sword", holder: "ally" }],
      win: [{ t: "give", to: "hero" }, { t: "print", text: "12" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const g = new THREE.Group();\ng.position.set(10, 0, 0);\nconst w = g.localToWorld(new THREE.Vector3(1, 0, 0)).x;\nconst l = g.worldToLocal(new THREE.Vector3(11, 0, 0)).x;\nconsole.log(w, l);",
      options: ["11 1", "1 11", "11 11"],
      answer: 0,
      output: "11 1",
      check: { compiles: true, stdout: "11 1" },
      explain: L("localToWorld goes from the group's space to the world; worldToLocal goes back.", "localToWorld pasa del espacio del grupo al mundo; worldToLocal hace el camino inverso.", "localToWorld はグループの空間からワールドへ、worldToLocal はその逆。"),
    },
    say(L(
      "The world matrix lives in matrixWorld. Reading it directly? Call scene.updateMatrixWorld() first, or it may be stale.",
      "La matriz del mundo vive en matrixWorld. ¿La lees directo? Llama antes a scene.updateMatrixWorld() o puede estar vieja.",
      "ワールド行列は matrixWorld にある。直接読むなら先に scene.updateMatrixWorld() を呼ぼう。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const scene = new THREE.Scene();\nconst group = new THREE.Group();\ngroup.position.y = 2;\ngroup.scale.setScalar(3);\nconst child = new THREE.Object3D();\nchild.position.set(1, 1, 0);\nscene.add(group);\ngroup.add(child);\nscene.updateMatrixWorld();\nconsole.log(new THREE.Vector3().setFromMatrixPosition(child.matrixWorld).toArray().join(","));',
      options: ["3,5,0", "1,3,0", "3,3,0"],
      answer: 0,
      output: "3,5,0",
      check: { compiles: true, stdout: "3,5,0" },
      explain: L("Scale 3 first: (1, 1) becomes (3, 3). Then the group's y = 2 lifts it to (3, 5).", "Primero la escala 3: (1, 1) pasa a (3, 3). Luego la y = 2 del grupo la sube a (3, 5).", "先に scale 3 で (1, 1) が (3, 3)。グループの y = 2 で (3, 5) になる。"),
    },
    {
      kind: "run",
      prompt: L("Grab the sword without moving it: sword world x: 12", "Toma la espada sin moverla: sword world x: 12", "剣を動かさず拾おう：sword world x: 12"),
      starter: IMP + "const hero = new THREE.Group();\nhero.position.x = 10;\nconst sword = new THREE.Object3D();\nsword.position.x = 12;\nhero.updateMatrixWorld();\nhero.add(sword);\nconst w = new THREE.Vector3();\nsword.getWorldPosition(w);\nconsole.log(\"sword world x: \" + w.x);\n",
      solution: IMP + "const hero = new THREE.Group();\nhero.position.x = 10;\nconst sword = new THREE.Object3D();\nsword.position.x = 12;\nhero.updateMatrixWorld();\nhero.attach(sword);\nconst w = new THREE.Vector3();\nsword.getWorldPosition(w);\nconsole.log(\"sword world x: \" + w.x);\n",
      expect: "sword world x: 12",
      fallback: [String.raw`hero\.attach\s*\(\s*sword\s*\)`, String.raw`sword\.position\.x\s*=\s*2\s*;`],
      explain: L("add keeps local x 12, so the sword lands at 22. attach converts it to local 2 and it stays put.", "add mantiene local x 12 y la espada cae en 22. attach la convierte a local 2 y no se mueve.", "add はローカル12のままで22に跳ぶ。attach はローカル2に直すので動かないよ。"),
    },
  ],
};

// ─── 2.2 Arrows in the quiver ──────────────────────────────────────────────
const vectors: LessonDef = {
  slug: "vectors",
  title: L("Arrows in the quiver", "Flechas en el carcaj", "矢筒の矢"),
  concept: "vectors",
  mode: "lesson",
  xp: 70,
  enemy: "threejs/leak-blob",
  enemyName: L("ALIAS BLOB", "BLOB ALIAS", "エイリアスブロブ"),
  beats: [
    say(L(
      "A Vector3 is an arrow: x, y, z. Its methods CHANGE the vector itself and return it, so you can chain them.",
      "Un Vector3 es una flecha: x, y, z. Sus métodos CAMBIAN el propio vector y lo devuelven, así puedes encadenarlos.",
      "Vector3 は x・y・z の矢。メソッドは自分自身を変えて自分を返すから、つなげて書けるよ。",
    )),
    {
      kind: "act",
      prompt: L("Share an arrow, then give each its own", "Comparte una flecha y luego dale una a cada uno", "矢を共有して、次はそれぞれに渡そう"),
      steps: [
        { label: L("ARROW a", "FLECHA a", "矢 a"), line: "const a = new THREE.Vector3(1, 2, 3);", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "x 1" }] },
        { label: L("b = a", "b = a", "b = a"), line: "const b = a;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b", value: "x 1" }, { t: "lend", to: "ally" }] },
        { label: L("BEND b", "DOBLAR b", "b を曲げる"), line: "b.x = 9;", effects: [{ t: "value", actor: "ally", text: "x 9" }, { t: "value", actor: "hero", text: "x 9" }, { t: "shake" }, { t: "say", actor: "hero", text: L("Mine changed too!", "¡La mía cambió!", "ぼくのも変わった！") }] },
        { label: L("CLONE", "CLONAR", "クローン"), line: "const c = a.clone();", effects: [{ t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "c", value: "x 9" }, { t: "banner", text: L("OWN ARROW!", "¡FLECHA PROPIA!", "自分の矢！") }] },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const a = new THREE.Vector3(1, 2, 3);\nconst b = a;\nb.x = 9;\nconsole.log(a.x);",
      options: ["9", "1", "undefined"],
      answer: 0,
      output: "9",
      check: { compiles: true, stdout: "9" },
      explain: L("b = a copies the reference, not the arrow. Both names point to the same Vector3.", "b = a copia la referencia, no la flecha. Ambos nombres apuntan al mismo Vector3.", "b = a は参照のコピー。2つの名前が同じ Vector3 を指しているよ。"),
      win: [{ t: "print", text: "9" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const v = new THREE.Vector3(1, 1, 1);\nconst r = v.add(new THREE.Vector3(1, 0, 0));\nconsole.log(v.x, r === v);",
      options: ["2 true", "1 false", "2 false"],
      answer: 0,
      output: "2 true",
      check: { compiles: true, stdout: "2 true" },
      explain: L("add() changes v and returns v itself. It does not build a new vector.", "add() cambia v y devuelve el mismo v. No crea un vector nuevo.", "add() は v を変えて v 自身を返す。新しいベクトルは作らない。"),
    },
    {
      kind: "type",
      prompt: L("Copy the arrow before changing it", "Copia la flecha antes de cambiarla", "変える前に矢をコピーしよう"),
      code: IMP + "const pos = new THREE.Vector3(0, 0, 0);\nconst next = pos.___().add(new THREE.Vector3(1, 0, 0));\nconsole.log(pos.x, next.x);",
      answer: "clone",
      check: { compiles: true, stdout: "0 1" },
      explain: L("clone() makes a new Vector3 with the same numbers, so add() changes only the copy.", "clone() crea un Vector3 nuevo con los mismos números, así add() solo cambia la copia.", "clone() は同じ値の新しい Vector3 を作る。add() はコピーだけを変えるよ。"),
      win: [{ t: "print", text: "0 1" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const a = new THREE.Vector3(1, 1, 1);\nconst b = new THREE.Vector3(1, 1, 1);\nconsole.log(a === b, a.equals(b));",
      options: ["false true", "true true", "false false"],
      answer: 0,
      output: "false true",
      check: { compiles: true, stdout: "false true" },
      explain: L("=== asks 'same object?'. equals() asks 'same numbers?'.", "=== pregunta '¿el mismo objeto?'. equals() pregunta '¿los mismos números?'.", "=== は「同じオブジェクト？」、equals() は「同じ値？」を調べるよ。"),
    },
    say(L(
      "Arrows have a length. distanceTo measures between two points. normalize() keeps the direction but makes the length 1.",
      "Las flechas tienen longitud. distanceTo mide entre dos puntos. normalize() mantiene la dirección con longitud 1.",
      "矢には長さがある。distanceTo は2点の距離。normalize() は向きはそのままで長さを1にするよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const v = new THREE.Vector3(3, 4, 0);\nconst d = new THREE.Vector3(0, 0, 0).distanceTo(new THREE.Vector3(0, 3, 4));\nconsole.log(v.length(), d);",
      options: ["5 5", "7 7", "25 25"],
      answer: 0,
      output: "5 5",
      check: { compiles: true, stdout: "5 5" },
      explain: L("Pythagoras: √(3² + 4²) = 5, in any pair of axes.", "Pitágoras: √(3² + 4²) = 5, en cualquier par de ejes.", "三平方の定理：√(3² + 4²) = 5。どの軸の組でも同じ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const n = new THREE.Vector3(3, 4, 0).normalize();\nconsole.log(n.toArray().join(","));',
      options: ["0.6000000000000001,0.8,0", "0.6,0.8,0", "3,4,0"],
      answer: 0,
      output: "0.6000000000000001,0.8,0",
      check: { compiles: true, stdout: "0.6000000000000001,0.8,0" },
      explain: L("Floats are binary: 3/5 is a hair off. Print 3D math with toFixed(n) to keep it readable.", "Los floats son binarios: 3/5 queda a un pelo. Imprime matemática 3D con toFixed(n) para leerla bien.", "小数は二進数なので 3/5 が少しずれる。3D の計算は toFixed(n) で表示しよう。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("A crumb of float!", "¡Una miga de float!", "小数のかけら！") }],
    },
    say(L(
      "dot() tells how much two arrows agree: 0 means perpendicular. cross() builds an arrow perpendicular to both.",
      "dot() dice cuánto coinciden dos flechas: 0 es perpendicular. cross() crea una flecha perpendicular a ambas.",
      "dot() は2本の矢の向きの一致度で、0なら直角。cross() は両方に直角な矢を作るよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const x = new THREE.Vector3(1, 0, 0);\nconst y = new THREE.Vector3(0, 1, 0);\nconst z = x.clone().cross(y);\nconsole.log(x.dot(y), z.toArray().join(\",\"));",
      options: ["0 0,0,1", "1 0,0,1", "0 0,0,-1"],
      answer: 0,
      output: "0 0,0,1",
      check: { compiles: true, stdout: "0 0,0,1" },
      explain: L("X and Y are perpendicular, so dot is 0. X × Y = +Z. Swap the order and you get -Z.", "X e Y son perpendiculares: dot es 0. X × Y = +Z. Si cambias el orden obtienes -Z.", "X と Y は直角なので dot は0。X × Y = +Z。順番を逆にすると -Z になる。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const v = new THREE.Vector3(0, 0, 0).lerp(new THREE.Vector3(10, 0, 0), 0.25);\nconsole.log(v.x);",
      options: ["2.5", "0.25", "7.5"],
      answer: 0,
      output: "2.5",
      check: { compiles: true, stdout: "2.5" },
      explain: L("lerp(target, t) walks a fraction t of the way to the target: a quarter of 10 is 2.5.", "lerp(target, t) avanza una fracción t hacia el objetivo: un cuarto de 10 es 2.5.", "lerp(target, t) は目標まで t の割合だけ進む。10 の4分の1で2.5。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const v = new THREE.Vector3(1, 2, 3).multiplyScalar(2).sub(new THREE.Vector3(1, 1, 1));\nconsole.log(v.toArray().join(","));',
      options: ["1,3,5", "2,4,6", "0,2,4"],
      answer: 0,
      output: "1,3,5",
      check: { compiles: true, stdout: "1,3,5" },
      explain: L("Chained left to right: (2, 4, 6), then minus 1 on each axis.", "Encadenado de izquierda a derecha: (2, 4, 6), luego menos 1 en cada eje.", "左から順に (2, 4, 6)、それから各軸から1を引く。"),
    },
    {
      kind: "run",
      prompt: L("Preview the step: it must print pos 0 next 1", "Previsualiza el paso: debe imprimir pos 0 next 1", "一歩を試そう：pos 0 next 1 と表示"),
      starter: IMP + "const pos = new THREE.Vector3(0, 0, 0);\nconst step = new THREE.Vector3(1, 0, 0);\nconst next = pos.add(step);\nconsole.log(`pos ${pos.x} next ${next.x}`);\n",
      solution: IMP + "const pos = new THREE.Vector3(0, 0, 0);\nconst step = new THREE.Vector3(1, 0, 0);\nconst next = pos.clone().add(step);\nconsole.log(`pos ${pos.x} next ${next.x}`);\n",
      expect: "pos 0 next 1",
      fallback: [String.raw`pos\.clone\(\)\.add\(\s*step\s*\)`, String.raw`new\s+THREE\.Vector3\(\)\.(copy\(\s*pos\s*\)\.add\(\s*step\s*\)|addVectors\(\s*pos\s*,\s*step\s*\))`, String.raw`step\.clone\(\)\.add\(\s*pos\s*\)`],
      explain: L("pos.add(step) moved the real position. Clone first so only the preview changes.", "pos.add(step) movió la posición real. Clona primero para que solo cambie la vista previa.", "pos.add(step) は本物の位置を動かす。先に clone() すれば試しの方だけ変わるよ。"),
    },
  ],
};

// ─── 2.3 Turning without tangles ───────────────────────────────────────────
const rotations: LessonDef = {
  slug: "matrices-quaternions-euler",
  title: L("Turning without tangles", "Girar sin enredos", "からまない回転"),
  concept: "rotations",
  mode: "lesson",
  xp: 80,
  enemy: "threejs/gimbal-knot",
  enemyName: L("GIMBAL KNOT", "NUDO GIMBAL", "ジンバルノット"),
  beats: [
    say(L(
      "A Matrix4 packs move, turn and scale into 16 numbers. Multiplying matrices chains transforms, and ORDER matters.",
      "Una Matrix4 guarda mover, girar y escalar en 16 números. Multiplicar matrices encadena transformaciones, y el ORDEN importa.",
      "Matrix4 は移動・回転・拡大を16個の数にまとめる。行列の掛け算で変形をつなぐ。順番が大事だよ。",
    )),
    {
      kind: "act",
      prompt: L("Apply two spells to the point x = 1", "Aplica dos hechizos al punto x = 1", "点 x = 1 に2つの呪文をかけよう"),
      steps: [
        { label: L("SCALE x2", "ESCALA x2", "2倍"), line: "const S = new THREE.Matrix4().makeScale(2, 2, 2);", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "S" }] },
        { label: L("MOVE +10", "MOVER +10", "+10 移動"), line: "const T = new THREE.Matrix4().makeTranslation(10, 0, 0);", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "key", holder: "ally" }, { t: "tag", actor: "ally", text: "T" }] },
        { label: L("T × S", "T × S", "T × S"), line: "// scale first, then move: 1 → 2 → 12", effects: [{ t: "print", text: "12" }, { t: "say", actor: "hero", text: L("S acts first!", "¡S actúa primero!", "S が先！") }], output: "12" },
        { label: L("S × T", "S × T", "S × T"), line: "// move first, then scale: 1 → 11 → 22", effects: [{ t: "print", text: "22" }, { t: "shake" }, { t: "banner", text: L("ORDER MATTERS", "EL ORDEN IMPORTA", "順番が大事") }], output: "22" },
      ],
    },
    say(L(
      "In a × b, b touches the point FIRST. a.multiply(b) means a × b; a.premultiply(b) means b × a.",
      "En a × b, b toca el punto PRIMERO. a.multiply(b) es a × b; a.premultiply(b) es b × a.",
      "a × b では b が先に点に効く。a.multiply(b) は a × b、a.premultiply(b) は b × a だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const T = new THREE.Matrix4().makeTranslation(10, 0, 0);\nconst S = new THREE.Matrix4().makeScale(2, 2, 2);\nconst p = (m: THREE.Matrix4) => new THREE.Vector3(1, 0, 0).applyMatrix4(m).x;\nconsole.log(p(T.clone().multiply(S)), p(T.clone().premultiply(S)));",
      options: ["12 22", "22 12", "12 12"],
      answer: 0,
      output: "12 22",
      check: { compiles: true, stdout: "12 22" },
      explain: L("T × S scales then moves: 12. S × T moves then scales: (1 + 10) × 2 = 22.", "T × S escala y luego mueve: 12. S × T mueve y luego escala: (1 + 10) × 2 = 22.", "T × S は拡大→移動で12。S × T は移動→拡大で (1 + 10) × 2 = 22。"),
      win: [{ t: "print", text: "12 22" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const m = new THREE.Matrix4().set(\n  1, 2, 3, 4,\n  5, 6, 7, 8,\n  9, 10, 11, 12,\n  13, 14, 15, 16,\n);\nconsole.log(m.elements.slice(0, 4).join(\",\"));",
      options: ["1,5,9,13", "1,2,3,4", "13,14,15,16"],
      answer: 0,
      output: "1,5,9,13",
      check: { compiles: true, stdout: "1,5,9,13" },
      explain: L("set() reads row by row, but elements is stored COLUMN by column. The first column is 1, 5, 9, 13.", "set() se lee fila por fila, pero elements se guarda COLUMNA por columna. La primera columna es 1, 5, 9, 13.", "set() は行ごとに書くけど、elements は列ごとに保存される。1列目は 1, 5, 9, 13。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const m = new THREE.Matrix4().makeTranslation(5, 0, 0);\nconsole.log(m.elements[12], new THREE.Matrix4().makeScale(2, 3, 4).determinant());",
      options: ["5 24", "0 9", "5 9"],
      answer: 0,
      output: "5 24",
      check: { compiles: true, stdout: "5 24" },
      explain: L("Translation lives in slots 12, 13, 14. A scale matrix's determinant is the volume factor: 2 × 3 × 4.", "La traslación vive en las casillas 12, 13 y 14. El determinante de una escala es el factor de volumen: 2 × 3 × 4.", "移動は12・13・14番に入る。拡大行列の行列式は体積の倍率で 2×3×4。"),
    },
    say(L(
      "rotation is an Euler: three angles applied in an order, \"XYZ\" by default. When two rings line up, you lose an axis: GIMBAL LOCK.",
      "rotation es un Euler: tres ángulos en un orden, \"XYZ\" por defecto. Si dos anillos se alinean, pierdes un eje: GIMBAL LOCK.",
      "rotation は Euler で、3つの角度を順番に適用（初期は \"XYZ\"）。2つの輪が重なると軸が1つ消える。ジンバルロックだ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'console.log(new THREE.Euler().order, new THREE.Euler(0, 0, 0, "YXZ").order);',
      options: ["XYZ YXZ", "XYZ XYZ", "ZYX YXZ"],
      answer: 0,
      output: "XYZ YXZ",
      check: { compiles: true, stdout: "XYZ YXZ" },
      explain: L("The default order is XYZ. Cameras often use YXZ: turn left-right first, then look up-down.", "El orden por defecto es XYZ. Las cámaras suelen usar YXZ: girar a los lados y luego mirar arriba o abajo.", "初期の順番は XYZ。カメラはよく YXZ を使う。左右を向いてから上下を見るんだ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: IMP + 'const e = new THREE.Euler(0, 0, 0, "ABC");',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2345: the order must be an EulerOrder such as \"XYZ\" or \"YXZ\". tsc knows all six.", "TS2345: el orden debe ser un EulerOrder como \"XYZ\" o \"YXZ\". tsc conoce los seis.", "TS2345：順番は \"XYZ\" や \"YXZ\" などの EulerOrder だけ。tsc は6通り全部知っている。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "predict",
      prompt: L("Which describes gimbal lock?", "¿Qué describe el gimbal lock?", "ジンバルロックの説明は？"),
      code: IMP + "const o = new THREE.Object3D();\no.rotation.set(0, Math.PI / 2, 0);\n// now X and Z turn around the same line",
      options: [L("Two axes align: one is lost", "Dos ejes se alinean: se pierde uno", "2軸が重なり1つ失う"), L("A WebGL error", "Un error de WebGL", "WebGL のエラー")],
      answer: 0,
      explain: L("With Y at 90°, X and Z spin the same way. Quaternions avoid this: one turn, no rings.", "Con Y a 90°, X y Z giran igual. Los cuaterniones lo evitan: un giro, sin anillos.", "Y が90°だと X と Z が同じ回り方になる。クォータニオンなら輪がないので起きない。"),
      win: [{ t: "banner", text: L("GIMBAL LOCK", "GIMBAL LOCK", "ジンバルロック") }],
    },
    say(L(
      "A Quaternion stores a turn as x, y, z, w (no turn: w = 1). object.rotation and object.quaternion always stay in sync.",
      "Un Quaternion guarda un giro como x, y, z, w (sin giro: w = 1). object.rotation y object.quaternion siempre van sincronizados.",
      "クォータニオンは回転を x・y・z・w で持つ（回転なしは w = 1）。rotation と quaternion は常に連動するよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const o = new THREE.Object3D();\no.rotation.y = Math.PI / 2;\nconsole.log(o.quaternion.y.toFixed(3), o.quaternion.w.toFixed(3));",
      options: ["0.707 0.707", "1.571 0.000", "0.000 1.000"],
      answer: 0,
      output: "0.707 0.707",
      check: { compiles: true, stdout: "0.707 0.707" },
      explain: L("Setting rotation updates quaternion too. A 90° turn holds sin 45° and cos 45° ≈ 0.707.", "Cambiar rotation también actualiza quaternion. Un giro de 90° guarda sen 45° y cos 45° ≈ 0.707.", "rotation を変えると quaternion も更新。90°回転は sin 45° と cos 45° ≈ 0.707。"),
    },
    {
      kind: "type",
      prompt: L("Turn halfway, smoothly", "Gira a mitad de camino, suave", "なめらかに半分回そう"),
      code: IMP + "const a = new THREE.Quaternion();\nconst b = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 0, 1), Math.PI / 2);\nconst h = a.clone().___(b, 0.5);\nconsole.log((2 * Math.acos(h.w) * 180 / Math.PI).toFixed(1));",
      answer: "slerp",
      check: { compiles: true, stdout: "45.0" },
      explain: L("slerp blends two turns along the shortest arc. Halfway from 0° to 90° is 45°.", "slerp mezcla dos giros por el arco más corto. A mitad de 0° a 90° hay 45°.", "slerp は2つの回転を最短の弧でつなぐ。0°と90°の真ん中は45°。"),
      win: [{ t: "print", text: "45.0" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const m = new THREE.Matrix4().compose(\n  new THREE.Vector3(1, 2, 3), new THREE.Quaternion(), new THREE.Vector3(2, 2, 2),\n);\nconst p = new THREE.Vector3(), q = new THREE.Quaternion(), s = new THREE.Vector3();\nm.decompose(p, q, s);\nconsole.log(p.toArray().join(\",\"), s.toArray().join(\",\"));",
      options: ["1,2,3 2,2,2", "2,4,6 2,2,2", "1,2,3 1,1,1"],
      answer: 0,
      output: "1,2,3 2,2,2",
      check: { compiles: true, stdout: "1,2,3 2,2,2" },
      explain: L("compose packs position, quaternion and scale into a matrix; decompose unpacks them again.", "compose empaca posición, cuaternión y escala en una matriz; decompose los desempaca.", "compose で位置・回転・拡大を行列に詰め、decompose で取り出せるよ。"),
    },
    {
      kind: "run",
      prompt: L("Scale first, then move: it must print x: 12", "Escala primero, luego mueve: debe imprimir x: 12", "拡大してから移動：x: 12 と表示"),
      starter: IMP + "const T = new THREE.Matrix4().makeTranslation(10, 0, 0);\nconst S = new THREE.Matrix4().makeScale(2, 2, 2);\nconst M = S.clone().multiply(T);\nconsole.log(\"x: \" + new THREE.Vector3(1, 0, 0).applyMatrix4(M).x);\n",
      solution: IMP + "const T = new THREE.Matrix4().makeTranslation(10, 0, 0);\nconst S = new THREE.Matrix4().makeScale(2, 2, 2);\nconst M = T.clone().multiply(S);\nconsole.log(\"x: \" + new THREE.Vector3(1, 0, 0).applyMatrix4(M).x);\n",
      expect: "x: 12",
      fallback: [String.raw`T\.clone\(\)\.multiply\(\s*S\s*\)`, String.raw`S\.clone\(\)\.premultiply\(\s*T\s*\)`, String.raw`multiplyMatrices\(\s*T\s*,\s*S\s*\)`],
      explain: L("The matrix on the right acts first. To scale first, S goes on the right: T × S.", "La matriz de la derecha actúa primero. Para escalar primero, S va a la derecha: T × S.", "右の行列が先に効く。先に拡大するなら S を右に置いて T × S。"),
    },
  ],
};

// ─── 2.4 Boss: Graph Wraith ────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "graph-wraith",
  title: L("Boss: Graph Wraith", "Jefe: Espectro del Grafo", "ボス：グラフレイス"),
  concept: "scene_graph",
  mode: "boss",
  xp: 180,
  enemy: "ghost",
  enemyName: L("GRAPH WRAITH", "ESPECTRO DEL GRAFO", "グラフレイス"),
  beats: [
    enemySays(L(
      "Ooooh... in my forest, local and world blur together, arrows are shared and every turn tangles. Find your way out!",
      "Uuuuh... en mi bosque lo local y el mundo se mezclan, las flechas se comparten y cada giro se enreda. ¡Encuentra la salida!",
      "おおお…この森ではローカルもワールドも混ざり、矢は共有され、回転はからまる。出口を探してみろ！",
    )),
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "const parent = new THREE.Group();\nparent.position.x = 5;\nconst child = new THREE.Object3D();\nchild.position.x = 2;\nparent.add(child);\nconsole.log(child.getWorldPosition(new THREE.Vector3()).x);", options: ["7", "2", "5"], answer: 0, output: "7", check: { compiles: true, stdout: "7" }, explain: L("World = parent's 5 + local 2.", "Mundo = el 5 del padre + el 2 local.", "ワールド＝親の5＋ローカル2。") },
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "const v = new THREE.Vector3(2, 0, 0);\nconst w = v;\nw.multiplyScalar(3);\nconsole.log(v.x);", options: ["6", "2", "3"], answer: 0, output: "6", check: { compiles: true, stdout: "6" }, explain: L("w and v are the same Vector3, and multiplyScalar mutates it.", "w y v son el mismo Vector3, y multiplyScalar lo modifica.", "w と v は同じ Vector3。multiplyScalar はそれを書きかえる。") },
    { kind: "predict", time: 15, prompt: L("a.multiply(b) on a point: which acts first?", "a.multiply(b) sobre un punto: ¿cuál primero?", "a.multiply(b) を点に：先に効くのは？"), code: IMP + "const a = new THREE.Matrix4().makeTranslation(1, 0, 0);\nconst b = new THREE.Matrix4().makeScale(3, 3, 3);\na.multiply(b);", options: [L("b first, then a", "b primero, luego a", "b が先、次に a"), L("a first, then b", "a primero, luego b", "a が先、次に b")], answer: 0, explain: L("a.multiply(b) is a × b: the right-hand matrix touches the point first.", "a.multiply(b) es a × b: la matriz de la derecha toca el punto primero.", "a.multiply(b) は a × b。右の行列が先に点に効く。") },
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "const q = new THREE.Quaternion();\nconsole.log(q.w, q.length());", options: ["1 1", "0 0", "0 1"], answer: 0, output: "1 1", check: { compiles: true, stdout: "1 1" }, explain: L("The identity quaternion (no turn) is (0, 0, 0, 1), and its length is 1.", "El cuaternión identidad (sin giro) es (0, 0, 0, 1), y su longitud es 1.", "回転なしのクォータニオンは (0, 0, 0, 1)。長さは1。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const g = new THREE.Group();\nconst c = new THREE.Object3D();\nc.position.set(5, 0, 0);\ng.position.set(10, 0, 0);\ng.updateMatrixWorld();\ng.attach(c);\nconsole.log(c.position.x);", options: ["-5", "5", "15"], answer: 0, output: "-5", check: { compiles: true, stdout: "-5" }, explain: L("attach keeps world x 5, so relative to a parent at 10 the local x is -5.", "attach conserva x 5 en el mundo; respecto a un padre en 10, la x local es -5.", "attach はワールド x 5 を保つ。親が10なのでローカルは -5。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const v = new THREE.Vector3(1, 0, 0).applyAxisAngle(new THREE.Vector3(0, 0, 1), Math.PI / 2);\nconsole.log(v.y.toFixed(3));", options: ["1.000", "0.000", "-1.000"], answer: 0, output: "1.000", check: { compiles: true, stdout: "1.000" }, explain: L("A quarter turn around Z swings +X up to +Y.", "Un cuarto de vuelta en Z lleva +X hasta +Y.", "Z 軸で4分の1回転すると +X は +Y へ。") },
    { kind: "pick", time: 12, prompt: L("Smoothly blend two orientations", "Mezcla suave dos orientaciones", "2つの向きをなめらかにつなぐ"), code: IMP + "const from = new THREE.Quaternion();\nconst to = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), Math.PI);\nconst mid = from.clone().___(to, 0.5);\nconsole.log(mid.w.toFixed(3));", options: ["slerp", "multiply"], answer: 0, check: { compiles: true, stdout: "0.707" }, explain: L("slerp follows the shortest arc. Lerping Euler angles one by one can wobble or lock.", "slerp sigue el arco más corto. Interpolar ángulos Euler uno a uno puede tambalear o bloquearse.", "slerp は最短の弧をたどる。Euler 角を別々に補間するとぶれたりロックしたりする。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + 'const root = new THREE.Group(); root.name = "root";\nconst a = new THREE.Object3D(); a.name = "a";\nconst b = new THREE.Object3D(); b.name = "b";\nconst c = new THREE.Object3D(); c.name = "c";\nroot.add(a, b);\nb.add(c);\nb.visible = false;\nconst names: string[] = [];\nroot.traverseVisible((o) => { names.push(o.name); });\nconsole.log(names.join(","));', options: ["root,a", "root,a,b,c", "root,a,c"], answer: 0, output: "root,a", check: { compiles: true, stdout: "root,a" }, explain: L("traverseVisible skips a hidden object AND its whole subtree.", "traverseVisible salta un objeto oculto Y todo su subárbol.", "traverseVisible は隠れた物体とその子孫を全部とばす。") },
    { kind: "type", time: 15, prompt: L("Combine T and S into M = T × S", "Combina T y S en M = T × S", "T と S から M = T × S を作ろう"), code: IMP + "const T = new THREE.Matrix4().makeTranslation(10, 0, 0);\nconst S = new THREE.Matrix4().makeScale(2, 2, 2);\nconst M = new THREE.Matrix4().___(T, S);\nconsole.log(new THREE.Vector3(1, 0, 0).applyMatrix4(M).x);", answer: "multiplyMatrices", check: { compiles: true, stdout: "12" }, explain: L("multiplyMatrices(a, b) stores a × b. S acts first: 1 → 2 → 12.", "multiplyMatrices(a, b) guarda a × b. S actúa primero: 1 → 2 → 12.", "multiplyMatrices(a, b) は a × b。S が先に効いて 1 → 2 → 12。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const a = new THREE.Vector3(0, 1, 0);\nconst b = new THREE.Vector3(1, 0, 0);\nconst c = a.clone().cross(b);\nconsole.log(a.dot(b), c.z);", options: ["0 -1", "0 1", "1 0"], answer: 0, output: "0 -1", check: { compiles: true, stdout: "0 -1" }, explain: L("Perpendicular, so dot is 0. Y × X is -Z: cross order matters.", "Perpendiculares: dot es 0. Y × X es -Z: el orden en cross importa.", "直角なので dot は0。Y × X は -Z。cross は順番が大事。") },
    enemySays(L(
      "Nooo... you kept every child in its place and every turn untangled. The Loop Tower ticks above. Mind the clock!",
      "Nooo... mantuviste a cada hijo en su lugar y cada giro sin enredos. La Torre del Bucle late arriba. ¡Cuidado con el reloj!",
      "うおお…子はみな元の場所、回転もからまない。上ではループの塔が時を刻む。時間に気をつけろ！",
    )),
  ],
};

export const graphForest: RegionDef = {
  slug: "graph-forest",
  name: L("Graph Forest", "Bosque del Grafo", "グラフの森"),
  subtitle: L("Scene graph · vectors · rotations", "Grafo de escena · vectores · giros", "シーングラフ・ベクトル・回転"),
  theme: "forest",
  lessons: [sceneGraph, vectors, rotations, boss],
};
