import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 3 · LOOP TOWER  (render loop and delta time, raycasting, assets/colour/lights/shadows, disposal and performance)
// Snippets run three r186 without a GPU: math, scene graph, Raycaster, Timer and InstancedMesh run for real;
// WebGLRenderer, GLTFLoader and requestAnimationFrame only appear in act lines or type-check-only claims.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });
const code = (...lines: string[]) => ["import * as THREE from \"three\";", ...lines].join("\n");

const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const YES = L("Yes", "Sí", "はい");
const NO = L("No", "No", "いいえ");

// ─── 3.1 The heartbeat: render loop and delta time ─────────────────────────
const renderLoop: LessonDef = {
  slug: "render-loop",
  title: L("The heartbeat", "El latido", "心臓のビート"),
  concept: "render loop",
  mode: "lesson",
  xp: 80,
  enemy: "slime",
  enemyName: L("SPEED SLIME", "SLIME VELOZ", "スピードスライム"),
  beats: [
    say(L(
      "Welcome to Loop Tower! To animate, three.js redraws the scene many times a second. Each redraw is a FRAME.",
      "¡Bienvenido a la Torre del Bucle! Para animar, three.js redibuja la escena muchas veces por segundo. Cada dibujo es un FRAME.",
      "ループの塔へようこそ！アニメーションは、シーンを1秒に何度も描き直すこと。1回の描画をフレームと呼ぶよ。",
    )),
    {
      kind: "act",
      prompt: L("Build the heartbeat of the scene", "Arma el latido de la escena", "シーンの心臓を作ろう"),
      steps: [
        { label: L("NEW TIMER", "NUEVO TIMER", "タイマー"), line: "const timer = new THREE.Timer();", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "timer" }] },
        { label: L("LOOP", "BUCLE", "ループ"), line: "function loop(time: number) {" },
        { label: L("BOOK NEXT", "PEDIR OTRO", "次を予約"), line: "  requestAnimationFrame(loop);", effects: [{ t: "say", actor: "hero", text: L("Again next frame!", "¡Otra vez!", "次のフレームも！") }] },
        { label: L("TICK", "TIC", "時を刻む"), line: "  timer.update(time);", effects: [{ t: "value", actor: "hero", text: "dt=0.016" }] },
        { label: L("SPIN", "GIRAR", "回す"), line: "  cube.rotation.y += timer.getDelta();", effects: [{ t: "attack", from: "hero", to: "enemy" }] },
        { label: L("PAINT", "PINTAR", "描く"), line: "  renderer.render(scene, camera);\n}" },
        { label: L("START", "EMPEZAR", "スタート"), line: "requestAnimationFrame(loop);", effects: [{ t: "banner", text: L("60 FPS!", "¡60 FPS!", "60 FPS！") }] },
      ],
    },
    say(L(
      "requestAnimationFrame calls you once per screen refresh: 60 times a second on one screen, 120 or 144 on others.",
      "requestAnimationFrame te llama una vez por refresco de pantalla: 60 veces por segundo en una, 120 o 144 en otras.",
      "requestAnimationFrame は画面の更新ごとに1回呼ぶ。1秒に60回の画面もあれば、120回や144回の画面もある。",
    )),
    {
      kind: "predict",
      prompt: L("Units per second at 60 and 120 fps?", "¿Unidades por segundo a 60 y 120 fps?", "60fps と 120fps で1秒に何進む？"),
      code: "const perFrame = 0.1; // x += 0.1 every frame\nconsole.log(perFrame * 60, perFrame * 120);",
      options: ["6 12", "6 6", "12 6"],
      answer: 0,
      output: "6 12",
      check: { compiles: true, stdout: "6 12" },
      explain: L("A fixed step per frame runs twice as fast on a 120 Hz screen. Speed must not depend on fps.", "Un paso fijo por frame va el doble de rápido en una pantalla de 120 Hz. La velocidad no debe depender de los fps.", "フレームごとに固定で進めると、120Hz の画面では2倍速になる。速さが fps に左右されてはダメ。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "say", actor: "enemy", text: L("Double speed!", "¡Doble velocidad!", "2倍速だ！") }, { t: "shake" }],
    },
    say(L(
      "The fix: DELTA TIME. Move speed × dt, where dt is the seconds since the last frame. Same distance per second on every screen.",
      "La solución: DELTA TIME. Mueve velocidad × dt, con dt = segundos desde el último frame. Igual distancia por segundo en toda pantalla.",
      "解決策はデルタタイム。速さ × dt だけ動かそう。dt は前のフレームからの秒数。どの画面でも1秒の移動量が同じになる。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: "const speed = 4; // units per second\nconst dt = 0.25; // seconds since last frame\nconsole.log(speed * dt);",
      options: ["1", "4", "16"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("4 units per second for a quarter of a second is 1 unit.", "4 unidades por segundo durante un cuarto de segundo es 1 unidad.", "1秒に4進む速さで0.25秒なら、進むのは1だよ。"),
      win: [{ t: "print", text: "1" }],
    },
    say(L(
      "THREE.Timer measures dt for you: call update() once per frame, then getDelta() returns seconds. (THREE.Clock is deprecated.)",
      "THREE.Timer mide dt por ti: llama a update() una vez por frame y getDelta() da los segundos. (THREE.Clock está obsoleto.)",
      "THREE.Timer が dt を測ってくれる。毎フレーム1回 update() を呼べば、getDelta() が秒数を返すよ（Clock は非推奨）。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const timer = new THREE.Timer();", "timer.update(1000); // time in ms", "timer.update(1016);", "console.log(timer.getDelta(), timer.getDelta());"),
      options: ["0.016 0.016", "16 16", "0.016 0"],
      answer: 0,
      output: "0.016 0.016",
      check: { compiles: true, stdout: "0.016 0.016" },
      explain: L("update() takes milliseconds; getDelta() gives seconds and stays the same until the next update().", "update() recibe milisegundos; getDelta() da segundos y no cambia hasta el próximo update().", "update() はミリ秒を受け取り、getDelta() は秒を返す。次の update() までは同じ値だよ。"),
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "timer" }],
      win: [{ t: "value", actor: "hero", text: "dt=0.016" }],
    },
    {
      kind: "type",
      prompt: L("Tick the timer for this frame", "Haz avanzar el timer en este frame", "このフレームのタイマーを進めよう"),
      code: code("const timer = new THREE.Timer();", "timer.update(0);", "timer.___(250);", "console.log(timer.getDelta());"),
      answer: "update",
      check: { compiles: true, stdout: "0.25" },
      explain: L("update(time) records the new frame; 250 ms later, getDelta() is 0.25 s.", "update(time) registra el nuevo frame; 250 ms después, getDelta() da 0.25 s.", "update(time) で新しいフレームを記録。250ms 後なので getDelta() は 0.25 秒だよ。"),
      win: [{ t: "print", text: "0.25" }],
    },
    say(L(
      "A hidden tab pauses the loop. Back again, dt can be seconds long and objects teleport. Clamp it: Math.min(dt, 0.1).",
      "Una pestaña oculta pausa el bucle. Al volver, dt puede durar segundos y los objetos se teletransportan. Limítalo: Math.min(dt, 0.1).",
      "隠れたタブではループが止まる。戻ると dt が数秒になり、物体がワープする。Math.min(dt, 0.1) でおさえよう。",
    )),
    {
      kind: "predict",
      prompt: L("Tab hidden for 2.5 s. How far?", "Pestaña oculta 2.5 s. ¿Cuánto avanza?", "2.5秒タブを隠した。どれだけ進む？"),
      code: "const speed = 10;\nconst dt = Math.min(2.5, 0.1);\nconsole.log(speed * dt);",
      options: ["1", "25", "10"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("Math.min caps dt at 0.1 s, so the jump is 1 unit instead of 25.", "Math.min limita dt a 0.1 s, así que el salto es 1 unidad y no 25.", "Math.min で dt を 0.1秒に制限。だから25ではなく1だけ進むよ。"),
      win: [{ t: "say", actor: "hero", text: L("No teleport!", "¡Sin teletransporte!", "ワープなし！") }],
    },
    {
      kind: "order",
      prompt: L("Order one frame of the loop", "Ordena un frame del bucle", "1フレームの処理を並べよう"),
      lines: ["timer.update(time);", "const dt = timer.getDelta();", "cube.rotation.y += 2 * dt;", "renderer.render(scene, camera);"],
      check: {
        compiles: true,
        program: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene, camera: THREE.Camera, cube: THREE.Mesh;", "const timer = new THREE.Timer();", "function loop(time: number) {", "  timer.update(time);", "  const dt = timer.getDelta();", "  cube.rotation.y += 2 * dt;", "  renderer.render(scene, camera);", "}"),
      },
      explain: L("Tick the clock, read dt, move things, then paint the frame.", "Avanza el reloj, lee dt, mueve las cosas y luego pinta el frame.", "時計を進め、dt を読み、物を動かしてから描くよ。"),
    },
    {
      kind: "run",
      prompt: L("Make it fps-independent: 5 units in 1 s", "Hazlo independiente de fps: 5 unidades en 1 s", "fps に左右されず1秒で5進ませよう"),
      starter: code(
        "const SPEED = 5; // units per second",
        "function simulate(fps: number, seconds: number): number {",
        "  const dt = 1 / fps;",
        "  let x = 0;",
        "  for (let i = 0; i < fps * seconds; i++) x += SPEED;",
        "  return x;",
        "}",
        "console.log(`30fps=${simulate(30, 1).toFixed(2)} 60fps=${simulate(60, 1).toFixed(2)}`);",
      ) + "\n",
      solution: code(
        "const SPEED = 5; // units per second",
        "function simulate(fps: number, seconds: number): number {",
        "  const dt = 1 / fps;",
        "  let x = 0;",
        "  for (let i = 0; i < fps * seconds; i++) x += SPEED * dt;",
        "  return x;",
        "}",
        "console.log(`30fps=${simulate(30, 1).toFixed(2)} 60fps=${simulate(60, 1).toFixed(2)}`);",
      ) + "\n",
      expect: "30fps=5.00 60fps=5.00",
      fallback: [String.raw`x\s*\+=\s*SPEED\s*\*\s*dt`, String.raw`x\s*\+=\s*dt\s*\*\s*SPEED`, String.raw`x\s*\+=\s*SPEED\s*\/\s*fps`],
      explain: L("Multiply by dt: each frame moves SPEED × dt, so one second adds up to 5 at any fps.", "Multiplica por dt: cada frame mueve SPEED × dt, así un segundo suma 5 a cualquier fps.", "dt を掛けよう。毎フレーム SPEED × dt 進めば、どの fps でも1秒で5になる。"),
    },
  ],
};

// ─── 3.2 The pointing wand: raycasting ─────────────────────────────────────
const raycasting: LessonDef = {
  slug: "raycasting",
  title: L("The pointing wand", "La varita que apunta", "指さしの杖"),
  concept: "raycasting",
  mode: "lesson",
  xp: 85,
  enemy: "threejs/lost-wanderer",
  enemyName: L("LOST WANDERER", "ERRANTE PERDIDO", "まいごの旅人"),
  beats: [
    say(L(
      "To click a 3D object, shoot a RAY from the camera through the pointer. A Raycaster lists every mesh the ray touches.",
      "Para hacer clic en un objeto 3D, lanza un RAYO desde la cámara a través del puntero. Un Raycaster lista cada malla que toca.",
      "3Dの物体をクリックするには、カメラからポインターを通る光線を撃つ。Raycaster が当たったメッシュを全部教えてくれる。",
    )),
    say(L(
      "First, turn pixels into NDC: x goes -1 (left) to +1 (right), y goes -1 (bottom) to +1 (top). Screen y grows DOWN, so flip it.",
      "Pasa píxeles a NDC: x va de -1 (izquierda) a +1 (derecha), y de -1 (abajo) a +1 (arriba). La y de pantalla crece hacia ABAJO: inviértela.",
      "まずピクセルを NDC に変換。x は左-1〜右+1、y は下-1〜上+1。画面の y は下向きに増えるから反転しよう。",
    )),
    {
      kind: "act",
      prompt: L("Point the wand and pick a target", "Apunta la varita y elige un blanco", "杖を向けて的を選ぼう"),
      steps: [
        { label: L("TO NDC", "A NDC", "NDC へ"), line: "const ndc = new THREE.Vector2((px / w) * 2 - 1, -(py / h) * 2 + 1);", effects: [{ t: "item", kind: "sword", holder: "hero" }, { t: "tag", actor: "hero", text: "ndc", value: "0,0" }] },
        { label: L("AIM", "APUNTAR", "ねらう"), line: "raycaster.setFromCamera(ndc, camera);", effects: [{ t: "say", actor: "hero", text: L("Aim from the eye", "Desde el ojo", "カメラからねらう") }] },
        { label: L("CAST", "LANZAR", "撃つ"), line: "const hits = raycaster.intersectObjects(scene.children);", effects: [{ t: "attack", from: "hero", to: "enemy" }] },
        { label: L("NEAREST", "EL MÁS CERCA", "いちばん近い"), line: "if (hits.length > 0) console.log(hits[0].object.name);", effects: [{ t: "say", actor: "enemy", text: L("Picked!", "¡Elegido!", "選ばれた！") }, { t: "print", text: "wanderer" }], output: "wanderer" },
      ],
    },
    {
      kind: "predict",
      prompt: L("Pixels to NDC on an 800×600 canvas", "Píxeles a NDC en un lienzo de 800×600", "800×600 のキャンバスで NDC は？"),
      code: "const ndc = (px: number, py: number) =>\n  [(px / 800) * 2 - 1, -(py / 600) * 2 + 1];\nconsole.log(ndc(400, 300).join(\",\"), ndc(0, 0).join(\",\"));",
      options: ["0,0 -1,1", "0,0 -1,-1", "400,300 0,0"],
      answer: 0,
      output: "0,0 -1,1",
      check: { compiles: true, stdout: "0,0 -1,1" },
      explain: L("The centre is (0, 0). The top-left pixel is x = -1 and, after the flip, y = +1.", "El centro es (0, 0). El píxel de arriba a la izquierda es x = -1 y, tras invertir, y = +1.", "中心は (0, 0)。左上のピクセルは x = -1、反転したので y = +1 だよ。"),
      win: [{ t: "print", text: "0,0 -1,1" }],
    },
    {
      kind: "pick",
      prompt: L("Pointer at the top edge: NDC y is…", "Puntero en el borde superior: y en NDC es…", "上端のポインター：NDC の y は？"),
      code: "const toY = (py: number, h: number) => -(py / h) * 2 + 1;\nconsole.log(toY(0, 600) === ___);",
      options: ["1", "-1", "0"],
      answer: 0,
      check: { compiles: true, stdout: "true" },
      explain: L("In NDC, up is positive: the top edge is +1 and the bottom edge is -1.", "En NDC, arriba es positivo: el borde superior es +1 y el inferior -1.", "NDC では上がプラス。上端は +1、下端は -1 だよ。"),
    },
    say(L(
      "Hits come sorted NEAREST first. Each hit has distance, point and object, so hits[0] is what the player clicked.",
      "Los impactos llegan ordenados del MÁS CERCANO al más lejano. Cada uno tiene distance, point y object: hits[0] es lo que se clicó.",
      "当たりは近い順に並ぶ。それぞれ distance・point・object を持つから、hits[0] がクリックされた物だよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "const scene = new THREE.Scene();",
        "for (const [name, z] of [[\"far\", -5], [\"near\", 0]] as const) {",
        "  const box = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());",
        "  box.name = name; box.position.z = z; scene.add(box);",
        "}",
        "scene.updateMatrixWorld();",
        "const rc = new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, 10), new THREE.Vector3(0, 0, -1));",
        "console.log(rc.intersectObjects(scene.children).map((h) => h.object.name).join(\",\"));",
      ),
      options: ["near,far", "far,near", "near"],
      answer: 0,
      output: "near,far",
      check: { compiles: true, stdout: "near,far" },
      explain: L("The ray goes through both boxes. Results are sorted by distance, not by the order they were added.", "El rayo atraviesa ambas cajas. Los resultados se ordenan por distancia, no por orden de llegada.", "光線は両方の箱を通る。結果は追加した順ではなく、距離の順に並ぶよ。"),
      win: [{ t: "print", text: "near,far" }],
    },
    {
      kind: "predict",
      prompt: L("The default ray length?", "¿El largo del rayo por defecto?", "光線の長さの初期値は？"),
      code: code("const rc = new THREE.Raycaster();", "console.log(rc.near, rc.far);"),
      options: ["0 Infinity", "0.1 2000", "0 100"],
      answer: 0,
      output: "0 Infinity",
      check: { compiles: true, stdout: "0 Infinity" },
      explain: L("near and far limit where hits count. By default the ray starts at 0 and never ends.", "near y far limitan dónde cuentan los impactos. Por defecto el rayo empieza en 0 y no termina.", "near と far は当たりを数える範囲。初期値では 0 から始まり、終わりがないよ。"),
    },
    say(L(
      "intersectObjects also checks children inside groups, because recursive is true by default. Pass false for the top level only.",
      "intersectObjects también revisa los hijos dentro de grupos, porque recursive es true por defecto. Pasa false para solo el primer nivel.",
      "intersectObjects はグループの中の子も調べる。recursive の初期値が true だからね。false なら一番上だけ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code(
        "const group = new THREE.Group();",
        "group.add(new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial()));",
        "const scene = new THREE.Scene();",
        "scene.add(group);",
        "scene.updateMatrixWorld();",
        "const rc = new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, 10), new THREE.Vector3(0, 0, -1));",
        "console.log(rc.intersectObjects(scene.children).length, rc.intersectObjects(scene.children, false).length);",
      ),
      options: ["1 0", "1 1", "0 0"],
      answer: 0,
      output: "1 0",
      check: { compiles: true, stdout: "1 0" },
      explain: L("A Group has no geometry. With recursive = false the ray never looks inside it.", "Un Group no tiene geometría. Con recursive = false el rayo nunca mira adentro.", "Group には形がない。recursive = false だと中を見ないよ。"),
    },
    say(L(
      "The ray reads each mesh's matrixWorld. Move a mesh but skip the update, and the ray still hits it at its OLD place.",
      "El rayo lee el matrixWorld de cada malla. Si mueves una malla sin actualizarla, el rayo la sigue tocando en su lugar VIEJO.",
      "光線は各メッシュの matrixWorld を読む。動かしても更新しないと、光線は古い場所に当たり続ける。",
    )),
    {
      kind: "predict",
      prompt: L("Hits before and after the update?", "¿Impactos antes y después de actualizar?", "更新の前と後の当たり数は？"),
      code: code(
        "const box = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());",
        "box.position.x = 3; // moved away from the ray",
        "const rc = new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, 10), new THREE.Vector3(0, 0, -1));",
        "const before = rc.intersectObject(box).length;",
        "box.updateMatrixWorld();",
        "console.log(before, rc.intersectObject(box).length);",
      ),
      options: ["1 0", "0 0", "0 1"],
      answer: 0,
      output: "1 0",
      check: { compiles: true, stdout: "1 0" },
      explain: L("Before updateMatrixWorld the box still sits at x = 0 for the ray. The renderer updates it each frame.", "Antes de updateMatrixWorld, para el rayo la caja sigue en x = 0. El renderer la actualiza en cada frame.", "updateMatrixWorld の前は、光線にとって箱はまだ x = 0。レンダラーは毎フレーム更新するよ。"),
      setup: [{ t: "enter", actor: "enemy" }, { t: "tag", actor: "enemy", text: "box", value: "x=3" }],
      win: [{ t: "say", actor: "enemy", text: L("I was a ghost!", "¡Era un fantasma!", "残像だった！") }],
    },
    {
      kind: "predict",
      prompt: L("Ray from behind a plane, then DoubleSide", "Rayo desde atrás del plano, luego DoubleSide", "板の裏から撃つ。次に DoubleSide"),
      code: code(
        "const plane = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), new THREE.MeshBasicMaterial());",
        "const rc = new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, -10), new THREE.Vector3(0, 0, 1));",
        "const a = rc.intersectObject(plane).length;",
        "plane.material.side = THREE.DoubleSide;",
        "console.log(a, rc.intersectObject(plane).length);",
      ),
      options: ["0 1", "1 1", "0 0"],
      answer: 0,
      output: "0 1",
      check: { compiles: true, stdout: "0 1" },
      explain: L("Raycasting respects material.side: a FrontSide plane is invisible from behind, to rays too.", "El raycasting respeta material.side: un plano FrontSide es invisible desde atrás, también para los rayos.", "レイキャストは material.side に従う。FrontSide の板は裏からだと光線にも見えないよ。"),
    },
    {
      kind: "run",
      prompt: L("The wand picks the trap. Make it hit the gem", "La varita elige la trampa. Haz que toque la gema", "杖が罠を選んでしまう。宝石に当てよう"),
      starter: code(
        "const camera = new THREE.PerspectiveCamera(50, 800 / 600, 0.1, 100);",
        "camera.position.z = 5; camera.updateMatrixWorld();",
        "const scene = new THREE.Scene();",
        "const add = (name: string, y: number) => { const b = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial()); b.name = name; b.position.y = y; scene.add(b); };",
        "add(\"gem\", 1.2); add(\"trap\", -1.2); scene.updateMatrixWorld();",
        "const toNdc = (px: number, py: number) => new THREE.Vector2((px / 800) * 2 - 1, (py / 600) * 2 - 1);",
        "const rc = new THREE.Raycaster();",
        "rc.setFromCamera(toNdc(400, 150), camera); // pointer in the upper half",
        "const hits = rc.intersectObjects(scene.children);",
        "console.log(\"hit \" + (hits[0]?.object.name ?? \"nothing\"));",
      ) + "\n",
      solution: code(
        "const camera = new THREE.PerspectiveCamera(50, 800 / 600, 0.1, 100);",
        "camera.position.z = 5; camera.updateMatrixWorld();",
        "const scene = new THREE.Scene();",
        "const add = (name: string, y: number) => { const b = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial()); b.name = name; b.position.y = y; scene.add(b); };",
        "add(\"gem\", 1.2); add(\"trap\", -1.2); scene.updateMatrixWorld();",
        "const toNdc = (px: number, py: number) => new THREE.Vector2((px / 800) * 2 - 1, -(py / 600) * 2 + 1);",
        "const rc = new THREE.Raycaster();",
        "rc.setFromCamera(toNdc(400, 150), camera); // pointer in the upper half",
        "const hits = rc.intersectObjects(scene.children);",
        "console.log(\"hit \" + (hits[0]?.object.name ?? \"nothing\"));",
      ) + "\n",
      expect: "hit gem",
      fallback: [String.raw`-\s*\(\s*py\s*\/\s*600\s*\)\s*\*\s*2\s*\+\s*1`, String.raw`1\s*-\s*\(\s*py\s*\/\s*600\s*\)\s*\*\s*2`, String.raw`1\s*-\s*2\s*\*\s*\(?\s*py\s*\/\s*600`, String.raw`-\s*\(\s*\(\s*py\s*\/\s*600\s*\)\s*\*\s*2\s*-\s*1\s*\)`],
      explain: L("Flip y: -(py / 600) * 2 + 1. Pixel 150 is in the upper half, so NDC y must be positive.", "Invierte y: -(py / 600) * 2 + 1. El píxel 150 está en la mitad de arriba, así que y en NDC debe ser positiva.", "y を反転しよう：-(py / 600) * 2 + 1。150 は上半分だから NDC の y はプラスになるはず。"),
    },
  ],
};

// ─── 3.3 Treasure from afar: assets, colour, lights and shadows ────────────
const assets: LessonDef = {
  slug: "assets-lights-shadows",
  title: L("Treasure from afar", "Tesoro de lejos", "遠くから届く宝"),
  concept: "assets and shadows",
  mode: "lesson",
  xp: 85,
  enemy: "golem",
  enemyName: L("SHADOW GOLEM", "GÓLEM DE SOMBRA", "かげゴーレム"),
  beats: [
    say(L(
      "Big models are made in 3D tools and saved as glTF (.glb). GLTFLoader brings them in, and gltf.scene is a Group to add.",
      "Los modelos grandes se hacen en herramientas 3D y se guardan como glTF (.glb). GLTFLoader los trae, y gltf.scene es un Group que agregas.",
      "大きなモデルは3Dツールで作り、glTF（.glb）で保存する。GLTFLoader で読みこみ、gltf.scene という Group を追加するよ。",
    )),
    {
      kind: "act",
      prompt: L("Load a treasure chest", "Carga un cofre del tesoro", "宝箱を読みこもう"),
      steps: [
        { label: L("IMPORT", "IMPORTAR", "インポート"), line: "import { GLTFLoader } from \"three/addons/loaders/GLTFLoader.js\";" },
        { label: L("LOADER", "CARGADOR", "ローダー"), line: "const loader = new GLTFLoader();", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "loader" }] },
        { label: L("WAIT", "ESPERAR", "待つ"), line: "const gltf = await loader.loadAsync(\"/chest.glb\");", effects: [{ t: "wait", ms: 400 }, { t: "item", kind: "gem", holder: "ally" }, { t: "say", actor: "ally", text: L("Delivery!", "¡Entrega!", "お届け！") }] },
        { label: L("ADD", "AGREGAR", "追加"), line: "scene.add(gltf.scene);", effects: [{ t: "give", to: "hero" }, { t: "banner", text: L("CHEST IN SCENE", "COFRE EN ESCENA", "宝箱が登場") }] },
      ],
    },
    {
      kind: "pick",
      prompt: L("What goes into the scene?", "¿Qué entra en la escena?", "シーンに入れるのは？"),
      code: code("import { GLTFLoader } from \"three/addons/loaders/GLTFLoader.js\";", "const scene = new THREE.Scene();", "const gltf = await new GLTFLoader().loadAsync(\"/chest.glb\");", "scene.add(___);"),
      options: ["gltf.scene", "gltf", "gltf.mesh"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: L("loadAsync resolves to a gltf object; its scene is the Group to add. gltf itself is not an Object3D.", "loadAsync da un objeto gltf; su scene es el Group a agregar. gltf en sí no es un Object3D.", "loadAsync は gltf オブジェクトを返す。追加するのは gltf.scene という Group。gltf 自体は Object3D じゃない。"),
    },
    say(L(
      "Photo-like colour textures are sRGB: set texture.colorSpace = THREE.SRGBColorSpace. Data maps (normal, roughness) stay NoColorSpace.",
      "Las texturas de color son sRGB: pon texture.colorSpace = THREE.SRGBColorSpace. Los mapas de datos (normal, roughness) van en NoColorSpace.",
      "色テクスチャは sRGB。texture.colorSpace = THREE.SRGBColorSpace にしよう。法線などのデータは NoColorSpace のまま。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const tex = new THREE.Texture();", "console.log(tex.colorSpace === THREE.NoColorSpace, THREE.SRGBColorSpace);"),
      options: ["true srgb", "false srgb", "true linear"],
      answer: 0,
      output: "true srgb",
      check: { compiles: true, stdout: "true srgb" },
      explain: L("A new texture has no colour space. Loaded by hand, a colour map must be tagged sRGB or it looks washed out. glTF does it for you.", "Una textura nueva no tiene espacio de color. Cargada a mano, hay que marcarla sRGB o se ve deslavada. glTF lo hace por ti.", "新しいテクスチャに色空間はない。手で読んだ色テクスチャは sRGB にしないと白っぽくなる。glTF は自動だよ。"),
    },
    {
      kind: "pick",
      prompt: L("Colour space for a normal map", "Espacio de color de un normal map", "法線マップの色空間は？"),
      code: code("const normalMap = new THREE.Texture();", "normalMap.colorSpace = ___;"),
      options: ["THREE.NoColorSpace", "THREE.SRGBColorSpace"],
      answer: 0,
      check: { compiles: true },
      explain: L("A normal map stores directions, not colours. Converting it from sRGB would bend every normal.", "Un normal map guarda direcciones, no colores. Convertirlo desde sRGB doblaría cada normal.", "法線マップが持つのは色ではなく向き。sRGB として変換すると法線がゆがむよ。"),
    },
    say(L(
      "Lights: Ambient and Hemisphere light everything evenly, with no direction and no shadows. Directional, Point and Spot can cast them.",
      "Luces: Ambient y Hemisphere iluminan todo parejo, sin dirección ni sombras. Directional, Point y Spot sí pueden proyectarlas.",
      "ライト：Ambient と Hemisphere は全体を均一に照らし、向きも影もない。Directional・Point・Spot は影を落とせる。",
    )),
    {
      kind: "predict",
      prompt: L("Which light has a shadow camera?", "¿Qué luz tiene cámara de sombra?", "影のカメラを持つライトは？"),
      code: code("console.log(\"shadow\" in new THREE.AmbientLight(), \"shadow\" in new THREE.SpotLight());"),
      options: ["false true", "true true", "true false"],
      answer: 0,
      output: "false true",
      check: { compiles: true, stdout: "false true" },
      explain: L("Only lights with a direction get a shadow object. AmbientLight lights everything equally and casts nothing.", "Solo las luces con dirección tienen un objeto shadow. AmbientLight ilumina todo igual y no proyecta nada.", "向きのあるライトだけが shadow を持つ。AmbientLight は全体を同じに照らし、影を落とさない。"),
    },
    say(L(
      "Shadows need FOUR switches, all false by default: renderer.shadowMap.enabled, light.castShadow, mesh.castShadow, floor.receiveShadow.",
      "Las sombras piden CUATRO interruptores, todos en false: renderer.shadowMap.enabled, light.castShadow, mesh.castShadow, floor.receiveShadow.",
      "影には4つのスイッチが必要。初期値はすべて false：shadowMap.enabled、light と mesh の castShadow、床の receiveShadow。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const mesh = new THREE.Mesh();", "const sun = new THREE.DirectionalLight();", "console.log(mesh.castShadow, mesh.receiveShadow, sun.castShadow);"),
      options: ["false false false", "true true true", "false false true"],
      answer: 0,
      output: "false false false",
      check: { compiles: true, stdout: "false false false" },
      explain: L("Shadows are costly, so every flag starts off. You turn on exactly the ones you need.", "Las sombras cuestan, así que cada bandera empieza apagada. Enciendes solo las que necesitas.", "影は重いので、フラグは全部オフから始まる。必要なものだけオンにしよう。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "say", actor: "enemy", text: L("No shadows yet!", "¡Aún sin sombras!", "まだ影はない！") }],
    },
    {
      kind: "type",
      prompt: L("Let the sun cast shadows", "Haz que el sol proyecte sombras", "太陽に影を落とさせよう"),
      code: code("const sun = new THREE.DirectionalLight(0xffffff, 3);", "sun.___ = true;", "console.log(sun.castShadow);"),
      answer: "castShadow",
      check: { compiles: true, stdout: "true" },
      explain: L("castShadow on the light makes it render a shadow map. Meshes still need their own castShadow.", "castShadow en la luz hace que genere un mapa de sombras. Las mallas igual necesitan su propio castShadow.", "ライトの castShadow で影マップが作られる。メッシュにもそれぞれ castShadow が必要だよ。"),
      win: [{ t: "banner", text: L("SUN CASTS", "EL SOL PROYECTA", "太陽が影を落とす") }],
    },
    {
      kind: "order",
      prompt: L("Load the chest, then add it", "Carga el cofre y luego agrégalo", "宝箱を読みこんで追加しよう"),
      lines: ["const loader = new GLTFLoader();", "const gltf = await loader.loadAsync(\"/chest.glb\");", "scene.add(gltf.scene);"],
      check: {
        compiles: true,
        program: code("import { GLTFLoader } from \"three/addons/loaders/GLTFLoader.js\";", "const scene = new THREE.Scene();", "const loader = new GLTFLoader();", "const gltf = await loader.loadAsync(\"/chest.glb\");", "scene.add(gltf.scene);"),
      },
      explain: L("Make the loader, await the file, then add gltf.scene: you can't add what hasn't arrived.", "Crea el cargador, espera el archivo y agrega gltf.scene: no puedes agregar lo que no llegó.", "ローダーを作り、ファイルを待ってから gltf.scene を追加。届いていない物は追加できない。"),
    },
    {
      kind: "run",
      prompt: L("Every mesh of the model must cast a shadow", "Cada malla del modelo debe proyectar sombra", "モデルの全メッシュに影を落とさせよう"),
      starter: code(
        "const part = (name: string) => { const m = new THREE.Mesh(); m.name = name; return m; };",
        "const model = new THREE.Group(); // stands in for gltf.scene",
        "const body = part(\"body\"), arm = part(\"arm\"), hand = part(\"hand\");",
        "model.add(body); body.add(arm); arm.add(hand);",
        "model.castShadow = true;",
        "let casters = 0;",
        "model.traverse((o) => { if (o instanceof THREE.Mesh && o.castShadow) casters++; });",
        "console.log(\"shadow casters: \" + casters);",
      ) + "\n",
      solution: code(
        "const part = (name: string) => { const m = new THREE.Mesh(); m.name = name; return m; };",
        "const model = new THREE.Group(); // stands in for gltf.scene",
        "const body = part(\"body\"), arm = part(\"arm\"), hand = part(\"hand\");",
        "model.add(body); body.add(arm); arm.add(hand);",
        "model.traverse((o) => { if (o instanceof THREE.Mesh) o.castShadow = true; });",
        "let casters = 0;",
        "model.traverse((o) => { if (o instanceof THREE.Mesh && o.castShadow) casters++; });",
        "console.log(\"shadow casters: \" + casters);",
      ) + "\n",
      expect: "shadow casters: 3",
      fallback: [String.raw`=>\s*\{?\s*(if\s*\([^)]*\)\s*)?\w+\.castShadow\s*=\s*true`, String.raw`(body|arm|hand)\.castShadow\s*=\s*(body|arm|hand)\.castShadow\s*=\s*(body|arm|hand)\.castShadow\s*=\s*true`],
      explain: L("The flag isn't inherited. traverse visits every node, so set castShadow on each Mesh inside.", "La bandera no se hereda. traverse visita cada nodo: pon castShadow en cada Mesh de adentro.", "フラグは子に受けつがれない。traverse で全ノードを回り、中の Mesh ごとに castShadow を立てよう。"),
    },
  ],
};

// ─── 3.4 Sweep the stage: disposal and performance ─────────────────────────
const dispose: LessonDef = {
  slug: "dispose-and-performance",
  title: L("Sweep the stage", "Barre el escenario", "舞台のおそうじ"),
  concept: "disposal",
  mode: "lesson",
  xp: 90,
  enemy: "threejs/leak-blob",
  enemyName: L("LEAK BLOB", "MANCHA FUGA", "リークブロブ"),
  beats: [
    say(L(
      "Geometries, materials and textures live on the GPU. scene.remove(mesh) only takes it off stage: the GPU memory stays!",
      "Geometrías, materiales y texturas viven en la GPU. scene.remove(mesh) solo lo saca de escena: ¡la memoria de la GPU sigue ocupada!",
      "形・マテリアル・テクスチャは GPU に住む。scene.remove(mesh) は舞台から下ろすだけ。GPU のメモリは残るよ！",
    )),
    {
      kind: "act",
      prompt: L("Remove the mesh, then really free it", "Quita la malla y luego libérala de verdad", "メッシュを外して、本当に解放しよう"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "mesh" }, { t: "item", kind: "gem", holder: "ally" }],
      steps: [
        { label: L("REMOVE", "QUITAR", "外す"), line: "scene.remove(mesh);", effects: [{ t: "exit", actor: "ally" }, { t: "say", actor: "enemy", text: L("Gem still held!", "¡Sigue con la gema!", "まだ宝石を持ってる！") }, { t: "shake" }] },
        { label: L("GEOMETRY", "GEOMETRÍA", "形"), line: "mesh.geometry.dispose();", effects: [{ t: "drop" }] },
        { label: L("MATERIAL", "MATERIAL", "マテリアル"), line: "mesh.material.dispose();" },
        { label: L("TEXTURE", "TEXTURA", "テクスチャ"), line: "texture.dispose();", effects: [{ t: "attack", from: "hero", to: "enemy" }, { t: "banner", text: L("MEMORY FREE", "MEMORIA LIBRE", "メモリ解放") }] },
      ],
    },
    {
      kind: "pick",
      prompt: L("Does scene.remove(mesh) free GPU memory?", "¿scene.remove(mesh) libera la GPU?", "scene.remove で GPU メモリは空く？"),
      code: "scene.remove(mesh);\n// GPU memory freed? ___",
      options: [NO, YES],
      answer: 0,
      explain: L("remove only detaches the object. Call dispose() on its geometry, material and textures.", "remove solo desconecta el objeto. Llama a dispose() en su geometría, material y texturas.", "remove は外すだけ。形・マテリアル・テクスチャの dispose() を呼ぼう。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const geo = new THREE.BoxGeometry();", "let events = 0;", "geo.addEventListener(\"dispose\", () => events++);", "geo.dispose();", "console.log(events);"),
      options: ["1", "0", "undefined"],
      answer: 0,
      output: "1",
      check: { compiles: true, stdout: "1" },
      explain: L("dispose() fires a \"dispose\" event. The renderer listens to it and deletes the GPU buffers.", "dispose() lanza un evento \"dispose\". El renderer lo escucha y borra los buffers de la GPU.", "dispose() は \"dispose\" イベントを出す。レンダラーがそれを聞いて GPU のバッファを消すよ。"),
      win: [{ t: "print", text: "1" }],
    },
    say(L(
      "Watch renderer.info.memory: it counts geometries and textures on the GPU. If it keeps growing, something leaks.",
      "Vigila renderer.info.memory: cuenta geometrías y texturas en la GPU. Si no deja de crecer, algo tiene fugas.",
      "renderer.info.memory を見よう。GPU 上の形とテクスチャの数だよ。増え続けるならリークしている。",
    )),
    {
      kind: "pick",
      prompt: L("Where do you spot a leak?", "¿Dónde detectas una fuga?", "リークを見つける場所は？"),
      code: code("declare const renderer: THREE.WebGLRenderer;", "declare const scene: THREE.Scene;", "console.log(___);"),
      options: ["renderer.info.memory.geometries", "scene.children.length"],
      answer: 0,
      check: { compiles: true },
      explain: L("scene.children only shows what's on stage. Removed but undisposed meshes still count in renderer.info.memory.", "scene.children solo muestra lo que está en escena. Las mallas quitadas sin dispose siguen contando en renderer.info.memory.", "scene.children は舞台の上だけ。外しただけのメッシュは renderer.info.memory にまだ数えられる。"),
    },
    {
      kind: "pick",
      prompt: L("10 meshes share a material. Remove one:", "10 mallas comparten material. Quitas una:", "10個で共有するマテリアル。1個外すと？"),
      code: "scene.remove(meshes[0]);\n// dispose the shared material now? ___",
      options: [L("No, only when none use it", "No, solo cuando nadie la use", "いいえ、誰も使わなくなったら"), L("Yes, right away", "Sí, de inmediato", "はい、すぐに")],
      answer: 0,
      explain: L("The other 9 still draw with it. Dispose shared resources only after the last user is gone.", "Las otras 9 aún la usan para dibujar. Libera recursos compartidos solo cuando se va el último usuario.", "残りの9個がまだ使っている。共有リソースは最後の利用者がいなくなってから解放しよう。"),
    },
    say(L(
      "Speed: each visible mesh costs about one DRAW CALL. 1000 trees = 1000 calls. InstancedMesh draws many copies in ONE.",
      "Velocidad: cada malla visible cuesta más o menos un DRAW CALL. 1000 árboles = 1000 llamadas. InstancedMesh dibuja muchas copias en UNA.",
      "速さの話。見えるメッシュ1つでドローコール約1回。木1000本なら1000回。InstancedMesh なら1回でたくさん描ける。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const trees = new THREE.InstancedMesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial(), 3);", "console.log(trees.count, trees.instanceMatrix.array.length);"),
      options: ["3 48", "3 3", "1 16"],
      answer: 0,
      output: "3 48",
      check: { compiles: true, stdout: "3 48" },
      explain: L("One mesh, 3 instances, each with its own 4×4 matrix: 3 × 16 = 48 numbers in one buffer.", "Una malla, 3 instancias, cada una con su matriz 4×4: 3 × 16 = 48 números en un buffer.", "メッシュ1つにインスタンス3つ。それぞれ4×4行列なので 3 × 16 = 48 個の数だよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "trees", value: "3" }],
      win: [{ t: "say", actor: "hero", text: L("One call, 3 trees", "Una llamada, 3 árboles", "1回で木3本") }],
    },
    {
      kind: "type",
      prompt: L("Place instance 1 at x = 7", "Pon la instancia 1 en x = 7", "インスタンス1を x = 7 へ"),
      code: code("const trees = new THREE.InstancedMesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial(), 3);", "trees.___(1, new THREE.Matrix4().makeTranslation(7, 0, 0));", "const out = new THREE.Matrix4();", "trees.getMatrixAt(1, out);", "console.log(out.elements[12]);"),
      answer: "setMatrixAt",
      check: { compiles: true, stdout: "7" },
      explain: L("setMatrixAt(index, matrix) writes one instance's transform; getMatrixAt reads it back.", "setMatrixAt(índice, matriz) escribe la transformación de una instancia; getMatrixAt la lee.", "setMatrixAt(番号, 行列) で1つのインスタンスの変換を書き、getMatrixAt で読むよ。"),
      win: [{ t: "print", text: "7" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: code("const trees = new THREE.InstancedMesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial(), 3);", "const before = trees.instanceMatrix.version;", "trees.instanceMatrix.needsUpdate = true;", "console.log(before, trees.instanceMatrix.version);"),
      options: ["0 1", "0 0", "1 1"],
      answer: 0,
      output: "0 1",
      check: { compiles: true, stdout: "0 1" },
      explain: L("needsUpdate = true bumps the version, which tells the renderer to upload the matrices again.", "needsUpdate = true sube la versión, y eso le avisa al renderer que vuelva a subir las matrices.", "needsUpdate = true で version が上がり、レンダラーが行列を送り直す合図になる。"),
    },
    {
      kind: "pick",
      prompt: L("1000 moving trees, same mesh and material", "1000 árboles en movimiento, misma malla y material", "同じ形と素材の木1000本が動く"),
      code: "// best way to draw them: ___",
      options: ["InstancedMesh", L("1000 separate meshes", "1000 mallas separadas", "別々のメッシュ1000個")],
      answer: 0,
      explain: L("InstancedMesh draws every copy in one call and each still moves via setMatrixAt.", "InstancedMesh dibuja todas las copias en una llamada y cada una se mueve con setMatrixAt.", "InstancedMesh なら1回で全部描けて、setMatrixAt でそれぞれ動かせるよ。"),
    },
    {
      kind: "run",
      prompt: L("clear() leaks! Dispose before removing", "¡clear() tiene fugas! Libera antes de quitar", "clear() がリーク！外す前に解放しよう"),
      starter: code(
        "const scene = new THREE.Scene();",
        "let disposed = 0;",
        "const count = <T extends THREE.EventDispatcher<{ dispose: {} }>>(r: T) => { r.addEventListener(\"dispose\", () => disposed++); return r; };",
        "for (let i = 0; i < 2; i++) scene.add(new THREE.Mesh(count(new THREE.BoxGeometry()), count(new THREE.MeshBasicMaterial())));",
        "function clear(root: THREE.Object3D): void {",
        "  for (const child of [...root.children]) {",
        "    root.remove(child);",
        "  }",
        "}",
        "clear(scene);",
        "console.log(`children: ${scene.children.length} disposed: ${disposed}`);",
      ) + "\n",
      solution: code(
        "const scene = new THREE.Scene();",
        "let disposed = 0;",
        "const count = <T extends THREE.EventDispatcher<{ dispose: {} }>>(r: T) => { r.addEventListener(\"dispose\", () => disposed++); return r; };",
        "for (let i = 0; i < 2; i++) scene.add(new THREE.Mesh(count(new THREE.BoxGeometry()), count(new THREE.MeshBasicMaterial())));",
        "function clear(root: THREE.Object3D): void {",
        "  for (const child of [...root.children]) {",
        "    if (child instanceof THREE.Mesh) { child.geometry.dispose(); child.material.dispose(); }",
        "    root.remove(child);",
        "  }",
        "}",
        "clear(scene);",
        "console.log(`children: ${scene.children.length} disposed: ${disposed}`);",
      ) + "\n",
      expect: "disposed: 4",
      fallback: [String.raw`geometry\.dispose\(\)[\s\S]*material\.dispose\(\)`, String.raw`material\.dispose\(\)[\s\S]*geometry\.dispose\(\)`],
      explain: L("Before remove, call child.geometry.dispose() and child.material.dispose(): 2 meshes × 2 = 4.", "Antes de remove, llama a child.geometry.dispose() y child.material.dispose(): 2 mallas × 2 = 4.", "remove の前に child.geometry.dispose() と child.material.dispose() を呼ぼう。2個 × 2 = 4。"),
    },
  ],
};

// ─── 3.5 Boss: Frame Dragon ────────────────────────────────────────────────
const boss: LessonDef = {
  slug: "frame-dragon",
  title: L("Boss: Frame Dragon", "Jefe: Dragón de Frames", "ボス：フレームドラゴン"),
  concept: "render loop",
  mode: "boss",
  xp: 200,
  enemy: "dragon",
  enemyName: L("FRAME DRAGON", "DRAGÓN DE FRAMES", "フレームドラゴン"),
  beats: [
    enemySays(L(
      "I AM THE FRAME DRAGON. I eat frames, leak memory and hide behind planes. Can your loop survive me?",
      "SOY EL DRAGÓN DE FRAMES. Como frames, dejo fugas de memoria y me escondo tras los planos. ¿Tu bucle sobrevivirá?",
      "我はフレームドラゴン。フレームを喰らい、メモリを漏らし、板の裏に隠れる。お前のループは耐えられるか？",
    )),
    { kind: "predict", time: 15, prompt: PRINT, code: code("const t = new THREE.Timer();", "t.update(0);", "t.update(50);", "console.log(t.getDelta());"), options: ["0.05", "50", "0.5"], answer: 0, output: "0.05", check: { compiles: true, stdout: "0.05" }, explain: L("50 ms between updates is 0.05 seconds.", "50 ms entre updates son 0.05 segundos.", "update の間が 50ms なら 0.05 秒。") },
    { kind: "pick", time: 12, prompt: L("Frame-rate independent move", "Movimiento independiente de fps", "fps に左右されない動き"), code: "declare const dt: number;\nlet x = 0;\nconst speed = 3;\nx += ___;", options: ["speed * dt", "speed"], answer: 0, check: { compiles: true }, explain: L("Scale by dt so every screen covers the same distance per second.", "Escala por dt para que toda pantalla recorra lo mismo por segundo.", "dt を掛ければ、どの画面でも1秒の移動量が同じ。") },
    { kind: "predict", time: 15, prompt: L("How many steps of 1/60 s fit?", "¿Cuántos pasos de 1/60 s caben?", "1/60秒の刻みは何回入る？"), code: "let acc = 0.04, steps = 0;\nconst STEP = 1 / 60;\nwhile (acc >= STEP) { acc -= STEP; steps++; }\nconsole.log(steps);", options: ["2", "3", "1"], answer: 0, output: "2", check: { compiles: true, stdout: "2" }, explain: L("A fixed-step accumulator: 0.04 s holds two 1/60 s physics steps; the rest waits.", "Un acumulador de paso fijo: 0.04 s contiene dos pasos de 1/60 s; el resto espera.", "固定ステップの蓄積：0.04秒に1/60秒は2回。残りは次へ持ちこす。") },
    { kind: "predict", time: 18, prompt: L("A ray too short to reach?", "¿Un rayo demasiado corto?", "届かない短い光線？"), code: code("const box = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());", "box.updateMatrixWorld();", "const from = new THREE.Vector3(0.2, 0.1, 10), dir = new THREE.Vector3(0, 0, -1);", "const long = new THREE.Raycaster(from, dir);", "const short = new THREE.Raycaster(from, dir, 0, 5);", "console.log(long.intersectObject(box).length, short.intersectObject(box).length);"), options: ["1 0", "1 1", "0 0"], answer: 0, output: "1 0", check: { compiles: true, stdout: "1 0" }, explain: L("The box face is 9.5 away; far = 5 stops the short ray before it.", "La cara de la caja está a 9.5; far = 5 frena el rayo corto antes.", "箱の面は 9.5 先。far = 5 の光線は手前で止まる。") },
    { kind: "predict", time: 15, prompt: PRINT, code: code("const box = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());", "box.updateMatrixWorld();", "const rc = new THREE.Raycaster(new THREE.Vector3(0.2, 0.1, 10), new THREE.Vector3(0, 0, -1));", "const hit = rc.intersectObject(box)[0];", "console.log(hit.distance.toFixed(1), hit.point.z);"), options: ["9.5 0.5", "10 0", "9.5 -0.5"], answer: 0, output: "9.5 0.5", check: { compiles: true, stdout: "9.5 0.5" }, explain: L("The ray meets the front face at z = 0.5, which is 9.5 from its origin at z = 10.", "El rayo toca la cara frontal en z = 0.5, a 9.5 de su origen en z = 10.", "光線は z = 0.5 の前面に当たる。原点 z = 10 から 9.5 の距離。") },
    { kind: "pick", time: 15, prompt: L("Flags on, still no shadows. Missing:", "Banderas listas, sin sombras. Falta:", "フラグは全部オン、でも影なし。足りないのは？"), code: code("declare const renderer: THREE.WebGLRenderer;", "// light.castShadow, mesh.castShadow, floor.receiveShadow: true", "renderer.___ = true;"), options: ["shadowMap.enabled", "castShadow"], answer: 0, check: { compiles: true, wrongFail: true }, explain: L("The renderer must enable its shadow map too; it has no castShadow.", "El renderer también debe activar su shadowMap; no tiene castShadow.", "レンダラーも shadowMap を有効に。castShadow はレンダラーにはない。") },
    { kind: "predict", time: 15, prompt: L("Does it compile?", "¿Compila?", "コンパイルできる？"), code: code("const group = new THREE.Group();", "const first: THREE.Mesh = group.children[0];"), options: [YES, L("No: children are Object3D", "No: children son Object3D", "いいえ：子は Object3D")], answer: 1, check: { compiles: false }, explain: L("TS2739: children are typed Object3D. Narrow with instanceof THREE.Mesh first.", "TS2739: children son Object3D. Primero acota con instanceof THREE.Mesh.", "TS2739：children は Object3D 型。まず instanceof THREE.Mesh で絞ろう。") },
    { kind: "predict", time: 12, prompt: PRINT, code: code("const im = new THREE.InstancedMesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial(), 100);", "console.log(im.instanceMatrix.array.length);"), options: ["1600", "100", "400"], answer: 0, output: "1600", check: { compiles: true, stdout: "1600" }, explain: L("100 instances × 16 numbers per 4×4 matrix.", "100 instancias × 16 números por matriz 4×4.", "100個 × 4×4行列の16個。") },
    { kind: "pick", time: 15, prompt: L("A route change leaks GPU memory. Fix:", "Un cambio de ruta fuga memoria. Arreglo:", "画面遷移でメモリリーク。直し方は？"), code: "// leaving the 3D page: ___", options: [L("dispose geometries, materials, textures", "dispose de geometrías, materiales y texturas", "形・素材・テクスチャを dispose"), L("only scene.clear()", "solo scene.clear()", "scene.clear() だけ")], answer: 0, explain: L("clear() just detaches children; GPU resources die only with dispose().", "clear() solo desconecta a los hijos; los recursos de GPU mueren solo con dispose().", "clear() は子を外すだけ。GPU 資源は dispose() でしか消えない。") },
    { kind: "type", time: 15, prompt: L("Tag the photo texture as sRGB", "Marca la textura de foto como sRGB", "写真テクスチャを sRGB に"), code: code("const photo = new THREE.Texture();", "photo.colorSpace = THREE.___;", "console.log(photo.colorSpace);"), answer: "SRGBColorSpace", check: { compiles: true, stdout: "srgb" }, explain: L("Colour maps are sRGB; untagged they look washed out.", "Los mapas de color son sRGB; sin marcar se ven deslavados.", "色テクスチャは sRGB。指定しないと白っぽくなる。") },
    enemySays(L(
      "My frames... steady at last. Your loop is clean, your memory swept. The scene is yours, director.",
      "Mis frames... por fin estables. Tu bucle está limpio y tu memoria barrida. La escena es tuya.",
      "我がフレームが…ついに安定した。ループは清く、メモリも片づいた。このシーンはお前のものだ、監督よ。",
    )),
  ],
};

export const loopTower: RegionDef = {
  slug: "loop-tower",
  name: L("Loop Tower", "Torre del Bucle", "ループの塔"),
  subtitle: L("Time · picking · assets · cleanup", "Tiempo · selección · recursos · limpieza", "時間・選択・アセット・片づけ"),
  theme: "tower",
  lessons: [renderLoop, raycasting, assets, dispose, boss],
};
