import type { Beat, LessonDef, RegionDef, Text } from "../../../lib/content/types.ts";
import { L } from "../../../lib/i18n/text.ts";

// REGION 1 · SCENE VILLAGE  (scene/camera/renderer, meshes, geometry and materials, Object3D transforms)
// Snippets only use three's math and scene graph: a WebGLRenderer is only ever declared, never constructed.

const say = (text: Text): Beat => ({ kind: "dialog", speaker: "master", text });
const enemySays = (text: Text): Beat => ({ kind: "dialog", speaker: "enemy", text });

const IMP = 'import * as THREE from "three";\n';
const PRINT = L("What does it print?", "¿Qué imprime?", "何が表示される？");
const COMPILES = L("Does it compile?", "¿Compila?", "コンパイルできる？");
const YES = L("Yes", "Sí", "はい");
const NO_TSC = L("No: tsc stops it", "No: tsc lo detiene", "いいえ：tsc が止める");

// ─── 1.1 Stage, eye and painter ────────────────────────────────────────────
const sceneCamera: LessonDef = {
  slug: "scene-camera-renderer",
  title: L("Stage, eye and painter", "Escenario, ojo y pintor", "舞台と目と絵描き"),
  concept: "scene_basics",
  mode: "lesson",
  xp: 60,
  enemy: "threejs/lost-wanderer",
  enemyName: L("LOST WANDERER", "ERRANTE PERDIDO", "まいごの旅人"),
  beats: [
    say(L(
      "Welcome to Scenara! Every three.js picture needs three things: a SCENE (the stage), a CAMERA (the eye) and a RENDERER (the painter).",
      "¡Bienvenido a Scenara! Toda imagen de three.js necesita tres partes: una ESCENA (escenario), una CÁMARA (el ojo) y un RENDERER (el pintor).",
      "シーネラへようこそ！three.js の絵には3つ必要。舞台のシーン、目のカメラ、絵描きのレンダラーだよ。",
    )),
    {
      kind: "act",
      prompt: L("Build the stage in order and call the painter", "Arma el escenario en orden y llama al pintor", "順番に舞台を作って、絵描きを呼ぼう"),
      steps: [
        { label: L("STAGE", "ESCENARIO", "舞台"), line: "const scene = new THREE.Scene();", effects: [{ t: "tag", actor: "hero", text: "scene" }, { t: "say", actor: "hero", text: L("An empty stage.", "Escenario vacío.", "からっぽの舞台") }] },
        { label: L("EYE", "OJO", "目"), line: "const camera = new THREE.PerspectiveCamera(75, 16 / 9, 0.1, 1000);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "camera", value: "fov 75" }, { t: "item", kind: "scroll", holder: "ally" }] },
        { label: L("ACTOR", "ACTOR", "役者"), line: "scene.add(mesh);", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "value", actor: "hero", text: "1 child" }] },
        { label: L("PAINT", "PINTAR", "描く"), line: "renderer.render(scene, camera);", effects: [{ t: "enter", actor: "enemy" }, { t: "banner", text: L("FRAME PAINTED!", "¡CUADRO PINTADO!", "1枚描けた！") }] },
      ],
    },
    say(L(
      "The renderer only paints when you call render(scene, camera). PerspectiveCamera takes (fov, aspect, near, far).",
      "El renderer solo pinta cuando llamas a render(scene, camera). PerspectiveCamera recibe (fov, aspect, near, far).",
      "レンダラーは render(scene, camera) を呼んだ時だけ描く。カメラの引数は (fov, aspect, near, far) だよ。",
    )),
    {
      kind: "predict",
      prompt: L("No arguments. What does it print?", "Sin argumentos. ¿Qué imprime?", "引数なし。何が表示される？"),
      code: IMP + "const cam = new THREE.PerspectiveCamera();\nconsole.log(cam.fov, cam.aspect, cam.near, cam.far);",
      options: ["50 1 0.1 2000", "75 1 0.1 1000", "0 0 0 0"],
      answer: 0,
      output: "50 1 0.1 2000",
      check: { compiles: true, stdout: "50 1 0.1 2000" },
      explain: L("The defaults are fov 50 (degrees), aspect 1, near 0.1 and far 2000.", "Los valores por defecto son fov 50 (grados), aspect 1, near 0.1 y far 2000.", "初期値は fov 50（度）、aspect 1、near 0.1、far 2000 だよ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "cam" }],
      win: [{ t: "value", actor: "ally", text: "fov 50" }, { t: "print", text: "50 1 0.1 2000" }],
    },
    say(L(
      "fov is the VERTICAL view angle, in degrees. Every new camera starts at the origin, looking down -Z.",
      "fov es el ángulo de visión VERTICAL, en grados. Toda cámara nueva empieza en el origen, mirando hacia -Z.",
      "fov は縦方向の視野角で、単位は度。新しいカメラは原点にいて -Z の方を向いているよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const cam = new THREE.PerspectiveCamera(75, 16 / 9, 0.1, 1000);\nconsole.log(cam.position.z);",
      options: ["0", "1000", "75"],
      answer: 0,
      output: "0",
      check: { compiles: true, stdout: "0" },
      explain: L("It sits at (0, 0, 0). A cube at the origin would swallow it: move the camera back.", "Está en (0, 0, 0). Un cubo en el origen la envolvería: aleja la cámara.", "位置は (0, 0, 0)。原点の立方体に埋もれちゃうから、カメラを後ろに下げよう。"),
      setup: [{ t: "enter", actor: "enemy" }],
      win: [{ t: "print", text: "0" }, { t: "say", actor: "enemy", text: L("I'm inside the cube!", "¡Estoy en el cubo!", "箱の中だ！") }],
    },
    {
      kind: "type",
      prompt: L("Move the camera back, toward the viewer", "Aleja la cámara, hacia quien mira", "カメラを手前に下げよう"),
      code: IMP + "const camera = new THREE.PerspectiveCamera();\ncamera.position.___ = 5;\nconsole.log(camera.position.toArray().join(\",\"));",
      answer: "z",
      check: { compiles: true, stdout: "0,0,5" },
      explain: L("It looks down -Z, so a positive z steps it back and the origin comes into view.", "Mira hacia -Z, así que una z positiva la aleja y el origen entra en cuadro.", "-Z を向いているから、z をプラスにすると下がって原点が見えるよ。"),
      win: [{ t: "value", actor: "ally", text: "z = 5" }, { t: "print", text: "0,0,5" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: IMP + 'const cam = new THREE.PerspectiveCamera();\ncam.fov = "75";',
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2322: fov is a number. The three.js types catch it before anything is drawn.", "TS2322: fov es un number. Los tipos de three.js lo atrapan antes de dibujar nada.", "TS2322：fov は number。描く前に three.js の型が見つけてくれる。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "order",
      prompt: L("Order the lines to put a mesh on stage", "Ordena las líneas para poner una malla", "メッシュを舞台に置く順に並べよう"),
      lines: [
        'import * as THREE from "three";',
        "const scene = new THREE.Scene();",
        "const mesh = new THREE.Mesh();",
        "scene.add(mesh);",
        "console.log(scene.children.length);",
      ],
      check: { compiles: true, stdout: "1" },
      explain: L("Import, make the stage, make the actor, add it, then use it. add() puts it in scene.children.", "Importa, crea el escenario, crea el actor, agrégalo y úsalo. add() lo pone en scene.children.", "import→舞台→役者→追加→利用の順。add() で scene.children に入るよ。"),
      win: [{ t: "print", text: "1" }],
    },
    say(L(
      "When the window resizes: set camera.aspect, call camera.updateProjectionMatrix(), then renderer.setSize(w, h).",
      "Al cambiar el tamaño: ajusta camera.aspect, llama a camera.updateProjectionMatrix() y luego renderer.setSize(w, h).",
      "画面サイズが変わったら aspect を設定し、updateProjectionMatrix() を呼んで、setSize(w, h) だよ。",
    )),
    {
      kind: "pick",
      prompt: L("Complete the resize handler", "Completa el manejador de resize", "リサイズ処理を完成させよう"),
      code: IMP + "declare const renderer: THREE.WebGLRenderer;\nconst camera = new THREE.PerspectiveCamera(75, 1, 0.1, 100);\nfunction onResize(w: number, h: number) {\n  camera.aspect = w / h;\n  camera.___();\n  renderer.setSize(w, h);\n}",
      options: ["updateProjectionMatrix", "updateMatrix", "render"],
      answer: 0,
      check: { compiles: true },
      explain: L("Camera settings are cached in projectionMatrix. Change fov, aspect, near or far and you must rebuild it.", "Los ajustes de cámara se guardan en projectionMatrix. Si cambias fov, aspect, near o far, hay que reconstruirla.", "カメラの設定は projectionMatrix に保存される。fov や aspect を変えたら作り直そう。"),
    },
    {
      kind: "predict",
      prompt: L("A mesh 2500 units away, far = 2000. Seen?", "Una malla a 2500 unidades, far = 2000. ¿Se ve?", "2500 先のメッシュ、far = 2000。見える？"),
      code: IMP + "const camera = new THREE.PerspectiveCamera(50, 1, 0.1, 2000);\nconst mesh = new THREE.Mesh();\nmesh.position.z = -2500;",
      options: [L("No: it's past far", "No: está más allá de far", "いいえ：far より遠い"), L("Yes, just tiny", "Sí, pero diminuta", "はい、小さく見える")],
      answer: 0,
      explain: L("Only what lies between near and far is drawn. Anything outside that box (the frustum) is cut.", "Solo se dibuja lo que está entre near y far. Lo que queda fuera de esa caja (el frustum) se corta.", "描かれるのは near と far の間だけ。その範囲（視錐台）の外は切り捨てられるよ。"),
    },
    {
      kind: "predict",
      prompt: L("Why cap setPixelRatio at 2?", "¿Por qué limitar setPixelRatio a 2?", "setPixelRatio を2までにする理由は？"),
      code: IMP + "declare const renderer: THREE.WebGLRenderer;\nrenderer.setPixelRatio(Math.min(devicePixelRatio, 2));",
      options: [L("Pixels grow with its square", "Los píxeles crecen al cuadrado", "画素数が2乗で増える"), L("Textures break above 2", "Las texturas fallan sobre 2", "2超でテクスチャが壊れる")],
      answer: 0,
      explain: L("Ratio 3 paints 9 pixels per CSS pixel, ratio 2 only 4. Phones heat up for almost no visible gain.", "Con ratio 3 se pintan 9 píxeles por píxel CSS, con 2 solo 4. El teléfono se calienta casi sin ganancia visible.", "比率3なら CSS 1画素につき9画素、2なら4画素。見た目はほぼ同じでスマホが熱くなるだけ。"),
    },
    {
      kind: "run",
      prompt: L("Fix the resize: it must print p00 0.652", "Arregla el resize: debe imprimir p00 0.652", "リサイズを直そう：p00 0.652 と表示"),
      starter: IMP + "const camera = new THREE.PerspectiveCamera(75, 16 / 9, 0.1, 1000);\nfunction onResize(width: number, height: number): void {\n  camera.aspect = width / height;\n}\nonResize(800, 400);\nconsole.log(\"p00 \" + camera.projectionMatrix.elements[0].toFixed(3));\n",
      solution: IMP + "const camera = new THREE.PerspectiveCamera(75, 16 / 9, 0.1, 1000);\nfunction onResize(width: number, height: number): void {\n  camera.aspect = width / height;\n  camera.updateProjectionMatrix();\n}\nonResize(800, 400);\nconsole.log(\"p00 \" + camera.projectionMatrix.elements[0].toFixed(3));\n",
      expect: "p00 0.652",
      fallback: [String.raw`updateProjectionMatrix\s*\(\s*\)`],
      explain: L("Without updateProjectionMatrix() the old 16:9 matrix stays and the picture looks stretched.", "Sin updateProjectionMatrix() queda la matriz vieja de 16:9 y la imagen se ve estirada.", "updateProjectionMatrix() がないと古い 16:9 の行列のままで、絵が伸びて見えるよ。"),
    },
  ],
};

// ─── 1.2 Body and skin ─────────────────────────────────────────────────────
const meshes: LessonDef = {
  slug: "meshes-geometry-material",
  title: L("Body and skin", "Cuerpo y piel", "からだと肌"),
  concept: "materials",
  mode: "lesson",
  xp: 65,
  enemy: "threejs/leak-blob",
  enemyName: L("TRIANGLE BLOB", "BLOB DE TRIÁNGULOS", "さんかくブロブ"),
  beats: [
    say(L(
      "A Mesh is an actor made of two parts: a GEOMETRY (its body, made of points) and a MATERIAL (its skin).",
      "Una Mesh es un actor de dos partes: una GEOMETRÍA (su cuerpo, hecho de puntos) y un MATERIAL (su piel).",
      "メッシュは2つでできた役者。点でできたからだのジオメトリと、肌のマテリアルだよ。",
    )),
    {
      kind: "act",
      prompt: L("Build a red cube and watch the lights", "Arma un cubo rojo y mira la luz", "赤い立方体を作って、光を見てね"),
      steps: [
        { label: L("BODY", "CUERPO", "からだ"), line: "const geo = new THREE.BoxGeometry(1, 1, 1);", effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "geo" }] },
        { label: L("SKIN", "PIEL", "肌"), line: "const mat = new THREE.MeshStandardMaterial({ color: 0xff0000 });", effects: [{ t: "enter", actor: "ally" }, { t: "item", kind: "gem", holder: "ally" }, { t: "tag", actor: "ally", text: "mat" }] },
        { label: L("MESH", "MALLA", "メッシュ"), line: "const cube = new THREE.Mesh(geo, mat);\nscene.add(cube);", effects: [{ t: "give", to: "hero" }, { t: "tag", actor: "hero", text: "cube" }] },
        { label: L("RENDER", "RENDER", "描く"), line: "renderer.render(scene, camera);", effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("All black?!", "¿¡Todo negro!?", "真っ黒？！") }] },
        { label: L("LIGHT", "LUZ", "光"), line: "scene.add(new THREE.DirectionalLight(0xffffff, 3));", effects: [{ t: "banner", text: L("LIGHT!", "¡LUZ!", "ライト！") }, { t: "say", actor: "hero", text: L("Red at last!", "¡Rojo al fin!", "やっと赤！") }] },
      ],
    },
    say(L(
      "MeshStandardMaterial reacts to light, so with no light it is black. MeshBasicMaterial ignores light: always flat color.",
      "MeshStandardMaterial reacciona a la luz: sin luz se ve negro. MeshBasicMaterial ignora la luz: siempre color plano.",
      "Standard は光に反応するので、光がないと黒。Basic は光を無視して、いつも同じ色だよ。",
    )),
    {
      kind: "pick",
      prompt: L("This skin is visible with no lights", "Esta piel se ve sin luces", "光なしでも見える肌は？"),
      code: IMP + "const mat = new THREE.___({ color: 0x00ff00 });\nconst mesh = new THREE.Mesh(new THREE.BoxGeometry(), mat);",
      options: ["MeshBasicMaterial", "MeshStandardMaterial", "MeshPhongMaterial"],
      answer: 0,
      check: { compiles: true },
      explain: L("Basic ignores lighting. Lambert, Phong, Standard and Physical need a light or they render black.", "Basic ignora la iluminación. Lambert, Phong, Standard y Physical necesitan luz o se ven negras.", "Basic は光を無視する。Lambert・Phong・Standard・Physical は光がないと黒くなるよ。"),
      win: [{ t: "item", kind: "gem", holder: "hero" }, { t: "say", actor: "hero", text: L("Green, no lamp!", "¡Verde sin lámpara!", "灯りなしで緑！") }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const m = new THREE.Mesh();\nconsole.log(m.geometry.type);",
      options: ["BufferGeometry", "BoxGeometry", "undefined"],
      answer: 0,
      output: "BufferGeometry",
      check: { compiles: true, stdout: "BufferGeometry" },
      explain: L("An empty Mesh gets an empty BufferGeometry and a MeshBasicMaterial. Every geometry is a BufferGeometry.", "Una Mesh vacía recibe una BufferGeometry vacía y un MeshBasicMaterial. Toda geometría es una BufferGeometry.", "空のメッシュには空の BufferGeometry と Basic マテリアルが入る。ジオメトリはみな BufferGeometry だよ。"),
      win: [{ t: "print", text: "BufferGeometry" }],
    },
    say(L(
      "A geometry stores corners (vertices). A cube has 8 corners, but each face needs its own copies to light it right.",
      "Una geometría guarda esquinas (vértices). Un cubo tiene 8, pero cada cara necesita sus propias copias para iluminarse bien.",
      "ジオメトリは角（頂点）を持つ。立方体の角は8つだけど、面ごとに専用の角が必要なんだ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const g = new THREE.BoxGeometry(1, 1, 1);\nconsole.log(g.attributes.position.count, g.index?.count);",
      options: ["24 36", "8 12", "8 36"],
      answer: 0,
      output: "24 36",
      check: { compiles: true, stdout: "24 36" },
      explain: L("6 faces × 4 corners = 24 vertices. 6 faces × 2 triangles × 3 indices = 36.", "6 caras × 4 esquinas = 24 vértices. 6 caras × 2 triángulos × 3 índices = 36.", "6面×4角＝24頂点。6面×2三角形×3インデックス＝36だよ。"),
      setup: [{ t: "item", kind: "scroll", holder: "hero" }],
      win: [{ t: "value", actor: "hero", text: "24 verts" }, { t: "print", text: "24 36" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const g = new THREE.PlaneGeometry(2, 2);\nconsole.log(g.attributes.position.count);",
      options: ["4", "6", "2"],
      answer: 0,
      output: "4",
      check: { compiles: true, stdout: "4" },
      explain: L("A flat square: 4 corners, drawn as 2 triangles (6 indices).", "Un cuadrado plano: 4 esquinas, dibujadas como 2 triángulos (6 índices).", "平らな四角形は4頂点。2つの三角形（6インデックス）で描くよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const s = new THREE.MeshStandardMaterial();\nconsole.log(s.roughness, s.metalness);",
      options: ["1 0", "0 1", "0.5 0.5"],
      answer: 0,
      output: "1 0",
      check: { compiles: true, stdout: "1 0" },
      explain: L("Standard starts fully rough and not metal at all: a matte surface like clay.", "Standard empieza totalmente rugoso y nada metálico: una superficie mate como la arcilla.", "Standard の初期値はザラザラで金属ゼロ。粘土みたいなつや消しだよ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: IMP + "const mat = new THREE.MeshBasicMaterial();\nmat.roughness = 0.5;",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2339: roughness belongs to MeshStandardMaterial. Basic has no lighting knobs at all.", "TS2339: roughness es de MeshStandardMaterial. Basic no tiene perillas de iluminación.", "TS2339：roughness は Standard のもの。Basic には光の設定がないよ。"),
      win: [{ t: "shake" }],
    },
    say(L(
      "Colors are THREE.Color objects. Set them with hex numbers like 0xff0000 and read them back with getHexString().",
      "Los colores son objetos THREE.Color. Se asignan con hex como 0xff0000 y se leen con getHexString().",
      "色は THREE.Color オブジェクト。0xff0000 のような16進で設定し、getHexString() で読めるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const c = new THREE.Color(0xff0000);\nconsole.log(c.getHexString(), c.r);",
      options: ["ff0000 1", "#ff0000 255", "ff0000 255"],
      answer: 0,
      output: "ff0000 1",
      check: { compiles: true, stdout: "ff0000 1" },
      explain: L("getHexString() has no #. Components r, g, b go from 0 to 1, not 0 to 255.", "getHexString() no lleva #. Los componentes r, g, b van de 0 a 1, no de 0 a 255.", "getHexString() に # は付かない。r・g・b は 0〜255 じゃなく 0〜1 だよ。"),
      win: [{ t: "print", text: "ff0000 1" }],
    },
    {
      kind: "predict",
      prompt: L("Gray #808080. What does it print?", "Gris #808080. ¿Qué imprime?", "灰色 #808080。何が表示される？"),
      code: IMP + 'const c = new THREE.Color("#808080");\nconsole.log(c.r.toFixed(4), c.getHexString());',
      options: ["0.2159 808080", "0.5020 808080", "0.5000 808080"],
      answer: 0,
      output: "0.2159 808080",
      check: { compiles: true, stdout: "0.2159 808080" },
      explain: L("CSS colors are sRGB; three stores them in LINEAR light for correct math, and converts back when you read hex.", "Los colores CSS son sRGB; three los guarda en luz LINEAL para calcular bien y los convierte al leer hex.", "CSS の色は sRGB。three は計算用にリニアで保存し、16進で読む時に戻すよ。"),
    },
    {
      kind: "run",
      prompt: L("Repaint the skin: it must print color 00ff00", "Repinta la piel: debe imprimir color 00ff00", "肌を塗り直そう：color 00ff00 と表示"),
      starter: IMP + "const mat = new THREE.MeshStandardMaterial({ color: 0xff0000 });\n// @ts-expect-error a number is not a Color\nmat.color = 0x00ff00;\nconsole.log(\"color \" + mat.color.getHexString());\n",
      solution: IMP + "const mat = new THREE.MeshStandardMaterial({ color: 0xff0000 });\nmat.color.set(0x00ff00);\nconsole.log(\"color \" + mat.color.getHexString());\n",
      expect: "color 00ff00",
      fallback: [String.raw`mat\.color\.set(Hex)?\s*\(`, String.raw`mat\.color\.setStyle\s*\(`, String.raw`mat\.color\s*=\s*new\s+THREE\.Color\s*\(`],
      explain: L("mat.color is a Color object: replacing it with a number breaks it. Change it in place with set().", "mat.color es un objeto Color: cambiarlo por un número lo rompe. Modifícalo en su lugar con set().", "mat.color は Color オブジェクト。数値で置きかえると壊れる。set() でその場で変えよう。"),
    },
  ],
};

// ─── 1.3 Move, turn, grow ──────────────────────────────────────────────────
const transforms: LessonDef = {
  slug: "object3d-transforms",
  title: L("Move, turn, grow", "Mover, girar, crecer", "動く・回る・のびる"),
  concept: "transforms",
  mode: "lesson",
  xp: 70,
  enemy: "threejs/gimbal-knot",
  enemyName: L("SPIN KNOT", "NUDO GIRATORIO", "ぐるぐるノット"),
  beats: [
    say(L(
      "Every object is an Object3D with a pose: position (where), rotation (which way) and scale (how big).",
      "Todo objeto es un Object3D con una pose: position (dónde), rotation (hacia dónde) y scale (qué tan grande).",
      "どの物体も Object3D でポーズを持つ。position は場所、rotation は向き、scale は大きさだよ。",
    )),
    {
      kind: "act",
      prompt: L("Pose the hero and watch the chips", "Posa al héroe y mira las fichas", "主人公にポーズをとらせよう"),
      steps: [
        { label: L("WALK", "CAMINAR", "歩く"), line: "hero.position.set(2, 0, 0);", effects: [{ t: "tag", actor: "hero", text: "position", value: "2,0,0" }] },
        { label: L("TURN", "GIRAR", "回る"), line: "hero.rotation.y = Math.PI / 2;", effects: [{ t: "value", actor: "hero", text: "y 90°" }, { t: "say", actor: "hero", text: L("A quarter turn!", "¡Un cuarto de vuelta!", "4分の1回転！") }] },
        { label: L("GROW", "CRECER", "のびる"), line: "hero.scale.set(2, 2, 2);", effects: [{ t: "value", actor: "hero", text: "x2" }, { t: "banner", text: L("BIG HERO!", "¡HÉROE GIGANTE!", "でっかい！") }] },
        {
          label: L("REPLACE", "REEMPLAZAR", "置きかえ"),
          line: "hero.position = new THREE.Vector3(1, 2, 3);",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: L("Can't swap it!", "¡No se cambia!", "交換できない！") }],
          error: {
            compiler: "error TS2540: Cannot assign to 'position' because it is a read-only property.",
            plain: L("position is a fixed Vector3. Change its numbers with set(), never replace it.", "position es un Vector3 fijo. Cambia sus números con set(), nunca lo reemplaces.", "position は固定の Vector3。中身を set() で変えよう。置きかえはダメ。"),
          },
        },
      ],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const o = new THREE.Object3D();\nconsole.log(o.position.toArray().join(","), o.scale.toArray().join(","));',
      options: ["0,0,0 1,1,1", "0,0,0 0,0,0", "1,1,1 1,1,1"],
      answer: 0,
      output: "0,0,0 1,1,1",
      check: { compiles: true, stdout: "0,0,0 1,1,1" },
      explain: L("A new object stands at the origin at normal size. A scale of 0 would make it vanish.", "Un objeto nuevo está en el origen con tamaño normal. Una escala 0 lo haría desaparecer.", "新しい物体は原点にいて大きさは等倍。scale が 0 だと消えちゃうよ。"),
      win: [{ t: "print", text: "0,0,0 1,1,1" }],
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: IMP + "const mesh = new THREE.Mesh();\nmesh.position = new THREE.Vector3(1, 2, 3);",
      options: [YES, NO_TSC],
      answer: 1,
      check: { compiles: false },
      explain: L("TS2540: position is read-only. Write mesh.position.set(1, 2, 3) instead.", "TS2540: position es de solo lectura. Escribe mesh.position.set(1, 2, 3).", "TS2540：position は読み取り専用。mesh.position.set(1, 2, 3) と書こう。"),
      win: [{ t: "shake" }],
    },
    {
      kind: "type",
      prompt: L("Move the mesh in place", "Mueve la malla en su lugar", "その場でメッシュを動かそう"),
      code: IMP + 'const mesh = new THREE.Mesh();\nmesh.position.___(1, 2, 3);\nconsole.log(mesh.position.toArray().join(","));',
      answer: "set",
      check: { compiles: true, stdout: "1,2,3" },
      explain: L("set(x, y, z) changes the existing vector. You can also write one axis: mesh.position.x = 1.", "set(x, y, z) cambia el vector existente. También puedes escribir un eje: mesh.position.x = 1.", "set(x, y, z) で今のベクトルを書きかえる。mesh.position.x = 1 のように1軸ずつでもOK。"),
      win: [{ t: "tag", actor: "hero", text: "position", value: "1,2,3" }, { t: "print", text: "1,2,3" }],
    },
    say(L(
      "Rotation is in RADIANS, not degrees. A half turn is Math.PI. MathUtils.degToRad converts for you.",
      "La rotación va en RADIANES, no en grados. Media vuelta es Math.PI. MathUtils.degToRad convierte por ti.",
      "回転の単位は度じゃなくラジアン。半回転は Math.PI。MathUtils.degToRad で変換できるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "console.log(THREE.MathUtils.radToDeg(Math.PI / 2), THREE.MathUtils.degToRad(180) === Math.PI);",
      options: ["90 true", "1.5708 true", "90 false"],
      answer: 0,
      output: "90 true",
      check: { compiles: true, stdout: "90 true" },
      explain: L("PI/2 radians is a quarter turn: 90 degrees. 180 degrees is exactly Math.PI.", "PI/2 radianes es un cuarto de vuelta: 90 grados. 180 grados es exactamente Math.PI.", "PI/2 ラジアンは4分の1回転で90度。180度はちょうど Math.PI だよ。"),
    },
    {
      kind: "predict",
      prompt: COMPILES,
      code: IMP + "const mesh = new THREE.Mesh();\nmesh.rotation.y = 90;",
      options: [L("Yes, but it spins 90 radians", "Sí, pero gira 90 radianes", "はい、でも90ラジアン回る"), NO_TSC],
      answer: 0,
      check: { compiles: true },
      explain: L("It's a number, so tsc is happy. But 90 radians is about 14 full spins: a logic bug.", "Es un number, así que tsc está feliz. Pero 90 radianes son unas 14 vueltas: un bug de lógica.", "number だから tsc は通す。でも90ラジアンは約14回転。ロジックのバグだよ。"),
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: L("Dizzy! Hee!", "¡Mareo! ¡Ji!", "目が回る！") }],
    },
    say(L(
      "The pose is baked into a local matrix. three rebuilds it before each render, or when you call updateMatrix().",
      "La pose se guarda en una matriz local. three la reconstruye antes de cada render, o al llamar a updateMatrix().",
      "ポーズはローカル行列にまとめられる。描画の前か、updateMatrix() を呼んだ時に作り直されるよ。",
    )),
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const o = new THREE.Object3D();\no.position.set(1, 0, 0);\nconsole.log(o.matrix.elements[12]);\no.updateMatrix();\nconsole.log(o.matrix.elements[12]);",
      options: [L("0, then 1", "0, luego 1", "0 のあと 1"), L("1, then 1", "1, luego 1", "1 のあと 1"), L("0, then 0", "0, luego 0", "0 のあと 0")],
      answer: 0,
      output: "0\n1",
      check: { compiles: true, stdout: "0\n1" },
      explain: L("Changing position doesn't touch the matrix yet. updateMatrix() writes x into slot 12.", "Cambiar position aún no toca la matriz. updateMatrix() escribe x en la casilla 12.", "position を変えても行列はまだそのまま。updateMatrix() で x が12番に入るよ。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const a = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());\nconst b = a.clone();\nconsole.log(b.geometry === a.geometry, b.material === a.material, b.position === a.position);",
      options: ["true true false", "false false false", "true true true"],
      answer: 0,
      output: "true true false",
      check: { compiles: true, stdout: "true true false" },
      explain: L("clone() copies the pose but SHARES body and skin. Repaint one clone and all of them change color.", "clone() copia la pose pero COMPARTE cuerpo y piel. Repinta un clon y todos cambian de color.", "clone() はポーズをコピーし、からだと肌は共有する。1つを塗ると全部の色が変わるよ。"),
      setup: [{ t: "enter", actor: "ally" }, { t: "item", kind: "gem", holder: "hero" }],
      win: [{ t: "lend", to: "ally" }, { t: "print", text: "true true false" }],
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + "const o = new THREE.Object3D();\no.lookAt(5, 0, 0);\nconsole.log(o.rotation.y.toFixed(3));",
      options: ["1.571", "90.000", "5.000"],
      answer: 0,
      output: "1.571",
      check: { compiles: true, stdout: "1.571" },
      explain: L("lookAt turns the object toward a point. Facing +X is a quarter turn: PI/2 ≈ 1.571 radians.", "lookAt gira el objeto hacia un punto. Mirar a +X es un cuarto de vuelta: PI/2 ≈ 1.571 radianes.", "lookAt は物体を点の方へ向ける。+X を向くのは4分の1回転で PI/2 ≈ 1.571。"),
    },
    {
      kind: "predict",
      prompt: PRINT,
      code: IMP + 'const box = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1));\nbox.scale.set(2, 1, 1);\nbox.updateMatrixWorld();\nconst size = new THREE.Box3().setFromObject(box).getSize(new THREE.Vector3());\nconsole.log(size.toArray().join(","));',
      options: ["2,1,1", "2,2,2", "1,1,1"],
      answer: 0,
      output: "2,1,1",
      check: { compiles: true, stdout: "2,1,1" },
      explain: L("Scale works per axis: (2, 1, 1) makes it twice as wide, same height and depth.", "La escala va por eje: (2, 1, 1) lo hace el doble de ancho, misma altura y fondo.", "scale は軸ごと。(2, 1, 1) は幅だけ2倍で、高さと奥行きはそのまま。"),
      win: [{ t: "print", text: "2,1,1" }],
    },
    {
      kind: "run",
      prompt: L("Point the arm up: it must print tip 0.00 1.00", "Apunta el brazo arriba: debe imprimir tip 0.00 1.00", "腕を上へ：tip 0.00 1.00 と表示"),
      starter: IMP + "const arm = new THREE.Object3D();\narm.rotation.z = 90;\narm.updateMatrix();\nconst tip = new THREE.Vector3(1, 0, 0).applyMatrix4(arm.matrix);\nconsole.log(`tip ${tip.x.toFixed(2)} ${tip.y.toFixed(2)}`);\n",
      solution: IMP + "const arm = new THREE.Object3D();\narm.rotation.z = Math.PI / 2;\narm.updateMatrix();\nconst tip = new THREE.Vector3(1, 0, 0).applyMatrix4(arm.matrix);\nconsole.log(`tip ${tip.x.toFixed(2)} ${tip.y.toFixed(2)}`);\n",
      expect: "tip 0.00 1.00",
      fallback: [String.raw`rotation\.z\s*=\s*Math\.PI\s*/\s*2`, String.raw`rotation\.z\s*=\s*(THREE\.)?MathUtils\.degToRad\(\s*90\s*\)`, String.raw`rotation\.z\s*=\s*1\.57`],
      explain: L("90 is read as 90 radians. A quarter turn is Math.PI / 2, or MathUtils.degToRad(90).", "90 se lee como 90 radianes. Un cuarto de vuelta es Math.PI / 2, o MathUtils.degToRad(90).", "90 は90ラジアンとして読まれる。4分の1回転は Math.PI / 2 か degToRad(90) だよ。"),
    },
  ],
};

// ─── 1.4 Boss: Scene Gremlin ───────────────────────────────────────────────
const boss: LessonDef = {
  slug: "scene-gremlin",
  title: L("Boss: Scene Gremlin", "Jefe: Gremlin de Escena", "ボス：シーングレムリン"),
  concept: "scene_basics",
  mode: "boss",
  xp: 170,
  enemy: "threejs/leak-blob",
  enemyName: L("SCENE GREMLIN", "GREMLIN DE ESCENA", "シーングレムリン"),
  beats: [
    enemySays(L(
      "HEH! I switched off your lights, shrank your cameras and twisted every pose. Can you still frame a shot?",
      "¡JE! Apagué tus luces, encogí tus cámaras y torcí cada pose. ¿Aún sabes encuadrar una toma?",
      "ヘヘ！光を消して、カメラを縮めて、ポーズを全部ねじった。それでも絵を撮れるかな？",
    )),
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "const cam = new THREE.PerspectiveCamera(60);\nconsole.log(cam.fov, cam.aspect);", options: ["60 1", "60 undefined", "50 1"], answer: 0, output: "60 1", check: { compiles: true, stdout: "60 1" }, explain: L("Only fov was given; aspect keeps its default of 1.", "Solo se dio fov; aspect mantiene su valor por defecto de 1.", "fov だけ指定。aspect は初期値の1のまま。") },
    { kind: "predict", time: 12, prompt: L("Standard material, all black. Fix?", "Material Standard, todo negro. ¿Arreglo?", "Standard で真っ黒。直し方は？"), code: IMP + "const mat = new THREE.MeshStandardMaterial({ color: 0x3366ff });\nconst scene = new THREE.Scene();\nscene.add(new THREE.Mesh(new THREE.BoxGeometry(), mat));", options: [L("Add a light", "Agregar una luz", "ライトを足す"), L("Raise camera.far", "Subir camera.far", "far を増やす")], answer: 0, explain: L("Standard needs light to show its color. No light, no color.", "Standard necesita luz para mostrar su color. Sin luz, sin color.", "Standard は光がないと色が出ない。") },
    { kind: "predict", time: 12, prompt: COMPILES, code: IMP + "const mesh = new THREE.Mesh();\nmesh.scale = new THREE.Vector3(2, 2, 2);", options: [YES, NO_TSC], answer: 1, check: { compiles: false }, explain: L("TS2540: scale is read-only. Use mesh.scale.set(2, 2, 2).", "TS2540: scale es de solo lectura. Usa mesh.scale.set(2, 2, 2).", "TS2540：scale は読み取り専用。set(2, 2, 2) を使おう。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const m = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());\nconst c = m.clone();\nc.position.x = 5;\nconsole.log(m.position.x, c.geometry === m.geometry);", options: ["0 true", "5 true", "0 false"], answer: 0, output: "0 true", check: { compiles: true, stdout: "0 true" }, explain: L("Each clone has its own pose, but the geometry is shared.", "Cada clon tiene su propia pose, pero la geometría se comparte.", "ポーズはそれぞれ別、ジオメトリは共有。") },
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "const c = new THREE.Color(0x00ff00);\nconsole.log(c.g, c.getHexString());", options: ["1 00ff00", "255 00ff00", "1 #00ff00"], answer: 0, output: "1 00ff00", check: { compiles: true, stdout: "1 00ff00" }, explain: L("Channels go from 0 to 1, and the hex string has no #.", "Los canales van de 0 a 1 y el string hex no lleva #.", "チャンネルは0〜1、16進文字列に # はない。") },
    { kind: "pick", time: 12, prompt: L("After changing fov, call…", "Tras cambiar fov, llama a…", "fov を変えたら呼ぶのは…"), code: IMP + "const camera = new THREE.PerspectiveCamera();\ncamera.fov = 30;\ncamera.___();\nconsole.log(camera.projectionMatrix.elements[5].toFixed(2));", options: ["updateProjectionMatrix", "updateMatrixWorld"], answer: 0, check: { compiles: true, stdout: "3.73" }, explain: L("The projection matrix caches fov, aspect, near and far.", "La matriz de proyección guarda fov, aspect, near y far.", "射影行列が fov・aspect・near・far を覚えている。") },
    { kind: "predict", time: 12, prompt: PRINT, code: IMP + "console.log(THREE.MathUtils.degToRad(90).toFixed(4));", options: ["1.5708", "90.0000", "3.1416"], answer: 0, output: "1.5708", check: { compiles: true, stdout: "1.5708" }, explain: L("90 degrees is PI/2 radians ≈ 1.5708.", "90 grados son PI/2 radianes ≈ 1.5708.", "90度は PI/2 ラジアン ≈ 1.5708。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const g = new THREE.BoxGeometry(2, 2, 2);\nconst p = new THREE.PlaneGeometry(2, 2);\nconsole.log(g.index?.count, p.index?.count);", options: ["36 6", "12 2", "24 4"], answer: 0, output: "36 6", check: { compiles: true, stdout: "36 6" }, explain: L("Indices: 12 triangles × 3 for the box, 2 × 3 for the plane. Size doesn't change counts.", "Índices: 12 triángulos × 3 en la caja, 2 × 3 en el plano. El tamaño no cambia la cuenta.", "箱は12三角形×3、平面は2×3。大きさで数は変わらない。") },
    { kind: "type", time: 15, prompt: L("Grow it 3x in every direction", "Hazlo 3x más grande en todo", "全方向に3倍にしよう"), code: IMP + 'const mesh = new THREE.Mesh();\nmesh.scale.___(3);\nconsole.log(mesh.scale.toArray().join(","));', answer: "setScalar", check: { compiles: true, stdout: "3,3,3" }, explain: L("setScalar(3) sets x, y and z to 3 at once.", "setScalar(3) pone x, y y z en 3 a la vez.", "setScalar(3) で x・y・z を一度に3にする。") },
    { kind: "predict", time: 15, prompt: PRINT, code: IMP + "const o = new THREE.Object3D();\no.rotation.z = Math.PI;\no.updateMatrix();\nconst p = new THREE.Vector3(1, 0, 0).applyMatrix4(o.matrix);\nconsole.log(p.x.toFixed(2));", options: ["-1.00", "1.00", "0.00"], answer: 0, output: "-1.00", check: { compiles: true, stdout: "-1.00" }, explain: L("Math.PI is a half turn, so +X ends up at -X.", "Math.PI es media vuelta, así que +X termina en -X.", "Math.PI は半回転。+X は -X へ。") },
    enemySays(L(
      "Grr... lights on, cameras straight, poses fixed. The forest of parents and children awaits. You'll get lost there!",
      "Grr... luces encendidas, cámaras derechas, poses arregladas. El bosque de padres e hijos te espera. ¡Ahí te perderás!",
      "ぐぬぬ…光もカメラもポーズも元通り。次は親子の森だ。そこで迷子になるがいい！",
    )),
  ],
};

export const sceneVillage: RegionDef = {
  slug: "scene-village",
  name: L("Scene Village", "Aldea de la Escena", "シーン村"),
  subtitle: L("Scene · camera · mesh · transforms", "Escena · cámara · malla · transformar", "シーン・カメラ・メッシュ・変形"),
  theme: "village",
  lessons: [sceneCamera, meshes, transforms, boss],
};
