import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { enemySays, say } from "../helpers.ts";

// REGION 1 · ALDEA LET  (variables, mut, tipos, shadowing)

const letBasics: LessonDef = {
  slug: "hola-let",
  title: "¡Hola, let!",
  concept: "let",
  mode: "lesson",
  xp: 40,
  enemy: "slime",
  enemyName: "BUG SINTAXIS",
  beats: [
    say("¡Eh, aprendiz! Soy Ferro, sensei del código. En este reino el código ES magia."),
    say("Cada respuesta correcta golpea al BUG. ¡Derrótalo aprendiendo!"),
    {
      kind: "act",
      prompt: "Pulsa los botones. Mira cómo cada línea controla el mundo.",
      steps: [
        { label: "HABLAR", line: 'println!("¡Hola!");', effects: [{ t: "say", actor: "hero", text: "¡Hola!" }], output: "¡Hola!" },
        { label: "CREAR VIDA", line: "let vida = 3;", effects: [{ t: "tag", actor: "hero", text: "vida", value: "3" }, { t: "hp", actor: "hero", value: 3 }] },
        { label: "MOSTRAR VIDA", line: 'println!("{}", vida);', effects: [{ t: "say", actor: "hero", text: "¡Tengo 3!" }], output: "3" },
      ],
    },
    say("let crea una VARIABLE: una etiqueta con nombre pegada a un valor. vida → 3."),
    {
      kind: "pick",
      prompt: "Dale 5 de vida al héroe",
      code: "___ vida = 5;",
      options: ["let", "var", "set", "int"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: "En Rust las variables nacen con let. var e int son de otros lenguajes.",
      setup: [{ t: "untag", actor: "hero" }],
      win: [{ t: "tag", actor: "hero", text: "vida", value: "5" }, { t: "hp", actor: "hero", value: 5 }],
    },
    {
      kind: "pick",
      prompt: "Muestra el oro del héroe",
      code: 'let oro = 10;\nprintln!("{}", ___);',
      options: ["oro", '"oro"', "$oro", "10oro"],
      answer: 0,
      check: { compiles: true, stdout: "10" },
      explain: '"oro" con comillas compila, pero imprime el texto oro, no el 10. Sin comillas usas la variable.',
      setup: [{ t: "tag", actor: "hero", text: "oro", value: "10" }],
      win: [{ t: "print", text: "10" }, { t: "say", actor: "hero", text: "¡10 de oro!" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let x = 7;\nprintln!("x vale {}", x);',
      options: ["x vale 7", "x vale {}", "x vale x", "Error"],
      answer: 0,
      output: "x vale 7",
      check: { compiles: true, stdout: "x vale 7" },
      explain: "{} es un hueco que se rellena con el valor de x.",
    },
    say("Cada instrucción termina en punto y coma ;  ¡Es el cierre del hechizo!"),
    {
      kind: "type",
      prompt: "Escribe la palabra que crea variables",
      code: "___ escudo = 2;",
      answer: "let",
      check: { compiles: true },
      explain: "let + nombre + = + valor + ;",
      win: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "escudo", value: "2" }],
    },
    {
      kind: "order",
      prompt: "Arma el programa: todo empieza en fn main()",
      lines: ["fn main() {", "    let nivel = 1;", '    println!("{}", nivel);', "}"],
      explain: "Primero abres main, luego creas la variable, la usas y cierras la llave.",
      win: [{ t: "print", text: "1" }],
    },
    {
      kind: "run",
      prompt: "¡Tu primer programa REAL! Haz que imprima: Hola, Rust",
      starter: 'fn main() {\n    println!("escribe aquí");\n}\n',
      expect: "Hola, Rust",
      solution: 'fn main() {\n    println!("Hola, Rust");\n}\n',
      fallback: [
        String.raw`print(ln)?!\s*\(\s*"Hola, Rust(\\n)?"\s*\)`,
        String.raw`print(ln)?!\s*\(\s*"Hola, \{\}"\s*,\s*"Rust"\s*\)`,
        String.raw`print(ln)?!\s*\(\s*"\{\}"\s*,\s*"Hola, Rust"\s*\)`,
      ],
      explain: "Cambia el texto entre comillas por Hola, Rust",
      win: [{ t: "say", actor: "hero", text: "¡Hola, Rust!" }],
    },
  ],
};

const mutLesson: LessonDef = {
  slug: "mut",
  title: "mut: cambiar",
  concept: "mut",
  mode: "lesson",
  xp: 50,
  enemy: "slime",
  enemyName: "BUG CONGELADO",
  beats: [
    say("En Rust las variables son INMUTABLES por defecto. Una vez creadas... ¡no cambian!"),
    {
      kind: "act",
      prompt: "Intenta curar al héroe",
      steps: [
        { label: "CREAR VIDA", line: "let vida = 3;", effects: [{ t: "tag", actor: "hero", text: "vida", value: "3" }, { t: "hp", actor: "hero", value: 3 }] },
        {
          label: "CURAR",
          line: "vida = 5;",
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: "¿¡Eh!?" }],
          error: { compiler: "error[E0384]: cannot assign twice to immutable variable `vida`", plain: "vida no es mutable: no puede cambiar." },
        },
      ],
    },
    say("Para que pueda cambiar, añade mut al crearla. mut = mutable."),
    {
      kind: "act",
      prompt: "Ahora con mut",
      setup: [{ t: "untag", actor: "hero" }],
      steps: [
        { label: "CREAR VIDA", line: "let mut vida = 3;", effects: [{ t: "tag", actor: "hero", text: "mut vida", value: "3" }, { t: "hp", actor: "hero", value: 3 }] },
        { label: "CURAR", line: "vida = 5;", effects: [{ t: "hp", actor: "hero", value: 5 }, { t: "value", actor: "hero", text: "5" }, { t: "banner", text: "¡CURADO!" }] },
      ],
    },
    {
      kind: "pick",
      prompt: "El bug ataca. Haz que la vida pueda bajar",
      code: "let ___ vida = 5;\nvida = vida - 1;",
      options: ["mut", "var", "const", "&"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: "Sin mut, la segunda línea no compila.",
      setup: [{ t: "tag", actor: "hero", text: "vida", value: "5" }, { t: "hp", actor: "hero", value: 5 }],
      win: [{ t: "attack", from: "enemy", to: "hero" }, { t: "hp", actor: "hero", value: 4 }, { t: "value", actor: "hero", text: "4" }],
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: "let oro = 10;\noro = 20;",
      options: ["Sí: oro vale 20", "No: oro no es mut", "Sí: oro vale 10", "No: falta tipo"],
      answer: 1,
      check: { compiles: false },
      explain: "error[E0384]: oro es inmutable. Necesita let mut oro.",
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let mut c = 1;\nc = c + 1;\nc = c * 10;\nprintln!("{}", c);',
      options: ["1", "2", "20", "11"],
      answer: 2,
      output: "20",
      check: { compiles: true, stdout: "20" },
      explain: "1 → 2 → 20. Cada línea actualiza c.",
    },
    {
      kind: "type",
      prompt: "Haz mutable el contador de combo",
      code: "let ___ combo = 0;",
      answer: "mut",
      check: { compiles: true },
      explain: "let mut nombre = valor;",
    },
    {
      kind: "pick",
      prompt: "Suma 3 al daño de un golpe",
      code: "let mut dmg = 0;\ndmg ___ 3;",
      options: ["+=", "=+", "++", "=="],
      answer: 0,
      check: { compiles: true },
      explain: "+= suma y asigna. Rust no tiene ++, y == solo compara: compila, pero dmg sigue en 0.",
      win: [{ t: "banner", text: "DMG +3" }],
    },
    say("Inmutable por defecto te protege de cambios accidentales. Usa mut solo cuando LO NECESITES."),
    {
      kind: "run",
      prompt: "Este código no compila. Arréglalo para que imprima 3",
      starter: "fn main() {\n    let contador = 0;\n    contador += 1;\n    contador += 1;\n    contador += 1;\n    println!(\"{}\", contador);\n}\n",
      expect: "3",
      solution: 'fn main() {\n    let mut contador = 0;\n    contador += 1;\n    contador += 1;\n    contador += 1;\n    println!("{}", contador);\n}\n',
      fallback: [
        String.raw`let\s+mut\s+contador\b`,
        String.raw`let\s+contador\s*=\s*contador\s*\+\s*1\s*;`,
      ],
      explain: "contador necesita ser mut para poder sumarle.",
    },
  ],
};

const typesLesson: LessonDef = {
  slug: "tipos-sombras",
  title: "Tipos y sombras",
  concept: "types",
  mode: "lesson",
  xp: 50,
  enemy: "ghost",
  enemyName: "BUG FANTASMA",
  beats: [
    say("Cada valor tiene un TIPO. i32 = entero · f64 = decimal · bool = sí/no · &str = texto."),
    {
      kind: "act",
      prompt: "Crea al héroe con tipos explícitos",
      steps: [
        { label: "VIDA", line: "let vida: i32 = 3;", effects: [{ t: "tag", actor: "hero", text: "vida: i32", value: "3" }] },
        { label: "VELOCIDAD", line: "let vel: f64 = 1.5;", effects: [{ t: "tag", actor: "hero", text: "vel: f64", value: "1.5" }, { t: "say", actor: "hero", text: "¡Zum!" }] },
        { label: "VIVO", line: "let vivo: bool = true;", effects: [{ t: "tag", actor: "hero", text: "vivo: bool", value: "true" }] },
        { label: "NOMBRE", line: 'let nombre: &str = "Ferris";', effects: [{ t: "tag", actor: "hero", text: "nombre: &str", value: '"Ferris"' }, { t: "say", actor: "hero", text: "¡Soy Ferris!" }] },
      ],
    },
    {
      kind: "pick",
      prompt: "Elige el tipo para 42 monedas",
      code: "let monedas: ___ = 42;",
      options: ["i32", "f64", "bool", "&str"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: "42 es un entero: i32.",
      win: [{ t: "tag", actor: "hero", text: "monedas", value: "42" }],
    },
    {
      kind: "pick",
      prompt: "Elige el tipo para 3.14",
      code: "let pi: ___ = 3.14;",
      options: ["i32", "f64", "bool", "char"],
      answer: 1,
      check: { compiles: true, wrongFail: true },
      explain: "Con punto decimal es f64.",
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'let x: i32 = "hola";',
      options: ["Sí", 'No: "hola" no es i32'],
      answer: 1,
      check: { compiles: false },
      explain: "error[E0308]: mismatched types. El tipo y el valor deben coincidir.",
    },
    say("Truco ninja: SHADOWING. Repite let con el mismo nombre y creas una variable NUEVA que tapa a la anterior."),
    {
      kind: "act",
      prompt: "Duplica el poder con shadowing",
      setup: [{ t: "untag", actor: "hero" }],
      steps: [
        { label: "PODER", line: "let poder = 5;", effects: [{ t: "tag", actor: "hero", text: "poder", value: "5" }] },
        { label: "SOMBRA x2", line: "let poder = poder * 2;", effects: [{ t: "value", actor: "hero", text: "10" }, { t: "banner", text: "¡SOMBRA!" }] },
        { label: "MOSTRAR", line: 'println!("{}", poder);', output: "10" },
      ],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let x = 5;\nlet x = x + 1;\nlet x = x * 2;\nprintln!("{}", x);',
      options: ["5", "6", "12", "11"],
      answer: 2,
      output: "12",
      check: { compiles: true, stdout: "12" },
      explain: "5 → 6 → 12. Cada let crea una x nueva.",
    },
    {
      kind: "predict",
      prompt: "Shadowing puede cambiar el tipo. ¿Compila?",
      code: 'let espacios = "   ";\nlet espacios = espacios.len();',
      options: ["Sí: es una variable nueva", "No: cambia de tipo"],
      answer: 0,
      check: { compiles: true },
      explain: "Con let creas otra variable, así que puede tener otro tipo. Con mut no podrías.",
    },
    {
      kind: "type",
      prompt: "Escribe el tipo booleano",
      code: "let listo: ___ = false;",
      answer: "bool",
      check: { compiles: true },
      explain: "true y false son de tipo bool.",
    },
    {
      kind: "run",
      prompt: "Usa shadowing para que imprima: Nivel 2",
      starter: 'fn main() {\n    let nivel = 1;\n    // usa shadowing aquí\n    println!("Nivel {}", nivel);\n}\n',
      expect: "Nivel 2",
      solution: 'fn main() {\n    let nivel = 1;\n    let nivel = nivel + 1;\n    println!("Nivel {}", nivel);\n}\n',
      fallback: [
        String.raw`let\s+nivel\s*(:\s*\w+\s*)?=\s*(nivel\s*\+\s*1|1\s*\+\s*nivel|nivel\s*\*\s*2|2\s*\*\s*nivel|nivel\s*\+\s*nivel)\s*;`,
        String.raw`let\s+nivel\s*(:\s*\w+\s*)?=\s*2\s*;`,
      ],
      explain: "Añade: let nivel = nivel + 1;",
    },
  ],
};

const boss1: LessonDef = {
  slug: "jefe-golem",
  title: "JEFE: Golem Inmutable",
  concept: "let",
  mode: "boss",
  xp: 120,
  enemy: "golem",
  enemyName: "GOLEM INMUTABLE",
  beats: [
    enemySays("¡GRRR! En mi aldea NADA cambia. ¡Demuestra lo que sabes!"),
    { kind: "pick", time: 12, prompt: "¡Rápido! Crea la variable", code: "___ x = 1;", options: ["let", "var", "new"], answer: 0, check: { compiles: true, wrongFail: true }, explain: "let crea variables." },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "let a = 1;\na = 2;", options: ["Sí", "No"], answer: 1, check: { compiles: false }, explain: "a no es mut." },
    { kind: "type", time: 12, prompt: "Hazla mutable", code: "let ___ hp = 9;", answer: "mut", check: { compiles: true }, explain: "let mut" },
    { kind: "predict", time: 12, prompt: "¿Qué imprime?", code: 'let n = 2;\nlet n = n * n;\nprintln!("{}", n);', options: ["2", "4", "Error"], answer: 1, output: "4", check: { compiles: true, stdout: "4" }, explain: "Shadowing: n nueva = 4." },
    { kind: "pick", time: 12, prompt: "Tipo para 0.5", code: "let p: ___ = 0.5;", options: ["i32", "f64", "bool"], answer: 1, check: { compiles: true, wrongFail: true }, explain: "Decimal → f64." },
    { kind: "pick", time: 12, prompt: "Suma 10", code: "let mut oro = 0;\noro ___ 10;", options: ["+=", "++", "=+"], answer: 0, check: { compiles: true, wrongFail: true }, explain: "+=" },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "let v: bool = 1;", options: ["Sí", "No"], answer: 1, check: { compiles: false }, explain: "1 es i32, no bool." },
    { kind: "type", time: 15, prompt: "Tipo de texto prestado", code: 'let s: ___ = "hola";', answer: "&str", check: { compiles: true }, explain: "Los literales de texto son &str." },
    enemySays("¡Imposible...! Mi roca... se... desmorona..."),
  ],
};

export const aldeaLet: RegionDef = {
  slug: "aldea-let",
  name: "Aldea Let",
  subtitle: "Variables · mut · tipos",
  theme: "village",
  lessons: [letBasics, mutLesson, typesLesson, boss1],
};
