import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { enemySays, say } from "../helpers.ts";

// REGION 2 · BOSQUE OWNERSHIP  (move, clone, borrowing)

const ownership: LessonDef = {
  slug: "un-solo-dueno",
  title: "Un solo dueño",
  concept: "ownership",
  mode: "lesson",
  xp: 60,
  enemy: "slime",
  enemyName: "BUG LADRÓN",
  beats: [
    say("Bienvenido al Bosque del Ownership. Aquí rige la LEY DEL DUEÑO."),
    say("Regla 1: cada valor tiene UN SOLO dueño. Mira esta espada (un String)."),
    {
      kind: "act",
      prompt: "Pulsa en orden y observa la espada",
      steps: [
        { label: "FORJAR", line: 'let a = String::from("espada");', effects: [{ t: "item", kind: "sword", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }] },
        { label: "DAR A b", line: "let b = a;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "give", to: "ally" }, { t: "dead", actor: "hero" }] },
        {
          label: "USAR a",
          line: 'println!("{}", a);',
          effects: [{ t: "shake" }, { t: "say", actor: "hero", text: "¡Ya no la tengo!" }],
          error: { compiler: "error[E0382]: borrow of moved value: `a`", plain: "a ya no es dueña: la espada se MOVIÓ a b." },
        },
      ],
    },
    say("Eso es un MOVE. Con let b = a; la propiedad pasa a b. a queda inválida para siempre."),
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'let s1 = String::from("gema");\nlet s2 = s1;\nprintln!("{}", s1);',
      options: ["Sí: imprime gema", "No: s1 se movió a s2"],
      answer: 1,
      check: { compiles: false },
      explain: "Tras el move, usar s1 es error E0382.",
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "s1" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "s2" }, { t: "give", to: "ally" }, { t: "dead", actor: "hero" }],
    },
    {
      kind: "pick",
      prompt: "Usa la variable que SÍ es dueña",
      code: 'let a = String::from("poción");\nlet b = a;\nprintln!("{}", ___);',
      options: ["b", "a", "&a"],
      answer: 0,
      check: { compiles: true, stdout: "poción", wrongFail: true },
      explain: "La poción ahora es de b.",
      setup: [{ t: "item", kind: "potion", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "give", to: "ally" }, { t: "dead", actor: "hero" }],
      win: [{ t: "say", actor: "ally", text: "¡poción!" }, { t: "print", text: "poción" }],
    },
    say("Regla 2: cuando el dueño sale de su bloque { }, el valor se DESTRUYE (drop). ¡Sin recolector de basura!"),
    {
      kind: "act",
      prompt: "Mira qué pasa al cerrar el bloque",
      setup: [],
      steps: [
        { label: "ABRIR BLOQUE", line: "{" },
        { label: "CREAR", line: '    let gema = String::from("gema");', effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "gema" }] },
        { label: "CERRAR", line: "} // gema sale del bloque", effects: [{ t: "drop" }, { t: "untag", actor: "hero" }, { t: "banner", text: "DROP!" }] },
      ],
    },
    say("Ojo: los números (i32, bool...) se COPIAN, no se mueven. Son baratos de duplicar."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let x = 5;\nlet y = x;\nprintln!("{} {}", x, y);',
      options: ["5 5", "Error: x movida", "5 0"],
      answer: 0,
      output: "5 5",
      check: { compiles: true, stdout: "5 5" },
      explain: "i32 es Copy: x sigue siendo válida.",
    },
    {
      kind: "predict",
      prompt: "Pasar un String a una función, ¿lo mueve?",
      code: 'fn tomar(s: String) {}\n\nlet s = String::from("hola");\ntomar(s);\nprintln!("{}", s);',
      options: ["Imprime hola", "Error: s se movió a tomar"],
      answer: 1,
      check: { compiles: false },
      explain: "Pasar por valor también es un move.",
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "s" }],
      win: [{ t: "give", to: "enemy" }, { t: "dead", actor: "hero" }, { t: "say", actor: "enemy", text: "¡Mío!" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Excalibur",
      starter: 'fn main() {\n    let espada = String::from("Excalibur");\n    let heroe = espada;\n    println!("{}", espada);\n}\n',
      expect: "Excalibur",
      solution: 'fn main() {\n    let espada = String::from("Excalibur");\n    let heroe = espada;\n    println!("{}", heroe);\n}\n',
      fallback: [
        String.raw`println!\s*\(\s*"\{\}"\s*,\s*heroe\s*\)`,
        String.raw`println!\s*\(\s*"\{heroe\}"\s*\)`,
        String.raw`espada\s*\.\s*clone\s*\(\s*\)`,
        String.raw`let\s+heroe\s*=\s*&\s*espada\s*;`,
      ],
      explain: "Imprime la variable que es dueña: heroe.",
    },
  ],
};

const cloneLesson: LessonDef = {
  slug: "clone",
  title: "clone: duplicar",
  concept: "clone",
  mode: "lesson",
  xp: 60,
  enemy: "ghost",
  enemyName: "BUG ESPEJO",
  beats: [
    say("¿Y si AMBOS necesitan la espada? .clone() forja una copia nueva y completa."),
    {
      kind: "act",
      prompt: "Clona la espada",
      steps: [
        { label: "FORJAR", line: 'let a = String::from("espada");', effects: [{ t: "item", kind: "sword", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }] },
        { label: "CLONAR", line: "let b = a.clone();", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "clone", to: "ally" }, { t: "banner", text: "¡CLON!" }] },
        { label: "USAR AMBAS", line: 'println!("{} {}", a, b);', effects: [{ t: "say", actor: "hero", text: "¡Mía!" }, { t: "say", actor: "ally", text: "¡Y mía!" }], output: "espada espada" },
      ],
    },
    {
      kind: "pick",
      prompt: "Que ambos tengan el mapa",
      code: 'let a = String::from("mapa");\nlet b = a.___;\nprintln!("{} {}", a, b);',
      options: ["clone()", "copy()", "dup()", "move()"],
      answer: 0,
      check: { compiles: true, stdout: "mapa mapa", wrongFail: true },
      explain: ".clone() duplica el String.",
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "clone", to: "ally" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let a = String::from("oro");\nlet b = a.clone();\nprintln!("{}", a);',
      options: ["oro", "Error: a movida"],
      answer: 0,
      output: "oro",
      check: { compiles: true, stdout: "oro" },
      explain: "clone no mueve: a sigue siendo dueña de su oro.",
    },
    say("Clonar cuesta: copia toda la memoria. Úsalo con intención, no para callar al compilador."),
    say("Los tipos simples (i32, f64, bool, char) son Copy: se duplican solos al asignar."),
    {
      kind: "pick",
      prompt: "¿Qué tipo se MUEVE al asignar?",
      code: "let b = a; // a es de tipo ___",
      options: ["String", "i32", "bool", "char"],
      answer: 0,
      check: { program: "#![allow(unused)]\nfn main() {\n    let a = String::from(\"x\");\n    let b = a;\n    println!(\"{}\", a);\n}\n", compiles: false },
      explain: "String guarda datos en el heap: se mueve. Los demás son Copy.",
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let a = true;\nlet b = a;\nprintln!("{} {}", a, b);',
      options: ["true true", "Error"],
      answer: 0,
      output: "true true",
      check: { compiles: true, stdout: "true true" },
      explain: "bool es Copy.",
    },
    {
      kind: "type",
      prompt: "Escribe el método que duplica",
      code: "let copia = original.___();",
      answer: "clone",
      check: { program: "#![allow(unused)]\nfn main() {\n    let original = String::from(\"x\");\n    let copia = original.clone();\n    println!(\"{} {}\", original, copia);\n}\n", compiles: true, stdout: "x x" },
      explain: "original.clone()",
    },
    {
      kind: "order",
      prompt: "Ordena: crear, clonar y usar ambos",
      lines: ['let a = String::from("pan");', "let b = a.clone();", 'println!("{} {}", a, b);'],
      explain: "No puedes clonar algo que aún no existe.",
      win: [{ t: "print", text: "pan pan" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo para que imprima: escudo y escudo",
      starter: 'fn main() {\n    let a = String::from("escudo");\n    let b = a;\n    println!("{} y {}", a, b);\n}\n',
      expect: "escudo y escudo",
      solution: 'fn main() {\n    let a = String::from("escudo");\n    let b = a.clone();\n    println!("{} y {}", a, b);\n}\n',
      fallback: [
        String.raw`a\s*\.\s*clone\s*\(\s*\)`,
        String.raw`let\s+b\s*=\s*&\s*a\s*;`,
        String.raw`println!\s*\(\s*"\{\} y \{\}"\s*,\s*b\s*,\s*b\s*\)`,
      ],
      explain: "Usa a.clone() para que a no se mueva.",
    },
  ],
};

const borrowLesson: LessonDef = {
  slug: "prestamos",
  title: "Préstamos & y &mut",
  concept: "borrowing",
  mode: "lesson",
  xp: 70,
  enemy: "slime",
  enemyName: "BUG CADENA",
  beats: [
    say("Clonar es caro. Mejor PRESTAR: con & das una referencia. El dueño sigue siendo dueño."),
    {
      kind: "act",
      prompt: "Presta la espada",
      steps: [
        { label: "FORJAR", line: 'let a = String::from("espada");', effects: [{ t: "item", kind: "sword", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }] },
        { label: "PRESTAR", line: "let r = &a;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r = &a" }, { t: "lend", to: "ally" }] },
        { label: "USAR AMBOS", line: 'println!("{} {}", a, r);', effects: [{ t: "say", actor: "hero", text: "¡Sigue siendo mía!" }], output: "espada espada" },
      ],
    },
    {
      kind: "pick",
      prompt: "Presta la gema sin perderla",
      code: 'fn mirar(s: &String) {}\n\nlet a = String::from("gema");\nmirar(___);\nprintln!("{}", a);',
      options: ["&a", "a", "*a", "mut a"],
      answer: 0,
      check: { compiles: true, stdout: "gema", wrongFail: true },
      explain: "Con &a prestas. Con a la moverías.",
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }, { t: "enter", actor: "ally" }],
      win: [{ t: "lend", to: "ally" }, { t: "print", text: "gema" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'fn largo(s: &String) -> usize { s.len() }\n\nlet a = String::from("hola");\nlet n = largo(&a);\nprintln!("{} {}", a, n);',
      options: ["hola 4", "Error: a movida", "hola 0"],
      answer: 0,
      output: "hola 4",
      check: { compiles: true, stdout: "hola 4" },
      explain: "largo solo pidió prestado: a sigue siendo válida.",
    },
    say("Para MODIFICAR algo prestado usa &mut. Y el dueño también debe ser mut."),
    {
      kind: "act",
      prompt: "Mejora la espada prestada",
      setup: [],
      steps: [
        { label: "FORJAR", line: 'let mut a = String::from("espada");', effects: [{ t: "item", kind: "sword", holder: "hero" }, { t: "tag", actor: "hero", text: "mut a" }] },
        { label: "PRESTAR MUT", line: "let r = &mut a;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r = &mut a" }, { t: "lend", to: "ally", mut: true }] },
        { label: "MEJORAR", line: 'r.push_str("+1");', effects: [{ t: "say", actor: "ally", text: "¡Forjada!" }, { t: "value", actor: "hero", text: "espada+1" }, { t: "banner", text: "ESPADA +1" }] },
      ],
    },
    {
      kind: "pick",
      prompt: "Préstalo para modificarlo",
      code: 'let mut s = String::from("lv");\nlet r = ___ s;\nr.push_str("2");',
      options: ["&mut", "&", "mut", "*"],
      answer: 0,
      check: { compiles: true, wrongFail: true },
      explain: "& solo permite leer. &mut permite modificar.",
    },
    say("LA GRAN REGLA: muchos & a la vez, O un solo &mut. Nunca ambos al mismo tiempo."),
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'let mut s = String::from("x");\nlet r1 = &mut s;\nlet r2 = &mut s;\nprintln!("{} {}", r1, r2);',
      options: ["Sí", "No: dos &mut a la vez"],
      answer: 1,
      check: { compiles: false },
      explain: "error[E0499]: solo puede haber un &mut activo.",
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'let s = String::from("x");\nlet r1 = &s;\nlet r2 = &s;\nprintln!("{} {}", r1, r2);',
      options: ["Sí: imprime x x", "No"],
      answer: 0,
      output: "x x",
      check: { compiles: true, stdout: "x x" },
      explain: "Muchos lectores & a la vez están permitidos.",
    },
    {
      kind: "type",
      prompt: "Escribe el tipo de referencia mutable",
      code: "fn subir(n: ___ i32) { *n += 1; }",
      answer: "&mut",
      check: { compiles: true },
      explain: "&mut i32 permite modificar el entero prestado.",
    },
    {
      kind: "run",
      prompt: "Arréglalo: el héroe debe llegar a Nivel 2",
      starter: "fn subir_nivel(nivel: &mut i32) {\n    *nivel += 1;\n}\n\nfn main() {\n    let nivel = 1;\n    subir_nivel(nivel);\n    println!(\"Nivel {}\", nivel);\n}\n",
      expect: "Nivel 2",
      solution: 'fn subir_nivel(nivel: &mut i32) {\n    *nivel += 1;\n}\n\nfn main() {\n    let mut nivel = 1;\n    subir_nivel(&mut nivel);\n    println!("Nivel {}", nivel);\n}\n',
      fallback: [
        String.raw`let\s+mut\s+nivel[\s\S]*subir_nivel\s*\(\s*&mut\s+nivel\s*\)`,
        String.raw`let\s+mut\s+nivel\b[\s\S]*&\s*mut\s+nivel\b`,
      ],
      explain: "nivel debe ser mut y debes pasar &mut nivel.",
    },
  ],
};

const boss2: LessonDef = {
  slug: "jefe-dragon",
  title: "JEFE: Dragón Borrow",
  concept: "borrowing",
  mode: "boss",
  xp: 150,
  enemy: "dragon",
  enemyName: "DRAGÓN BORROW",
  beats: [
    enemySays("¡SOY EL BORROW CHECKER! Ningún valor escapa de mis reglas. ¡En guardia!"),
    { kind: "predict", time: 12, prompt: "¿Compila?", code: 'let a = String::from("x");\nlet b = a;\nprintln!("{}", a);', options: ["Sí", "No"], answer: 1, check: { compiles: false }, explain: "a se movió." },
    { kind: "pick", time: 12, prompt: "Presta sin mover", code: "mirar(___);", options: ["&a", "a", "*a"], answer: 0, check: { program: "#![allow(unused)]\nfn mirar(s: &String) {}\n\nfn main() {\n    let a = String::from(\"x\");\n    mirar(&a);\n    println!(\"{}\", a);\n}\n", compiles: true, stdout: "x" }, explain: "&a presta." },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "let x = 5;\nlet y = x;\nprintln!(\"{}\", x);", options: ["Sí", "No"], answer: 0, check: { compiles: true, stdout: "5" }, explain: "i32 es Copy." },
    { kind: "type", time: 12, prompt: "Duplica el String", code: "let b = a.___();", answer: "clone", check: { program: "#![allow(unused)]\nfn main() {\n    let a = String::from(\"x\");\n    let b = a.clone();\n    println!(\"{} {}\", a, b);\n}\n", compiles: true, stdout: "x x" }, explain: "a.clone()" },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "let mut s = String::new();\nlet a = &mut s;\nlet b = &mut s;\na.push('!');", options: ["Sí", "No"], answer: 1, check: { compiles: false }, explain: "Dos &mut vivos a la vez." },
    { kind: "pick", time: 12, prompt: "Para modificar lo prestado", code: "fn f(s: ___ String) {}", options: ["&mut", "&", "mut"], answer: 0, check: { program: "#![allow(unused)]\nfn f(s: &mut String) {\n    s.push('!');\n}\n\nfn main() {\n    let mut s = String::from(\"x\");\n    f(&mut s);\n    println!(\"{}\", s);\n}\n", compiles: true, stdout: "x!" }, explain: "&mut String" },
    { kind: "predict", time: 12, prompt: "Al cerrar } el dueño...", code: '{\n    let s = String::from("x");\n} // ¿qué pasa con s?', options: ["Se destruye (drop)", "Sigue viva", "Se copia"], answer: 0, check: { program: "#![allow(unused)]\nstruct S;\nimpl Drop for S {\n    fn drop(&mut self) {\n        println!(\"drop\");\n    }\n}\n\nfn main() {\n    {\n        let s = S;\n        println!(\"dentro\");\n    } // s sale del bloque\n    println!(\"fuera\");\n}\n", compiles: true, stdout: "dentro\ndrop\nfuera" }, explain: "Fin del bloque → drop." },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: 'let s = String::from("x");\nlet r1 = &s;\nlet r2 = &s;\nprintln!("{}{}", r1, r2);', options: ["Sí", "No"], answer: 0, check: { compiles: true, stdout: "xx" }, explain: "Varios & están bien." },
    { kind: "type", time: 15, prompt: "Pasa nivel para modificarlo", code: "subir(___ nivel);", answer: "&mut", check: { program: "#![allow(unused)]\nfn subir(n: &mut i32) {\n    *n += 1;\n}\n\nfn main() {\n    let mut nivel = 1;\n    subir(&mut nivel);\n    println!(\"{}\", nivel);\n}\n", compiles: true, stdout: "2" }, explain: "subir(&mut nivel)" },
    enemySays("Grrr... respetaste todas mis reglas... El bosque es tuyo, rustáceo."),
  ],
};

export const bosqueOwnership: RegionDef = {
  slug: "bosque-ownership",
  name: "Bosque Ownership",
  subtitle: "Move · clone · préstamos",
  theme: "forest",
  lessons: [ownership, cloneLesson, borrowLesson, boss2],
};
