import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { enemySays, say } from "../helpers.ts";

// REGION 4 · CASTILLO TRAITS  (struct + impl, traits, métodos por defecto, genéricos y bounds,
// derive y traits estándar, Display, trait objects con dyn)

// Contrato y personajes compartidos por las lecciones 2 y 4 (y el jefe).
const HAB =
  'trait Habilidad {\n    fn usar(&self) -> String;\n}\n\nstruct Mago;\nimpl Habilidad for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\n\nstruct Arquero;\nimpl Habilidad for Arquero {\n    fn usar(&self) -> String { String::from("¡Flecha!") }\n}\n';

/** Programa completo: el contrato Habilidad + Mago + Arquero, y `body` dentro de main. */
const conHab = (body: string, extra = "") =>
  `#![allow(unused)]\n${HAB}${extra}\nfn main() {\n${body.split("\n").map((l) => "    " + l).join("\n")}\n}\n`;

const PRESENTAR = 'fn presentar<T: Habilidad>(x: &T) {\n    println!("{}", x.usar());\n}\n';

const contrato: LessonDef = {
  slug: "contrato-habilidad",
  title: "El contrato Habilidad",
  concept: "traits",
  mode: "lesson",
  xp: 70,
  enemy: "slime",
  enemyName: "BUG IMPOSTOR",
  beats: [
    say("Bienvenido al Castillo Traits. Aquí cada personaje aprende HABILIDADES, y cada uno las usa a su manera."),
    say("Antes, una herramienta: struct agrupa datos e impl le da MÉTODOS, funciones que reciben &self."),
    {
      kind: "act",
      prompt: "Crea un Mago con un método",
      setup: [],
      steps: [
        { label: "DEFINIR", line: "struct Mago { nombre: String }", effects: [{ t: "enter", actor: "hero" }, { t: "banner", text: "struct Mago" }] },
        { label: "ABRIR impl", line: "impl Mago {" },
        { label: "MÉTODO", line: '    fn saludar(&self) -> String { format!("Soy {}", self.nombre) }', effects: [{ t: "item", kind: "scroll", holder: "hero" }] },
        { label: "CERRAR", line: "}" },
        { label: "CREAR", line: 'let m = Mago { nombre: String::from("Ada") };', effects: [{ t: "tag", actor: "hero", text: "m: Mago" }] },
        { label: "LLAMAR", line: 'println!("{}", m.saludar());', effects: [{ t: "say", actor: "hero", text: "¡Soy Ada!" }], output: "Soy Ada" },
      ],
    },
    {
      kind: "pick",
      prompt: "El método toma prestado al Mago",
      code: 'struct Mago { nombre: String }\nimpl Mago {\n    fn saludar(___) -> String { format!("Soy {}", self.nombre) }\n}\nlet m = Mago { nombre: String::from("Ada") };\nprintln!("{}", m.saludar());',
      options: ["&self", "&Mago", "this"],
      answer: 0,
      explain: "&self es un préstamo del valor sobre el que llamas: m.saludar().",
      check: { compiles: true, stdout: "Soy Ada", wrongFail: true },
      setup: [{ t: "tag", actor: "hero", text: "m: Mago" }],
      win: [{ t: "say", actor: "hero", text: "¡Soy Ada!" }, { t: "print", text: "Soy Ada" }],
    },
    say("Un TRAIT es un contrato: una lista de métodos. Quien lo implementa gana la insignia."),
    {
      kind: "act",
      prompt: "Dos personajes firman el mismo contrato",
      setup: [],
      steps: [
        { label: "CONTRATO", line: "trait Habilidad { fn usar(&self) -> String; }", effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "banner", text: "TRAIT Habilidad" }] },
        { label: "PERSONAJES", line: "struct Mago;\nstruct Arquero;", effects: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }] },
        { label: "MAGO FIRMA", line: 'impl Habilidad for Mago { fn usar(&self) -> String { String::from("¡Fuego!") } }', effects: [{ t: "say", actor: "hero", text: "¡Firmado!" }] },
        { label: "ARQUERO FIRMA", line: 'impl Habilidad for Arquero { fn usar(&self) -> String { String::from("¡Flecha!") } }', effects: [{ t: "clone", to: "ally" }, { t: "say", actor: "ally", text: "¡Yo también!" }] },
        { label: "USAR", line: 'println!("{} {}", Mago.usar(), Arquero.usar());', effects: [{ t: "say", actor: "hero", text: "¡Fuego!" }, { t: "say", actor: "ally", text: "¡Flecha!" }], output: "¡Fuego! ¡Flecha!" },
      ],
    },
    say("Mismo contrato, distinto estilo. El trait dice QUÉ se puede hacer; cada impl decide CÓMO."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'impl Habilidad for Mago { fn usar(&self) -> String { String::from("¡Fuego!") } }\nimpl Habilidad for Arquero { fn usar(&self) -> String { String::from("¡Flecha!") } }\nprintln!("{}", Arquero.usar());',
      options: ["¡Flecha!", "¡Fuego!", "Error: hay dos usar()"],
      answer: 0,
      output: "¡Flecha!",
      explain: "Cada tipo tiene su propio usar(). Arquero responde con el suyo.",
      check: { program: conHab('println!("{}", Arquero.usar());'), compiles: true, stdout: "¡Flecha!" },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }],
      win: [{ t: "say", actor: "ally", text: "¡Flecha!" }, { t: "print", text: "¡Flecha!" }],
    },
    {
      kind: "predict",
      prompt: "El Mago firma pero no cumple. ¿Compila?",
      code: "trait Habilidad { fn usar(&self) -> String; }\nstruct Mago;\nimpl Habilidad for Mago {}",
      options: ["Sí", "No: falta implementar usar"],
      answer: 1,
      explain: "Un contrato se cumple entero: falta usar() y Rust da error E0046.",
      check: { compiles: false },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "item", kind: "shield", holder: "hero" }],
      win: [{ t: "drop" }, { t: "say", actor: "enemy", text: "¡Impostor!" }],
    },
    {
      kind: "type",
      prompt: "Firma el contrato para el Mago",
      code: 'trait Habilidad { fn usar(&self) -> String; }\nstruct Mago;\nimpl ___ for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\nprintln!("{}", Mago.usar());',
      answer: "Habilidad",
      explain: "impl NombreDelTrait for Tipo { ... }",
      check: { compiles: true, stdout: "¡Fuego!" },
      win: [{ t: "say", actor: "hero", text: "¡Fuego!" }],
    },
    say("Un trait también puede traer un método POR DEFECTO, con cuerpo. Quien no lo reescribe, lo hereda."),
    {
      kind: "predict",
      prompt: "Mago no escribe grito(). ¿Qué imprime?",
      code: 'trait Habilidad {\n    fn usar(&self) -> String;\n    fn grito(&self) -> String { String::from("¡A la carga!") }\n}\nstruct Mago;\nimpl Habilidad for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\nprintln!("{}", Mago.grito());',
      options: ["¡A la carga!", "¡Fuego!", "Error: Mago no tiene grito"],
      answer: 0,
      output: "¡A la carga!",
      explain: "grito() tiene cuerpo en el trait: Mago lo recibe gratis.",
      check: { compiles: true, stdout: "¡A la carga!" },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }],
      win: [{ t: "say", actor: "hero", text: "¡A la carga!" }, { t: "print", text: "¡A la carga!" }],
    },
    {
      kind: "order",
      prompt: "Ordena: crear al Arquero, usar y mostrar",
      lines: ["let a = Arquero;", "let frase = a.usar();", 'println!("Grito: {}", frase);'],
      explain: "Primero existe el Arquero, luego usa su habilidad y al final se imprime.",
      check: { program: conHab('let a = Arquero;\nlet frase = a.usar();\nprintln!("Grito: {}", frase);'), compiles: true, stdout: "Grito: ¡Flecha!" },
      win: [{ t: "print", text: "Grito: ¡Flecha!" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir ¡Escudo arriba!",
      starter: 'trait Habilidad {\n    fn usar(&self) -> String;\n}\n\nstruct Caballero;\n\nimpl Habilidad for Caballero {}\n\nfn main() {\n    let c = Caballero;\n    println!("{}", c.usar());\n}\n',
      expect: "¡Escudo arriba!",
      solution: 'trait Habilidad {\n    fn usar(&self) -> String;\n}\n\nstruct Caballero;\n\nimpl Habilidad for Caballero {\n    fn usar(&self) -> String { String::from("¡Escudo arriba!") }\n}\n\nfn main() {\n    let c = Caballero;\n    println!("{}", c.usar());\n}\n',
      fallback: [
        String.raw`fn\s+usar\s*\(\s*&\s*self\s*\)\s*->\s*String\s*\{[^}]*Escudo arriba`,
        String.raw`impl\s+Habilidad\s+for\s+Caballero\s*\{[\s\S]*fn\s+usar[\s\S]*Escudo arriba`,
      ],
      explain: "El Caballero firmó el contrato: dentro del impl debe escribir usar() con su cuerpo.",
    },
  ],
};

const genericos: LessonDef = {
  slug: "genericos-y-bounds",
  title: "Genéricos con insignia",
  concept: "traits",
  mode: "lesson",
  xp: 75,
  enemy: "ghost",
  enemyName: "BUG SIN INSIGNIA",
  beats: [
    say("¿Una sola función para CUALQUIERA que tenga la insignia Habilidad? Para eso están los genéricos."),
    say("T es un tipo comodín. Con <T: Habilidad> pones una condición: T debe cumplir el contrato."),
    {
      kind: "act",
      prompt: "Una puerta que solo abre con la insignia",
      setup: [],
      steps: [
        { label: "FIRMA", line: "fn presentar<T: Habilidad>(x: &T) {", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "banner", text: "T: Habilidad" }] },
        { label: "CUERPO", line: '    println!("{}", x.usar());' },
        { label: "CERRAR", line: "}" },
        { label: "MAGO", line: "presentar(&Mago);", effects: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "say", actor: "hero", text: "¡Fuego!" }], output: "¡Fuego!" },
        { label: "ARQUERO", line: "presentar(&Arquero);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }, { t: "say", actor: "ally", text: "¡Flecha!" }], output: "¡Flecha!" },
        {
          label: "UN NÚMERO",
          line: "presentar(&5);",
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¿Insignia? No tengo" }],
          error: { compiler: "error[E0277]: the trait bound `{integer}: Habilidad` is not satisfied", plain: "5 es un número: no implementa Habilidad, así que no cumple T: Habilidad." },
        },
      ],
    },
    {
      kind: "pick",
      prompt: "Exige la insignia a T",
      code: 'fn presentar<T: ___>(x: &T) {\n    println!("{}", x.usar());\n}\npresentar(&Mago);\npresentar(&Arquero);',
      options: ["Habilidad", "Mago", "String"],
      answer: 0,
      explain: "La condición nombra al TRAIT. Así sirve para Mago, Arquero y cualquiera con la insignia.",
      check: { program: conHab("presentar(&Mago);\npresentar(&Arquero);", `\n${PRESENTAR}`), compiles: true, stdout: "¡Fuego!\n¡Flecha!" },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }],
      win: [{ t: "say", actor: "hero", text: "¡Fuego!" }, { t: "say", actor: "ally", text: "¡Flecha!" }],
    },
    {
      kind: "predict",
      prompt: "Roca no implementa Habilidad. ¿Compila?",
      code: "struct Roca;\npresentar(&Roca);",
      options: ["Sí: no imprime nada", "No: Roca no cumple T: Habilidad"],
      answer: 1,
      explain: "Rust revisa la condición al compilar: E0277, Roca no tiene la insignia.",
      check: { program: conHab("presentar(&Roca);", `\n${PRESENTAR}\nstruct Roca;\n`), compiles: false },
      setup: [{ t: "tag", actor: "enemy", text: "Roca" }],
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡No me dejan entrar!" }],
    },
    say("Atajo: x: &impl Habilidad significa lo mismo. Se lee: «algo que implemente Habilidad»."),
    {
      kind: "type",
      prompt: "Usa el atajo impl",
      code: 'fn presentar(x: &impl ___) {\n    println!("{}", x.usar());\n}\npresentar(&Arquero);',
      answer: "Habilidad",
      explain: "&impl Habilidad: cualquier tipo con la insignia, sin escribir <T>.",
      check: { program: conHab('fn presentar(x: &impl Habilidad) {\n    println!("{}", x.usar());\n}\npresentar(&Arquero);'), compiles: true, stdout: "¡Flecha!" },
      win: [{ t: "say", actor: "ally", text: "¡Flecha!" }, { t: "print", text: "¡Flecha!" }],
    },
    say("Si la firma se alarga, pasa las condiciones a un where al final. Mismo significado, más legible."),
    {
      kind: "pick",
      prompt: "Mueve la condición al final",
      code: 'fn presentar<T>(x: &T)\n___ T: Habilidad {\n    println!("{}", x.usar());\n}\npresentar(&Mago);',
      options: ["where", "if", "when", "for"],
      answer: 0,
      explain: "where T: Habilidad equivale a <T: Habilidad>.",
      check: { program: conHab('fn presentar<T>(x: &T)\nwhere T: Habilidad {\n    println!("{}", x.usar());\n}\npresentar(&Mago);'), compiles: true, stdout: "¡Fuego!" },
    },
    say("¿Dos insignias? Súmalas con +. T: Habilidad + Clone exige el contrato Y saber clonarse."),
    {
      kind: "pick",
      prompt: "Exige las dos insignias",
      code: "fn reclutar<T: Habilidad ___ Clone>(x: &T) -> T {\n    x.clone()\n}",
      options: ["+", ",", "&", "and"],
      answer: 0,
      explain: "Los bounds se combinan con +: T: Habilidad + Clone.",
      check: {
        program:
          '#![allow(unused)]\ntrait Habilidad {\n    fn usar(&self) -> String;\n}\n\n#[derive(Clone)]\nstruct Mago;\nimpl Habilidad for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\n\nfn reclutar<T: Habilidad + Clone>(x: &T) -> T {\n    x.clone()\n}\n\nfn main() {\n    let otro = reclutar(&Mago);\n    println!("{}", otro.usar());\n}\n',
        compiles: true,
        stdout: "¡Fuego!",
      },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "item", kind: "shield", holder: "hero" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "otro Mago" }, { t: "clone", to: "ally" }],
    },
    {
      kind: "predict",
      prompt: "Mago tiene Habilidad pero NO Clone. ¿Compila?",
      code: "fn reclutar<T: Habilidad + Clone>(x: &T) -> T {\n    x.clone()\n}\nreclutar(&Mago);",
      options: ["Sí", "No: Mago no implementa Clone"],
      answer: 1,
      explain: "Con + hacen falta TODAS las insignias. A Mago le falta Clone: E0277.",
      check: { program: conHab("reclutar(&Mago);", "\nfn reclutar<T: Habilidad + Clone>(x: &T) -> T {\n    x.clone()\n}\n"), compiles: false },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }],
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: "Me falta Clone" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Llega: ¡Fuego!",
      starter: 'trait Habilidad { fn usar(&self) -> String; }\n\nstruct Mago;\nimpl Habilidad for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\n\nfn anunciar<T>(x: &T) {\n    println!("Llega: {}", x.usar());\n}\n\nfn main() { anunciar(&Mago); }\n',
      expect: "Llega: ¡Fuego!",
      solution: 'trait Habilidad { fn usar(&self) -> String; }\n\nstruct Mago;\nimpl Habilidad for Mago {\n    fn usar(&self) -> String { String::from("¡Fuego!") }\n}\n\nfn anunciar<T: Habilidad>(x: &T) {\n    println!("Llega: {}", x.usar());\n}\n\nfn main() { anunciar(&Mago); }\n',
      fallback: [
        String.raw`anunciar\s*<\s*T\s*:[^>]*Habilidad`,
        String.raw`where\s+T\s*:[^{]*Habilidad`,
        String.raw`x\s*:\s*&\s*impl\s+Habilidad`,
        String.raw`x\s*:\s*&\s*dyn\s+Habilidad`,
      ],
      explain: "Sin condición, Rust no sabe que T tiene usar() (E0599). Pide T: Habilidad.",
    },
  ],
};

const armeria: LessonDef = {
  slug: "derive-y-display",
  title: "La armería estándar",
  concept: "traits",
  mode: "lesson",
  xp: 75,
  enemy: "golem",
  enemyName: "BUG ILEGIBLE",
  beats: [
    say("Rust trae traits listos: Debug, Clone, PartialEq, Display... Pero tu struct no los tiene de fábrica."),
    {
      kind: "act",
      prompt: "Intenta mostrar una gema",
      setup: [],
      steps: [
        { label: "DEFINIR", line: "struct Gema { valor: u32 }", effects: [{ t: "item", kind: "gem", holder: "hero" }] },
        { label: "CREAR", line: "let g = Gema { valor: 7 };", effects: [{ t: "tag", actor: "hero", text: "g", value: "7" }] },
        {
          label: "MOSTRAR",
          line: 'println!("{:?}", g);',
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡No sé leer eso!" }],
          error: { compiler: "error[E0277]: `Gema` doesn't implement `Debug`", plain: "{:?} usa el trait Debug, y Gema no lo implementa." },
        },
        { label: "DERIVAR", line: "#[derive(Debug)]\nstruct Gema { valor: u32 }", effects: [{ t: "banner", text: "#[derive(Debug)]" }] },
        { label: "REINTENTAR", line: 'println!("{:?}", g);', effects: [{ t: "print", text: "Gema { valor: 7 }" }, { t: "say", actor: "hero", text: "¡Ahora sí!" }], output: "Gema { valor: 7 }" },
      ],
    },
    say("#[derive(...)] escribe el impl por ti. Y {:?} imprime el valor en formato de depuración."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: '#[derive(Debug)]\nstruct Gema { valor: u32 }\nlet g = Gema { valor: 9 };\nprintln!("{:?}", g);',
      options: ["Gema { valor: 9 }", "9", "Error: falta Debug"],
      answer: 0,
      output: "Gema { valor: 9 }",
      explain: "Debug derivado muestra el nombre del struct y sus campos.",
      check: { compiles: true, stdout: "Gema { valor: 9 }" },
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "g", value: "9" }],
      win: [{ t: "print", text: "Gema { valor: 9 }" }],
    },
    {
      kind: "pick",
      prompt: "Que la poción se pueda duplicar",
      code: '#[derive(___)]\nstruct Pocion { usos: u32 }\nlet p = Pocion { usos: 2 };\nlet q = p.clone();\nprintln!("{} {}", p.usos, q.usos);',
      options: ["Clone", "Debug", "Copy"],
      answer: 0,
      explain: ".clone() viene del trait Clone. Derívalo y tu struct sabe clonarse.",
      check: { compiles: true, stdout: "2 2", wrongFail: true },
      setup: [{ t: "item", kind: "potion", holder: "hero" }, { t: "tag", actor: "hero", text: "p" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "q" }, { t: "clone", to: "ally" }, { t: "print", text: "2 2" }],
    },
    say("PartialEq te da ==. Sin él, Rust no sabe si dos gemas son iguales."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: '#[derive(PartialEq)]\nstruct Gema { valor: u32 }\nlet a = Gema { valor: 3 };\nlet b = Gema { valor: 3 };\nprintln!("{}", a == b);',
      options: ["true", "false", "Error: no se pueden comparar"],
      answer: 0,
      output: "true",
      explain: "PartialEq derivado compara campo a campo: 3 == 3.",
      check: { compiles: true, stdout: "true" },
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "3" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b", value: "3" }],
      win: [{ t: "clone", to: "ally" }, { t: "say", actor: "hero", text: "¡Iguales!" }],
    },
    {
      kind: "predict",
      prompt: "Sin derive. ¿Compila?",
      code: 'struct Gema { valor: u32 }\nlet a = Gema { valor: 3 };\nlet b = Gema { valor: 3 };\nprintln!("{}", a == b);',
      options: ["Sí: imprime true", "No: Gema no implementa PartialEq"],
      answer: 1,
      explain: "Sin PartialEq no existe == para Gema: error E0369.",
      check: { compiles: false },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¿== qué?" }],
    },
    say("Copy exige Clone: lo que se copia solo también debe saber clonarse. Por eso se derivan juntos."),
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: "#[derive(Copy)]\nstruct Punto { x: i32 }",
      options: ["Sí", "No: Copy necesita Clone"],
      answer: 1,
      explain: "Copy depende de Clone: escribe #[derive(Clone, Copy)].",
      check: { compiles: false },
    },
    {
      kind: "type",
      prompt: "Que Punto se copie como un i32",
      code: '#[derive(Clone, ___)]\nstruct Punto { x: i32 }\nlet a = Punto { x: 1 };\nlet b = a;\nprintln!("{} {}", a.x, b.x);',
      answer: "Copy",
      explain: "Con Clone + Copy, let b = a; copia en vez de mover: a sigue viva.",
      check: { compiles: true, stdout: "1 1" },
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "a" }],
      win: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }, { t: "clone", to: "ally" }, { t: "print", text: "1 1" }],
    },
    say("derive no sirve para todo. Para {} implementas Display a mano: tú decides qué texto ve la gente."),
    {
      kind: "act",
      prompt: "Escribe Display para la gema",
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "g", value: "7" }],
      steps: [
        { label: "IMPORTAR", line: "use std::fmt;" },
        { label: "FIRMAR", line: "impl fmt::Display for Gema {", effects: [{ t: "banner", text: "Display" }] },
        { label: "MÉTODO", line: "    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {" },
        { label: "ESCRIBIR", line: '        write!(f, "Gema de {} quilates", self.valor)', effects: [{ t: "item", kind: "scroll", holder: "hero" }] },
        { label: "CERRAR", line: "    }\n}" },
        { label: "MOSTRAR", line: 'println!("{}", g);', effects: [{ t: "say", actor: "hero", text: "¡7 quilates!" }], output: "Gema de 7 quilates" },
      ],
    },
    {
      kind: "pick",
      prompt: "{} necesita este trait",
      code: 'use std::fmt;\nstruct Gema { valor: u32 }\nimpl fmt::___ for Gema {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "Gema de {} quilates", self.valor)\n    }\n}\nprintln!("{}", Gema { valor: 5 });',
      options: ["Display", "Debug", "Print"],
      answer: 0,
      explain: "{} usa Display y {:?} usa Debug. Print no existe.",
      check: { compiles: true, stdout: "Gema de 5 quilates", wrongFail: true },
      win: [{ t: "print", text: "Gema de 5 quilates" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Ferro (nivel 3)",
      starter: 'use std::fmt;\nstruct Heroe { nombre: String, nivel: u32 }\n\nimpl fmt::Debug for Heroe {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "{} (nivel {})", self.nombre, self.nivel)\n    }\n}\n\nfn main() {\n    let h = Heroe { nombre: String::from("Ferro"), nivel: 3 };\n    println!("{}", h);\n}\n',
      expect: "Ferro (nivel 3)",
      solution: 'use std::fmt;\nstruct Heroe { nombre: String, nivel: u32 }\n\nimpl fmt::Display for Heroe {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "{} (nivel {})", self.nombre, self.nivel)\n    }\n}\n\nfn main() {\n    let h = Heroe { nombre: String::from("Ferro"), nivel: 3 };\n    println!("{}", h);\n}\n',
      fallback: [
        String.raw`impl\s+(fmt::|std::fmt::)?Display\s+for\s+Heroe`,
        String.raw`println!\s*\(\s*"\{:\?\}"\s*,\s*h\s*\)`,
        String.raw`println!\s*\(\s*"\{h:\?\}"\s*\)`,
      ],
      explain: "println!(\"{}\") pide Display, no Debug. Cambia el trait del impl.",
    },
  ],
};

const tropa: LessonDef = {
  slug: "tropa-dyn",
  title: "La tropa mixta",
  concept: "traits",
  mode: "lesson",
  xp: 75,
  enemy: "slime",
  enemyName: "BUG UNIFORME",
  beats: [
    say("vec![a, b] crea una lista (Vec) y for x in &lista recorre cada elemento. Pero un Vec admite UN solo tipo."),
    say("¿Cómo meter a un Mago y a un Arquero en la misma tropa? Con una caja que solo mira la insignia."),
    {
      kind: "act",
      prompt: "Forma una tropa con tipos distintos",
      setup: [],
      steps: [
        {
          label: "INTENTO",
          line: "let tropa = vec![Mago, Arquero];",
          effects: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }, { t: "shake" }],
          error: { compiler: "error[E0308]: mismatched types", plain: "Un Vec exige un solo tipo, y Mago y Arquero son tipos distintos." },
        },
        { label: "CAJAS", line: "let tropa: Vec<Box<dyn Habilidad>> = vec![", effects: [{ t: "banner", text: "dyn Habilidad" }] },
        { label: "MAGO", line: "    Box::new(Mago),", effects: [{ t: "item", kind: "shield", holder: "hero" }, { t: "tag", actor: "hero", text: "Box<dyn Habilidad>" }] },
        { label: "ARQUERO", line: "    Box::new(Arquero),", effects: [{ t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "Box<dyn Habilidad>" }] },
        { label: "CERRAR", line: "];" },
        { label: "RECORRER", line: 'for p in &tropa { println!("{}", p.usar()); }', effects: [{ t: "say", actor: "hero", text: "¡Fuego!" }, { t: "say", actor: "ally", text: "¡Flecha!" }], output: "¡Fuego!\n¡Flecha!" },
      ],
    },
    say("Box<dyn Habilidad> es una caja con «algo que tiene la insignia». Qué usar() se llama se decide al EJECUTAR."),
    {
      kind: "pick",
      prompt: "Una caja para cualquier Habilidad",
      code: 'let tropa: Vec<Box<___ Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\nfor p in &tropa {\n    println!("{}", p.usar());\n}',
      options: ["dyn", "impl", "&", "mut"],
      answer: 0,
      explain: "dyn Trait es un objeto del trait: un tipo cualquiera detrás de la insignia.",
      check: { program: conHab('let tropa: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\nfor p in &tropa {\n    println!("{}", p.usar());\n}'), compiles: true, stdout: "¡Fuego!\n¡Flecha!" },
      setup: [{ t: "tag", actor: "hero", text: "Mago" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "Arquero" }],
      win: [{ t: "say", actor: "hero", text: "¡Fuego!" }, { t: "say", actor: "ally", text: "¡Flecha!" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let tropa: Vec<Box<dyn Habilidad>> =\n    vec![Box::new(Arquero), Box::new(Mago), Box::new(Arquero)];\nfor p in &tropa {\n    println!("{}", p.usar());\n}',
      options: ["¡Flecha! ¡Fuego! ¡Flecha! (en líneas)", "¡Fuego! ¡Fuego! ¡Fuego! (en líneas)", "Error: tipos mezclados"],
      answer: 0,
      output: "¡Flecha!\n¡Fuego!\n¡Flecha!",
      explain: "Cada caja llama al usar() de SU tipo, en el orden del Vec.",
      check: { program: conHab('let tropa: Vec<Box<dyn Habilidad>> =\n    vec![Box::new(Arquero), Box::new(Mago), Box::new(Arquero)];\nfor p in &tropa {\n    println!("{}", p.usar());\n}'), compiles: true, stdout: "¡Flecha!\n¡Fuego!\n¡Flecha!" },
    },
    {
      kind: "predict",
      prompt: "Sin escribir dyn. ¿Compila?",
      code: "let tropa = vec![Box::new(Mago), Box::new(Arquero)];",
      options: ["Sí", "No: Box<Mago> y Box<Arquero> son tipos distintos"],
      answer: 1,
      explain: "Sin la anotación, el Vec toma el tipo Box<Mago> y el Arquero no cabe: E0308.",
      check: { program: conHab("let tropa = vec![Box::new(Mago), Box::new(Arquero)];"), compiles: false },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡Todos iguales!" }],
    },
    {
      kind: "type",
      prompt: "Mete al Mago en la caja",
      code: 'let caja: Box<dyn Habilidad> = Box::___(Mago);\nprintln!("{}", caja.usar());',
      answer: "new",
      explain: "Box::new(valor) guarda el valor en una caja.",
      check: { program: conHab('let caja: Box<dyn Habilidad> = Box::new(Mago);\nprintln!("{}", caja.usar());'), compiles: true, stdout: "¡Fuego!" },
      win: [{ t: "item", kind: "shield", holder: "hero" }, { t: "say", actor: "hero", text: "¡Fuego!" }],
    },
    say("Dos caminos: <T: Habilidad> es despacho ESTÁTICO. Rust crea una versión por tipo al compilar: muy rápido."),
    say("dyn Habilidad es despacho DINÁMICO: se busca el método al ejecutar. Permite mezclar tipos, con un pequeño costo."),
    {
      kind: "predict",
      prompt: "¿Qué camino permite mezclar tipos en un Vec?",
      code: "// A: fn presentar<T: Habilidad>(x: &T)\n// B: Vec<Box<dyn Habilidad>>",
      options: ["A: genéricos", "B: dyn"],
      answer: 1,
      explain: "Un genérico fija UN tipo T por llamada. dyn deja convivir tipos distintos.",
      check: { program: conHab('let tropa: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\nprintln!("{}", tropa.len());'), compiles: true, stdout: "2" },
    },
    {
      kind: "predict",
      prompt: "presentar(&Mago) con <T: Habilidad>: ¿cuándo se elige usar()?",
      code: `${PRESENTAR}\npresentar(&Mago);`,
      options: ["Al compilar (estático)", "Al ejecutar (dinámico)"],
      answer: 0,
      explain: "Con genéricos, Rust genera presentar para Mago al compilar.",
      check: { program: conHab("presentar(&Mago);", `\n${PRESENTAR}`), compiles: true, stdout: "¡Fuego!" },
    },
    {
      kind: "order",
      prompt: "Ordena: arma la tropa y que todos ataquen",
      lines: ["let tropa: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];", "for p in &tropa {", '    println!("{}", p.usar());', "}"],
      explain: "Primero existe la tropa; luego el for recorre cada caja y llama a usar().",
      check: { program: conHab('let tropa: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\nfor p in &tropa {\n    println!("{}", p.usar());\n}'), compiles: true, stdout: "¡Fuego!\n¡Flecha!" },
      win: [{ t: "print", text: "¡Fuego!" }, { t: "print", text: "¡Flecha!" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Ataca: ¡Flecha!",
      starter: 'trait Habilidad { fn usar(&self) -> String; }\nstruct Mago;\nstruct Arquero;\nimpl Habilidad for Mago { fn usar(&self) -> String { String::from("¡Fuego!") } }\nimpl Habilidad for Arquero { fn usar(&self) -> String { String::from("¡Flecha!") } }\n\nfn main() {\n    let tropa = vec![Box::new(Mago), Box::new(Arquero)];\n    for p in &tropa {\n        println!("Ataca: {}", p.usar());\n    }\n}\n',
      expect: "Ataca: ¡Flecha!",
      solution: 'trait Habilidad { fn usar(&self) -> String; }\nstruct Mago;\nstruct Arquero;\nimpl Habilidad for Mago { fn usar(&self) -> String { String::from("¡Fuego!") } }\nimpl Habilidad for Arquero { fn usar(&self) -> String { String::from("¡Flecha!") } }\n\nfn main() {\n    let tropa: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\n    for p in &tropa {\n        println!("Ataca: {}", p.usar());\n    }\n}\n',
      fallback: [
        String.raw`dyn\s+Habilidad`,
      ],
      explain: "Anota el tipo: Vec<Box<dyn Habilidad>>. Así caben Mago y Arquero.",
    },
  ],
};

const boss4: LessonDef = {
  slug: "jefe-traits",
  title: "JEFE: Dragón Genérico",
  concept: "traits",
  mode: "boss",
  xp: 180,
  enemy: "dragon",
  enemyName: "DRAGÓN GENÉRICO",
  beats: [
    enemySays("SOY EL DRAGÓN DEL CASTILLO. Solo cruza quien cumple sus contratos. ¿Tienes la insignia?"),
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "trait Volar { fn volar(&self); }\nstruct Ave;\nimpl Volar for Ave {}", options: ["Sí", "No"], answer: 1, explain: "Falta implementar volar().", check: { compiles: false } },
    { kind: "pick", time: 12, prompt: "Firma el contrato", code: 'trait Volar { fn volar(&self) -> u32; }\nstruct Ave;\nimpl ___ for Ave { fn volar(&self) -> u32 { 3 } }\nprintln!("{}", Ave.volar());', options: ["Volar", "Ave", "trait"], answer: 0, explain: "impl Trait for Tipo.", check: { compiles: true, stdout: "3", wrongFail: true } },
    { kind: "predict", time: 12, prompt: "¿Qué imprime?", code: 'trait Rugir { fn rugir(&self) -> u32 { 1 } }\nstruct Dragon;\nimpl Rugir for Dragon {}\nprintln!("{}", Dragon.rugir());', options: ["1", "Error"], answer: 0, explain: "Método por defecto: se hereda.", check: { compiles: true, stdout: "1" } },
    { kind: "pick", time: 12, prompt: "Exige la insignia", code: "fn f<T: ___>(x: &T) -> String { x.usar() }", options: ["Habilidad", "Mago", "dyn"], answer: 0, explain: "T: Habilidad", check: { program: conHab("println!(\"{}\", f(&Mago));", "\nfn f<T: Habilidad>(x: &T) -> String { x.usar() }\n"), compiles: true, stdout: "¡Fuego!" } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "fn presentar<T: Habilidad>(x: &T) {}\npresentar(&3);", options: ["Sí", "No"], answer: 1, explain: "3 no implementa Habilidad: E0277.", check: { program: conHab("presentar(&3);", "\nfn presentar<T: Habilidad>(x: &T) {}\n"), compiles: false } },
    { kind: "type", time: 12, prompt: "El atajo del genérico", code: "fn f(x: &___ Habilidad) -> String { x.usar() }", answer: "impl", explain: "&impl Habilidad", check: { program: conHab("println!(\"{}\", f(&Arquero));", "\nfn f(x: &impl Habilidad) -> String { x.usar() }\n"), compiles: true, stdout: "¡Flecha!" } },
    { kind: "pick", time: 12, prompt: "Para usar ==", code: '#[derive(___)]\nstruct Oro { n: u32 }\nprintln!("{}", Oro { n: 1 } == Oro { n: 1 });', options: ["PartialEq", "Debug", "Clone"], answer: 0, explain: "== viene de PartialEq.", check: { compiles: true, stdout: "true", wrongFail: true } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "#[derive(Copy)]\nstruct Escama;", options: ["Sí", "No"], answer: 1, explain: "Copy exige Clone.", check: { compiles: false } },
    { kind: "type", time: 15, prompt: "Tropa con tipos mezclados", code: "let v: Vec<Box<___ Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];", answer: "dyn", explain: "Box<dyn Habilidad>", check: { program: conHab("let v: Vec<Box<dyn Habilidad>> = vec![Box::new(Mago), Box::new(Arquero)];\nprintln!(\"{}\", v.len());"), compiles: true, stdout: "2" } },
    { kind: "predict", time: 15, prompt: "<T: Habilidad> usa despacho...", code: "fn presentar<T: Habilidad>(x: &T)", options: ["Estático (al compilar)", "Dinámico (al ejecutar)"], answer: 0, explain: "Genéricos = estático. dyn = dinámico.", check: { program: conHab("presentar(&Mago);", `\n${PRESENTAR}`), compiles: true, stdout: "¡Fuego!" } },
    enemySays("Grrr... cada tipo cumplió su contrato. El castillo es tuyo, rustáceo. La torre te espera."),
  ],
};

export const castilloTraits: RegionDef = {
  slug: "castillo-traits",
  name: "Castillo Traits",
  subtitle: "Traits · genéricos",
  theme: "castle",
  lessons: [contrato, genericos, armeria, tropa, boss4],
};
