import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { enemySays, say } from "../helpers.ts";

// REGION 3 · MONTE LIFETIMES  (alcance, referencias colgantes, 'a, structs con referencias, 'static)

const MAS_LARGO = "fn mas_largo<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n";

const colgantes: LessonDef = {
  slug: "alcance-y-colgantes",
  title: "Préstamos con fecha",
  concept: "lifetimes",
  mode: "lesson",
  xp: 70,
  enemy: "ghost",
  enemyName: "BUG COLGANTE",
  beats: [
    say("Bienvenido al Monte Lifetimes. Aquí todo préstamo tiene fecha de devolución."),
    say("Regla: una referencia NUNCA puede vivir más que su dueño. Si no, apuntaría a la nada."),
    {
      kind: "act",
      prompt: "Pulsa en orden y vigila la referencia r",
      setup: [],
      steps: [
        { label: "DECLARAR r", line: "let r;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r" }] },
        { label: "ABRIR BLOQUE", line: "{" },
        { label: "FORJAR", line: '    let x = String::from("gema");', effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "x" }] },
        { label: "PRESTAR", line: "    r = &x;", effects: [{ t: "tag", actor: "ally", text: "r = &x" }, { t: "lend", to: "ally" }] },
        { label: "CERRAR", line: "} // x muere aquí", effects: [{ t: "drop" }, { t: "untag", actor: "hero" }, { t: "dead", actor: "ally" }, { t: "banner", text: "¡FANTASMA!" }] },
        {
          label: "USAR r",
          line: 'println!("{}", r);',
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: "¡Apunto a la nada!" }],
          error: { compiler: "error[E0597]: `x` does not live long enough", plain: "x murió al cerrar }, pero r seguía prestándola: referencia COLGANTE." },
        },
      ],
    },
    say("Una referencia colgante es un fantasma. Rust la caza al COMPILAR, no en producción."),
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: "let r;\n{\n    let x = 5;\n    r = &x;\n}\nprintln!(\"{}\", r);",
      options: ["Sí: imprime 5", "No: x no vive lo suficiente"],
      answer: 1,
      explain: "x muere en }. r la usaría después: error E0597.",
      check: { compiles: false },
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r = &x" }, { t: "tag", actor: "hero", text: "x", value: "5" }],
      win: [{ t: "untag", actor: "hero" }, { t: "dead", actor: "ally" }, { t: "say", actor: "enemy", text: "¡Bu! Me atrapaste" }],
    },
    {
      kind: "pick",
      prompt: "Que el oro sobreviva al bloque",
      code: 'let r;\n{\n    let x = String::from("oro");\n    r = ___;\n}\nprintln!("{}", r);',
      options: ["x", "&x", "&mut x"],
      answer: 0,
      explain: "Si r recibe la PROPIEDAD (move), el oro ya no muere en }.",
      check: { compiles: true, stdout: "oro", wrongFail: true },
      setup: [{ t: "item", kind: "potion", holder: "hero" }, { t: "tag", actor: "hero", text: "x" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r" }],
      win: [{ t: "give", to: "ally" }, { t: "dead", actor: "hero" }, { t: "print", text: "oro" }],
    },
    {
      kind: "predict",
      prompt: "La referencia muere ANTES que el dueño. ¿Qué imprime?",
      code: 'let x = String::from("pan");\n{\n    let r = &x;\n    println!("{}", r);\n} // r muere aquí\nprintln!("{}", x);',
      options: ["pan y pan (dos líneas)", "Error: r colgante"],
      answer: 0,
      output: "pan\npan",
      explain: "Al revés no hay problema: el préstamo termina y el dueño sigue vivo.",
      check: { compiles: true, stdout: "pan\npan" },
    },
    say("En funciones igual: no puedes devolver una referencia a algo local. Muere al salir."),
    {
      kind: "act",
      prompt: "Intenta devolver un préstamo de algo local",
      setup: [],
      steps: [
        { label: "FIRMA", line: "fn crear() -> &String {" },
        { label: "FORJAR", line: '    let s = String::from("mapa");', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "s" }] },
        { label: "DEVOLVER &s", line: "    &s", effects: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }] },
        {
          label: "CERRAR",
          line: "}",
          effects: [{ t: "drop" }, { t: "dead", actor: "ally" }, { t: "shake" }],
          error: { compiler: "error[E0106]: missing lifetime specifier", plain: "s muere al cerrar }. No hay nadie de quien pedir prestado." },
        },
        { label: "MEJOR ASÍ", line: 'fn crear() -> String { String::from("mapa") }', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "give", to: "ally" }, { t: "banner", text: "¡MOVE, NO PRÉSTAMO!" }] },
      ],
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'fn crear() -> &String {\n    let s = String::from("mapa");\n    &s\n}',
      options: ["Sí", "No: la referencia saldría colgando"],
      answer: 1,
      explain: "s muere al salir de crear: Rust rechaza devolver &s.",
      check: { compiles: false },
    },
    {
      kind: "pick",
      prompt: "Devuelve el mapa sin colgar nada",
      code: 'fn crear() -> ___ {\n    let s = String::from("mapa");\n    s\n}\n\nprintln!("{}", crear());',
      options: ["String", "&String", "&str"],
      answer: 0,
      explain: "Devuelve el String entero: la propiedad sale de la función.",
      check: { compiles: true, stdout: "mapa", wrongFail: true },
      win: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "print", text: "mapa" }],
    },
    {
      kind: "order",
      prompt: "Ordena: el dueño nace antes que el préstamo",
      lines: ['let x = String::from("luz");', "let r = &x;", 'println!("{}", r);'],
      explain: "Primero el dueño, luego el préstamo, y lo usas mientras x vive.",
      check: { compiles: true, stdout: "luz" },
      win: [{ t: "print", text: "luz" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Encontré: corona",
      starter: 'fn main() {\n    let r;\n    {\n        let tesoro = String::from("corona");\n        r = &tesoro;\n    }\n    println!("Encontré: {}", r);\n}\n',
      expect: "Encontré: corona",
      solution: 'fn main() {\n    let tesoro = String::from("corona");\n    let r;\n    {\n        r = &tesoro;\n    }\n    println!("Encontré: {}", r);\n}\n',
      fallback: [
        String.raw`r\s*=\s*tesoro\s*;`,
        String.raw`r\s*=\s*tesoro\s*\.\s*(clone|to_string|to_owned)\s*\(\s*\)`,
        String.raw`let\s+tesoro[^;]*;\s*let\s+r\b`,
        String.raw`r\s*=\s*&\s*tesoro\s*;\s*println!\s*\(\s*"Encontré: \{\}"\s*,\s*r\s*\)`,
      ],
      explain: "Saca tesoro del bloque para que viva tanto como r (o muévelo: r = tesoro).",
    },
  ],
};

const anotaciones: LessonDef = {
  slug: "anotaciones-a",
  title: "El contrato 'a",
  concept: "lifetimes",
  mode: "lesson",
  xp: 70,
  enemy: "golem",
  enemyName: "BUG AMBIGUO",
  beats: [
    say("Si una función recibe DOS referencias y devuelve una, Rust pregunta: ¿de cuál es el préstamo?"),
    {
      kind: "act",
      prompt: "Escribe la función y firma el contrato",
      setup: [],
      steps: [
        {
          label: "SIN ETIQUETA",
          line: "fn mas_largo(x: &str, y: &str) -> &str {",
          effects: [{ t: "tag", actor: "hero", text: "x" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "y" }, { t: "shake" }, { t: "say", actor: "enemy", text: "¿De x o de y?" }],
          error: { compiler: "error[E0106]: missing lifetime specifier", plain: "Rust no sabe si el resultado se presta de x o de y." },
        },
        {
          label: "FIRMAR 'a",
          line: "fn mas_largo<'a>(x: &'a str, y: &'a str) -> &'a str {",
          effects: [{ t: "tag", actor: "hero", text: "x: &'a str" }, { t: "tag", actor: "ally", text: "y: &'a str" }, { t: "banner", text: "CONTRATO 'a" }],
        },
        { label: "CUERPO", line: "    if x.len() > y.len() { x } else { y }", effects: [{ t: "say", actor: "hero", text: "¡Gana el más largo!" }] },
        { label: "CERRAR", line: "}", effects: [{ t: "banner", text: "¡COMPILA!" }] },
      ],
    },
    say("'a no alarga ninguna vida. Es un contrato: el resultado vale mientras x e y sigan vivas."),
    {
      kind: "pick",
      prompt: "Declara el lifetime genérico",
      code: "fn mas_largo<___>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n\nprintln!(\"{}\", mas_largo(\"hacha\", \"espada\"));",
      options: ["'a", "a", "&a", "<a>"],
      answer: 0,
      explain: "Los lifetimes se declaran como genéricos: <'a>, con apóstrofo.",
      check: { compiles: true, stdout: "espada", wrongFail: true },
      win: [{ t: "banner", text: "CONTRATO 'a" }, { t: "print", text: "espada" }],
    },
    {
      kind: "type",
      prompt: "La salida cumple el mismo contrato",
      code: "fn mas_largo<'a>(x: &'a str, y: &'a str) -> ___ str {\n    if x.len() > y.len() { x } else { y }\n}",
      answer: "&'a",
      explain: "-> &'a str: el resultado vive lo que el contrato 'a.",
      check: { compiles: true },
    },
    {
      kind: "predict",
      prompt: "b muere antes. ¿Compila?",
      code: `${MAS_LARGO}\nlet a = String::from("espada larga");\nlet res;\n{\n    let b = String::from("daga");\n    res = mas_largo(&a, &b);\n}\nprintln!("{}", res);`,
      options: ["Sí: imprime espada larga", "No: b no vive lo suficiente"],
      answer: 1,
      explain: "Con 'a, res vale solo mientras vivan AMBAS. b muere en }: error E0597.",
      check: { compiles: false },
      setup: [{ t: "tag", actor: "hero", text: "a" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "b" }],
      win: [{ t: "dead", actor: "ally" }, { t: "say", actor: "enemy", text: "¡Contrato roto!" }],
    },
    say("Buena noticia: casi nunca escribes 'a. Rust la deduce solo con reglas de ELISIÓN."),
    {
      kind: "act",
      prompt: "Mira lo que Rust deduce por ti",
      setup: [],
      steps: [
        { label: "UNA ENTRADA", line: "fn primera(s: &str) -> &str {", effects: [{ t: "tag", actor: "hero", text: "s" }] },
        { label: "CUERPO", line: "    &s[..1]", effects: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }, { t: "say", actor: "ally", text: "Vengo de s" }] },
        { label: "CERRAR", line: "}", effects: [{ t: "banner", text: "¡COMPILA!" }] },
        { label: "LO QUE VE RUST", line: "// fn primera<'a>(s: &'a str) -> &'a str", effects: [{ t: "banner", text: "ELISIÓN" }] },
      ],
    },
    say("Regla 1: una sola referencia de entrada → la salida toma su lifetime. Regla 2: en métodos con &self, toma el de self."),
    {
      kind: "predict",
      prompt: "Una sola entrada. ¿Compila?",
      code: 'fn primera(s: &str) -> &str {\n    &s[..1]\n}\n\nprintln!("{}", primera("rust"));',
      options: ["Sí: imprime r", "No: falta 'a"],
      answer: 0,
      output: "r",
      explain: "Una entrada, una salida: Rust deduce el lifetime solo.",
      check: { compiles: true, stdout: "r" },
    },
    {
      kind: "predict",
      prompt: "Dos entradas, sin 'a. ¿Compila?",
      code: "fn elegir(x: &str, y: &str) -> &str {\n    x\n}",
      options: ["Sí", "No: falta 'a"],
      answer: 1,
      explain: "Con dos referencias de entrada la elisión no adivina: E0106.",
      check: { compiles: false },
    },
    {
      kind: "predict",
      prompt: "Método con &self, sin 'a. ¿Compila?",
      code: 'struct Heroe { nombre: String }\n\nimpl Heroe {\n    fn nombre(&self) -> &str { &self.nombre }\n}\n\nlet h = Heroe { nombre: String::from("Ferro") };\nprintln!("{}", h.nombre());',
      options: ["Sí: imprime Ferro", "No: falta 'a"],
      answer: 0,
      output: "Ferro",
      explain: "Con &self, la salida toma el lifetime de self. Sin anotar nada.",
      check: { compiles: true, stdout: "Ferro" },
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Gana: martillo",
      starter: 'fn mas_largo(x: &str, y: &str) -> &str {\n    if x.len() > y.len() { x } else { y }\n}\n\nfn main() {\n    let a = String::from("martillo");\n    let b = String::from("pico");\n    println!("Gana: {}", mas_largo(&a, &b));\n}\n',
      expect: "Gana: martillo",
      solution: `${MAS_LARGO}\nfn main() {\n    let a = String::from("martillo");\n    let b = String::from("pico");\n    println!("Gana: {}", mas_largo(&a, &b));\n}\n`,
      fallback: [
        String.raw`fn\s+mas_largo\s*<\s*'(\w+)\s*>\s*\(\s*x\s*:\s*&\s*'\1\s+str\s*,\s*y\s*:\s*&\s*'\1\s+str\s*\)\s*->\s*&\s*'\1\s+str`,
        String.raw`fn\s+mas_largo\s*\([^)]*\)\s*->\s*String\b`,
      ],
      explain: "Declara <'a> y ponlo en x, y y en la salida.",
    },
  ],
};

const structsStatic: LessonDef = {
  slug: "structs-y-static",
  title: "Structs y 'static",
  concept: "lifetimes",
  mode: "lesson",
  xp: 70,
  enemy: "slime",
  enemyName: "BUG ETERNO",
  beats: [
    say("Un struct también puede guardar una referencia. Entonces lleva un lifetime: no puede vivir más que lo prestado."),
    {
      kind: "act",
      prompt: "Guarda un préstamo dentro de un struct",
      setup: [],
      steps: [
        { label: "DEFINIR", line: "struct Extracto<'a> { parte: &'a str }", effects: [{ t: "banner", text: "Extracto<'a>" }] },
        { label: "LIBRO", line: 'let libro = String::from("Rust es genial");', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "libro" }] },
        { label: "EXTRAER", line: "let e = Extracto { parte: &libro[..4] };", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "e.parte" }, { t: "lend", to: "ally" }] },
        { label: "LEER", line: 'println!("{}", e.parte);', effects: [{ t: "say", actor: "ally", text: "¡Rust!" }], output: "Rust" },
      ],
    },
    say("El contrato: e no puede sobrevivir a libro. Si libro muere antes, el borrow checker te frena."),
    {
      kind: "pick",
      prompt: "Completa el campo prestado",
      code: 'struct Extracto<\'a> { parte: ___ str }\n\nlet libro = String::from("Rust es genial");\nlet e = Extracto { parte: &libro[..4] };\nprintln!("{}", e.parte);',
      options: ["&'a", "&", "'a", "&mut"],
      answer: 0,
      explain: "El campo es una referencia con el contrato del struct: &'a str.",
      check: { compiles: true, stdout: "Rust", wrongFail: true },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "libro" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "e.parte" }],
      win: [{ t: "lend", to: "ally" }, { t: "print", text: "Rust" }],
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: "struct Extracto { parte: &str }",
      options: ["Sí", "No: falta el lifetime"],
      answer: 1,
      explain: "Un campo referencia necesita lifetime: Extracto<'a> y &'a str (E0106).",
      check: { compiles: false },
    },
    {
      kind: "predict",
      prompt: "libro muere antes que e. ¿Compila?",
      code: "struct Extracto<'a> { parte: &'a str }\n\nlet e;\n{\n    let libro = String::from(\"Rust es genial\");\n    e = Extracto { parte: &libro[..4] };\n}\nprintln!(\"{}\", e.parte);",
      options: ["Sí: imprime Rust", "No: libro no vive lo suficiente"],
      answer: 1,
      explain: "e guarda un préstamo de libro, y libro muere en }: E0597.",
      check: { compiles: false },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "libro" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "e.parte" }],
      win: [{ t: "drop" }, { t: "untag", actor: "hero" }, { t: "dead", actor: "ally" }],
    },
    say("'static es el lifetime más largo: vive TODO el programa. Los literales \"texto\" son &'static str."),
    {
      kind: "act",
      prompt: "Un literal no muere al cerrar el bloque",
      setup: [],
      steps: [
        { label: "DECLARAR r", line: "let r;", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "r" }] },
        { label: "ABRIR BLOQUE", line: "{" },
        { label: "LITERAL", line: '    let s: &\'static str = "eterno";', effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "s: 'static" }] },
        { label: "PRESTAR", line: "    r = s;", effects: [{ t: "tag", actor: "ally", text: "r = s" }, { t: "lend", to: "ally" }] },
        { label: "CERRAR", line: "}", effects: [{ t: "untag", actor: "hero" }, { t: "say", actor: "ally", text: "¡Sigo vivo!" }, { t: "banner", text: "'STATIC" }] },
        { label: "USAR r", line: 'println!("{}", r);', output: "eterno" },
      ],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'fn saludo() -> &\'static str {\n    "hola, aprendiz"\n}\n\nprintln!("{}", saludo());',
      options: ["hola, aprendiz", "Error: referencia colgante"],
      answer: 0,
      output: "hola, aprendiz",
      explain: "El literal vive en el programa entero: devolverlo es seguro.",
      check: { compiles: true, stdout: "hola, aprendiz" },
    },
    {
      kind: "type",
      prompt: "Escribe el lifetime de los literales",
      code: 'fn titulo() -> &___ str {\n    "Monte"\n}',
      answer: "'static",
      explain: "Un literal es &'static str.",
      check: { compiles: true },
    },
    say("Ojo: no pongas 'static solo para callar al compilador. Casi siempre basta devolver un String."),
    {
      kind: "pick",
      prompt: "format! crea un texto NUEVO. ¿Qué devuelves?",
      code: 'fn nombre(id: u32) -> ___ {\n    format!("heroe-{}", id)\n}\n\nprintln!("{}", nombre(7));',
      options: ["String", "&'static str", "&str"],
      answer: 0,
      explain: "format! crea un String: devuélvelo con su propiedad. &'static str no compilaría.",
      check: { compiles: true, stdout: "heroe-7", wrongFail: true },
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Leo: Runa de fuego",
      starter: 'struct Pergamino {\n    texto: &str,\n}\n\nfn main() {\n    let tinta = String::from("Runa de fuego");\n    let p = Pergamino { texto: &tinta };\n    println!("Leo: {}", p.texto);\n}\n',
      expect: "Leo: Runa de fuego",
      solution: 'struct Pergamino<\'a> {\n    texto: &\'a str,\n}\n\nfn main() {\n    let tinta = String::from("Runa de fuego");\n    let p = Pergamino { texto: &tinta };\n    println!("Leo: {}", p.texto);\n}\n',
      fallback: [
        String.raw`struct\s+Pergamino\s*<\s*'(\w+)\s*>[\s\S]*texto\s*:\s*&\s*'\1\s+str`,
        String.raw`texto\s*:\s*String\b[\s\S]*Pergamino\s*\{\s*texto\s*:\s*[^&\s]`,
      ],
      explain: "Pergamino<'a> y texto: &'a str. (Sin 'static: tinta no es un literal.)",
    },
  ],
};

const boss3: LessonDef = {
  slug: "jefe-lifetimes",
  title: "JEFE: Gólem Eterno",
  concept: "lifetimes",
  mode: "boss",
  xp: 170,
  enemy: "golem",
  enemyName: "GÓLEM ETERNO",
  beats: [
    enemySays("SOY EL GUARDIÁN DEL MONTE. Ninguna referencia colgante cruza mi paso. ¡Demuéstralo!"),
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "let r;\n{\n    let x = 1;\n    r = &x;\n}\nprintln!(\"{}\", r);", options: ["Sí", "No"], answer: 1, explain: "x muere antes que r.", check: { compiles: false } },
    { kind: "pick", time: 12, prompt: "Declara el lifetime", code: "fn f<___>(x: &'a str) -> &'a str { x }", options: ["'a", "a", "&a"], answer: 0, explain: "<'a>", check: { compiles: true, wrongFail: true } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "fn f(x: &str, y: &str) -> &str { y }", options: ["Sí", "No"], answer: 1, explain: "Dos entradas: falta 'a.", check: { compiles: false } },
    { kind: "type", time: 12, prompt: "Lifetime de un literal", code: 'let s: &___ str = "roca";', answer: "'static", explain: "&'static str", check: { compiles: true } },
    { kind: "pick", time: 12, prompt: "Devuelve algo creado dentro", code: 'fn crear() -> ___ { String::from("x") }', options: ["String", "&String", "&'static String"], answer: 0, explain: "Devuelve la propiedad.", check: { compiles: true, wrongFail: true } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "struct S { r: &str }", options: ["Sí", "No"], answer: 1, explain: "Falta S<'a> y &'a str.", check: { compiles: false } },
    { kind: "predict", time: 12, prompt: "¿Qué imprime?", code: `${MAS_LARGO}\nprintln!("{}", mas_largo("pico", "cumbre"));`, options: ["cumbre", "pico", "Error"], answer: 0, explain: "cumbre es más largo.", check: { compiles: true, stdout: "cumbre" } },
    { kind: "predict", time: 15, prompt: "¿Compila?", code: `${MAS_LARGO}\nlet a = String::from("aaaa");\nlet res;\n{\n    let b = String::from("b");\n    res = mas_largo(&a, &b);\n}\nprintln!("{}", res);`, options: ["Sí", "No"], answer: 1, explain: "b muere antes de usar res.", check: { compiles: false } },
    { kind: "type", time: 15, prompt: "Campo prestado del struct", code: "struct Extracto<'a> { parte: ___ str }", answer: "&'a", explain: "parte: &'a str", check: { compiles: true } },
    enemySays("Grrr... tus préstamos siempre vuelven a casa. Sube, rustáceo: la cumbre es tuya."),
  ],
};

export const monteLifetimes: RegionDef = {
  slug: "monte-lifetimes",
  name: "Monte Lifetimes",
  subtitle: "'a · referencias que viven",
  theme: "mountain",
  lessons: [colgantes, anotaciones, structsStatic, boss3],
};
