import type { LessonDef, RegionDef } from "../../../lib/content/types.ts";
import { enemySays, say } from "../helpers.ts";

// REGION 5 · TORRE FEARLESS  (closures y move, thread::spawn y join, Arc vs Rc, Mutex y
// Arc<Mutex<T>>, RwLock, canales mpsc, Send y Sync)

const T = "use std::thread;\n";
const A = "use std::sync::Arc;\nuse std::thread;\n";
const AM = "use std::sync::{Arc, Mutex};\nuse std::thread;\n";
const CH = "use std::sync::mpsc;\nuse std::thread;\n";

/** Programa completo: `body` dentro de main, como hace el validador con los fragmentos. */
const prog = (body: string) => `#![allow(unused)]\nfn main() {\n${body.split("\n").map((l) => "    " + l).join("\n")}\n}\n`;

const hilos: LessonDef = {
  slug: "hilos-y-move",
  title: "Ayudantes en paralelo",
  concept: "concurrency",
  mode: "lesson",
  xp: 75,
  enemy: "slime",
  enemyName: "BUG IMPACIENTE",
  beats: [
    say("Bienvenido a la Torre Fearless. Aquí no trabajas solo: llamas AYUDANTES que corren a la vez. Se llaman hilos."),
    say("Antes, una herramienta: un closure es una función sin nombre. |x| x * 2 recibe x; || { ... } no recibe nada."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'let doble = |x: i32| x * 2;\nprintln!("{}", doble(4));',
      options: ["8", "4", "Error: falta fn"],
      answer: 0,
      output: "8",
      explain: "doble es un closure: se llama como una función. doble(4) da 8.",
      check: { compiles: true, stdout: "8" },
    },
    {
      kind: "act",
      prompt: "Llama a un ayudante y espéralo",
      setup: [],
      steps: [
        { label: "IMPORTAR", line: "use std::thread;" },
        { label: "LLAMAR", line: "let h = thread::spawn(|| {", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "h" }, { t: "banner", text: "SPAWN" }] },
        { label: "TRABAJO", line: '    println!("¡Trabajo en paralelo!");', effects: [{ t: "say", actor: "ally", text: "¡Trabajando!" }] },
        { label: "CERRAR", line: "});" },
        { label: "ESPERAR", line: "h.join().unwrap();", effects: [{ t: "say", actor: "hero", text: "Te espero..." }, { t: "banner", text: "JOIN" }], output: "¡Trabajo en paralelo!" },
      ],
    },
    say("spawn lanza el hilo y devuelve un JoinHandle. join() espera a que termine. Sin join, main podría acabar antes."),
    {
      kind: "pick",
      prompt: "Espera a que el ayudante termine",
      code: `${T}let h = thread::spawn(|| {\n    println!("listo");\n});\nh.___().unwrap();`,
      options: ["join", "wait", "end"],
      answer: 0,
      explain: "join() bloquea a main hasta que el hilo termina.",
      check: { compiles: true, stdout: "listo", wrongFail: true },
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "h" }],
      win: [{ t: "say", actor: "ally", text: "¡Listo!" }, { t: "print", text: "listo" }],
    },
    {
      kind: "predict",
      prompt: "join() también trae el resultado. ¿Qué imprime?",
      code: `${T}let h = thread::spawn(|| 2 + 3);\nlet r = h.join().unwrap();\nprintln!("{}", r);`,
      options: ["5", "()", "Error: un hilo no devuelve nada"],
      answer: 0,
      output: "5",
      explain: "El valor que devuelve el closure llega a main por join().",
      check: { compiles: true, stdout: "5" },
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "h" }],
      win: [{ t: "item", kind: "gem", holder: "ally" }, { t: "give", to: "hero" }, { t: "print", text: "5" }],
    },
    say("Ojo: dos hilos que imprimen a la vez pueden salir en CUALQUIER orden. El sistema decide quién corre primero."),
    {
      kind: "predict",
      prompt: "¿En qué orden salen A y B?",
      code: `${T}let a = thread::spawn(|| println!("A"));\nlet b = thread::spawn(|| println!("B"));\na.join().unwrap();\nb.join().unwrap();`,
      options: ["Siempre A y luego B", "Puede variar en cada ejecución"],
      answer: 1,
      explain: "Los hilos corren en paralelo. join solo espera; no ordena lo que ya se imprimió.",
      check: { compiles: true },
      setup: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "a" }, { t: "tag", actor: "hero", text: "b" }],
      win: [{ t: "say", actor: "ally", text: "¿Yo primero?" }, { t: "say", actor: "hero", text: "¿O yo?" }],
    },
    say("Ahora el error clásico: el hilo quiere usar una variable de main. ¿Y si main termina y la suelta antes?"),
    {
      kind: "act",
      prompt: "Pasa el botín al ayudante",
      setup: [],
      steps: [
        { label: "FORJAR", line: "let botin = vec![1, 2, 3];", effects: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "botin" }] },
        { label: "PRESTAR", line: "let h = thread::spawn(|| {", effects: [{ t: "enter", actor: "ally" }, { t: "lend", to: "ally" }] },
        {
          label: "USAR",
          line: '    println!("{:?}", botin);',
          effects: [{ t: "shake" }, { t: "say", actor: "ally", text: "¿Y si main se va?" }],
          error: { compiler: "error[E0373]: closure may outlive the current function, but it borrows `botin`", plain: "El hilo podría vivir más que main. Un préstamo así quedaría colgando." },
        },
        { label: "CON move", line: "let h = thread::spawn(move || {", effects: [{ t: "give", to: "ally" }, { t: "dead", actor: "hero" }, { t: "tag", actor: "ally", text: "botin" }, { t: "banner", text: "MOVE" }] },
        { label: "USAR", line: '    println!("{:?}", botin);\n});\nh.join().unwrap();', effects: [{ t: "say", actor: "ally", text: "¡Ahora es mío!" }], output: "[1, 2, 3]" },
      ],
    },
    say("move || entrega la PROPIEDAD de lo que usa el closure al hilo. El ayudante es dueño y nadie se lo quita."),
    {
      kind: "pick",
      prompt: "Entrega el botín al hilo",
      code: `${T}let botin = vec![1, 2, 3];\nlet h = thread::spawn(___ || {\n    println!("{:?}", botin);\n});\nh.join().unwrap();`,
      options: ["move", "ref", "mut"],
      answer: 0,
      explain: "move mueve botin dentro del closure: el hilo ya no depende de main.",
      check: { compiles: true, stdout: "[1, 2, 3]", wrongFail: true },
      setup: [{ t: "item", kind: "gem", holder: "hero" }, { t: "tag", actor: "hero", text: "botin" }, { t: "enter", actor: "ally" }],
      win: [{ t: "give", to: "ally" }, { t: "dead", actor: "hero" }, { t: "print", text: "[1, 2, 3]" }],
    },
    {
      kind: "predict",
      prompt: "main usa botin después del move. ¿Compila?",
      code: `${T}let botin = vec![1, 2, 3];\nlet h = thread::spawn(move || {\n    println!("{}", botin.len());\n});\nh.join().unwrap();\nprintln!("{:?}", botin);`,
      options: ["Sí: imprime 3 y [1, 2, 3]", "No: botin se movió al hilo"],
      answer: 1,
      explain: "move es un move de verdad: botin ahora es del hilo. Usarlo en main es E0382.",
      check: { compiles: false },
      setup: [{ t: "item", kind: "gem", holder: "ally" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "botin" }, { t: "tag", actor: "hero", text: "botin" }, { t: "dead", actor: "hero" }],
      win: [{ t: "shake" }, { t: "say", actor: "hero", text: "¡Ya no lo tengo!" }],
    },
    {
      kind: "type",
      prompt: "Lanza el hilo",
      code: `${T}let h = thread::___(move || 7);\nprintln!("{}", h.join().unwrap());`,
      answer: "spawn",
      explain: "thread::spawn(closure) lanza un hilo nuevo.",
      check: { compiles: true, stdout: "7" },
      win: [{ t: "enter", actor: "ally" }, { t: "say", actor: "ally", text: "¡7!" }],
    },
    {
      kind: "order",
      prompt: "Ordena: crea, entrega, espera",
      lines: ['let nombre = String::from("Ada");', "let h = thread::spawn(move || {", '    println!("Hola, {}", nombre);', "});", "h.join().unwrap();"],
      explain: "El valor existe antes del hilo; move lo entrega; join espera al final.",
      check: { program: prog(`${T}let nombre = String::from("Ada");\nlet h = thread::spawn(move || {\n    println!("Hola, {}", nombre);\n});\nh.join().unwrap();`), compiles: true, stdout: "Hola, Ada" },
      win: [{ t: "print", text: "Hola, Ada" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Ayudante: Torre tomada",
      starter: 'use std::thread;\n\nfn main() {\n    let mensaje = String::from("Torre tomada");\n    let h = thread::spawn(|| {\n        println!("Ayudante: {}", mensaje);\n    });\n    h.join().unwrap();\n}\n',
      expect: "Ayudante: Torre tomada",
      solution: 'use std::thread;\n\nfn main() {\n    let mensaje = String::from("Torre tomada");\n    let h = thread::spawn(move || {\n        println!("Ayudante: {}", mensaje);\n    });\n    h.join().unwrap();\n}\n',
      fallback: [String.raw`spawn\s*\(\s*move\s*\|`],
      explain: "El closure toma prestado mensaje (E0373). Con move || el hilo se lo lleva.",
    },
  ],
};

const arc: LessonDef = {
  slug: "arc-compartido",
  title: "Pases al mismo tesoro",
  concept: "concurrency",
  mode: "lesson",
  xp: 80,
  enemy: "ghost",
  enemyName: "BUG DUPLICADO",
  beats: [
    say("move entrega el mapa a UN ayudante. ¿Y si tres ayudantes necesitan leer el mismo mapa?"),
    say("Arc<T> cuenta dueños: Atomic Reference Counted. Cada clon es un PASE al mismo valor, no una copia."),
    {
      kind: "act",
      prompt: "Reparte pases al mismo mapa",
      setup: [],
      steps: [
        { label: "IMPORTAR", line: "use std::sync::Arc;" },
        { label: "CREAR", line: 'let mapa = Arc::new(String::from("cueva"));', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "mapa", value: "1 pase" }] },
        { label: "OTRO PASE", line: "let pase = Arc::clone(&mapa);", effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "pase" }, { t: "value", actor: "hero", text: "2 pases" }] },
        { label: "CONTAR", line: 'println!("{}", Arc::strong_count(&mapa));', effects: [{ t: "say", actor: "hero", text: "¡Somos 2!" }], output: "2" },
        { label: "SOLTAR PASE", line: "drop(pase);", effects: [{ t: "untag", actor: "ally" }, { t: "exit", actor: "ally" }, { t: "value", actor: "hero", text: "1 pase" }] },
        { label: "CONTAR", line: 'println!("{}", Arc::strong_count(&mapa));', output: "1" },
      ],
    },
    say("Arc::clone NO copia el mapa: suma 1 al contador. drop(x) suelta un valor ya. Con 0 pases, el mapa se libera."),
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: "use std::sync::Arc;\nlet a = Arc::new(5);\nlet b = Arc::clone(&a);\nlet c = Arc::clone(&a);\nprintln!(\"{}\", Arc::strong_count(&a));",
      options: ["1", "2", "3"],
      answer: 2,
      output: "3",
      explain: "a, b y c son tres pases al mismo 5: el contador vale 3.",
      check: { compiles: true, stdout: "3" },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "a", value: "1" }],
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "value", actor: "hero", text: "3" }, { t: "print", text: "3" }],
    },
    {
      kind: "pick",
      prompt: "Pregunta cuántos pases hay",
      code: 'use std::sync::Arc;\nlet mapa = Arc::new(String::from("cueva"));\nlet pase = Arc::clone(&mapa);\nprintln!("{}", Arc::___(&mapa));',
      options: ["strong_count", "len", "count"],
      answer: 0,
      explain: "Arc::strong_count(&x) dice cuántos pases (Arc) apuntan al valor.",
      check: { compiles: true, stdout: "2" },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "mapa" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "pase" }],
      win: [{ t: "value", actor: "hero", text: "2" }, { t: "print", text: "2" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'use std::sync::Arc;\nlet mapa = Arc::new(String::from("cueva"));\nlet pase = Arc::clone(&mapa);\nprintln!("{} {}", mapa, pase);',
      options: ["cueva cueva", "cueva y un error", "Error: mapa se movió"],
      answer: 0,
      output: "cueva cueva",
      explain: "Ambos pases leen el mismo String. Arc::clone no mueve nada.",
      check: { compiles: true, stdout: "cueva cueva" },
    },
    say("¿Y Rc<T>? Hace lo mismo y es más barato, pero su contador no es atómico: no puede cruzar a otro hilo."),
    {
      kind: "act",
      prompt: "Intenta mandar un Rc a otro hilo",
      setup: [],
      steps: [
        { label: "IMPORTAR", line: "use std::rc::Rc;" },
        { label: "CREAR", line: 'let mapa = Rc::new(String::from("cueva"));', effects: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "mapa: Rc" }] },
        { label: "OTRO PASE", line: "let pase = Rc::clone(&mapa);", effects: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "pase" }] },
        {
          label: "AL HILO",
          line: 'thread::spawn(move || println!("{}", pase));',
          effects: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡Contador roto!" }],
          error: { compiler: "error[E0277]: `Rc<String>` cannot be sent between threads safely", plain: "Dos hilos sumando al contador de Rc a la vez lo romperían. Rust lo impide." },
        },
        { label: "USAR Arc", line: 'let mapa = Arc::new(String::from("cueva"));', effects: [{ t: "tag", actor: "hero", text: "mapa: Arc" }, { t: "banner", text: "¡Arc CRUZA HILOS!" }] },
      ],
    },
    say("Send es una insignia automática: «puedo mudarme a otro hilo». Arc la tiene. Rc no."),
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: `use std::rc::Rc;\n${T}let mapa = Rc::new(5);\nlet pase = Rc::clone(&mapa);\nlet h = thread::spawn(move || println!("{}", pase));\nh.join().unwrap();`,
      options: ["Sí: imprime 5", "No: Rc no se puede enviar entre hilos"],
      answer: 1,
      explain: "Rc no es Send: E0277. Para hilos, usa Arc.",
      check: { compiles: false },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "mapa: Rc" }, { t: "enter", actor: "ally" }],
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡No pasas!" }],
    },
    {
      kind: "pick",
      prompt: "Main y el ayudante leen el mapa",
      code: `${A}let mapa = Arc::new(5);\nlet pase = ___;\nlet h = thread::spawn(move || println!("{}", pase));\nh.join().unwrap();\nprintln!("{}", mapa);`,
      options: ["Arc::clone(&mapa)", "mapa", "&mapa"],
      answer: 0,
      explain: "Un pase nuevo viaja al hilo y mapa sigue en main. mapa se movería; &mapa colgaría.",
      check: { compiles: true, stdout: "5\n5", wrongFail: true },
      setup: [{ t: "item", kind: "scroll", holder: "hero" }, { t: "tag", actor: "hero", text: "mapa" }, { t: "enter", actor: "ally" }],
      win: [{ t: "clone", to: "ally" }, { t: "tag", actor: "ally", text: "pase" }, { t: "print", text: "5" }, { t: "print", text: "5" }],
    },
    {
      kind: "type",
      prompt: "Saca otro pase",
      code: 'use std::sync::Arc;\nlet mapa = Arc::new(String::from("cueva"));\nlet pase = Arc::___(&mapa);\nprintln!("{}", Arc::strong_count(&pase));',
      answer: "clone",
      explain: "Arc::clone(&x) crea un pase más al mismo valor.",
      check: { compiles: true, stdout: "2" },
      win: [{ t: "enter", actor: "ally" }, { t: "clone", to: "ally" }],
    },
    {
      kind: "order",
      prompt: "Ordena: el ayudante y el héroe leen el mapa",
      lines: ['let mapa = Arc::new(String::from("cueva"));', "let pase = Arc::clone(&mapa);", 'let h = thread::spawn(move || println!("Ayudante: {}", pase));', "h.join().unwrap();", 'println!("Héroe: {}", mapa);'],
      explain: "Primero el mapa, luego el pase que viaja al hilo, join y al final lee el héroe.",
      check: { program: prog(`${A}let mapa = Arc::new(String::from("cueva"));\nlet pase = Arc::clone(&mapa);\nlet h = thread::spawn(move || println!("Ayudante: {}", pase));\nh.join().unwrap();\nprintln!("Héroe: {}", mapa);`), compiles: true, stdout: "Ayudante: cueva\nHéroe: cueva" },
      win: [{ t: "print", text: "Ayudante: cueva" }, { t: "print", text: "Héroe: cueva" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Ayudante lee: cueva",
      starter: 'use std::rc::Rc;\nuse std::thread;\n\nfn main() {\n    let mapa = Rc::new(String::from("cueva"));\n    let pase = Rc::clone(&mapa);\n    let h = thread::spawn(move || {\n        println!("Ayudante lee: {}", pase);\n    });\n    h.join().unwrap();\n}\n',
      expect: "Ayudante lee: cueva",
      solution: 'use std::sync::Arc;\nuse std::thread;\n\nfn main() {\n    let mapa = Arc::new(String::from("cueva"));\n    let pase = Arc::clone(&mapa);\n    let h = thread::spawn(move || {\n        println!("Ayudante lee: {}", pase);\n    });\n    h.join().unwrap();\n}\n',
      fallback: [String.raw`Arc\s*::\s*new\s*\(`, String.raw`Arc\s*::\s*clone\s*\(`],
      explain: "Rc no es Send. Cambia Rc por Arc (y el use por std::sync::Arc).",
    },
  ],
};

const mutex: LessonDef = {
  slug: "mutex-cofre",
  title: "El cofre con llave",
  concept: "concurrency",
  mode: "lesson",
  xp: 85,
  enemy: "golem",
  enemyName: "BUG DE CARRERA",
  beats: [
    say("Arc deja LEER desde varios hilos. ¿Y escribir? Si dos suman a la vez, el oro se corrompe: carrera de datos."),
    say("Mutex<T> guarda el valor en un cofre. Para tocarlo pides la LLAVE con lock(). Solo uno la tiene a la vez."),
    {
      kind: "act",
      prompt: "Abre el cofre, suma y devuelve la llave",
      setup: [],
      steps: [
        { label: "IMPORTAR", line: "use std::sync::Mutex;" },
        { label: "COFRE", line: "let cofre = Mutex::new(0);", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "cofre", value: "0" }] },
        { label: "ABRIR BLOQUE", line: "{" },
        { label: "PEDIR LLAVE", line: "    let mut oro = cofre.lock().unwrap();", effects: [{ t: "enter", actor: "ally" }, { t: "give", to: "ally" }, { t: "tag", actor: "ally", text: "oro" }] },
        { label: "SUMAR", line: "    *oro += 10;", effects: [{ t: "value", actor: "hero", text: "10" }, { t: "say", actor: "ally", text: "¡+10!" }] },
        { label: "CERRAR", line: "} // oro muere: suelta la llave", effects: [{ t: "give", to: "hero" }, { t: "untag", actor: "ally" }, { t: "banner", text: "LLAVE DEVUELTA" }] },
        { label: "LEER", line: 'println!("{}", *cofre.lock().unwrap());', output: "10" },
      ],
    },
    say("lock() da un guardián (guard). Con * llegas al valor. Cuando el guard muere al cerrar }, la llave vuelve sola."),
    {
      kind: "pick",
      prompt: "Pide la llave del cofre",
      code: 'use std::sync::Mutex;\nlet cofre = Mutex::new(5);\n{\n    let mut oro = cofre.___().unwrap();\n    *oro += 1;\n}\nprintln!("{}", *cofre.lock().unwrap());',
      options: ["lock", "open", "key"],
      answer: 0,
      explain: "lock() espera la llave y devuelve el guard. Mutex no tiene open ni key.",
      check: { compiles: true, stdout: "6", wrongFail: true },
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "cofre", value: "5" }, { t: "enter", actor: "ally" }],
      win: [{ t: "give", to: "ally" }, { t: "value", actor: "hero", text: "6" }, { t: "give", to: "hero" }, { t: "print", text: "6" }],
    },
    {
      kind: "predict",
      prompt: "¿Qué imprime?",
      code: 'use std::sync::Mutex;\nlet cofre = Mutex::new(vec![1, 2]);\ncofre.lock().unwrap().push(3);\nprintln!("{}", cofre.lock().unwrap().len());',
      options: ["3", "2", "Se congela esperando la llave"],
      answer: 0,
      output: "3",
      explain: "El guard temporal muere al final de su línea: la llave vuelve y el segundo lock() la obtiene.",
      check: { compiles: true, stdout: "3" },
    },
    say("Para compartir el cofre entre hilos, combina ambos: Arc<Mutex<T>>. Arc reparte pases; Mutex reparte la llave."),
    {
      kind: "act",
      prompt: "Tres ayudantes suman al mismo cofre",
      setup: [],
      steps: [
        { label: "COFRE", line: "let cofre = Arc::new(Mutex::new(0));", effects: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "cofre", value: "0" }] },
        { label: "LISTA", line: "let mut hilos = vec![];" },
        { label: "REPETIR", line: "for _ in 0..3 {" },
        { label: "PASE", line: "    let pase = Arc::clone(&cofre);", effects: [{ t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "pase" }] },
        { label: "LANZAR", line: "    hilos.push(thread::spawn(move || {\n        *pase.lock().unwrap() += 1;\n    }));", effects: [{ t: "give", to: "ally" }, { t: "say", actor: "ally", text: "¡+1, toma la llave!" }, { t: "give", to: "hero" }, { t: "value", actor: "hero", text: "1, 2, 3..." }] },
        { label: "CERRAR", line: "}" },
        { label: "ESPERAR", line: "for h in hilos { h.join().unwrap(); }", effects: [{ t: "value", actor: "hero", text: "3" }, { t: "banner", text: "JOIN" }] },
        { label: "LEER", line: 'println!("{}", *cofre.lock().unwrap());', output: "3" },
      ],
    },
    {
      kind: "predict",
      prompt: "Cinco hilos suman 2 cada uno. ¿Qué imprime?",
      code: "let cofre = Arc::new(Mutex::new(0));\nlet mut hilos = vec![];\nfor _ in 0..5 {\n    let pase = Arc::clone(&cofre);\n    hilos.push(thread::spawn(move || { *pase.lock().unwrap() += 2; }));\n}\nfor h in hilos { h.join().unwrap(); }\nprintln!(\"{}\", *cofre.lock().unwrap());",
      options: ["10", "2", "Varía en cada ejecución"],
      answer: 0,
      output: "10",
      explain: "Cada hilo suma con la llave en mano, sin pisarse. Tras los join, 5 × 2 = 10.",
      check: { program: prog(`${AM}let cofre = Arc::new(Mutex::new(0));\nlet mut hilos = vec![];\nfor _ in 0..5 {\n    let pase = Arc::clone(&cofre);\n    hilos.push(thread::spawn(move || { *pase.lock().unwrap() += 2; }));\n}\nfor h in hilos { h.join().unwrap(); }\nprintln!("{}", *cofre.lock().unwrap());`), compiles: true, stdout: "10" },
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "cofre", value: "0" }],
      win: [{ t: "value", actor: "hero", text: "10" }, { t: "print", text: "10" }],
    },
    {
      kind: "pick",
      prompt: "¿Qué va dentro del Arc para poder sumar?",
      code: `${AM}let cofre = Arc::new(___::new(0));\nlet pase = Arc::clone(&cofre);\nlet h = thread::spawn(move || { *pase.lock().unwrap() += 5; });\nh.join().unwrap();\nprintln!("{}", *cofre.lock().unwrap());`,
      options: ["Mutex", "Box", "Arc"],
      answer: 0,
      explain: "Solo Mutex tiene lock(). Arc comparte; Mutex permite mutar por turnos.",
      check: { compiles: true, stdout: "5", wrongFail: true },
      win: [{ t: "item", kind: "key", holder: "hero" }, { t: "print", text: "5" }],
    },
    {
      kind: "predict",
      prompt: "Arc sin Mutex. ¿Compila?",
      code: `${A}let oro = Arc::new(0);\nlet pase = Arc::clone(&oro);\nlet h = thread::spawn(move || { *pase += 1; });\nh.join().unwrap();`,
      options: ["Sí", "No: no se puede mutar a través de Arc"],
      answer: 1,
      explain: "Arc solo da acceso compartido (lectura). Para escribir necesitas Mutex dentro.",
      check: { compiles: false },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡Sin llave no!" }],
    },
    say("Peligro: si un hilo espera una llave que nadie suelta, se congela para siempre. Eso es un DEADLOCK."),
    {
      kind: "predict",
      prompt: "El bloque suelta la llave antes del segundo lock. ¿Qué imprime?",
      code: 'use std::sync::Mutex;\nlet cofre = Mutex::new(1);\n{\n    let mut a = cofre.lock().unwrap();\n    *a += 1;\n}\nlet b = cofre.lock().unwrap();\nprintln!("{}", *b);',
      options: ["2", "1", "Se congela: deadlock"],
      answer: 0,
      output: "2",
      explain: "a muere en } y devuelve la llave. Sin ese bloque, el segundo lock() esperaría para siempre.",
      check: { compiles: true, stdout: "2" },
      setup: [{ t: "item", kind: "key", holder: "hero" }, { t: "tag", actor: "hero", text: "cofre", value: "1" }],
      win: [{ t: "value", actor: "hero", text: "2" }, { t: "print", text: "2" }],
    },
    say("Variante: RwLock deja MUCHOS lectores a la vez con read(), o UN solo escritor con write()."),
    {
      kind: "predict",
      prompt: "Dos lectores a la vez. ¿Qué imprime?",
      code: 'use std::sync::RwLock;\nlet mapa = RwLock::new(5);\nlet r1 = mapa.read().unwrap();\nlet r2 = mapa.read().unwrap();\nprintln!("{}", *r1 + *r2);',
      options: ["10", "5", "Se congela: deadlock"],
      answer: 0,
      output: "10",
      explain: "Varios read() conviven sin problema. Solo write() pide exclusividad.",
      check: { compiles: true, stdout: "10" },
    },
    {
      kind: "type",
      prompt: "Pide la llave",
      code: 'use std::sync::Mutex;\nlet cofre = Mutex::new(1);\nlet mut oro = cofre.___().unwrap();\n*oro += 1;\nprintln!("{}", *oro);',
      answer: "lock",
      explain: "cofre.lock().unwrap() te da el guard con la llave.",
      check: { compiles: true, stdout: "2" },
      win: [{ t: "item", kind: "key", holder: "hero" }, { t: "print", text: "2" }],
    },
    {
      kind: "order",
      prompt: "Ordena: un ayudante suma al cofre",
      lines: ["let pase = Arc::clone(&cofre);", "let h = thread::spawn(move || {", "    *pase.lock().unwrap() += 1;", "});", "h.join().unwrap();"],
      explain: "Primero el pase, luego el hilo que lo mueve, y al final join.",
      check: { program: prog(`${AM}let cofre = Arc::new(Mutex::new(0));\nlet pase = Arc::clone(&cofre);\nlet h = thread::spawn(move || {\n    *pase.lock().unwrap() += 1;\n});\nh.join().unwrap();\nprintln!("{}", *cofre.lock().unwrap());`), compiles: true, stdout: "1" },
      win: [{ t: "print", text: "1" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Oro total: 4",
      starter: 'use std::sync::Arc;\nuse std::thread;\n\nfn main() {\n    let oro = Arc::new(0);\n    let mut hilos = vec![];\n    for _ in 0..4 {\n        let pase = Arc::clone(&oro);\n        hilos.push(thread::spawn(move || { *pase += 1; }));\n    }\n    for h in hilos { h.join().unwrap(); }\n    println!("Oro total: {}", oro);\n}\n',
      expect: "Oro total: 4",
      solution: 'use std::sync::{Arc, Mutex};\nuse std::thread;\n\nfn main() {\n    let oro = Arc::new(Mutex::new(0));\n    let mut hilos = vec![];\n    for _ in 0..4 {\n        let pase = Arc::clone(&oro);\n        hilos.push(thread::spawn(move || { *pase.lock().unwrap() += 1; }));\n    }\n    for h in hilos { h.join().unwrap(); }\n    println!("Oro total: {}", *oro.lock().unwrap());\n}\n',
      fallback: [String.raw`Mutex\s*::\s*new\s*\(`, String.raw`Atomic\w+\s*::\s*new\s*\(`],
      explain: "Mete el oro en un cofre: Arc::new(Mutex::new(0)) y suma con *pase.lock().unwrap() += 1.",
    },
  ],
};

const canales: LessonDef = {
  slug: "canales-mensajes",
  title: "Pergaminos mensajeros",
  concept: "concurrency",
  mode: "lesson",
  xp: 80,
  enemy: "ghost",
  enemyName: "BUG CHISMOSO",
  beats: [
    say("Otra forma de cooperar: en vez de compartir el cofre, envía MENSAJES. No compartas memoria: comunícate."),
    say("mpsc::channel() crea un canal: tx envía y rx recibe. mpsc significa muchos productores, un consumidor."),
    {
      kind: "act",
      prompt: "El ayudante te envía un pergamino",
      setup: [],
      steps: [
        { label: "IMPORTAR", line: "use std::sync::mpsc;" },
        { label: "CANAL", line: "let (tx, rx) = mpsc::channel();", effects: [{ t: "tag", actor: "hero", text: "rx" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "tx" }, { t: "banner", text: "CANAL" }] },
        { label: "LANZAR", line: "thread::spawn(move || {", effects: [{ t: "say", actor: "ally", text: "¡Voy al norte!" }] },
        { label: "ENVIAR", line: '    tx.send(String::from("¡Dragón al norte!")).unwrap();', effects: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "give", to: "hero" }] },
        { label: "CERRAR", line: "});" },
        { label: "RECIBIR", line: 'println!("{}", rx.recv().unwrap());', effects: [{ t: "say", actor: "hero", text: "¡Recibido!" }], output: "¡Dragón al norte!" },
      ],
    },
    say("send() MUEVE el valor por el canal: deja de ser del que envía. recv() espera hasta que llegue algo."),
    {
      kind: "pick",
      prompt: "Envía el número por el canal",
      code: `${CH}let (tx, rx) = mpsc::channel();\nthread::spawn(move || { tx.___(5).unwrap(); });\nprintln!("{}", rx.recv().unwrap());`,
      options: ["send", "push", "recv"],
      answer: 0,
      explain: "tx.send(valor) envía; rx.recv() recibe. Sender no tiene push ni recv.",
      check: { compiles: true, stdout: "5", wrongFail: true },
      setup: [{ t: "tag", actor: "hero", text: "rx" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "tx" }, { t: "item", kind: "scroll", holder: "ally" }],
      win: [{ t: "give", to: "hero" }, { t: "print", text: "5" }],
    },
    {
      kind: "predict",
      prompt: "¿Compila?",
      code: 'use std::sync::mpsc;\nlet (tx, rx) = mpsc::channel();\nlet carta = String::from("hola");\ntx.send(carta).unwrap();\nprintln!("{}", carta);',
      options: ["Sí: imprime hola", "No: carta se movió al canal"],
      answer: 1,
      explain: "send toma la propiedad. Usar carta después es E0382, como cualquier move.",
      check: { compiles: false },
      setup: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "carta" }],
      win: [{ t: "give", to: "hero" }, { t: "dead", actor: "ally" }],
    },
    {
      kind: "type",
      prompt: "Recibe el mensaje",
      code: `${CH}let (tx, rx) = mpsc::channel();\nthread::spawn(move || { tx.send("hola").unwrap(); });\nlet msg = rx.___().unwrap();\nprintln!("{}", msg);`,
      answer: "recv",
      explain: "rx.recv() espera hasta que llega un mensaje.",
      check: { compiles: true, stdout: "hola" },
      win: [{ t: "say", actor: "hero", text: "¡hola!" }, { t: "print", text: "hola" }],
    },
    say("¿Varios mensajeros? Clona tx: cada hilo lleva su propio tx hacia el mismo rx."),
    {
      kind: "act",
      prompt: "Dos mensajeros, un solo receptor",
      setup: [],
      steps: [
        { label: "CANAL", line: "let (tx, rx) = mpsc::channel();", effects: [{ t: "tag", actor: "hero", text: "rx" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "tx" }] },
        { label: "CLONAR tx", line: "let tx2 = tx.clone();", effects: [{ t: "tag", actor: "ally", text: "tx, tx2" }, { t: "banner", text: "2 MENSAJEROS" }] },
        { label: "ENVÍA 1", line: "thread::spawn(move || { tx.send(1).unwrap(); });", effects: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "give", to: "hero" }] },
        { label: "ENVÍA 2", line: "thread::spawn(move || { tx2.send(2).unwrap(); });", effects: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "give", to: "hero" }] },
        { label: "SUMAR", line: "let mut total = 0;\nfor n in rx { total += n; }", effects: [{ t: "tag", actor: "hero", text: "total", value: "3" }] },
        { label: "MOSTRAR", line: 'println!("{}", total);', output: "3" },
      ],
    },
    say("for n in rx recibe hasta que TODOS los tx mueren. Por eso se hace drop(tx) del original si no lo usas."),
    {
      kind: "predict",
      prompt: "Tres mensajeros envían 10, 20 y 30. ¿Qué imprime?",
      code: `${CH}let (tx, rx) = mpsc::channel();\nfor i in 1..=3 {\n    let tx = tx.clone();\n    thread::spawn(move || { tx.send(i * 10).unwrap(); });\n}\ndrop(tx);\nlet mut total = 0;\nfor n in rx { total += n; }\nprintln!("{}", total);`,
      options: ["60", "10", "Se queda esperando"],
      answer: 0,
      output: "60",
      explain: "Llegan los tres (en cualquier orden) y la suma no depende del orden. drop(tx) deja terminar el for.",
      check: { compiles: true, stdout: "60" },
      setup: [{ t: "tag", actor: "hero", text: "rx" }, { t: "enter", actor: "ally" }, { t: "tag", actor: "ally", text: "tx × 3" }],
      win: [{ t: "item", kind: "scroll", holder: "ally" }, { t: "give", to: "hero" }, { t: "tag", actor: "hero", text: "total", value: "60" }, { t: "print", text: "60" }],
    },
    say("Send: «puedo mudarme a otro hilo». Sync: «varios hilos pueden mirarme a la vez». Rust las pone solo."),
    {
      kind: "pick",
      prompt: "¿Qué insignia exige mover x a otro hilo?",
      code: 'fn enviar<T: ___ + \'static>(x: T) {\n    std::thread::spawn(move || drop(x)).join().unwrap();\n}\nenviar(String::from("carta"));\nprintln!("ok");',
      options: ["Send", "Sync", "Copy"],
      answer: 0,
      explain: "spawn exige que lo que se mueve al hilo sea Send. Sync es para compartir con &.",
      check: { compiles: true, stdout: "ok", wrongFail: true },
    },
    {
      kind: "predict",
      prompt: "Un Rc por el canal. ¿Compila?",
      code: `use std::rc::Rc;\n${CH}let (tx, rx) = mpsc::channel();\nthread::spawn(move || { tx.send(Rc::new(5)).unwrap(); });\nprintln!("{}", rx.recv().unwrap());`,
      options: ["Sí: imprime 5", "No: Rc no es Send"],
      answer: 1,
      explain: "Enviar es mudar el valor a otro hilo. Rc no es Send: E0277.",
      check: { compiles: false },
      win: [{ t: "shake" }, { t: "say", actor: "enemy", text: "¡Rc no viaja!" }],
    },
    {
      kind: "order",
      prompt: "Ordena: el ayudante avisa y el héroe escucha",
      lines: ["let (tx, rx) = mpsc::channel();", "thread::spawn(move || {", '    tx.send("listo").unwrap();', "});", 'println!("{}", rx.recv().unwrap());'],
      explain: "Primero el canal, luego el hilo que envía, y al final main recibe.",
      check: { program: prog(`${CH}let (tx, rx) = mpsc::channel();\nthread::spawn(move || {\n    tx.send("listo").unwrap();\n});\nprintln!("{}", rx.recv().unwrap());`), compiles: true, stdout: "listo" },
      win: [{ t: "print", text: "listo" }],
    },
    {
      kind: "run",
      prompt: "Arréglalo: debe imprimir Total: 42",
      starter: 'use std::sync::mpsc;\nuse std::thread;\n\nfn main() {\n    let (tx, rx) = mpsc::channel();\n    thread::spawn(move || { tx.send(20).unwrap(); });\n    thread::spawn(move || { tx.send(22).unwrap(); });\n    let mut total = 0;\n    for n in rx { total += n; }\n    println!("Total: {}", total);\n}\n',
      expect: "Total: 42",
      solution: 'use std::sync::mpsc;\nuse std::thread;\n\nfn main() {\n    let (tx, rx) = mpsc::channel();\n    let tx2 = tx.clone();\n    thread::spawn(move || { tx.send(20).unwrap(); });\n    thread::spawn(move || { tx2.send(22).unwrap(); });\n    let mut total = 0;\n    for n in rx { total += n; }\n    println!("Total: {}", total);\n}\n',
      fallback: [String.raw`tx\s*\.\s*clone\s*\(\s*\)`, String.raw`Sender\s*::\s*clone\s*\(`],
      explain: "El primer hilo se llevó tx (E0382). Clona tx para el segundo mensajero.",
    },
  ],
};

const boss5: LessonDef = {
  slug: "jefe-concurrencia",
  title: "JEFE: Dragón Fearless",
  concept: "concurrency",
  mode: "boss",
  xp: 200,
  enemy: "dragon",
  enemyName: "DRAGÓN FEARLESS",
  beats: [
    enemySays("SOY EL DRAGÓN DE LA TORRE. Mis llamas corren en mil hilos a la vez. ¿Puedes seguirles el paso?"),
    { kind: "predict", time: 12, prompt: "¿Compila?", code: `${T}let v = vec![1, 2];\nlet h = thread::spawn(|| println!("{:?}", v));\nh.join().unwrap();`, options: ["Sí", "No"], answer: 1, explain: "Falta move: E0373.", check: { compiles: false } },
    { kind: "pick", time: 12, prompt: "Espera al hilo", code: `${T}let h = thread::spawn(|| 1);\nprintln!("{}", h.___().unwrap());`, options: ["join", "wait", "end"], answer: 0, explain: "join() espera y trae el valor.", check: { compiles: true, stdout: "1", wrongFail: true } },
    { kind: "type", time: 12, prompt: "Entrega v al hilo", code: `${T}let v = vec![1, 2];\nlet h = thread::spawn(___ || println!("{}", v.len()));\nh.join().unwrap();`, answer: "move", explain: "move || se lleva v.", check: { compiles: true, stdout: "2" } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: `use std::rc::Rc;\n${T}let r = Rc::new(1);\nlet h = thread::spawn(move || println!("{}", r));\nh.join().unwrap();`, options: ["Sí", "No"], answer: 1, explain: "Rc no es Send.", check: { compiles: false } },
    { kind: "predict", time: 12, prompt: "¿Qué imprime?", code: 'use std::sync::Arc;\nlet a = Arc::new(1);\nlet b = Arc::clone(&a);\nprintln!("{}", Arc::strong_count(&b));', options: ["1", "2"], answer: 1, explain: "Dos pases: a y b.", check: { compiles: true, stdout: "2" } },
    { kind: "pick", time: 12, prompt: "Para mutar compartido", code: 'use std::sync::{Arc, Mutex};\nlet c = Arc::new(___::new(0));\n*c.lock().unwrap() += 1;\nprintln!("{}", *c.lock().unwrap());', options: ["Mutex", "Box", "Arc"], answer: 0, explain: "Arc<Mutex<T>>.", check: { compiles: true, stdout: "1", wrongFail: true } },
    { kind: "predict", time: 12, prompt: "¿Compila?", code: "use std::sync::Arc;\nlet oro = Arc::new(0);\n*oro += 1;", options: ["Sí", "No"], answer: 1, explain: "Arc no deja mutar: falta Mutex.", check: { compiles: false } },
    { kind: "type", time: 12, prompt: "Pide la llave", code: 'use std::sync::Mutex;\nlet m = Mutex::new(1);\nlet mut g = m.___().unwrap();\n*g += 1;\nprintln!("{}", *g);', answer: "lock", explain: "m.lock().unwrap()", check: { compiles: true, stdout: "2" } },
    { kind: "predict", time: 15, prompt: "¿Qué imprime?", code: `${CH}let (tx, rx) = mpsc::channel();\nfor i in 1..=3 {\n    let tx = tx.clone();\n    thread::spawn(move || { tx.send(i).unwrap(); });\n}\ndrop(tx);\nlet mut t = 0;\nfor n in rx { t += n; }\nprintln!("{}", t);`, options: ["6", "3", "Se queda esperando"], answer: 0, explain: "1 + 2 + 3, y drop(tx) cierra el canal.", check: { compiles: true, stdout: "6" } },
    { kind: "pick", time: 15, prompt: "Insignia para mudarse de hilo", code: "fn f<T: ___ + 'static>(x: T) {\n    std::thread::spawn(move || drop(x));\n}", options: ["Send", "Sync", "Copy"], answer: 0, explain: "Mover a otro hilo exige Send.", check: { compiles: true, wrongFail: true } },
    enemySays("Grrr... ni una carrera de datos. Tus hilos trabajan sin miedo. La Torre es tuya, rustáceo."),
  ],
};

export const torreFearless: RegionDef = {
  slug: "torre-fearless",
  name: "Torre Fearless",
  subtitle: "Hilos · Arc · Mutex",
  theme: "tower",
  lessons: [hilos, arc, mutex, canales, boss5],
};
